
;;# data
[
{:match/id "match_5709"
:match/league "France Ligue 1"
:match/hometeam "AJ Auxerre"
:match/awayteam "Paris Saint-Germain"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 49
:event/card_type "y"
:event/player1 "Alain Traore"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1443146"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_5709"}

{:event/type "goal"
:event/elapsed 86
:event/player1 "Kamel Chafni"
:event/sortorder 0
:event/team "home"
:event/id "event_1443304"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_5709"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Benoit Pedretti"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1443305"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_5709"}


]

