
;;# data
[
{:match/id "match_9717"
:match/league "Germany 1. Bundesliga"
:match/hometeam "FC Schalke 04"
:match/awayteam "Hamburger SV"
:match/score "0:0"
:match/hometeam_goals "0"
:match/awayteam_goals "0"}

{:event/type "shoton"
:event/elapsed 1
:event/subtype "distance"
:event/player1 "Tranquillo Barnetta"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4022123"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_9717"}

{:event/type "corner"
:event/elapsed 2
:event/subtype "cross_left"
:event/player1 "Tranquillo Barnetta"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4022128"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_9717"}

{:event/type "shotoff"
:event/elapsed 2
:event/subtype "big chance crossbar"
:event/player1 "Klaas Jan Huntelaar"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4022134"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_9717"}

{:event/type "corner"
:event/elapsed 2
:event/subtype "cross_left"
:event/player1 "Tranquillo Barnetta"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_4022139"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_9717"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Mohamed Gouaida"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4022147"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_9717"}

{:event/type "corner"
:event/elapsed 3
:event/subtype "cross_left"
:event/player1 "Valon Behrami"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_4022151"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_9717"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Eric Maxim Choupo-Moting"
:event/subtype "trip"
:event/player1 "Petr Jiracek"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4022160"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_9717"}

{:event/type "shoton"
:event/elapsed 6
:event/subtype "blocked_shot"
:event/player1 "Matthias Ostrzolek"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4022187"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_9717"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Christian Fuchs"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4022214"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_9717"}

{:event/type "shoton"
:event/elapsed 8
:event/subtype "header"
:event/player1 "Tranquillo Barnetta"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4022215"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_9717"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Klaas Jan Huntelaar"
:event/subtype "trip"
:event/player1 "Matthias Ostrzolek"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4022218"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_9717"}

{:event/type "shoton"
:event/elapsed 9
:event/subtype "shot"
:event/player1 "Klaas Jan Huntelaar"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4022226"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_9717"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Nicolai Mueller"
:event/subtype "trip"
:event/player1 "Christian Fuchs"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4022251"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_9717"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Tranquillo Barnetta"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4022273"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_9717"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Eric Maxim Choupo-Moting"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4022289"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_9717"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Marco Hoeger"
:event/subtype "obstruction"
:event/player1 "Ashton-Phillip Goetz"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4022307"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_9717"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Tranquillo Barnetta"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4022311"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_9717"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Petr Jiracek"
:event/subtype "trip"
:event/player1 "Marco Hoeger"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4022330"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_9717"}

{:event/type "shotoff"
:event/elapsed 20
:event/subtype "distance"
:event/player1 "Eric Maxim Choupo-Moting"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4022341"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_9717"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Christian Fuchs"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4022356"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_9717"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_4022370"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_9717"}

{:event/type "shoton"
:event/elapsed 23
:event/subtype "shot"
:event/player1 "Tranquillo Barnetta"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4022373"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_9717"}

{:event/type "foulcommit"
:event/elapsed 24
:event/subtype "hands"
:event/player1 "Artjoms Rudnevs"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4022386"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_9717"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Christian Fuchs"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4022411"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_9717"}

{:event/type "shotoff"
:event/elapsed 28
:event/subtype "volley"
:event/player1 "Christian Fuchs"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4022423"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_9717"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Artjoms Rudnevs"
:event/subtype "dangerous_play"
:event/player1 "Dennis Aogo"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4022428"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_9717"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Lewis Holtby"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4022430"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_9717"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Atsuto Uchida"
:event/subtype "pull"
:event/player1 "Mohamed Gouaida"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4022440"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_9717"}

{:event/type "shotoff"
:event/elapsed 30
:event/subtype "big chance shot"
:event/player1 "Petr Jiracek"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4022453"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_9717"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Atsuto Uchida"
:event/subtype "pushing"
:event/player1 "Matthias Ostrzolek"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4022589"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_9717"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Christian Fuchs"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4022602"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_9717"}

{:event/type "shoton"
:event/elapsed 36
:event/subtype "header"
:event/player1 "Benedikt Hoewedes"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4022609"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_9717"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Nicolai Mueller"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4022616"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_9717"}

{:event/type "shoton"
:event/elapsed 36
:event/subtype "header"
:event/player1 "Petr Jiracek"
:event/sortorder 4
:event/team "away"
:event/event_type "shoton"
:event/id "event_4022622"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_9717"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Klaas Jan Huntelaar"
:event/subtype "dangerous_play"
:event/player1 "Cleber"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4022630"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_9717"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Tranquillo Barnetta"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4022642"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_9717"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/sortorder 1
:event/team "away"
:event/event_type "throwin"
:event/id "event_4022693"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_9717"}

{:event/type "shoton"
:event/elapsed 41
:event/subtype "blocked_shot"
:event/player1 "Tranquillo Barnetta"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4022750"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_9717"}

{:event/type "card"
:event/elapsed 42
:event/card_type "y"
:event/subtype "verbal_abuse"
:event/player1 "Valon Behrami"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_4022763"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_9717"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Christian Fuchs"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4022782"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_9717"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Nicolai Mueller"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4022793"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_9717"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "big chance shot"
:event/player1 "Artjoms Rudnevs"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4022860"
:event/minute 46
:event/match_id "match_9717"}

{:event/type "foulcommit"
:event/elapsed 47
:event/player2 "Nicolai Mueller"
:event/subtype "pushing"
:event/player1 "Benedikt Hoewedes"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4023141"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_9717"}

{:event/type "shoton"
:event/elapsed 49
:event/subtype "big chance shot"
:event/player1 "Eric Maxim Choupo-Moting"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4023198"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_9717"}

{:event/type "shoton"
:event/elapsed 50
:event/subtype "blocked_shot"
:event/player1 "Mohamed Gouaida"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4023248"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_9717"}

{:event/type "shoton"
:event/elapsed 51
:event/subtype "shot"
:event/player1 "Lewis Holtby"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4023260"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_9717"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Eric Maxim Choupo-Moting"
:event/subtype "trip"
:event/player1 "Petr Jiracek"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4023274"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_9717"}

{:event/type "shotoff"
:event/elapsed 54
:event/subtype "distance"
:event/player1 "Klaas Jan Huntelaar"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4023328"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_9717"}

{:event/type "shoton"
:event/elapsed 55
:event/subtype "volley"
:event/player1 "Tranquillo Barnetta"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4023379"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_9717"}

{:event/type "shoton"
:event/elapsed 56
:event/subtype "blocked_shot"
:event/player1 "Matthias Ostrzolek"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4023402"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_9717"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Petr Jiracek"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4023405"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_9717"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Ashton-Phillip Goetz"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4023467"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_9717"}

{:event/type "corner"
:event/elapsed 59
:event/subtype "cross_right"
:event/player1 "Lewis Holtby"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4023474"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_9717"}

{:event/type "shoton"
:event/elapsed 60
:event/subtype "deflected"
:event/player1 "Lewis Holtby"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4023516"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_9717"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Atsuto Uchida"
:event/subtype "pushing"
:event/player1 "Petr Jiracek"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4023554"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_9717"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Marco Hoeger"
:event/subtype "pushing"
:event/player1 "Petr Jiracek"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4023567"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_9717"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Eric Maxim Choupo-Moting"
:event/subtype "pushing"
:event/player1 "Johan Djourou"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4023575"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_9717"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Nicolai Mueller"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4023582"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_9717"}

{:event/type "corner"
:event/elapsed 66
:event/subtype "cross_right"
:event/player1 "Dennis Aogo"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4023609"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_9717"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Mohamed Gouaida"
:event/subtype "pull"
:event/player1 "Marco Hoeger"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4023645"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_9717"}

{:event/type "card"
:event/elapsed 69
:event/card_type "y"
:event/player1 "Marco Hoeger"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_4023646"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_9717"}

{:event/type "shoton"
:event/elapsed 70
:event/subtype "blocked_shot"
:event/player1 "Lewis Holtby"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4023656"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_9717"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Valon Behrami"
:event/subtype "pushing"
:event/player1 "Leroy Sane"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4023669"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_9717"}

{:event/type "shoton"
:event/elapsed 72
:event/subtype "distance"
:event/player1 "Cleber"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4023687"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_9717"}

{:event/type "foulcommit"
:event/elapsed 74
:event/player2 "Matthias Ostrzolek"
:event/subtype "trip"
:event/player1 "Roman Neustaedter"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4023704"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_9717"}

{:event/type "foulcommit"
:event/elapsed 74
:event/player2 "Benedikt Hoewedes"
:event/subtype "pull"
:event/player1 "Nicolai Mueller"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4023709"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_9717"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Matthias Ostrzolek"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4023719"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_9717"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Matthias Ostrzolek"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4023724"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_9717"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Marco Hoeger"
:event/subtype "pushing"
:event/player1 "Valon Behrami"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4023734"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_9717"}

{:event/type "foulcommit"
:event/elapsed 76
:event/player2 "Mohamed Gouaida"
:event/subtype "serious_foul"
:event/player1 "Benedikt Hoewedes"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4023740"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_9717"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Ashton-Phillip Goetz"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4023759"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_9717"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Petr Jiracek"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4023771"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_9717"}

{:event/type "shoton"
:event/elapsed 77
:event/subtype "shot"
:event/player1 "Mohamed Gouaida"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4023779"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_9717"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Nicolai Mueller"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4023800"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_9717"}

{:event/type "corner"
:event/elapsed 78
:event/subtype "cross_right"
:event/player1 "Lewis Holtby"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4023811"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_9717"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Dennis Aogo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4023830"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_9717"}

{:event/type "corner"
:event/elapsed 79
:event/subtype "cross_left"
:event/player1 "Dennis Aogo"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4023842"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_9717"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/sortorder 4
:event/team "home"
:event/event_type "throwin"
:event/id "event_4023850"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_9717"}

{:event/type "shoton"
:event/elapsed 80
:event/subtype "big chance shot"
:event/player1 "Eric Maxim Choupo-Moting"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4023886"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_9717"}

{:event/type "corner"
:event/elapsed 80
:event/subtype "cross_left"
:event/player1 "Dennis Aogo"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4023890"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_9717"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Marco Hoeger"
:event/subtype "dangerous_play"
:event/player1 "Cleber"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4023900"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_9717"}

{:event/type "card"
:event/elapsed 81
:event/card_type "y"
:event/player1 "Cleber"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4023910"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_9717"}

{:event/type "shoton"
:event/elapsed 82
:event/subtype "direct_freekick"
:event/player1 "Klaas Jan Huntelaar"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4023931"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_9717"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Dennis Aogo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4023984"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_9717"}

{:event/type "corner"
:event/elapsed 84
:event/subtype "cross_right"
:event/player1 "Dennis Aogo"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4023996"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_9717"}

{:event/type "shotoff"
:event/elapsed 85
:event/subtype "post"
:event/player1 "Roman Neustaedter"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4024009"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_9717"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Mohamed Gouaida"
:event/subtype "trip"
:event/player1 "Marco Hoeger"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4024057"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_9717"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Lewis Holtby"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4024068"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_9717"}

{:event/type "corner"
:event/elapsed 87
:event/subtype "cross_left"
:event/player1 "Lewis Holtby"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4024086"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_9717"}

{:event/type "shoton"
:event/elapsed 87
:event/subtype "distance"
:event/player1 "Cleber"
:event/sortorder 4
:event/team "away"
:event/event_type "shoton"
:event/id "event_4024100"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_9717"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Petr Jiracek"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4024143"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_9717"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Petr Jiracek"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4024189"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_9717"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Nicolai Mueller"
:event/subtype "pushing"
:event/player1 "Marco Hoeger"
:event/sortorder 5
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4024229"
:event/minute 92
:event/match_id "match_9717"}


]

