
;;# data
[
{:match/id "match_8001"
:match/league "Germany 1. Bundesliga"
:match/hometeam "VfB Stuttgart"
:match/awayteam "Eintracht Frankfurt"
:match/score "2:0"
:match/hometeam_goals "2"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 26
:event/card_type "y"
:event/player1 "Patrick Ochs"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_657247"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_8001"}

{:event/type "goal"
:event/elapsed 33
:event/player1 "Cacau"
:event/sortorder 0
:event/team "home"
:event/id "event_656579"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_8001"}

{:event/type "goal"
:event/elapsed 48
:event/player1 "Mario Gomez"
:event/sortorder 0
:event/team "home"
:event/id "event_657050"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_8001"}

{:event/type "card"
:event/elapsed 67
:event/card_type "y"
:event/player1 "Roberto Hilbert"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_657252"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_8001"}

{:event/type "card"
:event/elapsed 84
:event/card_type "y"
:event/player1 "Michael Fink"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_657537"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_8001"}


]

