
;;# data
[
{:match/id "match_12313"
:match/league "Italy Serie A"
:match/hometeam "Lazio"
:match/awayteam "Sassuolo"
:match/score "3:2"
:match/hometeam_goals "3"
:match/awayteam_goals "2"}

{:event/type "card"
:event/elapsed 3
:event/card_type "y"
:event/player1 "Francesco Magnanelli"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3285766"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_12313"}

{:event/type "card"
:event/elapsed 26
:event/card_type "y"
:event/player1 "Stefan Daniel Radu"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3285785"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_12313"}

{:event/type "card"
:event/elapsed 26
:event/card_type "y"
:event/player1 "Aleandro Rosi"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_3285786"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_12313"}

{:event/type "goal"
:event/elapsed 36
:event/player2 "Christian Daniel Ledesma"
:event/player1 "Stefan Daniel Radu"
:event/sortorder 0
:event/team "home"
:event/id "event_3285791"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_12313"}

{:event/type "card"
:event/elapsed 45
:event/card_type "y"
:event/player1 "Simone Zaza"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3285802"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_12313"}

{:event/type "goal"
:event/elapsed 72
:event/player2 "Francesco Magnanelli"
:event/player1 "Sergio Floccari"
:event/sortorder 0
:event/team "away"
:event/id "event_3285837"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_12313"}

{:event/type "goal"
:event/elapsed 74
:event/player2 "Alvaro Gonzalez"
:event/player1 "Miroslav Klose"
:event/sortorder 0
:event/team "home"
:event/id "event_3285838"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_12313"}

{:event/type "goal"
:event/elapsed 79
:event/player1 "Antonio Floro Flores"
:event/sortorder 0
:event/team "away"
:event/id "event_3285843"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_12313"}

{:event/type "goal"
:event/elapsed 83
:event/player2 "Stefan Daniel Radu"
:event/player1 "Antonio Candreva"
:event/sortorder 0
:event/team "home"
:event/id "event_3285846"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_12313"}


]

