
;;# data
[
{:match/id "match_12129"
:match/league "Italy Serie A"
:match/hometeam "Napoli"
:match/awayteam "Chievo Verona"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 13
:event/card_type "y"
:event/player1 "Marco Andreolli"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2445118"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_12129"}

{:event/type "card"
:event/elapsed 20
:event/card_type "y"
:event/player1 "Luca Rigoni"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2445122"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_12129"}

{:event/type "goal"
:event/elapsed 58
:event/player1 "Marek Hamsik"
:event/sortorder 0
:event/team "home"
:event/id "event_2445145"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_12129"}

{:event/type "card"
:event/elapsed 67
:event/card_type "y"
:event/player1 "Kamil Vacek"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2445149"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_12129"}

{:event/type "card"
:event/elapsed 78
:event/card_type "y"
:event/player1 "Kamil Vacek"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2445154"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_12129"}


]

