
;;# data
[
{:match/id "match_8921"
:match/league "Germany 1. Bundesliga"
:match/hometeam "VfB Stuttgart"
:match/awayteam "1. FSV Mainz 05"
:match/score "4:1"
:match/hometeam_goals "4"
:match/awayteam_goals "1"}

{:event/type "goal"
:event/elapsed 3
:event/player1 "Andreas Ivanschitz"
:event/sortorder 0
:event/team "away"
:event/id "event_2038167"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_8921"}

{:event/type "goal"
:event/elapsed 7
:event/player1 "Tamas Hajnal"
:event/sortorder 0
:event/team "home"
:event/id "event_2038168"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_8921"}

{:event/type "goal"
:event/elapsed 49
:event/player1 "Vedad Ibisevic"
:event/sortorder 0
:event/team "home"
:event/id "event_2038959"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_8921"}

{:event/type "card"
:event/elapsed 65
:event/card_type "y"
:event/player1 "Eugen Polanski"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2039254"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_8921"}

{:event/type "goal"
:event/elapsed 66
:event/player1 "Zdravko Kuzmanovic"
:event/sortorder 0
:event/team "home"
:event/id "event_2039131"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_8921"}

{:event/type "goal"
:event/elapsed 85
:event/player1 "Vedad Ibisevic"
:event/sortorder 0
:event/team "home"
:event/id "event_2039441"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_8921"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Shinji Okazaki"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2039524"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_8921"}


]

