
;;# data
[
{:match/id "match_9639"
:match/league "Germany 1. Bundesliga"
:match/hometeam "TSG 1899 Hoffenheim"
:match/awayteam "Bayer 04 Leverkusen"
:match/score "1:2"
:match/hometeam_goals "1"
:match/awayteam_goals "2"}

{:event/type "card"
:event/elapsed 9
:event/card_type "y"
:event/player1 "Omer Toprak"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3070392"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_9639"}

{:event/type "card"
:event/elapsed 23
:event/card_type "y"
:event/player1 "Philipp Wollscheid"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3070413"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_9639"}

{:event/type "goal"
:event/elapsed 26
:event/player1 "Sidney Sam"
:event/sortorder 0
:event/team "away"
:event/id "event_3070412"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_9639"}

{:event/type "card"
:event/elapsed 41
:event/card_type "y"
:event/player1 "Jens Hegeler"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3070426"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_9639"}

{:event/type "card"
:event/elapsed 67
:event/card_type "y"
:event/player1 "Gonzalo Castro"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3070481"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_9639"}

{:event/type "goal"
:event/elapsed 71
:event/player1 "Stefan Kiessling"
:event/sortorder 0
:event/team "away"
:event/id "event_3070484"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_9639"}

{:event/type "goal"
:event/elapsed 88
:event/player1 "Sven Schipplock"
:event/sortorder 0
:event/team "home"
:event/id "event_3070505"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_9639"}


]

