
;;# data
[
{:match/id "match_23226"
:match/league "Spain LIGA BBVA"
:match/hometeam "Real Madrid CF"
:match/awayteam "FC Barcelona"
:match/score "2:1"
:match/hometeam_goals "2"
:match/awayteam_goals "1"}

{:event/type "goal"
:event/elapsed 6
:event/player1 "Karim Benzema"
:event/sortorder 0
:event/team "home"
:event/id "event_2629069"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_23226"}

{:event/type "goal"
:event/elapsed 18
:event/player1 "Lionel Messi"
:event/sortorder 0
:event/team "away"
:event/id "event_2629183"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_23226"}

{:event/type "card"
:event/elapsed 51
:event/card_type "y"
:event/player1 "Sergio Ramos"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2629813"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_23226"}

{:event/type "card"
:event/elapsed 55
:event/card_type "y"
:event/player1 "Jordi Alba"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2629954"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_23226"}

{:event/type "card"
:event/elapsed 58
:event/card_type "y"
:event/player1 "Gerard Pique"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2629955"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_23226"}

{:event/type "card"
:event/elapsed 62
:event/card_type "y"
:event/player1 "Fabio Coentrao"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2630029"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_23226"}

{:event/type "card"
:event/elapsed 64
:event/card_type "y"
:event/player1 "Thiago Alcantara"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2630087"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_23226"}

{:event/type "card"
:event/elapsed 68
:event/card_type "y"
:event/player1 "Alvaro Morata"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2630219"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_23226"}

{:event/type "goal"
:event/elapsed 82
:event/player1 "Sergio Ramos"
:event/sortorder 0
:event/team "home"
:event/id "event_2630371"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_23226"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Daniel Alves"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2630564"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_23226"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Andres Iniesta"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2630565"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_23226"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Alvaro Arbeloa"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2630566"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_23226"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Victor Valdes"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2630918"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_23226"}

{:event/type "card"
:event/elapsed 90
:event/card_type "r"
:event/player1 "Victor Valdes"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2630920"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_23226"}


]

