
;;# data
[
{:match/id "match_21654"
:match/league "Spain LIGA BBVA"
:match/hometeam "RCD Espanyol"
:match/awayteam "RC Recreativo"
:match/score "1:1"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "card"
:event/elapsed 45
:event/card_type "y"
:event/player1 "Rafael Barber"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_570195"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_21654"}

{:event/type "goal"
:event/elapsed 62
:event/player1 "Nicolas Pareja"
:event/sortorder 0
:event/team "home"
:event/id "event_570333"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_21654"}

{:event/type "card"
:event/elapsed 67
:event/card_type "y"
:event/player1 "Nene"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_570382"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_21654"}

{:event/type "card"
:event/elapsed 80
:event/card_type "y"
:event/player1 "Cesar Arzo"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_570553"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_21654"}

{:event/type "card"
:event/elapsed 86
:event/card_type "y"
:event/player1 "Daniel Jarque"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_570639"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_21654"}

{:event/type "goal"
:event/elapsed 90
:event/player1 "Marco Ruben"
:event/sortorder 0
:event/team "away"
:event/id "event_570595"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_21654"}

{:event/type "card"
:event/elapsed 90
:event/card_type "r"
:event/player1 "Carlos Kameni"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_570641"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_21654"}


]

