
;;# data
[
{:match/id "match_15168"
:match/league "Netherlands Eredivisie"
:match/hometeam "Ajax"
:match/awayteam "Willem II"
:match/score "5:0"
:match/hometeam_goals "5"
:match/awayteam_goals "0"}

{:event/type "goal"
:event/elapsed 14
:event/player2 "Lucas Andersen"
:event/player1 "Kolbeinn Sigthorsson"
:event/sortorder 0
:event/team "home"
:event/id "event_3992781"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_15168"}

{:event/type "card"
:event/elapsed 15
:event/card_type "y"
:event/player1 "Ali Messaoud"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3992825"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_15168"}

{:event/type "goal"
:event/elapsed 27
:event/player2 "Lucas Andersen"
:event/player1 "Arkadiusz Milik"
:event/sortorder 0
:event/team "home"
:event/id "event_3992973"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_15168"}

{:event/type "goal"
:event/elapsed 31
:event/player2 "Lasse Schoene"
:event/player1 "Joel Veltman"
:event/sortorder 0
:event/team "home"
:event/id "event_3993034"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_15168"}

{:event/type "card"
:event/elapsed 35
:event/card_type "y"
:event/player1 "Mitchell Dijks"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3993097"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_15168"}

{:event/type "goal"
:event/elapsed 43
:event/player2 "Lucas Andersen"
:event/player1 "Arkadiusz Milik"
:event/sortorder 0
:event/team "home"
:event/id "event_3993231"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_15168"}

{:event/type "card"
:event/elapsed 44
:event/card_type "y"
:event/player1 "Stijn Wuytens"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3993296"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_15168"}

{:event/type "goal"
:event/elapsed 57
:event/player2 "Arkadiusz Milik"
:event/player1 "Davy Klaassen"
:event/sortorder 0
:event/team "home"
:event/id "event_3993611"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_15168"}

{:event/type "card"
:event/elapsed 83
:event/card_type "y"
:event/player1 "Ricardo Ippel"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3993805"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_15168"}


]

