
;;# data
[
{:match/id "match_15267"
:match/league "Netherlands Eredivisie"
:match/hometeam "SC Cambuur"
:match/awayteam "Heracles Almelo"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "goal"
:event/elapsed 19
:event/player2 "Etienne Reijnen"
:event/player1 "Sander van de Streek"
:event/sortorder 0
:event/team "home"
:event/id "event_4214397"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_15267"}

{:event/type "card"
:event/elapsed 27
:event/card_type "y"
:event/player1 "Thomas Bruns"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_4214569"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_15267"}

{:event/type "card"
:event/elapsed 74
:event/card_type "y"
:event/player1 "Vytautas Andriuskevicius"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_4215361"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_15267"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Martijn Barto"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_4215450"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_15267"}


]

