
;;# data
[
{:match/id "match_2507"
:match/league "England Premier League"
:match/hometeam "Bolton Wanderers"
:match/awayteam "Liverpool"
:match/score "0:1"
:match/hometeam_goals "0"
:match/awayteam_goals "1"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/sortorder 1
:event/team "home"
:event/event_type "throwin"
:event/id "event_1247696"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_1247701"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Joe Cole"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1247712"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1247715"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_2507"}

{:event/type "corner"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1247715"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_2507"}

{:event/type "shotoff"
:event/elapsed 4
:event/subtype "header"
:event/player1 "Fernando Torres"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1247717"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Paul Robinson"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1247727"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_2507"}

{:event/type "shotoff"
:event/elapsed 5
:event/subtype "header"
:event/player1 "Kevin Davies"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1247728"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Gretar Rafn Steinsson"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1247742"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_2507"}

{:event/type "shotoff"
:event/elapsed 8
:event/subtype "shot"
:event/player1 "Fernando Torres"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1247753"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Joe Cole"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1247755"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_2507"}

{:event/type "corner"
:event/elapsed 9
:event/subtype "short"
:event/player1 "Steven Gerrard"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1247759"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1247761"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_2507"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Maxi Rodriguez"
:event/player1 "Matthew Taylor"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1247767"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Paul Konchesky"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1247771"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_2507"}

{:event/type "foulcommit"
:event/elapsed 12
:event/subtype "hands"
:event/player1 "Kevin Davies"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1247778"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Stuart Holden"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1247799"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_2507"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "Kevin Davies"
:event/player1 "Lucas Leiva"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1247810"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Joe Cole"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1247815"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_2507"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Kevin Davies"
:event/subtype "pushing"
:event/player1 "Sotirios Kyrgiakos"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1247819"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_2507"}

{:event/type "shoton"
:event/elapsed 18
:event/subtype "blocked_shot"
:event/player1 "Matthew Taylor"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1247823"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_2507"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Sotirios Kyrgiakos"
:event/player1 "Fabrice Muamba"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1247824"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Jamie Carragher"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1247827"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_2507"}

{:event/type "shoton"
:event/elapsed 20
:event/subtype "blocked_shot"
:event/player1 "Gretar Rafn Steinsson"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1247831"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_2507"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player1 "Kevin Davies"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1247833"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_2507"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Chung-Yong Lee"
:event/player1 "Paul Konchesky"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1247835"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_2507"}

{:event/type "card"
:event/elapsed 21
:event/card_type "y"
:event/subtype "emergency_brake"
:event/player1 "Paul Konchesky"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1247836"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_2507"}

{:event/type "shoton"
:event/elapsed 23
:event/subtype "volley"
:event/player1 "Stuart Holden"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1247844"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_2507"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Stuart Holden"
:event/subtype "from_behind"
:event/player1 "Fernando Torres"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1247847"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Paul Robinson"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1247852"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_2507"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Raul Meireles"
:event/player1 "Fabrice Muamba"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1247860"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_2507"}

{:event/type "shotoff"
:event/elapsed 30
:event/subtype "bad shot"
:event/player1 "Joe Cole"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1247876"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_2507"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Jamie Carragher"
:event/player1 "Matthew Taylor"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1247880"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_2507"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Lucas Leiva"
:event/player1 "Stuart Holden"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1247890"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_2507"}

{:event/type "shotoff"
:event/elapsed 34
:event/subtype "direct_freekick"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1247893"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/sortorder 2
:event/team "home"
:event/event_type "throwin"
:event/id "event_1247905"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Paul Robinson"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1247908"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_2507"}

{:event/type "shotoff"
:event/elapsed 37
:event/subtype "distance"
:event/player1 "Fabrice Muamba"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1247913"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Matthew Taylor"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1247936"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_2507"}

{:event/type "shotoff"
:event/elapsed 41
:event/player1 "Steven Gerrard"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1247946"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_2507"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Kevin Davies"
:event/subtype "pushing"
:event/player1 "Sotirios Kyrgiakos"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1247952"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_2507"}

{:event/type "shoton"
:event/elapsed 43
:event/subtype "direct_freekick"
:event/player1 "Matthew Taylor"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1247957"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_2507"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Stuart Holden"
:event/player1 "Fernando Torres"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1247962"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_2507"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Jamie Carragher"
:event/player1 "Kevin Davies"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1247966"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_2507"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "Johan Elmander"
:event/player1 "Martin Skrtel"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1247982"
:event/minute 46
:event/match_id "match_2507"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "direct_freekick"
:event/player1 "Matthew Taylor"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1247987"
:event/minute 46
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Gretar Rafn Steinsson"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1248049"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Paul Robinson"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1248051"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Chung-Yong Lee"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_1248053"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_2507"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 45
:event/player2 "Fernando Torres"
:event/subtype "pushing"
:event/player1 "Gary Cahill"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1247993"
:event/minute 47
:event/match_id "match_2507"}

{:event/type "shoton"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "header"
:event/player1 "Sotirios Kyrgiakos"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1247997"
:event/minute 47
:event/match_id "match_2507"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Steven Gerrard"
:event/subtype "shirt_pull"
:event/player1 "Matthew Taylor"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1248080"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_2507"}

{:event/type "card"
:event/elapsed 49
:event/card_type "y"
:event/player1 "Matthew Taylor"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_1248082"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_2507"}

{:event/type "shoton"
:event/elapsed 52
:event/subtype "blocked_shot"
:event/player1 "Fernando Torres"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1248118"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Joe Cole"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1248119"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_2507"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Kevin Davies"
:event/subtype "pushing"
:event/player1 "Martin Skrtel"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1248129"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Gretar Rafn Steinsson"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1248141"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/sortorder 1
:event/team "home"
:event/event_type "throwin"
:event/id "event_1248143"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_2507"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Sotirios Kyrgiakos"
:event/player1 "Kevin Davies"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1248144"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_2507"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Chung-Yong Lee"
:event/player1 "Paul Konchesky"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1248155"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Maxi Rodriguez"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1248184"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_1248194"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_2507"}

{:event/type "shoton"
:event/elapsed 60
:event/subtype "deflected"
:event/player1 "Steven Gerrard"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1248204"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/sortorder 2
:event/team "home"
:event/event_type "throwin"
:event/id "event_1248232"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_2507"}

{:event/type "shoton"
:event/elapsed 63
:event/subtype "deflected"
:event/player1 "Fernando Torres"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1248240"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Raul Meireles"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1248251"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1248255"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_2507"}

{:event/type "corner"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1248255"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_2507"}

{:event/type "shotoff"
:event/elapsed 66
:event/subtype "header"
:event/player1 "Sotirios Kyrgiakos"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1248256"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "David Ngog"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1248269"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_2507"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Johan Elmander"
:event/subtype "shirt_pull"
:event/player1 "Martin Skrtel"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1248275"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_2507"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player1 "Sotirios Kyrgiakos"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1248281"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1248296"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_2507"}

{:event/type "shotoff"
:event/elapsed 71
:event/subtype "bicycle_kick"
:event/player1 "Maxi Rodriguez"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1248299"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_1248303"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_2507"}

{:event/type "shotoff"
:event/elapsed 73
:event/subtype "distance"
:event/player1 "Johan Elmander"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1248313"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Matthew Taylor"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1248318"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_2507"}

{:event/type "corner"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Matthew Taylor"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1248318"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_2507"}

{:event/type "shotoff"
:event/elapsed 74
:event/subtype "header"
:event/player1 "Zatyiah Knight"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1248319"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_2507"}

{:event/type "shotoff"
:event/elapsed 75
:event/subtype "shot"
:event/player1 "Johan Elmander"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1248327"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_2507"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Kevin Davies"
:event/player1 "Martin Skrtel"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1248330"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_2507"}

{:event/type "card"
:event/elapsed 75
:event/card_type "y"
:event/subtype "emergency_brake"
:event/player1 "Martin Skrtel"
:event/sortorder 4
:event/team "away"
:event/event_type "card"
:event/id "event_1248332"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_2507"}

{:event/type "shotoff"
:event/elapsed 76
:event/subtype "header"
:event/player1 "Kevin Davies"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1248337"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1248347"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_2507"}

{:event/type "corner"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1248347"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_2507"}

{:event/type "shoton"
:event/elapsed 78
:event/subtype "blocked_shot"
:event/player1 "Fabrice Muamba"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1248355"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_2507"}

{:event/type "shoton"
:event/elapsed 79
:event/subtype "blocked_shot"
:event/player1 "Gretar Rafn Steinsson"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1248359"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_2507"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "David Ngog"
:event/player1 "Gary Cahill"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1248397"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_2507"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Sotirios Kyrgiakos"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1248424"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Paul Konchesky"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1248435"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_2507"}

{:event/type "goal"
:event/elapsed 86
:event/player2 "Fernando Torres"
:event/subtype "shot"
:event/player1 "Maxi Rodriguez"
:event/sortorder 3
:event/team "away"
:event/id "event_1248445"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_2507"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player2 "Maxi Rodriguez"
:event/player1 "Gretar Rafn Steinsson"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1248475"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_2507"}

{:event/type "card"
:event/elapsed 89
:event/card_type "y"
:event/player1 "Gretar Rafn Steinsson"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1248484"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/sortorder 1
:event/team "home"
:event/event_type "throwin"
:event/id "event_1248492"
:event/minute 91
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_1248510"
:event/minute 93
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/sortorder 1
:event/team "home"
:event/event_type "throwin"
:event/id "event_1248511"
:event/minute 93
:event/match_id "match_2507"}

{:event/type "shoton"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "distance"
:event/player1 "Gary Cahill"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_1248516"
:event/minute 93
:event/match_id "match_2507"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Rodrigo"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1248519"
:event/minute 94
:event/match_id "match_2507"}

{:event/type "shoton"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "distance"
:event/player1 "Fabrice Muamba"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_1248524"
:event/minute 94
:event/match_id "match_2507"}


]

