
;;# data
[
{:match/id "match_8653"
:match/league "Germany 1. Bundesliga"
:match/hometeam "Hannover 96"
:match/awayteam "Borussia Mönchengladbach"
:match/score "0:1"
:match/hometeam_goals "0"
:match/awayteam_goals "1"}

{:event/type "card"
:event/elapsed 35
:event/card_type "y"
:event/player1 "Sergio Pinto"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1529110"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_8653"}

{:event/type "card"
:event/elapsed 63
:event/card_type "y"
:event/player1 "Karim Haggui"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1529570"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_8653"}

{:event/type "goal"
:event/elapsed 76
:event/player1 "Marco Reus"
:event/sortorder 0
:event/team "away"
:event/id "event_1529744"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_8653"}


]

