
;;# data
[
{:match/id "match_22529"
:match/league "Spain LIGA BBVA"
:match/hometeam "Villarreal CF"
:match/awayteam "Real Zaragoza"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Carlos Diogo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1512272"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_22529"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Santi Cazorla"
:event/subtype "from_behind"
:event/player1 "Carlos Diogo"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1512279"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_22529"}

{:event/type "shotoff"
:event/elapsed 4
:event/subtype "shot"
:event/player1 "Said Boutahar"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1512282"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_22529"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Giuseppe Rossi"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1512286"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_22529"}

{:event/type "foulcommit"
:event/elapsed 6
:event/player2 "Bruno Soriano"
:event/subtype "serious_foul"
:event/player1 "Leonardo Ponzio"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1512289"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_22529"}

{:event/type "foulcommit"
:event/elapsed 6
:event/player2 "Cani"
:event/subtype "from_behind"
:event/player1 "Ivan Obradovic"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1512290"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_22529"}

{:event/type "card"
:event/elapsed 7
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Ivan Obradovic"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1512291"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_22529"}

{:event/type "shoton"
:event/elapsed 8
:event/subtype "distance"
:event/player1 "Said Boutahar"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_1512295"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_22529"}

{:event/type "shoton"
:event/elapsed 9
:event/subtype "shot"
:event/player1 "Giuseppe Rossi"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1512298"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_22529"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Borja Valero"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_1512300"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_22529"}

{:event/type "corner"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Borja Valero"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_1512300"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_22529"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Jiri Jarosik"
:event/subtype "from_behind"
:event/player1 "Mateo Pablo Musacchio"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1512301"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_22529"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Borja Valero"
:event/subtype "from_behind"
:event/player1 "Nicolas Bertolo"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1512303"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_22529"}

{:event/type "shotoff"
:event/elapsed 12
:event/subtype "shot"
:event/player1 "Santi Cazorla"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1512305"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_22529"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Said Boutahar"
:event/subtype "from_behind"
:event/player1 "Mateo Pablo Musacchio"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1512310"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_22529"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "Mateo Pablo Musacchio"
:event/subtype "pushing"
:event/player1 "Said Boutahar"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1512313"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_22529"}

{:event/type "shoton"
:event/elapsed 17
:event/subtype "shot"
:event/player1 "Ikechukwu Uche"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1512316"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_22529"}

{:event/type "shotoff"
:event/elapsed 18
:event/subtype "distance"
:event/player1 "Leonardo Ponzio"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1512319"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_22529"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Giuseppe Rossi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1512324"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_22529"}

{:event/type "corner"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Giuseppe Rossi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1512324"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_22529"}

{:event/type "shotoff"
:event/elapsed 21
:event/subtype "shot"
:event/player1 "Mateo Pablo Musacchio"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1512325"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_22529"}

{:event/type "shoton"
:event/elapsed 22
:event/subtype "shot"
:event/player1 "Ikechukwu Uche"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1512327"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_22529"}

{:event/type "card"
:event/elapsed 23
:event/card_type "y"
:event/subtype "verbal_abuse"
:event/player1 "Cani"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1512329"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_22529"}

{:event/type "shoton"
:event/elapsed 24
:event/subtype "shot"
:event/player1 "Giuseppe Rossi"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1512331"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_22529"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Borja Valero"
:event/subtype "obstruction"
:event/player1 "Gabi"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1512337"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_22529"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Mario Gaspar"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1512339"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_22529"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Santi Cazorla"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1512341"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_22529"}

{:event/type "corner"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Santi Cazorla"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1512341"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_22529"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Ivan Obradovic"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1512342"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_22529"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Borja Valero"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1512345"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_22529"}

{:event/type "shoton"
:event/elapsed 32
:event/subtype "shot"
:event/player1 "Giuseppe Rossi"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1512347"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_22529"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Santi Cazorla"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1512348"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_22529"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Ivan Obradovic"
:event/subtype "from_behind"
:event/player1 "Borja Valero"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1512352"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_22529"}

{:event/type "shoton"
:event/elapsed 37
:event/subtype "distance"
:event/player1 "Leonardo Ponzio"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1512359"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_22529"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Bruno Soriano"
:event/subtype "from_behind"
:event/player1 "Ikechukwu Uche"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1512360"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_22529"}

{:event/type "card"
:event/elapsed 37
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Ikechukwu Uche"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_1512361"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_22529"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Giuseppe Rossi"
:event/subtype "pushing"
:event/player1 "Maurizio Lanzaro"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1512362"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_22529"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Mario Gaspar"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1512364"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_22529"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Borja Valero"
:event/subtype "from_behind"
:event/player1 "Gabi"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1512369"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_22529"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Giuseppe Rossi"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1512374"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_22529"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Santi Cazorla"
:event/subtype "from_behind"
:event/player1 "Carlos Diogo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1512377"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_22529"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Giuseppe Rossi"
:event/subtype "from_behind"
:event/player1 "Maurizio Lanzaro"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1512378"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_22529"}

{:event/type "shoton"
:event/elapsed 44
:event/subtype "blocked_shot"
:event/player1 "Jose Catala"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1512379"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_22529"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Borja Valero"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1512383"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_22529"}

{:event/type "corner"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Borja Valero"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1512383"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_22529"}

{:event/type "foulcommit"
:event/elapsed 46
:event/player2 "Ivan Obradovic"
:event/subtype "from_behind"
:event/player1 "Nilmar"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1512391"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_22529"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Ivan Obradovic"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1512393"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_22529"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Borja Valero"
:event/subtype "from_behind"
:event/player1 "Gabi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1512394"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_22529"}

{:event/type "shoton"
:event/elapsed 50
:event/subtype "shot"
:event/player1 "Ikechukwu Uche"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1512400"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_22529"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Ikechukwu Uche"
:event/subtype "from_behind"
:event/player1 "Mateo Pablo Musacchio"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1512406"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_22529"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Cani"
:event/subtype "from_behind"
:event/player1 "Gabi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1512407"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_22529"}

{:event/type "card"
:event/elapsed 53
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Gabi"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1512408"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_22529"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Ivan Obradovic"
:event/subtype "pushing"
:event/player1 "Giuseppe Rossi"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1512412"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_22529"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Borja Valero"
:event/subtype "from_behind"
:event/player1 "Leonardo Ponzio"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1512413"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_22529"}

{:event/type "shoton"
:event/elapsed 57
:event/subtype "shot"
:event/player1 "Ikechukwu Uche"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1512417"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_22529"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Borja Valero"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1512423"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_22529"}

{:event/type "foulcommit"
:event/elapsed 59
:event/player2 "Borja Valero"
:event/subtype "from_behind"
:event/player1 "Ivan Obradovic"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1512425"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_22529"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Ander Herrera"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1512429"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_22529"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Said Boutahar"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1512431"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_22529"}

{:event/type "corner"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Said Boutahar"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1512431"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_22529"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Carlos Diogo"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1512432"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_22529"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Carlos Diogo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1512436"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_22529"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Gabi"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1512437"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_22529"}

{:event/type "corner"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Gabi"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1512437"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_22529"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Giuseppe Rossi"
:event/subtype "from_behind"
:event/player1 "Leonardo Ponzio"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1512438"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_22529"}

{:event/type "card"
:event/elapsed 64
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Leonardo Ponzio"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1512439"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_22529"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Carlos Diogo"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1512441"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_22529"}

{:event/type "shoton"
:event/elapsed 65
:event/subtype "deflected"
:event/player1 "Ander Herrera"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1512442"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_22529"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Javier Paredes"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1512443"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_22529"}

{:event/type "corner"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Javier Paredes"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1512443"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_22529"}

{:event/type "shotoff"
:event/elapsed 66
:event/subtype "distance"
:event/player1 "Leonardo Ponzio"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1512446"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_22529"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Mario Gaspar"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1512450"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_22529"}

{:event/type "shoton"
:event/elapsed 69
:event/subtype "shot"
:event/player1 "Leonardo Ponzio"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1512453"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_22529"}

{:event/type "shoton"
:event/elapsed 70
:event/subtype "shot"
:event/player1 "Jose Catala"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1512456"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_22529"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Giuseppe Rossi"
:event/subtype "penalty"
:event/player1 "Leonardo Ponzio"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1512459"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_22529"}

{:event/type "card"
:event/elapsed 70
:event/card_type "y"
:event/subtype "verbal_abuse"
:event/player1 "Maurizio Lanzaro"
:event/sortorder 5
:event/team "away"
:event/event_type "card"
:event/id "event_1512457"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_22529"}

{:event/type "goal"
:event/elapsed 71
:event/player1 "Giuseppe Rossi"
:event/sortorder 0
:event/team "home"
:event/id "event_1512460"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_22529"}

{:event/type "foulcommit"
:event/elapsed 74
:event/player2 "Leonardo Ponzio"
:event/subtype "from_behind"
:event/player1 "Borja Valero"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1512465"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_22529"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Javier Paredes"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1512466"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_22529"}

{:event/type "foulcommit"
:event/elapsed 76
:event/player2 "Borja Valero"
:event/subtype "from_behind"
:event/player1 "Angel Lafita"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1512469"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_22529"}

{:event/type "shotoff"
:event/elapsed 81
:event/subtype "distance"
:event/player1 "Leonardo Ponzio"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1512479"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_22529"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Angel Lafita"
:event/subtype "from_behind"
:event/player1 "Mateo Pablo Musacchio"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1512481"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_22529"}

{:event/type "shotoff"
:event/elapsed 82
:event/subtype "distance"
:event/player1 "Carlos Diogo"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1512484"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_22529"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Javier Paredes"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1512491"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_22529"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Carlos Diogo"
:event/subtype "from_behind"
:event/player1 "Marco Ruben"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1512493"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_22529"}

{:event/type "shoton"
:event/elapsed 87
:event/subtype "direct_freekick"
:event/player1 "Javier Paredes"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1512494"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_22529"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Wakaso Mubarak"
:event/subtype "from_behind"
:event/player1 "Leonardo Ponzio"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1512496"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_22529"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Wakaso Mubarak"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1512497"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_22529"}

{:event/type "shoton"
:event/elapsed 88
:event/subtype "shot"
:event/player1 "Marco Ruben"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1512498"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_22529"}

{:event/type "shotoff"
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Ander Herrera"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1512503"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_22529"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Gabi"
:event/subtype "from_behind"
:event/player1 "Borja Valero"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1512517"
:event/minute 93
:event/match_id "match_22529"}

{:event/type "card"
:event/elapsed_plus 3
:event/elapsed 90
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Borja Valero"
:event/sortorder 3
:event/team "home"
:event/event_type "card"
:event/id "event_1512518"
:event/minute 93
:event/match_id "match_22529"}

{:event/type "card"
:event/elapsed_plus 4
:event/elapsed 90
:event/card_type "y"
:event/subtype "diving"
:event/player1 "Ikechukwu Uche"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1512520"
:event/minute 94
:event/match_id "match_22529"}


]

