
;;# data
[
{:match/id "match_3143"
:match/league "England Premier League"
:match/hometeam "Manchester United"
:match/awayteam "Aston Villa"
:match/score "4:0"
:match/hometeam_goals "4"
:match/awayteam_goals "0"}

{:event/type "shoton"
:event/elapsed 1
:event/subtype "shot"
:event/player1 "Andreas Weimann"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_2062578"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_3143"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Wayne Rooney"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2062585"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_3143"}

{:event/type "shoton"
:event/elapsed 4
:event/subtype "blocked_shot"
:event/player1 "Wayne Rooney"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_2062604"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_3143"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Ashley Young"
:event/subtype "penalty"
:event/player1 "Ciaran Clark"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2062619"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_3143"}

{:event/type "goal"
:event/elapsed 7
:event/player1 "Wayne Rooney"
:event/sortorder 1
:event/team "home"
:event/id "event_2062628"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_3143"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Gary Gardner"
:event/player1 "Michael Carrick"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2062641"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3143"}

{:event/type "card"
:event/elapsed 9
:event/card_type "y"
:event/player1 "Michael Carrick"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_2062680"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3143"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player1 "Jonny Evans"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2062688"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_3143"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Ashley Young"
:event/subtype "serious_foul"
:event/player1 "Stephen Ireland"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2062698"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_3143"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Wayne Rooney"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2062703"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_3143"}

{:event/type "shoton"
:event/elapsed 17
:event/subtype "header"
:event/player1 "Danny Welbeck"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_2062704"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_3143"}

{:event/type "shoton"
:event/elapsed 18
:event/subtype "shot"
:event/player1 "Wayne Rooney"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_2062711"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3143"}

{:event/type "corner"
:event/elapsed 19
:event/subtype "short"
:event/player1 "Ashley Young"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2062715"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_3143"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player1 "Wayne Rooney"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2062734"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_3143"}

{:event/type "shotoff"
:event/elapsed 21
:event/subtype "big chance header"
:event/player1 "Ciaran Clark"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2062741"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_3143"}

{:event/type "shoton"
:event/elapsed 23
:event/subtype "blocked_shot"
:event/player1 "Danny Welbeck"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_2062763"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_3143"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Ashley Young"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2062766"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_3143"}

{:event/type "corner"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Ashley Young"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2062766"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_3143"}

{:event/type "shotoff"
:event/elapsed 24
:event/subtype "header"
:event/player1 "Wayne Rooney"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2062768"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_3143"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Antonio Valencia"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2062776"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3143"}

{:event/type "shoton"
:event/elapsed 25
:event/subtype "blocked_shot"
:event/player1 "Danny Welbeck"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_2062777"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3143"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Ashley Young"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2062780"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3143"}

{:event/type "corner"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Ashley Young"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2062780"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3143"}

{:event/type "shoton"
:event/elapsed 25
:event/subtype "distance"
:event/player1 "Paul Scholes"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_2062782"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3143"}

{:event/type "shotoff"
:event/elapsed 27
:event/subtype "distance"
:event/player1 "Stephen Ireland"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2062789"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_3143"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Ashley Young"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2062800"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_3143"}

{:event/type "corner"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Ashley Young"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2062800"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_3143"}

{:event/type "shotoff"
:event/elapsed 29
:event/subtype "distance"
:event/player1 "Paul Scholes"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2062804"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_3143"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Antonio Valencia"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_2062852"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3143"}

{:event/type "shoton"
:event/elapsed 33
:event/subtype "shot"
:event/player1 "Danny Welbeck"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_2062853"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3143"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Ashley Young"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2062860"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_3143"}

{:event/type "corner"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Ashley Young"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2062860"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_3143"}

{:event/type "shotoff"
:event/elapsed 34
:event/subtype "shot"
:event/player1 "Wayne Rooney"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2062863"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_3143"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Patrice Evra"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2062887"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_3143"}

{:event/type "shotoff"
:event/elapsed 36
:event/subtype "bad shot"
:event/player1 "Antonio Valencia"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2062890"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_3143"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player1 "Barry Bannan"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2062894"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_3143"}

{:event/type "card"
:event/elapsed 38
:event/card_type "y"
:event/player1 "Gary Gardner"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2062910"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_3143"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player1 "Rafael"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2062940"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3143"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Patrice Evra"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2062956"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_3143"}

{:event/type "goal"
:event/elapsed 44
:event/player2 "Patrice Evra"
:event/subtype "tap_in"
:event/player1 "Danny Welbeck"
:event/sortorder 0
:event/team "home"
:event/id "event_2062957"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_3143"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "Patrice Evra"
:event/player1 "Gary Gardner"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2062975"
:event/minute 46
:event/match_id "match_3143"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Gabriel Agbonlahor"
:event/player1 "Paul Scholes"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2063148"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_3143"}

{:event/type "card"
:event/elapsed 49
:event/card_type "y"
:event/player1 "Paul Scholes"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_2063150"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_3143"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Ashley Young"
:event/subtype "serious_foul"
:event/player1 "Alan Hutton"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2063168"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3143"}

{:event/type "card"
:event/elapsed 51
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Alan Hutton"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_2063170"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3143"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Barry Bannan"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2063183"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_3143"}

{:event/type "shotoff"
:event/elapsed 54
:event/subtype "distance"
:event/player1 "Barry Bannan"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2063197"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_3143"}

{:event/type "shotoff"
:event/elapsed 63
:event/subtype "deflected"
:event/player1 "Paul Scholes"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2063261"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3143"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Antonio Valencia"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2063281"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_3143"}

{:event/type "corner"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Antonio Valencia"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2063281"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_3143"}

{:event/type "shotoff"
:event/elapsed 65
:event/subtype "shot"
:event/player1 "Nani"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2063282"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_3143"}

{:event/type "shoton"
:event/elapsed 66
:event/subtype "header"
:event/player1 "Emile Heskey"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_2063295"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_3143"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Barry Bannan"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_2063297"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_3143"}

{:event/type "corner"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Barry Bannan"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_2063297"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_3143"}

{:event/type "foulcommit"
:event/elapsed 67
:event/subtype "hands"
:event/player1 "Andreas Weimann"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2063310"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3143"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Antonio Valencia"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2063314"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_3143"}

{:event/type "shotoff"
:event/elapsed 68
:event/subtype "big chance shot"
:event/player1 "Wayne Rooney"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2063319"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_3143"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Barry Bannan"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2063328"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_3143"}

{:event/type "shotoff"
:event/elapsed 71
:event/subtype "deflected"
:event/player1 "Gabriel Agbonlahor"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2063341"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3143"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Barry Bannan"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_2063350"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3143"}

{:event/type "corner"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Barry Bannan"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_2063350"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3143"}

{:event/type "shotoff"
:event/elapsed 71
:event/subtype "header"
:event/player1 "Nathan Baker"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2063353"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3143"}

{:event/type "goal"
:event/elapsed 74
:event/player2 "Antonio Valencia"
:event/subtype "shot"
:event/player1 "Wayne Rooney"
:event/sortorder 1
:event/team "home"
:event/id "event_2063372"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_3143"}

{:event/type "foulcommit"
:event/elapsed 76
:event/player2 "unknown"
:event/player1 "Michael Carrick"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2063388"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3143"}

{:event/type "shotoff"
:event/elapsed 77
:event/subtype "direct_freekick"
:event/player1 "Gary Gardner"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2063396"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_3143"}

{:event/type "corner"
:event/elapsed 79
:event/subtype "short"
:event/player1 "Antonio Valencia"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2063430"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_3143"}

{:event/type "shoton"
:event/elapsed 79
:event/subtype "shot"
:event/player1 "Danny Welbeck"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_2063432"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_3143"}

{:event/type "corner"
:event/elapsed 80
:event/subtype "short"
:event/player1 "Nani"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2063435"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_3143"}

{:event/type "shotoff"
:event/elapsed 80
:event/subtype "deflected"
:event/player1 "Antonio Valencia"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2063440"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_3143"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Antonio Valencia"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2063442"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_3143"}

{:event/type "corner"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Antonio Valencia"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2063442"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_3143"}

{:event/type "shoton"
:event/elapsed 80
:event/subtype "blocked_shot"
:event/player1 "Nani"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_2063443"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_3143"}

{:event/type "shoton"
:event/elapsed 81
:event/subtype "shot"
:event/player1 "Antonio Valencia"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_2063447"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_3143"}

{:event/type "corner"
:event/elapsed 81
:event/subtype "short"
:event/player1 "Antonio Valencia"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2063450"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_3143"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player1 "Dimitar Berbatov"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2063492"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_3143"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Barry Bannan"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2063502"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3143"}

{:event/type "corner"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Barry Bannan"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2063502"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3143"}

{:event/type "shotoff"
:event/elapsed 86
:event/subtype "header"
:event/player1 "James Collins"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2063505"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3143"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Barry Bannan"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_2063524"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_3143"}

{:event/type "corner"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Barry Bannan"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_2063524"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_3143"}

{:event/type "foulcommit"
:event/elapsed 87
:event/player1 "Emile Heskey"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2063525"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_3143"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Antonio Valencia"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2063530"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_3143"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2063539"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3143"}

{:event/type "shoton"
:event/elapsed 90
:event/subtype "blocked_shot"
:event/player1 "Dimitar Berbatov"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_2063540"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3143"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2063542"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3143"}

{:event/type "corner"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2063542"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3143"}

{:event/type "shotoff"
:event/elapsed 90
:event/subtype "big chance header"
:event/player1 "Jonny Evans"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2063545"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3143"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Michael Carrick"
:event/subtype "serious_foul"
:event/player1 "Barry Bannan"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2063550"
:event/minute 91
:event/match_id "match_3143"}

{:event/type "card"
:event/elapsed_plus 1
:event/elapsed 90
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Barry Bannan"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_2063551"
:event/minute 91
:event/match_id "match_3143"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "serious_foul"
:event/player1 "Nani"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2063554"
:event/minute 92
:event/match_id "match_3143"}

{:event/type "card"
:event/elapsed_plus 2
:event/elapsed 90
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Nani"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_2063555"
:event/minute 92
:event/match_id "match_3143"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2063558"
:event/minute 93
:event/match_id "match_3143"}

{:event/type "goal"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Jonny Evans"
:event/subtype "shot"
:event/player1 "Nani"
:event/sortorder 1
:event/team "home"
:event/id "event_2063559"
:event/event_type "goal"
:event/goal_type "n"
:event/minute 93
:event/match_id "match_3143"}

{:event/type "shotoff"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Tom Cleverley"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2063568"
:event/minute 95
:event/match_id "match_3143"}


]

