
;;# data
[
{:match/id "match_3260"
:match/league "England Premier League"
:match/hometeam "Liverpool"
:match/awayteam "Newcastle United"
:match/score "1:1"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "shoton"
:event/elapsed 2
:event/subtype "blocked_shot"
:event/player1 "Steven Gerrard"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_2458791"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_3260"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Raheem Sterling"
:event/subtype "pushing"
:event/player1 "Vurnon Anita"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2458794"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_3260"}

{:event/type "shoton"
:event/elapsed 3
:event/subtype "indirect freekick"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_2458800"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Raheem Sterling"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2458804"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_3260"}

{:event/type "corner"
:event/elapsed 4
:event/subtype "short"
:event/player1 "Raheem Sterling"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_2458806"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Raheem Sterling"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2458814"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Andre Wisdom"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2458828"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_3260"}

{:event/type "shotoff"
:event/elapsed 8
:event/subtype "deflected"
:event/player1 "Suso"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2458839"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2458843"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_3260"}

{:event/type "corner"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2458843"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Nuri Sahin"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2458847"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3260"}

{:event/type "corner"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Nuri Sahin"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2458847"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3260"}

{:event/type "shotoff"
:event/elapsed 11
:event/subtype "distance"
:event/player1 "Raheem Sterling"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2458856"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_3260"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Luis Suarez"
:event/subtype "pushing"
:event/player1 "Fabricio Coloccini"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2458863"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_3260"}

{:event/type "shotoff"
:event/elapsed 15
:event/subtype "distance"
:event/player1 "Demba Ba"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2458882"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_3260"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "James Perch"
:event/player1 "Nuri Sahin"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2458889"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Jonas Gutierrez"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2458894"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_3260"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Luis Suarez"
:event/subtype "from_behind"
:event/player1 "James Perch"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2458905"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_3260"}

{:event/type "shotoff"
:event/elapsed 20
:event/subtype "direct_freekick"
:event/player1 "Luis Suarez"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2458910"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_3260"}

{:event/type "shotoff"
:event/elapsed 21
:event/subtype "distance"
:event/player1 "Hatem Ben Arfa"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2458914"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_3260"}

{:event/type "shoton"
:event/elapsed 21
:event/subtype "shot"
:event/player1 "Luis Suarez"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_2458917"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_3260"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Fabricio Coloccini"
:event/subtype "trip"
:event/player1 "Luis Suarez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2458920"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_3260"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Daniel Agger"
:event/subtype "pushing"
:event/player1 "Demba Ba"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2458923"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Nuri Sahin"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2458928"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_3260"}

{:event/type "corner"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Nuri Sahin"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2458928"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_3260"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Jonas Gutierrez"
:event/player1 "Nuri Sahin"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2458959"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_3260"}

{:event/type "shotoff"
:event/elapsed 29
:event/subtype "header"
:event/player1 "Luis Suarez"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2458976"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_3260"}

{:event/type "foulcommit"
:event/elapsed 30
:event/player2 "Demba Ba"
:event/subtype "from_behind"
:event/player1 "Joe Allen"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2458986"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2458995"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_3260"}

{:event/type "corner"
:event/elapsed 32
:event/subtype "short"
:event/player1 "Nuri Sahin"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2458998"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_3260"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Hatem Ben Arfa"
:event/subtype "trip"
:event/player1 "Suso"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2459000"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_3260"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Raheem Sterling"
:event/subtype "trip"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2459034"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_3260"}

{:event/type "shotoff"
:event/elapsed 40
:event/subtype "distance"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2459037"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_3260"}

{:event/type "shotoff"
:event/elapsed 41
:event/subtype "bad shot"
:event/player1 "Luis Suarez"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2459051"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3260"}

{:event/type "shoton"
:event/elapsed 41
:event/subtype "blocked_shot"
:event/player1 "Suso"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_2459055"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_2459058"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3260"}

{:event/type "corner"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_2459058"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3260"}

{:event/type "shotoff"
:event/elapsed 42
:event/subtype "volley"
:event/player1 "Suso"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2459060"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Hatem Ben Arfa"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2459076"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_3260"}

{:event/type "goal"
:event/elapsed 44
:event/player2 "Hatem Ben Arfa"
:event/subtype "volley"
:event/player1 "Yohan Cabaye"
:event/sortorder 1
:event/team "away"
:event/id "event_2459077"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_3260"}

{:event/type "shotoff"
:event/elapsed 45
:event/subtype "distance"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2459084"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_3260"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "bad shot"
:event/player1 "Luis Suarez"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2459090"
:event/minute 46
:event/match_id "match_3260"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "hands"
:event/player1 "Suso"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2459098"
:event/minute 47
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2459099"
:event/minute 47
:event/match_id "match_3260"}

{:event/type "shotoff"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "shot"
:event/player1 "Steven Taylor"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2459104"
:event/minute 48
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Suso"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2459170"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_3260"}

{:event/type "corner"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Suso"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2459170"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Raheem Sterling"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2459179"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_3260"}

{:event/type "corner"
:event/elapsed 49
:event/subtype "short"
:event/player1 "Steven Gerrard"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2459180"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_3260"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Raheem Sterling"
:event/player1 "Vurnon Anita"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2459187"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2459189"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_3260"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Papiss Cisse"
:event/subtype "dangerous_play"
:event/player1 "Raheem Sterling"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2459195"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2459203"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_3260"}

{:event/type "shotoff"
:event/elapsed 53
:event/subtype "volley"
:event/player1 "Vurnon Anita"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2459206"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_3260"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Luis Suarez"
:event/subtype "pushing"
:event/player1 "Davide Santon"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2459209"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2459215"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Raheem Sterling"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2459220"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3260"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Tim Krul"
:event/subtype "pushing"
:event/player1 "Martin Skrtel"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2459222"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Jose Enrique"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2459234"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_3260"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Danny Simpson"
:event/subtype "trip"
:event/player1 "Nuri Sahin"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2459239"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_3260"}

{:event/type "shoton"
:event/elapsed 58
:event/subtype "distance"
:event/player1 "Luis Suarez"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_2459256"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Nuri Sahin"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2459259"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3260"}

{:event/type "corner"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Nuri Sahin"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2459259"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3260"}

{:event/type "shotoff"
:event/elapsed 60
:event/subtype "deflected"
:event/player1 "Nuri Sahin"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2459271"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_3260"}

{:event/type "shoton"
:event/elapsed 61
:event/subtype "blocked_shot"
:event/player1 "Steven Gerrard"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_2459287"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_3260"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Raheem Sterling"
:event/subtype "pushing"
:event/player1 "Danny Simpson"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2459302"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2459307"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3260"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Papiss Cisse"
:event/player1 "Jose Enrique"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2459315"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2459321"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2459325"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_3260"}

{:event/type "corner"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2459325"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_2459331"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_3260"}

{:event/type "corner"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_2459331"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_3260"}

{:event/type "goal"
:event/elapsed 67
:event/player2 "Jose Enrique"
:event/subtype "shot"
:event/player1 "Luis Suarez"
:event/sortorder 1
:event/team "home"
:event/id "event_2459351"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3260"}

{:event/type "shoton"
:event/elapsed 70
:event/subtype "big chance shot"
:event/player1 "Jonjo Shelvey"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_2459370"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_3260"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Martin Skrtel"
:event/player1 "Shane Ferguson"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2459371"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_3260"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Fabricio Coloccini"
:event/player1 "Luis Suarez"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2459374"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_3260"}

{:event/type "corner"
:event/elapsed 71
:event/subtype "short"
:event/player1 "Hatem Ben Arfa"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2459384"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Hatem Ben Arfa"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2459385"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3260"}

{:event/type "foulcommit"
:event/elapsed 72
:event/player2 "Sammy Ameobi"
:event/player1 "Nuri Sahin"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2459387"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_3260"}

{:event/type "shotoff"
:event/elapsed 72
:event/subtype "direct_freekick"
:event/player1 "Hatem Ben Arfa"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2459394"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2459401"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3260"}

{:event/type "shoton"
:event/elapsed 73
:event/subtype "blocked_shot"
:event/player1 "Raheem Sterling"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_2459405"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Luis Suarez"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2459415"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_3260"}

{:event/type "corner"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Luis Suarez"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2459415"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_3260"}

{:event/type "shoton"
:event/elapsed 76
:event/subtype "big chance blocked"
:event/player1 "Raheem Sterling"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_2459431"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_2459433"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3260"}

{:event/type "corner"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_2459433"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Vurnon Anita"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2459439"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_3260"}

{:event/type "shotoff"
:event/elapsed 77
:event/subtype "volley"
:event/player1 "Papiss Cisse"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2459445"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_3260"}

{:event/type "foulcommit"
:event/elapsed 78
:event/player2 "Raheem Sterling"
:event/player1 "Jonas Gutierrez"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2459453"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2459459"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2459462"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_3260"}

{:event/type "corner"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2459462"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_3260"}

{:event/type "shoton"
:event/elapsed 80
:event/subtype "shot"
:event/player1 "Hatem Ben Arfa"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_2459467"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Jose Enrique"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2459489"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_3260"}

{:event/type "shoton"
:event/elapsed 83
:event/subtype "shot"
:event/player1 "Sammy Ameobi"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_2459495"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_3260"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Luis Suarez"
:event/subtype "dangerous_play"
:event/player1 "Fabricio Coloccini"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2459498"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_3260"}

{:event/type "card"
:event/elapsed 84
:event/card_type "r"
:event/subtype "serious_fouls"
:event/player1 "Fabricio Coloccini"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_2459501"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2459503"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Raheem Sterling"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2459513"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3260"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player1 "Sammy Ameobi"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2459522"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Jonjo Shelvey"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2459529"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2459540"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_3260"}

{:event/type "corner"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2459540"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_3260"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Steven Gerrard"
:event/subtype "trip"
:event/player1 "Davide Santon"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2459543"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_2459545"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_3260"}

{:event/type "shoton"
:event/elapsed 88
:event/subtype "volley"
:event/player1 "Jonjo Shelvey"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_2459547"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Jose Enrique"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2459561"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3260"}

{:event/type "shoton"
:event/elapsed 90
:event/subtype "big chance header"
:event/player1 "Jonjo Shelvey"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_2459562"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3260"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Raheem Sterling"
:event/player1 "Davide Santon"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2459571"
:event/minute 93
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Luis Suarez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2459572"
:event/minute 94
:event/match_id "match_3260"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Luis Suarez"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2459576"
:event/minute 94
:event/match_id "match_3260"}

{:event/type "corner"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Luis Suarez"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2459576"
:event/minute 94
:event/match_id "match_3260"}


]

