
;;# data
[
{:match/id "match_23859"
:match/league "Spain LIGA BBVA"
:match/hometeam "Atlético Madrid"
:match/awayteam "Villarreal CF"
:match/score "1:1"
:match/hometeam_goals "0"
:match/awayteam_goals "1"}

{:event/type "foulcommit"
:event/elapsed 4
:event/subtype "hands"
:event/player1 "Mario Mandzukic"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4015176"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_23859"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Miranda"
:event/player1 "Denis Cheryshev"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4015202"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_23859"}

{:event/type "shotoff"
:event/elapsed 10
:event/subtype "shot"
:event/player1 "Guilherme Siqueira"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4015228"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_23859"}

{:event/type "corner"
:event/elapsed 12
:event/subtype "short_right"
:event/player1 "Koke"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4015245"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Tiago"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4015246"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_23859"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Koke"
:event/player1 "Jonathan dos Santos"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4015253"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_23859"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Victor Ruiz"
:event/player1 "Miranda"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4015543"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 13
:event/subtype "cross"
:event/player1 "Gabi"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4015257"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Gabi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4015272"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_23859"}

{:event/type "corner"
:event/elapsed 15
:event/subtype "cross_left"
:event/player1 "Koke"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4015277"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Arda Turan"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4015283"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_23859"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "Mario Gaspar"
:event/player1 "Raul Garcia"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4015284"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Arda Turan"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4015287"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_23859"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Diego Godin"
:event/subtype "trip"
:event/player1 "Ikechukwu Uche"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4015296"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_23859"}

{:event/type "card"
:event/elapsed 17
:event/card_type "y"
:event/player1 "Ikechukwu Uche"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_4015298"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_23859"}

{:event/type "shotoff"
:event/elapsed 18
:event/subtype "distance"
:event/player1 "Koke"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4015301"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_23859"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Juanfran"
:event/player1 "Luciano Dario Vietto"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4015322"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_23859"}

{:event/type "corner"
:event/elapsed 23
:event/subtype "cross_right"
:event/player1 "Gabi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4015343"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Juanfran"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4015348"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Arda Turan"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4015354"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Jonathan dos Santos"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4015358"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Denis Cheryshev"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4015368"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Mario Mandzukic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4015370"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_23859"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Luciano Dario Vietto"
:event/subtype "trip"
:event/player1 "Arda Turan"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4015377"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_23859"}

{:event/type "card"
:event/elapsed 28
:event/card_type "y"
:event/player1 "Arda Turan"
:event/sortorder 3
:event/team "home"
:event/event_type "card"
:event/id "event_4015378"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Denis Cheryshev"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4015391"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Guilherme Siqueira"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4015397"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_23859"}

{:event/type "corner"
:event/elapsed 33
:event/subtype "short_left"
:event/player1 "Manuel Trigueros"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4015411"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Jaume Costa"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4015412"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_23859"}

{:event/type "foulcommit"
:event/elapsed 34
:event/player2 "Tiago"
:event/player1 "Ikechukwu Uche"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4015416"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Arda Turan"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4015425"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_23859"}

{:event/type "shotoff"
:event/elapsed 35
:event/subtype "header"
:event/player1 "Diego Godin"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4015427"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_23859"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Jonathan dos Santos"
:event/subtype "trip"
:event/player1 "Mario Mandzukic"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4015437"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_23859"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Ikechukwu Uche"
:event/subtype "dangerous_play"
:event/player1 "Tiago"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4015441"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Juanfran"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4015444"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_23859"}

{:event/type "shoton"
:event/elapsed 38
:event/subtype "shot"
:event/player1 "Tiago"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4015447"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_23859"}

{:event/type "corner"
:event/elapsed 38
:event/subtype "cross_right"
:event/player1 "Koke"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4015448"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_23859"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Gabriel Paulista"
:event/subtype "pull"
:event/player1 "Diego Godin"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4015451"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_23859"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Tiago"
:event/player1 "Manuel Trigueros"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4015454"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_23859"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Mario Mandzukic"
:event/player1 "Jonathan dos Santos"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4015460"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_23859"}

{:event/type "card"
:event/elapsed 41
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Jonathan dos Santos"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_4015465"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_23859"}

{:event/type "card"
:event/elapsed 41
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Mario Mandzukic"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4015473"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_23859"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Guilherme Siqueira"
:event/subtype "pushing"
:event/player1 "Mario Gaspar"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4015477"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Koke"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4015480"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_23859"}

{:event/type "shoton"
:event/elapsed 43
:event/subtype "blocked_shot"
:event/player1 "Raul Garcia"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_4015484"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_23859"}

{:event/type "shoton"
:event/elapsed 43
:event/subtype "shot"
:event/player1 "Denis Cheryshev"
:event/sortorder 6
:event/team "away"
:event/event_type "shoton"
:event/id "event_4015490"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_23859"}

{:event/type "foulcommit"
:event/elapsed 44
:event/subtype "hands"
:event/player1 "Juanfran"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4015491"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_23859"}

{:event/type "card"
:event/elapsed 44
:event/card_type "y"
:event/player1 "Juanfran"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4015492"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Koke"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4015502"
:event/minute 46
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Gabi"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4015545"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_4015547"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_23859"}

{:event/type "shotoff"
:event/elapsed 48
:event/subtype "distance"
:event/player1 "Denis Cheryshev"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4015551"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_23859"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Arda Turan"
:event/player1 "Ikechukwu Uche"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4015553"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_23859"}

{:event/type "shotoff"
:event/elapsed 51
:event/subtype "shot"
:event/player1 "Luciano Dario Vietto"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4015555"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_23859"}

{:event/type "shoton"
:event/elapsed 51
:event/subtype "deflected"
:event/player1 "Denis Cheryshev"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_4015558"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Gabi"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_4015559"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_23859"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Jaume Costa"
:event/player1 "Arda Turan"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4015561"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Mario Gaspar"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4015562"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_23859"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Gabi"
:event/subtype "trip"
:event/player1 "Manuel Trigueros"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4015566"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_23859"}

{:event/type "card"
:event/elapsed 55
:event/card_type "y"
:event/player1 "Manuel Trigueros"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_4015567"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Gabi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4015568"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_23859"}

{:event/type "shoton"
:event/elapsed 57
:event/subtype "big chance shot"
:event/player1 "Mario Mandzukic"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4015570"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_23859"}

{:event/type "corner"
:event/elapsed 57
:event/subtype "short_right"
:event/player1 "Arda Turan"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4015571"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Juanfran"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4015572"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_23859"}

{:event/type "corner"
:event/elapsed 57
:event/subtype "cross_left"
:event/player1 "Koke"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_4015574"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Arda Turan"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4015577"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_23859"}

{:event/type "goal"
:event/elapsed 59
:event/subtype "header"
:event/player1 "Mario Mandzukic"
:event/sortorder 2
:event/team "home"
:event/id "event_4015578"
:event/event_type "goal"
:event/goal_type "dg"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_23859"}

{:event/type "foulcommit"
:event/elapsed 59
:event/player2 "Mario Gaspar"
:event/subtype "pushing"
:event/player1 "Mario Mandzukic"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4015579"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Juanfran"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4015580"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_23859"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Koke"
:event/player1 "Denis Cheryshev"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4015582"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Juanfran"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4015583"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Gabi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4015586"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_23859"}

{:event/type "shotoff"
:event/elapsed 64
:event/subtype "header"
:event/player1 "Koke"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4015587"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Denis Cheryshev"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4015589"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_23859"}

{:event/type "foulcommit"
:event/elapsed 67
:event/subtype "hands"
:event/player1 "Tomas Pina"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4015591"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Jonathan dos Santos"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4015594"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Antoine Griezmann"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4015597"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Gabi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4015598"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_23859"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Moi Gomez"
:event/player1 "Miranda"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4015611"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_23859"}

{:event/type "foulcommit"
:event/elapsed 72
:event/player2 "Mario Mandzukic"
:event/player1 "Tomas Pina"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4015681"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Mario Suarez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4015614"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Alessio Cerci"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4015616"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Jaume Costa"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4015618"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Koke"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4015620"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_23859"}

{:event/type "corner"
:event/elapsed 80
:event/subtype "cross_right"
:event/player1 "Koke"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4015622"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Koke"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_4015624"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_23859"}

{:event/type "shotoff"
:event/elapsed 80
:event/subtype "header"
:event/player1 "Diego Godin"
:event/sortorder 5
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4015625"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Guilherme Siqueira"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4015627"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_23859"}

{:event/type "shotoff"
:event/elapsed 82
:event/subtype "shot"
:event/player1 "Tiago"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4015629"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_23859"}

{:event/type "shoton"
:event/elapsed 82
:event/subtype "shot"
:event/player1 "Denis Cheryshev"
:event/sortorder 5
:event/team "away"
:event/event_type "shoton"
:event/id "event_4015632"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_23859"}

{:event/type "corner"
:event/elapsed 83
:event/subtype "cross_left"
:event/player1 "Jonathan dos Santos"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4015633"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Jonathan dos Santos"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4015635"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_23859"}

{:event/type "foulcommit"
:event/elapsed 83
:event/player2 "Diego Godin"
:event/subtype "pushing"
:event/player1 "Victor Ruiz"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4015636"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_23859"}

{:event/type "goal"
:event/elapsed 84
:event/player2 "Moi Gomez"
:event/subtype "shot"
:event/player1 "Luciano Dario Vietto"
:event/sortorder 1
:event/team "away"
:event/id "event_4015639"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Guilherme Siqueira"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4015641"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_23859"}

{:event/type "foulcommit"
:event/elapsed 87
:event/player2 "Bruno Soriano"
:event/player1 "Mario Suarez"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4015643"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_23859"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Jonathan dos Santos"
:event/player1 "Koke"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4015644"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_23859"}

{:event/type "card"
:event/elapsed 88
:event/card_type "y"
:event/player1 "Koke"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4015645"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_23859"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player2 "Alessio Cerci"
:event/player1 "Jaume Costa"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4015648"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Juanfran"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4015650"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_23859"}

{:event/type "shotoff"
:event/elapsed 90
:event/subtype "header"
:event/player1 "Diego Godin"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4015651"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_23859"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Jonathan dos Santos"
:event/player1 "Guilherme Siqueira"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4015653"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_23859"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Diego Godin"
:event/player1 "Bruno Soriano"
:event/sortorder 6
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4015658"
:event/minute 92
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Koke"
:event/sortorder 7
:event/team "home"
:event/event_type "cross"
:event/id "event_4015660"
:event/minute 92
:event/match_id "match_23859"}

{:event/type "corner"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross_right"
:event/player1 "Koke"
:event/sortorder 9
:event/team "home"
:event/event_type "corner"
:event/id "event_4015662"
:event/minute 93
:event/match_id "match_23859"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/sortorder 11
:event/team "home"
:event/event_type "throwin"
:event/id "event_4015664"
:event/minute 93
:event/match_id "match_23859"}


]

