
;;# data
[
{:match/id "match_3685"
:match/league "England Premier League"
:match/hometeam "Swansea City"
:match/awayteam "Newcastle United"
:match/score "2:1"
:match/hometeam_goals "3"
:match/awayteam_goals "0"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Alejandro Pozuelo"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3161644"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Jonjo Shelvey"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_3161652"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_3685"}

{:event/type "shoton"
:event/elapsed 6
:event/subtype "header"
:event/player1 "Alvaro Vazquez"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3161653"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Pablo Hernandez"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3161689"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Yoan Gouffran"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3161705"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3685"}

{:event/type "shotoff"
:event/elapsed 10
:event/subtype "distance"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3161722"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Jonjo Shelvey"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3161748"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Moussa Sissoko"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3161754"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Moussa Sissoko"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_3161758"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Mathieu Debuchy"
:event/sortorder 7
:event/team "away"
:event/event_type "cross"
:event/id "event_3161763"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_3685"}

{:event/type "shoton"
:event/elapsed 12
:event/subtype "header"
:event/player1 "Loic Remy"
:event/sortorder 8
:event/team "away"
:event/event_type "shoton"
:event/id "event_3161764"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Alejandro Pozuelo"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3161792"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Jonjo Shelvey"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3161829"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_3685"}

{:event/type "shotoff"
:event/elapsed 18
:event/subtype "shot"
:event/player1 "Alvaro Vazquez"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3161851"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3685"}

{:event/type "shoton"
:event/elapsed 19
:event/subtype "distance"
:event/player1 "Davide Santon"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_3161865"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Ben Davies"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3161876"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Alejandro Pozuelo"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3161879"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_3685"}

{:event/type "shotoff"
:event/elapsed 21
:event/subtype "distance"
:event/player1 "Jonjo Shelvey"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3161888"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Ben Davies"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3161918"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Mathieu Debuchy"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3161936"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Mathieu Debuchy"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3161947"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Mathieu Debuchy"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3161949"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_3685"}

{:event/type "shoton"
:event/elapsed 25
:event/subtype "shot"
:event/player1 "Shola Ameobi"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3161968"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3685"}

{:event/type "shoton"
:event/elapsed 26
:event/subtype "distance"
:event/player1 "Chico"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3161994"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_3685"}

{:event/type "shoton"
:event/elapsed 29
:event/subtype "blocked_shot"
:event/player1 "Shola Ameobi"
:event/sortorder 4
:event/team "away"
:event/event_type "shoton"
:event/id "event_3162047"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_3685"}

{:event/type "shotoff"
:event/elapsed 30
:event/subtype "shot"
:event/player1 "Loic Remy"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3162058"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_3685"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Shola Ameobi"
:event/subtype "obstruction"
:event/player1 "Nathan Dyer"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3162087"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_3685"}

{:event/type "shotoff"
:event/elapsed 32
:event/subtype "direct_freekick"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3162095"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_3685"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Pablo Hernandez"
:event/subtype "from_behind"
:event/player1 "Mathieu Debuchy"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3162161"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Dwight Tiendalli"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3162172"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_3685"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Nathan Dyer"
:event/subtype "from_behind"
:event/player1 "Fabricio Coloccini"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3162189"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_3685"}

{:event/type "shoton"
:event/elapsed 38
:event/subtype "blocked_shot"
:event/player1 "Jonjo Shelvey"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3162203"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Dwight Tiendalli"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3162226"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Pablo Hernandez"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3162228"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_3685"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Shola Ameobi"
:event/subtype "from_behind"
:event/player1 "Ashley Williams"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3162235"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_3685"}

{:event/type "shoton"
:event/elapsed 41
:event/subtype "blocked_shot"
:event/player1 "Yoan Gouffran"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3162260"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3685"}

{:event/type "shoton"
:event/elapsed 41
:event/subtype "blocked_shot"
:event/player1 "Yohan Cabaye"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3162265"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3685"}

{:event/type "shotoff"
:event/elapsed 41
:event/subtype "distance"
:event/player1 "Cheik Tiote"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3162269"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3685"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Jonathan De Guzman"
:event/subtype "from_behind"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3162320"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Nathan Dyer"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3162322"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_3685"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Jonathan De Guzman"
:event/player1 "Loic Remy"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3162347"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_3685"}

{:event/type "foulcommit"
:event/elapsed 46
:event/player2 "Dwight Tiendalli"
:event/player1 "Cheik Tiote"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3162501"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Alejandro Pozuelo"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_3162379"
:event/minute 46
:event/match_id "match_3685"}

{:event/type "goal"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "shot"
:event/player1 "Nathan Dyer"
:event/sortorder 8
:event/team "home"
:event/id "event_3162371"
:event/event_type "goal"
:event/goal_type "n"
:event/minute 46
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Jonathan De Guzman"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3162517"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_3685"}

{:event/type "shoton"
:event/elapsed 47
:event/subtype "header"
:event/player1 "Nathan Dyer"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3162521"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Mathieu Debuchy"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3162570"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Davide Santon"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3162594"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3685"}

{:event/type "shoton"
:event/elapsed 51
:event/subtype "deflected"
:event/player1 "Yohan Cabaye"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_3162604"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3685"}

{:event/type "shoton"
:event/elapsed 51
:event/subtype "shot"
:event/player1 "Shola Ameobi"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_3162606"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3685"}

{:event/type "shotoff"
:event/elapsed 51
:event/subtype "distance"
:event/player1 "Jonjo Shelvey"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3162609"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Mathieu Debuchy"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3162630"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Yoan Gouffran"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3162637"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Shola Ameobi"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3162673"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3162680"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_3685"}

{:event/type "corner"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3162680"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_3685"}

{:event/type "shotoff"
:event/elapsed 56
:event/subtype "header"
:event/player1 "Loic Remy"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3162682"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_3685"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Cheik Tiote"
:event/player1 "Nathan Dyer"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3162700"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Yoan Gouffran"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3162712"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3685"}

{:event/type "shoton"
:event/elapsed 58
:event/subtype "blocked_shot"
:event/player1 "Loic Remy"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3162714"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3685"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Pablo Hernandez"
:event/subtype "trip"
:event/player1 "Mathieu Debuchy"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3162719"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3685"}

{:event/type "card"
:event/elapsed 58
:event/card_type "y"
:event/player1 "Mathieu Debuchy"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_3162720"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Jonathan De Guzman"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_3162752"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Jonathan De Guzman"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3162983"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3685"}

{:event/type "corner"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Jonathan De Guzman"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3162983"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3685"}

{:event/type "shoton"
:event/elapsed 65
:event/subtype "blocked_shot"
:event/player1 "Shola Ameobi"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_3162817"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Moussa Sissoko"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3162837"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_3685"}

{:event/type "goal"
:event/elapsed 66
:event/player1 "Mathieu Debuchy"
:event/sortorder 10
:event/team "away"
:event/id "event_3162842"
:event/event_type "goal"
:event/goal_type "o"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Jonathan De Guzman"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3162880"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_3685"}

{:event/type "corner"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Jonathan De Guzman"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3162880"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Pablo Hernandez"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3162893"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Jonathan De Guzman"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_3162964"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3685"}

{:event/type "corner"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Jonathan De Guzman"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_3162964"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Nathan Dyer"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3162965"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_3685"}

{:event/type "shotoff"
:event/elapsed 74
:event/subtype "shot"
:event/player1 "Jonjo Shelvey"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3162969"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_3685"}

{:event/type "shoton"
:event/elapsed 75
:event/subtype "distance"
:event/player1 "Jonjo Shelvey"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3162994"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Jonathan De Guzman"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3163011"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3685"}

{:event/type "corner"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Jonathan De Guzman"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3163011"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Gabriel Obertan"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_3163019"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Mathieu Debuchy"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3163052"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_3685"}

{:event/type "goal"
:event/elapsed 81
:event/player2 "Jonathan De Guzman"
:event/subtype "distance"
:event/player1 "Jonjo Shelvey"
:event/sortorder 5
:event/team "home"
:event/id "event_3163124"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_3685"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Gabriel Obertan"
:event/subtype "obstruction"
:event/player1 "Chico"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3163161"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_3685"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Nathan Dyer"
:event/subtype "trip"
:event/player1 "Massadio Haidara"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3163202"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3685"}

{:event/type "card"
:event/elapsed 86
:event/card_type "y"
:event/player1 "Massadio Haidara"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_3163205"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Jonathan De Guzman"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3163226"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_3685"}

{:event/type "corner"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Jonathan De Guzman"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3163226"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_3685"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Cheik Tiote"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3163267"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3685"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Roland Lamah"
:event/subtype "trip"
:event/player1 "Loic Remy"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3163278"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3685"}


]

