
;;# data
[
{:match/id "match_7731"
:match/league "France Ligue 1"
:match/hometeam "GFC Ajaccio"
:match/awayteam "Paris Saint-Germain"
:match/score "0:4"
:match/hometeam_goals "0"
:match/awayteam_goals "4"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Jacques Zoua Daogari"
:event/subtype "trip"
:event/player1 "Thiago Motta"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5581663"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_7731"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Angel Di Maria"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5581683"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_7731"}

{:event/type "corner"
:event/elapsed 11
:event/subtype "cross_right"
:event/player1 "David Ducourtioux"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_5581885"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_7731"}

{:event/type "cross"
:event/elapsed 13
:event/subtype "cross"
:event/player1 "Angel Di Maria"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5581917"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_7731"}

{:event/type "goal"
:event/elapsed 13
:event/player2 "Angel Di Maria"
:event/subtype "header"
:event/player1 "Edinson Cavani"
:event/sortorder 1
:event/team "away"
:event/id "event_5581929"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_7731"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Khalid Boutaib"
:event/subtype "trip"
:event/player1 "Lavyin Kurzawa"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5582089"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_7731"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Jerome Le Moigne"
:event/subtype "trip"
:event/player1 "Thiago Motta"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5582122"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_7731"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Alexandre Coeff"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5582150"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_7731"}

{:event/type "corner"
:event/elapsed 23
:event/subtype "cross_right"
:event/player1 "Alexandre Coeff"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_5582156"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_7731"}

{:event/type "shotoff"
:event/elapsed 24
:event/subtype "header"
:event/player1 "Roderic Filippi"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5582174"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_7731"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Issiaga Sylla"
:event/player1 "Thiago Silva"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5582222"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_7731"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Thiago Silva"
:event/player1 "Jacques Zoua Daogari"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5582268"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_7731"}

{:event/type "foulcommit"
:event/elapsed 30
:event/player2 "Marquinhos"
:event/subtype "pushing"
:event/player1 "David Ducourtioux"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5582309"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_7731"}

{:event/type "shotoff"
:event/elapsed 31
:event/subtype "crossbar"
:event/player1 "Angel Di Maria"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5582322"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_7731"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Angel Di Maria"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5582371"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_7731"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Roderic Filippi"
:event/subtype "pull"
:event/player1 "Zlatan Ibrahimovic"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5582374"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_7731"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Alexandre Coeff"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5582393"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_7731"}

{:event/type "foulcommit"
:event/elapsed 34
:event/player2 "Christopher Nkunku"
:event/player1 "David Ducourtioux"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5582404"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_7731"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Angel Di Maria"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5582426"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_7731"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Benjamin Stambouli"
:event/subtype "pushing"
:event/player1 "David Ducourtioux"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5582503"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_7731"}

{:event/type "corner"
:event/elapsed 41
:event/subtype "cross_left"
:event/player1 "Angel Di Maria"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_5582553"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_7731"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Angel Di Maria"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5582579"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_7731"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Zlatan Ibrahimovic"
:event/player1 "Khalid Boutaib"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5582605"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_7731"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Thiago Motta"
:event/subtype "pushing"
:event/player1 "David Ducourtioux"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5582622"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_7731"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Alassane Toure"
:event/subtype "pushing"
:event/player1 "Edinson Cavani"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5582652"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_7731"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Jacques Zoua Daogari"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5582795"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_7731"}

{:event/type "foulcommit"
:event/elapsed 47
:event/player2 "Christopher Nkunku"
:event/subtype "pull"
:event/player1 "Jerome Le Moigne"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5582807"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_7731"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Angel Di Maria"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5582845"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_7731"}

{:event/type "goal"
:event/elapsed 49
:event/player2 "Angel Di Maria"
:event/subtype "shot"
:event/player1 "Edinson Cavani"
:event/sortorder 1
:event/team "away"
:event/id "event_5582848"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_7731"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Issiaga Sylla"
:event/subtype "trip"
:event/player1 "Thiago Silva"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5582895"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_7731"}

{:event/type "card"
:event/elapsed 51
:event/card_type "y"
:event/player1 "Thiago Silva"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_5582899"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_7731"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Edinson Cavani"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5582929"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_7731"}

{:event/type "shoton"
:event/elapsed 54
:event/subtype "big chance header"
:event/player1 "Zlatan Ibrahimovic"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_5582966"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_7731"}

{:event/type "corner"
:event/elapsed 54
:event/subtype "cross_right"
:event/player1 "Angel Di Maria"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_5582970"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_7731"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Pablo Martinez"
:event/player1 "Marquinhos"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5583000"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_7731"}

{:event/type "shoton"
:event/elapsed 56
:event/subtype "blocked_shot"
:event/player1 "Christopher Nkunku"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_5583003"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_7731"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Lavyin Kurzawa"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5583069"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_7731"}

{:event/type "goal"
:event/elapsed 58
:event/player2 "Lavyin Kurzawa"
:event/subtype "header"
:event/player1 "Edinson Cavani"
:event/sortorder 1
:event/team "away"
:event/id "event_5583072"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_7731"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Issiaga Sylla"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5583179"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_7731"}

{:event/type "corner"
:event/elapsed 62
:event/subtype "cross_left"
:event/player1 "Alexandre Coeff"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_5583195"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_7731"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Zlatan Ibrahimovic"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5583209"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_7731"}

{:event/type "shoton"
:event/elapsed 63
:event/subtype "blocked_shot"
:event/player1 "Jacques Zoua Daogari"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_5583223"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_7731"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Kevin Mayi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5583462"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_7731"}

{:event/type "foulcommit"
:event/elapsed 74
:event/player2 "Lucas Moura"
:event/subtype "obstruction"
:event/player1 "Kader Mangane"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5583489"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_7731"}

{:event/type "card"
:event/elapsed 74
:event/card_type "y"
:event/player1 "Kader Mangane"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_5583490"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_7731"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Angel Di Maria"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5583500"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_7731"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "David Ducourtioux"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5583515"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_7731"}

{:event/type "shoton"
:event/elapsed 76
:event/subtype "blocked_shot"
:event/player1 "Kevin Mayi"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_5583523"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_7731"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Issiaga Sylla"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_5583528"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_7731"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Issiaga Sylla"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5583644"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_7731"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Kevin Mayi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5583659"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_7731"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Damjan Djokovic"
:event/player1 "David Luiz"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5583669"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_7731"}

{:event/type "shoton"
:event/elapsed 83
:event/subtype "big chance shot"
:event/player1 "Lucas Moura"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_5583693"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_7731"}

{:event/type "corner"
:event/elapsed 83
:event/subtype "cross_right"
:event/player1 "Lucas Moura"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_5583704"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_7731"}

{:event/type "shotoff"
:event/elapsed 83
:event/subtype "header"
:event/player1 "Marquinhos"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5583707"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_7731"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Benjamin Stambouli"
:event/player1 "David Ducourtioux"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5583723"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_7731"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Lavyin Kurzawa"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5583758"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_7731"}

{:event/type "shotoff"
:event/elapsed 88
:event/subtype "distance"
:event/player1 "Kevin Mayi"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5583828"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_7731"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player2 "Damjan Djokovic"
:event/player1 "Thiago Motta"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5583857"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_7731"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Alexandre Coeff"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5583864"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_7731"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Pablo Martinez"
:event/subtype "trip"
:event/player1 "Jean-Kevin Augustin"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5583895"
:event/minute 91
:event/match_id "match_7731"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Alexandre Coeff"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_5583910"
:event/minute 91
:event/match_id "match_7731"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "big chance shot"
:event/player1 "Khalid Boutaib"
:event/sortorder 7
:event/team "home"
:event/event_type "shoton"
:event/id "event_5583920"
:event/minute 91
:event/match_id "match_7731"}

{:event/type "goal"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Maxwell"
:event/subtype "distance"
:event/player1 "Zlatan Ibrahimovic"
:event/sortorder 10
:event/team "away"
:event/id "event_5583946"
:event/event_type "goal"
:event/goal_type "n"
:event/minute 92
:event/match_id "match_7731"}


]

