
;;# data
[
{:match/id "match_11566"
:match/league "Italy Serie A"
:match/hometeam "Napoli"
:match/awayteam "Inter"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Marco Davide Faraoni"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1965567"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Blerim Dzemaili"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1965574"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1965576"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_11566"}

{:event/type "corner"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1965576"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_11566"}

{:event/type "shoton"
:event/elapsed 4
:event/subtype "distance"
:event/player1 "Gokhan Inler"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_1965578"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1965583"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1965587"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_11566"}

{:event/type "corner"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1965587"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_11566"}

{:event/type "shotoff"
:event/elapsed 8
:event/subtype "header"
:event/player1 "Edinson Cavani"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1965588"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_11566"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Marco Davide Faraoni"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1965595"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Esteban Cambiasso"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1965604"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_11566"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Christian Maggio"
:event/subtype "shirt_pull"
:event/player1 "Yuto Nagatomo"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1965609"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_11566"}

{:event/type "card"
:event/elapsed 13
:event/card_type "y"
:event/player1 "Yuto Nagatomo"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_1965610"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1965619"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_11566"}

{:event/type "corner"
:event/elapsed 15
:event/subtype "short"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1965621"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_11566"}

{:event/type "shotoff"
:event/elapsed 17
:event/subtype "deflected"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1965625"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1965627"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_11566"}

{:event/type "corner"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1965627"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_11566"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Wesley Sneijder"
:event/subtype "obstruction"
:event/player1 "Walter Gargano"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1965630"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_11566"}

{:event/type "card"
:event/elapsed 19
:event/card_type "y"
:event/player1 "Walter Gargano"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1965631"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Marco Davide Faraoni"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1965634"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1965637"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Christian Maggio"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1965641"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1965644"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_11566"}

{:event/type "corner"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1965644"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_11566"}

{:event/type "shoton"
:event/elapsed 25
:event/subtype "shot"
:event/player1 "Blerim Dzemaili"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1965650"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1965652"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_11566"}

{:event/type "corner"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1965652"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Blerim Dzemaili"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1965654"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_11566"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Hugo Campagnaro"
:event/player1 "Diego Milito"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1965656"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Dejan Stankovic"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1965659"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_11566"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Dejan Stankovic"
:event/player1 "Juan Camilo Zuniga"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1965661"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_11566"}

{:event/type "foulcommit"
:event/elapsed 29
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1965664"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_11566"}

{:event/type "shotoff"
:event/elapsed 29
:event/subtype "header"
:event/player1 "Edinson Cavani"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1965666"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1965677"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Gokhan Inler"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1965686"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_1965698"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_11566"}

{:event/type "corner"
:event/elapsed 42
:event/subtype "short"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1965703"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1965705"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_11566"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Diego Milito"
:event/subtype "dangerous_play"
:event/player1 "Paolo Cannavaro"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1965707"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_11566"}

{:event/type "shotoff"
:event/elapsed 43
:event/subtype "indirect freekick"
:event/player1 "Wesley Sneijder"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1965712"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_11566"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Marco Davide Faraoni"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1965714"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_11566"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player1 "Diego Milito"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1965722"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_11566"}

{:event/type "card"
:event/elapsed 45
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Diego Milito"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_1965723"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_11566"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Christian Maggio"
:event/player1 "Giampaolo Pazzini"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1965788"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_11566"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Walter Samuel"
:event/subtype "dangerous_play"
:event/player1 "Edinson Cavani"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1965790"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_11566"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Ezequiel Lavezzi"
:event/player1 "Walter Samuel"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1965794"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_11566"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Yuto Nagatomo"
:event/player1 "Christian Maggio"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1965800"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Esteban Cambiasso"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1965804"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_11566"}

{:event/type "shoton"
:event/elapsed 51
:event/subtype "blocked_shot"
:event/player1 "Dejan Stankovic"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1965806"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Marco Davide Faraoni"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1965809"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Juan Camilo Zuniga"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1965814"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_11566"}

{:event/type "shotoff"
:event/elapsed 52
:event/subtype "header"
:event/player1 "Christian Maggio"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1965815"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1965822"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_11566"}

{:event/type "corner"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1965822"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_11566"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player1 "Walter Gargano"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1965844"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_11566"}

{:event/type "foulcommit"
:event/elapsed 59
:event/player1 "Christian Maggio"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1965851"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_11566"}

{:event/type "goal"
:event/elapsed 59
:event/player2 "Blerim Dzemaili"
:event/subtype "shot"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 3
:event/team "home"
:event/id "event_1965853"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_11566"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Giampaolo Pazzini"
:event/player1 "Hugo Campagnaro"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1965859"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1965866"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_11566"}

{:event/type "corner"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1965866"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_11566"}

{:event/type "shotoff"
:event/elapsed 64
:event/subtype "shot"
:event/player1 "Edinson Cavani"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1965868"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_11566"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Christian Maggio"
:event/player1 "Yuto Nagatomo"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1965877"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_11566"}

{:event/type "shotoff"
:event/elapsed 66
:event/subtype "distance"
:event/player1 "Gokhan Inler"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1965879"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_11566"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Edinson Cavani"
:event/subtype "serious_foul"
:event/player1 "Ivan Cordoba"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1965884"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_11566"}

{:event/type "card"
:event/elapsed 67
:event/card_type "y"
:event/player1 "Ivan Cordoba"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_1965885"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_11566"}

{:event/type "shotoff"
:event/elapsed 69
:event/subtype "bad shot"
:event/player1 "Gokhan Inler"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1965891"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Hugo Campagnaro"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1965898"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_11566"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Juan Camilo Zuniga"
:event/subtype "shirt_pull"
:event/player1 "Marco Davide Faraoni"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1965901"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_11566"}

{:event/type "card"
:event/elapsed 70
:event/card_type "y"
:event/player1 "Marco Davide Faraoni"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_1965903"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_11566"}

{:event/type "corner"
:event/elapsed 71
:event/subtype "short"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1965912"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Walter Gargano"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1965913"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_11566"}

{:event/type "shotoff"
:event/elapsed 71
:event/subtype "header"
:event/player1 "Blerim Dzemaili"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1965915"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Yuto Nagatomo"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1965922"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_11566"}

{:event/type "shotoff"
:event/elapsed 72
:event/subtype "volley"
:event/player1 "Giampaolo Pazzini"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1965923"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Blerim Dzemaili"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1965927"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Yuto Nagatomo"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1965936"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Marco Davide Faraoni"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1965941"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_11566"}

{:event/type "foulcommit"
:event/elapsed 76
:event/player2 "Christian Maggio"
:event/player1 "Yuto Nagatomo"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1965944"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_11566"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Blerim Dzemaili"
:event/subtype "shirt_pull"
:event/player1 "Andrea Poli"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1965947"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_11566"}

{:event/type "card"
:event/elapsed 77
:event/card_type "y"
:event/player1 "Andrea Poli"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_1965948"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1965949"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_11566"}

{:event/type "corner"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1965949"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_11566"}

{:event/type "foulcommit"
:event/elapsed 79
:event/player2 "Giampaolo Pazzini"
:event/subtype "serious_foul"
:event/player1 "Salvatore Aronica"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1965952"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_11566"}

{:event/type "card"
:event/elapsed 79
:event/card_type "r"
:event/subtype "emergency_brake"
:event/player1 "Salvatore Aronica"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_1965954"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_11566"}

{:event/type "shoton"
:event/elapsed 80
:event/subtype "direct_freekick"
:event/player1 "Esteban Cambiasso"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1965958"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_11566"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Ezequiel Lavezzi"
:event/player1 "Ivan Cordoba"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1965961"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_11566"}

{:event/type "shotoff"
:event/elapsed 81
:event/subtype "direct_freekick"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1965965"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_11566"}

{:event/type "foulcommit"
:event/elapsed 83
:event/player1 "Andrea Poli"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1965974"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_11566"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Lucio"
:event/player1 "Blerim Dzemaili"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1965979"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_11566"}

{:event/type "foulcommit"
:event/elapsed 87
:event/player2 "Lucio"
:event/player1 "Edinson Cavani"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1965991"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Yuto Nagatomo"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1966002"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_11566"}

{:event/type "shotoff"
:event/elapsed 88
:event/subtype "big chance header"
:event/player1 "Giampaolo Pazzini"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1966003"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_11566"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1966013"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_11566"}

{:event/type "shoton"
:event/elapsed 90
:event/subtype "blocked_shot"
:event/player1 "Edinson Cavani"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_1966021"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_11566"}

{:event/type "shotoff"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "volley"
:event/player1 "Marco Davide Faraoni"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1966029"
:event/minute 92
:event/match_id "match_11566"}

{:event/type "foulcommit"
:event/elapsed_plus 4
:event/elapsed 90
:event/player1 "Andrea Poli"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1966035"
:event/minute 94
:event/match_id "match_11566"}


]

