
;;# data
[
{:match/id "match_10763"
:match/league "Italy Serie A"
:match/hometeam "Cagliari"
:match/awayteam "Livorno"
:match/score "3:0"
:match/hometeam_goals "3"
:match/awayteam_goals "0"}

{:event/type "goal"
:event/elapsed 3
:event/player1 "Joaquin Larrivey"
:event/sortorder 0
:event/team "home"
:event/id "event_911644"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_10763"}

{:event/type "card"
:event/elapsed 30
:event/card_type "y"
:event/player1 "Cristiano Lucarelli"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_911785"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_10763"}

{:event/type "card"
:event/elapsed 39
:event/card_type "y"
:event/player1 "Andrea Parola"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_911793"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_10763"}

{:event/type "goal"
:event/elapsed 50
:event/player1 "Joaquin Larrivey"
:event/sortorder 0
:event/team "home"
:event/id "event_911926"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_10763"}

{:event/type "card"
:event/elapsed 57
:event/card_type "y"
:event/player1 "Davide Biondini"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_911949"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_10763"}

{:event/type "goal"
:event/elapsed 64
:event/player1 "Jedaias Capucho Neves"
:event/sortorder 0
:event/team "home"
:event/id "event_911959"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_10763"}

{:event/type "card"
:event/elapsed 81
:event/card_type "y"
:event/player1 "Jedaias Capucho Neves"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_912012"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_10763"}

{:event/type "card"
:event/elapsed 89
:event/card_type "y"
:event/player1 "Alfonso De Lucia"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_912094"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_10763"}


]

