
;;# data
[
{:match/id "match_10724"
:match/league "Italy Serie A"
:match/hometeam "Palermo"
:match/awayteam "Siena"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 12
:event/card_type "y"
:event/player1 "Paul Constantin Codrea"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_890070"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_10724"}

{:event/type "goal"
:event/elapsed 41
:event/player1 "Edinson Cavani"
:event/sortorder 0
:event/team "home"
:event/id "event_890243"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_10724"}

{:event/type "card"
:event/elapsed 68
:event/card_type "y"
:event/player1 "Mark Bresciano"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_890601"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_10724"}

{:event/type "card"
:event/elapsed 69
:event/card_type "y"
:event/player1 "Michele Fini"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_890616"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_10724"}

{:event/type "card"
:event/elapsed 86
:event/card_type "y"
:event/player1 "Claudio Terzi"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_890769"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_10724"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Simon Kjaer"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_890788"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_10724"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Cesare Bovo"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_890815"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_10724"}


]

