
;;# data
[
{:match/id "match_9694"
:match/league "Germany 1. Bundesliga"
:match/hometeam "Eintracht Frankfurt"
:match/awayteam "SV Werder Bremen"
:match/score "5:2"
:match/hometeam_goals "5"
:match/awayteam_goals "2"}

{:event/type "foulcommit"
:event/elapsed 1
:event/player2 "Santiago Garcia"
:event/subtype "trip"
:event/player1 "Haris Seferovic"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3996754"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_9694"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "Makoto Hasebe"
:event/subtype "trip"
:event/player1 "Davie Selke"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3996781"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_9694"}

{:event/type "shoton"
:event/elapsed 3
:event/subtype "shot"
:event/player1 "Clemens Fritz"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3996791"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_9694"}

{:event/type "foulcommit"
:event/elapsed 6
:event/player2 "Stefan Aigner"
:event/subtype "dangerous_play"
:event/player1 "Assani Lukimya-Mulongoti"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3996838"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Marc Stendera"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3996843"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_3996873"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Levent Aycicek"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3996880"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Takashi Inui"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_3996885"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Haris Seferovic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3996892"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_3996913"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Timothy Chandler"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3996928"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_9694"}

{:event/type "corner"
:event/elapsed 12
:event/subtype "cross_right"
:event/player1 "Marc Stendera"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3996936"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Clemens Fritz"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3996961"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_9694"}

{:event/type "corner"
:event/elapsed 14
:event/subtype "cross_right"
:event/player1 "Zlatko Junuzovic"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3996973"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_9694"}

{:event/type "shoton"
:event/elapsed 14
:event/subtype "header"
:event/player1 "Sebastian Proedl"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_3996976"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_9694"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Santiago Garcia"
:event/subtype "trip"
:event/player1 "Stefan Aigner"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3996990"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_3997004"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_9694"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Marc Stendera"
:event/subtype "trip"
:event/player1 "Santiago Garcia"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3997013"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_9694"}

{:event/type "shoton"
:event/elapsed 17
:event/subtype "deflected"
:event/player1 "Haris Seferovic"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3997021"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_9694"}

{:event/type "corner"
:event/elapsed 17
:event/subtype "cross_left"
:event/player1 "Bastian Oczipka"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3997024"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Bastian Oczipka"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3997038"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_9694"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Haris Seferovic"
:event/subtype "trip"
:event/player1 "Sebastian Proedl"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3997043"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_9694"}

{:event/type "shoton"
:event/elapsed 20
:event/subtype "indirect freekick"
:event/player1 "Alexander Meier"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3997054"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_9694"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Marc Stendera"
:event/subtype "trip"
:event/player1 "Sebastian Proedl"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3997057"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_9694"}

{:event/type "card"
:event/elapsed 21
:event/card_type "y"
:event/player1 "Sebastian Proedl"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_3997059"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Stefan Aigner"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3997068"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Stefan Aigner"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3997072"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_9694"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Stefan Aigner"
:event/subtype "trip"
:event/player1 "Santiago Garcia"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3997083"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Marc Stendera"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3997090"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_9694"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Alexander Meier"
:event/subtype "trip"
:event/player1 "Clemens Fritz"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3997105"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_3997120"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_9694"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Luca Caldirola"
:event/subtype "trip"
:event/player1 "Haris Seferovic"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3997122"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_9694"}

{:event/type "shotoff"
:event/elapsed 29
:event/subtype "deflected"
:event/player1 "Fin Bartels"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3997124"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Haris Seferovic"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3997125"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_9694"}

{:event/type "shotoff"
:event/elapsed 30
:event/subtype "deflected"
:event/player1 "Takashi Inui"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3997127"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_9694"}

{:event/type "corner"
:event/elapsed 30
:event/subtype "cross_left"
:event/player1 "Marc Stendera"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3997128"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_9694"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Zlatko Junuzovic"
:event/subtype "pull"
:event/player1 "Takashi Inui"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3997132"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_9694"}

{:event/type "card"
:event/elapsed 31
:event/card_type "y"
:event/subtype "emergency_brake"
:event/player1 "Takashi Inui"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_3997134"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Timothy Chandler"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3997143"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_9694"}

{:event/type "shotoff"
:event/elapsed 33
:event/subtype "crossbar"
:event/player1 "Takashi Inui"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3997148"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_9694"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Marc Stendera"
:event/subtype "dangerous_play"
:event/player1 "Felix Kroos"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3997149"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_9694"}

{:event/type "shotoff"
:event/elapsed 34
:event/subtype "crossbar"
:event/player1 "Marc Stendera"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3997162"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_9694"}

{:event/type "goal"
:event/elapsed 34
:event/subtype "shot"
:event/player1 "Alexander Meier"
:event/sortorder 1
:event/team "home"
:event/id "event_3997155"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_9694"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Zlatko Junuzovic"
:event/subtype "trip"
:event/player1 "Stefan Aigner"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3997183"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_9694"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Santiago Garcia"
:event/subtype "trip"
:event/player1 "Stefan Aigner"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3997204"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Theodor Gebre Selassie"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3997213"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/sortorder 1
:event/team "away"
:event/event_type "throwin"
:event/id "event_3997215"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Luca Caldirola"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3997216"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_9694"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Clemens Fritz"
:event/subtype "pull"
:event/player1 "Marc Stendera"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3997219"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Santiago Garcia"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3997221"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Timothy Chandler"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3997241"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/sortorder 3
:event/team "home"
:event/event_type "throwin"
:event/id "event_3997244"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Timothy Chandler"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3997247"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_9694"}

{:event/type "corner"
:event/elapsed 42
:event/subtype "cross_right"
:event/player1 "Bastian Oczipka"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3997251"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_9694"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Luca Caldirola"
:event/subtype "trip"
:event/player1 "Stefan Aigner"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3997260"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_9694"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Clemens Fritz"
:event/subtype "from_behind"
:event/player1 "Haris Seferovic"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3997269"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_9694"}

{:event/type "corner"
:event/elapsed 45
:event/subtype "cross_left"
:event/player1 "Zlatko Junuzovic"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3997288"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_9694"}

{:event/type "goal"
:event/elapsed 45
:event/player2 "Zlatko Junuzovic"
:event/subtype "header"
:event/player1 "Theodor Gebre Selassie"
:event/sortorder 1
:event/team "away"
:event/id "event_3997290"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_9694"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "distance"
:event/player1 "Haris Seferovic"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3997300"
:event/minute 46
:event/match_id "match_9694"}

{:event/type "corner"
:event/elapsed 47
:event/subtype "cross_right"
:event/player1 "Bastian Oczipka"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3997545"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_9694"}

{:event/type "corner"
:event/elapsed 48
:event/subtype "cross_right"
:event/player1 "Bastian Oczipka"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3997552"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_9694"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Santiago Garcia"
:event/subtype "trip"
:event/player1 "Marc Stendera"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3997555"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Zlatko Junuzovic"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3997565"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Bastian Oczipka"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3997595"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_9694"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Timothy Chandler"
:event/subtype "trip"
:event/player1 "Fin Bartels"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3997603"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Takashi Inui"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3997607"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_9694"}

{:event/type "goal"
:event/elapsed 52
:event/player2 "Takashi Inui"
:event/subtype "tap_in"
:event/player1 "Haris Seferovic"
:event/sortorder 2
:event/team "home"
:event/id "event_3997609"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Bastian Oczipka"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3997658"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Bastian Oczipka"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3997669"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_9694"}

{:event/type "corner"
:event/elapsed 57
:event/subtype "cross_left"
:event/player1 "Takashi Inui"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_3997674"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_9694"}

{:event/type "corner"
:event/elapsed 59
:event/subtype "cross_left"
:event/player1 "Takashi Inui"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3997702"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Haris Seferovic"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_3997711"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_9694"}

{:event/type "shoton"
:event/elapsed 60
:event/subtype "header"
:event/player1 "Anderson"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3997715"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Timothy Chandler"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3997722"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_9694"}

{:event/type "shoton"
:event/elapsed 60
:event/subtype "header"
:event/player1 "Alexander Meier"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_3997725"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/sortorder 4
:event/team "away"
:event/event_type "throwin"
:event/id "event_3997733"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Santiago Garcia"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3997776"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_3997778"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_9694"}

{:event/type "shoton"
:event/elapsed 64
:event/subtype "deflected"
:event/player1 "Fin Bartels"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3997780"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_9694"}

{:event/type "corner"
:event/elapsed 65
:event/subtype "cross_right"
:event/player1 "Marc Stendera"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3997790"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_9694"}

{:event/type "shotoff"
:event/elapsed 65
:event/subtype "crossbar"
:event/player1 "Anderson"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3997792"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_3997801"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Santiago Garcia"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3997802"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_9694"}

{:event/type "shoton"
:event/elapsed 66
:event/subtype "distance"
:event/player1 "Felix Kroos"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_3997805"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_9694"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Clemens Fritz"
:event/subtype "trip"
:event/player1 "Marc Stendera"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3997812"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_9694"}

{:event/type "shoton"
:event/elapsed 68
:event/subtype "shot"
:event/player1 "Stefan Aigner"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3997827"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_9694"}

{:event/type "goal"
:event/elapsed 68
:event/subtype "shot"
:event/player1 "Alexander Meier"
:event/sortorder 2
:event/team "home"
:event/id "event_3997830"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_9694"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Santiago Garcia"
:event/subtype "trip"
:event/player1 "Stefan Aigner"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3997849"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Bastian Oczipka"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3997857"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_9694"}

{:event/type "shoton"
:event/elapsed 72
:event/subtype "bicycle_kick"
:event/player1 "Stefan Aigner"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3997860"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_9694"}

{:event/type "foulcommit"
:event/elapsed 72
:event/player2 "Luca Caldirola"
:event/subtype "trip"
:event/player1 "Haris Seferovic"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3997868"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_9694"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Timothy Chandler"
:event/subtype "trip"
:event/player1 "Santiago Garcia"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3997872"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Stefan Aigner"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3997876"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Bastian Oczipka"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3997907"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_9694"}

{:event/type "goal"
:event/elapsed 76
:event/player2 "Bastian Oczipka"
:event/subtype "shot"
:event/player1 "Stefan Aigner"
:event/sortorder 1
:event/team "home"
:event/id "event_3997908"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_9694"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Zlatko Junuzovic"
:event/subtype "trip"
:event/player1 "Makoto Hasebe"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3997926"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Zlatko Junuzovic"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3997930"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_9694"}

{:event/type "foulcommit"
:event/elapsed 78
:event/player2 "Theodor Gebre Selassie"
:event/subtype "trip"
:event/player1 "Marco Russ"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3997946"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Zlatko Junuzovic"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3997950"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_9694"}

{:event/type "goal"
:event/elapsed 79
:event/player2 "Fin Bartels"
:event/subtype "shot"
:event/player1 "Luca Caldirola"
:event/sortorder 2
:event/team "away"
:event/id "event_3997959"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Stefan Aigner"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3997971"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_9694"}

{:event/type "goal"
:event/elapsed 80
:event/player2 "Takashi Inui"
:event/subtype "distance"
:event/player1 "Marc Stendera"
:event/sortorder 1
:event/team "home"
:event/id "event_3997973"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_9694"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Slobodan Medojevic"
:event/subtype "pull"
:event/player1 "Zlatko Junuzovic"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3998051"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_9694"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Fin Bartels"
:event/subtype "trip"
:event/player1 "Timothy Chandler"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3998089"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_9694"}

{:event/type "card"
:event/elapsed 85
:event/card_type "y"
:event/player1 "Timothy Chandler"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_3998060"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_9694"}

{:event/type "foulcommit"
:event/elapsed 86
:event/subtype "hands"
:event/player1 "Haris Seferovic"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3998066"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_9694"}

{:event/type "shotoff"
:event/elapsed 87
:event/subtype "deflected"
:event/player1 "Levent Aycicek"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3998084"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_9694"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/sortorder 2
:event/team "away"
:event/event_type "throwin"
:event/id "event_3998101"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_9694"}

{:event/type "shotoff"
:event/elapsed 88
:event/subtype "crossbar"
:event/player1 "Zlatko Junuzovic"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3998104"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_9694"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Haris Seferovic"
:event/subtype "trip"
:event/player1 "Clemens Fritz"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3998142"
:event/minute 91
:event/match_id "match_9694"}

{:event/type "card"
:event/elapsed_plus 2
:event/elapsed 90
:event/card_type "y"
:event/player1 "Clemens Fritz"
:event/sortorder 5
:event/team "away"
:event/event_type "card"
:event/id "event_3998167"
:event/minute 92
:event/match_id "match_9694"}

{:event/type "shoton"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Sonny Kittel"
:event/sortorder 7
:event/team "home"
:event/event_type "shoton"
:event/id "event_3998175"
:event/minute 93
:event/match_id "match_9694"}


]

