
;;# data
[
{:match/id "match_3036"
:match/league "England Premier League"
:match/hometeam "Stoke City"
:match/awayteam "Sunderland"
:match/score "0:1"
:match/hometeam_goals "0"
:match/awayteam_goals "1"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/sortorder 3
:event/team "home"
:event/event_type "throwin"
:event/id "event_1915531"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_3036"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Jack Colback"
:event/player1 "Jermaine Pennant"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1915536"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1915556"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_3036"}

{:event/type "corner"
:event/elapsed 8
:event/subtype "short"
:event/player1 "Jermaine Pennant"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1915619"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1915621"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_3036"}

{:event/type "shoton"
:event/elapsed 8
:event/subtype "blocked_shot"
:event/player1 "Marc Wilson"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1915624"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1915652"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3036"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Jermaine Pennant"
:event/player1 "David Meyler"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1915742"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1915763"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_3036"}

{:event/type "corner"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1915763"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Glenn Whelan"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1915765"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1915791"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3036"}

{:event/type "corner"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1915791"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3036"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Craig Gardner"
:event/player1 "Glenn Whelan"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1915799"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_3036"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Stephane Sessegnon"
:event/subtype "advantage"
:event/player1 "Robert Huth"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1915824"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_1915852"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_3036"}

{:event/type "shoton"
:event/elapsed 25
:event/subtype "blocked_shot"
:event/player1 "Craig Gardner"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1915884"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3036"}

{:event/type "shoton"
:event/elapsed 25
:event/subtype "blocked_shot"
:event/player1 "Stephane Sessegnon"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1915887"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3036"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Jack Colback"
:event/player1 "Glenn Whelan"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1915894"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Jonathan Walters"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1915907"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Sebastian Larsson"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1915935"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_3036"}

{:event/type "corner"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Sebastian Larsson"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1915935"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_3036"}

{:event/type "shotoff"
:event/elapsed 30
:event/subtype "distance"
:event/player1 "Stephane Sessegnon"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1915944"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Marc Wilson"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1915994"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3036"}

{:event/type "foulcommit"
:event/elapsed 36
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1916031"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "James McClean"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1916046"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_3036"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Jack Colback"
:event/player1 "Robert Huth"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1916070"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Kieran Richardson"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1916088"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_3036"}

{:event/type "corner"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Kieran Richardson"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1916088"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Phil Bardsley"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1916111"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3036"}

{:event/type "shoton"
:event/elapsed 41
:event/subtype "distance"
:event/player1 "Jonathan Walters"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1916124"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Phil Bardsley"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1916154"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_3036"}

{:event/type "foulcommit"
:event/elapsed 44
:event/subtype "hands"
:event/player1 "Craig Gardner"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1916164"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_3036"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "David Meyler"
:event/subtype "dangerous_play"
:event/player1 "Robert Huth"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1916181"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_3036"}

{:event/type "card"
:event/elapsed 45
:event/card_type "r"
:event/player1 "Robert Huth"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_1916185"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Kieran Richardson"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1916332"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_3036"}

{:event/type "corner"
:event/elapsed 47
:event/subtype "short"
:event/player1 "James McClean"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1916343"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "James McClean"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1916344"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_3036"}

{:event/type "shotoff"
:event/elapsed 47
:event/subtype "header"
:event/player1 "Stephane Sessegnon"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1916346"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_3036"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "David Meyler"
:event/player1 "Ricardo Fuller"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1916402"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3036"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Jonathan Walters"
:event/player1 "John O'Shea"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1916417"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_3036"}

{:event/type "card"
:event/elapsed 52
:event/card_type "y"
:event/subtype "verbal_abuse"
:event/player1 "John O'Shea"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1916420"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_3036"}

{:event/type "shotoff"
:event/elapsed 52
:event/subtype "deflected"
:event/player1 "Marc Wilson"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1916434"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Glenn Whelan"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1916442"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_3036"}

{:event/type "corner"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Glenn Whelan"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1916442"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_3036"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Peter Crouch"
:event/subtype "pushing"
:event/player1 "Michael Turner"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1916458"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_1916469"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Sebastian Larsson"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1916478"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "James McClean"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_1916480"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3036"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Jack Colback"
:event/player1 "Rory Delap"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1916509"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "James McClean"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1916517"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Kieran Richardson"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1916523"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Sebastian Larsson"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1916526"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3036"}

{:event/type "corner"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Sebastian Larsson"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1916526"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Marc Wilson"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_1916537"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3036"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player1 "Jonathan Woodgate"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1916561"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_3036"}

{:event/type "goal"
:event/elapsed 60
:event/player2 "Stephane Sessegnon"
:event/subtype "shot"
:event/player1 "James McClean"
:event/sortorder 2
:event/team "away"
:event/id "event_1916567"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_1916590"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_1916603"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3036"}

{:event/type "shotoff"
:event/elapsed 64
:event/subtype "distance"
:event/player1 "Rory Delap"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1916606"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_3036"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Peter Crouch"
:event/player1 "Michael Turner"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1916618"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_3036"}

{:event/type "foulcommit"
:event/elapsed 66
:event/player2 "Ricardo Fuller"
:event/player1 "Michael Turner"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1916632"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_1916647"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3036"}

{:event/type "shotoff"
:event/elapsed 68
:event/subtype "shot"
:event/player1 "Jonathan Walters"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1916667"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_1916709"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_3036"}

{:event/type "shoton"
:event/elapsed 71
:event/subtype "header"
:event/player1 "Peter Crouch"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1916725"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "James McClean"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1916766"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Sebastian Larsson"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1916775"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3036"}

{:event/type "corner"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Sebastian Larsson"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1916775"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_1916811"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_3036"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Phil Bardsley"
:event/player1 "Ricardo Fuller"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1916850"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_3036"}

{:event/type "shoton"
:event/elapsed 82
:event/subtype "shot"
:event/player1 "Ricardo Fuller"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1916878"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Ryan Shotton"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1916934"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_1916993"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3036"}

{:event/type "shotoff"
:event/elapsed 90
:event/subtype "deflected"
:event/player1 "Marc Wilson"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1916997"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Glenn Whelan"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1917000"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3036"}

{:event/type "corner"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Glenn Whelan"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1917000"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3036"}

{:event/type "shotoff"
:event/elapsed 90
:event/subtype "header"
:event/player1 "Peter Crouch"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1917002"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3036"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Stephane Sessegnon"
:event/player1 "Rory Delap"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1917027"
:event/minute 92
:event/match_id "match_3036"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_1917042"
:event/minute 93
:event/match_id "match_3036"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Michael Turner"
:event/player1 "Peter Crouch"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1917045"
:event/minute 93
:event/match_id "match_3036"}


]

