
;;# data
[
{:match/id "match_12504"
:match/league "Italy Serie A"
:match/hometeam "Torino"
:match/awayteam "Inter"
:match/score "4:3"
:match/hometeam_goals "3"
:match/awayteam_goals "3"}

{:event/type "card"
:event/elapsed 5
:event/card_type "r"
:event/player1 "Samir Handanovic"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3077227"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_12504"}

{:event/type "goal"
:event/elapsed 7
:event/player1 "Alessio Cerci"
:event/sortorder 0
:event/team "home"
:event/id "event_3077225"
:event/event_type "goal"
:event/goal_type "npm"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_12504"}

{:event/type "goal"
:event/elapsed 21
:event/player1 "Alexander Farnerud"
:event/sortorder 0
:event/team "home"
:event/id "event_3077234"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_12504"}

{:event/type "card"
:event/elapsed 26
:event/card_type "y"
:event/player1 "Saphir Taider"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3077235"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_12504"}

{:event/type "card"
:event/elapsed 33
:event/card_type "y"
:event/player1 "Alessandro Gazzi"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3077237"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_12504"}

{:event/type "card"
:event/elapsed 37
:event/card_type "y"
:event/player1 "Alexander Farnerud"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3077238"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_12504"}

{:event/type "goal"
:event/elapsed 45
:event/player1 "Fredy Guarin"
:event/sortorder 0
:event/team "away"
:event/id "event_3077240"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_12504"}

{:event/type "goal"
:event/elapsed 53
:event/player1 "Ciro Immobile"
:event/sortorder 0
:event/team "home"
:event/id "event_3077252"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_12504"}

{:event/type "goal"
:event/elapsed 55
:event/player1 "Rodrigo Palacio"
:event/sortorder 0
:event/team "away"
:event/id "event_3077253"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_12504"}

{:event/type "goal"
:event/elapsed 71
:event/player1 "Rodrigo Palacio"
:event/sortorder 0
:event/team "away"
:event/id "event_3077257"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_12504"}

{:event/type "card"
:event/elapsed 78
:event/card_type "y"
:event/player1 "Esteban Cambiasso"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3077262"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_12504"}

{:event/type "card"
:event/elapsed 80
:event/card_type "y"
:event/player1 "Ciro Immobile"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_3077265"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_12504"}

{:event/type "goal"
:event/elapsed 90
:event/player1 "Nicola Bellomo"
:event/sortorder 0
:event/team "home"
:event/id "event_3077271"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_12504"}


]

