
;;# data
[
{:match/id "match_2725"
:match/league "England Premier League"
:match/hometeam "West Bromwich Albion"
:match/awayteam "Arsenal"
:match/score "2:2"
:match/hometeam_goals "2"
:match/awayteam_goals "2"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 5
:event/team "home"
:event/event_type "corner"
:event/id "event_1464483"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_2725"}

{:event/type "corner"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 5
:event/team "home"
:event/event_type "corner"
:event/id "event_1464483"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_2725"}

{:event/type "goal"
:event/elapsed 3
:event/player2 "Chris Brunt"
:event/subtype "header"
:event/player1 "Steven Reid"
:event/sortorder 10
:event/team "home"
:event/id "event_1464423"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_2725"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Bacary Sagna"
:event/player1 "Jerome Thomas"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1464458"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Jerome Thomas"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1464476"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Robin van Persie"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1464491"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_2725"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Andrey Arshavin"
:event/player1 "Paul Scharner"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1464606"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Samir Nasri"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1464663"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_2725"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Robin van Persie"
:event/subtype "from_behind"
:event/player1 "Abdoulaye Meite"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1464670"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_2725"}

{:event/type "card"
:event/elapsed 18
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Abdoulaye Meite"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_1464672"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Samir Nasri"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1464687"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_2725"}

{:event/type "corner"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Samir Nasri"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1464687"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Gael Clichy"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1464742"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_2725"}

{:event/type "shoton"
:event/elapsed 24
:event/subtype "shot"
:event/player1 "Andrey Arshavin"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_1464751"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Samir Nasri"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1464766"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Gael Clichy"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1464775"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_2725"}

{:event/type "shotoff"
:event/elapsed 26
:event/subtype "crossbar"
:event/player1 "Robin van Persie"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1464777"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_2725"}

{:event/type "shoton"
:event/elapsed 26
:event/subtype "big chance shot"
:event/player1 "Aaron Ramsey"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1464781"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Gael Clichy"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1464782"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_2725"}

{:event/type "shotoff"
:event/elapsed 26
:event/subtype "shot"
:event/player1 "Denilson"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1464787"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1464799"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Robin van Persie"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1464806"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Gael Clichy"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1464810"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_2725"}

{:event/type "shoton"
:event/elapsed 28
:event/subtype "shot"
:event/player1 "Jack Wilshere"
:event/sortorder 4
:event/team "away"
:event/event_type "shoton"
:event/id "event_1464816"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Andrey Arshavin"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1464823"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Samir Nasri"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1464829"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2725"}

{:event/type "corner"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Samir Nasri"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1464829"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Samir Nasri"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1464833"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_2725"}

{:event/type "corner"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Samir Nasri"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1464833"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_2725"}

{:event/type "foulcommit"
:event/elapsed 30
:event/player1 "Paul Scharner"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1464849"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_2725"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Jerome Thomas"
:event/player1 "Bacary Sagna"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1464872"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Samir Nasri"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1464917"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "James Morrison"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1464942"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_2725"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Jerome Thomas"
:event/player1 "Denilson"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1464970"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_2725"}

{:event/type "card"
:event/elapsed 37
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Denilson"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1464974"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_2725"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Paul Scharner"
:event/player1 "Andrey Arshavin"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1465060"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Nicky Shorey"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1465137"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Gael Clichy"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1465371"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_2725"}

{:event/type "shotoff"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "shot"
:event/player1 "Robin van Persie"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1465205"
:event/minute 47
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Bacary Sagna"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1465214"
:event/minute 48
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Gael Clichy"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1465401"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_2725"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "hands"
:event/player1 "Nicky Shorey"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1465216"
:event/minute 48
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed_plus 5
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Bacary Sagna"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1465237"
:event/minute 50
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Andrey Arshavin"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1465489"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_2725"}

{:event/type "shoton"
:event/elapsed 53
:event/subtype "header"
:event/player1 "Marouane Chamakh"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1465490"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_2725"}

{:event/type "shotoff"
:event/elapsed 55
:event/subtype "big chance shot"
:event/player1 "Chris Brunt"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1465535"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_2725"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Youssuf Mulumbu"
:event/player1 "Robin van Persie"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1465540"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Gael Clichy"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1465565"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Aaron Ramsey"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1465571"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_2725"}

{:event/type "shotoff"
:event/elapsed 57
:event/subtype "header"
:event/player1 "Robin van Persie"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1465574"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_2725"}

{:event/type "goal"
:event/elapsed 58
:event/player2 "Youssuf Mulumbu"
:event/subtype "shot"
:event/player1 "Peter Odemwingie"
:event/sortorder 2
:event/team "home"
:event/id "event_1465616"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Marouane Chamakh"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1465639"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_2725"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Peter Odemwingie"
:event/player1 "Laurent Koscielny"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1465665"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_2725"}

{:event/type "card"
:event/elapsed 61
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Laurent Koscielny"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1465668"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_2725"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player1 "Jerome Thomas"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1465698"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Samir Nasri"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1465718"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_2725"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Jack Wilshere"
:event/player1 "Steven Reid"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1465756"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_2725"}

{:event/type "foulcommit"
:event/elapsed 66
:event/player2 "Steven Reid"
:event/player1 "Andrey Arshavin"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1465769"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_2725"}

{:event/type "foulcommit"
:event/elapsed 66
:event/player2 "Marouane Chamakh"
:event/player1 "James Morrison"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1465780"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_2725"}

{:event/type "shotoff"
:event/elapsed 67
:event/subtype "direct_freekick"
:event/player1 "Robin van Persie"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1465798"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_2725"}

{:event/type "shoton"
:event/elapsed 68
:event/subtype "blocked_shot"
:event/player1 "Andrey Arshavin"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1465814"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Samir Nasri"
:event/sortorder 9
:event/team "away"
:event/event_type "cross"
:event/id "event_1465855"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Robin van Persie"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1465830"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_2725"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Bacary Sagna"
:event/player1 "Marek Cech"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1465845"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_2725"}

{:event/type "goal"
:event/elapsed 70
:event/player2 "Marouane Chamakh"
:event/subtype "shot"
:event/player1 "Andrey Arshavin"
:event/sortorder 10
:event/team "away"
:event/id "event_1465858"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Robin van Persie"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1465880"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Bacary Sagna"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1465928"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Gael Clichy"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1465929"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Marc-Antoine Fortune"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1465948"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Andrey Arshavin"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1465960"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1465986"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_2725"}

{:event/type "goal"
:event/elapsed 78
:event/subtype "shot"
:event/player1 "Robin van Persie"
:event/sortorder 1
:event/team "away"
:event/id "event_1465990"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_2725"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Laurent Koscielny"
:event/player1 "Marc-Antoine Fortune"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1466017"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_2725"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Marouane Chamakh"
:event/player1 "Youssuf Mulumbu"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1466021"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_2725"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Steven Reid"
:event/player1 "Samir Nasri"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1466045"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_2725"}

{:event/type "card"
:event/elapsed 81
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Samir Nasri"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1466048"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_2725"}

{:event/type "shoton"
:event/elapsed 82
:event/subtype "deflected"
:event/player1 "Marc-Antoine Fortune"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1466065"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1466073"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_2725"}

{:event/type "corner"
:event/elapsed 83
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1466073"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Samir Nasri"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_1466089"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_2725"}

{:event/type "corner"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Samir Nasri"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_1466089"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_2725"}

{:event/type "shotoff"
:event/elapsed 84
:event/subtype "header"
:event/player1 "Robin van Persie"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1466092"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Gael Clichy"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1466132"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_2725"}

{:event/type "shoton"
:event/elapsed 85
:event/subtype "header"
:event/player1 "Robin van Persie"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_1466134"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_2725"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Andrey Arshavin"
:event/subtype "from_behind"
:event/player1 "Youssuf Mulumbu"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1466190"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Samir Nasri"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1466210"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_2725"}

{:event/type "corner"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Samir Nasri"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1466210"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Jack Wilshere"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1466215"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Andrey Arshavin"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1466239"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_2725"}

{:event/type "shotoff"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Jack Wilshere"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1466260"
:event/minute 92
:event/match_id "match_2725"}

{:event/type "shoton"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "volley"
:event/player1 "Gael Clichy"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1466272"
:event/minute 94
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Samir Nasri"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1466275"
:event/minute 94
:event/match_id "match_2725"}

{:event/type "corner"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Samir Nasri"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1466275"
:event/minute 94
:event/match_id "match_2725"}

{:event/type "shoton"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "blocked_shot"
:event/player1 "Samir Nasri"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1466276"
:event/minute 94
:event/match_id "match_2725"}

{:event/type "shoton"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "deflected"
:event/player1 "Bacary Sagna"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1466278"
:event/minute 95
:event/match_id "match_2725"}

{:event/type "cross"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Samir Nasri"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1466279"
:event/minute 95
:event/match_id "match_2725"}

{:event/type "corner"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Samir Nasri"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1466279"
:event/minute 95
:event/match_id "match_2725"}


]

