
;;# data
[
{:match/id "match_10194"
:match/league "Germany 1. Bundesliga"
:match/hometeam "FC Bayern Munich"
:match/awayteam "Hannover 96"
:match/score "3:1"
:match/hometeam_goals "3"
:match/awayteam_goals "1"}

{:event/type "shotoff"
:event/elapsed 1
:event/subtype "distance"
:event/player1 "Felix Klaus"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5603908"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_10194"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Miiko Albornoz"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5603954"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_10194"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Miiko Albornoz"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_5603962"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_10194"}

{:event/type "corner"
:event/elapsed 4
:event/subtype "short_left"
:event/player1 "Felix Klaus"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_5603966"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_10194"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Kingsley Coman"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5603973"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_10194"}

{:event/type "corner"
:event/elapsed 4
:event/subtype "cross_right"
:event/player1 "Franck Ribery"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_5603977"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_10194"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Franck Ribery"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5603985"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_10194"}

{:event/type "foulcommit"
:event/elapsed 6
:event/player2 "Kingsley Coman"
:event/subtype "trip"
:event/player1 "Edgar Prib"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5604014"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_10194"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Philipp Lahm"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5604051"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_10194"}

{:event/type "shotoff"
:event/elapsed 8
:event/subtype "header"
:event/player1 "Kingsley Coman"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5604054"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_10194"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Jerome Boateng"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_5604065"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_10194"}

{:event/type "shoton"
:event/elapsed 8
:event/subtype "volley"
:event/player1 "Robert Lewandowski"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_5604066"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_10194"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Franck Ribery"
:event/player1 "Fynn Arkenberg"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5604116"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_10194"}

{:event/type "shotoff"
:event/elapsed 12
:event/subtype "shot"
:event/player1 "Arturo Vidal"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5604135"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_10194"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Kingsley Coman"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5604151"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_10194"}

{:event/type "goal"
:event/elapsed 12
:event/subtype "deflected"
:event/player1 "Robert Lewandowski"
:event/sortorder 4
:event/team "home"
:event/id "event_5604153"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_10194"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Kingsley Coman"
:event/subtype "trip"
:event/player1 "Felix Klaus"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5604186"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_10194"}

{:event/type "shotoff"
:event/elapsed 14
:event/subtype "shot"
:event/player1 "Felix Klaus"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5604201"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_10194"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Mehdi Benatia"
:event/subtype "pushing"
:event/player1 "Manuel Schmiedebach"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5604229"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_10194"}

{:event/type "shotoff"
:event/elapsed 18
:event/subtype "deflected"
:event/player1 "Franck Ribery"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5604300"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_10194"}

{:event/type "corner"
:event/elapsed 19
:event/subtype "cross_left"
:event/player1 "Mario Goetze"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5604307"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_10194"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Jerome Boateng"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5604311"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_10194"}

{:event/type "shoton"
:event/elapsed 19
:event/subtype "distance"
:event/player1 "Franck Ribery"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_5604319"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_10194"}

{:event/type "shoton"
:event/elapsed 20
:event/subtype "lob"
:event/player1 "Mario Goetze"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_5604345"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_10194"}

{:event/type "shoton"
:event/elapsed 22
:event/subtype "shot"
:event/player1 "Felix Klaus"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_5604380"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_10194"}

{:event/type "shotoff"
:event/elapsed 22
:event/subtype "big chance shot"
:event/player1 "Iver Fossum"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5604387"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_10194"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Fynn Arkenberg"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5604400"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_10194"}

{:event/type "corner"
:event/elapsed 24
:event/subtype "cross_right"
:event/player1 "Miiko Albornoz"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_5604411"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_10194"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Franck Ribery"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5604445"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_10194"}

{:event/type "corner"
:event/elapsed 26
:event/subtype "cross_right"
:event/player1 "Thiago Alcantara"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5604453"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_10194"}

{:event/type "shotoff"
:event/elapsed 26
:event/subtype "distance"
:event/player1 "Valmir Sulejmani"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5604463"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_10194"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Kingsley Coman"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5604487"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_10194"}

{:event/type "goal"
:event/elapsed 28
:event/player2 "Kingsley Coman"
:event/subtype "lob"
:event/player1 "Mario Goetze"
:event/sortorder 1
:event/team "home"
:event/id "event_5604507"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_10194"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Franck Ribery"
:event/player1 "Waldemar Anton"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5604519"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_10194"}

{:event/type "foulcommit"
:event/elapsed 30
:event/player2 "Kingsley Coman"
:event/subtype "trip"
:event/player1 "Salif Sane"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5604522"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_10194"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Mario Goetze"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5604545"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_10194"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Thiago Alcantara"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5604551"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_10194"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Franck Ribery"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5604581"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_10194"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Edgar Prib"
:event/subtype "trip"
:event/player1 "Arturo Vidal"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5604601"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_10194"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Miiko Albornoz"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5604619"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_10194"}

{:event/type "shoton"
:event/elapsed 35
:event/subtype "shot"
:event/player1 "Robert Lewandowski"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5604644"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_10194"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Kingsley Coman"
:event/subtype "trip"
:event/player1 "Miiko Albornoz"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5604670"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_10194"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Thiago Alcantara"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5604677"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_10194"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Jerome Boateng"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5604681"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_10194"}

{:event/type "shotoff"
:event/elapsed 37
:event/subtype "big chance post"
:event/player1 "Kingsley Coman"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5604682"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_10194"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Manuel Schmiedebach"
:event/player1 "Franck Ribery"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5604689"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_10194"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Arturo Vidal"
:event/subtype "pull"
:event/player1 "Iver Fossum"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5604696"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_10194"}

{:event/type "corner"
:event/elapsed 39
:event/subtype "cross_right"
:event/player1 "Franck Ribery"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5604706"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_10194"}

{:event/type "shotoff"
:event/elapsed 39
:event/subtype "volley"
:event/player1 "Robert Lewandowski"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5604709"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_10194"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Fynn Arkenberg"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_5604720"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_10194"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Valmir Sulejmani"
:event/subtype "serious_foul"
:event/player1 "Arturo Vidal"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5604760"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_10194"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Iver Fossum"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5604771"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_10194"}

{:event/type "shoton"
:event/elapsed 42
:event/subtype "distance"
:event/player1 "Manuel Schmiedebach"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_5604778"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_10194"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Felix Klaus"
:event/subtype "dangerous_play"
:event/player1 "Philipp Lahm"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5604805"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_10194"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Felix Klaus"
:event/player1 "Mehdi Benatia"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5604826"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_10194"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Miiko Albornoz"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5604837"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_10194"}

{:event/type "shotoff"
:event/elapsed 44
:event/subtype "big chance volley"
:event/player1 "Waldemar Anton"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5604842"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_10194"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "blocked_shot"
:event/player1 "Felix Klaus"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_5604864"
:event/minute 46
:event/match_id "match_10194"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "Manuel Schmiedebach"
:event/subtype "trip"
:event/player1 "Robert Lewandowski"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5604866"
:event/minute 46
:event/match_id "match_10194"}

{:event/type "shoton"
:event/elapsed 48
:event/subtype "distance"
:event/player1 "Artur Sobiech"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_5605064"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_10194"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Salif Sane"
:event/subtype "pull"
:event/player1 "Kingsley Coman"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5605073"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_10194"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Miiko Albornoz"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5605084"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_10194"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Franck Ribery"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5605115"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_10194"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Kingsley Coman"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5605145"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_10194"}

{:event/type "corner"
:event/elapsed 54
:event/subtype "short_left"
:event/player1 "Franck Ribery"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_5605207"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_10194"}

{:event/type "goal"
:event/elapsed 54
:event/subtype "shot"
:event/player1 "Mario Goetze"
:event/sortorder 3
:event/team "home"
:event/id "event_5605214"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_10194"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Kingsley Coman"
:event/subtype "trip"
:event/player1 "Felix Klaus"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5605258"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_10194"}

{:event/type "card"
:event/elapsed 56
:event/card_type "y"
:event/subtype "emergency_brake"
:event/player1 "Felix Klaus"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_5605260"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_10194"}

{:event/type "shoton"
:event/elapsed 58
:event/subtype "shot"
:event/player1 "Kingsley Coman"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_5605291"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_10194"}

{:event/type "shoton"
:event/elapsed 59
:event/subtype "distance"
:event/player1 "Edgar Prib"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_5605320"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_10194"}

{:event/type "corner"
:event/elapsed 59
:event/subtype "cross_right"
:event/player1 "Felix Klaus"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_5605330"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_10194"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Salif Sane"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5605334"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_10194"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player2 "Edgar Prib"
:event/subtype "trip"
:event/player1 "Franck Ribery"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5605339"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_10194"}

{:event/type "shotoff"
:event/elapsed 61
:event/subtype "direct_freekick"
:event/player1 "Edgar Prib"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5605361"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_10194"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Iver Fossum"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5605407"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_10194"}

{:event/type "shotoff"
:event/elapsed 63
:event/subtype "big chance shot"
:event/player1 "Edgar Prib"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5605413"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_10194"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Miiko Albornoz"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5605455"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_10194"}

{:event/type "corner"
:event/elapsed 65
:event/subtype "cross_left"
:event/player1 "Felix Klaus"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_5605463"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_10194"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Fynn Arkenberg"
:event/subtype "pull"
:event/player1 "Franck Ribery"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5605475"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_10194"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Ceyhun Gulselam"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5605494"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_10194"}

{:event/type "goal"
:event/elapsed 66
:event/player2 "Ceyhun Gulselam"
:event/subtype "shot"
:event/player1 "Artur Sobiech"
:event/sortorder 1
:event/team "away"
:event/id "event_5605498"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_10194"}

{:event/type "shoton"
:event/elapsed 68
:event/subtype "big chance shot"
:event/player1 "Edgar Prib"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_5605526"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_10194"}

{:event/type "shotoff"
:event/elapsed 69
:event/subtype "distance"
:event/player1 "Ceyhun Gulselam"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5605566"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_10194"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Thiago Alcantara"
:event/subtype "obstruction"
:event/player1 "Iver Fossum"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5605585"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_10194"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Fynn Arkenberg"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5605624"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_10194"}

{:event/type "shotoff"
:event/elapsed 72
:event/subtype "distance"
:event/player1 "Ceyhun Gulselam"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5605634"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_10194"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "David Alaba"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_5605649"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_10194"}

{:event/type "shoton"
:event/elapsed 73
:event/subtype "distance"
:event/player1 "Philipp Lahm"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5605656"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_10194"}

{:event/type "corner"
:event/elapsed 74
:event/subtype "cross_left"
:event/player1 "Franck Ribery"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_5605679"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_10194"}

{:event/type "shotoff"
:event/elapsed 76
:event/subtype "big chance shot"
:event/player1 "Franck Ribery"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5605732"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_10194"}

{:event/type "foulcommit"
:event/elapsed 76
:event/player2 "Arturo Vidal"
:event/player1 "Artur Sobiech"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5605744"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_10194"}

{:event/type "corner"
:event/elapsed 78
:event/subtype "cross_right"
:event/player1 "Miiko Albornoz"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_5605815"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_10194"}

{:event/type "shotoff"
:event/elapsed 78
:event/subtype "header"
:event/player1 "Salif Sane"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5605819"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_10194"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Thiago Alcantara"
:event/player1 "Manuel Schmiedebach"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5605940"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_10194"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5605959"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_10194"}

{:event/type "shoton"
:event/elapsed 84
:event/subtype "shot"
:event/player1 "Mario Goetze"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_5605992"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_10194"}

{:event/type "corner"
:event/elapsed 85
:event/subtype "cross_right"
:event/player1 "Mario Goetze"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5605999"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_10194"}

{:event/type "corner"
:event/elapsed 86
:event/subtype "short_left"
:event/player1 "Franck Ribery"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_5606033"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_10194"}

{:event/type "corner"
:event/elapsed 86
:event/subtype "cross_left"
:event/player1 "Thiago Alcantara"
:event/sortorder 5
:event/team "home"
:event/event_type "corner"
:event/id "event_5606039"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_10194"}

{:event/type "shotoff"
:event/elapsed 87
:event/subtype "distance"
:event/player1 "Robert Lewandowski"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5606054"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_10194"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Thiago Alcantara"
:event/subtype "pull"
:event/player1 "Waldemar Anton"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5606093"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_10194"}

{:event/type "shotoff"
:event/elapsed 89
:event/subtype "deflected"
:event/player1 "Sebastian Rode"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5606109"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_10194"}

{:event/type "corner"
:event/elapsed 89
:event/subtype "short_left"
:event/player1 "Thiago Alcantara"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_5606121"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_10194"}

{:event/type "shoton"
:event/elapsed 90
:event/subtype "big chance shot"
:event/player1 "Arturo Vidal"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_5606152"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_10194"}

{:event/type "corner"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "short_left"
:event/player1 "Thiago Alcantara"
:event/sortorder 5
:event/team "home"
:event/event_type "corner"
:event/id "event_5606155"
:event/minute 91
:event/match_id "match_10194"}


]

