
;;# data
[
{:match/id "match_11185"
:match/league "Italy Serie A"
:match/hometeam "Napoli"
:match/awayteam "Cesena"
:match/score "2:0"
:match/hometeam_goals "2"
:match/awayteam_goals "0"}

{:event/type "goal"
:event/elapsed 13
:event/player1 "Edinson Cavani"
:event/sortorder 0
:event/team "home"
:event/id "event_1400002"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_11185"}

{:event/type "card"
:event/elapsed 43
:event/card_type "y"
:event/player1 "Christian Maggio"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1400286"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_11185"}

{:event/type "card"
:event/elapsed 80
:event/card_type "y"
:event/player1 "Fabiano Santacroce"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1400771"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_11185"}

{:event/type "goal"
:event/elapsed 90
:event/player1 "Jose Sosa"
:event/sortorder 0
:event/team "home"
:event/id "event_1400840"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_11185"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Luis Jimenez"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1400865"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_11185"}


]

