
;;# data
[
{:match/id "match_6560"
:match/league "France Ligue 1"
:match/hometeam "SC Bastia"
:match/awayteam "Toulouse FC"
:match/score "0:0"
:match/hometeam_goals "0"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 33
:event/card_type "y"
:event/player1 "Franck Tabanou"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2729855"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_6560"}

{:event/type "card"
:event/elapsed 65
:event/card_type "y"
:event/player1 "Aymen Abdennour"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2729954"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_6560"}


]

