
;;# data
[
{:match/id "match_7613"
:match/league "France Ligue 1"
:match/hometeam "Montpellier Hérault SC"
:match/awayteam "Toulouse FC"
:match/score "2:0"
:match/hometeam_goals "2"
:match/awayteam_goals "0"}

{:event/type "foulcommit"
:event/elapsed 1
:event/player2 "Francois Moubandje"
:event/player1 "Souleymane Camara"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5285619"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Adrien Regattin"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5285641"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Jerome Roussillon"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5285656"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_7613"}

{:event/type "corner"
:event/elapsed 3
:event/subtype "cross_left"
:event/player1 "Jamel Saihi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5285661"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_5285714"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_7613"}

{:event/type "shoton"
:event/elapsed 5
:event/subtype "volley"
:event/player1 "Mustapha Yatabare"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5285722"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Adrien Regattin"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5285734"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_7613"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Bryan Dabo"
:event/subtype "serious_foul"
:event/player1 "Etienne Didot"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5285769"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_7613"}

{:event/type "shoton"
:event/elapsed 8
:event/subtype "shot"
:event/player1 "Souleymane Camara"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5285799"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_7613"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "William Remy"
:event/subtype "trip"
:event/player1 "Adrien Regattin"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5285814"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Etienne Didot"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5285837"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_7613"}

{:event/type "shoton"
:event/elapsed 10
:event/subtype "header"
:event/player1 "Wissam Ben Yedder"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_5285845"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_7613"}

{:event/type "corner"
:event/elapsed 10
:event/subtype "cross_right"
:event/player1 "Adrien Regattin"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_5285850"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Adrien Regattin"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_5285860"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Marcel Tisserand"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5285904"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_7613"}

{:event/type "shotoff"
:event/elapsed 14
:event/subtype "distance"
:event/player1 "Etienne Didot"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5285934"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_7613"}

{:event/type "shoton"
:event/elapsed 15
:event/subtype "distance"
:event/player1 "Oscar Trejo"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_5285965"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Ryad Boudebouz"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5285975"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_7613"}

{:event/type "foulcommit"
:event/elapsed 17
:event/subtype "hands"
:event/player1 "Mustapha Yatabare"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5286027"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_7613"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Uros Spajic"
:event/subtype "dangerous_play"
:event/player1 "Souleymane Camara"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5286059"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_7613"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Jonas Martin"
:event/subtype "serious_foul"
:event/player1 "Adrien Regattin"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5286115"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_7613"}

{:event/type "card"
:event/elapsed 21
:event/card_type "y"
:event/player1 "Adrien Regattin"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_5286119"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Ryad Boudebouz"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5286132"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Souleymane Camara"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_5286139"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Bryan Dabo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5286154"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Jerome Roussillon"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5286161"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_7613"}

{:event/type "shoton"
:event/elapsed 23
:event/subtype "deflected"
:event/player1 "Mustapha Yatabare"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_5286167"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_7613"}

{:event/type "goal"
:event/elapsed 24
:event/player2 "Souleymane Camara"
:event/subtype "shot"
:event/player1 "Mustapha Yatabare"
:event/sortorder 3
:event/team "home"
:event/id "event_5286182"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_7613"}

{:event/type "shotoff"
:event/elapsed 26
:event/subtype "distance"
:event/player1 "Marcel Tisserand"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5286212"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_7613"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Marcel Tisserand"
:event/player1 "Souleymane Camara"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5286241"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_7613"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Mustapha Yatabare"
:event/player1 "Alexis Blin"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5286251"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_7613"}

{:event/type "foulcommit"
:event/elapsed 30
:event/player2 "Oscar Trejo"
:event/subtype "obstruction"
:event/player1 "Jamel Saihi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5286294"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Jonas Martin"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_5286302"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Marcel Tisserand"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5286310"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Alexis Blin"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5286324"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Uros Spajic"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5286349"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Marcel Tisserand"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5286386"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Etienne Didot"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_5286390"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Souleymane Camara"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5286408"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_7613"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Wissam Ben Yedder"
:event/subtype "pull"
:event/player1 "Hilton"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5286440"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Adrien Regattin"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5286444"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_7613"}

{:event/type "shoton"
:event/elapsed 38
:event/subtype "big chance header"
:event/player1 "Uros Spajic"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_5286450"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_7613"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "William Remy"
:event/player1 "Uros Spajic"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5286465"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_7613"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Souleymane Camara"
:event/player1 "Uros Spajic"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5286499"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_7613"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Bryan Dabo"
:event/subtype "pull"
:event/player1 "Etienne Didot"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5286520"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Bryan Dabo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5286532"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Jerome Roussillon"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5286542"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_7613"}

{:event/type "shoton"
:event/elapsed 44
:event/subtype "deflected"
:event/player1 "Etienne Didot"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_5286553"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Adrien Regattin"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5286582"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_7613"}

{:event/type "corner"
:event/elapsed 45
:event/subtype "cross_left"
:event/player1 "Adrien Regattin"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_5286584"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_7613"}

{:event/type "foulcommit"
:event/elapsed 47
:event/player2 "Wissam Ben Yedder"
:event/subtype "pushing"
:event/player1 "Jamel Saihi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5286834"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Francois Moubandje"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5286870"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Souleymane Camara"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5286891"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_7613"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Oscar Trejo"
:event/subtype "trip"
:event/player1 "Jonas Martin"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5286919"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Francois Moubandje"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5286921"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_7613"}

{:event/type "shotoff"
:event/elapsed 51
:event/subtype "distance"
:event/player1 "Adrien Regattin"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5286929"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_7613"}

{:event/type "foulcommit"
:event/elapsed 52
:event/subtype "hands"
:event/player1 "Jamel Saihi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5286949"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Adrien Regattin"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5286957"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_7613"}

{:event/type "shotoff"
:event/elapsed 53
:event/subtype "header"
:event/player1 "Jean-Daniel Akpa-Akpro"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5286962"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_7613"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Ryad Boudebouz"
:event/subtype "serious_foul"
:event/player1 "Uros Spajic"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5286981"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Jonas Martin"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5286988"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_7613"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Marcel Tisserand"
:event/player1 "Jonas Martin"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5287017"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_7613"}

{:event/type "corner"
:event/elapsed 57
:event/subtype "cross_right"
:event/player1 "Ryad Boudebouz"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_5287085"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Francois Moubandje"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5287128"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Jerome Roussillon"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5287150"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Rodrigue Casimir Ninga"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5287161"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_7613"}

{:event/type "foulcommit"
:event/elapsed 61
:event/subtype "hands"
:event/player1 "Rodrigue Casimir Ninga"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5287168"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_7613"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player1 "Marcel Tisserand"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5287178"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_7613"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Ryad Boudebouz"
:event/subtype "pushing"
:event/player1 "Uros Spajic"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5287219"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_7613"}

{:event/type "shoton"
:event/elapsed 63
:event/subtype "blocked_shot"
:event/player1 "Mustapha Yatabare"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_5287233"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Adrien Regattin"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5287256"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Jean-Daniel Akpa-Akpro"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5287282"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Jean-Daniel Akpa-Akpro"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5287304"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Adrien Regattin"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5287325"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_7613"}

{:event/type "shotoff"
:event/elapsed 68
:event/subtype "volley"
:event/player1 "Wissam Ben Yedder"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5287328"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Jean-Daniel Akpa-Akpro"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5287362"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_7613"}

{:event/type "shoton"
:event/elapsed 69
:event/subtype "shot"
:event/player1 "Wissam Ben Yedder"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_5287364"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Francois Moubandje"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5287371"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_7613"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Rodrigue Casimir Ninga"
:event/subtype "pull"
:event/player1 "Jean-Daniel Akpa-Akpro"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5287393"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Oscar Trejo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5287429"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Rodrigue Casimir Ninga"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5287444"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_7613"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Oscar Trejo"
:event/player1 "Ryad Boudebouz"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5287482"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_7613"}

{:event/type "shotoff"
:event/elapsed 75
:event/subtype "distance"
:event/player1 "Ryad Boudebouz"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5287493"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_7613"}

{:event/type "corner"
:event/elapsed 78
:event/subtype "cross_left"
:event/player1 "Ryad Boudebouz"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5287546"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Ryad Boudebouz"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5287566"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_7613"}

{:event/type "shotoff"
:event/elapsed 79
:event/subtype "big chance shot"
:event/player1 "Kevin Berigaud"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5287568"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Jean-Daniel Akpa-Akpro"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5287607"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_7613"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Jean-Daniel Akpa-Akpro"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5287630"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_7613"}

{:event/type "shotoff"
:event/elapsed 82
:event/subtype "big chance header"
:event/player1 "Zinedine Machach"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5287632"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_7613"}

{:event/type "foulcommit"
:event/elapsed 83
:event/player2 "William Remy"
:event/subtype "serious_foul"
:event/player1 "Francois Moubandje"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5287649"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_7613"}

{:event/type "card"
:event/elapsed 83
:event/card_type "y"
:event/player1 "Francois Moubandje"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_5287652"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_7613"}

{:event/type "shotoff"
:event/elapsed 84
:event/subtype "miss_kick"
:event/player1 "Martin Braithwaite"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5287681"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_7613"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player1 "Ryad Boudebouz"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5287722"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_7613"}

{:event/type "corner"
:event/elapsed 87
:event/subtype "cross_left"
:event/player1 "Ryad Boudebouz"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5287735"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_7613"}

{:event/type "goal"
:event/elapsed 88
:event/player2 "Ryad Boudebouz"
:event/subtype "header"
:event/player1 "Souleymane Camara"
:event/sortorder 0
:event/team "home"
:event/id "event_5287743"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_7613"}

{:event/type "corner"
:event/elapsed 90
:event/subtype "cross_right"
:event/player1 "Oscar Trejo"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_5287767"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_7613"}

{:event/type "corner"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross_right"
:event/player1 "Oscar Trejo"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_5287795"
:event/minute 91
:event/match_id "match_7613"}

{:event/type "shotoff"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Wissam Ben Yedder"
:event/sortorder 6
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5287816"
:event/minute 92
:event/match_id "match_7613"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Somalia"
:event/player1 "Ramy Bensebaini"
:event/sortorder 11
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5287843"
:event/minute 93
:event/match_id "match_7613"}

{:event/type "foulcommit"
:event/elapsed_plus 4
:event/elapsed 90
:event/player2 "Jamel Saihi"
:event/subtype "pull"
:event/player1 "Alexis Blin"
:event/sortorder 12
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5287852"
:event/minute 94
:event/match_id "match_7613"}


]

