
;;# data
[
{:match/id "match_9042"
:match/league "Germany 1. Bundesliga"
:match/hometeam "Borussia Dortmund"
:match/awayteam "VfB Stuttgart"
:match/score "0:0"
:match/hometeam_goals "0"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 18
:event/card_type "y"
:event/player1 "Raphael Holzhauser"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2454709"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_9042"}

{:event/type "card"
:event/elapsed 21
:event/card_type "y"
:event/player1 "William Kvist"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2454816"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_9042"}

{:event/type "card"
:event/elapsed 71
:event/card_type "y"
:event/player1 "Vedad Ibisevic"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2455454"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_9042"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Christian Gentner"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2455923"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_9042"}


]

