
;;# data
[
{:match/id "match_24261"
:match/league "Spain LIGA BBVA"
:match/hometeam "SD Eibar"
:match/awayteam "Real Sporting de Gijón"
:match/score "3:0"
:match/hometeam_goals "2"
:match/awayteam_goals "0"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "Keko"
:event/subtype "trip"
:event/player1 "Omar Mascarell"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5137495"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Simone Verdi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5137500"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_24261"}

{:event/type "corner"
:event/elapsed 4
:event/subtype "cross_right"
:event/player1 "Saul Berjon"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_5137504"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_24261"}

{:event/type "shotoff"
:event/elapsed 4
:event/subtype "distance"
:event/player1 "Dani Garcia"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5137509"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 6
:event/player2 "Jony"
:event/subtype "trip"
:event/player1 "Gonzalo Escalante"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5137517"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Keko"
:event/subtype "serious_foul"
:event/player1 "Alex Menendez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5137523"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_24261"}

{:event/type "card"
:event/elapsed 7
:event/card_type "y"
:event/player1 "Alex Menendez"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_5137524"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Saul Berjon"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5137527"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_24261"}

{:event/type "corner"
:event/elapsed 8
:event/subtype "short_left"
:event/player1 "Saul Berjon"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_5137530"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Simone Verdi"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5137533"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_24261"}

{:event/type "shotoff"
:event/elapsed 8
:event/subtype "shot"
:event/player1 "Ivan Ramis"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5137535"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Simone Verdi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5137548"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Keko"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_5137553"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_24261"}

{:event/type "corner"
:event/elapsed 12
:event/subtype "cross_right"
:event/player1 "Saul Berjon"
:event/sortorder 5
:event/team "home"
:event/event_type "corner"
:event/id "event_5137557"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_24261"}

{:event/type "shoton"
:event/elapsed 13
:event/subtype "blocked_shot"
:event/player1 "Ivan Ramis"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_5137559"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Ander Capa"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5137567"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Lora"
:event/subtype "pushing"
:event/player1 "Saul Berjon"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5137581"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Alex Menendez"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5137587"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_24261"}

{:event/type "corner"
:event/elapsed 18
:event/subtype "short_left"
:event/player1 "unknown"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_5137592"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Alex Menendez"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5137594"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 18
:event/subtype "hands"
:event/player1 "Dani Ndi"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5137596"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Borja Baston"
:event/subtype "pushing"
:event/player1 "unknown"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5137602"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Manuel Lillo Castellano"
:event/subtype "trip"
:event/player1 "unknown"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5137603"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_24261"}

{:event/type "shotoff"
:event/elapsed 21
:event/subtype "direct_freekick"
:event/player1 "Saul Berjon"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5137606"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Lora"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5137620"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_24261"}

{:event/type "shotoff"
:event/elapsed 24
:event/subtype "shot"
:event/player1 "Alen Halilovic"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5137621"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Dani Ndi"
:event/subtype "trip"
:event/player1 "Dani Garcia"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5137629"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_24261"}

{:event/type "corner"
:event/elapsed 26
:event/subtype "cross_left"
:event/player1 "unknown"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_5137635"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_24261"}

{:event/type "corner"
:event/elapsed 27
:event/subtype "short_left"
:event/player1 "unknown"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_5137637"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Jony"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5137638"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Simone Verdi"
:event/subtype "trip"
:event/player1 "Omar Mascarell"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5137641"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Simone Verdi"
:event/subtype "trip"
:event/player1 "Jorge Mere"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5137648"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Ivan Ramis"
:event/subtype "dangerous_play"
:event/player1 "Antonio Sanabria"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5137651"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Keko"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5137654"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Gonzalo Escalante"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5137656"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_24261"}

{:event/type "shotoff"
:event/elapsed 30
:event/subtype "shot"
:event/player1 "Saul Berjon"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5137657"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_24261"}

{:event/type "shoton"
:event/elapsed 32
:event/subtype "shot"
:event/player1 "Borja Baston"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5137667"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Lora"
:event/subtype "trip"
:event/player1 "Borja Baston"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5137673"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_24261"}

{:event/type "shoton"
:event/elapsed 38
:event/subtype "blocked_shot"
:event/player1 "Keko"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5137676"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_24261"}

{:event/type "corner"
:event/elapsed 39
:event/subtype "cross_right"
:event/player1 "Saul Berjon"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5137677"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Simone Verdi"
:event/subtype "trip"
:event/player1 "Alberto Guitian"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5137680"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_24261"}

{:event/type "card"
:event/elapsed 39
:event/card_type "y"
:event/player1 "Alberto Guitian"
:event/sortorder 4
:event/team "away"
:event/event_type "card"
:event/id "event_5137681"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Saul Berjon"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5137682"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Dani Garcia"
:event/subtype "trip"
:event/player1 "Dani Ndi"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5137684"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Manuel Lillo Castellano"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5137685"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Dani Ndi"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5137687"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_24261"}

{:event/type "shotoff"
:event/elapsed 43
:event/subtype "shot"
:event/player1 "Saul Berjon"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5137689"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Dani Garcia"
:event/subtype "trip"
:event/player1 "Antonio Sanabria"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5137697"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 46
:event/player2 "Gonzalo Escalante"
:event/subtype "trip"
:event/player1 "unknown"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5137778"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 46
:event/subtype "hands"
:event/player1 "Simone Verdi"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5137779"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Antonio Sanabria"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5137786"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_24261"}

{:event/type "shoton"
:event/elapsed 47
:event/subtype "blocked_shot"
:event/player1 "Jony"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_5137788"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/sortorder 2
:event/team "away"
:event/event_type "throwin"
:event/id "event_5137790"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Dani Ndi"
:event/subtype "trip"
:event/player1 "Ivan Ramis"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5137805"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Lora"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5137810"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/sortorder 1
:event/team "away"
:event/event_type "throwin"
:event/id "event_5137812"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Dani Garcia"
:event/subtype "pushing"
:event/player1 "Omar Mascarell"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5137814"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Alex Menendez"
:event/subtype "pushing"
:event/player1 "Keko"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5137823"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Manuel Lillo Castellano"
:event/subtype "trip"
:event/player1 "Alen Halilovic"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5137828"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Simone Verdi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5137832"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Manuel Lillo Castellano"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5137838"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_24261"}

{:event/type "goal"
:event/elapsed 55
:event/subtype "shot"
:event/player1 "Keko"
:event/sortorder 2
:event/team "home"
:event/id "event_5137839"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_24261"}

{:event/type "corner"
:event/elapsed 57
:event/subtype "short_left"
:event/player1 "Saul Berjon"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5137849"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Dani Ndi"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5137855"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Jony"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5137857"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_24261"}

{:event/type "corner"
:event/elapsed 59
:event/subtype "cross_right"
:event/player1 "unknown"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_5137861"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Ander Capa"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5137870"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player2 "Dani Ndi"
:event/subtype "trip"
:event/player1 "Ivan Ramis"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5137876"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_24261"}

{:event/type "card"
:event/elapsed 60
:event/card_type "y"
:event/player1 "Ivan Ramis"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_5137879"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Jony"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5137881"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_24261"}

{:event/type "goal"
:event/elapsed 62
:event/player2 "Saul Berjon"
:event/subtype "shot"
:event/player1 "Borja Baston"
:event/sortorder 2
:event/team "home"
:event/id "event_5137890"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Jony"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5137896"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "unknown"
:event/subtype "pushing"
:event/player1 "Borja Baston"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5137909"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Dani Ndi"
:event/subtype "pushing"
:event/player1 "Manuel Lillo Castellano"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5137905"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_24261"}

{:event/type "card"
:event/elapsed 65
:event/card_type "y"
:event/player1 "Manuel Lillo Castellano"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_5137908"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_24261"}

{:event/type "shotoff"
:event/elapsed 66
:event/subtype "direct_freekick"
:event/player1 "Jony"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5137913"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Keko"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5137915"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Jony"
:event/subtype "from_behind"
:event/player1 "Dani Garcia"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5137917"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_24261"}

{:event/type "card"
:event/elapsed 67
:event/card_type "y"
:event/player1 "Dani Garcia"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_5137918"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "unknown"
:event/subtype "trip"
:event/player1 "Manuel Lillo Castellano"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5137934"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Borja Baston"
:event/subtype "trip"
:event/player1 "unknown"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5137937"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Simone Verdi"
:event/subtype "trip"
:event/player1 "Lora"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5137941"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_24261"}

{:event/type "card"
:event/elapsed 71
:event/card_type "y"
:event/player1 "Lora"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_5137942"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_24261"}

{:event/type "shoton"
:event/elapsed 72
:event/subtype "direct_freekick"
:event/player1 "Simone Verdi"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5137950"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 72
:event/player2 "Dani Ndi"
:event/subtype "trip"
:event/player1 "Gonzalo Escalante"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5137964"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Jony"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5137959"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_24261"}

{:event/type "corner"
:event/elapsed 74
:event/subtype "cross_left"
:event/player1 "Jony"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_5137961"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_24261"}

{:event/type "shoton"
:event/elapsed 75
:event/subtype "blocked_shot"
:event/player1 "Carlos Castro"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_5137974"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Dani Ndi"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5137976"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_24261"}

{:event/type "corner"
:event/elapsed 75
:event/subtype "cross_left"
:event/player1 "unknown"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_5137977"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_5137986"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_24261"}

{:event/type "shotoff"
:event/elapsed 77
:event/subtype "shot"
:event/player1 "Keko"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5137995"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Alex Menendez"
:event/subtype "dangerous_play"
:event/player1 "Simone Verdi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5138000"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_24261"}

{:event/type "shotoff"
:event/elapsed 81
:event/subtype "shot"
:event/player1 "Dani Ndi"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5138003"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_5138006"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_24261"}

{:event/type "shotoff"
:event/elapsed 83
:event/subtype "shot"
:event/player1 "Carlos Castro"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5138007"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_24261"}

{:event/type "goal"
:event/elapsed 83
:event/subtype "shot"
:event/player1 "Keko"
:event/sortorder 4
:event/team "home"
:event/id "event_5138010"
:event/event_type "goal"
:event/goal_type "dg"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_24261"}

{:event/type "corner"
:event/elapsed 84
:event/subtype "short_left"
:event/player1 "unknown"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_5138012"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Jony"
:event/subtype "pushing"
:event/player1 "Borja Baston"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5138013"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5138014"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5138015"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_24261"}

{:event/type "shotoff"
:event/elapsed 86
:event/subtype "shot"
:event/player1 "Alen Halilovic"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5138019"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 87
:event/player2 "Mauro Dos Santos"
:event/subtype "trip"
:event/player1 "Carlos Castro"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5138022"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Simone Verdi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5138023"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Dani Ndi"
:event/subtype "trip"
:event/player1 "Manuel Lillo Castellano"
:event/sortorder 9
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5138039"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Dani Ndi"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5138029"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Jony"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_5138033"
:event/minute 91
:event/match_id "match_24261"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Antonio Luna"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_5138035"
:event/minute 91
:event/match_id "match_24261"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Ivan Ramis"
:event/subtype "trip"
:event/player1 "Carlos Castro"
:event/sortorder 9
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5138040"
:event/minute 93
:event/match_id "match_24261"}


]

