
;;# data
[
{:match/id "match_2059"
:match/league "England Premier League"
:match/hometeam "Liverpool"
:match/awayteam "Stoke City"
:match/score "0:0"
:match/hometeam_goals "0"
:match/awayteam_goals "0"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_412115"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_412117"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_2059"}

{:event/type "corner"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_412117"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Xabi Alonso"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_412119"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_2059"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Fernando Torres"
:event/player1 "Ibrahima Sonko"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_412127"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_412138"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Liam Lawrence"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_412141"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_2059"}

{:event/type "corner"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Liam Lawrence"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_412141"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_2059"}

{:event/type "shotoff"
:event/elapsed 5
:event/subtype "distance"
:event/player1 "Dave Kitson"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_412164"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Alvaro Arbeloa"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_412182"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Dirk Kuyt"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_412191"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_2059"}

{:event/type "shoton"
:event/elapsed 8
:event/subtype "volley"
:event/player1 "Robbie Keane"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_412192"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_2059"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Alvaro Arbeloa"
:event/player1 "Salif Diao"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_412202"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_2059"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Robbie Keane"
:event/subtype "from_behind"
:event/player1 "Seyi Olofinjana"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_412219"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_2059"}

{:event/type "shoton"
:event/elapsed 12
:event/subtype "direct_freekick"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_412224"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_2059"}

{:event/type "shotoff"
:event/elapsed 13
:event/subtype "distance"
:event/player1 "Xabi Alonso"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_412236"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_2059"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Andy Griffin"
:event/player1 "Fernando Torres"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_412246"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Albert Riera"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_412257"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Dirk Kuyt"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_412259"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_412273"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Albert Riera"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_412276"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_2059"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Alvaro Arbeloa"
:event/player1 "Rory Delap"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_412279"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Dirk Kuyt"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_412288"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_2059"}

{:event/type "shotoff"
:event/elapsed 19
:event/subtype "distance"
:event/player1 "Xabi Alonso"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_412294"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Albert Riera"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_412333"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_2059"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Mamady Sidibe"
:event/player1 "Dirk Kuyt"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_412349"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_2059"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Fernando Torres"
:event/player1 "Andy Griffin"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_412359"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Dirk Kuyt"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_412363"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_2059"}

{:event/type "shotoff"
:event/elapsed 27
:event/subtype "distance"
:event/player1 "Albert Riera"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_412368"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Albert Riera"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_412378"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Albert Riera"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_412380"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_412383"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2059"}

{:event/type "corner"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_412383"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2059"}

{:event/type "shoton"
:event/elapsed 29
:event/subtype "distance"
:event/player1 "Xabi Alonso"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_412387"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_412388"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2059"}

{:event/type "corner"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_412388"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2059"}

{:event/type "shotoff"
:event/elapsed 33
:event/subtype "distance"
:event/player1 "Dirk Kuyt"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_412427"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Dave Kitson"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_412431"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Albert Riera"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_412433"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_2059"}

{:event/type "shotoff"
:event/elapsed 34
:event/subtype "distance"
:event/player1 "Steven Gerrard"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_412445"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Dirk Kuyt"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_412466"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_2059"}

{:event/type "shotoff"
:event/elapsed 37
:event/subtype "distance"
:event/player1 "Xabi Alonso"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_412470"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Alvaro Arbeloa"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_412483"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Liam Lawrence"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_412493"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_2059"}

{:event/type "shoton"
:event/elapsed 39
:event/subtype "blocked_shot"
:event/player1 "Albert Riera"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_412496"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_412498"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Albert Riera"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_412506"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_2059"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Albert Riera"
:event/player1 "Mamady Sidibe"
:event/sortorder 5
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_412509"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_2059"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Alvaro Arbeloa"
:event/player1 "Rory Delap"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_412517"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Albert Riera"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_412520"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_2059"}

{:event/type "foulcommit"
:event/elapsed 42
:event/subtype "hands"
:event/player1 "Andy Griffin"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_412524"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Albert Riera"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_412536"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_412539"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_2059"}

{:event/type "corner"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_412539"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_2059"}

{:event/type "shoton"
:event/elapsed 43
:event/subtype "blocked_shot"
:event/player1 "Xabi Alonso"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_412540"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_412542"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_412546"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_2059"}

{:event/type "corner"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_412546"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_412550"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_412556"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_2059"}

{:event/type "corner"
:event/elapsed 45
:event/subtype "short"
:event/player1 "Steven Gerrard"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_412563"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_2059"}

{:event/type "shoton"
:event/elapsed 45
:event/subtype "blocked_shot"
:event/player1 "Albert Riera"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_412565"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_2059"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Liam Lawrence"
:event/player1 "Alvaro Arbeloa"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_412567"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/sortorder 1
:event/team "away"
:event/event_type "throwin"
:event/id "event_412575"
:event/minute 46
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Seyi Olofinjana"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_412667"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_2059"}

{:event/type "shotoff"
:event/elapsed 47
:event/subtype "shot"
:event/player1 "Liam Lawrence"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_412673"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_412677"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Albert Riera"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_412680"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_2059"}

{:event/type "corner"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Albert Riera"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_412680"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_2059"}

{:event/type "corner"
:event/elapsed 48
:event/subtype "short"
:event/player1 "Albert Riera"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_412686"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Albert Riera"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_412688"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_2059"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Leon Cort"
:event/player1 "Dirk Kuyt"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_412691"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_412702"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_2059"}

{:event/type "corner"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_412702"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_2059"}

{:event/type "shotoff"
:event/elapsed 50
:event/subtype "header"
:event/player1 "Albert Riera"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_412704"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Fernando Torres"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_412723"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Alvaro Arbeloa"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_412725"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_2059"}

{:event/type "shoton"
:event/elapsed 52
:event/subtype "volley"
:event/player1 "Robbie Keane"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_412728"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/sortorder 1
:event/team "away"
:event/event_type "throwin"
:event/id "event_412733"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Liam Lawrence"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_412741"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_2059"}

{:event/type "corner"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Liam Lawrence"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_412741"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Fernando Torres"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_412746"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_2059"}

{:event/type "corner"
:event/elapsed 53
:event/subtype "short"
:event/sortorder 5
:event/team "home"
:event/event_type "corner"
:event/id "event_412754"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Albert Riera"
:event/sortorder 6
:event/team "home"
:event/event_type "cross"
:event/id "event_412756"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_412758"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_2059"}

{:event/type "corner"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_412758"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Alvaro Arbeloa"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_412765"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_2059"}

{:event/type "shotoff"
:event/elapsed 54
:event/subtype "header"
:event/player1 "Fernando Torres"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_412769"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Dirk Kuyt"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_412780"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_2059"}

{:event/type "shoton"
:event/elapsed 56
:event/subtype "blocked_shot"
:event/player1 "unknown"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_412784"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_412835"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Rory Delap"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_412841"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Liam Lawrence"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_412850"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_2059"}

{:event/type "corner"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Liam Lawrence"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_412850"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_2059"}

{:event/type "shoton"
:event/elapsed 61
:event/subtype "header"
:event/player1 "Abdoulaye Faye"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_412854"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_2059"}

{:event/type "corner"
:event/elapsed 61
:event/subtype "short"
:event/player1 "Albert Riera"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_412859"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Albert Riera"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_412860"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_2059"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Seyi Olofinjana"
:event/player1 "Albert Riera"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_412872"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Dirk Kuyt"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_412884"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Dirk Kuyt"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_412899"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_2059"}

{:event/type "shoton"
:event/elapsed 65
:event/subtype "blocked_shot"
:event/player1 "Fernando Torres"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_412903"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_412907"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_2059"}

{:event/type "corner"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_412907"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_2059"}

{:event/type "foulcommit"
:event/elapsed 66
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_412913"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_2059"}

{:event/type "shoton"
:event/elapsed 67
:event/subtype "shot"
:event/player1 "Dirk Kuyt"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_412932"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_2059"}

{:event/type "shotoff"
:event/elapsed 68
:event/subtype "distance"
:event/player1 "Dirk Kuyt"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_412942"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_2059"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Dirk Kuyt"
:event/player1 "Andy Griffin"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_412951"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_2059"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Dirk Kuyt"
:event/subtype "from_behind"
:event/player1 "Richard Cresswell"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_412972"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Dirk Kuyt"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_412982"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_2059"}

{:event/type "corner"
:event/elapsed 72
:event/subtype "short"
:event/player1 "Steven Gerrard"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_412985"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Xabi Alonso"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_412988"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_2059"}

{:event/type "shotoff"
:event/elapsed 73
:event/subtype "distance"
:event/player1 "Jamie Carragher"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_412991"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Alvaro Arbeloa"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_413004"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_2059"}

{:event/type "shotoff"
:event/elapsed 74
:event/subtype "distance"
:event/player1 "Steven Gerrard"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_413008"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_2059"}

{:event/type "shoton"
:event/elapsed 77
:event/subtype "blocked_shot"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_413026"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_413028"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_2059"}

{:event/type "corner"
:event/elapsed 77
:event/subtype "cross"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_413028"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_413031"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_2059"}

{:event/type "shotoff"
:event/elapsed 79
:event/subtype "volley"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_413046"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_2059"}

{:event/type "shoton"
:event/elapsed 80
:event/subtype "distance"
:event/player1 "Xabi Alonso"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_413056"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_413065"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Rory Delap"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_413069"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_2059"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Ricardo Fuller"
:event/player1 "Alvaro Arbeloa"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_413074"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_2059"}

{:event/type "shoton"
:event/elapsed 83
:event/subtype "blocked_shot"
:event/player1 "Rory Delap"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_413078"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_413087"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_2059"}

{:event/type "shoton"
:event/elapsed 84
:event/subtype "volley"
:event/player1 "Dirk Kuyt"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_413091"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_2059"}

{:event/type "shotoff"
:event/elapsed 84
:event/subtype "shot"
:event/player1 "Fernando Torres"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_413098"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_2059"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Ricardo Fuller"
:event/subtype "from_behind"
:event/player1 "Martin Skrtel"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_413111"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_2059"}

{:event/type "card"
:event/elapsed 85
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Martin Skrtel"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_413115"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_2059"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Alvaro Arbeloa"
:event/player1 "Mamady Sidibe"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_413119"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_413125"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Yossi Benayoun"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_413131"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_413134"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_2059"}

{:event/type "corner"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_413134"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Martin Skrtel"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_413138"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_413140"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_2059"}

{:event/type "corner"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_413140"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_413152"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_413156"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_2059"}

{:event/type "corner"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_413156"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Xabi Alonso"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_413159"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_2059"}

{:event/type "corner"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Xabi Alonso"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_413159"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Alvaro Arbeloa"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_413166"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_2059"}

{:event/type "corner"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Alvaro Arbeloa"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_413166"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_2059"}

{:event/type "shotoff"
:event/elapsed 90
:event/subtype "distance"
:event/player1 "Steven Gerrard"
:event/sortorder 6
:event/team "home"
:event/event_type "shotoff"
:event/id "event_413169"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_2059"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Jamie Carragher"
:event/subtype "serious_foul"
:event/player1 "Ricardo Fuller"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_413181"
:event/minute 91
:event/match_id "match_2059"}

{:event/type "card"
:event/elapsed_plus 1
:event/elapsed 90
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Ricardo Fuller"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_413182"
:event/minute 91
:event/match_id "match_2059"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_413193"
:event/minute 92
:event/match_id "match_2059"}

{:event/type "shotoff"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Steven Gerrard"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_413199"
:event/minute 93
:event/match_id "match_2059"}


]

