
;;# data
[
{:match/id "match_6535"
:match/league "France Ligue 1"
:match/hometeam "Stade Rennais FC"
:match/awayteam "Paris Saint-Germain"
:match/score "0:2"
:match/hometeam_goals "0"
:match/awayteam_goals "2"}

{:event/type "card"
:event/elapsed 32
:event/card_type "y"
:event/player1 "John Boye"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2682086"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_6535"}

{:event/type "card"
:event/elapsed 33
:event/card_type "y"
:event/player1 "Marco Verratti"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2682108"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_6535"}

{:event/type "goal"
:event/elapsed 56
:event/player1 "Jeremy Menez"
:event/sortorder 0
:event/team "away"
:event/id "event_2682459"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_6535"}

{:event/type "card"
:event/elapsed 78
:event/card_type "y"
:event/player1 "Clement Chantome"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2682550"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_6535"}

{:event/type "card"
:event/elapsed 80
:event/card_type "y"
:event/player1 "Gregory van der Wiel"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2682674"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_6535"}

{:event/type "goal"
:event/elapsed 90
:event/player1 "Zlatan Ibrahimovic"
:event/sortorder 0
:event/team "away"
:event/id "event_2682606"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_6535"}


]

