
;;# data
[
{:match/id "match_7787"
:match/league "France Ligue 1"
:match/hometeam "Toulouse FC"
:match/awayteam "Olympique de Marseille"
:match/score "1:1"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Wissam Ben Yedder"
:event/player1 "Lassana Diarra"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4820287"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Francois Moubandje"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4820314"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_7787"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Karim Rekik"
:event/subtype "pushing"
:event/player1 "Martin Braithwaite"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4820357"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_7787"}

{:event/type "shotoff"
:event/elapsed 7
:event/subtype "volley"
:event/player1 "Etienne Didot"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4820466"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Paolo De Ceglie"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_4820495"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Wissam Ben Yedder"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4820519"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_7787"}

{:event/type "corner"
:event/elapsed 10
:event/subtype "cross_left"
:event/player1 "Wissam Ben Yedder"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4820620"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_7787"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Marcel Tisserand"
:event/player1 "Remy Cabella"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4820697"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_7787"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Adrien Regattin"
:event/player1 "Karim Rekik"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4820791"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Adrien Regattin"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4820812"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_7787"}

{:event/type "shotoff"
:event/elapsed 17
:event/subtype "shot"
:event/player1 "Lucas Silva"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4820906"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_7787"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Tongo Hamed Doumbia"
:event/player1 "Lucas Silva"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4820958"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Adrien Regattin"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4821011"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Mauricio Isla"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4821187"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Marcel Tisserand"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4821227"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_7787"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Jean-Daniel Akpa-Akpro"
:event/player1 "Paolo De Ceglie"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4821270"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Remy Cabella"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4821303"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Jean-Daniel Akpa-Akpro"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4821373"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_7787"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Lucas Silva"
:event/player1 "Adrien Regattin"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4821390"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Abdelaziz Barrada"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4821424"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_7787"}

{:event/type "corner"
:event/elapsed 29
:event/subtype "cross_left"
:event/player1 "Abdelaziz Barrada"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4821445"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Abdelaziz Barrada"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4821457"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Paolo De Ceglie"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4821528"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_7787"}

{:event/type "corner"
:event/elapsed 32
:event/subtype "cross_right"
:event/player1 "Abdelaziz Barrada"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4821559"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Georges N'Koudou"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4821587"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_7787"}

{:event/type "shotoff"
:event/elapsed 34
:event/subtype "distance"
:event/player1 "Lucas Silva"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4821677"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_7787"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Remy Cabella"
:event/player1 "Francois Moubandje"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4821723"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_7787"}

{:event/type "card"
:event/elapsed 36
:event/card_type "y"
:event/player1 "Francois Moubandje"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4821727"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_7787"}

{:event/type "shoton"
:event/elapsed 40
:event/subtype "distance"
:event/player1 "Adrien Regattin"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4821846"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Abdelaziz Barrada"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4821862"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_7787"}

{:event/type "corner"
:event/elapsed 41
:event/subtype "cross_right"
:event/player1 "Abdelaziz Barrada"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4821876"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Paolo De Ceglie"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4821879"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Remy Cabella"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4821899"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Paolo De Ceglie"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4821907"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_7787"}

{:event/type "corner"
:event/elapsed 42
:event/subtype "cross_left"
:event/player1 "Abdelaziz Barrada"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_4821917"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_7787"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Martin Braithwaite"
:event/player1 "Nicolas N'Koulou"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4821952"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_7787"}

{:event/type "shoton"
:event/elapsed 45
:event/subtype "blocked_shot"
:event/player1 "Abdelaziz Barrada"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4821982"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Francois Moubandje"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4822462"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_7787"}

{:event/type "corner"
:event/elapsed 48
:event/subtype "cross_left"
:event/player1 "Abdelaziz Barrada"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_4822476"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_7787"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Abdelaziz Barrada"
:event/player1 "Etienne Didot"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4822505"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_7787"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Remy Cabella"
:event/player1 "Tongo Hamed Doumbia"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4822522"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Abdelaziz Barrada"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4822576"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_7787"}

{:event/type "shoton"
:event/elapsed 51
:event/subtype "blocked_shot"
:event/player1 "Lucas Ariel Ocampos"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4822580"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_7787"}

{:event/type "shotoff"
:event/elapsed 52
:event/subtype "shot"
:event/player1 "Tongo Hamed Doumbia"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4822587"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_7787"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Karim Rekik"
:event/subtype "pushing"
:event/player1 "Martin Braithwaite"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4822639"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_7787"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Remy Cabella"
:event/player1 "Tongo Hamed Doumbia"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4822650"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_7787"}

{:event/type "shoton"
:event/elapsed 54
:event/subtype "blocked_shot"
:event/player1 "Abdelaziz Barrada"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4822663"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Remy Cabella"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4822684"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Adrien Regattin"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4822696"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_7787"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Wissam Ben Yedder"
:event/player1 "Lassana Diarra"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4822713"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Adrien Regattin"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4822731"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_7787"}

{:event/type "shotoff"
:event/elapsed 57
:event/subtype "shot"
:event/player1 "Remy Cabella"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4822743"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_7787"}

{:event/type "shotoff"
:event/elapsed 59
:event/subtype "distance"
:event/player1 "Georges N'Koudou"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4822795"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_7787"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Jean-Daniel Akpa-Akpro"
:event/player1 "Lassana Diarra"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4822852"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_7787"}

{:event/type "shotoff"
:event/elapsed 61
:event/subtype "distance"
:event/player1 "Wissam Ben Yedder"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4822853"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Abdelaziz Barrada"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4822907"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_7787"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Wissam Ben Yedder"
:event/player1 "Lassana Diarra"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4822956"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_7787"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Francois Moubandje"
:event/player1 "Georges N'Koudou"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4823001"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Adrien Regattin"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4823015"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_7787"}

{:event/type "goal"
:event/elapsed 68
:event/player2 "Adrien Regattin"
:event/subtype "shot"
:event/player1 "Martin Braithwaite"
:event/sortorder 1
:event/team "home"
:event/id "event_4823026"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_7787"}

{:event/type "shotoff"
:event/elapsed 69
:event/subtype "distance"
:event/player1 "Martin Braithwaite"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4823057"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Abdelaziz Barrada"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4823086"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Tongo Hamed Doumbia"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4823171"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_7787"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Jean-Daniel Akpa-Akpro"
:event/player1 "Paolo De Ceglie"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4823212"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_7787"}

{:event/type "foulcommit"
:event/elapsed 78
:event/player2 "Jean-Daniel Akpa-Akpro"
:event/player1 "Benjamin Mendy"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4823291"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_7787"}

{:event/type "card"
:event/elapsed 78
:event/card_type "r"
:event/subtype "emergency_brake"
:event/player1 "Benjamin Mendy"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4823296"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_7787"}

{:event/type "shotoff"
:event/elapsed 79
:event/subtype "direct_freekick"
:event/player1 "Wissam Ben Yedder"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4823316"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_7787"}

{:event/type "foulcommit"
:event/elapsed 79
:event/player2 "Mauricio Isla"
:event/player1 "Adrien Regattin"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4823333"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_7787"}

{:event/type "shotoff"
:event/elapsed 80
:event/subtype "big chance shot"
:event/player1 "Martin Braithwaite"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4823360"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_7787"}

{:event/type "shotoff"
:event/elapsed 81
:event/subtype "volley"
:event/player1 "Lucas Ariel Ocampos"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4823375"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Marcel Tisserand"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4823430"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_7787"}

{:event/type "shoton"
:event/elapsed 83
:event/subtype "bicycle_kick"
:event/player1 "Adrien Regattin"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4823435"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_7787"}

{:event/type "corner"
:event/elapsed 83
:event/subtype "cross_right"
:event/player1 "Wissam Ben Yedder"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4823442"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_7787"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Georges N'Koudou"
:event/player1 "Francois Moubandje"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4823449"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_7787"}

{:event/type "card"
:event/elapsed 84
:event/card_type "y"
:event/player1 "Francois Moubandje"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4823450"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_7787"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Lassana Diarra"
:event/player1 "Adrien Regattin"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4823469"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_7787"}

{:event/type "card"
:event/elapsed 85
:event/card_type "y"
:event/subtype "verbal_abuse"
:event/player1 "Tongo Hamed Doumbia"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4823474"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Abdelaziz Barrada"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4823484"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_7787"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Lassana Diarra"
:event/player1 "Tongo Hamed Doumbia"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4823491"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_7787"}

{:event/type "foulcommit"
:event/elapsed 87
:event/player2 "Georges N'Koudou"
:event/subtype "serious_foul"
:event/player1 "Steeve Yago"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4823500"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_7787"}

{:event/type "card"
:event/elapsed 87
:event/card_type "r"
:event/player1 "Steeve Yago"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_4823503"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_7787"}

{:event/type "card"
:event/elapsed 87
:event/card_type "y"
:event/player1 "Jean-Daniel Akpa-Akpro"
:event/sortorder 3
:event/team "home"
:event/event_type "card"
:event/id "event_4823504"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Abdelaziz Barrada"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4823515"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_7787"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Yann Bodiger"
:event/player1 "Karim Rekik"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4823517"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_7787"}

{:event/type "shotoff"
:event/elapsed 90
:event/subtype "bad shot"
:event/player1 "Tongo Hamed Doumbia"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4823527"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_7787"}

{:event/type "goal"
:event/elapsed 90
:event/player2 "Abdelaziz Barrada"
:event/subtype "shot"
:event/player1 "Michy Batshuayi"
:event/sortorder 3
:event/team "away"
:event/id "event_4823533"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_7787"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Yann Bodiger"
:event/player1 "Bouna Sarr"
:event/sortorder 7
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4823543"
:event/minute 91
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Marcel Tisserand"
:event/sortorder 9
:event/team "home"
:event/event_type "cross"
:event/id "event_4823550"
:event/minute 92
:event/match_id "match_7787"}

{:event/type "corner"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross_left"
:event/player1 "Marcel Tisserand"
:event/sortorder 11
:event/team "home"
:event/event_type "corner"
:event/id "event_4823554"
:event/minute 93
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Marcel Tisserand"
:event/sortorder 12
:event/team "home"
:event/event_type "cross"
:event/id "event_4823556"
:event/minute 93
:event/match_id "match_7787"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Bouna Sarr"
:event/sortorder 14
:event/team "away"
:event/event_type "cross"
:event/id "event_4823558"
:event/minute 93
:event/match_id "match_7787"}


]

