
;;# data
[
{:match/id "match_9299"
:match/league "Germany 1. Bundesliga"
:match/hometeam "SC Freiburg"
:match/awayteam "SV Werder Bremen"
:match/score "1:2"
:match/hometeam_goals "1"
:match/awayteam_goals "2"}

{:event/type "card"
:event/elapsed 11
:event/card_type "y"
:event/player1 "Fallou Diagne"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2377750"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_9299"}

{:event/type "goal"
:event/elapsed 36
:event/player1 "Jonathan Schmid"
:event/sortorder 0
:event/team "home"
:event/id "event_2377795"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_9299"}

{:event/type "goal"
:event/elapsed 47
:event/player1 "Joseph Akpala"
:event/sortorder 0
:event/team "away"
:event/id "event_2377883"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_9299"}

{:event/type "card"
:event/elapsed 53
:event/card_type "y"
:event/player1 "Zlatko Junuzovic"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2377895"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_9299"}

{:event/type "goal"
:event/elapsed 59
:event/player1 "Aaron Hunt"
:event/sortorder 0
:event/team "away"
:event/id "event_2377894"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_9299"}

{:event/type "card"
:event/elapsed 66
:event/card_type "y"
:event/player1 "Joseph Akpala"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2377911"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_9299"}

{:event/type "card"
:event/elapsed 67
:event/card_type "y"
:event/player1 "Daniel Caligiuri"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2377919"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_9299"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Marko Arnautovic"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2377984"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_9299"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Sebastian Mielitz"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2377985"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_9299"}


]

