
;;# data
[
{:match/id "match_24025"
:match/league "Spain LIGA BBVA"
:match/hometeam "Granada CF"
:match/awayteam "Villarreal CF"
:match/score "0:0"
:match/hometeam_goals "0"
:match/awayteam_goals "0"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Piti"
:event/subtype "trip"
:event/player1 "Bruno Soriano"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3727060"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Fran Rico"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3727065"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Piti"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3727067"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_24025"}

{:event/type "shotoff"
:event/elapsed 3
:event/subtype "header"
:event/player1 "Success Isaac"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3727069"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_24025"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Fran Rico"
:event/subtype "trip"
:event/player1 "Luciano Dario Vietto"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3727081"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Alfredo Ortuno"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3727095"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Moi Gomez"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3727100"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Moi Gomez"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3727103"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_24025"}

{:event/type "shotoff"
:event/elapsed 7
:event/subtype "volley"
:event/player1 "Gerard Moreno"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3727105"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Manuel Trigueros"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3727113"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Mario Gaspar"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3727120"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_24025"}

{:event/type "shotoff"
:event/elapsed 9
:event/subtype "shot"
:event/player1 "Mario Gaspar"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3727124"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_24025"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Ruben Rochina"
:event/subtype "pushing"
:event/player1 "Bruno Soriano"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3727135"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Ruben Rochina"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3727137"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_24025"}

{:event/type "shotoff"
:event/elapsed 11
:event/subtype "distance"
:event/player1 "Jeison Murillo"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3727142"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Piti"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3727162"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Success Isaac"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3727170"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_24025"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Manuel Iturra"
:event/player1 "Luciano Dario Vietto"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3727177"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Fran Rico"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3727180"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_24025"}

{:event/type "shotoff"
:event/elapsed 19
:event/subtype "distance"
:event/player1 "Ruben Rochina"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3727183"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Success Isaac"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3727201"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_24025"}

{:event/type "corner"
:event/elapsed 22
:event/subtype "cross_left"
:event/player1 "Piti"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3727203"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_24025"}

{:event/type "corner"
:event/elapsed 23
:event/subtype "cross_left"
:event/player1 "Piti"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3727206"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_24025"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Sergio Asenjo"
:event/subtype "pushing"
:event/player1 "Jeison Murillo"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3727208"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_24025"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Moi Gomez"
:event/subtype "trip"
:event/player1 "Piti"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3727226"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_24025"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Gerard Moreno"
:event/subtype "pushing"
:event/player1 "Juan Carlos"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3727234"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Mario Gaspar"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3727236"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Adrian Marin"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3727248"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_24025"}

{:event/type "foulcommit"
:event/elapsed 30
:event/player2 "Gerard Moreno"
:event/subtype "advantage"
:event/player1 "Fran Rico"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3727254"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_24025"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Success Isaac"
:event/subtype "pushing"
:event/player1 "Bruno Soriano"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3727265"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Mario Gaspar"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3727273"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_24025"}

{:event/type "shotoff"
:event/elapsed 34
:event/subtype "shot"
:event/player1 "Luciano Dario Vietto"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3727275"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_24025"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Manuel Trigueros"
:event/subtype "dangerous_play"
:event/player1 "Fran Rico"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3727287"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_24025"}

{:event/type "shotoff"
:event/elapsed 39
:event/subtype "deflected"
:event/player1 "Manuel Trigueros"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3727296"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Allan Nyom"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3727303"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Ruben Rochina"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3727308"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_24025"}

{:event/type "shoton"
:event/elapsed 41
:event/subtype "blocked_shot"
:event/player1 "Manuel Trigueros"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3727310"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_24025"}

{:event/type "shotoff"
:event/elapsed 42
:event/subtype "deflected"
:event/player1 "Bruno Soriano"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3727312"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_24025"}

{:event/type "corner"
:event/elapsed 42
:event/subtype "short_left"
:event/player1 "Manuel Trigueros"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3727317"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Javier Espinosa Gonzalez"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3727318"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_24025"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Allan Nyom"
:event/subtype "pushing"
:event/player1 "Gabriel Paulista"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3727321"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_24025"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player1 "Fran Rico"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3727326"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_24025"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Ruben Rochina"
:event/subtype "trip"
:event/player1 "Mario Gaspar"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3727327"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_24025"}

{:event/type "foulcommit"
:event/elapsed 45
:event/subtype "hands"
:event/player1 "Bruno Soriano"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3727330"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_24025"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Gabriel Paulista"
:event/subtype "trip"
:event/player1 "Alfredo Ortuno"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3727333"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_24025"}

{:event/type "corner"
:event/elapsed 48
:event/subtype "cross_right"
:event/player1 "Javier Espinosa Gonzalez"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3727393"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_24025"}

{:event/type "shoton"
:event/elapsed 48
:event/subtype "blocked_shot"
:event/player1 "Adrian Marin"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_3727395"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Manuel Trigueros"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_3727397"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Juan Carlos"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3727400"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_24025"}

{:event/type "corner"
:event/elapsed 49
:event/subtype "cross_left"
:event/player1 "Piti"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3727401"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_24025"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Luciano Dario Vietto"
:event/subtype "pull"
:event/player1 "Piti"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3727407"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Javier Espinosa Gonzalez"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3727412"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_24025"}

{:event/type "corner"
:event/elapsed 53
:event/subtype "cross_right"
:event/player1 "Javier Espinosa Gonzalez"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3727424"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_24025"}

{:event/type "shoton"
:event/elapsed 53
:event/subtype "header"
:event/player1 "Gabriel Paulista"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3727425"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_24025"}

{:event/type "corner"
:event/elapsed 54
:event/subtype "cross_left"
:event/player1 "Javier Espinosa Gonzalez"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3727428"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_24025"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Jean-Sylvain Babin"
:event/subtype "pushing"
:event/player1 "Luciano Dario Vietto"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3727432"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Allan Nyom"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3727448"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_24025"}

{:event/type "corner"
:event/elapsed 57
:event/subtype "cross_right"
:event/player1 "Fran Rico"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3727451"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_24025"}

{:event/type "shotoff"
:event/elapsed 57
:event/subtype "deflected"
:event/player1 "Darwin Machis"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3727453"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_24025"}

{:event/type "corner"
:event/elapsed 57
:event/subtype "cross_right"
:event/player1 "Fran Rico"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_3727459"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Allan Nyom"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3727467"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_24025"}

{:event/type "shoton"
:event/elapsed 59
:event/subtype "header"
:event/player1 "Alfredo Ortuno"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_3727470"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_24025"}

{:event/type "shotoff"
:event/elapsed 60
:event/subtype "deflected"
:event/player1 "Manuel Trigueros"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3727475"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_24025"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Mateo Pablo Musacchio"
:event/subtype "dangerous_play"
:event/player1 "Darwin Machis"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3727480"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_24025"}

{:event/type "card"
:event/elapsed 61
:event/card_type "y"
:event/player1 "Darwin Machis"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_3727481"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Allan Nyom"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_3727485"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_24025"}

{:event/type "shoton"
:event/elapsed 62
:event/subtype "volley"
:event/player1 "Darwin Machis"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3727487"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_24025"}

{:event/type "corner"
:event/elapsed 63
:event/subtype "cross_left"
:event/player1 "Javier Espinosa Gonzalez"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3727497"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_24025"}

{:event/type "shotoff"
:event/elapsed 63
:event/subtype "header"
:event/player1 "Luciano Dario Vietto"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3727498"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_24025"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Allan Nyom"
:event/subtype "pushing"
:event/player1 "Cani"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3727527"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_24025"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Ruben Rochina"
:event/subtype "trip"
:event/player1 "Manuel Trigueros"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3727529"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Fran Rico"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3727534"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_24025"}

{:event/type "shotoff"
:event/elapsed 69
:event/subtype "volley"
:event/player1 "Jean-Sylvain Babin"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3727535"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_24025"}

{:event/type "foulcommit"
:event/elapsed 71
:event/subtype "diving"
:event/player1 "Luciano Dario Vietto"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3727546"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_24025"}

{:event/type "card"
:event/elapsed 71
:event/card_type "y"
:event/subtype "diving"
:event/player1 "Luciano Dario Vietto"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_3727549"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_24025"}

{:event/type "shotoff"
:event/elapsed 72
:event/subtype "shot"
:event/player1 "Denis Cheryshev"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3727553"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Darwin Machis"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3727562"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_24025"}

{:event/type "shoton"
:event/elapsed 74
:event/subtype "distance"
:event/player1 "Luciano Dario Vietto"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3727568"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Denis Cheryshev"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3727576"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Darwin Machis"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3727581"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_24025"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player1 "Ruben Rochina"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3727590"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Darwin Machis"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3727594"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_24025"}

{:event/type "card"
:event/elapsed 78
:event/card_type "y"
:event/subtype "advantage"
:event/player1 "Manuel Trigueros"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_3727597"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_24025"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Bruno Soriano"
:event/subtype "trip"
:event/player1 "Fran Rico"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3727610"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_24025"}

{:event/type "shotoff"
:event/elapsed 82
:event/subtype "shot"
:event/player1 "Antonio Rukavina"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3727614"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_24025"}

{:event/type "corner"
:event/elapsed 83
:event/subtype "cross_left"
:event/player1 "Fran Rico"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3727626"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_24025"}

{:event/type "shoton"
:event/elapsed 84
:event/subtype "shot"
:event/player1 "Denis Cheryshev"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3727630"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_24025"}

{:event/type "shoton"
:event/elapsed 85
:event/subtype "shot"
:event/player1 "Jhon Cordoba"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3727636"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_24025"}

{:event/type "corner"
:event/elapsed 85
:event/subtype "cross_right"
:event/player1 "Fran Rico"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3727638"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_24025"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Fran Rico"
:event/subtype "dangerous_play"
:event/player1 "Moi Gomez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3727645"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Fran Rico"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3727646"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_24025"}

{:event/type "corner"
:event/elapsed 87
:event/subtype "cross_right"
:event/player1 "Fran Rico"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3727649"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_24025"}

{:event/type "shoton"
:event/elapsed 87
:event/subtype "big chance header"
:event/player1 "Jeison Murillo"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3727650"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_24025"}

{:event/type "foulcommit"
:event/elapsed 87
:event/player2 "Sergio Asenjo"
:event/subtype "obstruction"
:event/player1 "Jhon Cordoba"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3727652"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_24025"}

{:event/type "card"
:event/elapsed 87
:event/card_type "y"
:event/player1 "Jhon Cordoba"
:event/sortorder 3
:event/team "home"
:event/event_type "card"
:event/id "event_3727654"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Darwin Machis"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3727658"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_24025"}

{:event/type "corner"
:event/elapsed 89
:event/subtype "cross_left"
:event/player1 "Fran Rico"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3727662"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Mario Gaspar"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_3727680"
:event/minute 93
:event/match_id "match_24025"}

{:event/type "shoton"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "blocked_shot"
:event/player1 "Denis Cheryshev"
:event/sortorder 6
:event/team "away"
:event/event_type "shoton"
:event/id "event_3727682"
:event/minute 93
:event/match_id "match_24025"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Darwin Machis"
:event/sortorder 7
:event/team "home"
:event/event_type "cross"
:event/id "event_3727683"
:event/minute 93
:event/match_id "match_24025"}

{:event/type "foulcommit"
:event/elapsed_plus 4
:event/elapsed 90
:event/player1 "Allan Nyom"
:event/sortorder 9
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3727686"
:event/minute 94
:event/match_id "match_24025"}

{:event/type "card"
:event/elapsed_plus 4
:event/elapsed 90
:event/card_type "y"
:event/player1 "Allan Nyom"
:event/sortorder 10
:event/team "home"
:event/event_type "card"
:event/id "event_3727687"
:event/minute 94
:event/match_id "match_24025"}


]

