
;;# data
[
{:match/id "match_3328"
:match/league "England Premier League"
:match/hometeam "Wigan Athletic"
:match/awayteam "Queens Park Rangers"
:match/score "2:2"
:match/hometeam_goals "2"
:match/awayteam_goals "2"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Shaun Derry"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2512879"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Shaun Wright-Phillips"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2512904"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_3328"}

{:event/type "shoton"
:event/elapsed 4
:event/subtype "distance"
:event/player1 "Adel Taarabt"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_2512915"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Adel Taarabt"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2512950"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Samba Diakite"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_2512960"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_3328"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "James McArthur"
:event/subtype "pushing"
:event/player1 "Stephane M'Bia"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2512988"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3328"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Samba Diakite"
:event/subtype "pushing"
:event/player1 "Jordi Gomez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2513014"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Shaun Wright-Phillips"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2513075"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_3328"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Clint Hill"
:event/subtype "dangerous_play"
:event/player1 "Arouna Kone"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2513082"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Franco Di Santo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2513086"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Jean Beausejour"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2513106"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_3328"}

{:event/type "corner"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Jean Beausejour"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2513106"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Ronnie Stam"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2513110"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3328"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Jean Beausejour"
:event/subtype "dangerous_play"
:event/player1 "Jose Bosingwa"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2513114"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3328"}

{:event/type "shoton"
:event/elapsed 18
:event/subtype "shot"
:event/player1 "David Jones"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_2513128"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Jean Beausejour"
:event/sortorder 5
:event/team "home"
:event/event_type "corner"
:event/id "event_2513129"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3328"}

{:event/type "corner"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Jean Beausejour"
:event/sortorder 5
:event/team "home"
:event/event_type "corner"
:event/id "event_2513129"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Jean Beausejour"
:event/sortorder 6
:event/team "home"
:event/event_type "corner"
:event/id "event_2513132"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3328"}

{:event/type "corner"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Jean Beausejour"
:event/sortorder 6
:event/team "home"
:event/event_type "corner"
:event/id "event_2513132"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3328"}

{:event/type "goal"
:event/elapsed 18
:event/subtype "volley"
:event/player1 "James McCarthy"
:event/sortorder 8
:event/team "home"
:event/id "event_2513123"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Armand Traore"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2513219"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Adel Taarabt"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_2513226"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3328"}

{:event/type "corner"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Adel Taarabt"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_2513226"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3328"}

{:event/type "goal"
:event/elapsed 25
:event/player2 "Adel Taarabt"
:event/subtype "header"
:event/player1 "Ryan Nelsen"
:event/sortorder 3
:event/team "away"
:event/id "event_2513222"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Ronnie Stam"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2513268"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_3328"}

{:event/type "shoton"
:event/elapsed 29
:event/subtype "shot"
:event/player1 "Franco Di Santo"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_2513271"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Jean Beausejour"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_2513280"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Ronnie Stam"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2513310"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_3328"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Robert Green"
:event/subtype "dangerous_play"
:event/player1 "Jean Beausejour"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2513315"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_3328"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Franco Di Santo"
:event/subtype "from_behind"
:event/player1 "Shaun Derry"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2513329"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "James McArthur"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2513343"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3328"}

{:event/type "foulcommit"
:event/elapsed 35
:event/subtype "hands"
:event/player1 "Adel Taarabt"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2513364"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_3328"}

{:event/type "shotoff"
:event/elapsed 35
:event/subtype "direct_freekick"
:event/player1 "Jordi Gomez"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2513378"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_3328"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Jamie Mackie"
:event/subtype "pushing"
:event/player1 "David Jones"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2513394"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_3328"}

{:event/type "shotoff"
:event/elapsed 39
:event/subtype "shot"
:event/player1 "Franco Di Santo"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2513421"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_3328"}

{:event/type "shotoff"
:event/elapsed 41
:event/subtype "header"
:event/player1 "Jamie Mackie"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2513461"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3328"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Franco Di Santo"
:event/subtype "pushing"
:event/player1 "Jose Bosingwa"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2513493"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Jean Beausejour"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2513507"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Ronnie Stam"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2513512"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Ronnie Stam"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2513517"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_3328"}

{:event/type "corner"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Ronnie Stam"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2513517"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_3328"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "shot"
:event/player1 "Shaun Wright-Phillips"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2513538"
:event/minute 46
:event/match_id "match_3328"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 45
:event/player2 "Ronnie Stam"
:event/subtype "from_behind"
:event/player1 "Adel Taarabt"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2513553"
:event/minute 47
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Armand Traore"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2513620"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_3328"}

{:event/type "card"
:event/elapsed_plus 2
:event/elapsed 45
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Adel Taarabt"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_2513557"
:event/minute 47
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Ronnie Stam"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2513559"
:event/minute 48
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Jamie Mackie"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2513630"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Samba Diakite"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_2513643"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_3328"}

{:event/type "shoton"
:event/elapsed 51
:event/subtype "shot"
:event/player1 "James McCarthy"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_2513661"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Emmerson Boyce"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2513684"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_3328"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Jean Beausejour"
:event/subtype "pushing"
:event/player1 "Shaun Wright-Phillips"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2513687"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_3328"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "James McCarthy"
:event/subtype "dangerous_play"
:event/player1 "Stephane M'Bia"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2513710"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_3328"}

{:event/type "shoton"
:event/elapsed 55
:event/subtype "shot"
:event/player1 "Jordi Gomez"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_2513742"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "David Jones"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2513749"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_3328"}

{:event/type "corner"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "David Jones"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2513749"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "David Jones"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_2513755"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Jean Beausejour"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2513760"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_3328"}

{:event/type "corner"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Jean Beausejour"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2513760"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Jean Beausejour"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2513762"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_3328"}

{:event/type "shoton"
:event/elapsed 57
:event/subtype "volley"
:event/player1 "David Jones"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_2513767"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_3328"}

{:event/type "shotoff"
:event/elapsed 57
:event/subtype "crossbar"
:event/player1 "Jordi Gomez"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2513768"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Franco Di Santo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2513785"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3328"}

{:event/type "corner"
:event/elapsed 59
:event/subtype "short"
:event/player1 "Jean Beausejour"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2513788"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Jean Beausejour"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2513789"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "James McCarthy"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_2513794"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_3328"}

{:event/type "shotoff"
:event/elapsed 60
:event/subtype "shot"
:event/player1 "David Jones"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2513808"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_3328"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Arouna Kone"
:event/subtype "advantage"
:event/player1 "Stephane M'Bia"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2513850"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Ronnie Stam"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2513885"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_3328"}

{:event/type "corner"
:event/elapsed 64
:event/subtype "short"
:event/player1 "Ronnie Stam"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2513889"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "David Jones"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2513895"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_3328"}

{:event/type "corner"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "David Jones"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2513895"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Jean Beausejour"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_2513901"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Jean Beausejour"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_2513904"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_3328"}

{:event/type "corner"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Jean Beausejour"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_2513904"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_3328"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Ryan Nelsen"
:event/subtype "from_behind"
:event/player1 "James McArthur"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2513963"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Jamie Mackie"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2513976"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_3328"}

{:event/type "shoton"
:event/elapsed 69
:event/subtype "volley"
:event/player1 "Stephane M'Bia"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_2513979"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Shaun Wright-Phillips"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2513985"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_3328"}

{:event/type "corner"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Shaun Wright-Phillips"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2513985"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Shaun Wright-Phillips"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_2514021"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3328"}

{:event/type "goal"
:event/elapsed 71
:event/player2 "Shaun Wright-Phillips"
:event/subtype "shot"
:event/player1 "Djibril Cisse"
:event/sortorder 3
:event/team "away"
:event/id "event_2514009"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Jean Beausejour"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2514063"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3328"}

{:event/type "goal"
:event/elapsed 74
:event/player2 "Jean Beausejour"
:event/subtype "shot"
:event/player1 "James McCarthy"
:event/sortorder 0
:event/team "home"
:event/id "event_2514057"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_3328"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Franco Di Santo"
:event/subtype "from_behind"
:event/player1 "Ryan Nelsen"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2514211"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_3328"}

{:event/type "shoton"
:event/elapsed 87
:event/subtype "shot"
:event/player1 "Jordi Gomez"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_2514256"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_3328"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player2 "Clint Hill"
:event/subtype "dangerous_play"
:event/player1 "Mauro Boselli"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2514276"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Esteban Granero"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2514313"
:event/minute 91
:event/match_id "match_3328"}

{:event/type "corner"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Esteban Granero"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2514313"
:event/minute 91
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Esteban Granero"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2514317"
:event/minute 91
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Esteban Granero"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2514364"
:event/minute 93
:event/match_id "match_3328"}

{:event/type "corner"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Esteban Granero"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2514364"
:event/minute 93
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Esteban Granero"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2514366"
:event/minute 93
:event/match_id "match_3328"}

{:event/type "shotoff"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "header"
:event/player1 "Jamie Mackie"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2514368"
:event/minute 94
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Shaun Maloney"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2514384"
:event/minute 95
:event/match_id "match_3328"}

{:event/type "cross"
:event/elapsed_plus 6
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Shaun Maloney"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2514391"
:event/minute 96
:event/match_id "match_3328"}

{:event/type "corner"
:event/elapsed_plus 6
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Shaun Maloney"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2514391"
:event/minute 96
:event/match_id "match_3328"}


]

