
;;# data
[
{:match/id "match_8477"
:match/league "Germany 1. Bundesliga"
:match/hometeam "VfB Stuttgart"
:match/awayteam "TSG 1899 Hoffenheim"
:match/score "1:1"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "goal"
:event/elapsed 11
:event/player1 "Sejad Salihovic"
:event/sortorder 0
:event/team "away"
:event/id "event_1311021"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_8477"}

{:event/type "card"
:event/elapsed 15
:event/card_type "y"
:event/player1 "Arthur Boka"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1311128"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_8477"}

{:event/type "goal"
:event/elapsed 34
:event/player1 "Martin Harnik"
:event/sortorder 0
:event/team "home"
:event/id "event_1311216"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_8477"}

{:event/type "card"
:event/elapsed 41
:event/card_type "r"
:event/player1 "Isaac Vorsah"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1311479"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_8477"}

{:event/type "card"
:event/elapsed 67
:event/card_type "y"
:event/player1 "Sejad Salihovic"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1311970"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_8477"}

{:event/type "card"
:event/elapsed 68
:event/card_type "y"
:event/player1 "Tobias Weis"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1311971"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_8477"}

{:event/type "card"
:event/elapsed 75
:event/card_type "y"
:event/player1 "Martin Harnik"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1312107"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_8477"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Cacau"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1312307"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_8477"}


]

