
;;# data
[
{:match/id "match_7507"
:match/league "France Ligue 1"
:match/hometeam "Stade Rennais FC"
:match/awayteam "Olympique de Marseille"
:match/score "0:1"
:match/hometeam_goals "0"
:match/awayteam_goals "1"}

{:event/type "foulcommit"
:event/elapsed 1
:event/player2 "Georges N'Koudou"
:event/player1 "Steven Moreira"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5077433"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_7507"}

{:event/type "card"
:event/elapsed 1
:event/card_type "y"
:event/player1 "Steven Moreira"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_5077434"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_7507"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Benjamin Mendy"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5077435"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_7507"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Mehdi Zeffane"
:event/player1 "Benjamin Mendy"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5077440"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_7507"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Mehdi Zeffane"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5077442"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_7507"}

{:event/type "foulcommit"
:event/elapsed 8
:event/player2 "Jeremie Boga"
:event/player1 "Lassana Diarra"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5077446"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_7507"}

{:event/type "shoton"
:event/elapsed 9
:event/subtype "blocked_shot"
:event/player1 "Ousmane Dembele"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_5077449"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_7507"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Yacouba Sylla"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5077447"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_7507"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Remy Cabella"
:event/player1 "Mexer"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5077451"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_7507"}

{:event/type "shoton"
:event/elapsed 12
:event/subtype "direct_freekick"
:event/player1 "Romain Alessandrini"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_5077452"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_7507"}

{:event/type "cross"
:event/elapsed 13
:event/subtype "cross"
:event/player1 "Romain Alessandrini"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5077454"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_7507"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Gelson Fernandes"
:event/subtype "pull"
:event/player1 "Michy Batshuayi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5077456"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_7507"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "Mauricio Isla"
:event/player1 "Mehdi Zeffane"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5077459"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_7507"}

{:event/type "shotoff"
:event/elapsed 19
:event/subtype "deflected"
:event/player1 "Benjamin Andre"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5077462"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_7507"}

{:event/type "corner"
:event/elapsed 20
:event/subtype "cross_right"
:event/player1 "Ousmane Dembele"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5077463"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_7507"}

{:event/type "goal"
:event/elapsed 21
:event/player2 "Mauricio Isla"
:event/subtype "distance"
:event/player1 "Remy Cabella"
:event/sortorder 0
:event/team "away"
:event/id "event_5077466"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_7507"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Brice Dja Djedje"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5077470"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_7507"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Jeremie Boga"
:event/subtype "trip"
:event/player1 "Karim Rekik"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5077472"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_7507"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Cheikh Mbengue"
:event/subtype "dangerous_play"
:event/player1 "Remy Cabella"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5077473"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_7507"}

{:event/type "card"
:event/elapsed 26
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Remy Cabella"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_5077474"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_7507"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Ousmane Dembele"
:event/player1 "Brice Dja Djedje"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5077476"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_7507"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Romain Alessandrini"
:event/subtype "pushing"
:event/player1 "Cheikh Mbengue"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5077483"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_7507"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Benjamin Andre"
:event/player1 "Romain Alessandrini"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5077484"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_7507"}

{:event/type "shotoff"
:event/elapsed 34
:event/subtype "shot"
:event/player1 "Ousmane Dembele"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5077491"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_7507"}

{:event/type "shotoff"
:event/elapsed 37
:event/subtype "miss_kick"
:event/player1 "Jeremie Boga"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5077493"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_7507"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Kamil Grosicki"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5077495"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_7507"}

{:event/type "corner"
:event/elapsed 39
:event/subtype "cross_left"
:event/player1 "Kamil Grosicki"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_5077496"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_7507"}

{:event/type "shotoff"
:event/elapsed 40
:event/subtype "shot"
:event/player1 "Jeremie Boga"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5077497"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_7507"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Ousmane Dembele"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5077499"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_7507"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Mauricio Isla"
:event/player1 "Benjamin Andre"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5077501"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_7507"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Benjamin Mendy"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5077502"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_7507"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Lassana Diarra"
:event/player1 "Ousmane Dembele"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5077504"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_7507"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Lassana Diarra"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_5077505"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_7507"}

{:event/type "shoton"
:event/elapsed 43
:event/subtype "deflected"
:event/player1 "Georges N'Koudou"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_5077507"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_7507"}

{:event/type "corner"
:event/elapsed 43
:event/subtype "cross_left"
:event/player1 "Georges N'Koudou"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_5077508"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_7507"}

{:event/type "shotoff"
:event/elapsed 43
:event/subtype "header"
:event/player1 "Nicolas N'Koulou"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5077509"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_7507"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Georges N'Koudou"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5077511"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_7507"}

{:event/type "corner"
:event/elapsed 45
:event/subtype "short_right"
:event/player1 "Romain Alessandrini"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_5077513"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_7507"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Georges N'Koudou"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5077514"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_7507"}

{:event/type "shoton"
:event/elapsed 46
:event/subtype "shot"
:event/player1 "Georges N'Koudou"
:event/sortorder 5
:event/team "away"
:event/event_type "shoton"
:event/id "event_5077522"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_7507"}

{:event/type "corner"
:event/elapsed 46
:event/subtype "short_left"
:event/player1 "Remy Cabella"
:event/sortorder 6
:event/team "away"
:event/event_type "corner"
:event/id "event_5077622"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_7507"}

{:event/type "shoton"
:event/elapsed 47
:event/subtype "deflected"
:event/player1 "Georges N'Koudou"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_5077523"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_7507"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Georges N'Koudou"
:event/player1 "Steven Moreira"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5077526"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_7507"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Jacques Alaixys Romao"
:event/subtype "dangerous_play"
:event/player1 "Benjamin Andre"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5077527"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_7507"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Remy Cabella"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5077528"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_7507"}

{:event/type "shotoff"
:event/elapsed 49
:event/subtype "header"
:event/player1 "Nicolas N'Koulou"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5077529"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_7507"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Lucas Ariel Ocampos"
:event/player1 "Benjamin Andre"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5077534"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_7507"}

{:event/type "card"
:event/elapsed 51
:event/card_type "y"
:event/player1 "Benjamin Andre"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_5077535"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_7507"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Remy Cabella"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5077536"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_7507"}

{:event/type "shotoff"
:event/elapsed 52
:event/subtype "header"
:event/player1 "Michy Batshuayi"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5077537"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_7507"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Ousmane Dembele"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5077541"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_7507"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Ousmane Dembele"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5077544"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_7507"}

{:event/type "shoton"
:event/elapsed 55
:event/subtype "blocked_shot"
:event/player1 "Gelson Fernandes"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_5077547"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_7507"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Lucas Ariel Ocampos"
:event/subtype "dangerous_play"
:event/player1 "Mexer"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5077548"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_7507"}

{:event/type "card"
:event/elapsed 56
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Mexer"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_5077549"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_7507"}

{:event/type "shoton"
:event/elapsed 57
:event/subtype "blocked_shot"
:event/player1 "Benjamin Andre"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_5077550"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_7507"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Brice Dja Djedje"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5077554"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_7507"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Remy Cabella"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_5077556"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_7507"}

{:event/type "shotoff"
:event/elapsed 60
:event/subtype "bicycle_kick"
:event/player1 "Lucas Ariel Ocampos"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5077557"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_7507"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Brice Dja Djedje"
:event/player1 "Ousmane Dembele"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5077563"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_7507"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Remy Cabella"
:event/subtype "pushing"
:event/player1 "Gelson Fernandes"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5077565"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_7507"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Juan Quintero"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5077572"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_7507"}

{:event/type "shoton"
:event/elapsed 68
:event/subtype "blocked_shot"
:event/player1 "Juan Quintero"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_5077574"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_7507"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Steven Moreira"
:event/player1 "Michy Batshuayi"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5077576"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_7507"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Kamil Grosicki"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5077578"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_7507"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Kamil Grosicki"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5077581"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_7507"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Steven Moreira"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5077584"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_7507"}

{:event/type "shoton"
:event/elapsed 78
:event/subtype "header"
:event/player1 "Benjamin Andre"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_5077585"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_7507"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Kamil Grosicki"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5077586"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_7507"}

{:event/type "foulcommit"
:event/elapsed 78
:event/player2 "Lucas Ariel Ocampos"
:event/player1 "Benjamin Andre"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5077588"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_7507"}

{:event/type "shoton"
:event/elapsed 79
:event/subtype "distance"
:event/player1 "Remy Cabella"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_5077589"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_7507"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Benjamin Andre"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5077592"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_7507"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Steven Moreira"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5077596"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_7507"}

{:event/type "corner"
:event/elapsed 84
:event/subtype "cross_right"
:event/player1 "Kamil Grosicki"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5077597"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_7507"}

{:event/type "shoton"
:event/elapsed 85
:event/subtype "blocked_shot"
:event/player1 "Ousmane Dembele"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_5077600"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_7507"}

{:event/type "corner"
:event/elapsed 85
:event/subtype "cross_left"
:event/player1 "Kamil Grosicki"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_5077602"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_7507"}

{:event/type "shoton"
:event/elapsed 86
:event/subtype "distance"
:event/player1 "Michy Batshuayi"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_5077604"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_7507"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Remy Cabella"
:event/player1 "Sylvain Armand"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5077606"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_7507"}

{:event/type "card"
:event/elapsed 88
:event/card_type "y"
:event/player1 "Sylvain Armand"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_5077607"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_7507"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Abdelaziz Barrada"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5077608"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_7507"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player2 "Juan Quintero"
:event/player1 "Jacques Alaixys Romao"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5077610"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_7507"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Juan Quintero"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5077611"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_7507"}

{:event/type "corner"
:event/elapsed 90
:event/subtype "cross_right"
:event/player1 "Juan Quintero"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_5077613"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_7507"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Benjamin Mendy"
:event/player1 "Ousmane Dembele"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5077614"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_7507"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/subtype "stall_time"
:event/player1 "Steve Mandanda"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_5077615"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_7507"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Juan Quintero"
:event/player1 "Lucas Ariel Ocampos"
:event/sortorder 6
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5077618"
:event/minute 91
:event/match_id "match_7507"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Michy Batshuayi"
:event/player1 "Steven Moreira"
:event/sortorder 7
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5077619"
:event/minute 92
:event/match_id "match_7507"}


]

