
;;# data
[
{:match/id "match_3571"
:match/league "England Premier League"
:match/hometeam "Everton"
:match/awayteam "Newcastle United"
:match/score "2:2"
:match/hometeam_goals "2"
:match/awayteam_goals "2"}

{:event/type "foulcommit"
:event/elapsed 1
:event/player1 "Hatem Ben Arfa"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2355670"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_3571"}

{:event/type "shoton"
:event/elapsed 2
:event/subtype "shot"
:event/player1 "Marouane Fellaini"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_2355672"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_3571"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Papiss Cisse"
:event/subtype "serious_foul"
:event/player1 "Philip Neville"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2355684"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_3571"}

{:event/type "card"
:event/elapsed 7
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Philip Neville"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_2355685"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_3571"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Marouane Fellaini"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2355692"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_3571"}

{:event/type "shotoff"
:event/elapsed 11
:event/subtype "big chance shot"
:event/player1 "Steven Pienaar"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2355702"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_3571"}

{:event/type "shoton"
:event/elapsed 13
:event/subtype "blocked_shot"
:event/player1 "Leon Osman"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_2355705"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_3571"}

{:event/type "goal"
:event/elapsed 15
:event/player2 "Steven Pienaar"
:event/subtype "shot"
:event/player1 "Leighton Baines"
:event/sortorder 5
:event/team "home"
:event/id "event_2355710"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_3571"}

{:event/type "shoton"
:event/elapsed 19
:event/subtype "blocked_shot"
:event/player1 "Kevin Mirallas"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_2355716"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_3571"}

{:event/type "shotoff"
:event/elapsed 20
:event/subtype "big chance shot"
:event/player1 "Kevin Mirallas"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2355722"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_3571"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Sylvain Distin"
:event/player1 "Papiss Cisse"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2355725"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_3571"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Kevin Mirallas"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2355728"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_3571"}

{:event/type "corner"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Kevin Mirallas"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2355728"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_3571"}

{:event/type "shoton"
:event/elapsed 23
:event/subtype "shot"
:event/player1 "Kevin Mirallas"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_2355731"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_3571"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player1 "Marouane Fellaini"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2355742"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_3571"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Sylvain Marveaux"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2355743"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_3571"}

{:event/type "shotoff"
:event/elapsed 27
:event/subtype "big chance shot"
:event/player1 "Papiss Cisse"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2355744"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_3571"}

{:event/type "foulcommit"
:event/elapsed 30
:event/player2 "Tony Hibbert"
:event/player1 "Vurnon Anita"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2355754"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_3571"}

{:event/type "card"
:event/elapsed 30
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Vurnon Anita"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_2355755"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_3571"}

{:event/type "shotoff"
:event/elapsed 31
:event/subtype "post"
:event/player1 "Phil Jagielka"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2355756"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_3571"}

{:event/type "foulcommit"
:event/elapsed 34
:event/subtype "hands"
:event/player1 "Leon Osman"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2355759"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_3571"}

{:event/type "shotoff"
:event/elapsed 37
:event/subtype "deflected"
:event/player1 "Hatem Ben Arfa"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2355763"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_3571"}

{:event/type "shoton"
:event/elapsed 37
:event/subtype "shot"
:event/player1 "Sylvain Marveaux"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_2355765"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_3571"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Nikica Jelavic"
:event/player1 "James Perch"
:event/sortorder 7
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2355766"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_3571"}

{:event/type "card"
:event/elapsed 37
:event/card_type "y"
:event/player1 "James Perch"
:event/sortorder 8
:event/team "away"
:event/event_type "card"
:event/id "event_2355767"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_3571"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Steven Taylor"
:event/player1 "Kevin Mirallas"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2355773"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_3571"}

{:event/type "shoton"
:event/elapsed 41
:event/subtype "shot"
:event/player1 "Kevin Mirallas"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_2355776"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3571"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Nikica Jelavic"
:event/subtype "advantage"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2355778"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_3571"}

{:event/type "shotoff"
:event/elapsed 43
:event/subtype "big chance shot"
:event/player1 "Steven Pienaar"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2355780"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_3571"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player1 "Marouane Fellaini"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2355787"
:event/minute 46
:event/match_id "match_3571"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 45
:event/player1 "Tony Hibbert"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2355789"
:event/minute 47
:event/match_id "match_3571"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2355806"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_3571"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Kevin Mirallas"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_2355808"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_3571"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "serious_foul"
:event/player1 "Jonas Gutierrez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2355791"
:event/minute 48
:event/match_id "match_3571"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2355793"
:event/minute 48
:event/match_id "match_3571"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player1 "Victor Anichebe"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2355810"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_3571"}

{:event/type "goal"
:event/elapsed 49
:event/player2 "Yohan Cabaye"
:event/subtype "shot"
:event/player1 "Demba Ba"
:event/sortorder 3
:event/team "away"
:event/id "event_2355811"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_3571"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Hatem Ben Arfa"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2355816"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3571"}

{:event/type "shotoff"
:event/elapsed 51
:event/subtype "header"
:event/player1 "Demba Ba"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2355817"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3571"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Leon Osman"
:event/player1 "Papiss Cisse"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2355827"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_3571"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_2355828"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_3571"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "James Perch"
:event/player1 "Kevin Mirallas"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2355830"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3571"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Hatem Ben Arfa"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2355831"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3571"}

{:event/type "shotoff"
:event/elapsed 56
:event/subtype "deflected"
:event/player1 "Marouane Fellaini"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2355833"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_3571"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2355834"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_3571"}

{:event/type "corner"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2355834"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_3571"}

{:event/type "shotoff"
:event/elapsed 56
:event/subtype "bad shot"
:event/player1 "Leon Osman"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2355835"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_3571"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Jonas Gutierrez"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_2355839"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_3571"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2355840"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3571"}

{:event/type "corner"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2355840"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3571"}

{:event/type "foulcommit"
:event/elapsed 59
:event/player1 "Philip Neville"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2355843"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_3571"}

{:event/type "shotoff"
:event/elapsed 62
:event/subtype "volley"
:event/player1 "Papiss Cisse"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2355849"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_3571"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Leon Osman"
:event/player1 "Yohan Cabaye"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2355851"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_3571"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Steven Pienaar"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2355853"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3571"}

{:event/type "corner"
:event/elapsed 63
:event/subtype "short"
:event/player1 "Steven Pienaar"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2355854"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3571"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Jonas Gutierrez"
:event/player1 "Victor Anichebe"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2355855"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3571"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Steve Harper"
:event/subtype "serious_foul"
:event/player1 "Victor Anichebe"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2355856"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_3571"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Davide Santon"
:event/subtype "from_behind"
:event/player1 "Kevin Mirallas"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2355863"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3571"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_2355866"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_3571"}

{:event/type "corner"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_2355866"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_3571"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "James Perch"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_2355869"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_3571"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_2355870"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_3571"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "James Perch"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2355872"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_3571"}

{:event/type "shotoff"
:event/elapsed 70
:event/subtype "deflected"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2355874"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_3571"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_2355876"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_3571"}

{:event/type "corner"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_2355876"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_3571"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Tony Hibbert"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2355878"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3571"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Leighton Baines"
:event/player1 "Papiss Cisse"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2355891"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3571"}

{:event/type "shotoff"
:event/elapsed 75
:event/subtype "big chance shot"
:event/player1 "Leon Osman"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2355893"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3571"}

{:event/type "shoton"
:event/elapsed 77
:event/subtype "header"
:event/player1 "Victor Anichebe"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_2355897"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_3571"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Tony Hibbert"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2355899"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_3571"}

{:event/type "foulcommit"
:event/elapsed 79
:event/subtype "serious_foul"
:event/player1 "Steven Pienaar"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2355900"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_3571"}

{:event/type "shotoff"
:event/elapsed 79
:event/subtype "crossbar"
:event/player1 "Victor Anichebe"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2355902"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_3571"}

{:event/type "card"
:event/elapsed 79
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Steven Pienaar"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_2355901"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_3571"}

{:event/type "shotoff"
:event/elapsed 81
:event/subtype "big chance shot"
:event/player1 "Demba Ba"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2355905"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_3571"}

{:event/type "shotoff"
:event/elapsed 82
:event/subtype "deflected"
:event/player1 "Kevin Mirallas"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2355909"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_3571"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_2355910"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_3571"}

{:event/type "foulcommit"
:event/elapsed 85
:event/subtype "serious_foul"
:event/player1 "Marouane Fellaini"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2355914"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_3571"}

{:event/type "card"
:event/elapsed 85
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Marouane Fellaini"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_2355915"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_3571"}

{:event/type "shoton"
:event/elapsed 86
:event/subtype "shot"
:event/player1 "Hatem Ben Arfa"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_2355918"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3571"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player1 "Shola Ameobi"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2355919"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3571"}

{:event/type "card"
:event/elapsed 86
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Shola Ameobi"
:event/sortorder 6
:event/team "away"
:event/event_type "card"
:event/id "event_2355922"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3571"}

{:event/type "goal"
:event/elapsed 88
:event/player2 "Steven Pienaar"
:event/subtype "shot"
:event/player1 "Victor Anichebe"
:event/sortorder 1
:event/team "home"
:event/id "event_2355929"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_3571"}

{:event/type "goal"
:event/elapsed 90
:event/player2 "Shola Ameobi"
:event/subtype "shot"
:event/player1 "Demba Ba"
:event/sortorder 0
:event/team "away"
:event/id "event_2355930"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3571"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Yohan Cabaye"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_2355934"
:event/minute 91
:event/match_id "match_3571"}

{:event/type "foulcommit"
:event/elapsed_plus 4
:event/elapsed 90
:event/player1 "Demba Ba"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2355940"
:event/minute 94
:event/match_id "match_3571"}

{:event/type "foulcommit"
:event/elapsed_plus 4
:event/elapsed 90
:event/player1 "Victor Anichebe"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2355941"
:event/minute 94
:event/match_id "match_3571"}


]

