
;;# data
[
{:match/id "match_24508"
:match/league "Spain LIGA BBVA"
:match/hometeam "UD Las Palmas"
:match/awayteam "Sevilla FC"
:match/score "2:0"
:match/hometeam_goals "2"
:match/awayteam_goals "0"}

{:event/type "shoton"
:event/elapsed 1
:event/subtype "volley"
:event/player1 "Sergio Ezequiel Araujo"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_4822471"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_24508"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "Roque Mesa"
:event/subtype "dangerous_play"
:event/player1 "Grzegorz Krychowiak"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4822506"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Jonathan Viera"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4822516"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_24508"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "Jonathan Viera"
:event/subtype "trip"
:event/player1 "Grzegorz Krychowiak"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4822527"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Jonathan Viera"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4822559"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_24508"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Hernan"
:event/subtype "trip"
:event/player1 "Michael Krohn-Dehli"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4822602"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_24508"}

{:event/type "foulcommit"
:event/elapsed 6
:event/player2 "Wakaso Mubarak"
:event/subtype "trip"
:event/player1 "Michael Krohn-Dehli"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4823581"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_24508"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Vicente Iborra"
:event/subtype "trip"
:event/player1 "Wakaso Mubarak"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4822689"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_24508"}

{:event/type "card"
:event/elapsed 9
:event/card_type "y"
:event/player1 "Wakaso Mubarak"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4822693"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Coke"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4822737"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_24508"}

{:event/type "shotoff"
:event/elapsed 10
:event/subtype "shot"
:event/player1 "Ciro Immobile"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4822744"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_24508"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Dani Castellano"
:event/subtype "trip"
:event/player1 "Coke"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4822769"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Sergio Ezequiel Araujo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4822782"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_24508"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Sebastian Cristoforo"
:event/subtype "pull"
:event/player1 "David Simon"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4822821"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_24508"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Wakaso Mubarak"
:event/subtype "trip"
:event/player1 "Grzegorz Krychowiak"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4822862"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_24508"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Pedro Bigas"
:event/subtype "trip"
:event/player1 "Fernando Llorente"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4822984"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_24508"}

{:event/type "card"
:event/elapsed 19
:event/card_type "y"
:event/player1 "Fernando Llorente"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_4822986"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Sergio Ezequiel Araujo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4823041"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_24508"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Benoit Tremoulinas"
:event/subtype "trip"
:event/player1 "David Simon"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4823062"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Michael Krohn-Dehli"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4823077"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_24508"}

{:event/type "shoton"
:event/elapsed 23
:event/subtype "blocked_shot"
:event/player1 "Coke"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4823079"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_24508"}

{:event/type "shoton"
:event/elapsed 24
:event/subtype "shot"
:event/player1 "Fernando Llorente"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4823112"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_24508"}

{:event/type "shotoff"
:event/elapsed 25
:event/subtype "shot"
:event/player1 "Dani Castellano"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4823130"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_24508"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Grzegorz Krychowiak"
:event/subtype "trip"
:event/player1 "Jonathan Viera"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4823161"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_24508"}

{:event/type "foulcommit"
:event/elapsed 27
:event/subtype "hands"
:event/player1 "Sebastian Cristoforo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4823401"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_24508"}

{:event/type "shotoff"
:event/elapsed 30
:event/subtype "shot"
:event/player1 "Coke"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4823242"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_24508"}

{:event/type "goal"
:event/elapsed 30
:event/player2 "Sergio Ezequiel Araujo"
:event/subtype "shot"
:event/player1 "Roque Mesa"
:event/sortorder 4
:event/team "home"
:event/id "event_4823263"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Coke"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4823311"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_24508"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Sebastian Cristoforo"
:event/subtype "pushing"
:event/player1 "Roque Mesa"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4823336"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Michael Krohn-Dehli"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4823349"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Coke"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4823371"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_24508"}

{:event/type "shotoff"
:event/elapsed 35
:event/subtype "shot"
:event/player1 "Michael Krohn-Dehli"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4823389"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Vicente Iborra"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4823428"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Sebastian Cristoforo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4823436"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_24508"}

{:event/type "shotoff"
:event/elapsed 38
:event/subtype "shot"
:event/player1 "Sergio Ezequiel Araujo"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4823459"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Ciro Immobile"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4823478"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_24508"}

{:event/type "shoton"
:event/elapsed 42
:event/subtype "blocked_shot"
:event/player1 "Roque Mesa"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4823512"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_24508"}

{:event/type "corner"
:event/elapsed 42
:event/subtype "cross_left"
:event/player1 "Jonathan Viera"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4823518"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_24508"}

{:event/type "shotoff"
:event/elapsed 42
:event/subtype "deflected"
:event/player1 "Wakaso Mubarak"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4823520"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_24508"}

{:event/type "corner"
:event/elapsed 43
:event/subtype "cross_right"
:event/player1 "Wakaso Mubarak"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4823522"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_24508"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Benoit Tremoulinas"
:event/subtype "pull"
:event/player1 "David Simon"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4823534"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_24508"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Ciro Immobile"
:event/subtype "obstruction"
:event/player1 "Artiles Oliva Aythami"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4823539"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_24508"}

{:event/type "card"
:event/elapsed 45
:event/card_type "y"
:event/player1 "Artiles Oliva Aythami"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4823540"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Michael Krohn-Dehli"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4823546"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Jonathan Viera"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4823584"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_24508"}

{:event/type "shotoff"
:event/elapsed 47
:event/subtype "header"
:event/player1 "Sergio Ezequiel Araujo"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4823585"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_24508"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Hernan"
:event/subtype "trip"
:event/player1 "Vicente Iborra"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4823600"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_24508"}

{:event/type "card"
:event/elapsed 52
:event/card_type "y"
:event/player1 "Vicente Iborra"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4823601"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Jonathan Viera"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4823606"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_24508"}

{:event/type "shoton"
:event/elapsed 54
:event/subtype "blocked_shot"
:event/player1 "Jonathan Viera"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4823612"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_24508"}

{:event/type "shoton"
:event/elapsed 57
:event/subtype "shot"
:event/player1 "Jonathan Viera"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4823635"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_24508"}

{:event/type "corner"
:event/elapsed 57
:event/subtype "cross_right"
:event/player1 "Wakaso Mubarak"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4823637"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_24508"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Vicente Iborra"
:event/subtype "trip"
:event/player1 "Pedro Bigas"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4823643"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_24508"}

{:event/type "card"
:event/elapsed 58
:event/card_type "y"
:event/player1 "Pedro Bigas"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4823644"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Michael Krohn-Dehli"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4823654"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_24508"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Wakaso Mubarak"
:event/subtype "trip"
:event/player1 "Vicente Iborra"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4823665"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_24508"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Artiles Oliva Aythami"
:event/subtype "trip"
:event/player1 "Michael Krohn-Dehli"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4823677"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_24508"}

{:event/type "card"
:event/elapsed 67
:event/card_type "y"
:event/player1 "Michael Krohn-Dehli"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4823678"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_24508"}

{:event/type "shoton"
:event/elapsed 68
:event/subtype "blocked_shot"
:event/player1 "Kevin Gameiro"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4823684"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_24508"}

{:event/type "corner"
:event/elapsed 68
:event/subtype "cross_right"
:event/player1 "Jose Antonio Reyes"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4823686"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_24508"}

{:event/type "shotoff"
:event/elapsed 69
:event/subtype "header"
:event/player1 "Thimothee Kolodziejczak"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4823687"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Michael Krohn-Dehli"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4823694"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Michael Krohn-Dehli"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4823697"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_24508"}

{:event/type "shoton"
:event/elapsed 71
:event/subtype "blocked_shot"
:event/player1 "Coke"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4823699"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_24508"}

{:event/type "corner"
:event/elapsed 71
:event/subtype "cross_left"
:event/player1 "Michael Krohn-Dehli"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_4823700"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_24508"}

{:event/type "shoton"
:event/elapsed 71
:event/subtype "blocked_header"
:event/player1 "Grzegorz Krychowiak"
:event/sortorder 4
:event/team "away"
:event/event_type "shoton"
:event/id "event_4823703"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_24508"}

{:event/type "shoton"
:event/elapsed 72
:event/subtype "blocked_shot"
:event/player1 "Grzegorz Krychowiak"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4823704"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_24508"}

{:event/type "corner"
:event/elapsed 72
:event/subtype "cross_right"
:event/player1 "Jose Antonio Reyes"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4823705"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Benoit Tremoulinas"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4823715"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Benoit Tremoulinas"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4823719"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_24508"}

{:event/type "shotoff"
:event/elapsed 74
:event/subtype "bicycle_kick"
:event/player1 "Coke"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4823722"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_24508"}

{:event/type "corner"
:event/elapsed 76
:event/subtype "cross_left"
:event/player1 "Jonathan Viera"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4823739"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_24508"}

{:event/type "shotoff"
:event/elapsed 76
:event/subtype "deflected"
:event/player1 "Hernan"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4823743"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_24508"}

{:event/type "corner"
:event/elapsed 76
:event/subtype "cross_left"
:event/player1 "Jonathan Viera"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_4823745"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Sergio Ezequiel Araujo"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_4823748"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_24508"}

{:event/type "goal"
:event/elapsed 76
:event/player2 "Sergio Ezequiel Araujo"
:event/subtype "header"
:event/player1 "Antolin Alcaraz"
:event/sortorder 5
:event/team "home"
:event/id "event_4823750"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_24508"}

{:event/type "foulcommit"
:event/elapsed 78
:event/player2 "Vitolo"
:event/subtype "trip"
:event/player1 "David Simon"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4823758"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Jose Antonio Reyes"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4823760"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_24508"}

{:event/type "shoton"
:event/elapsed 79
:event/subtype "header"
:event/player1 "Kevin Gameiro"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4823761"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_24508"}

{:event/type "corner"
:event/elapsed 79
:event/subtype "short_right"
:event/player1 "Vitolo"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4823762"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Jose Antonio Reyes"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4823763"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_24508"}

{:event/type "shotoff"
:event/elapsed 79
:event/subtype "header"
:event/player1 "Marco Andreolli"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4823764"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Coke"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4823785"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_24508"}

{:event/type "corner"
:event/elapsed 83
:event/subtype "cross_left"
:event/player1 "Michael Krohn-Dehli"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4823787"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_24508"}

{:event/type "shotoff"
:event/elapsed 83
:event/subtype "header"
:event/player1 "Coke"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4823788"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Michael Krohn-Dehli"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4823794"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Thimothee Kolodziejczak"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4823799"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_24508"}

{:event/type "shotoff"
:event/elapsed 85
:event/subtype "volley"
:event/player1 "Michael Krohn-Dehli"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4823802"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Coke"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4823808"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_24508"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Nabil El Zhar"
:event/subtype "trip"
:event/player1 "Kevin Gameiro"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4823813"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Benoit Tremoulinas"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4823821"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Vicente Iborra"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_4823825"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_24508"}

{:event/type "shoton"
:event/elapsed 90
:event/subtype "big chance volley"
:event/player1 "Coke"
:event/sortorder 5
:event/team "away"
:event/event_type "shoton"
:event/id "event_4823826"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Benoit Tremoulinas"
:event/sortorder 6
:event/team "away"
:event/event_type "cross"
:event/id "event_4823828"
:event/minute 91
:event/match_id "match_24508"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Nabil El Zhar"
:event/subtype "pushing"
:event/player1 "Kevin Gameiro"
:event/sortorder 10
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4823834"
:event/minute 91
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Vitolo"
:event/sortorder 13
:event/team "away"
:event/event_type "cross"
:event/id "event_4823839"
:event/minute 92
:event/match_id "match_24508"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Thimothee Kolodziejczak"
:event/sortorder 14
:event/team "away"
:event/event_type "cross"
:event/id "event_4823840"
:event/minute 93
:event/match_id "match_24508"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Nabil El Zhar"
:event/subtype "trip"
:event/player1 "Jose Antonio Reyes"
:event/sortorder 16
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4823842"
:event/minute 93
:event/match_id "match_24508"}

{:event/type "card"
:event/elapsed_plus 3
:event/elapsed 90
:event/card_type "y"
:event/player1 "Jose Antonio Reyes"
:event/sortorder 17
:event/team "away"
:event/event_type "card"
:event/id "event_4823843"
:event/minute 93
:event/match_id "match_24508"}


]

