
;;# data
[
{:match/id "match_8227"
:match/league "Germany 1. Bundesliga"
:match/hometeam "Hertha BSC Berlin"
:match/awayteam "VfL Bochum"
:match/score "0:0"
:match/hometeam_goals "0"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 53
:event/card_type "y"
:event/player1 "Roman Prokoph"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_932165"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_8227"}

{:event/type "card"
:event/elapsed 56
:event/card_type "y"
:event/player1 "Florian Kringe"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_932218"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_8227"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Philipp Heerwagen"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_932632"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_8227"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Cicero"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_932695"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_8227"}


]

