
;;# data
[
{:match/id "match_7167"
:match/league "France Ligue 1"
:match/hometeam "AS Saint-Étienne"
:match/awayteam "Stade de Reims"
:match/score "4:0"
:match/hometeam_goals "3"
:match/awayteam_goals "1"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Jonathan Brison"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3649782"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_7167"}

{:event/type "shotoff"
:event/elapsed 1
:event/subtype "bicycle_kick"
:event/player1 "Max-Alain Gradel"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3649785"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Kevin Monnet-Paquet"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3649800"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Max-Alain Gradel"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3649805"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_7167"}

{:event/type "corner"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Max-Alain Gradel"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3649805"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_7167"}

{:event/type "shotoff"
:event/elapsed 4
:event/subtype "post"
:event/player1 "Benjamin Corgnet"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3649809"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Diego"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3649830"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Benjamin Corgnet"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3649842"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Max-Alain Gradel"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3649850"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Franck Tabanou"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_3649855"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_7167"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Antoine Devaux"
:event/subtype "pull"
:event/player1 "Loic Perrin"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3649861"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Aissa Mandi"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3649863"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_7167"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Aissa Mandi"
:event/player1 "Benjamin Corgnet"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3649884"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_7167"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Gregory Bourillon"
:event/player1 "Benjamin Corgnet"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3649891"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Franck Tabanou"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3649913"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_7167"}

{:event/type "shotoff"
:event/elapsed 14
:event/subtype "volley"
:event/player1 "Kevin Monnet-Paquet"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3649914"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Diego"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3649922"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Max-Alain Gradel"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3649940"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_7167"}

{:event/type "corner"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Max-Alain Gradel"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3649940"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Jonathan Brison"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3649951"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Max-Alain Gradel"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3649965"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_7167"}

{:event/type "corner"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Max-Alain Gradel"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3649965"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_7167"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Kevin Monnet-Paquet"
:event/player1 "Aissa Mandi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3650002"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Fabien Lemoine"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3650005"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_7167"}

{:event/type "shoton"
:event/elapsed 25
:event/subtype "blocked_shot"
:event/player1 "Max-Alain Gradel"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3650010"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_7167"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Diego"
:event/player1 "Jonathan Brison"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3650016"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_7167"}

{:event/type "shoton"
:event/elapsed 26
:event/subtype "shot"
:event/player1 "Kevin Monnet-Paquet"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3650021"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_7167"}

{:event/type "shoton"
:event/elapsed 27
:event/subtype "deflected"
:event/player1 "Benjamin Moukandjo"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3650410"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_7167"}

{:event/type "goal"
:event/elapsed 27
:event/player1 "Loic Perrin"
:event/sortorder 1
:event/team "home"
:event/id "event_3650039"
:event/event_type "goal"
:event/goal_type "o"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_7167"}

{:event/type "shoton"
:event/elapsed 29
:event/subtype "shot"
:event/player1 "Benjamin Corgnet"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3650068"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_7167"}

{:event/type "shotoff"
:event/elapsed 31
:event/subtype "bad shot"
:event/player1 "Max-Alain Gradel"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3650079"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Benjamin Moukandjo"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3650108"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_7167"}

{:event/type "corner"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Benjamin Moukandjo"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3650108"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_7167"}

{:event/type "foulcommit"
:event/elapsed 34
:event/player2 "Benjamin Corgnet"
:event/player1 "Antoine Devaux"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3650118"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_7167"}

{:event/type "card"
:event/elapsed 35
:event/card_type "y"
:event/player1 "Antoine Devaux"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3650119"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_7167"}

{:event/type "shoton"
:event/elapsed 35
:event/subtype "direct_freekick"
:event/player1 "Max-Alain Gradel"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3650126"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Max-Alain Gradel"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3650129"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_7167"}

{:event/type "corner"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Max-Alain Gradel"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3650129"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_7167"}

{:event/type "shotoff"
:event/elapsed 36
:event/subtype "shot"
:event/player1 "Mevlut Erdinc"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3650132"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Benjamin Moukandjo"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3650141"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_3650151"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Franck Tabanou"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3650182"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Kevin Monnet-Paquet"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3650189"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_7167"}

{:event/type "shoton"
:event/elapsed 41
:event/subtype "shot"
:event/player1 "Max-Alain Gradel"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_3650191"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_3650209"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_7167"}

{:event/type "shoton"
:event/elapsed 43
:event/subtype "shot"
:event/player1 "Gaetan Charbonnier"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3650212"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Diego"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3650215"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_7167"}

{:event/type "corner"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Diego"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3650215"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_7167"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Max-Alain Gradel"
:event/player1 "Aissa Mandi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3650226"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Max-Alain Gradel"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3650227"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_7167"}

{:event/type "foulcommit"
:event/elapsed 46
:event/player2 "Mustapha Bayal Sall"
:event/player1 "Gaetan Charbonnier"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3650280"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Kevin Monnet-Paquet"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3650285"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_7167"}

{:event/type "shotoff"
:event/elapsed 47
:event/subtype "deflected"
:event/player1 "Benjamin Corgnet"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3650290"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Jonathan Brison"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3650294"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_7167"}

{:event/type "shoton"
:event/elapsed 48
:event/subtype "header"
:event/player1 "Benjamin Corgnet"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3650296"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_7167"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Loic Perrin"
:event/player1 "Benjamin Moukandjo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3650305"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_7167"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Franck Tabanou"
:event/player1 "Antoine Devaux"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3650308"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Fabien Lemoine"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3650329"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_7167"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Gaetan Charbonnier"
:event/subtype "pull"
:event/player1 "Max-Alain Gradel"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3650336"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_7167"}

{:event/type "shotoff"
:event/elapsed 54
:event/subtype "shot"
:event/player1 "Benjamin Corgnet"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3650351"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_7167"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Max-Alain Gradel"
:event/player1 "Aissa Mandi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3650373"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Franck Tabanou"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3650377"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_7167"}

{:event/type "shotoff"
:event/elapsed 56
:event/subtype "header"
:event/player1 "Mustapha Bayal Sall"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3650381"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_7167"}

{:event/type "shoton"
:event/elapsed 58
:event/subtype "blocked_shot"
:event/player1 "Kevin Monnet-Paquet"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3650398"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_7167"}

{:event/type "shoton"
:event/elapsed 59
:event/subtype "blocked_shot"
:event/player1 "Kevin Monnet-Paquet"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3650417"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_7167"}

{:event/type "foulcommit"
:event/elapsed 59
:event/player2 "Max-Alain Gradel"
:event/player1 "Gregory Bourillon"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3650420"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_7167"}

{:event/type "card"
:event/elapsed 59
:event/card_type "y"
:event/player1 "Gregory Bourillon"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_3650423"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_7167"}

{:event/type "goal"
:event/elapsed 60
:event/subtype "direct_freekick"
:event/player1 "Max-Alain Gradel"
:event/sortorder 0
:event/team "home"
:event/id "event_3650432"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_7167"}

{:event/type "shotoff"
:event/elapsed 62
:event/subtype "bad shot"
:event/player1 "Max-Alain Gradel"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3650442"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Max-Alain Gradel"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3650475"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_7167"}

{:event/type "corner"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Max-Alain Gradel"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3650475"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_7167"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Benjamin Moukandjo"
:event/player1 "Mustapha Bayal Sall"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3650483"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_7167"}

{:event/type "card"
:event/elapsed 65
:event/card_type "y"
:event/player1 "Mustapha Bayal Sall"
:event/sortorder 3
:event/team "home"
:event/event_type "card"
:event/id "event_3650487"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Diego"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3650495"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_7167"}

{:event/type "shoton"
:event/elapsed 70
:event/subtype "shot"
:event/player1 "Benjamin Moukandjo"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3650532"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Mevlut Erdinc"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3650537"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_7167"}

{:event/type "goal"
:event/elapsed 70
:event/player2 "Mevlut Erdinc"
:event/subtype "header"
:event/player1 "Kevin Monnet-Paquet"
:event/sortorder 3
:event/team "home"
:event/id "event_3650539"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_7167"}

{:event/type "shotoff"
:event/elapsed 74
:event/subtype "shot"
:event/player1 "Antoine Devaux"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3650570"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Romain Hamouma"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3650617"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_7167"}

{:event/type "corner"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Romain Hamouma"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3650617"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Renaud Cohade"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_3650622"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_7167"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Fabien Lemoine"
:event/player1 "Eliran Atar"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3650638"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Romain Hamouma"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3650641"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_7167"}

{:event/type "goal"
:event/elapsed 81
:event/player2 "Romain Hamouma"
:event/subtype "tap_in"
:event/player1 "Mevlut Erdinc"
:event/sortorder 2
:event/team "home"
:event/id "event_3650642"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Antoine Devaux"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3650654"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_7167"}

{:event/type "foulcommit"
:event/elapsed 83
:event/player2 "Diego"
:event/subtype "dangerous_play"
:event/player1 "Jonathan Brison"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3650659"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_7167"}

{:event/type "card"
:event/elapsed 83
:event/card_type "y"
:event/player1 "Jonathan Brison"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_3650662"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Benjamin Moukandjo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3650672"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_7167"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Romain Hamouma"
:event/player1 "Aissa Mandi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3650695"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Kevin Monnet-Paquet"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_3650705"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_7167"}

{:event/type "shoton"
:event/elapsed 87
:event/subtype "blocked_shot"
:event/player1 "Romain Hamouma"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_3650708"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_7167"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Renaud Cohade"
:event/player1 "Prince Oniangue"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3650752"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_7167"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Aissa Mandi"
:event/player1 "Ricky van Wolfswinkel"
:event/sortorder 7
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3650773"
:event/minute 91
:event/match_id "match_7167"}

{:event/type "shotoff"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "deflected"
:event/player1 "Prince Oniangue"
:event/sortorder 8
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3650776"
:event/minute 94
:event/match_id "match_7167"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Eliran Atar"
:event/sortorder 9
:event/team "away"
:event/event_type "corner"
:event/id "event_3650778"
:event/minute 94
:event/match_id "match_7167"}

{:event/type "corner"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Eliran Atar"
:event/sortorder 9
:event/team "away"
:event/event_type "corner"
:event/id "event_3650778"
:event/minute 94
:event/match_id "match_7167"}

{:event/type "shoton"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Ricky van Wolfswinkel"
:event/sortorder 11
:event/team "home"
:event/event_type "shoton"
:event/id "event_3650781"
:event/minute 95
:event/match_id "match_7167"}

{:event/type "shotoff"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "distance"
:event/player1 "Benjamin Moukandjo"
:event/sortorder 13
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3650784"
:event/minute 95
:event/match_id "match_7167"}


]

