
;;# data
[
{:match/id "match_22394"
:match/league "Spain LIGA BBVA"
:match/hometeam "Getafe CF"
:match/awayteam "Levante UD"
:match/score "4:1"
:match/hometeam_goals "4"
:match/awayteam_goals "1"}

{:event/type "goal"
:event/elapsed 5
:event/player1 "Jaime Gavilan"
:event/sortorder 0
:event/team "home"
:event/id "event_1161900"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_22394"}

{:event/type "goal"
:event/elapsed 11
:event/player1 "Adrian Colunga"
:event/sortorder 0
:event/team "home"
:event/id "event_1161901"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_22394"}

{:event/type "goal"
:event/elapsed 14
:event/player1 "Rafa Jorda"
:event/sortorder 0
:event/team "away"
:event/id "event_1161917"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_22394"}

{:event/type "card"
:event/elapsed 28
:event/card_type "y"
:event/player1 "Javier Venta"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1162001"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_22394"}

{:event/type "card"
:event/elapsed 47
:event/card_type "y"
:event/player1 "Rafa Lopez"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1162199"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_22394"}

{:event/type "card"
:event/elapsed 50
:event/card_type "y"
:event/player1 "Rafa Jorda"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1162227"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_22394"}

{:event/type "card"
:event/elapsed 62
:event/card_type "y"
:event/player1 "Derek Boateng"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1162305"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_22394"}

{:event/type "card"
:event/elapsed 77
:event/card_type "y"
:event/player1 "Miguel Robuste"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1162400"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_22394"}

{:event/type "card"
:event/elapsed 85
:event/card_type "y"
:event/player1 "Francisco Javier Casquero"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1162613"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_22394"}

{:event/type "goal"
:event/elapsed 90
:event/player1 "Jaime Gavilan"
:event/sortorder 0
:event/team "home"
:event/id "event_1162530"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_22394"}

{:event/type "goal"
:event/elapsed 90
:event/player1 "Angel Javier Arizmendi"
:event/sortorder 0
:event/team "home"
:event/id "event_1162531"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_22394"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Miguel Torres"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1162532"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_22394"}


]

