
;;# data
[
{:match/id "match_23243"
:match/league "Spain LIGA BBVA"
:match/hometeam "Granada CF"
:match/awayteam "Levante UD"
:match/score "1:1"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "card"
:event/elapsed 3
:event/card_type "y"
:event/player1 "Allan Nyom"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2655461"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_23243"}

{:event/type "card"
:event/elapsed 18
:event/card_type "y"
:event/player1 "Valdo"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2655470"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_23243"}

{:event/type "card"
:event/elapsed 28
:event/card_type "y"
:event/player1 "Loukas Vyntra"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2655474"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_23243"}

{:event/type "card"
:event/elapsed 31
:event/card_type "y"
:event/player1 "Pedro Rios"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2655480"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_23243"}

{:event/type "goal"
:event/elapsed 32
:event/player1 "Guilherme Siqueira"
:event/sortorder 0
:event/team "home"
:event/id "event_2655479"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_23243"}

{:event/type "card"
:event/elapsed 35
:event/card_type "y"
:event/player1 "Mikel Rico"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2655483"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_23243"}

{:event/type "goal"
:event/elapsed 50
:event/player1 "Robert Acquafresca"
:event/sortorder 0
:event/team "away"
:event/id "event_2655497"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_23243"}

{:event/type "card"
:event/elapsed 55
:event/card_type "y"
:event/player1 "Guilherme Siqueira"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2655504"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_23243"}

{:event/type "card"
:event/elapsed 56
:event/card_type "y"
:event/player1 "Jose Recio"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2655505"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_23243"}

{:event/type "card"
:event/elapsed 58
:event/card_type "y"
:event/player1 "Robert Acquafresca"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2655510"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_23243"}

{:event/type "card"
:event/elapsed 66
:event/card_type "y"
:event/player1 "Inigo Lopez"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2655512"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_23243"}

{:event/type "card"
:event/elapsed 75
:event/card_type "y"
:event/player1 "Sergio Ballesteros"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2655531"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_23243"}

{:event/type "card"
:event/elapsed 83
:event/card_type "y"
:event/player1 "Nolito"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2655536"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_23243"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Nabil El Zhar"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2655542"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_23243"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Gabriel Torje"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2655544"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_23243"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Yacine Brahimi"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2655547"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_23243"}


]

