
;;# data
[
{:match/id "match_10684"
:match/league "Italy Serie A"
:match/hometeam "Roma"
:match/awayteam "Bari"
:match/score "4:0"
:match/hometeam_goals "3"
:match/awayteam_goals "1"}

{:event/type "goal"
:event/elapsed 6
:event/player1 "Francesco Totti"
:event/sortorder 0
:event/team "home"
:event/id "event_846616"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_10684"}

{:event/type "goal"
:event/elapsed 14
:event/player1 "Francesco Totti"
:event/sortorder 0
:event/team "home"
:event/id "event_846683"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_10684"}

{:event/type "goal"
:event/elapsed 28
:event/player1 "Francesco Totti"
:event/sortorder 0
:event/team "home"
:event/id "event_846795"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_10684"}

{:event/type "card"
:event/elapsed 43
:event/card_type "y"
:event/player1 "Phillippe Mexes"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_847490"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_10684"}

{:event/type "card"
:event/elapsed 62
:event/card_type "y"
:event/player1 "Andrea Ranocchia"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_847491"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_10684"}

{:event/type "card"
:event/elapsed 71
:event/card_type "y"
:event/player1 "Marco Andreolli"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_847594"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_10684"}

{:event/type "goal"
:event/elapsed 73
:event/player1 "Marco Andreolli"
:event/sortorder 0
:event/team "home"
:event/id "event_847584"
:event/event_type "goal"
:event/goal_type "o"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_10684"}

{:event/type "card"
:event/elapsed 75
:event/card_type "y"
:event/player1 "Massimo Donati"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_847771"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_10684"}

{:event/type "card"
:event/elapsed 86
:event/card_type "y"
:event/player1 "Vladimir Koman"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_847754"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_10684"}


]

