
;;# data
[
{:match/id "match_9321"
:match/league "Germany 1. Bundesliga"
:match/hometeam "Borussia Dortmund"
:match/awayteam "FC Schalke 04"
:match/score "1:2"
:match/hometeam_goals "1"
:match/awayteam_goals "2"}

{:event/type "goal"
:event/elapsed 14
:event/player1 "Ibrahim Afellay"
:event/sortorder 0
:event/team "away"
:event/id "event_2424357"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_9321"}

{:event/type "card"
:event/elapsed 45
:event/card_type "y"
:event/player1 "Marco Hoeger"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2424751"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_9321"}

{:event/type "goal"
:event/elapsed 48
:event/player1 "Marco Hoeger"
:event/sortorder 0
:event/team "away"
:event/id "event_2424903"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_9321"}

{:event/type "goal"
:event/elapsed 55
:event/player1 "Robert Lewandowski"
:event/sortorder 0
:event/team "home"
:event/id "event_2425059"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_9321"}

{:event/type "card"
:event/elapsed 56
:event/card_type "y"
:event/player1 "Julian Schieber"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2425060"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_9321"}

{:event/type "card"
:event/elapsed 62
:event/card_type "y"
:event/player1 "Moritz Leitner"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2425106"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_9321"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Christian Fuchs"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2425534"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_9321"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Lars Unnerstall"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2425535"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_9321"}


]

