
;;# data
[
{:match/id "match_4666"
:match/league "England Premier League"
:match/hometeam "Norwich City"
:match/awayteam "Sunderland"
:match/score "0:3"
:match/hometeam_goals "0"
:match/awayteam_goals "3"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Steven Naismith"
:event/player1 "Patrick van Aanholt"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5495361"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Robert Brady"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5495362"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_4666"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "DeAndre Yedlin"
:event/player1 "Robert Brady"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5495576"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_4666"}

{:event/type "corner"
:event/elapsed 6
:event/subtype "cross_right"
:event/player1 "Robert Brady"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_5495380"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_4666"}

{:event/type "shoton"
:event/elapsed 6
:event/subtype "blocked_shot"
:event/player1 "Jonathan Howson"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_5495381"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_4666"}

{:event/type "shoton"
:event/elapsed 7
:event/subtype "distance"
:event/player1 "Robert Brady"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_5495383"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Martin Olsson"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5495386"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed 13
:event/subtype "cross"
:event/player1 "Robert Brady"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5495404"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_4666"}

{:event/type "shoton"
:event/elapsed 13
:event/subtype "header"
:event/player1 "Dieumerci Mbokani"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5495406"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_4666"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Steven Naismith"
:event/subtype "from_behind"
:event/player1 "Jan Kirchhoff"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5495409"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Jonathan Howson"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5495411"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_4666"}

{:event/type "corner"
:event/elapsed 17
:event/subtype "cross_right"
:event/player1 "Robert Brady"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5495416"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_4666"}

{:event/type "corner"
:event/elapsed 17
:event/subtype "cross_left"
:event/player1 "Robert Brady"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_5495419"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_4666"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Jermain Defoe"
:event/player1 "Matt Jarvis"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5495423"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Lee Cattermole"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5495426"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_4666"}

{:event/type "shotoff"
:event/elapsed 18
:event/subtype "shot"
:event/player1 "Fabio Borini"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5495428"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Patrick van Aanholt"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5495431"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_4666"}

{:event/type "shotoff"
:event/elapsed 19
:event/subtype "bad shot"
:event/player1 "Patrick van Aanholt"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5495434"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "DeAndre Yedlin"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5495449"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Andre Wisdom"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5495460"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_4666"}

{:event/type "shoton"
:event/elapsed 26
:event/subtype "blocked_shot"
:event/player1 "Steven Naismith"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_5495462"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_4666"}

{:event/type "corner"
:event/elapsed 26
:event/subtype "cross_right"
:event/player1 "Robert Brady"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_5495465"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_4666"}

{:event/type "shoton"
:event/elapsed 26
:event/subtype "distance"
:event/player1 "Martin Olsson"
:event/sortorder 5
:event/team "home"
:event/event_type "shoton"
:event/id "event_5495468"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_4666"}

{:event/type "corner"
:event/elapsed 27
:event/subtype "cross_left"
:event/player1 "Gary O'Neil"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5495471"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Wahbi Khazri"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5495485"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/sortorder 2
:event/team "away"
:event/event_type "throwin"
:event/id "event_5495487"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_4666"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Gary O'Neil"
:event/subtype "serious_foul"
:event/player1 "Wahbi Khazri"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5495497"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_4666"}

{:event/type "card"
:event/elapsed 32
:event/card_type "y"
:event/player1 "Wahbi Khazri"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_5495498"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Robert Brady"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5495504"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Fabio Borini"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5495508"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_4666"}

{:event/type "shotoff"
:event/elapsed 35
:event/subtype "volley"
:event/player1 "Lee Cattermole"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5495510"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_4666"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Fabio Borini"
:event/player1 "Steven Naismith"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5495517"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_4666"}

{:event/type "corner"
:event/elapsed 38
:event/subtype "cross_right"
:event/player1 "Robert Brady"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5495525"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_4666"}

{:event/type "shoton"
:event/elapsed 38
:event/subtype "deflected"
:event/player1 "Dieumerci Mbokani"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5495527"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Andre Wisdom"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5495533"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Jermain Defoe"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5495535"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_4666"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Fabio Borini"
:event/subtype "penalty"
:event/player1 "Andre Wisdom"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5495537"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_4666"}

{:event/type "card"
:event/elapsed 40
:event/card_type "y"
:event/player1 "Andre Wisdom"
:event/sortorder 5
:event/team "home"
:event/event_type "card"
:event/id "event_5495540"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_4666"}

{:event/type "goal"
:event/elapsed 41
:event/player1 "Fabio Borini"
:event/sortorder 0
:event/team "away"
:event/id "event_5495539"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Matt Jarvis"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5495542"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Andre Wisdom"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5495549"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Andre Wisdom"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5495552"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_4666"}

{:event/type "corner"
:event/elapsed 46
:event/subtype "cross_left"
:event/player1 "Gary O'Neil"
:event/sortorder 7
:event/team "home"
:event/event_type "corner"
:event/id "event_5495616"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Nathan Redmond"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5495618"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_4666"}

{:event/type "corner"
:event/elapsed 47
:event/subtype "cross_right"
:event/player1 "Gary O'Neil"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_5495621"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_4666"}

{:event/type "shotoff"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "bad shot"
:event/player1 "Fabio Borini"
:event/sortorder 8
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5495566"
:event/minute 47
:event/match_id "match_4666"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 45
:event/player2 "Dieumerci Mbokani"
:event/player1 "Jan Kirchhoff"
:event/sortorder 10
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5495568"
:event/minute 47
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Robert Brady"
:event/sortorder 11
:event/team "home"
:event/event_type "cross"
:event/id "event_5495570"
:event/minute 48
:event/match_id "match_4666"}

{:event/type "shotoff"
:event/elapsed 49
:event/subtype "big chance post"
:event/player1 "Nathan Redmond"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5495625"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_4666"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Fabio Borini"
:event/player1 "Dieumerci Mbokani"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5495632"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_4666"}

{:event/type "shotoff"
:event/elapsed 52
:event/subtype "distance"
:event/player1 "Sebastien Bassong"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5495642"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Fabio Borini"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5495657"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_4666"}

{:event/type "goal"
:event/elapsed 53
:event/player2 "Fabio Borini"
:event/subtype "shot"
:event/player1 "Jermain Defoe"
:event/sortorder 2
:event/team "away"
:event/id "event_5495658"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_4666"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Nathan Redmond"
:event/player1 "Lee Cattermole"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5495675"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Nathan Redmond"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5495676"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_4666"}

{:event/type "shotoff"
:event/elapsed 58
:event/subtype "miss_kick"
:event/player1 "Steven Naismith"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5495677"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_4666"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Gary O'Neil"
:event/subtype "serious_foul"
:event/player1 "Lee Cattermole"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5495686"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_4666"}

{:event/type "card"
:event/elapsed 59
:event/card_type "y"
:event/player1 "Lee Cattermole"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_5495687"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_4666"}

{:event/type "card"
:event/elapsed 59
:event/card_type "y"
:event/subtype "verbal_abuse"
:event/player1 "Martin Olsson"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_5495691"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Andre Wisdom"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5495727"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_4666"}

{:event/type "corner"
:event/elapsed 63
:event/subtype "cross_right"
:event/player1 "Gary O'Neil"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5495731"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_4666"}

{:event/type "corner"
:event/elapsed 63
:event/subtype "cross_right"
:event/player1 "Wesley Hoolahan"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_5495735"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Martin Olsson"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5495746"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_4666"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Wesley Hoolahan"
:event/player1 "Lee Cattermole"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5495754"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Gary O'Neil"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5495759"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_4666"}

{:event/type "shoton"
:event/elapsed 66
:event/subtype "deflected"
:event/player1 "Wesley Hoolahan"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_5495764"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_4666"}

{:event/type "corner"
:event/elapsed 66
:event/subtype "cross_left"
:event/player1 "Gary O'Neil"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_5495766"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_4666"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Lee Cattermole"
:event/player1 "Gary O'Neil"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5495798"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_4666"}

{:event/type "shotoff"
:event/elapsed 70
:event/subtype "direct_freekick"
:event/player1 "Sebastian Larsson"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5495805"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_4666"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Jan Kirchhoff"
:event/player1 "Gary O'Neil"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5495813"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Andre Wisdom"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5495874"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Cameron Jerome"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5495877"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_4666"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Nathan Redmond"
:event/player1 "Jan Kirchhoff"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5495893"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_4666"}

{:event/type "shoton"
:event/elapsed 81
:event/subtype "big chance shot"
:event/player1 "Nathan Redmond"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5495898"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_4666"}

{:event/type "corner"
:event/elapsed 81
:event/subtype "short_right"
:event/player1 "Wesley Hoolahan"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_5495899"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Jonathan Howson"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_5495901"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_4666"}

{:event/type "shotoff"
:event/elapsed 81
:event/subtype "header"
:event/player1 "Wesley Hoolahan"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5495902"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_4666"}

{:event/type "shoton"
:event/elapsed 82
:event/subtype "deflected"
:event/player1 "Nathan Redmond"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5495909"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_4666"}

{:event/type "corner"
:event/elapsed 82
:event/subtype "cross_left"
:event/player1 "Nathan Redmond"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_5495910"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_4666"}

{:event/type "shoton"
:event/elapsed 83
:event/subtype "header"
:event/player1 "Gary O'Neil"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_5495913"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Nathan Redmond"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5495925"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Nathan Redmond"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_5495928"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Wesley Hoolahan"
:event/sortorder 6
:event/team "home"
:event/event_type "cross"
:event/id "event_5495934"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_4666"}

{:event/type "shotoff"
:event/elapsed 86
:event/subtype "bad shot"
:event/player1 "Cameron Jerome"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5495967"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_4666"}

{:event/type "shotoff"
:event/elapsed 87
:event/subtype "shot"
:event/player1 "Gary O'Neil"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5495974"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_4666"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Dieumerci Mbokani"
:event/player1 "Younes Kaboul"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5495982"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Wesley Hoolahan"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5495991"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_4666"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Wesley Hoolahan"
:event/player1 "Fabio Borini"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5495999"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_4666"}

{:event/type "goal"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Sebastian Larsson"
:event/subtype "shot"
:event/player1 "Duncan Watmore"
:event/sortorder 4
:event/team "away"
:event/id "event_5496055"
:event/event_type "goal"
:event/goal_type "n"
:event/minute 91
:event/match_id "match_4666"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Martin Olsson"
:event/player1 "Fabio Borini"
:event/sortorder 7
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5496093"
:event/minute 93
:event/match_id "match_4666"}

{:event/type "shotoff"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Wesley Hoolahan"
:event/sortorder 8
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5496104"
:event/minute 93
:event/match_id "match_4666"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Martin Olsson"
:event/sortorder 10
:event/team "home"
:event/event_type "cross"
:event/id "event_5496124"
:event/minute 94
:event/match_id "match_4666"}

{:event/type "corner"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "cross_left"
:event/player1 "Nathan Redmond"
:event/sortorder 11
:event/team "home"
:event/event_type "corner"
:event/id "event_5496128"
:event/minute 95
:event/match_id "match_4666"}


]

