
;;# data
[
{:match/id "match_6633"
:match/league "France Ligue 1"
:match/hometeam "Olympique de Marseille"
:match/awayteam "Évian Thonon Gaillard FC"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 32
:event/card_type "y"
:event/player1 "Aldo Angoula"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2371783"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_6633"}

{:event/type "goal"
:event/elapsed 33
:event/player1 "Morgan Amalfitano"
:event/sortorder 0
:event/team "home"
:event/id "event_2371782"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_6633"}

{:event/type "card"
:event/elapsed 50
:event/card_type "y"
:event/player1 "Jeremy Morel"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2372029"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_6633"}


]

