
;;# data
[
{:match/id "match_21578"
:match/league "Spain LIGA BBVA"
:match/hometeam "FC Barcelona"
:match/awayteam "Real Madrid CF"
:match/score "3:0"
:match/hometeam_goals "2"
:match/awayteam_goals "0"}

{:event/type "foulcommit"
:event/elapsed 1
:event/player2 "Thierry Henry"
:event/player1 "Michel Salgado"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_528956"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_21578"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Lionel Messi"
:event/player1 "Jose Maria Guti"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_528957"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_21578"}

{:event/type "shotoff"
:event/elapsed 3
:event/subtype "distance"
:event/player1 "Eric Abidal"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_528959"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_21578"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "Thierry Henry"
:event/player1 "Fernando Gago"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_528966"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Thierry Henry"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_528968"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_21578"}

{:event/type "foulcommit"
:event/elapsed 6
:event/player2 "Lionel Messi"
:event/player1 "Sergio Ramos"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_528971"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_21578"}

{:event/type "shoton"
:event/elapsed 6
:event/subtype "shot"
:event/player1 "Lionel Messi"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_528975"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_21578"}

{:event/type "foulcommit"
:event/elapsed 6
:event/player2 "Royston Drenthe"
:event/player1 "Daniel Alves"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_528976"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_21578"}

{:event/type "shotoff"
:event/elapsed 7
:event/subtype "distance"
:event/player1 "Thierry Henry"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_528980"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Samuel Eto'o"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_528982"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Xavi Hernandez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_528995"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_21578"}

{:event/type "corner"
:event/elapsed 11
:event/subtype "short"
:event/player1 "Lionel Messi"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_528997"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Xavi Hernandez"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_528999"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_21578"}

{:event/type "corner"
:event/elapsed 11
:event/subtype "short"
:event/player1 "Xavi Hernandez"
:event/sortorder 5
:event/team "home"
:event/event_type "corner"
:event/id "event_529002"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_21578"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Lionel Messi"
:event/player1 "Wesley Sneijder"
:event/sortorder 6
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_529003"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_21578"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Lionel Messi"
:event/player1 "Fernando Gago"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_529018"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Eric Abidal"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_529021"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_21578"}

{:event/type "shoton"
:event/elapsed 16
:event/subtype "shot"
:event/player1 "Lionel Messi"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_529022"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Thierry Henry"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_529024"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_21578"}

{:event/type "shoton"
:event/elapsed 19
:event/subtype "blocked_shot"
:event/player1 "Eric Abidal"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_529028"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_21578"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Samuel Eto'o"
:event/subtype "from_behind"
:event/player1 "Christoph Metzelder"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_529036"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_21578"}

{:event/type "card"
:event/elapsed 22
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Christoph Metzelder"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_529037"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Royston Drenthe"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_529039"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_21578"}

{:event/type "shoton"
:event/elapsed 24
:event/subtype "shot"
:event/player1 "Wesley Sneijder"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_529040"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Wesley Sneijder"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_529041"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_21578"}

{:event/type "corner"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Wesley Sneijder"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_529041"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Fernando Gago"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_529044"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_21578"}

{:event/type "shoton"
:event/elapsed 26
:event/subtype "shot"
:event/player1 "Royston Drenthe"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_529045"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Wesley Sneijder"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_529046"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_21578"}

{:event/type "corner"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Wesley Sneijder"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_529046"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_21578"}

{:event/type "shotoff"
:event/elapsed 27
:event/subtype "crossbar"
:event/player1 "Gonzalo Higuain"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_529047"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_21578"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Eidur Gudjohnsen"
:event/player1 "Fernando Gago"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_529049"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_21578"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Lionel Messi"
:event/subtype "serious_foul"
:event/player1 "Sergio Ramos"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_529050"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_21578"}

{:event/type "card"
:event/elapsed 28
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Sergio Ramos"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_529051"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Thierry Henry"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_529057"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_21578"}

{:event/type "shoton"
:event/elapsed 33
:event/subtype "shot"
:event/player1 "Thierry Henry"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_529060"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_21578"}

{:event/type "corner"
:event/elapsed 33
:event/subtype "short"
:event/player1 "Xavi Hernandez"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_529061"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_21578"}

{:event/type "shoton"
:event/elapsed 33
:event/subtype "distance"
:event/player1 "Samuel Eto'o"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_529062"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_21578"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Daniel Alves"
:event/player1 "Raul"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_529067"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Xavi Hernandez"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_529070"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Daniel Alves"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_529073"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_21578"}

{:event/type "corner"
:event/elapsed 40
:event/subtype "short"
:event/player1 "Lionel Messi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_529075"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Xavi Hernandez"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_529076"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_21578"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Gonzalo Higuain"
:event/subtype "serious_foul"
:event/player1 "Rafael Marquez"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_529079"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_21578"}

{:event/type "card"
:event/elapsed 40
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Rafael Marquez"
:event/sortorder 5
:event/team "home"
:event/event_type "card"
:event/id "event_529080"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_21578"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Lionel Messi"
:event/subtype "serious_foul"
:event/player1 "Royston Drenthe"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_529082"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_21578"}

{:event/type "card"
:event/elapsed 42
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Royston Drenthe"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_529083"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Daniel Alves"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_529084"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Xavi Hernandez"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_529086"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_21578"}

{:event/type "corner"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Xavi Hernandez"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_529086"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_21578"}

{:event/type "shoton"
:event/elapsed 44
:event/subtype "blocked_shot"
:event/player1 "Samuel Eto'o"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_529089"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_21578"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "unknown"
:event/player1 "Eric Abidal"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_529090"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_21578"}

{:event/type "foulcommit"
:event/elapsed 47
:event/player2 "Samuel Eto'o"
:event/player1 "Raul"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_529097"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Lionel Messi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_529098"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_21578"}

{:event/type "shoton"
:event/elapsed 48
:event/subtype "shot"
:event/player1 "Samuel Eto'o"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_529099"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Eidur Gudjohnsen"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_529100"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_21578"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Raul"
:event/player1 "Eidur Gudjohnsen"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_529102"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_529103"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Jose Maria Guti"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_529106"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Jose Maria Guti"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_529108"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_21578"}

{:event/type "corner"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Jose Maria Guti"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_529108"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_21578"}

{:event/type "shotoff"
:event/elapsed 50
:event/subtype "crossbar"
:event/player1 "Raul"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_529109"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Jose Maria Guti"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_529112"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_21578"}

{:event/type "corner"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Jose Maria Guti"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_529112"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_21578"}

{:event/type "shoton"
:event/elapsed 52
:event/subtype "blocked_shot"
:event/player1 "Lionel Messi"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_529114"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Daniel Alves"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_529115"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_21578"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Raul"
:event/player1 "Yaya Toure"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_529117"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Gonzalo Higuain"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_529120"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_21578"}

{:event/type "shotoff"
:event/elapsed 56
:event/subtype "shot"
:event/player1 "Samuel Eto'o"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_529127"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_21578"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Rafael Marquez"
:event/player1 "Raul"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_529130"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_21578"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player2 "Royston Drenthe"
:event/player1 "Daniel Alves"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_529133"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_21578"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Fernando Gago"
:event/player1 "Lionel Messi"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_529135"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_21578"}

{:event/type "foulcommit"
:event/elapsed 62
:event/subtype "hands"
:event/player1 "Eidur Gudjohnsen"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_529136"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Thierry Henry"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_529139"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_21578"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Royston Drenthe"
:event/player1 "Xavi Hernandez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_529143"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_21578"}

{:event/type "foulcommit"
:event/elapsed 66
:event/player2 "Raul"
:event/player1 "Rafael Marquez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_529144"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Thierry Henry"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_529145"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Xavi Hernandez"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_529147"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_21578"}

{:event/type "corner"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Xavi Hernandez"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_529147"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_21578"}

{:event/type "shotoff"
:event/elapsed 68
:event/subtype "distance"
:event/player1 "Lionel Messi"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_529149"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Thierry Henry"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_529151"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_21578"}

{:event/type "shoton"
:event/elapsed 69
:event/subtype "deflected"
:event/player1 "Xavi Hernandez"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_529152"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Daniel Alves"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_529153"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_21578"}

{:event/type "corner"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Daniel Alves"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_529153"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_21578"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Sergio Busquets"
:event/subtype "penalty"
:event/player1 "Michel Salgado"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_529155"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_21578"}

{:event/type "card"
:event/elapsed 69
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Michel Salgado"
:event/sortorder 5
:event/team "away"
:event/event_type "card"
:event/id "event_529157"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_21578"}

{:event/type "goal"
:event/elapsed 70
:event/subtype "saved"
:event/player1 "Samuel Eto'o"
:event/sortorder 0
:event/team "home"
:event/id "event_529156"
:event/event_type "goal"
:event/goal_type "npm"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_21578"}

{:event/type "shoton"
:event/elapsed 72
:event/subtype "distance"
:event/player1 "Samuel Eto'o"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_529158"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Thierry Henry"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_529162"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Eric Abidal"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_529165"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Xavi Hernandez"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_529167"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_21578"}

{:event/type "corner"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Xavi Hernandez"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_529167"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Lionel Messi"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_529168"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Xavi Hernandez"
:event/sortorder 5
:event/team "home"
:event/event_type "corner"
:event/id "event_529170"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_21578"}

{:event/type "corner"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Xavi Hernandez"
:event/sortorder 5
:event/team "home"
:event/event_type "corner"
:event/id "event_529170"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Eric Abidal"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_529173"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_21578"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Yaya Toure"
:event/player1 "Javi Garcia"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_529178"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_21578"}

{:event/type "foulcommit"
:event/elapsed 78
:event/player2 "Rafael van der Vaart"
:event/player1 "Yaya Toure"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_529179"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_21578"}

{:event/type "shoton"
:event/elapsed 78
:event/subtype "shot"
:event/player1 "unknown"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_529180"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_21578"}

{:event/type "foulcommit"
:event/elapsed 79
:event/player2 "Sergio Ramos"
:event/player1 "Yaya Toure"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_529182"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Daniel Alves"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_529184"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_21578"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Yaya Toure"
:event/player1 "Fernando Gago"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_529189"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Daniel Alves"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_529190"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Xavi Hernandez"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_529192"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_21578"}

{:event/type "corner"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Xavi Hernandez"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_529192"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_21578"}

{:event/type "goal"
:event/elapsed 83
:event/player2 "Carles Puyol"
:event/subtype "shot"
:event/player1 "Samuel Eto'o"
:event/sortorder 2
:event/team "home"
:event/id "event_529194"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Javi Garcia"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_529196"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_21578"}

{:event/type "card"
:event/elapsed 85
:event/card_type "y"
:event/player1 "Samuel Eto'o"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_529198"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_21578"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Carles Puyol"
:event/player1 "Raul"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_529203"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Xavi Hernandez"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_529205"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_21578"}

{:event/type "corner"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Xavi Hernandez"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_529205"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_21578"}

{:event/type "corner"
:event/elapsed 90
:event/subtype "short"
:event/player1 "Xavi Hernandez"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_529207"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_21578"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Fernando Gago"
:event/player1 "Aleksandr Hleb"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_529208"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_21578"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/subtype "verbal_abuse"
:event/player1 "Iker Casillas"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_529209"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_21578"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Thierry Henry"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_529213"
:event/minute 91
:event/match_id "match_21578"}

{:event/type "goal"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Thierry Henry"
:event/subtype "shot"
:event/player1 "Lionel Messi"
:event/sortorder 5
:event/team "home"
:event/id "event_529214"
:event/event_type "goal"
:event/goal_type "n"
:event/minute 91
:event/match_id "match_21578"}

{:event/type "card"
:event/elapsed_plus 2
:event/elapsed 90
:event/card_type "y"
:event/player1 "Lionel Messi"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_529218"
:event/minute 92
:event/match_id "match_21578"}


]

