
;;# data
[
{:match/id "match_3546"
:match/league "England Premier League"
:match/hometeam "Tottenham Hotspur"
:match/awayteam "Southampton"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Benoit Assou-Ekotto"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2745714"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_3546"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "Steven Davis"
:event/player1 "Jan Vertonghen"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2745729"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_3546"}

{:event/type "shotoff"
:event/elapsed 3
:event/subtype "direct_freekick"
:event/player1 "Adam Lallana"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2745731"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_3546"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Guilherme Do Prado"
:event/subtype "pushing"
:event/player1 "Moussa Dembele"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2745745"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_3546"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Benoit Assou-Ekotto"
:event/player1 "Guilherme Do Prado"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2745762"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_3546"}

{:event/type "shotoff"
:event/elapsed 6
:event/subtype "shot"
:event/player1 "Jermain Defoe"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2745766"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_3546"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Moussa Dembele"
:event/player1 "Guilherme Do Prado"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2745791"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Benoit Assou-Ekotto"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2745824"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3546"}

{:event/type "shotoff"
:event/elapsed 11
:event/subtype "big chance volley"
:event/player1 "Nathaniel Clyne"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2745848"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_3546"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Clint Dempsey"
:event/player1 "Guilherme Do Prado"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2745897"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_2745898"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_3546"}

{:event/type "shoton"
:event/elapsed 15
:event/subtype "blocked_shot"
:event/player1 "Clint Dempsey"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_2745905"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Guilherme Do Prado"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2745960"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_3546"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Kyle Walker"
:event/subtype "trip"
:event/player1 "Luke Shaw"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2745963"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/sortorder 3
:event/team "home"
:event/event_type "throwin"
:event/id "event_2745980"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Benoit Assou-Ekotto"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2745985"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2745989"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_3546"}

{:event/type "corner"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2745989"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Guilherme Do Prado"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2745996"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Adam Lallana"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_2745999"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3546"}

{:event/type "corner"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Adam Lallana"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_2745999"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3546"}

{:event/type "shotoff"
:event/elapsed 25
:event/subtype "header"
:event/player1 "Jay Rodriguez"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2746001"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Rickie Lambert"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2746022"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_3546"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Guilherme Do Prado"
:event/player1 "Benoit Assou-Ekotto"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2746039"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Nathaniel Clyne"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_2746056"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3546"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Jay Rodriguez"
:event/player1 "Moussa Dembele"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2746074"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_3546"}

{:event/type "shotoff"
:event/elapsed 36
:event/subtype "post"
:event/player1 "Rickie Lambert"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2746109"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_3546"}

{:event/type "shoton"
:event/elapsed 36
:event/subtype "header"
:event/player1 "Steven Davis"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_2746114"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_3546"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Steven Davis"
:event/player1 "Tom Huddlestone"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2746124"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_2746178"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3546"}

{:event/type "foulcommit"
:event/elapsed 41
:event/subtype "hands"
:event/player1 "Jermain Defoe"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2746180"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3546"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Benoit Assou-Ekotto"
:event/player1 "Guilherme Do Prado"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2746199"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Gareth Bale"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2746221"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Gareth Bale"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2746251"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_3546"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "Clint Dempsey"
:event/player1 "Jose Fonte"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2746267"
:event/minute 46
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2746272"
:event/minute 47
:event/match_id "match_3546"}

{:event/type "foulcommit"
:event/elapsed 47
:event/player2 "Lewis Holtby"
:event/player1 "Jay Rodriguez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2746524"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2746278"
:event/minute 47
:event/match_id "match_3546"}

{:event/type "corner"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2746278"
:event/minute 47
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Benoit Assou-Ekotto"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_2746280"
:event/minute 47
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2746296"
:event/minute 48
:event/match_id "match_3546"}

{:event/type "corner"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2746296"
:event/minute 48
:event/match_id "match_3546"}

{:event/type "shotoff"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "header"
:event/player1 "Gareth Bale"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2746300"
:event/minute 48
:event/match_id "match_3546"}

{:event/type "shoton"
:event/elapsed 52
:event/subtype "shot"
:event/player1 "Adam Lallana"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_2746589"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_3546"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Adam Lallana"
:event/player1 "Tom Huddlestone"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2746642"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Rickie Lambert"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2746648"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Adam Lallana"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2746663"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3546"}

{:event/type "corner"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Adam Lallana"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2746663"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3546"}

{:event/type "shotoff"
:event/elapsed 58
:event/subtype "deflected"
:event/player1 "Adam Lallana"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2746667"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Adam Lallana"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_2746679"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3546"}

{:event/type "corner"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Adam Lallana"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_2746679"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Nathaniel Clyne"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2746686"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Adam Lallana"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_2746697"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_3546"}

{:event/type "corner"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Adam Lallana"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_2746697"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_3546"}

{:event/type "shotoff"
:event/elapsed 59
:event/subtype "distance"
:event/player1 "Luke Shaw"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2746700"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Benoit Assou-Ekotto"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2746733"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Gareth Bale"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_2746750"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Rickie Lambert"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_2746760"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3546"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Jermain Defoe"
:event/subtype "advantage"
:event/player1 "Luke Shaw"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2746764"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Benoit Assou-Ekotto"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2746793"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Benoit Assou-Ekotto"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_2746799"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_3546"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Gareth Bale"
:event/subtype "pushing"
:event/player1 "Jay Rodriguez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2746804"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3546"}

{:event/type "shotoff"
:event/elapsed 68
:event/subtype "shot"
:event/player1 "Clint Dempsey"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2746811"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2746825"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_3546"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Artur Boruc"
:event/player1 "Emmanuel Adebayor"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2746826"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_3546"}

{:event/type "foulcommit"
:event/elapsed 71
:event/subtype "hands"
:event/player1 "Benoit Assou-Ekotto"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2746831"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3546"}

{:event/type "card"
:event/elapsed 71
:event/card_type "y"
:event/player1 "Benoit Assou-Ekotto"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_2746832"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Adam Lallana"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_2746833"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3546"}

{:event/type "foulcommit"
:event/elapsed 72
:event/player2 "Clint Dempsey"
:event/player1 "Jack Cork"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2746836"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Emmanuel Mayuka"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2746841"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Adam Lallana"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_2746843"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3546"}

{:event/type "corner"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Adam Lallana"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_2746843"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3546"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Jermain Defoe"
:event/subtype "from_behind"
:event/player1 "Steven Davis"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2746847"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3546"}

{:event/type "card"
:event/elapsed 73
:event/card_type "y"
:event/player1 "Steven Davis"
:event/sortorder 5
:event/team "away"
:event/event_type "card"
:event/id "event_2746848"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3546"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Jose Fonte"
:event/player1 "Emmanuel Adebayor"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2746854"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Kyle Walker"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2746868"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2746870"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_3546"}

{:event/type "corner"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2746870"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_2746873"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Gareth Bale"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2746884"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Gylfi Sigurdsson"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2746886"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Benoit Assou-Ekotto"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2746893"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Kyle Walker"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2746894"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_3546"}

{:event/type "shotoff"
:event/elapsed 83
:event/subtype "deflected"
:event/player1 "Gareth Bale"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2746898"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2746901"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_3546"}

{:event/type "corner"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2746901"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_3546"}

{:event/type "shoton"
:event/elapsed 84
:event/subtype "distance"
:event/player1 "Jan Vertonghen"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_2746903"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_3546"}

{:event/type "goal"
:event/elapsed 86
:event/player2 "Kyle Walker"
:event/subtype "distance"
:event/player1 "Gareth Bale"
:event/sortorder 0
:event/team "home"
:event/id "event_2746909"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3546"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Emmanuel Mayuka"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2746931"
:event/minute 94
:event/match_id "match_3546"}


]

