
;;# data
[
{:match/id "match_22497"
:match/league "Spain LIGA BBVA"
:match/hometeam "RC Deportivo de La Coruña"
:match/awayteam "Levante UD"
:match/score "0:1"
:match/hometeam_goals "0"
:match/awayteam_goals "1"}

{:event/type "card"
:event/elapsed 46
:event/card_type "y"
:event/player1 "Ruben Perez"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1471010"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_22497"}

{:event/type "card"
:event/elapsed 73
:event/card_type "y"
:event/player1 "Alberto Lopo"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1471381"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_22497"}

{:event/type "card"
:event/elapsed 79
:event/card_type "y"
:event/player1 "Vicente Iborra"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1471382"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_22497"}

{:event/type "card"
:event/elapsed 84
:event/card_type "y"
:event/player1 "Xavier Torres"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1471486"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_22497"}

{:event/type "goal"
:event/elapsed 90
:event/player1 "Ruben Suarez"
:event/sortorder 0
:event/team "away"
:event/id "event_1471485"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_22497"}


]

