
;;# data
[
{:match/id "match_10916"
:match/league "Italy Serie A"
:match/hometeam "Catania"
:match/awayteam "Siena"
:match/score "2:2"
:match/hometeam_goals "2"
:match/awayteam_goals "2"}

{:event/type "goal"
:event/elapsed 11
:event/player1 "Maxi Lopez"
:event/sortorder 0
:event/team "home"
:event/id "event_1050725"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_10916"}

{:event/type "card"
:event/elapsed 16
:event/card_type "y"
:event/player1 "Cribari"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1050836"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_10916"}

{:event/type "card"
:event/elapsed 18
:event/card_type "y"
:event/player1 "Takayuki Morimoto"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1050846"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_10916"}

{:event/type "card"
:event/elapsed 22
:event/card_type "y"
:event/player1 "Aleandro Rosi"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1050909"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_10916"}

{:event/type "goal"
:event/elapsed 49
:event/player1 "Massimo Maccarone"
:event/sortorder 0
:event/team "away"
:event/id "event_1051398"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_10916"}

{:event/type "goal"
:event/elapsed 50
:event/player1 "Marco Biagianti"
:event/sortorder 0
:event/team "home"
:event/id "event_1051418"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_10916"}

{:event/type "card"
:event/elapsed 60
:event/card_type "y"
:event/player1 "Abdelkader Ghezzal"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1051609"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_10916"}

{:event/type "goal"
:event/elapsed 69
:event/player1 "Simone Vergassola"
:event/sortorder 0
:event/team "away"
:event/id "event_1051736"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_10916"}

{:event/type "card"
:event/elapsed 81
:event/card_type "y"
:event/player1 "Reginaldo"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1051938"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_10916"}


]

