
;;# data
[
{:match/id "match_8088"
:match/league "Germany 1. Bundesliga"
:match/hometeam "FC Bayern Munich"
:match/awayteam "VfL Bochum"
:match/score "3:3"
:match/hometeam_goals "3"
:match/awayteam_goals "3"}

{:event/type "goal"
:event/elapsed 16
:event/player1 "Daniel van Buyten"
:event/sortorder 0
:event/team "home"
:event/id "event_433279"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_8088"}

{:event/type "goal"
:event/elapsed 29
:event/player1 "Sinan Kaloglu"
:event/sortorder 0
:event/team "away"
:event/id "event_433338"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_8088"}

{:event/type "card"
:event/elapsed 35
:event/card_type "y"
:event/player1 "Paul Freier"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_433398"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_8088"}

{:event/type "goal"
:event/elapsed 45
:event/player1 "Ze Roberto"
:event/sortorder 0
:event/team "home"
:event/id "event_433483"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_8088"}

{:event/type "card"
:event/elapsed 62
:event/card_type "y"
:event/player1 "Mergim Mavraj"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_433745"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_8088"}

{:event/type "goal"
:event/elapsed 68
:event/player1 "Ze Roberto"
:event/sortorder 0
:event/team "home"
:event/id "event_433767"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_8088"}

{:event/type "card"
:event/elapsed 74
:event/card_type "y"
:event/player1 "Jose Sosa"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_433791"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_8088"}

{:event/type "card"
:event/elapsed 76
:event/card_type "y"
:event/player1 "Sinan Kaloglu"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_433827"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_8088"}

{:event/type "goal"
:event/elapsed 83
:event/player1 "Christoph Dabrowski"
:event/sortorder 0
:event/team "away"
:event/id "event_433941"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_8088"}

{:event/type "goal"
:event/elapsed 85
:event/player1 "Dennis Grote"
:event/sortorder 0
:event/team "away"
:event/id "event_433930"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_8088"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Massimo Oddo"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_434026"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_8088"}


]

