
;;# data
[
{:match/id "match_21942"
:match/league "Spain LIGA BBVA"
:match/hometeam "RCD Espanyol"
:match/awayteam "Racing Santander"
:match/score "0:4"
:match/hometeam_goals "0"
:match/awayteam_goals "4"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Gonzalo Colsa"
:event/player1 "Jose Maria Callejon"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_869188"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_21942"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Luis Garcia"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_869203"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_21942"}

{:event/type "corner"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Luis Garcia"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_869203"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_21942"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Ivan Pillud"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_869208"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_21942"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_869215"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_21942"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Ben Sahar"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_869224"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_21942"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Luis Garcia"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_869230"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_21942"}

{:event/type "corner"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Luis Garcia"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_869230"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_21942"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Luis Garcia"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_869235"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_21942"}

{:event/type "corner"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Luis Garcia"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_869235"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_21942"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Oscar Serrano"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_869246"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_21942"}

{:event/type "shotoff"
:event/elapsed 9
:event/subtype "shot"
:event/player1 "Pedro Munitis"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_869247"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Ivan Pillud"
:event/player1 "Mehdi Lacen"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_869255"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 12
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_869278"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_21942"}

{:event/type "shotoff"
:event/elapsed 12
:event/subtype "big chance shot"
:event/player1 "Jose Maria Callejon"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_869280"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Sergio Canales"
:event/subtype "pushing"
:event/player1 "Ivan Pillud"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_869300"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_21942"}

{:event/type "shoton"
:event/elapsed 15
:event/subtype "header"
:event/player1 "Nasief Morris"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_869311"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_21942"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Pedro Munitis"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_869312"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_21942"}

{:event/type "corner"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Pedro Munitis"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_869312"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Luis Garcia"
:event/player1 "Gonzalo Colsa"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_869335"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_21942"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Ben Sahar"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_869345"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Ivan Pillud"
:event/subtype "serious_foul"
:event/player1 "Oscar Serrano"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_869352"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player1 "Jose Raul Baena"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_869367"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_21942"}

{:event/type "shotoff"
:event/elapsed 21
:event/subtype "shot"
:event/player1 "Ben Sahar"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_869376"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_21942"}

{:event/type "shotoff"
:event/elapsed 23
:event/subtype "distance"
:event/player1 "Sergio Canales"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_869398"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 27
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_869441"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_21942"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Mohammed Tchite"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_869455"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Pedro Munitis"
:event/player1 "Ivan Pillud"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_869473"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_21942"}

{:event/type "corner"
:event/elapsed 30
:event/subtype "short"
:event/player1 "Pedro Munitis"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_869481"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_21942"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Pedro Munitis"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_869484"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_21942"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Sergio Canales"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_869489"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_21942"}

{:event/type "corner"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Sergio Canales"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_869489"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Luis Garcia"
:event/subtype "pushing"
:event/player1 "Nasief Morris"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_869501"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Ben Sahar"
:event/subtype "serious_foul"
:event/player1 "Nasief Morris"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_869531"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_21942"}

{:event/type "card"
:event/elapsed 33
:event/card_type "y"
:event/subtype "emergency_brake"
:event/player1 "Nasief Morris"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_869533"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_21942"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Ben Sahar"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_869585"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_21942"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Oscar Serrano"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_869600"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Pedro Munitis"
:event/subtype "pushing"
:event/player1 "Luis Garcia"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_869628"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Luis Garcia"
:event/subtype "pushing"
:event/player1 "Christian Fernandez"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_869647"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Ivan Pillud"
:event/subtype "serious_foul"
:event/player1 "Oscar Serrano"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_869657"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_21942"}

{:event/type "card"
:event/elapsed 43
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Oscar Serrano"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_869658"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_21942"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Pedro Munitis"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_869677"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_21942"}

{:event/type "shotoff"
:event/elapsed 44
:event/subtype "big chance shot"
:event/player1 "Mohammed Tchite"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_869679"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "Sergio Canales"
:event/player1 "Nicolas Pareja"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_869692"
:event/minute 46
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 46
:event/player1 "Pedro Munitis"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_869839"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 47
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_869846"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_21942"}

{:event/type "goal"
:event/elapsed 47
:event/player2 "Sergio Canales"
:event/subtype "header"
:event/player1 "Henrique"
:event/sortorder 4
:event/team "away"
:event/id "event_869848"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_21942"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Luis Garcia"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_869862"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_21942"}

{:event/type "corner"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Luis Garcia"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_869862"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Sergio Canales"
:event/player1 "Jose Raul Baena"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_869865"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_21942"}

{:event/type "goal"
:event/elapsed 53
:event/player2 "Pedro Munitis"
:event/subtype "shot"
:event/player1 "Sergio Canales"
:event/sortorder 0
:event/team "away"
:event/id "event_869879"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Victor Ruiz"
:event/subtype "serious_foul"
:event/player1 "Mohammed Tchite"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_869926"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_21942"}

{:event/type "card"
:event/elapsed 58
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Mohammed Tchite"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_869929"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 59
:event/player2 "Jose Maria Callejon"
:event/player1 "Pedro Munitis"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_869938"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_21942"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Ivan Pillud"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_869971"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_21942"}

{:event/type "shotoff"
:event/elapsed 63
:event/subtype "shot"
:event/player1 "Ivan Alonso"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_869972"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Oscar Serrano"
:event/subtype "penalty"
:event/player1 "Ivan Pillud"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_869994"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_21942"}

{:event/type "goal"
:event/elapsed 68
:event/player1 "Mohammed Tchite"
:event/sortorder 0
:event/team "away"
:event/id "event_869998"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Marc Torrejon Moya"
:event/subtype "pushing"
:event/player1 "Ivan Alonso"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_870005"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Jose Maria Callejon"
:event/player1 "Pedro Munitis"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_870015"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_21942"}

{:event/type "goal"
:event/elapsed 72
:event/player2 "Oscar Serrano"
:event/subtype "shot"
:event/player1 "Sergio Canales"
:event/sortorder 2
:event/team "away"
:event/id "event_870027"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Ferran Corominas"
:event/subtype "serious_foul"
:event/player1 "Gonzalo Colsa"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_870045"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_21942"}

{:event/type "card"
:event/elapsed 73
:event/card_type "y"
:event/subtype "emergency_brake"
:event/player1 "Gonzalo Colsa"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_870047"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 74
:event/player1 "Juan Forlin"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_870052"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_21942"}

{:event/type "card"
:event/elapsed 74
:event/card_type "y"
:event/player1 "Juan Forlin"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_870054"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_21942"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Luis Garcia"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_870057"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_21942"}

{:event/type "corner"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Luis Garcia"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_870057"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Oscar Serrano"
:event/subtype "pushing"
:event/player1 "Ivan Pillud"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_870061"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_21942"}

{:event/type "shoton"
:event/elapsed 77
:event/subtype "blocked_shot"
:event/player1 "Oscar Serrano"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_870073"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_21942"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Luis Garcia"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_870078"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_21942"}

{:event/type "corner"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Luis Garcia"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_870078"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player1 "Jose Maria Callejon"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_870122"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 84
:event/subtype "serious_foul"
:event/player1 "Raul Tamudo"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_870146"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 87
:event/player2 "Henrique"
:event/subtype "serious_foul"
:event/player1 "Ivan Alonso"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_870169"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 87
:event/player2 "Jose Maria Callejon"
:event/subtype "pushing"
:event/player1 "Oriol"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_870171"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Mohammed Tchite"
:event/subtype "shirt_pull"
:event/player1 "Victor Ruiz"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_870178"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_21942"}

{:event/type "card"
:event/elapsed 88
:event/card_type "y"
:event/subtype "shirt_pull"
:event/player1 "Victor Ruiz"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_870179"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_21942"}

{:event/type "corner"
:event/elapsed 89
:event/subtype "short"
:event/player1 "Pedro Munitis"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_870189"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player2 "Ferran Corominas"
:event/player1 "Christian Fernandez"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_870198"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_21942"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Luis Garcia"
:event/player1 "Ivan Pillud"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_870207"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_21942"}

{:event/type "shotoff"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Jose Maria Callejon"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_870224"
:event/minute 92
:event/match_id "match_21942"}


]

