
;;# data
[
{:match/id "match_6604"
:match/league "France Ligue 1"
:match/hometeam "FC Lorient"
:match/awayteam "Paris Saint-Germain"
:match/score "1:3"
:match/hometeam_goals "1"
:match/awayteam_goals "3"}

{:event/type "card"
:event/elapsed 50
:event/card_type "y"
:event/player1 "Yann Jouffre"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2788661"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_6604"}

{:event/type "goal"
:event/elapsed 51
:event/player1 "Zlatan Ibrahimovic"
:event/sortorder 0
:event/team "away"
:event/id "event_2788583"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_6604"}

{:event/type "goal"
:event/elapsed 63
:event/player1 "Kevin Gameiro"
:event/sortorder 0
:event/team "away"
:event/id "event_2788593"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_6604"}

{:event/type "goal"
:event/elapsed 65
:event/player1 "Kevin Gameiro"
:event/sortorder 0
:event/team "away"
:event/id "event_2788596"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_6604"}

{:event/type "card"
:event/elapsed 81
:event/card_type "r"
:event/player1 "Ronan Le Crom"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2788617"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_6604"}

{:event/type "goal"
:event/elapsed 84
:event/player1 "Arnaud Le Lan"
:event/sortorder 0
:event/team "home"
:event/id "event_2788630"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_6604"}


]

