
;;# data
[
{:match/id "match_9713"
:match/league "Germany 1. Bundesliga"
:match/hometeam "Eintracht Frankfurt"
:match/awayteam "Hertha BSC Berlin"
:match/score "4:4"
:match/hometeam_goals "4"
:match/awayteam_goals "4"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Marc Stendera"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4018816"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_9713"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Bastian Oczipka"
:event/subtype "pushing"
:event/player1 "Anis Ben-Hatira"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4018834"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_9713"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Haris Seferovic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4018850"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_9713"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Anderson"
:event/subtype "pushing"
:event/player1 "Ronny"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4018861"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_9713"}

{:event/type "shotoff"
:event/elapsed 8
:event/subtype "big chance shot"
:event/player1 "Alexander Meier"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4018872"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_9713"}

{:event/type "shotoff"
:event/elapsed 10
:event/subtype "deflected"
:event/player1 "Haris Seferovic"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4018892"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_9713"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Stefan Aigner"
:event/subtype "dangerous_play"
:event/player1 "Julian Schieber"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4018904"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_9713"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Takashi Inui"
:event/subtype "dangerous_play"
:event/player1 "Peter Niemeyer"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4018915"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_9713"}

{:event/type "cross"
:event/elapsed 13
:event/subtype "cross"
:event/player1 "Marc Stendera"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4018920"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_9713"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Peter Niemeyer"
:event/subtype "pushing"
:event/player1 "Stefan Aigner"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4018929"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_9713"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Stefan Aigner"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4018987"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_9713"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Timothy Chandler"
:event/subtype "pushing"
:event/player1 "Julian Schieber"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4018996"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_9713"}

{:event/type "foulcommit"
:event/elapsed 20
:event/subtype "hands"
:event/player1 "Bastian Oczipka"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4019001"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_9713"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "John Anthony Brooks"
:event/subtype "dangerous_play"
:event/player1 "Alexander Meier"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4019013"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_9713"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Ronny"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4019020"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_9713"}

{:event/type "goal"
:event/elapsed 22
:event/player2 "Ronny"
:event/subtype "volley"
:event/player1 "John Anthony Brooks"
:event/sortorder 1
:event/team "away"
:event/id "event_4019022"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_9713"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Roy Beerens"
:event/subtype "serious_foul"
:event/player1 "Stefan Aigner"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4019047"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_9713"}

{:event/type "card"
:event/elapsed 24
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Stefan Aigner"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_4019049"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_9713"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Ronny"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4019055"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_9713"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Bastian Oczipka"
:event/subtype "pull"
:event/player1 "Anis Ben-Hatira"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4019083"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_9713"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Haris Seferovic"
:event/subtype "pushing"
:event/player1 "John Anthony Brooks"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4019090"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_9713"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Marc Stendera"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4019099"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_9713"}

{:event/type "shotoff"
:event/elapsed 29
:event/subtype "shot"
:event/player1 "Anis Ben-Hatira"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4019109"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_9713"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Nico Schulz"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4019147"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_9713"}

{:event/type "corner"
:event/elapsed 33
:event/subtype "cross_left"
:event/player1 "Ronny"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_4019150"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_9713"}

{:event/type "goal"
:event/elapsed 33
:event/player2 "Ronny"
:event/subtype "header"
:event/player1 "Anis Ben-Hatira"
:event/sortorder 4
:event/team "away"
:event/id "event_4019151"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_9713"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Takashi Inui"
:event/subtype "trip"
:event/player1 "Hajime Hosogai"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4019168"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_9713"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Peter Niemeyer"
:event/subtype "trip"
:event/player1 "Takashi Inui"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4019179"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_9713"}

{:event/type "goal"
:event/elapsed 37
:event/player2 "Anis Ben-Hatira"
:event/subtype "shot"
:event/player1 "Julian Schieber"
:event/sortorder 2
:event/team "away"
:event/id "event_4019184"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_9713"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Timothy Chandler"
:event/subtype "pull"
:event/player1 "Genki Haraguchi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4019227"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_9713"}

{:event/type "shoton"
:event/elapsed 40
:event/subtype "blocked_shot"
:event/player1 "Haris Seferovic"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_4019235"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_9713"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Bastian Oczipka"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4019246"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_9713"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Haris Seferovic"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4019249"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_9713"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Alexander Meier"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4019257"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_9713"}

{:event/type "goal"
:event/elapsed 43
:event/subtype "shot"
:event/player1 "Stefan Aigner"
:event/sortorder 2
:event/team "home"
:event/id "event_4019262"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_9713"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "John Anthony Brooks"
:event/subtype "trip"
:event/player1 "Alexander Madlung"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4019292"
:event/minute 46
:event/match_id "match_9713"}

{:event/type "foulcommit"
:event/elapsed 47
:event/player2 "Peter Niemeyer"
:event/subtype "trip"
:event/player1 "Haris Seferovic"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4019328"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_9713"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Stefan Aigner"
:event/subtype "pushing"
:event/player1 "Peter Niemeyer"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4019349"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_9713"}

{:event/type "shoton"
:event/elapsed 50
:event/subtype "blocked_shot"
:event/player1 "Haris Seferovic"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4019360"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_9713"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Marc Stendera"
:event/subtype "pushing"
:event/player1 "John Anthony Brooks"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4019365"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_9713"}

{:event/type "card"
:event/elapsed 51
:event/card_type "y"
:event/player1 "John Anthony Brooks"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_4019368"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_9713"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Marc Stendera"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4019375"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_9713"}

{:event/type "corner"
:event/elapsed 51
:event/subtype "cross_right"
:event/player1 "Marc Stendera"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_4019379"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_9713"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Timothy Chandler"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4019385"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_9713"}

{:event/type "shoton"
:event/elapsed 52
:event/subtype "big chance header"
:event/player1 "Alexander Meier"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4019386"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_9713"}

{:event/type "shotoff"
:event/elapsed 54
:event/subtype "shot"
:event/player1 "Takashi Inui"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4019410"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_9713"}

{:event/type "shoton"
:event/elapsed 56
:event/subtype "blocked_shot"
:event/player1 "Timothy Chandler"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4019438"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_9713"}

{:event/type "shoton"
:event/elapsed 57
:event/subtype "distance"
:event/player1 "Haris Seferovic"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4019453"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_9713"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Takashi Inui"
:event/subtype "pushing"
:event/player1 "Peter Pekarik"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4019458"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_9713"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Makoto Hasebe"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4019467"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_9713"}

{:event/type "goal"
:event/elapsed 58
:event/player2 "Makoto Hasebe"
:event/subtype "header"
:event/player1 "Haris Seferovic"
:event/sortorder 3
:event/team "home"
:event/id "event_4019469"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_9713"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Haris Seferovic"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4019495"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_9713"}

{:event/type "shoton"
:event/elapsed 60
:event/subtype "shot"
:event/player1 "Julian Schieber"
:event/sortorder 5
:event/team "away"
:event/event_type "shoton"
:event/id "event_4019503"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_9713"}

{:event/type "corner"
:event/elapsed 61
:event/subtype "cross_left"
:event/player1 "Ronny"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4019505"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_9713"}

{:event/type "shotoff"
:event/elapsed 61
:event/subtype "distance"
:event/player1 "Hajime Hosogai"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4019509"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_9713"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Haris Seferovic"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_4019515"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_9713"}

{:event/type "shotoff"
:event/elapsed 62
:event/subtype "big chance shot"
:event/player1 "Anis Ben-Hatira"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4019535"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_9713"}

{:event/type "corner"
:event/elapsed 64
:event/subtype "cross_right"
:event/player1 "Ronny"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4019564"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_9713"}

{:event/type "corner"
:event/elapsed 65
:event/subtype "cross_right"
:event/player1 "Ronny"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4019569"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_9713"}

{:event/type "card"
:event/elapsed 66
:event/card_type "y"
:event/subtype "stall_time"
:event/player1 "Ronny"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_4019582"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_9713"}

{:event/type "foulcommit"
:event/elapsed 66
:event/player2 "Peter Niemeyer"
:event/subtype "dangerous_play"
:event/player1 "Marc Stendera"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4019591"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_9713"}

{:event/type "card"
:event/elapsed 67
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Marc Stendera"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_4019593"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_9713"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Bastian Oczipka"
:event/subtype "pull"
:event/player1 "Anis Ben-Hatira"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4019603"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_9713"}

{:event/type "shoton"
:event/elapsed 68
:event/subtype "blocked_shot"
:event/player1 "Alexander Madlung"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4019611"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_9713"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Makoto Hasebe"
:event/subtype "pushing"
:event/player1 "Nico Schulz"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4019630"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_9713"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Timothy Chandler"
:event/subtype "trip"
:event/player1 "Genki Haraguchi"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4019636"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_9713"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Nico Schulz"
:event/subtype "trip"
:event/player1 "Takashi Inui"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4019652"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_9713"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Bastian Oczipka"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4019669"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_9713"}

{:event/type "corner"
:event/elapsed 77
:event/subtype "cross_left"
:event/player1 "Bastian Oczipka"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4019701"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_9713"}

{:event/type "foulcommit"
:event/elapsed 78
:event/player2 "Sonny Kittel"
:event/subtype "pushing"
:event/player1 "Hajime Hosogai"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4019714"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_9713"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Marc Stendera"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4019718"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_9713"}

{:event/type "corner"
:event/elapsed 79
:event/subtype "cross_right"
:event/player1 "Takashi Inui"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4019720"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_9713"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Anis Ben-Hatira"
:event/subtype "trip"
:event/player1 "Bastian Oczipka"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4019731"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_9713"}

{:event/type "card"
:event/elapsed 80
:event/card_type "y"
:event/player1 "Bastian Oczipka"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4019732"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_9713"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Anis Ben-Hatira"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4019741"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_9713"}

{:event/type "goal"
:event/elapsed 80
:event/player2 "Anis Ben-Hatira"
:event/subtype "shot"
:event/player1 "Peter Niemeyer"
:event/sortorder 3
:event/team "away"
:event/id "event_4019744"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_9713"}

{:event/type "shoton"
:event/elapsed 83
:event/subtype "big chance shot"
:event/player1 "Alexander Meier"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4019770"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_9713"}

{:event/type "foulcommit"
:event/elapsed 83
:event/player2 "Marc Stendera"
:event/subtype "pushing"
:event/player1 "Genki Haraguchi"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4019776"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_9713"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Julian Schieber"
:event/subtype "pushing"
:event/player1 "Alexander Madlung"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4019781"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_9713"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Haris Seferovic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4019802"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_9713"}

{:event/type "corner"
:event/elapsed 86
:event/subtype "cross_left"
:event/player1 "Takashi Inui"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4019806"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_9713"}

{:event/type "shotoff"
:event/elapsed 86
:event/subtype "distance"
:event/player1 "Marc Stendera"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4019812"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_9713"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Marc Stendera"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4019841"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_9713"}

{:event/type "shoton"
:event/elapsed 89
:event/subtype "blocked_shot"
:event/player1 "Takashi Inui"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4019844"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_9713"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Takashi Inui"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4019859"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_9713"}

{:event/type "goal"
:event/elapsed 90
:event/player2 "Anderson"
:event/subtype "header"
:event/player1 "Alexander Meier"
:event/sortorder 2
:event/team "home"
:event/id "event_4019863"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_9713"}

{:event/type "goal"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Sonny Kittel"
:event/subtype "shot"
:event/player1 "Alexander Meier"
:event/sortorder 7
:event/team "home"
:event/id "event_4019893"
:event/event_type "goal"
:event/goal_type "n"
:event/minute 91
:event/match_id "match_9713"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Lucas Piazon"
:event/subtype "trip"
:event/player1 "Nico Schulz"
:event/sortorder 9
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4019912"
:event/minute 93
:event/match_id "match_9713"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Lucas Piazon"
:event/sortorder 10
:event/team "home"
:event/event_type "cross"
:event/id "event_4019916"
:event/minute 93
:event/match_id "match_9713"}

{:event/type "corner"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross_right"
:event/player1 "Marc Stendera"
:event/sortorder 12
:event/team "home"
:event/event_type "corner"
:event/id "event_4019922"
:event/minute 94
:event/match_id "match_9713"}

{:event/type "foulcommit"
:event/elapsed_plus 6
:event/elapsed 90
:event/player2 "Hajime Hosogai"
:event/subtype "trip"
:event/player1 "Sonny Kittel"
:event/sortorder 19
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4019946"
:event/minute 96
:event/match_id "match_9713"}


]

