
;;# data
[
{:match/id "match_9611"
:match/league "Germany 1. Bundesliga"
:match/hometeam "VfB Stuttgart"
:match/awayteam "Eintracht Frankfurt"
:match/score "2:1"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "goal"
:event/elapsed 14
:event/player1 "Marco Russ"
:event/sortorder 0
:event/team "away"
:event/id "event_3012003"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_9611"}

{:event/type "goal"
:event/elapsed 16
:event/player1 "Timo Werner"
:event/sortorder 0
:event/team "home"
:event/id "event_3012027"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_9611"}

{:event/type "card"
:event/elapsed 28
:event/card_type "y"
:event/player1 "William Kvist"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3012053"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_9611"}

{:event/type "card"
:event/elapsed 39
:event/card_type "y"
:event/player1 "Constant Djakpa"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3012142"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_9611"}

{:event/type "card"
:event/elapsed 61
:event/card_type "y"
:event/player1 "Gotoku Sakai"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3012610"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_9611"}

{:event/type "card"
:event/elapsed 87
:event/card_type "y"
:event/player1 "Martin Harnik"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3012751"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_9611"}

{:event/type "goal"
:event/elapsed 90
:event/player1 "Vedad Ibisevic"
:event/sortorder 2
:event/team "home"
:event/id "event_3012778"
:event/event_type "goal"
:event/goal_type "npm"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_9611"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Anderson"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_3012795"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_9611"}


]

