
;;# data
[
{:match/id "match_4580"
:match/league "England Premier League"
:match/hometeam "Liverpool"
:match/awayteam "Everton"
:match/score "4:0"
:match/hometeam_goals "4"
:match/awayteam_goals "0"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Philippe Coutinho"
:event/subtype "obstruction"
:event/player1 "Bryan Oviedo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5519949"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_4580"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "James Milner"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5519962"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_4580"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Ross Barkley"
:event/subtype "pushing"
:event/player1 "James Milner"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5520049"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_4580"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Gareth Barry"
:event/subtype "trip"
:event/player1 "James Milner"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5520069"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_4580"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5520111"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_4580"}

{:event/type "shoton"
:event/elapsed 6
:event/subtype "big chance shot"
:event/player1 "Adam Lallana"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_5520133"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_4580"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "James Milner"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_5521850"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_4580"}

{:event/type "shoton"
:event/elapsed 6
:event/subtype "blocked_shot"
:event/player1 "Philippe Coutinho"
:event/sortorder 6
:event/team "home"
:event/event_type "shoton"
:event/id "event_5520138"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_4580"}

{:event/type "foulcommit"
:event/elapsed 8
:event/player2 "Leighton Baines"
:event/subtype "trip"
:event/player1 "James Milner"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5520220"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_4580"}

{:event/type "card"
:event/elapsed 8
:event/card_type "y"
:event/player1 "James Milner"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_5520226"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_4580"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Alberto Moreno"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5520314"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_4580"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Alberto Moreno"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5520409"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_4580"}

{:event/type "shotoff"
:event/elapsed 12
:event/subtype "shot"
:event/player1 "Kevin Mirallas"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5520426"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_4580"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Divock Origi"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_5520447"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_4580"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "Ross Barkley"
:event/subtype "trip"
:event/player1 "Adam Lallana"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5520605"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_4580"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Ramiro Funes Mori"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5520632"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_4580"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Nathaniel Clyne"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5520720"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_4580"}

{:event/type "shotoff"
:event/elapsed 19
:event/subtype "bad shot"
:event/player1 "Kevin Mirallas"
:event/sortorder 5
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5520765"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_4580"}

{:event/type "shotoff"
:event/elapsed 21
:event/subtype "shot"
:event/player1 "Philippe Coutinho"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5520826"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_4580"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Alberto Moreno"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_5520900"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_4580"}

{:event/type "shoton"
:event/elapsed 23
:event/subtype "blocked_shot"
:event/player1 "Adam Lallana"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5520939"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_4580"}

{:event/type "corner"
:event/elapsed 24
:event/subtype "short_left"
:event/player1 "Philippe Coutinho"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5520955"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_4580"}

{:event/type "shoton"
:event/elapsed 24
:event/subtype "shot"
:event/player1 "Lucas Leiva"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5520958"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_4580"}

{:event/type "shotoff"
:event/elapsed 24
:event/subtype "big chance header"
:event/player1 "Adam Lallana"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5520976"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_4580"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Roberto Firmino"
:event/subtype "trip"
:event/player1 "James McCarthy"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5521015"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_4580"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Adam Lallana"
:event/subtype "from_behind"
:event/player1 "Ramiro Funes Mori"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5521063"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_4580"}

{:event/type "shotoff"
:event/elapsed 27
:event/subtype "direct_freekick"
:event/player1 "Philippe Coutinho"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5521112"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_4580"}

{:event/type "corner"
:event/elapsed 28
:event/subtype "short_right"
:event/player1 "James Milner"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_5521172"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_4580"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Roberto Firmino"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5521181"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_4580"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "James Milner"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_5521185"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_4580"}

{:event/type "corner"
:event/elapsed 29
:event/subtype "cross_right"
:event/player1 "James Milner"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5521208"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_4580"}

{:event/type "shotoff"
:event/elapsed 29
:event/subtype "distance"
:event/player1 "Dejan Lovren"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5521215"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_4580"}

{:event/type "shoton"
:event/elapsed 30
:event/subtype "shot"
:event/player1 "Roberto Firmino"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5521255"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_4580"}

{:event/type "shoton"
:event/elapsed 31
:event/subtype "blocked_shot"
:event/player1 "Ross Barkley"
:event/sortorder 4
:event/team "away"
:event/event_type "shoton"
:event/id "event_5521339"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_4580"}

{:event/type "shoton"
:event/elapsed 32
:event/subtype "blocked_shot"
:event/player1 "Adam Lallana"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_5521383"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_4580"}

{:event/type "shoton"
:event/elapsed 33
:event/subtype "blocked_shot"
:event/player1 "Philippe Coutinho"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_5521386"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_4580"}

{:event/type "corner"
:event/elapsed 33
:event/subtype "cross_left"
:event/player1 "James Milner"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_5521401"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_4580"}

{:event/type "shoton"
:event/elapsed 33
:event/subtype "blocked_shot"
:event/player1 "Dejan Lovren"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_5521422"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_4580"}

{:event/type "shoton"
:event/elapsed 33
:event/subtype "deflected"
:event/player1 "Philippe Coutinho"
:event/sortorder 5
:event/team "home"
:event/event_type "shoton"
:event/id "event_5521415"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_4580"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "James McCarthy"
:event/subtype "advantage"
:event/player1 "Lucas Leiva"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5521472"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_4580"}

{:event/type "corner"
:event/elapsed 36
:event/subtype "cross_right"
:event/player1 "Kevin Mirallas"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_5521482"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_4580"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Gareth Barry"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5521500"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_4580"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Philippe Coutinho"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5521507"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_4580"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Divock Origi"
:event/subtype "trip"
:event/player1 "Gareth Barry"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5521519"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_4580"}

{:event/type "shoton"
:event/elapsed 39
:event/subtype "shot"
:event/player1 "Divock Origi"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5521528"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_4580"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Ross Barkley"
:event/subtype "trip"
:event/player1 "Lucas Leiva"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5521550"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_4580"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "James Milner"
:event/subtype "obstruction"
:event/player1 "Aaron Lennon"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5521559"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_4580"}

{:event/type "card"
:event/elapsed 42
:event/card_type "y"
:event/player1 "Aaron Lennon"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_5521562"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_4580"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "James Milner"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5521572"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_4580"}

{:event/type "shoton"
:event/elapsed 43
:event/subtype "blocked_shot"
:event/player1 "Nathaniel Clyne"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5521577"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_4580"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "James Milner"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_5521582"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_4580"}

{:event/type "goal"
:event/elapsed 43
:event/player2 "James Milner"
:event/subtype "header"
:event/player1 "Divock Origi"
:event/sortorder 4
:event/team "home"
:event/id "event_5521585"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_4580"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Mamadou Sakho"
:event/subtype "pushing"
:event/player1 "Kevin Mirallas"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5521733"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_4580"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "Roberto Firmino"
:event/subtype "advantage"
:event/player1 "James McCarthy"
:event/sortorder 5
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5521628"
:event/minute 46
:event/match_id "match_4580"}

{:event/type "corner"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross_left"
:event/player1 "James Milner"
:event/sortorder 8
:event/team "home"
:event/event_type "corner"
:event/id "event_5521643"
:event/minute 47
:event/match_id "match_4580"}

{:event/type "goal"
:event/elapsed_plus 2
:event/elapsed 45
:event/player2 "James Milner"
:event/subtype "header"
:event/player1 "Mamadou Sakho"
:event/sortorder 12
:event/team "home"
:event/id "event_5521652"
:event/event_type "goal"
:event/goal_type "n"
:event/minute 47
:event/match_id "match_4580"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Alberto Moreno"
:event/subtype "dangerous_play"
:event/player1 "Bryan Oviedo"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5522361"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_4580"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Divock Origi"
:event/subtype "serious_foul"
:event/player1 "Ramiro Funes Mori"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5522437"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_4580"}

{:event/type "card"
:event/elapsed 50
:event/card_type "r"
:event/player1 "Ramiro Funes Mori"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_5522467"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_4580"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "James Milner"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5522671"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_4580"}

{:event/type "shoton"
:event/elapsed 58
:event/subtype "shot"
:event/player1 "Roberto Firmino"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_5522811"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_4580"}

{:event/type "shoton"
:event/elapsed 60
:event/subtype "shot"
:event/player1 "Daniel Sturridge"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_5522872"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_4580"}

{:event/type "goal"
:event/elapsed 61
:event/player2 "Lucas Leiva"
:event/subtype "shot"
:event/player1 "Daniel Sturridge"
:event/sortorder 1
:event/team "home"
:event/id "event_5522915"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_4580"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Muhamed Besic"
:event/subtype "trip"
:event/player1 "Lucas Leiva"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5523076"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_4580"}

{:event/type "shoton"
:event/elapsed 65
:event/subtype "blocked_shot"
:event/player1 "Philippe Coutinho"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_5523111"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_4580"}

{:event/type "corner"
:event/elapsed 66
:event/subtype "cross_left"
:event/player1 "James Milner"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_5523146"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_4580"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Nathaniel Clyne"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5523250"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_4580"}

{:event/type "shoton"
:event/elapsed 69
:event/subtype "blocked_shot"
:event/player1 "Philippe Coutinho"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5523253"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_4580"}

{:event/type "shoton"
:event/elapsed 69
:event/subtype "distance"
:event/player1 "Alberto Moreno"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_5523256"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_4580"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Joe Allen"
:event/subtype "pushing"
:event/player1 "Leighton Baines"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5523288"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_4580"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "James Milner"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_5523313"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_4580"}

{:event/type "shotoff"
:event/elapsed 70
:event/subtype "bad shot"
:event/player1 "Philippe Coutinho"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5523319"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_4580"}

{:event/type "shotoff"
:event/elapsed 72
:event/subtype "deflected"
:event/player1 "Alberto Moreno"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5523379"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_4580"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "James Milner"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5523418"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_4580"}

{:event/type "shoton"
:event/elapsed 73
:event/subtype "blocked_shot"
:event/player1 "Joe Allen"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5523422"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_4580"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Nathaniel Clyne"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5523462"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_4580"}

{:event/type "shotoff"
:event/elapsed 74
:event/subtype "shot"
:event/player1 "Nathaniel Clyne"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5523480"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_4580"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "James Milner"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5523527"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_4580"}

{:event/type "shotoff"
:event/elapsed 75
:event/subtype "header"
:event/player1 "Daniel Sturridge"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5523531"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_4580"}

{:event/type "goal"
:event/elapsed 76
:event/player2 "Joe Allen"
:event/subtype "shot"
:event/player1 "Philippe Coutinho"
:event/sortorder 2
:event/team "home"
:event/id "event_5523570"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_4580"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Adam Lallana"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5523627"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_4580"}

{:event/type "shoton"
:event/elapsed 79
:event/subtype "shot"
:event/player1 "Philippe Coutinho"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_5523641"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_4580"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "James Milner"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5523664"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_4580"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Alberto Moreno"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5523677"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_4580"}

{:event/type "foulcommit"
:event/elapsed 82
:event/subtype "hands"
:event/player1 "Bryan Oviedo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5523695"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_4580"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Nathaniel Clyne"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5523704"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_4580"}

{:event/type "corner"
:event/elapsed 83
:event/subtype "cross_right"
:event/player1 "Philippe Coutinho"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_5523706"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_4580"}

{:event/type "shotoff"
:event/elapsed 84
:event/subtype "shot"
:event/player1 "Alberto Moreno"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5523712"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_4580"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Nathaniel Clyne"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5523725"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_4580"}

{:event/type "corner"
:event/elapsed 85
:event/subtype "short_right"
:event/player1 "Jordon Ibe"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_5523727"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_4580"}

{:event/type "shotoff"
:event/elapsed 86
:event/subtype "shot"
:event/player1 "Alberto Moreno"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5523730"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_4580"}

{:event/type "foulcommit"
:event/elapsed 87
:event/player2 "Joe Allen"
:event/subtype "pull"
:event/player1 "Steven Pienaar"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5523744"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_4580"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Nathaniel Clyne"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5523745"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_4580"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Bryan Oviedo"
:event/subtype "pull"
:event/player1 "Jordon Ibe"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5523774"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_4580"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Jordon Ibe"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_5523777"
:event/minute 91
:event/match_id "match_4580"}

{:event/type "shotoff"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "big chance shot"
:event/player1 "Nathaniel Clyne"
:event/sortorder 9
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5523786"
:event/minute 92
:event/match_id "match_4580"}

{:event/type "shotoff"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Lucas Leiva"
:event/sortorder 11
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5523788"
:event/minute 93
:event/match_id "match_4580"}

{:event/type "shoton"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "distance"
:event/player1 "Daniel Sturridge"
:event/sortorder 14
:event/team "home"
:event/event_type "shoton"
:event/id "event_5523791"
:event/minute 94
:event/match_id "match_4580"}

{:event/type "corner"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "short_left"
:event/player1 "Jordon Ibe"
:event/sortorder 15
:event/team "home"
:event/event_type "corner"
:event/id "event_5523792"
:event/minute 95
:event/match_id "match_4580"}

{:event/type "cross"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Jordon Ibe"
:event/sortorder 16
:event/team "home"
:event/event_type "cross"
:event/id "event_5523793"
:event/minute 95
:event/match_id "match_4580"}

{:event/type "shoton"
:event/elapsed_plus 7
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Jordon Ibe"
:event/sortorder 21
:event/team "home"
:event/event_type "shoton"
:event/id "event_5523798"
:event/minute 97
:event/match_id "match_4580"}

{:event/type "foulcommit"
:event/elapsed_plus 7
:event/elapsed 90
:event/player2 "Aaron Lennon"
:event/subtype "from_behind"
:event/player1 "Alberto Moreno"
:event/sortorder 22
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5523799"
:event/minute 97
:event/match_id "match_4580"}


]

