
;;# data
[
{:match/id "match_2707"
:match/league "England Premier League"
:match/hometeam "Bolton Wanderers"
:match/awayteam "Aston Villa"
:match/score "3:3"
:match/hometeam_goals "3"
:match/awayteam_goals "2"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Stuart Holden"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1439867"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_2707"}

{:event/type "corner"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Stuart Holden"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1439867"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_2707"}

{:event/type "shoton"
:event/elapsed 1
:event/subtype "blocked_shot"
:event/player1 "Kevin Davies"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_1439872"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/sortorder 5
:event/team "home"
:event/event_type "throwin"
:event/id "event_1439877"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_2707"}

{:event/type "shotoff"
:event/elapsed 2
:event/subtype "distance"
:event/player1 "Johan Elmander"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1439884"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Paul Robinson"
:event/subtype "pushing"
:event/player1 "Marc Albrighton"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1439919"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Johan Elmander"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1439927"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_2707"}

{:event/type "shotoff"
:event/elapsed 6
:event/subtype "shot"
:event/player1 "Gary Cahill"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1439929"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Fabian Delph"
:event/subtype "pushing"
:event/player1 "Kevin Davies"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1439937"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1439945"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed 8
:event/player2 "Fabrice Muamba"
:event/subtype "pushing"
:event/player1 "Ashley Young"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1439953"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Ashley Young"
:event/subtype "from_behind"
:event/player1 "Johan Elmander"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1439979"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_1440032"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_2707"}

{:event/type "corner"
:event/elapsed 14
:event/subtype "short"
:event/player1 "Martin Petrov"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1440036"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_1440038"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_2707"}

{:event/type "shoton"
:event/elapsed 15
:event/subtype "blocked_shot"
:event/player1 "David Wheater"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_1440043"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_2707"}

{:event/type "goal"
:event/elapsed 15
:event/player2 "Kyle Walker"
:event/subtype "shot"
:event/player1 "Darren Bent"
:event/sortorder 4
:event/team "away"
:event/id "event_1440049"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Marc Albrighton"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1440087"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Stuart Holden"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1440134"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Marc Albrighton"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1440141"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_2707"}

{:event/type "shotoff"
:event/elapsed 22
:event/subtype "post"
:event/player1 "Darren Bent"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1440143"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Nathan Baker"
:event/subtype "pushing"
:event/player1 "Kevin Davies"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1440147"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Martin Petrov"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1440156"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Kevin Davies"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1440206"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_2707"}

{:event/type "shotoff"
:event/elapsed 27
:event/subtype "header"
:event/player1 "Daniel Sturridge"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1440209"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Daniel Sturridge"
:event/subtype "pushing"
:event/player1 "Luke Young"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1440227"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Johan Elmander"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1440230"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed 30
:event/player2 "Stewart Downing"
:event/subtype "obstruction"
:event/player1 "Gretar Rafn Steinsson"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1440240"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Gary Cahill"
:event/subtype "pushing"
:event/player1 "Ashley Young"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1440256"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Stuart Holden"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1440272"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Ashley Young"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1440289"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_2707"}

{:event/type "corner"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Ashley Young"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1440289"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Jussi Jaaskelainen"
:event/subtype "pushing"
:event/player1 "Kyle Walker"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1440291"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed 34
:event/player2 "David Wheater"
:event/subtype "pushing"
:event/player1 "Darren Bent"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1440301"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Fabrice Muamba"
:event/subtype "pushing"
:event/player1 "Nigel Reo-Coker"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1440308"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_2707"}

{:event/type "shoton"
:event/elapsed 36
:event/subtype "blocked_shot"
:event/player1 "Martin Petrov"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1440322"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_2707"}

{:event/type "card"
:event/elapsed 37
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Ciaran Clark"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1440330"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_2707"}

{:event/type "shoton"
:event/elapsed 37
:event/subtype "blocked_shot"
:event/player1 "Daniel Sturridge"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1440335"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_1440337"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Fabian Delph"
:event/subtype "obstruction"
:event/player1 "Johan Elmander"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1440350"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_2707"}

{:event/type "card"
:event/elapsed 39
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Johan Elmander"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1440354"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Nathan Baker"
:event/subtype "pushing"
:event/player1 "Kevin Davies"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1440379"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_2707"}

{:event/type "corner"
:event/elapsed 44
:event/subtype "short"
:event/player1 "Stuart Holden"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1440420"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Martin Petrov"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1440421"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Ashley Young"
:event/subtype "pushing"
:event/player1 "Johan Elmander"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1440427"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_1440442"
:event/minute 46
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Stuart Holden"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1440458"
:event/minute 46
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Marc Albrighton"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1440591"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_2707"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "blocked_shot"
:event/player1 "Johan Elmander"
:event/sortorder 5
:event/team "home"
:event/event_type "shoton"
:event/id "event_1440465"
:event/minute 46
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Martin Petrov"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1440473"
:event/minute 47
:event/match_id "match_2707"}

{:event/type "corner"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Martin Petrov"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1440473"
:event/minute 47
:event/match_id "match_2707"}

{:event/type "goal"
:event/elapsed_plus 2
:event/elapsed 45
:event/player2 "Martin Petrov"
:event/subtype "header"
:event/player1 "Gary Cahill"
:event/sortorder 1
:event/team "home"
:event/id "event_1440469"
:event/event_type "goal"
:event/goal_type "n"
:event/minute 47
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 45
:event/player2 "Gretar Rafn Steinsson"
:event/subtype "pushing"
:event/player1 "Marc Albrighton"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1440491"
:event/minute 48
:event/match_id "match_2707"}

{:event/type "shoton"
:event/elapsed 50
:event/subtype "shot"
:event/player1 "Darren Bent"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1440650"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Martin Petrov"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1440680"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Gretar Rafn Steinsson"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1440682"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_2707"}

{:event/type "shotoff"
:event/elapsed 51
:event/subtype "header"
:event/player1 "Daniel Sturridge"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1440685"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Stuart Holden"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1440723"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Marc Albrighton"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_1440731"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_2707"}

{:event/type "shotoff"
:event/elapsed 53
:event/subtype "big chance shot"
:event/player1 "Stewart Downing"
:event/sortorder 5
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1440735"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_2707"}

{:event/type "shoton"
:event/elapsed 54
:event/subtype "blocked_shot"
:event/player1 "Darren Bent"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1440747"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Ashley Young"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1440752"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_2707"}

{:event/type "corner"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Ashley Young"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1440752"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_2707"}

{:event/type "shoton"
:event/elapsed 55
:event/subtype "blocked_shot"
:event/player1 "Stewart Downing"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1440756"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Marc Albrighton"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1440765"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_2707"}

{:event/type "shoton"
:event/elapsed 55
:event/subtype "blocked_shot"
:event/player1 "Darren Bent"
:event/sortorder 4
:event/team "away"
:event/event_type "shoton"
:event/id "event_1440768"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_2707"}

{:event/type "shoton"
:event/elapsed 56
:event/subtype "big chance shot"
:event/player1 "Darren Bent"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1440776"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/sortorder 2
:event/team "home"
:event/event_type "throwin"
:event/id "event_1440780"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Ashley Young"
:event/subtype "pushing"
:event/player1 "David Wheater"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1440804"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Johan Elmander"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1440852"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed 59
:event/subtype "hands"
:event/player1 "Martin Petrov"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1440853"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player2 "David Wheater"
:event/subtype "pushing"
:event/player1 "Darren Bent"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1440880"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Nigel Reo-Coker"
:event/subtype "from_behind"
:event/player1 "Stuart Holden"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1440912"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_2707"}

{:event/type "card"
:event/elapsed 61
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Stuart Holden"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_1440914"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_2707"}

{:event/type "shotoff"
:event/elapsed 62
:event/subtype "distance"
:event/player1 "Ashley Young"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1440922"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Ciaran Clark"
:event/subtype "pushing"
:event/player1 "Johan Elmander"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1440938"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Ashley Young"
:event/subtype "shirt_pull"
:event/player1 "Mark Davies"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1440969"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1440982"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_2707"}

{:event/type "goal"
:event/elapsed 64
:event/player2 "Stewart Downing"
:event/subtype "shot"
:event/player1 "Marc Albrighton"
:event/sortorder 1
:event/team "away"
:event/id "event_1440971"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_2707"}

{:event/type "shotoff"
:event/elapsed 67
:event/subtype "volley"
:event/player1 "Daniel Sturridge"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1440998"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Ashley Young"
:event/subtype "penalty"
:event/player1 "David Wheater"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1441048"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_2707"}

{:event/type "card"
:event/elapsed 69
:event/card_type "y"
:event/subtype "verbal_abuse"
:event/player1 "Gretar Rafn Steinsson"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1441114"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_2707"}

{:event/type "card"
:event/elapsed 69
:event/card_type "y"
:event/subtype "verbal_abuse"
:event/player1 "Jussi Jaaskelainen"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_1441053"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_2707"}

{:event/type "goal"
:event/elapsed 70
:event/subtype "saved_back_into_play"
:event/player1 "Ashley Young"
:event/sortorder 0
:event/team "away"
:event/id "event_1441080"
:event/event_type "goal"
:event/goal_type "npm"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Marc Albrighton"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1441085"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Ashley Young"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1441091"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_2707"}

{:event/type "corner"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Ashley Young"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1441091"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Stuart Holden"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1441122"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_2707"}

{:event/type "corner"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Stuart Holden"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1441122"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed 74
:event/player2 "Ashley Young"
:event/subtype "pushing"
:event/player1 "Paul Robinson"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1441129"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Chung-Yong Lee"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1441150"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_2707"}

{:event/type "corner"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Chung-Yong Lee"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1441150"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_2707"}

{:event/type "shoton"
:event/elapsed 75
:event/subtype "header"
:event/player1 "Gary Cahill"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1441165"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_2707"}

{:event/type "goal"
:event/elapsed 75
:event/subtype "shot"
:event/player1 "Gary Cahill"
:event/sortorder 1
:event/team "home"
:event/id "event_1441152"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Marc Albrighton"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1441186"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Mark Davies"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1441191"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Ashley Young"
:event/subtype "pushing"
:event/player1 "David Wheater"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1441197"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_2707"}

{:event/type "card"
:event/elapsed 77
:event/card_type "y"
:event/subtype "pushing"
:event/player1 "David Wheater"
:event/sortorder 3
:event/team "home"
:event/event_type "card"
:event/id "event_1441201"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_2707"}

{:event/type "shotoff"
:event/elapsed 78
:event/subtype "header"
:event/player1 "Nathan Baker"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1441213"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Stuart Holden"
:event/subtype "pushing"
:event/player1 "Nigel Reo-Coker"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1441265"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Ashley Young"
:event/subtype "pushing"
:event/player1 "Paul Robinson"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1441281"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed 83
:event/player2 "Ashley Young"
:event/subtype "pushing"
:event/player1 "Gary Cahill"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1441323"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1441347"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_2707"}

{:event/type "corner"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1441347"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Kyle Walker"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_1441355"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Daniel Sturridge"
:event/subtype "from_behind"
:event/player1 "Nigel Reo-Coker"
:event/sortorder 6
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1441363"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Gary Cahill"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1441379"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Stuart Holden"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1441389"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_2707"}

{:event/type "corner"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Stuart Holden"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1441389"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Stuart Holden"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1441396"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Stuart Holden"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1441402"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_2707"}

{:event/type "corner"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Stuart Holden"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1441402"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Ivan Klasnic"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_1441406"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_2707"}

{:event/type "shoton"
:event/elapsed 86
:event/subtype "blocked_shot"
:event/player1 "Stuart Holden"
:event/sortorder 6
:event/team "home"
:event/event_type "shoton"
:event/id "event_1441410"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Daniel Sturridge"
:event/sortorder 6
:event/team "home"
:event/event_type "corner"
:event/id "event_1441419"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_2707"}

{:event/type "corner"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Daniel Sturridge"
:event/sortorder 6
:event/team "home"
:event/event_type "corner"
:event/id "event_1441419"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_2707"}

{:event/type "goal"
:event/elapsed 86
:event/subtype "shot"
:event/player1 "Ivan Klasnic"
:event/sortorder 7
:event/team "home"
:event/id "event_1441411"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Ashley Young"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1441451"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_2707"}

{:event/type "corner"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Ashley Young"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1441451"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Nathan Baker"
:event/subtype "pushing"
:event/player1 "Kevin Davies"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1441468"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Nigel Reo-Coker"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1441477"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_2707"}

{:event/type "shoton"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "blocked_shot"
:event/player1 "Stewart Downing"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1441507"
:event/minute 92
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Mark Davies"
:event/subtype "serious_foul"
:event/player1 "Kyle Walker"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1441515"
:event/minute 92
:event/match_id "match_2707"}

{:event/type "card"
:event/elapsed_plus 2
:event/elapsed 90
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Kyle Walker"
:event/sortorder 4
:event/team "away"
:event/event_type "card"
:event/id "event_1441517"
:event/minute 92
:event/match_id "match_2707"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Nathan Baker"
:event/subtype "pushing"
:event/player1 "Kevin Davies"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1441520"
:event/minute 93
:event/match_id "match_2707"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1441546"
:event/minute 94
:event/match_id "match_2707"}

{:event/type "shotoff"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "header"
:event/player1 "Darren Bent"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1441547"
:event/minute 95
:event/match_id "match_2707"}


]

