
;;# data
[
{:match/id "match_9869"
:match/league "Germany 1. Bundesliga"
:match/hometeam "SC Freiburg"
:match/awayteam "SC Paderborn 07"
:match/score "1:2"
:match/hometeam_goals "1"
:match/awayteam_goals "2"}

{:event/type "foulcommit"
:event/elapsed 1
:event/player2 "Elias Kachunga"
:event/subtype "trip"
:event/player1 "Vladimir Darida"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4425297"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Moritz Stoppelkamp"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4425301"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_9869"}

{:event/type "shoton"
:event/elapsed 2
:event/subtype "blocked_shot"
:event/player1 "Moritz Stoppelkamp"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4425310"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_9869"}

{:event/type "corner"
:event/elapsed 2
:event/subtype "cross_right"
:event/player1 "Moritz Stoppelkamp"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4425314"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Elias Kachunga"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4425322"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_9869"}

{:event/type "foulcommit"
:event/elapsed 4
:event/subtype "trip"
:event/player1 "Moritz Stoppelkamp"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4425357"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Admir Mehmedi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4425395"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_9869"}

{:event/type "shotoff"
:event/elapsed 6
:event/subtype "bicycle_kick"
:event/player1 "Nils Petersen"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4425399"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_4425433"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_9869"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Elias Kachunga"
:event/subtype "trip"
:event/player1 "Nicolas Hoefler"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4425460"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_9869"}

{:event/type "shotoff"
:event/elapsed 10
:event/subtype "post"
:event/player1 "Marc Vucinovic"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4425472"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 13
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_4425511"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 13
:event/subtype "cross"
:event/player1 "Moritz Stoppelkamp"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4425516"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Admir Mehmedi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4425549"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_4425566"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_9869"}

{:event/type "shoton"
:event/elapsed 16
:event/subtype "shot"
:event/player1 "Elias Kachunga"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4425575"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Vladimir Darida"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4425580"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_9869"}

{:event/type "corner"
:event/elapsed 17
:event/subtype "cross_right"
:event/player1 "Jonathan Schmid"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4425586"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Jonathan Schmid"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4425589"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/sortorder 1
:event/team "home"
:event/event_type "throwin"
:event/id "event_4425608"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Moritz Stoppelkamp"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4425626"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_9869"}

{:event/type "shoton"
:event/elapsed 20
:event/subtype "header"
:event/player1 "Srdjan Lakic"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4425632"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_9869"}

{:event/type "shoton"
:event/elapsed 21
:event/subtype "blocked_shot"
:event/player1 "Oliver Sorg"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4425639"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_9869"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Julian Schuster"
:event/subtype "from_behind"
:event/player1 "Marvin Bakalorz"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4425649"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_9869"}

{:event/type "shoton"
:event/elapsed 22
:event/subtype "blocked_shot"
:event/player1 "Jonathan Schmid"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4425674"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_9869"}

{:event/type "corner"
:event/elapsed 23
:event/subtype "short_left"
:event/player1 "Jonathan Schmid"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4425676"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_9869"}

{:event/type "foulcommit"
:event/elapsed 23
:event/subtype "pushing"
:event/player1 "Pavel Krmas"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4425691"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_9869"}

{:event/type "corner"
:event/elapsed 24
:event/subtype "cross_left"
:event/player1 "Moritz Stoppelkamp"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4425708"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_9869"}

{:event/type "shoton"
:event/elapsed 25
:event/subtype "volley"
:event/player1 "Marc Vucinovic"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4425724"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Jonathan Schmid"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4425729"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Oliver Sorg"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4425749"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_9869"}

{:event/type "shoton"
:event/elapsed 26
:event/subtype "big chance shot"
:event/player1 "Jonathan Schmid"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_4425757"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_9869"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Vladimir Darida"
:event/subtype "pushing"
:event/player1 "Marvin Bakalorz"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4425773"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Mike Frantz"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4425784"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_9869"}

{:event/type "shoton"
:event/elapsed 28
:event/subtype "big chance shot"
:event/player1 "Admir Mehmedi"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4425795"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_9869"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Marvin Bakalorz"
:event/player1 "Admir Mehmedi"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4429526"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Admir Mehmedi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4425808"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_9869"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Nils Petersen"
:event/subtype "trip"
:event/player1 "Marc Vucinovic"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4425840"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Jonathan Schmid"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4425858"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_9869"}

{:event/type "shoton"
:event/elapsed 32
:event/subtype "blocked_shot"
:event/player1 "Vladimir Darida"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4425861"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_9869"}

{:event/type "corner"
:event/elapsed 32
:event/subtype "cross_right"
:event/player1 "Jonathan Schmid"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4425868"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Jonathan Schmid"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4425938"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_9869"}

{:event/type "corner"
:event/elapsed 36
:event/subtype "cross_left"
:event/player1 "Jonathan Schmid"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4425971"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Elias Kachunga"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4426010"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_9869"}

{:event/type "shotoff"
:event/elapsed 37
:event/subtype "header"
:event/player1 "Srdjan Lakic"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4426014"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_9869"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Maximilian Philipp"
:event/subtype "serious_foul"
:event/player1 "Daniel Brueckner"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4426036"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_9869"}

{:event/type "card"
:event/elapsed 38
:event/card_type "y"
:event/player1 "Daniel Brueckner"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4426048"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Jonathan Schmid"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4426065"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_9869"}

{:event/type "shotoff"
:event/elapsed 39
:event/subtype "distance"
:event/player1 "Julian Schuster"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4426074"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_9869"}

{:event/type "goal"
:event/elapsed 40
:event/player2 "Jonathan Schmid"
:event/subtype "shot"
:event/player1 "Nils Petersen"
:event/sortorder 1
:event/team "home"
:event/id "event_4426114"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_9869"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Moritz Stoppelkamp"
:event/subtype "trip"
:event/player1 "Sascha Riether"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4426151"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Admir Mehmedi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4426195"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Vladimir Darida"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4426253"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Moritz Stoppelkamp"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_4426271"
:event/minute 46
:event/match_id "match_9869"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "shot"
:event/player1 "Elias Kachunga"
:event/sortorder 5
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4426277"
:event/minute 46
:event/match_id "match_9869"}

{:event/type "foulcommit"
:event/elapsed 46
:event/player2 "Maximilian Philipp"
:event/subtype "from_behind"
:event/player1 "Rafa Lopez"
:event/sortorder 5
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4426583"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Sascha Riether"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4426600"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Marc Vucinovic"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4426636"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_9869"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Daniel Brueckner"
:event/subtype "trip"
:event/player1 "Jonathan Schmid"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4426777"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Moritz Stoppelkamp"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4426781"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Marc Vucinovic"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4426800"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_9869"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Julian Schuster"
:event/subtype "trip"
:event/player1 "Moritz Stoppelkamp"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4426852"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_9869"}

{:event/type "shoton"
:event/elapsed 56
:event/subtype "blocked_shot"
:event/player1 "Admir Mehmedi"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4426882"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_9869"}

{:event/type "corner"
:event/elapsed 56
:event/subtype "cross_right"
:event/player1 "Jonathan Schmid"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4426889"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_9869"}

{:event/type "shoton"
:event/elapsed 56
:event/subtype "blocked_shot"
:event/player1 "Admir Mehmedi"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4426894"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_9869"}

{:event/type "shoton"
:event/elapsed 57
:event/subtype "header"
:event/player1 "Pavel Krmas"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4426902"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_9869"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Jens Wemmer"
:event/player1 "Admir Mehmedi"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4429471"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Sascha Riether"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4426933"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Jonathan Schmid"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4426960"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_9869"}

{:event/type "corner"
:event/elapsed 59
:event/subtype "short_right"
:event/player1 "Jonathan Schmid"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4426982"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_9869"}

{:event/type "shotoff"
:event/elapsed 59
:event/subtype "distance"
:event/player1 "Vladimir Darida"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4426988"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_9869"}

{:event/type "corner"
:event/elapsed 61
:event/subtype "cross_right"
:event/player1 "Moritz Stoppelkamp"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4427033"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_9869"}

{:event/type "corner"
:event/elapsed 61
:event/subtype "cross_right"
:event/player1 "Moritz Stoppelkamp"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_4427050"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_9869"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Roman Buerki"
:event/subtype "pushing"
:event/player1 "Patrick Ziegler"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4427065"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Marvin Bakalorz"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4427076"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Marc Vucinovic"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4427087"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_9869"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Nicolas Hoefler"
:event/subtype "pull"
:event/player1 "Elias Kachunga"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4427108"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_9869"}

{:event/type "foulcommit"
:event/elapsed 66
:event/player2 "Jonathan Schmid"
:event/subtype "trip"
:event/player1 "Daniel Brueckner"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4427153"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Admir Mehmedi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4427163"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_9869"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Jens Wemmer"
:event/subtype "serious_foul"
:event/player1 "Julian Schuster"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4427179"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_9869"}

{:event/type "card"
:event/elapsed 68
:event/card_type "y"
:event/player1 "Julian Schuster"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4427182"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Moritz Stoppelkamp"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4427196"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_9869"}

{:event/type "corner"
:event/elapsed 69
:event/subtype "cross_right"
:event/player1 "Moritz Stoppelkamp"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4427202"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_9869"}

{:event/type "corner"
:event/elapsed 69
:event/subtype "cross_right"
:event/player1 "Moritz Stoppelkamp"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_4427218"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_9869"}

{:event/type "goal"
:event/elapsed 70
:event/player2 "Srdjan Lakic"
:event/subtype "shot"
:event/player1 "Lukas Rupp"
:event/sortorder 0
:event/team "away"
:event/id "event_4427240"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Elias Kachunga"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4427263"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_9869"}

{:event/type "shoton"
:event/elapsed 72
:event/subtype "shot"
:event/player1 "Lukas Rupp"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4427267"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Jens Wemmer"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4427308"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Jens Wemmer"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4427321"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Admir Mehmedi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4427364"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_9869"}

{:event/type "foulcommit"
:event/elapsed 78
:event/player2 "Uwe Huenemeier"
:event/subtype "pushing"
:event/player1 "Admir Mehmedi"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4427475"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Mahir Saglik"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4427501"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_9869"}

{:event/type "goal"
:event/elapsed 80
:event/player2 "Mahir Saglik"
:event/subtype "shot"
:event/player1 "Lukas Rupp"
:event/sortorder 0
:event/team "away"
:event/id "event_4427538"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Sascha Riether"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4427575"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_9869"}

{:event/type "corner"
:event/elapsed 81
:event/subtype "short_right"
:event/player1 "Jonathan Schmid"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4427580"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_9869"}

{:event/type "shoton"
:event/elapsed 81
:event/subtype "shot"
:event/player1 "Admir Mehmedi"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4427604"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_9869"}

{:event/type "foulcommit"
:event/elapsed 83
:event/subtype "serious_foul"
:event/player1 "Elias Kachunga"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4427674"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_9869"}

{:event/type "card"
:event/elapsed 83
:event/card_type "y"
:event/player1 "Elias Kachunga"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4427684"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Jonathan Schmid"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4427703"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_9869"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Pavel Krmas"
:event/subtype "trip"
:event/player1 "Moritz Stoppelkamp"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4427725"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Felix Klaus"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4427738"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_9869"}

{:event/type "corner"
:event/elapsed 85
:event/subtype "cross_left"
:event/player1 "Jonathan Schmid"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4427748"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Sascha Riether"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4427791"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_9869"}

{:event/type "foulcommit"
:event/elapsed 87
:event/player2 "Srdjan Lakic"
:event/subtype "pushing"
:event/player1 "Nicolas Hoefler"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4427828"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_9869"}

{:event/type "shotoff"
:event/elapsed 88
:event/subtype "post"
:event/player1 "Christian Guenter"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4427877"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_9869"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player2 "Felix Klaus"
:event/subtype "obstruction"
:event/player1 "Patrick Ziegler"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4427912"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_9869"}

{:event/type "card"
:event/elapsed 89
:event/card_type "y"
:event/player1 "Patrick Ziegler"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4427918"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_9869"}

{:event/type "shotoff"
:event/elapsed 90
:event/subtype "direct_freekick"
:event/player1 "Admir Mehmedi"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4427957"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Jonathan Schmid"
:event/sortorder 6
:event/team "home"
:event/event_type "cross"
:event/id "event_4428056"
:event/minute 92
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Felix Klaus"
:event/sortorder 10
:event/team "home"
:event/event_type "cross"
:event/id "event_4428132"
:event/minute 94
:event/match_id "match_9869"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Vladimir Darida"
:event/sortorder 12
:event/team "home"
:event/event_type "cross"
:event/id "event_4428140"
:event/minute 94
:event/match_id "match_9869"}


]

