
;;# data
[
{:match/id "match_8693"
:match/league "Germany 1. Bundesliga"
:match/hometeam "SV Werder Bremen"
:match/awayteam "Hamburger SV"
:match/score "2:3"
:match/hometeam_goals "3"
:match/awayteam_goals "2"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "Joris Mathijsen"
:event/player1 "Hugo Almeida"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1187251"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_8693"}

{:event/type "foulcommit"
:event/elapsed 5
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1187268"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_8693"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Eljero Elia"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1187296"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_8693"}

{:event/type "foulcommit"
:event/elapsed 11
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1187333"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_8693"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Guy Demel"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1187372"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_8693"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Marko Marin"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1187376"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_8693"}

{:event/type "corner"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Marko Marin"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1187376"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_8693"}

{:event/type "shotoff"
:event/elapsed 17
:event/subtype "header"
:event/player1 "Claudio Pizarro"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1187377"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_8693"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Heiko Westermann"
:event/subtype "pushing"
:event/player1 "Hugo Almeida"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1187382"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_8693"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Tomas Rincon"
:event/player1 "Torsten Frings"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1187383"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_8693"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Marcell Jansen"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1187385"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_8693"}

{:event/type "shotoff"
:event/elapsed 21
:event/subtype "big chance shot"
:event/player1 "Ruud van Nistelrooy"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1187386"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_8693"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Claudio Pizarro"
:event/subtype "pushing"
:event/player1 "Guy Demel"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1187389"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_8693"}

{:event/type "goal"
:event/elapsed 25
:event/player1 "Guy Demel"
:event/sortorder 1
:event/team "away"
:event/id "event_1187392"
:event/event_type "goal"
:event/goal_type "o"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_8693"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Marcell Jansen"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1187393"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_8693"}

{:event/type "corner"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Marcell Jansen"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1187393"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_8693"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player1 "Marcell Jansen"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1187395"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_8693"}

{:event/type "goal"
:event/elapsed 28
:event/player2 "Aaron Hunt"
:event/subtype "header"
:event/player1 "Hugo Almeida"
:event/sortorder 2
:event/team "home"
:event/id "event_1187397"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_8693"}

{:event/type "foulcommit"
:event/elapsed 30
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1187400"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_8693"}

{:event/type "foulcommit"
:event/elapsed 30
:event/player1 "Eljero Elia"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1187403"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_8693"}

{:event/type "card"
:event/elapsed 30
:event/card_type "y"
:event/subtype "emergency_brake"
:event/player1 "Eljero Elia"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_1187404"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_8693"}

{:event/type "foulcommit"
:event/elapsed 32
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1187409"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_8693"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player1 "Clemens Fritz"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1187420"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_8693"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Mikael Silvestre"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1187433"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_8693"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Torsten Frings"
:event/subtype "serious_foul"
:event/player1 "Tomas Rincon"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1187437"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_8693"}

{:event/type "card"
:event/elapsed 36
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Tomas Rincon"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_1187439"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_8693"}

{:event/type "shoton"
:event/elapsed 39
:event/subtype "shot"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1187460"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_8693"}

{:event/type "shoton"
:event/elapsed 40
:event/subtype "blocked_shot"
:event/player1 "Ze Roberto"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1187466"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_8693"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player1 "David Jarolim"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1187498"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_8693"}

{:event/type "shotoff"
:event/elapsed 45
:event/subtype "shot"
:event/player1 "Ruud van Nistelrooy"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1187508"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_8693"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Eljero Elia"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1187641"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_8693"}

{:event/type "corner"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Eljero Elia"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1187641"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_8693"}

{:event/type "shoton"
:event/elapsed 47
:event/subtype "shot"
:event/player1 "Marcell Jansen"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1187645"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_8693"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Ze Roberto"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1187646"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_8693"}

{:event/type "corner"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Ze Roberto"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1187646"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_8693"}

{:event/type "shotoff"
:event/elapsed 48
:event/subtype "bad shot"
:event/player1 "Marcell Jansen"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1187649"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_8693"}

{:event/type "shotoff"
:event/elapsed 48
:event/subtype "distance"
:event/player1 "Hugo Almeida"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1187656"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_8693"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Ruud van Nistelrooy"
:event/player1 "Philipp Bargfrede"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1187670"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_8693"}

{:event/type "foulcommit"
:event/elapsed 59
:event/player2 "David Jarolim"
:event/player1 "Philipp Bargfrede"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1187746"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_8693"}

{:event/type "goal"
:event/elapsed 59
:event/subtype "shot"
:event/player1 "Ruud van Nistelrooy"
:event/sortorder 1
:event/team "away"
:event/id "event_1187747"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_8693"}

{:event/type "foulcommit"
:event/elapsed 61
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1187758"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_8693"}

{:event/type "shotoff"
:event/elapsed 62
:event/subtype "deflected"
:event/player1 "Jonathan Pitroipa"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1187773"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_8693"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Ze Roberto"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1187774"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_8693"}

{:event/type "corner"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Ze Roberto"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1187774"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_8693"}

{:event/type "goal"
:event/elapsed 63
:event/subtype "shot"
:event/player1 "Jonathan Pitroipa"
:event/sortorder 0
:event/team "away"
:event/id "event_1187775"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_8693"}

{:event/type "shotoff"
:event/elapsed 66
:event/subtype "big chance shot"
:event/player1 "Hugo Almeida"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1187789"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_8693"}

{:event/type "foulcommit"
:event/elapsed 66
:event/player2 "Marko Marin"
:event/player1 "Eric Maxim Choupo-Moting"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1187792"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_8693"}

{:event/type "shotoff"
:event/elapsed 67
:event/subtype "direct_freekick"
:event/player1 "Hugo Almeida"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1187797"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_8693"}

{:event/type "shoton"
:event/elapsed 67
:event/subtype "big chance shot"
:event/player1 "Claudio Pizarro"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_1187802"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_8693"}

{:event/type "foulcommit"
:event/elapsed 74
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1187811"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_8693"}

{:event/type "shotoff"
:event/elapsed 76
:event/subtype "deflected"
:event/player1 "Eric Maxim Choupo-Moting"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1187815"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_8693"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Ze Roberto"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1187817"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_8693"}

{:event/type "corner"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Ze Roberto"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1187817"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_8693"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Marko Marin"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1187820"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_8693"}

{:event/type "shoton"
:event/elapsed 77
:event/subtype "shot"
:event/player1 "Claudio Pizarro"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1187821"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_8693"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Aaron Hunt"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1187822"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_8693"}

{:event/type "corner"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Aaron Hunt"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1187822"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_8693"}

{:event/type "shoton"
:event/elapsed 77
:event/subtype "shot"
:event/player1 "Mikael Silvestre"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_1187823"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_8693"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player1 "Daniel Jensen"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1187842"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_8693"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Wesley"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1187847"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_8693"}

{:event/type "goal"
:event/elapsed 85
:event/player2 "Wesley"
:event/subtype "shot"
:event/player1 "Hugo Almeida"
:event/sortorder 4
:event/team "home"
:event/id "event_1187848"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_8693"}

{:event/type "shotoff"
:event/elapsed 89
:event/subtype "deflected"
:event/player1 "Ruud van Nistelrooy"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1187858"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_8693"}

{:event/type "corner"
:event/elapsed 89
:event/subtype "short"
:event/player1 "Gojko Kacar"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1187859"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_8693"}

{:event/type "shoton"
:event/elapsed 89
:event/subtype "shot"
:event/player1 "Gojko Kacar"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1187860"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_8693"}

{:event/type "shotoff"
:event/elapsed 89
:event/subtype "header"
:event/player1 "Joris Mathijsen"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1187861"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_8693"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1187867"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_8693"}

{:event/type "shoton"
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Ruud van Nistelrooy"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1187868"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_8693"}

{:event/type "card"
:event/elapsed_plus 2
:event/elapsed 90
:event/card_type "y"
:event/subtype "stall_time"
:event/player1 "Tim Wiese"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1187873"
:event/minute 92
:event/match_id "match_8693"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "David Jarolim"
:event/player1 "Philipp Bargfrede"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1187877"
:event/minute 92
:event/match_id "match_8693"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Piotr Trochowski"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1187881"
:event/minute 93
:event/match_id "match_8693"}

{:event/type "corner"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Piotr Trochowski"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1187881"
:event/minute 93
:event/match_id "match_8693"}


]

