
;;# data
[
{:match/id "match_22443"
:match/league "Spain LIGA BBVA"
:match/hometeam "Villarreal CF"
:match/awayteam "Málaga CF"
:match/score "1:1"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Marco Ruben"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1421242"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_22443"}

{:event/type "foulcommit"
:event/elapsed 2
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1421244"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_22443"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Antonio Apono"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1421246"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_22443"}

{:event/type "corner"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Antonio Apono"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1421246"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_22443"}

{:event/type "shotoff"
:event/elapsed 3
:event/subtype "header"
:event/player1 "Martin Demichelis"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1421247"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_22443"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Manolo Gaspar,28"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1421258"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_22443"}

{:event/type "foulcommit"
:event/elapsed 7
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1421263"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_22443"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Antonio Apono"
:event/player1 "Borja Valero"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1421271"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_22443"}

{:event/type "foulcommit"
:event/elapsed 11
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1421276"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_22443"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Joan Capdevila"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1421291"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_22443"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Marco Ruben"
:event/subtype "from_behind"
:event/player1 "Weligton"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1421299"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_22443"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Jose Salomon Rondon"
:event/subtype "serious_foul"
:event/player1 "Bruno Soriano"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1421316"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_22443"}

{:event/type "card"
:event/elapsed 21
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Bruno Soriano"
:event/sortorder 3
:event/team "home"
:event/event_type "card"
:event/id "event_1421317"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_22443"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Borja Valero"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1421320"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_22443"}

{:event/type "corner"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Borja Valero"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1421320"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_22443"}

{:event/type "foulcommit"
:event/elapsed 24
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1421321"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_22443"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Borja Valero"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1421326"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_22443"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Mario Gaspar"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1421327"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_22443"}

{:event/type "foulcommit"
:event/elapsed 29
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1421334"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_22443"}

{:event/type "shotoff"
:event/elapsed 30
:event/subtype "shot"
:event/player1 "Jose Salomon Rondon"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1421339"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_22443"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Carlos Marchena"
:event/player1 "Jose Recio"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1421351"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_22443"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Giuseppe Rossi"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1421368"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_22443"}

{:event/type "goal"
:event/elapsed 36
:event/player2 "Giuseppe Rossi"
:event/subtype "shot"
:event/player1 "Marco Ruben"
:event/sortorder 5
:event/team "home"
:event/id "event_1421366"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_22443"}

{:event/type "shotoff"
:event/elapsed 39
:event/subtype "distance"
:event/player1 "Mario Gaspar"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1421380"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_22443"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Weligton"
:event/subtype "pushing"
:event/player1 "Marco Ruben"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1421386"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_22443"}

{:event/type "foulcommit"
:event/elapsed 42
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1421395"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_22443"}

{:event/type "shoton"
:event/elapsed 45
:event/subtype "shot"
:event/player1 "Nilmar"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1421416"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_22443"}

{:event/type "foulcommit"
:event/elapsed 46
:event/subtype "pushing"
:event/player1 "Francisco Portillo"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1421492"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_22443"}

{:event/type "shoton"
:event/elapsed 48
:event/subtype "shot"
:event/player1 "Nilmar"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1421504"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_22443"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Eliseu"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1421512"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_22443"}

{:event/type "shoton"
:event/elapsed 49
:event/subtype "distance"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1421523"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_22443"}

{:event/type "foulcommit"
:event/elapsed 50
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1421529"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_22443"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Eliseu"
:event/player1 "Marco Ruben"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1421540"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_22443"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Borja Valero"
:event/player1 "Sebastian Fernandez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1421546"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_22443"}

{:event/type "shotoff"
:event/elapsed 53
:event/subtype "bad shot"
:event/player1 "Eliseu"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1421553"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_22443"}

{:event/type "shotoff"
:event/elapsed 62
:event/subtype "big chance shot"
:event/player1 "Sebastian Fernandez"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1421618"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_22443"}

{:event/type "shotoff"
:event/elapsed 63
:event/subtype "big chance shot"
:event/player1 "Nilmar"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1421625"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_22443"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Martin Demichelis"
:event/subtype "pushing"
:event/player1 "Marco Ruben"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1421635"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_22443"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1421644"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_22443"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Borja Valero"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1421651"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_22443"}

{:event/type "corner"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Borja Valero"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1421651"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_22443"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Sebastian Fernandez"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1421664"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_22443"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Joan Capdevila"
:event/subtype "from_behind"
:event/player1 "Enzo Maresca"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1421703"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_22443"}

{:event/type "card"
:event/elapsed 77
:event/card_type "y"
:event/player1 "Enzo Maresca"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1421705"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_22443"}

{:event/type "shotoff"
:event/elapsed 78
:event/subtype "crossbar"
:event/player1 "Santi Cazorla"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1421711"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_22443"}

{:event/type "shoton"
:event/elapsed 78
:event/subtype "big chance shot"
:event/player1 "Santi Cazorla"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1421713"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_22443"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Jose Salomon Rondon"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1421745"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_22443"}

{:event/type "goal"
:event/elapsed 82
:event/player2 "Jose Salomon Rondon"
:event/subtype "shot"
:event/player1 "Sebastian Fernandez"
:event/sortorder 1
:event/team "away"
:event/id "event_1421741"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_22443"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Borja Valero"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1421757"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_22443"}

{:event/type "corner"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Borja Valero"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1421757"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_22443"}

{:event/type "shotoff"
:event/elapsed 84
:event/subtype "header"
:event/player1 "Bruno Soriano"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1421758"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_22443"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Sebastian Fernandez"
:event/subtype "pushing"
:event/player1 "Mario Gaspar"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1421774"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_22443"}

{:event/type "shotoff"
:event/elapsed 86
:event/subtype "distance"
:event/player1 "Giuseppe Rossi"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1421779"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_22443"}

{:event/type "foulcommit"
:event/elapsed 87
:event/subtype "hands"
:event/player1 "Jose Salomon Rondon"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1421788"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_22443"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Borja Valero"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1421818"
:event/minute 92
:event/match_id "match_22443"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Gonzalo Rodriguez"
:event/player1 "Jose Salomon Rondon"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1421822"
:event/minute 92
:event/match_id "match_22443"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "pushing"
:event/player1 "Jose Salomon Rondon"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1421824"
:event/minute 93
:event/match_id "match_22443"}


]

