
;;# data
[
{:match/id "match_9149"
:match/league "Germany 1. Bundesliga"
:match/hometeam "Hamburger SV"
:match/awayteam "Eintracht Frankfurt"
:match/score "0:2"
:match/hometeam_goals "0"
:match/awayteam_goals "2"}

{:event/type "card"
:event/elapsed 18
:event/card_type "y"
:event/player1 "Milan Badelj"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2580224"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_9149"}

{:event/type "goal"
:event/elapsed 22
:event/player1 "Srdjan Lakic"
:event/sortorder 0
:event/team "away"
:event/id "event_2580223"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_9149"}

{:event/type "goal"
:event/elapsed 36
:event/player1 "Srdjan Lakic"
:event/sortorder 0
:event/team "away"
:event/id "event_2580289"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_9149"}

{:event/type "card"
:event/elapsed 71
:event/card_type "y"
:event/player1 "Artjoms Rudnevs"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2580511"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_9149"}

{:event/type "card"
:event/elapsed 83
:event/card_type "y"
:event/player1 "Jeffrey Bruma"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2580573"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_9149"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Karim Matmour"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2580618"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_9149"}


]

