
;;# data
[
{:match/id "match_8619"
:match/league "Germany 1. Bundesliga"
:match/hometeam "FC Bayern Munich"
:match/awayteam "SV Werder Bremen"
:match/score "0:0"
:match/hometeam_goals "0"
:match/awayteam_goals "0"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Philipp Bargfrede"
:event/subtype "pushing"
:event/player1 "Thomas Mueller"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1158825"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_8619"}

{:event/type "shotoff"
:event/elapsed 3
:event/subtype "shot"
:event/player1 "Marko Arnautovic"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1158838"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_8619"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Marko Arnautovic"
:event/subtype "pushing"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1158858"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_8619"}

{:event/type "shotoff"
:event/elapsed 5
:event/subtype "post"
:event/player1 "Philipp Bargfrede"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1158865"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_8619"}

{:event/type "foulcommit"
:event/elapsed 6
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1158869"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_8619"}

{:event/type "shoton"
:event/elapsed 7
:event/subtype "shot"
:event/player1 "Franck Ribery"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1158881"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_8619"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Diego Contento"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1158888"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_8619"}

{:event/type "shoton"
:event/elapsed 9
:event/subtype "shot"
:event/player1 "Thomas Mueller"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1158892"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_8619"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Diego Contento"
:event/subtype "from_behind"
:event/player1 "Wesley"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1158898"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_8619"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Franck Ribery"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1158904"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_8619"}

{:event/type "corner"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Franck Ribery"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1158904"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_8619"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Philipp Lahm"
:event/subtype "pushing"
:event/player1 "Marko Arnautovic"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1158911"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_8619"}

{:event/type "shotoff"
:event/elapsed 12
:event/subtype "big chance header"
:event/player1 "Thomas Mueller"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1158915"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_8619"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player1 "Bastian Schweinsteiger"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1158920"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_8619"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Thomas Mueller"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1158944"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_8619"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player1 "Mark van Bommel"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1158951"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_8619"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Diego Contento"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1158965"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_8619"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Franck Ribery"
:event/player1 "Clemens Fritz"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1158999"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_8619"}

{:event/type "shoton"
:event/elapsed 21
:event/subtype "blocked_shot"
:event/player1 "Ivica Olic"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1159000"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_8619"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Franck Ribery"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1159002"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_8619"}

{:event/type "foulcommit"
:event/elapsed 23
:event/subtype "hands"
:event/player1 "Thomas Mueller"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1159003"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_8619"}

{:event/type "shoton"
:event/elapsed 24
:event/subtype "shot"
:event/player1 "Franck Ribery"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1159005"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_8619"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Diego Contento"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1159006"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_8619"}

{:event/type "corner"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Diego Contento"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1159006"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_8619"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Marko Marin"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1159008"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_8619"}

{:event/type "corner"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Marko Marin"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1159008"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_8619"}

{:event/type "shoton"
:event/elapsed 32
:event/subtype "big chance shot"
:event/player1 "Marko Marin"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1159017"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_8619"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Aaron Hunt"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1159020"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_8619"}

{:event/type "corner"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Aaron Hunt"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1159020"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_8619"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Wesley"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1159041"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_8619"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Holger Badstuber"
:event/subtype "shirt_pull"
:event/player1 "Marko Arnautovic"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1159059"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_8619"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Thomas Mueller"
:event/player1 "Philipp Bargfrede"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1159082"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_8619"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Franck Ribery"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1159090"
:event/minute 46
:event/match_id "match_8619"}

{:event/type "corner"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Franck Ribery"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1159090"
:event/minute 46
:event/match_id "match_8619"}

{:event/type "shotoff"
:event/elapsed 47
:event/subtype "big chance shot"
:event/player1 "Franck Ribery"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1159196"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_8619"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Diego Contento"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1159202"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_8619"}

{:event/type "shotoff"
:event/elapsed 50
:event/subtype "shot"
:event/player1 "Wesley"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1159215"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_8619"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Marko Arnautovic"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1159222"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_8619"}

{:event/type "shoton"
:event/elapsed 50
:event/subtype "blocked_shot"
:event/player1 "Wesley"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_1159223"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_8619"}

{:event/type "shotoff"
:event/elapsed 52
:event/subtype "distance"
:event/player1 "Aaron Hunt"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1159239"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_8619"}

{:event/type "shotoff"
:event/elapsed 53
:event/subtype "shot"
:event/player1 "Toni Kroos"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1159243"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_8619"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Franck Ribery"
:event/player1 "Clemens Fritz"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1159251"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_8619"}

{:event/type "shoton"
:event/elapsed 54
:event/subtype "big chance shot"
:event/player1 "Toni Kroos"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1159256"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_8619"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Franck Ribery"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1159258"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_8619"}

{:event/type "corner"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Franck Ribery"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1159258"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_8619"}

{:event/type "shotoff"
:event/elapsed 54
:event/subtype "shot"
:event/player1 "Ivica Olic"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1159259"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_8619"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Holger Badstuber"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1159280"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_8619"}

{:event/type "corner"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Holger Badstuber"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1159280"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_8619"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Wesley"
:event/player1 "Mark van Bommel"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1159286"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_8619"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Marko Marin"
:event/player1 "Bastian Schweinsteiger"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1159310"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_8619"}

{:event/type "shoton"
:event/elapsed 63
:event/subtype "blocked_shot"
:event/player1 "Franck Ribery"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1159328"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_8619"}

{:event/type "shoton"
:event/elapsed 64
:event/subtype "shot"
:event/player1 "Marko Arnautovic"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1159331"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_8619"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Bastian Schweinsteiger"
:event/subtype "obstruction"
:event/player1 "Philipp Bargfrede"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1159334"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_8619"}

{:event/type "shotoff"
:event/elapsed 65
:event/subtype "shot"
:event/player1 "Ivica Olic"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1159339"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_8619"}

{:event/type "foulcommit"
:event/elapsed 66
:event/player1 "Ivica Olic"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1159344"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_8619"}

{:event/type "shoton"
:event/elapsed 67
:event/subtype "distance"
:event/player1 "Toni Kroos"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1159349"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_8619"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Holger Badstuber"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1159350"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_8619"}

{:event/type "corner"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Holger Badstuber"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1159350"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_8619"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Mark van Bommel"
:event/player1 "Aaron Hunt"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1159355"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_8619"}

{:event/type "foulcommit"
:event/elapsed 69
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1159356"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_8619"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Marko Marin"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1159358"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_8619"}

{:event/type "shotoff"
:event/elapsed 71
:event/subtype "shot"
:event/player1 "Tim Borowski"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1159359"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_8619"}

{:event/type "foulcommit"
:event/elapsed 72
:event/player2 "Tim Borowski"
:event/player1 "Mark van Bommel"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1159366"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_8619"}

{:event/type "shoton"
:event/elapsed 76
:event/subtype "shot"
:event/player1 "Diego Contento"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1159375"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_8619"}

{:event/type "shoton"
:event/elapsed 78
:event/subtype "blocked_shot"
:event/player1 "Franck Ribery"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1159381"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_8619"}

{:event/type "shotoff"
:event/elapsed 81
:event/subtype "shot"
:event/player1 "Mario Gomez"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1159391"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_8619"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Toni Kroos"
:event/player1 "Philipp Bargfrede"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1159394"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_8619"}

{:event/type "shotoff"
:event/elapsed 83
:event/subtype "direct_freekick"
:event/player1 "Franck Ribery"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1159395"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_8619"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Franck Ribery"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1159404"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_8619"}

{:event/type "corner"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Franck Ribery"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1159404"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_8619"}

{:event/type "foulcommit"
:event/elapsed 87
:event/player2 "Sebastian Proedl"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1159413"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_8619"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Franck Ribery"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1159414"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_8619"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Toni Kroos"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1159415"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_8619"}

{:event/type "corner"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Toni Kroos"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1159415"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_8619"}

{:event/type "shoton"
:event/elapsed 89
:event/subtype "shot"
:event/player1 "Hugo Almeida"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1159420"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_8619"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Bastian Schweinsteiger"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1159427"
:event/minute 91
:event/match_id "match_8619"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Diego Contento"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1159430"
:event/minute 92
:event/match_id "match_8619"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Holger Badstuber"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_1159433"
:event/minute 92
:event/match_id "match_8619"}

{:event/type "corner"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Holger Badstuber"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_1159433"
:event/minute 92
:event/match_id "match_8619"}

{:event/type "corner"
:event/elapsed_plus 3
:event/elapsed 90
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1159435"
:event/minute 93
:event/match_id "match_8619"}


]

