
;;# data
[
{:match/id "match_9324"
:match/league "Germany 1. Bundesliga"
:match/hometeam "SV Werder Bremen"
:match/awayteam "Borussia Mönchengladbach"
:match/score "4:0"
:match/hometeam_goals "4"
:match/awayteam_goals "0"}

{:event/type "goal"
:event/elapsed 37
:event/player1 "Nils Petersen"
:event/sortorder 0
:event/team "home"
:event/id "event_2426409"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_9324"}

{:event/type "goal"
:event/elapsed 45
:event/player1 "Marko Arnautovic"
:event/sortorder 0
:event/team "home"
:event/id "event_2426450"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_9324"}

{:event/type "card"
:event/elapsed 54
:event/card_type "y"
:event/player1 "Kevin de Bruyne"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2426603"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_9324"}

{:event/type "card"
:event/elapsed 59
:event/card_type "y"
:event/player1 "Haavard Nordtveit"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2426604"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_9324"}

{:event/type "card"
:event/elapsed 60
:event/card_type "y"
:event/player1 "Patrick Herrmann"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2426641"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_9324"}

{:event/type "goal"
:event/elapsed 75
:event/player1 "Niclas Fuellkrug"
:event/sortorder 0
:event/team "home"
:event/id "event_2426702"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_9324"}

{:event/type "goal"
:event/elapsed 86
:event/player1 "Zlatko Junuzovic"
:event/sortorder 0
:event/team "home"
:event/id "event_2426703"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_9324"}


]

