
;;# data
[
{:match/id "match_6954"
:match/league "France Ligue 1"
:match/hometeam "Olympique Lyonnais"
:match/awayteam "SC Bastia"
:match/score "4:1"
:match/hometeam_goals "4"
:match/awayteam_goals "1"}

{:event/type "goal"
:event/elapsed 14
:event/player2 "Henri Bedimo"
:event/player1 "Bafetimbi Gomis"
:event/sortorder 0
:event/team "home"
:event/id "event_3427313"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_6954"}

{:event/type "goal"
:event/elapsed 23
:event/player1 "Nabil Fekir"
:event/sortorder 0
:event/team "home"
:event/id "event_3427405"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_6954"}

{:event/type "card"
:event/elapsed 24
:event/card_type "y"
:event/player1 "Nabil Fekir"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3427428"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_6954"}

{:event/type "card"
:event/elapsed 39
:event/card_type "y"
:event/player1 "Wahbi Khazri"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3427569"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_6954"}

{:event/type "goal"
:event/elapsed 47
:event/player1 "Gianni Bruno"
:event/sortorder 0
:event/team "away"
:event/id "event_3427751"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_6954"}

{:event/type "goal"
:event/elapsed 50
:event/player2 "Nabil Fekir"
:event/player1 "Bakary Kone"
:event/sortorder 0
:event/team "home"
:event/id "event_3427793"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_6954"}

{:event/type "goal"
:event/elapsed 64
:event/player2 "Nabil Fekir"
:event/player1 "Alexandre Lacazette"
:event/sortorder 0
:event/team "home"
:event/id "event_3427983"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_6954"}

{:event/type "card"
:event/elapsed 70
:event/card_type "y"
:event/player1 "Bakary Kone"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_3428170"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_6954"}


]

