
;;# data
[
{:match/id "match_1955"
:match/league "England Premier League"
:match/hometeam "Middlesbrough"
:match/awayteam "Stoke City"
:match/score "4:0"
:match/hometeam_goals "2"
:match/awayteam_goals "1"}

{:event/type "shotoff"
:event/elapsed 2
:event/subtype "distance"
:event/player1 "Liam Lawrence"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_388163"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_1955"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "Liam Lawrence"
:event/player1 "Afonso Alves,24"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_388181"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_1955"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Tuncay Sanli"
:event/player1 "Amdy Faye"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_388192"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_1955"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_388208"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_1955"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Carl Dickinson"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_388242"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_1955"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_388247"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_1955"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Liam Lawrence"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_388258"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_1955"}

{:event/type "corner"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Liam Lawrence"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_388258"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_1955"}

{:event/type "shotoff"
:event/elapsed 9
:event/subtype "distance"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_388264"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_1955"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player1 "Rory Delap"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_388274"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_1955"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Jeremie Aliadiere"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_388303"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_1955"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Gary O'Neil"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_388329"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_1955"}

{:event/type "shotoff"
:event/elapsed 12
:event/subtype "header"
:event/player1 "Afonso Alves,24"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_388331"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_1955"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Ricardo Fuller"
:event/player1 "Robert Huth"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_388346"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_1955"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Liam Lawrence"
:event/player1 "Gary O'Neil"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_388371"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_1955"}

{:event/type "shotoff"
:event/elapsed 16
:event/subtype "distance"
:event/player1 "Ricardo Fuller"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_388384"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_1955"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "Afonso Alves,24"
:event/player1 "Amdy Faye"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_388398"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_1955"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_388406"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_1955"}

{:event/type "shoton"
:event/elapsed 18
:event/subtype "shot"
:event/player1 "Mohamed Shawky"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_388422"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_1955"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Dave Kitson"
:event/player1 "Robert Huth"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_388428"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_1955"}

{:event/type "shoton"
:event/elapsed 19
:event/subtype "direct_freekick"
:event/player1 "Liam Lawrence"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_388439"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_1955"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Liam Lawrence"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_388444"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_1955"}

{:event/type "corner"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Liam Lawrence"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_388444"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_1955"}

{:event/type "shotoff"
:event/elapsed 21
:event/subtype "shot"
:event/player1 "Ricardo Fuller"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_388454"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_1955"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Robert Huth"
:event/player1 "Ricardo Fuller"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_388465"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_1955"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Rory Delap"
:event/player1 "Justin Hoyte"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_388478"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_1955"}

{:event/type "corner"
:event/elapsed 24
:event/subtype "short"
:event/player1 "Liam Lawrence"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_388491"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_1955"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Liam Lawrence"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_388496"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_1955"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Liam Lawrence"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_388497"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_1955"}

{:event/type "corner"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Liam Lawrence"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_388497"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_1955"}

{:event/type "foulcommit"
:event/elapsed 25
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_388512"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_1955"}

{:event/type "card"
:event/elapsed 28
:event/card_type "y"
:event/player1 "Andy Griffin"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_388553"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_1955"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Gary O'Neil"
:event/player1 "Ricardo Fuller"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_388568"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_1955"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Liam Lawrence"
:event/player1 "Emanuel Pogatetz"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_388586"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_1955"}

{:event/type "shotoff"
:event/elapsed 32
:event/subtype "distance"
:event/player1 "Abdoulaye Faye"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_388597"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_1955"}

{:event/type "foulcommit"
:event/elapsed 34
:event/player2 "Dave Kitson"
:event/player1 "Robert Huth"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_388626"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_1955"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Mohamed Shawky"
:event/subtype "serious_foul"
:event/player1 "Abdoulaye Faye"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_388646"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_1955"}

{:event/type "card"
:event/elapsed 36
:event/card_type "r"
:event/subtype "serious_fouls"
:event/player1 "Amdy Faye"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_388648"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_1955"}

{:event/type "goal"
:event/elapsed 38
:event/subtype "direct_freekick"
:event/player1 "Afonso Alves,24"
:event/sortorder 0
:event/team "home"
:event/id "event_388676"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_1955"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Dave Kitson"
:event/player1 "Mohamed Shawky"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_388691"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_1955"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player1 "Dave Kitson"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_388692"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_1955"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Mohamed Shawky"
:event/player1 "Carl Dickinson"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_388722"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_1955"}

{:event/type "shotoff"
:event/elapsed 42
:event/subtype "distance"
:event/player1 "Afonso Alves,24"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_388739"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_1955"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Jeremie Aliadiere"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_388757"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_1955"}

{:event/type "shotoff"
:event/elapsed 44
:event/subtype "deflected"
:event/player1 "Tuncay Sanli"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_388761"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_1955"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_388766"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_1955"}

{:event/type "corner"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_388766"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_1955"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player1 "David Wheater"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_388768"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_1955"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "Robert Huth"
:event/player1 "Seyi Olofinjana"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_388799"
:event/minute 46
:event/match_id "match_1955"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_388905"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_1955"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Jeremie Aliadiere"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_388937"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_1955"}

{:event/type "foulcommit"
:event/elapsed 49
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_388943"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_1955"}

{:event/type "shotoff"
:event/elapsed 50
:event/subtype "direct_freekick"
:event/player1 "Stewart Downing"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_388950"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_1955"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_388968"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_1955"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_388980"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_1955"}

{:event/type "corner"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_388980"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_1955"}

{:event/type "shotoff"
:event/elapsed 51
:event/subtype "crossbar"
:event/player1 "Gary O'Neil"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_388983"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_1955"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Justin Hoyte"
:event/subtype "serious_foul"
:event/player1 "Ricardo Fuller"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_388999"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_1955"}

{:event/type "card"
:event/elapsed 52
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Ricardo Fuller"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_389004"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_1955"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Ricardo Fuller"
:event/player1 "Robert Huth"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_389047"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_1955"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Dave Kitson"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_389053"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_1955"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Afonso Alves,24"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_389070"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_1955"}

{:event/type "shotoff"
:event/elapsed 57
:event/subtype "crossbar"
:event/player1 "Tuncay Sanli"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_389073"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_1955"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_389088"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_1955"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player1 "Gary O'Neil"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_389095"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_1955"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Tuncay Sanli"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_389116"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_1955"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_389152"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_1955"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Robert Huth"
:event/player1 "Ricardo Fuller"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_389191"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_1955"}

{:event/type "shoton"
:event/elapsed 63
:event/subtype "shot"
:event/player1 "Stewart Downing"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_389204"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_1955"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Afonso Alves,24"
:event/subtype "penalty"
:event/player1 "Seyi Olofinjana"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_389216"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_1955"}

{:event/type "card"
:event/elapsed 64
:event/card_type "y"
:event/subtype "verbal_abuse"
:event/player1 "Liam Lawrence"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_389527"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_1955"}

{:event/type "goal"
:event/elapsed 65
:event/subtype "crossbar"
:event/player1 "Stewart Downing"
:event/sortorder 0
:event/team "home"
:event/id "event_389225"
:event/event_type "goal"
:event/goal_type "npm"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_1955"}

{:event/type "shotoff"
:event/elapsed 67
:event/subtype "distance"
:event/player1 "Didier Digard"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_389263"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_1955"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Dave Kitson"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_389285"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_1955"}

{:event/type "shotoff"
:event/elapsed 70
:event/subtype "shot"
:event/player1 "Tuncay Sanli"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_389298"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_1955"}

{:event/type "shotoff"
:event/elapsed 71
:event/subtype "deflected"
:event/player1 "Tuncay Sanli"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_389310"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_1955"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Gary O'Neil"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_389314"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_1955"}

{:event/type "corner"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Gary O'Neil"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_389314"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_1955"}

{:event/type "shotoff"
:event/elapsed 71
:event/subtype "shot"
:event/player1 "Didier Digard"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_389316"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_1955"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Liam Lawrence"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_389323"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_1955"}

{:event/type "goal"
:event/elapsed 72
:event/player1 "Justin Hoyte"
:event/sortorder 0
:event/team "home"
:event/id "event_389329"
:event/event_type "goal"
:event/goal_type "o"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_1955"}

{:event/type "shoton"
:event/elapsed 73
:event/subtype "shot"
:event/player1 "Tuncay Sanli"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_389340"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_1955"}

{:event/type "shoton"
:event/elapsed 76
:event/subtype "shot"
:event/player1 "Afonso Alves,24"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_389377"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_1955"}

{:event/type "foulcommit"
:event/elapsed 78
:event/player2 "Dave Kitson"
:event/subtype "serious_foul"
:event/player1 "Gary O'Neil"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_389414"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_1955"}

{:event/type "card"
:event/elapsed 79
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Gary O'Neil"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_389417"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_1955"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_389429"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_1955"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Andrew Taylor"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_389444"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_1955"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Mamady Sidibe"
:event/subtype "serious_foul"
:event/player1 "Robert Huth"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_389450"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_1955"}

{:event/type "card"
:event/elapsed 81
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Robert Huth"
:event/sortorder 3
:event/team "home"
:event/event_type "card"
:event/id "event_389452"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_1955"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Jeremie Aliadiere"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_389467"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_1955"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_389504"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_1955"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Didier Digard"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_389511"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_1955"}

{:event/type "goal"
:event/elapsed 86
:event/player2 "Didier Digard"
:event/subtype "shot"
:event/player1 "Tuncay Sanli"
:event/sortorder 1
:event/team "home"
:event/id "event_389515"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_1955"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Rory Delap"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_389523"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_1955"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Stewart Downing"
:event/subtype "serious_foul"
:event/player1 "Andy Wilkinson"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_389564"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_1955"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Andy Wilkinson"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_389566"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_1955"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Robert Huth"
:event/player1 "Richard Cresswell"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_389586"
:event/minute 91
:event/match_id "match_1955"}

{:event/type "corner"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "short"
:event/player1 "Stewart Downing"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_389611"
:event/minute 94
:event/match_id "match_1955"}

{:event/type "foulcommit"
:event/elapsed_plus 4
:event/elapsed 90
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_389616"
:event/minute 94
:event/match_id "match_1955"}


]

