
;;# data
[
{:match/id "match_3185"
:match/league "England Premier League"
:match/hometeam "Swansea City"
:match/awayteam "Liverpool"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "shotoff"
:event/elapsed 9
:event/subtype "shot"
:event/player1 "Joe Allen"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2138184"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3185"}

{:event/type "shoton"
:event/elapsed 12
:event/subtype "indirect freekick"
:event/player1 "Gylfi Sigurdsson"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_2138273"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_3185"}

{:event/type "shoton"
:event/elapsed 12
:event/subtype "blocked_shot"
:event/player1 "Scott Sinclair"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_2138300"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_3185"}

{:event/type "corner"
:event/elapsed 12
:event/subtype "short"
:event/sortorder 11
:event/team "home"
:event/event_type "corner"
:event/id "event_2138274"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_3185"}

{:event/type "cross"
:event/elapsed 13
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2138281"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_3185"}

{:event/type "shotoff"
:event/elapsed 15
:event/subtype "distance"
:event/player1 "Maxi Rodriguez"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2138339"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_3185"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Daniel Graham"
:event/player1 "Jamie Carragher"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2138452"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_3185"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Glen Johnson"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2138497"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_3185"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Joe Allen"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2138516"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_3185"}

{:event/type "corner"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Joe Allen"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2138516"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_3185"}

{:event/type "shoton"
:event/elapsed 23
:event/subtype "blocked_shot"
:event/player1 "Gylfi Sigurdsson"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_2138524"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_3185"}

{:event/type "shoton"
:event/elapsed 25
:event/subtype "blocked_shot"
:event/player1 "Jonjo Shelvey"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_2138557"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3185"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Andy Carroll"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2138592"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_3185"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Gylfi Sigurdsson"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2138618"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_3185"}

{:event/type "corner"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Gylfi Sigurdsson"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2138618"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_3185"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Leon Britton"
:event/subtype "from_behind"
:event/player1 "Jonjo Shelvey"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2138666"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_3185"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Leon Britton"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2138726"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_3185"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Steven Caulker"
:event/subtype "pushing"
:event/player1 "Jonjo Shelvey"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2138729"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_3185"}

{:event/type "shoton"
:event/elapsed 33
:event/subtype "direct_freekick"
:event/player1 "Gylfi Sigurdsson"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_2138753"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3185"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Gylfi Sigurdsson"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2138754"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3185"}

{:event/type "corner"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Gylfi Sigurdsson"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2138754"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3185"}

{:event/type "shotoff"
:event/elapsed 34
:event/subtype "distance"
:event/player1 "Leon Britton"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2138776"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_3185"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Scott Sinclair"
:event/subtype "pushing"
:event/player1 "Martin Kelly"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2138833"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_3185"}

{:event/type "shotoff"
:event/elapsed 37
:event/subtype "shot"
:event/player1 "Andy Carroll"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2138864"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_3185"}

{:event/type "shoton"
:event/elapsed 39
:event/subtype "shot"
:event/player1 "Neil Taylor"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_2138908"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_3185"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Martin Kelly"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2138928"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_3185"}

{:event/type "shoton"
:event/elapsed 40
:event/subtype "header"
:event/player1 "Andy Carroll"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_2138931"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_3185"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Maxi Rodriguez"
:event/player1 "Nathan Dyer"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2138939"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_3185"}

{:event/type "shotoff"
:event/elapsed 42
:event/subtype "shot"
:event/player1 "Andy Carroll"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2138987"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_3185"}

{:event/type "shoton"
:event/elapsed 44
:event/subtype "big chance shot"
:event/player1 "Nathan Dyer"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_2139033"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_3185"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Nathan Dyer"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2139072"
:event/minute 46
:event/match_id "match_3185"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "Andy Carroll"
:event/subtype "from_behind"
:event/player1 "Ashley Williams"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2139077"
:event/minute 46
:event/match_id "match_3185"}

{:event/type "card"
:event/elapsed_plus 3
:event/elapsed 45
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Ashley Williams"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2139083"
:event/minute 48
:event/match_id "match_3185"}

{:event/type "card"
:event/elapsed_plus 3
:event/elapsed 45
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Andy Carroll"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_2139084"
:event/minute 48
:event/match_id "match_3185"}

{:event/type "shoton"
:event/elapsed 49
:event/subtype "blocked_shot"
:event/player1 "Gylfi Sigurdsson"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_2139392"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_3185"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2139420"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3185"}

{:event/type "corner"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2139420"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3185"}

{:event/type "shoton"
:event/elapsed 51
:event/subtype "shot"
:event/player1 "Jordan Henderson"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_2139424"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3185"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Gylfi Sigurdsson"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2139486"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_3185"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Daniel Agger"
:event/player1 "Gylfi Sigurdsson"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2139495"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_3185"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2139520"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_3185"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Maxi Rodriguez"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2139544"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3185"}

{:event/type "corner"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Maxi Rodriguez"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2139544"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3185"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_2139562"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3185"}

{:event/type "corner"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_2139562"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3185"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2139564"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_3185"}

{:event/type "corner"
:event/elapsed 56
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2139564"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_3185"}

{:event/type "shoton"
:event/elapsed 56
:event/subtype "bicycle_kick"
:event/player1 "Andy Carroll"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_2139587"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_3185"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Nathan Dyer"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2139661"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_3185"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player2 "Andy Carroll"
:event/player1 "Neil Taylor"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2139673"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_3185"}

{:event/type "shotoff"
:event/elapsed 60
:event/subtype "shot"
:event/player1 "Scott Sinclair"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2139697"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_3185"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Gylfi Sigurdsson"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2139759"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3185"}

{:event/type "corner"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Gylfi Sigurdsson"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2139759"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3185"}

{:event/type "shotoff"
:event/elapsed 63
:event/subtype "deflected"
:event/player1 "Angel Rangel"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2139772"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3185"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Gylfi Sigurdsson"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2139790"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_3185"}

{:event/type "corner"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Gylfi Sigurdsson"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2139790"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_3185"}

{:event/type "shotoff"
:event/elapsed 64
:event/subtype "header"
:event/player1 "Steven Caulker"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2139793"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_3185"}

{:event/type "shotoff"
:event/elapsed 65
:event/subtype "shot"
:event/player1 "Craig Bellamy"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2139828"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_3185"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Angel Rangel"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2139885"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3185"}

{:event/type "foulcommit"
:event/elapsed 67
:event/subtype "hands"
:event/player1 "Nathan Dyer"
:event/sortorder 12
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2139967"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3185"}

{:event/type "foulcommit"
:event/elapsed 72
:event/player2 "Luis Suarez"
:event/subtype "from_behind"
:event/player1 "Joe Allen"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2140019"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_3185"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Luis Suarez"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2140093"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3185"}

{:event/type "corner"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Luis Suarez"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2140093"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3185"}

{:event/type "shoton"
:event/elapsed 75
:event/subtype "header"
:event/player1 "Daniel Agger"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_2140096"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3185"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Luis Suarez"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_2140103"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3185"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Dirk Kuyt"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2140119"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3185"}

{:event/type "shoton"
:event/elapsed 76
:event/subtype "shot"
:event/player1 "Andy Carroll"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_2140120"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3185"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Gylfi Sigurdsson"
:event/subtype "shirt_pull"
:event/player1 "Dirk Kuyt"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2140142"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_3185"}

{:event/type "shoton"
:event/elapsed 80
:event/subtype "blocked_shot"
:event/player1 "Scott Sinclair"
:event/sortorder 12
:event/team "home"
:event/event_type "shoton"
:event/id "event_2140289"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_3185"}

{:event/type "shoton"
:event/elapsed 85
:event/subtype "blocked_shot"
:event/player1 "Luis Suarez"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_2140371"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_3185"}

{:event/type "goal"
:event/elapsed 86
:event/player2 "Angel Rangel"
:event/subtype "shot"
:event/player1 "Daniel Graham"
:event/sortorder 1
:event/team "home"
:event/id "event_2140411"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3185"}

{:event/type "shoton"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "blocked_shot"
:event/player1 "Luis Suarez"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_2140463"
:event/minute 92
:event/match_id "match_3185"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Craig Bellamy"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_2140464"
:event/minute 92
:event/match_id "match_3185"}

{:event/type "corner"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Craig Bellamy"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_2140464"
:event/minute 92
:event/match_id "match_3185"}

{:event/type "shotoff"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "header"
:event/player1 "Daniel Agger"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2140465"
:event/minute 92
:event/match_id "match_3185"}


]

