
;;# data
[
{:match/id "match_4408"
:match/league "England Premier League"
:match/hometeam "West Ham United"
:match/awayteam "Chelsea"
:match/score "2:2"
:match/hometeam_goals "2"
:match/awayteam_goals "1"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Willian"
:event/subtype "pushing"
:event/player1 "Manuel Lanzini"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4943242"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_4408"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "Gary Cahill"
:event/subtype "trip"
:event/player1 "Diafra Sakho"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4943298"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_4408"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Manuel Lanzini"
:event/subtype "trip"
:event/player1 "Ramires"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4943304"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "James Collins"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4943314"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_4408"}

{:event/type "shotoff"
:event/elapsed 5
:event/subtype "shot"
:event/player1 "Dimitri Payet"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4943337"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_4408"}

{:event/type "shotoff"
:event/elapsed 9
:event/subtype "bad shot"
:event/player1 "Diego Costa"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4943479"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Aaron Cresswell"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4943528"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_4408"}

{:event/type "corner"
:event/elapsed 11
:event/subtype "cross_left"
:event/player1 "Dimitri Payet"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4943537"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed 13
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4943575"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_4408"}

{:event/type "shoton"
:event/elapsed 14
:event/subtype "blocked_shot"
:event/player1 "Diego Costa"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_4943624"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_4408"}

{:event/type "corner"
:event/elapsed 14
:event/subtype "cross_right"
:event/player1 "Willian"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_4943631"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_4408"}

{:event/type "shotoff"
:event/elapsed 14
:event/subtype "header"
:event/player1 "Diego Costa"
:event/sortorder 5
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4943636"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_4408"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "Dimitri Payet"
:event/subtype "trip"
:event/player1 "Cesc Fabregas"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4943681"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_4408"}

{:event/type "shoton"
:event/elapsed 17
:event/subtype "direct_freekick"
:event/player1 "Dimitri Payet"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4943707"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_4408"}

{:event/type "corner"
:event/elapsed 17
:event/subtype "cross_left"
:event/player1 "Dimitri Payet"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4943722"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_4408"}

{:event/type "goal"
:event/elapsed 17
:event/subtype "volley"
:event/player1 "Mauro Zarate"
:event/sortorder 3
:event/team "home"
:event/id "event_4943726"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_4408"}

{:event/type "shoton"
:event/elapsed 21
:event/subtype "blocked_shot"
:event/player1 "Carl Jenkinson"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4943809"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_4408"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Mauro Zarate"
:event/subtype "trip"
:event/player1 "Cesar Azpilicueta"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4943839"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_4408"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Mauro Zarate"
:event/subtype "trip"
:event/player1 "Cesar Azpilicueta"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4943877"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_4408"}

{:event/type "card"
:event/elapsed 24
:event/card_type "y"
:event/player1 "Cesar Azpilicueta"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_4943879"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_4408"}

{:event/type "shotoff"
:event/elapsed 25
:event/subtype "shot"
:event/player1 "Ramires"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4943897"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_4408"}

{:event/type "foulcommit"
:event/elapsed 30
:event/player2 "Ramires"
:event/subtype "pushing"
:event/player1 "Diafra Sakho"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4943998"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_4408"}

{:event/type "corner"
:event/elapsed 31
:event/subtype "cross_left"
:event/player1 "Cesc Fabregas"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4944003"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_4408"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Ramires"
:event/subtype "trip"
:event/player1 "Aaron Cresswell"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4944026"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_4408"}

{:event/type "shoton"
:event/elapsed 33
:event/subtype "direct_freekick"
:event/player1 "Willian"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4944045"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Eden Hazard"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4944048"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Cesc Fabregas"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4944081"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_4408"}

{:event/type "corner"
:event/elapsed 35
:event/subtype "cross_right"
:event/player1 "Cesc Fabregas"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4944086"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_4408"}

{:event/type "shoton"
:event/elapsed 35
:event/subtype "big chance header"
:event/player1 "Kurt Zouma"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_4944095"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_4408"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Cheikhou Kouyate"
:event/subtype "pull"
:event/player1 "Nemanja Matic"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4944102"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_4408"}

{:event/type "card"
:event/elapsed 35
:event/card_type "y"
:event/player1 "Nemanja Matic"
:event/sortorder 5
:event/team "away"
:event/event_type "card"
:event/id "event_4944103"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Dimitri Payet"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4944114"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_4408"}

{:event/type "shoton"
:event/elapsed 36
:event/subtype "header"
:event/player1 "James Collins"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4944118"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Kurt Zouma"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4944142"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_4408"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Aaron Cresswell"
:event/subtype "trip"
:event/player1 "Ramires"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4944157"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_4408"}

{:event/type "shotoff"
:event/elapsed 39
:event/subtype "big chance shot"
:event/player1 "Manuel Lanzini"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4944218"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Carl Jenkinson"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4944272"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_4408"}

{:event/type "corner"
:event/elapsed 42
:event/subtype "cross_left"
:event/player1 "Dimitri Payet"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4944308"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_4408"}

{:event/type "goal"
:event/elapsed 42
:event/subtype "shot"
:event/player1 "Cesc Fabregas"
:event/sortorder 5
:event/team "away"
:event/id "event_4944324"
:event/event_type "goal"
:event/goal_type "dg"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_4408"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Diafra Sakho"
:event/subtype "trip"
:event/player1 "Nemanja Matic"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4944375"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_4408"}

{:event/type "card"
:event/elapsed 45
:event/card_type "y"
:event/player1 "Nemanja Matic"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_4944396"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_4408"}

{:event/type "card"
:event/elapsed_plus 1
:event/elapsed 45
:event/card_type "y"
:event/subtype "verbal_abuse"
:event/player1 "Diego Costa"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4944468"
:event/minute 46
:event/match_id "match_4408"}

{:event/type "card"
:event/elapsed_plus 1
:event/elapsed 45
:event/card_type "y"
:event/subtype "verbal_abuse"
:event/player1 "Cesc Fabregas"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_4944429"
:event/minute 46
:event/match_id "match_4408"}

{:event/type "foulcommit"
:event/elapsed 46
:event/player2 "Mauro Zarate"
:event/subtype "trip"
:event/player1 "Cesar Azpilicueta"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4944789"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Dimitri Payet"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_4944446"
:event/minute 46
:event/match_id "match_4408"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Diafra Sakho"
:event/subtype "trip"
:event/player1 "Ramires"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4944908"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_4408"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "James Tomkins"
:event/subtype "dangerous_play"
:event/player1 "Diego Costa"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4945024"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Aaron Cresswell"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4945031"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_4408"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Cesar Azpilicueta"
:event/subtype "pushing"
:event/player1 "Mauro Zarate"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4945057"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Diego Costa"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4945133"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_4408"}

{:event/type "corner"
:event/elapsed 56
:event/subtype "cross_left"
:event/player1 "Willian"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_4945142"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_4408"}

{:event/type "goal"
:event/elapsed 56
:event/player2 "Willian"
:event/subtype "volley"
:event/player1 "Gary Cahill"
:event/sortorder 4
:event/team "away"
:event/id "event_4945146"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_4408"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Eden Hazard"
:event/subtype "trip"
:event/player1 "Mark Noble"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4945208"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_4408"}

{:event/type "shoton"
:event/elapsed 58
:event/subtype "direct_freekick"
:event/player1 "Willian"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4945216"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Carl Jenkinson"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4945232"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/sortorder 1
:event/team "home"
:event/event_type "throwin"
:event/id "event_4945246"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Dimitri Payet"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4945265"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_4408"}

{:event/type "shoton"
:event/elapsed 60
:event/subtype "volley"
:event/player1 "Mauro Zarate"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4945280"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Aaron Cresswell"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4945308"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_4408"}

{:event/type "corner"
:event/elapsed 61
:event/subtype "cross_left"
:event/player1 "Dimitri Payet"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4945327"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Aaron Cresswell"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4945390"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_4408"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Eden Hazard"
:event/subtype "trip"
:event/player1 "Carl Jenkinson"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4945420"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4945437"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_4408"}

{:event/type "shotoff"
:event/elapsed 65
:event/subtype "header"
:event/player1 "Diego Costa"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4945443"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Diafra Sakho"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4945491"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_4408"}

{:event/type "shoton"
:event/elapsed 68
:event/subtype "blocked_shot"
:event/player1 "Dimitri Payet"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4945500"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Mark Noble"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4945538"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Dimitri Payet"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4945541"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Dimitri Payet"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4945559"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Aaron Cresswell"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4945606"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_4408"}

{:event/type "foulcommit"
:event/elapsed 74
:event/player2 "Ramires"
:event/subtype "from_behind"
:event/player1 "Cheikhou Kouyate"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4945643"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_4408"}

{:event/type "card"
:event/elapsed 74
:event/card_type "y"
:event/player1 "Cheikhou Kouyate"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4945644"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Dimitri Payet"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4945661"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Manuel Lanzini"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4945694"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Aaron Cresswell"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4945708"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_4408"}

{:event/type "corner"
:event/elapsed 78
:event/subtype "cross_right"
:event/player1 "Dimitri Payet"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4945728"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_4408"}

{:event/type "shoton"
:event/elapsed 78
:event/subtype "deflected"
:event/player1 "Ramires"
:event/sortorder 4
:event/team "away"
:event/event_type "shoton"
:event/id "event_4945742"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_4408"}

{:event/type "shoton"
:event/elapsed 78
:event/subtype "blocked_shot"
:event/player1 "Manuel Lanzini"
:event/sortorder 5
:event/team "home"
:event/event_type "shoton"
:event/id "event_4945744"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Aaron Cresswell"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4945755"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_4408"}

{:event/type "goal"
:event/elapsed 79
:event/player2 "Aaron Cresswell"
:event/subtype "header"
:event/player1 "Andy Carroll"
:event/sortorder 1
:event/team "home"
:event/id "event_4945756"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_4408"}

{:event/type "shotoff"
:event/elapsed 80
:event/subtype "distance"
:event/player1 "Willian"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4945777"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_4408"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Andy Carroll"
:event/subtype "trip"
:event/player1 "Willian"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4945792"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_4408"}

{:event/type "card"
:event/elapsed 82
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Willian"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_4945802"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_4408"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Eden Hazard"
:event/subtype "trip"
:event/player1 "Andy Carroll"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4945865"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4945874"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_4945888"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_4408"}

{:event/type "corner"
:event/elapsed 87
:event/subtype "short_left"
:event/player1 "Dimitri Payet"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4945907"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Dimitri Payet"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4945910"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_4408"}

{:event/type "corner"
:event/elapsed 87
:event/subtype "short_left"
:event/player1 "Dimitri Payet"
:event/sortorder 5
:event/team "home"
:event/event_type "corner"
:event/id "event_4945917"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_4408"}

{:event/type "shotoff"
:event/elapsed 88
:event/subtype "shot"
:event/player1 "Pedro Mba Obiang"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4945927"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4945947"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_4408"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Willian"
:event/subtype "trip"
:event/player1 "Diafra Sakho"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4945992"
:event/minute 91
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 7
:event/team "away"
:event/event_type "cross"
:event/id "event_4946013"
:event/minute 92
:event/match_id "match_4408"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "John Obi Mikel"
:event/sortorder 9
:event/team "away"
:event/event_type "cross"
:event/id "event_4946017"
:event/minute 92
:event/match_id "match_4408"}

{:event/type "foulcommit"
:event/elapsed_plus 5
:event/elapsed 90
:event/player2 "Dimitri Payet"
:event/subtype "serious_foul"
:event/player1 "John Obi Mikel"
:event/sortorder 12
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4946058"
:event/minute 95
:event/match_id "match_4408"}

{:event/type "card"
:event/elapsed_plus 5
:event/elapsed 90
:event/card_type "y"
:event/player1 "John Obi Mikel"
:event/sortorder 13
:event/team "away"
:event/event_type "card"
:event/id "event_4946060"
:event/minute 95
:event/match_id "match_4408"}


]

