
;;# data
[
{:match/id "match_2704"
:match/league "England Premier League"
:match/hometeam "Wolverhampton Wanderers"
:match/awayteam "Tottenham Hotspur"
:match/score "4:3"
:match/hometeam_goals "3"
:match/awayteam_goals "3"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Alan Hutton"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1445477"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Luka Modric"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1445480"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_2704"}

{:event/type "shotoff"
:event/elapsed 2
:event/subtype "shot"
:event/player1 "Roman Pavlyuchenko"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1445482"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Adam Hammill"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1445523"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_2704"}

{:event/type "corner"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Adam Hammill"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1445523"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_2704"}

{:event/type "shotoff"
:event/elapsed 5
:event/player1 "Nenad Milijas"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1445526"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_2704"}

{:event/type "shoton"
:event/elapsed 6
:event/subtype "blocked_shot"
:event/player1 "Sandro"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1445537"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Steven Pienaar"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1445549"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Matt Jarvis"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1445588"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Adam Hammill"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1445641"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_2704"}

{:event/type "shotoff"
:event/elapsed 17
:event/subtype "header"
:event/player1 "Nenad Milijas"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1445642"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_2704"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Kevin Doyle"
:event/player1 "Michael Dawson"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1445648"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Nenad Milijas"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1445661"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_2704"}

{:event/type "corner"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Nenad Milijas"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1445661"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_2704"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Karl Henry"
:event/player1 "Jermain Defoe"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1445667"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Matt Jarvis"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1445675"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_2704"}

{:event/type "corner"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Matt Jarvis"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1445675"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Kevin Foley"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_1445683"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_2704"}

{:event/type "shotoff"
:event/elapsed 20
:event/subtype "deflected"
:event/player1 "Matt Jarvis"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1445684"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Nenad Milijas"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1445688"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_2704"}

{:event/type "corner"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Nenad Milijas"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1445688"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Nenad Milijas"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1445690"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_2704"}

{:event/type "goal"
:event/elapsed 20
:event/player2 "Nenad Milijas"
:event/subtype "header"
:event/player1 "Kevin Doyle"
:event/sortorder 4
:event/team "home"
:event/id "event_1445691"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_2704"}

{:event/type "shotoff"
:event/elapsed 22
:event/subtype "shot"
:event/player1 "Steven Pienaar"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1445702"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_2704"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Luka Modric"
:event/player1 "Karl Henry"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1445728"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_2704"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Roman Pavlyuchenko"
:event/player1 "Christophe Berra"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1445732"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_2704"}

{:event/type "shoton"
:event/elapsed 25
:event/subtype "blocked_shot"
:event/player1 "Steven Pienaar"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_1445740"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_2704"}

{:event/type "shotoff"
:event/elapsed 25
:event/subtype "shot"
:event/player1 "Luka Modric"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1445741"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_2704"}

{:event/type "foulcommit"
:event/elapsed 27
:event/subtype "hands"
:event/player1 "Kevin Foley"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1445746"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Steven Pienaar"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1445747"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Luka Modric"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1445750"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_2704"}

{:event/type "corner"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Luka Modric"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1445750"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Alan Hutton"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1445760"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_2704"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Steven Pienaar"
:event/player1 "Stephen Ward"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1445771"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2704"}

{:event/type "shoton"
:event/elapsed 29
:event/subtype "shot"
:event/player1 "Roman Pavlyuchenko"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1445777"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2704"}

{:event/type "goal"
:event/elapsed 30
:event/player2 "Roman Pavlyuchenko"
:event/subtype "distance"
:event/player1 "Jermain Defoe"
:event/sortorder 1
:event/team "away"
:event/id "event_1445786"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Adam Hammill"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1445804"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Alan Hutton"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1445818"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_2704"}

{:event/type "goal"
:event/elapsed 35
:event/subtype "distance"
:event/player1 "Jermain Defoe"
:event/sortorder 0
:event/team "away"
:event/id "event_1445839"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Roman Pavlyuchenko"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1445857"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_2704"}

{:event/type "shoton"
:event/elapsed 37
:event/subtype "blocked_shot"
:event/player1 "Jermain Defoe"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1445859"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Matt Jarvis"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1445876"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_2704"}

{:event/type "shoton"
:event/elapsed 39
:event/subtype "deflected"
:event/player1 "Kevin Doyle"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1445884"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_2704"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Nenad Milijas"
:event/subtype "penalty"
:event/player1 "Alan Hutton"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1445887"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_2704"}

{:event/type "card"
:event/elapsed 40
:event/card_type "y"
:event/player1 "Alan Hutton"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1445890"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_2704"}

{:event/type "goal"
:event/elapsed 40
:event/player1 "Kevin Doyle"
:event/sortorder 1
:event/team "home"
:event/id "event_1445894"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_2704"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Luka Modric"
:event/player1 "Karl Henry"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1445915"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Roman Pavlyuchenko"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1445935"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_2704"}

{:event/type "shotoff"
:event/elapsed 44
:event/subtype "deflected"
:event/player1 "Jermain Defoe"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1445936"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Luka Modric"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1445940"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_2704"}

{:event/type "corner"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Luka Modric"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1445940"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_2704"}

{:event/type "shoton"
:event/elapsed 45
:event/subtype "header"
:event/player1 "Michael Dawson"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1445942"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Adam Hammill"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1445957"
:event/minute 46
:event/match_id "match_2704"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "bad shot"
:event/player1 "Nenad Milijas"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1445962"
:event/minute 46
:event/match_id "match_2704"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 45
:event/player2 "Jermaine Jenas"
:event/player1 "Karl Henry"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1445975"
:event/minute 47
:event/match_id "match_2704"}

{:event/type "foulcommit"
:event/elapsed 47
:event/player2 "Benoit Assou-Ekotto"
:event/player1 "Kevin Doyle"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1446094"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_2704"}

{:event/type "goal"
:event/elapsed 48
:event/player2 "Jermaine Jenas"
:event/subtype "shot"
:event/player1 "Roman Pavlyuchenko"
:event/sortorder 0
:event/team "away"
:event/id "event_1446114"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Matt Jarvis"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1446127"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_2704"}

{:event/type "shotoff"
:event/elapsed 50
:event/subtype "header"
:event/player1 "Stephen Ward"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1446129"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Roman Pavlyuchenko"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1446138"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_2704"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Kevin Doyle"
:event/player1 "William Gallas"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1446153"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_2704"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Adam Hammill"
:event/subtype "obstruction"
:event/player1 "Michael Dawson"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1446155"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_2704"}

{:event/type "card"
:event/elapsed 54
:event/card_type "y"
:event/player1 "Michael Dawson"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_1446156"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Adam Hammill"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1446167"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Karl Henry"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1446170"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Matt Jarvis"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1446177"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Steven Pienaar"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1446185"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_2704"}

{:event/type "shotoff"
:event/elapsed 58
:event/subtype "bad shot"
:event/player1 "Matt Jarvis"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1446192"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_2704"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Christophe Berra"
:event/player1 "Roman Pavlyuchenko"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1446195"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_2704"}

{:event/type "shotoff"
:event/elapsed 60
:event/subtype "distance"
:event/player1 "Roman Pavlyuchenko"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1446210"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_2704"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player1 "William Gallas"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1446213"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_2704"}

{:event/type "shotoff"
:event/elapsed 61
:event/subtype "direct_freekick"
:event/player1 "Nenad Milijas"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1446222"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Matt Jarvis"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1446243"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Adam Hammill"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1446259"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Nenad Milijas"
:event/sortorder 5
:event/team "home"
:event/event_type "corner"
:event/id "event_1446271"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_2704"}

{:event/type "corner"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Nenad Milijas"
:event/sortorder 5
:event/team "home"
:event/event_type "corner"
:event/id "event_1446271"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_2704"}

{:event/type "shoton"
:event/elapsed 65
:event/subtype "blocked_shot"
:event/player1 "Adam Hammill"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1446275"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_2704"}

{:event/type "shoton"
:event/elapsed 65
:event/subtype "distance"
:event/player1 "Nenad Milijas"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_1446283"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_2704"}

{:event/type "corner"
:event/elapsed 66
:event/subtype "short"
:event/player1 "Matt Jarvis"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1446284"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_2704"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Nenad Milijas"
:event/player1 "Sandro"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1446300"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_2704"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Gareth Bale"
:event/player1 "George Elokobi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1446329"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Gareth Bale"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1446338"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Richard Stearman"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_1446345"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Matt Jarvis"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1446359"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_2704"}

{:event/type "shotoff"
:event/elapsed 73
:event/subtype "shot"
:event/player1 "Sylvan Ebanks-Blake"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1446362"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_1446383"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Jermaine Jenas"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1446384"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Kevin Doyle"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1446390"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_2704"}

{:event/type "shotoff"
:event/elapsed 76
:event/subtype "shot"
:event/player1 "Nenad Milijas"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1446393"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_2704"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Sylvan Ebanks-Blake"
:event/subtype "shirt_pull"
:event/player1 "William Gallas"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1446399"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_2704"}

{:event/type "card"
:event/elapsed 77
:event/card_type "y"
:event/subtype "emergency_brake"
:event/player1 "William Gallas"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1446403"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "George Elokobi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1446412"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Matt Jarvis"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1446414"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_2704"}

{:event/type "corner"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Matt Jarvis"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1446414"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Matt Jarvis"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1446416"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_2704"}

{:event/type "shoton"
:event/elapsed 79
:event/subtype "shot"
:event/player1 "Gareth Bale"
:event/sortorder 7
:event/team "away"
:event/event_type "shoton"
:event/id "event_1446442"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_2704"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Kevin Doyle"
:event/player1 "Benoit Assou-Ekotto"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1446447"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_2704"}

{:event/type "goal"
:event/elapsed 80
:event/player1 "Richard Stearman"
:event/sortorder 3
:event/team "home"
:event/id "event_1446457"
:event/event_type "goal"
:event/goal_type "dg"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_2704"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Heurelho Gomes"
:event/player1 "Richard Stearman"
:event/sortorder 6
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1446466"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_2704"}

{:event/type "shoton"
:event/elapsed 83
:event/subtype "blocked_shot"
:event/player1 "Kevin Doyle"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1446484"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_2704"}

{:event/type "shoton"
:event/elapsed 83
:event/subtype "header"
:event/player1 "Karl Henry"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1446485"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_2704"}

{:event/type "shotoff"
:event/elapsed 84
:event/subtype "post"
:event/player1 "Jermain Defoe"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1446499"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_2704"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player1 "Sylvan Ebanks-Blake"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1446502"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_2704"}

{:event/type "shoton"
:event/elapsed 86
:event/subtype "blocked_shot"
:event/player1 "Niko Kranjcar"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1446526"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_2704"}

{:event/type "shotoff"
:event/elapsed 86
:event/subtype "deflected"
:event/player1 "Aaron Lennon"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1446527"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_2704"}

{:event/type "corner"
:event/elapsed 86
:event/subtype "short"
:event/player1 "Gareth Bale"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1446528"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Gareth Bale"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_1446529"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_2704"}

{:event/type "shoton"
:event/elapsed 86
:event/subtype "blocked_shot"
:event/player1 "Jermain Defoe"
:event/sortorder 6
:event/team "away"
:event/event_type "shoton"
:event/id "event_1446536"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Matt Jarvis"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1446541"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_2704"}

{:event/type "goal"
:event/elapsed 87
:event/player2 "Matt Jarvis"
:event/subtype "header"
:event/player1 "Steven Fletcher"
:event/sortorder 2
:event/team "home"
:event/id "event_1446542"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_2704"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player1 "Steven Fletcher"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1446547"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_2704"}

{:event/type "shoton"
:event/elapsed 90
:event/subtype "blocked_shot"
:event/player1 "Jermaine Jenas"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1446548"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/sortorder 1
:event/team "away"
:event/event_type "throwin"
:event/id "event_1446550"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_2704"}

{:event/type "shoton"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "distance"
:event/player1 "Gareth Bale"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1446572"
:event/minute 92
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Gareth Bale"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1446579"
:event/minute 94
:event/match_id "match_2704"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Niko Kranjcar"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1446582"
:event/minute 94
:event/match_id "match_2704"}

{:event/type "corner"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Niko Kranjcar"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1446582"
:event/minute 94
:event/match_id "match_2704"}


]

