
;;# data
[
{:match/id "match_9886"
:match/league "Germany 1. Bundesliga"
:match/hometeam "SC Freiburg"
:match/awayteam "FC Bayern Munich"
:match/score "2:1"
:match/hometeam_goals "2"
:match/awayteam_goals "1"}

{:event/type "shotoff"
:event/elapsed 1
:event/subtype "shot"
:event/player1 "Mario Goetze"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4479530"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_9886"}

{:event/type "shoton"
:event/elapsed 3
:event/subtype "shot"
:event/player1 "Mario Goetze"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4479578"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "Mehdi Benatia"
:event/subtype "pull"
:event/player1 "Karim Guede"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4479584"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_9886"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Mitchell Weiser"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4479619"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_9886"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Bastian Schweinsteiger"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4479638"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_9886"}

{:event/type "shotoff"
:event/elapsed 6
:event/subtype "shot"
:event/player1 "Rafinha"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4479643"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Jonathan Schmid"
:event/subtype "trip"
:event/player1 "Juan Bernat"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4479660"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_9886"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Jonathan Schmid"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4479663"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_9886"}

{:event/type "shoton"
:event/elapsed 9
:event/subtype "shot"
:event/player1 "Jonathan Schmid"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_4479694"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_9886"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Mitchell Weiser"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4479707"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_9886"}

{:event/type "corner"
:event/elapsed 10
:event/subtype "cross_left"
:event/player1 "Xabi Alonso"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_4479718"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Pavel Krmas"
:event/subtype "pushing"
:event/player1 "Mehdi Benatia"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4479729"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Mehdi Benatia"
:event/subtype "pull"
:event/player1 "Admir Mehmedi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4479785"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_9886"}

{:event/type "goal"
:event/elapsed 13
:event/player2 "Mitchell Weiser"
:event/subtype "tap_in"
:event/player1 "Bastian Schweinsteiger"
:event/sortorder 4
:event/team "away"
:event/id "event_4479790"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Mensur Mujdza"
:event/subtype "pushing"
:event/player1 "Mario Goetze"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4479845"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_9886"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Mitchell Weiser"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4479830"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_9886"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Rafinha"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4479857"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_9886"}

{:event/type "corner"
:event/elapsed 16
:event/subtype "cross_left"
:event/player1 "Xabi Alonso"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_4479864"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_9886"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Xabi Alonso"
:event/sortorder 5
:event/team "away"
:event/event_type "cross"
:event/id "event_4479877"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_9886"}

{:event/type "corner"
:event/elapsed 17
:event/subtype "cross_right"
:event/player1 "Xabi Alonso"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4479883"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Pavel Krmas"
:event/subtype "pushing"
:event/player1 "Bastian Schweinsteiger"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4479954"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_9886"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Jonathan Schmid"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4480012"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_9886"}

{:event/type "corner"
:event/elapsed 23
:event/subtype "short_right"
:event/player1 "Jonathan Schmid"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_4480021"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_9886"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Vladimir Darida"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_4480028"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_9886"}

{:event/type "shotoff"
:event/elapsed 23
:event/subtype "shot"
:event/player1 "Felix Klaus"
:event/sortorder 5
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4480034"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_9886"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Nicolas Hoefler"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4480055"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_9886"}

{:event/type "shoton"
:event/elapsed 25
:event/subtype "blocked_shot"
:event/player1 "Felix Klaus"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4480059"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Stefan Mitrovic"
:event/subtype "pushing"
:event/player1 "Mario Goetze"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4480077"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Rafinha"
:event/subtype "trip"
:event/player1 "Felix Klaus"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4480120"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_9886"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Xabi Alonso"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4480126"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_9886"}

{:event/type "shoton"
:event/elapsed 27
:event/subtype "shot"
:event/player1 "Robert Lewandowski"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_4480140"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_9886"}

{:event/type "corner"
:event/elapsed 28
:event/subtype "cross_left"
:event/player1 "Xabi Alonso"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4480146"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_9886"}

{:event/type "shoton"
:event/elapsed 28
:event/subtype "header"
:event/player1 "Jerome Boateng"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4480148"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_9886"}

{:event/type "shotoff"
:event/elapsed 29
:event/subtype "distance"
:event/player1 "Christian Guenter"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4480172"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Bastian Schweinsteiger"
:event/subtype "from_behind"
:event/player1 "Nicolas Hoefler"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4480212"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_9886"}

{:event/type "goal"
:event/elapsed 33
:event/player2 "Felix Klaus"
:event/subtype "shot"
:event/player1 "Admir Mehmedi"
:event/sortorder 3
:event/team "home"
:event/id "event_4480264"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed 34
:event/player2 "Xabi Alonso"
:event/subtype "pull"
:event/player1 "Vladimir Darida"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4480320"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Mensur Mujdza"
:event/subtype "pushing"
:event/player1 "Mario Goetze"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4480431"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Juan Bernat"
:event/subtype "pull"
:event/player1 "Admir Mehmedi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4480473"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Admir Mehmedi"
:event/subtype "trip"
:event/player1 "Bastian Schweinsteiger"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4480594"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_9886"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Christian Guenter"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4480616"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Felix Klaus"
:event/subtype "pushing"
:event/player1 "Mario Goetze"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4480661"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Robert Lewandowski"
:event/subtype "pull"
:event/player1 "Pavel Krmas"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4480688"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed 46
:event/player2 "Jonathan Schmid"
:event/subtype "pushing"
:event/player1 "Mehdi Benatia"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4480983"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_9886"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Jonathan Schmid"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4481003"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Mario Goetze"
:event/subtype "from_behind"
:event/player1 "Mensur Mujdza"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4481035"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_9886"}

{:event/type "shotoff"
:event/elapsed 48
:event/subtype "direct_freekick"
:event/player1 "Xabi Alonso"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4481050"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Mitchell Weiser"
:event/subtype "pushing"
:event/player1 "Karim Guede"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4481115"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_9886"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Xabi Alonso"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4481123"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_9886"}

{:event/type "shoton"
:event/elapsed 51
:event/subtype "header"
:event/player1 "Mario Goetze"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4481133"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Christian Guenter"
:event/subtype "pull"
:event/player1 "Xabi Alonso"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4481213"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_9886"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Mitchell Weiser"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4481266"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Mensur Mujdza"
:event/subtype "pull"
:event/player1 "Mehdi Benatia"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4481279"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Juan Bernat"
:event/subtype "pushing"
:event/player1 "Admir Mehmedi"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4481293"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_9886"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Jonathan Schmid"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4481371"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_9886"}

{:event/type "corner"
:event/elapsed 59
:event/subtype "cross_right"
:event/player1 "Xabi Alonso"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_4481442"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player2 "Bastian Schweinsteiger"
:event/subtype "trip"
:event/player1 "Stefan Mitrovic"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4481468"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_9886"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Xabi Alonso"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4481487"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_9886"}

{:event/type "corner"
:event/elapsed 61
:event/subtype "cross_right"
:event/player1 "Xabi Alonso"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4481497"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Xabi Alonso"
:event/subtype "pushing"
:event/player1 "Vladimir Darida"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4481514"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_9886"}

{:event/type "corner"
:event/elapsed 63
:event/subtype "cross_right"
:event/player1 "Mario Goetze"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_4481548"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_9886"}

{:event/type "shotoff"
:event/elapsed 63
:event/subtype "header"
:event/player1 "Robert Lewandowski"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4481554"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Manuel Neuer"
:event/subtype "pull"
:event/player1 "Karim Guede"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4481600"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_9886"}

{:event/type "card"
:event/elapsed 65
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Karim Guede"
:event/sortorder 4
:event/team "home"
:event/event_type "card"
:event/id "event_4481614"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_9886"}

{:event/type "corner"
:event/elapsed 66
:event/subtype "cross_left"
:event/player1 "Jonathan Schmid"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_4481635"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_9886"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Mitchell Weiser"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4481666"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_9886"}

{:event/type "corner"
:event/elapsed 68
:event/subtype "cross_left"
:event/player1 "Mario Goetze"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_4481673"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Bastian Schweinsteiger"
:event/subtype "trip"
:event/player1 "Felix Klaus"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4481684"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_9886"}

{:event/type "shotoff"
:event/elapsed 70
:event/subtype "crossbar"
:event/player1 "Bastian Schweinsteiger"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4481696"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_9886"}

{:event/type "shotoff"
:event/elapsed 70
:event/subtype "shot"
:event/player1 "Bastian Schweinsteiger"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4481704"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed 72
:event/player2 "Nicolas Hoefler"
:event/subtype "pushing"
:event/player1 "Mitchell Weiser"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4481732"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_9886"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Mitchell Weiser"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4481769"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_9886"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Nicolas Hoefler"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4481799"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_9886"}

{:event/type "shotoff"
:event/elapsed 75
:event/subtype "shot"
:event/player1 "Christian Guenter"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4481805"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_9886"}

{:event/type "shotoff"
:event/elapsed 75
:event/subtype "distance"
:event/player1 "Admir Mehmedi"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4481823"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed 76
:event/player2 "Philipp Lahm"
:event/subtype "trip"
:event/player1 "Jonathan Schmid"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4481847"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_9886"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Robert Lewandowski"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4481891"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_9886"}

{:event/type "shotoff"
:event/elapsed 78
:event/subtype "shot"
:event/player1 "Mario Goetze"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4481894"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed 79
:event/player2 "Vladimir Darida"
:event/subtype "pull"
:event/player1 "Thiago Alcantara"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4481947"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Vladimir Darida"
:event/subtype "pushing"
:event/player1 "Rafinha"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4481976"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_9886"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Christian Guenter"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4482001"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_9886"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Robert Lewandowski"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4482021"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Admir Mehmedi"
:event/subtype "trip"
:event/player1 "Thiago Alcantara"
:event/sortorder 5
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4482036"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_9886"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Mario Goetze"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4482061"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_9886"}

{:event/type "corner"
:event/elapsed 82
:event/subtype "cross_left"
:event/player1 "Thiago Alcantara"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4482076"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_9886"}

{:event/type "shoton"
:event/elapsed 83
:event/subtype "distance"
:event/player1 "Juan Bernat"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4482096"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_9886"}

{:event/type "shotoff"
:event/elapsed 84
:event/subtype "shot"
:event/player1 "Mitchell Weiser"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4482139"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_9886"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Mitchell Weiser"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4482184"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_9886"}

{:event/type "shoton"
:event/elapsed 86
:event/subtype "shot"
:event/player1 "Thiago Alcantara"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4482193"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_9886"}

{:event/type "corner"
:event/elapsed 86
:event/subtype "cross_left"
:event/player1 "Mario Goetze"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4482201"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_9886"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Karim Guede"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4482316"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_9886"}

{:event/type "goal"
:event/elapsed 89
:event/player2 "Karim Guede"
:event/subtype "shot"
:event/player1 "Nils Petersen"
:event/sortorder 2
:event/team "home"
:event/id "event_4482309"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_9886"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Thomas Mueller"
:event/subtype "pushing"
:event/player1 "Vladimir Darida"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4482362"
:event/minute 91
:event/match_id "match_9886"}


]

