
;;# data
[
{:match/id "match_10327"
:match/league "Italy Serie A"
:match/hometeam "Palermo"
:match/awayteam "Siena"
:match/score "2:0"
:match/hometeam_goals "2"
:match/awayteam_goals "0"}

{:event/type "goal"
:event/elapsed 30
:event/player1 "Mattia Cassani"
:event/sortorder 0
:event/team "home"
:event/id "event_529717"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_10327"}

{:event/type "goal"
:event/elapsed 54
:event/player1 "Fabio Simplicio"
:event/sortorder 0
:event/team "home"
:event/id "event_529942"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_10327"}

{:event/type "card"
:event/elapsed 84
:event/card_type "y"
:event/player1 "Cesare Bovo"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_530138"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_10327"}


]

