
;;# data
[
{:match/id "match_3848"
:match/league "England Premier League"
:match/hometeam "West Ham United"
:match/awayteam "Hull City"
:match/score "1:2"
:match/hometeam_goals "2"
:match/awayteam_goals "1"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Ahmed El Mohamady"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3346210"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Shane Long"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3346216"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3346229"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_3848"}

{:event/type "shoton"
:event/elapsed 7
:event/subtype "shot"
:event/player1 "Stewart Downing"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3346239"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_3848"}

{:event/type "corner"
:event/elapsed 7
:event/subtype "short"
:event/player1 "Andy Carroll"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3346243"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Andy Carroll"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3346245"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Andy Carroll"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3346248"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_3848"}

{:event/type "corner"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Andy Carroll"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3346248"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Roger Johnson"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3346256"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "George McCartney"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3346262"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_3848"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player1 "Andy Carroll"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3346266"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Shane Long"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3346270"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_3848"}

{:event/type "shotoff"
:event/elapsed 13
:event/player1 "Stewart Downing"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3346273"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_3848"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Nikica Jelavic"
:event/player1 "George McCartney"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3346282"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3346287"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_3848"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "Tom Huddlestone"
:event/player1 "Kevin Nolan"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3346302"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Curtis Davies"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3346303"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_3848"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player1 "Jake Livermore"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3346321"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_3848"}

{:event/type "card"
:event/elapsed 19
:event/card_type "y"
:event/player1 "Jake Livermore"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_3346322"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Ahmed El Mohamady"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3346339"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_3848"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Mohamed Diame"
:event/subtype "penalty"
:event/player1 "Allan McGregor"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3346349"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_3848"}

{:event/type "card"
:event/elapsed 23
:event/card_type "r"
:event/player1 "Allan McGregor"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3346364"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_3848"}

{:event/type "goal"
:event/elapsed 26
:event/player1 "Mark Noble"
:event/sortorder 2
:event/team "home"
:event/id "event_3346377"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Ahmed El Mohamady"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3346390"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Andy Carroll"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3346413"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_3848"}

{:event/type "corner"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Andy Carroll"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3346413"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_3848"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Matthew Taylor"
:event/player1 "Shane Long"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3346436"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Mohamed Diame"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3346439"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Mark Noble"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3346463"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_3848"}

{:event/type "shotoff"
:event/elapsed 37
:event/player1 "Tom Huddlestone"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3346473"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_3848"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "James Tomkins"
:event/player1 "Shane Long"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3346492"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_3848"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Matthew Taylor"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3346510"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "George McCartney"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3346519"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_3848"}

{:event/type "shotoff"
:event/elapsed 42
:event/player1 "Andy Carroll"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3346520"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_3848"}

{:event/type "foulcommit"
:event/elapsed 46
:event/player1 "Mohamed Diame"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3346686"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_3848"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "George McCartney"
:event/player1 "David Meyler"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3346538"
:event/minute 46
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Ahmed El Mohamady"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3346687"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Adrian"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_3346543"
:event/minute 46
:event/match_id "match_3848"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Shane Long"
:event/player1 "George McCartney"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3346695"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3346739"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_3848"}

{:event/type "goal"
:event/elapsed 48
:event/subtype "direct_freekick"
:event/player1 "Tom Huddlestone"
:event/sortorder 2
:event/team "away"
:event/id "event_3346698"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_3848"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 45
:event/player2 "Nikica Jelavic"
:event/player1 "Mohamed Diame"
:event/sortorder 7
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3346552"
:event/minute 48
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 8
:event/team "away"
:event/event_type "cross"
:event/id "event_3346554"
:event/minute 48
:event/match_id "match_3848"}

{:event/type "shotoff"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "header"
:event/player1 "James Chester"
:event/sortorder 9
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3346556"
:event/minute 48
:event/match_id "match_3848"}

{:event/type "foulcommit"
:event/elapsed_plus 4
:event/elapsed 45
:event/player2 "David Meyler"
:event/player1 "Guy Demel"
:event/sortorder 11
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3346564"
:event/minute 49
:event/match_id "match_3848"}

{:event/type "shoton"
:event/elapsed_plus 4
:event/elapsed 45
:event/subtype "shot"
:event/player1 "Maynor Figueroa"
:event/sortorder 13
:event/team "away"
:event/event_type "shoton"
:event/id "event_3346569"
:event/minute 49
:event/match_id "match_3848"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player1 "Roger Johnson"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3346707"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3346708"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed_plus 5
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 15
:event/team "away"
:event/event_type "corner"
:event/id "event_3346576"
:event/minute 50
:event/match_id "match_3848"}

{:event/type "corner"
:event/elapsed_plus 5
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 15
:event/team "away"
:event/event_type "corner"
:event/id "event_3346576"
:event/minute 50
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "David Meyler"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3346709"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3848"}

{:event/type "foulcommit"
:event/elapsed_plus 6
:event/elapsed 45
:event/player2 "Maynor Figueroa"
:event/player1 "Andy Carroll"
:event/sortorder 18
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3346586"
:event/minute 51
:event/match_id "match_3848"}

{:event/type "goal"
:event/elapsed 54
:event/player1 "James Chester"
:event/sortorder 0
:event/team "away"
:event/id "event_3346726"
:event/event_type "goal"
:event/goal_type "o"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3346733"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3848"}

{:event/type "corner"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3346733"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3848"}

{:event/type "shotoff"
:event/elapsed 56
:event/player1 "Curtis Davies"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3346737"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_3848"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Maynor Figueroa"
:event/player1 "Roger Johnson"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3346757"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_3848"}

{:event/type "shotoff"
:event/elapsed 61
:event/player1 "Stewart Downing"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3346768"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Mohamed Diame"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3346786"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3346799"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Ahmed El Mohamady"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3346820"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3848"}

{:event/type "shoton"
:event/elapsed 68
:event/subtype "shot"
:event/player1 "Mohamed Diame"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3346827"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_3848"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player1 "George McCartney"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3346844"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Steve Harper"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3346845"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_3848"}

{:event/type "shoton"
:event/elapsed 70
:event/subtype "shot"
:event/player1 "Nikica Jelavic"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3346851"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3346873"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3848"}

{:event/type "corner"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3346873"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3848"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Guy Demel"
:event/player1 "David Meyler"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3346887"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Guy Demel"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3346890"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Andy Carroll"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3346891"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3346908"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_3848"}

{:event/type "corner"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3346908"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3346922"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Kevin Nolan"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3346928"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Liam Rosenior"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3346962"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_3848"}

{:event/type "shoton"
:event/elapsed 83
:event/subtype "shot"
:event/player1 "Kevin Nolan"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3346969"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_3848"}

{:event/type "shotoff"
:event/elapsed 83
:event/subtype "shot"
:event/player1 "Matthew Taylor"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3346976"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_3848"}

{:event/type "shoton"
:event/elapsed 84
:event/subtype "shot"
:event/player1 "Tom Huddlestone"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3346986"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3346987"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_3848"}

{:event/type "corner"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3346987"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Ahmed El Mohamady"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_3346990"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Joe Cole"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_3347000"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_3848"}

{:event/type "corner"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Joe Cole"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_3347000"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "David Meyler"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3347018"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Liam Rosenior"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3347021"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3347034"
:event/minute 91
:event/match_id "match_3848"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 90
:event/player1 "Shane Long"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3347035"
:event/minute 91
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Liam Rosenior"
:event/sortorder 9
:event/team "away"
:event/event_type "cross"
:event/id "event_3347058"
:event/minute 94
:event/match_id "match_3848"}

{:event/type "foulcommit"
:event/elapsed_plus 5
:event/elapsed 90
:event/player1 "David Meyler"
:event/sortorder 10
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3347064"
:event/minute 95
:event/match_id "match_3848"}

{:event/type "cross"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Adrian"
:event/sortorder 11
:event/team "home"
:event/event_type "cross"
:event/id "event_3347065"
:event/minute 95
:event/match_id "match_3848"}


]

