
;;# data
[
{:match/id "match_11699"
:match/league "Italy Serie A"
:match/hometeam "Juventus"
:match/awayteam "Bologna"
:match/score "1:1"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "shotoff"
:event/elapsed 1
:event/subtype "distance"
:event/player1 "Alessandro Del Piero"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1666761"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Panagiotis Kone"
:event/player1 "Claudio Marchisio"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1666773"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Milos Krasic"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1666807"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 6
:event/player2 "Jean-Francois Gillet"
:event/player1 "Simone Pepe"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1666808"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_11699"}

{:event/type "shoton"
:event/elapsed 8
:event/subtype "deflected"
:event/player1 "Mirko Vucinic"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1666839"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Alessandro Diamanti"
:event/subtype "serious_foul"
:event/player1 "Andrea Pirlo"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1666871"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Archimede Morleo"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1666880"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_11699"}

{:event/type "shoton"
:event/elapsed 10
:event/subtype "shot"
:event/player1 "Archimede Morleo"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_1666889"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Gaston Ramirez"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1666891"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_11699"}

{:event/type "corner"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Gaston Ramirez"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1666891"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_11699"}

{:event/type "shoton"
:event/elapsed 11
:event/subtype "blocked_shot"
:event/player1 "Daniele Portanova"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1666895"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Daniele Portanova"
:event/player1 "Paolo De Ceglie"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1666920"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Alessandro Diamanti"
:event/subtype "serious_foul"
:event/player1 "Simone Pepe"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1666922"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_11699"}

{:event/type "card"
:event/elapsed 13
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Simone Pepe"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_1666923"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_11699"}

{:event/type "shotoff"
:event/elapsed 14
:event/subtype "distance"
:event/player1 "Gaston Ramirez"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1666934"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Giorgio Chiellini"
:event/player1 "Gaston Ramirez"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1666948"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Stephan Lichtsteiner"
:event/player1 "Panagiotis Kone"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1666980"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Alessandro Diamanti"
:event/subtype "from_behind"
:event/player1 "Paolo De Ceglie"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1666987"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Federico Casarini"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1667037"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Paolo De Ceglie"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1667043"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Milos Krasic"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1667051"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_11699"}

{:event/type "corner"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Milos Krasic"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1667051"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_11699"}

{:event/type "shoton"
:event/elapsed 23
:event/subtype "blocked_shot"
:event/player1 "Panagiotis Kone"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1667078"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Gaston Ramirez"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1667088"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_11699"}

{:event/type "corner"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Gaston Ramirez"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1667088"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Giorgio Chiellini"
:event/subtype "from_behind"
:event/player1 "Daniele Portanova"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1667095"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Gaby Mudingayi"
:event/player1 "Mirko Vucinic"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1667100"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_11699"}

{:event/type "card"
:event/elapsed 24
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Mirko Vucinic"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_1667101"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Milos Krasic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1667112"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Paolo De Ceglie"
:event/player1 "Alessandro Diamanti"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1667125"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_11699"}

{:event/type "shoton"
:event/elapsed 28
:event/subtype "blocked_shot"
:event/player1 "Gaby Mudingayi"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1667157"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Gaston Ramirez"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1667163"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_11699"}

{:event/type "corner"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Gaston Ramirez"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1667163"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Giorgio Chiellini"
:event/player1 "Daniele Portanova"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1667174"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Mirko Vucinic"
:event/player1 "Panagiotis Kone"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1667181"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_11699"}

{:event/type "goal"
:event/elapsed 29
:event/player2 "Andrea Pirlo"
:event/subtype "shot"
:event/player1 "Mirko Vucinic"
:event/sortorder 3
:event/team "home"
:event/id "event_1667182"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_11699"}

{:event/type "card"
:event/elapsed 29
:event/card_type "y"
:event/subtype "verbal_abuse"
:event/player1 "Panagiotis Kone"
:event/sortorder 9
:event/team "away"
:event/event_type "card"
:event/id "event_1667529"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Andrea Pirlo"
:event/subtype "pushing"
:event/player1 "Gaston Ramirez"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1667202"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Stephan Lichtsteiner"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1667207"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Gaston Ramirez"
:event/player1 "Milos Krasic"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1667231"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_11699"}

{:event/type "shotoff"
:event/elapsed 34
:event/subtype "shot"
:event/player1 "Alessandro Del Piero"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1667268"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Gaby Mudingayi"
:event/player1 "Alessandro Del Piero"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1667289"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Stephan Lichtsteiner"
:event/player1 "Panagiotis Kone"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1667294"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Simone Pepe"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1667305"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_11699"}

{:event/type "shoton"
:event/elapsed 37
:event/subtype "big chance shot"
:event/player1 "Milos Krasic"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1667307"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_11699"}

{:event/type "shotoff"
:event/elapsed 38
:event/subtype "shot"
:event/player1 "Daniele Portanova"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1667324"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Simone Pepe"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1667334"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Diego Perez"
:event/player1 "Claudio Marchisio"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1667398"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_11699"}

{:event/type "shotoff"
:event/elapsed 42
:event/subtype "header"
:event/player1 "Gaston Ramirez"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1667404"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Stephan Lichtsteiner"
:event/subtype "serious_foul"
:event/player1 "Diego Perez"
:event/sortorder 6
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1667410"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_11699"}

{:event/type "card"
:event/elapsed 42
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Diego Perez"
:event/sortorder 7
:event/team "away"
:event/event_type "card"
:event/id "event_1667413"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Andrea Pirlo"
:event/player1 "Gaston Ramirez"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1667441"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Archimede Morleo"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1667456"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_11699"}

{:event/type "shoton"
:event/elapsed 45
:event/subtype "distance"
:event/player1 "Gaby Mudingayi"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_1667461"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "Archimede Morleo"
:event/player1 "Mirko Vucinic"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1667489"
:event/minute 46
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 46
:event/player2 "Giorgio Chiellini"
:event/player1 "Gaston Ramirez"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1667705"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_11699"}

{:event/type "card"
:event/elapsed_plus 2
:event/elapsed 45
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Mirko Vucinic"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1667511"
:event/minute 47
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Stephan Lichtsteiner"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1667728"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Nico Pulzetti"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1667739"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 50
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1667757"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_11699"}

{:event/type "shoton"
:event/elapsed 50
:event/subtype "blocked_shot"
:event/player1 "Claudio Marchisio"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_1667768"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_11699"}

{:event/type "shotoff"
:event/elapsed 51
:event/subtype "big chance post"
:event/player1 "Milos Krasic"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1667778"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Nico Pulzetti"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1667785"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_11699"}

{:event/type "shoton"
:event/elapsed 52
:event/subtype "big chance shot"
:event/player1 "Gaston Ramirez"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1667795"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Gaston Ramirez"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1667796"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_11699"}

{:event/type "corner"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Gaston Ramirez"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1667796"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_11699"}

{:event/type "goal"
:event/elapsed 52
:event/player2 "Gaston Ramirez"
:event/subtype "header"
:event/player1 "Daniele Portanova"
:event/sortorder 3
:event/team "away"
:event/id "event_1667797"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Panagiotis Kone"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1667818"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Mikael Antonsson"
:event/player1 "Andrea Pirlo"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1667829"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Milos Krasic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1667862"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Paolo De Ceglie"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1667865"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Paolo De Ceglie"
:event/player1 "Federico Casarini"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1667874"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_11699"}

{:event/type "card"
:event/elapsed 58
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Federico Casarini"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1667880"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Panagiotis Kone"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1667891"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_11699"}

{:event/type "shoton"
:event/elapsed 60
:event/subtype "distance"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1667897"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player1 "Daniele Portanova"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1667898"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Emanuele Giaccherini"
:event/player1 "Federico Casarini"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1667912"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_11699"}

{:event/type "corner"
:event/elapsed 61
:event/subtype "short"
:event/player1 "Andrea Pirlo"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1667917"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_11699"}

{:event/type "shoton"
:event/elapsed 61
:event/subtype "blocked_shot"
:event/player1 "Andrea Pirlo"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_1667924"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_11699"}

{:event/type "shoton"
:event/elapsed 62
:event/subtype "distance"
:event/player1 "Andrea Pirlo"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1667930"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_11699"}

{:event/type "corner"
:event/elapsed 62
:event/subtype "short"
:event/player1 "Andrea Pirlo"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1667932"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Emanuele Giaccherini"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1667934"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_11699"}

{:event/type "shotoff"
:event/elapsed 63
:event/subtype "deflected"
:event/player1 "Giorgio Chiellini"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1667942"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Claudio Marchisio"
:event/subtype "shirt_pull"
:event/player1 "Nico Pulzetti"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1667978"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_11699"}

{:event/type "card"
:event/elapsed 65
:event/card_type "y"
:event/subtype "shirt_pull"
:event/player1 "Nico Pulzetti"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1667980"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_11699"}

{:event/type "shoton"
:event/elapsed 65
:event/subtype "blocked_shot"
:event/player1 "Andrea Pirlo"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1667987"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_11699"}

{:event/type "corner"
:event/elapsed 66
:event/subtype "short"
:event/player1 "Andrea Pirlo"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1667988"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Emanuele Giaccherini"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1667991"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_11699"}

{:event/type "shoton"
:event/elapsed 66
:event/subtype "blocked_shot"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_1667995"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Andrea Pirlo"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1668016"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_11699"}

{:event/type "corner"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Andrea Pirlo"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1668016"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Andrea Pirlo"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1668023"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_11699"}

{:event/type "corner"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Andrea Pirlo"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1668023"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_11699"}

{:event/type "shoton"
:event/elapsed 68
:event/subtype "header"
:event/player1 "Andrea Barzagli"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1668025"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Andrea Pirlo"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1668028"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_11699"}

{:event/type "corner"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Andrea Pirlo"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1668028"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Alessandro Matri"
:event/player1 "Mikael Antonsson"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1668053"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Emanuele Giaccherini"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1668064"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Panagiotis Kone"
:event/player1 "Stephan Lichtsteiner"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1668068"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_11699"}

{:event/type "card"
:event/elapsed 72
:event/card_type "y"
:event/subtype "emergency_brake"
:event/player1 "Stephan Lichtsteiner"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1668070"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Andrea Pirlo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1668103"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Gaston Ramirez"
:event/player1 "Arturo Vidal"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1668118"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 76
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1668128"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_11699"}

{:event/type "shoton"
:event/elapsed 77
:event/subtype "blocked_shot"
:event/player1 "Emanuele Giaccherini"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1668136"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_11699"}

{:event/type "corner"
:event/elapsed 77
:event/subtype "short"
:event/player1 "Simone Pepe"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1668137"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Simone Pepe"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1668138"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Stephan Lichtsteiner"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1668156"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 78
:event/player2 "Andrea Pirlo"
:event/player1 "Gaby Mudingayi"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1668160"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_11699"}

{:event/type "shotoff"
:event/elapsed 79
:event/subtype "indirect freekick"
:event/player1 "Andrea Pirlo"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1668171"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Simone Pepe"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1668190"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Simone Pepe"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1668192"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Federico Casarini"
:event/player1 "Arturo Vidal"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1668213"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Gaston Ramirez"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1668234"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_11699"}

{:event/type "corner"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Gaston Ramirez"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1668234"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_11699"}

{:event/type "shotoff"
:event/elapsed 84
:event/subtype "bad shot"
:event/player1 "Archimede Morleo"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1668254"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_11699"}

{:event/type "shotoff"
:event/elapsed 85
:event/subtype "distance"
:event/player1 "Panagiotis Kone"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1668277"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Andrea Pirlo"
:event/player1 "Federico Casarini"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1668285"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_11699"}

{:event/type "shotoff"
:event/elapsed 86
:event/subtype "shot"
:event/player1 "Marco Di Vaio"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1668288"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Stephan Lichtsteiner"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1668301"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Andrea Pirlo"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1668305"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_11699"}

{:event/type "corner"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Andrea Pirlo"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1668305"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed 89
:event/subtype "hands"
:event/player1 "Alessandro Matri"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1668344"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Stephan Lichtsteiner"
:event/player1 "Archimede Morleo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1668356"
:event/minute 91
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Gaston Ramirez"
:event/player1 "Giorgio Chiellini"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1668381"
:event/minute 92
:event/match_id "match_11699"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player1 "Marco Di Vaio"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1668391"
:event/minute 92
:event/match_id "match_11699"}

{:event/type "card"
:event/elapsed_plus 5
:event/elapsed 90
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Leonardo Bonucci"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1668418"
:event/minute 95
:event/match_id "match_11699"}

{:event/type "card"
:event/elapsed_plus 5
:event/elapsed 90
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Daniele Portanova"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1668420"
:event/minute 95
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Andrea Pirlo"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1668421"
:event/minute 95
:event/match_id "match_11699"}

{:event/type "corner"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Andrea Pirlo"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1668421"
:event/minute 95
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Emanuele Giaccherini"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1668424"
:event/minute 95
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Andrea Pirlo"
:event/sortorder 5
:event/team "home"
:event/event_type "corner"
:event/id "event_1668429"
:event/minute 95
:event/match_id "match_11699"}

{:event/type "corner"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Andrea Pirlo"
:event/sortorder 5
:event/team "home"
:event/event_type "corner"
:event/id "event_1668429"
:event/minute 95
:event/match_id "match_11699"}

{:event/type "cross"
:event/elapsed_plus 6
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Arturo Vidal"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1668437"
:event/minute 96
:event/match_id "match_11699"}


]

