
;;# data
[
{:match/id "match_7455"
:match/league "France Ligue 1"
:match/hometeam "Olympique Lyonnais"
:match/awayteam "Toulouse FC"
:match/score "3:1"
:match/hometeam_goals "3"
:match/awayteam_goals "0"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Sergi Darder"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4940188"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_7455"}

{:event/type "shotoff"
:event/elapsed 3
:event/subtype "distance"
:event/player1 "Jordan Ferri"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4940191"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Jordan Ferri"
:event/player1 "Oscar Trejo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4940194"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Jordan Ferri"
:event/player1 "Oscar Trejo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4940222"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_7455"}

{:event/type "corner"
:event/elapsed 9
:event/subtype "cross_right"
:event/player1 "Oscar Trejo"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4940245"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_7455"}

{:event/type "shoton"
:event/elapsed 9
:event/subtype "header"
:event/player1 "Tongo Hamed Doumbia"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4940250"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Christophe Jallet"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4940258"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_7455"}

{:event/type "shoton"
:event/elapsed 10
:event/subtype "shot"
:event/player1 "Mathieu Valbuena"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_4940263"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_7455"}

{:event/type "shoton"
:event/elapsed 12
:event/subtype "volley"
:event/player1 "Claudio Beauvue"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4940290"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_7455"}

{:event/type "corner"
:event/elapsed 13
:event/subtype "cross_right"
:event/player1 "Mathieu Valbuena"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4940298"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Jeremy Morel"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4940323"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_7455"}

{:event/type "shotoff"
:event/elapsed 15
:event/subtype "header"
:event/player1 "Claudio Beauvue"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4940328"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Mathieu Valbuena"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4940359"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_7455"}

{:event/type "goal"
:event/elapsed 18
:event/player2 "Mathieu Valbuena"
:event/subtype "shot"
:event/player1 "Sergi Darder"
:event/sortorder 2
:event/team "home"
:event/id "event_4940361"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Oscar Trejo"
:event/player1 "Jordan Ferri"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4940369"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Jean-Daniel Akpa-Akpro"
:event/subtype "trip"
:event/player1 "Christophe Jallet"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4940373"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Oscar Trejo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4940381"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Yann Bodiger"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4940389"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Alexandre Lacazette"
:event/subtype "pushing"
:event/player1 "Steeve Yago"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4940399"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Mathieu Valbuena"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4940404"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_7455"}

{:event/type "shotoff"
:event/elapsed 22
:event/subtype "shot"
:event/player1 "Christophe Jallet"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4940408"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Alexandre Lacazette"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4940429"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_7455"}

{:event/type "shoton"
:event/elapsed 24
:event/subtype "header"
:event/player1 "Jeremy Morel"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4940431"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Francois Moubandje"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4940448"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Mathieu Valbuena"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4940454"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Jordan Ferri"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4940456"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Mathieu Valbuena"
:event/subtype "serious_foul"
:event/player1 "Francois Moubandje"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4940460"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_7455"}

{:event/type "card"
:event/elapsed 29
:event/card_type "y"
:event/player1 "Francois Moubandje"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_4940462"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Yann Bodiger"
:event/subtype "trip"
:event/player1 "Sergi Darder"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4940479"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Sergi Darder"
:event/subtype "serious_foul"
:event/player1 "Yann Bodiger"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4940483"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_7455"}

{:event/type "card"
:event/elapsed 31
:event/card_type "y"
:event/player1 "Yann Bodiger"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_4940485"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Alexandre Lacazette"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4940498"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_7455"}

{:event/type "shotoff"
:event/elapsed 33
:event/subtype "post"
:event/player1 "Sergi Darder"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4940500"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Martin Braithwaite"
:event/player1 "Jordan Ferri"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4940508"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Wissam Ben Yedder"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4940513"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed 34
:event/player2 "Alexandre Lacazette"
:event/player1 "Steeve Yago"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4940516"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Oscar Trejo"
:event/player1 "Corentin Tolisso"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4940531"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Wissam Ben Yedder"
:event/player1 "Jordan Ferri"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4940537"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Oscar Trejo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4940542"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Jeremy Morel"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4940551"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Alexandre Lacazette"
:event/subtype "from_behind"
:event/player1 "Jean-Daniel Akpa-Akpro"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4940560"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_7455"}

{:event/type "shoton"
:event/elapsed 40
:event/subtype "direct_freekick"
:event/player1 "Mathieu Valbuena"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_4940579"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Wissam Ben Yedder"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4940592"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_7455"}

{:event/type "shotoff"
:event/elapsed 42
:event/subtype "distance"
:event/player1 "Jean-Daniel Akpa-Akpro"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4940597"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Mathieu Valbuena"
:event/player1 "Yann Bodiger"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4940602"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Francois Moubandje"
:event/subtype "pushing"
:event/player1 "Alexandre Lacazette"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4940611"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Alexandre Lacazette"
:event/subtype "dangerous_play"
:event/player1 "Jean-Daniel Akpa-Akpro"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4940617"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_7455"}

{:event/type "card"
:event/elapsed 44
:event/card_type "y"
:event/player1 "Jean-Daniel Akpa-Akpro"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_4940618"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Mathieu Valbuena"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4940634"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed 47
:event/player2 "Christophe Jallet"
:event/subtype "dangerous_play"
:event/player1 "Somalia"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4940752"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Claudio Beauvue"
:event/sortorder 6
:event/team "home"
:event/event_type "cross"
:event/id "event_4940648"
:event/minute 47
:event/match_id "match_7455"}

{:event/type "shoton"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "shot"
:event/player1 "Alexandre Lacazette"
:event/sortorder 7
:event/team "home"
:event/event_type "shoton"
:event/id "event_4940649"
:event/minute 47
:event/match_id "match_7455"}

{:event/type "corner"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross_right"
:event/player1 "Mathieu Valbuena"
:event/sortorder 10
:event/team "home"
:event/event_type "corner"
:event/id "event_4940656"
:event/minute 47
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Marcel Tisserand"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4940758"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_7455"}

{:event/type "corner"
:event/elapsed 48
:event/subtype "cross_right"
:event/player1 "Oscar Trejo"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_4940762"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_7455"}

{:event/type "shotoff"
:event/elapsed 48
:event/subtype "header"
:event/player1 "Martin Braithwaite"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4940764"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Mathieu Valbuena"
:event/sortorder 12
:event/team "home"
:event/event_type "cross"
:event/id "event_4940661"
:event/minute 48
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Jeremy Morel"
:event/sortorder 15
:event/team "home"
:event/event_type "cross"
:event/id "event_4940662"
:event/minute 48
:event/match_id "match_7455"}

{:event/type "shoton"
:event/elapsed 49
:event/subtype "deflected"
:event/player1 "Claudio Beauvue"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4940775"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_7455"}

{:event/type "corner"
:event/elapsed_plus 4
:event/elapsed 45
:event/subtype "cross_left"
:event/player1 "Mathieu Valbuena"
:event/sortorder 16
:event/team "home"
:event/event_type "corner"
:event/id "event_4940666"
:event/minute 49
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Maxime Gonalons"
:event/subtype "from_behind"
:event/player1 "Oscar Trejo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4940780"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_7455"}

{:event/type "card"
:event/elapsed 50
:event/card_type "y"
:event/player1 "Oscar Trejo"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4940781"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_7455"}

{:event/type "shotoff"
:event/elapsed 51
:event/subtype "shot"
:event/player1 "Sergi Darder"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4940794"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Oscar Trejo"
:event/subtype "serious_foul"
:event/player1 "Jeremy Morel"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4940802"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_7455"}

{:event/type "card"
:event/elapsed 51
:event/card_type "y"
:event/player1 "Jeremy Morel"
:event/sortorder 4
:event/team "home"
:event/event_type "card"
:event/id "event_4940803"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Oscar Trejo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4940809"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Mathieu Valbuena"
:event/player1 "Steeve Yago"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4940812"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Jordan Ferri"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4940827"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_7455"}

{:event/type "shoton"
:event/elapsed 53
:event/subtype "volley"
:event/player1 "Claudio Beauvue"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4940831"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Marcel Tisserand"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4940833"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_7455"}

{:event/type "shoton"
:event/elapsed 54
:event/subtype "big chance shot"
:event/player1 "Somalia"
:event/sortorder 6
:event/team "away"
:event/event_type "shoton"
:event/id "event_4940842"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_7455"}

{:event/type "corner"
:event/elapsed 55
:event/subtype "cross_right"
:event/player1 "Oscar Trejo"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4940845"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_7455"}

{:event/type "goal"
:event/elapsed 55
:event/subtype "shot"
:event/player1 "Martin Braithwaite"
:event/sortorder 3
:event/team "away"
:event/id "event_4940856"
:event/event_type "goal"
:event/goal_type "dg"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Jeremy Morel"
:event/player1 "Jean-Daniel Akpa-Akpro"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4940870"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Marcel Tisserand"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4940888"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_7455"}

{:event/type "shotoff"
:event/elapsed 59
:event/subtype "deflected"
:event/player1 "Jeremy Morel"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4940904"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_7455"}

{:event/type "corner"
:event/elapsed 60
:event/subtype "cross_left"
:event/player1 "Mathieu Valbuena"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4940907"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Martin Braithwaite"
:event/player1 "Samuel Umtiti"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4940922"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_7455"}

{:event/type "corner"
:event/elapsed 63
:event/subtype "cross_left"
:event/player1 "Oscar Trejo"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4940937"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Anthony Lopes"
:event/subtype "pushing"
:event/player1 "Yann Bodiger"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4940938"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_7455"}

{:event/type "shoton"
:event/elapsed 67
:event/subtype "shot"
:event/player1 "Martin Braithwaite"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_4940960"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Wissam Ben Yedder"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_4940961"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Jeremy Morel"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4940977"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Claudio Beauvue"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_4940986"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_7455"}

{:event/type "goal"
:event/elapsed 69
:event/player2 "Claudio Beauvue"
:event/subtype "shot"
:event/player1 "Mathieu Valbuena"
:event/sortorder 5
:event/team "home"
:event/id "event_4940988"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Corentin Tolisso"
:event/subtype "pushing"
:event/player1 "Oscar Trejo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4941001"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_7455"}

{:event/type "shotoff"
:event/elapsed 72
:event/subtype "distance"
:event/player1 "Corentin Tolisso"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4941016"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Jordan Ferri"
:event/player1 "Jean-Daniel Akpa-Akpro"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4941023"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Marcel Tisserand"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4941035"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Mathieu Valbuena"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4941042"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_7455"}

{:event/type "shotoff"
:event/elapsed 76
:event/subtype "shot"
:event/player1 "Sergi Darder"
:event/sortorder 5
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4941047"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Christophe Jallet"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4941062"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Steeve Yago"
:event/subtype "trip"
:event/player1 "Alexandre Lacazette"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4941092"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Adrien Regattin"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4941093"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_7455"}

{:event/type "corner"
:event/elapsed 83
:event/subtype "cross_left"
:event/player1 "Adrien Regattin"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4941096"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Jean-Armel Kana-Biyik"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4941099"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_7455"}

{:event/type "shotoff"
:event/elapsed 84
:event/subtype "bad shot"
:event/player1 "Jordan Ferri"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4941104"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Rachid Ghezzal"
:event/player1 "Steeve Yago"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4941114"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Jeremy Morel"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4941118"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed 87
:event/subtype "hands"
:event/player1 "Jeremy Morel"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4941129"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Adrien Regattin"
:event/subtype "trip"
:event/player1 "Maxime Gonalons"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4941139"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_7455"}

{:event/type "shotoff"
:event/elapsed 89
:event/subtype "direct_freekick"
:event/player1 "Adrien Regattin"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4941147"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Somalia"
:event/player1 "Gnaly Maxwell Cornet"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4941162"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_7455"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Aleksandar Pesic"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4941164"
:event/minute 91
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "hands"
:event/player1 "Yann Bodiger"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4941166"
:event/minute 91
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Jean-Daniel Akpa-Akpro"
:event/player1 "Steed Malbranque"
:event/sortorder 5
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4941167"
:event/minute 92
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Yann Bodiger"
:event/player1 "Corentin Tolisso"
:event/sortorder 6
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4941168"
:event/minute 92
:event/match_id "match_7455"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Steeve Yago"
:event/player1 "Gnaly Maxwell Cornet"
:event/sortorder 7
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4941173"
:event/minute 93
:event/match_id "match_7455"}

{:event/type "shotoff"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "distance"
:event/player1 "Yann Bodiger"
:event/sortorder 10
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4941181"
:event/minute 93
:event/match_id "match_7455"}

{:event/type "goal"
:event/elapsed_plus 4
:event/elapsed 90
:event/player2 "Claudio Beauvue"
:event/subtype "shot"
:event/player1 "Gnaly Maxwell Cornet"
:event/sortorder 13
:event/team "home"
:event/id "event_4941184"
:event/event_type "goal"
:event/goal_type "n"
:event/minute 94
:event/match_id "match_7455"}


]

