
;;# data
[
{:match/id "match_7449"
:match/league "France Ligue 1"
:match/hometeam "Angers SCO"
:match/awayteam "En Avant de Guingamp"
:match/score "0:0"
:match/hometeam_goals "0"
:match/awayteam_goals "0"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Gilles Sunu"
:event/subtype "pushing"
:event/player1 "Jeremy Sorbon"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4947586"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_7449"}

{:event/type "foulcommit"
:event/elapsed 6
:event/player2 "Jeremy Sorbon"
:event/subtype "pushing"
:event/player1 "Gilles Sunu"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4947654"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_7449"}

{:event/type "foulcommit"
:event/elapsed 6
:event/player2 "Yannis Salibur"
:event/subtype "trip"
:event/player1 "Yoann Andreu"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4947659"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Yannis Salibur"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4947670"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_7449"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Gilles Sunu"
:event/subtype "pushing"
:event/player1 "Benjamin Brou Angoua"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4947682"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_7449"}

{:event/type "shotoff"
:event/elapsed 9
:event/subtype "shot"
:event/player1 "Gilles Sunu"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4947703"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Vincent Manceau"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4947727"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_7449"}

{:event/type "shoton"
:event/elapsed 11
:event/subtype "header"
:event/player1 "Gilles Sunu"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4947733"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_7449"}

{:event/type "shoton"
:event/elapsed 11
:event/subtype "deflected"
:event/player1 "Romain Saiss"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4947745"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_7449"}

{:event/type "corner"
:event/elapsed 12
:event/subtype "cross_right"
:event/player1 "Thomas Mangani"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4947755"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Yannis Salibur"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4947763"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_7449"}

{:event/type "corner"
:event/elapsed 13
:event/subtype "short_right"
:event/player1 "Yannis Salibur"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4947777"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Yannis Salibur"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4947795"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_7449"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Gilles Sunu"
:event/subtype "pushing"
:event/player1 "Jeremy Sorbon"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4947805"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Thomas Mangani"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4947817"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_7449"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Jeremy Sorbon"
:event/subtype "pull"
:event/player1 "Cheikh Ndoye"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4947872"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_7449"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Nicolas Benezet"
:event/subtype "serious_foul"
:event/player1 "Abdoul Razzagui Camara"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4947890"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_7449"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Cheikh Ndoye"
:event/subtype "dangerous_play"
:event/player1 "Mustapha Diallo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4947905"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Abdoul Razzagui Camara"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4947927"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_7449"}

{:event/type "corner"
:event/elapsed 22
:event/subtype "cross_left"
:event/player1 "Thomas Mangani"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4947933"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Vincent Manceau"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4947948"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_7449"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Yannis Salibur"
:event/subtype "from_behind"
:event/player1 "Yoann Andreu"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4947996"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Yannis Salibur"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4947999"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Yannis Salibur"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4948007"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Abdoul Razzagui Camara"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4948021"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Yannis Salibur"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4948041"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_7449"}

{:event/type "corner"
:event/elapsed 33
:event/subtype "cross_right"
:event/player1 "Nicolas Benezet"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4948047"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_7449"}

{:event/type "shoton"
:event/elapsed 33
:event/subtype "deflected"
:event/player1 "Jimmy Briand"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4948049"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_7449"}

{:event/type "corner"
:event/elapsed 33
:event/subtype "short_right"
:event/player1 "Nicolas Benezet"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4948051"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Yannis Salibur"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4948053"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Dorian Leveque"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4948062"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_7449"}

{:event/type "corner"
:event/elapsed 34
:event/subtype "cross_left"
:event/player1 "Nicolas Benezet"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4948068"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_7449"}

{:event/type "shoton"
:event/elapsed 34
:event/subtype "big chance shot"
:event/player1 "Mustapha Diallo"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4948072"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_7449"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Lionel Mathis"
:event/subtype "pushing"
:event/player1 "Ismael Traore"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4948075"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Yannis Salibur"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4948085"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_7449"}

{:event/type "corner"
:event/elapsed 36
:event/subtype "cross_right"
:event/player1 "Yannis Salibur"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4948092"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_7449"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Cheikh Ndoye"
:event/subtype "from_behind"
:event/player1 "Mustapha Diallo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4948107"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_7449"}

{:event/type "card"
:event/elapsed 38
:event/card_type "y"
:event/player1 "Mustapha Diallo"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4948108"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Thomas Mangani"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4948111"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_7449"}

{:event/type "shoton"
:event/elapsed 39
:event/subtype "header"
:event/player1 "Romain Thomas"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4948115"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_7449"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Jimmy Briand"
:event/subtype "trip"
:event/player1 "Gilles Sunu"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4948119"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Yannis Salibur"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4948124"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_7449"}

{:event/type "shotoff"
:event/elapsed 40
:event/subtype "shot"
:event/player1 "Yannis Salibur"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4948126"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_7449"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Lionel Mathis"
:event/player1 "Thomas Mangani"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4948131"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_7449"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Yannis Salibur"
:event/subtype "trip"
:event/player1 "Romain Thomas"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4948142"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_7449"}

{:event/type "card"
:event/elapsed 43
:event/card_type "y"
:event/player1 "Romain Thomas"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_4948160"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Yannis Salibur"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_4948177"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_7449"}

{:event/type "shoton"
:event/elapsed 44
:event/subtype "distance"
:event/player1 "Abdoul Razzagui Camara"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4948184"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_7449"}

{:event/type "corner"
:event/elapsed 44
:event/subtype "short_left"
:event/player1 "Gilles Sunu"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_4948186"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_7449"}

{:event/type "shotoff"
:event/elapsed 44
:event/subtype "distance"
:event/player1 "Gilles Sunu"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4948187"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_7449"}

{:event/type "foulcommit"
:event/elapsed 46
:event/player2 "Yannis Salibur"
:event/subtype "trip"
:event/player1 "Yoann Andreu"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4948429"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_7449"}

{:event/type "foulcommit"
:event/elapsed 47
:event/player2 "Mustapha Diallo"
:event/subtype "trip"
:event/player1 "Ferebory Dore"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4948442"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_7449"}

{:event/type "shotoff"
:event/elapsed 48
:event/subtype "distance"
:event/player1 "Yannis Salibur"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4948451"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Abdoul Razzagui Camara"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4948459"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_7449"}

{:event/type "corner"
:event/elapsed 49
:event/subtype "cross_left"
:event/player1 "Thomas Mangani"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4948464"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_7449"}

{:event/type "shotoff"
:event/elapsed 49
:event/subtype "shot"
:event/player1 "Nicolas Benezet"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4948476"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_7449"}

{:event/type "shotoff"
:event/elapsed 52
:event/subtype "distance"
:event/player1 "Gilles Sunu"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4948524"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_7449"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Mustapha Diallo"
:event/subtype "pushing"
:event/player1 "Ferebory Dore"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4948550"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Thomas Mangani"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4948571"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_7449"}

{:event/type "corner"
:event/elapsed 55
:event/subtype "cross_right"
:event/player1 "Thomas Mangani"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4948584"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Yoann Andreu"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4948611"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_7449"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Abdoul Razzagui Camara"
:event/subtype "from_behind"
:event/player1 "Benjamin Brou Angoua"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4948634"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_7449"}

{:event/type "card"
:event/elapsed 58
:event/card_type "y"
:event/player1 "Benjamin Brou Angoua"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4948639"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Thomas Mangani"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4948653"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_7449"}

{:event/type "shoton"
:event/elapsed 59
:event/subtype "deflected"
:event/player1 "Yannis Salibur"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_4948664"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_7449"}

{:event/type "corner"
:event/elapsed 60
:event/subtype "cross_right"
:event/player1 "Yannis Salibur"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4948676"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Yannis Salibur"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4948682"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_7449"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Jeremy Sorbon"
:event/subtype "trip"
:event/player1 "Slimane Sissoko"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4948706"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Abdoul Razzagui Camara"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4948720"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Thomas Mangani"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4948744"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_7449"}

{:event/type "corner"
:event/elapsed 65
:event/subtype "cross_right"
:event/player1 "Thomas Mangani"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4948752"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Romain Thomas"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4948782"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_7449"}

{:event/type "shoton"
:event/elapsed 67
:event/subtype "blocked_header"
:event/player1 "Cheikh Ndoye"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4948786"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_7449"}

{:event/type "corner"
:event/elapsed 67
:event/subtype "cross_right"
:event/player1 "Thomas Mangani"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4948793"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_7449"}

{:event/type "shotoff"
:event/elapsed 67
:event/subtype "header"
:event/player1 "Romain Saiss"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4948795"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Yoann Andreu"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4948801"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_7449"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Vincent Manceau"
:event/subtype "pushing"
:event/player1 "Jimmy Briand"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4948836"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Jimmy Briand"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4948879"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_7449"}

{:event/type "shoton"
:event/elapsed 73
:event/subtype "shot"
:event/player1 "Mustapha Diallo"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4948884"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_7449"}

{:event/type "foulcommit"
:event/elapsed 74
:event/subtype "hands"
:event/player1 "Pierrick Capelle"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4948886"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_7449"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Lionel Mathis"
:event/subtype "pushing"
:event/player1 "Thomas Mangani"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4948901"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_7449"}

{:event/type "shoton"
:event/elapsed 76
:event/subtype "deflected"
:event/player1 "Younousse Sankhare"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4948924"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_7449"}

{:event/type "corner"
:event/elapsed 76
:event/subtype "cross_left"
:event/player1 "Younousse Sankhare"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_4948925"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Yannis Salibur"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4948932"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_7449"}

{:event/type "shotoff"
:event/elapsed 77
:event/subtype "header"
:event/player1 "Mustapha Diallo"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4948937"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_7449"}

{:event/type "foulcommit"
:event/elapsed 78
:event/subtype "hands"
:event/player1 "Slimane Sissoko"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4948948"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Yannis Salibur"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4948952"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_7449"}

{:event/type "foulcommit"
:event/elapsed 79
:event/player2 "Mustapha Diallo"
:event/subtype "pushing"
:event/player1 "Cheikh Ndoye"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4948965"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_7449"}

{:event/type "shotoff"
:event/elapsed 80
:event/subtype "distance"
:event/player1 "Thomas Mangani"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4948981"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_7449"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Mustapha Diallo"
:event/subtype "serious_foul"
:event/player1 "Slimane Sissoko"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4948989"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_7449"}

{:event/type "card"
:event/elapsed 81
:event/card_type "r"
:event/player1 "Slimane Sissoko"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4948992"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_7449"}

{:event/type "foulcommit"
:event/elapsed 83
:event/player2 "Marcus Regis Coco"
:event/subtype "trip"
:event/player1 "Thomas Mangani"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4949016"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_7449"}

{:event/type "card"
:event/elapsed 83
:event/card_type "y"
:event/player1 "Thomas Mangani"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_4949018"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_7449"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Romain Saiss"
:event/subtype "dangerous_play"
:event/player1 "Mustapha Diallo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4949041"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Yoann Andreu"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4949049"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_7449"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Yoann Andreu"
:event/subtype "pull"
:event/player1 "Marcus Regis Coco"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4949068"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_7449"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Marcus Regis Coco"
:event/subtype "pushing"
:event/player1 "Yoann Andreu"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4949079"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Yannis Salibur"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4949084"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Yoann Andreu"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_4949097"
:event/minute 92
:event/match_id "match_7449"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Yoann Andreu"
:event/player1 "Yannis Salibur"
:event/sortorder 6
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4949108"
:event/minute 93
:event/match_id "match_7449"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Romain Saiss"
:event/subtype "pushing"
:event/player1 "Benjamin Brou Angoua"
:event/sortorder 7
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4949114"
:event/minute 93
:event/match_id "match_7449"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Pierrick Capelle"
:event/sortorder 8
:event/team "home"
:event/event_type "cross"
:event/id "event_4949118"
:event/minute 94
:event/match_id "match_7449"}

{:event/type "shotoff"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "crossbar"
:event/player1 "Cheikh Ndoye"
:event/sortorder 9
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4949123"
:event/minute 94
:event/match_id "match_7449"}

{:event/type "shoton"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Jimmy Briand"
:event/sortorder 11
:event/team "away"
:event/event_type "shoton"
:event/id "event_4949134"
:event/minute 95
:event/match_id "match_7449"}


]

