
;;# data
[
{:match/id "match_10761"
:match/league "Italy Serie A"
:match/hometeam "Chievo Verona"
:match/awayteam "Juventus"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "goal"
:event/elapsed 33
:event/player1 "Pablo Mariano Granoche"
:event/sortorder 0
:event/team "home"
:event/id "event_913785"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_10761"}

{:event/type "card"
:event/elapsed 60
:event/card_type "y"
:event/player1 "Pablo Mariano Granoche"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_914316"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_10761"}

{:event/type "card"
:event/elapsed 64
:event/card_type "y"
:event/player1 "Mario Yepes"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_914387"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_10761"}

{:event/type "card"
:event/elapsed 70
:event/card_type "y"
:event/player1 "Jonathan Zebina"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_914422"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_10761"}

{:event/type "card"
:event/elapsed 74
:event/card_type "y"
:event/player1 "Felipe Melo"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_914446"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_10761"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Luca Ariatti"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_914631"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_10761"}


]

