
;;# data
[
{:match/id "match_5800"
:match/league "France Ligue 1"
:match/hometeam "AJ Auxerre"
:match/awayteam "Montpellier Hérault SC"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 41
:event/card_type "y"
:event/player1 "Mapou Yanga-Mbiwa"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1542268"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_5800"}

{:event/type "card"
:event/elapsed 41
:event/card_type "y"
:event/player1 "Cyril Jeunechamp"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1542269"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_5800"}

{:event/type "card"
:event/elapsed 56
:event/card_type "y"
:event/player1 "Jamel Saihi"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1542478"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_5800"}

{:event/type "card"
:event/elapsed 58
:event/card_type "y"
:event/player1 "Dennis Oliech"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1542477"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_5800"}

{:event/type "goal"
:event/elapsed 79
:event/player1 "Roy Contout"
:event/sortorder 0
:event/team "home"
:event/id "event_1542528"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_5800"}

{:event/type "card"
:event/elapsed 83
:event/card_type "y"
:event/player1 "Roy Contout"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1542568"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_5800"}


]

