
;;# data
[
{:match/id "match_8702"
:match/league "Germany 1. Bundesliga"
:match/hometeam "VfB Stuttgart"
:match/awayteam "Eintracht Frankfurt"
:match/score "1:2"
:match/hometeam_goals "1"
:match/awayteam_goals "2"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Patrick Ochs"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1204689"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Stefano Celozzi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1204707"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_8702"}

{:event/type "shotoff"
:event/elapsed 4
:event/subtype "big chance crossbar"
:event/player1 "Christian Traesch"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1204717"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_8702"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Cacau"
:event/subtype "pushing"
:event/player1 "Marco Russ"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1204728"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Christian Gentner"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1204734"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Mamadou Bah"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1204781"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_8702"}

{:event/type "shotoff"
:event/elapsed 8
:event/subtype "shot"
:event/player1 "Pavel Pogrebnyak"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1204788"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_8702"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Giorgos Tzavellas"
:event/subtype "pushing"
:event/player1 "Christian Traesch"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1204816"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_8702"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Benjamin Koehler"
:event/subtype "shirt_pull"
:event/player1 "Pavel Pogrebnyak"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1204827"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Giorgos Tzavellas"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1204880"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_8702"}

{:event/type "shotoff"
:event/elapsed 14
:event/subtype "header"
:event/player1 "Theofanis Gekas"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1204881"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_8702"}

{:event/type "shoton"
:event/elapsed 14
:event/subtype "big chance shot"
:event/player1 "Cacau"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_1204890"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Patrick Ochs"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1204904"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Giorgos Tzavellas"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1204918"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_8702"}

{:event/type "corner"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Giorgos Tzavellas"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1204918"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_8702"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "Pavel Pogrebnyak"
:event/subtype "pushing"
:event/player1 "Maik Franz"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1204927"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_8702"}

{:event/type "shotoff"
:event/elapsed 17
:event/subtype "header"
:event/player1 "Matthieu Delpierre"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1204940"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_1204952"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_8702"}

{:event/type "goal"
:event/elapsed 18
:event/player2 "Chris"
:event/subtype "header"
:event/player1 "Theofanis Gekas"
:event/sortorder 1
:event/team "away"
:event/id "event_1204954"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Cristian Molinaro"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1204977"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_8702"}

{:event/type "shoton"
:event/elapsed 21
:event/subtype "deflected"
:event/player1 "Christian Gentner"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1204980"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Zdravko Kuzmanovic"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1204983"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_8702"}

{:event/type "corner"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Zdravko Kuzmanovic"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1204983"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_8702"}

{:event/type "shotoff"
:event/elapsed 22
:event/subtype "distance"
:event/player1 "Cristian Molinaro"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1204985"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Patrick Ochs"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1204993"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_8702"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Christian Gentner"
:event/subtype "serious_foul"
:event/player1 "Patrick Ochs"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1204997"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_8702"}

{:event/type "shoton"
:event/elapsed 24
:event/subtype "direct_freekick"
:event/player1 "Zdravko Kuzmanovic"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1205004"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_8702"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Christian Gentner"
:event/subtype "from_behind"
:event/player1 "Pirmin Schwegler"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1205012"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_8702"}

{:event/type "card"
:event/elapsed 25
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Pirmin Schwegler"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1205010"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Stefano Celozzi"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1205016"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Christian Gentner"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1205057"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_8702"}

{:event/type "shotoff"
:event/elapsed 31
:event/subtype "bad shot"
:event/player1 "Stefano Celozzi"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1205061"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Giorgos Tzavellas"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1205094"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_8702"}

{:event/type "shotoff"
:event/elapsed 34
:event/subtype "header"
:event/player1 "Theofanis Gekas"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1205096"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Zdravko Kuzmanovic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1205113"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Christian Gentner"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1205114"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_8702"}

{:event/type "foulcommit"
:event/elapsed 35
:event/subtype "hands"
:event/player1 "Pavel Pogrebnyak"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1205123"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_8702"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Maik Franz"
:event/subtype "pushing"
:event/player1 "Christian Gentner"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1205186"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_8702"}

{:event/type "shotoff"
:event/elapsed 39
:event/subtype "header"
:event/player1 "Mamadou Bah"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1205218"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Christian Gentner"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1205311"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Giorgos Tzavellas"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1205342"
:event/minute 46
:event/match_id "match_8702"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "Christian Gentner"
:event/subtype "pushing"
:event/player1 "Chris"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1205354"
:event/minute 46
:event/match_id "match_8702"}

{:event/type "foulcommit"
:event/elapsed 47
:event/player2 "Cacau"
:event/subtype "serious_foul"
:event/player1 "Maik Franz"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1205662"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_8702"}

{:event/type "card"
:event/elapsed 47
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Maik Franz"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1205664"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_8702"}

{:event/type "shotoff"
:event/elapsed 49
:event/subtype "shot"
:event/player1 "Theofanis Gekas"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1205689"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Halil Altintop"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1205701"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_8702"}

{:event/type "shotoff"
:event/elapsed 49
:event/subtype "shot"
:event/player1 "Theofanis Gekas"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1205702"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_8702"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Pavel Pogrebnyak"
:event/subtype "pushing"
:event/player1 "Maik Franz"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1205705"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_8702"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Giorgos Tzavellas"
:event/subtype "pushing"
:event/player1 "Cacau"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1205717"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Patrick Ochs"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1205751"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_8702"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Halil Altintop"
:event/subtype "from_behind"
:event/player1 "Matthieu Delpierre"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1205761"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_8702"}

{:event/type "shotoff"
:event/elapsed 53
:event/subtype "direct_freekick"
:event/player1 "Benjamin Koehler"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1205765"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Pirmin Schwegler"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1205777"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_8702"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Pavel Pogrebnyak"
:event/subtype "shirt_pull"
:event/player1 "Marco Russ"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1205801"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_8702"}

{:event/type "card"
:event/elapsed 55
:event/card_type "y"
:event/subtype "shirt_pull"
:event/player1 "Marco Russ"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1205803"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_8702"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Sebastian Jung"
:event/subtype "pushing"
:event/player1 "Serdar Tasci"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1205813"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_8702"}

{:event/type "shotoff"
:event/elapsed 56
:event/subtype "distance"
:event/player1 "Chris"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1205826"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Arthur Boka"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1205846"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_8702"}

{:event/type "shotoff"
:event/elapsed 58
:event/subtype "volley"
:event/player1 "Christian Traesch"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1205851"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Stefano Celozzi"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1205861"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_8702"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player2 "Arthur Boka"
:event/subtype "pushing"
:event/player1 "Pirmin Schwegler"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1205878"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Christian Gentner"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1205888"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_8702"}

{:event/type "corner"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Christian Gentner"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1205888"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_8702"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Arthur Boka"
:event/subtype "pushing"
:event/player1 "Benjamin Koehler"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1205904"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Christian Gentner"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1205913"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_8702"}

{:event/type "corner"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Christian Gentner"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1205913"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_8702"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Maik Franz"
:event/subtype "pushing"
:event/player1 "Serdar Tasci"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1205916"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/sortorder 3
:event/team "away"
:event/event_type "throwin"
:event/id "event_1205939"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_8702"}

{:event/type "shoton"
:event/elapsed 66
:event/subtype "blocked_shot"
:event/player1 "Pirmin Schwegler"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1205941"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_8702"}

{:event/type "shoton"
:event/elapsed 66
:event/subtype "deflected"
:event/player1 "Patrick Ochs"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1205951"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Giorgos Tzavellas"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1205953"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_8702"}

{:event/type "corner"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Giorgos Tzavellas"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1205953"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Giorgos Tzavellas"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1205961"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_8702"}

{:event/type "shoton"
:event/elapsed 68
:event/subtype "big chance shot"
:event/player1 "Patrick Ochs"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_1205965"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Giorgos Tzavellas"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_1205967"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_8702"}

{:event/type "corner"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Giorgos Tzavellas"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_1205967"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_8702"}

{:event/type "goal"
:event/elapsed 68
:event/player2 "Giorgos Tzavellas"
:event/subtype "header"
:event/player1 "Chris"
:event/sortorder 5
:event/team "away"
:event/id "event_1205968"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_8702"}

{:event/type "card"
:event/elapsed 71
:event/card_type "y"
:event/subtype "hands"
:event/player1 "Pavel Pogrebnyak"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1205972"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_8702"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Patrick Ochs"
:event/subtype "pushing"
:event/player1 "Cacau"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1205987"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Mamadou Bah"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1205997"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_8702"}

{:event/type "corner"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Mamadou Bah"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1205997"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_8702"}

{:event/type "shotoff"
:event/elapsed 75
:event/subtype "shot"
:event/player1 "Christian Traesch"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1205999"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_8702"}

{:event/type "shotoff"
:event/elapsed 75
:event/subtype "shot"
:event/player1 "Ciprian Marica"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1206003"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_8702"}

{:event/type "foulcommit"
:event/elapsed 76
:event/player2 "Halil Altintop"
:event/subtype "pushing"
:event/player1 "Mamadou Bah"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1206026"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_8702"}

{:event/type "shotoff"
:event/elapsed 78
:event/subtype "crossbar"
:event/player1 "Pavel Pogrebnyak"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1206037"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_8702"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Patrick Ochs"
:event/subtype "from_behind"
:event/player1 "Arthur Boka"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1206057"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_8702"}

{:event/type "card"
:event/elapsed 80
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Arthur Boka"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_1206059"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_8702"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Pavel Pogrebnyak"
:event/subtype "pushing"
:event/player1 "Sebastian Jung"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1206073"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_8702"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Christian Traesch"
:event/subtype "shirt_pull"
:event/player1 "Giorgos Tzavellas"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1206079"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_8702"}

{:event/type "shotoff"
:event/elapsed 82
:event/subtype "post"
:event/player1 "Arthur Boka"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1206085"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Arthur Boka"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_1206113"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_8702"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Patrick Ochs"
:event/subtype "serious_foul"
:event/player1 "Matthieu Delpierre"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1206120"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_8702"}

{:event/type "card"
:event/elapsed 84
:event/card_type "r"
:event/subtype "serious_fouls"
:event/player1 "Matthieu Delpierre"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_1206124"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Martin Harnik"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1206140"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_8702"}

{:event/type "shoton"
:event/elapsed 84
:event/subtype "header"
:event/player1 "Ciprian Marica"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_1206148"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_8702"}

{:event/type "goal"
:event/elapsed 85
:event/subtype "shot"
:event/player1 "Pavel Pogrebnyak"
:event/sortorder 0
:event/team "home"
:event/id "event_1206132"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_8702"}

{:event/type "card"
:event/elapsed 85
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Giorgos Tzavellas"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1206138"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Arthur Boka"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1206161"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_8702"}

{:event/type "shotoff"
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Halil Altintop"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1206206"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_8702"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Christian Traesch"
:event/subtype "pushing"
:event/player1 "Marco Russ"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1206212"
:event/minute 91
:event/match_id "match_8702"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Zdravko Kuzmanovic"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_1206227"
:event/minute 91
:event/match_id "match_8702"}

{:event/type "corner"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Zdravko Kuzmanovic"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_1206227"
:event/minute 91
:event/match_id "match_8702"}

{:event/type "corner"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "short"
:event/player1 "Zdravko Kuzmanovic"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1206245"
:event/minute 92
:event/match_id "match_8702"}


]

