
;;# data
[
{:match/id "match_4269"
:match/league "England Premier League"
:match/hometeam "Arsenal"
:match/awayteam "Sunderland"
:match/score "0:0"
:match/hometeam_goals "0"
:match/awayteam_goals "0"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Aaron Ramsey"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4498334"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_4269"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "Kieran Gibbs"
:event/player1 "Adam Johnson"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4498344"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Hector Bellerin"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4498339"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_4269"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Sebastian Larsson"
:event/subtype "pull"
:event/player1 "Hector Bellerin"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4498347"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_4269"}

{:event/type "foulcommit"
:event/elapsed 6
:event/player2 "Billy Jones"
:event/subtype "pushing"
:event/player1 "Aaron Ramsey"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4498349"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Sebastian Larsson"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4498355"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Billy Jones"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4498362"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Hector Bellerin"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4498366"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_4269"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Santi Cazorla"
:event/player1 "Lee Cattermole"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4498372"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Kieran Gibbs"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4498376"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_4269"}

{:event/type "corner"
:event/elapsed 12
:event/subtype "cross_left"
:event/player1 "Mesut Oezil"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4498378"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_4269"}

{:event/type "corner"
:event/elapsed 13
:event/subtype "short_left"
:event/player1 "Mesut Oezil"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4498380"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 13
:event/subtype "cross"
:event/player1 "Mesut Oezil"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4498382"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Hector Bellerin"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4498398"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_4269"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Sebastian Coates"
:event/subtype "pushing"
:event/player1 "Olivier Giroud"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4498399"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Olivier Giroud"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4498403"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_4269"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Sebastian Larsson"
:event/subtype "serious_foul"
:event/player1 "Aaron Ramsey"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4498415"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_4269"}

{:event/type "card"
:event/elapsed 18
:event/card_type "y"
:event/player1 "Aaron Ramsey"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_4498416"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Mesut Oezil"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4498423"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_4269"}

{:event/type "shotoff"
:event/elapsed 20
:event/subtype "volley"
:event/player1 "Jack Wilshere"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4498424"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_4269"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Santi Cazorla"
:event/player1 "Lee Cattermole"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4498442"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Mesut Oezil"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4498453"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_4269"}

{:event/type "shoton"
:event/elapsed 23
:event/subtype "distance"
:event/player1 "Santi Cazorla"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4498458"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_4269"}

{:event/type "shoton"
:event/elapsed 26
:event/subtype "blocked_shot"
:event/player1 "Alexis Sanchez"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_4498479"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_4269"}

{:event/type "shoton"
:event/elapsed 27
:event/subtype "blocked_shot"
:event/player1 "Olivier Giroud"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4498488"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_4269"}

{:event/type "shotoff"
:event/elapsed 27
:event/subtype "distance"
:event/player1 "Kieran Gibbs"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4498489"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Daniel Graham"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4498503"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_4269"}

{:event/type "shotoff"
:event/elapsed 30
:event/subtype "volley"
:event/player1 "Mesut Oezil"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4498520"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_4269"}

{:event/type "shotoff"
:event/elapsed 32
:event/subtype "shot"
:event/player1 "Olivier Giroud"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4498530"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Kieran Gibbs"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4498542"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_4269"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Daniel Graham"
:event/subtype "dangerous_play"
:event/player1 "Per Mertesacker"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4498562"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_4269"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Mesut Oezil"
:event/subtype "pushing"
:event/player1 "Lee Cattermole"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4498573"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_4269"}

{:event/type "shotoff"
:event/elapsed 38
:event/subtype "distance"
:event/player1 "Mesut Oezil"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4498581"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_4269"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Jack Wilshere"
:event/subtype "pushing"
:event/player1 "Sebastian Larsson"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4498589"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Mesut Oezil"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4498590"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_4269"}

{:event/type "shoton"
:event/elapsed 40
:event/subtype "distance"
:event/player1 "Alexis Sanchez"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4498597"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Mesut Oezil"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4498607"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_4269"}

{:event/type "shotoff"
:event/elapsed 42
:event/subtype "distance"
:event/player1 "Adam Johnson"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4498620"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_4269"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player1 "Jermain Defoe"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4498637"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Kieran Gibbs"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4498665"
:event/minute 47
:event/match_id "match_4269"}

{:event/type "corner"
:event/elapsed 47
:event/subtype "cross_left"
:event/player1 "Alexis Sanchez"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4498769"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_4269"}

{:event/type "shoton"
:event/elapsed 50
:event/subtype "big chance shot"
:event/player1 "Steven Fletcher"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4498796"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_4269"}

{:event/type "shoton"
:event/elapsed 50
:event/subtype "big chance shot"
:event/player1 "Patrick van Aanholt"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_4498798"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_4269"}

{:event/type "corner"
:event/elapsed 51
:event/subtype "cross_left"
:event/player1 "Sebastian Larsson"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4498799"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Mesut Oezil"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4498812"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_4269"}

{:event/type "shoton"
:event/elapsed 55
:event/subtype "header"
:event/player1 "Olivier Giroud"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4498813"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_4269"}

{:event/type "shoton"
:event/elapsed 55
:event/subtype "blocked_shot"
:event/player1 "Steven Fletcher"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_4498816"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Hector Bellerin"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4498818"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_4269"}

{:event/type "shoton"
:event/elapsed 56
:event/subtype "volley"
:event/player1 "Olivier Giroud"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4498820"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_4269"}

{:event/type "shotoff"
:event/elapsed 56
:event/subtype "distance"
:event/player1 "Aaron Ramsey"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4498822"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Hector Bellerin"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4498830"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_4269"}

{:event/type "shoton"
:event/elapsed 58
:event/subtype "distance"
:event/player1 "Kieran Gibbs"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4498831"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_4269"}

{:event/type "shoton"
:event/elapsed 60
:event/subtype "blocked_shot"
:event/player1 "Alexis Sanchez"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4498839"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_4269"}

{:event/type "shoton"
:event/elapsed 60
:event/subtype "lob"
:event/player1 "Steven Fletcher"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4498841"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_4269"}

{:event/type "corner"
:event/elapsed 61
:event/subtype "cross_left"
:event/player1 "Sebastian Larsson"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4498843"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_4269"}

{:event/type "shotoff"
:event/elapsed 61
:event/subtype "header"
:event/player1 "Sebastian Coates"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4498845"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_4269"}

{:event/type "shoton"
:event/elapsed 63
:event/subtype "blocked_shot"
:event/player1 "Santi Cazorla"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4498855"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_4269"}

{:event/type "shoton"
:event/elapsed 63
:event/subtype "blocked_shot"
:event/player1 "Kieran Gibbs"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4498856"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_4269"}

{:event/type "corner"
:event/elapsed 63
:event/subtype "cross_right"
:event/player1 "Mesut Oezil"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4498857"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_4269"}

{:event/type "shoton"
:event/elapsed 63
:event/subtype "blocked_shot"
:event/player1 "Santi Cazorla"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_4498859"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Mesut Oezil"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4498860"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Alexis Sanchez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4498868"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_4269"}

{:event/type "shoton"
:event/elapsed 66
:event/subtype "blocked_shot"
:event/player1 "Alexis Sanchez"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4498870"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Mesut Oezil"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4498873"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_4269"}

{:event/type "shotoff"
:event/elapsed 67
:event/subtype "header"
:event/player1 "Olivier Giroud"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4498874"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_4269"}

{:event/type "shotoff"
:event/elapsed 67
:event/subtype "header"
:event/player1 "Alexis Sanchez"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4498876"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_4269"}

{:event/type "shoton"
:event/elapsed 68
:event/subtype "blocked_shot"
:event/player1 "Aaron Ramsey"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4498881"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Patrick van Aanholt"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4498882"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_4269"}

{:event/type "shotoff"
:event/elapsed 69
:event/subtype "big chance shot"
:event/player1 "Steven Fletcher"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4498883"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Hector Bellerin"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4498891"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Hector Bellerin"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4498894"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_4269"}

{:event/type "shoton"
:event/elapsed 73
:event/subtype "shot"
:event/player1 "Theo Walcott"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4498899"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_4269"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Theo Walcott"
:event/player1 "Lee Cattermole"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4498902"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Santi Cazorla"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4498903"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Aaron Ramsey"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4498907"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Kieran Gibbs"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4498913"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Hector Bellerin"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4498917"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_4269"}

{:event/type "shotoff"
:event/elapsed 77
:event/subtype "distance"
:event/player1 "Santi Cazorla"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4498920"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Alexis Sanchez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4498931"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_4269"}

{:event/type "shotoff"
:event/elapsed 83
:event/subtype "shot"
:event/player1 "Tomas Rosicky"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4498942"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_4269"}

{:event/type "shoton"
:event/elapsed 84
:event/subtype "shot"
:event/player1 "Theo Walcott"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4498948"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_4269"}

{:event/type "shoton"
:event/elapsed 85
:event/subtype "distance"
:event/player1 "Aaron Ramsey"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4498951"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_4269"}

{:event/type "corner"
:event/elapsed 86
:event/subtype "cross_right"
:event/player1 "Tomas Rosicky"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4498955"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_4269"}

{:event/type "shoton"
:event/elapsed 87
:event/subtype "shot"
:event/player1 "Theo Walcott"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4498961"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Aaron Ramsey"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4498967"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Hector Bellerin"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4498973"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Alexis Sanchez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4498975"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Alexis Sanchez"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4498978"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Olivier Giroud"
:event/sortorder 6
:event/team "home"
:event/event_type "cross"
:event/id "event_4498985"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_4269"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Alexis Sanchez"
:event/sortorder 9
:event/team "home"
:event/event_type "cross"
:event/id "event_4498991"
:event/minute 91
:event/match_id "match_4269"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Sebastian Larsson"
:event/subtype "pushing"
:event/player1 "Tomas Rosicky"
:event/sortorder 11
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4498993"
:event/minute 92
:event/match_id "match_4269"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Hector Bellerin"
:event/subtype "pull"
:event/player1 "Jermain Defoe"
:event/sortorder 12
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4498994"
:event/minute 93
:event/match_id "match_4269"}


]

