
;;# data
[
{:match/id "match_6350"
:match/league "France Ligue 1"
:match/hometeam "Girondins de Bordeaux"
:match/awayteam "FC Sochaux-Montbéliard"
:match/score "1:3"
:match/hometeam_goals "2"
:match/awayteam_goals "2"}

{:event/type "goal"
:event/elapsed 33
:event/player1 "Loic Poujol"
:event/sortorder 0
:event/team "away"
:event/id "event_2506005"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_6350"}

{:event/type "goal"
:event/elapsed 40
:event/player1 "Jerome Roussillon"
:event/sortorder 0
:event/team "away"
:event/id "event_2506009"
:event/event_type "goal"
:event/goal_type "o"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_6350"}

{:event/type "goal"
:event/elapsed 48
:event/player1 "Yoan Gouffran"
:event/sortorder 0
:event/team "home"
:event/id "event_2506030"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_6350"}

{:event/type "card"
:event/elapsed 63
:event/card_type "y"
:event/player1 "Yaya Banana"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2506053"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_6350"}

{:event/type "card"
:event/elapsed 86
:event/card_type "y"
:event/player1 "Marc Planus"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2506067"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_6350"}

{:event/type "goal"
:event/elapsed 87
:event/player1 "Rafael Dias"
:event/sortorder 0
:event/team "away"
:event/id "event_2506066"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_6350"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Jussie"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2506095"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_6350"}


]

