
;;# data
[
{:match/id "match_23019"
:match/league "Spain LIGA BBVA"
:match/hometeam "Getafe CF"
:match/awayteam "Villarreal CF"
:match/score "0:0"
:match/hometeam_goals "0"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 15
:event/card_type "y"
:event/player1 "Gonzalo Rodriguez"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1710729"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_23019"}

{:event/type "card"
:event/elapsed 35
:event/card_type "y"
:event/player1 "Pablo Sarabia"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1710967"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_23019"}

{:event/type "card"
:event/elapsed 48
:event/card_type "y"
:event/player1 "Juan Valera"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1711300"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_23019"}

{:event/type "card"
:event/elapsed 57
:event/card_type "y"
:event/player1 "Borja Valero"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1711480"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_23019"}

{:event/type "card"
:event/elapsed 59
:event/card_type "y"
:event/player1 "Jose Catala"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1711481"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_23019"}

{:event/type "card"
:event/elapsed 62
:event/card_type "y"
:event/player1 "Ruben Perez"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1711482"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_23019"}

{:event/type "card"
:event/elapsed 71
:event/card_type "y"
:event/player1 "Giuseppe Rossi"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1711581"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_23019"}

{:event/type "card"
:event/elapsed 75
:event/card_type "y"
:event/player1 "Carlos Marchena"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1711618"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_23019"}

{:event/type "card"
:event/elapsed 78
:event/card_type "y"
:event/player1 "Michel"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1711741"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_23019"}


]

