
;;# data
[
{:match/id "match_23313"
:match/league "Spain LIGA BBVA"
:match/hometeam "RC Deportivo de La Coruña"
:match/awayteam "Atlético Madrid"
:match/score "0:0"
:match/hometeam_goals "0"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 42
:event/card_type "y"
:event/player1 "Diego Godin"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2747906"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_23313"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Bruno Vilela Gama"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2747926"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_23313"}


]

