
;;# data
[
{:match/id "match_22678"
:match/league "Spain LIGA BBVA"
:match/hometeam "CA Osasuna"
:match/awayteam "Levante UD"
:match/score "2:0"
:match/hometeam_goals "2"
:match/awayteam_goals "0"}

{:event/type "goal"
:event/elapsed 39
:event/player1 "Alvaro Cejudo"
:event/sortorder 0
:event/team "home"
:event/id "event_1747182"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_22678"}

{:event/type "card"
:event/elapsed 40
:event/card_type "y"
:event/player1 "Alvaro Cejudo"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1747288"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_22678"}

{:event/type "goal"
:event/elapsed 42
:event/player1 "Nino"
:event/sortorder 0
:event/team "home"
:event/id "event_1747287"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_22678"}

{:event/type "card"
:event/elapsed 49
:event/card_type "y"
:event/player1 "Vicente Iborra"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1747359"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_22678"}

{:event/type "card"
:event/elapsed 59
:event/card_type "y"
:event/player1 "Alvaro Cejudo"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1747456"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_22678"}

{:event/type "card"
:event/elapsed 61
:event/card_type "y"
:event/player1 "Raul Garcia"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1747561"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_22678"}

{:event/type "card"
:event/elapsed 82
:event/card_type "y"
:event/player1 "Asier del Horno"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1747676"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_22678"}

{:event/type "card"
:event/elapsed 86
:event/card_type "y"
:event/player1 "Valdo"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1747683"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_22678"}


]

