
;;# data
[
{:match/id "match_21601"
:match/league "Spain LIGA BBVA"
:match/hometeam "RC Recreativo"
:match/awayteam "CD Numancia"
:match/score "3:2"
:match/hometeam_goals "3"
:match/awayteam_goals "1"}

{:event/type "goal"
:event/elapsed 16
:event/player1 "Jose Javier Barkero"
:event/sortorder 0
:event/team "away"
:event/id "event_544835"
:event/event_type "goal"
:event/goal_type "npm"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_21601"}

{:event/type "goal"
:event/elapsed 18
:event/player1 "Javi Fuego"
:event/sortorder 0
:event/team "home"
:event/id "event_544836"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_21601"}

{:event/type "card"
:event/elapsed 28
:event/card_type "y"
:event/player1 "Hipolito Poli"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_544894"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_21601"}

{:event/type "card"
:event/elapsed 35
:event/card_type "y"
:event/player1 "Javi Fuego"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_544934"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_21601"}

{:event/type "goal"
:event/elapsed 47
:event/player1 "Javier Camunas"
:event/sortorder 0
:event/team "home"
:event/id "event_544996"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_21601"}

{:event/type "goal"
:event/elapsed 61
:event/player1 "Fernandez Aitor Tornavaca,29"
:event/sortorder 0
:event/team "home"
:event/id "event_545070"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_21601"}

{:event/type "card"
:event/elapsed 72
:event/card_type "y"
:event/player1 "Iago Bouzon"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_545123"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_21601"}

{:event/type "goal"
:event/elapsed 90
:event/player1 "Gorka Brit"
:event/sortorder 0
:event/team "away"
:event/id "event_545222"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_21601"}


]

