
;;# data
[
{:match/id "match_22572"
:match/league "Spain LIGA BBVA"
:match/hometeam "RCD Espanyol"
:match/awayteam "Valencia CF"
:match/score "2:2"
:match/hometeam_goals "2"
:match/awayteam_goals "2"}

{:event/type "foulcommit"
:event/elapsed 1
:event/player2 "Joan Verdu"
:event/player1 "Jonas"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1550103"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_22572"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Jose Maria Callejon"
:event/player1 "Joaquin"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1550133"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_22572"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Joan Verdu"
:event/player1 "Bruno Saltor"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1550161"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Bruno Saltor"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1550170"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_22572"}

{:event/type "goal"
:event/elapsed 9
:event/subtype "shot"
:event/player1 "Roberto Soldado"
:event/sortorder 3
:event/team "away"
:event/id "event_1550180"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_22572"}

{:event/type "corner"
:event/elapsed 11
:event/subtype "short"
:event/player1 "Jose Maria Callejon"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1550196"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_22572"}

{:event/type "shotoff"
:event/elapsed 11
:event/subtype "bad shot"
:event/player1 "Francisco Chica"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1550200"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Pablo Osvaldo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1550209"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_22572"}

{:event/type "shoton"
:event/elapsed 14
:event/subtype "blocked_shot"
:event/player1 "Javi Lopez"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1550224"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Jose Maria Callejon"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1550240"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Jose Maria Callejon"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1550245"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Ernesto Galan"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1550249"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Joan Verdu"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1550251"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_22572"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "Raul Rodriguez"
:event/player1 "Jonas"
:event/sortorder 5
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1550257"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Joaquin"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1550265"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_22572"}

{:event/type "shoton"
:event/elapsed 18
:event/subtype "distance"
:event/player1 "Joan Verdu"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_1550270"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_22572"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Ivan Alonso"
:event/player1 "Mehmet Topal"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1550279"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_22572"}

{:event/type "goal"
:event/elapsed 19
:event/player2 "Luis Garcia"
:event/subtype "shot"
:event/player1 "Pablo Osvaldo"
:event/sortorder 6
:event/team "home"
:event/id "event_1550274"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_22572"}

{:event/type "shoton"
:event/elapsed 22
:event/subtype "distance"
:event/player1 "Ever Banega"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1550308"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_22572"}

{:event/type "shoton"
:event/elapsed 22
:event/subtype "volley"
:event/player1 "Joaquin"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1550309"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_22572"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Jeremy Mathieu"
:event/player1 "Javi Lopez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1550318"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_22572"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Ever Banega"
:event/player1 "Jose Maria Callejon"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1550326"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Bruno Saltor"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1550335"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_22572"}

{:event/type "goal"
:event/elapsed 25
:event/player2 "Bruno Saltor"
:event/subtype "shot"
:event/player1 "Juan Mata"
:event/sortorder 3
:event/team "away"
:event/id "event_1550330"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Luis Garcia"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1550342"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_22572"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Luis Garcia"
:event/player1 "Juan Mata"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1550348"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_22572"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Jonas"
:event/player1 "Javi Lopez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1550352"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_22572"}

{:event/type "corner"
:event/elapsed 28
:event/subtype "short"
:event/player1 "Joaquin"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1550359"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Joaquin"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1550362"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_22572"}

{:event/type "corner"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Joaquin"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1550362"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Roberto Soldado"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1550376"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Javi Lopez"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1550393"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Jose Maria Callejon"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_1550396"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Luis Garcia"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1550405"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_22572"}

{:event/type "corner"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Luis Garcia"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1550405"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Roberto Soldado"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1550409"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_22572"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Javi Lopez"
:event/player1 "Mehmet Topal"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1550423"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_22572"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Mehmet Topal"
:event/player1 "Ivan Alonso"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1550425"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_22572"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Luis Garcia"
:event/player1 "Bruno Saltor"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1550426"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_22572"}

{:event/type "corner"
:event/elapsed 36
:event/subtype "short"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1550432"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_22572"}

{:event/type "shotoff"
:event/elapsed 36
:event/subtype "bicycle_kick"
:event/player1 "Pablo Osvaldo"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1550433"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Jose Maria Callejon"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1550443"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_22572"}

{:event/type "shoton"
:event/elapsed 40
:event/subtype "distance"
:event/player1 "Francisco Chica"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1550450"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_22572"}

{:event/type "card"
:event/elapsed 42
:event/card_type "y"
:event/player1 "Jordi Amat"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_1550460"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Joan Verdu"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1550471"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_22572"}

{:event/type "corner"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Joan Verdu"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1550471"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Luis Garcia"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_1550474"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Ever Banega"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1550479"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_22572"}

{:event/type "shotoff"
:event/elapsed 49
:event/subtype "distance"
:event/player1 "Joan Verdu"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1550552"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_22572"}

{:event/type "shotoff"
:event/elapsed 50
:event/subtype "shot"
:event/player1 "Pablo Osvaldo"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1550557"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Jose Maria Callejon"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1550563"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_22572"}

{:event/type "shotoff"
:event/elapsed 51
:event/subtype "volley"
:event/player1 "Luis Garcia"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1550564"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_22572"}

{:event/type "card"
:event/elapsed 52
:event/card_type "y"
:event/subtype "stall_time"
:event/player1 "Cesar Sanchez"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1550571"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_22572"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Javi Lopez"
:event/subtype "pushing"
:event/player1 "Mehmet Topal"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1550576"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Francisco Chica"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1550579"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_22572"}

{:event/type "shotoff"
:event/elapsed 53
:event/subtype "shot"
:event/player1 "Roberto Soldado"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1550584"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_22572"}

{:event/type "shoton"
:event/elapsed 54
:event/subtype "blocked_shot"
:event/player1 "Jose Maria Callejon"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1550591"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Juan Mata"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1550594"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Bruno Saltor"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1550607"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Joaquin"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1550610"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_22572"}

{:event/type "corner"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Joaquin"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1550610"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_22572"}

{:event/type "shotoff"
:event/elapsed 56
:event/subtype "header"
:event/player1 "David Navarro"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1550613"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_22572"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Joan Verdu"
:event/subtype "from_behind"
:event/player1 "Mehmet Topal"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1550616"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_22572"}

{:event/type "shoton"
:event/elapsed 57
:event/subtype "distance"
:event/player1 "Francisco Chica"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1550620"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_22572"}

{:event/type "corner"
:event/elapsed 58
:event/subtype "short"
:event/player1 "Jose Maria Callejon"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1550626"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Ernesto Galan"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1550629"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_22572"}

{:event/type "card"
:event/elapsed 61
:event/card_type "y"
:event/subtype "stall_time"
:event/player1 "Roberto Soldado"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1550648"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_22572"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Pablo Osvaldo"
:event/subtype "from_behind"
:event/player1 "Ever Banega"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1550667"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_22572"}

{:event/type "shotoff"
:event/elapsed 64
:event/subtype "direct_freekick"
:event/player1 "Javi Moreno Marquez"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1550669"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Joan Verdu"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1550681"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_22572"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Joaquin"
:event/subtype "from_behind"
:event/player1 "Alvaro Vazquez"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1550683"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Francisco Chica"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1550701"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_22572"}

{:event/type "shotoff"
:event/elapsed 68
:event/subtype "header"
:event/player1 "Alvaro Vazquez"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1550704"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_22572"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Jeremy Mathieu"
:event/subtype "from_behind"
:event/player1 "Luis Garcia"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1550706"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_22572"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Javi Moreno Marquez"
:event/subtype "from_behind"
:event/player1 "Ever Banega"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1550717"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_22572"}

{:event/type "card"
:event/elapsed 71
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Ever Banega"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1550718"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Juan Mata"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1550721"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_22572"}

{:event/type "shotoff"
:event/elapsed 72
:event/subtype "header"
:event/player1 "Joaquin"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1550723"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_22572"}

{:event/type "shotoff"
:event/elapsed 73
:event/subtype "shot"
:event/player1 "Joaquin"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1550733"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_22572"}

{:event/type "foulcommit"
:event/elapsed 74
:event/player2 "Alvaro Vazquez"
:event/subtype "pushing"
:event/player1 "Miguel"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1550740"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_22572"}

{:event/type "shoton"
:event/elapsed 76
:event/subtype "shot"
:event/player1 "Luis Garcia"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1550752"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_22572"}

{:event/type "goal"
:event/elapsed 76
:event/subtype "shot"
:event/player1 "Ernesto Galan"
:event/sortorder 2
:event/team "home"
:event/id "event_1550753"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_22572"}

{:event/type "shoton"
:event/elapsed 78
:event/subtype "shot"
:event/player1 "Pablo Osvaldo"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_1550767"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_22572"}

{:event/type "shotoff"
:event/elapsed 80
:event/subtype "shot"
:event/player1 "Juan Mata"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1550783"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_22572"}

{:event/type "foulcommit"
:event/elapsed 81
:event/subtype "hands"
:event/player1 "Ever Banega"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1550790"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Jordi Alba"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_1550802"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_22572"}

{:event/type "shotoff"
:event/elapsed 83
:event/subtype "deflected"
:event/player1 "Javi Lopez"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1550806"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Javi Moreno Marquez"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1550811"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_22572"}

{:event/type "corner"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Javi Moreno Marquez"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1550811"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_22572"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Roberto Soldado"
:event/subtype "from_behind"
:event/player1 "Javi Lopez"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1550815"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_22572"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Roberto Soldado"
:event/subtype "from_behind"
:event/player1 "Rui Fonte"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1550840"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_22572"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Rui Fonte"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_1550842"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Mehmet Topal"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1550846"
:event/minute 91
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Jeremy Mathieu"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_1550850"
:event/minute 91
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Miguel"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1550852"
:event/minute 92
:event/match_id "match_22572"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Joaquin"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1550857"
:event/minute 92
:event/match_id "match_22572"}

{:event/type "corner"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Joaquin"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1550857"
:event/minute 92
:event/match_id "match_22572"}

{:event/type "shoton"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Ever Banega"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1550863"
:event/minute 93
:event/match_id "match_22572"}


]

