
;;# data
[
{:match/id "match_22093"
:match/league "Spain LIGA BBVA"
:match/hometeam "Athletic Club de Bilbao"
:match/awayteam "Getafe CF"
:match/score "2:2"
:match/hometeam_goals "2"
:match/awayteam_goals "2"}

{:event/type "goal"
:event/elapsed 13
:event/player1 "Pablo Orbaiz"
:event/sortorder 0
:event/team "home"
:event/id "event_1004511"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_22093"}

{:event/type "goal"
:event/elapsed 32
:event/player1 "Manu del Moral"
:event/sortorder 0
:event/team "away"
:event/id "event_1004662"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_22093"}

{:event/type "card"
:event/elapsed 37
:event/card_type "y"
:event/player1 "Manu del Moral"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1004705"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_22093"}

{:event/type "card"
:event/elapsed 37
:event/card_type "y"
:event/player1 "David Cortes"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1004721"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_22093"}

{:event/type "card"
:event/elapsed 38
:event/card_type "r"
:event/player1 "Pablo Orbaiz"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1004746"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_22093"}

{:event/type "card"
:event/elapsed 59
:event/card_type "y"
:event/player1 "Carlos Gurpegi"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1005001"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_22093"}

{:event/type "card"
:event/elapsed 63
:event/card_type "y"
:event/player1 "Rafa Lopez"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1005042"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_22093"}

{:event/type "card"
:event/elapsed 76
:event/card_type "y"
:event/player1 "Miguel Torres"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1005171"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_22093"}

{:event/type "goal"
:event/elapsed 80
:event/player1 "Fernando Llorente"
:event/sortorder 0
:event/team "home"
:event/id "event_1005124"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_22093"}

{:event/type "card"
:event/elapsed 81
:event/card_type "r"
:event/player1 "Miguel Torres"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1005172"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_22093"}

{:event/type "goal"
:event/elapsed 86
:event/player1 "Pedro Leon"
:event/sortorder 0
:event/team "away"
:event/id "event_1005202"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_22093"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Derek Boateng"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1005250"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_22093"}


]

