
;;# data
[
{:match/id "match_22905"
:match/league "Spain LIGA BBVA"
:match/hometeam "FC Barcelona"
:match/awayteam "Athletic Club de Bilbao"
:match/score "2:0"
:match/hometeam_goals "2"
:match/awayteam_goals "0"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Lionel Messi"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2025115"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_22905"}

{:event/type "corner"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Lionel Messi"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2025115"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_22905"}

{:event/type "shoton"
:event/elapsed 5
:event/subtype "distance"
:event/player1 "Daniel Alves"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_2025116"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_22905"}

{:event/type "shotoff"
:event/elapsed 6
:event/subtype "big chance shot"
:event/player1 "Gerard Pique"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2025117"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_22905"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Andres Iniesta"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2025128"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_22905"}

{:event/type "corner"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Andres Iniesta"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2025128"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_22905"}

{:event/type "shotoff"
:event/elapsed 9
:event/subtype "distance"
:event/player1 "Daniel Alves"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2025129"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_22905"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Andres Iniesta"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2025158"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_22905"}

{:event/type "corner"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Andres Iniesta"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2025158"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_22905"}

{:event/type "shoton"
:event/elapsed 15
:event/subtype "blocked_shot"
:event/player1 "Lionel Messi"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_2025146"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_22905"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Lionel Messi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2025157"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_22905"}

{:event/type "corner"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Lionel Messi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2025157"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_22905"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Lionel Messi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2025160"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_22905"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Markel Susaeta"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2025164"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_22905"}

{:event/type "corner"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Markel Susaeta"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2025164"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_22905"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player1 "Javier Martinez"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2025165"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_22905"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Lionel Messi"
:event/player1 "Javier Martinez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2025166"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_22905"}

{:event/type "shotoff"
:event/elapsed 24
:event/subtype "distance"
:event/player1 "Adriano"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2025169"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_22905"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Lionel Messi"
:event/player1 "Borja Ekiza"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2025173"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_22905"}

{:event/type "shoton"
:event/elapsed 25
:event/subtype "direct_freekick"
:event/player1 "Lionel Messi"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_2025176"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_22905"}

{:event/type "corner"
:event/elapsed 25
:event/subtype "short"
:event/player1 "Andres Iniesta"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2025179"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_22905"}

{:event/type "shoton"
:event/elapsed 26
:event/subtype "header"
:event/player1 "Gerard Pique"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_2025180"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_22905"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Daniel Alves"
:event/player1 "Gaizka Toquero"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2025183"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_22905"}

{:event/type "shotoff"
:event/elapsed 28
:event/subtype "big chance shot"
:event/player1 "Andres Iniesta"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2025189"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_22905"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Lionel Messi"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2025192"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_22905"}

{:event/type "corner"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Lionel Messi"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2025192"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_22905"}

{:event/type "shoton"
:event/elapsed 29
:event/subtype "header"
:event/player1 "Sergio Busquets"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_2025193"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_22905"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Alexis Sanchez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2025203"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_22905"}

{:event/type "shoton"
:event/elapsed 32
:event/subtype "shot"
:event/player1 "Daniel Alves"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_2025206"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_22905"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Sergio Busquets"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2025215"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_22905"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Lionel Messi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2025228"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_22905"}

{:event/type "corner"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Lionel Messi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2025228"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_22905"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Alexis Sanchez"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2025230"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_22905"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player1 "Gerard Pique"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2025231"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_22905"}

{:event/type "goal"
:event/elapsed 40
:event/player2 "Lionel Messi"
:event/subtype "shot"
:event/player1 "Andres Iniesta"
:event/sortorder 0
:event/team "home"
:event/id "event_2025243"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_22905"}

{:event/type "shoton"
:event/elapsed 42
:event/subtype "shot"
:event/player1 "Lionel Messi"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_2025245"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_22905"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Markel Susaeta"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2025247"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_22905"}

{:event/type "corner"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Markel Susaeta"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2025247"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_22905"}

{:event/type "foulcommit"
:event/elapsed 47
:event/player1 "Adriano"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2025267"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_22905"}

{:event/type "shoton"
:event/elapsed 50
:event/subtype "blocked_shot"
:event/player1 "Lionel Messi"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_2025272"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_22905"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player1 "Gaizka Toquero"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2025274"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_22905"}

{:event/type "card"
:event/elapsed 52
:event/card_type "y"
:event/player1 "Gaizka Toquero"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_2025275"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_22905"}

{:event/type "shoton"
:event/elapsed 55
:event/subtype "shot"
:event/player1 "Cristian Tello Herrera"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_2025278"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_22905"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Andres Iniesta"
:event/subtype "serious_foul"
:event/player1 "Ander Iturraspe"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2025280"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_22905"}

{:event/type "card"
:event/elapsed 56
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Ander Iturraspe"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_2025281"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_22905"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Andres Iniesta"
:event/player1 "Oscar de Marcos"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2025282"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_22905"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Cristian Tello Herrera"
:event/subtype "penalty"
:event/player1 "Javier Martinez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2025283"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_22905"}

{:event/type "card"
:event/elapsed 58
:event/card_type "y"
:event/player1 "Javier Martinez"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_2025284"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_22905"}

{:event/type "goal"
:event/elapsed 58
:event/player1 "Lionel Messi"
:event/sortorder 2
:event/team "home"
:event/id "event_2025285"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_22905"}

{:event/type "shotoff"
:event/elapsed 63
:event/subtype "deflected"
:event/player1 "Pedro Rodriguez"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2025293"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_22905"}

{:event/type "foulcommit"
:event/elapsed 66
:event/player1 "Sergio Busquets"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2025300"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_22905"}

{:event/type "card"
:event/elapsed 66
:event/card_type "y"
:event/player1 "Sergio Busquets"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_2025301"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_22905"}

{:event/type "shoton"
:event/elapsed 68
:event/subtype "deflected"
:event/player1 "Andres Iniesta"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_2025304"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_22905"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Lionel Messi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2025305"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_22905"}

{:event/type "corner"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Lionel Messi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2025305"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_22905"}

{:event/type "shoton"
:event/elapsed 69
:event/subtype "header"
:event/player1 "Gerard Pique"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_2025306"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_22905"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player1 "Lionel Messi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2025309"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_22905"}

{:event/type "shoton"
:event/elapsed 74
:event/subtype "shot"
:event/player1 "Lionel Messi"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_2025312"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_22905"}

{:event/type "foulcommit"
:event/elapsed 76
:event/player2 "Thiago Alcantara"
:event/player1 "Markel Susaeta"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2025313"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_22905"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Lionel Messi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2025316"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_22905"}

{:event/type "corner"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Lionel Messi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2025316"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_22905"}

{:event/type "shoton"
:event/elapsed 80
:event/subtype "shot"
:event/player1 "Iker Muniain"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_2025319"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_22905"}

{:event/type "corner"
:event/elapsed 80
:event/subtype "short"
:event/player1 "Markel Susaeta"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_2025322"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_22905"}

{:event/type "shotoff"
:event/elapsed 80
:event/subtype "shot"
:event/player1 "Ander Iturraspe"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2025323"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_22905"}

{:event/type "shotoff"
:event/elapsed 82
:event/subtype "deflected"
:event/player1 "Iker Muniain"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2025327"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_22905"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Iker Muniain"
:event/player1 "Seydou Keita"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2025329"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_22905"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Lionel Messi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2025332"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_22905"}

{:event/type "corner"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Lionel Messi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2025332"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_22905"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Adriano"
:event/player1 "Iker Muniain"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2025334"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_22905"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Gerard Pique"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2025335"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_22905"}

{:event/type "shotoff"
:event/elapsed 90
:event/subtype "crossbar"
:event/player1 "Seydou Keita"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2025337"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_22905"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Pedro Rodriguez"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_2025341"
:event/minute 91
:event/match_id "match_22905"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player1 "Pedro Rodriguez"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2025342"
:event/minute 91
:event/match_id "match_22905"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Ander Iturraspe"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_2025347"
:event/minute 92
:event/match_id "match_22905"}


]

