
;;# data
[
{:match/id "match_3718"
:match/league "England Premier League"
:match/hometeam "West Bromwich Albion"
:match/awayteam "Hull City"
:match/score "1:1"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Scott Sinclair"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3179013"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_3718"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "Yannick Sagbo"
:event/player1 "Gareth McAuley"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3179038"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_3718"}

{:event/type "foulcommit"
:event/elapsed 5
:event/subtype "pushing"
:event/player1 "Yannick Sagbo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3179051"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Liam Ridgewell"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3179052"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3179060"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_3718"}

{:event/type "corner"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3179060"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "James Morrison"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_3179079"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_3179088"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Alex Bruce"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3179092"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Ahmed El Mohamady"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3179104"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3179110"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_3718"}

{:event/type "corner"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3179110"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_3718"}

{:event/type "shotoff"
:event/elapsed 10
:event/subtype "header"
:event/player1 "James Chester"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3179117"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_3718"}

{:event/type "foulcommit"
:event/elapsed 16
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3179193"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Jake Livermore"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3179245"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_3718"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Daniel Graham"
:event/subtype "pushing"
:event/player1 "Chris Brunt"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3179269"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3179270"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_3718"}

{:event/type "foulcommit"
:event/elapsed 22
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3179273"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_3718"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Liam Ridgewell"
:event/subtype "obstruction"
:event/player1 "Ahmed El Mohamady"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3179280"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_3179281"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Yannick Sagbo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3179306"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_3718"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Stephane Sessegnon"
:event/subtype "obstruction"
:event/player1 "Maynor Figueroa"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3179316"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Billy Jones"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3179323"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_3718"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Youssuf Mulumbu"
:event/subtype "pull"
:event/player1 "David Meyler"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3179337"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Billy Jones"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3179343"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3179345"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_3718"}

{:event/type "corner"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3179345"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_3718"}

{:event/type "goal"
:event/elapsed 28
:event/player2 "Daniel Graham"
:event/subtype "shot"
:event/player1 "Jake Livermore"
:event/sortorder 11
:event/team "away"
:event/id "event_3179355"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Daniel Graham"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3179389"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_3718"}

{:event/type "foulcommit"
:event/elapsed 32
:event/subtype "pull"
:event/player1 "Gareth McAuley"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3179408"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Maynor Figueroa"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3179454"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_3718"}

{:event/type "shotoff"
:event/elapsed 35
:event/subtype "deflected"
:event/player1 "David Meyler"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3179460"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_3179462"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_3718"}

{:event/type "corner"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_3179462"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Youssuf Mulumbu"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3179471"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3179480"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_3718"}

{:event/type "corner"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3179480"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_3718"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Liam Ridgewell"
:event/subtype "pushing"
:event/player1 "Yannick Sagbo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3179493"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_3718"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Scott Sinclair"
:event/subtype "from_behind"
:event/player1 "James Chester"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3179501"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3179503"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3179508"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_3718"}

{:event/type "corner"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3179508"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_3718"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Jonas Olsson"
:event/subtype "pushing"
:event/player1 "David Meyler"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3179515"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_3718"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Youssuf Mulumbu"
:event/subtype "from_behind"
:event/player1 "David Meyler"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3179526"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_3718"}

{:event/type "card"
:event/elapsed 40
:event/card_type "y"
:event/player1 "David Meyler"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_3179528"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_3718"}

{:event/type "foulcommit"
:event/elapsed 42
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3179553"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Liam Ridgewell"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3179583"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_3718"}

{:event/type "shotoff"
:event/elapsed 44
:event/subtype "bad shot"
:event/player1 "James Morrison"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3179585"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_3718"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Billy Jones"
:event/subtype "trip"
:event/player1 "Tom Huddlestone"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3179586"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3179606"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_3718"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "blocked_shot"
:event/player1 "Billy Jones"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_3179614"
:event/minute 46
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Stephane Sessegnon"
:event/sortorder 6
:event/team "home"
:event/event_type "cross"
:event/id "event_3179635"
:event/minute 47
:event/match_id "match_3718"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "James Morrison"
:event/subtype "dangerous_play"
:event/player1 "Jake Livermore"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3179688"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Yannick Sagbo"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_3179732"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_3718"}

{:event/type "foulcommit"
:event/elapsed 51
:event/subtype "hands"
:event/player1 "Maynor Figueroa"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3179748"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3179752"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Liam Ridgewell"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3179756"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Billy Jones"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3179779"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_3718"}

{:event/type "shoton"
:event/elapsed 55
:event/subtype "big chance shot"
:event/player1 "Stephane Sessegnon"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3179792"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3179795"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3718"}

{:event/type "corner"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3179795"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3718"}

{:event/type "shoton"
:event/elapsed 55
:event/subtype "blocked_shot"
:event/player1 "Youssuf Mulumbu"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_3179797"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_3179798"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3718"}

{:event/type "corner"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_3179798"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3718"}

{:event/type "shoton"
:event/elapsed 55
:event/subtype "blocked_shot"
:event/player1 "Chris Brunt"
:event/sortorder 5
:event/team "home"
:event/event_type "shoton"
:event/id "event_3179803"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3718"}

{:event/type "shotoff"
:event/elapsed 56
:event/subtype "shot"
:event/player1 "Shane Long"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3179809"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3179858"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_3718"}

{:event/type "corner"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3179858"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_3718"}

{:event/type "shoton"
:event/elapsed 60
:event/subtype "header"
:event/player1 "Gareth McAuley"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3179861"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3179888"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Liam Ridgewell"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3179905"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3718"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Maynor Figueroa"
:event/subtype "trip"
:event/player1 "Billy Jones"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3179929"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_3718"}

{:event/type "card"
:event/elapsed 64
:event/card_type "y"
:event/player1 "Billy Jones"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_3179937"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Maynor Figueroa"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3179948"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Yannick Sagbo"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3179981"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3718"}

{:event/type "shoton"
:event/elapsed 68
:event/subtype "shot"
:event/player1 "Tom Huddlestone"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3179983"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_3718"}

{:event/type "shoton"
:event/elapsed 68
:event/subtype "big chance shot"
:event/player1 "Ahmed El Mohamady"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3179984"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_3718"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Billy Jones"
:event/player1 "Yannick Sagbo"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3180026"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_3718"}

{:event/type "foulcommit"
:event/elapsed 72
:event/player2 "Matej Vydra"
:event/subtype "pull"
:event/player1 "Tom Huddlestone"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3180040"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_3718"}

{:event/type "shotoff"
:event/elapsed 72
:event/subtype "distance"
:event/player1 "James Morrison"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3180049"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3180060"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_3718"}

{:event/type "corner"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3180060"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_3718"}

{:event/type "shotoff"
:event/elapsed 74
:event/subtype "header"
:event/player1 "Saido Berahino"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3180062"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_3718"}

{:event/type "shoton"
:event/elapsed 75
:event/subtype "blocked_shot"
:event/player1 "Saido Berahino"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3180078"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3180082"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3718"}

{:event/type "corner"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3180082"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3180085"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Shane Long"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3180118"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_3718"}

{:event/type "foulcommit"
:event/elapsed 79
:event/player2 "Jake Livermore"
:event/subtype "trip"
:event/player1 "James Morrison"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3180164"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_3718"}

{:event/type "foulcommit"
:event/elapsed 83
:event/player2 "Youssuf Mulumbu"
:event/subtype "from_behind"
:event/player1 "Alex Bruce"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3180174"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3180175"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_3718"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "David Meyler"
:event/subtype "from_behind"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3180200"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_3718"}

{:event/type "foulcommit"
:event/elapsed 86
:event/subtype "pushing"
:event/player1 "Maynor Figueroa"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3180209"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3718"}

{:event/type "goal"
:event/elapsed 86
:event/player2 "Zoltan Gera"
:event/subtype "shot"
:event/player1 "Matej Vydra"
:event/sortorder 11
:event/team "home"
:event/id "event_3180213"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3718"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Maynor Figueroa"
:event/subtype "from_behind"
:event/player1 "Zoltan Gera"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3180235"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_3718"}

{:event/type "card"
:event/elapsed 88
:event/card_type "y"
:event/player1 "Zoltan Gera"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_3180236"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_3718"}

{:event/type "shotoff"
:event/elapsed 89
:event/subtype "direct_freekick"
:event/player1 "Tom Huddlestone"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3180248"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_3718"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Gareth McAuley"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3180268"
:event/minute 91
:event/match_id "match_3718"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "bad shot"
:event/player1 "Saido Berahino"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3180270"
:event/minute 91
:event/match_id "match_3718"}


]

