
;;# data
[
{:match/id "match_6627"
:match/league "France Ligue 1"
:match/hometeam "ES Troyes AC"
:match/awayteam "LOSC Lille"
:match/score "1:1"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "goal"
:event/elapsed 38
:event/player1 "Dimitri Payet"
:event/sortorder 0
:event/team "away"
:event/id "event_2349314"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_6627"}

{:event/type "card"
:event/elapsed 69
:event/card_type "y"
:event/player1 "Benoit Pedretti"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2349670"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_6627"}

{:event/type "card"
:event/elapsed 80
:event/card_type "y"
:event/player1 "Fabien Camus"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2349736"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_6627"}

{:event/type "goal"
:event/elapsed 88
:event/player1 "Sebastien Grax"
:event/sortorder 0
:event/team "home"
:event/id "event_2349735"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_6627"}


]

