
;;# data
[
{:match/id "match_4061"
:match/league "England Premier League"
:match/hometeam "Leicester City"
:match/awayteam "Liverpool"
:match/score "0:4"
:match/hometeam_goals "1"
:match/awayteam_goals "3"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Rickie Lambert"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3982347"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_4061"}

{:event/type "corner"
:event/elapsed 5
:event/subtype "cross_left"
:event/player1 "Jamie Vardy"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3982380"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_4061"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Raheem Sterling"
:event/player1 "Ritchie De Laet"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3982416"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3982426"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_4061"}

{:event/type "shotoff"
:event/elapsed 8
:event/subtype "header"
:event/player1 "Martin Skrtel"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3982429"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_4061"}

{:event/type "shoton"
:event/elapsed 9
:event/subtype "blocked_shot"
:event/player1 "Adam Lallana"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3982438"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_4061"}

{:event/type "shoton"
:event/elapsed 9
:event/subtype "blocked_shot"
:event/player1 "Lucas Leiva"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3982440"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_4061"}

{:event/type "shotoff"
:event/elapsed 9
:event/subtype "distance"
:event/player1 "Jamie Vardy"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3982444"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Ritchie De Laet"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_3982473"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_4061"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Adam Lallana"
:event/player1 "Jeffrey Schlupp"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3982475"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Rickie Lambert"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3982506"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_4061"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Jeffrey Schlupp"
:event/subtype "obstruction"
:event/player1 "Lucas Leiva"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3982515"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Jeffrey Schlupp"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3982521"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_4061"}

{:event/type "corner"
:event/elapsed 18
:event/subtype "cross_left"
:event/player1 "Matthew James"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3982529"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_4061"}

{:event/type "shoton"
:event/elapsed 18
:event/subtype "blocked_shot"
:event/player1 "Jeffrey Schlupp"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_3982532"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Matthew James"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_3982535"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_4061"}

{:event/type "shotoff"
:event/elapsed 20
:event/subtype "distance"
:event/player1 "Esteban Cambiasso"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3982559"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Riyad Mahrez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3982573"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_4061"}

{:event/type "shoton"
:event/elapsed 21
:event/subtype "big chance shot"
:event/player1 "Jamie Vardy"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_3982595"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_4061"}

{:event/type "shotoff"
:event/elapsed 21
:event/subtype "big chance post"
:event/player1 "Jose Leonardo Ulloa"
:event/sortorder 9
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3982619"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_4061"}

{:event/type "goal"
:event/elapsed 22
:event/player1 "Simon Mignolet"
:event/sortorder 0
:event/team "away"
:event/id "event_3982582"
:event/event_type "goal"
:event/goal_type "o"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_4061"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Jordan Henderson"
:event/player1 "Matthew James"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3982614"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3982624"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_4061"}

{:event/type "corner"
:event/elapsed 25
:event/subtype "cross_left"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3982631"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_4061"}

{:event/type "shotoff"
:event/elapsed 25
:event/subtype "distance"
:event/player1 "Glen Johnson"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3982635"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_4061"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Raheem Sterling"
:event/player1 "Riyad Mahrez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3982642"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3982656"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Lucas Leiva"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3982662"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_4061"}

{:event/type "goal"
:event/elapsed 27
:event/subtype "shot"
:event/player1 "Adam Lallana"
:event/sortorder 4
:event/team "away"
:event/id "event_3982666"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_4061"}

{:event/type "corner"
:event/elapsed 30
:event/subtype "cross_left"
:event/player1 "Matthew James"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3982704"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_4061"}

{:event/type "shotoff"
:event/elapsed 30
:event/subtype "header"
:event/player1 "Marcin Wasilewski"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3982706"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Jordan Henderson"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3982748"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_4061"}

{:event/type "corner"
:event/elapsed 33
:event/subtype "cross_right"
:event/player1 "Steven Gerrard"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3982760"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_4061"}

{:event/type "shoton"
:event/elapsed 33
:event/subtype "blocked_header"
:event/player1 "Martin Skrtel"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_3982763"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_3982766"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_4061"}

{:event/type "shoton"
:event/elapsed 36
:event/subtype "volley"
:event/player1 "Riyad Mahrez"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3982815"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_4061"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Paul Konchesky"
:event/player1 "Adam Lallana"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3982821"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_4061"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Jamie Vardy"
:event/subtype "serious_foul"
:event/player1 "Adam Lallana"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3982852"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_4061"}

{:event/type "card"
:event/elapsed 38
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Adam Lallana"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_3982855"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Matthew James"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3982864"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_4061"}

{:event/type "foulcommit"
:event/elapsed 39
:event/subtype "hands"
:event/player1 "Raheem Sterling"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3982868"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Javier Manquillo"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_3982955"
:event/minute 46
:event/match_id "match_4061"}

{:event/type "corner"
:event/elapsed 46
:event/subtype "cross_right"
:event/player1 "Matthew James"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_3983092"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Matthew James"
:event/sortorder 6
:event/team "home"
:event/event_type "cross"
:event/id "event_3983096"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Jamie Vardy"
:event/sortorder 7
:event/team "home"
:event/event_type "cross"
:event/id "event_3983097"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_4061"}

{:event/type "corner"
:event/elapsed 47
:event/subtype "cross_right"
:event/player1 "Matthew James"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3983099"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Matthew James"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3983101"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_4061"}

{:event/type "shotoff"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "distance"
:event/player1 "Matthew James"
:event/sortorder 7
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3982977"
:event/minute 47
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Jeffrey Schlupp"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3983114"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Ritchie De Laet"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3983133"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_4061"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Marcin Wasilewski"
:event/subtype "pushing"
:event/player1 "Rickie Lambert"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3983153"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_4061"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Steven Gerrard"
:event/player1 "Jamie Vardy"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3983161"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Raheem Sterling"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3983163"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_4061"}

{:event/type "goal"
:event/elapsed 54
:event/subtype "shot"
:event/player1 "Steven Gerrard"
:event/sortorder 3
:event/team "away"
:event/id "event_3983164"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Jeffrey Schlupp"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3983175"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_4061"}

{:event/type "shotoff"
:event/elapsed 56
:event/subtype "distance"
:event/player1 "Jose Leonardo Ulloa"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3983180"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_4061"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Alberto Moreno"
:event/player1 "Riyad Mahrez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3983193"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_4061"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Raheem Sterling"
:event/player1 "Riyad Mahrez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3983203"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3983204"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_4061"}

{:event/type "shotoff"
:event/elapsed 59
:event/subtype "distance"
:event/player1 "Jordan Henderson"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3983214"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_4061"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Jamie Vardy"
:event/player1 "Lucas Leiva"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3983226"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Matthew James"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3983229"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Jeffrey Schlupp"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3983231"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_4061"}

{:event/type "shotoff"
:event/elapsed 62
:event/subtype "distance"
:event/player1 "Marcin Wasilewski"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3983232"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_4061"}

{:event/type "shotoff"
:event/elapsed 63
:event/subtype "distance"
:event/player1 "Raheem Sterling"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3983243"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_4061"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Rickie Lambert"
:event/player1 "Wes Morgan"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3983255"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_4061"}

{:event/type "card"
:event/elapsed 64
:event/card_type "r"
:event/subtype "emergency_brake"
:event/player1 "Wes Morgan"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3983264"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3983278"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_4061"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Matthew James"
:event/player1 "Steven Gerrard"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3983282"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_4061"}

{:event/type "card"
:event/elapsed 65
:event/card_type "y"
:event/subtype "emergency_brake"
:event/player1 "Steven Gerrard"
:event/sortorder 4
:event/team "away"
:event/event_type "card"
:event/id "event_3983287"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_4061"}

{:event/type "shotoff"
:event/elapsed 66
:event/subtype "direct_freekick"
:event/player1 "Riyad Mahrez"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3983292"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_4061"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Riyad Mahrez"
:event/player1 "Lucas Leiva"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3983326"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_4061"}

{:event/type "shoton"
:event/elapsed 68
:event/subtype "blocked_shot"
:event/player1 "Matthew James"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3983329"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Riyad Mahrez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3983338"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_4061"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Raheem Sterling"
:event/player1 "Riyad Mahrez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3983367"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Esteban Cambiasso"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_3983430"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_4061"}

{:event/type "shoton"
:event/elapsed 74
:event/subtype "big chance shot"
:event/player1 "Riyad Mahrez"
:event/sortorder 5
:event/team "home"
:event/event_type "shoton"
:event/id "event_3983434"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_4061"}

{:event/type "shoton"
:event/elapsed 75
:event/subtype "blocked_shot"
:event/player1 "Esteban Cambiasso"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3983437"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_4061"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Jordan Henderson"
:event/player1 "Jeffrey Schlupp"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3983447"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_4061"}

{:event/type "card"
:event/elapsed 75
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Jeffrey Schlupp"
:event/sortorder 3
:event/team "home"
:event/event_type "card"
:event/id "event_3983450"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Joe Allen"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3983474"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_4061"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Jamie Vardy"
:event/player1 "Lucas Leiva"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3983485"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Matthew James"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3983489"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_4061"}

{:event/type "foulcommit"
:event/elapsed 78
:event/player2 "Riyad Mahrez"
:event/player1 "Alberto Moreno"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3983493"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Matthew James"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_3983500"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_4061"}

{:event/type "shoton"
:event/elapsed 79
:event/subtype "blocked_shot"
:event/player1 "Jamie Vardy"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3983506"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_4061"}

{:event/type "corner"
:event/elapsed 79
:event/subtype "cross_right"
:event/player1 "Matthew James"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3983509"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_4061"}

{:event/type "shoton"
:event/elapsed 79
:event/subtype "blocked_shot"
:event/player1 "Jeffrey Schlupp"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_3983519"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Matthew James"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3983541"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Jamie Vardy"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3983546"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_4061"}

{:event/type "corner"
:event/elapsed 83
:event/subtype "cross_right"
:event/player1 "Jordan Henderson"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3983556"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_4061"}

{:event/type "shoton"
:event/elapsed 83
:event/subtype "blocked_shot"
:event/player1 "Martin Skrtel"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3983559"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Joe Allen"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3983564"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_3983571"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_4061"}

{:event/type "goal"
:event/elapsed 84
:event/player2 "Raheem Sterling"
:event/subtype "shot"
:event/player1 "Jordan Henderson"
:event/sortorder 0
:event/team "away"
:event/id "event_3983574"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_4061"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Raheem Sterling"
:event/player1 "Matthew James"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3983606"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_4061"}

{:event/type "shoton"
:event/elapsed 88
:event/subtype "blocked_shot"
:event/player1 "Riyad Mahrez"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3983634"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_4061"}

{:event/type "shoton"
:event/elapsed 88
:event/subtype "blocked_shot"
:event/player1 "Matthew James"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3983646"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_4061"}

{:event/type "corner"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross_right"
:event/player1 "Marc Albrighton"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3983685"
:event/minute 91
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Matthew James"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_3983690"
:event/minute 91
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Marc Albrighton"
:event/sortorder 6
:event/team "home"
:event/event_type "cross"
:event/id "event_3983693"
:event/minute 91
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Marc Albrighton"
:event/sortorder 9
:event/team "home"
:event/event_type "cross"
:event/id "event_3983706"
:event/minute 92
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Riyad Mahrez"
:event/sortorder 12
:event/team "home"
:event/event_type "cross"
:event/id "event_3983716"
:event/minute 92
:event/match_id "match_4061"}

{:event/type "corner"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "short_left"
:event/player1 "Steven Gerrard"
:event/sortorder 16
:event/team "away"
:event/event_type "corner"
:event/id "event_3983756"
:event/minute 95
:event/match_id "match_4061"}

{:event/type "cross"
:event/elapsed_plus 6
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Marc Albrighton"
:event/sortorder 18
:event/team "home"
:event/event_type "cross"
:event/id "event_3983759"
:event/minute 96
:event/match_id "match_4061"}

{:event/type "shoton"
:event/elapsed_plus 6
:event/elapsed 90
:event/subtype "header"
:event/player1 "Jose Leonardo Ulloa"
:event/sortorder 19
:event/team "home"
:event/event_type "shoton"
:event/id "event_3983761"
:event/minute 96
:event/match_id "match_4061"}


]

