
;;# data
[
{:match/id "match_3222"
:match/league "England Premier League"
:match/hometeam "Everton"
:match/awayteam "Liverpool"
:match/score "0:3"
:match/hometeam_goals "0"
:match/awayteam_goals "2"}

{:event/type "foulcommit"
:event/elapsed 1
:event/player2 "Stewart Downing"
:event/player1 "Tony Hibbert"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1688474"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Charlie Adam"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1688475"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_3222"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Tim Cahill"
:event/subtype "pushing"
:event/player1 "Martin Kelly"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1688480"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_3222"}

{:event/type "shotoff"
:event/elapsed 3
:event/subtype "deflected"
:event/player1 "Marouane Fellaini"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1688484"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_1688485"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_3222"}

{:event/type "corner"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_1688485"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Jose Enrique"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1688488"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_3222"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Jamie Carragher"
:event/player1 "Tim Cahill"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1688492"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Luis Suarez"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_1688500"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Dirk Kuyt"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1688510"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3222"}

{:event/type "shoton"
:event/elapsed 9
:event/subtype "big chance header"
:event/player1 "Luis Suarez"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_1688511"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Seamus Coleman"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_1688512"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3222"}

{:event/type "shoton"
:event/elapsed 9
:event/subtype "header"
:event/player1 "Tim Cahill"
:event/sortorder 5
:event/team "home"
:event/event_type "shoton"
:event/id "event_1688513"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1688514"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_3222"}

{:event/type "corner"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1688514"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Leon Osman"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1688516"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_3222"}

{:event/type "corner"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Leon Osman"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1688516"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Leon Osman"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1688518"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_3222"}

{:event/type "shotoff"
:event/elapsed 11
:event/subtype "shot"
:event/player1 "Sylvain Distin"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1688521"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Dirk Kuyt"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1688524"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_3222"}

{:event/type "shotoff"
:event/elapsed 15
:event/subtype "distance"
:event/player1 "Louis Saha"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1688528"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_3222"}

{:event/type "corner"
:event/elapsed 17
:event/subtype "short"
:event/player1 "Leon Osman"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1688536"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1688537"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Leon Osman"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_1688539"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_3222"}

{:event/type "corner"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Leon Osman"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_1688539"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_3222"}

{:event/type "shoton"
:event/elapsed 18
:event/subtype "blocked_shot"
:event/player1 "Seamus Coleman"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1688541"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3222"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Martin Skrtel"
:event/subtype "pushing"
:event/player1 "Seamus Coleman"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1688543"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3222"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Marouane Fellaini"
:event/player1 "Andy Carroll"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1688544"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_3222"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Martin Kelly"
:event/player1 "Leon Osman"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1688545"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_3222"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Louis Saha"
:event/player1 "Dirk Kuyt"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1688552"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_3222"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Luis Suarez"
:event/subtype "dangerous_play"
:event/player1 "Jack Rodwell"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1688559"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_3222"}

{:event/type "card"
:event/elapsed 23
:event/card_type "r"
:event/subtype "serious_fouls"
:event/player1 "Jack Rodwell"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_1688560"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_3222"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Charlie Adam"
:event/subtype "dangerous_play"
:event/player1 "Tim Cahill"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1688566"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_3222"}

{:event/type "card"
:event/elapsed 28
:event/card_type "y"
:event/player1 "Tim Cahill"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1688567"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_3222"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Jose Enrique"
:event/player1 "Seamus Coleman"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1688568"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Martin Kelly"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1688569"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_3222"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Louis Saha"
:event/player1 "Martin Skrtel"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1688571"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Martin Kelly"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1688575"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Dirk Kuyt"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1688577"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Dirk Kuyt"
:event/sortorder 5
:event/team "away"
:event/event_type "cross"
:event/id "event_1688579"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Dirk Kuyt"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1688582"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_3222"}

{:event/type "shotoff"
:event/elapsed 33
:event/subtype "shot"
:event/player1 "Luis Suarez"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1688586"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Martin Kelly"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1688588"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_3222"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Lucas Leiva"
:event/player1 "Marouane Fellaini"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1688594"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_3222"}

{:event/type "shoton"
:event/elapsed 38
:event/subtype "blocked_shot"
:event/player1 "Charlie Adam"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1688595"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Tony Hibbert"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1688596"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Jose Enrique"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1688601"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Martin Kelly"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1688602"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_3222"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Leon Osman"
:event/player1 "Charlie Adam"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1688604"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Louis Saha"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1688610"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_3222"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Luis Suarez"
:event/subtype "penalty"
:event/player1 "Phil Jagielka"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1688612"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_3222"}

{:event/type "goal"
:event/elapsed 44
:event/subtype "saved"
:event/player1 "Dirk Kuyt"
:event/sortorder 1
:event/team "away"
:event/id "event_1688613"
:event/event_type "goal"
:event/goal_type "npm"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Charlie Adam"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1688614"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_3222"}

{:event/type "corner"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Charlie Adam"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1688614"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Charlie Adam"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1688616"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_3222"}

{:event/type "corner"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Charlie Adam"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1688616"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1688622"
:event/minute 47
:event/match_id "match_3222"}

{:event/type "shoton"
:event/elapsed 47
:event/subtype "distance"
:event/player1 "Martin Kelly"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1688640"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Lucas Leiva"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1688624"
:event/minute 47
:event/match_id "match_3222"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 45
:event/player2 "Lucas Leiva"
:event/player1 "Louis Saha"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1688626"
:event/minute 48
:event/match_id "match_3222"}

{:event/type "shotoff"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "crossbar"
:event/player1 "Charlie Adam"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1688627"
:event/minute 48
:event/match_id "match_3222"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Louis Saha"
:event/subtype "from_behind"
:event/player1 "Lucas Leiva"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1688645"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_3222"}

{:event/type "card"
:event/elapsed 50
:event/card_type "y"
:event/player1 "Lucas Leiva"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1688646"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1688653"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_3222"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Jose Enrique"
:event/player1 "Seamus Coleman"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1688654"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_3222"}

{:event/type "shotoff"
:event/elapsed 53
:event/subtype "shot"
:event/player1 "Louis Saha"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1688657"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Charlie Adam"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1688659"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_3222"}

{:event/type "corner"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Charlie Adam"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1688659"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_3222"}

{:event/type "shoton"
:event/elapsed 53
:event/subtype "header"
:event/player1 "Andy Carroll"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_1688660"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Martin Kelly"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1688662"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Charlie Adam"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1688665"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_3222"}

{:event/type "corner"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Charlie Adam"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1688665"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_3222"}

{:event/type "shoton"
:event/elapsed 55
:event/subtype "header"
:event/player1 "Andy Carroll"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1688667"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Charlie Adam"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1688668"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3222"}

{:event/type "corner"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Charlie Adam"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1688668"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3222"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Stewart Downing"
:event/player1 "Seamus Coleman"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1688672"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1688674"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_3222"}

{:event/type "shotoff"
:event/elapsed 58
:event/subtype "distance"
:event/player1 "Lucas Leiva"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1688677"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3222"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player2 "Royston Drenthe"
:event/player1 "Dirk Kuyt"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1688681"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Royston Drenthe"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1688682"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_3222"}

{:event/type "shotoff"
:event/elapsed 61
:event/subtype "distance"
:event/player1 "Louis Saha"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1688684"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1688686"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_3222"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player1 "Tim Cahill"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1688688"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Jose Enrique"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1688696"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3222"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Dirk Kuyt"
:event/player1 "Royston Drenthe"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1688701"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_3222"}

{:event/type "shotoff"
:event/elapsed 69
:event/subtype "header"
:event/player1 "Luis Suarez"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1688703"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Tony Hibbert"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1688709"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3222"}

{:event/type "goal"
:event/elapsed 71
:event/player2 "Jose Enrique"
:event/subtype "volley"
:event/player1 "Andy Carroll"
:event/sortorder 4
:event/team "away"
:event/id "event_1688712"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3222"}

{:event/type "shoton"
:event/elapsed 72
:event/subtype "distance"
:event/player1 "Tim Cahill"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1688713"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Tony Hibbert"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1688715"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Andy Carroll"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1688718"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1688721"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Craig Bellamy"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_1688724"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3222"}

{:event/type "corner"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Craig Bellamy"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_1688724"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Craig Bellamy"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1688726"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Tony Hibbert"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1688728"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Tony Hibbert"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1688730"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_3222"}

{:event/type "foulcommit"
:event/elapsed 78
:event/player2 "Jamie Carragher"
:event/player1 "Louis Saha"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1688731"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_3222"}

{:event/type "goal"
:event/elapsed 82
:event/player2 "Dirk Kuyt"
:event/subtype "loose_ball"
:event/player1 "Luis Suarez"
:event/sortorder 1
:event/team "away"
:event/id "event_1688736"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Royston Drenthe"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1688737"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_3222"}

{:event/type "shotoff"
:event/elapsed 83
:event/subtype "shot"
:event/player1 "Louis Saha"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1688738"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_3222"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player1 "Dirk Kuyt"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1688740"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_3222"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Royston Drenthe"
:event/player1 "Lucas Leiva"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1688747"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_3222"}

{:event/type "shotoff"
:event/elapsed 86
:event/subtype "distance"
:event/player1 "Leighton Baines"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1688748"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Craig Bellamy"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1688757"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1688759"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Craig Bellamy"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1688767"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_3222"}

{:event/type "corner"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Craig Bellamy"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1688767"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_3222"}

{:event/type "shotoff"
:event/elapsed 89
:event/subtype "distance"
:event/player1 "Steven Gerrard"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1688769"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Craig Bellamy"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1688770"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_3222"}

{:event/type "corner"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Craig Bellamy"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1688770"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_3222"}

{:event/type "shotoff"
:event/elapsed 89
:event/subtype "shot"
:event/player1 "Andy Carroll"
:event/sortorder 5
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1688772"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_3222"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Marouane Fellaini"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1688777"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3222"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Royston Drenthe"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1688784"
:event/minute 91
:event/match_id "match_3222"}

{:event/type "corner"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "short"
:event/player1 "Luis Suarez"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1688785"
:event/minute 92
:event/match_id "match_3222"}

{:event/type "shotoff"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "post"
:event/player1 "Dirk Kuyt"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1688786"
:event/minute 92
:event/match_id "match_3222"}


]

