
;;# data
[
{:match/id "match_6479"
:match/league "France Ligue 1"
:match/hometeam "SC Bastia"
:match/awayteam "AC Ajaccio"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 14
:event/card_type "y"
:event/player1 "Sylvain Marchal"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2631192"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_6479"}

{:event/type "card"
:event/elapsed 43
:event/card_type "y"
:event/player1 "Jeremy Choplin"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2631218"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_6479"}

{:event/type "goal"
:event/elapsed 47
:event/player1 "Toifilou Maoulida"
:event/sortorder 0
:event/team "home"
:event/id "event_2631227"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_6479"}

{:event/type "card"
:event/elapsed 54
:event/card_type "y"
:event/player1 "Matthieu Chalme"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2631239"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_6479"}

{:event/type "card"
:event/elapsed 56
:event/card_type "y"
:event/player1 "Dennis Oliech"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2631240"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_6479"}

{:event/type "card"
:event/elapsed 60
:event/card_type "y"
:event/player1 "Samuel Bouhours"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2631241"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_6479"}

{:event/type "card"
:event/elapsed 80
:event/card_type "y"
:event/player1 "Matthieu Chalme"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2631278"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_6479"}

{:event/type "card"
:event/elapsed 90
:event/card_type "r"
:event/player1 "Dennis Oliech"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2631308"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_6479"}

{:event/type "card"
:event/elapsed 90
:event/card_type "r"
:event/player1 "Benjamin Andre"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2631309"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_6479"}

{:event/type "card"
:event/elapsed 90
:event/card_type "r"
:event/player1 "Jerome Rothen"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2631311"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_6479"}

{:event/type "card"
:event/elapsed 90
:event/card_type "r"
:event/player1 "Florian Thauvin"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2631312"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_6479"}


]

