
;;# data
[
{:match/id "match_22324"
:match/league "Spain LIGA BBVA"
:match/hometeam "Atlético Madrid"
:match/awayteam "RCD Espanyol"
:match/score "2:3"
:match/hometeam_goals "2"
:match/awayteam_goals "3"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Joan Verdu"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1300982"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_22324"}

{:event/type "shotoff"
:event/elapsed 2
:event/subtype "shot"
:event/player1 "Pablo Osvaldo"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1300984"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_22324"}

{:event/type "shoton"
:event/elapsed 3
:event/subtype "distance"
:event/player1 "Diego Forlan"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1300989"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_22324"}

{:event/type "shoton"
:event/elapsed 4
:event/subtype "shot"
:event/player1 "Pablo Osvaldo"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1300993"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_22324"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player1 "Diego Forlan"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1300995"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_22324"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Luis Perea"
:event/subtype "from_behind"
:event/player1 "Jose Maria Callejon"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1300999"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_22324"}

{:event/type "foulcommit"
:event/elapsed 8
:event/player2 "Sergio Aguero"
:event/subtype "from_behind"
:event/player1 "Jordi Amat"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1301004"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_22324"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Javi Lopez"
:event/subtype "from_behind"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1301009"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_22324"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Didac Vila"
:event/subtype "from_behind"
:event/player1 "Tiago"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1301022"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_22324"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Tomas Ujfalusi"
:event/subtype "from_behind"
:event/player1 "Joan Verdu"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1301024"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_22324"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "Sergio Aguero"
:event/subtype "from_behind"
:event/player1 "Jose Maria Callejon"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1301035"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_22324"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Sergio Aguero"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1301036"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_22324"}

{:event/type "shotoff"
:event/elapsed 16
:event/subtype "shot"
:event/player1 "Simao"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1301037"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_22324"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Joan Verdu"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1301046"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_22324"}

{:event/type "shotoff"
:event/elapsed 18
:event/subtype "header"
:event/player1 "Pablo Osvaldo"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1301047"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_22324"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Joan Verdu"
:event/subtype "from_behind"
:event/player1 "Tomas Ujfalusi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1301056"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_22324"}

{:event/type "shoton"
:event/elapsed 21
:event/subtype "blocked_shot"
:event/player1 "Jose Maria Callejon"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1301064"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_22324"}

{:event/type "shoton"
:event/elapsed 22
:event/subtype "blocked_shot"
:event/player1 "Jose Maria Callejon"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1301066"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_22324"}

{:event/type "foulcommit"
:event/elapsed 22
:event/subtype "penalty"
:event/player1 "Jose Antonio Reyes"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1301067"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_22324"}

{:event/type "card"
:event/elapsed 22
:event/card_type "y"
:event/subtype "hands"
:event/player1 "Jose Antonio Reyes"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_1301069"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_22324"}

{:event/type "goal"
:event/elapsed 22
:event/player1 "Luis Garcia"
:event/sortorder 2
:event/team "away"
:event/id "event_1301068"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_22324"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player1 "Javi Lopez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1301075"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_22324"}

{:event/type "card"
:event/elapsed 24
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Javi Lopez"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1301076"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_22324"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Jose Antonio Reyes"
:event/subtype "serious_foul"
:event/player1 "Jose Raul Baena"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1301082"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_22324"}

{:event/type "card"
:event/elapsed 26
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Jose Raul Baena"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1301083"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_22324"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Tiago"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1301087"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_22324"}

{:event/type "shoton"
:event/elapsed 28
:event/subtype "shot"
:event/player1 "Simao"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1301088"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_22324"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Sergio Aguero"
:event/subtype "from_behind"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1301095"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_22324"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Javi Lopez"
:event/subtype "from_behind"
:event/player1 "Filipe Luis"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1301099"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_22324"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Joan Verdu"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1301100"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_22324"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Javi Moreno Marquez"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1301104"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_22324"}

{:event/type "corner"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Javi Moreno Marquez"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1301104"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_22324"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Simao"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1301107"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_22324"}

{:event/type "shotoff"
:event/elapsed 34
:event/subtype "volley"
:event/player1 "Sergio Aguero"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1301108"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_22324"}

{:event/type "shoton"
:event/elapsed 36
:event/subtype "shot"
:event/player1 "Jose Antonio Reyes"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1301116"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_22324"}

{:event/type "shotoff"
:event/elapsed 36
:event/subtype "shot"
:event/player1 "Sergio Aguero"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1301118"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_22324"}

{:event/type "shotoff"
:event/elapsed 37
:event/subtype "distance"
:event/player1 "Javi Moreno Marquez"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1301124"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_22324"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Javi Moreno Marquez"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1301127"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_22324"}

{:event/type "corner"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Javi Moreno Marquez"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1301127"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_22324"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Luis Garcia"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_1301129"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_22324"}

{:event/type "corner"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Luis Garcia"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_1301129"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_22324"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Sergio Aguero"
:event/subtype "from_behind"
:event/player1 "Jordi Amat"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1301137"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_22324"}

{:event/type "card"
:event/elapsed 39
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Jordi Amat"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1301138"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_22324"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Mario Suarez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1301142"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_22324"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Simao"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1301144"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_22324"}

{:event/type "corner"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Simao"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1301144"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_22324"}

{:event/type "shotoff"
:event/elapsed 41
:event/subtype "shot"
:event/player1 "Jose Antonio Reyes"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1301145"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_22324"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Diego Forlan"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1301147"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_22324"}

{:event/type "shoton"
:event/elapsed 43
:event/subtype "shot"
:event/player1 "Sergio Aguero"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1301149"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_22324"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Simao"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1301151"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_22324"}

{:event/type "corner"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Simao"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1301151"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_22324"}

{:event/type "shotoff"
:event/elapsed 44
:event/subtype "distance"
:event/player1 "Diego Forlan"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1301154"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_22324"}

{:event/type "card"
:event/elapsed 44
:event/card_type "y"
:event/subtype "verbal_abuse"
:event/player1 "Simao"
:event/sortorder 5
:event/team "home"
:event/event_type "card"
:event/id "event_1301155"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_22324"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "Jose Antonio Reyes"
:event/subtype "serious_foul"
:event/player1 "Joan Verdu"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1301157"
:event/minute 46
:event/match_id "match_22324"}

{:event/type "card"
:event/elapsed_plus 1
:event/elapsed 45
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Joan Verdu"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_1301158"
:event/minute 46
:event/match_id "match_22324"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Jose Antonio Reyes"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1301160"
:event/minute 48
:event/match_id "match_22324"}

{:event/type "corner"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Jose Antonio Reyes"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1301160"
:event/minute 48
:event/match_id "match_22324"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Diego Forlan"
:event/subtype "pushing"
:event/player1 "Jordi Amat"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1301167"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_22324"}

{:event/type "shoton"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "shot"
:event/player1 "Tiago"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1301161"
:event/minute 48
:event/match_id "match_22324"}

{:event/type "shoton"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "shot"
:event/player1 "Diego Godin"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1301162"
:event/minute 48
:event/match_id "match_22324"}

{:event/type "goal"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "shot"
:event/player1 "Tiago"
:event/sortorder 3
:event/team "home"
:event/id "event_1301163"
:event/event_type "goal"
:event/goal_type "n"
:event/minute 48
:event/match_id "match_22324"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Jose Raul Baena"
:event/subtype "serious_foul"
:event/player1 "Tiago"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1301170"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_22324"}

{:event/type "card"
:event/elapsed 48
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Tiago"
:event/sortorder 4
:event/team "home"
:event/event_type "card"
:event/id "event_1301171"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_22324"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Jose Raul Baena"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1301173"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_22324"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Luis Garcia"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1301175"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_22324"}

{:event/type "corner"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Luis Garcia"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1301175"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_22324"}

{:event/type "shoton"
:event/elapsed 51
:event/subtype "shot"
:event/player1 "Diego Forlan"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1301178"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_22324"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Filipe Luis"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1301179"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_22324"}

{:event/type "shotoff"
:event/elapsed 52
:event/subtype "shot"
:event/player1 "Diego Forlan"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1301180"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_22324"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Simao"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1301182"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_22324"}

{:event/type "corner"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Simao"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1301182"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_22324"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Tiago"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1301183"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_22324"}

{:event/type "shoton"
:event/elapsed 54
:event/subtype "shot"
:event/player1 "Pablo Osvaldo"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1301185"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_22324"}

{:event/type "goal"
:event/elapsed 54
:event/subtype "shot"
:event/player1 "Joan Verdu"
:event/sortorder 2
:event/team "away"
:event/id "event_1301187"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_22324"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Sergio Aguero"
:event/subtype "from_behind"
:event/player1 "Juan Forlin"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1301188"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_22324"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Tiago"
:event/subtype "serious_foul"
:event/player1 "Jose Raul Baena"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1301190"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_22324"}

{:event/type "shotoff"
:event/elapsed 59
:event/subtype "direct_freekick"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1301192"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_22324"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Tiago"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1301193"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_22324"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Javi Lopez"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1301195"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_22324"}

{:event/type "shoton"
:event/elapsed 63
:event/subtype "shot"
:event/player1 "Pablo Osvaldo"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1301196"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_22324"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Diego Forlan"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1301200"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_22324"}

{:event/type "goal"
:event/elapsed 66
:event/player2 "Diego Forlan"
:event/subtype "shot"
:event/player1 "Sergio Aguero"
:event/sortorder 1
:event/team "home"
:event/id "event_1301201"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_22324"}

{:event/type "card"
:event/elapsed 67
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Carlos Kameni"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1301202"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_22324"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Jose Antonio Reyes"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1301204"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_22324"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Simao"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1301206"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_22324"}

{:event/type "corner"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Simao"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1301206"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_22324"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Jose Antonio Reyes"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1301208"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_22324"}

{:event/type "corner"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Jose Antonio Reyes"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1301208"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_22324"}

{:event/type "shotoff"
:event/elapsed 70
:event/subtype "distance"
:event/player1 "Raul Garcia"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1301211"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_22324"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Didac Vila"
:event/subtype "from_behind"
:event/player1 "Raul Garcia"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1301213"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_22324"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Raul Garcia"
:event/subtype "from_behind"
:event/player1 "Joan Verdu"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1301214"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_22324"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Simao"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1301215"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_22324"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Diego Forlan"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1301217"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_22324"}

{:event/type "corner"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Diego Forlan"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1301217"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_22324"}

{:event/type "foulcommit"
:event/elapsed 75
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1301220"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_22324"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Luis Garcia"
:event/subtype "serious_foul"
:event/player1 "Jose Antonio Reyes"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1301222"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_22324"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Luis Garcia"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1301224"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_22324"}

{:event/type "goal"
:event/elapsed 78
:event/player2 "Luis Garcia"
:event/subtype "shot"
:event/player1 "Pablo Osvaldo"
:event/sortorder 2
:event/team "away"
:event/id "event_1301223"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_22324"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Raul Garcia"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1301225"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_22324"}

{:event/type "shotoff"
:event/elapsed 80
:event/subtype "shot"
:event/player1 "Sergio Aguero"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1301227"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_22324"}

{:event/type "foulcommit"
:event/elapsed 84
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1301231"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_22324"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Mario Suarez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1301232"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_22324"}

{:event/type "shotoff"
:event/elapsed 86
:event/subtype "shot"
:event/player1 "Fran Merida"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1301234"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_22324"}

{:event/type "foulcommit"
:event/elapsed 87
:event/player2 "Sergio Aguero"
:event/subtype "serious_foul"
:event/player1 "Juan Forlin"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1301235"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_22324"}

{:event/type "card"
:event/elapsed 87
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Juan Forlin"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1301236"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_22324"}

{:event/type "foulcommit"
:event/elapsed 89
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1301239"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_22324"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Sergio Garcia"
:event/subtype "from_behind"
:event/player1 "Diego Godin"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1301240"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_22324"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Pablo Osvaldo"
:event/subtype "serious_foul"
:event/player1 "Diego Godin"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1301244"
:event/minute 91
:event/match_id "match_22324"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Javi Lopez"
:event/subtype "serious_foul"
:event/player1 "Diego Godin"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1301247"
:event/minute 93
:event/match_id "match_22324"}

{:event/type "cross"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Sergio Aguero"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1301249"
:event/minute 95
:event/match_id "match_22324"}

{:event/type "corner"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Sergio Aguero"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1301249"
:event/minute 95
:event/match_id "match_22324"}


]

