
;;# data
[
{:match/id "match_6726"
:match/league "France Ligue 1"
:match/hometeam "Stade de Reims"
:match/awayteam "Paris Saint-Germain"
:match/score "0:3"
:match/hometeam_goals "0"
:match/awayteam_goals "3"}

{:event/type "card"
:event/elapsed 21
:event/card_type "y"
:event/player1 "Mickael Tacalfred"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3145499"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_6726"}

{:event/type "goal"
:event/elapsed 25
:event/player1 "Lucas Moura"
:event/sortorder 0
:event/team "away"
:event/id "event_3145582"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_6726"}

{:event/type "card"
:event/elapsed 43
:event/card_type "y"
:event/player1 "Mads Albaek"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3145807"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_6726"}

{:event/type "card"
:event/elapsed 46
:event/card_type "y"
:event/player1 "Thiago Motta"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3146016"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_6726"}

{:event/type "card"
:event/elapsed 53
:event/card_type "y"
:event/player1 "Franck Signorino"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3146031"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_6726"}

{:event/type "goal"
:event/elapsed 60
:event/player1 "Jeremy Menez"
:event/sortorder 0
:event/team "away"
:event/id "event_3146121"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_6726"}

{:event/type "card"
:event/elapsed 63
:event/card_type "y"
:event/player1 "Alex"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3146113"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_6726"}

{:event/type "goal"
:event/elapsed 90
:event/player1 "Zlatan Ibrahimovic"
:event/sortorder 0
:event/team "away"
:event/id "event_3146315"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_6726"}


]

