
;;# data
[
{:match/id "match_9136"
:match/league "Germany 1. Bundesliga"
:match/hometeam "SV Werder Bremen"
:match/awayteam "Hamburger SV"
:match/score "3:0"
:match/hometeam_goals "2"
:match/awayteam_goals "0"}

{:event/type "goal"
:event/elapsed 42
:event/player1 "Aaron Hunt"
:event/sortorder 0
:event/team "home"
:event/id "event_2319071"
:event/event_type "goal"
:event/goal_type "npm"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_9136"}

{:event/type "goal"
:event/elapsed 51
:event/player1 "Aaron Hunt"
:event/sortorder 0
:event/team "home"
:event/id "event_2319261"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_9136"}

{:event/type "goal"
:event/elapsed 67
:event/player1 "Nils Petersen"
:event/sortorder 0
:event/team "home"
:event/id "event_2319347"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_9136"}

{:event/type "card"
:event/elapsed 80
:event/card_type "y"
:event/player1 "Robert Tesche"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2319482"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_9136"}


]

