
;;# data
[
{:match/id "match_2837"
:match/league "England Premier League"
:match/hometeam "Bolton Wanderers"
:match/awayteam "Manchester United"
:match/score "2:2"
:match/hometeam_goals "2"
:match/awayteam_goals "2"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1188568"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_2837"}

{:event/type "shotoff"
:event/elapsed 2
:event/subtype "bad shot"
:event/player1 "Dimitar Berbatov"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1188573"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "Chung-Yong Lee"
:event/player1 "Patrice Evra"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1188575"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_2837"}

{:event/type "shotoff"
:event/elapsed 3
:event/subtype "header"
:event/player1 "Johan Elmander"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1188579"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_1188581"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1188584"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_2837"}

{:event/type "corner"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1188584"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Dimitar Berbatov"
:event/player1 "Samuel Ricketts"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1188585"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_2837"}

{:event/type "shotoff"
:event/elapsed 6
:event/subtype "deflected"
:event/player1 "Chung-Yong Lee"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1188593"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Martin Petrov"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1188594"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_2837"}

{:event/type "corner"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Martin Petrov"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1188594"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_2837"}

{:event/type "goal"
:event/elapsed 6
:event/player2 "Martin Petrov"
:event/player1 "Zatyiah Knight"
:event/sortorder 4
:event/team "home"
:event/id "event_1188595"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1188599"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_2837"}

{:event/type "corner"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1188599"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Darren Fletcher"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1188607"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_2837"}

{:event/type "shoton"
:event/elapsed 10
:event/subtype "big chance shot"
:event/player1 "Ryan Giggs"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1188608"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_2837"}

{:event/type "shoton"
:event/elapsed 10
:event/subtype "distance"
:event/player1 "Martin Petrov"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1188609"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1188613"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Kevin Davies"
:event/player1 "Paul Scholes"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1188616"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_2837"}

{:event/type "shoton"
:event/elapsed 14
:event/subtype "shot"
:event/player1 "Darren Fletcher"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1188630"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1188633"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/sortorder 3
:event/team "home"
:event/event_type "throwin"
:event/id "event_1188637"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Martin Petrov"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1188640"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_2837"}

{:event/type "corner"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Martin Petrov"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1188640"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_2837"}

{:event/type "shoton"
:event/elapsed 16
:event/subtype "shot"
:event/player1 "Wayne Rooney"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1188643"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Chung-Yong Lee"
:event/player1 "Patrice Evra"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1188651"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Kevin Davies"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1188662"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Nani"
:event/player1 "Paul Robinson"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1188664"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_2837"}

{:event/type "shoton"
:event/elapsed 22
:event/subtype "distance"
:event/player1 "Samuel Ricketts"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1188665"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Fabrice Muamba"
:event/player1 "Dimitar Berbatov"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1188666"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_2837"}

{:event/type "goal"
:event/elapsed 23
:event/subtype "shot"
:event/player1 "Nani"
:event/sortorder 1
:event/team "away"
:event/id "event_1188667"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Nani"
:event/player1 "Martin Petrov"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1188671"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Martin Petrov"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1188672"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_2837"}

{:event/type "shotoff"
:event/elapsed 28
:event/subtype "deflected"
:event/player1 "Chung-Yong Lee"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1188673"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Stuart Holden"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1188675"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_2837"}

{:event/type "corner"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Stuart Holden"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1188675"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Martin Petrov"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1188678"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/sortorder 2
:event/team "home"
:event/event_type "throwin"
:event/id "event_1188680"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1188684"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1188686"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1188688"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_2837"}

{:event/type "corner"
:event/elapsed 32
:event/subtype "short"
:event/player1 "Ryan Giggs"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1188690"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Patrice Evra"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1188691"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1188693"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1188695"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_2837"}

{:event/type "corner"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1188695"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_1188697"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 6
:event/team "away"
:event/event_type "corner"
:event/id "event_1188699"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_2837"}

{:event/type "corner"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 6
:event/team "away"
:event/event_type "corner"
:event/id "event_1188699"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed 34
:event/player2 "Paul Robinson"
:event/player1 "Patrice Evra"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1188702"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Dimitar Berbatov"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1188704"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_1188708"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Kevin Davies"
:event/player1 "Patrice Evra"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1188713"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Nemanja Vidic"
:event/player1 "Kevin Davies"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1188716"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1188717"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_2837"}

{:event/type "shotoff"
:event/elapsed 40
:event/subtype "distance"
:event/player1 "Wayne Rooney"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1188724"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "John O'Shea"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1188734"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_2837"}

{:event/type "shotoff"
:event/elapsed 45
:event/subtype "deflected"
:event/player1 "Johan Elmander"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1188740"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Martin Petrov"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1188741"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_2837"}

{:event/type "corner"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Martin Petrov"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1188741"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Patrice Evra"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1188844"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_2837"}

{:event/type "shotoff"
:event/elapsed 46
:event/subtype "volley"
:event/player1 "Wayne Rooney"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1188846"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Patrice Evra"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_1188751"
:event/minute 46
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1188753"
:event/minute 47
:event/match_id "match_2837"}

{:event/type "corner"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1188753"
:event/minute 47
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed 47
:event/player2 "Jonny Evans"
:event/player1 "Kevin Davies"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1188848"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_2837"}

{:event/type "shotoff"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "header"
:event/player1 "Nemanja Vidic"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1188754"
:event/minute 47
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Patrice Evra"
:event/player1 "Johan Elmander"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1188856"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_2837"}

{:event/type "shotoff"
:event/elapsed 51
:event/subtype "distance"
:event/player1 "Martin Petrov"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1188882"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_2837"}

{:event/type "shoton"
:event/elapsed 52
:event/subtype "blocked_shot"
:event/player1 "Martin Petrov"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1188893"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Martin Petrov"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1188908"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_2837"}

{:event/type "corner"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Martin Petrov"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1188908"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_2837"}

{:event/type "shotoff"
:event/elapsed 54
:event/subtype "header"
:event/player1 "Kevin Davies"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1188910"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Patrice Evra"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1188927"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Chung-Yong Lee"
:event/player1 "Patrice Evra"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1188930"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Patrice Evra"
:event/player1 "Kevin Davies"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1188940"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Martin Petrov"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1188956"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_2837"}

{:event/type "corner"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Martin Petrov"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1188956"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Ji-Sung Park"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1188964"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1188968"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_2837"}

{:event/type "corner"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1188968"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Darren Fletcher"
:event/player1 "Fabrice Muamba"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1188986"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Ji-Sung Park"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1188994"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1189000"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_2837"}

{:event/type "corner"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1189000"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_2837"}

{:event/type "shoton"
:event/elapsed 62
:event/subtype "shot"
:event/player1 "Dimitar Berbatov"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1189010"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Ji-Sung Park"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1189014"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_2837"}

{:event/type "corner"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Ji-Sung Park"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1189014"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Chung-Yong Lee"
:event/player1 "Patrice Evra"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1189023"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Paul Robinson"
:event/player1 "Dimitar Berbatov"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1189027"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Federico Macheda"
:event/player1 "Gretar Rafn Steinsson"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1189036"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "John O'Shea"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1189049"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_2837"}

{:event/type "corner"
:event/elapsed 66
:event/subtype "short"
:event/player1 "Nani"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1189053"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Ji-Sung Park"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1189058"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1189061"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_2837"}

{:event/type "corner"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1189061"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_2837"}

{:event/type "goal"
:event/elapsed 67
:event/player2 "Johan Elmander"
:event/subtype "deflected"
:event/player1 "Martin Petrov"
:event/sortorder 4
:event/team "home"
:event/id "event_1189067"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_2837"}

{:event/type "shoton"
:event/elapsed 68
:event/subtype "blocked_shot"
:event/player1 "Dimitar Berbatov"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1189078"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1189081"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player1 "Kevin Davies"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1189083"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1189086"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player1 "Nani"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1189092"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player1 "Kevin Davies"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1189103"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_2837"}

{:event/type "shotoff"
:event/elapsed 73
:event/subtype "big chance shot"
:event/player1 "Johan Elmander"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1189123"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed 74
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1189126"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_2837"}

{:event/type "goal"
:event/elapsed 74
:event/player2 "Nani"
:event/subtype "header"
:event/player1 "Michael Owen"
:event/sortorder 2
:event/team "away"
:event/id "event_1189130"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Kevin Davies"
:event/subtype "from_behind"
:event/player1 "Paul Scholes"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1189137"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_2837"}

{:event/type "card"
:event/elapsed 75
:event/card_type "y"
:event/player1 "Paul Scholes"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1189138"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_2837"}

{:event/type "shoton"
:event/elapsed 76
:event/subtype "blocked_shot"
:event/player1 "Martin Petrov"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1189154"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed 77
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1189157"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Ji-Sung Park"
:event/player1 "Mark Davies"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1189163"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_2837"}

{:event/type "shotoff"
:event/elapsed 78
:event/subtype "big chance shot"
:event/player1 "Nani"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1189171"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Ji-Sung Park"
:event/player1 "Mark Davies"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1189191"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_2837"}

{:event/type "card"
:event/elapsed 80
:event/card_type "y"
:event/player1 "Mark Davies"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_1189192"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1189193"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_2837"}

{:event/type "shotoff"
:event/elapsed 82
:event/subtype "distance"
:event/player1 "Paul Scholes"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1189199"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_2837"}

{:event/type "shoton"
:event/elapsed 82
:event/subtype "blocked_shot"
:event/player1 "Paul Scholes"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_1189207"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1189211"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_2837"}

{:event/type "corner"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1189211"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed 83
:event/player2 "Johan Elmander"
:event/subtype "from_behind"
:event/player1 "Nemanja Vidic"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1189213"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_2837"}

{:event/type "card"
:event/elapsed 83
:event/card_type "y"
:event/player1 "Nemanja Vidic"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_1189215"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Nemanja Vidic"
:event/player1 "Kevin Davies"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1189223"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_2837"}

{:event/type "shotoff"
:event/elapsed 85
:event/subtype "shot"
:event/player1 "Johan Elmander"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1189229"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Kevin Davies"
:event/player1 "Dimitar Berbatov"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1189231"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1189245"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed 87
:event/player2 "Johan Elmander"
:event/player1 "Paul Scholes"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1189249"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_2837"}

{:event/type "shotoff"
:event/elapsed 88
:event/subtype "direct_freekick"
:event/player1 "Martin Petrov"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1189252"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_1189260"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_2837"}

{:event/type "shotoff"
:event/elapsed 89
:event/subtype "deflected"
:event/player1 "Chung-Yong Lee"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1189265"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_2837"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Martin Petrov"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1189268"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_2837"}

{:event/type "corner"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Martin Petrov"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1189268"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_2837"}

{:event/type "foulcommit"
:event/elapsed_plus 4
:event/elapsed 90
:event/player2 "Patrice Evra"
:event/player1 "Mark Davies"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1189305"
:event/minute 94
:event/match_id "match_2837"}


]

