
;;# data
[
{:match/id "match_12451"
:match/league "Italy Serie A"
:match/hometeam "Genoa"
:match/awayteam "Roma"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 56
:event/card_type "y"
:event/player1 "Tin Jedvaj"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3480695"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_12451"}

{:event/type "goal"
:event/elapsed 83
:event/player1 "Ioannis Fetfatzidis"
:event/sortorder 0
:event/team "home"
:event/id "event_3480757"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_12451"}


]

