
;;# data
[
{:match/id "match_8046"
:match/league "Germany 1. Bundesliga"
:match/hometeam "VfB Stuttgart"
:match/awayteam "FC Energie Cottbus"
:match/score "2:0"
:match/hometeam_goals "2"
:match/awayteam_goals "0"}

{:event/type "goal"
:event/elapsed 19
:event/player1 "Thomas Hitzlsperger"
:event/sortorder 0
:event/team "home"
:event/id "event_681792"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_8046"}

{:event/type "card"
:event/elapsed 41
:event/card_type "y"
:event/player1 "Mario Cvitanovic"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_682047"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_8046"}

{:event/type "goal"
:event/elapsed 78
:event/player1 "Cacau"
:event/sortorder 0
:event/team "home"
:event/id "event_682735"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_8046"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Stiven Rivic"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_683058"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_8046"}


]

