
;;# data
[
{:match/id "match_5834"
:match/league "France Ligue 1"
:match/hometeam "OGC Nice"
:match/awayteam "FC Lorient"
:match/score "2:0"
:match/hometeam_goals "2"
:match/awayteam_goals "0"}

{:event/type "goal"
:event/elapsed 1
:event/player1 "Eric Mouloungui"
:event/sortorder 0
:event/team "home"
:event/id "event_1562672"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_5834"}

{:event/type "goal"
:event/elapsed 16
:event/player1 "Eric Mouloungui"
:event/sortorder 0
:event/team "home"
:event/id "event_1562756"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_5834"}

{:event/type "card"
:event/elapsed 28
:event/card_type "y"
:event/player1 "Jacques Alaixys Romao"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1562857"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_5834"}

{:event/type "card"
:event/elapsed 44
:event/card_type "y"
:event/player1 "Jeremy Morel"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1562947"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_5834"}

{:event/type "card"
:event/elapsed 55
:event/card_type "y"
:event/player1 "Gregory Bourillon"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1563316"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_5834"}

{:event/type "card"
:event/elapsed 82
:event/card_type "y"
:event/player1 "Eric Mouloungui"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1563568"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_5834"}

{:event/type "card"
:event/elapsed 83
:event/card_type "y"
:event/player1 "Jacques Alaixys Romao"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1563523"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_5834"}


]

