
;;# data
[
{:match/id "match_3236"
:match/league "England Premier League"
:match/hometeam "Stoke City"
:match/awayteam "Fulham"
:match/score "2:0"
:match/hometeam_goals "2"
:match/awayteam_goals "0"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_1708947"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/sortorder 1
:event/team "home"
:event/event_type "throwin"
:event/id "event_1708966"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_3236"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Brede Hangeland"
:event/player1 "Jonathan Walters"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1708976"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "John Arne Riise"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1708985"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "John Arne Riise"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1708992"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_3236"}

{:event/type "shoton"
:event/elapsed 5
:event/subtype "blocked_shot"
:event/player1 "Andrew Johnson"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_1708993"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Danny Murphy"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1708998"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_3236"}

{:event/type "corner"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Danny Murphy"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1708998"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_3236"}

{:event/type "foulcommit"
:event/elapsed 8
:event/player2 "Steve Sidwell"
:event/player1 "Glenn Whelan"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1709028"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Andy Wilkinson"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1709060"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Matthew Etherington"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1709075"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_3236"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Jermaine Pennant"
:event/player1 "Clint Dempsey"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1709081"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_3236"}

{:event/type "shotoff"
:event/elapsed 12
:event/subtype "shot"
:event/player1 "Andy Wilkinson"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1709102"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1709167"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_3236"}

{:event/type "corner"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1709167"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/sortorder 3
:event/team "home"
:event/event_type "throwin"
:event/id "event_1709176"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_3236"}

{:event/type "shoton"
:event/elapsed 19
:event/subtype "blocked_shot"
:event/player1 "Moussa Dembele"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1709197"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_3236"}

{:event/type "shotoff"
:event/elapsed 19
:event/subtype "distance"
:event/player1 "John Arne Riise"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1709199"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/sortorder 1
:event/team "home"
:event/event_type "throwin"
:event/id "event_1709216"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_3236"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Mark Schwarzer"
:event/subtype "pushing"
:event/player1 "Peter Crouch"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1709220"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1709235"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_3236"}

{:event/type "shotoff"
:event/elapsed 22
:event/subtype "bad shot"
:event/player1 "Peter Crouch"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1709237"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_3236"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Clint Dempsey"
:event/player1 "Glenn Whelan"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1709252"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Jonathan Walters"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1709272"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_3236"}

{:event/type "shoton"
:event/elapsed 26
:event/subtype "blocked_shot"
:event/player1 "Rory Delap"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1709308"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1709310"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/sortorder 1
:event/team "home"
:event/event_type "throwin"
:event/id "event_1709316"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_3236"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Glenn Whelan"
:event/player1 "Moussa Dembele"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1709318"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_3236"}

{:event/type "shoton"
:event/elapsed 28
:event/subtype "blocked_shot"
:event/player1 "Marc Wilson"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1709332"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_3236"}

{:event/type "shoton"
:event/elapsed 28
:event/subtype "shot"
:event/player1 "Peter Crouch"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1709336"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1709340"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_3236"}

{:event/type "corner"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1709340"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_1709351"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1709381"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_3236"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Danny Murphy"
:event/player1 "Glenn Whelan"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1709396"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1709421"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Matthew Etherington"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1709440"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_3236"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Mark Schwarzer"
:event/subtype "pushing"
:event/player1 "Peter Crouch"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1709443"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_3236"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Matthew Upson"
:event/player1 "Bobby Zamora"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1709474"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_3236"}

{:event/type "shoton"
:event/elapsed 37
:event/subtype "blocked_shot"
:event/player1 "Jermaine Pennant"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1709476"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Andy Wilkinson"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1709480"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_3236"}

{:event/type "shotoff"
:event/elapsed 38
:event/subtype "bad shot"
:event/player1 "Matthew Etherington"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1709489"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_3236"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Glenn Whelan"
:event/player1 "Bobby Zamora"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1709496"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Chris Baird"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1709520"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_3236"}

{:event/type "shotoff"
:event/elapsed 40
:event/subtype "header"
:event/player1 "Bobby Zamora"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1709525"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1709557"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_1709563"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_3236"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Peter Crouch"
:event/player1 "Danny Murphy"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1709589"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_3236"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "big chance shot"
:event/player1 "Jermaine Pennant"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1709612"
:event/minute 46
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1709705"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_3236"}

{:event/type "shoton"
:event/elapsed 46
:event/subtype "blocked_shot"
:event/player1 "Matthew Etherington"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_1709709"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_3236"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 45
:event/player2 "Ryan Shawcross"
:event/player1 "Bobby Zamora"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1709633"
:event/minute 47
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Andrew Johnson"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1709640"
:event/minute 48
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1709745"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_3236"}

{:event/type "corner"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1709745"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_3236"}

{:event/type "shotoff"
:event/elapsed 52
:event/subtype "distance"
:event/player1 "Rory Delap"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1709795"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_3236"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Steve Sidwell"
:event/player1 "Rory Delap"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1709819"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_1709846"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_3236"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Ryan Shawcross"
:event/player1 "Clint Dempsey"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1709857"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3236"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Clint Dempsey"
:event/player1 "Rory Delap"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1709866"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3236"}

{:event/type "card"
:event/elapsed 55
:event/card_type "y"
:event/player1 "Rory Delap"
:event/sortorder 3
:event/team "home"
:event/event_type "card"
:event/id "event_1709867"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_1709881"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_3236"}

{:event/type "shoton"
:event/elapsed 56
:event/subtype "blocked_shot"
:event/player1 "Steve Sidwell"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1709885"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_1709906"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_3236"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Matthew Upson"
:event/player1 "Clint Dempsey"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1709911"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_3236"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Clint Dempsey"
:event/player1 "Glenn Whelan"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1709923"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3236"}

{:event/type "foulcommit"
:event/elapsed 59
:event/player2 "Jermaine Pennant"
:event/player1 "Danny Murphy"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1709933"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Andrew Johnson"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1709955"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_1709976"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_1710003"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Matthew Etherington"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1710013"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_3236"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Bobby Zamora"
:event/player1 "Jermaine Pennant"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1710018"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "John Arne Riise"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1710031"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_3236"}

{:event/type "foulcommit"
:event/elapsed 66
:event/player2 "Jermaine Pennant"
:event/subtype "pushing"
:event/player1 "Steve Sidwell"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1710039"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_3236"}

{:event/type "card"
:event/elapsed 66
:event/card_type "y"
:event/subtype "verbal_abuse"
:event/player1 "Damien Duff"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_1710088"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_3236"}

{:event/type "shotoff"
:event/elapsed 67
:event/subtype "big chance post"
:event/player1 "Rory Delap"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1710074"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Matthew Etherington"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_1710078"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3236"}

{:event/type "corner"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Matthew Etherington"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_1710078"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3236"}

{:event/type "shotoff"
:event/elapsed 68
:event/subtype "header"
:event/player1 "Matthew Upson"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1710082"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Jonathan Walters"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1710118"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_3236"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Clint Dempsey"
:event/player1 "Jermaine Pennant"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1710123"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_3236"}

{:event/type "card"
:event/elapsed 70
:event/card_type "y"
:event/player1 "Jermaine Pennant"
:event/sortorder 4
:event/team "home"
:event/event_type "card"
:event/id "event_1710130"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_3236"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Jermaine Pennant"
:event/player1 "Danny Murphy"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1710170"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3236"}

{:event/type "shotoff"
:event/elapsed 74
:event/subtype "direct_freekick"
:event/player1 "Marc Wilson"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1710179"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1710192"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1710200"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3236"}

{:event/type "corner"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1710200"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3236"}

{:event/type "shoton"
:event/elapsed 75
:event/subtype "big chance header"
:event/player1 "Marc Wilson"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_1710202"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3236"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Andrew Johnson"
:event/subtype "shirt_pull"
:event/player1 "Glenn Whelan"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1710206"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3236"}

{:event/type "card"
:event/elapsed 75
:event/card_type "y"
:event/subtype "emergency_brake"
:event/player1 "Glenn Whelan"
:event/sortorder 5
:event/team "home"
:event/event_type "card"
:event/id "event_1710208"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3236"}

{:event/type "foulcommit"
:event/elapsed 76
:event/player2 "Danny Murphy"
:event/player1 "Matthew Upson"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1710220"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3236"}

{:event/type "card"
:event/elapsed 77
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Danny Murphy"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1710229"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_3236"}

{:event/type "card"
:event/elapsed 77
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Matthew Upson"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_1710235"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_3236"}

{:event/type "shotoff"
:event/elapsed 78
:event/subtype "crossbar"
:event/player1 "John Arne Riise"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1710245"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_3236"}

{:event/type "foulcommit"
:event/elapsed 79
:event/player2 "Jermaine Pennant"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1710249"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_3236"}

{:event/type "card"
:event/elapsed 79
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Bobby Zamora"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1711497"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Andy Wilkinson"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1710269"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_3236"}

{:event/type "shotoff"
:event/elapsed 80
:event/subtype "shot"
:event/player1 "Matthew Etherington"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1710273"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_3236"}

{:event/type "goal"
:event/elapsed 80
:event/player2 "Matthew Etherington"
:event/subtype "tap_in"
:event/player1 "Jonathan Walters"
:event/sortorder 3
:event/team "home"
:event/id "event_1710274"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Clint Dempsey"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1710285"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Damien Duff"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1710291"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_3236"}

{:event/type "corner"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Damien Duff"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1710291"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_3236"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player1 "John Arne Riise"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1710294"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_3236"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_1710326"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_3236"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Dean Whitehead"
:event/subtype "pushing"
:event/player1 "Steve Sidwell"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1710346"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3236"}

{:event/type "shotoff"
:event/elapsed 86
:event/subtype "direct_freekick"
:event/player1 "Glenn Whelan"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1710352"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3236"}

{:event/type "foulcommit"
:event/elapsed 87
:event/player2 "Matthew Etherington"
:event/player1 "Chris Baird"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1710360"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_3236"}

{:event/type "card"
:event/elapsed 87
:event/card_type "y"
:event/player1 "Chris Baird"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1710361"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_3236"}

{:event/type "goal"
:event/elapsed 87
:event/player2 "Matthew Etherington"
:event/subtype "header"
:event/player1 "Rory Delap"
:event/sortorder 3
:event/team "home"
:event/id "event_1710371"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_3236"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Dean Whitehead"
:event/player1 "Bobby Zamora"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1710446"
:event/minute 91
:event/match_id "match_3236"}

{:event/type "shoton"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "distance"
:event/player1 "Clint Dempsey"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1710461"
:event/minute 94
:event/match_id "match_3236"}


]

