
;;# data
[
{:match/id "match_8497"
:match/league "Germany 1. Bundesliga"
:match/hometeam "VfL Wolfsburg"
:match/awayteam "TSG 1899 Hoffenheim"
:match/score "2:2"
:match/hometeam_goals "2"
:match/awayteam_goals "2"}

{:event/type "goal"
:event/elapsed 34
:event/player1 "Luiz Gustavo"
:event/sortorder 0
:event/team "away"
:event/id "event_1334866"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_8497"}

{:event/type "goal"
:event/elapsed 40
:event/player1 "Gylfi Sigurdsson"
:event/sortorder 0
:event/team "away"
:event/id "event_1334883"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_8497"}

{:event/type "card"
:event/elapsed 72
:event/card_type "y"
:event/player1 "Alexander Madlung"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1335072"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_8497"}

{:event/type "goal"
:event/elapsed 75
:event/player1 "Diego"
:event/sortorder 0
:event/team "home"
:event/id "event_1335065"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_8497"}

{:event/type "card"
:event/elapsed 77
:event/card_type "y"
:event/player1 "Sejad Salihovic"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1335163"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_8497"}

{:event/type "card"
:event/elapsed 78
:event/card_type "y"
:event/player1 "Mario Mandzukic"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1335162"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_8497"}

{:event/type "goal"
:event/elapsed 90
:event/player1 "Edin Dzeko"
:event/sortorder 0
:event/team "home"
:event/id "event_1335161"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_8497"}


]

