
;;# data
[
{:match/id "match_22804"
:match/league "Spain LIGA BBVA"
:match/hometeam "Levante UD"
:match/awayteam "Racing Santander"
:match/score "1:1"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "goal"
:event/elapsed 23
:event/player1 "Arouna Kone"
:event/sortorder 0
:event/team "home"
:event/id "event_1917246"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_22804"}

{:event/type "card"
:event/elapsed 34
:event/card_type "y"
:event/player1 "Xavier Torres"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1917345"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_22804"}

{:event/type "card"
:event/elapsed 38
:event/card_type "y"
:event/player1 "Alvaro Gonzalez Soberon"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1917433"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_22804"}

{:event/type "goal"
:event/elapsed 61
:event/player1 "Manuel Arana"
:event/sortorder 0
:event/team "away"
:event/id "event_1917710"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_22804"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Juanfran Garcia"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1917835"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_22804"}


]

