
;;# data
[
{:match/id "match_9340"
:match/league "Germany 1. Bundesliga"
:match/hometeam "1. FSV Mainz 05"
:match/awayteam "VfB Stuttgart"
:match/score "3:2"
:match/hometeam_goals "3"
:match/awayteam_goals "2"}

{:event/type "goal"
:event/elapsed 14
:event/player1 "Nicolai Mueller"
:event/sortorder 0
:event/team "home"
:event/id "event_2914403"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_9340"}

{:event/type "goal"
:event/elapsed 16
:event/player1 "Vedad Ibisevic"
:event/sortorder 0
:event/team "away"
:event/id "event_2914423"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_9340"}

{:event/type "card"
:event/elapsed 37
:event/card_type "y"
:event/player1 "Sven Ulreich"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2914530"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_9340"}

{:event/type "card"
:event/elapsed 46
:event/card_type "y"
:event/player1 "Benedikt Roecker"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2916516"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_9340"}

{:event/type "card"
:event/elapsed 51
:event/card_type "y"
:event/player1 "Moritz Leitner"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2914891"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_9340"}

{:event/type "card"
:event/elapsed 62
:event/card_type "y"
:event/player1 "Sebastian Polter"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2915018"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_9340"}

{:event/type "card"
:event/elapsed 62
:event/card_type "y"
:event/player1 "Niki Zimling"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_2916520"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_9340"}

{:event/type "goal"
:event/elapsed 65
:event/player1 "Shinji Okazaki"
:event/sortorder 0
:event/team "home"
:event/id "event_2915027"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_9340"}

{:event/type "goal"
:event/elapsed 78
:event/player1 "Nicolai Mueller"
:event/sortorder 0
:event/team "home"
:event/id "event_2915107"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_9340"}

{:event/type "goal"
:event/elapsed 82
:event/player1 "Martin Harnik"
:event/sortorder 0
:event/team "away"
:event/id "event_2915146"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_9340"}

{:event/type "card"
:event/elapsed 85
:event/card_type "y"
:event/player1 "Arthur Boka"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2915182"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_9340"}


]

