
;;# data
[
{:match/id "match_22333"
:match/league "Spain LIGA BBVA"
:match/hometeam "Real Sociedad"
:match/awayteam "Athletic Club de Bilbao"
:match/score "2:1"
:match/hometeam_goals "2"
:match/awayteam_goals "0"}

{:event/type "foulcommit"
:event/elapsed 1
:event/player2 "Xabier Prieto"
:event/subtype "pushing"
:event/player1 "Fernando Amorebieta"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1318058"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Jon Aurtenetxe"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1318065"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1318068"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_22333"}

{:event/type "corner"
:event/elapsed 2
:event/subtype "cross"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1318068"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_22333"}

{:event/type "shoton"
:event/elapsed 2
:event/subtype "shot"
:event/player1 "Mikel San Jose"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_1318070"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Iker Muniain"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1318071"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_22333"}

{:event/type "corner"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Iker Muniain"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1318071"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_22333"}

{:event/type "foulcommit"
:event/elapsed 3
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1318073"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Alberto De la Bella"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1318078"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_22333"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "David Zurutuza"
:event/subtype "pushing"
:event/player1 "Javier Martinez"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1318083"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Igor Gabilondo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1318091"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Markel Susaeta"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1318094"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_22333"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Fernando Llorente"
:event/subtype "pushing"
:event/player1 "Diego Rivas"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1318102"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_22333"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Mikel Eizaguirre Aranburu"
:event/subtype "shirt_pull"
:event/player1 "Markel Susaeta"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1318107"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Javier Martinez"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1318111"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "David Zurutuza"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1318116"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Jon Aurtenetxe"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1318121"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Xabier Prieto"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1318125"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Markel Susaeta"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1318129"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 13
:event/subtype "cross"
:event/player1 "Igor Gabilondo"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1318136"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_22333"}

{:event/type "corner"
:event/elapsed 13
:event/subtype "cross"
:event/player1 "Igor Gabilondo"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1318136"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_22333"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Igor Gabilondo"
:event/subtype "pushing"
:event/player1 "Alberto De la Bella"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1318140"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Jon Aurtenetxe"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_1318146"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Jon Aurtenetxe"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1318151"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_22333"}

{:event/type "shotoff"
:event/elapsed 15
:event/subtype "shot"
:event/player1 "Igor Gabilondo"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1318152"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Antoine Griezmann"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1318155"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Joseba Llorente"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1318161"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Xabier Prieto"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_1318164"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_22333"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Gorka Iraizoz Moreno"
:event/subtype "shirt_pull"
:event/player1 "Joseba Llorente"
:event/sortorder 6
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1318167"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_22333"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Mikel San Jose"
:event/player1 "Joseba Llorente"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1318173"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_22333"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "David Zurutuza"
:event/subtype "serious_foul"
:event/player1 "Javier Martinez"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1318176"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Iker Muniain"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1318178"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Markel Susaeta"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1318179"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_22333"}

{:event/type "shotoff"
:event/elapsed 21
:event/subtype "shot"
:event/player1 "Javier Martinez"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1318183"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Igor Gabilondo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1318187"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Xabier Prieto"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1318190"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_22333"}

{:event/type "shotoff"
:event/elapsed 23
:event/subtype "volley"
:event/player1 "Diego Rivas"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1318193"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Carlos Martinez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1318199"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_22333"}

{:event/type "foulcommit"
:event/elapsed 24
:event/subtype "penalty"
:event/player1 "Mikel San Jose"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1318200"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_22333"}

{:event/type "card"
:event/elapsed 25
:event/card_type "y"
:event/subtype "hands"
:event/player1 "Mikel San Jose"
:event/sortorder -1
:event/team "away"
:event/event_type "card"
:event/id "event_1318634"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_22333"}

{:event/type "goal"
:event/elapsed 25
:event/player1 "Xabier Prieto"
:event/sortorder 0
:event/team "home"
:event/id "event_1318201"
:event/event_type "goal"
:event/goal_type "rp"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_22333"}

{:event/type "goal"
:event/elapsed 26
:event/player1 "Xabier Prieto"
:event/sortorder 0
:event/team "home"
:event/id "event_1318204"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_22333"}

{:event/type "card"
:event/elapsed 27
:event/card_type "y"
:event/subtype "Removing Shirt"
:event/player1 "Xabier Prieto"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1318206"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_22333"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Iker Muniain"
:event/subtype "serious_foul"
:event/player1 "Alberto De la Bella"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1318208"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_22333"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Diego Rivas"
:event/subtype "pushing"
:event/player1 "Iker Muniain"
:event/sortorder 5
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1318214"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_22333"}

{:event/type "foulcommit"
:event/elapsed 29
:event/subtype "hands"
:event/player1 "Diego Rivas"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1318219"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_22333"}

{:event/type "card"
:event/elapsed 29
:event/card_type "y"
:event/subtype "hands"
:event/player1 "Diego Rivas"
:event/sortorder 3
:event/team "home"
:event/event_type "card"
:event/id "event_1318221"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Andoni Iraola"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1318227"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Iker Muniain"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1318230"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_22333"}

{:event/type "corner"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Iker Muniain"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1318230"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_22333"}

{:event/type "shotoff"
:event/elapsed 31
:event/subtype "header"
:event/player1 "Carlos Gurpegi"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1318231"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_22333"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Fernando Llorente"
:event/subtype "from_behind"
:event/player1 "Mikel Gonzalez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1318233"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_22333"}

{:event/type "shotoff"
:event/elapsed 33
:event/subtype "direct_freekick"
:event/player1 "Markel Susaeta"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1318234"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Xabier Prieto"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1318238"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Diego Rivas"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1318240"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_22333"}

{:event/type "corner"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Diego Rivas"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1318240"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Antoine Griezmann"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1318244"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_22333"}

{:event/type "shotoff"
:event/elapsed 35
:event/subtype "shot"
:event/player1 "Alberto De la Bella"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1318245"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_22333"}

{:event/type "foulcommit"
:event/elapsed 35
:event/subtype "hands"
:event/player1 "Xabier Prieto"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1318247"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Xabier Prieto"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1318248"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Igor Gabilondo"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_1318253"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_22333"}

{:event/type "shotoff"
:event/elapsed 38
:event/subtype "shot"
:event/player1 "Fernando Llorente"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1318254"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Carlos Martinez"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1318256"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_22333"}

{:event/type "shotoff"
:event/elapsed 39
:event/subtype "post"
:event/player1 "Antoine Griezmann"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1318258"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Igor Gabilondo"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1318260"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_22333"}

{:event/type "shotoff"
:event/elapsed 39
:event/subtype "shot"
:event/player1 "Markel Susaeta"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1318261"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Carlos Martinez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1318263"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_22333"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Fernando Llorente"
:event/subtype "pushing"
:event/player1 "Mikel Gonzalez"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1318267"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_22333"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Fernando Amorebieta"
:event/subtype "pushing"
:event/player1 "Joseba Llorente"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1318271"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Diego Rivas"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1318274"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_22333"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Alberto De la Bella"
:event/subtype "serious_foul"
:event/player1 "Carlos Gurpegi"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1318276"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_22333"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Alberto De la Bella"
:event/subtype "pushing"
:event/player1 "Fernando Llorente"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1318280"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Igor Gabilondo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1318281"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Diego Rivas"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1318287"
:event/minute 46
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Markel Susaeta"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1318342"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_22333"}

{:event/type "corner"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Markel Susaeta"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1318342"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_22333"}

{:event/type "shotoff"
:event/elapsed 47
:event/subtype "header"
:event/player1 "Mikel San Jose"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1318345"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Iker Muniain"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1318351"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Xabier Prieto"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1318360"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_22333"}

{:event/type "goal"
:event/elapsed 49
:event/player1 "Mikel San Jose"
:event/sortorder 1
:event/team "away"
:event/id "event_1318362"
:event/event_type "goal"
:event/goal_type "o"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_22333"}

{:event/type "foulcommit"
:event/elapsed 50
:event/subtype "hands"
:event/player1 "Fernando Llorente"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1318367"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Gaizka Toquero"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1318370"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_22333"}

{:event/type "shotoff"
:event/elapsed 53
:event/subtype "shot"
:event/player1 "Fernando Llorente"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1318383"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Markel Susaeta"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1318386"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_22333"}

{:event/type "corner"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Markel Susaeta"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1318386"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_22333"}

{:event/type "shotoff"
:event/elapsed 54
:event/subtype "shot"
:event/player1 "Andoni Iraola"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1318391"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "David Zurutuza"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1318400"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_22333"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "David Zurutuza"
:event/subtype "serious_foul"
:event/player1 "Fernando Amorebieta"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1318401"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_22333"}

{:event/type "shoton"
:event/elapsed 56
:event/subtype "shot"
:event/player1 "Antoine Griezmann"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1318404"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Antoine Griezmann"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1318406"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_22333"}

{:event/type "corner"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Antoine Griezmann"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1318406"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Antoine Griezmann"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1318413"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Pablo Orbaiz"
:event/sortorder 5
:event/team "away"
:event/event_type "cross"
:event/id "event_1318419"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Markel Susaeta"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1318426"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_22333"}

{:event/type "corner"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Markel Susaeta"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1318426"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Pablo Orbaiz"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_1318431"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Pablo Orbaiz"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1318438"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Andoni Iraola"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1318449"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Andoni Iraola"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_1318456"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Markel Susaeta"
:event/sortorder 6
:event/team "away"
:event/event_type "corner"
:event/id "event_1318459"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_22333"}

{:event/type "corner"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Markel Susaeta"
:event/sortorder 6
:event/team "away"
:event/event_type "corner"
:event/id "event_1318459"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Markel Susaeta"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1318461"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_22333"}

{:event/type "shotoff"
:event/elapsed 63
:event/subtype "header"
:event/player1 "Fernando Llorente"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1318462"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_22333"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "David Zurutuza"
:event/subtype "pushing"
:event/player1 "Carlos Gurpegi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1318467"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_22333"}

{:event/type "shotoff"
:event/elapsed 64
:event/subtype "header"
:event/player1 "Joseba Llorente"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1318470"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Xabier Prieto"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_1318475"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_22333"}

{:event/type "shoton"
:event/elapsed 65
:event/subtype "shot"
:event/player1 "Iker Muniain"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1318479"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_22333"}

{:event/type "foulcommit"
:event/elapsed 66
:event/player2 "Javier Martinez"
:event/subtype "shirt_pull"
:event/player1 "Diego Rivas"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1318481"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Gaizka Toquero"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1318487"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Gaizka Toquero"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1318489"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_22333"}

{:event/type "shoton"
:event/elapsed 67
:event/subtype "shot"
:event/player1 "Gaizka Toquero"
:event/sortorder 4
:event/team "away"
:event/event_type "shoton"
:event/id "event_1318492"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Fernando Llorente"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1318502"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Javier Martinez"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1318505"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Carlos Martinez"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1318508"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Gaizka Toquero"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_1318510"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Markel Susaeta"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1318519"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_22333"}

{:event/type "corner"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Markel Susaeta"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1318519"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_22333"}

{:event/type "shotoff"
:event/elapsed 72
:event/subtype "shot"
:event/player1 "Markel Susaeta"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1318524"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Gorka Iraizoz Moreno"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1318533"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_22333"}

{:event/type "shoton"
:event/elapsed 74
:event/subtype "shot"
:event/player1 "Pablo Orbaiz"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_1318536"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Markel Susaeta"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1318539"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_22333"}

{:event/type "corner"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Markel Susaeta"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1318539"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_22333"}

{:event/type "shotoff"
:event/elapsed 75
:event/subtype "header"
:event/player1 "Fernando Llorente"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1318540"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Andoni Iraola"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1318546"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_22333"}

{:event/type "foulcommit"
:event/elapsed 76
:event/player2 "Mikel Eizaguirre Aranburu"
:event/subtype "pushing"
:event/player1 "Gaizka Toquero"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1318553"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_22333"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Antoine Griezmann"
:event/subtype "from_behind"
:event/player1 "Ander Iturraspe"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1318562"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_22333"}

{:event/type "shoton"
:event/elapsed 78
:event/subtype "blocked_shot"
:event/player1 "Pablo Orbaiz"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1318567"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Gaizka Toquero"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1318568"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Markel Susaeta"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1318570"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_22333"}

{:event/type "corner"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Markel Susaeta"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1318570"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_22333"}

{:event/type "shotoff"
:event/elapsed 79
:event/subtype "shot"
:event/player1 "Andoni Iraola"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1318575"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_22333"}

{:event/type "foulcommit"
:event/elapsed 82
:event/subtype "hands"
:event/player1 "Diego Rivas"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1318583"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_22333"}

{:event/type "shoton"
:event/elapsed 83
:event/subtype "blocked_shot"
:event/player1 "Carlos Gurpegi"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1318584"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Iker Muniain"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1318585"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Alberto De la Bella"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1318588"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Ander Iturraspe"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1318590"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Diego Rivas"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1318593"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_22333"}

{:event/type "shoton"
:event/elapsed 86
:event/subtype "blocked_shot"
:event/player1 "Markel Susaeta"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1318595"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_22333"}

{:event/type "foulcommit"
:event/elapsed 87
:event/player2 "Ander Iturraspe"
:event/subtype "shirt_pull"
:event/player1 "Diego Rivas"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1318596"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Alberto De la Bella"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1318597"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Gaizka Toquero"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1318599"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_22333"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Carlos Gurpegi"
:event/subtype "pushing"
:event/player1 "Antoine Griezmann"
:event/sortorder 5
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1318604"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_22333"}

{:event/type "shotoff"
:event/elapsed 89
:event/subtype "header"
:event/player1 "Gaizka Toquero"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1318608"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_22333"}

{:event/type "foulcommit"
:event/elapsed 90
:event/subtype "hands"
:event/player1 "Imanol Agirretxe"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1318612"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_22333"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Markel Bergara"
:event/subtype "pushing"
:event/player1 "Carlos Gurpegi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1318614"
:event/minute 91
:event/match_id "match_22333"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Xabier Prieto"
:event/subtype "serious_foul"
:event/player1 "Carlos Gurpegi"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1318616"
:event/minute 91
:event/match_id "match_22333"}

{:event/type "card"
:event/elapsed_plus 1
:event/elapsed 90
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Carlos Gurpegi"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_1318617"
:event/minute 91
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Iker Muniain"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1318621"
:event/minute 93
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Ander Iturraspe"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1318624"
:event/minute 93
:event/match_id "match_22333"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Ander Iturraspe"
:event/sortorder 5
:event/team "away"
:event/event_type "cross"
:event/id "event_1318626"
:event/minute 93
:event/match_id "match_22333"}

{:event/type "shotoff"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Fernando Llorente"
:event/sortorder 6
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1318627"
:event/minute 93
:event/match_id "match_22333"}


]

