
;;# data
[
{:match/id "match_7053"
:match/league "France Ligue 1"
:match/hometeam "LOSC Lille"
:match/awayteam "FC Metz"
:match/score "0:0"
:match/hometeam_goals "0"
:match/awayteam_goals "0"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/sortorder 1
:event/team "away"
:event/event_type "throwin"
:event/id "event_3633482"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Gaetan Bussmann"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3633489"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_7053"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Florent Balmont"
:event/player1 "Sylvain Marchal"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3633502"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_7053"}

{:event/type "shotoff"
:event/elapsed 3
:event/subtype "shot"
:event/player1 "Sebastien Corchia"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3633512"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_7053"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Florent Balmont"
:event/subtype "from_behind"
:event/player1 "Guirane N'Daw"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3633546"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Franck Beria"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3633586"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Sebastien Corchia"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3633590"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_7053"}

{:event/type "corner"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Sebastien Corchia"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3633590"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Sebastien Corchia"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3633602"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_7053"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Jeremy Choplin"
:event/subtype "from_behind"
:event/player1 "Simon Kjaer"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3633616"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Florent Balmont"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3633620"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_7053"}

{:event/type "shoton"
:event/elapsed 11
:event/subtype "header"
:event/player1 "Simon Kjaer"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3633625"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Idrissa Gana Gueye"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3633629"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_7053"}

{:event/type "corner"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Idrissa Gana Gueye"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3633629"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Yeni N'Gbakoto"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3633634"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_7053"}

{:event/type "corner"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Yeni N'Gbakoto"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3633634"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_7053"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Florent Balmont"
:event/subtype "from_behind"
:event/player1 "Romain Rocchi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3633652"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_7053"}

{:event/type "shoton"
:event/elapsed 15
:event/subtype "distance"
:event/player1 "Juan Falcon"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3633690"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_7053"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "Florent Balmont"
:event/player1 "Guirane N'Daw"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3633700"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Marko Basa"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3633708"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_7053"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Jeremy Choplin"
:event/subtype "serious_foul"
:event/player1 "Pape Ndiaye Souare"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3633726"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Florent Balmont"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3633736"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_7053"}

{:event/type "shotoff"
:event/elapsed 19
:event/subtype "shot"
:event/player1 "Ryan Mendes"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3633742"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Sebastien Corchia"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3633775"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_7053"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player1 "Rio Mavuba"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3633805"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Guirane N'Daw"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3633810"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_7053"}

{:event/type "shotoff"
:event/elapsed 23
:event/subtype "header"
:event/player1 "unknown"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3633814"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_7053"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Divock Origi"
:event/subtype "from_behind"
:event/player1 "Jeremy Choplin"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3633831"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Sebastien Corchia"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3633840"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_7053"}

{:event/type "shoton"
:event/elapsed 26
:event/subtype "header"
:event/player1 "Divock Origi"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3633844"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Sebastien Corchia"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3633849"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_7053"}

{:event/type "corner"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Sebastien Corchia"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3633849"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Pape Ndiaye Souare"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3633917"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_7053"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Rio Mavuba"
:event/subtype "serious_foul"
:event/player1 "Romain Metannire"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3633951"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_7053"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Idrissa Gana Gueye"
:event/subtype "from_behind"
:event/player1 "unknown"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3633960"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Florent Balmont"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3633966"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_7053"}

{:event/type "shotoff"
:event/elapsed 34
:event/subtype "header"
:event/player1 "Divock Origi"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3633970"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_7053"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Franck Beria"
:event/player1 "Gaetan Bussmann"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3633984"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Sebastien Corchia"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3634001"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_7053"}

{:event/type "corner"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Sebastien Corchia"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3634001"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Rio Mavuba"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3634009"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_7053"}

{:event/type "shoton"
:event/elapsed 36
:event/subtype "header"
:event/player1 "Pape Ndiaye Souare"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_3634013"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_7053"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Florent Balmont"
:event/subtype "from_behind"
:event/player1 "Guirane N'Daw"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3634040"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_7053"}

{:event/type "card"
:event/elapsed 37
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Guirane N'Daw"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_3634032"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_7053"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player1 "Romain Rocchi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3634045"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Sebastien Corchia"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3634058"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Florent Balmont"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3634063"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_7053"}

{:event/type "corner"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Florent Balmont"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3634063"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_7053"}

{:event/type "shoton"
:event/elapsed 40
:event/subtype "distance"
:event/player1 "Idrissa Gana Gueye"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_3634070"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_7053"}

{:event/type "foulcommit"
:event/elapsed 40
:event/subtype "hands"
:event/player1 "Sebastien Corchia"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3634077"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Guirane N'Daw"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3634080"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_7053"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "unknown"
:event/subtype "pull"
:event/player1 "Franck Beria"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3634100"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_7053"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player1 "Guirane N'Daw"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3634109"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_7053"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Yeni N'Gbakoto"
:event/subtype "serious_foul"
:event/player1 "Simon Kjaer"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3634117"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_7053"}

{:event/type "shotoff"
:event/elapsed 44
:event/subtype "distance"
:event/player1 "Yeni N'Gbakoto"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3634126"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_7053"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "Florent Balmont"
:event/player1 "Guirane N'Daw"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3634169"
:event/minute 46
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Florent Balmont"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3634174"
:event/minute 46
:event/match_id "match_7053"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Divock Origi"
:event/subtype "pushing"
:event/player1 "Gaetan Bussmann"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3634267"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Florent Balmont"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3634270"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_7053"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player1 "Romain Rocchi"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3634360"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_7053"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player1 "Ryan Mendes"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3634370"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_7053"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player1 "Jeremy Choplin"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3634392"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Florent Balmont"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3634399"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_7053"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Yeni N'Gbakoto"
:event/subtype "pushing"
:event/player1 "Idrissa Gana Gueye"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3634404"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_7053"}

{:event/type "shoton"
:event/elapsed 58
:event/subtype "shot"
:event/player1 "Ryan Mendes"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3634414"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_7053"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Romain Rocchi"
:event/player1 "Simon Kjaer"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3634467"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Yeni N'Gbakoto"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3634472"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Bouna Sarr"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3634482"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_7053"}

{:event/type "corner"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Bouna Sarr"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3634482"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Bouna Sarr"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_3634488"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_7053"}

{:event/type "corner"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Bouna Sarr"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_3634488"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Franck Beria"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_3634498"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Pape Ndiaye Souare"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3634532"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Franck Beria"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3634544"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Pape Ndiaye Souare"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3634588"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Franck Beria"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3634594"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Sebastien Corchia"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3634625"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_7053"}

{:event/type "corner"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Sebastien Corchia"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3634625"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_7053"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player1 "Marko Basa"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3634687"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_7053"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Franck Beria"
:event/player1 "Bouna Sarr"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3634693"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_7053"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Rio Mavuba"
:event/player1 "Cheick Doukoure"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3634711"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_7053"}

{:event/type "shotoff"
:event/elapsed 79
:event/subtype "shot"
:event/player1 "Nolan Roux"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3634750"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Rio Mavuba"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3634787"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Pape Ndiaye Souare"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3634814"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_7053"}

{:event/type "shoton"
:event/elapsed 84
:event/subtype "deflected"
:event/player1 "Sylvio Ronny Rodelin"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3634834"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Marcos Lopes"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3634843"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_7053"}

{:event/type "corner"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Marcos Lopes"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3634843"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_7053"}

{:event/type "shotoff"
:event/elapsed 85
:event/subtype "header"
:event/player1 "Simon Kjaer"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3634848"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Marcos Lopes"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3634872"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_7053"}

{:event/type "corner"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Marcos Lopes"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3634872"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_7053"}

{:event/type "shotoff"
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Nolan Roux"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3634913"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_7053"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "hands"
:event/player1 "Marko Basa"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3634942"
:event/minute 91
:event/match_id "match_7053"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player1 "Gaetan Bussmann"
:event/sortorder 5
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3634966"
:event/minute 93
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Pape Ndiaye Souare"
:event/sortorder 6
:event/team "home"
:event/event_type "cross"
:event/id "event_3634969"
:event/minute 93
:event/match_id "match_7053"}

{:event/type "foulcommit"
:event/elapsed_plus 4
:event/elapsed 90
:event/player2 "Nolan Roux"
:event/player1 "Guido Milan"
:event/sortorder 8
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3634984"
:event/minute 94
:event/match_id "match_7053"}

{:event/type "cross"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Marcos Lopes"
:event/sortorder 9
:event/team "home"
:event/event_type "cross"
:event/id "event_3634995"
:event/minute 95
:event/match_id "match_7053"}


]

