
;;# data
[
{:match/id "match_7695"
:match/league "France Ligue 1"
:match/hometeam "Olympique de Marseille"
:match/awayteam "Girondins de Bordeaux"
:match/score "0:0"
:match/hometeam_goals "0"
:match/awayteam_goals "0"}

{:event/type "shoton"
:event/elapsed 2
:event/subtype "volley"
:event/player1 "Bouna Sarr"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_5485111"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_7695"}

{:event/type "corner"
:event/elapsed 2
:event/subtype "cross_right"
:event/player1 "Florian Thauvin"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_5485112"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_7695"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "Pablo"
:event/subtype "trip"
:event/player1 "Steven Fletcher"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5485115"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_7695"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Bouna Sarr"
:event/subtype "obstruction"
:event/player1 "Thomas Toure"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5485123"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Florian Thauvin"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5485128"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Florian Thauvin"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5485133"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_7695"}

{:event/type "shotoff"
:event/elapsed 6
:event/subtype "header"
:event/player1 "Steven Fletcher"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5485134"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_7695"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Remy Cabella"
:event/subtype "trip"
:event/player1 "Adam Ounas"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5485138"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Florian Thauvin"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5485141"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_7695"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Nicolas N'Koulou"
:event/subtype "trip"
:event/player1 "Thomas Toure"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5485149"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_7695"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Remy Cabella"
:event/subtype "trip"
:event/player1 "Enzo Crivelli"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5485155"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Benjamin Mendy"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5485157"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_7695"}

{:event/type "shotoff"
:event/elapsed 14
:event/subtype "shot"
:event/player1 "Adam Ounas"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5485187"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_7695"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Diego Contento"
:event/subtype "dangerous_play"
:event/player1 "Bouna Sarr"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5485197"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_7695"}

{:event/type "shotoff"
:event/elapsed 18
:event/subtype "volley"
:event/player1 "Andre Biyogo Poko"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5485210"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_7695"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Javier Manquillo"
:event/subtype "serious_foul"
:event/player1 "Thomas Toure"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5485219"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_7695"}

{:event/type "card"
:event/elapsed 19
:event/card_type "y"
:event/player1 "Thomas Toure"
:event/sortorder 4
:event/team "away"
:event/event_type "card"
:event/id "event_5485222"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Benjamin Mendy"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5485232"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_7695"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Adam Ounas"
:event/subtype "obstruction"
:event/player1 "Karim Rekik"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5485236"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_7695"}

{:event/type "card"
:event/elapsed 23
:event/card_type "y"
:event/subtype "emergency_brake"
:event/player1 "Karim Rekik"
:event/sortorder 4
:event/team "home"
:event/event_type "card"
:event/id "event_5485237"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Benjamin Mendy"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_5485240"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Florian Thauvin"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5485246"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_7695"}

{:event/type "corner"
:event/elapsed 25
:event/subtype "short_right"
:event/player1 "Adam Ounas"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_5485252"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_7695"}

{:event/type "shotoff"
:event/elapsed 25
:event/subtype "distance"
:event/player1 "Adam Ounas"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5485256"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_7695"}

{:event/type "shoton"
:event/elapsed 26
:event/subtype "shot"
:event/player1 "Remy Cabella"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5485260"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_7695"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Steven Fletcher"
:event/subtype "trip"
:event/player1 "Cedric Yambere"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5485264"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_7695"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Bouna Sarr"
:event/subtype "obstruction"
:event/player1 "Pablo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5485268"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_7695"}

{:event/type "card"
:event/elapsed 28
:event/card_type "y"
:event/player1 "Pablo"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_5485269"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Florian Thauvin"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5485273"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_7695"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Enzo Crivelli"
:event/subtype "pushing"
:event/player1 "Lucas Silva"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5485275"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Javier Manquillo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5485282"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_7695"}

{:event/type "foulcommit"
:event/elapsed 30
:event/player1 "Steven Fletcher"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5485285"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_7695"}

{:event/type "shoton"
:event/elapsed 31
:event/subtype "distance"
:event/player1 "Florian Thauvin"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_5485289"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_7695"}

{:event/type "corner"
:event/elapsed 32
:event/subtype "cross_left"
:event/player1 "Benjamin Mendy"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_5485293"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_7695"}

{:event/type "foulcommit"
:event/elapsed 33
:event/subtype "pushing"
:event/player1 "Florian Thauvin"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5485304"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_7695"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Remy Cabella"
:event/subtype "pull"
:event/player1 "Cedric Yambere"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5485316"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Bouna Sarr"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5485318"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Javier Manquillo"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5485321"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_7695"}

{:event/type "shoton"
:event/elapsed 36
:event/subtype "shot"
:event/player1 "Adam Ounas"
:event/sortorder 5
:event/team "away"
:event/event_type "shoton"
:event/id "event_5485325"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Florian Thauvin"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5485332"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Andre Biyogo Poko"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5485341"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_7695"}

{:event/type "shotoff"
:event/elapsed 42
:event/subtype "crossbar"
:event/player1 "Adam Ounas"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5485344"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_7695"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Mauricio Isla"
:event/subtype "pushing"
:event/player1 "Cedric Yambere"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5485348"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Florian Thauvin"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5485351"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_7695"}

{:event/type "corner"
:event/elapsed 44
:event/subtype "cross_left"
:event/player1 "Florian Thauvin"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5485354"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_7695"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Mathieu Debuchy"
:event/subtype "pushing"
:event/player1 "Remy Cabella"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5485356"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Benjamin Mendy"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5485462"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_7695"}

{:event/type "corner"
:event/elapsed 49
:event/subtype "cross_left"
:event/player1 "Florian Thauvin"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5485465"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_7695"}

{:event/type "corner"
:event/elapsed 50
:event/subtype "cross_right"
:event/player1 "Bouna Sarr"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_5485472"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Andre Biyogo Poko"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5485476"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Andre Biyogo Poko"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5485484"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_7695"}

{:event/type "corner"
:event/elapsed 53
:event/subtype "cross_right"
:event/player1 "Adam Ounas"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_5485487"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_7695"}

{:event/type "shoton"
:event/elapsed 54
:event/subtype "blocked_shot"
:event/player1 "Thomas Toure"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_5485488"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_7695"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Florian Thauvin"
:event/subtype "trip"
:event/player1 "Diego Rolan"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5485501"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Bouna Sarr"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5485504"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_7695"}

{:event/type "foulcommit"
:event/elapsed 59
:event/player2 "Diego Rolan"
:event/subtype "dangerous_play"
:event/player1 "Nicolas N'Koulou"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5485525"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_7695"}

{:event/type "card"
:event/elapsed 59
:event/card_type "y"
:event/player1 "Nicolas N'Koulou"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_5485527"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Thomas Toure"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5485529"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_7695"}

{:event/type "shotoff"
:event/elapsed 61
:event/subtype "deflected"
:event/player1 "Andre Biyogo Poko"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5485538"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_7695"}

{:event/type "corner"
:event/elapsed 61
:event/subtype "cross_right"
:event/player1 "Thomas Toure"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_5485542"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_7695"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Karim Rekik"
:event/subtype "pushing"
:event/player1 "Enzo Crivelli"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5485548"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_7695"}

{:event/type "corner"
:event/elapsed 64
:event/subtype "cross_left"
:event/player1 "Georges N'Koudou"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5485556"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_7695"}

{:event/type "shotoff"
:event/elapsed 64
:event/subtype "header"
:event/player1 "Steven Fletcher"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5485557"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_7695"}

{:event/type "corner"
:event/elapsed 67
:event/subtype "cross_right"
:event/player1 "Thomas Toure"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_5485569"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_7695"}

{:event/type "shoton"
:event/elapsed 67
:event/subtype "header"
:event/player1 "Cedric Yambere"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_5485570"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_7695"}

{:event/type "foulcommit"
:event/elapsed 67
:event/subtype "dangerous_play"
:event/player1 "Georges N'Koudou"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5485572"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Bouna Sarr"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5485574"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_7695"}

{:event/type "shotoff"
:event/elapsed 70
:event/subtype "shot"
:event/player1 "Thomas Toure"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5485588"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Remy Cabella"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_5485590"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_7695"}

{:event/type "shoton"
:event/elapsed 73
:event/subtype "shot"
:event/player1 "Thomas Toure"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_5485605"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Benjamin Mendy"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5485608"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_7695"}

{:event/type "corner"
:event/elapsed 76
:event/subtype "cross_right"
:event/player1 "Bouna Sarr"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_5485613"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_7695"}

{:event/type "corner"
:event/elapsed 76
:event/subtype "cross_right"
:event/player1 "Bouna Sarr"
:event/sortorder 5
:event/team "home"
:event/event_type "corner"
:event/id "event_5485616"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_7695"}

{:event/type "shotoff"
:event/elapsed 77
:event/subtype "distance"
:event/player1 "Andre Biyogo Poko"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5485618"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Georges N'Koudou"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5485624"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_7695"}

{:event/type "card"
:event/elapsed 78
:event/card_type "y"
:event/subtype "verbal_abuse"
:event/player1 "Michy Batshuayi"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_5485627"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_7695"}

{:event/type "foulcommit"
:event/elapsed 81
:event/subtype "hands"
:event/player1 "Michy Batshuayi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5485647"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Thomas Toure"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5485649"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_7695"}

{:event/type "corner"
:event/elapsed 83
:event/subtype "short_right"
:event/player1 "Bouna Sarr"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_5485657"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Remy Cabella"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5485658"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Benjamin Mendy"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_5485659"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_7695"}

{:event/type "shotoff"
:event/elapsed 84
:event/subtype "deflected"
:event/player1 "Jussie"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5485666"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_7695"}

{:event/type "corner"
:event/elapsed 85
:event/subtype "cross_right"
:event/player1 "Thomas Toure"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_5485667"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_7695"}

{:event/type "shoton"
:event/elapsed 86
:event/subtype "shot"
:event/player1 "Steven Fletcher"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5485673"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Georges N'Koudou"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5485675"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_7695"}

{:event/type "shoton"
:event/elapsed 86
:event/subtype "blocked_shot"
:event/player1 "Steven Fletcher"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_5485677"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Benjamin Mendy"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5485678"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Georges N'Koudou"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5485680"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Benjamin Mendy"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5485682"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Bouna Sarr"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5485687"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_7695"}

{:event/type "foulcommit"
:event/elapsed 90
:event/subtype "hands"
:event/player1 "Remy Cabella"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5485690"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_7695"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Benjamin Mendy"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5485693"
:event/minute 91
:event/match_id "match_7695"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "pushing"
:event/player1 "Steven Fletcher"
:event/sortorder 5
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5485696"
:event/minute 92
:event/match_id "match_7695"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Andre Biyogo Poko"
:event/subtype "trip"
:event/player1 "Michy Batshuayi"
:event/sortorder 8
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5485699"
:event/minute 93
:event/match_id "match_7695"}


]

