
;;# data
[
{:match/id "match_21565"
:match/league "Spain LIGA BBVA"
:match/hometeam "Málaga CF"
:match/awayteam "CA Osasuna"
:match/score "4:2"
:match/hometeam_goals "4"
:match/awayteam_goals "2"}

{:event/type "card"
:event/elapsed 12
:event/card_type "y"
:event/player1 "Juanfran"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_510815"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_21565"}

{:event/type "card"
:event/elapsed 26
:event/card_type "y"
:event/player1 "Jesus Gamez"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_511155"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_21565"}

{:event/type "card"
:event/elapsed 33
:event/card_type "y"
:event/player1 "Oier"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_511156"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_21565"}

{:event/type "card"
:event/elapsed 52
:event/card_type "y"
:event/player1 "Patxi Martinez Punal"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_511562"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_21565"}

{:event/type "goal"
:event/elapsed 55
:event/player1 "Antonio Apono"
:event/sortorder 0
:event/team "home"
:event/id "event_511597"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_21565"}

{:event/type "goal"
:event/elapsed 61
:event/player1 "Nabil Baha"
:event/sortorder 0
:event/team "home"
:event/id "event_511681"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_21565"}

{:event/type "card"
:event/elapsed 73
:event/card_type "y"
:event/player1 "Duda"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_511941"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_21565"}

{:event/type "goal"
:event/elapsed 79
:event/player1 "Javad Nekounam"
:event/sortorder 0
:event/team "away"
:event/id "event_511843"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_21565"}

{:event/type "goal"
:event/elapsed 80
:event/player1 "Miguel Flano"
:event/sortorder 0
:event/team "away"
:event/id "event_511862"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_21565"}

{:event/type "goal"
:event/elapsed 83
:event/player1 "Alberto Luque,21"
:event/sortorder 0
:event/team "home"
:event/id "event_511900"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_21565"}

{:event/type "card"
:event/elapsed 86
:event/card_type "y"
:event/player1 "Iban Javier Cuadrado"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_511956"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_21565"}

{:event/type "goal"
:event/elapsed 90
:event/player1 "Eliseu"
:event/sortorder 0
:event/team "home"
:event/id "event_511983"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_21565"}


]

