
;;# data
[
{:match/id "match_11733"
:match/league "Italy Serie A"
:match/hometeam "Napoli"
:match/awayteam "Parma"
:match/score "1:2"
:match/hometeam_goals "1"
:match/awayteam_goals "2"}

{:event/type "foulcommit"
:event/elapsed 6
:event/player2 "Gokhan Inler"
:event/player1 "Sergio Floccari"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1712124"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1712126"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_11733"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Walter Gargano"
:event/player1 "Francesco Modesto"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1712128"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1712131"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_11733"}

{:event/type "corner"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1712131"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1712134"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_11733"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Gokhan Inler"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1712143"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_11733"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Christian Maggio"
:event/player1 "Massimo Gobbi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1712145"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_11733"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Sergio Floccari"
:event/player1 "Paolo Cannavaro"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1712150"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_11733"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "Sergio Floccari"
:event/player1 "Hugo Campagnaro"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1712163"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_11733"}

{:event/type "shoton"
:event/elapsed 17
:event/subtype "blocked_shot"
:event/player1 "Sebastian Giovinco"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1712166"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_11733"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Hugo Campagnaro"
:event/player1 "Sebastian Giovinco"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1712171"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_11733"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Ezequiel Lavezzi"
:event/player1 "Abderrazak Jadid"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1712176"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_11733"}

{:event/type "shotoff"
:event/elapsed 19
:event/subtype "direct_freekick"
:event/player1 "Edinson Cavani"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1712182"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Sergio Floccari"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1712187"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_11733"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Gokhan Inler"
:event/player1 "Francesco Modesto"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1712190"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_11733"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Jonathan Biabiany"
:event/player1 "unknown"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1712193"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Sergio Floccari"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1712198"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_11733"}

{:event/type "shotoff"
:event/elapsed 22
:event/subtype "header"
:event/player1 "Jonathan Biabiany"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1712201"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Christian Maggio"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1712204"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_11733"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Christian Maggio"
:event/player1 "Jonathan Biabiany"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1712231"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_11733"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Paolo Cannavaro"
:event/subtype "shirt_pull"
:event/player1 "Stefano Morrone"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1712254"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_11733"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Edinson Cavani"
:event/player1 "Stefano Morrone"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1712261"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Christian Maggio"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1712268"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Alessandro Lucarelli"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1712270"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1712271"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1712273"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_11733"}

{:event/type "corner"
:event/elapsed 34
:event/subtype "cross"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1712273"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1712280"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_11733"}

{:event/type "corner"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1712280"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_11733"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Stefano Morrone"
:event/player1 "unknown"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1712287"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_11733"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Sebastian Giovinco"
:event/player1 "Salvatore Aronica"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1712294"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_11733"}

{:event/type "shoton"
:event/elapsed 38
:event/subtype "direct_freekick"
:event/player1 "Sebastian Giovinco"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1712297"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Jonathan Biabiany"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1712312"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_11733"}

{:event/type "shoton"
:event/elapsed 40
:event/subtype "header"
:event/player1 "Sebastian Giovinco"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1712315"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Marek Hamsik"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1712316"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Gokhan Inler"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1712320"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_11733"}

{:event/type "shoton"
:event/elapsed 42
:event/subtype "distance"
:event/player1 "Abderrazak Jadid"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1712325"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_11733"}

{:event/type "shoton"
:event/elapsed 43
:event/subtype "distance"
:event/player1 "Gokhan Inler"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1712336"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1712341"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_11733"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Alessandro Lucarelli"
:event/player1 "Christian Maggio"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1712342"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_11733"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "Gabriel Paletta"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1712352"
:event/minute 46
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1712359"
:event/minute 47
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Sebastian Giovinco"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1712362"
:event/minute 48
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1712420"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_11733"}

{:event/type "shotoff"
:event/elapsed 48
:event/subtype "distance"
:event/player1 "Christian Maggio"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1712424"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_11733"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Gokhan Inler"
:event/subtype "shirt_pull"
:event/player1 "Stefano Morrone"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1712430"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1712434"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_11733"}

{:event/type "shotoff"
:event/elapsed 51
:event/subtype "distance"
:event/player1 "Gokhan Inler"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1712438"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_11733"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "unknown"
:event/player1 "Stefano Morrone"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1712444"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Jonathan Biabiany"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1712460"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_11733"}

{:event/type "shotoff"
:event/elapsed 55
:event/subtype "distance"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1712464"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_11733"}

{:event/type "shoton"
:event/elapsed 56
:event/subtype "blocked_shot"
:event/player1 "Marek Hamsik"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1712469"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1712474"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_11733"}

{:event/type "corner"
:event/elapsed 56
:event/subtype "cross"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1712474"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_11733"}

{:event/type "shotoff"
:event/elapsed 56
:event/subtype "shot"
:event/player1 "Edinson Cavani"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1712477"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_11733"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Sergio Floccari"
:event/player1 "Salvatore Aronica"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1712480"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_11733"}

{:event/type "goal"
:event/elapsed 57
:event/player2 "Sergio Floccari"
:event/subtype "shot"
:event/player1 "Massimo Gobbi"
:event/sortorder 3
:event/team "away"
:event/id "event_1712488"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1712495"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1712498"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_11733"}

{:event/type "corner"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1712498"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_11733"}

{:event/type "shoton"
:event/elapsed 59
:event/subtype "header"
:event/player1 "Edinson Cavani"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_1712500"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_11733"}

{:event/type "shotoff"
:event/elapsed 59
:event/subtype "shot"
:event/player1 "Edinson Cavani"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1712501"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Francesco Modesto"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1712505"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_11733"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player1 "Abderrazak Jadid"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1712509"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Hugo Campagnaro"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1712513"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_11733"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Ezequiel Lavezzi"
:event/player1 "Jonathan Biabiany"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1712518"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_11733"}

{:event/type "card"
:event/elapsed 62
:event/card_type "y"
:event/player1 "Jonathan Biabiany"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_1712546"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_11733"}

{:event/type "shoton"
:event/elapsed 63
:event/subtype "header"
:event/player1 "Hugo Campagnaro"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1712521"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_11733"}

{:event/type "corner"
:event/elapsed 64
:event/subtype "short"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1712528"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1712529"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_11733"}

{:event/type "corner"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1712529"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_11733"}

{:event/type "shotoff"
:event/elapsed 65
:event/subtype "distance"
:event/player1 "Gokhan Inler"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1712531"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Francesco Valiani"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1712561"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_11733"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Sergio Floccari"
:event/player1 "Paolo Cannavaro"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1712565"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_11733"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Sebastian Giovinco"
:event/player1 "Hugo Campagnaro"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1712578"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_11733"}

{:event/type "card"
:event/elapsed 73
:event/card_type "y"
:event/player1 "Hugo Campagnaro"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_1712909"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_11733"}

{:event/type "card"
:event/elapsed 74
:event/card_type "y"
:event/subtype "diving"
:event/player1 "Ezequiel Lavezzi"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1712584"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_11733"}

{:event/type "card"
:event/elapsed 75
:event/card_type "y"
:event/player1 "Juan Camilo Zuniga"
:event/sortorder 3
:event/team "home"
:event/event_type "card"
:event/id "event_1712910"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_11733"}

{:event/type "foulcommit"
:event/elapsed 76
:event/player2 "Giuseppe Mascara"
:event/player1 "Francesco Modesto"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1712595"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_11733"}

{:event/type "goal"
:event/elapsed 76
:event/player2 "Ezequiel Lavezzi"
:event/subtype "shot"
:event/player1 "Giuseppe Mascara"
:event/sortorder 1
:event/team "home"
:event/id "event_1712597"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Juan Camilo Zuniga"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1712622"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Christian Maggio"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1712635"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Marek Hamsik"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1712638"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Sebastian Giovinco"
:event/sortorder -1
:event/team "away"
:event/event_type "cross"
:event/id "event_1712643"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_11733"}

{:event/type "goal"
:event/elapsed 83
:event/player2 "Sebastian Giovinco"
:event/subtype "tap_in"
:event/player1 "Francesco Modesto"
:event/sortorder 0
:event/team "away"
:event/id "event_1712642"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Juan Camilo Zuniga"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1712653"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_11733"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player1 "Manuele Blasi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1712661"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_11733"}

{:event/type "shoton"
:event/elapsed 86
:event/subtype "big chance header"
:event/player1 "Marek Hamsik"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1712668"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_11733"}

{:event/type "shoton"
:event/elapsed 86
:event/subtype "big chance header"
:event/player1 "Edinson Cavani"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1712672"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Giuseppe Mascara"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1712676"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_11733"}

{:event/type "shotoff"
:event/elapsed 87
:event/subtype "header"
:event/player1 "Edinson Cavani"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1712677"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Marek Hamsik"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1712695"
:event/minute 91
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Christian Maggio"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1712700"
:event/minute 92
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Christian Maggio"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1712702"
:event/minute 93
:event/match_id "match_11733"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Christian Maggio"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1712707"
:event/minute 94
:event/match_id "match_11733"}


]

