
;;# data
[
{:match/id "match_7652"
:match/league "France Ligue 1"
:match/hometeam "FC Lorient"
:match/awayteam "AS Saint-Étienne"
:match/score "0:1"
:match/hometeam_goals "0"
:match/awayteam_goals "1"}

{:event/type "foulcommit"
:event/elapsed 1
:event/player2 "Romain Hamouma"
:event/subtype "serious_foul"
:event/player1 "Benjamin Lecomte"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4704682"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_7652"}

{:event/type "card"
:event/elapsed 1
:event/card_type "r"
:event/player1 "Benjamin Lecomte"
:event/sortorder 4
:event/team "home"
:event/event_type "card"
:event/id "event_4704683"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_7652"}

{:event/type "shoton"
:event/elapsed 4
:event/subtype "direct_freekick"
:event/player1 "Pierre-Yves Polomat"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4704714"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_7652"}

{:event/type "corner"
:event/elapsed 4
:event/subtype "cross_left"
:event/player1 "Valentin Eysseric"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4704717"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Romain Hamouma"
:event/subtype "trip"
:event/player1 "Walid Mesloub"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4704733"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_7652"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Valentin Eysseric"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4704741"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 6
:event/subtype "hands"
:event/player1 "Jeremy Clement"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4704746"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Lamine Gassama"
:event/subtype "pushing"
:event/player1 "Kevin Monnet-Paquet"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4704750"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_7652"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Raphael Guerreiro"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4704754"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_7652"}

{:event/type "corner"
:event/elapsed 8
:event/subtype "cross_left"
:event/player1 "Valentin Eysseric"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4704768"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Romain Hamouma"
:event/subtype "pushing"
:event/player1 "Francois Bellugou"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4704794"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_7652"}

{:event/type "shoton"
:event/elapsed 10
:event/subtype "direct_freekick"
:event/player1 "Nolan Roux"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4704812"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Raphael Guerreiro"
:event/subtype "pull"
:event/player1 "Kevin Theophile-Catherine"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4704829"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_7652"}

{:event/type "cross"
:event/elapsed 13
:event/subtype "cross"
:event/player1 "Romain Hamouma"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4704850"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Lamine Gassama"
:event/subtype "pull"
:event/player1 "Valentin Eysseric"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4704871"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Ibrahim Didier Ndong"
:event/subtype "pushing"
:event/player1 "Pierre-Yves Polomat"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4704874"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_7652"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Raphael Guerreiro"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4704878"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Lamine Kone"
:event/subtype "pushing"
:event/player1 "Nolan Roux"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4704946"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Mustapha Bayal Sall"
:event/subtype "pushing"
:event/player1 "Walid Mesloub"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4704948"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Benjamin Moukandjo"
:event/subtype "pushing"
:event/player1 "Mustapha Bayal Sall"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4704991"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Vincent Le Goff"
:event/subtype "dangerous_play"
:event/player1 "Romain Hamouma"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4705000"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_7652"}

{:event/type "shoton"
:event/elapsed 26
:event/subtype "shot"
:event/player1 "Raphael Guerreiro"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4705039"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Pierre-Yves Polomat"
:event/subtype "trip"
:event/player1 "Ibrahim Didier Ndong"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4705053"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_7652"}

{:event/type "shoton"
:event/elapsed 28
:event/subtype "big chance shot"
:event/player1 "Kevin Monnet-Paquet"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4705066"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_7652"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Pierre-Yves Polomat"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4705070"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_7652"}

{:event/type "shotoff"
:event/elapsed 30
:event/subtype "big chance shot"
:event/player1 "Nolan Roux"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4705100"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Benjamin Moukandjo"
:event/subtype "serious_foul"
:event/player1 "Mustapha Bayal Sall"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4705115"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_7652"}

{:event/type "card"
:event/elapsed 31
:event/card_type "y"
:event/player1 "Mustapha Bayal Sall"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4705122"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_7652"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Kevin Theophile-Catherine"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4705134"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Lamine Gassama"
:event/subtype "trip"
:event/player1 "Fabien Lemoine"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4705140"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_7652"}

{:event/type "shoton"
:event/elapsed 34
:event/subtype "shot"
:event/player1 "Romain Hamouma"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4705180"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_7652"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Raphael Guerreiro"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4705198"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_7652"}

{:event/type "corner"
:event/elapsed 36
:event/subtype "cross_left"
:event/player1 "Raphael Guerreiro"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4705204"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Florentin Pogba"
:event/subtype "pushing"
:event/player1 "Benjamin Moukandjo"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4705224"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_7652"}

{:event/type "shoton"
:event/elapsed 38
:event/subtype "blocked_shot"
:event/player1 "Valentin Eysseric"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4705232"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Raphael Guerreiro"
:event/subtype "trip"
:event/player1 "Jeremy Clement"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4705279"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_7652"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Walid Mesloub"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4705291"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_7652"}

{:event/type "shoton"
:event/elapsed 43
:event/subtype "header"
:event/player1 "Lamine Kone"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4705293"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Walid Mesloub"
:event/subtype "trip"
:event/player1 "Fabien Lemoine"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4705302"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_7652"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Walid Mesloub"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4705307"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_7652"}

{:event/type "shoton"
:event/elapsed 45
:event/subtype "blocked_shot"
:event/player1 "Raphael Guerreiro"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4705309"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_7652"}

{:event/type "shoton"
:event/elapsed 45
:event/subtype "blocked_shot"
:event/player1 "Ibrahim Didier Ndong"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4705312"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_7652"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Lamine Gassama"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_4705324"
:event/minute 46
:event/match_id "match_7652"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "big chance header"
:event/player1 "Benjamin Moukandjo"
:event/sortorder 5
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4705326"
:event/minute 46
:event/match_id "match_7652"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Romain Hamouma"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4705462"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_7652"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Pierre-Yves Polomat"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4705474"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_7652"}

{:event/type "corner"
:event/elapsed 48
:event/subtype "cross_left"
:event/player1 "Valentin Eysseric"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4705478"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Benjamin Moukandjo"
:event/subtype "pull"
:event/player1 "Kevin Monnet-Paquet"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4705499"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_7652"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Raphael Guerreiro"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4705509"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_7652"}

{:event/type "shotoff"
:event/elapsed 52
:event/subtype "miss_kick"
:event/player1 "Nolan Roux"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4705541"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_7652"}

{:event/type "shotoff"
:event/elapsed 53
:event/subtype "distance"
:event/player1 "Kevin Theophile-Catherine"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4705567"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_7652"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Kevin Monnet-Paquet"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4705587"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Pierre-Yves Polomat"
:event/subtype "pull"
:event/player1 "Ibrahim Didier Ndong"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4705598"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Francois Bellugou"
:event/subtype "trip"
:event/player1 "Romain Hamouma"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4705613"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_7652"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Raphael Guerreiro"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4705632"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_7652"}

{:event/type "shotoff"
:event/elapsed 57
:event/subtype "volley"
:event/player1 "Ibrahim Didier Ndong"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4705633"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Walid Mesloub"
:event/subtype "trip"
:event/player1 "Fabien Lemoine"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4705653"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_7652"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Benjamin Moukandjo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4705664"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_7652"}

{:event/type "shotoff"
:event/elapsed 59
:event/subtype "deflected"
:event/player1 "Vincent Le Goff"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4705668"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_7652"}

{:event/type "card"
:event/elapsed 60
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Romain Hamouma"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4705696"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_7652"}

{:event/type "corner"
:event/elapsed 61
:event/subtype "cross_left"
:event/player1 "Walid Mesloub"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4705707"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_7652"}

{:event/type "corner"
:event/elapsed 61
:event/subtype "cross_right"
:event/player1 "Raphael Guerreiro"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4705721"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Francois Bellugou"
:event/subtype "pushing"
:event/player1 "Benjamin Corgnet"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4705756"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_7652"}

{:event/type "shotoff"
:event/elapsed 64
:event/subtype "big chance shot"
:event/player1 "Nolan Roux"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4705773"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_7652"}

{:event/type "card"
:event/elapsed 65
:event/card_type "y"
:event/subtype "kicked_ball_away"
:event/player1 "Kevin Monnet-Paquet"
:event/sortorder 4
:event/team "away"
:event/event_type "card"
:event/id "event_4705877"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_7652"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Kevin Theophile-Catherine"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4705810"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Walid Mesloub"
:event/player1 "Benjamin Corgnet"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4705815"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_7652"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Romain Hamouma"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4705843"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 71
:event/subtype "hands"
:event/player1 "Fabien Lemoine"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4705868"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_7652"}

{:event/type "shotoff"
:event/elapsed 72
:event/subtype "direct_freekick"
:event/player1 "Raphael Guerreiro"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4705884"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_7652"}

{:event/type "shotoff"
:event/elapsed 75
:event/subtype "shot"
:event/player1 "Benjamin Corgnet"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4705952"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_7652"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Kevin Monnet-Paquet"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4705966"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_7652"}

{:event/type "shoton"
:event/elapsed 76
:event/subtype "blocked_shot"
:event/player1 "Benjamin Corgnet"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4705968"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 76
:event/player2 "Mustapha Bayal Sall"
:event/subtype "pushing"
:event/player1 "Benjamin Moukandjo"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4705972"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_7652"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Kevin Theophile-Catherine"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4705975"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_7652"}

{:event/type "corner"
:event/elapsed 77
:event/subtype "cross_right"
:event/player1 "Romain Hamouma"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_4705988"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Lamine Kone"
:event/subtype "pushing"
:event/player1 "Mustapha Bayal Sall"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4705996"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 79
:event/player2 "Benjamin Corgnet"
:event/subtype "obstruction"
:event/player1 "Lamine Kone"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4706029"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_7652"}

{:event/type "shoton"
:event/elapsed 80
:event/subtype "blocked_shot"
:event/player1 "Florentin Pogba"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4706046"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Jeremy Clement"
:event/subtype "trip"
:event/player1 "Ibrahim Didier Ndong"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4706080"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 83
:event/player2 "Lamine Gassama"
:event/subtype "pushing"
:event/player1 "Kevin Monnet-Paquet"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4706086"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Fabien Lemoine"
:event/subtype "trip"
:event/player1 "Ibrahim Didier Ndong"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4706120"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_7652"}

{:event/type "shotoff"
:event/elapsed 85
:event/subtype "shot"
:event/player1 "Kevin Theophile-Catherine"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4706132"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_7652"}

{:event/type "goal"
:event/elapsed 87
:event/player2 "Neal Maupay"
:event/subtype "shot"
:event/player1 "Romain Hamouma"
:event/sortorder 3
:event/team "away"
:event/id "event_4706173"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_7652"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Romain Philippoteaux"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4706192"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Lamine Kone"
:event/player1 "Neal Maupay"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4706234"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_7652"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Lamine Gassama"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_4706239"
:event/minute 91
:event/match_id "match_7652"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "blocked_shot"
:event/player1 "Benjamin Jeannot"
:event/sortorder 7
:event/team "home"
:event/event_type "shoton"
:event/id "event_4706244"
:event/minute 91
:event/match_id "match_7652"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "blocked_shot"
:event/player1 "Vincent Le Goff"
:event/sortorder 8
:event/team "home"
:event/event_type "shoton"
:event/id "event_4706246"
:event/minute 91
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Kevin Monnet-Paquet"
:event/subtype "from_behind"
:event/player1 "Romain Philippoteaux"
:event/sortorder 9
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4706251"
:event/minute 91
:event/match_id "match_7652"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Francois Bellugou"
:event/subtype "trip"
:event/player1 "Neal Maupay"
:event/sortorder 11
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4706280"
:event/minute 93
:event/match_id "match_7652"}


]

