
;;# data
[
{:match/id "match_10956"
:match/league "Italy Serie A"
:match/hometeam "Lazio"
:match/awayteam "Udinese"
:match/score "3:1"
:match/hometeam_goals "3"
:match/awayteam_goals "1"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Mauricio Isla"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1085413"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_10956"}

{:event/type "shoton"
:event/elapsed 3
:event/subtype "shot"
:event/player1 "Alexis Sanchez"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1085414"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Simone Pepe"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1085423"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_10956"}

{:event/type "shotoff"
:event/elapsed 5
:event/subtype "shot"
:event/player1 "Antonio Di Natale"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1085424"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_10956"}

{:event/type "shoton"
:event/elapsed 6
:event/subtype "shot"
:event/player1 "Sergio Floccari"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1085430"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_10956"}

{:event/type "foulcommit"
:event/elapsed 9
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1085438"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Antonio Floro Flores"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1085439"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Antonio Di Natale"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1085440"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_10956"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Giuseppe Biava"
:event/subtype "from_behind"
:event/player1 "Simone Pepe"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1085447"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed 13
:event/subtype "cross"
:event/player1 "Christian Brocchi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1085448"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_10956"}

{:event/type "shotoff"
:event/elapsed 15
:event/subtype "distance"
:event/player1 "Sergio Floccari"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1085459"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Sergio Floccari"
:event/sortorder -1
:event/team "home"
:event/event_type "cross"
:event/id "event_1085479"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_10956"}

{:event/type "goal"
:event/elapsed 16
:event/player2 "Sergio Floccari"
:event/subtype "shot"
:event/player1 "Thomas Hitzlsperger"
:event/sortorder 0
:event/team "home"
:event/id "event_1085463"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Sergio Floccari"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1085508"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_10956"}

{:event/type "shotoff"
:event/elapsed 20
:event/subtype "shot"
:event/player1 "Thomas Hitzlsperger"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1085509"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_10956"}

{:event/type "foulcommit"
:event/elapsed 21
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1085527"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_10956"}

{:event/type "shoton"
:event/elapsed 22
:event/subtype "direct_freekick"
:event/player1 "Simone Pepe"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1085530"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Lionel Scaloni"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1085537"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_10956"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Christian Daniel Ledesma"
:event/subtype "from_behind"
:event/player1 "Kwadwo Asamoah"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1085542"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_10956"}

{:event/type "foulcommit"
:event/elapsed 24
:event/subtype "hands"
:event/player1 "Damiano Ferronetti"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1085555"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Simone Pepe"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1085562"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Antonio Di Natale"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1085573"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_10956"}

{:event/type "shoton"
:event/elapsed 26
:event/subtype "shot"
:event/player1 "Antonio Floro Flores"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1085574"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Antonio Floro Flores"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1085577"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_10956"}

{:event/type "corner"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Antonio Floro Flores"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1085577"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_10956"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Christian Brocchi"
:event/player1 "Simone Pepe"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1085597"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1085603"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Christian Daniel Ledesma"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1085608"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_10956"}

{:event/type "corner"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Christian Daniel Ledesma"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1085608"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_10956"}

{:event/type "shotoff"
:event/elapsed 29
:event/subtype "shot"
:event/player1 "Thomas Hitzlsperger"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1085610"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Antonio Floro Flores"
:event/sortorder -1
:event/team "away"
:event/event_type "cross"
:event/id "event_1085612"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_10956"}

{:event/type "goal"
:event/elapsed 30
:event/player2 "Antonio Floro Flores"
:event/subtype "shot"
:event/player1 "Antonio Di Natale"
:event/sortorder 0
:event/team "away"
:event/id "event_1085611"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_10956"}

{:event/type "foulcommit"
:event/elapsed 32
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1085631"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_10956"}

{:event/type "shoton"
:event/elapsed 33
:event/subtype "shot"
:event/player1 "Tommaso Rocchi"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1085639"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_10956"}

{:event/type "corner"
:event/elapsed 33
:event/subtype "short"
:event/player1 "Tommaso Rocchi"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1085645"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Christian Daniel Ledesma"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1085648"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_10956"}

{:event/type "corner"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Christian Daniel Ledesma"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1085648"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Sergio Floccari"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1085675"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_10956"}

{:event/type "shoton"
:event/elapsed 36
:event/subtype "shot"
:event/player1 "Tommaso Rocchi"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1085677"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Christian Daniel Ledesma"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1085679"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_10956"}

{:event/type "corner"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Christian Daniel Ledesma"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1085679"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_10956"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Christian Brocchi"
:event/subtype "serious_foul"
:event/player1 "Mauricio Isla"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1085690"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_10956"}

{:event/type "card"
:event/elapsed 37
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Mauricio Isla"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_1085691"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_10956"}

{:event/type "card"
:event/elapsed 38
:event/card_type "r"
:event/subtype "verbal_abuse"
:event/player1 "Mauricio Isla"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1085699"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_10956"}

{:event/type "shoton"
:event/elapsed 39
:event/subtype "direct_freekick"
:event/player1 "Christian Brocchi"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1085711"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_10956"}

{:event/type "shotoff"
:event/elapsed 40
:event/subtype "shot"
:event/player1 "Lionel Scaloni"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1085714"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Lionel Scaloni"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1085746"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_10956"}

{:event/type "shotoff"
:event/elapsed 43
:event/subtype "shot"
:event/player1 "Christian Daniel Ledesma"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1085747"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_10956"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Simone Pepe"
:event/subtype "from_behind"
:event/player1 "Christian Daniel Ledesma"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1085753"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Thomas Hitzlsperger"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1085757"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_10956"}

{:event/type "goal"
:event/elapsed 45
:event/player2 "Thomas Hitzlsperger"
:event/subtype "shot"
:event/player1 "Sergio Floccari"
:event/sortorder 2
:event/team "home"
:event/id "event_1085758"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_10956"}

{:event/type "shotoff"
:event/elapsed 50
:event/subtype "shot"
:event/player1 "Tommaso Rocchi"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1085862"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Christian Daniel Ledesma"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1085864"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_10956"}

{:event/type "corner"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Christian Daniel Ledesma"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1085864"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_10956"}

{:event/type "shoton"
:event/elapsed 51
:event/subtype "distance"
:event/player1 "Christian Brocchi"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1085865"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_10956"}

{:event/type "goal"
:event/elapsed 52
:event/player2 "Christian Daniel Ledesma"
:event/player1 "Christian Brocchi"
:event/sortorder 0
:event/team "home"
:event/id "event_1085868"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Antonio Di Natale"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1085879"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_10956"}

{:event/type "corner"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Antonio Di Natale"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1085879"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Antonio Di Natale"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1085882"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_10956"}

{:event/type "shotoff"
:event/elapsed 55
:event/subtype "header"
:event/player1 "Maurizio Domizzi"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1085883"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_10956"}

{:event/type "foulcommit"
:event/elapsed 55
:event/subtype "hands"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1085885"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_10956"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Tommaso Rocchi"
:event/subtype "serious_foul"
:event/player1 "Juan Cuadrado"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1085886"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_10956"}

{:event/type "shoton"
:event/elapsed 56
:event/subtype "direct_freekick"
:event/player1 "Christian Daniel Ledesma"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1085887"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_10956"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Giuseppe Biava"
:event/subtype "serious_foul"
:event/player1 "Giovanni Pasquale"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1085894"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Andre Dias"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1085899"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_10956"}

{:event/type "corner"
:event/elapsed 62
:event/subtype "short"
:event/player1 "Christian Daniel Ledesma"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1085917"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_10956"}

{:event/type "shoton"
:event/elapsed 62
:event/subtype "shot"
:event/player1 "Tommaso Rocchi"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1085918"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Christian Daniel Ledesma"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1085921"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_10956"}

{:event/type "corner"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Christian Daniel Ledesma"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1085921"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Antonio Di Natale"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1085928"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_10956"}

{:event/type "shotoff"
:event/elapsed 64
:event/subtype "shot"
:event/player1 "Alexis Sanchez"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1085929"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_10956"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Alexis Sanchez"
:event/subtype "serious_foul"
:event/player1 "Christian Daniel Ledesma"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1085950"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_10956"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player1 "unknown"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1085961"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_10956"}

{:event/type "card"
:event/elapsed 69
:event/card_type "y"
:event/player1 "Sebastiano Siviglia"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_1085964"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Mauro Zarate"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1085971"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Sergio Floccari"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1085987"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_10956"}

{:event/type "foulcommit"
:event/elapsed 75
:event/subtype "from_behind"
:event/player1 "Thomas Hitzlsperger"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1085994"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_10956"}

{:event/type "shoton"
:event/elapsed 75
:event/subtype "shot"
:event/player1 "Juan Cuadrado"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1085999"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Christian Daniel Ledesma"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1086001"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_10956"}

{:event/type "corner"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Christian Daniel Ledesma"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1086001"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_10956"}

{:event/type "shoton"
:event/elapsed 76
:event/subtype "shot"
:event/player1 "Sergio Floccari"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1086004"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_10956"}

{:event/type "shoton"
:event/elapsed 78
:event/subtype "shot"
:event/player1 "Sergio Floccari"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1086008"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Sergio Floccari"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1086010"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_10956"}

{:event/type "shoton"
:event/elapsed 78
:event/subtype "shot"
:event/player1 "Sergio Floccari"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1086011"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_10956"}

{:event/type "shoton"
:event/elapsed 78
:event/subtype "shot"
:event/player1 "Modibo Diakite"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_1086017"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_10956"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Guilherme Siqueira"
:event/subtype "serious_foul"
:event/player1 "Modibo Diakite"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1086032"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_10956"}

{:event/type "card"
:event/elapsed 80
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Modibo Diakite"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_1086034"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_10956"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Juan Cuadrado"
:event/player1 "Christian Daniel Ledesma"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1086055"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_10956"}

{:event/type "shoton"
:event/elapsed 85
:event/subtype "distance"
:event/player1 "Kwadwo Asamoah"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1086056"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_10956"}

{:event/type "shoton"
:event/elapsed 85
:event/subtype "shot"
:event/player1 "Alexis Sanchez"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_1086058"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Antonio Di Natale"
:event/sortorder 5
:event/team "away"
:event/event_type "corner"
:event/id "event_1086062"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_10956"}

{:event/type "corner"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Antonio Di Natale"
:event/sortorder 5
:event/team "away"
:event/event_type "corner"
:event/id "event_1086062"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_10956"}

{:event/type "shotoff"
:event/elapsed 87
:event/subtype "shot"
:event/player1 "Christian Brocchi"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1086079"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_10956"}

{:event/type "shoton"
:event/elapsed 87
:event/subtype "shot"
:event/player1 "Alexis Sanchez"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1086083"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_10956"}

{:event/type "shotoff"
:event/elapsed 87
:event/subtype "shot"
:event/player1 "Alexis Sanchez"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1086084"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_10956"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player1 "Kwadwo Asamoah"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1086095"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Mauro Zarate"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1086102"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_10956"}

{:event/type "shotoff"
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Roberto Baronio"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1086103"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1086111"
:event/minute 91
:event/match_id "match_10956"}

{:event/type "corner"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1086111"
:event/minute 91
:event/match_id "match_10956"}

{:event/type "shoton"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Juan Cuadrado"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1086118"
:event/minute 92
:event/match_id "match_10956"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Roberto Baronio"
:event/player1 "Kwadwo Asamoah"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1086123"
:event/minute 93
:event/match_id "match_10956"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Christian Daniel Ledesma"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1086126"
:event/minute 93
:event/match_id "match_10956"}

{:event/type "corner"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Christian Daniel Ledesma"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1086126"
:event/minute 93
:event/match_id "match_10956"}


]

