
;;# data
[
{:match/id "match_23353"
:match/league "Spain LIGA BBVA"
:match/hometeam "FC Barcelona"
:match/awayteam "Málaga CF"
:match/score "4:1"
:match/hometeam_goals "4"
:match/awayteam_goals "1"}

{:event/type "goal"
:event/elapsed 3
:event/player1 "David Villa"
:event/sortorder 0
:event/team "home"
:event/id "event_2796589"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_23353"}

{:event/type "goal"
:event/elapsed 14
:event/player1 "Cesc Fabregas"
:event/sortorder 0
:event/team "home"
:event/id "event_2796593"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_23353"}

{:event/type "goal"
:event/elapsed 15
:event/player1 "Martin Montoya"
:event/sortorder 0
:event/team "home"
:event/id "event_2796599"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_23353"}

{:event/type "goal"
:event/elapsed 52
:event/player1 "Andres Iniesta"
:event/sortorder 0
:event/team "home"
:event/id "event_2796725"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_23353"}

{:event/type "goal"
:event/elapsed 56
:event/player1 "Pedro Morales"
:event/sortorder 0
:event/team "away"
:event/id "event_2796726"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_23353"}


]

