
;;# data
[
{:match/id "match_9910"
:match/league "Germany 1. Bundesliga"
:match/hometeam "TSG 1899 Hoffenheim"
:match/awayteam "SC Freiburg"
:match/score "3:3"
:match/hometeam_goals "3"
:match/awayteam_goals "3"}

{:event/type "foulcommit"
:event/elapsed 1
:event/player2 "Kevin Volland"
:event/subtype "pushing"
:event/player1 "Vladimir Darida"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3764318"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Mensur Mujdza"
:event/subtype "pushing"
:event/player1 "Kevin Volland"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3764327"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_9910"}

{:event/type "shoton"
:event/elapsed 5
:event/subtype "distance"
:event/player1 "Kevin Volland"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3764376"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_9910"}

{:event/type "shoton"
:event/elapsed 7
:event/subtype "blocked_shot"
:event/player1 "Adam Szalai"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3764399"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Mike Frantz"
:event/subtype "pushing"
:event/player1 "Andreas Beck"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3764404"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Maximilian Philipp"
:event/subtype "pushing"
:event/player1 "Jannik Vestergaard"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3764467"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Felix Klaus"
:event/subtype "trip"
:event/player1 "Sebastian Rudy"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3764478"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Tarik Elyounoussi"
:event/subtype "pushing"
:event/player1 "Christian Guenter"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3764503"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_9910"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Kevin Volland"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3764521"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_9910"}

{:event/type "corner"
:event/elapsed 15
:event/subtype "cross_left"
:event/player1 "Sebastian Rudy"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3764526"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_9910"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Eugen Polanski"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3764543"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_9910"}

{:event/type "shotoff"
:event/elapsed 16
:event/subtype "deflected"
:event/player1 "Kevin Volland"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3764544"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_9910"}

{:event/type "shotoff"
:event/elapsed 18
:event/subtype "big chance shot"
:event/player1 "Maximilian Philipp"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3764571"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Julian Schuster"
:event/subtype "trip"
:event/player1 "Tobias Strobl"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3764594"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_9910"}

{:event/type "shoton"
:event/elapsed 20
:event/subtype "big chance shot"
:event/player1 "Vladimir Darida"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3764601"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_9910"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Mensur Mujdza"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3764649"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Sebastian Rudy"
:event/subtype "trip"
:event/player1 "Christian Guenter"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3764656"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_9910"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Sebastian Rudy"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3764661"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_9910"}

{:event/type "shotoff"
:event/elapsed 30
:event/subtype "volley"
:event/player1 "Adam Szalai"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3764734"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Christian Guenter"
:event/subtype "trip"
:event/player1 "Sebastian Rudy"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3764754"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_9910"}

{:event/type "goal"
:event/elapsed 31
:event/player2 "Maximilian Philipp"
:event/subtype "shot"
:event/player1 "Mike Frantz"
:event/sortorder 2
:event/team "away"
:event/id "event_3764758"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_9910"}

{:event/type "goal"
:event/elapsed 33
:event/player2 "Jonathan Schmid"
:event/subtype "shot"
:event/player1 "Mike Frantz"
:event/sortorder 1
:event/team "away"
:event/id "event_3764783"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Eugen Polanski"
:event/subtype "trip"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3764831"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_9910"}

{:event/type "shotoff"
:event/elapsed 38
:event/subtype "shot"
:event/player1 "Adam Szalai"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3764840"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_9910"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Adam Szalai"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3764860"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_9910"}

{:event/type "corner"
:event/elapsed 39
:event/subtype "cross_right"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3764864"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_9910"}

{:event/type "shotoff"
:event/elapsed 40
:event/subtype "header"
:event/player1 "Niklas Suele"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3764871"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Vladimir Darida"
:event/subtype "trip"
:event/player1 "Tobias Strobl"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3764898"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_9910"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3764906"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_9910"}

{:event/type "corner"
:event/elapsed 42
:event/subtype "cross_left"
:event/player1 "Jonathan Schmid"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_3764913"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_9910"}

{:event/type "goal"
:event/elapsed 44
:event/player2 "Kevin Volland"
:event/subtype "shot"
:event/player1 "Tarik Elyounoussi"
:event/sortorder 1
:event/team "home"
:event/id "event_3764936"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_9910"}

{:event/type "shotoff"
:event/elapsed 45
:event/subtype "distance"
:event/player1 "Kevin Volland"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3764957"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "Jannik Vestergaard"
:event/subtype "trip"
:event/player1 "Vladimir Darida"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3764984"
:event/minute 46
:event/match_id "match_9910"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Sebastian Rudy"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_3764986"
:event/minute 46
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Tarik Elyounoussi"
:event/subtype "pull"
:event/player1 "Julian Schuster"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3765128"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Vladimir Darida"
:event/subtype "pushing"
:event/player1 "Eugen Polanski"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3765214"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Eugen Polanski"
:event/subtype "dangerous_play"
:event/player1 "Felix Klaus"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3765226"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_9910"}

{:event/type "card"
:event/elapsed 54
:event/card_type "y"
:event/player1 "Felix Klaus"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_3765233"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_9910"}

{:event/type "shoton"
:event/elapsed 55
:event/subtype "direct_freekick"
:event/player1 "Jannik Vestergaard"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3765246"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_9910"}

{:event/type "card"
:event/elapsed 56
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Mensur Mujdza"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3765257"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_9910"}

{:event/type "card"
:event/elapsed 56
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Andreas Beck"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_3765265"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_9910"}

{:event/type "corner"
:event/elapsed 56
:event/subtype "cross_left"
:event/player1 "Jannik Vestergaard"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3765269"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_9910"}

{:event/type "shotoff"
:event/elapsed 57
:event/subtype "distance"
:event/player1 "Sebastian Rudy"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3765281"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_9910"}

{:event/type "corner"
:event/elapsed 57
:event/subtype "cross_left"
:event/player1 "Sebastian Rudy"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_3765300"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_9910"}

{:event/type "shotoff"
:event/elapsed 58
:event/subtype "shot"
:event/player1 "Eugen Polanski"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3765306"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Andreas Beck"
:event/subtype "dangerous_play"
:event/player1 "Julian Schuster"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3765367"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_9910"}

{:event/type "card"
:event/elapsed 61
:event/card_type "y"
:event/player1 "Julian Schuster"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_3765370"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Christian Guenter"
:event/subtype "pushing"
:event/player1 "Adam Szalai"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3765385"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Tarik Elyounoussi"
:event/subtype "trip"
:event/player1 "Mensur Mujdza"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3765411"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_9910"}

{:event/type "goal"
:event/elapsed 63
:event/subtype "direct_freekick"
:event/player1 "Sebastian Rudy"
:event/sortorder 1
:event/team "home"
:event/id "event_3765424"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Felix Klaus"
:event/subtype "trip"
:event/player1 "Sebastian Rudy"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3765458"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Christian Guenter"
:event/subtype "pushing"
:event/player1 "Niklas Suele"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3765535"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Vladimir Darida"
:event/subtype "trip"
:event/player1 "Pirmin Schwegler"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3765571"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_9910"}

{:event/type "shoton"
:event/elapsed 72
:event/subtype "blocked_shot"
:event/player1 "Jonathan Schmid"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3765579"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_9910"}

{:event/type "corner"
:event/elapsed 72
:event/subtype "cross_left"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3765583"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Pavel Krmas"
:event/subtype "pushing"
:event/player1 "Anthony Modeste"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3765597"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Jannik Vestergaard"
:event/subtype "trip"
:event/player1 "Vladimir Darida"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3765603"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_9910"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Jannik Vestergaard"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3765612"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed 74
:event/player2 "Christian Guenter"
:event/subtype "trip"
:event/player1 "Pirmin Schwegler"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3765628"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Jonathan Schmid"
:event/subtype "penalty"
:event/player1 "Tobias Strobl"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3765640"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_9910"}

{:event/type "card"
:event/elapsed 75
:event/card_type "y"
:event/player1 "Tobias Strobl"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_3765647"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_9910"}

{:event/type "goal"
:event/elapsed 75
:event/player1 "Vladimir Darida"
:event/sortorder 2
:event/team "away"
:event/id "event_3765651"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Anthony Modeste"
:event/subtype "trip"
:event/player1 "Marc-Oliver Kempf"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3765674"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_9910"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Roberto Firmino"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3765675"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_9910"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Kevin Volland"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3765692"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Pirmin Schwegler"
:event/subtype "dangerous_play"
:event/player1 "Vladimir Darida"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3765729"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_9910"}

{:event/type "card"
:event/elapsed 81
:event/card_type "r"
:event/player1 "Vladimir Darida"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_3765731"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_9910"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Kevin Volland"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3765746"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_9910"}

{:event/type "shotoff"
:event/elapsed 83
:event/subtype "header"
:event/player1 "Niklas Suele"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3765747"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Jannik Vestergaard"
:event/subtype "pushing"
:event/player1 "Pavel Krmas"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3765769"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_9910"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Sebastian Rudy"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3765773"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_9910"}

{:event/type "shotoff"
:event/elapsed 84
:event/subtype "header"
:event/player1 "Tobias Strobl"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3765774"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_9910"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Kevin Volland"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3765780"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_9910"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3765793"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_9910"}

{:event/type "shoton"
:event/elapsed 86
:event/subtype "header"
:event/player1 "Jannik Vestergaard"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3765794"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Sascha Riether"
:event/subtype "trip"
:event/player1 "Pirmin Schwegler"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3765800"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_9910"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Felix Klaus"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3765808"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_9910"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Kevin Volland"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3765837"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_9910"}

{:event/type "shotoff"
:event/elapsed 89
:event/subtype "volley"
:event/player1 "Tarik Elyounoussi"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3765840"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Christian Guenter"
:event/subtype "trip"
:event/player1 "Kevin Volland"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3765849"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_9910"}

{:event/type "corner"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "short_left"
:event/player1 "Jonathan Schmid"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_3765874"
:event/minute 91
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Felix Klaus"
:event/subtype "trip"
:event/player1 "Sebastian Rudy"
:event/sortorder 7
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3765896"
:event/minute 92
:event/match_id "match_9910"}

{:event/type "card"
:event/elapsed_plus 2
:event/elapsed 90
:event/card_type "y"
:event/player1 "Sebastian Rudy"
:event/sortorder 8
:event/team "home"
:event/event_type "card"
:event/id "event_3765899"
:event/minute 92
:event/match_id "match_9910"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Tobias Strobl"
:event/subtype "pushing"
:event/player1 "Sascha Riether"
:event/sortorder 9
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3765908"
:event/minute 93
:event/match_id "match_9910"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Kevin Volland"
:event/sortorder 10
:event/team "home"
:event/event_type "cross"
:event/id "event_3765913"
:event/minute 93
:event/match_id "match_9910"}

{:event/type "shoton"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "header"
:event/player1 "Niklas Suele"
:event/sortorder 11
:event/team "home"
:event/event_type "shoton"
:event/id "event_3765918"
:event/minute 93
:event/match_id "match_9910"}

{:event/type "shoton"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Tobias Strobl"
:event/sortorder 12
:event/team "home"
:event/event_type "shoton"
:event/id "event_3765920"
:event/minute 93
:event/match_id "match_9910"}

{:event/type "goal"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Jannik Vestergaard"
:event/sortorder 13
:event/team "home"
:event/id "event_3765912"
:event/event_type "goal"
:event/goal_type "n"
:event/minute 93
:event/match_id "match_9910"}


]

