
;;# data
[
{:match/id "match_11098"
:match/league "Italy Serie A"
:match/hometeam "Cesena"
:match/awayteam "Cagliari"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Luis Jimenez"
:event/player1 "Francesco Pisano"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1335243"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_11098"}

{:event/type "shotoff"
:event/elapsed 3
:event/subtype "distance"
:event/player1 "Fabio Caserta"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1335249"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Andrea Cossu"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1335254"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_11098"}

{:event/type "corner"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Andrea Cossu"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1335254"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Andrea Cossu"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1335264"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Maurizio Lauro"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1335266"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 8
:event/player2 "Andrea Cossu"
:event/player1 "Giuseppe Colucci"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1335276"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Maximiliano Pellegrino"
:event/player1 "Robert Acquafresca"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1335291"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Davide Biondini"
:event/player1 "Maurizio Lauro"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1335296"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Emanuele Giaccherini"
:event/player1 "Radja Nainggolan"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1335301"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Davide Biondini"
:event/subtype "pushing"
:event/player1 "Erjon Bogdani"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1335306"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_11098"}

{:event/type "card"
:event/elapsed 13
:event/card_type "y"
:event/player1 "Erjon Bogdani"
:event/sortorder 3
:event/team "home"
:event/event_type "card"
:event/id "event_1335310"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Andrea Cossu"
:event/player1 "Luis Jimenez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1335322"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 15
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1335328"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_11098"}

{:event/type "shotoff"
:event/elapsed 16
:event/subtype "volley"
:event/player1 "Marco Parolo"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1335331"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Fabio Caserta"
:event/subtype "pushing"
:event/player1 "Daniele Conti"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1335337"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_11098"}

{:event/type "goal"
:event/elapsed 17
:event/subtype "shot"
:event/player1 "Luis Jimenez"
:event/sortorder 2
:event/team "home"
:event/id "event_1335338"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Alessandro Agostini"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1335353"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Andrea Cossu"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1335356"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_11098"}

{:event/type "corner"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Andrea Cossu"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1335356"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_11098"}

{:event/type "shoton"
:event/elapsed 21
:event/subtype "blocked_shot"
:event/player1 "Daniele Conti"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1335362"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_11098"}

{:event/type "shotoff"
:event/elapsed 21
:event/subtype "shot"
:event/player1 "Radja Nainggolan"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1335364"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Francesco Pisano"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1335374"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_11098"}

{:event/type "shotoff"
:event/elapsed 24
:event/subtype "shot"
:event/player1 "Fabio Caserta"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1335380"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Maurizio Lauro"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1335397"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Davide Astori"
:event/player1 "Erjon Bogdani"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1335398"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Andrea Cossu"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1335455"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Andrea Cossu"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1335470"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Francesco Pisano"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1335475"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player1 "Erjon Bogdani"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1335479"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Emanuele Giaccherini"
:event/player1 "Davide Astori"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1335485"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_11098"}

{:event/type "card"
:event/elapsed 39
:event/card_type "y"
:event/player1 "Davide Astori"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1335488"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_11098"}

{:event/type "shotoff"
:event/elapsed 40
:event/subtype "header"
:event/player1 "Erjon Bogdani"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1335495"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Andrea Cossu"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1335497"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Davide Biondini"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1335498"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_11098"}

{:event/type "shotoff"
:event/elapsed 40
:event/subtype "bicycle_kick"
:event/player1 "Robert Acquafresca"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1335499"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Radja Nainggolan"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1335509"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Davide Biondini"
:event/player1 "Erjon Bogdani"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1335521"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Andrea Cossu"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1335522"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Luis Jimenez"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1335531"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_11098"}

{:event/type "corner"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Luis Jimenez"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1335531"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Michele Canini"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1335537"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_11098"}

{:event/type "shotoff"
:event/elapsed 44
:event/subtype "crossbar"
:event/player1 "Robert Acquafresca"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1335538"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_11098"}

{:event/type "shotoff"
:event/elapsed 44
:event/subtype "volley"
:event/player1 "Daniele Conti"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1335539"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player1 "Fabio Caserta"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1335549"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_11098"}

{:event/type "shotoff"
:event/elapsed 46
:event/subtype "distance"
:event/player1 "Emanuele Giaccherini"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1335639"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Steve von Bergen"
:event/player1 "Andrea Cossu"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1335647"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Emanuele Giaccherini"
:event/player1 "Andrea Cossu"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1335657"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_11098"}

{:event/type "shoton"
:event/elapsed 51
:event/subtype "shot"
:event/player1 "Emanuele Giaccherini"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1335660"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Andrea Cossu"
:event/subtype "pushing"
:event/player1 "Marco Parolo"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1335662"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Andrea Cossu"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1335667"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Alessandro Agostini"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1335668"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Andrea Cossu"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1335672"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_11098"}

{:event/type "corner"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Andrea Cossu"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1335672"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Andrea Cossu"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1335676"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_11098"}

{:event/type "shoton"
:event/elapsed 53
:event/subtype "blocked_shot"
:event/player1 "Giuseppe Colucci"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_1335684"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Yuto Nagatomo"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1335688"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 54
:event/subtype "hands"
:event/player1 "Andrea Cossu"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1335698"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Andrea Cossu"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1335726"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_11098"}

{:event/type "corner"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Andrea Cossu"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1335726"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Robert Acquafresca"
:event/subtype "pushing"
:event/player1 "Giuseppe Colucci"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1335729"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Davide Astori"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1335732"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Francesco Pisano"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1335742"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Radja Nainggolan"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1335755"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Fabio Caserta"
:event/subtype "pushing"
:event/player1 "Radja Nainggolan"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1335761"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 62
:event/subtype "hands"
:event/player1 "Alessandro Matri"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1335768"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_11098"}

{:event/type "shoton"
:event/elapsed 63
:event/subtype "shot"
:event/player1 "Emanuele Giaccherini"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1335773"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Luis Jimenez"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1335775"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_11098"}

{:event/type "corner"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Luis Jimenez"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1335775"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Luis Jimenez"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1335779"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_11098"}

{:event/type "corner"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Luis Jimenez"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1335779"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_11098"}

{:event/type "shotoff"
:event/elapsed 64
:event/subtype "shot"
:event/player1 "Fabio Caserta"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1335784"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Emanuele Giaccherini"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1335795"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Andrea Lazzari"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1335799"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Marco Parolo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1335804"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Andrea Cossu"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1335813"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_11098"}

{:event/type "shotoff"
:event/elapsed 69
:event/subtype "indirect freekick"
:event/player1 "Andrea Lazzari"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1335817"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Maurizio Lauro"
:event/player1 "Davide Biondini"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1335828"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Maurizio Lauro"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1335843"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Michael Agazzi"
:event/player1 "Fabio Caserta"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1335848"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Andrea Cossu"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1335862"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Fabio Caserta"
:event/player1 "Andrea Lazzari"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1335876"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 77
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1335878"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Andrea Cossu"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1335879"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_11098"}

{:event/type "corner"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Andrea Cossu"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1335879"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Andrea Cossu"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1335881"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 78
:event/player2 "Emanuele Giaccherini"
:event/player1 "Radja Nainggolan"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1335885"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 79
:event/subtype "hands"
:event/player1 "Luis Jimenez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1335891"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Alessandro Agostini"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1335902"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_11098"}

{:event/type "shotoff"
:event/elapsed 80
:event/subtype "header"
:event/player1 "Davide Biondini"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1335904"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 83
:event/player2 "Radja Nainggolan"
:event/subtype "serious_foul"
:event/player1 "Luis Jimenez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1335926"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_11098"}

{:event/type "card"
:event/elapsed 83
:event/card_type "y"
:event/player1 "Luis Jimenez"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_1335927"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_11098"}

{:event/type "shotoff"
:event/elapsed 84
:event/subtype "volley"
:event/player1 "Emanuele Giaccherini"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1335937"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player1 "Radja Nainggolan"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1335941"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_11098"}

{:event/type "shotoff"
:event/elapsed 86
:event/subtype "deflected"
:event/player1 "Luis Jimenez"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1335949"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_11098"}

{:event/type "corner"
:event/elapsed 86
:event/subtype "short"
:event/player1 "Emanuele Giaccherini"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1335953"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Fabio Caserta"
:event/player1 "Michele Canini"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1335961"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 87
:event/player1 "Igor Budan"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1335973"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Maximiliano Pellegrino"
:event/player1 "Alessandro Matri"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1336010"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Daniele Ragatzu"
:event/player1 "Giuseppe Colucci"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1336016"
:event/minute 91
:event/match_id "match_11098"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Andrea Lazzari"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1336025"
:event/minute 92
:event/match_id "match_11098"}

{:event/type "corner"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Andrea Lazzari"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1336025"
:event/minute 92
:event/match_id "match_11098"}

{:event/type "shotoff"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "bicycle_kick"
:event/player1 "Alessandro Matri"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1336029"
:event/minute 92
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Igor Budan"
:event/player1 "Davide Astori"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1336033"
:event/minute 93
:event/match_id "match_11098"}

{:event/type "shotoff"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "volley"
:event/player1 "Matias Ezequiel Schelotto"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1336038"
:event/minute 93
:event/match_id "match_11098"}

{:event/type "foulcommit"
:event/elapsed_plus 4
:event/elapsed 90
:event/player2 "Igor Budan"
:event/player1 "Gabriele Perico"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1336043"
:event/minute 94
:event/match_id "match_11098"}


]

