
;;# data
[
{:match/id "match_6141"
:match/league "France Ligue 1"
:match/hometeam "SM Caen"
:match/awayteam "AC Ajaccio"
:match/score "0:0"
:match/hometeam_goals "0"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 38
:event/card_type "y"
:event/player1 "Carl Medjani"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2027526"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_6141"}

{:event/type "card"
:event/elapsed 41
:event/card_type "y"
:event/player1 "Mehdi Mostefa"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2027532"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_6141"}

{:event/type "card"
:event/elapsed 53
:event/card_type "y"
:event/player1 "Fousseni Diawara"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2027737"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_6141"}

{:event/type "card"
:event/elapsed 67
:event/card_type "y"
:event/player1 "Ilan"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2027872"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_6141"}

{:event/type "card"
:event/elapsed 79
:event/card_type "y"
:event/player1 "Lenny Nangis"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2028035"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_6141"}


]

