
;;# data
[
{:match/id "match_21840"
:match/league "Spain LIGA BBVA"
:match/hometeam "Villarreal CF"
:match/awayteam "Racing Santander"
:match/score "2:0"
:match/hometeam_goals "2"
:match/awayteam_goals "0"}

{:event/type "goal"
:event/elapsed 28
:event/player1 "Joan Capdevila"
:event/sortorder 0
:event/team "home"
:event/id "event_419467"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_21840"}

{:event/type "goal"
:event/elapsed 32
:event/player1 "Joseba Llorente"
:event/sortorder 0
:event/team "home"
:event/id "event_419501"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_21840"}

{:event/type "card"
:event/elapsed 49
:event/card_type "y"
:event/player1 "Juan Valera"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_419862"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_21840"}

{:event/type "card"
:event/elapsed 55
:event/card_type "y"
:event/player1 "Diego Godin"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_420035"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_21840"}

{:event/type "card"
:event/elapsed 77
:event/card_type "y"
:event/player1 "Ezequiel Garay"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_420175"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_21840"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Ariel Ibagaza"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_420271"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_21840"}


]

