
;;# data
[
{:match/id "match_8256"
:match/league "Germany 1. Bundesliga"
:match/hometeam "1. FC Nürnberg"
:match/awayteam "FC Bayern Munich"
:match/score "1:1"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Mark van Bommel"
:event/player1 "Angelos Charisteas"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_960405"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_8256"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Mario Gomez"
:event/player1 "Andreas Wolf"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_960410"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_8256"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Mike Frantz"
:event/player1 "Mario Gomez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_960441"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_8256"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Arjen Robben"
:event/player1 "Javier Pinola"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_960467"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_8256"}

{:event/type "foulcommit"
:event/elapsed 13
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_960484"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_8256"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Philipp Lahm"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_960493"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_8256"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Arjen Robben"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_960497"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_8256"}

{:event/type "corner"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Arjen Robben"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_960497"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_8256"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Arjen Robben"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_960499"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_8256"}

{:event/type "corner"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Arjen Robben"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_960499"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_8256"}

{:event/type "shoton"
:event/elapsed 15
:event/subtype "blocked_shot"
:event/player1 "Mario Gomez"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_960503"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_8256"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Bastian Schweinsteiger"
:event/sortorder 5
:event/team "away"
:event/event_type "corner"
:event/id "event_960510"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_8256"}

{:event/type "corner"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Bastian Schweinsteiger"
:event/sortorder 5
:event/team "away"
:event/event_type "corner"
:event/id "event_960510"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_8256"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Arjen Robben"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_960522"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_8256"}

{:event/type "foulcommit"
:event/elapsed 21
:event/subtype "pushing"
:event/player1 "Mario Gomez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_960540"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_8256"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Arjen Robben"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_960562"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_8256"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Mike Frantz"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_960564"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_8256"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Mike Frantz"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_960571"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_8256"}

{:event/type "corner"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Mike Frantz"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_960571"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_8256"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Mike Frantz"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_960578"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_8256"}

{:event/type "corner"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Mike Frantz"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_960578"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_8256"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Arjen Robben"
:event/player1 "Ilkay Guendogan"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_960581"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_8256"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Mike Frantz"
:event/subtype "pushing"
:event/player1 "Ivica Olic"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_960589"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_8256"}

{:event/type "shotoff"
:event/elapsed 30
:event/subtype "deflected"
:event/player1 "Arjen Robben"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_960592"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_8256"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Bastian Schweinsteiger"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_960598"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_8256"}

{:event/type "corner"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Bastian Schweinsteiger"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_960598"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_8256"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Breno"
:event/subtype "from_behind"
:event/player1 "Ivica Olic"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_960614"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_8256"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Philipp Lahm"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_960640"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_8256"}

{:event/type "shotoff"
:event/elapsed 34
:event/subtype "distance"
:event/player1 "Mark van Bommel"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_960642"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_8256"}

{:event/type "foulcommit"
:event/elapsed 34
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_960646"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_8256"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Philipp Lahm"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_960660"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_8256"}

{:event/type "goal"
:event/elapsed 38
:event/player2 "Mario Gomez"
:event/subtype "shot"
:event/player1 "Thomas Mueller"
:event/sortorder 1
:event/team "away"
:event/id "event_960687"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_8256"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player1 "Mario Gomez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_960711"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_8256"}

{:event/type "foulcommit"
:event/elapsed 42
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_960728"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_8256"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Ivica Olic"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_960762"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_8256"}

{:event/type "shoton"
:event/elapsed 45
:event/subtype "blocked_shot"
:event/player1 "Arjen Robben"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_960763"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_8256"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Arjen Robben"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_960766"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_8256"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "big chance volley"
:event/player1 "Ivica Olic"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_960771"
:event/minute 46
:event/match_id "match_8256"}

{:event/type "foulcommit"
:event/elapsed 47
:event/player2 "Dennis Diekmeier"
:event/player1 "Diego Contento"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_960923"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_8256"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Javier Pinola"
:event/subtype "pushing"
:event/player1 "Hamit Altintop"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_960950"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_8256"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Mario Gomez"
:event/player1 "Breno"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_960965"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_8256"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Eric Maxim Choupo-Moting"
:event/player1 "Martin Demichelis"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_960985"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_8256"}

{:event/type "goal"
:event/elapsed 54
:event/player2 "Eric Maxim Choupo-Moting"
:event/subtype "shot"
:event/player1 "Ilkay Guendogan"
:event/sortorder 0
:event/team "home"
:event/id "event_960990"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_8256"}

{:event/type "shotoff"
:event/elapsed 55
:event/subtype "big chance shot"
:event/player1 "Ilkay Guendogan"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_961001"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_8256"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Bastian Schweinsteiger"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_961016"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_8256"}

{:event/type "corner"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Bastian Schweinsteiger"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_961016"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_8256"}

{:event/type "shotoff"
:event/elapsed 57
:event/subtype "shot"
:event/player1 "Albert Bunjaku"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_961025"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_8256"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Mario Gomez"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_961056"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_8256"}

{:event/type "shotoff"
:event/elapsed 60
:event/subtype "header"
:event/player1 "Ivica Olic"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_961057"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_8256"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Martin Demichelis"
:event/subtype "serious_foul"
:event/player1 "Albert Bunjaku"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_961063"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_8256"}

{:event/type "card"
:event/elapsed 61
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Albert Bunjaku"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_961064"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_8256"}

{:event/type "foulcommit"
:event/elapsed 64
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_961088"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_8256"}

{:event/type "shotoff"
:event/elapsed 64
:event/subtype "shot"
:event/player1 "Thomas Mueller"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_961089"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_8256"}

{:event/type "shotoff"
:event/elapsed 66
:event/subtype "shot"
:event/player1 "Dennis Diekmeier"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_961097"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_8256"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player1 "Mickaeel Tavares"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_961102"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_8256"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Mario Gomez"
:event/subtype "pushing"
:event/player1 "Andreas Wolf"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_961109"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_8256"}

{:event/type "shoton"
:event/elapsed 69
:event/subtype "blocked_shot"
:event/player1 "Bastian Schweinsteiger"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_961115"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_8256"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Javier Pinola"
:event/player1 "Miroslav Klose"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_961136"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_8256"}

{:event/type "foulcommit"
:event/elapsed 74
:event/subtype "hands"
:event/player1 "Eric Maxim Choupo-Moting"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_961138"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_8256"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Hamit Altintop"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_961142"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_8256"}

{:event/type "corner"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Hamit Altintop"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_961142"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_8256"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Thomas Mueller"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_961145"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_8256"}

{:event/type "shoton"
:event/elapsed 77
:event/subtype "big chance shot"
:event/player1 "Mario Gomez"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_961160"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_8256"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Holger Badstuber"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_961163"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_8256"}

{:event/type "corner"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Holger Badstuber"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_961163"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_8256"}

{:event/type "foulcommit"
:event/elapsed 78
:event/player1 "Martin Demichelis"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_961164"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_8256"}

{:event/type "shoton"
:event/elapsed 84
:event/subtype "shot"
:event/player1 "Mario Gomez"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_961226"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_8256"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Bastian Schweinsteiger"
:event/player1 "Marcel Risse"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_961239"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_8256"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Mark van Bommel"
:event/player1 "Ilkay Guendogan"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_961251"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_8256"}

{:event/type "foulcommit"
:event/elapsed 89
:event/subtype "serious_foul"
:event/player1 "Hamit Altintop"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_961286"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_8256"}

{:event/type "card"
:event/elapsed 89
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Hamit Altintop"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_961290"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_8256"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Hamit Altintop"
:event/subtype "shirt_pull"
:event/player1 "Christian Eigler"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_961311"
:event/minute 91
:event/match_id "match_8256"}

{:event/type "card"
:event/elapsed_plus 1
:event/elapsed 90
:event/card_type "y"
:event/subtype "shirt_pull"
:event/player1 "Christian Eigler"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_961313"
:event/minute 91
:event/match_id "match_8256"}


]

