
;;# data
[
{:match/id "match_9887"
:match/league "Germany 1. Bundesliga"
:match/hometeam "VfB Stuttgart"
:match/awayteam "Hamburger SV"
:match/score "2:1"
:match/hometeam_goals "2"
:match/awayteam_goals "1"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Filip Kostic"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4479537"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_9887"}

{:event/type "shotoff"
:event/elapsed 2
:event/subtype "deflected"
:event/player1 "Serey Die"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4479541"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_9887"}

{:event/type "corner"
:event/elapsed 2
:event/subtype "cross_left"
:event/player1 "Filip Kostic"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4479548"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_9887"}

{:event/type "shoton"
:event/elapsed 2
:event/subtype "shot"
:event/player1 "Serey Die"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_4479553"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Gojko Kacar"
:event/player1 "Daniel Didavi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4479605"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_9887"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Rafael van der Vaart"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4479609"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_9887"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Filip Kostic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4479674"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Pierre-Michel Lasogga"
:event/player1 "Martin Harnik"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4479699"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_9887"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Rafael van der Vaart"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4479703"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Martin Harnik"
:event/player1 "Marcell Jansen"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4479730"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_9887"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Daniel Didavi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4479737"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Gojko Kacar"
:event/player1 "Daniel Ginczek"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4479762"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_9887"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Rafael van der Vaart"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4479772"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_9887"}

{:event/type "goal"
:event/elapsed 12
:event/player2 "Rafael van der Vaart"
:event/subtype "header"
:event/player1 "Gojko Kacar"
:event/sortorder 2
:event/team "away"
:event/id "event_4479777"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Serey Die"
:event/player1 "Ivica Olic"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4479818"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Christian Gentner"
:event/player1 "Marcell Jansen"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4479838"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "Serey Die"
:event/player1 "Pierre-Michel Lasogga"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4479871"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_9887"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Filip Kostic"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4479878"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_9887"}

{:event/type "shoton"
:event/elapsed 17
:event/subtype "distance"
:event/player1 "Daniel Didavi"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4479890"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_9887"}

{:event/type "shoton"
:event/elapsed 18
:event/subtype "deflected"
:event/player1 "Pierre-Michel Lasogga"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4479902"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Rafael van der Vaart"
:event/player1 "Daniel Schwaab"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4479921"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_9887"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Daniel Didavi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4479950"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Gojko Kacar"
:event/player1 "Florian Klein"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4479952"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_9887"}

{:event/type "shotoff"
:event/elapsed 21
:event/subtype "distance"
:event/player1 "Marcell Jansen"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4479977"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Matthias Ostrzolek"
:event/player1 "Daniel Ginczek"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4480000"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_9887"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Heiko Westermann"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4480024"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Filip Kostic"
:event/player1 "Gojko Kacar"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4480041"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_9887"}

{:event/type "shoton"
:event/elapsed 27
:event/subtype "blocked_shot"
:event/player1 "Filip Kostic"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4480119"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_9887"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Daniel Schwaab"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4480138"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_9887"}

{:event/type "goal"
:event/elapsed 27
:event/subtype "shot"
:event/player1 "Christian Gentner"
:event/sortorder 2
:event/team "home"
:event/id "event_4480129"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_9887"}

{:event/type "shoton"
:event/elapsed 29
:event/subtype "distance"
:event/player1 "Christian Gentner"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4480175"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_9887"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Daniel Didavi"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4480229"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Timo Baumgartl"
:event/player1 "Rafael van der Vaart"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4480462"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_9887"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Daniel Ginczek"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4480289"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_9887"}

{:event/type "corner"
:event/elapsed 34
:event/subtype "cross_right"
:event/player1 "Filip Kostic"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4480302"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed 34
:event/player2 "Daniel Didavi"
:event/player1 "Heiko Westermann"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4480325"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_9887"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Filip Kostic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4480330"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_9887"}

{:event/type "corner"
:event/elapsed 35
:event/subtype "cross_left"
:event/player1 "Filip Kostic"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4480351"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_9887"}

{:event/type "goal"
:event/elapsed 35
:event/subtype "shot"
:event/player1 "Martin Harnik"
:event/sortorder 4
:event/team "home"
:event/id "event_4480361"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed 39
:event/subtype "hands"
:event/player1 "Heiko Westermann"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4480514"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_9887"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Filip Kostic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4480523"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_9887"}

{:event/type "shoton"
:event/elapsed 40
:event/subtype "blocked_shot"
:event/player1 "Daniel Schwaab"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4480528"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_9887"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Ivica Olic"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4480563"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_9887"}

{:event/type "corner"
:event/elapsed 42
:event/subtype "cross_right"
:event/player1 "Rafael van der Vaart"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4480613"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_9887"}

{:event/type "shoton"
:event/elapsed 42
:event/subtype "blocked_header"
:event/player1 "Johan Djourou"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4480620"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_9887"}

{:event/type "shotoff"
:event/elapsed 44
:event/subtype "shot"
:event/player1 "Martin Harnik"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4480654"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed 45
:event/subtype "hands"
:event/player1 "Ivo Ilicevic"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4480721"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "Johan Djourou"
:event/player1 "Daniel Didavi"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4480989"
:event/minute 46
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "Christian Gentner"
:event/player1 "Rafael van der Vaart"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4480739"
:event/minute 46
:event/match_id "match_9887"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Ivo Ilicevic"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4481023"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_9887"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Heiko Westermann"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4481037"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_9887"}

{:event/type "shotoff"
:event/elapsed 48
:event/subtype "header"
:event/player1 "Pierre-Michel Lasogga"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4481041"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_9887"}

{:event/type "shotoff"
:event/elapsed 48
:event/subtype "big chance shot"
:event/player1 "Filip Kostic"
:event/sortorder 5
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4481066"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Daniel Didavi"
:event/player1 "Gojko Kacar"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4481140"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_9887"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Filip Kostic"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4481158"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_9887"}

{:event/type "corner"
:event/elapsed 52
:event/subtype "cross_right"
:event/player1 "Filip Kostic"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4481182"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Marcell Jansen"
:event/player1 "Christian Gentner"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4481211"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_9887"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Matthias Ostrzolek"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4481225"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_9887"}

{:event/type "shotoff"
:event/elapsed 53
:event/subtype "distance"
:event/player1 "Johan Djourou"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4481238"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_9887"}

{:event/type "card"
:event/elapsed 56
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Rene Adler"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_4481343"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Antonio Ruediger"
:event/subtype "pushing"
:event/player1 "Ivica Olic"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4481383"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_9887"}

{:event/type "card"
:event/elapsed 58
:event/card_type "y"
:event/player1 "Ivica Olic"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4481399"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed 59
:event/player2 "Christian Gentner"
:event/player1 "Slobodan Rajkovic"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4481448"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Daniel Didavi"
:event/player1 "Rafael van der Vaart"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4481483"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_9887"}

{:event/type "shotoff"
:event/elapsed 61
:event/subtype "direct_freekick"
:event/player1 "Daniel Didavi"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4481485"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_9887"}

{:event/type "shoton"
:event/elapsed 61
:event/subtype "shot"
:event/player1 "Daniel Didavi"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_4481505"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_9887"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Filip Kostic"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_4481508"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_9887"}

{:event/type "corner"
:event/elapsed 62
:event/subtype "short_right"
:event/player1 "Filip Kostic"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_4481528"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_9887"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Daniel Schwaab"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_4481531"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_9887"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Daniel Schwaab"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4481534"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_9887"}

{:event/type "shoton"
:event/elapsed 63
:event/subtype "header"
:event/player1 "Timo Baumgartl"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4481537"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_9887"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Florian Klein"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4481559"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Christian Gentner"
:event/player1 "Heiko Westermann"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4481688"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_9887"}

{:event/type "card"
:event/elapsed 69
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Gojko Kacar"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_4481694"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_9887"}

{:event/type "card"
:event/elapsed 69
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Daniel Didavi"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4481698"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_9887"}

{:event/type "shotoff"
:event/elapsed 70
:event/subtype "direct_freekick"
:event/player1 "Daniel Didavi"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4481714"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_9887"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Ivica Olic"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4481733"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_9887"}

{:event/type "corner"
:event/elapsed 72
:event/subtype "cross_left"
:event/player1 "Rafael van der Vaart"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4481735"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_9887"}

{:event/type "shoton"
:event/elapsed 73
:event/subtype "distance"
:event/player1 "Daniel Didavi"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4481762"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_9887"}

{:event/type "shotoff"
:event/elapsed 74
:event/subtype "distance"
:event/player1 "Filip Kostic"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4481793"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Filip Kostic"
:event/player1 "Heiko Westermann"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4481908"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed 78
:event/player2 "Daniel Ginczek"
:event/player1 "Heiko Westermann"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4481920"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed 79
:event/player2 "Alexandru Maxim"
:event/player1 "Rafael van der Vaart"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4481965"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Antonio Ruediger"
:event/player1 "Zoltan Stieber"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4482046"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_9887"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Filip Kostic"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4482070"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_9887"}

{:event/type "shotoff"
:event/elapsed 82
:event/subtype "deflected"
:event/player1 "Martin Harnik"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4482074"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_9887"}

{:event/type "corner"
:event/elapsed 82
:event/subtype "cross_left"
:event/player1 "Filip Kostic"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_4482078"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_9887"}

{:event/type "shoton"
:event/elapsed 83
:event/subtype "shot"
:event/player1 "Daniel Ginczek"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4482087"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_9887"}

{:event/type "shoton"
:event/elapsed 83
:event/subtype "big chance shot"
:event/player1 "Filip Kostic"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4482112"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Artjoms Rudnevs"
:event/player1 "Timo Baumgartl"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4482202"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_9887"}

{:event/type "shoton"
:event/elapsed 87
:event/subtype "blocked_shot"
:event/player1 "Artjoms Rudnevs"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4482380"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_9887"}

{:event/type "shoton"
:event/elapsed 89
:event/subtype "big chance shot"
:event/player1 "Timo Werner"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4482291"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_9887"}

{:event/type "corner"
:event/elapsed 89
:event/subtype "short_left"
:event/player1 "Filip Kostic"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4482302"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_9887"}

{:event/type "corner"
:event/elapsed 90
:event/subtype "short_left"
:event/player1 "Filip Kostic"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4482329"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Rafael van der Vaart"
:event/player1 "Alexandru Maxim"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4482337"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_9887"}

{:event/type "corner"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "short_left"
:event/player1 "Alexandru Maxim"
:event/sortorder 5
:event/team "home"
:event/event_type "corner"
:event/id "event_4482435"
:event/minute 92
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Alexandru Maxim"
:event/subtype "trip"
:event/player1 "Rafael van der Vaart"
:event/sortorder 7
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4482449"
:event/minute 93
:event/match_id "match_9887"}

{:event/type "card"
:event/elapsed_plus 3
:event/elapsed 90
:event/card_type "y"
:event/player1 "Rafael van der Vaart"
:event/sortorder 8
:event/team "away"
:event/event_type "card"
:event/id "event_4482454"
:event/minute 93
:event/match_id "match_9887"}

{:event/type "foulcommit"
:event/elapsed_plus 4
:event/elapsed 90
:event/player2 "Filip Kostic"
:event/subtype "serious_foul"
:event/player1 "Heiko Westermann"
:event/sortorder 11
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4482484"
:event/minute 94
:event/match_id "match_9887"}

{:event/type "card"
:event/elapsed_plus 4
:event/elapsed 90
:event/card_type "y"
:event/player1 "Heiko Westermann"
:event/sortorder 12
:event/team "away"
:event/event_type "card"
:event/id "event_4482485"
:event/minute 94
:event/match_id "match_9887"}


]

