
;;# data
[
{:match/id "match_9707"
:match/league "Germany 1. Bundesliga"
:match/hometeam "SC Freiburg"
:match/awayteam "Hamburger SV"
:match/score "1:0"
:match/hometeam_goals "0"
:match/awayteam_goals "0"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Felix Klaus"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4006649"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_9707"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Felix Klaus"
:event/subtype "penalty"
:event/player1 "Ronny Marcos"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4006658"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_9707"}

{:event/type "goal"
:event/elapsed 3
:event/subtype "saved_back_into_play"
:event/player1 "Vladimir Darida"
:event/sortorder 0
:event/team "home"
:event/id "event_4006661"
:event/event_type "goal"
:event/goal_type "npm"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_9707"}

{:event/type "shotoff"
:event/elapsed 4
:event/subtype "header"
:event/player1 "Valon Behrami"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4006673"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_9707"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Rafael van der Vaart"
:event/subtype "pushing"
:event/player1 "Karim Guede"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4006678"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_9707"}

{:event/type "foulcommit"
:event/elapsed 6
:event/player2 "Artjoms Rudnevs"
:event/subtype "pull"
:event/player1 "Christian Guenter"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4006697"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_9707"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Rafael van der Vaart"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4006707"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_9707"}

{:event/type "foulcommit"
:event/elapsed 8
:event/player2 "Cleber"
:event/subtype "trip"
:event/player1 "Admir Mehmedi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4006717"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_9707"}

{:event/type "corner"
:event/elapsed 8
:event/subtype "short_left"
:event/player1 "Admir Mehmedi"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4006727"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_9707"}

{:event/type "corner"
:event/elapsed 9
:event/subtype "cross_left"
:event/player1 "Nicolas Hoefler"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4006732"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_9707"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Ronny Marcos"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4006741"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_9707"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Pierre-Michel Lasogga"
:event/subtype "pushing"
:event/player1 "Marc-Oliver Kempf"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4006779"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_9707"}

{:event/type "cross"
:event/elapsed 13
:event/subtype "cross"
:event/player1 "Rafael van der Vaart"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4006780"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_9707"}

{:event/type "shotoff"
:event/elapsed 13
:event/subtype "header"
:event/player1 "Pierre-Michel Lasogga"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4006781"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_9707"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Johan Djourou"
:event/subtype "pushing"
:event/player1 "Admir Mehmedi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4006794"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_9707"}

{:event/type "corner"
:event/elapsed 17
:event/subtype "cross_right"
:event/player1 "Rafael van der Vaart"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4006824"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_9707"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Sascha Riether"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4006837"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_9707"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Ronny Marcos"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4006855"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_9707"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Dennis Diekmeier"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4006872"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_9707"}

{:event/type "shoton"
:event/elapsed 21
:event/subtype "distance"
:event/player1 "Valon Behrami"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4006874"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_9707"}

{:event/type "shoton"
:event/elapsed 22
:event/subtype "blocked_shot"
:event/player1 "Admir Mehmedi"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4006885"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_9707"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Nicolai Mueller"
:event/subtype "trip"
:event/player1 "Admir Mehmedi"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4006893"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_9707"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Ronny Marcos"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4006898"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_9707"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Felix Klaus"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4006911"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_9707"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Vladimir Darida"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4006917"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_9707"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_4006951"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_9707"}

{:event/type "shotoff"
:event/elapsed 31
:event/subtype "distance"
:event/player1 "Pierre-Michel Lasogga"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4007000"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_9707"}

{:event/type "foulcommit"
:event/elapsed 31
:event/subtype "hands"
:event/player1 "Karim Guede"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4007010"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_9707"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Ronny Marcos"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4007022"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_9707"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Valon Behrami"
:event/subtype "trip"
:event/player1 "Karim Guede"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4007030"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_9707"}

{:event/type "foulcommit"
:event/elapsed 34
:event/player2 "Vladimir Darida"
:event/subtype "dangerous_play"
:event/player1 "Rafael van der Vaart"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4007064"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_9707"}

{:event/type "shotoff"
:event/elapsed 35
:event/subtype "distance"
:event/player1 "Artjoms Rudnevs"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4007093"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_9707"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_4007142"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_9707"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Felix Klaus"
:event/subtype "pull"
:event/player1 "Valon Behrami"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4007159"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_9707"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Christian Guenter"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4007170"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_9707"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Dennis Diekmeier"
:event/subtype "trip"
:event/player1 "Marc Torrejon Moya"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4007188"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_9707"}

{:event/type "card"
:event/elapsed 40
:event/card_type "y"
:event/player1 "Marc Torrejon Moya"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4007196"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_9707"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Felix Klaus"
:event/subtype "trip"
:event/player1 "Cleber"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4007215"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_9707"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_4007281"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_9707"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Rafael van der Vaart"
:event/subtype "pushing"
:event/player1 "Nicolas Hoefler"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4007302"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_9707"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Rafael van der Vaart"
:event/subtype "trip"
:event/player1 "Vladimir Darida"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4007323"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_9707"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Felix Klaus"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4007691"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_9707"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 45
:event/player2 "Pierre-Michel Lasogga"
:event/subtype "pushing"
:event/player1 "Felix Klaus"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4007370"
:event/minute 47
:event/match_id "match_9707"}

{:event/type "corner"
:event/elapsed 48
:event/subtype "cross_right"
:event/player1 "Christian Guenter"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4007702"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_9707"}

{:event/type "shoton"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "direct_freekick"
:event/player1 "Pierre-Michel Lasogga"
:event/sortorder 5
:event/team "away"
:event/event_type "shoton"
:event/id "event_4007389"
:event/minute 48
:event/match_id "match_9707"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Felix Klaus"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4007760"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_9707"}

{:event/type "shoton"
:event/elapsed 50
:event/subtype "header"
:event/player1 "Jonathan Schmid"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4007766"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_9707"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Karim Guede"
:event/subtype "dangerous_play"
:event/player1 "Cleber"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4007793"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_9707"}

{:event/type "shotoff"
:event/elapsed 52
:event/subtype "shot"
:event/player1 "Jonathan Schmid"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4007806"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_9707"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Nicolai Mueller"
:event/subtype "pull"
:event/player1 "Christian Guenter"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4007885"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_9707"}

{:event/type "card"
:event/elapsed 54
:event/card_type "y"
:event/player1 "Christian Guenter"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4007890"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_9707"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Rafael van der Vaart"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4007893"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_9707"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Roman Buerki"
:event/subtype "pushing"
:event/player1 "Cleber"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4007901"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_9707"}

{:event/type "card"
:event/elapsed 55
:event/card_type "y"
:event/player1 "Cleber"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_4007908"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_9707"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Felix Klaus"
:event/subtype "obstruction"
:event/player1 "Nicolai Mueller"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4007963"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_9707"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Dennis Diekmeier"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4007990"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_9707"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Felix Klaus"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4008020"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_9707"}

{:event/type "shoton"
:event/elapsed 61
:event/subtype "distance"
:event/player1 "Julian Schuster"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4008028"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_9707"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Vladimir Darida"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4008046"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_9707"}

{:event/type "shoton"
:event/elapsed 64
:event/subtype "deflected"
:event/player1 "Nicolai Mueller"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4008070"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_9707"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Vladimir Darida"
:event/subtype "trip"
:event/player1 "Valon Behrami"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4008076"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_9707"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Nicolas Hoefler"
:event/subtype "dangerous_play"
:event/player1 "Valon Behrami"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4008121"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_9707"}

{:event/type "card"
:event/elapsed 69
:event/card_type "y"
:event/player1 "Valon Behrami"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4008124"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_9707"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Johan Djourou"
:event/subtype "trip"
:event/player1 "Admir Mehmedi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4008142"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_9707"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Valon Behrami"
:event/subtype "pull"
:event/player1 "Dani Schahin"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4008179"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_9707"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Ronny Marcos"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4008187"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_9707"}

{:event/type "shotoff"
:event/elapsed 74
:event/subtype "header"
:event/player1 "Mohamed Gouaida"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4008192"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_9707"}

{:event/type "foulcommit"
:event/elapsed 76
:event/player2 "Lewis Holtby"
:event/subtype "from_behind"
:event/player1 "Julian Schuster"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4008243"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_9707"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Jonathan Schmid"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4008277"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_9707"}

{:event/type "shoton"
:event/elapsed 77
:event/subtype "deflected"
:event/player1 "Lewis Holtby"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_4008292"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_9707"}

{:event/type "corner"
:event/elapsed 77
:event/subtype "cross_left"
:event/player1 "Lewis Holtby"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_4008300"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_9707"}

{:event/type "shotoff"
:event/elapsed 79
:event/subtype "volley"
:event/player1 "Petr Jiracek"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4008331"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_9707"}

{:event/type "foulcommit"
:event/elapsed 79
:event/player2 "Mohamed Gouaida"
:event/subtype "trip"
:event/player1 "Julian Schuster"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4008352"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_9707"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Lewis Holtby"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4008365"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_9707"}

{:event/type "shoton"
:event/elapsed 80
:event/subtype "header"
:event/player1 "Petr Jiracek"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4008374"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_9707"}

{:event/type "shoton"
:event/elapsed 82
:event/subtype "deflected"
:event/player1 "Philipp Zulechner"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4008434"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_9707"}

{:event/type "corner"
:event/elapsed 82
:event/subtype "cross_right"
:event/player1 "Jonathan Schmid"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_4008436"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_9707"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Dennis Diekmeier"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4008452"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_9707"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Cleber"
:event/subtype "pull"
:event/player1 "Philipp Zulechner"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4008486"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_9707"}

{:event/type "shotoff"
:event/elapsed 86
:event/subtype "shot"
:event/player1 "Dani Schahin"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4008540"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_9707"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Jonathan Schmid"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4008592"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_9707"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Jonathan Schmid"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4008624"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_9707"}

{:event/type "shotoff"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "miss_kick"
:event/player1 "Lewis Holtby"
:event/sortorder 8
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4008748"
:event/minute 93
:event/match_id "match_9707"}

{:event/type "shoton"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Admir Mehmedi"
:event/sortorder 10
:event/team "home"
:event/event_type "shoton"
:event/id "event_4008757"
:event/minute 94
:event/match_id "match_9707"}


]

