
;;# data
[
{:match/id "match_12721"
:match/league "Italy Serie A"
:match/hometeam "Chievo Verona"
:match/awayteam "Palermo"
:match/score "2:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Alberto Paloschi"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4283104"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_4283106"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Matias Ezequiel Schelotto"
:event/subtype "trip"
:event/player1 "Franco Vazquez"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4283108"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Valter Birsa"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4283115"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/sortorder 3
:event/team "home"
:event/event_type "throwin"
:event/id "event_4283121"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Nicholas Sebastian Frey"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_4283124"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_4283126"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_12721"}

{:event/type "shotoff"
:event/elapsed 4
:event/subtype "volley"
:event/player1 "Riccardo Meggiorini"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4283128"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 6
:event/player2 "Riccardo Meggiorini"
:event/subtype "trip"
:event/player1 "Enzo Maresca"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4283148"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_12721"}

{:event/type "shotoff"
:event/elapsed 7
:event/subtype "shot"
:event/player1 "Paulo Dybala"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4283156"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Ervin Zukanovic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4283180"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Nicholas Sebastian Frey"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4283184"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_12721"}

{:event/type "shotoff"
:event/elapsed 10
:event/subtype "deflected"
:event/player1 "Riccardo Meggiorini"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4283190"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_12721"}

{:event/type "corner"
:event/elapsed 10
:event/subtype "cross_right"
:event/player1 "Valter Birsa"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4283194"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_12721"}

{:event/type "shoton"
:event/elapsed 10
:event/subtype "blocked_shot"
:event/player1 "Mariano Julio Izco"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_4283206"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Ervin Zukanovic"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_4283208"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Franco Vazquez"
:event/subtype "trip"
:event/player1 "Mariano Julio Izco"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4283215"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Sinisa Andjelkovic"
:event/subtype "pull"
:event/player1 "Alberto Paloschi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4283232"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_12721"}

{:event/type "shoton"
:event/elapsed 13
:event/subtype "shot"
:event/player1 "Paulo Dybala"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4283246"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_12721"}

{:event/type "corner"
:event/elapsed 13
:event/subtype "cross_right"
:event/player1 "Edgar Barreto"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_4283251"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Nicholas Sebastian Frey"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4283278"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_12721"}

{:event/type "shoton"
:event/elapsed 15
:event/subtype "volley"
:event/player1 "Valter Birsa"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4283280"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_12721"}

{:event/type "shoton"
:event/elapsed 16
:event/subtype "deflected"
:event/player1 "Riccardo Meggiorini"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4283287"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_12721"}

{:event/type "shotoff"
:event/elapsed 17
:event/subtype "shot"
:event/player1 "Robin Quaison"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4283296"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Ivan Radovanovic"
:event/subtype "trip"
:event/player1 "Luca Rigoni"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4283319"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Valter Birsa"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4283323"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Franco Vazquez"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4283336"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Franco Vazquez"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4283341"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Franco Vazquez"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4283346"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_12721"}

{:event/type "shotoff"
:event/elapsed 24
:event/subtype "volley"
:event/player1 "Valter Birsa"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4283373"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_12721"}

{:event/type "corner"
:event/elapsed 25
:event/subtype "cross_right"
:event/player1 "Franco Vazquez"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4283394"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_12721"}

{:event/type "shotoff"
:event/elapsed 25
:event/subtype "volley"
:event/player1 "Enzo Maresca"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4283396"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Sinisa Andjelkovic"
:event/subtype "pushing"
:event/player1 "Alberto Paloschi"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4283401"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Fabio Daprela"
:event/subtype "trip"
:event/player1 "Matias Ezequiel Schelotto"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4283417"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Alberto Paloschi"
:event/subtype "trip"
:event/player1 "Enzo Maresca"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4283436"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_12721"}

{:event/type "card"
:event/elapsed 29
:event/card_type "y"
:event/player1 "Enzo Maresca"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4283439"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 30
:event/player2 "Edgar Barreto"
:event/subtype "pushing"
:event/player1 "Nicholas Sebastian Frey"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4283457"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Enzo Maresca"
:event/subtype "trip"
:event/player1 "Mariano Julio Izco"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4283468"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Matias Ezequiel Schelotto"
:event/subtype "pushing"
:event/player1 "Robin Quaison"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4283495"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_12721"}

{:event/type "goal"
:event/elapsed 36
:event/player2 "Riccardo Meggiorini"
:event/subtype "shot"
:event/player1 "Alberto Paloschi"
:event/sortorder 0
:event/team "home"
:event/id "event_4283550"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Mariano Julio Izco"
:event/subtype "trip"
:event/player1 "Luca Rigoni"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4283601"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Nicholas Sebastian Frey"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4283631"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Franco Vazquez"
:event/subtype "trip"
:event/player1 "Mariano Julio Izco"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4283653"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_12721"}

{:event/type "card"
:event/elapsed 42
:event/card_type "y"
:event/player1 "Mariano Julio Izco"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4283654"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_12721"}

{:event/type "shotoff"
:event/elapsed 43
:event/subtype "direct_freekick"
:event/player1 "Enzo Maresca"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4283679"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Franco Vazquez"
:event/subtype "trip"
:event/player1 "Riccardo Meggiorini"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4283691"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Mariano Julio Izco"
:event/subtype "trip"
:event/player1 "Franco Vazquez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4283695"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_12721"}

{:event/type "shoton"
:event/elapsed 45
:event/subtype "blocked_shot"
:event/player1 "Riccardo Meggiorini"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4283703"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Fabio Daprela"
:event/subtype "pushing"
:event/player1 "Alberto Paloschi"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4283707"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 46
:event/player2 "Paulo Dybala"
:event/subtype "trip"
:event/player1 "Dario Dainelli"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4283839"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Paulo Dybala"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4283847"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Robin Quaison"
:event/subtype "trip"
:event/player1 "Bostjan Cesar"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4283857"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Edgar Barreto"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4283862"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Roberto Vitiello"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4283867"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Alberto Paloschi"
:event/subtype "trip"
:event/player1 "Fabio Daprela"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4283872"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Ivan Radovanovic"
:event/subtype "trip"
:event/player1 "Robin Quaison"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4283886"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_12721"}

{:event/type "corner"
:event/elapsed 52
:event/subtype "cross_left"
:event/player1 "Valter Birsa"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4283902"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_12721"}

{:event/type "shoton"
:event/elapsed 52
:event/subtype "header"
:event/player1 "Ervin Zukanovic"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4283905"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/sortorder 2
:event/team "home"
:event/event_type "throwin"
:event/id "event_4283908"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Ivan Radovanovic"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_4283911"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_12721"}

{:event/type "corner"
:event/elapsed 53
:event/subtype "cross_right"
:event/player1 "Valter Birsa"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4283914"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Bostjan Cesar"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4283930"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Riccardo Meggiorini"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4283951"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Ervin Zukanovic"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4283958"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Valter Birsa"
:event/subtype "trip"
:event/player1 "Luca Rigoni"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4283967"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Ivan Radovanovic"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4283989"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Roberto Vitiello"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4284004"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_12721"}

{:event/type "shotoff"
:event/elapsed 59
:event/subtype "shot"
:event/player1 "Andrea Belotti"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4284005"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_12721"}

{:event/type "shotoff"
:event/elapsed 60
:event/subtype "shot"
:event/player1 "Riccardo Meggiorini"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4284019"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Ivan Radovanovic"
:event/subtype "pull"
:event/player1 "Paulo Dybala"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4284032"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 61
:event/subtype "penalty"
:event/player1 "Sinisa Andjelkovic"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4284034"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_12721"}

{:event/type "card"
:event/elapsed 61
:event/card_type "y"
:event/player1 "Sinisa Andjelkovic"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_4284035"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_12721"}

{:event/type "goal"
:event/elapsed 62
:event/subtype "missed"
:event/player1 "Alberto Paloschi"
:event/sortorder 0
:event/team "home"
:event/id "event_4284041"
:event/event_type "goal"
:event/goal_type "npm"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_12721"}

{:event/type "shotoff"
:event/elapsed 63
:event/subtype "deflected"
:event/player1 "Andrea Belotti"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4284052"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_12721"}

{:event/type "corner"
:event/elapsed 63
:event/subtype "cross_right"
:event/player1 "Paulo Dybala"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4284054"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Nicholas Sebastian Frey"
:event/subtype "pushing"
:event/player1 "Claudio Terzi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4284057"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Paulo Dybala"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4284061"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_12721"}

{:event/type "corner"
:event/elapsed 65
:event/subtype "cross_left"
:event/player1 "Paulo Dybala"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4284065"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_12721"}

{:event/type "shotoff"
:event/elapsed 66
:event/subtype "header"
:event/player1 "Sinisa Andjelkovic"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4284066"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Riccardo Meggiorini"
:event/subtype "pushing"
:event/player1 "Franco Vazquez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4284079"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Ruben Botta"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4284089"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Fabio Daprela"
:event/subtype "pull"
:event/player1 "Alberto Paloschi"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4284090"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_12721"}

{:event/type "shoton"
:event/elapsed 70
:event/subtype "blocked_shot"
:event/player1 "Franco Vazquez"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4284105"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_12721"}

{:event/type "shoton"
:event/elapsed 70
:event/subtype "blocked_shot"
:event/player1 "Luca Rigoni"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_4284110"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Achraf Lazaar"
:event/subtype "pull"
:event/player1 "Riccardo Meggiorini"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4284111"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_12721"}

{:event/type "shoton"
:event/elapsed 71
:event/subtype "blocked_shot"
:event/player1 "Ivan Radovanovic"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4284116"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Paulo Dybala"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4284119"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Roberto Vitiello"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4284133"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Ruben Botta"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4284143"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_12721"}

{:event/type "shoton"
:event/elapsed 75
:event/subtype "big chance shot"
:event/player1 "Alberto Paloschi"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4284145"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Franco Vazquez"
:event/subtype "serious_foul"
:event/player1 "Dario Dainelli"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4284147"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_12721"}

{:event/type "shotoff"
:event/elapsed 76
:event/subtype "direct_freekick"
:event/player1 "Edgar Barreto"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4284156"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Ivan Radovanovic"
:event/subtype "pushing"
:event/player1 "Franco Vazquez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4284173"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_12721"}

{:event/type "shotoff"
:event/elapsed 78
:event/subtype "volley"
:event/player1 "Paulo Dybala"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4284190"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_12721"}

{:event/type "corner"
:event/elapsed 79
:event/subtype "cross_right"
:event/player1 "Ruben Botta"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4284203"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_12721"}

{:event/type "corner"
:event/elapsed 79
:event/subtype "cross_right"
:event/player1 "Ruben Botta"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4284206"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 79
:event/player2 "Cristiano Biraghi"
:event/subtype "trip"
:event/player1 "Franco Vazquez"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4284210"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Ivan Radovanovic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4284211"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Andrea Rispoli"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4284217"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_12721"}

{:event/type "corner"
:event/elapsed 81
:event/subtype "cross_right"
:event/player1 "Paulo Dybala"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4284222"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_12721"}

{:event/type "shotoff"
:event/elapsed 81
:event/subtype "crossbar"
:event/player1 "Franco Vazquez"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4284224"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_12721"}

{:event/type "shoton"
:event/elapsed 81
:event/subtype "distance"
:event/player1 "Cristiano Biraghi"
:event/sortorder 5
:event/team "home"
:event/event_type "shoton"
:event/id "event_4284231"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_12721"}

{:event/type "shoton"
:event/elapsed 82
:event/subtype "shot"
:event/player1 "Edgar Barreto"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4284247"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Achraf Lazaar"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4284257"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_12721"}

{:event/type "shotoff"
:event/elapsed 83
:event/subtype "header"
:event/player1 "Andrea Belotti"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4284260"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Andrea Rispoli"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4284267"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_12721"}

{:event/type "corner"
:event/elapsed 84
:event/subtype "short_right"
:event/player1 "Andrea Rispoli"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_4284271"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Paulo Dybala"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_4284272"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Achraf Lazaar"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4284276"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Sinisa Andjelkovic"
:event/subtype "pushing"
:event/player1 "Sergio Pellissier"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4284287"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Enzo Maresca"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4284289"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Franco Vazquez"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4284294"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Ruben Botta"
:event/subtype "pull"
:event/player1 "Sinisa Andjelkovic"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4284299"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_12721"}

{:event/type "card"
:event/elapsed 86
:event/card_type "y"
:event/player1 "Sinisa Andjelkovic"
:event/sortorder 5
:event/team "away"
:event/event_type "card"
:event/id "event_4284301"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Cristiano Biraghi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4284307"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_12721"}

{:event/type "corner"
:event/elapsed 87
:event/subtype "cross_left"
:event/player1 "Paulo Dybala"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4284311"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Edgar Barreto"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4284324"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_12721"}

{:event/type "corner"
:event/elapsed 89
:event/subtype "cross_left"
:event/player1 "Edgar Barreto"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4284329"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_12721"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Andrea Belotti"
:event/subtype "pushing"
:event/player1 "Dario Dainelli"
:event/sortorder 5
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4284356"
:event/minute 91
:event/match_id "match_12721"}

{:event/type "shotoff"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "distance"
:event/player1 "Paulo Dybala"
:event/sortorder 6
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4284380"
:event/minute 93
:event/match_id "match_12721"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Paulo Dybala"
:event/sortorder 8
:event/team "away"
:event/event_type "cross"
:event/id "event_4284388"
:event/minute 94
:event/match_id "match_12721"}

{:event/type "shoton"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "distance"
:event/player1 "Achraf Lazaar"
:event/sortorder 10
:event/team "away"
:event/event_type "shoton"
:event/id "event_4284395"
:event/minute 94
:event/match_id "match_12721"}


]

