
;;# data
[
{:match/id "match_1997"
:match/league "England Premier League"
:match/hometeam "Wigan Athletic"
:match/awayteam "Manchester United"
:match/score "1:2"
:match/hometeam_goals "1"
:match/awayteam_goals "2"}

{:event/type "shotoff"
:event/elapsed 1
:event/subtype "shot"
:event/player1 "Antonio Valencia"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_679992"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_1997"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Paul Scharner"
:event/player1 "Paul Scholes"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_680001"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_1997"}

{:event/type "shoton"
:event/elapsed 4
:event/subtype "blocked_shot"
:event/player1 "Michael Brown"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_680006"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Dimitar Berbatov"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_680051"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_1997"}

{:event/type "shotoff"
:event/elapsed 10
:event/subtype "header"
:event/player1 "Wayne Rooney"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_680052"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_680059"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_1997"}

{:event/type "shotoff"
:event/elapsed 11
:event/subtype "shot"
:event/player1 "Michael Carrick"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_680060"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_1997"}

{:event/type "foulcommit"
:event/elapsed 14
:event/subtype "hands"
:event/player1 "Paul Scholes"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_680084"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_1997"}

{:event/type "shoton"
:event/elapsed 14
:event/subtype "direct_freekick"
:event/player1 "Charles N'Zogbia"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_680091"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Charles N'Zogbia"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_680097"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_1997"}

{:event/type "corner"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Charles N'Zogbia"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_680097"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_1997"}

{:event/type "foulcommit"
:event/elapsed 15
:event/subtype "hands"
:event/player1 "Lee Cattermole"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_680100"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Michael Carrick"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_680110"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_1997"}

{:event/type "shoton"
:event/elapsed 16
:event/subtype "distance"
:event/player1 "Hugo Rodallega"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_680114"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Charles N'Zogbia"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_680139"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_1997"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Michael Carrick"
:event/player1 "Charles N'Zogbia"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_680142"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_1997"}

{:event/type "shotoff"
:event/elapsed 20
:event/subtype "distance"
:event/player1 "Michael Carrick"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_680144"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_1997"}

{:event/type "foulcommit"
:event/elapsed 21
:event/subtype "hands"
:event/player1 "Lee Cattermole"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_680155"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_1997"}

{:event/type "shoton"
:event/elapsed 21
:event/subtype "blocked_shot"
:event/player1 "Wayne Rooney"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_680162"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_1997"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Patrice Evra"
:event/player1 "Emmerson Boyce"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_680172"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_1997"}

{:event/type "shoton"
:event/elapsed 24
:event/subtype "blocked_shot"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_680183"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_1997"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Dimitar Berbatov"
:event/player1 "Paul Scharner"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_680189"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Patrice Evra"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_680194"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Charles N'Zogbia"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_680200"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_1997"}

{:event/type "shotoff"
:event/elapsed 26
:event/subtype "shot"
:event/player1 "Maynor Figueroa"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_680204"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_1997"}

{:event/type "goal"
:event/elapsed 28
:event/player2 "Lee Cattermole"
:event/subtype "shot"
:event/player1 "Hugo Rodallega"
:event/sortorder 0
:event/team "home"
:event/id "event_680224"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Antonio Valencia"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_680234"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Wayne Rooney"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_680241"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_1997"}

{:event/type "shotoff"
:event/elapsed 32
:event/subtype "distance"
:event/player1 "Charles N'Zogbia"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_680250"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_680262"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_1997"}

{:event/type "corner"
:event/elapsed 33
:event/subtype "short"
:event/player1 "Wayne Rooney"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_680264"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Wayne Rooney"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_680265"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_1997"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Michael Carrick"
:event/player1 "Lee Cattermole"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_680304"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_680334"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_1997"}

{:event/type "shotoff"
:event/elapsed 44
:event/subtype "shot"
:event/player1 "Wayne Rooney"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_680335"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_1997"}

{:event/type "shoton"
:event/elapsed 44
:event/subtype "distance"
:event/player1 "Lee Cattermole"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_680343"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Patrice Evra"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_680363"
:event/minute 46
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Charles N'Zogbia"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_680369"
:event/minute 47
:event/match_id "match_1997"}

{:event/type "shotoff"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "shot"
:event/player1 "Hugo Rodallega"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_680373"
:event/minute 47
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Wayne Rooney"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_680379"
:event/minute 47
:event/match_id "match_1997"}

{:event/type "corner"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Wayne Rooney"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_680379"
:event/minute 47
:event/match_id "match_1997"}

{:event/type "shotoff"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "shot"
:event/player1 "Nemanja Vidic"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_680380"
:event/minute 47
:event/match_id "match_1997"}

{:event/type "shotoff"
:event/elapsed 49
:event/subtype "distance"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_680461"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Antonio Valencia"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_680473"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Charles N'Zogbia"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_680477"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_1997"}

{:event/type "corner"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Charles N'Zogbia"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_680477"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_1997"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Wayne Rooney"
:event/player1 "Paul Scharner"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_680481"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Michael Brown"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_680484"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_1997"}

{:event/type "shotoff"
:event/elapsed 53
:event/subtype "shot"
:event/player1 "Maynor Figueroa"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_680485"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Wayne Rooney"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_680487"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Charles N'Zogbia"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_680498"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_1997"}

{:event/type "corner"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Charles N'Zogbia"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_680498"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_1997"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Dimitar Berbatov"
:event/player1 "Paul Scharner"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_680507"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Carlos Tevez"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_680514"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_1997"}

{:event/type "goal"
:event/elapsed 61
:event/player2 "Michael Carrick"
:event/subtype "shot"
:event/player1 "Carlos Tevez"
:event/sortorder 0
:event/team "away"
:event/id "event_680525"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_1997"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Michael Carrick"
:event/player1 "Charles N'Zogbia"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_680528"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_1997"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Jonny Evans"
:event/player1 "Hugo Rodallega"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_680531"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_1997"}

{:event/type "foulcommit"
:event/elapsed 66
:event/player2 "Nemanja Vidic"
:event/player1 "Hugo Rodallega"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_680545"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_1997"}

{:event/type "shoton"
:event/elapsed 67
:event/subtype "blocked_shot"
:event/player1 "Mario Melchiot"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_680548"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Antonio Valencia"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_680550"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Charles N'Zogbia"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_680553"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_1997"}

{:event/type "corner"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Charles N'Zogbia"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_680553"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_1997"}

{:event/type "shotoff"
:event/elapsed 67
:event/subtype "header"
:event/player1 "Titus Bramble"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_680554"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Patrice Evra"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_680559"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_680569"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Carlos Tevez"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_680582"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Wayne Rooney"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_680584"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_1997"}

{:event/type "corner"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Wayne Rooney"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_680584"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_1997"}

{:event/type "shotoff"
:event/elapsed 73
:event/subtype "shot"
:event/player1 "John O'Shea"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_680588"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_1997"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Cristiano Ronaldo"
:event/player1 "Michael Brown"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_680600"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_1997"}

{:event/type "shoton"
:event/elapsed 76
:event/subtype "blocked_shot"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_680603"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_1997"}

{:event/type "shotoff"
:event/elapsed 76
:event/subtype "distance"
:event/player1 "Michael Carrick"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_680604"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_1997"}

{:event/type "shoton"
:event/elapsed 77
:event/subtype "deflected"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_680607"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_1997"}

{:event/type "shoton"
:event/elapsed 80
:event/subtype "shot"
:event/player1 "Wayne Rooney"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_680619"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Dimitar Berbatov"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_680626"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Carlos Tevez"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_680628"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_1997"}

{:event/type "shotoff"
:event/elapsed 81
:event/subtype "distance"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_680629"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_680639"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_1997"}

{:event/type "shoton"
:event/elapsed 84
:event/subtype "shot"
:event/player1 "Carlos Tevez"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_680641"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_1997"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Cristiano Ronaldo"
:event/player1 "Mido"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_680642"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_680647"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_1997"}

{:event/type "corner"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_680647"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_1997"}

{:event/type "goal"
:event/elapsed 86
:event/player2 "John O'Shea"
:event/subtype "shot"
:event/player1 "Michael Carrick"
:event/sortorder 0
:event/team "away"
:event/id "event_680653"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Antonio Valencia"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_680657"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_680665"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_1997"}

{:event/type "shotoff"
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_680666"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_1997"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Antonio Valencia"
:event/player1 "Ryan Giggs"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_680675"
:event/minute 93
:event/match_id "match_1997"}

{:event/type "shoton"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "deflected"
:event/player1 "Paul Scharner"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_680678"
:event/minute 94
:event/match_id "match_1997"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Hugo Rodallega"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_680679"
:event/minute 94
:event/match_id "match_1997"}

{:event/type "corner"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Hugo Rodallega"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_680679"
:event/minute 94
:event/match_id "match_1997"}


]

