
;;# data
[
{:match/id "match_22703"
:match/league "Spain LIGA BBVA"
:match/hometeam "Valencia CF"
:match/awayteam "Real Madrid CF"
:match/score "2:3"
:match/hometeam_goals "2"
:match/awayteam_goals "3"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Daniel Parejo"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_1780182"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_22703"}

{:event/type "shotoff"
:event/elapsed 1
:event/subtype "distance"
:event/player1 "Tino Costa"
:event/sortorder 5
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1780183"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "Sami Khedira"
:event/player1 "Victor Ruiz"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1780198"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_22703"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1780211"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_22703"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Jordi Alba"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1780230"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_22703"}

{:event/type "shoton"
:event/elapsed 7
:event/subtype "blocked_shot"
:event/player1 "Daniel Parejo"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1780231"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Cristiano Ronaldo"
:event/player1 "Miguel"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1780253"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_22703"}

{:event/type "shotoff"
:event/elapsed 10
:event/subtype "shot"
:event/player1 "Sami Khedira"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1780258"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Xabi Alonso"
:event/player1 "Daniel Parejo"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1780264"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_22703"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Mesut Oezil"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1780270"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_22703"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Lassana Diarra"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1780272"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_22703"}

{:event/type "shoton"
:event/elapsed 11
:event/subtype "blocked_shot"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_1780273"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_22703"}

{:event/type "shotoff"
:event/elapsed 11
:event/subtype "big chance shot"
:event/player1 "Karim Benzema"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1780274"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Jordi Alba"
:event/subtype "pushing"
:event/player1 "Sami Khedira"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1780284"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_22703"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Miguel"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1780299"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Marcelo"
:event/player1 "Miguel"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1780306"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Daniel Parejo"
:event/player1 "Xabi Alonso"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1780308"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Jeremy Mathieu"
:event/player1 "Lassana Diarra"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1780309"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_22703"}

{:event/type "shotoff"
:event/elapsed 17
:event/subtype "shot"
:event/player1 "Karim Benzema"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1780325"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_22703"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Mesut Oezil"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1780336"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_22703"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Jeremy Mathieu"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1780347"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Marcelo"
:event/player1 "Miguel"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1780352"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_22703"}

{:event/type "goal"
:event/elapsed 20
:event/player2 "Xabi Alonso"
:event/subtype "shot"
:event/player1 "Karim Benzema"
:event/sortorder 9
:event/team "away"
:event/id "event_1780354"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Adil Rami"
:event/player1 "Sami Khedira"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1780363"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Lassana Diarra"
:event/player1 "Tino Costa"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1780367"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_22703"}

{:event/type "card"
:event/elapsed 22
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Tino Costa"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_1780369"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Tino Costa"
:event/player1 "Lassana Diarra"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1780384"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Mesut Oezil"
:event/player1 "Jordi Alba"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1780389"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Marcelo"
:event/player1 "Sofiane Feghouli"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1780393"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_22703"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Jeremy Mathieu"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1780412"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_22703"}

{:event/type "shotoff"
:event/elapsed 28
:event/subtype "deflected"
:event/player1 "Daniel Parejo"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1780415"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_22703"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Tino Costa"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1780417"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_22703"}

{:event/type "corner"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Tino Costa"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1780417"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_22703"}

{:event/type "shoton"
:event/elapsed 28
:event/subtype "blocked_shot"
:event/player1 "Jeremy Mathieu"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_1780418"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_22703"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1780449"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_22703"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Mesut Oezil"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1780453"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_22703"}

{:event/type "shotoff"
:event/elapsed 32
:event/subtype "deflected"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1780458"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_22703"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Mesut Oezil"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1780463"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_22703"}

{:event/type "corner"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Mesut Oezil"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1780463"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_22703"}

{:event/type "shotoff"
:event/elapsed 32
:event/subtype "shot"
:event/player1 "Xabi Alonso"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1780465"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Jeremy Mathieu"
:event/player1 "Alvaro Arbeloa"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1780475"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_22703"}

{:event/type "card"
:event/elapsed 33
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Alvaro Arbeloa"
:event/sortorder 9
:event/team "away"
:event/event_type "card"
:event/id "event_1780476"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_22703"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Daniel Parejo"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1780503"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_22703"}

{:event/type "corner"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Daniel Parejo"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1780503"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Alvaro Arbeloa"
:event/player1 "Jordi Alba"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1780515"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Xabi Alonso"
:event/player1 "Tino Costa"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1780526"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_22703"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Lassana Diarra"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1780532"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Alvaro Arbeloa"
:event/player1 "Jeremy Mathieu"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1780536"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Tino Costa"
:event/player1 "Karim Benzema"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1780543"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_22703"}

{:event/type "shoton"
:event/elapsed 42
:event/subtype "big chance shot"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1780547"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_22703"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Jeremy Mathieu"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1780553"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Marcelo"
:event/subtype "from_behind"
:event/player1 "Sofiane Feghouli"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1780556"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Karim Benzema"
:event/player1 "Miguel"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1780557"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_22703"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Miguel"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1780564"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_22703"}

{:event/type "shotoff"
:event/elapsed 47
:event/subtype "header"
:event/player1 "Roberto Soldado"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1780565"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Daniel Parejo"
:event/player1 "Lassana Diarra"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1780570"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_22703"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Jeremy Mathieu"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_1780575"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_22703"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Sofiane Feghouli"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1780576"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_22703"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Jeremy Mathieu"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1780578"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Cristiano Ronaldo"
:event/player1 "David Albelda"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1780580"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "David Albelda"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1780583"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_22703"}

{:event/type "card"
:event/elapsed 53
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_1780584"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Roberto Soldado"
:event/subtype "serious_foul"
:event/player1 "Marcelo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1780585"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_22703"}

{:event/type "card"
:event/elapsed 55
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Marcelo"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1780586"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_22703"}

{:event/type "card"
:event/elapsed 56
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Mesut Oezil"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1780587"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_22703"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Daniel Parejo"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1780592"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_22703"}

{:event/type "corner"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Daniel Parejo"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1780592"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_22703"}

{:event/type "shoton"
:event/elapsed 58
:event/subtype "blocked_shot"
:event/player1 "Tino Costa"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1780593"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Jordi Alba"
:event/subtype "obstruction"
:event/player1 "Mesut Oezil"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1780594"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 59
:event/player2 "Lassana Diarra"
:event/player1 "Tino Costa"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1780595"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_22703"}

{:event/type "card"
:event/elapsed 59
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Sergio Ramos"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_1780597"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_22703"}

{:event/type "card"
:event/elapsed 59
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "David Albelda"
:event/sortorder 3
:event/team "home"
:event/event_type "card"
:event/id "event_1780598"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Jordi Alba"
:event/player1 "Mesut Oezil"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1780600"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Jordi Alba"
:event/player1 "Mesut Oezil"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1780602"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Xabi Alonso"
:event/player1 "Tino Costa"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1780603"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "David Albelda"
:event/subtype "serious_foul"
:event/player1 "Xabi Alonso"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1780610"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_22703"}

{:event/type "card"
:event/elapsed 65
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Xabi Alonso"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1780611"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_22703"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/sortorder 3
:event/team "home"
:event/event_type "throwin"
:event/id "event_1780615"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_22703"}

{:event/type "shotoff"
:event/elapsed 67
:event/subtype "distance"
:event/player1 "Jeremy Mathieu"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1780619"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player1 "Karim Benzema"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1780623"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Victor Ruiz"
:event/player1 "Lassana Diarra"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1780625"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Sergio Ramos"
:event/player1 "Sofiane Feghouli"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1780626"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_22703"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Mesut Oezil"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1780628"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_22703"}

{:event/type "corner"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Mesut Oezil"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1780628"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_22703"}

{:event/type "goal"
:event/elapsed 72
:event/player2 "Mesut Oezil"
:event/subtype "header"
:event/player1 "Sergio Ramos"
:event/sortorder 1
:event/team "away"
:event/id "event_1780629"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_22703"}

{:event/type "shoton"
:event/elapsed 75
:event/subtype "big chance shot"
:event/player1 "Pablo Hernandez"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_1780637"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_22703"}

{:event/type "goal"
:event/elapsed 75
:event/subtype "shot"
:event/player1 "Roberto Soldado"
:event/sortorder 4
:event/team "home"
:event/id "event_1780638"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 76
:event/player2 "Gonzalo Higuain"
:event/player1 "Jonas"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1780640"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 78
:event/player2 "Jeremy Mathieu"
:event/player1 "Raul Albiol"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1780646"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_22703"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Jeremy Mathieu"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1780647"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_22703"}

{:event/type "shoton"
:event/elapsed 79
:event/subtype "blocked_shot"
:event/player1 "Roberto Soldado"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1780649"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_22703"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Tino Costa"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1780650"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_22703"}

{:event/type "corner"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Tino Costa"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1780650"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_22703"}

{:event/type "goal"
:event/elapsed 79
:event/subtype "shot"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 4
:event/team "away"
:event/id "event_1780652"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_22703"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1780656"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_22703"}

{:event/type "shoton"
:event/elapsed 82
:event/subtype "blocked_shot"
:event/player1 "Gonzalo Higuain"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1780657"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_22703"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Pablo Hernandez"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1780659"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_22703"}

{:event/type "goal"
:event/elapsed 83
:event/player2 "Pablo Hernandez"
:event/subtype "shot"
:event/player1 "Roberto Soldado"
:event/sortorder 2
:event/team "home"
:event/id "event_1780660"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_22703"}

{:event/type "shotoff"
:event/elapsed 84
:event/subtype "distance"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1780662"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_22703"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Miguel"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1780664"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Cristiano Ronaldo"
:event/player1 "Roberto Soldado"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1780667"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_22703"}

{:event/type "shoton"
:event/elapsed 87
:event/subtype "distance"
:event/player1 "Aritz Aduriz"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1780671"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 87
:event/player1 "Gonzalo Higuain"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1780672"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_22703"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Pablo Hernandez"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1780674"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_22703"}

{:event/type "shotoff"
:event/elapsed 88
:event/subtype "distance"
:event/player1 "Adil Rami"
:event/sortorder 5
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1780678"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player2 "Cristiano Ronaldo"
:event/player1 "Miguel"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1780680"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed 90
:event/subtype "hands"
:event/player1 "Marcelo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1780682"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player1 "Mesut Oezil"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1780687"
:event/minute 91
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed_plus 4
:event/elapsed 90
:event/player2 "Tino Costa"
:event/player1 "Esteban Granero"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1780692"
:event/minute 94
:event/match_id "match_22703"}

{:event/type "card"
:event/elapsed_plus 4
:event/elapsed 90
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Esteban Granero"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1780693"
:event/minute 94
:event/match_id "match_22703"}

{:event/type "foulcommit"
:event/elapsed_plus 4
:event/elapsed 90
:event/player2 "Tino Costa"
:event/player1 "Mesut Oezil"
:event/sortorder 5
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1780697"
:event/minute 94
:event/match_id "match_22703"}

{:event/type "card"
:event/elapsed_plus 4
:event/elapsed 90
:event/card_type "y"
:event/subtype "verbal_abuse"
:event/player1 "Diego Alves"
:event/sortorder 5
:event/team "home"
:event/event_type "card"
:event/id "event_1780709"
:event/minute 94
:event/match_id "match_22703"}

{:event/type "shotoff"
:event/elapsed_plus 6
:event/elapsed 90
:event/subtype "big chance crossbar"
:event/player1 "Adil Rami"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1780699"
:event/minute 96
:event/match_id "match_22703"}

{:event/type "shoton"
:event/elapsed_plus 6
:event/elapsed 90
:event/subtype "blocked_shot"
:event/player1 "Roberto Soldado"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1780700"
:event/minute 96
:event/match_id "match_22703"}

{:event/type "cross"
:event/elapsed_plus 6
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Tino Costa"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1780701"
:event/minute 96
:event/match_id "match_22703"}

{:event/type "corner"
:event/elapsed_plus 6
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Tino Costa"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1780701"
:event/minute 96
:event/match_id "match_22703"}


]

