
;;# data
[
{:match/id "match_15301"
:match/league "Netherlands Eredivisie"
:match/hometeam "SC Heerenveen"
:match/awayteam "NAC Breda"
:match/score "0:0"
:match/hometeam_goals "0"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 7
:event/card_type "y"
:event/player1 "Doke Schmidt"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_4315319"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_15301"}

{:event/type "card"
:event/elapsed 28
:event/card_type "y"
:event/player1 "Demy de Zeeuw"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_4315389"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_15301"}

{:event/type "card"
:event/elapsed 86
:event/card_type "y"
:event/player1 "Dirk Marcellis"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_4316595"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_15301"}


]

