
;;# data
[
{:match/id "match_9048"
:match/league "Germany 1. Bundesliga"
:match/hometeam "TSG 1899 Hoffenheim"
:match/awayteam "FC Schalke 04"
:match/score "3:2"
:match/hometeam_goals "3"
:match/awayteam_goals "2"}

{:event/type "goal"
:event/elapsed 13
:event/player1 "Kevin Volland"
:event/sortorder 0
:event/team "home"
:event/id "event_2454694"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_9048"}

{:event/type "card"
:event/elapsed 20
:event/card_type "y"
:event/player1 "Sebastian Rudy"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2454710"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_9048"}

{:event/type "card"
:event/elapsed 30
:event/card_type "y"
:event/player1 "Marvin Compper"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2454819"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_9048"}

{:event/type "goal"
:event/elapsed 37
:event/player1 "Roman Neustaedter"
:event/sortorder 0
:event/team "away"
:event/id "event_2454934"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_9048"}

{:event/type "card"
:event/elapsed 63
:event/card_type "y"
:event/player1 "Christian Fuchs"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2455411"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_9048"}

{:event/type "card"
:event/elapsed 64
:event/card_type "y"
:event/player1 "Ibrahim Afellay"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2455412"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_9048"}

{:event/type "goal"
:event/elapsed 67
:event/player1 "Roberto Firmino"
:event/sortorder 0
:event/team "home"
:event/id "event_2455410"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_9048"}

{:event/type "card"
:event/elapsed 73
:event/card_type "y"
:event/player1 "Klaas Jan Huntelaar"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2455442"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_9048"}

{:event/type "goal"
:event/elapsed 82
:event/player1 "Atsuto Uchida"
:event/sortorder 0
:event/team "away"
:event/id "event_2455558"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_9048"}

{:event/type "goal"
:event/elapsed 90
:event/player1 "Sven Schipplock"
:event/sortorder 0
:event/team "home"
:event/id "event_2455788"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_9048"}


]

