
;;# data
[
{:match/id "match_12026"
:match/league "Italy Serie A"
:match/hometeam "Milan"
:match/awayteam "Catania"
:match/score "4:2"
:match/hometeam_goals "4"
:match/awayteam_goals "2"}

{:event/type "card"
:event/elapsed 9
:event/card_type "y"
:event/player1 "Mattia De Sciglio"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2733725"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_12026"}

{:event/type "card"
:event/elapsed 26
:event/card_type "y"
:event/player1 "Gonzalo Bergessio"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2733729"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_12026"}

{:event/type "goal"
:event/elapsed 30
:event/player1 "Nicola Legrottaglie"
:event/sortorder 0
:event/team "away"
:event/id "event_2733732"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_12026"}

{:event/type "card"
:event/elapsed 37
:event/card_type "y"
:event/player1 "Alberto Frison,18"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2733738"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_12026"}

{:event/type "card"
:event/elapsed 41
:event/card_type "y"
:event/player1 "Nicola Legrottaglie"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2733747"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_12026"}

{:event/type "goal"
:event/elapsed 45
:event/player1 "Mathieu Flamini"
:event/sortorder 0
:event/team "home"
:event/id "event_2733742"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_12026"}

{:event/type "goal"
:event/elapsed 65
:event/player1 "Gonzalo Bergessio"
:event/sortorder 0
:event/team "away"
:event/id "event_2733763"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_12026"}

{:event/type "card"
:event/elapsed 72
:event/card_type "y"
:event/player1 "Mario Balotelli"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2733766"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_12026"}

{:event/type "goal"
:event/elapsed 75
:event/player1 "Giampaolo Pazzini"
:event/sortorder 0
:event/team "home"
:event/id "event_2733767"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_12026"}

{:event/type "goal"
:event/elapsed 77
:event/player1 "Giampaolo Pazzini"
:event/sortorder 0
:event/team "home"
:event/id "event_2733769"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_12026"}

{:event/type "card"
:event/elapsed 78
:event/card_type "y"
:event/player1 "Mathieu Flamini"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2733770"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_12026"}

{:event/type "card"
:event/elapsed 78
:event/card_type "y"
:event/player1 "Pablo Barrientos"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2733771"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_12026"}

{:event/type "card"
:event/elapsed 86
:event/card_type "y"
:event/player1 "Giovanni Marchese"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2733782"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_12026"}

{:event/type "goal"
:event/elapsed 90
:event/player1 "Mario Balotelli"
:event/sortorder 0
:event/team "home"
:event/id "event_2733779"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_12026"}


]

