
;;# data
[
{:match/id "match_2415"
:match/league "England Premier League"
:match/hometeam "Birmingham City"
:match/awayteam "Burnley"
:match/score "2:1"
:match/hometeam_goals "2"
:match/awayteam_goals "1"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Martin Paterson"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1066369"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Cameron Jerome"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1066371"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_2415"}

{:event/type "shotoff"
:event/elapsed 2
:event/subtype "header"
:event/player1 "Lee Bowyer"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1066372"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_2415"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Barry Ferguson"
:event/subtype "from_behind"
:event/player1 "Wade Elliott"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1066374"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Jack Cork"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1066377"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_2415"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Graham Alexander"
:event/subtype "from_behind"
:event/player1 "Lee Bowyer"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1066379"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_2415"}

{:event/type "shotoff"
:event/elapsed 7
:event/subtype "direct_freekick"
:event/player1 "Daniel Fox"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1066380"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_2415"}

{:event/type "shoton"
:event/elapsed 9
:event/subtype "deflected"
:event/player1 "Cristian Benitez"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1066383"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Lee Bowyer"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1066384"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_2415"}

{:event/type "corner"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Lee Bowyer"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1066384"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Lee Bowyer"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1066386"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_2415"}

{:event/type "corner"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Lee Bowyer"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1066386"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_2415"}

{:event/type "shoton"
:event/elapsed 10
:event/subtype "distance"
:event/player1 "Martin Paterson"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1066388"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_2415"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Sebastian Larsson"
:event/subtype "from_behind"
:event/player1 "Wade Elliott"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1066392"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_2415"}

{:event/type "shotoff"
:event/elapsed 14
:event/subtype "distance"
:event/player1 "Cameron Jerome"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1066396"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Roger Johnson"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1066399"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_2415"}

{:event/type "shotoff"
:event/elapsed 16
:event/subtype "distance"
:event/player1 "Gregory Vignal"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1066401"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Martin Paterson"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_1066403"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Daniel Fox"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1066405"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_2415"}

{:event/type "corner"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Daniel Fox"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1066405"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_2415"}

{:event/type "shoton"
:event/elapsed 17
:event/subtype "blocked_shot"
:event/player1 "Jack Cork"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_1066407"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Sebastian Larsson"
:event/sortorder 6
:event/team "home"
:event/event_type "cross"
:event/id "event_1066410"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Lee Bowyer"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1066412"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_2415"}

{:event/type "corner"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Lee Bowyer"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1066412"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_2415"}

{:event/type "shotoff"
:event/elapsed 18
:event/subtype "header"
:event/player1 "Cameron Jerome"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1066413"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_2415"}

{:event/type "shoton"
:event/elapsed 19
:event/subtype "big chance shot"
:event/player1 "Cameron Jerome"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1066416"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "James McFadden"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1066417"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_2415"}

{:event/type "corner"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "James McFadden"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1066417"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_2415"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Graham Alexander"
:event/subtype "pushing"
:event/player1 "Sebastian Larsson"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1066419"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Martin Paterson"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1066420"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_2415"}

{:event/type "corner"
:event/elapsed 21
:event/subtype "short"
:event/player1 "Daniel Fox"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1066422"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_2415"}

{:event/type "shoton"
:event/elapsed 23
:event/subtype "distance"
:event/player1 "Jack Cork"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1066428"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Martin Paterson"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1066429"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Graham Alexander"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1066432"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_2415"}

{:event/type "corner"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Graham Alexander"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1066432"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Wade Elliott"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1066434"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Martin Paterson"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1066436"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Graham Alexander"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1066438"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_2415"}

{:event/type "corner"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Graham Alexander"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1066438"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_2415"}

{:event/type "foulcommit"
:event/elapsed 27
:event/subtype "hands"
:event/player1 "Steven Fletcher"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1066439"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Gregory Vignal"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1066443"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Sebastian Larsson"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1066444"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2415"}

{:event/type "shoton"
:event/elapsed 29
:event/subtype "header"
:event/player1 "Cameron Jerome"
:event/sortorder 6
:event/team "home"
:event/event_type "shoton"
:event/id "event_1066454"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2415"}

{:event/type "goal"
:event/elapsed 29
:event/subtype "header"
:event/player1 "Cameron Jerome"
:event/sortorder 9
:event/team "home"
:event/id "event_1066445"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Stuart Parnaby"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1066448"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_2415"}

{:event/type "foulcommit"
:event/elapsed 32
:event/subtype "hands"
:event/player1 "Liam Ridgewell"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1066449"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_2415"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Steven Caldwell"
:event/subtype "pushing"
:event/player1 "Roger Johnson"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1066451"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_2415"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Martin Paterson"
:event/subtype "shirt_pull"
:event/player1 "Gregory Vignal"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1066452"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Jack Cork"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1066455"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Graham Alexander"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1066457"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_2415"}

{:event/type "corner"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Graham Alexander"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1066457"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Martin Paterson"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1066462"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_2415"}

{:event/type "corner"
:event/elapsed 39
:event/subtype "short"
:event/player1 "Graham Alexander"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1066464"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Graham Alexander"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1066465"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_2415"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Cameron Jerome"
:event/subtype "from_behind"
:event/player1 "Steven Caldwell"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1066468"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_2415"}

{:event/type "goal"
:event/elapsed 41
:event/player2 "Roger Johnson"
:event/subtype "header"
:event/player1 "Cristian Benitez"
:event/sortorder 3
:event/team "home"
:event/id "event_1066470"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_2415"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Gregory Vignal"
:event/subtype "pushing"
:event/player1 "Martin Paterson"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1066474"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_2415"}

{:event/type "shotoff"
:event/elapsed 47
:event/subtype "distance"
:event/player1 "Steven Fletcher"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1066480"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_2415"}

{:event/type "shoton"
:event/elapsed 49
:event/subtype "distance"
:event/player1 "Steven Fletcher"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1066483"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "David Nugent"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1066484"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_2415"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Lee Bowyer"
:event/subtype "serious_foul"
:event/player1 "Daniel Fox"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1066486"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_2415"}

{:event/type "card"
:event/elapsed 50
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Daniel Fox"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_1066487"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_2415"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Wade Elliott"
:event/subtype "from_behind"
:event/player1 "Lee Bowyer"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1066493"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_2415"}

{:event/type "shotoff"
:event/elapsed 55
:event/subtype "distance"
:event/player1 "Cristian Benitez"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1066497"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_2415"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Jack Cork"
:event/subtype "serious_foul"
:event/player1 "Stuart Parnaby"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1066499"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_2415"}

{:event/type "card"
:event/elapsed 56
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Stuart Parnaby"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_1066500"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Cristian Benitez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1066505"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_2415"}

{:event/type "shotoff"
:event/elapsed 58
:event/subtype "big chance volley"
:event/player1 "Sebastian Larsson"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1066506"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_2415"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player2 "Gregory Vignal"
:event/subtype "from_behind"
:event/player1 "Tyrone Mears"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1066514"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Steven Fletcher"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1066516"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_2415"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Gregory Vignal"
:event/subtype "pushing"
:event/player1 "Steven Fletcher"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1066525"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_2415"}

{:event/type "foulcommit"
:event/elapsed 66
:event/player2 "Tyrone Mears"
:event/subtype "serious_foul"
:event/player1 "Gregory Vignal"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1066527"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_2415"}

{:event/type "card"
:event/elapsed 66
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Gregory Vignal"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_1066528"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_2415"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Jack Cork"
:event/subtype "pushing"
:event/player1 "Sebastian Larsson"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1066538"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_2415"}

{:event/type "shoton"
:event/elapsed 72
:event/subtype "blocked_shot"
:event/player1 "Tyrone Mears"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1066545"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Graham Alexander"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1066547"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_2415"}

{:event/type "corner"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Graham Alexander"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1066547"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Sebastian Larsson"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1066553"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_2415"}

{:event/type "corner"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Sebastian Larsson"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1066553"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_2415"}

{:event/type "shoton"
:event/elapsed 74
:event/subtype "blocked_shot"
:event/player1 "Cristian Benitez"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_1066556"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_2415"}

{:event/type "shotoff"
:event/elapsed 79
:event/subtype "shot"
:event/player1 "Lee Bowyer"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1066571"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Sebastian Larsson"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1066580"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_2415"}

{:event/type "corner"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Sebastian Larsson"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1066580"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Graham Alexander"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1066582"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_2415"}

{:event/type "corner"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Graham Alexander"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1066582"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_2415"}

{:event/type "shotoff"
:event/elapsed 82
:event/subtype "header"
:event/player1 "Steven Caldwell"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1066592"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_2415"}

{:event/type "shotoff"
:event/elapsed 83
:event/subtype "distance"
:event/player1 "Martin Paterson"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1066597"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_2415"}

{:event/type "goal"
:event/elapsed 87
:event/player2 "Jack Cork"
:event/subtype "shot"
:event/player1 "Steven Thompson"
:event/sortorder 3
:event/team "away"
:event/id "event_1066619"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_2415"}

{:event/type "shotoff"
:event/elapsed 89
:event/subtype "distance"
:event/player1 "Michel"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1066631"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_2415"}

{:event/type "cross"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Martin Paterson"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1066674"
:event/minute 95
:event/match_id "match_2415"}


]

