
;;# data
[
{:match/id "match_11352"
:match/league "Italy Serie A"
:match/hometeam "Fiorentina"
:match/awayteam "Parma"
:match/score "2:0"
:match/hometeam_goals "2"
:match/awayteam_goals "0"}

{:event/type "shoton"
:event/elapsed 1
:event/subtype "shot"
:event/player1 "Adem Ljajic"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1189405"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_11352"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Riccardo Montolivo"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1189409"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_11352"}

{:event/type "corner"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Riccardo Montolivo"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1189409"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_11352"}

{:event/type "shoton"
:event/elapsed 2
:event/subtype "header"
:event/player1 "Alberto Gilardino"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1189416"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_11352"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Juan Vargas"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1189436"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_11352"}

{:event/type "corner"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Juan Vargas"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1189436"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_11352"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Alessandro Lucarelli"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1189497"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_11352"}

{:event/type "shotoff"
:event/elapsed 8
:event/subtype "distance"
:event/player1 "Massimo Gobbi"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1189510"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_11352"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Alberto Gilardino"
:event/subtype "from_behind"
:event/player1 "Alessandro Lucarelli"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1189571"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_11352"}

{:event/type "shotoff"
:event/elapsed 13
:event/subtype "shot"
:event/player1 "Juan Vargas"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1189589"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_11352"}

{:event/type "shotoff"
:event/elapsed 14
:event/subtype "shot"
:event/player1 "Adem Ljajic"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1189609"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_11352"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Alessandro Gamberini"
:event/subtype "pushing"
:event/player1 "Valeri Bojinov"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1189620"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_11352"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Alessio Cerci"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1189628"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_11352"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Valeri Bojinov"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1189641"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_11352"}

{:event/type "shoton"
:event/elapsed 19
:event/subtype "distance"
:event/player1 "Massimo Gobbi"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1189681"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_11352"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Cristian Zaccardo"
:event/subtype "pushing"
:event/player1 "Juan Vargas"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1189703"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_11352"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Juan Vargas"
:event/subtype "obstruction"
:event/player1 "Francesco Valiani"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1189712"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_11352"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Cristian Zaccardo"
:event/subtype "obstruction"
:event/player1 "Juan Vargas"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1189719"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_11352"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Juan Vargas"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1189753"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_11352"}

{:event/type "shoton"
:event/elapsed 25
:event/subtype "shot"
:event/player1 "Alessio Cerci"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1189768"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_11352"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Juan Vargas"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1189776"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_11352"}

{:event/type "shoton"
:event/elapsed 26
:event/subtype "shot"
:event/player1 "Alberto Gilardino"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1189777"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_11352"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Fernando Marquez"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1189800"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_11352"}

{:event/type "corner"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Fernando Marquez"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1189800"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_11352"}

{:event/type "shotoff"
:event/elapsed 29
:event/subtype "distance"
:event/player1 "Juan Vargas"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1189814"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_11352"}

{:event/type "foulcommit"
:event/elapsed 30
:event/player2 "Marco Donadel"
:event/subtype "obstruction"
:event/player1 "Massimo Gobbi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1189831"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_11352"}

{:event/type "shoton"
:event/elapsed 30
:event/subtype "distance"
:event/player1 "Alessio Cerci"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1189834"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_11352"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Adem Ljajic"
:event/subtype "from_behind"
:event/player1 "Stefano Morrone"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1189848"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_11352"}

{:event/type "shoton"
:event/elapsed 31
:event/subtype "direct_freekick"
:event/player1 "Adem Ljajic"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1189853"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_11352"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Cristian Zaccardo"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1189868"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_11352"}

{:event/type "corner"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Cristian Zaccardo"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1189868"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_11352"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Alessio Cerci"
:event/subtype "obstruction"
:event/player1 "Stefano Morrone"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1189872"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_11352"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Riccardo Montolivo"
:event/subtype "obstruction"
:event/player1 "Massimo Gobbi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1189921"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_11352"}

{:event/type "shotoff"
:event/elapsed 38
:event/subtype "distance"
:event/player1 "Alessio Cerci"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1189969"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_11352"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Lorenzo De Silvestri"
:event/subtype "obstruction"
:event/player1 "Massimo Gobbi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1190011"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_11352"}

{:event/type "shotoff"
:event/elapsed 41
:event/subtype "distance"
:event/player1 "Juan Vargas"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1190013"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_11352"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Stefano Morrone"
:event/subtype "pushing"
:event/player1 "Alberto Gilardino"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1190057"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_11352"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Riccardo Montolivo"
:event/subtype "from_behind"
:event/player1 "Stefano Morrone"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1190086"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_11352"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "direct_freekick"
:event/player1 "Alessio Cerci"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1190094"
:event/minute 46
:event/match_id "match_11352"}

{:event/type "shotoff"
:event/elapsed 47
:event/subtype "distance"
:event/player1 "Valeri Bojinov"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1190280"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_11352"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Francesco Valiani"
:event/subtype "from_behind"
:event/player1 "Felipe"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1190300"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_11352"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Cristian Zaccardo"
:event/subtype "serious_foul"
:event/player1 "Juan Vargas"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1190330"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_11352"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Riccardo Montolivo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1190353"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_11352"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Antonio Candreva"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1190370"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_11352"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Alberto Gilardino"
:event/subtype "pushing"
:event/player1 "Massimo Paci"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1190407"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_11352"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Felipe"
:event/subtype "from_behind"
:event/player1 "Antonio Candreva"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1190443"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_11352"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Juan Vargas"
:event/subtype "from_behind"
:event/player1 "Francesco Valiani"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1190470"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_11352"}

{:event/type "card"
:event/elapsed 56
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Francesco Valiani"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1190478"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_11352"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Felipe"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1190516"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_11352"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Fernando Marquez"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1190534"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_11352"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Antonio Candreva"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1190545"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_11352"}

{:event/type "corner"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Antonio Candreva"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1190545"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_11352"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Fernando Marquez"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1190546"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_11352"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Juan Vargas"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1190565"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_11352"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player2 "Alberto Gilardino"
:event/subtype "penalty"
:event/player1 "Alessandro Lucarelli"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1190571"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_11352"}

{:event/type "card"
:event/elapsed 60
:event/card_type "y"
:event/subtype "shirt_pull"
:event/player1 "Alessandro Lucarelli"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_1190573"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_11352"}

{:event/type "goal"
:event/elapsed 61
:event/player1 "Adem Ljajic"
:event/sortorder 0
:event/team "home"
:event/id "event_1190586"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_11352"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Angelo"
:event/subtype "obstruction"
:event/player1 "Felipe"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1190609"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_11352"}

{:event/type "shoton"
:event/elapsed 65
:event/subtype "blocked_shot"
:event/player1 "Alberto Gilardino"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1190640"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_11352"}

{:event/type "card"
:event/elapsed 65
:event/card_type "y"
:event/subtype "verbal_abuse"
:event/player1 "Massimo Paci"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1190649"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_11352"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Valeri Bojinov"
:event/subtype "pushing"
:event/player1 "Cesare Natali"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1190672"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_11352"}

{:event/type "card"
:event/elapsed 67
:event/card_type "y"
:event/subtype "pushing"
:event/player1 "Cesare Natali"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_1190676"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_11352"}

{:event/type "shoton"
:event/elapsed 67
:event/subtype "direct_freekick"
:event/player1 "Valeri Bojinov"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1190677"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_11352"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Angelo"
:event/subtype "pushing"
:event/player1 "Nikola Gulan"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1190728"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_11352"}

{:event/type "foulcommit"
:event/elapsed 72
:event/player2 "Angelo"
:event/subtype "obstruction"
:event/player1 "Marco Donadel"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1190734"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_11352"}

{:event/type "shoton"
:event/elapsed 73
:event/subtype "distance"
:event/player1 "Adem Ljajic"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1190756"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_11352"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Marco Donadel"
:event/subtype "serious_foul"
:event/player1 "Antonio Candreva"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1190761"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_11352"}

{:event/type "card"
:event/elapsed 73
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Antonio Candreva"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_1190762"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_11352"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Alessio Cerci"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1190773"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_11352"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Juan Vargas"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1190775"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_11352"}

{:event/type "shoton"
:event/elapsed 75
:event/subtype "distance"
:event/player1 "Adem Ljajic"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1190790"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_11352"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Angelo"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1190792"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_11352"}

{:event/type "goal"
:event/elapsed 76
:event/player2 "Alessio Cerci"
:event/subtype "distance"
:event/player1 "Lorenzo De Silvestri"
:event/sortorder 0
:event/team "home"
:event/id "event_1190816"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_11352"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Angelo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1190836"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_11352"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Hernan Crespo"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1190837"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_11352"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Alessandro Gamberini"
:event/subtype "pushing"
:event/player1 "Valeri Bojinov"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1190869"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_11352"}

{:event/type "corner"
:event/elapsed 81
:event/subtype "short"
:event/player1 "Adem Ljajic"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1190882"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_11352"}

{:event/type "shoton"
:event/elapsed 83
:event/subtype "blocked_shot"
:event/player1 "Alberto Gilardino"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1190915"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_11352"}

{:event/type "shotoff"
:event/elapsed 85
:event/subtype "shot"
:event/player1 "Alessio Cerci"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1190955"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_11352"}

{:event/type "shoton"
:event/elapsed 86
:event/subtype "distance"
:event/player1 "Fernando Marquez"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1190964"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_11352"}

{:event/type "shotoff"
:event/elapsed 88
:event/subtype "shot"
:event/player1 "Valeri Bojinov"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1190991"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_11352"}

{:event/type "shoton"
:event/elapsed 88
:event/subtype "shot"
:event/player1 "Riccardo Montolivo"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1191001"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_11352"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Adem Ljajic"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1191010"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_11352"}

{:event/type "corner"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Adem Ljajic"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1191010"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_11352"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Adem Ljajic"
:event/subtype "obstruction"
:event/player1 "Massimo Paci"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1191023"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_11352"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Valeri Bojinov"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1191039"
:event/minute 91
:event/match_id "match_11352"}

{:event/type "corner"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Valeri Bojinov"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1191039"
:event/minute 91
:event/match_id "match_11352"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Fernando Marquez"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1191047"
:event/minute 92
:event/match_id "match_11352"}

{:event/type "corner"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Fernando Marquez"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1191047"
:event/minute 92
:event/match_id "match_11352"}

{:event/type "foulcommit"
:event/elapsed_plus 4
:event/elapsed 90
:event/player2 "Mario Alberto Santana"
:event/subtype "from_behind"
:event/player1 "Valeri Bojinov"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1191062"
:event/minute 94
:event/match_id "match_11352"}


]

