
;;# data
[
{:match/id "match_5633"
:match/league "France Ligue 1"
:match/hometeam "LOSC Lille"
:match/awayteam "AS Saint-Étienne"
:match/score "1:1"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "card"
:event/elapsed 9
:event/card_type "y"
:event/player1 "Adil Rami"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1340959"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_5633"}

{:event/type "card"
:event/elapsed 18
:event/card_type "y"
:event/player1 "Mustapha Bayal Sall"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1340958"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_5633"}

{:event/type "card"
:event/elapsed 41
:event/card_type "y"
:event/player1 "Bakary Sako"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1341860"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_5633"}

{:event/type "goal"
:event/elapsed 72
:event/player1 "Moussa Sow"
:event/sortorder 0
:event/team "home"
:event/id "event_1341139"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_5633"}

{:event/type "goal"
:event/elapsed 75
:event/player1 "Bakary Sako"
:event/sortorder 0
:event/team "away"
:event/id "event_1341140"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_5633"}

{:event/type "card"
:event/elapsed 79
:event/card_type "y"
:event/player1 "Loris Nery"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1341861"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_5633"}


]

