
;;# data
[
{:match/id "match_23640"
:match/league "Spain LIGA BBVA"
:match/hometeam "Real Madrid CF"
:match/awayteam "Athletic Club de Bilbao"
:match/score "3:1"
:match/hometeam_goals "3"
:match/awayteam_goals "1"}

{:event/type "card"
:event/elapsed 20
:event/card_type "y"
:event/player1 "Carlos Gurpegi"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2955288"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_23640"}

{:event/type "goal"
:event/elapsed 25
:event/player1 "Isco"
:event/sortorder 0
:event/team "home"
:event/id "event_2955319"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_23640"}

{:event/type "card"
:event/elapsed 28
:event/card_type "y"
:event/player1 "Sami Khedira"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2955359"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_23640"}

{:event/type "goal"
:event/elapsed 45
:event/player1 "Cristiano Ronaldo"
:event/sortorder 0
:event/team "home"
:event/id "event_2955479"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_23640"}

{:event/type "card"
:event/elapsed 66
:event/card_type "y"
:event/player1 "Benat Etxebarria"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2955651"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_23640"}

{:event/type "goal"
:event/elapsed 72
:event/player1 "Isco"
:event/sortorder 0
:event/team "home"
:event/id "event_2955666"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_23640"}

{:event/type "goal"
:event/elapsed 79
:event/player1 "Ibai Gomez"
:event/sortorder 0
:event/team "away"
:event/id "event_2955689"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_23640"}


]

