
;;# data
[
{:match/id "match_10265"
:match/league "Italy Serie A"
:match/hometeam "Torino"
:match/awayteam "Lecce"
:match/score "3:0"
:match/hometeam_goals "3"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 29
:event/card_type "y"
:event/player1 "Souleymane Adama Diamoutene"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_391439"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_10265"}

{:event/type "goal"
:event/elapsed 29
:event/player1 "Alessandro Rosina"
:event/sortorder 0
:event/team "home"
:event/id "event_391443"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_10265"}

{:event/type "goal"
:event/elapsed 33
:event/player1 "Paolo Zanetti"
:event/sortorder 0
:event/team "home"
:event/id "event_391454"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_10265"}

{:event/type "card"
:event/elapsed 38
:event/card_type "y"
:event/player1 "Eugenio Corini"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_391475"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_10265"}

{:event/type "card"
:event/elapsed 54
:event/card_type "y"
:event/player1 "Guillermo Giacomazzi"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_391657"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_10265"}

{:event/type "goal"
:event/elapsed 74
:event/player1 "Rolando Bianchi"
:event/sortorder 0
:event/team "home"
:event/id "event_391894"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_10265"}


]

