
;;# data
[
{:match/id "match_2767"
:match/league "England Premier League"
:match/hometeam "Blackpool"
:match/awayteam "Newcastle United"
:match/score "1:1"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "foulcommit"
:event/elapsed 1
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1517563"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_2767"}

{:event/type "shoton"
:event/elapsed 2
:event/subtype "shot"
:event/player1 "Jose Enrique"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1517570"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_2767"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Stephen Crainey"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1517590"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_2767"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Jonas Gutierrez"
:event/subtype "shirt_pull"
:event/player1 "Matthew Phillips"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1517607"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_2767"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Jonas Gutierrez"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1517692"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_2767"}

{:event/type "shotoff"
:event/elapsed 9
:event/subtype "distance"
:event/player1 "Gary Taylor-Fletcher"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1517711"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_2767"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1517748"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_2767"}

{:event/type "shoton"
:event/elapsed 11
:event/subtype "shot"
:event/player1 "Shola Ameobi"
:event/sortorder 4
:event/team "away"
:event/event_type "shoton"
:event/id "event_1517756"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_2767"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1517832"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_2767"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player1 "Shola Ameobi"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1517834"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_2767"}

{:event/type "goal"
:event/elapsed 17
:event/player2 "Joey Barton"
:event/subtype "distance"
:event/player1 "Peter Loevenkrands"
:event/sortorder 0
:event/team "away"
:event/id "event_1517864"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_2767"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Neal Eardley"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1517903"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_2767"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Dudley Campbell"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1518056"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_2767"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Charlie Adam"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1518060"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_2767"}

{:event/type "corner"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Charlie Adam"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1518060"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_2767"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "David Vaughan"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_1518064"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_2767"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Charlie Adam"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1518073"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_2767"}

{:event/type "corner"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Charlie Adam"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1518073"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_2767"}

{:event/type "shotoff"
:event/elapsed 27
:event/subtype "shot"
:event/player1 "Dudley Campbell"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1518075"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_2767"}

{:event/type "corner"
:event/elapsed 31
:event/subtype "short"
:event/player1 "Charlie Adam"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1518158"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_2767"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Neal Eardley"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1518162"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_2767"}

{:event/type "shoton"
:event/elapsed 31
:event/subtype "deflected"
:event/player1 "Charlie Adam"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_1518163"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_2767"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Charlie Adam"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1518174"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_2767"}

{:event/type "corner"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Charlie Adam"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1518174"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_2767"}

{:event/type "goal"
:event/elapsed 32
:event/player2 "Charlie Adam"
:event/subtype "shot"
:event/player1 "Dudley Campbell"
:event/sortorder 1
:event/team "home"
:event/id "event_1518181"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_2767"}

{:event/type "foulcommit"
:event/elapsed 34
:event/player2 "Stephen Crainey"
:event/subtype "from_behind"
:event/player1 "Cheik Tiote"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1518212"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_2767"}

{:event/type "shoton"
:event/elapsed 35
:event/subtype "shot"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1518235"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_2767"}

{:event/type "shotoff"
:event/elapsed 36
:event/subtype "shot"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1518253"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_2767"}

{:event/type "foulcommit"
:event/elapsed 36
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1518259"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_2767"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Jonas Gutierrez"
:event/subtype "from_behind"
:event/player1 "Ian Evatt"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1518303"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_2767"}

{:event/type "shoton"
:event/elapsed 39
:event/subtype "header"
:event/player1 "Kevin Nolan"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1518315"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_2767"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Cheik Tiote"
:event/subtype "from_behind"
:event/player1 "Gary Taylor-Fletcher"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1518326"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_2767"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player1 "Fabricio Coloccini"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1518357"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_2767"}

{:event/type "shoton"
:event/elapsed 42
:event/subtype "shot"
:event/player1 "Ian Evatt"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1518382"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_2767"}

{:event/type "shoton"
:event/elapsed 42
:event/subtype "deflected"
:event/player1 "Alex Baptiste"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_1518393"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_2767"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Charlie Adam"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1518395"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_2767"}

{:event/type "corner"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Charlie Adam"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1518395"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_2767"}

{:event/type "shoton"
:event/elapsed 43
:event/subtype "shot"
:event/player1 "Alex Baptiste"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1518414"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_2767"}

{:event/type "shoton"
:event/elapsed 43
:event/subtype "blocked_shot"
:event/player1 "Joey Barton"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_1518421"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_2767"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Matthew Phillips"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_1518521"
:event/minute 46
:event/match_id "match_2767"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "header"
:event/player1 "Dudley Campbell"
:event/sortorder 5
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1518526"
:event/minute 46
:event/match_id "match_2767"}

{:event/type "foulcommit"
:event/elapsed 47
:event/player2 "Cheik Tiote"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1518669"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_2767"}

{:event/type "shotoff"
:event/elapsed 49
:event/subtype "distance"
:event/player1 "Shola Ameobi"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1518690"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_2767"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player1 "Keith Southern"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1518712"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_2767"}

{:event/type "shoton"
:event/elapsed 51
:event/subtype "blocked_shot"
:event/player1 "Jonas Gutierrez"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1518717"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_2767"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Matthew Phillips"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1518718"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_2767"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Shola Ameobi"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1518734"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_2767"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Shola Ameobi"
:event/subtype "obstruction"
:event/player1 "Alex Baptiste"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1518742"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_2767"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Dudley Campbell"
:event/subtype "serious_foul"
:event/player1 "Cheik Tiote"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1518812"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_2767"}

{:event/type "card"
:event/elapsed 55
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Cheik Tiote"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1518815"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_2767"}

{:event/type "shotoff"
:event/elapsed 56
:event/subtype "direct_freekick"
:event/player1 "Charlie Adam"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1518826"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_2767"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Charlie Adam"
:event/subtype "serious_foul"
:event/player1 "Cheik Tiote"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1518847"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_2767"}

{:event/type "shotoff"
:event/elapsed 58
:event/subtype "direct_freekick"
:event/player1 "Neal Eardley"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1518857"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_2767"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Stephen Crainey"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1518882"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_2767"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Stephen Crainey"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1518920"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_2767"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Stephen Crainey"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1518939"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_2767"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Stephen Crainey"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1518956"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_2767"}

{:event/type "shotoff"
:event/elapsed 64
:event/subtype "header"
:event/player1 "Gary Taylor-Fletcher"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1518958"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_2767"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Cheik Tiote"
:event/subtype "from_behind"
:event/player1 "Gary Taylor-Fletcher"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1518977"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_2767"}

{:event/type "shotoff"
:event/elapsed 66
:event/subtype "post"
:event/player1 "Charlie Adam"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1519006"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_2767"}

{:event/type "shotoff"
:event/elapsed 66
:event/subtype "distance"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1519008"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_2767"}

{:event/type "foulcommit"
:event/elapsed 67
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1519025"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_2767"}

{:event/type "shoton"
:event/elapsed 68
:event/subtype "deflected"
:event/player1 "Shola Ameobi"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1519043"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_2767"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Joey Barton"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1519048"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_2767"}

{:event/type "corner"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Joey Barton"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1519048"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_2767"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Jose Enrique"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1519084"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_2767"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Joey Barton"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1519087"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_2767"}

{:event/type "corner"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Joey Barton"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1519087"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_2767"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Joey Barton"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1519099"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_2767"}

{:event/type "corner"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Joey Barton"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1519099"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_2767"}

{:event/type "shotoff"
:event/elapsed 72
:event/subtype "header"
:event/player1 "Fabricio Coloccini"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1519101"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_2767"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player1 "Gary Taylor-Fletcher"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1519107"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_2767"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Joey Barton"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1519118"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_2767"}

{:event/type "corner"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Joey Barton"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1519118"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_2767"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Stephen Crainey"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1519160"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_2767"}

{:event/type "shoton"
:event/elapsed 76
:event/subtype "blocked_shot"
:event/player1 "Gary Taylor-Fletcher"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1519164"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_2767"}

{:event/type "shotoff"
:event/elapsed 76
:event/subtype "shot"
:event/player1 "Keith Southern"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1519165"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_2767"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Cheik Tiote"
:event/player1 "Keith Southern"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1519175"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_2767"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1519217"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_2767"}

{:event/type "foulcommit"
:event/elapsed 80
:event/subtype "pushing"
:event/player1 "Gary Taylor-Fletcher"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1519221"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_2767"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Gary Taylor-Fletcher"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1519262"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_2767"}

{:event/type "shoton"
:event/elapsed 85
:event/subtype "blocked_shot"
:event/player1 "Stephen Ireland"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1519304"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_2767"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Jonas Gutierrez"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1519309"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_2767"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Stephen Crainey"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1519317"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_2767"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Tim Krul"
:event/subtype "pushing"
:event/player1 "Dudley Campbell"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1519339"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_2767"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Mike Williamson"
:event/subtype "serious_foul"
:event/player1 "Ian Evatt"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1519378"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_2767"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Ian Evatt"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_1519383"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_2767"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Stephen Crainey"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1519431"
:event/minute 94
:event/match_id "match_2767"}

{:event/type "foulcommit"
:event/elapsed_plus 4
:event/elapsed 90
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1519437"
:event/minute 94
:event/match_id "match_2767"}


]

