
;;# data
[
{:match/id "match_3399"
:match/league "England Premier League"
:match/hometeam "Chelsea"
:match/awayteam "Arsenal"
:match/score "2:1"
:match/hometeam_goals "2"
:match/awayteam_goals "1"}

{:event/type "shotoff"
:event/elapsed 1
:event/subtype "distance"
:event/player1 "Frank Lampard"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2562834"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_3399"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Fernando Torres"
:event/player1 "Per Mertesacker"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2562838"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Frank Lampard"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2562839"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_3399"}

{:event/type "shotoff"
:event/elapsed 3
:event/subtype "header"
:event/player1 "Branislav Ivanovic"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2562840"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Cesar Azpilicueta"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2562844"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_3399"}

{:event/type "shotoff"
:event/elapsed 5
:event/subtype "shot"
:event/player1 "Olivier Giroud"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2562847"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_3399"}

{:event/type "goal"
:event/elapsed 6
:event/player2 "Cesar Azpilicueta"
:event/subtype "shot"
:event/player1 "Juan Mata"
:event/sortorder 1
:event/team "home"
:event/id "event_2562851"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Juan Mata"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2562854"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_3399"}

{:event/type "shoton"
:event/elapsed 9
:event/subtype "distance"
:event/player1 "Santi Cazorla"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_2562859"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Theo Walcott"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_2562860"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3399"}

{:event/type "corner"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Theo Walcott"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_2562860"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3399"}

{:event/type "shoton"
:event/elapsed 11
:event/subtype "shot"
:event/player1 "Eden Hazard"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_2562865"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Juan Mata"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2562867"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_3399"}

{:event/type "corner"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Juan Mata"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2562867"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 13
:event/subtype "cross"
:event/player1 "Fernando Torres"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2562872"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Cesar Azpilicueta"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2562874"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Cesar Azpilicueta"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_2562876"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_3399"}

{:event/type "shotoff"
:event/elapsed 15
:event/subtype "distance"
:event/player1 "Oscar"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2562878"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_3399"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "Ramires"
:event/subtype "penalty"
:event/player1 "Wojciech Szczesny"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2562886"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_3399"}

{:event/type "card"
:event/elapsed 16
:event/card_type "y"
:event/player1 "Wojciech Szczesny"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_2562887"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_3399"}

{:event/type "goal"
:event/elapsed 16
:event/player1 "Frank Lampard"
:event/sortorder 3
:event/team "home"
:event/id "event_2562888"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Olivier Giroud"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2562889"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3399"}

{:event/type "corner"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Olivier Giroud"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2562889"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3399"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Ramires"
:event/subtype "advantage"
:event/player1 "Santi Cazorla"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2562891"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Juan Mata"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_2562892"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3399"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Oscar"
:event/player1 "Bacary Sagna"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2562894"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Bacary Sagna"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_2562903"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Kieran Gibbs"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2562905"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_3399"}

{:event/type "shoton"
:event/elapsed 21
:event/subtype "deflected"
:event/player1 "Eden Hazard"
:event/sortorder 5
:event/team "home"
:event/event_type "shoton"
:event/id "event_2562910"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Bacary Sagna"
:event/sortorder 6
:event/team "away"
:event/event_type "cross"
:event/id "event_2562911"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Santi Cazorla"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2562913"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Olivier Giroud"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_2562914"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_3399"}

{:event/type "corner"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Olivier Giroud"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_2562914"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_3399"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Eden Hazard"
:event/player1 "Francis Coquelin"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2562920"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Juan Mata"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2562921"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Juan Mata"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2562928"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Fernando Torres"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2562941"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_3399"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Abou Diaby"
:event/subtype "advantage"
:event/player1 "Oscar"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2562943"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Bacary Sagna"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2562944"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Ashley Cole"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2562948"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_3399"}

{:event/type "foulcommit"
:event/elapsed 30
:event/player2 "Oscar"
:event/player1 "Jack Wilshere"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2562952"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Oscar"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2562975"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Bacary Sagna"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2562985"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_3399"}

{:event/type "shotoff"
:event/elapsed 36
:event/subtype "bad shot"
:event/player1 "Ramires"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2562987"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_3399"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Bacary Sagna"
:event/player1 "Oscar"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2562990"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Jack Wilshere"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2562992"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Jack Wilshere"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_2562994"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_3399"}

{:event/type "corner"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Jack Wilshere"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_2562994"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Oscar"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2563000"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Theo Walcott"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2563002"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_3399"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Francis Coquelin"
:event/player1 "Fernando Torres"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2563007"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Ramires"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2563014"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Juan Mata"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2563017"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_3399"}

{:event/type "corner"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Juan Mata"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2563017"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Eden Hazard"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2563024"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_3399"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Ramires"
:event/subtype "pushing"
:event/player1 "Jack Wilshere"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2563030"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Juan Mata"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2563031"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_3399"}

{:event/type "shotoff"
:event/elapsed 45
:event/subtype "miss_kick"
:event/player1 "Fernando Torres"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2563032"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_3399"}

{:event/type "foulcommit"
:event/elapsed 46
:event/player2 "Francis Coquelin"
:event/player1 "Ramires"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2563097"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_3399"}

{:event/type "foulcommit"
:event/elapsed 47
:event/player2 "Theo Walcott"
:event/player1 "Ashley Cole"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2563099"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Jack Wilshere"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2563104"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_3399"}

{:event/type "shoton"
:event/elapsed 47
:event/subtype "shot"
:event/player1 "Per Mertesacker"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_2563106"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_3399"}

{:event/type "shoton"
:event/elapsed 49
:event/subtype "shot"
:event/player1 "Theo Walcott"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_2563112"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Bacary Sagna"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2563118"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Cesar Azpilicueta"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2563128"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_3399"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Santi Cazorla"
:event/subtype "pushing"
:event/player1 "Eden Hazard"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2563137"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Kieran Gibbs"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_2563146"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_3399"}

{:event/type "shoton"
:event/elapsed 57
:event/subtype "header"
:event/player1 "Olivier Giroud"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_2563147"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_3399"}

{:event/type "shoton"
:event/elapsed 58
:event/subtype "blocked_shot"
:event/player1 "Frank Lampard"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_2563151"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3399"}

{:event/type "goal"
:event/elapsed 58
:event/player2 "Santi Cazorla"
:event/subtype "shot"
:event/player1 "Theo Walcott"
:event/sortorder 2
:event/team "away"
:event/id "event_2563155"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3399"}

{:event/type "shotoff"
:event/elapsed 61
:event/subtype "shot"
:event/player1 "Theo Walcott"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2563173"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_3399"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Eden Hazard"
:event/player1 "Kieran Gibbs"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2563175"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Juan Mata"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2563176"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Theo Walcott"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2563179"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3399"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Frank Lampard"
:event/player1 "Bacary Sagna"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2563180"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3399"}

{:event/type "foulcommit"
:event/elapsed 66
:event/player2 "Theo Walcott"
:event/player1 "Ashley Cole"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2563186"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_3399"}

{:event/type "card"
:event/elapsed 66
:event/card_type "y"
:event/subtype "kicked_ball_away"
:event/player1 "Juan Mata"
:event/sortorder 4
:event/team "home"
:event/event_type "card"
:event/id "event_2563187"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_3399"}

{:event/type "shoton"
:event/elapsed 67
:event/subtype "blocked_shot"
:event/player1 "Santi Cazorla"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_2563203"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Jack Wilshere"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_2563204"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3399"}

{:event/type "corner"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Jack Wilshere"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_2563204"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Jack Wilshere"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2563215"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Juan Mata"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2563223"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_3399"}

{:event/type "corner"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Juan Mata"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2563223"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_3399"}

{:event/type "shoton"
:event/elapsed 73
:event/subtype "distance"
:event/player1 "Ramires"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_2563227"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Jack Wilshere"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_2563229"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3399"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Cesar Azpilicueta"
:event/player1 "Jack Wilshere"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2563231"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3399"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Aaron Ramsey"
:event/player1 "Ramires"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2563233"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3399"}

{:event/type "shoton"
:event/elapsed 76
:event/subtype "distance"
:event/player1 "Fernando Torres"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_2563239"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Theo Walcott"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2563276"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_3399"}

{:event/type "shoton"
:event/elapsed 83
:event/subtype "big chance shot"
:event/player1 "Demba Ba"
:event/sortorder 5
:event/team "home"
:event/event_type "shoton"
:event/id "event_2563283"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_3399"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Santi Cazorla"
:event/player1 "Ashley Cole"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2563302"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Jack Wilshere"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2563303"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3399"}

{:event/type "foulcommit"
:event/elapsed 87
:event/player2 "Bacary Sagna"
:event/player1 "Ashley Cole"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2563305"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_3399"}

{:event/type "card"
:event/elapsed 87
:event/card_type "y"
:event/player1 "Ashley Cole"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_2563306"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_3399"}

{:event/type "shotoff"
:event/elapsed 88
:event/subtype "direct_freekick"
:event/player1 "Thomas Vermaelen"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2563309"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_3399"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player2 "Demba Ba"
:event/player1 "Aaron Ramsey"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2563319"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Juan Mata"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2563321"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3399"}

{:event/type "shoton"
:event/elapsed 90
:event/subtype "blocked_shot"
:event/player1 "Ryan Bertrand"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_2563323"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3399"}

{:event/type "shoton"
:event/elapsed 90
:event/subtype "distance"
:event/player1 "Olivier Giroud"
:event/sortorder 4
:event/team "away"
:event/event_type "shoton"
:event/id "event_2563326"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Aaron Ramsey"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_2563336"
:event/minute 91
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Bacary Sagna"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2563347"
:event/minute 93
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Jack Wilshere"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_2563349"
:event/minute 93
:event/match_id "match_3399"}

{:event/type "corner"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Jack Wilshere"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_2563349"
:event/minute 93
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Jack Wilshere"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2563354"
:event/minute 94
:event/match_id "match_3399"}

{:event/type "corner"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Jack Wilshere"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2563354"
:event/minute 94
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Santi Cazorla"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_2563363"
:event/minute 94
:event/match_id "match_3399"}

{:event/type "corner"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Santi Cazorla"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_2563363"
:event/minute 94
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Jack Wilshere"
:event/sortorder 6
:event/team "away"
:event/event_type "corner"
:event/id "event_2563365"
:event/minute 94
:event/match_id "match_3399"}

{:event/type "corner"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Jack Wilshere"
:event/sortorder 6
:event/team "away"
:event/event_type "corner"
:event/id "event_2563365"
:event/minute 94
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Theo Walcott"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2563367"
:event/minute 95
:event/match_id "match_3399"}

{:event/type "cross"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Jack Wilshere"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_2563370"
:event/minute 95
:event/match_id "match_3399"}

{:event/type "shotoff"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "header"
:event/player1 "Olivier Giroud"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2563371"
:event/minute 95
:event/match_id "match_3399"}

{:event/type "foulcommit"
:event/elapsed_plus 6
:event/elapsed 90
:event/player2 "Cesar Azpilicueta"
:event/subtype "pushing"
:event/player1 "Olivier Giroud"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2563373"
:event/minute 96
:event/match_id "match_3399"}


]

