
;;# data
[
{:match/id "match_12204"
:match/league "Italy Serie A"
:match/hometeam "Torino"
:match/awayteam "Lazio"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 18
:event/card_type "y"
:event/player1 "Lucas Biglia"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3167496"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_12204"}

{:event/type "goal"
:event/elapsed 19
:event/player1 "Kamil Glik"
:event/sortorder 0
:event/team "home"
:event/id "event_3167497"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_12204"}

{:event/type "card"
:event/elapsed 36
:event/card_type "y"
:event/player1 "Brayan Perea"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3167604"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_12204"}

{:event/type "card"
:event/elapsed 45
:event/card_type "y"
:event/player1 "Migjen Basha"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3167716"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_12204"}

{:event/type "card"
:event/elapsed 55
:event/card_type "y"
:event/player1 "Alessio Cerci"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3167810"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_12204"}

{:event/type "card"
:event/elapsed 78
:event/card_type "y"
:event/player1 "Kamil Glik"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3167893"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_12204"}


]

