
;;# data
[
{:match/id "match_23159"
:match/league "Spain LIGA BBVA"
:match/hometeam "Atlético Madrid"
:match/awayteam "Levante UD"
:match/score "2:0"
:match/hometeam_goals "2"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 20
:event/card_type "y"
:event/player1 "Gabi"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2564013"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_23159"}

{:event/type "goal"
:event/elapsed 32
:event/player1 "Adrian Lopez"
:event/sortorder 0
:event/team "home"
:event/id "event_2564066"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_23159"}

{:event/type "card"
:event/elapsed 41
:event/card_type "y"
:event/player1 "Pedro Lopez"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2564067"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_23159"}

{:event/type "card"
:event/elapsed 50
:event/card_type "y"
:event/player1 "Michel Herrero"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2564100"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_23159"}

{:event/type "goal"
:event/elapsed 60
:event/player1 "Koke"
:event/sortorder 0
:event/team "home"
:event/id "event_2564101"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_23159"}

{:event/type "card"
:event/elapsed 79
:event/card_type "y"
:event/player1 "Gustavo Adolfo Munua"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2564108"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_23159"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Sergio Ballesteros"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2564114"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_23159"}


]

