
;;# data
[
{:match/id "match_22839"
:match/league "Spain LIGA BBVA"
:match/hometeam "Rayo Vallecano"
:match/awayteam "Racing Santander"
:match/score "4:2"
:match/hometeam_goals "4"
:match/awayteam_goals "2"}

{:event/type "card"
:event/elapsed 3
:event/card_type "r"
:event/player1 "Tono"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1973827"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_22839"}

{:event/type "goal"
:event/elapsed 9
:event/player1 "Marc Torrejon Moya"
:event/sortorder 0
:event/team "away"
:event/id "event_1973833"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_22839"}

{:event/type "goal"
:event/elapsed 28
:event/player1 "Gonzalo Colsa"
:event/sortorder 0
:event/team "away"
:event/id "event_1973947"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_22839"}

{:event/type "card"
:event/elapsed 40
:event/card_type "y"
:event/player1 "Emiliano Daniel Armenteros"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1974039"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_22839"}

{:event/type "card"
:event/elapsed 42
:event/card_type "y"
:event/player1 "Diego Costa"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1974040"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_22839"}

{:event/type "goal"
:event/elapsed 45
:event/player1 "Michu"
:event/sortorder 0
:event/team "home"
:event/id "event_1974093"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_22839"}

{:event/type "card"
:event/elapsed 53
:event/card_type "y"
:event/player1 "Javi Fuego"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1974305"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_22839"}

{:event/type "card"
:event/elapsed 54
:event/card_type "y"
:event/player1 "Raul Tamudo"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1974306"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_22839"}

{:event/type "goal"
:event/elapsed 65
:event/player1 "Michu"
:event/sortorder 0
:event/team "home"
:event/id "event_1974246"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_22839"}

{:event/type "goal"
:event/elapsed 68
:event/player1 "Raul Tamudo"
:event/sortorder 0
:event/team "home"
:event/id "event_1974251"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_22839"}

{:event/type "card"
:event/elapsed 71
:event/card_type "y"
:event/player1 "Alvaro Gonzalez Soberon"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1974307"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_22839"}

{:event/type "goal"
:event/elapsed 73
:event/player1 "Piti"
:event/sortorder 0
:event/team "home"
:event/id "event_1974304"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_22839"}

{:event/type "card"
:event/elapsed 87
:event/card_type "y"
:event/player1 "Pape Kouli Diop"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1974453"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_22839"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Bernardo"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1974454"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_22839"}


]

