
;;# data
[
{:match/id "match_12600"
:match/league "Italy Serie A"
:match/hometeam "Lazio"
:match/awayteam "Sampdoria"
:match/score "3:0"
:match/hometeam_goals "3"
:match/awayteam_goals "0"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Felipe Anderson"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4051405"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_12600"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Dusan Basta"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4051422"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_12600"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Vasco Regini"
:event/player1 "Dusan Basta"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4051430"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_12600"}

{:event/type "corner"
:event/elapsed 8
:event/subtype "short_left"
:event/player1 "Lucas Biglia"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4051444"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_12600"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Senad Lulic"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4051445"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_12600"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Vasco Regini"
:event/player1 "Marco Parolo"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4051449"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_12600"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Stefan Daniel Radu"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4051465"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_12600"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Stefan Daniel Radu"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4051472"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_12600"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Fabrizio Cacciatore"
:event/player1 "Senad Lulic"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4051481"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_12600"}

{:event/type "shotoff"
:event/elapsed 13
:event/subtype "distance"
:event/player1 "Stefan Daniel Radu"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4051490"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_12600"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Felipe Anderson"
:event/player1 "Pedro Mba Obiang"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4051496"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_12600"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Angelo Palombo"
:event/player1 "Filip Djordjevic"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4051497"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_12600"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Stefan Daniel Radu"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4051503"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_12600"}

{:event/type "corner"
:event/elapsed 17
:event/subtype "cross_right"
:event/player1 "Lucas Biglia"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4051505"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_12600"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Lucas Biglia"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4051507"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_12600"}

{:event/type "corner"
:event/elapsed 19
:event/subtype "cross_right"
:event/player1 "Lucas Biglia"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4051512"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_12600"}

{:event/type "foulcommit"
:event/elapsed 19
:event/subtype "hands"
:event/player1 "Marco Parolo"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4051513"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_12600"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Felipe Anderson"
:event/player1 "Daniele Gastaldello"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4051520"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_12600"}

{:event/type "card"
:event/elapsed 20
:event/card_type "y"
:event/player1 "Daniele Gastaldello"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4051521"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_12600"}

{:event/type "shoton"
:event/elapsed 21
:event/subtype "direct_freekick"
:event/player1 "Lucas Biglia"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4051525"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_12600"}

{:event/type "corner"
:event/elapsed 22
:event/subtype "cross_right"
:event/player1 "Lucas Biglia"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4051527"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_12600"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Filip Djordjevic"
:event/player1 "Luca Rizzo"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4051537"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_12600"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Dusan Basta"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4051538"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_12600"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Felipe Anderson"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4051544"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_12600"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Lucas Biglia"
:event/subtype "pushing"
:event/player1 "Angelo Palombo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4051548"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_12600"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4051551"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_12600"}

{:event/type "shoton"
:event/elapsed 25
:event/subtype "shot"
:event/player1 "Stefano Okaka Chuka"
:event/sortorder 4
:event/team "away"
:event/event_type "shoton"
:event/id "event_4051553"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_12600"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Dusan Basta"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4051568"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_12600"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Dusan Basta"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4051571"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_12600"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Senad Lulic"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4051573"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_12600"}

{:event/type "shoton"
:event/elapsed 29
:event/subtype "blocked_header"
:event/player1 "Filip Djordjevic"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_4051574"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_12600"}

{:event/type "corner"
:event/elapsed 29
:event/subtype "short_left"
:event/player1 "Lucas Biglia"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_4051578"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_12600"}

{:event/type "shotoff"
:event/elapsed 29
:event/subtype "shot"
:event/player1 "Stefan de Vrij"
:event/sortorder 6
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4051580"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_12600"}

{:event/type "shotoff"
:event/elapsed 30
:event/subtype "deflected"
:event/player1 "Felipe Anderson"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4051583"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_12600"}

{:event/type "corner"
:event/elapsed 31
:event/subtype "cross_left"
:event/player1 "Lucas Biglia"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4051585"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_12600"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Fabrizio Cacciatore"
:event/subtype "dangerous_play"
:event/player1 "Marco Parolo"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4051587"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_12600"}

{:event/type "shoton"
:event/elapsed 33
:event/subtype "distance"
:event/player1 "Felipe Anderson"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4051594"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_12600"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Dusan Basta"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4051597"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_12600"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Felipe Anderson"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4051601"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_12600"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Emiliano Viviano"
:event/subtype "pushing"
:event/player1 "Filip Djordjevic"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4051602"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_12600"}

{:event/type "shotoff"
:event/elapsed 37
:event/subtype "bad shot"
:event/player1 "Stefan Daniel Radu"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4051607"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_12600"}

{:event/type "goal"
:event/elapsed 38
:event/player2 "Felipe Anderson"
:event/subtype "shot"
:event/player1 "Marco Parolo"
:event/sortorder 1
:event/team "home"
:event/id "event_4051611"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_12600"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Stefano Okaka Chuka"
:event/player1 "Lorik Cana"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4051616"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_12600"}

{:event/type "shotoff"
:event/elapsed 41
:event/subtype "deflected"
:event/player1 "Marco Parolo"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4051619"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_12600"}

{:event/type "corner"
:event/elapsed 41
:event/subtype "cross_right"
:event/player1 "Lucas Biglia"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4051621"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_12600"}

{:event/type "goal"
:event/elapsed 41
:event/player2 "Senad Lulic"
:event/subtype "distance"
:event/player1 "Felipe Anderson"
:event/sortorder 3
:event/team "home"
:event/id "event_4051623"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_12600"}

{:event/type "foulcommit"
:event/elapsed 43
:event/subtype "hands"
:event/player1 "Filip Djordjevic"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4051625"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_12600"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Angelo Palombo"
:event/player1 "Felipe Anderson"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4051637"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_12600"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Luca Rizzo"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4051641"
:event/minute 46
:event/match_id "match_12600"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "Roberto Soriano"
:event/subtype "dangerous_play"
:event/player1 "Lorik Cana"
:event/sortorder 6
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4051648"
:event/minute 46
:event/match_id "match_12600"}

{:event/type "shoton"
:event/elapsed 47
:event/subtype "shot"
:event/player1 "Felipe Anderson"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4051667"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_12600"}

{:event/type "card"
:event/elapsed_plus 2
:event/elapsed 45
:event/card_type "y"
:event/player1 "Lorik Cana"
:event/sortorder 7
:event/team "home"
:event/event_type "card"
:event/id "event_4051649"
:event/minute 47
:event/match_id "match_12600"}

{:event/type "shotoff"
:event/elapsed 50
:event/subtype "shot"
:event/player1 "Senad Lulic"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4051683"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_12600"}

{:event/type "shoton"
:event/elapsed 51
:event/subtype "distance"
:event/player1 "Filip Djordjevic"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4051690"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_12600"}

{:event/type "corner"
:event/elapsed 51
:event/subtype "cross_left"
:event/player1 "Lucas Biglia"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_4051692"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_12600"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Emiliano Viviano"
:event/player1 "Filip Djordjevic"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4051694"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_12600"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Marco Parolo"
:event/player1 "Pawel Wszolek"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4051697"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_12600"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Filip Djordjevic"
:event/player1 "Pawel Wszolek"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4051700"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_12600"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Lucas Biglia"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4051701"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_12600"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Ogenyi Onazi"
:event/player1 "Pedro Mba Obiang"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4051705"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_12600"}

{:event/type "shoton"
:event/elapsed 55
:event/subtype "blocked_shot"
:event/player1 "Felipe Anderson"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4051708"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_12600"}

{:event/type "corner"
:event/elapsed 55
:event/subtype "short_left"
:event/player1 "Lucas Biglia"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_4051709"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_12600"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "unknown"
:event/player1 "Dusan Basta"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4051711"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_12600"}

{:event/type "card"
:event/elapsed 56
:event/card_type "y"
:event/subtype "emergency_brake"
:event/player1 "Dusan Basta"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_4051714"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_12600"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Angelo Palombo"
:event/player1 "Ogenyi Onazi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4051720"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_12600"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Stefan Daniel Radu"
:event/player1 "Stefano Okaka Chuka"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4051721"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_12600"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Dusan Basta"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4051724"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_12600"}

{:event/type "shoton"
:event/elapsed 61
:event/subtype "header"
:event/player1 "Marco Parolo"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_4051725"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_12600"}

{:event/type "shotoff"
:event/elapsed 63
:event/subtype "deflected"
:event/player1 "Marco Parolo"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4051731"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_12600"}

{:event/type "corner"
:event/elapsed 63
:event/subtype "short_left"
:event/player1 "Lucas Biglia"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4051732"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_12600"}

{:event/type "shotoff"
:event/elapsed 63
:event/subtype "shot"
:event/player1 "Stefano Mauri"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4051734"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_12600"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Lucas Biglia"
:event/player1 "Roberto Soriano"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4051739"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_12600"}

{:event/type "card"
:event/elapsed 64
:event/card_type "y"
:event/player1 "Roberto Soriano"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_4051741"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_12600"}

{:event/type "foulcommit"
:event/elapsed 66
:event/player2 "Roberto Soriano"
:event/player1 "Lucas Biglia"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4051745"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_12600"}

{:event/type "goal"
:event/elapsed 66
:event/player2 "Felipe Anderson"
:event/subtype "tap_in"
:event/player1 "Filip Djordjevic"
:event/sortorder 4
:event/team "home"
:event/id "event_4051749"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_12600"}

{:event/type "shoton"
:event/elapsed 68
:event/subtype "distance"
:event/player1 "unknown"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4051755"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_12600"}

{:event/type "shotoff"
:event/elapsed 72
:event/subtype "shot"
:event/player1 "unknown"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4051767"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_12600"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Dusan Basta"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4051778"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_12600"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Roberto Soriano"
:event/player1 "Marco Parolo"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4051781"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_12600"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Fabrizio Cacciatore"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4051786"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_12600"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Filip Djordjevic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4051796"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_12600"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Angelo Palombo"
:event/player1 "Filip Djordjevic"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4051803"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_12600"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Angelo Palombo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4051805"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_12600"}

{:event/type "shotoff"
:event/elapsed 83
:event/subtype "distance"
:event/player1 "Stefano Okaka Chuka"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4051812"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_12600"}

{:event/type "shotoff"
:event/elapsed 86
:event/subtype "deflected"
:event/player1 "Felipe Anderson"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4051821"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_12600"}

{:event/type "corner"
:event/elapsed 86
:event/subtype "cross_right"
:event/player1 "Antonio Candreva"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4051824"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_12600"}

{:event/type "corner"
:event/elapsed 88
:event/subtype "short_right"
:event/player1 "Antonio Candreva"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4051832"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_12600"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Antonio Candreva"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4051834"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_12600"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player1 "Felipe Anderson"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4051837"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_12600"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player2 "Angelo Palombo"
:event/player1 "Ogenyi Onazi"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4051838"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_12600"}

{:event/type "shotoff"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "deflected"
:event/player1 "Stefano Okaka Chuka"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4051849"
:event/minute 93
:event/match_id "match_12600"}

{:event/type "corner"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross_left"
:event/player1 "Roberto Soriano"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_4051850"
:event/minute 93
:event/match_id "match_12600"}


]

