
;;# data
[
{:match/id "match_4293"
:match/league "England Premier League"
:match/hometeam "Liverpool"
:match/awayteam "Queens Park Rangers"
:match/score "3:1"
:match/hometeam_goals "2"
:match/awayteam_goals "1"}

{:event/type "corner"
:event/elapsed 1
:event/subtype "cross_right"
:event/player1 "Matthew Phillips"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4425857"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_4293"}

{:event/type "shoton"
:event/elapsed 2
:event/subtype "blocked_shot"
:event/player1 "Philippe Coutinho"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4425870"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_4293"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Adam Lallana"
:event/subtype "trip"
:event/player1 "Nedum Onuoha"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4425916"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_4293"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Raheem Sterling"
:event/subtype "trip"
:event/player1 "Clint Hill"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4425934"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_4293"}

{:event/type "foulcommit"
:event/elapsed 8
:event/player2 "Charlie Austin"
:event/subtype "trip"
:event/player1 "Dejan Lovren"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4426026"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Matthew Phillips"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4426042"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_4293"}

{:event/type "shotoff"
:event/elapsed 9
:event/subtype "volley"
:event/player1 "Steven Caulker"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4426066"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Matthew Phillips"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_4426090"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_4293"}

{:event/type "corner"
:event/elapsed 10
:event/subtype "cross_left"
:event/player1 "Matthew Phillips"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4426104"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_4293"}

{:event/type "shoton"
:event/elapsed 10
:event/subtype "distance"
:event/player1 "Leroy Fer"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_4426120"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_4293"}

{:event/type "corner"
:event/elapsed 11
:event/subtype "cross_left"
:event/player1 "Matthew Phillips"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4426128"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_4293"}

{:event/type "shotoff"
:event/elapsed 11
:event/subtype "shot"
:event/player1 "Karl Henry"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4426138"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_4293"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Glen Johnson"
:event/subtype "trip"
:event/player1 "Matthew Phillips"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4426163"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_4293"}

{:event/type "shotoff"
:event/elapsed 13
:event/subtype "volley"
:event/player1 "Steven Gerrard"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4426189"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_4293"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Adam Lallana"
:event/subtype "trip"
:event/player1 "Leroy Fer"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4426216"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Adam Lallana"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4426227"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Raheem Sterling"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4426263"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_4293"}

{:event/type "shoton"
:event/elapsed 16
:event/subtype "shot"
:event/player1 "Rickie Lambert"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4426281"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Raheem Sterling"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4426304"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4426307"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_4293"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Leroy Fer"
:event/subtype "trip"
:event/player1 "Steven Gerrard"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4426317"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_4293"}

{:event/type "card"
:event/elapsed 18
:event/card_type "y"
:event/player1 "Steven Gerrard"
:event/sortorder 3
:event/team "home"
:event/event_type "card"
:event/id "event_4426322"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Matthew Phillips"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_4426330"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_4293"}

{:event/type "goal"
:event/elapsed 20
:event/player2 "Rickie Lambert"
:event/subtype "shot"
:event/player1 "Philippe Coutinho"
:event/sortorder 0
:event/team "home"
:event/id "event_4426349"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_4293"}

{:event/type "corner"
:event/elapsed 21
:event/subtype "cross_right"
:event/player1 "Steven Gerrard"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4426373"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_4293"}

{:event/type "shotoff"
:event/elapsed 24
:event/subtype "shot"
:event/player1 "Adam Lallana"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4426422"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_4293"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Nedum Onuoha"
:event/subtype "pushing"
:event/player1 "Adam Lallana"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4426446"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_4293"}

{:event/type "shotoff"
:event/elapsed 26
:event/subtype "shot"
:event/player1 "Steven Caulker"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4426453"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_4293"}

{:event/type "shotoff"
:event/elapsed 27
:event/subtype "shot"
:event/player1 "Steven Gerrard"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4426467"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Matthew Phillips"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4426476"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_4426494"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Raheem Sterling"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4426507"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Karl Henry"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4426514"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_4293"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Raheem Sterling"
:event/subtype "trip"
:event/player1 "Sandro"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4426529"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Emre Can"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4426543"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_4293"}

{:event/type "shotoff"
:event/elapsed 35
:event/subtype "shot"
:event/player1 "Charlie Austin"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4426628"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Raheem Sterling"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4426689"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_4293"}

{:event/type "shoton"
:event/elapsed 38
:event/subtype "blocked_shot"
:event/player1 "Philippe Coutinho"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4426717"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Charlie Austin"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4426735"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_4293"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Emre Can"
:event/subtype "trip"
:event/player1 "Joey Barton"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4426751"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_4293"}

{:event/type "shoton"
:event/elapsed 40
:event/subtype "direct_freekick"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4426780"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Raheem Sterling"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4426788"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_4293"}

{:event/type "corner"
:event/elapsed 41
:event/subtype "cross_right"
:event/player1 "Jordan Henderson"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4426798"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_4293"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Joey Barton"
:event/subtype "dangerous_play"
:event/player1 "Steven Gerrard"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4426803"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_4293"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Jordan Henderson"
:event/subtype "serious_foul"
:event/player1 "Sandro"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4426849"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_4293"}

{:event/type "card"
:event/elapsed 43
:event/card_type "y"
:event/player1 "Sandro"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4426854"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4426857"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_4293"}

{:event/type "shotoff"
:event/elapsed 43
:event/subtype "header"
:event/player1 "Dejan Lovren"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4426861"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Raheem Sterling"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4427363"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_4293"}

{:event/type "foulcommit"
:event/elapsed 47
:event/player2 "Glen Johnson"
:event/subtype "pushing"
:event/player1 "Leroy Fer"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4427400"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_4293"}

{:event/type "corner"
:event/elapsed 47
:event/subtype "short_right"
:event/player1 "Raheem Sterling"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_4427426"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Jordan Henderson"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4427431"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_4293"}

{:event/type "shotoff"
:event/elapsed 48
:event/subtype "shot"
:event/player1 "Philippe Coutinho"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4427435"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_4427496"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_4293"}

{:event/type "shotoff"
:event/elapsed 49
:event/subtype "shot"
:event/player1 "Joey Barton"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4427507"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_4293"}

{:event/type "shotoff"
:event/elapsed 50
:event/subtype "shot"
:event/player1 "Adam Lallana"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4427541"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Matthew Phillips"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4427615"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_4293"}

{:event/type "shotoff"
:event/elapsed 52
:event/subtype "header"
:event/player1 "Suk-Young Yun"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4427626"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_4293"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Emre Can"
:event/subtype "trip"
:event/player1 "Charlie Austin"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4427668"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Emre Can"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4427682"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_4293"}

{:event/type "corner"
:event/elapsed 53
:event/subtype "cross_right"
:event/player1 "Jordan Henderson"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4427693"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Jordan Henderson"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4427727"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_4293"}

{:event/type "shotoff"
:event/elapsed 55
:event/subtype "big chance shot"
:event/player1 "Raheem Sterling"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4427729"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Emre Can"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4427789"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_4293"}

{:event/type "foulcommit"
:event/elapsed 57
:event/subtype "hands"
:event/player1 "Richard Dunne"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4427816"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_4293"}

{:event/type "shoton"
:event/elapsed 58
:event/subtype "blocked_shot"
:event/player1 "Rickie Lambert"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4427851"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Adam Lallana"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4427930"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Suk-Young Yun"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4427960"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_4293"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Suk-Young Yun"
:event/subtype "pull"
:event/player1 "Emre Can"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4427980"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Joey Barton"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4427997"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_4293"}

{:event/type "shoton"
:event/elapsed 65
:event/subtype "shot"
:event/player1 "Rickie Lambert"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4428162"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Jordan Henderson"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4428169"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_4293"}

{:event/type "foulcommit"
:event/elapsed 66
:event/player2 "Adam Lallana"
:event/subtype "trip"
:event/player1 "Karl Henry"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4428184"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_4293"}

{:event/type "shoton"
:event/elapsed 66
:event/subtype "blocked_shot"
:event/player1 "Sandro"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4428206"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_4293"}

{:event/type "shoton"
:event/elapsed 67
:event/subtype "shot"
:event/player1 "Matthew Phillips"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4428209"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_4293"}

{:event/type "shoton"
:event/elapsed 69
:event/subtype "blocked_shot"
:event/player1 "Rickie Lambert"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4428261"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_4293"}

{:event/type "shotoff"
:event/elapsed 69
:event/subtype "deflected"
:event/player1 "Steven Gerrard"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4428263"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_4293"}

{:event/type "corner"
:event/elapsed 69
:event/subtype "cross_right"
:event/player1 "Steven Gerrard"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_4428269"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_4293"}

{:event/type "shoton"
:event/elapsed 69
:event/subtype "header"
:event/player1 "Dejan Lovren"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_4428275"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_4293"}

{:event/type "corner"
:event/elapsed 70
:event/subtype "cross_right"
:event/player1 "Matthew Phillips"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4428298"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Suk-Young Yun"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4428313"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_4293"}

{:event/type "corner"
:event/elapsed 71
:event/subtype "cross_left"
:event/player1 "Matthew Phillips"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_4428339"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Matthew Phillips"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4428343"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Matthew Phillips"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4428363"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_4293"}

{:event/type "corner"
:event/elapsed 73
:event/subtype "cross_right"
:event/player1 "Joey Barton"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4428368"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_4293"}

{:event/type "goal"
:event/elapsed 73
:event/player2 "Joey Barton"
:event/subtype "shot"
:event/player1 "Leroy Fer"
:event/sortorder 1
:event/team "away"
:event/id "event_4428370"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_4293"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Bobby Zamora"
:event/subtype "trip"
:event/player1 "Dejan Lovren"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4428414"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_4293"}

{:event/type "card"
:event/elapsed 75
:event/card_type "y"
:event/player1 "Dejan Lovren"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4428418"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Joey Barton"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4428426"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_4293"}

{:event/type "foulcommit"
:event/elapsed 76
:event/player2 "Suk-Young Yun"
:event/subtype "trip"
:event/player1 "Philippe Coutinho"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4428436"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Joey Barton"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4428442"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_4293"}

{:event/type "foulcommit"
:event/elapsed 76
:event/player2 "Raheem Sterling"
:event/subtype "trip"
:event/player1 "Richard Dunne"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4428454"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_4293"}

{:event/type "card"
:event/elapsed 76
:event/card_type "y"
:event/player1 "Richard Dunne"
:event/sortorder 4
:event/team "away"
:event/event_type "card"
:event/id "event_4428456"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Emre Can"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4428464"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Jordan Henderson"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4428487"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_4293"}

{:event/type "corner"
:event/elapsed 78
:event/subtype "cross_right"
:event/player1 "Jordan Henderson"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4428493"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_4293"}

{:event/type "foulcommit"
:event/elapsed 79
:event/player2 "Martin Skrtel"
:event/subtype "penalty"
:event/player1 "Nedum Onuoha"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4428502"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_4293"}

{:event/type "card"
:event/elapsed 79
:event/card_type "y"
:event/player1 "Nedum Onuoha"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_4428510"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_4293"}

{:event/type "goal"
:event/elapsed 79
:event/subtype "saved_back_into_play"
:event/player1 "Steven Gerrard"
:event/sortorder 3
:event/team "home"
:event/id "event_4428514"
:event/event_type "goal"
:event/goal_type "npm"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_4293"}

{:event/type "corner"
:event/elapsed 80
:event/subtype "cross_right"
:event/player1 "Jordan Henderson"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4428525"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_4293"}

{:event/type "shotoff"
:event/elapsed 80
:event/subtype "header"
:event/player1 "Steven Gerrard"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4428526"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_4293"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Dejan Lovren"
:event/subtype "trip"
:event/player1 "Bobby Zamora"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4428536"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_4293"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Matthew Phillips"
:event/subtype "trip"
:event/player1 "Emre Can"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4428553"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Suk-Young Yun"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4428570"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Charlie Austin"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4428576"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_4293"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Jordon Ibe"
:event/subtype "trip"
:event/player1 "Nedum Onuoha"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4428585"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_4293"}

{:event/type "card"
:event/elapsed 82
:event/card_type "y"
:event/player1 "Nedum Onuoha"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_4428588"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4428620"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_4293"}

{:event/type "shotoff"
:event/elapsed 85
:event/subtype "volley"
:event/player1 "Raheem Sterling"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4428646"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_4293"}

{:event/type "corner"
:event/elapsed 86
:event/subtype "short_left"
:event/player1 "Philippe Coutinho"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4428677"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Philippe Coutinho"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4428678"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_4293"}

{:event/type "shoton"
:event/elapsed 87
:event/subtype "blocked_shot"
:event/player1 "Philippe Coutinho"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4428687"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_4293"}

{:event/type "corner"
:event/elapsed 87
:event/subtype "cross_left"
:event/player1 "Philippe Coutinho"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_4428690"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_4293"}

{:event/type "goal"
:event/elapsed 87
:event/player2 "Philippe Coutinho"
:event/subtype "header"
:event/player1 "Steven Gerrard"
:event/sortorder 4
:event/team "home"
:event/id "event_4428692"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_4293"}

{:event/type "foulcommit"
:event/elapsed 90
:event/subtype "hands"
:event/player1 "Sandro"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4428747"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_4293"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Charlie Austin"
:event/subtype "trip"
:event/player1 "Lucas Leiva"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4428766"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Joey Barton"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4428775"
:event/minute 91
:event/match_id "match_4293"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "bicycle_kick"
:event/player1 "Clint Hill"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4428782"
:event/minute 91
:event/match_id "match_4293"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Jordon Ibe"
:event/subtype "pull"
:event/player1 "Joey Barton"
:event/sortorder 7
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4428806"
:event/minute 92
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Raheem Sterling"
:event/sortorder 8
:event/team "home"
:event/event_type "cross"
:event/id "event_4428816"
:event/minute 93
:event/match_id "match_4293"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Philippe Coutinho"
:event/sortorder 10
:event/team "home"
:event/event_type "cross"
:event/id "event_4428821"
:event/minute 93
:event/match_id "match_4293"}

{:event/type "shoton"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "header"
:event/player1 "Jordon Ibe"
:event/sortorder 11
:event/team "home"
:event/event_type "shoton"
:event/id "event_4428826"
:event/minute 93
:event/match_id "match_4293"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Martin Skrtel"
:event/subtype "trip"
:event/player1 "Charlie Austin"
:event/sortorder 12
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4428828"
:event/minute 93
:event/match_id "match_4293"}

{:event/type "card"
:event/elapsed_plus 3
:event/elapsed 90
:event/card_type "y"
:event/player1 "Charlie Austin"
:event/sortorder 13
:event/team "away"
:event/event_type "card"
:event/id "event_4428830"
:event/minute 93
:event/match_id "match_4293"}


]

