
;;# data
[
{:match/id "match_5836"
:match/league "France Ligue 1"
:match/hometeam "Stade Rennais FC"
:match/awayteam "AS Nancy-Lorraine"
:match/score "0:2"
:match/hometeam_goals "0"
:match/awayteam_goals "2"}

{:event/type "goal"
:event/elapsed 16
:event/player1 "Bakaye Traore"
:event/sortorder 0
:event/team "away"
:event/id "event_1562757"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_5836"}

{:event/type "card"
:event/elapsed 54
:event/card_type "y"
:event/player1 "Fabien Lemoine"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1563426"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_5836"}

{:event/type "card"
:event/elapsed 79
:event/card_type "y"
:event/player1 "Youssouf Hadji"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1563569"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_5836"}

{:event/type "goal"
:event/elapsed 90
:event/player1 "Julien Feret"
:event/sortorder 0
:event/team "away"
:event/id "event_1563601"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_5836"}


]

