
;;# data
[
{:match/id "match_9543"
:match/league "Germany 1. Bundesliga"
:match/hometeam "FC Augsburg"
:match/awayteam "VfB Stuttgart"
:match/score "2:1"
:match/hometeam_goals "2"
:match/awayteam_goals "1"}

{:event/type "goal"
:event/elapsed 6
:event/player1 "Halil Altintop"
:event/sortorder 0
:event/team "home"
:event/id "event_2937746"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_9543"}

{:event/type "card"
:event/elapsed 10
:event/card_type "y"
:event/player1 "Paul Verhaegh"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2937817"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_9543"}

{:event/type "card"
:event/elapsed 24
:event/card_type "y"
:event/player1 "Mohammed Abdellaoue"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2937837"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_9543"}

{:event/type "goal"
:event/elapsed 36
:event/player1 "Jan-Ingwer Callsen-Bracker"
:event/sortorder 0
:event/team "home"
:event/id "event_2937863"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_9543"}

{:event/type "goal"
:event/elapsed 42
:event/player1 "Vedad Ibisevic"
:event/sortorder 0
:event/team "away"
:event/id "event_2937897"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_9543"}

{:event/type "card"
:event/elapsed 60
:event/card_type "y"
:event/player1 "Christian Gentner"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2938213"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_9543"}

{:event/type "card"
:event/elapsed 67
:event/card_type "y"
:event/player1 "Gotoku Sakai"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2938236"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_9543"}

{:event/type "card"
:event/elapsed 70
:event/card_type "r"
:event/player1 "Ibrahima Traore"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2938246"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_9543"}

{:event/type "card"
:event/elapsed 86
:event/card_type "y"
:event/player1 "Andre Hahn"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_2938309"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_9543"}


]

