
;;# data
[
{:match/id "match_22624"
:match/league "Spain LIGA BBVA"
:match/hometeam "UD Almería"
:match/awayteam "Málaga CF"
:match/score "2:1"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "card"
:event/elapsed 40
:event/card_type "y"
:event/player1 "Juanma Ortiz"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1206566"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_22624"}

{:event/type "card"
:event/elapsed 40
:event/card_type "y"
:event/player1 "Eliseu"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1206645"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_22624"}

{:event/type "card"
:event/elapsed 42
:event/card_type "r"
:event/player1 "Eliseu"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1206559"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_22624"}

{:event/type "card"
:event/elapsed 44
:event/card_type "y"
:event/player1 "Antonio Apono"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1206646"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_22624"}

{:event/type "goal"
:event/elapsed 50
:event/player1 "Quincy Owusu-Abeyie"
:event/sortorder 0
:event/team "away"
:event/id "event_1206757"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_22624"}

{:event/type "card"
:event/elapsed 63
:event/card_type "y"
:event/player1 "Patrick Mtiliga"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1206959"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_22624"}

{:event/type "goal"
:event/elapsed 64
:event/player1 "Kalu Uche"
:event/sortorder 0
:event/team "home"
:event/id "event_1206958"
:event/event_type "goal"
:event/goal_type "npm"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_22624"}

{:event/type "card"
:event/elapsed 66
:event/card_type "y"
:event/player1 "Carlos Garcia"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1206960"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_22624"}

{:event/type "card"
:event/elapsed 67
:event/card_type "y"
:event/player1 "Fernando"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1207010"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_22624"}

{:event/type "goal"
:event/elapsed 76
:event/player1 "Kalu Uche"
:event/sortorder 0
:event/team "home"
:event/id "event_1207049"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_22624"}

{:event/type "card"
:event/elapsed 79
:event/card_type "y"
:event/player1 "Ruben"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1207050"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_22624"}

{:event/type "card"
:event/elapsed 80
:event/card_type "y"
:event/player1 "Marcelo Silva"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1207173"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_22624"}


]

