
;;# data
[
{:match/id "match_21520"
:match/league "Spain LIGA BBVA"
:match/hometeam "RC Deportivo de La Coruña"
:match/awayteam "Real Madrid CF"
:match/score "2:1"
:match/hometeam_goals "2"
:match/awayteam_goals "1"}

{:event/type "foulcommit"
:event/elapsed 1
:event/subtype "hands"
:event/player1 "Ruud van Nistelrooy"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_393365"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Pablo Alvarez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_393368"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_21520"}

{:event/type "shotoff"
:event/elapsed 2
:event/subtype "post"
:event/player1 "Mista"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_393370"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Marcelo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_393383"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Marcelo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_393394"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_21520"}

{:event/type "shotoff"
:event/elapsed 7
:event/subtype "shot"
:event/player1 "Gonzalo Higuain"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_393395"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player1 "Sergio Ramos"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_393400"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Pablo Alvarez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_393421"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Alberto Lopo"
:event/player1 "Raul"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_393424"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 13
:event/subtype "cross"
:event/player1 "Ruud van Nistelrooy"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_393426"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Andres Guardado"
:event/player1 "Jose Maria Guti"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_393450"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Pablo Alvarez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_393453"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Sergio Ramos"
:event/player1 "Julian de Guzman"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_393455"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player1 "Laure"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_393456"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Sergio"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_393459"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_21520"}

{:event/type "shoton"
:event/elapsed 23
:event/subtype "blocked_shot"
:event/player1 "Gonzalo Higuain"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_393464"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Andres Guardado"
:event/player1 "Pepe"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_393470"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Andres Guardado"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_393471"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_21520"}

{:event/type "goal"
:event/elapsed 27
:event/player2 "Andres Guardado"
:event/subtype "header"
:event/player1 "Mista"
:event/sortorder 0
:event/team "home"
:event/id "event_393472"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Pepe"
:event/player1 "Mista"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_393473"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Marcelo"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_393474"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_21520"}

{:event/type "shoton"
:event/elapsed 29
:event/subtype "blocked_shot"
:event/player1 "Arjen Robben"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_393475"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Raul"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_393478"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 30
:event/player1 "Pepe"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_393480"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Raul"
:event/subtype "shirt_pull"
:event/player1 "Alberto Lopo"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_393481"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_21520"}

{:event/type "card"
:event/elapsed 31
:event/card_type "y"
:event/subtype "shirt_pull"
:event/player1 "Alberto Lopo"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_393482"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_21520"}

{:event/type "shotoff"
:event/elapsed 32
:event/subtype "header"
:event/player1 "Arjen Robben"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_393484"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Mahamadou Diarra"
:event/player1 "Julian de Guzman"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_393486"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_21520"}

{:event/type "shoton"
:event/elapsed 34
:event/subtype "deflected"
:event/player1 "Arjen Robben"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_393488"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 34
:event/player2 "Andres Guardado"
:event/player1 "Sergio Ramos"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_393489"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Ze Castro"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_393492"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_21520"}

{:event/type "corner"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Ze Castro"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_393492"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_21520"}

{:event/type "shoton"
:event/elapsed 35
:event/subtype "shot"
:event/player1 "Arjen Robben"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_393499"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_393505"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_21520"}

{:event/type "corner"
:event/elapsed 36
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_393505"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_21520"}

{:event/type "shotoff"
:event/elapsed 36
:event/subtype "distance"
:event/player1 "Jose Maria Guti"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_393506"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Arjen Robben"
:event/player1 "Filipe Luis"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_393513"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Mahamadou Diarra"
:event/subtype "pushing"
:event/player1 "Julian de Guzman"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_393521"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Jose Maria Guti"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_393525"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Joan Verdu"
:event/player1 "Mahamadou Diarra"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_393527"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_21520"}

{:event/type "shoton"
:event/elapsed 42
:event/subtype "blocked_shot"
:event/player1 "Sergio"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_393532"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_21520"}

{:event/type "shotoff"
:event/elapsed 42
:event/subtype "distance"
:event/player1 "Sergio"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_393534"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Marcelo"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_393540"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Julian de Guzman"
:event/player1 "Pepe"
:event/sortorder 5
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_393542"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_21520"}

{:event/type "shoton"
:event/elapsed 44
:event/subtype "blocked_shot"
:event/player1 "Gonzalo Higuain"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_393550"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Arjen Robben"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_393551"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_21520"}

{:event/type "shotoff"
:event/elapsed 45
:event/subtype "header"
:event/player1 "Marcelo"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_393556"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_21520"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "crossbar"
:event/player1 "Marcelo"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_393563"
:event/minute 46
:event/match_id "match_21520"}

{:event/type "shoton"
:event/elapsed 47
:event/subtype "blocked_shot"
:event/player1 "Raul"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_393630"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_21520"}

{:event/type "goal"
:event/elapsed 47
:event/subtype "shot"
:event/player1 "Ruud van Nistelrooy"
:event/sortorder 3
:event/team "away"
:event/id "event_393633"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Andres Guardado"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_393638"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Andres Guardado"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_393642"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Mahamadou Diarra"
:event/subtype "pushing"
:event/player1 "Julian de Guzman"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_393648"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Andres Guardado"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_393658"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_21520"}

{:event/type "corner"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Andres Guardado"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_393658"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_21520"}

{:event/type "goal"
:event/elapsed 51
:event/player2 "Andres Guardado"
:event/subtype "header"
:event/player1 "Alberto Lopo"
:event/sortorder 3
:event/team "home"
:event/id "event_393660"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_21520"}

{:event/type "corner"
:event/elapsed 54
:event/subtype "short"
:event/player1 "Arjen Robben"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_393671"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Marcelo"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_393672"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_21520"}

{:event/type "shoton"
:event/elapsed 54
:event/subtype "header"
:event/player1 "Mahamadou Diarra"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_393673"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Mista"
:event/subtype "serious_foul"
:event/player1 "Jose Maria Guti"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_393677"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_21520"}

{:event/type "card"
:event/elapsed 55
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Jose Maria Guti"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_393678"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Filipe Luis"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_393684"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Gabriel Heinze"
:event/player1 "Joan Verdu"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_393685"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Julian de Guzman"
:event/subtype "pushing"
:event/player1 "Ruud van Nistelrooy"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_393692"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Marcelo"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_393693"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 59
:event/player2 "Gabriel Heinze"
:event/player1 "Mista"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_393695"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Andres Guardado"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_393704"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Sergio"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_393708"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_21520"}

{:event/type "corner"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Sergio"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_393708"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Mahamadou Diarra"
:event/player1 "Alberto Lopo"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_393711"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_21520"}

{:event/type "shoton"
:event/elapsed 63
:event/subtype "distance"
:event/player1 "Mahamadou Diarra"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_393717"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Gonzalo Higuain"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_393718"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_21520"}

{:event/type "corner"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Gonzalo Higuain"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_393718"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Laure"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_393728"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_21520"}

{:event/type "shoton"
:event/elapsed 66
:event/subtype "blocked_shot"
:event/player1 "Arjen Robben"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_393737"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_21520"}

{:event/type "shotoff"
:event/elapsed 67
:event/subtype "shot"
:event/player1 "Julian de Guzman"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_393744"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Ivan Sanchez Riki"
:event/subtype "shirt_pull"
:event/player1 "Gabriel Heinze"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_393749"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Andres Guardado"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_393753"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_21520"}

{:event/type "corner"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Andres Guardado"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_393753"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player1 "Ivan Sanchez Riki"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_393754"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Filipe Luis"
:event/subtype "serious_foul"
:event/player1 "Sergio Ramos"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_393756"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_21520"}

{:event/type "card"
:event/elapsed 71
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Sergio Ramos"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_393757"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Arjen Robben"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_393764"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Pablo Alvarez"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_393766"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_21520"}

{:event/type "shotoff"
:event/elapsed 75
:event/subtype "deflected"
:event/player1 "Julian de Guzman"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_393768"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Sergio"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_393769"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_21520"}

{:event/type "corner"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Sergio"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_393769"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Gonzalo Higuain"
:event/subtype "serious_foul"
:event/player1 "Pablo Alvarez"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_393770"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_21520"}

{:event/type "card"
:event/elapsed 75
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Pablo Alvarez"
:event/sortorder 3
:event/team "home"
:event/event_type "card"
:event/id "event_393771"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_21520"}

{:event/type "shoton"
:event/elapsed 76
:event/subtype "blocked_shot"
:event/player1 "Marcelo"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_393773"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Filipe Luis"
:event/subtype "pushing"
:event/player1 "Sergio Ramos"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_393776"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 78
:event/player2 "Alberto Lopo"
:event/player1 "Raul"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_393778"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_21520"}

{:event/type "card"
:event/elapsed 79
:event/card_type "y"
:event/subtype "stall_time"
:event/player1 "Daniel Aranzubia"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_393779"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Jose Maria Guti"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_393781"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_21520"}

{:event/type "corner"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Jose Maria Guti"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_393781"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_21520"}

{:event/type "shoton"
:event/elapsed 81
:event/subtype "distance"
:event/player1 "Gonzalo Higuain"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_393783"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_21520"}

{:event/type "shotoff"
:event/elapsed 81
:event/subtype "shot"
:event/player1 "Joan Verdu"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_393784"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Alberto Lopo"
:event/player1 "Ruud van Nistelrooy"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_393788"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Sergio Ramos"
:event/subtype "pushing"
:event/player1 "Andres Guardado"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_393789"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Juan Rodriguez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_393790"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_21520"}

{:event/type "shoton"
:event/elapsed 85
:event/subtype "shot"
:event/player1 "Omar Bravo"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_393791"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Royston Drenthe"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_393792"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_21520"}

{:event/type "corner"
:event/elapsed 85
:event/subtype "short"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_393794"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Laure"
:event/subtype "serious_foul"
:event/player1 "Marcelo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_393795"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_21520"}

{:event/type "card"
:event/elapsed 86
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Marcelo"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_393796"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Mahamadou Diarra"
:event/subtype "pushing"
:event/player1 "Omar Bravo"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_393797"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_21520"}

{:event/type "corner"
:event/elapsed 90
:event/subtype "short"
:event/player1 "Joan Verdu"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_393806"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Andres Guardado"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_393807"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player1 "Sergio"
:event/sortorder 5
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_393809"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Andres Guardado"
:event/subtype "pushing"
:event/player1 "Mahamadou Diarra"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_393811"
:event/minute 91
:event/match_id "match_21520"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Sergio Ramos"
:event/player1 "Alberto Lopo"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_393813"
:event/minute 92
:event/match_id "match_21520"}

{:event/type "shoton"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "blocked_shot"
:event/player1 "Sergio Ramos"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_393814"
:event/minute 92
:event/match_id "match_21520"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Arjen Robben"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_393815"
:event/minute 93
:event/match_id "match_21520"}


]

