
;;# data
[
{:match/id "match_11149"
:match/league "Italy Serie A"
:match/hometeam "Milan"
:match/awayteam "Cesena"
:match/score "1:1"
:match/hometeam_goals "2"
:match/awayteam_goals "0"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Fabio Caserta"
:event/player1 "Alexander Merkel"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1379018"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_11149"}

{:event/type "shoton"
:event/elapsed 3
:event/subtype "big chance shot"
:event/player1 "Dominique Malonga"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1379025"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1379028"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Fabio Caserta"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1379030"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_11149"}

{:event/type "corner"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Fabio Caserta"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1379030"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_11149"}

{:event/type "shotoff"
:event/elapsed 5
:event/subtype "distance"
:event/player1 "Thiago Silva"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1379032"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_11149"}

{:event/type "foulcommit"
:event/elapsed 6
:event/player2 "Robinho"
:event/player1 "Fabio Caserta"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1379035"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_11149"}

{:event/type "shotoff"
:event/elapsed 7
:event/subtype "distance"
:event/player1 "Massimo Ambrosini"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1379037"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Luca Ceccarelli"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1379041"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_11149"}

{:event/type "shotoff"
:event/elapsed 11
:event/subtype "deflected"
:event/player1 "Dominique Malonga"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1379045"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Fabio Caserta"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1379046"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_11149"}

{:event/type "corner"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Fabio Caserta"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1379046"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_11149"}

{:event/type "card"
:event/elapsed 12
:event/card_type "y"
:event/player1 "Fabio Caserta"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_1379049"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_11149"}

{:event/type "shotoff"
:event/elapsed 13
:event/subtype "distance"
:event/player1 "Dominique Malonga"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1379050"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 13
:event/subtype "cross"
:event/player1 "Massimo Ambrosini"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1379054"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Luca Ceccarelli"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1379058"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Zlatan Ibrahimovic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1379064"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_11149"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "Fabio Caserta"
:event/player1 "Antonio Cassano"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1379066"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_11149"}

{:event/type "shoton"
:event/elapsed 17
:event/subtype "big chance shot"
:event/player1 "Matias Ezequiel Schelotto"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1379070"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Matias Ezequiel Schelotto"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1379071"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Fabio Caserta"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1379075"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_11149"}

{:event/type "corner"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Fabio Caserta"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1379075"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Fabio Caserta"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1379077"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_11149"}

{:event/type "shotoff"
:event/elapsed 18
:event/subtype "shot"
:event/player1 "Igor Budan"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1379079"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Zlatan Ibrahimovic"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1379083"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_11149"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Igor Budan"
:event/player1 "Alessandro Nesta"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1379087"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_11149"}

{:event/type "card"
:event/elapsed 21
:event/card_type "y"
:event/player1 "Alessandro Nesta"
:event/sortorder 11
:event/team "home"
:event/event_type "card"
:event/id "event_1379093"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_11149"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player1 "Luca Antonini"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1379099"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_11149"}

{:event/type "card"
:event/elapsed 23
:event/card_type "y"
:event/player1 "Luca Antonini"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_1379097"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Robinho"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1379102"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_11149"}

{:event/type "foulcommit"
:event/elapsed 25
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1379104"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Marco Parolo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1379107"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_11149"}

{:event/type "shoton"
:event/elapsed 27
:event/subtype "big chance shot"
:event/player1 "Robinho"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1379112"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Antonio Cassano"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1379116"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Antonio Cassano"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1379122"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Thiago Silva"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1379125"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_11149"}

{:event/type "shoton"
:event/elapsed 30
:event/subtype "big chance shot"
:event/player1 "Zlatan Ibrahimovic"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1379128"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_11149"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Luca Antonini"
:event/subtype "shirt_pull"
:event/player1 "Matias Ezequiel Schelotto"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1379131"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Matias Ezequiel Schelotto"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1379132"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_11149"}

{:event/type "shoton"
:event/elapsed 32
:event/subtype "big chance shot"
:event/player1 "Thiago Silva"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_1379141"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Antonio Cassano"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1379144"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_11149"}

{:event/type "corner"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Antonio Cassano"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1379144"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_11149"}

{:event/type "shotoff"
:event/elapsed 33
:event/subtype "big chance shot"
:event/player1 "Luca Antonini"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1379145"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_11149"}

{:event/type "foulcommit"
:event/elapsed 34
:event/player2 "Luca Antonini"
:event/subtype "pushing"
:event/player1 "Matias Ezequiel Schelotto"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1379155"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_11149"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Thiago Silva"
:event/player1 "Fabio Caserta"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1379157"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_11149"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Steve von Bergen"
:event/player1 "Massimo Ambrosini"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1379159"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Luca Ceccarelli"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1379165"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_11149"}

{:event/type "shotoff"
:event/elapsed 37
:event/subtype "bad shot"
:event/player1 "Antonio Cassano"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1379169"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_11149"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Giuseppe Colucci"
:event/subtype "pushing"
:event/player1 "Zlatan Ibrahimovic"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1379176"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_11149"}

{:event/type "shotoff"
:event/elapsed 39
:event/subtype "deflected"
:event/player1 "Fabio Caserta"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1379177"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Antonio Cassano"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1379179"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_11149"}

{:event/type "shotoff"
:event/elapsed 40
:event/subtype "distance"
:event/player1 "Marco Parolo"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1379183"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1379186"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_11149"}

{:event/type "shotoff"
:event/elapsed 41
:event/subtype "shot"
:event/player1 "Antonio Cassano"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1379189"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Ignazio Abate"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1379197"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_11149"}

{:event/type "shoton"
:event/elapsed 42
:event/subtype "header"
:event/player1 "Zlatan Ibrahimovic"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1379198"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Thiago Silva"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1379201"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_11149"}

{:event/type "shoton"
:event/elapsed 43
:event/subtype "big chance header"
:event/player1 "Zlatan Ibrahimovic"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1379202"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Ignazio Abate"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1379203"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_11149"}

{:event/type "goal"
:event/elapsed 45
:event/player1 "Maximiliano Pellegrino"
:event/sortorder 2
:event/team "away"
:event/id "event_1379210"
:event/event_type "goal"
:event/goal_type "o"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Antonio Cassano"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1379238"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_11149"}

{:event/type "corner"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "short"
:event/player1 "Alexander Merkel"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1379216"
:event/minute 47
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Antonio Cassano"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1379242"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Antonio Cassano"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1379244"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_11149"}

{:event/type "corner"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Antonio Cassano"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1379244"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Zlatan Ibrahimovic"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1379246"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_11149"}

{:event/type "foulcommit"
:event/elapsed 50
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1379249"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_11149"}

{:event/type "corner"
:event/elapsed 52
:event/subtype "short"
:event/player1 "Antonio Cassano"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1379252"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_11149"}

{:event/type "corner"
:event/elapsed 52
:event/subtype "short"
:event/player1 "Antonio Cassano"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1379254"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_11149"}

{:event/type "shotoff"
:event/elapsed 55
:event/subtype "volley"
:event/player1 "Massimo Ambrosini"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1379259"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_11149"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Robinho"
:event/subtype "shirt_pull"
:event/player1 "Giuseppe Colucci"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1379262"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_11149"}

{:event/type "shoton"
:event/elapsed 56
:event/subtype "direct_freekick"
:event/player1 "Zlatan Ibrahimovic"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1379264"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_11149"}

{:event/type "corner"
:event/elapsed 57
:event/subtype "short"
:event/player1 "Antonio Cassano"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1379265"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_11149"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Antonio Cassano"
:event/subtype "pushing"
:event/player1 "Fabio Caserta"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1379267"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_11149"}

{:event/type "shotoff"
:event/elapsed 57
:event/subtype "direct_freekick"
:event/player1 "Robinho"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1379268"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Antonio Cassano"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1379272"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_11149"}

{:event/type "foulcommit"
:event/elapsed 59
:event/player1 "Dominique Malonga"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1379276"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Antonio Cassano"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1379277"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_11149"}

{:event/type "shotoff"
:event/elapsed 60
:event/subtype "volley"
:event/player1 "Zlatan Ibrahimovic"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1379282"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_11149"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Fabio Caserta"
:event/player1 "Ignazio Abate"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1379288"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_11149"}

{:event/type "foulcommit"
:event/elapsed 64
:event/subtype "shirt_pull"
:event/player1 "Antonio Cassano"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1379301"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Ignazio Abate"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1379302"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Ignazio Abate"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1379303"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_11149"}

{:event/type "shotoff"
:event/elapsed 65
:event/subtype "distance"
:event/player1 "Fabio Caserta"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1379307"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Zlatan Ibrahimovic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1379314"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Fabio Caserta"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1379317"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_11149"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Antonio Cassano"
:event/player1 "Maximiliano Pellegrino"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1379320"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Massimo Ambrosini"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1379323"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_11149"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Dominique Malonga"
:event/player1 "Alexander Merkel"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1379325"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_11149"}

{:event/type "shotoff"
:event/elapsed 69
:event/subtype "direct_freekick"
:event/player1 "Marco Parolo"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1379328"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_11149"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Massimo Ambrosini"
:event/player1 "Marco Parolo"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1379330"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Massimo Ambrosini"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1379332"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_11149"}

{:event/type "shotoff"
:event/elapsed 71
:event/subtype "distance"
:event/player1 "Thiago Silva"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1379337"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_11149"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Antonio Cassano"
:event/player1 "Paolo Sammarco"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1379341"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_11149"}

{:event/type "shotoff"
:event/elapsed 74
:event/subtype "deflected"
:event/player1 "Antonio Cassano"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1379349"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Zlatan Ibrahimovic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1379356"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_11149"}

{:event/type "shoton"
:event/elapsed 77
:event/subtype "big chance shot"
:event/player1 "Robinho"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_1379363"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_11149"}

{:event/type "shoton"
:event/elapsed 78
:event/subtype "shot"
:event/player1 "Robinho"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1379365"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_11149"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Erjon Bogdani"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1379370"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_11149"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Giuseppe Colucci"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1379375"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Paolo Sammarco"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1379376"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_11149"}

{:event/type "shotoff"
:event/elapsed 82
:event/subtype "bad shot"
:event/player1 "Paolo Sammarco"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1379387"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_11149"}

{:event/type "card"
:event/elapsed 82
:event/card_type "y"
:event/player1 "Christian Abbiati"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_1379390"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_11149"}

{:event/type "shoton"
:event/elapsed 86
:event/subtype "volley"
:event/player1 "Robinho"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1379401"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_11149"}

{:event/type "shotoff"
:event/elapsed 86
:event/subtype "deflected"
:event/player1 "Robinho"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1379402"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_11149"}

{:event/type "foulcommit"
:event/elapsed 87
:event/player2 "Erjon Bogdani"
:event/subtype "shirt_pull"
:event/player1 "Mario Yepes"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1379405"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_11149"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player1 "Marco Parolo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1379409"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Robinho"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1379410"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_11149"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player2 "Massimo Ambrosini"
:event/player1 "Marco Parolo"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1379414"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_11149"}

{:event/type "shotoff"
:event/elapsed 90
:event/subtype "direct_freekick"
:event/player1 "Alexandre Pato"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1379415"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_11149"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Massimo Ambrosini"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1379418"
:event/minute 91
:event/match_id "match_11149"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Thiago Silva"
:event/subtype "pushing"
:event/player1 "Dominique Malonga"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1379421"
:event/minute 92
:event/match_id "match_11149"}

{:event/type "shotoff"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "big chance crossbar"
:event/player1 "Robinho"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1379424"
:event/minute 92
:event/match_id "match_11149"}

{:event/type "shotoff"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "volley"
:event/player1 "Giuseppe Colucci"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1379427"
:event/minute 93
:event/match_id "match_11149"}

{:event/type "goal"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Robinho"
:event/subtype "shot"
:event/player1 "Zlatan Ibrahimovic"
:event/sortorder 2
:event/team "home"
:event/id "event_1379428"
:event/event_type "goal"
:event/goal_type "n"
:event/minute 93
:event/match_id "match_11149"}


]

