
;;# data
[
{:match/id "match_15341"
:match/league "Netherlands Eredivisie"
:match/hometeam "PEC Zwolle"
:match/awayteam "Ajax"
:match/score "1:1"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "card"
:event/elapsed 6
:event/card_type "y"
:event/player1 "Jesper Drost"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_4400041"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_15341"}

{:event/type "card"
:event/elapsed 33
:event/card_type "y"
:event/player1 "Lucas Andersen"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_4400288"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_15341"}

{:event/type "card"
:event/elapsed 40
:event/card_type "y"
:event/player1 "Joel Veltman"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_4400358"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_15341"}

{:event/type "goal"
:event/elapsed 48
:event/player2 "Ryan Thomas"
:event/player1 "Jesper Drost"
:event/sortorder 0
:event/team "home"
:event/id "event_4400978"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_15341"}

{:event/type "goal"
:event/elapsed 89
:event/player1 "Kolbeinn Sigthorsson"
:event/sortorder 0
:event/team "away"
:event/id "event_4401765"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_15341"}


]

