
;;# data
[
{:match/id "match_12011"
:match/league "Italy Serie A"
:match/hometeam "Torino"
:match/awayteam "Roma"
:match/score "1:2"
:match/hometeam_goals "1"
:match/awayteam_goals "2"}

{:event/type "goal"
:event/elapsed 22
:event/player1 "Pablo Osvaldo"
:event/sortorder 0
:event/team "away"
:event/id "event_2699491"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_12011"}

{:event/type "card"
:event/elapsed 27
:event/card_type "y"
:event/player1 "Nicolas Burdisso"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2699565"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_12011"}

{:event/type "goal"
:event/elapsed 31
:event/player1 "Rolando Bianchi"
:event/sortorder 0
:event/team "home"
:event/id "event_2699564"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_12011"}

{:event/type "card"
:event/elapsed 32
:event/card_type "y"
:event/player1 "Rolando Bianchi"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2699566"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_12011"}

{:event/type "card"
:event/elapsed 34
:event/card_type "y"
:event/player1 "Alessandro Gazzi"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2699574"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_12011"}

{:event/type "card"
:event/elapsed 38
:event/card_type "y"
:event/player1 "Federico Balzaretti"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2699660"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_12011"}

{:event/type "goal"
:event/elapsed 60
:event/player1 "Erik Lamela"
:event/sortorder 0
:event/team "away"
:event/id "event_2699763"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_12011"}

{:event/type "card"
:event/elapsed 77
:event/card_type "y"
:event/player1 "Giuseppe Vives"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2699850"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_12011"}

{:event/type "card"
:event/elapsed 80
:event/card_type "y"
:event/player1 "Federico Balzaretti"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2699864"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_12011"}

{:event/type "card"
:event/elapsed 83
:event/card_type "y"
:event/player1 "Michael Bradley"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2699878"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_12011"}


]

