
;;# data
[
{:match/id "match_12548"
:match/league "Italy Serie A"
:match/hometeam "Hellas Verona"
:match/awayteam "Fiorentina"
:match/score "1:2"
:match/hometeam_goals "1"
:match/awayteam_goals "2"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Alejandro Gonzalez"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3957312"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "Luca Toni"
:event/subtype "trip"
:event/player1 "Stefan Savic"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3957330"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_12548"}

{:event/type "shoton"
:event/elapsed 4
:event/subtype "shot"
:event/player1 "Panagiotis Tachtsidis"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3957355"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_12548"}

{:event/type "shotoff"
:event/elapsed 5
:event/subtype "shot"
:event/player1 "Nicolas Lopez"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3957377"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Borja Valero"
:event/subtype "trip"
:event/player1 "Mounir Obbadi"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3957379"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_12548"}

{:event/type "shoton"
:event/elapsed 8
:event/subtype "blocked_shot"
:event/player1 "David Pizarro"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3957419"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Marcos Alonso"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3957420"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_12548"}

{:event/type "corner"
:event/elapsed 10
:event/subtype "cross_right"
:event/player1 "Gustavo Campanharo"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3957460"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "David Pizarro"
:event/subtype "trip"
:event/player1 "Gustavo Campanharo"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3957468"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Marcos Alonso"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3957472"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_12548"}

{:event/type "shotoff"
:event/elapsed 11
:event/subtype "volley"
:event/player1 "Joaquin"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3957476"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Joaquin"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_3957485"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Gonzalo Rodriguez"
:event/subtype "pushing"
:event/player1 "Luca Toni"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3957504"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 13
:event/subtype "cross"
:event/player1 "David Pizarro"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3957528"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Marcos Alonso"
:event/subtype "trip"
:event/player1 "Alejandro Gonzalez"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3957534"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Matias Fernandez"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3957553"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Matias Fernandez"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3957561"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_12548"}

{:event/type "shoton"
:event/elapsed 15
:event/subtype "big chance shot"
:event/player1 "Juan Cuadrado"
:event/sortorder 5
:event/team "away"
:event/event_type "shoton"
:event/id "event_3957573"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_12548"}

{:event/type "corner"
:event/elapsed 16
:event/subtype "cross_right"
:event/player1 "Matias Fernandez"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3957583"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_12548"}

{:event/type "goal"
:event/elapsed 16
:event/player2 "Marcos Alonso"
:event/subtype "shot"
:event/player1 "Gonzalo Rodriguez"
:event/sortorder 2
:event/team "away"
:event/id "event_3957587"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_12548"}

{:event/type "shoton"
:event/elapsed 17
:event/subtype "blocked_shot"
:event/player1 "Nicolas Lopez"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3957606"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_12548"}

{:event/type "corner"
:event/elapsed 17
:event/subtype "cross_right"
:event/player1 "Nicolas Lopez"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3957609"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Joaquin"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3957622"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_12548"}

{:event/type "corner"
:event/elapsed 20
:event/subtype "cross_right"
:event/player1 "Matias Fernandez"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3957642"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_12548"}

{:event/type "shoton"
:event/elapsed 20
:event/subtype "header"
:event/player1 "Gonzalo Rodriguez"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3957646"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_12548"}

{:event/type "corner"
:event/elapsed 20
:event/subtype "cross_right"
:event/player1 "Matias Fernandez"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_3957653"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Vangelis Moras"
:event/subtype "pushing"
:event/player1 "Marcos Alonso"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3957657"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Rafael Marquez"
:event/subtype "pushing"
:event/player1 "Mario Gomez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3957663"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Marcos Alonso"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3957674"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_12548"}

{:event/type "shoton"
:event/elapsed 22
:event/subtype "shot"
:event/player1 "Marcos Alonso"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_3957681"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Artur Ionita"
:event/subtype "trip"
:event/player1 "David Pizarro"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3957687"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Emil Hallfredsson"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3957702"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Gustavo Campanharo"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3957704"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Neto"
:event/subtype "pushing"
:event/player1 "Luca Toni"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3957707"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Borja Valero"
:event/subtype "trip"
:event/player1 "Gustavo Campanharo"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3957734"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_12548"}

{:event/type "card"
:event/elapsed 26
:event/card_type "y"
:event/player1 "Gustavo Campanharo"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_3957739"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Luca Toni"
:event/subtype "trip"
:event/player1 "Gonzalo Rodriguez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3957766"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_12548"}

{:event/type "shotoff"
:event/elapsed 29
:event/subtype "crossbar"
:event/player1 "Mario Gomez"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3957772"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_12548"}

{:event/type "shotoff"
:event/elapsed 30
:event/subtype "shot"
:event/player1 "Marcos Alonso"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3957795"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 32
:event/subtype "hands"
:event/player1 "Luca Toni"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3957838"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "David Pizarro"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3957857"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Emil Hallfredsson"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3957863"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_12548"}

{:event/type "shotoff"
:event/elapsed 34
:event/subtype "crossbar"
:event/player1 "Luca Toni"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3957866"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Luca Toni"
:event/subtype "trip"
:event/player1 "David Pizarro"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3957910"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_12548"}

{:event/type "card"
:event/elapsed 36
:event/card_type "y"
:event/player1 "David Pizarro"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_3957912"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Panagiotis Tachtsidis"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3957917"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Marcos Alonso"
:event/subtype "trip"
:event/player1 "Alejandro Gonzalez"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3957931"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Matias Fernandez"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3957939"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_12548"}

{:event/type "goal"
:event/elapsed 39
:event/player2 "Luca Toni"
:event/subtype "shot"
:event/player1 "Nicolas Lopez"
:event/sortorder 2
:event/team "home"
:event/id "event_3957960"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_12548"}

{:event/type "card"
:event/elapsed 40
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Neto"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_3957997"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_12548"}

{:event/type "shoton"
:event/elapsed 41
:event/subtype "blocked_shot"
:event/player1 "Juan Cuadrado"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_3958022"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Luca Toni"
:event/subtype "serious_foul"
:event/player1 "Borja Valero"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3958036"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_12548"}

{:event/type "card"
:event/elapsed 42
:event/card_type "y"
:event/player1 "Borja Valero"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_3958040"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Nicolas Lopez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3958052"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Joaquin"
:event/subtype "pull"
:event/player1 "Artur Ionita"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3958068"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Juan Cuadrado"
:event/subtype "trip"
:event/player1 "Alejandro Gonzalez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3958087"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Matias Fernandez"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3958095"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Joaquin"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_3958113"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "Vangelis Moras"
:event/subtype "pushing"
:event/player1 "Mario Gomez"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3958125"
:event/minute 46
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 47
:event/player2 "Stefan Savic"
:event/subtype "pushing"
:event/player1 "Luca Toni"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3958309"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Juan Cuadrado"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3958318"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 45
:event/player2 "Nicolas Lopez"
:event/subtype "pushing"
:event/player1 "David Pizarro"
:event/sortorder 6
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3958150"
:event/minute 47
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "cross"
:event/player1 "David Pizarro"
:event/sortorder 7
:event/team "away"
:event/event_type "cross"
:event/id "event_3958171"
:event/minute 48
:event/match_id "match_12548"}

{:event/type "corner"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "cross_right"
:event/player1 "Matias Fernandez"
:event/sortorder 9
:event/team "away"
:event/event_type "corner"
:event/id "event_3958178"
:event/minute 48
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Borja Valero"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3958333"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Luca Toni"
:event/subtype "pushing"
:event/player1 "Jose Maria Basanta"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3958348"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_12548"}

{:event/type "corner"
:event/elapsed 50
:event/subtype "cross_right"
:event/player1 "Matias Fernandez"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_3958364"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Vangelis Moras"
:event/subtype "pushing"
:event/player1 "Mario Gomez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3958367"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Matias Fernandez"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3958379"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_12548"}

{:event/type "shotoff"
:event/elapsed 52
:event/subtype "deflected"
:event/player1 "Juan Cuadrado"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3958387"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_12548"}

{:event/type "corner"
:event/elapsed 52
:event/subtype "cross_right"
:event/player1 "Matias Fernandez"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_3958389"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Joaquin"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3958397"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Gustavo Campanharo"
:event/subtype "pushing"
:event/player1 "Marcos Alonso"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3958400"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_12548"}

{:event/type "shotoff"
:event/elapsed 55
:event/subtype "shot"
:event/player1 "Marcos Alonso"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3958428"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Juan Cuadrado"
:event/subtype "trip"
:event/player1 "Gustavo Campanharo"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3958445"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Matias Fernandez"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3958461"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_12548"}

{:event/type "corner"
:event/elapsed 58
:event/subtype "cross_left"
:event/player1 "Matias Fernandez"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_3958469"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Borja Valero"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_3958474"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Borja Valero"
:event/sortorder 6
:event/team "away"
:event/event_type "cross"
:event/id "event_3958476"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_12548"}

{:event/type "shoton"
:event/elapsed 58
:event/subtype "blocked_header"
:event/player1 "Mario Gomez"
:event/sortorder 7
:event/team "away"
:event/event_type "shoton"
:event/id "event_3958480"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Joaquin"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3958491"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_12548"}

{:event/type "shotoff"
:event/elapsed 59
:event/subtype "big chance volley"
:event/player1 "Marcos Alonso"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3958493"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 60
:event/subtype "hands"
:event/player1 "Luca Toni"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3958498"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Borja Valero"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3958518"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_12548"}

{:event/type "corner"
:event/elapsed 61
:event/subtype "short_right"
:event/player1 "Matias Fernandez"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_3958524"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Marcos Alonso"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3958529"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_12548"}

{:event/type "goal"
:event/elapsed 62
:event/player2 "Marcos Alonso"
:event/subtype "shot"
:event/player1 "Juan Cuadrado"
:event/sortorder 1
:event/team "away"
:event/id "event_3958530"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Juan Cuadrado"
:event/subtype "dangerous_play"
:event/player1 "Vangelis Moras"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3958573"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Emil Hallfredsson"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3958588"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_12548"}

{:event/type "shotoff"
:event/elapsed 67
:event/subtype "volley"
:event/player1 "Panagiotis Tachtsidis"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3958598"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Juan Vargas"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3958608"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_12548"}

{:event/type "corner"
:event/elapsed 69
:event/subtype "cross_left"
:event/player1 "Matias Fernandez"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3958614"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 72
:event/player2 "Lazaros Christodoulopoulos"
:event/subtype "trip"
:event/player1 "Stefan Savic"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3958644"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_12548"}

{:event/type "shoton"
:event/elapsed 73
:event/subtype "distance"
:event/player1 "Lazaros Christodoulopoulos"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3958656"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Lazaros Christodoulopoulos"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3958657"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Artur Ionita"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_3958659"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_12548"}

{:event/type "shotoff"
:event/elapsed 74
:event/subtype "header"
:event/player1 "Lazaros Christodoulopoulos"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3958664"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_12548"}

{:event/type "corner"
:event/elapsed 75
:event/subtype "cross_right"
:event/player1 "Matias Fernandez"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3958677"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Lazaros Christodoulopoulos"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_3958682"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_12548"}

{:event/type "shotoff"
:event/elapsed 75
:event/subtype "volley"
:event/player1 "Gustavo Campanharo"
:event/sortorder 5
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3958685"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_12548"}

{:event/type "shotoff"
:event/elapsed 77
:event/subtype "deflected"
:event/player1 "Panagiotis Tachtsidis"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3958700"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_12548"}

{:event/type "corner"
:event/elapsed 77
:event/subtype "cross_left"
:event/player1 "Lazaros Christodoulopoulos"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_3958705"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_12548"}

{:event/type "corner"
:event/elapsed 78
:event/subtype "cross_left"
:event/player1 "Lazaros Christodoulopoulos"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3958710"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_12548"}

{:event/type "shotoff"
:event/elapsed 78
:event/subtype "shot"
:event/player1 "Luca Toni"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3958712"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 79
:event/subtype "hands"
:event/player1 "Artur Ionita"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3958721"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Nicolas Lopez"
:event/subtype "pull"
:event/player1 "Jose Maria Basanta"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3958733"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_12548"}

{:event/type "card"
:event/elapsed 80
:event/card_type "y"
:event/player1 "Jose Maria Basanta"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_3958734"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Lazaros Christodoulopoulos"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3958740"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Vangelis Moras"
:event/subtype "trip"
:event/player1 "Mario Gomez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3958758"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 83
:event/player2 "Artur Ionita"
:event/subtype "trip"
:event/player1 "Juan Vargas"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3958779"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Nicolas Lopez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3958797"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Javier Saviola"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3958818"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_12548"}

{:event/type "corner"
:event/elapsed 87
:event/subtype "short_right"
:event/player1 "Nicolas Lopez"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3958825"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_12548"}

{:event/type "shotoff"
:event/elapsed 87
:event/subtype "deflected"
:event/player1 "Rafael Marquez"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3958826"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_12548"}

{:event/type "corner"
:event/elapsed 87
:event/subtype "cross_right"
:event/player1 "Nicolas Lopez"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_3958828"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_12548"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Nicolas Lopez"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_3958835"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Juan Cuadrado"
:event/subtype "pull"
:event/player1 "Lazaros Christodoulopoulos"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3958844"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_12548"}

{:event/type "card"
:event/elapsed 88
:event/card_type "y"
:event/player1 "Lazaros Christodoulopoulos"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_3958845"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Alessandro Agostini"
:event/subtype "trip"
:event/player1 "Jasmin Kurtic"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3958853"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_12548"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Khouma Babacar"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_3958883"
:event/minute 91
:event/match_id "match_12548"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Vangelis Moras"
:event/subtype "pushing"
:event/player1 "Khouma Babacar"
:event/sortorder 5
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3958903"
:event/minute 93
:event/match_id "match_12548"}


]

