
;;# data
[
{:match/id "match_3562"
:match/league "England Premier League"
:match/hometeam "Newcastle United"
:match/awayteam "Arsenal"
:match/score "0:1"
:match/hometeam_goals "0"
:match/awayteam_goals "1"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Santi Cazorla"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2779263"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_3562"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "Santi Cazorla"
:event/subtype "dangerous_play"
:event/player1 "Papiss Cisse"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2779266"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_3562"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Laurent Koscielny"
:event/subtype "pushing"
:event/player1 "Papiss Cisse"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2779275"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_3562"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Tomas Rosicky"
:event/subtype "serious_foul"
:event/player1 "Cheik Tiote"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2779298"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Santi Cazorla"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2779310"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_3562"}

{:event/type "shotoff"
:event/elapsed 6
:event/subtype "volley"
:event/player1 "Theo Walcott"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2779317"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_3562"}

{:event/type "shotoff"
:event/elapsed 7
:event/subtype "big chance shot"
:event/player1 "Papiss Cisse"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2779352"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Mathieu Debuchy"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_2779367"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Bacary Sagna"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2779389"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3562"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Theo Walcott"
:event/subtype "trip"
:event/player1 "Mapou Yanga-Mbiwa"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2779407"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Kieran Gibbs"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2779410"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Santi Cazorla"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2779426"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_3562"}

{:event/type "corner"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Santi Cazorla"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2779426"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_3562"}

{:event/type "shotoff"
:event/elapsed 12
:event/subtype "big chance header"
:event/player1 "Laurent Koscielny"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2779429"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_3562"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Laurent Koscielny"
:event/subtype "pushing"
:event/player1 "Papiss Cisse"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2779457"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_3562"}

{:event/type "shotoff"
:event/elapsed 14
:event/subtype "shot"
:event/player1 "Yoan Gouffran"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2779465"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Hatem Ben Arfa"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2779484"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Kieran Gibbs"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2779525"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_3562"}

{:event/type "shoton"
:event/elapsed 17
:event/subtype "deflected"
:event/player1 "Jonas Gutierrez"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_2779537"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_3562"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Jonas Gutierrez"
:event/subtype "dangerous_play"
:event/player1 "Bacary Sagna"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2779549"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2779571"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_3562"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Kieran Gibbs"
:event/subtype "pushing"
:event/player1 "Yoan Gouffran"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2779576"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Mathieu Debuchy"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2779603"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2779633"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_3562"}

{:event/type "corner"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2779633"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_3562"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Theo Walcott"
:event/subtype "pull"
:event/player1 "Jonas Gutierrez"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2779637"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_3562"}

{:event/type "card"
:event/elapsed 22
:event/card_type "y"
:event/subtype "shirt_pull"
:event/player1 "Jonas Gutierrez"
:event/sortorder 4
:event/team "home"
:event/event_type "card"
:event/id "event_2779638"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Theo Walcott"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2779656"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Tomas Rosicky"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_2779670"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_3562"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Lukas Podolski"
:event/subtype "trip"
:event/player1 "Hatem Ben Arfa"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2779675"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Theo Walcott"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2779684"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3562"}

{:event/type "shotoff"
:event/elapsed 25
:event/subtype "header"
:event/player1 "Per Mertesacker"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2779692"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Mapou Yanga-Mbiwa"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2779706"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Papiss Cisse"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2779722"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2779729"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_3562"}

{:event/type "corner"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2779729"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_2779760"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_3562"}

{:event/type "shotoff"
:event/elapsed 30
:event/subtype "shot"
:event/player1 "Alex Oxlade-Chamberlain"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2779793"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_3562"}

{:event/type "shotoff"
:event/elapsed 31
:event/subtype "shot"
:event/player1 "Santi Cazorla"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2779812"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_3562"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Mathieu Debuchy"
:event/subtype "pull"
:event/player1 "Lukas Podolski"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2779842"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Mathieu Debuchy"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2779850"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2779887"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2779911"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_3562"}

{:event/type "corner"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2779911"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_3562"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Lukas Podolski"
:event/subtype "trip"
:event/player1 "Yohan Cabaye"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2779932"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_3562"}

{:event/type "shoton"
:event/elapsed 38
:event/subtype "distance"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_2779980"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_3562"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Mathieu Debuchy"
:event/subtype "trip"
:event/player1 "Aaron Ramsey"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2779997"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_3562"}

{:event/type "card"
:event/elapsed 39
:event/card_type "y"
:event/subtype "advantage"
:event/player1 "Tomas Rosicky"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2780004"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Bacary Sagna"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2780019"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_3562"}

{:event/type "shotoff"
:event/elapsed 40
:event/subtype "shot"
:event/player1 "Hatem Ben Arfa"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2780031"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Bacary Sagna"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2780071"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Theo Walcott"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2780084"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Santi Cazorla"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_2780103"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_3562"}

{:event/type "corner"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Santi Cazorla"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_2780103"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Alex Oxlade-Chamberlain"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2780122"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_3562"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Aaron Ramsey"
:event/subtype "dangerous_play"
:event/player1 "Cheik Tiote"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2780173"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Theo Walcott"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2780199"
:event/minute 46
:event/match_id "match_3562"}

{:event/type "shoton"
:event/elapsed 46
:event/subtype "big chance shot"
:event/player1 "Theo Walcott"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_2780285"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_3562"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 45
:event/player2 "Aaron Ramsey"
:event/subtype "pushing"
:event/player1 "Papiss Cisse"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2780213"
:event/minute 47
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Tomas Rosicky"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2780372"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2780389"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Tomas Rosicky"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_2780398"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Aaron Ramsey"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2780411"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3562"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Bacary Sagna"
:event/subtype "trip"
:event/player1 "Yohan Cabaye"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2780429"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Theo Walcott"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2780443"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Lukas Podolski"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2780444"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_3562"}

{:event/type "goal"
:event/elapsed 52
:event/player2 "Lukas Podolski"
:event/subtype "bicycle_kick"
:event/player1 "Laurent Koscielny"
:event/sortorder 2
:event/team "away"
:event/id "event_2780446"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Theo Walcott"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2780555"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_3562"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Mapou Yanga-Mbiwa"
:event/subtype "trip"
:event/player1 "Bacary Sagna"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2780578"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_3562"}

{:event/type "shoton"
:event/elapsed 58
:event/subtype "blocked_shot"
:event/player1 "Papiss Cisse"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_2780611"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Mathieu Debuchy"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2780685"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Yoan Gouffran"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_2780724"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Santi Cazorla"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2780752"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3562"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Hatem Ben Arfa"
:event/subtype "trip"
:event/player1 "Santi Cazorla"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2780790"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Mathieu Debuchy"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2780795"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_3562"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Laurent Koscielny"
:event/subtype "trip"
:event/player1 "Yoan Gouffran"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2780799"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_3562"}

{:event/type "foulcommit"
:event/elapsed 65
:event/subtype "hands"
:event/player1 "Lukas Podolski"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2780822"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Tomas Rosicky"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_2780873"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3562"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Santi Cazorla"
:event/subtype "trip"
:event/player1 "Mapou Yanga-Mbiwa"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2780902"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_3562"}

{:event/type "shoton"
:event/elapsed 69
:event/subtype "blocked_shot"
:event/player1 "Lukas Podolski"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_2780936"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Lukas Podolski"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2780939"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_3562"}

{:event/type "shotoff"
:event/elapsed 69
:event/subtype "shot"
:event/player1 "Alex Oxlade-Chamberlain"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2780942"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_3562"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Vurnon Anita"
:event/subtype "pushing"
:event/player1 "Aaron Ramsey"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2780967"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_3562"}

{:event/type "foulcommit"
:event/elapsed 70
:event/subtype "hands"
:event/player1 "Vurnon Anita"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2780973"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_3562"}

{:event/type "shotoff"
:event/elapsed 72
:event/subtype "shot"
:event/player1 "Hatem Ben Arfa"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2781004"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Aaron Ramsey"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2781036"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Vurnon Anita"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2781095"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Aaron Ramsey"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2781099"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Mathieu Debuchy"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2781128"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Mapou Yanga-Mbiwa"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2781156"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_3562"}

{:event/type "corner"
:event/elapsed 79
:event/subtype "short"
:event/player1 "Hatem Ben Arfa"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_2781174"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Vurnon Anita"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_2781175"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_3562"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Mathieu Debuchy"
:event/subtype "pull"
:event/player1 "Kieran Gibbs"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2781223"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_3562"}

{:event/type "card"
:event/elapsed 81
:event/card_type "y"
:event/subtype "verbal_abuse"
:event/player1 "Kieran Gibbs"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_2781226"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Vurnon Anita"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2781243"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Alex Oxlade-Chamberlain"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_2781250"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Theo Walcott"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2781267"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_3562"}

{:event/type "corner"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Theo Walcott"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2781267"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_3562"}

{:event/type "shotoff"
:event/elapsed 83
:event/subtype "shot"
:event/player1 "Santi Cazorla"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2781276"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_3562"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Theo Walcott"
:event/subtype "trip"
:event/player1 "Jonas Gutierrez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2781296"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Cheik Tiote"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2781328"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Theo Walcott"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_2781341"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Vurnon Anita"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2781384"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Santi Cazorla"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2781415"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_3562"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Olivier Giroud"
:event/subtype "trip"
:event/player1 "Mathieu Debuchy"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2781452"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3562"}

{:event/type "shotoff"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "post"
:event/player1 "Theo Walcott"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2781502"
:event/minute 92
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Steve Harper"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_2781516"
:event/minute 92
:event/match_id "match_3562"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Steven Taylor"
:event/subtype "trip"
:event/player1 "Jack Wilshere"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2781531"
:event/minute 93
:event/match_id "match_3562"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Jack Wilshere"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2781544"
:event/minute 94
:event/match_id "match_3562"}

{:event/type "shoton"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Olivier Giroud"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_2781546"
:event/minute 94
:event/match_id "match_3562"}

{:event/type "corner"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "short"
:event/player1 "Aaron Ramsey"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2781550"
:event/minute 95
:event/match_id "match_3562"}


]

