
;;# data
[
{:match/id "match_6576"
:match/league "France Ligue 1"
:match/hometeam "FC Sochaux-Montbéliard"
:match/awayteam "FC Lorient"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 24
:event/card_type "y"
:event/player1 "Joseph Romeric Lopy"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2747654"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_6576"}

{:event/type "goal"
:event/elapsed 30
:event/player1 "Sloan Privat"
:event/sortorder 0
:event/team "home"
:event/id "event_2747665"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_6576"}

{:event/type "card"
:event/elapsed 83
:event/card_type "y"
:event/player1 "Maxime Baca"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2747869"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_6576"}


]

