
;;# data
[
{:match/id "match_10152"
:match/league "Germany 1. Bundesliga"
:match/hometeam "VfB Stuttgart"
:match/awayteam "Eintracht Frankfurt"
:match/score "2:3"
:match/hometeam_goals "1"
:match/awayteam_goals "4"}

{:event/type "foulcommit"
:event/elapsed 1
:event/player2 "Carlos Zambrano"
:event/player1 "Christian Gentner"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4717721"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_10152"}

{:event/type "shoton"
:event/elapsed 2
:event/subtype "shot"
:event/player1 "Marc Stendera"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4717686"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Marco Russ"
:event/player1 "Daniel Ginczek"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4717727"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Marc Stendera"
:event/subtype "dangerous_play"
:event/player1 "Daniel Schwaab"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4717731"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_10152"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Serey Die"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4717754"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Filip Kostic"
:event/player1 "Timothy Chandler"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4717830"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 8
:event/player2 "Filip Kostic"
:event/subtype "pushing"
:event/player1 "Timothy Chandler"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4717761"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_10152"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Emiliano Insua"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4717764"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_10152"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Emiliano Insua"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4717770"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_10152"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Martin Harnik"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4717778"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Emiliano Insua"
:event/subtype "pushing"
:event/player1 "Luc Castaignos"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4717789"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_10152"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Marc Stendera"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4717814"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_10152"}

{:event/type "goal"
:event/elapsed 11
:event/player1 "Adam Hlousek"
:event/sortorder 1
:event/team "home"
:event/id "event_4717803"
:event/event_type "goal"
:event/goal_type "o"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_10152"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Luc Castaignos"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4717886"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_10152"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Filip Kostic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4717852"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Makoto Hasebe"
:event/subtype "from_behind"
:event/player1 "Martin Harnik"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4717873"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_10152"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Bastian Oczipka"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4717892"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_10152"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Marc Stendera"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4717897"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Makoto Hasebe"
:event/subtype "trip"
:event/player1 "Daniel Ginczek"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4717906"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Filip Kostic"
:event/subtype "pull"
:event/player1 "Timothy Chandler"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4717914"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_10152"}

{:event/type "card"
:event/elapsed 21
:event/card_type "y"
:event/player1 "Timothy Chandler"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_4717925"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_10152"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Daniel Didavi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4717932"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_10152"}

{:event/type "corner"
:event/elapsed 23
:event/subtype "cross_left"
:event/player1 "Daniel Didavi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4717942"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_10152"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Filip Kostic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4717970"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_10152"}

{:event/type "shotoff"
:event/elapsed 25
:event/subtype "miss_kick"
:event/player1 "Christian Gentner"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4717975"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_10152"}

{:event/type "shotoff"
:event/elapsed 26
:event/subtype "shot"
:event/player1 "Martin Harnik"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4717978"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Daniel Didavi"
:event/subtype "trip"
:event/player1 "Marc Stendera"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4717985"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_10152"}

{:event/type "card"
:event/elapsed 26
:event/card_type "y"
:event/player1 "Marc Stendera"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_4717987"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_10152"}

{:event/type "shoton"
:event/elapsed 27
:event/subtype "shot"
:event/player1 "Daniel Ginczek"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4717996"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Marc Stendera"
:event/player1 "Daniel Schwaab"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4718019"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Stefan Aigner"
:event/subtype "trip"
:event/player1 "Emiliano Insua"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4718028"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Adam Hlousek"
:event/player1 "Haris Seferovic"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4718355"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_10152"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Martin Harnik"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4718056"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_10152"}

{:event/type "shotoff"
:event/elapsed 29
:event/subtype "deflected"
:event/player1 "Daniel Didavi"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4718064"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_10152"}

{:event/type "corner"
:event/elapsed 30
:event/subtype "cross_left"
:event/player1 "Filip Kostic"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4718077"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_10152"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Serey Die"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4718107"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_10152"}

{:event/type "goal"
:event/elapsed 30
:event/player2 "Serey Die"
:event/subtype "shot"
:event/player1 "Daniel Didavi"
:event/sortorder 3
:event/team "home"
:event/id "event_4718087"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Daniel Ginczek"
:event/player1 "Carlos Zambrano"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4718138"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_10152"}

{:event/type "shotoff"
:event/elapsed 32
:event/subtype "direct_freekick"
:event/player1 "Daniel Didavi"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4718143"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Carlos Zambrano"
:event/player1 "Daniel Ginczek"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4718231"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_10152"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Filip Kostic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4718208"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_10152"}

{:event/type "shotoff"
:event/elapsed 34
:event/subtype "big chance shot"
:event/player1 "Martin Harnik"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4718213"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Serey Die"
:event/player1 "Timothy Chandler"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4718277"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Haris Seferovic"
:event/player1 "Adam Hlousek"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4718290"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_10152"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Daniel Didavi"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4718314"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_10152"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Haris Seferovic"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4718424"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_10152"}

{:event/type "goal"
:event/elapsed 42
:event/player2 "Haris Seferovic"
:event/subtype "shot"
:event/player1 "Luc Castaignos"
:event/sortorder 2
:event/team "away"
:event/id "event_4718400"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_10152"}

{:event/type "shotoff"
:event/elapsed 43
:event/subtype "deflected"
:event/player1 "Daniel Ginczek"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4718536"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_10152"}

{:event/type "corner"
:event/elapsed 43
:event/subtype "cross_right"
:event/player1 "Daniel Didavi"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4718445"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_10152"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Emiliano Insua"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_4718450"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Timothy Chandler"
:event/subtype "trip"
:event/player1 "Daniel Didavi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4718494"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_10152"}

{:event/type "shotoff"
:event/elapsed 47
:event/subtype "shot"
:event/player1 "Haris Seferovic"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4718949"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 45
:event/player2 "Adam Hlousek"
:event/player1 "Luc Castaignos"
:event/sortorder 7
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4718616"
:event/minute 47
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 45
:event/player2 "Stefan Aigner"
:event/player1 "Filip Kostic"
:event/sortorder 8
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4718545"
:event/minute 47
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Bastian Oczipka"
:event/subtype "dangerous_play"
:event/player1 "Daniel Didavi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4718936"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_10152"}

{:event/type "card"
:event/elapsed 48
:event/card_type "y"
:event/player1 "Daniel Didavi"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4718939"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_10152"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Luc Castaignos"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4718963"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_10152"}

{:event/type "corner"
:event/elapsed 49
:event/subtype "cross_left"
:event/player1 "Marc Stendera"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_4718965"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Serey Die"
:event/subtype "pull"
:event/player1 "David Abraham"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4718986"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_10152"}

{:event/type "card"
:event/elapsed 50
:event/card_type "y"
:event/player1 "David Abraham"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_4718992"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_10152"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Daniel Didavi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4719007"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_10152"}

{:event/type "shoton"
:event/elapsed 51
:event/subtype "distance"
:event/player1 "Timo Werner"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4719018"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Stefan Reinartz"
:event/player1 "Serey Die"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4719029"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_10152"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Daniel Didavi"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4719050"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_10152"}

{:event/type "shoton"
:event/elapsed 53
:event/subtype "shot"
:event/player1 "Filip Kostic"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4719058"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Christian Gentner"
:event/subtype "from_behind"
:event/player1 "Marc Stendera"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4719091"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Aleksandar Ignjovski"
:event/subtype "dangerous_play"
:event/player1 "Emiliano Insua"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4719125"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_10152"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Makoto Hasebe"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4719134"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_10152"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Filip Kostic"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4719139"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_10152"}

{:event/type "shoton"
:event/elapsed 56
:event/subtype "shot"
:event/player1 "Timo Werner"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4719146"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_10152"}

{:event/type "corner"
:event/elapsed 56
:event/subtype "cross_left"
:event/player1 "Daniel Didavi"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4719155"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Daniel Ginczek"
:event/player1 "Carlos Zambrano"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4719296"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_10152"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Filip Kostic"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4719201"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_10152"}

{:event/type "shotoff"
:event/elapsed 59
:event/subtype "deflected"
:event/player1 "Daniel Ginczek"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4719223"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_10152"}

{:event/type "corner"
:event/elapsed 59
:event/subtype "cross_left"
:event/player1 "Daniel Didavi"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4719229"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_10152"}

{:event/type "corner"
:event/elapsed 59
:event/subtype "cross_right"
:event/player1 "Daniel Didavi"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_4719233"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 59
:event/player2 "Daniel Didavi"
:event/player1 "Luc Castaignos"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4719241"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player2 "Daniel Didavi"
:event/player1 "Bastian Oczipka"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4719251"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_10152"}

{:event/type "shoton"
:event/elapsed 60
:event/subtype "direct_freekick"
:event/player1 "Daniel Didavi"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4719254"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Timo Baumgartl"
:event/player1 "Luc Castaignos"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4719272"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_10152"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Filip Kostic"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4719283"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Daniel Didavi"
:event/subtype "pushing"
:event/player1 "Marc Stendera"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4719303"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_10152"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Daniel Didavi"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4719305"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_10152"}

{:event/type "shotoff"
:event/elapsed 65
:event/subtype "header"
:event/player1 "Timo Baumgartl"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4719310"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_10152"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Bastian Oczipka"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4719318"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_10152"}

{:event/type "shotoff"
:event/elapsed 65
:event/subtype "volley"
:event/player1 "Haris Seferovic"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4719323"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Luc Castaignos"
:event/subtype "penalty"
:event/player1 "Przemyslaw Tyton"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4719342"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_10152"}

{:event/type "card"
:event/elapsed 67
:event/card_type "r"
:event/player1 "Przemyslaw Tyton"
:event/sortorder 3
:event/team "home"
:event/event_type "card"
:event/id "event_4719345"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_10152"}

{:event/type "goal"
:event/elapsed 69
:event/player1 "Haris Seferovic"
:event/sortorder 0
:event/team "away"
:event/id "event_4719362"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_10152"}

{:event/type "shotoff"
:event/elapsed 71
:event/subtype "distance"
:event/player1 "Christian Gentner"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4719391"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "David Abraham"
:event/player1 "Daniel Ginczek"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4719475"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Luc Castaignos"
:event/subtype "trip"
:event/player1 "Daniel Schwaab"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4719427"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_10152"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Marc Stendera"
:event/sortorder 5
:event/team "away"
:event/event_type "cross"
:event/id "event_4719445"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "David Abraham"
:event/player1 "Emiliano Insua"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4719481"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_10152"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Haris Seferovic"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4719548"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 78
:event/player2 "Daniel Schwaab"
:event/subtype "trip"
:event/player1 "Bastian Oczipka"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4719766"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_10152"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Filip Kostic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4719657"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Stefan Aigner"
:event/player1 "Adam Hlousek"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4719837"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_10152"}

{:event/type "card"
:event/elapsed 86
:event/card_type "y"
:event/player1 "Adam Hlousek"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4719861"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_10152"}

{:event/type "goal"
:event/elapsed 87
:event/player2 "Stefan Reinartz"
:event/subtype "shot"
:event/player1 "Luc Castaignos"
:event/sortorder 1
:event/team "away"
:event/id "event_4719880"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_10152"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Makoto Hasebe"
:event/subtype "serious_foul"
:event/player1 "Daniel Ginczek"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4719964"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_10152"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Daniel Ginczek"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4719970"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_10152"}


]

