
;;# data
[
{:match/id "match_3781"
:match/league "England Premier League"
:match/hometeam "Liverpool"
:match/awayteam "Everton"
:match/score "5:0"
:match/hometeam_goals "4"
:match/awayteam_goals "0"}

{:event/type "shotoff"
:event/elapsed 2
:event/subtype "distance"
:event/player1 "Ross Barkley"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3230896"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_3781"}

{:event/type "shoton"
:event/elapsed 3
:event/subtype "distance"
:event/player1 "Jordan Henderson"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3230920"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_3781"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "James McCarthy"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3230945"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_3781"}

{:event/type "shoton"
:event/elapsed 8
:event/subtype "shot"
:event/player1 "Luis Suarez"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_3230987"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_3781"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_3230992"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_3781"}

{:event/type "corner"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_3230992"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_3781"}

{:event/type "shotoff"
:event/elapsed 8
:event/subtype "bad shot"
:event/player1 "Jordan Henderson"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3230995"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_3781"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Philippe Coutinho"
:event/subtype "pushing"
:event/player1 "Steven Pienaar"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3231022"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_3781"}

{:event/type "shoton"
:event/elapsed 11
:event/subtype "distance"
:event/player1 "Daniel Sturridge"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3231032"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_3781"}

{:event/type "shoton"
:event/elapsed 15
:event/subtype "distance"
:event/player1 "Luis Suarez"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3231068"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_3781"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "John Stones"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3231072"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_3781"}

{:event/type "shoton"
:event/elapsed 16
:event/subtype "blocked_shot"
:event/player1 "Steven Pienaar"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_3231077"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_3781"}

{:event/type "shotoff"
:event/elapsed 17
:event/subtype "distance"
:event/player1 "Steven Gerrard"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3231092"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_3781"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Daniel Sturridge"
:event/subtype "dangerous_play"
:event/player1 "Gareth Barry"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3231104"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3781"}

{:event/type "shoton"
:event/elapsed 18
:event/subtype "big chance shot"
:event/player1 "Raheem Sterling"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_3231108"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3781"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Philippe Coutinho"
:event/subtype "trip"
:event/player1 "Gareth Barry"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3231122"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_3781"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Jon Flanagan"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3231135"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_3781"}

{:event/type "shoton"
:event/elapsed 21
:event/subtype "blocked_shot"
:event/player1 "Luis Suarez"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_3231145"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_3781"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Luis Suarez"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_3231146"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_3781"}

{:event/type "corner"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Luis Suarez"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_3231146"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_3781"}

{:event/type "goal"
:event/elapsed 21
:event/player2 "Luis Suarez"
:event/subtype "header"
:event/player1 "Steven Gerrard"
:event/sortorder 5
:event/team "home"
:event/id "event_3231148"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_3781"}

{:event/type "shoton"
:event/elapsed 26
:event/subtype "blocked_shot"
:event/player1 "Ross Barkley"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3231220"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_3781"}

{:event/type "shotoff"
:event/elapsed 27
:event/subtype "shot"
:event/player1 "Daniel Sturridge"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3231225"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_3781"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Leighton Baines"
:event/subtype "trip"
:event/player1 "Jon Flanagan"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3231238"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_3781"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Daniel Sturridge"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3231258"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_3781"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Kevin Mirallas"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_3231288"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_3781"}

{:event/type "corner"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Kevin Mirallas"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_3231288"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_3781"}

{:event/type "shoton"
:event/elapsed 31
:event/subtype "shot"
:event/player1 "Phil Jagielka"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_3231301"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_3781"}

{:event/type "shotoff"
:event/elapsed 31
:event/subtype "shot"
:event/player1 "Gareth Barry"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3231303"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_3781"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "John Stones"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3231311"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_3781"}

{:event/type "shotoff"
:event/elapsed 32
:event/subtype "distance"
:event/player1 "Kevin Mirallas"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3231319"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_3781"}

{:event/type "goal"
:event/elapsed 33
:event/player2 "Philippe Coutinho"
:event/subtype "shot"
:event/player1 "Daniel Sturridge"
:event/sortorder 1
:event/team "home"
:event/id "event_3231325"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3781"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3231334"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_3781"}

{:event/type "foulcommit"
:event/elapsed 34
:event/player2 "Luis Suarez"
:event/subtype "trip"
:event/player1 "James McCarthy"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3231338"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_3781"}

{:event/type "goal"
:event/elapsed 35
:event/player2 "Kolo Toure"
:event/subtype "shot"
:event/player1 "Daniel Sturridge"
:event/sortorder 2
:event/team "home"
:event/id "event_3231340"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_3781"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Steven Naismith"
:event/subtype "from_behind"
:event/player1 "Martin Skrtel"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3231351"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_3781"}

{:event/type "card"
:event/elapsed 38
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Steven Pienaar"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3231352"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_3781"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3231354"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_3781"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Luis Suarez"
:event/subtype "obstruction"
:event/player1 "Gareth Barry"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3231357"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_3781"}

{:event/type "shoton"
:event/elapsed 40
:event/subtype "shot"
:event/player1 "Kevin Mirallas"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3231366"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_3781"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Kevin Mirallas"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_3231368"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_3781"}

{:event/type "corner"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Kevin Mirallas"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_3231368"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_3781"}

{:event/type "shotoff"
:event/elapsed 41
:event/subtype "deflected"
:event/player1 "Gareth Barry"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3231371"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3781"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3231374"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3781"}

{:event/type "corner"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3231374"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3781"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "James McCarthy"
:event/subtype "pull"
:event/player1 "Raheem Sterling"
:event/sortorder 5
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3231379"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3781"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Kevin Mirallas"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3231383"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_3781"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Kevin Mirallas"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_3231386"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_3781"}

{:event/type "corner"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Kevin Mirallas"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_3231386"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_3781"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Jon Flanagan"
:event/subtype "trip"
:event/player1 "Steven Pienaar"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3231388"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_3781"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Antolin Alcaraz"
:event/subtype "pushing"
:event/player1 "Luis Suarez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3231392"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_3781"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3231393"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_3781"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Raheem Sterling"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3231397"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_3781"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "blocked_shot"
:event/player1 "Kevin Mirallas"
:event/sortorder 4
:event/team "away"
:event/event_type "shoton"
:event/id "event_3231404"
:event/minute 46
:event/match_id "match_3781"}

{:event/type "shoton"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "blocked_shot"
:event/player1 "Ross Barkley"
:event/sortorder 7
:event/team "away"
:event/event_type "shoton"
:event/id "event_3231412"
:event/minute 47
:event/match_id "match_3781"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3231594"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_3781"}

{:event/type "shoton"
:event/elapsed 48
:event/subtype "blocked_shot"
:event/player1 "Ross Barkley"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_3231601"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_3781"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Leon Osman"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_3231603"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_3781"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 45
:event/player2 "Raheem Sterling"
:event/subtype "pull"
:event/player1 "Gareth Barry"
:event/sortorder 8
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3231414"
:event/minute 48
:event/match_id "match_3781"}

{:event/type "card"
:event/elapsed_plus 3
:event/elapsed 45
:event/card_type "y"
:event/player1 "Gareth Barry"
:event/sortorder 9
:event/team "away"
:event/event_type "card"
:event/id "event_3231416"
:event/minute 48
:event/match_id "match_3781"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3231606"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_3781"}

{:event/type "corner"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3231606"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_3781"}

{:event/type "shoton"
:event/elapsed 50
:event/subtype "shot"
:event/player1 "Leon Osman"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3231621"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_3781"}

{:event/type "goal"
:event/elapsed 50
:event/subtype "shot"
:event/player1 "Luis Suarez"
:event/sortorder 6
:event/team "home"
:event/id "event_3231626"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_3781"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Kolo Toure"
:event/subtype "pushing"
:event/player1 "Kevin Mirallas"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3231646"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3781"}

{:event/type "card"
:event/elapsed 52
:event/card_type "y"
:event/player1 "Kevin Mirallas"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3231647"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_3781"}

{:event/type "shoton"
:event/elapsed 54
:event/subtype "blocked_shot"
:event/player1 "Kevin Mirallas"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3231668"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_3781"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Raheem Sterling"
:event/subtype "penalty"
:event/player1 "Tim Howard"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3231673"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_3781"}

{:event/type "goal"
:event/elapsed 55
:event/subtype "missed"
:event/player1 "Daniel Sturridge"
:event/sortorder 0
:event/team "home"
:event/id "event_3231680"
:event/event_type "goal"
:event/goal_type "npm"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3781"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Leon Osman"
:event/subtype "trip"
:event/player1 "Steven Gerrard"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3231685"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3781"}

{:event/type "shoton"
:event/elapsed 56
:event/subtype "blocked_shot"
:event/player1 "Ross Barkley"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3231695"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_3781"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Jon Flanagan"
:event/subtype "pushing"
:event/player1 "Leon Osman"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3231698"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_3781"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "John Stones"
:event/subtype "trip"
:event/player1 "Luis Suarez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3231718"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_3781"}

{:event/type "foulcommit"
:event/elapsed 59
:event/player2 "Daniel Sturridge"
:event/subtype "obstruction"
:event/player1 "Antolin Alcaraz"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3231743"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_3781"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3231751"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_3781"}

{:event/type "corner"
:event/elapsed 60
:event/subtype "short"
:event/player1 "Steven Gerrard"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3231757"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_3781"}

{:event/type "shoton"
:event/elapsed 60
:event/subtype "shot"
:event/player1 "Philippe Coutinho"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_3231758"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_3781"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Luis Suarez"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_3231759"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_3781"}

{:event/type "corner"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Luis Suarez"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_3231759"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_3781"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Leon Osman"
:event/subtype "trip"
:event/player1 "Jon Flanagan"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3231782"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_3781"}

{:event/type "shoton"
:event/elapsed 62
:event/subtype "blocked_shot"
:event/player1 "Kevin Mirallas"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3231789"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_3781"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Gareth Barry"
:event/subtype "pull"
:event/player1 "Raheem Sterling"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3231806"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_3781"}

{:event/type "foulcommit"
:event/elapsed 66
:event/player2 "Kevin Mirallas"
:event/subtype "obstruction"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3231831"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_3781"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Leon Osman"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3231842"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3781"}

{:event/type "shoton"
:event/elapsed 67
:event/subtype "shot"
:event/player1 "Ross Barkley"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_3231849"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3781"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Kevin Mirallas"
:event/sortorder 5
:event/team "away"
:event/event_type "corner"
:event/id "event_3231854"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3781"}

{:event/type "corner"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Kevin Mirallas"
:event/sortorder 5
:event/team "away"
:event/event_type "corner"
:event/id "event_3231854"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3781"}

{:event/type "shotoff"
:event/elapsed 67
:event/subtype "header"
:event/player1 "Antolin Alcaraz"
:event/sortorder 6
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3231855"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3781"}

{:event/type "shoton"
:event/elapsed 70
:event/subtype "distance"
:event/player1 "James McCarthy"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3231886"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_3781"}

{:event/type "corner"
:event/elapsed 70
:event/subtype "short"
:event/player1 "Kevin Mirallas"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3231890"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_3781"}

{:event/type "shotoff"
:event/elapsed 71
:event/subtype "bad shot"
:event/player1 "Daniel Sturridge"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3231900"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3781"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Philippe Coutinho"
:event/subtype "trip"
:event/player1 "Leon Osman"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3231924"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3781"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Philippe Coutinho"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3231950"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_3781"}

{:event/type "shotoff"
:event/elapsed 74
:event/subtype "volley"
:event/player1 "Victor Moses"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3231953"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_3781"}

{:event/type "shoton"
:event/elapsed 77
:event/subtype "blocked_shot"
:event/player1 "Philippe Coutinho"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3231983"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_3781"}

{:event/type "shotoff"
:event/elapsed 77
:event/subtype "big chance shot"
:event/player1 "Aiden McGeady"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3231997"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_3781"}

{:event/type "shoton"
:event/elapsed 78
:event/subtype "distance"
:event/player1 "Leon Osman"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3232005"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_3781"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Leighton Baines"
:event/subtype "pushing"
:event/player1 "Luis Suarez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3232021"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_3781"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Leon Osman"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3232030"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_3781"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Leon Osman"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_3232037"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_3781"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "John Stones"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3232039"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_3781"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Kevin Mirallas"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_3232041"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_3781"}

{:event/type "corner"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Kevin Mirallas"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_3232041"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_3781"}

{:event/type "shoton"
:event/elapsed 83
:event/subtype "header"
:event/player1 "Phil Jagielka"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_3232042"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_3781"}

{:event/type "shotoff"
:event/elapsed 86
:event/subtype "shot"
:event/player1 "Victor Moses"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3232053"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3781"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "James McCarthy"
:event/subtype "pull"
:event/player1 "Luis Alberto"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3232068"
:event/minute 92
:event/match_id "match_3781"}

{:event/type "shotoff"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "deflected"
:event/player1 "Jordan Henderson"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3232072"
:event/minute 92
:event/match_id "match_3781"}

{:event/type "corner"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "short"
:event/player1 "Steven Gerrard"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_3232073"
:event/minute 93
:event/match_id "match_3781"}


]

