
;;# data
[
{:match/id "match_4719"
:match/league "England Premier League"
:match/hometeam "Arsenal"
:match/awayteam "Stoke City"
:match/score "2:0"
:match/hometeam_goals "2"
:match/awayteam_goals "0"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "Alexis Sanchez"
:event/subtype "trip"
:event/player1 "Phil Bardsley"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4757594"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_4719"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Santi Cazorla"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4757606"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_4719"}

{:event/type "shotoff"
:event/elapsed 4
:event/subtype "post"
:event/player1 "Alexis Sanchez"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4757626"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_4719"}

{:event/type "shotoff"
:event/elapsed 4
:event/subtype "shot"
:event/player1 "Theo Walcott"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4757631"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_4719"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Aaron Ramsey"
:event/subtype "dangerous_play"
:event/player1 "Marco van Ginkel"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4757667"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_4719"}

{:event/type "shoton"
:event/elapsed 6
:event/subtype "direct_freekick"
:event/player1 "Alexis Sanchez"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4757689"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_4719"}

{:event/type "corner"
:event/elapsed 6
:event/subtype "cross_left"
:event/player1 "Santi Cazorla"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4757693"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_4719"}

{:event/type "shoton"
:event/elapsed 7
:event/subtype "shot"
:event/player1 "Aaron Ramsey"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4757728"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_4719"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Alexis Sanchez"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4757753"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_4719"}

{:event/type "shotoff"
:event/elapsed 8
:event/subtype "post"
:event/player1 "Alexis Sanchez"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4757764"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_4719"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Hector Bellerin"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4757775"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_4719"}

{:event/type "shotoff"
:event/elapsed 9
:event/subtype "header"
:event/player1 "Theo Walcott"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4757782"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_4719"}

{:event/type "shoton"
:event/elapsed 11
:event/subtype "blocked_shot"
:event/player1 "Alexis Sanchez"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4757841"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_4719"}

{:event/type "shoton"
:event/elapsed 12
:event/subtype "shot"
:event/player1 "Theo Walcott"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4757878"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_4719"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "Marco van Ginkel"
:event/subtype "trip"
:event/player1 "Santi Cazorla"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4758001"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_4719"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Xherdan Shaqiri"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4758022"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_4719"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Petr Cech"
:event/subtype "pushing"
:event/player1 "Joselu"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4758028"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_4719"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Nacho Monreal"
:event/subtype "trip"
:event/player1 "Mame Biram Diouf"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4758134"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_4719"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Alexis Sanchez"
:event/subtype "trip"
:event/player1 "Marco van Ginkel"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4758139"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_4719"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Hector Bellerin"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4758087"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_4719"}

{:event/type "corner"
:event/elapsed 21
:event/subtype "cross_left"
:event/player1 "Santi Cazorla"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4758095"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_4719"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Glenn Whelan"
:event/player1 "Aaron Ramsey"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4758144"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_4719"}

{:event/type "shoton"
:event/elapsed 24
:event/subtype "distance"
:event/player1 "Laurent Koscielny"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4758174"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_4719"}

{:event/type "corner"
:event/elapsed 24
:event/subtype "cross_left"
:event/player1 "Mesut Oezil"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4758179"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_4719"}

{:event/type "shoton"
:event/elapsed 25
:event/subtype "shot"
:event/player1 "Santi Cazorla"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4758186"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_4719"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Laurent Koscielny"
:event/subtype "trip"
:event/player1 "Mame Biram Diouf"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4758191"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_4719"}

{:event/type "corner"
:event/elapsed 28
:event/subtype "short_left"
:event/player1 "Mesut Oezil"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4758234"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_4719"}

{:event/type "shoton"
:event/elapsed 30
:event/subtype "blocked_shot"
:event/player1 "Francis Coquelin"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4758266"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_4719"}

{:event/type "goal"
:event/elapsed 31
:event/player2 "Mesut Oezil"
:event/subtype "shot"
:event/player1 "Theo Walcott"
:event/sortorder 1
:event/team "home"
:event/id "event_4758284"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_4719"}

{:event/type "corner"
:event/elapsed 32
:event/subtype "cross_right"
:event/player1 "Mesut Oezil"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4758327"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_4719"}

{:event/type "shotoff"
:event/elapsed 33
:event/subtype "header"
:event/player1 "Theo Walcott"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4758334"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_4719"}

{:event/type "shoton"
:event/elapsed 33
:event/subtype "shot"
:event/player1 "Joselu"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_4758345"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_4719"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Aaron Ramsey"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4758367"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_4719"}

{:event/type "corner"
:event/elapsed 37
:event/subtype "cross_right"
:event/player1 "Mesut Oezil"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4758426"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_4719"}

{:event/type "shotoff"
:event/elapsed 37
:event/subtype "volley"
:event/player1 "Francis Coquelin"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4758438"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_4719"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Erik Pieters"
:event/subtype "pull"
:event/player1 "Mesut Oezil"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4758469"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_4719"}

{:event/type "card"
:event/elapsed 38
:event/card_type "y"
:event/player1 "Mesut Oezil"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4758483"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_4719"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Nacho Monreal"
:event/subtype "trip"
:event/player1 "Mame Biram Diouf"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4758546"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_4719"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Erik Pieters"
:event/subtype "obstruction"
:event/player1 "Santi Cazorla"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4758630"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_4719"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Erik Pieters"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4758667"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_4719"}

{:event/type "foulcommit"
:event/elapsed 47
:event/player2 "Alexis Sanchez"
:event/subtype "trip"
:event/player1 "Glenn Whelan"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4758967"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_4719"}

{:event/type "corner"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross_right"
:event/player1 "Santi Cazorla"
:event/sortorder 8
:event/team "home"
:event/event_type "corner"
:event/id "event_4758711"
:event/minute 47
:event/match_id "match_4719"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Nacho Monreal"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4759129"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_4719"}

{:event/type "corner"
:event/elapsed 52
:event/subtype "cross_left"
:event/player1 "Santi Cazorla"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4759145"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_4719"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Aaron Ramsey"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4759197"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_4719"}

{:event/type "corner"
:event/elapsed 54
:event/subtype "short_left"
:event/player1 "Santi Cazorla"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4759204"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_4719"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Hector Bellerin"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4759219"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_4719"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Joselu"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4759230"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_4719"}

{:event/type "shotoff"
:event/elapsed 55
:event/subtype "shot"
:event/player1 "Aaron Ramsey"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4759244"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_4719"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Phil Bardsley"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4759281"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_4719"}

{:event/type "shoton"
:event/elapsed 57
:event/subtype "shot"
:event/player1 "Xherdan Shaqiri"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4759293"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_4719"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Hector Bellerin"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4759340"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_4719"}

{:event/type "shoton"
:event/elapsed 61
:event/subtype "blocked_shot"
:event/player1 "Xherdan Shaqiri"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4759439"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_4719"}

{:event/type "shoton"
:event/elapsed 61
:event/subtype "blocked_shot"
:event/player1 "Xherdan Shaqiri"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4759454"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_4719"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Phil Bardsley"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4759464"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_4719"}

{:event/type "shoton"
:event/elapsed 63
:event/subtype "distance"
:event/player1 "Phil Bardsley"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4759493"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_4719"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Mesut Oezil"
:event/subtype "trip"
:event/player1 "Marco van Ginkel"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4759520"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_4719"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Santi Cazorla"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4759537"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_4719"}

{:event/type "corner"
:event/elapsed 65
:event/subtype "cross_left"
:event/player1 "Mesut Oezil"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4759544"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_4719"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Mesut Oezil"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_4759566"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_4719"}

{:event/type "corner"
:event/elapsed 66
:event/subtype "cross_left"
:event/player1 "Mesut Oezil"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4759573"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_4719"}

{:event/type "foulcommit"
:event/elapsed 66
:event/player2 "Aaron Ramsey"
:event/subtype "pull"
:event/player1 "Erik Pieters"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4759585"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_4719"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Hector Bellerin"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_4759601"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_4719"}

{:event/type "shoton"
:event/elapsed 67
:event/subtype "shot"
:event/player1 "Theo Walcott"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4759609"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_4719"}

{:event/type "corner"
:event/elapsed 68
:event/subtype "short_left"
:event/player1 "Santi Cazorla"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4759642"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_4719"}

{:event/type "shoton"
:event/elapsed 68
:event/subtype "blocked_shot"
:event/player1 "Santi Cazorla"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_4759651"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_4719"}

{:event/type "shotoff"
:event/elapsed 68
:event/subtype "shot"
:event/player1 "Alexis Sanchez"
:event/sortorder 5
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4759660"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_4719"}

{:event/type "shoton"
:event/elapsed 69
:event/subtype "shot"
:event/player1 "Mesut Oezil"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4759667"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_4719"}

{:event/type "shoton"
:event/elapsed 69
:event/subtype "blocked_shot"
:event/player1 "Alexis Sanchez"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_4759681"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_4719"}

{:event/type "shoton"
:event/elapsed 70
:event/subtype "shot"
:event/player1 "Theo Walcott"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4759706"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_4719"}

{:event/type "shoton"
:event/elapsed 73
:event/subtype "blocked_shot"
:event/player1 "Aaron Ramsey"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_4759779"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_4719"}

{:event/type "shoton"
:event/elapsed 73
:event/subtype "deflected"
:event/player1 "Santi Cazorla"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_4759785"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_4719"}

{:event/type "shoton"
:event/elapsed 74
:event/subtype "shot"
:event/player1 "Theo Walcott"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4759800"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_4719"}

{:event/type "shoton"
:event/elapsed 76
:event/subtype "blocked_shot"
:event/player1 "Alexis Sanchez"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4759846"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_4719"}

{:event/type "shotoff"
:event/elapsed 77
:event/subtype "shot"
:event/player1 "Olivier Giroud"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4759858"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_4719"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Phil Bardsley"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4759876"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_4719"}

{:event/type "shotoff"
:event/elapsed 78
:event/subtype "shot"
:event/player1 "Santi Cazorla"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4759898"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_4719"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Alexis Sanchez"
:event/subtype "dangerous_play"
:event/player1 "Phil Bardsley"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4759948"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_4719"}

{:event/type "card"
:event/elapsed 81
:event/card_type "y"
:event/player1 "Phil Bardsley"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4759954"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_4719"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Xherdan Shaqiri"
:event/player1 "Santi Cazorla"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4759962"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_4719"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Bojan Krkic"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4759971"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_4719"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Alex Oxlade-Chamberlain"
:event/subtype "pull"
:event/player1 "Phil Bardsley"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4760029"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_4719"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Santi Cazorla"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4760038"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_4719"}

{:event/type "goal"
:event/elapsed 85
:event/player2 "Santi Cazorla"
:event/subtype "header"
:event/player1 "Olivier Giroud"
:event/sortorder 1
:event/team "home"
:event/id "event_4760043"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_4719"}

{:event/type "shotoff"
:event/elapsed 87
:event/subtype "distance"
:event/player1 "Bojan Krkic"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4760082"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_4719"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Santi Cazorla"
:event/subtype "trip"
:event/player1 "Erik Pieters"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4760106"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_4719"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Santi Cazorla"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4760123"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_4719"}

{:event/type "shoton"
:event/elapsed 88
:event/subtype "header"
:event/player1 "Laurent Koscielny"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4760134"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_4719"}

{:event/type "corner"
:event/elapsed 89
:event/subtype "cross_right"
:event/player1 "Santi Cazorla"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4760143"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_4719"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Olivier Giroud"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4760175"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_4719"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Geoff Cameron"
:event/player1 "Alex Oxlade-Chamberlain"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4760204"
:event/minute 91
:event/match_id "match_4719"}

{:event/type "shotoff"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Olivier Giroud"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4760232"
:event/minute 93
:event/match_id "match_4719"}

{:event/type "corner"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross_left"
:event/player1 "Bojan Krkic"
:event/sortorder 7
:event/team "away"
:event/event_type "corner"
:event/id "event_4760253"
:event/minute 93
:event/match_id "match_4719"}


]

