
;;# data
[
{:match/id "match_3813"
:match/league "England Premier League"
:match/hometeam "West Bromwich Albion"
:match/awayteam "Chelsea"
:match/score "1:1"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Morgan Amalfitano"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3258739"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Branislav Ivanovic"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3258764"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Morgan Amalfitano"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3258781"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_3813"}

{:event/type "foulcommit"
:event/elapsed 8
:event/player2 "Willian"
:event/subtype "trip"
:event/player1 "Morgan Amalfitano"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3258809"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_3813"}

{:event/type "shotoff"
:event/elapsed 9
:event/subtype "bad shot"
:event/player1 "Branislav Ivanovic"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3258822"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3813"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Nemanja Matic"
:event/player1 "Thievy Bifouma"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3258826"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3258831"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_3813"}

{:event/type "corner"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3258831"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_3813"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Thievy Bifouma"
:event/player1 "Nemanja Matic"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3258855"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3258949"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_3813"}

{:event/type "corner"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3258949"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_3813"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "James Morrison"
:event/player1 "Nemanja Matic"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3258959"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_3813"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Eden Hazard"
:event/player1 "Claudio Yacob"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3258980"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3813"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "David Luiz"
:event/subtype "advantage"
:event/player1 "Saido Berahino"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3258983"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Eden Hazard"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3258987"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_3813"}

{:event/type "shotoff"
:event/elapsed 27
:event/subtype "distance"
:event/player1 "Willian"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3258998"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Morgan Amalfitano"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3259006"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_3813"}

{:event/type "shotoff"
:event/elapsed 28
:event/subtype "shot"
:event/player1 "Chris Brunt"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3259012"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Branislav Ivanovic"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3259038"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_3813"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Oscar"
:event/player1 "Steven Reid"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3259059"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_3259072"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3813"}

{:event/type "corner"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_3259072"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Ramires"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3259077"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_3813"}

{:event/type "corner"
:event/elapsed 35
:event/subtype "short"
:event/player1 "Willian"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3259080"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3259082"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_3813"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Ramires"
:event/player1 "Thievy Bifouma"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3259084"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_3813"}

{:event/type "shoton"
:event/elapsed 40
:event/subtype "blocked_shot"
:event/player1 "Ramires"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3259105"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3259107"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_3813"}

{:event/type "corner"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3259107"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_3813"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Eden Hazard"
:event/subtype "from_behind"
:event/player1 "Morgan Amalfitano"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3259112"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3813"}

{:event/type "card"
:event/elapsed 41
:event/card_type "y"
:event/player1 "Morgan Amalfitano"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_3259113"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Eden Hazard"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3259116"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_3813"}

{:event/type "shotoff"
:event/elapsed 42
:event/subtype "distance"
:event/player1 "Willian"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3259117"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Ramires"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3259120"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_3813"}

{:event/type "shotoff"
:event/elapsed 44
:event/subtype "miss_kick"
:event/player1 "Samuel Eto'o"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3259122"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Branislav Ivanovic"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3259127"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Cesar Azpilicueta"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3259130"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_3813"}

{:event/type "shotoff"
:event/elapsed 46
:event/subtype "volley"
:event/player1 "Oscar"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3259300"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 5
:event/team "away"
:event/event_type "corner"
:event/id "event_3259137"
:event/minute 46
:event/match_id "match_3813"}

{:event/type "corner"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 5
:event/team "away"
:event/event_type "corner"
:event/id "event_3259137"
:event/minute 46
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Eden Hazard"
:event/sortorder 8
:event/team "away"
:event/event_type "cross"
:event/id "event_3259141"
:event/minute 46
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Saido Berahino"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3259308"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 11
:event/team "away"
:event/event_type "corner"
:event/id "event_3259157"
:event/minute 48
:event/match_id "match_3813"}

{:event/type "corner"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 11
:event/team "away"
:event/event_type "corner"
:event/id "event_3259157"
:event/minute 48
:event/match_id "match_3813"}

{:event/type "goal"
:event/elapsed_plus 3
:event/elapsed 45
:event/player2 "David Luiz"
:event/subtype "volley"
:event/player1 "Branislav Ivanovic"
:event/sortorder 13
:event/team "away"
:event/id "event_3259160"
:event/event_type "goal"
:event/goal_type "n"
:event/minute 48
:event/match_id "match_3813"}

{:event/type "shoton"
:event/elapsed 50
:event/subtype "shot"
:event/player1 "Samuel Eto'o"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3259329"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_3813"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Craig Dawson"
:event/player1 "Samuel Eto'o"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3259335"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_3813"}

{:event/type "card"
:event/elapsed 50
:event/card_type "y"
:event/player1 "Claudio Yacob"
:event/sortorder 3
:event/team "home"
:event/event_type "card"
:event/id "event_3259339"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_3813"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Ramires"
:event/player1 "James Morrison"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3259346"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3813"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Thievy Bifouma"
:event/player1 "Cesar Azpilicueta"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3259357"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_3813"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Liam Ridgewell"
:event/subtype "dangerous_play"
:event/player1 "Willian"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3259363"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_3813"}

{:event/type "shoton"
:event/elapsed 55
:event/subtype "blocked_shot"
:event/player1 "Willian"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3259374"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Oscar"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3259394"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_3813"}

{:event/type "shoton"
:event/elapsed 58
:event/subtype "distance"
:event/player1 "Willian"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3259408"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3813"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Willian"
:event/subtype "trip"
:event/player1 "Liam Ridgewell"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3259431"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Morgan Amalfitano"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3259476"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "James Morrison"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3259479"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_3813"}

{:event/type "corner"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "James Morrison"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3259479"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_3813"}

{:event/type "shotoff"
:event/elapsed 65
:event/subtype "header"
:event/player1 "Gareth McAuley"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3259480"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_3813"}

{:event/type "foulcommit"
:event/elapsed 66
:event/player2 "Liam Ridgewell"
:event/subtype "pushing"
:event/player1 "Willian"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3259483"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_3813"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Liam Ridgewell"
:event/subtype "pushing"
:event/player1 "Willian"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3259496"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3813"}

{:event/type "card"
:event/elapsed 67
:event/card_type "y"
:event/player1 "Willian"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_3259497"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3813"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Thievy Bifouma"
:event/player1 "Cesar Azpilicueta"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3259506"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_3813"}

{:event/type "shotoff"
:event/elapsed 68
:event/subtype "shot"
:event/player1 "Samuel Eto'o"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3259510"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_3813"}

{:event/type "shotoff"
:event/elapsed 71
:event/subtype "bad shot"
:event/player1 "Thievy Bifouma"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3259539"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3813"}

{:event/type "shoton"
:event/elapsed 71
:event/subtype "shot"
:event/player1 "Willian"
:event/sortorder 5
:event/team "away"
:event/event_type "shoton"
:event/id "event_3259544"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3813"}

{:event/type "shotoff"
:event/elapsed 73
:event/subtype "shot"
:event/player1 "James Morrison"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3259555"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3259703"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3813"}

{:event/type "corner"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3259703"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Saido Berahino"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3259575"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3259581"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3813"}

{:event/type "corner"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3259581"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3813"}

{:event/type "shotoff"
:event/elapsed 75
:event/subtype "deflected"
:event/player1 "Thievy Bifouma"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3259583"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3259587"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3813"}

{:event/type "shotoff"
:event/elapsed 75
:event/subtype "bad shot"
:event/player1 "Thievy Bifouma"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3259589"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Steven Reid"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3259594"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3813"}

{:event/type "shotoff"
:event/elapsed 76
:event/subtype "big chance volley"
:event/player1 "Chris Brunt"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3259596"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3813"}

{:event/type "card"
:event/elapsed 76
:event/card_type "y"
:event/subtype "verbal_abuse"
:event/player1 "Branislav Ivanovic"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_3259601"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3813"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Fernando Torres"
:event/subtype "pull"
:event/player1 "Gareth McAuley"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3259605"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_3813"}

{:event/type "shotoff"
:event/elapsed 78
:event/subtype "direct_freekick"
:event/player1 "David Luiz"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3259615"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Saido Berahino"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3259624"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3259625"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_3813"}

{:event/type "corner"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3259625"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_3813"}

{:event/type "shotoff"
:event/elapsed 81
:event/subtype "header"
:event/player1 "Craig Dawson"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3259627"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_3813"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Victor Anichebe"
:event/subtype "pull"
:event/player1 "David Luiz"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3259633"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_3813"}

{:event/type "card"
:event/elapsed 81
:event/card_type "y"
:event/player1 "David Luiz"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_3259634"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Steven Reid"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3259638"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_3813"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Matej Vydra"
:event/player1 "Nemanja Matic"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3259640"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_3813"}

{:event/type "shoton"
:event/elapsed 83
:event/subtype "indirect freekick"
:event/player1 "Chris Brunt"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3259642"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Saido Berahino"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3259651"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_3813"}

{:event/type "goal"
:event/elapsed 87
:event/player2 "Saido Berahino"
:event/subtype "header"
:event/player1 "Victor Anichebe"
:event/sortorder 1
:event/team "home"
:event/id "event_3259652"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_3813"}

{:event/type "card"
:event/elapsed 88
:event/card_type "y"
:event/player1 "Victor Anichebe"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3259654"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_3813"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player2 "Steven Reid"
:event/subtype "trip"
:event/player1 "Nemanja Matic"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3259655"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_3813"}

{:event/type "card"
:event/elapsed 89
:event/card_type "y"
:event/player1 "Nemanja Matic"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_3259656"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_3813"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Steven Reid"
:event/player1 "Fernando Torres"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3259664"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3813"}

{:event/type "shotoff"
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Chris Brunt"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3259668"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3813"}

{:event/type "shotoff"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "distance"
:event/player1 "Branislav Ivanovic"
:event/sortorder 8
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3259677"
:event/minute 93
:event/match_id "match_3813"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Saido Berahino"
:event/player1 "Mohamed Salah"
:event/sortorder 10
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3259682"
:event/minute 93
:event/match_id "match_3813"}

{:event/type "shotoff"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "volley"
:event/player1 "Matej Vydra"
:event/sortorder 11
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3259683"
:event/minute 94
:event/match_id "match_3813"}

{:event/type "shoton"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "blocked_shot"
:event/player1 "Victor Anichebe"
:event/sortorder 12
:event/team "home"
:event/event_type "shoton"
:event/id "event_3259687"
:event/minute 95
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 13
:event/team "home"
:event/event_type "corner"
:event/id "event_3259688"
:event/minute 95
:event/match_id "match_3813"}

{:event/type "corner"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 13
:event/team "home"
:event/event_type "corner"
:event/id "event_3259688"
:event/minute 95
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 14
:event/team "home"
:event/event_type "cross"
:event/id "event_3259689"
:event/minute 95
:event/match_id "match_3813"}

{:event/type "shoton"
:event/elapsed_plus 7
:event/elapsed 90
:event/subtype "blocked_shot"
:event/player1 "Willian"
:event/sortorder 15
:event/team "away"
:event/event_type "shoton"
:event/id "event_3259690"
:event/minute 97
:event/match_id "match_3813"}

{:event/type "cross"
:event/elapsed_plus 7
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Eden Hazard"
:event/sortorder 16
:event/team "away"
:event/event_type "corner"
:event/id "event_3259692"
:event/minute 97
:event/match_id "match_3813"}

{:event/type "corner"
:event/elapsed_plus 7
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Eden Hazard"
:event/sortorder 16
:event/team "away"
:event/event_type "corner"
:event/id "event_3259692"
:event/minute 97
:event/match_id "match_3813"}


]

