
;;# data
[
{:match/id "match_12487"
:match/league "Italy Serie A"
:match/hometeam "Chievo Verona"
:match/awayteam "Atalanta"
:match/score "0:1"
:match/hometeam_goals "0"
:match/awayteam_goals "1"}

{:event/type "card"
:event/elapsed 9
:event/card_type "y"
:event/player1 "Simone Bentivoglio"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3045160"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_12487"}

{:event/type "goal"
:event/elapsed 16
:event/player1 "Maxi Moralez"
:event/sortorder 0
:event/team "away"
:event/id "event_3045203"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_12487"}

{:event/type "card"
:event/elapsed 57
:event/card_type "y"
:event/player1 "Cristian Raimondi"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3045679"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_12487"}

{:event/type "card"
:event/elapsed 89
:event/card_type "y"
:event/player1 "Bostjan Cesar"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3045821"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_12487"}


]

