
;;# data
[
{:match/id "match_5612"
:match/league "France Ligue 1"
:match/hometeam "Stade Brestois 29"
:match/awayteam "Montpellier Hérault SC"
:match/score "0:0"
:match/hometeam_goals "0"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 56
:event/card_type "y"
:event/player1 "Romain Pitau"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1326425"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_5612"}

{:event/type "card"
:event/elapsed 75
:event/card_type "y"
:event/player1 "Emir Spahic"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1326491"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_5612"}


]

