
;;# data
[
{:match/id "match_10771"
:match/league "Italy Serie A"
:match/hometeam "Palermo"
:match/awayteam "Fiorentina"
:match/score "3:0"
:match/hometeam_goals "3"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 16
:event/card_type "y"
:event/player1 "Riccardo Montolivo"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_923936"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_10771"}

{:event/type "goal"
:event/elapsed 27
:event/player1 "Abel Hernandez"
:event/sortorder 0
:event/team "home"
:event/id "event_923952"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_10771"}

{:event/type "card"
:event/elapsed 29
:event/card_type "y"
:event/player1 "Abel Hernandez"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_923979"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_10771"}

{:event/type "goal"
:event/elapsed 36
:event/player1 "Abel Hernandez"
:event/sortorder 0
:event/team "home"
:event/id "event_924023"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_10771"}

{:event/type "card"
:event/elapsed 39
:event/card_type "y"
:event/player1 "Federico Balzaretti"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_924056"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_10771"}

{:event/type "goal"
:event/elapsed 58
:event/player1 "Igor Budan"
:event/sortorder 0
:event/team "home"
:event/id "event_924275"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_10771"}


]

