
;;# data
[
{:match/id "match_2296"
:match/league "England Premier League"
:match/hometeam "Aston Villa"
:match/awayteam "Manchester United"
:match/score "2:0"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "James Milner"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_947956"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Darren Fletcher"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_947973"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_2296"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Richard Dunne"
:event/player1 "Nani"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_947991"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Paul Scholes"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_947995"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_2296"}

{:event/type "shotoff"
:event/elapsed 7
:event/subtype "distance"
:event/player1 "Stewart Downing"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_948016"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_2296"}

{:event/type "foulcommit"
:event/elapsed 8
:event/player2 "Ryan Giggs"
:event/player1 "Ashley Young"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_948024"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_2296"}

{:event/type "shoton"
:event/elapsed 8
:event/subtype "direct_freekick"
:event/player1 "Nani"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_948029"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_2296"}

{:event/type "shotoff"
:event/elapsed 9
:event/subtype "deflected"
:event/player1 "Ryan Giggs"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_948035"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_948045"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_2296"}

{:event/type "corner"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_948045"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_2296"}

{:event/type "shoton"
:event/elapsed 13
:event/subtype "blocked_shot"
:event/player1 "James Milner"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_948085"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_2296"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Ashley Young"
:event/player1 "Patrice Evra"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_948087"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_2296"}

{:event/type "shotoff"
:event/elapsed 13
:event/subtype "header"
:event/player1 "Carlos Cuellar"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_948098"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Luke Young"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_948126"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Ashley Young"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_948134"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_2296"}

{:event/type "shotoff"
:event/elapsed 18
:event/subtype "deflected"
:event/player1 "Ashley Young"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_948175"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_948185"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_2296"}

{:event/type "corner"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_948185"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_948190"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_2296"}

{:event/type "goal"
:event/elapsed 19
:event/subtype "header"
:event/player1 "Carlos Cuellar"
:event/sortorder 4
:event/team "home"
:event/id "event_948191"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Paul Scholes"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_948211"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_2296"}

{:event/type "shoton"
:event/elapsed 21
:event/subtype "blocked_shot"
:event/player1 "Paul Scholes"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_948232"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_948252"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_2296"}

{:event/type "shoton"
:event/elapsed 23
:event/subtype "deflected"
:event/player1 "Ryan Giggs"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_948261"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_2296"}

{:event/type "goal"
:event/elapsed 23
:event/player1 "James Collins"
:event/sortorder 2
:event/team "home"
:event/id "event_948254"
:event/event_type "goal"
:event/goal_type "o"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_2296"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Stiliyan Petrov"
:event/subtype "shirt_pull"
:event/player1 "Jonny Evans"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_948312"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_2296"}

{:event/type "card"
:event/elapsed 26
:event/card_type "y"
:event/subtype "shirt_pull"
:event/player1 "Jonny Evans"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_948319"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_2296"}

{:event/type "foulcommit"
:event/elapsed 27
:event/subtype "hands"
:event/player1 "Wes Brown"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_948325"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_2296"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Stiliyan Petrov"
:event/subtype "serious_foul"
:event/player1 "Nani"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_948359"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2296"}

{:event/type "card"
:event/elapsed 29
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Nani"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_948363"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_948392"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_2296"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Wes Brown"
:event/player1 "Gabriel Agbonlahor"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_948397"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Luke Young"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_948418"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_2296"}

{:event/type "shoton"
:event/elapsed 33
:event/subtype "blocked_shot"
:event/player1 "James Milner"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_948423"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "James Milner"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_948434"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Paul Scholes"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_948445"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_948459"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_2296"}

{:event/type "corner"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_948459"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_2296"}

{:event/type "shoton"
:event/elapsed 35
:event/subtype "volley"
:event/player1 "Michael Carrick"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_948463"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_948469"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_2296"}

{:event/type "corner"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_948469"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Darren Fletcher"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_948479"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_948507"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_2296"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Gabriel Agbonlahor"
:event/player1 "Wes Brown"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_948528"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Carlos Cuellar"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_948553"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_2296"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Rafael"
:event/player1 "James Milner"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_948571"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_2296"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Ashley Young"
:event/player1 "Wayne Rooney"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_948579"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_948607"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_948748"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_2296"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "distance"
:event/player1 "Stewart Downing"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_948638"
:event/minute 46
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_948750"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_2296"}

{:event/type "corner"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_948750"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_2296"}

{:event/type "shotoff"
:event/elapsed 46
:event/subtype "header"
:event/player1 "Darren Fletcher"
:event/sortorder 5
:event/team "away"
:event/event_type "shotoff"
:event/id "event_948751"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Darren Fletcher"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_948764"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_2296"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Antonio Valencia"
:event/player1 "Luke Young"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_948800"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_948845"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_2296"}

{:event/type "shotoff"
:event/elapsed 53
:event/subtype "shot"
:event/player1 "Antonio Valencia"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_948848"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Wayne Rooney"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_948859"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Patrice Evra"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_948876"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_948889"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_2296"}

{:event/type "corner"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_948889"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_2296"}

{:event/type "shoton"
:event/elapsed 56
:event/subtype "blocked_shot"
:event/player1 "Wayne Rooney"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_948897"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_2296"}

{:event/type "shoton"
:event/elapsed 58
:event/subtype "shot"
:event/player1 "James Milner"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_948934"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Ashley Young"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_948953"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_2296"}

{:event/type "shoton"
:event/elapsed 60
:event/subtype "header"
:event/player1 "Gabriel Agbonlahor"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_948957"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_2296"}

{:event/type "shotoff"
:event/elapsed 61
:event/subtype "shot"
:event/player1 "Wayne Rooney"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_948970"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_2296"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Ashley Young"
:event/player1 "Rafael"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_948977"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Antonio Valencia"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_949000"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_949022"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_2296"}

{:event/type "shotoff"
:event/elapsed 63
:event/subtype "shot"
:event/player1 "Wayne Rooney"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_949024"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_2296"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Luke Young"
:event/player1 "Antonio Valencia"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_949048"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_2296"}

{:event/type "foulcommit"
:event/elapsed 66
:event/player2 "Ryan Giggs"
:event/player1 "Carlos Cuellar"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_949067"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_2296"}

{:event/type "shoton"
:event/elapsed 66
:event/subtype "blocked_shot"
:event/player1 "Michael Carrick"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_949078"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_2296"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Michael Carrick"
:event/player1 "James Milner"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_949105"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_2296"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "James Collins"
:event/player1 "Antonio Valencia"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_949141"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Wayne Rooney"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_949160"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_2296"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Rafael"
:event/player1 "Steve Sidwell"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_949188"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_2296"}

{:event/type "shoton"
:event/elapsed 75
:event/subtype "distance"
:event/player1 "Wayne Rooney"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_949237"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Wayne Rooney"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_949245"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_2296"}

{:event/type "corner"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Wayne Rooney"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_949245"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Wayne Rooney"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_949253"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_2296"}

{:event/type "corner"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Wayne Rooney"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_949253"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Rafael"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_949286"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Carlos Cuellar"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_949393"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Carlos Cuellar"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_949421"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_2296"}

{:event/type "shotoff"
:event/elapsed 87
:event/subtype "header"
:event/player1 "Steve Sidwell"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_949422"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Wayne Rooney"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_949430"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_2296"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Darren Fletcher"
:event/player1 "James Milner"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_949441"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_2296"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player2 "Ashley Young"
:event/player1 "Rafael"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_949452"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_2296"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player2 "Antonio Valencia"
:event/player1 "Carlos Cuellar"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_949466"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_2296"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Gabriel Agbonlahor"
:event/player1 "Wayne Rooney"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_949500"
:event/minute 91
:event/match_id "match_2296"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Darren Fletcher"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_949519"
:event/minute 92
:event/match_id "match_2296"}


]

