
;;# data
[
{:match/id "match_6185"
:match/league "France Ligue 1"
:match/hometeam "AS Saint-Étienne"
:match/awayteam "Dijon FCO"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "goal"
:event/elapsed 43
:event/player1 "Pierre-Emerick Aubameyang"
:event/sortorder 0
:event/team "home"
:event/id "event_2102246"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_6185"}

{:event/type "card"
:event/elapsed 45
:event/card_type "y"
:event/player1 "Bakary Sako"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2102247"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_6185"}

{:event/type "card"
:event/elapsed 45
:event/card_type "y"
:event/player1 "Zie Diabate"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2102248"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_6185"}

{:event/type "card"
:event/elapsed 54
:event/card_type "y"
:event/player1 "Max-Alain Gradel"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2102431"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_6185"}

{:event/type "card"
:event/elapsed 60
:event/card_type "y"
:event/player1 "Laurent Batlles"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2102522"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_6185"}

{:event/type "card"
:event/elapsed 70
:event/card_type "y"
:event/player1 "Fabien Lemoine"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2102523"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_6185"}

{:event/type "card"
:event/elapsed 87
:event/card_type "y"
:event/player1 "Steven Paulle"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2102742"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_6185"}


]

