
;;# data
[
{:match/id "match_9037"
:match/league "Germany 1. Bundesliga"
:match/hometeam "FC Augsburg"
:match/awayteam "Fortuna Düsseldorf"
:match/score "0:2"
:match/hometeam_goals "0"
:match/awayteam_goals "2"}

{:event/type "card"
:event/elapsed 5
:event/card_type "y"
:event/player1 "Jan Moravek"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2303653"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_9037"}

{:event/type "card"
:event/elapsed 13
:event/card_type "y"
:event/player1 "Adam Bodzek"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2303652"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_9037"}

{:event/type "card"
:event/elapsed 41
:event/card_type "y"
:event/player1 "Matthias Ostrzolek"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2303902"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_9037"}

{:event/type "card"
:event/elapsed 63
:event/card_type "y"
:event/player1 "Giovanni Sio"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2304219"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_9037"}

{:event/type "goal"
:event/elapsed 69
:event/player1 "Dani Schahin"
:event/sortorder 0
:event/team "away"
:event/id "event_2304262"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_9037"}

{:event/type "goal"
:event/elapsed 79
:event/player1 "Dani Schahin"
:event/sortorder 0
:event/team "away"
:event/id "event_2304263"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_9037"}

{:event/type "card"
:event/elapsed 80
:event/card_type "y"
:event/player1 "Dani Schahin"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2304264"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_9037"}


]

