
;;# data
[
{:match/id "match_7097"
:match/league "France Ligue 1"
:match/hometeam "Toulouse FC"
:match/awayteam "FC Metz"
:match/score "3:0"
:match/hometeam_goals "3"
:match/awayteam_goals "0"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/sortorder 1
:event/team "away"
:event/event_type "throwin"
:event/id "event_3926372"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Pantxi Sirieix"
:event/player1 "Kevin Lejeune"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3926381"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_7097"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Jean-Daniel Akpa-Akpro"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3926394"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_7097"}

{:event/type "goal"
:event/elapsed 3
:event/player2 "Jean-Daniel Akpa-Akpro"
:event/subtype "tap_in"
:event/player1 "Pantxi Sirieix"
:event/sortorder 2
:event/team "home"
:event/id "event_3926400"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Aleksandar Pesic"
:event/player1 "Guido Milan"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3926441"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_7097"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Adrien Regattin"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3926461"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_7097"}

{:event/type "shoton"
:event/elapsed 6
:event/subtype "blocked_shot"
:event/player1 "Aleksandar Pesic"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3926467"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Jean-Daniel Akpa-Akpro"
:event/player1 "Guirane N'Daw"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3926563"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_7097"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Wissam Ben Yedder"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3926579"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Florent Malouda"
:event/player1 "Jean-Daniel Akpa-Akpro"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3926592"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Thibaut Vion"
:event/player1 "Uros Spajic"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3926603"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_7097"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Kevin Lejeune"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3926609"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Uros Spajic"
:event/subtype "dangerous_play"
:event/player1 "Thibaut Vion"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3926676"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_7097"}

{:event/type "card"
:event/elapsed 15
:event/card_type "y"
:event/player1 "Thibaut Vion"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_3926678"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_7097"}

{:event/type "shotoff"
:event/elapsed 17
:event/subtype "deflected"
:event/player1 "Tongo Hamed Doumbia"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3926734"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_7097"}

{:event/type "corner"
:event/elapsed 17
:event/subtype "cross_left"
:event/player1 "Wissam Ben Yedder"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3926741"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Florent Malouda"
:event/player1 "Jean-Daniel Akpa-Akpro"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3926823"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_7097"}

{:event/type "shoton"
:event/elapsed 19
:event/subtype "volley"
:event/player1 "Pantxi Sirieix"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3926788"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_7097"}

{:event/type "corner"
:event/elapsed 19
:event/subtype "cross_right"
:event/player1 "Wissam Ben Yedder"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3926800"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 21
:event/subtype "hands"
:event/player1 "Dusan Veskovac"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3926858"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_7097"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Florent Malouda"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3926862"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_7097"}

{:event/type "shoton"
:event/elapsed 22
:event/subtype "shot"
:event/player1 "Jeremy Choplin"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3926866"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Adrien Regattin"
:event/player1 "Ahmed Kashi"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3926870"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_7097"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Thibaut Vion"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3926904"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_7097"}

{:event/type "shotoff"
:event/elapsed 25
:event/subtype "bad shot"
:event/player1 "Guirane N'Daw"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3926921"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Dusan Veskovac"
:event/player1 "Modibo Maiga"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3926936"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_7097"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Jean-Daniel Akpa-Akpro"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3926943"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Guido Milan"
:event/player1 "Aleksandar Pesic"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3926955"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_7097"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Romain Metannire"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3926966"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_7097"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Adrien Regattin"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3927003"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Adrien Regattin"
:event/player1 "Romain Metannire"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3927023"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Wissam Ben Yedder"
:event/subtype "obstruction"
:event/player1 "Ahmed Kashi"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3927039"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Thibaut Vion"
:event/player1 "Tongo Hamed Doumbia"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3927046"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_7097"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Florent Malouda"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3927051"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 34
:event/player2 "Florent Malouda"
:event/player1 "Abel Aguilar"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3927076"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_7097"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Florent Malouda"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3927082"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_7097"}

{:event/type "corner"
:event/elapsed 35
:event/subtype "cross_left"
:event/player1 "Kevin Lejeune"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3927091"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Ahmed Kashi"
:event/player1 "Jean-Daniel Akpa-Akpro"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3927108"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Wissam Ben Yedder"
:event/player1 "Ahmed Kashi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3927136"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Guido Milan"
:event/player1 "Aleksandar Pesic"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3927161"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_7097"}

{:event/type "shoton"
:event/elapsed 39
:event/subtype "shot"
:event/player1 "Kevin Lejeune"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3927170"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Uros Spajic"
:event/player1 "Modibo Maiga"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3927243"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 41
:event/subtype "hands"
:event/player1 "Modibo Maiga"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3927290"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_7097"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Jose Luis Palomino"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3927214"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Francois Moubandje"
:event/player1 "Modibo Maiga"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3927230"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_7097"}

{:event/type "shoton"
:event/elapsed 42
:event/subtype "distance"
:event/player1 "Aleksandar Pesic"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3927237"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_7097"}

{:event/type "shoton"
:event/elapsed 43
:event/subtype "blocked_shot"
:event/player1 "Wissam Ben Yedder"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3927258"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Jeremy Choplin"
:event/player1 "Adrien Regattin"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3927305"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_7097"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Romain Metannire"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3927503"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 47
:event/player2 "Jeremy Choplin"
:event/player1 "Tongo Hamed Doumbia"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3927517"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Kevin Lejeune"
:event/player1 "Pantxi Sirieix"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3927599"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Guirane N'Daw"
:event/subtype "advantage"
:event/player1 "Pantxi Sirieix"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3927613"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_7097"}

{:event/type "card"
:event/elapsed 54
:event/card_type "y"
:event/subtype "advantage"
:event/player1 "Pantxi Sirieix"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3927635"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_7097"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Romain Metannire"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3927662"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Wissam Ben Yedder"
:event/player1 "Jeremy Choplin"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3927680"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_7097"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Wissam Ben Yedder"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3927700"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_7097"}

{:event/type "shotoff"
:event/elapsed 58
:event/subtype "header"
:event/player1 "Uros Spajic"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3927703"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_7097"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Romain Metannire"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3927715"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_7097"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_3927731"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_7097"}

{:event/type "goal"
:event/elapsed 61
:event/player2 "Aleksandar Pesic"
:event/subtype "shot"
:event/player1 "Wissam Ben Yedder"
:event/sortorder 2
:event/team "home"
:event/id "event_3927751"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Jean-Daniel Akpa-Akpro"
:event/subtype "pull"
:event/player1 "Jose Luis Palomino"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3927782"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_7097"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Wissam Ben Yedder"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3927793"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_7097"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Jean-Daniel Akpa-Akpro"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_3927806"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_7097"}

{:event/type "corner"
:event/elapsed 65
:event/subtype "cross_left"
:event/player1 "Wissam Ben Yedder"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3927816"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_7097"}

{:event/type "shotoff"
:event/elapsed 65
:event/subtype "header"
:event/player1 "Uros Spajic"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3927820"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Jeremy Choplin"
:event/player1 "Aleksandar Pesic"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3927908"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Jeremy Choplin"
:event/player1 "Aleksandar Pesic"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3927919"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_7097"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Florent Malouda"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3927924"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_7097"}

{:event/type "goal"
:event/elapsed 71
:event/player2 "Wissam Ben Yedder"
:event/subtype "shot"
:event/player1 "Aleksandar Pesic"
:event/sortorder 4
:event/team "home"
:event/id "event_3927945"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_7097"}

{:event/type "shoton"
:event/elapsed 73
:event/subtype "blocked_shot"
:event/player1 "Modibo Maiga"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3927979"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 76
:event/player2 "Uros Spajic"
:event/player1 "Florent Malouda"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3928012"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_7097"}

{:event/type "shotoff"
:event/elapsed 76
:event/subtype "distance"
:event/player1 "Guirane N'Daw"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3928021"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Ahmed Kashi"
:event/player1 "Aleksandar Pesic"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3928032"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_7097"}

{:event/type "corner"
:event/elapsed 78
:event/subtype "cross_right"
:event/player1 "Florent Malouda"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3928048"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_7097"}

{:event/type "shotoff"
:event/elapsed 78
:event/subtype "distance"
:event/player1 "Sergey Krivets"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3928052"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 80
:event/subtype "hands"
:event/player1 "Bouna Sarr"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3928081"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_7097"}

{:event/type "corner"
:event/elapsed 81
:event/subtype "cross_left"
:event/player1 "Adrien Regattin"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3928091"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_7097"}

{:event/type "shotoff"
:event/elapsed 81
:event/subtype "deflected"
:event/player1 "Jean-Daniel Akpa-Akpro"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3928094"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_7097"}

{:event/type "corner"
:event/elapsed 82
:event/subtype "cross_right"
:event/player1 "Adrien Regattin"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3928096"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_7097"}

{:event/type "corner"
:event/elapsed 82
:event/subtype "cross_right"
:event/player1 "Adrien Regattin"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3928100"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_7097"}

{:event/type "shotoff"
:event/elapsed 82
:event/subtype "header"
:event/player1 "Uros Spajic"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3928105"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_7097"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Adrien Regattin"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3928114"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Florent Malouda"
:event/player1 "Jean-Daniel Akpa-Akpro"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3928134"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_7097"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Bouna Sarr"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3928137"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_7097"}

{:event/type "shotoff"
:event/elapsed 85
:event/subtype "header"
:event/player1 "Guido Milan"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3928142"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Tongo Hamed Doumbia"
:event/player1 "Guirane N'Daw"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3928179"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_7097"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Pantxi Sirieix"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3928185"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player2 "Florent Malouda"
:event/player1 "Pavle Ninkov"
:event/sortorder 5
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3928198"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Florent Malouda"
:event/player1 "Pavle Ninkov"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3928207"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_7097"}

{:event/type "shotoff"
:event/elapsed 90
:event/subtype "distance"
:event/player1 "Sergey Krivets"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3928213"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_7097"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Francois Moubandje"
:event/player1 "Bouna Sarr"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3928220"
:event/minute 91
:event/match_id "match_7097"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/sortorder 6
:event/team "home"
:event/event_type "throwin"
:event/id "event_3928255"
:event/minute 93
:event/match_id "match_7097"}


]

