
;;# data
[
{:match/id "match_4118"
:match/league "England Premier League"
:match/hometeam "West Ham United"
:match/awayteam "Arsenal"
:match/score "2:2"
:match/hometeam_goals "1"
:match/awayteam_goals "2"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Morgan Amalfitano"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4036538"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_4118"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Nacho Monreal"
:event/subtype "trip"
:event/player1 "Joey O'Brien"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4036546"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Alex Song"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4036572"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_4118"}

{:event/type "corner"
:event/elapsed 5
:event/subtype "cross_right"
:event/player1 "Stewart Downing"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4036576"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_4118"}

{:event/type "corner"
:event/elapsed 6
:event/subtype "cross_left"
:event/player1 "Morgan Amalfitano"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4036588"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_4118"}

{:event/type "goal"
:event/elapsed 6
:event/subtype "shot"
:event/player1 "Alex Song"
:event/sortorder 1
:event/team "home"
:event/id "event_4036590"
:event/event_type "goal"
:event/goal_type "dg"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4036630"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Morgan Amalfitano"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4036649"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_4118"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Alexis Sanchez"
:event/subtype "pushing"
:event/player1 "Alex Song"
:event/sortorder 5
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4036657"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_4118"}

{:event/type "shoton"
:event/elapsed 11
:event/subtype "blocked_shot"
:event/player1 "Alexis Sanchez"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4036664"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_4118"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Nacho Monreal"
:event/subtype "pushing"
:event/player1 "Diafra Sakho"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4036682"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_4118"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Diafra Sakho"
:event/player1 "Nacho Monreal"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4036713"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Morgan Amalfitano"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4036716"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_4118"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Alexis Sanchez"
:event/subtype "trip"
:event/player1 "Joey O'Brien"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4036722"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_4118"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "Danny Welbeck"
:event/player1 "Alex Song"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4036739"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Santi Cazorla"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4036749"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Aaron Cresswell"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4036772"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_4118"}

{:event/type "shoton"
:event/elapsed 19
:event/subtype "shot"
:event/player1 "Cheikhou Kouyate"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4036787"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_4118"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "James Tomkins"
:event/subtype "pushing"
:event/player1 "Alexis Sanchez"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4036792"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_4118"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Stewart Downing"
:event/subtype "trip"
:event/player1 "Alexis Sanchez"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4036812"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Morgan Amalfitano"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4036818"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_4118"}

{:event/type "shoton"
:event/elapsed 21
:event/subtype "shot"
:event/player1 "Andy Carroll"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4036821"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_4118"}

{:event/type "corner"
:event/elapsed 21
:event/subtype "cross_left"
:event/player1 "Morgan Amalfitano"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4036827"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_4036833"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_4118"}

{:event/type "shotoff"
:event/elapsed 21
:event/subtype "shot"
:event/player1 "Andy Carroll"
:event/sortorder 5
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4036835"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_4118"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Alex Song"
:event/player1 "Alex Oxlade-Chamberlain"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4036864"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Morgan Amalfitano"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4036868"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_4118"}

{:event/type "shoton"
:event/elapsed 24
:event/subtype "header"
:event/player1 "Andy Carroll"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4036871"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_4118"}

{:event/type "shoton"
:event/elapsed 24
:event/subtype "deflected"
:event/player1 "Alexis Sanchez"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_4036885"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_4118"}

{:event/type "corner"
:event/elapsed 24
:event/subtype "cross_right"
:event/player1 "Santi Cazorla"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_4036890"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Alex Oxlade-Chamberlain"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4036898"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_4118"}

{:event/type "corner"
:event/elapsed 25
:event/subtype "cross_right"
:event/player1 "Santi Cazorla"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_4036908"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_4118"}

{:event/type "shoton"
:event/elapsed 25
:event/subtype "blocked_shot"
:event/player1 "Santi Cazorla"
:event/sortorder 5
:event/team "away"
:event/event_type "shoton"
:event/id "event_4036913"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_4118"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Alexis Sanchez"
:event/subtype "trip"
:event/player1 "Morgan Amalfitano"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4036934"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_4118"}

{:event/type "shoton"
:event/elapsed 31
:event/subtype "deflected"
:event/player1 "Morgan Amalfitano"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4037012"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_4118"}

{:event/type "corner"
:event/elapsed 31
:event/subtype "cross_right"
:event/player1 "Morgan Amalfitano"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4037014"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Cheikhou Kouyate"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_4037016"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Santi Cazorla"
:event/sortorder 7
:event/team "away"
:event/event_type "cross"
:event/id "event_4037023"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_4118"}

{:event/type "corner"
:event/elapsed 32
:event/subtype "cross_left"
:event/player1 "Alexis Sanchez"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4037030"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Aaron Cresswell"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4037043"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Joey O'Brien"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_4037047"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Alexis Sanchez"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4037059"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_4118"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Aaron Cresswell"
:event/player1 "Danny Welbeck"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4037079"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_4118"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Mathieu Debuchy"
:event/player1 "Andy Carroll"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4037085"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_4118"}

{:event/type "card"
:event/elapsed 36
:event/card_type "y"
:event/player1 "Andy Carroll"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4037086"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_4118"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Morgan Amalfitano"
:event/player1 "Alexis Sanchez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4037118"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Andy Carroll"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4037121"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4037124"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_4118"}

{:event/type "shotoff"
:event/elapsed 38
:event/subtype "big chance volley"
:event/player1 "James Tomkins"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4037125"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_4118"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Santi Cazorla"
:event/subtype "penalty"
:event/player1 "Winston Reid"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4037150"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_4118"}

{:event/type "goal"
:event/elapsed 41
:event/player1 "Santi Cazorla"
:event/sortorder 0
:event/team "away"
:event/id "event_4037167"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_4118"}

{:event/type "goal"
:event/elapsed 44
:event/player2 "Alex Oxlade-Chamberlain"
:event/subtype "shot"
:event/player1 "Danny Welbeck"
:event/sortorder 1
:event/team "away"
:event/id "event_4037224"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Morgan Amalfitano"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4037257"
:event/minute 46
:event/match_id "match_4118"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "big chance shot"
:event/player1 "Stewart Downing"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4037259"
:event/minute 46
:event/match_id "match_4118"}

{:event/type "corner"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross_right"
:event/player1 "Santi Cazorla"
:event/sortorder 10
:event/team "away"
:event/event_type "corner"
:event/id "event_4037282"
:event/minute 47
:event/match_id "match_4118"}

{:event/type "shoton"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "blocked_shot"
:event/player1 "Alexis Sanchez"
:event/sortorder 12
:event/team "away"
:event/event_type "shoton"
:event/id "event_4037295"
:event/minute 47
:event/match_id "match_4118"}

{:event/type "shoton"
:event/elapsed 48
:event/subtype "distance"
:event/player1 "Mathieu Debuchy"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4037378"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_4118"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Andy Carroll"
:event/player1 "Laurent Koscielny"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4037383"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_4118"}

{:event/type "card"
:event/elapsed 48
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Alexis Sanchez"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_4037387"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_4118"}

{:event/type "corner"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "short_left"
:event/player1 "Alex Oxlade-Chamberlain"
:event/sortorder 13
:event/team "away"
:event/event_type "corner"
:event/id "event_4037300"
:event/minute 48
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4037389"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Alexis Sanchez"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4037439"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_4118"}

{:event/type "shoton"
:event/elapsed 53
:event/subtype "shot"
:event/player1 "Mathieu Debuchy"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_4037449"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Diafra Sakho"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4037454"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_4118"}

{:event/type "corner"
:event/elapsed 54
:event/subtype "cross_left"
:event/player1 "Morgan Amalfitano"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_4037456"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "James Tomkins"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_4037457"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_4118"}

{:event/type "goal"
:event/elapsed 54
:event/player2 "James Tomkins"
:event/subtype "header"
:event/player1 "Cheikhou Kouyate"
:event/sortorder 5
:event/team "home"
:event/id "event_4037459"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Diafra Sakho"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4037474"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_4118"}

{:event/type "shoton"
:event/elapsed 57
:event/subtype "big chance shot"
:event/player1 "Santi Cazorla"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4037485"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_4118"}

{:event/type "corner"
:event/elapsed 57
:event/subtype "cross_left"
:event/player1 "Santi Cazorla"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_4037496"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_4118"}

{:event/type "shotoff"
:event/elapsed 57
:event/subtype "header"
:event/player1 "Mathieu Debuchy"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4037501"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Cheikhou Kouyate"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4037540"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Andy Carroll"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4037555"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Alexis Sanchez"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4037596"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_4118"}

{:event/type "shoton"
:event/elapsed 63
:event/subtype "shot"
:event/player1 "Winston Reid"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_4037603"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_4118"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "James Tomkins"
:event/player1 "Mathieu Debuchy"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4037610"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4037613"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4037619"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_4118"}

{:event/type "shotoff"
:event/elapsed 65
:event/subtype "lob"
:event/player1 "Andy Carroll"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4037625"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Morgan Amalfitano"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_4037637"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_4118"}

{:event/type "shoton"
:event/elapsed 66
:event/subtype "big chance shot"
:event/player1 "Danny Welbeck"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4037648"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_4118"}

{:event/type "shotoff"
:event/elapsed 66
:event/subtype "shot"
:event/player1 "Danny Welbeck"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4037661"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_4118"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Alexis Sanchez"
:event/subtype "pushing"
:event/player1 "Alex Song"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4037667"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Laurent Koscielny"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4037670"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_4118"}

{:event/type "shoton"
:event/elapsed 68
:event/subtype "deflected"
:event/player1 "Alexis Sanchez"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4037684"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_4118"}

{:event/type "corner"
:event/elapsed 68
:event/subtype "cross_right"
:event/player1 "Santi Cazorla"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4037694"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_4118"}

{:event/type "shoton"
:event/elapsed 68
:event/subtype "blocked_shot"
:event/player1 "Laurent Koscielny"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_4037695"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_4118"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Andy Carroll"
:event/player1 "Laurent Koscielny"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4037698"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_4118"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Aaron Cresswell"
:event/player1 "Alexis Sanchez"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4037735"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_4118"}

{:event/type "shotoff"
:event/elapsed 71
:event/subtype "distance"
:event/player1 "Morgan Amalfitano"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4037744"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Morgan Amalfitano"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4037756"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_4118"}

{:event/type "corner"
:event/elapsed 72
:event/subtype "cross_left"
:event/player1 "Stewart Downing"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_4037759"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4037766"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_4118"}

{:event/type "shoton"
:event/elapsed 73
:event/subtype "header"
:event/player1 "Andy Carroll"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4037769"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Danny Welbeck"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4037774"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Alexis Sanchez"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4037789"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_4118"}

{:event/type "shoton"
:event/elapsed 74
:event/subtype "big chance header"
:event/player1 "Alex Oxlade-Chamberlain"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4037793"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Morgan Amalfitano"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4037797"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_4118"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Santi Cazorla"
:event/subtype "pushing"
:event/player1 "Cheikhou Kouyate"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4037812"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Laurent Koscielny"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4037818"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_4118"}

{:event/type "shoton"
:event/elapsed 76
:event/subtype "big chance shot"
:event/player1 "Alexis Sanchez"
:event/sortorder 4
:event/team "away"
:event/event_type "shoton"
:event/id "event_4037833"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_4118"}

{:event/type "corner"
:event/elapsed 77
:event/subtype "cross_left"
:event/player1 "Santi Cazorla"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4037836"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_4118"}

{:event/type "shotoff"
:event/elapsed 77
:event/subtype "header"
:event/player1 "Laurent Koscielny"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4037840"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_4118"}

{:event/type "shotoff"
:event/elapsed 77
:event/subtype "big chance shot"
:event/player1 "Danny Welbeck"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4037854"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_4118"}

{:event/type "shoton"
:event/elapsed 80
:event/subtype "shot"
:event/player1 "Santi Cazorla"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4037893"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_4118"}

{:event/type "shotoff"
:event/elapsed 80
:event/subtype "shot"
:event/player1 "Santi Cazorla"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4037898"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_4118"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Enner Valencia"
:event/player1 "Mathieu Debuchy"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4037913"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_4118"}

{:event/type "card"
:event/elapsed 80
:event/card_type "y"
:event/player1 "Mathieu Debuchy"
:event/sortorder 4
:event/team "away"
:event/event_type "card"
:event/id "event_4037915"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Enner Valencia"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4037920"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_4118"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Santi Cazorla"
:event/subtype "pushing"
:event/player1 "James Tomkins"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4037973"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_4118"}

{:event/type "card"
:event/elapsed 84
:event/card_type "y"
:event/player1 "James Tomkins"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_4037974"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_4118"}

{:event/type "shoton"
:event/elapsed 85
:event/subtype "direct_freekick"
:event/player1 "Alexis Sanchez"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4037987"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Guy Demel"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4037997"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Aaron Cresswell"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_4038005"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Aaron Cresswell"
:event/sortorder 6
:event/team "home"
:event/event_type "cross"
:event/id "event_4038011"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_4118"}

{:event/type "shotoff"
:event/elapsed 87
:event/subtype "shot"
:event/player1 "Alex Oxlade-Chamberlain"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4038023"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_4118"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Alexis Sanchez"
:event/player1 "Winston Reid"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4038044"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_4118"}

{:event/type "card"
:event/elapsed 88
:event/card_type "y"
:event/player1 "Winston Reid"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_4038075"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Guy Demel"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4038064"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_4118"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "big chance shot"
:event/player1 "Kevin Nolan"
:event/sortorder 5
:event/team "home"
:event/event_type "shoton"
:event/id "event_4038102"
:event/minute 91
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Stewart Downing"
:event/sortorder 7
:event/team "home"
:event/event_type "cross"
:event/id "event_4038108"
:event/minute 91
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "James Tomkins"
:event/sortorder 10
:event/team "home"
:event/event_type "cross"
:event/id "event_4038116"
:event/minute 92
:event/match_id "match_4118"}

{:event/type "corner"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross_right"
:event/player1 "Morgan Amalfitano"
:event/sortorder 12
:event/team "home"
:event/event_type "corner"
:event/id "event_4038128"
:event/minute 92
:event/match_id "match_4118"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Alexis Sanchez"
:event/player1 "Andy Carroll"
:event/sortorder 13
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4038141"
:event/minute 93
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Kevin Nolan"
:event/sortorder 15
:event/team "home"
:event/event_type "cross"
:event/id "event_4038159"
:event/minute 94
:event/match_id "match_4118"}

{:event/type "foulcommit"
:event/elapsed_plus 4
:event/elapsed 90
:event/player2 "Alex Song"
:event/subtype "pushing"
:event/player1 "Alexis Sanchez"
:event/sortorder 17
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4038168"
:event/minute 94
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Alex Song"
:event/sortorder 18
:event/team "home"
:event/event_type "cross"
:event/id "event_4038172"
:event/minute 94
:event/match_id "match_4118"}

{:event/type "foulcommit"
:event/elapsed_plus 5
:event/elapsed 90
:event/player2 "Stewart Downing"
:event/player1 "Francis Coquelin"
:event/sortorder 20
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4038184"
:event/minute 95
:event/match_id "match_4118"}

{:event/type "card"
:event/elapsed_plus 5
:event/elapsed 90
:event/card_type "y"
:event/player1 "Francis Coquelin"
:event/sortorder 21
:event/team "away"
:event/event_type "card"
:event/id "event_4038185"
:event/minute 95
:event/match_id "match_4118"}

{:event/type "cross"
:event/elapsed_plus 6
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Alex Song"
:event/sortorder 22
:event/team "home"
:event/event_type "cross"
:event/id "event_4038193"
:event/minute 96
:event/match_id "match_4118"}

{:event/type "shotoff"
:event/elapsed_plus 6
:event/elapsed 90
:event/subtype "big chance header"
:event/player1 "Enner Valencia"
:event/sortorder 25
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4038197"
:event/minute 96
:event/match_id "match_4118"}


]

