
;;# data
[
{:match/id "match_3443"
:match/league "England Premier League"
:match/hometeam "Newcastle United"
:match/awayteam "Southampton"
:match/score "3:3"
:match/hometeam_goals "4"
:match/awayteam_goals "2"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Jack Cork"
:event/sortorder -2
:event/team "away"
:event/event_type "cross"
:event/id "event_2618031"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_3443"}

{:event/type "goal"
:event/elapsed 3
:event/player2 "Rickie Lambert"
:event/subtype "shot"
:event/player1 "Morgan Schneiderlin"
:event/sortorder 0
:event/team "away"
:event/id "event_2618029"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Mathieu Debuchy"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2618042"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Yoan Gouffran"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2618044"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_3443"}

{:event/type "corner"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Yoan Gouffran"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2618044"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_3443"}

{:event/type "shotoff"
:event/elapsed 7
:event/subtype "shot"
:event/player1 "Fabricio Coloccini"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2618046"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_3443"}

{:event/type "shoton"
:event/elapsed 8
:event/subtype "blocked_shot"
:event/player1 "Adam Lallana"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_2618049"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Nathaniel Clyne"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2618061"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_3443"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Steven Taylor"
:event/subtype "dangerous_play"
:event/player1 "Adam Lallana"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2618066"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 13
:event/subtype "cross"
:event/player1 "Papiss Cisse"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2618077"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Nathaniel Clyne"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2618081"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_3443"}

{:event/type "shoton"
:event/elapsed 15
:event/subtype "shot"
:event/player1 "Moussa Sissoko"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_2618089"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2618091"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_3443"}

{:event/type "corner"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2618091"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Moussa Sissoko"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2618097"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Mathieu Debuchy"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2618105"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3443"}

{:event/type "shotoff"
:event/elapsed 19
:event/subtype "miss_kick"
:event/player1 "Papiss Cisse"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2618111"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2618128"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_3443"}

{:event/type "corner"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2618128"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2618133"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_3443"}

{:event/type "corner"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2618133"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_3443"}

{:event/type "shoton"
:event/elapsed 22
:event/subtype "blocked_shot"
:event/player1 "Steven Taylor"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_2618134"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Mathieu Debuchy"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_2618135"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_3443"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Davide Santon"
:event/player1 "Rickie Lambert"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2618148"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_3443"}

{:event/type "shoton"
:event/elapsed 25
:event/subtype "blocked_shot"
:event/player1 "Rickie Lambert"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_2618154"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3443"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Jonas Gutierrez"
:event/player1 "Jay Rodriguez"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2618156"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3443"}

{:event/type "card"
:event/elapsed 25
:event/card_type "y"
:event/player1 "Jay Rodriguez"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_2618158"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3443"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Mathieu Debuchy"
:event/player1 "Luke Shaw"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2618167"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2618168"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_3443"}

{:event/type "shotoff"
:event/elapsed 28
:event/subtype "distance"
:event/player1 "Mathieu Debuchy"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2618179"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_3443"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Yohan Cabaye"
:event/player1 "Morgan Schneiderlin"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2618187"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_3443"}

{:event/type "shoton"
:event/elapsed 33
:event/subtype "big chance shot"
:event/player1 "Yoan Gouffran"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_2618210"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3443"}

{:event/type "goal"
:event/elapsed 33
:event/subtype "loose_ball"
:event/player1 "Moussa Sissoko"
:event/sortorder 1
:event/team "home"
:event/id "event_2618211"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3443"}

{:event/type "shotoff"
:event/elapsed 39
:event/subtype "shot"
:event/player1 "Moussa Sissoko"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2618239"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_3443"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Jonas Gutierrez"
:event/player1 "Luke Shaw"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2618249"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3443"}

{:event/type "card"
:event/elapsed 41
:event/card_type "y"
:event/subtype "shirt_pull"
:event/player1 "Luke Shaw"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_2618252"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Mathieu Debuchy"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_2618253"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3443"}

{:event/type "shotoff"
:event/elapsed 41
:event/subtype "shot"
:event/player1 "Jonas Gutierrez"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2618256"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Robert Elliot"
:event/sortorder -2
:event/team "home"
:event/event_type "cross"
:event/id "event_2618268"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_3443"}

{:event/type "goal"
:event/elapsed 42
:event/player2 "Robert Elliot"
:event/subtype "shot"
:event/player1 "Papiss Cisse"
:event/sortorder 0
:event/team "home"
:event/id "event_2618261"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Jay Rodriguez"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2618272"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_3443"}

{:event/type "foulcommit"
:event/elapsed 46
:event/player2 "Rickie Lambert"
:event/player1 "Mapou Yanga-Mbiwa"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2618350"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_3443"}

{:event/type "shoton"
:event/elapsed 47
:event/subtype "direct_freekick"
:event/player1 "Rickie Lambert"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_2618356"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Morgan Schneiderlin"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2618358"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_3443"}

{:event/type "corner"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Morgan Schneiderlin"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2618358"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_3443"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 45
:event/player2 "Nathaniel Clyne"
:event/player1 "Davide Santon"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2618302"
:event/minute 48
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Cheik Tiote"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_2618361"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Steven Davis"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2618304"
:event/minute 49
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Adam Lallana"
:event/sortorder -2
:event/team "away"
:event/event_type "cross"
:event/id "event_2618381"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_3443"}

{:event/type "goal"
:event/elapsed 50
:event/player2 "Adam Lallana"
:event/subtype "shot"
:event/player1 "Rickie Lambert"
:event/sortorder 0
:event/team "away"
:event/id "event_2618374"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Nathaniel Clyne"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2618386"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_3443"}

{:event/type "shotoff"
:event/elapsed 53
:event/subtype "big chance header"
:event/player1 "Rickie Lambert"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2618387"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_3443"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Nathaniel Clyne"
:event/player1 "Davide Santon"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2618394"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_3443"}

{:event/type "shotoff"
:event/elapsed 55
:event/subtype "shot"
:event/player1 "Adam Lallana"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2618405"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3443"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Steven Davis"
:event/player1 "Jonas Gutierrez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2618410"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2618438"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_3443"}

{:event/type "corner"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2618438"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Mathieu Debuchy"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2618456"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2618460"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3443"}

{:event/type "corner"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2618460"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Adam Lallana"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2618463"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Davide Santon"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2618477"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3443"}

{:event/type "foulcommit"
:event/elapsed 67
:event/subtype "penalty"
:event/player1 "Daniel Fox"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2618478"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3443"}

{:event/type "goal"
:event/elapsed 67
:event/player1 "Yohan Cabaye"
:event/sortorder 2
:event/team "home"
:event/id "event_2618481"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Adam Lallana"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2618508"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_3443"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Mapou Yanga-Mbiwa"
:event/player1 "Gaston Ramirez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2618511"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3443"}

{:event/type "foulcommit"
:event/elapsed 74
:event/player2 "Moussa Sissoko"
:event/player1 "Maya Yoshida"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2618514"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_3443"}

{:event/type "card"
:event/elapsed 74
:event/card_type "y"
:event/player1 "Maya Yoshida"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_2618515"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2618533"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3443"}

{:event/type "corner"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2618533"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3443"}

{:event/type "shoton"
:event/elapsed 78
:event/subtype "big chance blocked"
:event/player1 "Yoan Gouffran"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_2618542"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Davide Santon"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2618548"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_3443"}

{:event/type "goal"
:event/elapsed 79
:event/player1 "Jos Hooiveld"
:event/sortorder 1
:event/team "away"
:event/id "event_2618549"
:event/event_type "goal"
:event/goal_type "o"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Adam Lallana"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2618570"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Morgan Schneiderlin"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_2618571"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_3443"}

{:event/type "corner"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Morgan Schneiderlin"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_2618571"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Jack Cork"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2618573"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_3443"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Nathaniel Clyne"
:event/player1 "Papiss Cisse"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2618577"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_3443"}

{:event/type "foulcommit"
:event/elapsed 83
:event/player2 "Mathieu Debuchy"
:event/player1 "Daniel Fox"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2618578"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_3443"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Nathaniel Clyne"
:event/player1 "Davide Santon"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2618593"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Morgan Schneiderlin"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2618595"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Morgan Schneiderlin"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_2618599"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_3443"}

{:event/type "corner"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Morgan Schneiderlin"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_2618599"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_3443"}

{:event/type "card"
:event/elapsed 87
:event/card_type "y"
:event/subtype "verbal_abuse"
:event/player1 "Gaston Ramirez"
:event/sortorder 7
:event/team "away"
:event/event_type "card"
:event/id "event_2618605"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_3443"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Rickie Lambert"
:event/subtype "trip"
:event/player1 "Mapou Yanga-Mbiwa"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2618614"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3443"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "direct_freekick"
:event/player1 "Morgan Schneiderlin"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2618618"
:event/minute 91
:event/match_id "match_3443"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Mathieu Debuchy"
:event/player1 "Gaston Ramirez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2618631"
:event/minute 92
:event/match_id "match_3443"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Nathaniel Clyne"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2618643"
:event/minute 94
:event/match_id "match_3443"}

{:event/type "shotoff"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Adam Lallana"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2618645"
:event/minute 94
:event/match_id "match_3443"}


]

