
;;# data
[
{:match/id "match_22082"
:match/league "Spain LIGA BBVA"
:match/hometeam "Real Sporting de Gijón"
:match/awayteam "Athletic Club de Bilbao"
:match/score "0:1"
:match/hometeam_goals "0"
:match/awayteam_goals "0"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Carlos Gurpegi"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_993792"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_22082"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Xabier Aranburu Castillo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_993812"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_22082"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Pablo Orbaiz"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_993818"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_22082"}

{:event/type "corner"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Pablo Orbaiz"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_993818"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_22082"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player1 "Miguel Angel de las Cuevas"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_993836"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_22082"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Alberto Rivera"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_993837"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_22082"}

{:event/type "shotoff"
:event/elapsed 13
:event/subtype "distance"
:event/player1 "Gaizka Toquero"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_993846"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_22082"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Pablo Orbaiz"
:event/player1 "David Barral"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_993867"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_22082"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player1 "Luis Moran"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_993875"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_22082"}

{:event/type "shotoff"
:event/elapsed 22
:event/subtype "shot"
:event/player1 "Igor Gabilondo"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_993900"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_22082"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Diego Castro"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_993915"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_22082"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player1 "Javier Martinez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_993919"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_22082"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Jose Angel"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_993922"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_22082"}

{:event/type "shotoff"
:event/elapsed 32
:event/subtype "distance"
:event/player1 "Luis Moran"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_993924"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_22082"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Luis Moran"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_993926"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_22082"}

{:event/type "corner"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Luis Moran"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_993926"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_22082"}

{:event/type "shoton"
:event/elapsed 32
:event/subtype "blocked_shot"
:event/player1 "Miguel Angel de las Cuevas"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_993927"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_22082"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Igor Gabilondo"
:event/player1 "Diego Castro"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_993928"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_22082"}

{:event/type "shotoff"
:event/elapsed 34
:event/subtype "distance"
:event/player1 "Miguel Angel de las Cuevas"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_993930"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_22082"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Roberto Canella"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_993931"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_22082"}

{:event/type "shotoff"
:event/elapsed 36
:event/subtype "shot"
:event/player1 "Diego Castro"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_993932"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_22082"}

{:event/type "shoton"
:event/elapsed 38
:event/subtype "distance"
:event/player1 "Javier Martinez"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_993938"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_22082"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/sortorder 2
:event/team "away"
:event/event_type "throwin"
:event/id "event_993939"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_22082"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Pablo Orbaiz"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_993942"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_22082"}

{:event/type "corner"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Pablo Orbaiz"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_993942"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_22082"}

{:event/type "shotoff"
:event/elapsed 39
:event/subtype "header"
:event/player1 "Fernando Llorente"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_993943"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_22082"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Xabier Aranburu Castillo"
:event/player1 "David Barral"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_993945"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_22082"}

{:event/type "shotoff"
:event/elapsed 41
:event/subtype "shot"
:event/player1 "Markel Susaeta"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_993948"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_22082"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Markel Susaeta"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_993950"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_22082"}

{:event/type "shotoff"
:event/elapsed 43
:event/subtype "deflected"
:event/player1 "Miguel Angel de las Cuevas"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_993956"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_22082"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Luis Moran"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_993957"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_22082"}

{:event/type "corner"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Luis Moran"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_993957"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_22082"}

{:event/type "shoton"
:event/elapsed 43
:event/subtype "distance"
:event/player1 "Jose Angel"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_993959"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_22082"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_993962"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_22082"}

{:event/type "shotoff"
:event/elapsed 44
:event/subtype "deflected"
:event/player1 "Javier Martinez"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_993963"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_22082"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Igor Gabilondo"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_993964"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_22082"}

{:event/type "corner"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Igor Gabilondo"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_993964"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_22082"}

{:event/type "shotoff"
:event/elapsed 45
:event/subtype "header"
:event/player1 "Javier Martinez"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_993966"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_22082"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player1 "Diego Camacho"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_993970"
:event/minute 46
:event/match_id "match_22082"}

{:event/type "card"
:event/elapsed_plus 1
:event/elapsed 45
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Diego Camacho"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_993971"
:event/minute 46
:event/match_id "match_22082"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "blocked_shot"
:event/player1 "Markel Susaeta"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_993972"
:event/minute 46
:event/match_id "match_22082"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Gaizka Toquero"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_993973"
:event/minute 46
:event/match_id "match_22082"}

{:event/type "foulcommit"
:event/elapsed 47
:event/player2 "Roberto Canella"
:event/player1 "Fernando Llorente"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_994006"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_22082"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Alberto Rivera"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_994009"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_22082"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Luis Moran"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_994011"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_22082"}

{:event/type "corner"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Luis Moran"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_994011"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_22082"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Roberto Canella"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_994012"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_22082"}

{:event/type "shotoff"
:event/elapsed 49
:event/subtype "shot"
:event/player1 "Alberto Botia"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_994013"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_22082"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Gaizka Toquero"
:event/sortorder 5
:event/team "away"
:event/event_type "cross"
:event/id "event_994017"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_22082"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Diego Camacho"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_994021"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_22082"}

{:event/type "shoton"
:event/elapsed 51
:event/subtype "shot"
:event/player1 "Jose Angel"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_994024"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_22082"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Xabier Aranburu Castillo"
:event/player1 "Luis Moran"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_994029"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_22082"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Roberto Canella"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_994036"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_22082"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Luis Moran"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_994038"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_22082"}

{:event/type "corner"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Luis Moran"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_994038"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_22082"}

{:event/type "shoton"
:event/elapsed 54
:event/subtype "distance"
:event/player1 "Gaizka Toquero"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_994039"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_22082"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Igor Gabilondo"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_994041"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_22082"}

{:event/type "shotoff"
:event/elapsed 54
:event/subtype "header"
:event/player1 "Gaizka Toquero"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_994043"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_22082"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Gaizka Toquero"
:event/player1 "Jose Angel"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_994047"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_22082"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Igor Gabilondo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_994055"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_22082"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Gaizka Toquero"
:event/subtype "penalty"
:event/player1 "Jose Angel"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_994059"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_22082"}

{:event/type "card"
:event/elapsed 58
:event/card_type "y"
:event/subtype "pushing"
:event/player1 "Jose Angel"
:event/sortorder 3
:event/team "home"
:event/event_type "card"
:event/id "event_994061"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_22082"}

{:event/type "goal"
:event/elapsed 59
:event/subtype "saved_back_into_play"
:event/player1 "Igor Gabilondo"
:event/sortorder 0
:event/team "away"
:event/id "event_994064"
:event/event_type "goal"
:event/goal_type "npm"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_22082"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Roberto Canella"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_994072"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_22082"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Carlos Gurpegi"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_994081"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_22082"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Igor Gabilondo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_994096"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_22082"}

{:event/type "shoton"
:event/elapsed 67
:event/subtype "header"
:event/player1 "Fernando Llorente"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_994097"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_22082"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Diego Castro"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_994099"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_22082"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Javier Martinez"
:event/subtype "serious_foul"
:event/player1 "Alberto Rivera"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_994106"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_22082"}

{:event/type "card"
:event/elapsed 70
:event/card_type "y"
:event/subtype "pushing"
:event/player1 "Alberto Rivera"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_994107"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_22082"}

{:event/type "shotoff"
:event/elapsed 71
:event/subtype "volley"
:event/player1 "Javier Martinez"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_994112"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_22082"}

{:event/type "shotoff"
:event/elapsed 72
:event/subtype "distance"
:event/player1 "Diego Camacho"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_994117"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_22082"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Gaizka Toquero"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_994126"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_22082"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Alberto Rivera"
:event/subtype "shirt_pull"
:event/player1 "Javier Martinez"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_994128"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_22082"}

{:event/type "card"
:event/elapsed 74
:event/card_type "y"
:event/subtype "emergency_brake"
:event/player1 "Javier Martinez"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_994129"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_22082"}

{:event/type "foulcommit"
:event/elapsed 76
:event/player2 "David Barral"
:event/player1 "Fernando Amorebieta"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_994137"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_22082"}

{:event/type "foulcommit"
:event/elapsed 78
:event/player2 "Xabier Aranburu Castillo"
:event/player1 "Miguel Angel de las Cuevas"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_994138"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_22082"}

{:event/type "foulcommit"
:event/elapsed 79
:event/player2 "Fernando Llorente"
:event/player1 "Alberto Botia"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_994139"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_22082"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Pablo Orbaiz"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_994141"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_22082"}

{:event/type "corner"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Pablo Orbaiz"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_994141"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_22082"}

{:event/type "shoton"
:event/elapsed 83
:event/subtype "distance"
:event/player1 "Fernando Llorente"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_994144"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_22082"}

{:event/type "foulcommit"
:event/elapsed 83
:event/player2 "Ivan Hernandez"
:event/player1 "Markel Susaeta"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_994145"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_22082"}

{:event/type "shoton"
:event/elapsed 85
:event/subtype "shot"
:event/player1 "Carmelo Gonzalez"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_994149"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_22082"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "David Lopez"
:event/player1 "Ivan Hernandez"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_994150"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_22082"}

{:event/type "card"
:event/elapsed 85
:event/card_type "y"
:event/player1 "Ivan Hernandez"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_994151"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_22082"}

{:event/type "shoton"
:event/elapsed 86
:event/subtype "blocked_shot"
:event/player1 "David Lopez"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_994152"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_22082"}

{:event/type "foulcommit"
:event/elapsed 87
:event/player2 "Juan Pablo"
:event/player1 "Markel Susaeta"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_994153"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_22082"}

{:event/type "card"
:event/elapsed 87
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Markel Susaeta"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_994154"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_22082"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player1 "Fernando Amorebieta"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_994155"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_22082"}

{:event/type "card"
:event/elapsed 88
:event/card_type "y"
:event/player1 "Fernando Amorebieta"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_994156"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_22082"}

{:event/type "shoton"
:event/elapsed 90
:event/subtype "distance"
:event/player1 "Diego Camacho"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_994160"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_22082"}

{:event/type "corner"
:event/elapsed 90
:event/subtype "short"
:event/player1 "Diego Castro"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_994161"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_22082"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Pablo Orbaiz"
:event/player1 "David Barral"
:event/sortorder 5
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_994162"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_22082"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "David Barral"
:event/sortorder 6
:event/team "home"
:event/event_type "card"
:event/id "event_994163"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_22082"}

{:event/type "shotoff"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Fernando Llorente"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_994170"
:event/minute 93
:event/match_id "match_22082"}


]

