
;;# data
[
{:match/id "match_8489"
:match/league "Germany 1. Bundesliga"
:match/hometeam "1. FC Köln"
:match/awayteam "Eintracht Frankfurt"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 15
:event/card_type "y"
:event/player1 "Miso Brecko"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1323260"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_8489"}

{:event/type "card"
:event/elapsed 25
:event/card_type "y"
:event/player1 "Fabrice Ehret"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1323406"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_8489"}

{:event/type "goal"
:event/elapsed 56
:event/player1 "Christian Clemens"
:event/sortorder 0
:event/team "home"
:event/id "event_1324098"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_8489"}

{:event/type "card"
:event/elapsed 60
:event/card_type "y"
:event/player1 "Giorgos Tzavellas"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1324099"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_8489"}

{:event/type "card"
:event/elapsed 66
:event/card_type "y"
:event/player1 "Theofanis Gekas"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1324150"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_8489"}

{:event/type "card"
:event/elapsed 66
:event/card_type "y"
:event/player1 "Geromel"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1324151"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_8489"}

{:event/type "card"
:event/elapsed 78
:event/card_type "y"
:event/player1 "Marco Russ"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1324289"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_8489"}

{:event/type "card"
:event/elapsed 84
:event/card_type "y"
:event/player1 "Mate Jajalo"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1324602"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_8489"}

{:event/type "card"
:event/elapsed 89
:event/card_type "y"
:event/player1 "Christian Clemens"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1324517"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_8489"}


]

