
;;# data
[
{:match/id "match_5679"
:match/league "France Ligue 1"
:match/hometeam "AC Arles-Avignon"
:match/awayteam "Montpellier Hérault SC"
:match/score "0:0"
:match/hometeam_goals "0"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 41
:event/card_type "y"
:event/player1 "Dianbobo Balde"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1406804"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_5679"}

{:event/type "card"
:event/elapsed 50
:event/card_type "y"
:event/player1 "Gael Germany"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1407113"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_5679"}

{:event/type "card"
:event/elapsed 74
:event/card_type "y"
:event/player1 "Olivier Giroud"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1407198"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_5679"}


]

