
;;# data
[
{:match/id "match_9101"
:match/league "Germany 1. Bundesliga"
:match/hometeam "SC Freiburg"
:match/awayteam "SpVgg Greuther Fürth"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 7
:event/card_type "y"
:event/player1 "Thomas Kleine"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2512809"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_9101"}

{:event/type "goal"
:event/elapsed 15
:event/player1 "Daniel Caligiuri"
:event/sortorder 0
:event/team "home"
:event/id "event_2512814"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_9101"}

{:event/type "card"
:event/elapsed 33
:event/card_type "y"
:event/player1 "Gerald Asamoah"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2512910"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_9101"}

{:event/type "card"
:event/elapsed 47
:event/card_type "y"
:event/player1 "Oliver Sorg"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2513358"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_9101"}

{:event/type "card"
:event/elapsed 59
:event/card_type "y"
:event/player1 "Abdul Rahman Baba"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2513570"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_9101"}

{:event/type "card"
:event/elapsed 78
:event/card_type "y"
:event/player1 "Bernd Nehrig"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2513673"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_9101"}

{:event/type "card"
:event/elapsed 84
:event/card_type "y"
:event/player1 "Christian Guenter"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2513840"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_9101"}


]

