
;;# data
[
{:match/id "match_11932"
:match/league "Italy Serie A"
:match/hometeam "Milan"
:match/awayteam "Parma"
:match/score "1:2"
:match/hometeam_goals "2"
:match/awayteam_goals "1"}

{:event/type "goal"
:event/elapsed 39
:event/player1 "Gabriel Paletta"
:event/sortorder 0
:event/team "away"
:event/id "event_2603841"
:event/event_type "goal"
:event/goal_type "o"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_11932"}

{:event/type "card"
:event/elapsed 66
:event/card_type "y"
:event/player1 "Marco Marchionni"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2603901"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_11932"}

{:event/type "card"
:event/elapsed 73
:event/card_type "y"
:event/player1 "Cristian Zapata"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2603911"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_11932"}

{:event/type "goal"
:event/elapsed 78
:event/player1 "Mario Balotelli"
:event/sortorder 0
:event/team "home"
:event/id "event_2603924"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_11932"}

{:event/type "goal"
:event/elapsed 90
:event/player1 "Nicola Sansone"
:event/sortorder 0
:event/team "away"
:event/id "event_2603934"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_11932"}


]

