
;;# data
[
{:match/id "match_7688"
:match/league "France Ligue 1"
:match/hometeam "Toulouse FC"
:match/awayteam "SM Caen"
:match/score "1:1"
:match/hometeam_goals "2"
:match/awayteam_goals "0"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "Adrien Regattin"
:event/subtype "pushing"
:event/player1 "Alexandre Raineau"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5450981"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Adrien Regattin"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5451049"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Martin Braithwaite"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5451053"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Francois Moubandje"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_5451063"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Herve Bazile"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5451077"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed 8
:event/player2 "Tongo Hamed Doumbia"
:event/subtype "trip"
:event/player1 "Ismael Diomande"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5451097"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Etienne Didot"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5451106"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Etienne Didot"
:event/player1 "Ismael Diomande"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5451135"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Etienne Didot"
:event/subtype "trip"
:event/player1 "Alexandre Raineau"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5451142"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Andy Delort"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5451168"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Alexandre Raineau"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5451181"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Herve Bazile"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5451188"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Alexis Blin"
:event/subtype "pushing"
:event/player1 "Jonathan Delaplace"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5451192"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Sylvio Ronny Rodelin"
:event/subtype "trip"
:event/player1 "Marcel Tisserand"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5451252"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Herve Bazile"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5451313"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Julien Feret"
:event/subtype "serious_foul"
:event/player1 "Tongo Hamed Doumbia"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5451332"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Julien Feret"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5451350"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_7688"}

{:event/type "corner"
:event/elapsed 19
:event/subtype "cross_right"
:event/player1 "Julien Feret"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_5451365"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_7688"}

{:event/type "shotoff"
:event/elapsed 19
:event/subtype "header"
:event/player1 "Sylvio Ronny Rodelin"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5451374"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Dennis Appiah"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5451419"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_7688"}

{:event/type "shotoff"
:event/elapsed 21
:event/subtype "volley"
:event/player1 "Herve Bazile"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5451424"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Etienne Didot"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5451437"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_7688"}

{:event/type "shotoff"
:event/elapsed 22
:event/subtype "header"
:event/player1 "Wissam Ben Yedder"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5451445"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Sylvio Ronny Rodelin"
:event/subtype "dangerous_play"
:event/player1 "Alexis Blin"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5451457"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Adrien Regattin"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5451489"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Dennis Appiah"
:event/player1 "Martin Braithwaite"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5451503"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_7688"}

{:event/type "corner"
:event/elapsed 26
:event/subtype "cross_left"
:event/player1 "Herve Bazile"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_5451532"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed 27
:event/subtype "hands"
:event/player1 "Tongo Hamed Doumbia"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5451548"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Alexandre Raineau"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5451593"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_7688"}

{:event/type "goal"
:event/elapsed 30
:event/player1 "Sylvio Ronny Rodelin"
:event/sortorder 5
:event/team "away"
:event/id "event_5451605"
:event/event_type "goal"
:event/goal_type "o"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_7688"}

{:event/type "shotoff"
:event/elapsed 32
:event/subtype "distance"
:event/player1 "Julien Feret"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5451630"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Julien Feret"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5451643"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_7688"}

{:event/type "corner"
:event/elapsed 34
:event/subtype "cross_left"
:event/player1 "Herve Bazile"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_5451650"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Jonathan Delaplace"
:event/subtype "trip"
:event/player1 "Etienne Didot"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5451675"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Martin Braithwaite"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5451706"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Andy Delort"
:event/subtype "dangerous_play"
:event/player1 "Marcel Tisserand"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5451712"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Wissam Ben Yedder"
:event/subtype "trip"
:event/player1 "Alexandre Raineau"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5451722"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Herve Bazile"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5451739"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_7688"}

{:event/type "corner"
:event/elapsed 40
:event/subtype "cross_left"
:event/player1 "Herve Bazile"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_5451744"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Martin Braithwaite"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5451759"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Issa Diop"
:event/player1 "Andy Delort"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5451767"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Steeve Yago"
:event/subtype "trip"
:event/player1 "Ismael Diomande"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5451782"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_7688"}

{:event/type "corner"
:event/elapsed 43
:event/subtype "cross_right"
:event/player1 "Etienne Didot"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_5451791"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_7688"}

{:event/type "shoton"
:event/elapsed 43
:event/subtype "blocked_shot"
:event/player1 "Wissam Ben Yedder"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_5451796"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_7688"}

{:event/type "shoton"
:event/elapsed 43
:event/subtype "shot"
:event/player1 "Martin Braithwaite"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_5451799"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Julien Feret"
:event/subtype "trip"
:event/player1 "Adrien Regattin"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5451806"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed 47
:event/player2 "Steeve Yago"
:event/subtype "trip"
:event/player1 "Herve Bazile"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5452070"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed 47
:event/player2 "Andy Delort"
:event/subtype "pull"
:event/player1 "Issa Diop"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5452081"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_7688"}

{:event/type "card"
:event/elapsed 47
:event/card_type "y"
:event/player1 "Issa Diop"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_5452082"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Julien Feret"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5452092"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_7688"}

{:event/type "corner"
:event/elapsed 48
:event/subtype "cross_left"
:event/player1 "Julien Feret"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_5452098"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_7688"}

{:event/type "shoton"
:event/elapsed 51
:event/subtype "shot"
:event/player1 "Andy Delort"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_5452179"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Adrien Regattin"
:event/subtype "trip"
:event/player1 "Julien Feret"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5452188"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Alexandre Raineau"
:event/subtype "pushing"
:event/player1 "Martin Braithwaite"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5452197"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Alexis Blin"
:event/subtype "pushing"
:event/player1 "Ismael Diomande"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5452212"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Dennis Appiah"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5452253"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed 59
:event/player2 "Francois Moubandje"
:event/subtype "trip"
:event/player1 "unknown"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5452330"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Etienne Didot"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5452369"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_7688"}

{:event/type "corner"
:event/elapsed 61
:event/subtype "cross_right"
:event/player1 "Etienne Didot"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_5452387"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_7688"}

{:event/type "shotoff"
:event/elapsed 62
:event/subtype "header"
:event/player1 "Tongo Hamed Doumbia"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5452389"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5452430"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_7688"}

{:event/type "shoton"
:event/elapsed 63
:event/subtype "blocked_shot"
:event/player1 "Sylvio Ronny Rodelin"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_5452436"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_7688"}

{:event/type "shotoff"
:event/elapsed 64
:event/subtype "shot"
:event/player1 "Andy Delort"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5452440"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Dennis Appiah"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5452451"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Adrien Regattin"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5452467"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Francois Moubandje"
:event/subtype "pushing"
:event/player1 "Julien Feret"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5452527"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Alexandre Raineau"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5452558"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Martin Braithwaite"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5452593"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_7688"}

{:event/type "corner"
:event/elapsed 72
:event/subtype "cross_left"
:event/player1 "Etienne Didot"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_5452600"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed 74
:event/player2 "Wissam Ben Yedder"
:event/subtype "trip"
:event/player1 "Nicolas Seube"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5452646"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_7688"}

{:event/type "card"
:event/elapsed 74
:event/card_type "y"
:event/player1 "Nicolas Seube"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_5452649"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_7688"}

{:event/type "shoton"
:event/elapsed 75
:event/subtype "blocked_shot"
:event/player1 "Wissam Ben Yedder"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_5452660"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_7688"}

{:event/type "corner"
:event/elapsed 75
:event/subtype "cross_left"
:event/player1 "Etienne Didot"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_5452667"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed 76
:event/player2 "Alexandre Raineau"
:event/subtype "dangerous_play"
:event/player1 "Pantxi Sirieix"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5452677"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed 76
:event/player2 "Steeve Yago"
:event/subtype "pushing"
:event/player1 "Andy Delort"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5452691"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_7688"}

{:event/type "shoton"
:event/elapsed 80
:event/subtype "blocked_shot"
:event/player1 "Alexis Blin"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5452765"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Alexis Blin"
:event/subtype "dangerous_play"
:event/player1 "Julien Feret"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5452780"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "unknown"
:event/subtype "pull"
:event/player1 "Francois Moubandje"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5452814"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Sylvio Ronny Rodelin"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5452822"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Issa Diop"
:event/subtype "pull"
:event/player1 "Alaeddine Yahia"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5452824"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Pantxi Sirieix"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5452832"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_7688"}

{:event/type "goal"
:event/elapsed 85
:event/player2 "Pantxi Sirieix"
:event/subtype "volley"
:event/player1 "Martin Braithwaite"
:event/sortorder 1
:event/team "home"
:event/id "event_5452834"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/sortorder 1
:event/team "home"
:event/event_type "throwin"
:event/id "event_5452863"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Sylvio Ronny Rodelin"
:event/subtype "pull"
:event/player1 "Steeve Yago"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5452868"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Dennis Appiah"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5452884"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_7688"}

{:event/type "shotoff"
:event/elapsed 90
:event/subtype "distance"
:event/player1 "Wissam Ben Yedder"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5452908"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Alexis Blin"
:event/subtype "trip"
:event/player1 "unknown"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5452926"
:event/minute 91
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Marcel Tisserand"
:event/subtype "dangerous_play"
:event/player1 "unknown"
:event/sortorder 7
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5452953"
:event/minute 92
:event/match_id "match_7688"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Francois Moubandje"
:event/sortorder 8
:event/team "home"
:event/event_type "cross"
:event/id "event_5452984"
:event/minute 94
:event/match_id "match_7688"}

{:event/type "foulcommit"
:event/elapsed_plus 4
:event/elapsed 90
:event/player2 "Alexis Blin"
:event/subtype "trip"
:event/player1 "unknown"
:event/sortorder 10
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5452993"
:event/minute 94
:event/match_id "match_7688"}


]

