
;;# data
[
{:match/id "match_9059"
:match/league "Germany 1. Bundesliga"
:match/hometeam "Fortuna Düsseldorf"
:match/awayteam "TSG 1899 Hoffenheim"
:match/score "1:1"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "goal"
:event/elapsed 4
:event/player1 "Robbie Kruse"
:event/sortorder 0
:event/team "home"
:event/id "event_2472787"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_9059"}

{:event/type "card"
:event/elapsed 33
:event/card_type "y"
:event/player1 "Roberto Firmino"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2473018"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_9059"}

{:event/type "goal"
:event/elapsed 40
:event/player1 "Joselu"
:event/sortorder 0
:event/team "away"
:event/id "event_2473017"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_9059"}

{:event/type "card"
:event/elapsed 47
:event/card_type "y"
:event/player1 "Marvin Compper"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2473519"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_9059"}

{:event/type "card"
:event/elapsed 50
:event/card_type "y"
:event/player1 "Marvin Compper"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2473520"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_9059"}

{:event/type "card"
:event/elapsed 77
:event/card_type "y"
:event/player1 "Tobias Levels"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2473764"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_9059"}


]

