
;;# data
[
{:match/id "match_4523"
:match/league "England Premier League"
:match/hometeam "Chelsea"
:match/awayteam "West Bromwich Albion"
:match/score "1:3"
:match/hometeam_goals "2"
:match/awayteam_goals "2"}

{:event/type "shotoff"
:event/elapsed 2
:event/subtype "shot"
:event/player1 "Diego Costa"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5177044"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Darren Fletcher"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5177069"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_4523"}

{:event/type "shotoff"
:event/elapsed 4
:event/subtype "header"
:event/player1 "James McClean"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5177070"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_4523"}

{:event/type "shotoff"
:event/elapsed 8
:event/subtype "distance"
:event/player1 "Willian"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5177109"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_4523"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Chris Brunt"
:event/subtype "pushing"
:event/player1 "John Obi Mikel"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5177119"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Darren Fletcher"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5177125"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_4523"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Oscar"
:event/subtype "trip"
:event/player1 "Gareth McAuley"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5177147"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "James McClean"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5177162"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed 13
:event/subtype "cross"
:event/player1 "Craig Gardner"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5177167"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_4523"}

{:event/type "shotoff"
:event/elapsed 13
:event/subtype "deflected"
:event/player1 "Darren Fletcher"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5177169"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_4523"}

{:event/type "corner"
:event/elapsed 14
:event/subtype "cross_right"
:event/player1 "Chris Brunt"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_5177175"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_4523"}

{:event/type "shotoff"
:event/elapsed 14
:event/subtype "distance"
:event/player1 "Craig Gardner"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5177182"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_4523"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Darren Fletcher"
:event/subtype "trip"
:event/player1 "Willian"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5177193"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Craig Gardner"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5177205"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_4523"}

{:event/type "shoton"
:event/elapsed 16
:event/subtype "header"
:event/player1 "Craig Dawson"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_5177210"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_4523"}

{:event/type "corner"
:event/elapsed 16
:event/subtype "cross_right"
:event/player1 "Chris Brunt"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_5177215"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Jose Salomon Rondon"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5177219"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_4523"}

{:event/type "shoton"
:event/elapsed 17
:event/subtype "blocked_shot"
:event/player1 "Willian"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_5177224"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Branislav Ivanovic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5177269"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_4523"}

{:event/type "goal"
:event/elapsed 20
:event/player2 "Branislav Ivanovic"
:event/subtype "tap_in"
:event/player1 "Cesar Azpilicueta"
:event/sortorder 1
:event/team "home"
:event/id "event_5177270"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_4523"}

{:event/type "shotoff"
:event/elapsed 23
:event/subtype "bad shot"
:event/player1 "Oscar"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5177307"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_4523"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Craig Gardner"
:event/subtype "trip"
:event/player1 "John Obi Mikel"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5177326"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5177345"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_4523"}

{:event/type "shoton"
:event/elapsed 25
:event/subtype "header"
:event/player1 "James McClean"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_5177346"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_4523"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Willian"
:event/subtype "trip"
:event/player1 "Claudio Yacob"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5177355"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_4523"}

{:event/type "card"
:event/elapsed 25
:event/card_type "y"
:event/subtype "emergency_brake"
:event/player1 "Claudio Yacob"
:event/sortorder 6
:event/team "away"
:event/event_type "card"
:event/id "event_5177376"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_4523"}

{:event/type "corner"
:event/elapsed 29
:event/subtype "cross_right"
:event/player1 "Willian"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_5177422"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Cesc Fabregas"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5177431"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_4523"}

{:event/type "shotoff"
:event/elapsed 32
:event/subtype "shot"
:event/player1 "Diego Costa"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5177472"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_4523"}

{:event/type "goal"
:event/elapsed 33
:event/player2 "Darren Fletcher"
:event/subtype "distance"
:event/player1 "Craig Gardner"
:event/sortorder 1
:event/team "away"
:event/id "event_5177490"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_4523"}

{:event/type "shoton"
:event/elapsed 36
:event/subtype "shot"
:event/player1 "Diego Costa"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5177519"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_4523"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Oscar"
:event/subtype "pushing"
:event/player1 "Claudio Yacob"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5177539"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_4523"}

{:event/type "shoton"
:event/elapsed 38
:event/subtype "distance"
:event/player1 "Willian"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_5177544"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_4523"}

{:event/type "shotoff"
:event/elapsed 38
:event/subtype "deflected"
:event/player1 "Oscar"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5177546"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_4523"}

{:event/type "corner"
:event/elapsed 38
:event/subtype "cross_right"
:event/player1 "Willian"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_5177553"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5177574"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_4523"}

{:event/type "shotoff"
:event/elapsed 40
:event/subtype "distance"
:event/player1 "Jose Salomon Rondon"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5177591"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Cesc Fabregas"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5177615"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_4523"}

{:event/type "corner"
:event/elapsed 42
:event/subtype "cross_right"
:event/player1 "Willian"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_5177625"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "James McClean"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5177636"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Branislav Ivanovic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5177821"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_4523"}

{:event/type "corner"
:event/elapsed 47
:event/subtype "cross_right"
:event/player1 "Willian"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_5177829"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_4523"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 45
:event/player2 "Darren Fletcher"
:event/subtype "obstruction"
:event/player1 "John Obi Mikel"
:event/sortorder 5
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5177707"
:event/minute 47
:event/match_id "match_4523"}

{:event/type "corner"
:event/elapsed 48
:event/subtype "cross_right"
:event/player1 "Willian"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5177837"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_4523"}

{:event/type "shoton"
:event/elapsed 48
:event/subtype "header"
:event/player1 "Diego Costa"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_5177842"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_4523"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Boaz Myhill"
:event/player1 "Oscar"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5177841"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Craig Gardner"
:event/sortorder 6
:event/team "away"
:event/event_type "cross"
:event/id "event_5177713"
:event/minute 48
:event/match_id "match_4523"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Craig Gardner"
:event/subtype "serious_foul"
:event/player1 "Diego Costa"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5177848"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_4523"}

{:event/type "card"
:event/elapsed 49
:event/card_type "y"
:event/player1 "Diego Costa"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_5177852"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5177861"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Craig Dawson"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5177869"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_4523"}

{:event/type "corner"
:event/elapsed 51
:event/subtype "cross_right"
:event/player1 "Chris Brunt"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_5177875"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_4523"}

{:event/type "shoton"
:event/elapsed 52
:event/subtype "header"
:event/player1 "James McClean"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_5177884"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_4523"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Diego Costa"
:event/subtype "trip"
:event/player1 "Gareth McAuley"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5177892"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_4523"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Boaz Myhill"
:event/player1 "Diego Costa"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5177973"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Jonny Evans"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5177912"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_4523"}

{:event/type "shoton"
:event/elapsed 56
:event/subtype "deflected"
:event/player1 "Kenedy"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_5177922"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_4523"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Diego Costa"
:event/subtype "trip"
:event/player1 "Claudio Yacob"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5177937"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_4523"}

{:event/type "shotoff"
:event/elapsed 59
:event/subtype "direct_freekick"
:event/player1 "Willian"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5177947"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5177986"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_4523"}

{:event/type "corner"
:event/elapsed 63
:event/subtype "short_left"
:event/player1 "Willian"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5178009"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "John Obi Mikel"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5178011"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5178038"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_4523"}

{:event/type "shotoff"
:event/elapsed 64
:event/subtype "deflected"
:event/player1 "Diego Costa"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5178042"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_4523"}

{:event/type "corner"
:event/elapsed 64
:event/subtype "cross_left"
:event/player1 "Willian"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_5178045"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_4523"}

{:event/type "shoton"
:event/elapsed 66
:event/subtype "blocked_shot"
:event/player1 "Saido Berahino"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_5178070"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_4523"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Craig Dawson"
:event/subtype "trip"
:event/player1 "Kenedy"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5178085"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_4523"}

{:event/type "card"
:event/elapsed 68
:event/card_type "y"
:event/subtype "stall_time"
:event/player1 "Boaz Myhill"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_5178117"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_4523"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Craig Gardner"
:event/player1 "Branislav Ivanovic"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5178114"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Chris Brunt"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5178123"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Darren Fletcher"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_5178128"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_4523"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Kurt Zouma"
:event/subtype "dangerous_play"
:event/player1 "Saido Berahino"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5178130"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_4523"}

{:event/type "card"
:event/elapsed 70
:event/card_type "y"
:event/subtype "violence"
:event/player1 "Thibaut Courtois"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_5178135"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_4523"}

{:event/type "card"
:event/elapsed 70
:event/card_type "y"
:event/subtype "violence"
:event/player1 "James McClean"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_5178136"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Diego Costa"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5178161"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Cesc Fabregas"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5178179"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_4523"}

{:event/type "shotoff"
:event/elapsed 72
:event/subtype "deflected"
:event/player1 "Saido Berahino"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5178187"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_4523"}

{:event/type "corner"
:event/elapsed 73
:event/subtype "cross_left"
:event/player1 "Craig Gardner"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_5178201"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_4523"}

{:event/type "shotoff"
:event/elapsed 73
:event/subtype "deflected"
:event/player1 "James McClean"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5178207"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_4523"}

{:event/type "goal"
:event/elapsed 73
:event/player1 "Gareth McAuley"
:event/sortorder 4
:event/team "away"
:event/id "event_5178216"
:event/event_type "goal"
:event/goal_type "o"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_4523"}

{:event/type "shoton"
:event/elapsed 76
:event/subtype "shot"
:event/player1 "Diego Costa"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_5178262"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_4523"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Diego Costa"
:event/subtype "pushing"
:event/player1 "Gareth McAuley"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5178280"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_4523"}

{:event/type "shotoff"
:event/elapsed 78
:event/subtype "distance"
:event/player1 "Kurt Zouma"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5178300"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Craig Dawson"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5178319"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_4523"}

{:event/type "shoton"
:event/elapsed 80
:event/subtype "distance"
:event/player1 "Saido Berahino"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_5178323"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_4523"}

{:event/type "shotoff"
:event/elapsed 81
:event/subtype "distance"
:event/player1 "Kenedy"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5178339"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_4523"}

{:event/type "foulcommit"
:event/elapsed 83
:event/player2 "Kurt Zouma"
:event/subtype "pushing"
:event/player1 "Saido Berahino"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5178366"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "James McClean"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5178386"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Stephane Sessegnon"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_5178398"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_4523"}

{:event/type "corner"
:event/elapsed 85
:event/subtype "cross_left"
:event/player1 "Craig Gardner"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_5178408"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_4523"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "James McClean"
:event/subtype "obstruction"
:event/player1 "Cesar Azpilicueta"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5178415"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_4523"}

{:event/type "card"
:event/elapsed 85
:event/card_type "y"
:event/subtype "emergency_brake"
:event/player1 "Cesar Azpilicueta"
:event/sortorder 3
:event/team "home"
:event/event_type "card"
:event/id "event_5178418"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Darren Fletcher"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_5178421"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Craig Gardner"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5178424"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_4523"}

{:event/type "goal"
:event/elapsed 86
:event/subtype "shot"
:event/player1 "James McClean"
:event/sortorder 4
:event/team "away"
:event/id "event_5178422"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_4523"}

{:event/type "corner"
:event/elapsed 88
:event/subtype "cross_left"
:event/player1 "Stephane Sessegnon"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_5178458"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_4523"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player2 "Darren Fletcher"
:event/player1 "Oscar"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5178485"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_4523"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Jonny Evans"
:event/subtype "pushing"
:event/player1 "Oscar"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5178500"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_4523"}

{:event/type "corner"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "short_right"
:event/player1 "Chris Brunt"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_5178519"
:event/minute 91
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Stephane Sessegnon"
:event/sortorder 5
:event/team "away"
:event/event_type "cross"
:event/id "event_5178521"
:event/minute 91
:event/match_id "match_4523"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 9
:event/team "home"
:event/event_type "cross"
:event/id "event_5178545"
:event/minute 93
:event/match_id "match_4523"}

{:event/type "foulcommit"
:event/elapsed_plus 5
:event/elapsed 90
:event/player2 "Darren Fletcher"
:event/subtype "from_behind"
:event/player1 "Willian"
:event/sortorder 11
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5178573"
:event/minute 95
:event/match_id "match_4523"}


]

