
;;# data
[
{:match/id "match_3023"
:match/league "England Premier League"
:match/hometeam "Tottenham Hotspur"
:match/awayteam "Wigan Athletic"
:match/score "3:1"
:match/hometeam_goals "3"
:match/awayteam_goals "1"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Gareth Bale"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1908741"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Kyle Walker"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1908745"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Benoit Assou-Ekotto"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1908770"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_3023"}

{:event/type "corner"
:event/elapsed 5
:event/subtype "short"
:event/player1 "Luka Modric"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1908776"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Luka Modric"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1908787"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_3023"}

{:event/type "corner"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Luka Modric"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1908787"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_3023"}

{:event/type "shoton"
:event/elapsed 6
:event/subtype "big chance header"
:event/player1 "Younes Kaboul"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1908788"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Scott Parker"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1908795"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_3023"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Jean Beausejour"
:event/subtype "pushing"
:event/player1 "Scott Parker"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1908800"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Gareth Bale"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1908818"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Gareth Bale"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1908820"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_3023"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Franco Di Santo"
:event/player1 "Benoit Assou-Ekotto"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1908825"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Ronnie Stam"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1908834"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Benoit Assou-Ekotto"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1908839"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Luka Modric"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1908842"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_3023"}

{:event/type "corner"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Luka Modric"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1908842"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_3023"}

{:event/type "shotoff"
:event/elapsed 11
:event/subtype "deflected"
:event/player1 "Niko Kranjcar"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1908849"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Rafael van der Vaart"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1908850"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_3023"}

{:event/type "corner"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Rafael van der Vaart"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1908850"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_3023"}

{:event/type "shotoff"
:event/elapsed 12
:event/subtype "header"
:event/player1 "Younes Kaboul"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1908851"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_3023"}

{:event/type "shotoff"
:event/elapsed 16
:event/subtype "shot"
:event/player1 "Luka Modric"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1908883"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_3023"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Ronnie Stam"
:event/player1 "Rafael van der Vaart"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1908898"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Kyle Walker"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1908904"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3023"}

{:event/type "shotoff"
:event/elapsed 18
:event/subtype "header"
:event/player1 "Emmanuel Adebayor"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1908905"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Benoit Assou-Ekotto"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1908927"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_3023"}

{:event/type "shoton"
:event/elapsed 21
:event/subtype "shot"
:event/player1 "Niko Kranjcar"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1908936"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Benoit Assou-Ekotto"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1908959"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_3023"}

{:event/type "shotoff"
:event/elapsed 23
:event/subtype "deflected"
:event/player1 "Niko Kranjcar"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1908966"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Rafael van der Vaart"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1908969"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_3023"}

{:event/type "corner"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Rafael van der Vaart"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1908969"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_3023"}

{:event/type "shoton"
:event/elapsed 24
:event/subtype "big chance header"
:event/player1 "Younes Kaboul"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1908971"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Benoit Assou-Ekotto"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1909001"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_3023"}

{:event/type "shoton"
:event/elapsed 26
:event/subtype "blocked_shot"
:event/player1 "Gareth Bale"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1909003"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Gareth Bale"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1909010"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Luka Modric"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1909021"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_3023"}

{:event/type "goal"
:event/elapsed 29
:event/player2 "Luka Modric"
:event/subtype "shot"
:event/player1 "Gareth Bale"
:event/sortorder 1
:event/team "home"
:event/id "event_1909022"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_3023"}

{:event/type "shotoff"
:event/elapsed 30
:event/subtype "bad shot"
:event/player1 "James McCarthy"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1909039"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_3023"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Luka Modric"
:event/player1 "Ben Watson"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1909059"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Gareth Bale"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1909074"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3023"}

{:event/type "foulcommit"
:event/elapsed 34
:event/player1 "Emmanuel Adebayor"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1909096"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_3023"}

{:event/type "goal"
:event/elapsed 34
:event/subtype "shot"
:event/player1 "Luka Modric"
:event/sortorder 2
:event/team "home"
:event/id "event_1909098"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_3023"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Jordi Gomez"
:event/player1 "Scott Parker"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1909152"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_3023"}

{:event/type "shoton"
:event/elapsed 39
:event/subtype "blocked_shot"
:event/player1 "Gareth Bale"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1909157"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_3023"}

{:event/type "shoton"
:event/elapsed 42
:event/subtype "distance"
:event/player1 "Jake Livermore"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1909194"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_3023"}

{:event/type "foulcommit"
:event/elapsed 46
:event/player2 "Luka Modric"
:event/player1 "James McCarthy"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1909312"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Gareth Bale"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1909330"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_3023"}

{:event/type "shotoff"
:event/elapsed 49
:event/subtype "header"
:event/player1 "Emmanuel Adebayor"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1909331"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Gareth Bale"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1909353"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_3023"}

{:event/type "shotoff"
:event/elapsed 52
:event/subtype "shot"
:event/player1 "Victor Moses"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1909361"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Victor Moses"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1909365"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Jean Beausejour"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1909380"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Ronnie Stam"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1909384"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_3023"}

{:event/type "shoton"
:event/elapsed 59
:event/subtype "distance"
:event/player1 "Jordi Gomez"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1909406"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_3023"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player2 "Niko Kranjcar"
:event/subtype "serious_foul"
:event/player1 "Maynor Figueroa"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1909417"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_3023"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Niko Kranjcar"
:event/subtype "serious_foul"
:event/player1 "Franco Di Santo"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1909431"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Jordi Gomez"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1909449"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Benoit Assou-Ekotto"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1909454"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_3023"}

{:event/type "goal"
:event/elapsed 64
:event/player2 "Benoit Assou-Ekotto"
:event/subtype "shot"
:event/player1 "Gareth Bale"
:event/sortorder 2
:event/team "home"
:event/id "event_1909456"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_3023"}

{:event/type "shoton"
:event/elapsed 65
:event/subtype "blocked_shot"
:event/player1 "James McCarthy"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1909475"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "James McArthur"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1909560"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_3023"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Scott Parker"
:event/player1 "Ben Watson"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1909605"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3023"}

{:event/type "foulcommit"
:event/elapsed 76
:event/player2 "James McCarthy"
:event/player1 "Luka Modric"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1909617"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Jean Beausejour"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1909628"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_3023"}

{:event/type "shoton"
:event/elapsed 77
:event/subtype "distance"
:event/player1 "Ben Watson"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1909633"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Jean Beausejour"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1909650"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_3023"}

{:event/type "shotoff"
:event/elapsed 79
:event/subtype "distance"
:event/player1 "Ronnie Stam"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1909653"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_3023"}

{:event/type "goal"
:event/elapsed 81
:event/player2 "Victor Moses"
:event/subtype "shot"
:event/player1 "James McArthur"
:event/sortorder 0
:event/team "away"
:event/id "event_1909670"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_3023"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Scott Parker"
:event/subtype "pushing"
:event/player1 "James McArthur"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1909682"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Ronnie Stam"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1909693"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_3023"}

{:event/type "shoton"
:event/elapsed 85
:event/subtype "blocked_shot"
:event/player1 "Sandro"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1909722"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_3023"}

{:event/type "shoton"
:event/elapsed 86
:event/subtype "shot"
:event/player1 "Gareth Bale"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1909746"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3023"}

{:event/type "shotoff"
:event/elapsed 87
:event/subtype "distance"
:event/player1 "Scott Parker"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1909748"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Ronnie Stam"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1909773"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Maynor Figueroa"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1909788"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Conor Sammon"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1909800"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3023"}

{:event/type "shotoff"
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Gareth Bale"
:event/sortorder 7
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1909806"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Ronnie Stam"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1909822"
:event/minute 91
:event/match_id "match_3023"}

{:event/type "shotoff"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "shot"
:event/player1 "James McArthur"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1909828"
:event/minute 92
:event/match_id "match_3023"}

{:event/type "shoton"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "distance"
:event/player1 "Albert Crusat"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1909836"
:event/minute 92
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Niko Kranjcar"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1909842"
:event/minute 93
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Jean Beausejour"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1909847"
:event/minute 93
:event/match_id "match_3023"}

{:event/type "shoton"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Gareth Bale"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_1909850"
:event/minute 93
:event/match_id "match_3023"}

{:event/type "shotoff"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "shot"
:event/player1 "unknown"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1909852"
:event/minute 93
:event/match_id "match_3023"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Ronnie Stam"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1909859"
:event/minute 94
:event/match_id "match_3023"}

{:event/type "foulcommit"
:event/elapsed_plus 4
:event/elapsed 90
:event/player2 "Scott Parker"
:event/player1 "Albert Crusat"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1909863"
:event/minute 94
:event/match_id "match_3023"}

{:event/type "card"
:event/elapsed_plus 4
:event/elapsed 90
:event/card_type "y"
:event/subtype "kicked_ball_away"
:event/player1 "Albert Crusat"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_1909866"
:event/minute 94
:event/match_id "match_3023"}


]

