
;;# data
[
{:match/id "match_24060"
:match/league "Spain LIGA BBVA"
:match/hometeam "Real Sociedad"
:match/awayteam "Villarreal CF"
:match/score "0:1"
:match/hometeam_goals "0"
:match/awayteam_goals "0"}

{:event/type "shoton"
:event/elapsed 2
:event/subtype "shot"
:event/player1 "Joel Campbell"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4397143"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_24060"}

{:event/type "corner"
:event/elapsed 4
:event/subtype "cross_right"
:event/player1 "Carlos Vela"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4397156"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_24060"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Gerard Moreno"
:event/subtype "pushing"
:event/player1 "Mikel Gonzalez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4397163"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Carlos Martinez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4397195"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_24060"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Inigo Martinez"
:event/player1 "Joel Campbell"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4397209"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_24060"}

{:event/type "shotoff"
:event/elapsed 14
:event/subtype "bad shot"
:event/player1 "Jaume Costa"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4397219"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Carlos Vela"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4397233"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Alberto De la Bella"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4397245"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_24060"}

{:event/type "shoton"
:event/elapsed 18
:event/subtype "blocked_shot"
:event/player1 "Esteban Granero"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4397252"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_24060"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Bojan Jokic"
:event/subtype "pushing"
:event/player1 "Carlos Vela"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4397254"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_24060"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Joel Campbell"
:event/player1 "Mikel Gonzalez"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4397259"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_24060"}

{:event/type "shoton"
:event/elapsed 20
:event/subtype "blocked_shot"
:event/player1 "Xabier Prieto"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4397262"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_24060"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Jaume Costa"
:event/player1 "Ruben Pardo"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4397263"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_24060"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Joel Campbell"
:event/subtype "trip"
:event/player1 "David Zurutuza"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4397267"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Jonathan dos Santos"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4397270"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_24060"}

{:event/type "shotoff"
:event/elapsed 22
:event/subtype "big chance header"
:event/player1 "Tomas Pina"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4397272"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "David Zurutuza"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4397282"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Manuel Trigueros"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4397286"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_24060"}

{:event/type "corner"
:event/elapsed 25
:event/subtype "cross_right"
:event/player1 "Jonathan dos Santos"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4397296"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_24060"}

{:event/type "corner"
:event/elapsed 26
:event/subtype "short_right"
:event/player1 "Jonathan dos Santos"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4397302"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Joel Campbell"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4397305"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_24060"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Xabier Prieto"
:event/player1 "Jose Dorado"
:event/sortorder 5
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4397308"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_24060"}

{:event/type "shotoff"
:event/elapsed 27
:event/subtype "shot"
:event/player1 "Jaume Costa"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4397313"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_24060"}

{:event/type "foulcommit"
:event/elapsed 28
:event/subtype "hands"
:event/player1 "Jaume Costa"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4397318"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Esteban Granero"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4397321"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_24060"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Joel Campbell"
:event/player1 "Inigo Martinez"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4397325"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_24060"}

{:event/type "foulcommit"
:event/elapsed 30
:event/player2 "Jaume Costa"
:event/subtype "pushing"
:event/player1 "Carlos Martinez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4397331"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Alberto De la Bella"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4397333"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Esteban Granero"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4397340"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Carlos Martinez"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4397342"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_24060"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Carlos Vela"
:event/subtype "trip"
:event/player1 "Tomas Pina"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4397347"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_24060"}

{:event/type "shoton"
:event/elapsed 33
:event/subtype "blocked_shot"
:event/player1 "Ruben Pardo"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4397351"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_24060"}

{:event/type "corner"
:event/elapsed 33
:event/subtype "cross_left"
:event/player1 "Alberto De la Bella"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4397353"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Alberto De la Bella"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4397355"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Carlos Martinez"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4397357"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_24060"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Victor Ruiz"
:event/player1 "David Zurutuza"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4397370"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Manuel Trigueros"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4397372"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Manuel Trigueros"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4397386"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Carlos Martinez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4397388"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Carlos Martinez"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4397393"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "David Zurutuza"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4397395"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Esteban Granero"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4397397"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_24060"}

{:event/type "shoton"
:event/elapsed 41
:event/subtype "big chance volley"
:event/player1 "Manuel Trigueros"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4397403"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_24060"}

{:event/type "corner"
:event/elapsed 41
:event/subtype "cross_right"
:event/player1 "Jonathan dos Santos"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_4397405"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_24060"}

{:event/type "corner"
:event/elapsed 41
:event/subtype "cross_right"
:event/player1 "Jonathan dos Santos"
:event/sortorder 5
:event/team "away"
:event/event_type "corner"
:event/id "event_4397408"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_24060"}

{:event/type "shoton"
:event/elapsed 42
:event/subtype "big chance header"
:event/player1 "Tomas Pina"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4397409"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_24060"}

{:event/type "corner"
:event/elapsed 42
:event/subtype "cross_left"
:event/player1 "Jonathan dos Santos"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4397411"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_24060"}

{:event/type "shotoff"
:event/elapsed 42
:event/subtype "header"
:event/player1 "Gerard Moreno"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4397413"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Carlos Martinez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4397417"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_24060"}

{:event/type "corner"
:event/elapsed 43
:event/subtype "cross_right"
:event/player1 "Carlos Vela"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4397420"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_24060"}

{:event/type "shoton"
:event/elapsed 44
:event/subtype "blocked_shot"
:event/player1 "Jaume Costa"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4397426"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_24060"}

{:event/type "corner"
:event/elapsed 44
:event/subtype "cross_left"
:event/player1 "Jonathan dos Santos"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4397427"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_24060"}

{:event/type "shoton"
:event/elapsed 44
:event/subtype "deflected"
:event/player1 "Mario Gaspar"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_4397430"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_24060"}

{:event/type "corner"
:event/elapsed 44
:event/subtype "cross_left"
:event/player1 "Jonathan dos Santos"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_4397432"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_24060"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Imanol Agirretxe"
:event/player1 "Sergio Asenjo"
:event/sortorder 6
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4397492"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_24060"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "Xabier Prieto"
:event/subtype "trip"
:event/player1 "Jonathan dos Santos"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4397437"
:event/minute 46
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Mario Gaspar"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4397487"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_24060"}

{:event/type "card"
:event/elapsed_plus 1
:event/elapsed 45
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Jonathan dos Santos"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_4397438"
:event/minute 46
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Esteban Granero"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4397440"
:event/minute 46
:event/match_id "match_24060"}

{:event/type "shoton"
:event/elapsed 47
:event/subtype "blocked_shot"
:event/player1 "Jaume Costa"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4397489"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_24060"}

{:event/type "foulcommit"
:event/elapsed 47
:event/player2 "Xabier Prieto"
:event/subtype "pushing"
:event/player1 "Victor Ruiz"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4397490"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_24060"}

{:event/type "card"
:event/elapsed 47
:event/card_type "y"
:event/subtype "pushing"
:event/player1 "Victor Ruiz"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_4397491"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_24060"}

{:event/type "shotoff"
:event/elapsed 48
:event/subtype "shot"
:event/player1 "Carlos Martinez"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4397495"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Manuel Trigueros"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4397501"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "David Zurutuza"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4397505"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Carlos Vela"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4397508"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_24060"}

{:event/type "shotoff"
:event/elapsed 51
:event/subtype "header"
:event/player1 "David Zurutuza"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4397509"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_24060"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Joel Campbell"
:event/subtype "trip"
:event/player1 "Mikel Gonzalez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4397516"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_24060"}

{:event/type "shoton"
:event/elapsed 53
:event/subtype "blocked_shot"
:event/player1 "Jonathan dos Santos"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4397518"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_24060"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Carlos Vela"
:event/subtype "trip"
:event/player1 "Bojan Jokic"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4397520"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "David Zurutuza"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4397524"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Ruben Pardo"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4397532"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_24060"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Carlos Vela"
:event/subtype "from_behind"
:event/player1 "Manuel Trigueros"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4397542"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_24060"}

{:event/type "card"
:event/elapsed 59
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Manuel Trigueros"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_4397543"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_24060"}

{:event/type "shotoff"
:event/elapsed 60
:event/subtype "direct_freekick"
:event/player1 "Esteban Granero"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4397545"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_24060"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Jaume Costa"
:event/player1 "Xabier Prieto"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4397552"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_24060"}

{:event/type "corner"
:event/elapsed 62
:event/subtype "cross_right"
:event/player1 "Carlos Martinez"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4397555"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_24060"}

{:event/type "corner"
:event/elapsed 62
:event/subtype "cross_left"
:event/player1 "Carlos Vela"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4397558"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Alberto De la Bella"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4397562"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_24060"}

{:event/type "shotoff"
:event/elapsed 63
:event/subtype "header"
:event/player1 "Xabier Prieto"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4397563"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_24060"}

{:event/type "corner"
:event/elapsed 63
:event/subtype "cross_right"
:event/player1 "Esteban Granero"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4397564"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_24060"}

{:event/type "shoton"
:event/elapsed 63
:event/subtype "big chance header"
:event/player1 "Inigo Martinez"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_4397566"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Joel Campbell"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4397567"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_24060"}

{:event/type "shotoff"
:event/elapsed 65
:event/subtype "distance"
:event/player1 "Carlos Vela"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4397573"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_24060"}

{:event/type "foulcommit"
:event/elapsed 66
:event/player2 "Imanol Agirretxe"
:event/player1 "Mario Gaspar"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4397577"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Carlos Vela"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4397579"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "David Zurutuza"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4397582"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Carlos Martinez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4397599"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Xabier Prieto"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4397600"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_24060"}

{:event/type "shotoff"
:event/elapsed 70
:event/subtype "bad shot"
:event/player1 "Sergio Canales"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4397602"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_24060"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Esteban Granero"
:event/player1 "Joel Campbell"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4397605"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Xabier Prieto"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4397606"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_24060"}

{:event/type "shotoff"
:event/elapsed 72
:event/subtype "header"
:event/player1 "Alberto De la Bella"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4397607"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_24060"}

{:event/type "card"
:event/elapsed 73
:event/card_type "y"
:event/subtype "verbal_abuse"
:event/player1 "Juan Carlos"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_4397614"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_24060"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Jonathan dos Santos"
:event/subtype "serious_foul"
:event/player1 "Alberto De la Bella"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4397619"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_24060"}

{:event/type "shoton"
:event/elapsed 76
:event/subtype "blocked_shot"
:event/player1 "Tomas Pina"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4397624"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_24060"}

{:event/type "shotoff"
:event/elapsed 77
:event/subtype "distance"
:event/player1 "Sergio Canales"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4397630"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_24060"}

{:event/type "shoton"
:event/elapsed 78
:event/subtype "deflected"
:event/player1 "unknown"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_4397634"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_24060"}

{:event/type "corner"
:event/elapsed 79
:event/subtype "cross_left"
:event/player1 "Jonathan dos Santos"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4397637"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_24060"}

{:event/type "shotoff"
:event/elapsed 79
:event/subtype "shot"
:event/player1 "Tomas Pina"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4397642"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Gonzalo Castro"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4397649"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_24060"}

{:event/type "shoton"
:event/elapsed 81
:event/subtype "deflected"
:event/player1 "Esteban Granero"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4397651"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_24060"}

{:event/type "corner"
:event/elapsed 81
:event/subtype "cross_left"
:event/player1 "Gonzalo Castro"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_4397652"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_24060"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Joel Campbell"
:event/player1 "Mikel Gonzalez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4397654"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_24060"}

{:event/type "card"
:event/elapsed 82
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Mikel Gonzalez"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4397680"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Moi Gomez"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4397660"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_24060"}

{:event/type "shotoff"
:event/elapsed 83
:event/subtype "big chance shot"
:event/player1 "unknown"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4397661"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Xabier Prieto"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4397664"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_24060"}

{:event/type "shoton"
:event/elapsed 83
:event/subtype "shot"
:event/player1 "Gonzalo Castro"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_4397666"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Gonzalo Castro"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4397669"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_24060"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Joel Campbell"
:event/player1 "Ruben Pardo"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4397671"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Jonathan dos Santos"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4397672"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_24060"}

{:event/type "foulcommit"
:event/elapsed 87
:event/player2 "Moi Gomez"
:event/subtype "trip"
:event/player1 "Ruben Pardo"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4397685"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Jonathan dos Santos"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4397687"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_24060"}

{:event/type "goal"
:event/elapsed 89
:event/subtype "header"
:event/player1 "Victor Ruiz"
:event/sortorder 0
:event/team "away"
:event/id "event_4397688"
:event/event_type "goal"
:event/goal_type "dg"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Gonzalo Castro"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4397694"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_24060"}

{:event/type "shotoff"
:event/elapsed 90
:event/subtype "distance"
:event/player1 "Esteban Granero"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4397696"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_24060"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Alfred Finnbogason"
:event/subtype "from_behind"
:event/player1 "Bojan Jokic"
:event/sortorder 5
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4397699"
:event/minute 91
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Esteban Granero"
:event/sortorder 7
:event/team "home"
:event/event_type "cross"
:event/id "event_4397702"
:event/minute 91
:event/match_id "match_24060"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/sortorder 8
:event/team "home"
:event/event_type "throwin"
:event/id "event_4397703"
:event/minute 92
:event/match_id "match_24060"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Joel Campbell"
:event/player1 "Esteban Granero"
:event/sortorder 10
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4397706"
:event/minute 92
:event/match_id "match_24060"}

{:event/type "corner"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross_right"
:event/player1 "Jonathan dos Santos"
:event/sortorder 13
:event/team "away"
:event/event_type "corner"
:event/id "event_4397712"
:event/minute 94
:event/match_id "match_24060"}

{:event/type "shoton"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "big chance header"
:event/player1 "Mario Gaspar"
:event/sortorder 14
:event/team "away"
:event/event_type "shoton"
:event/id "event_4397713"
:event/minute 94
:event/match_id "match_24060"}


]

