
;;# data
[
{:match/id "match_4264"
:match/league "England Premier League"
:match/hometeam "Sunderland"
:match/awayteam "Crystal Palace"
:match/score "1:4"
:match/hometeam_goals "1"
:match/awayteam_goals "4"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Jack Rodwell"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4338525"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Joel Ward"
:event/player1 "Patrick van Aanholt"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4338540"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "Jordi Gomez"
:event/player1 "Joel Ward"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4338574"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Billy Jones"
:event/player1 "Yannick Bolasie"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4338596"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_4264"}

{:event/type "corner"
:event/elapsed 5
:event/subtype "cross_left"
:event/player1 "Jordi Gomez"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4338622"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_4264"}

{:event/type "shotoff"
:event/elapsed 5
:event/subtype "header"
:event/player1 "Steven Fletcher"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4338624"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_4264"}

{:event/type "corner"
:event/elapsed 6
:event/subtype "cross_left"
:event/player1 "Jordi Gomez"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_4338654"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_4264"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Connor Wickham"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4338671"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Wilfried Zaha"
:event/player1 "Jordi Gomez"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4338800"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_4264"}

{:event/type "shoton"
:event/elapsed 13
:event/subtype "blocked_shot"
:event/player1 "Mile Jedinak"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4338823"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_4264"}

{:event/type "shoton"
:event/elapsed 15
:event/subtype "distance"
:event/player1 "Jason Puncheon"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4338857"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_4264"}

{:event/type "shoton"
:event/elapsed 15
:event/subtype "blocked_shot"
:event/player1 "Glenn Murray"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4338879"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "James McArthur"
:event/subtype "dangerous_play"
:event/player1 "Jack Rodwell"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4338887"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_4264"}

{:event/type "card"
:event/elapsed 16
:event/card_type "y"
:event/player1 "Jack Rodwell"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_4338892"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_4264"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Jason Puncheon"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4338916"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_4264"}

{:event/type "corner"
:event/elapsed 17
:event/subtype "cross_right"
:event/player1 "Jason Puncheon"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4338922"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Costel Pantilimon"
:event/player1 "Scott Dann"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4338928"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_4264"}

{:event/type "card"
:event/elapsed 18
:event/card_type "y"
:event/player1 "Scott Dann"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4338951"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Jason Puncheon"
:event/player1 "Jack Rodwell"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4338970"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_4264"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Jason Puncheon"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4338975"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Billy Jones"
:event/player1 "Yannick Bolasie"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4338980"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_4264"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Billy Jones"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4338993"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Yannick Bolasie"
:event/player1 "Billy Jones"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4339008"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_4264"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Jason Puncheon"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4339009"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Yannick Bolasie"
:event/subtype "pull"
:event/player1 "Lee Cattermole"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4339031"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_4264"}

{:event/type "card"
:event/elapsed 24
:event/card_type "y"
:event/player1 "Lee Cattermole"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4339035"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_4264"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Scott Dann"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4339043"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Wilfried Zaha"
:event/player1 "Jordi Gomez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4339083"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Steven Fletcher"
:event/player1 "Damien Delaney"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4339088"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_4264"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Jordi Gomez"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4339096"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_4264"}

{:event/type "shotoff"
:event/elapsed 27
:event/subtype "bicycle_kick"
:event/player1 "Steven Fletcher"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4339098"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Steven Fletcher"
:event/player1 "Pape Ndiaye Souare"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4339121"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Pape Ndiaye Souare"
:event/subtype "obstruction"
:event/player1 "Billy Jones"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4339149"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Steven Fletcher"
:event/player1 "Mile Jedinak"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4339163"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_4264"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Lee Cattermole"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_4339174"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Glenn Murray"
:event/player1 "Jermain Defoe"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4339179"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_4264"}

{:event/type "shoton"
:event/elapsed 38
:event/subtype "blocked_shot"
:event/player1 "Yannick Bolasie"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4339310"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_4264"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Yannick Bolasie"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4339327"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_4264"}

{:event/type "corner"
:event/elapsed 39
:event/subtype "short_left"
:event/player1 "Jason Puncheon"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4339338"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_4264"}

{:event/type "shotoff"
:event/elapsed 39
:event/subtype "distance"
:event/player1 "Patrick van Aanholt"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4339358"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Patrick van Aanholt"
:event/player1 "Wilfried Zaha"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4339441"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_4264"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Patrick van Aanholt"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4339505"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_4264"}

{:event/type "shoton"
:event/elapsed 44
:event/subtype "volley"
:event/player1 "Steven Fletcher"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4339512"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_4264"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Connor Wickham"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4339540"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_4264"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross"
:event/sortorder 5
:event/team "home"
:event/event_type "throwin"
:event/id "event_4339585"
:event/minute 47
:event/match_id "match_4264"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Yannick Bolasie"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4339975"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_4264"}

{:event/type "goal"
:event/elapsed 48
:event/subtype "header"
:event/player1 "Glenn Murray"
:event/sortorder 1
:event/team "away"
:event/id "event_4339978"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_4264"}

{:event/type "shotoff"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "deflected"
:event/player1 "Connor Wickham"
:event/sortorder 7
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4339620"
:event/minute 48
:event/match_id "match_4264"}

{:event/type "corner"
:event/elapsed_plus 4
:event/elapsed 45
:event/subtype "cross_left"
:event/player1 "Jordi Gomez"
:event/sortorder 8
:event/team "home"
:event/event_type "corner"
:event/id "event_4339629"
:event/minute 49
:event/match_id "match_4264"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Yannick Bolasie"
:event/sortorder 10
:event/team "away"
:event/event_type "cross"
:event/id "event_4339644"
:event/minute 49
:event/match_id "match_4264"}

{:event/type "shoton"
:event/elapsed_plus 4
:event/elapsed 45
:event/subtype "blocked_shot"
:event/player1 "Wilfried Zaha"
:event/sortorder 11
:event/team "away"
:event/event_type "shoton"
:event/id "event_4339645"
:event/minute 49
:event/match_id "match_4264"}

{:event/type "goal"
:event/elapsed 51
:event/player2 "Glenn Murray"
:event/subtype "shot"
:event/player1 "Yannick Bolasie"
:event/sortorder 1
:event/team "away"
:event/id "event_4340080"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_4264"}

{:event/type "goal"
:event/elapsed 53
:event/player2 "Mile Jedinak"
:event/subtype "lob"
:event/player1 "Yannick Bolasie"
:event/sortorder 2
:event/team "away"
:event/id "event_4340145"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_4264"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Joel Ward"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4340215"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player1 "Connor Wickham"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4340267"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_4264"}

{:event/type "shoton"
:event/elapsed 59
:event/subtype "shot"
:event/player1 "Glenn Murray"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4340331"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Wilfried Zaha"
:event/player1 "Lee Cattermole"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4340377"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_4264"}

{:event/type "goal"
:event/elapsed 62
:event/player2 "Glenn Murray"
:event/subtype "shot"
:event/player1 "Yannick Bolasie"
:event/sortorder 2
:event/team "away"
:event/id "event_4340418"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Glenn Murray"
:event/player1 "Jack Rodwell"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4340453"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Jermain Defoe"
:event/player1 "Joel Ward"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4340486"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed 66
:event/subtype "hands"
:event/player1 "Wilfried Zaha"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4340488"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_4264"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Patrick van Aanholt"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4340492"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_4264"}

{:event/type "shoton"
:event/elapsed 66
:event/subtype "shot"
:event/player1 "James McArthur"
:event/sortorder 5
:event/team "away"
:event/event_type "shoton"
:event/id "event_4340499"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Steven Fletcher"
:event/player1 "James McArthur"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4340518"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_4264"}

{:event/type "card"
:event/elapsed 67
:event/card_type "y"
:event/player1 "James McArthur"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4340521"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_4264"}

{:event/type "corner"
:event/elapsed 68
:event/subtype "cross_left"
:event/player1 "Adam Johnson"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4341052"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Billy Jones"
:event/player1 "Jason Puncheon"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4340604"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Yaya Sanogo"
:event/player1 "Liam Bridcutt"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4340627"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_4264"}

{:event/type "shoton"
:event/elapsed 73
:event/subtype "blocked_shot"
:event/player1 "Joel Ward"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4340630"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Liam Bridcutt"
:event/player1 "Glenn Murray"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4340851"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_4264"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Wilfried Zaha"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4340669"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Joel Ward"
:event/player1 "Jermain Defoe"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4340704"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_4264"}

{:event/type "corner"
:event/elapsed 78
:event/subtype "cross_right"
:event/player1 "Jason Puncheon"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4340711"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed 79
:event/player2 "Jack Rodwell"
:event/player1 "Glenn Murray"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4340758"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Glenn Murray"
:event/player1 "Santiago Vergini"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4340770"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_4264"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Wilfried Zaha"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4340777"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_4264"}

{:event/type "shotoff"
:event/elapsed 83
:event/subtype "deflected"
:event/player1 "Jermain Defoe"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4340809"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_4264"}

{:event/type "corner"
:event/elapsed 83
:event/subtype "cross_left"
:event/player1 "Adam Johnson"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4340816"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_4264"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Jason Puncheon"
:event/sortorder 5
:event/team "away"
:event/event_type "cross"
:event/id "event_4340822"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_4264"}

{:event/type "corner"
:event/elapsed 84
:event/subtype "short_right"
:event/player1 "Jason Puncheon"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4340837"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_4264"}

{:event/type "shotoff"
:event/elapsed 87
:event/subtype "bad shot"
:event/player1 "Jermain Defoe"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4340894"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_4264"}

{:event/type "shotoff"
:event/elapsed 88
:event/subtype "distance"
:event/player1 "Adam Johnson"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4340913"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_4264"}

{:event/type "goal"
:event/elapsed 90
:event/player2 "Patrick van Aanholt"
:event/subtype "shot"
:event/player1 "Connor Wickham"
:event/sortorder 1
:event/team "home"
:event/id "event_4340941"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Connor Wickham"
:event/player1 "Mile Jedinak"
:event/sortorder 5
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4340971"
:event/minute 92
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Patrick van Aanholt"
:event/player1 "Wilfried Zaha"
:event/sortorder 6
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4340975"
:event/minute 92
:event/match_id "match_4264"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Jack Rodwell"
:event/player1 "Yaya Sanogo"
:event/sortorder 6
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4341037"
:event/minute 93
:event/match_id "match_4264"}

{:event/type "shoton"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Patrick van Aanholt"
:event/sortorder 8
:event/team "home"
:event/event_type "shoton"
:event/id "event_4340984"
:event/minute 93
:event/match_id "match_4264"}

{:event/type "corner"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross_left"
:event/player1 "Adam Johnson"
:event/sortorder 9
:event/team "home"
:event/event_type "corner"
:event/id "event_4340991"
:event/minute 93
:event/match_id "match_4264"}

{:event/type "shoton"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "blocked_shot"
:event/player1 "Jermain Defoe"
:event/sortorder 13
:event/team "home"
:event/event_type "shoton"
:event/id "event_4340999"
:event/minute 94
:event/match_id "match_4264"}

{:event/type "corner"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross_left"
:event/player1 "Adam Johnson"
:event/sortorder 14
:event/team "home"
:event/event_type "corner"
:event/id "event_4341000"
:event/minute 94
:event/match_id "match_4264"}


]

