
;;# data
[
{:match/id "match_11196"
:match/league "Italy Serie A"
:match/hometeam "Cagliari"
:match/awayteam "Chievo Verona"
:match/score "4:1"
:match/hometeam_goals "4"
:match/awayteam_goals "1"}

{:event/type "card"
:event/elapsed 12
:event/card_type "y"
:event/player1 "Davide Mandelli"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1408009"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_11196"}

{:event/type "goal"
:event/elapsed 19
:event/player1 "Daniele Conti"
:event/sortorder 0
:event/team "home"
:event/id "event_1408047"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_11196"}

{:event/type "goal"
:event/elapsed 29
:event/player1 "Michele Canini"
:event/sortorder 0
:event/team "home"
:event/id "event_1408095"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_11196"}

{:event/type "goal"
:event/elapsed 43
:event/player1 "Nene"
:event/sortorder 0
:event/team "home"
:event/id "event_1408239"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_11196"}

{:event/type "card"
:event/elapsed 64
:event/card_type "y"
:event/player1 "Gennaro Sardo"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1408547"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_11196"}

{:event/type "goal"
:event/elapsed 71
:event/player1 "Nene"
:event/sortorder 0
:event/team "home"
:event/id "event_1408546"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_11196"}

{:event/type "card"
:event/elapsed 75
:event/card_type "y"
:event/player1 "Luca Rigoni"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1408595"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_11196"}

{:event/type "card"
:event/elapsed 82
:event/card_type "y"
:event/player1 "Davide Astori"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1408622"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_11196"}

{:event/type "goal"
:event/elapsed 84
:event/player1 "Cyril Thereau"
:event/sortorder 0
:event/team "away"
:event/id "event_1408746"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_11196"}


]

