
;;# data
[
{:match/id "match_22232"
:match/league "Spain LIGA BBVA"
:match/hometeam "RCD Mallorca"
:match/awayteam "Real Valladolid"
:match/score "3:0"
:match/hometeam_goals "3"
:match/awayteam_goals "0"}

{:event/type "foulcommit"
:event/elapsed 4
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_777576"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_22232"}

{:event/type "goal"
:event/elapsed 4
:event/subtype "shot"
:event/player1 "Jose Carlos Nunes"
:event/sortorder 2
:event/team "home"
:event/id "event_777582"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 6
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_777597"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 8
:event/player2 "Borja Valero"
:event/subtype "from_behind"
:event/player1 "Borja Fernandez"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_777624"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Diego Costa"
:event/player1 "Ivan Ramis"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_777628"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_22232"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Jose Carlos Nunes"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_777639"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_22232"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_777644"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_22232"}

{:event/type "corner"
:event/elapsed 11
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_777644"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player1 "Javier Baraja"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_777696"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Aritz Aduriz"
:event/player1 "Nivaldo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_777724"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_22232"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Borja Valero"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_777732"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_22232"}

{:event/type "corner"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Borja Valero"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_777732"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_22232"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Tuni"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_777744"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Julio Alvarez"
:event/player1 "Borja Fernandez"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_777747"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_22232"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Fabian Canobbio"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_777765"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_22232"}

{:event/type "corner"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Fabian Canobbio"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_777765"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Tuni"
:event/subtype "from_behind"
:event/player1 "Pedro Lopez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_777770"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_22232"}

{:event/type "shoton"
:event/elapsed 24
:event/subtype "header"
:event/player1 "Aritz Aduriz"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_777778"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_22232"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Julio Alvarez"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_777781"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_22232"}

{:event/type "corner"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Julio Alvarez"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_777781"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Fabian Canobbio"
:event/player1 "Aritz Aduriz"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_777787"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_22232"}

{:event/type "shotoff"
:event/elapsed 26
:event/subtype "big chance shot"
:event/player1 "Victor Casadesus"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_777796"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_22232"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Fabian Canobbio"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_777801"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_22232"}

{:event/type "corner"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Fabian Canobbio"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_777801"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Pedro Lopez"
:event/player1 "Tuni"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_777808"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Aritz Aduriz"
:event/subtype "pushing"
:event/player1 "Javier Baraja"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_777815"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_22232"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Borja Valero"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_777850"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_22232"}

{:event/type "corner"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Borja Valero"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_777850"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 33
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_777853"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Borja Fernandez"
:event/player1 "Aritz Aduriz"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_777859"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Borja Valero"
:event/player1 "Borja Fernandez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_777868"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_22232"}

{:event/type "shoton"
:event/elapsed 36
:event/subtype "shot"
:event/player1 "Aritz Aduriz"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_777871"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Aritz Aduriz"
:event/subtype "shirt_pull"
:event/player1 "Alvaro Rubio"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_777921"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Sisi"
:event/subtype "pushing"
:event/player1 "Ayoze Diaz Diaz"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_777930"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_22232"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Tuni"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_777938"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 45
:event/subtype "pushing"
:event/player1 "Nivaldo"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_777949"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_22232"}

{:event/type "shotoff"
:event/elapsed 49
:event/subtype "big chance shot"
:event/player1 "Borja Fernandez"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_778040"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Nivaldo"
:event/player1 "Victor Casadesus"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_778043"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_22232"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Tuni"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_778055"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 54
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_778063"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_22232"}

{:event/type "shoton"
:event/elapsed 54
:event/subtype "big chance shot"
:event/player1 "Aritz Aduriz"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_778065"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_22232"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Julio Alvarez"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_778067"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_22232"}

{:event/type "corner"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Julio Alvarez"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_778067"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_22232"}

{:event/type "shotoff"
:event/elapsed 55
:event/subtype "big chance header"
:event/player1 "Victor Casadesus"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_778068"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Fabian Canobbio"
:event/player1 "Jose Miguel Josemi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_778078"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_22232"}

{:event/type "shotoff"
:event/elapsed 59
:event/subtype "shot"
:event/player1 "Mario Suarez"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_778095"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_22232"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Julio Alvarez"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_778107"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_22232"}

{:event/type "corner"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Julio Alvarez"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_778107"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Alberto Bueno"
:event/player1 "Ayoze Diaz Diaz"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_778109"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Julio Alvarez"
:event/player1 "unknown"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_778117"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_22232"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Julio Alvarez"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_778121"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_22232"}

{:event/type "shotoff"
:event/elapsed 63
:event/subtype "distance"
:event/player1 "Mario Suarez"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_778122"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player1 "Fabian Canobbio"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_778125"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_22232"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Tuni"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_778132"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_22232"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Tuni"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_778133"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 66
:event/player2 "Fabian Canobbio"
:event/player1 "Borja Valero"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_778142"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_22232"}

{:event/type "shotoff"
:event/elapsed 67
:event/subtype "header"
:event/player1 "Diego Costa"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_778148"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Tuni"
:event/subtype "shirt_pull"
:event/player1 "Pedro Lopez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_778155"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_22232"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Borja Valero"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_778160"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_22232"}

{:event/type "corner"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Borja Valero"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_778160"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_22232"}

{:event/type "shoton"
:event/elapsed 69
:event/subtype "header"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_778163"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_22232"}

{:event/type "goal"
:event/elapsed 70
:event/player2 "Mario Suarez"
:event/subtype "shot"
:event/player1 "Aritz Aduriz"
:event/sortorder 2
:event/team "home"
:event/id "event_778166"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Alberto Bueno"
:event/player1 "Tuni"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_778171"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Fabian Canobbio"
:event/subtype "pushing"
:event/player1 "Jose Carlos Nunes"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_778174"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_22232"}

{:event/type "shoton"
:event/elapsed 72
:event/subtype "big chance shot"
:event/player1 "Diego Costa"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_778181"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_22232"}

{:event/type "corner"
:event/elapsed 72
:event/subtype "short"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_778184"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_22232"}

{:event/type "goal"
:event/elapsed 73
:event/player2 "Victor Casadesus"
:event/subtype "shot"
:event/player1 "Borja Valero"
:event/sortorder 0
:event/team "home"
:event/id "event_778187"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_22232"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Fabian Canobbio"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_778200"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_22232"}

{:event/type "corner"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Fabian Canobbio"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_778200"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Pedro Lopez"
:event/subtype "shirt_pull"
:event/player1 "Victor Casadesus"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_778204"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Ivan Ramis"
:event/player1 "Diego Costa"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_778237"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 82
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_778253"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_22232"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Fabian Canobbio"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_778265"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_22232"}

{:event/type "corner"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Fabian Canobbio"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_778265"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_22232"}

{:event/type "shotoff"
:event/elapsed 83
:event/subtype "header"
:event/player1 "Alberto Bueno"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_778270"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_22232"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Borja Valero"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_778275"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_22232"}

{:event/type "corner"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Borja Valero"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_778275"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Borja Valero"
:event/subtype "pushing"
:event/player1 "Fabian Canobbio"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_778279"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Victor Casadesus"
:event/player1 "Nivaldo"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_778293"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_22232"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Jose Miguel Josemi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_778300"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player2 "Borja Fernandez"
:event/player1 "Alhassane Keita"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_778319"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_22232"}

{:event/type "shotoff"
:event/elapsed 90
:event/subtype "distance"
:event/player1 "Diego Costa"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_778326"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Marti Crespi"
:event/player1 "Borja Fernandez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_778328"
:event/minute 91
:event/match_id "match_22232"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Gonzalo Castro"
:event/player1 "Borja Fernandez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_778347"
:event/minute 93
:event/match_id "match_22232"}

{:event/type "shoton"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "distance"
:event/player1 "Jose Miguel Josemi"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_778350"
:event/minute 93
:event/match_id "match_22232"}


]

