
;;# data
[
{:match/id "match_22105"
:match/league "Spain LIGA BBVA"
:match/hometeam "FC Barcelona"
:match/awayteam "CA Osasuna"
:match/score "2:0"
:match/hometeam_goals "2"
:match/awayteam_goals "0"}

{:event/type "shoton"
:event/elapsed 2
:event/subtype "shot"
:event/player1 "Zlatan Ibrahimovic"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1009534"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_22105"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Daniel Alves"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1009535"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_22105"}

{:event/type "shotoff"
:event/elapsed 2
:event/subtype "header"
:event/player1 "Zlatan Ibrahimovic"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1009536"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "Javier Camunas"
:event/player1 "Daniel Alves"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1009541"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_22105"}

{:event/type "shoton"
:event/elapsed 4
:event/subtype "big chance shot"
:event/player1 "Krisztian Vadocz"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1009545"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_22105"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Patxi Martinez Punal"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1009548"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_22105"}

{:event/type "corner"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Patxi Martinez Punal"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1009548"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_22105"}

{:event/type "shotoff"
:event/elapsed 5
:event/subtype "header"
:event/player1 "Javad Nekounam"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1009549"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Thierry Henry"
:event/player1 "Javier Camunas"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1009559"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Masoud Shojaei"
:event/player1 "Gabriel Milito"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1009564"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_22105"}

{:event/type "shoton"
:event/elapsed 11
:event/subtype "blocked_shot"
:event/player1 "Masoud Shojaei"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1009567"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_22105"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Patxi Martinez Punal"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1009568"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_22105"}

{:event/type "corner"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Patxi Martinez Punal"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1009568"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Sergio Busquets"
:event/player1 "Patxi Martinez Punal"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1009575"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Lionel Messi"
:event/player1 "Miguel Flano"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1009576"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_22105"}

{:event/type "shotoff"
:event/elapsed 15
:event/subtype "deflected"
:event/player1 "Lionel Messi"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1009578"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_22105"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Maxwell"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1009579"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_22105"}

{:event/type "corner"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Maxwell"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1009579"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_22105"}

{:event/type "shoton"
:event/elapsed 15
:event/subtype "shot"
:event/player1 "Thierry Henry"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1009580"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_22105"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Lionel Messi"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1009581"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_22105"}

{:event/type "corner"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Lionel Messi"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1009581"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_22105"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Javier Camunas"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1009585"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_22105"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Patxi Martinez Punal"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1009589"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_22105"}

{:event/type "corner"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Patxi Martinez Punal"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1009589"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_22105"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/sortorder 2
:event/team "away"
:event/event_type "throwin"
:event/id "event_1009592"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed 18
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1009593"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed 22
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1009607"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed 24
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1009610"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Cesar Azpilicueta"
:event/player1 "Thierry Henry"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1009615"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed 25
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1009618"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player1 "Krisztian Vadocz"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1009624"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_22105"}

{:event/type "shoton"
:event/elapsed 30
:event/subtype "blocked_shot"
:event/player1 "Zlatan Ibrahimovic"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1009633"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_22105"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Lionel Messi"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1009634"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_22105"}

{:event/type "corner"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Lionel Messi"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1009634"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed 34
:event/player2 "Thierry Henry"
:event/player1 "Cesar Azpilicueta"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1009648"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_22105"}

{:event/type "shoton"
:event/elapsed 35
:event/subtype "deflected"
:event/player1 "Zlatan Ibrahimovic"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1009650"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_22105"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Lionel Messi"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1009651"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_22105"}

{:event/type "corner"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Lionel Messi"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1009651"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Juanfran"
:event/player1 "Maxwell"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1009658"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Masoud Shojaei"
:event/player1 "Sergio Busquets"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1009678"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_22105"}

{:event/type "card"
:event/elapsed 39
:event/card_type "y"
:event/player1 "Sergio Busquets"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_1009679"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_22105"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_1009690"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed 46
:event/player2 "Pedro Rodriguez"
:event/player1 "Patxi Martinez Punal"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1010134"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_22105"}

{:event/type "card"
:event/elapsed 46
:event/card_type "y"
:event/player1 "Patxi Martinez Punal"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_1010135"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_22105"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Andres Iniesta"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1010201"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_22105"}

{:event/type "corner"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Andres Iniesta"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1010201"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed 49
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1010217"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed 50
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1010236"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_22105"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Pedro Rodriguez"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1010256"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_22105"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Pedro Rodriguez"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1010261"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_22105"}

{:event/type "corner"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Pedro Rodriguez"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1010261"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Cesar Azpilicueta"
:event/player1 "Andres Iniesta"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1010269"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_22105"}

{:event/type "card"
:event/elapsed 51
:event/card_type "y"
:event/player1 "Andres Iniesta"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_1010270"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_22105"}

{:event/type "shotoff"
:event/elapsed 53
:event/subtype "shot"
:event/player1 "Lionel Messi"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1010320"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Masoud Shojaei"
:event/player1 "Gabriel Milito"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1010340"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_22105"}

{:event/type "shotoff"
:event/elapsed 58
:event/subtype "header"
:event/player1 "Lionel Messi"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1010437"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Sergio Busquets"
:event/player1 "Krisztian Vadocz"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1010506"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_22105"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Andres Iniesta"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1010532"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_22105"}

{:event/type "corner"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Andres Iniesta"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1010532"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_22105"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Andres Iniesta"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1010541"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_22105"}

{:event/type "shotoff"
:event/elapsed 63
:event/subtype "header"
:event/player1 "Yaya Toure"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1010542"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Andres Iniesta"
:event/player1 "Cesar Azpilicueta"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1010597"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed 66
:event/player2 "Zlatan Ibrahimovic"
:event/player1 "Jose Josetxo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1010610"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Nacho Monreal"
:event/player1 "Pedro Rodriguez"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1010689"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_22105"}

{:event/type "card"
:event/elapsed 70
:event/card_type "y"
:event/subtype "verbal_abuse"
:event/player1 "Daniel Alves"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1010707"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed 71
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1010715"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_22105"}

{:event/type "shoton"
:event/elapsed 71
:event/subtype "header"
:event/player1 "Seydou Keita"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1010724"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_22105"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Maxwell"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1010743"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_22105"}

{:event/type "goal"
:event/elapsed 73
:event/subtype "shot"
:event/player1 "Zlatan Ibrahimovic"
:event/sortorder 2
:event/team "home"
:event/id "event_1010735"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed 76
:event/subtype "hands"
:event/player1 "Jose Josetxo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1010774"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_22105"}

{:event/type "card"
:event/elapsed 77
:event/card_type "y"
:event/player1 "Jose Josetxo"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1010775"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Yaya Toure"
:event/player1 "Krisztian Vadocz"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1010782"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_22105"}

{:event/type "corner"
:event/elapsed 79
:event/subtype "short"
:event/player1 "Andres Iniesta"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1010794"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Lionel Messi"
:event/player1 "Patxi Martinez Punal"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1010810"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Jose Josetxo"
:event/player1 "Lionel Messi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1010814"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_22105"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Daniel Alves"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1010819"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_22105"}

{:event/type "shotoff"
:event/elapsed 83
:event/subtype "shot"
:event/player1 "Lionel Messi"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1010825"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_22105"}

{:event/type "card"
:event/elapsed 86
:event/card_type "y"
:event/subtype "kicked_ball_away"
:event/player1 "Lionel Messi"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1010852"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Cesar Azpilicueta"
:event/player1 "Lionel Messi"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1010856"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Yaya Toure"
:event/player1 "Patxi Martinez Punal"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1010861"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_22105"}

{:event/type "goal"
:event/elapsed 89
:event/subtype "shot"
:event/player1 "Bojan Krkic"
:event/sortorder 0
:event/team "home"
:event/id "event_1010895"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_22105"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Cesar Azpilicueta"
:event/player1 "Bojan Krkic"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1010984"
:event/minute 93
:event/match_id "match_22105"}


]

