
;;# data
[
{:match/id "match_12028"
:match/league "Italy Serie A"
:match/hometeam "Chievo Verona"
:match/awayteam "Genoa"
:match/score "0:1"
:match/hometeam_goals "0"
:match/awayteam_goals "1"}

{:event/type "card"
:event/elapsed 60
:event/card_type "y"
:event/player1 "Paul Papp"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2731958"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_12028"}

{:event/type "card"
:event/elapsed 62
:event/card_type "y"
:event/player1 "Gennaro Sardo"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2731959"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_12028"}

{:event/type "card"
:event/elapsed 68
:event/card_type "y"
:event/player1 "Marco Borriello"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2732036"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_12028"}

{:event/type "goal"
:event/elapsed 73
:event/player1 "Marco Borriello"
:event/sortorder 0
:event/team "away"
:event/id "event_2731999"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_12028"}

{:event/type "card"
:event/elapsed 76
:event/card_type "y"
:event/player1 "Cyril Thereau"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2732035"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_12028"}

{:event/type "card"
:event/elapsed 85
:event/card_type "y"
:event/player1 "Perparim Hetemaj"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2732123"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_12028"}


]

