
;;# data
[
{:match/id "match_4081"
:match/league "England Premier League"
:match/hometeam "Chelsea"
:match/awayteam "Hull City"
:match/score "2:0"
:match/hometeam_goals "2"
:match/awayteam_goals "0"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Filipe Luis"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4007053"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Oscar"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4007119"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_4081"}

{:event/type "goal"
:event/elapsed 7
:event/player2 "Oscar"
:event/subtype "header"
:event/player1 "Eden Hazard"
:event/sortorder 1
:event/team "home"
:event/id "event_4007120"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_4081"}

{:event/type "foulcommit"
:event/elapsed 8
:event/player2 "Diego Costa"
:event/subtype "trip"
:event/player1 "Jake Livermore"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4007148"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_4081"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Sone Aluko"
:event/subtype "trip"
:event/player1 "Gary Cahill"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4007192"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Ahmed El Mohamady"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4007203"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_4081"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "John Terry"
:event/subtype "dangerous_play"
:event/player1 "Curtis Davies"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4007214"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_4081"}

{:event/type "shotoff"
:event/elapsed 12
:event/subtype "volley"
:event/player1 "Jake Livermore"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4007235"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_4081"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Oscar"
:event/subtype "trip"
:event/player1 "Tom Huddlestone"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4007309"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_4081"}

{:event/type "card"
:event/elapsed 15
:event/card_type "y"
:event/player1 "Tom Huddlestone"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_4007311"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4007320"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Andrew Robertson"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4007409"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_4081"}

{:event/type "shotoff"
:event/elapsed 21
:event/subtype "shot"
:event/player1 "Sone Aluko"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4007436"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_4081"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "David Meyler"
:event/subtype "trip"
:event/player1 "Diego Costa"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4007459"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Andrew Robertson"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4007468"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4007499"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_4081"}

{:event/type "corner"
:event/elapsed 26
:event/subtype "cross_right"
:event/player1 "Sone Aluko"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4007504"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_4081"}

{:event/type "foulcommit"
:event/elapsed 26
:event/subtype "hands"
:event/player1 "David Meyler"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4007508"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_4081"}

{:event/type "card"
:event/elapsed 26
:event/card_type "y"
:event/player1 "David Meyler"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_4007510"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Branislav Ivanovic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4007521"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_4081"}

{:event/type "shotoff"
:event/elapsed 27
:event/subtype "deflected"
:event/player1 "Diego Costa"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4007527"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_4081"}

{:event/type "corner"
:event/elapsed 27
:event/subtype "cross_right"
:event/player1 "Willian"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4007534"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_4081"}

{:event/type "shotoff"
:event/elapsed 27
:event/subtype "header"
:event/player1 "Gary Cahill"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4007535"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_4081"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Ahmed El Mohamady"
:event/subtype "trip"
:event/player1 "Oscar"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4007559"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_4081"}

{:event/type "foulcommit"
:event/elapsed 31
:event/subtype "diving"
:event/player1 "Willian"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4007582"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_4081"}

{:event/type "card"
:event/elapsed 31
:event/card_type "y"
:event/player1 "Willian"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4007584"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_4081"}

{:event/type "corner"
:event/elapsed 32
:event/subtype "cross_right"
:event/player1 "Sone Aluko"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4007597"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Andrew Robertson"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4007657"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "David Meyler"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4007666"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_4081"}

{:event/type "shotoff"
:event/elapsed 36
:event/subtype "header"
:event/player1 "Nikica Jelavic"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4007670"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_4081"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Sone Aluko"
:event/subtype "serious_foul"
:event/player1 "Gary Cahill"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4007723"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_4081"}

{:event/type "card"
:event/elapsed 38
:event/card_type "y"
:event/player1 "Gary Cahill"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4007727"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_4081"}

{:event/type "shoton"
:event/elapsed 40
:event/subtype "blocked_shot"
:event/player1 "Nikica Jelavic"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4007780"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Andrew Robertson"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4007784"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_4081"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Willian"
:event/subtype "pull"
:event/player1 "Andrew Robertson"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4007832"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4007836"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_4081"}

{:event/type "corner"
:event/elapsed 42
:event/subtype "cross_right"
:event/player1 "Willian"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_4007853"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Filipe Luis"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4007873"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "John Obi Mikel"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4007905"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_4081"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Sone Aluko"
:event/subtype "pull"
:event/player1 "John Obi Mikel"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4007919"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Jake Livermore"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4007929"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Andrew Robertson"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4007932"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_4081"}

{:event/type "shotoff"
:event/elapsed 45
:event/subtype "volley"
:event/player1 "Ahmed El Mohamady"
:event/sortorder 5
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4007940"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_4081"}

{:event/type "foulcommit"
:event/elapsed 46
:event/player2 "David Meyler"
:event/subtype "trip"
:event/player1 "John Obi Mikel"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4008191"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Tom Huddlestone"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4008207"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Filipe Luis"
:event/sortorder 9
:event/team "home"
:event/event_type "cross"
:event/id "event_4007979"
:event/minute 47
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Ahmed El Mohamady"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4008270"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_4081"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Gary Cahill"
:event/subtype "trip"
:event/player1 "Sone Aluko"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4008311"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_4081"}

{:event/type "shotoff"
:event/elapsed 51
:event/subtype "shot"
:event/player1 "Jake Livermore"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4008351"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_4081"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Branislav Ivanovic"
:event/subtype "trip"
:event/player1 "David Meyler"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4008382"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Oscar"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4008385"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Filipe Luis"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4008424"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Oscar"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4008432"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_4081"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Willian"
:event/subtype "trip"
:event/player1 "Jake Livermore"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4008450"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4008458"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_4081"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Willian"
:event/subtype "from_behind"
:event/player1 "Alex Bruce"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4008478"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_4081"}

{:event/type "card"
:event/elapsed 57
:event/card_type "y"
:event/player1 "Alex Bruce"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_4008494"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Nemanja Matic"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4008514"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_4081"}

{:event/type "foulcommit"
:event/elapsed 58
:event/subtype "diving"
:event/player1 "Diego Costa"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4008538"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_4081"}

{:event/type "card"
:event/elapsed 58
:event/card_type "y"
:event/player1 "Diego Costa"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_4008543"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Andrew Robertson"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4008580"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_4081"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player2 "Eden Hazard"
:event/subtype "pushing"
:event/player1 "James Chester"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4008587"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_4081"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player2 "Filipe Luis"
:event/subtype "serious_foul"
:event/player1 "Tom Huddlestone"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4008597"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_4081"}

{:event/type "card"
:event/elapsed 61
:event/card_type "r"
:event/player1 "Tom Huddlestone"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_4008601"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_4081"}

{:event/type "shoton"
:event/elapsed 63
:event/subtype "shot"
:event/player1 "Oscar"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4008669"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_4081"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Oscar"
:event/subtype "trip"
:event/player1 "James Chester"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4008771"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_4081"}

{:event/type "card"
:event/elapsed 67
:event/card_type "y"
:event/player1 "James Chester"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4008777"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4008797"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_4081"}

{:event/type "corner"
:event/elapsed 68
:event/subtype "short_left"
:event/player1 "Willian"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4008806"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4008809"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_4081"}

{:event/type "goal"
:event/elapsed 68
:event/player2 "Eden Hazard"
:event/subtype "shot"
:event/player1 "Diego Costa"
:event/sortorder 5
:event/team "home"
:event/id "event_4008819"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_4081"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Curtis Davies"
:event/subtype "trip"
:event/player1 "Diego Costa"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4008879"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Filipe Luis"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4008869"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_4081"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Branislav Ivanovic"
:event/subtype "trip"
:event/player1 "Robert Brady"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4008876"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Nemanja Matic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4008884"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_4081"}

{:event/type "corner"
:event/elapsed 73
:event/subtype "short_left"
:event/player1 "Eden Hazard"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4008894"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_4081"}

{:event/type "shoton"
:event/elapsed 73
:event/subtype "blocked_shot"
:event/player1 "Oscar"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4008897"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_4081"}

{:event/type "shoton"
:event/elapsed 73
:event/subtype "blocked_shot"
:event/player1 "Oscar"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4008904"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_4081"}

{:event/type "shotoff"
:event/elapsed 73
:event/subtype "deflected"
:event/player1 "Gary Cahill"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4008908"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Branislav Ivanovic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4008953"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Robert Brady"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4008961"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_4081"}

{:event/type "shoton"
:event/elapsed 78
:event/subtype "blocked_shot"
:event/player1 "Diego Costa"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4008981"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_4081"}

{:event/type "shotoff"
:event/elapsed 78
:event/subtype "shot"
:event/player1 "Branislav Ivanovic"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4008983"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4009016"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_4081"}

{:event/type "corner"
:event/elapsed 80
:event/subtype "short_left"
:event/player1 "Eden Hazard"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4009033"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Filipe Luis"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4009037"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_4081"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "David Meyler"
:event/subtype "trip"
:event/player1 "Branislav Ivanovic"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4009050"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_4081"}

{:event/type "shoton"
:event/elapsed 84
:event/subtype "blocked_shot"
:event/player1 "Andre Schuerrle"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4009096"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_4081"}

{:event/type "shoton"
:event/elapsed 86
:event/subtype "blocked_shot"
:event/player1 "Andre Schuerrle"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4009129"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_4081"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Gaston Ramirez"
:event/subtype "trip"
:event/player1 "Nemanja Matic"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4009137"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_4081"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Robert Brady"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4009147"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_4081"}

{:event/type "foulcommit"
:event/elapsed 87
:event/player2 "Ahmed El Mohamady"
:event/subtype "dangerous_play"
:event/player1 "Diego Costa"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4009155"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_4081"}

{:event/type "shotoff"
:event/elapsed 88
:event/subtype "direct_freekick"
:event/player1 "Robert Brady"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4009187"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_4081"}

{:event/type "corner"
:event/elapsed 89
:event/subtype "cross_left"
:event/player1 "Robert Brady"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4009194"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_4081"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Ahmed El Mohamady"
:event/subtype "trip"
:event/player1 "Filipe Luis"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4009222"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_4081"}

{:event/type "corner"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross_left"
:event/player1 "Robert Brady"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_4009237"
:event/minute 91
:event/match_id "match_4081"}


]

