
;;# data
[
{:match/id "match_4069"
:match/league "England Premier League"
:match/hometeam "Aston Villa"
:match/awayteam "Leicester City"
:match/score "2:1"
:match/hometeam_goals "2"
:match/awayteam_goals "1"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Aly Cissokho"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3996336"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_4069"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Jeffrey Schlupp"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3996388"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_4069"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Jamie Vardy"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3996400"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_4069"}

{:event/type "shotoff"
:event/elapsed 10
:event/subtype "distance"
:event/player1 "Matthew James"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3996401"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_4069"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Aly Cissokho"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_3996411"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_4069"}

{:event/type "shotoff"
:event/elapsed 11
:event/subtype "distance"
:event/player1 "Christian Benteke"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3996415"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_4069"}

{:event/type "shotoff"
:event/elapsed 12
:event/subtype "big chance shot"
:event/player1 "Christian Benteke"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3996439"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_4069"}

{:event/type "shoton"
:event/elapsed 13
:event/subtype "distance"
:event/player1 "Riyad Mahrez"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3996458"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_4069"}

{:event/type "goal"
:event/elapsed 13
:event/subtype "tap_in"
:event/player1 "Jose Leonardo Ulloa"
:event/sortorder 2
:event/team "away"
:event/id "event_3996459"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_4069"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Gabriel Agbonlahor"
:event/player1 "Danny Simpson"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3996492"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_4069"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Gabriel Agbonlahor"
:event/player1 "Marcin Wasilewski"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3996520"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_4069"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Ashley R. Westwood"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3996532"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_4069"}

{:event/type "goal"
:event/elapsed 18
:event/player2 "Ashley R. Westwood"
:event/subtype "header"
:event/player1 "Ciaran Clark"
:event/sortorder 0
:event/team "home"
:event/id "event_3996534"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_4069"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Christian Benteke"
:event/player1 "Marcin Wasilewski"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3996560"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_4069"}

{:event/type "shoton"
:event/elapsed 21
:event/subtype "shot"
:event/player1 "Riyad Mahrez"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3996584"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_4069"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Alan Hutton"
:event/player1 "Jamie Vardy"
:event/sortorder 9
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3996620"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_4069"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Tom Cleverley"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3996629"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_4069"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Jeffrey Schlupp"
:event/player1 "Alan Hutton"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3996654"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_4069"}

{:event/type "shoton"
:event/elapsed 26
:event/subtype "blocked_shot"
:event/player1 "Gabriel Agbonlahor"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3996662"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_4069"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Aly Cissokho"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3996676"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_4069"}

{:event/type "shotoff"
:event/elapsed 31
:event/subtype "shot"
:event/player1 "Jeffrey Schlupp"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3996755"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_4069"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Riyad Mahrez"
:event/player1 "Aly Cissokho"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3996787"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_4069"}

{:event/type "foulcommit"
:event/elapsed 34
:event/player2 "Danny Simpson"
:event/player1 "Charles N'Zogbia"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3996803"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_4069"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Matthew James"
:event/player1 "Charles N'Zogbia"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3996818"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_4069"}

{:event/type "card"
:event/elapsed 35
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Charles N'Zogbia"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_3996821"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_4069"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Riyad Mahrez"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3996824"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_4069"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Paul Konchesky"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_3996831"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_4069"}

{:event/type "corner"
:event/elapsed 36
:event/subtype "cross_left"
:event/player1 "Matthew James"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3996835"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_4069"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Jeffrey Schlupp"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3996850"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_4069"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Riyad Mahrez"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_3996854"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_4069"}

{:event/type "shoton"
:event/elapsed 39
:event/subtype "blocked_shot"
:event/player1 "Christian Benteke"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3996889"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_4069"}

{:event/type "corner"
:event/elapsed 39
:event/subtype "cross_right"
:event/player1 "Ashley R. Westwood"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3996898"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_4069"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Jores Okore"
:event/player1 "Jose Leonardo Ulloa"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3996910"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_4069"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Ashley R. Westwood"
:event/player1 "Jamie Vardy"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3996923"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_4069"}

{:event/type "card"
:event/elapsed 41
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Jamie Vardy"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_3996926"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_4069"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Charles N'Zogbia"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3996978"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_4069"}

{:event/type "foulcommit"
:event/elapsed 46
:event/player2 "Gabriel Agbonlahor"
:event/player1 "Danny Simpson"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3997171"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_4069"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Tom Cleverley"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_3997177"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_4069"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Alan Hutton"
:event/player1 "Jeffrey Schlupp"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3997198"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_4069"}

{:event/type "shotoff"
:event/elapsed 48
:event/subtype "shot"
:event/player1 "Tom Cleverley"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3997203"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_4069"}

{:event/type "foulcommit"
:event/elapsed_plus 4
:event/elapsed 45
:event/player2 "Jose Leonardo Ulloa"
:event/player1 "Gabriel Agbonlahor"
:event/sortorder 8
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3997037"
:event/minute 49
:event/match_id "match_4069"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Gabriel Agbonlahor"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3997222"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_4069"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Aly Cissokho"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3997227"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_4069"}

{:event/type "foulcommit"
:event/elapsed_plus 5
:event/elapsed 45
:event/player1 "Jose Leonardo Ulloa"
:event/sortorder 10
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3997053"
:event/minute 50
:event/match_id "match_4069"}

{:event/type "shotoff"
:event/elapsed 51
:event/subtype "shot"
:event/player1 "Jeffrey Schlupp"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3997236"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_4069"}

{:event/type "shoton"
:event/elapsed 52
:event/subtype "blocked_shot"
:event/player1 "Kieran Richardson"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3997256"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_4069"}

{:event/type "corner"
:event/elapsed 52
:event/subtype "cross_left"
:event/player1 "Tom Cleverley"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3997258"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_4069"}

{:event/type "shoton"
:event/elapsed 54
:event/subtype "big chance shot"
:event/player1 "Christian Benteke"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_3997279"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_4069"}

{:event/type "corner"
:event/elapsed 54
:event/subtype "cross_left"
:event/player1 "Charles N'Zogbia"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_3997282"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_4069"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Kieran Richardson"
:event/player1 "Riyad Mahrez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3997301"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_4069"}

{:event/type "foulcommit"
:event/elapsed 56
:event/subtype "hands"
:event/player1 "Christian Benteke"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3997302"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_4069"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Gabriel Agbonlahor"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3997307"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_4069"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Riyad Mahrez"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3997332"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_4069"}

{:event/type "foulcommit"
:event/elapsed 59
:event/player2 "Gabriel Agbonlahor"
:event/player1 "Esteban Cambiasso"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3997335"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_4069"}

{:event/type "card"
:event/elapsed 59
:event/card_type "y"
:event/subtype "emergency_brake"
:event/player1 "Esteban Cambiasso"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_3997337"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_4069"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Alan Hutton"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_3997340"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_4069"}

{:event/type "shotoff"
:event/elapsed 60
:event/subtype "header"
:event/player1 "Gabriel Agbonlahor"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3997343"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_4069"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Alan Hutton"
:event/player1 "Jeffrey Schlupp"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3997355"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_4069"}

{:event/type "card"
:event/elapsed 61
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Jeffrey Schlupp"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_3997358"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_4069"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Jeffrey Schlupp"
:event/player1 "Gabriel Agbonlahor"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3997368"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_4069"}

{:event/type "corner"
:event/elapsed 65
:event/subtype "cross_left"
:event/player1 "Jack Grealish"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3997424"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_4069"}

{:event/type "shoton"
:event/elapsed 69
:event/subtype "distance"
:event/player1 "David Nugent"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3997459"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_4069"}

{:event/type "corner"
:event/elapsed 69
:event/subtype "cross_left"
:event/player1 "Matthew James"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3997470"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_4069"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "David Nugent"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3997496"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_4069"}

{:event/type "goal"
:event/elapsed 71
:event/player2 "Christian Benteke"
:event/subtype "shot"
:event/player1 "Alan Hutton"
:event/sortorder 5
:event/team "home"
:event/id "event_3997500"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_4069"}

{:event/type "card"
:event/elapsed 71
:event/card_type "y"
:event/player1 "Marcin Wasilewski"
:event/sortorder 9
:event/team "away"
:event/event_type "card"
:event/id "event_3997519"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_4069"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Danny Simpson"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3997515"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_4069"}

{:event/type "corner"
:event/elapsed 73
:event/subtype "cross_right"
:event/player1 "Riyad Mahrez"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3997529"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_4069"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Riyad Mahrez"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3997537"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_4069"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Aly Cissokho"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_3997546"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_4069"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Jeffrey Schlupp"
:event/player1 "Carlos Sanchez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3997554"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_4069"}

{:event/type "card"
:event/elapsed 75
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Carlos Sanchez"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_3997558"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_4069"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Matthew James"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3997563"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_4069"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Jack Grealish"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3997583"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_4069"}

{:event/type "shoton"
:event/elapsed 77
:event/subtype "big chance header"
:event/player1 "Christian Benteke"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3997584"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_4069"}

{:event/type "corner"
:event/elapsed 77
:event/subtype "cross_right"
:event/player1 "Jack Grealish"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3997586"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_4069"}

{:event/type "shoton"
:event/elapsed 77
:event/subtype "big chance header"
:event/player1 "Ciaran Clark"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_3997589"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_4069"}

{:event/type "foulcommit"
:event/elapsed 78
:event/player2 "Jores Okore"
:event/player1 "unknown"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3997602"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_4069"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Alan Hutton"
:event/subtype "serious_foul"
:event/player1 "Paul Konchesky"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3997619"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_4069"}

{:event/type "card"
:event/elapsed 80
:event/card_type "r"
:event/player1 "Paul Konchesky"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_3997628"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_4069"}

{:event/type "card"
:event/elapsed 81
:event/card_type "y"
:event/subtype "violence"
:event/player1 "Alan Hutton"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3997633"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_4069"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Marc Albrighton"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3997639"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_4069"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "David Nugent"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3997646"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_4069"}

{:event/type "shoton"
:event/elapsed 83
:event/subtype "blocked_shot"
:event/player1 "Matthew James"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3997650"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_4069"}

{:event/type "corner"
:event/elapsed 83
:event/subtype "cross_right"
:event/player1 "Esteban Cambiasso"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_3997654"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_4069"}

{:event/type "corner"
:event/elapsed 83
:event/subtype "cross_left"
:event/player1 "Matthew James"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_3997659"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_4069"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Riyad Mahrez"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3997668"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_4069"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Gabriel Agbonlahor"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3997683"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_4069"}

{:event/type "shoton"
:event/elapsed 84
:event/subtype "blocked_shot"
:event/player1 "Jack Grealish"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_3997686"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_4069"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Matthew James"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3997710"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_4069"}

{:event/type "shoton"
:event/elapsed 88
:event/subtype "blocked_shot"
:event/player1 "Kieran Richardson"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3997757"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_4069"}

{:event/type "shotoff"
:event/elapsed 89
:event/subtype "bicycle_kick"
:event/player1 "Esteban Cambiasso"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3997766"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_4069"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Marcin Wasilewski"
:event/player1 "Gabriel Agbonlahor"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3997779"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_4069"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Gabriel Agbonlahor"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_3997781"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_4069"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Matthew James"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_3997785"
:event/minute 91
:event/match_id "match_4069"}

{:event/type "shotoff"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "distance"
:event/player1 "unknown"
:event/sortorder 8
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3997814"
:event/minute 94
:event/match_id "match_4069"}


]

