
;;# data
[
{:match/id "match_10053"
:match/league "Germany 1. Bundesliga"
:match/hometeam "Eintracht Frankfurt"
:match/awayteam "FC Augsburg"
:match/score "1:1"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Makoto Hasebe"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4695119"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_10053"}

{:event/type "shotoff"
:event/elapsed 2
:event/subtype "header"
:event/player1 "Joel Gerezgiher"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4695123"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_10053"}

{:event/type "shotoff"
:event/elapsed 4
:event/subtype "distance"
:event/player1 "Tobias Werner"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4695157"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Daniel Baier"
:event/player1 "Haris Seferovic"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4695181"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Bastian Oczipka"
:event/player1 "Caiuby"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4695202"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_10053"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Makoto Hasebe"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4695220"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Carlos Zambrano"
:event/player1 "Caiuby"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4695231"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_10053"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Joel Gerezgiher"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4695240"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Jeong-Ho Hong"
:event/subtype "dangerous_play"
:event/player1 "Haris Seferovic"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4695305"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_10053"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Stefan Aigner"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4695244"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_10053"}

{:event/type "shoton"
:event/elapsed 11
:event/subtype "shot"
:event/player1 "Halil Altintop"
:event/sortorder 5
:event/team "away"
:event/event_type "shoton"
:event/id "event_4695251"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_10053"}

{:event/type "corner"
:event/elapsed 12
:event/subtype "cross_left"
:event/player1 "Konstantinos Stafylidis"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4695255"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_10053"}

{:event/type "shotoff"
:event/elapsed 14
:event/subtype "distance"
:event/player1 "Tobias Werner"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4695279"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Alexander Esswein"
:event/player1 "David Abraham"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4696064"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Paul Verhaegh"
:event/player1 "Joel Gerezgiher"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4695329"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_10053"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Dominik Kohr"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4695339"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Jeong-Ho Hong"
:event/player1 "Luc Castaignos"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4696056"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_10053"}

{:event/type "corner"
:event/elapsed 19
:event/subtype "cross_right"
:event/player1 "Tobias Werner"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4695350"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Alexander Esswein"
:event/subtype "trip"
:event/player1 "Makoto Hasebe"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4695363"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_10053"}

{:event/type "card"
:event/elapsed 20
:event/card_type "y"
:event/player1 "Makoto Hasebe"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_4695366"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Makoto Hasebe"
:event/player1 "Halil Altintop"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4695381"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Haris Seferovic"
:event/player1 "Konstantinos Stafylidis"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4695392"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_10053"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Joel Gerezgiher"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4695389"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_10053"}

{:event/type "shotoff"
:event/elapsed 22
:event/subtype "header"
:event/player1 "Stefan Reinartz"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4695391"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_10053"}

{:event/type "goal"
:event/elapsed 24
:event/player2 "Halil Altintop"
:event/subtype "distance"
:event/player1 "Caiuby"
:event/sortorder 0
:event/team "away"
:event/id "event_4695396"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Daniel Baier"
:event/player1 "Haris Seferovic"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4696037"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Halil Altintop"
:event/subtype "serious_foul"
:event/player1 "Stefan Reinartz"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4695424"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Stefan Aigner"
:event/player1 "Tobias Werner"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4695448"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 30
:event/player2 "Daniel Baier"
:event/player1 "Stefan Aigner"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4695473"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_10053"}

{:event/type "shotoff"
:event/elapsed 31
:event/subtype "shot"
:event/player1 "Tobias Werner"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4695506"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Carlos Zambrano"
:event/player1 "Caiuby"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4695562"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Carlos Zambrano"
:event/player1 "Caiuby"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4696015"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Luc Castaignos"
:event/player1 "Ragnar Klavan"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4695595"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_10053"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Bastian Oczipka"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4695608"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_10053"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Joel Gerezgiher"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4695614"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_10053"}

{:event/type "shoton"
:event/elapsed 36
:event/subtype "blocked_shot"
:event/player1 "Haris Seferovic"
:event/sortorder 5
:event/team "home"
:event/event_type "shoton"
:event/id "event_4695628"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Dominik Kohr"
:event/player1 "Stefan Reinartz"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4696002"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_10053"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Tobias Werner"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4695700"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Marco Russ"
:event/player1 "Ragnar Klavan"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4695939"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Alexander Esswein"
:event/subtype "pushing"
:event/player1 "Makoto Hasebe"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4695729"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_10053"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Joel Gerezgiher"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4695752"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_10053"}

{:event/type "shoton"
:event/elapsed 42
:event/subtype "shot"
:event/player1 "Marco Russ"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4695764"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Carlos Zambrano"
:event/player1 "Alexander Esswein"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4695946"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_10053"}

{:event/type "corner"
:event/elapsed 42
:event/subtype "cross_left"
:event/player1 "Stefan Reinartz"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4695770"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Carlos Zambrano"
:event/player1 "Tobias Werner"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4695991"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Marco Russ"
:event/player1 "Dominik Kohr"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4695830"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_10053"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Stefan Aigner"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4695839"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_10053"}

{:event/type "corner"
:event/elapsed 45
:event/subtype "cross_right"
:event/player1 "Joel Gerezgiher"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4695847"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 47
:event/player2 "Daniel Baier"
:event/subtype "dangerous_play"
:event/player1 "Haris Seferovic"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4696145"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Bastian Oczipka"
:event/player1 "Alexander Esswein"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4696165"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_10053"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Timothy Chandler"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4696175"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Halil Altintop"
:event/subtype "from_behind"
:event/player1 "Carlos Zambrano"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4696231"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Makoto Hasebe"
:event/subtype "serious_foul"
:event/player1 "Dominik Kohr"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4696296"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_10053"}

{:event/type "card"
:event/elapsed 53
:event/card_type "y"
:event/player1 "Dominik Kohr"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_4696302"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_10053"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Timothy Chandler"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4696324"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_10053"}

{:event/type "shotoff"
:event/elapsed 55
:event/subtype "big chance shot"
:event/player1 "Haris Seferovic"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4696350"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_10053"}

{:event/type "corner"
:event/elapsed 58
:event/subtype "cross_right"
:event/player1 "Bastian Oczipka"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4696428"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_10053"}

{:event/type "shoton"
:event/elapsed 58
:event/subtype "distance"
:event/player1 "Timothy Chandler"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4696439"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_10053"}

{:event/type "corner"
:event/elapsed 59
:event/subtype "cross_left"
:event/player1 "Bastian Oczipka"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4696444"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_10053"}

{:event/type "shotoff"
:event/elapsed 59
:event/subtype "distance"
:event/player1 "Timothy Chandler"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4696451"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player2 "Ragnar Klavan"
:event/player1 "Luc Castaignos"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4696493"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Marco Russ"
:event/player1 "Halil Altintop"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4696529"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_10053"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Haris Seferovic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4696549"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_10053"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Makoto Hasebe"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4696554"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Daniel Baier"
:event/player1 "Makoto Hasebe"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4696559"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_10053"}

{:event/type "shotoff"
:event/elapsed 64
:event/subtype "distance"
:event/player1 "Alexander Esswein"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4696576"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "David Abraham"
:event/player1 "Caiuby"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4696593"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_10053"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Stefan Aigner"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4696610"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_10053"}

{:event/type "corner"
:event/elapsed 66
:event/subtype "cross_right"
:event/player1 "Makoto Hasebe"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4696615"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_10053"}

{:event/type "shotoff"
:event/elapsed 66
:event/subtype "header"
:event/player1 "Luc Castaignos"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4696617"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_10053"}

{:event/type "shotoff"
:event/elapsed 67
:event/subtype "shot"
:event/player1 "Alexander Esswein"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4696629"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Ragnar Klavan"
:event/player1 "Luc Castaignos"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4696650"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_10053"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Haris Seferovic"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4696675"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_10053"}

{:event/type "shoton"
:event/elapsed 72
:event/subtype "deflected"
:event/player1 "Dong-Won Ji"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4696698"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_10053"}

{:event/type "corner"
:event/elapsed 73
:event/subtype "cross_right"
:event/player1 "Tobias Werner"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4696710"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_10053"}

{:event/type "shoton"
:event/elapsed 73
:event/subtype "shot"
:event/player1 "Tobias Werner"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4696713"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_10053"}

{:event/type "corner"
:event/elapsed 73
:event/subtype "cross_right"
:event/player1 "Tobias Werner"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4696717"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_10053"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Alexander Esswein"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4696749"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_10053"}

{:event/type "corner"
:event/elapsed 78
:event/subtype "cross_right"
:event/player1 "Gian-Luca Waldschmidt"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4696800"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 79
:event/player2 "Timothy Chandler"
:event/player1 "Konstantinos Stafylidis"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4696938"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_10053"}

{:event/type "shotoff"
:event/elapsed 79
:event/subtype "big chance shot"
:event/player1 "Stefan Aigner"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4696826"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_10053"}

{:event/type "shoton"
:event/elapsed 81
:event/subtype "big chance shot"
:event/player1 "Dong-Won Ji"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4696881"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Haris Seferovic"
:event/player1 "Dominik Kohr"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4696900"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_10053"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Timothy Chandler"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4696913"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_10053"}

{:event/type "corner"
:event/elapsed 82
:event/subtype "cross_right"
:event/player1 "Gian-Luca Waldschmidt"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4696918"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_10053"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Marco Russ"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4696959"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_10053"}

{:event/type "shotoff"
:event/elapsed 84
:event/subtype "distance"
:event/player1 "Konstantinos Stafylidis"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4696985"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_10053"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Timothy Chandler"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4697006"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Dong-Won Ji"
:event/player1 "Timothy Chandler"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4697130"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Carlos Zambrano"
:event/player1 "Daniel Baier"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4697178"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_10053"}

{:event/type "shoton"
:event/elapsed 85
:event/subtype "big chance shot"
:event/player1 "Tobias Werner"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4697033"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_10053"}

{:event/type "goal"
:event/elapsed 86
:event/player2 "Gian-Luca Waldschmidt"
:event/subtype "shot"
:event/player1 "Marco Russ"
:event/sortorder 0
:event/team "home"
:event/id "event_4697055"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_10053"}

{:event/type "card"
:event/elapsed 89
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Paul Verhaegh"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_4697137"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_10053"}

{:event/type "card"
:event/elapsed 89
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Carlos Zambrano"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4697140"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Aleksandar Ignjovski"
:event/subtype "dangerous_play"
:event/player1 "Markus Feulner"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4697213"
:event/minute 92
:event/match_id "match_10053"}

{:event/type "card"
:event/elapsed_plus 2
:event/elapsed 90
:event/card_type "y"
:event/player1 "Markus Feulner"
:event/sortorder 4
:event/team "away"
:event/event_type "card"
:event/id "event_4697216"
:event/minute 92
:event/match_id "match_10053"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Bastian Oczipka"
:event/player1 "Sascha Moelders"
:event/sortorder 7
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4697295"
:event/minute 92
:event/match_id "match_10053"}


]

