
;;# data
[
{:match/id "match_23055"
:match/league "Spain LIGA BBVA"
:match/hometeam "Real Madrid CF"
:match/awayteam "Real Zaragoza"
:match/score "4:0"
:match/hometeam_goals "4"
:match/awayteam_goals "0"}

{:event/type "goal"
:event/elapsed 23
:event/player1 "Gonzalo Higuain"
:event/sortorder 0
:event/team "home"
:event/id "event_2457073"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_23055"}

{:event/type "goal"
:event/elapsed 25
:event/player1 "Angel Di Maria"
:event/sortorder 0
:event/team "home"
:event/id "event_2457078"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_23055"}

{:event/type "card"
:event/elapsed 37
:event/card_type "y"
:event/player1 "Luka Modric"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2457094"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_23055"}

{:event/type "card"
:event/elapsed 65
:event/card_type "y"
:event/player1 "Sergio Ramos"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2457148"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_23055"}

{:event/type "card"
:event/elapsed 70
:event/card_type "y"
:event/player1 "Abraham Minero"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2457151"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_23055"}

{:event/type "card"
:event/elapsed 76
:event/card_type "y"
:event/player1 "Cristian Sapunaru"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2457171"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_23055"}

{:event/type "goal"
:event/elapsed 89
:event/player1 "Michael Essien"
:event/sortorder 0
:event/team "home"
:event/id "event_2457180"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_23055"}

{:event/type "goal"
:event/elapsed 90
:event/player1 "Luka Modric"
:event/sortorder 0
:event/team "home"
:event/id "event_2457183"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_23055"}


]

