
;;# data
[
{:match/id "match_7067"
:match/league "France Ligue 1"
:match/hometeam "OGC Nice"
:match/awayteam "SC Bastia"
:match/score "0:1"
:match/hometeam_goals "0"
:match/awayteam_goals "1"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Carlos Eduardo"
:event/subtype "dangerous_play"
:event/player1 "Christopher Maboulou"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3846994"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_7067"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Gregoire Puel"
:event/subtype "serious_foul"
:event/player1 "Mathieu Philippe Peybernes"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3846998"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Carlos Eduardo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3847012"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_7067"}

{:event/type "foulcommit"
:event/elapsed 8
:event/player2 "Drissa Diakite"
:event/subtype "pushing"
:event/player1 "Niklas Hult"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3847088"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_7067"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Mathieu Bodmer"
:event/subtype "pull"
:event/player1 "Floyd Ayite"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3847131"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Jordan Amavi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3847151"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_7067"}

{:event/type "shoton"
:event/elapsed 12
:event/subtype "header"
:event/player1 "Alexy Bosetti"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3847154"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Francois Kamano"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3847158"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_7067"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Julien Palmieri"
:event/subtype "trip"
:event/player1 "Valentin Eysseric"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3847177"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Gregoire Puel"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3847238"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_7067"}

{:event/type "corner"
:event/elapsed 18
:event/subtype "cross_right"
:event/player1 "Valentin Eysseric"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3847247"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_7067"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Drissa Diakite"
:event/subtype "pushing"
:event/player1 "Souleymane Diawara"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3847252"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Gregoire Puel"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3847274"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_7067"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Francois Kamano"
:event/subtype "trip"
:event/player1 "Nampalys Mendy"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3847292"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_7067"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Floyd Ayite"
:event/subtype "trip"
:event/player1 "Jordan Amavi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3847302"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_7067"}

{:event/type "shoton"
:event/elapsed 22
:event/subtype "direct_freekick"
:event/player1 "Francois Kamano"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3847320"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_7067"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Drissa Diakite"
:event/subtype "trip"
:event/player1 "Niklas Hult"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3847330"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_7067"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Nampalys Mendy"
:event/subtype "trip"
:event/player1 "Hervin Ongenda"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3847337"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_7067"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Gregoire Puel"
:event/subtype "trip"
:event/player1 "Hervin Ongenda"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3847358"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_7067"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Ryad Boudebouz"
:event/subtype "dangerous_play"
:event/player1 "Nampalys Mendy"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3847363"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_7067"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Julien Palmieri"
:event/subtype "trip"
:event/player1 "Valentin Eysseric"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3847373"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_7067"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Francois Kamano"
:event/subtype "pushing"
:event/player1 "Jordan Amavi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3847409"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Carlos Eduardo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3847421"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_7067"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Hervin Ongenda"
:event/subtype "trip"
:event/player1 "Carlos Eduardo"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3847426"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Alexy Bosetti"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_3847429"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Niklas Hult"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3847433"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Jordan Amavi"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_3847437"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_7067"}

{:event/type "corner"
:event/elapsed 32
:event/subtype "cross_left"
:event/player1 "Valentin Eysseric"
:event/sortorder 5
:event/team "home"
:event/event_type "corner"
:event/id "event_3847448"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Christopher Maboulou"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3847456"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Julien Palmieri"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3847479"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Alexy Bosetti"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3847487"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_7067"}

{:event/type "shotoff"
:event/elapsed 36
:event/subtype "bad shot"
:event/player1 "Gregoire Puel"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3847490"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_7067"}

{:event/type "shotoff"
:event/elapsed 36
:event/subtype "distance"
:event/player1 "Francois Kamano"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3847498"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_7067"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Drissa Diakite"
:event/subtype "pull"
:event/player1 "Jordan Amavi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3847512"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_7067"}

{:event/type "card"
:event/elapsed 38
:event/card_type "y"
:event/player1 "Jordan Amavi"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_3847516"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Gregoire Puel"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3847531"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_7067"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Valentin Eysseric"
:event/subtype "trip"
:event/player1 "Guillaume Gillet"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3847541"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_7067"}

{:event/type "shotoff"
:event/elapsed 40
:event/subtype "distance"
:event/player1 "Jordan Amavi"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3847544"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_7067"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Niklas Hult"
:event/subtype "pushing"
:event/player1 "Drissa Diakite"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3847557"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_7067"}

{:event/type "card"
:event/elapsed 41
:event/card_type "y"
:event/player1 "Drissa Diakite"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_3847558"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_7067"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Carlos Eduardo"
:event/subtype "trip"
:event/player1 "Guillaume Gillet"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3847604"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Valentin Eysseric"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3847614"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_7067"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "Francois Kamano"
:event/subtype "trip"
:event/player1 "Carlos Eduardo"
:event/sortorder 6
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3847622"
:event/minute 46
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Christopher Maboulou"
:event/sortorder 9
:event/team "away"
:event/event_type "cross"
:event/id "event_3847634"
:event/minute 46
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Drissa Diakite"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3847740"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_7067"}

{:event/type "shotoff"
:event/elapsed 49
:event/subtype "shot"
:event/player1 "Floyd Ayite"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3847776"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Floyd Ayite"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3847798"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_7067"}

{:event/type "goal"
:event/elapsed 51
:event/subtype "shot"
:event/player1 "Floyd Ayite"
:event/sortorder 4
:event/team "away"
:event/id "event_3847812"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Alexy Bosetti"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3847824"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_7067"}

{:event/type "corner"
:event/elapsed 53
:event/subtype "cross_left"
:event/player1 "Valentin Eysseric"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3847826"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_7067"}

{:event/type "shoton"
:event/elapsed 53
:event/subtype "blocked_shot"
:event/player1 "Mathieu Bodmer"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_3847827"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Carlos Eduardo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3847862"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_7067"}

{:event/type "shoton"
:event/elapsed 56
:event/subtype "shot"
:event/player1 "Valentin Eysseric"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3847867"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_7067"}

{:event/type "card"
:event/elapsed 57
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Ryad Boudebouz"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3847881"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_7067"}

{:event/type "card"
:event/elapsed 57
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Alexy Bosetti"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_3847883"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Gregoire Puel"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3847893"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Francois Kamano"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3847909"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_7067"}

{:event/type "shoton"
:event/elapsed 60
:event/subtype "blocked_shot"
:event/player1 "Didier Digard"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3847934"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Eric Bautheac"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_3847975"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_7067"}

{:event/type "shoton"
:event/elapsed 63
:event/subtype "blocked_shot"
:event/player1 "Didier Digard"
:event/sortorder 5
:event/team "home"
:event/event_type "shoton"
:event/id "event_3847979"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Gregoire Puel"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3847982"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Eric Bautheac"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3848005"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_7067"}

{:event/type "shotoff"
:event/elapsed 66
:event/subtype "distance"
:event/player1 "Souleymane Diawara"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3848015"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_7067"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Carlos Eduardo"
:event/subtype "trip"
:event/player1 "Gadji Tallo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3848029"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_7067"}

{:event/type "shoton"
:event/elapsed 67
:event/subtype "direct_freekick"
:event/player1 "Eric Bautheac"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3848041"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_7067"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Jordan Amavi"
:event/subtype "trip"
:event/player1 "Floyd Ayite"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3848051"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_7067"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Hervin Ongenda"
:event/subtype "trip"
:event/player1 "Alassane Plea"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3848071"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_7067"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Guillaume Gillet"
:event/subtype "dangerous_play"
:event/player1 "Didier Digard"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3848093"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_7067"}

{:event/type "card"
:event/elapsed 70
:event/card_type "y"
:event/player1 "Didier Digard"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_3848094"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_7067"}

{:event/type "shoton"
:event/elapsed 72
:event/subtype "distance"
:event/player1 "Eric Bautheac"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_3848109"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_7067"}

{:event/type "corner"
:event/elapsed 72
:event/subtype "cross_right"
:event/player1 "Eric Bautheac"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_3848112"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_7067"}

{:event/type "shoton"
:event/elapsed 73
:event/subtype "blocked_shot"
:event/player1 "Alassane Plea"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3848120"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_7067"}

{:event/type "corner"
:event/elapsed 73
:event/subtype "cross_right"
:event/player1 "Eric Bautheac"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3848122"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_7067"}

{:event/type "shotoff"
:event/elapsed 74
:event/subtype "distance"
:event/player1 "Nampalys Mendy"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3848134"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Gregoire Puel"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_3848142"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_7067"}

{:event/type "shotoff"
:event/elapsed 75
:event/subtype "header"
:event/player1 "Eric Bautheac"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3848147"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Alassane Plea"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3848168"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_7067"}

{:event/type "shotoff"
:event/elapsed 77
:event/subtype "big chance volley"
:event/player1 "Alexy Bosetti"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3848169"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Alassane Plea"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3848184"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_7067"}

{:event/type "corner"
:event/elapsed 78
:event/subtype "cross_right"
:event/player1 "Eric Bautheac"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3848189"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_7067"}

{:event/type "foulcommit"
:event/elapsed 79
:event/player2 "Julien Palmieri"
:event/subtype "dangerous_play"
:event/player1 "Eric Bautheac"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3848202"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_7067"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Gregoire Puel"
:event/subtype "pushing"
:event/player1 "Floyd Ayite"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3848215"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_7067"}

{:event/type "shotoff"
:event/elapsed 82
:event/subtype "shot"
:event/player1 "Alassane Plea"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3848234"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_7067"}

{:event/type "corner"
:event/elapsed 84
:event/subtype "cross_left"
:event/player1 "Eric Bautheac"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3848253"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_7067"}

{:event/type "shotoff"
:event/elapsed 84
:event/subtype "header"
:event/player1 "Didier Digard"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3848256"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_7067"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Souleymane Diawara"
:event/subtype "pull"
:event/player1 "Gadji Tallo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3848268"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Jordan Amavi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3848293"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_7067"}

{:event/type "shotoff"
:event/elapsed 88
:event/subtype "big chance shot"
:event/player1 "Valentin Eysseric"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3848298"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_7067"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Didier Digard"
:event/subtype "pushing"
:event/player1 "Gadji Tallo"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3848303"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Jordan Amavi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3848323"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Didier Digard"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3848331"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_7067"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "distance"
:event/player1 "Valentin Eysseric"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3848339"
:event/minute 91
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Didier Digard"
:event/sortorder 6
:event/team "home"
:event/event_type "cross"
:event/id "event_3848351"
:event/minute 91
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Alassane Plea"
:event/sortorder 9
:event/team "home"
:event/event_type "cross"
:event/id "event_3848361"
:event/minute 92
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Jordan Amavi"
:event/sortorder 11
:event/team "home"
:event/event_type "cross"
:event/id "event_3848368"
:event/minute 92
:event/match_id "match_7067"}

{:event/type "shoton"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Joao Rodriguez"
:event/sortorder 15
:event/team "away"
:event/event_type "shoton"
:event/id "event_3848382"
:event/minute 93
:event/match_id "match_7067"}

{:event/type "corner"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "short_left"
:event/player1 "Joao Rodriguez"
:event/sortorder 16
:event/team "away"
:event/event_type "corner"
:event/id "event_3848385"
:event/minute 93
:event/match_id "match_7067"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Didier Digard"
:event/sortorder 17
:event/team "home"
:event/event_type "cross"
:event/id "event_3848390"
:event/minute 94
:event/match_id "match_7067"}

{:event/type "shoton"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "distance"
:event/player1 "Gregoire Puel"
:event/sortorder 20
:event/team "home"
:event/event_type "shoton"
:event/id "event_3848396"
:event/minute 94
:event/match_id "match_7067"}

{:event/type "foulcommit"
:event/elapsed_plus 5
:event/elapsed 90
:event/player2 "Nampalys Mendy"
:event/subtype "pull"
:event/player1 "Joao Rodriguez"
:event/sortorder 22
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3848404"
:event/minute 95
:event/match_id "match_7067"}

{:event/type "card"
:event/elapsed_plus 6
:event/elapsed 90
:event/card_type "y"
:event/player1 "Joao Rodriguez"
:event/sortorder 23
:event/team "away"
:event/event_type "card"
:event/id "event_3848406"
:event/minute 96
:event/match_id "match_7067"}


]

