
;;# data
[
{:match/id "match_22459"
:match/league "Spain LIGA BBVA"
:match/hometeam "Real Zaragoza"
:match/awayteam "Athletic Club de Bilbao"
:match/score "2:1"
:match/hometeam_goals "2"
:match/awayteam_goals "1"}

{:event/type "goal"
:event/elapsed 18
:event/player1 "Fernando Llorente"
:event/sortorder 0
:event/team "away"
:event/id "event_1437052"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_22459"}

{:event/type "card"
:event/elapsed 24
:event/card_type "y"
:event/player1 "Javier Martinez"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1437075"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_22459"}

{:event/type "card"
:event/elapsed 38
:event/card_type "y"
:event/player1 "Gabi"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1437191"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_22459"}

{:event/type "goal"
:event/elapsed 48
:event/player1 "Jiri Jarosik"
:event/sortorder 0
:event/team "home"
:event/id "event_1437402"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_22459"}

{:event/type "goal"
:event/elapsed 55
:event/player1 "Ikechukwu Uche"
:event/sortorder 0
:event/team "home"
:event/id "event_1437482"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_22459"}

{:event/type "card"
:event/elapsed 60
:event/card_type "y"
:event/player1 "Leonardo Ponzio"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1437616"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_22459"}

{:event/type "card"
:event/elapsed 64
:event/card_type "y"
:event/player1 "Mikel Balenziaga"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1437839"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_22459"}

{:event/type "card"
:event/elapsed 71
:event/card_type "y"
:event/player1 "Jiri Jarosik"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1437837"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_22459"}

{:event/type "card"
:event/elapsed 81
:event/card_type "y"
:event/player1 "Matteo Contini"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1437838"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_22459"}


]

