
;;# data
[
{:match/id "match_10005"
:match/league "Germany 1. Bundesliga"
:match/hometeam "FC Schalke 04"
:match/awayteam "Hannover 96"
:match/score "3:1"
:match/hometeam_goals "3"
:match/awayteam_goals "1"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Leon Andreasen"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5078383"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_10005"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "Eric Maxim Choupo-Moting"
:event/subtype "trip"
:event/player1 "Oliver Sorg"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5078390"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_10005"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Joel Matip"
:event/subtype "trip"
:event/player1 "Ceyhun Gulselam"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5078397"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_10005"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Artur Sobiech"
:event/subtype "trip"
:event/player1 "Sascha Riether"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5078404"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_10005"}

{:event/type "corner"
:event/elapsed 7
:event/subtype "cross_right"
:event/player1 "Leon Andreasen"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_5078420"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Oliver Sorg"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_5078422"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Oliver Sorg"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5078430"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_10005"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Miiko Albornoz"
:event/subtype "trip"
:event/player1 "Sascha Riether"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5078443"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_10005"}

{:event/type "card"
:event/elapsed 9
:event/card_type "y"
:event/player1 "Sascha Riether"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_5078445"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Leon Andreasen"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5078448"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_10005"}

{:event/type "shoton"
:event/elapsed 10
:event/subtype "blocked_shot"
:event/player1 "Klaas Jan Huntelaar"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_5078457"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Leon Andreasen"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5078461"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Dennis Aogo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5078487"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_10005"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Max Meyer"
:event/subtype "trip"
:event/player1 "Manuel Schmiedebach"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5078494"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Leon Goretzka"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5078503"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_10005"}

{:event/type "shoton"
:event/elapsed 16
:event/subtype "blocked_shot"
:event/player1 "Benedikt Hoewedes"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5078507"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Sascha Riether"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5078530"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Sascha Riether"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_5078538"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_10005"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Leon Andreasen"
:event/subtype "trip"
:event/player1 "Dennis Aogo"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5078545"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Miiko Albornoz"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5078550"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_10005"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Klaas Jan Huntelaar"
:event/subtype "trip"
:event/player1 "Christian Schulz"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5078558"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_10005"}

{:event/type "shoton"
:event/elapsed 21
:event/subtype "blocked_shot"
:event/player1 "Max Meyer"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5078568"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_10005"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Johannes Geis"
:event/subtype "trip"
:event/player1 "Ceyhun Gulselam"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5078570"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Johannes Geis"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5078575"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Sascha Riether"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5078586"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_10005"}

{:event/type "shoton"
:event/elapsed 23
:event/subtype "header"
:event/player1 "Leroy Sane"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_5078587"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Johannes Geis"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5078591"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_10005"}

{:event/type "shotoff"
:event/elapsed 24
:event/subtype "shot"
:event/player1 "Dennis Aogo"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5078594"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Manuel Schmiedebach"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5078608"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Leon Andreasen"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5078621"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_10005"}

{:event/type "shotoff"
:event/elapsed 27
:event/subtype "big chance shot"
:event/player1 "Max Meyer"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5078625"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Sascha Riether"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5078631"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_10005"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Max Meyer"
:event/subtype "trip"
:event/player1 "Kenan Karaman"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5078646"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Johannes Geis"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5078648"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_10005"}

{:event/type "shoton"
:event/elapsed 33
:event/subtype "blocked_shot"
:event/player1 "Ceyhun Gulselam"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_5078664"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_10005"}

{:event/type "shotoff"
:event/elapsed 34
:event/subtype "shot"
:event/player1 "Leroy Sane"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5078678"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Sascha Riether"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5078688"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_10005"}

{:event/type "corner"
:event/elapsed 36
:event/subtype "cross_right"
:event/player1 "Johannes Geis"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5078694"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_10005"}

{:event/type "shoton"
:event/elapsed 36
:event/subtype "blocked_shot"
:event/player1 "Max Meyer"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_5078703"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_10005"}

{:event/type "shoton"
:event/elapsed 37
:event/subtype "blocked_shot"
:event/player1 "Leroy Sane"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_5078706"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_10005"}

{:event/type "shotoff"
:event/elapsed 37
:event/subtype "shot"
:event/player1 "Benedikt Hoewedes"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5078710"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Klaas Jan Huntelaar"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_5078718"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Sascha Riether"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5078723"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_10005"}

{:event/type "shotoff"
:event/elapsed 40
:event/subtype "shot"
:event/player1 "Klaas Jan Huntelaar"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5078739"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_10005"}

{:event/type "corner"
:event/elapsed 42
:event/subtype "cross_left"
:event/player1 "Johannes Geis"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_5078757"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Max Meyer"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5078780"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_10005"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Oliver Sorg"
:event/subtype "trip"
:event/player1 "Eric Maxim Choupo-Moting"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5078787"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_10005"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "big chance shot"
:event/player1 "Leroy Sane"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_5078794"
:event/minute 46
:event/match_id "match_10005"}

{:event/type "corner"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross_right"
:event/player1 "Johannes Geis"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_5078795"
:event/minute 46
:event/match_id "match_10005"}

{:event/type "shoton"
:event/elapsed 47
:event/subtype "shot"
:event/player1 "Max Meyer"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5078908"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_10005"}

{:event/type "corner"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross_right"
:event/player1 "Johannes Geis"
:event/sortorder 5
:event/team "home"
:event/event_type "corner"
:event/id "event_5078803"
:event/minute 47
:event/match_id "match_10005"}

{:event/type "corner"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross_right"
:event/player1 "Johannes Geis"
:event/sortorder 8
:event/team "home"
:event/event_type "corner"
:event/id "event_5078808"
:event/minute 47
:event/match_id "match_10005"}

{:event/type "shotoff"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "volley"
:event/player1 "Leon Goretzka"
:event/sortorder 10
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5078812"
:event/minute 47
:event/match_id "match_10005"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Leon Andreasen"
:event/subtype "trip"
:event/player1 "Eric Maxim Choupo-Moting"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5078925"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Kenan Karaman"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5078931"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_10005"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Klaas Jan Huntelaar"
:event/subtype "penalty"
:event/player1 "Marcelo"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5078940"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_10005"}

{:event/type "card"
:event/elapsed 51
:event/card_type "y"
:event/player1 "Marcelo"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_5078942"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_10005"}

{:event/type "goal"
:event/elapsed 51
:event/player1 "Johannes Geis"
:event/sortorder 3
:event/team "home"
:event/id "event_5078944"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Leon Andreasen"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5078954"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_10005"}

{:event/type "shotoff"
:event/elapsed 54
:event/subtype "header"
:event/player1 "Kenan Karaman"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5078956"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_10005"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Leon Goretzka"
:event/subtype "pull"
:event/player1 "Leon Andreasen"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5078976"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_10005"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Leroy Sane"
:event/subtype "trip"
:event/player1 "Miiko Albornoz"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5079000"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_10005"}

{:event/type "shotoff"
:event/elapsed 62
:event/subtype "shot"
:event/player1 "Kenan Karaman"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5079012"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_10005"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Max Meyer"
:event/subtype "trip"
:event/player1 "Christian Schulz"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5079024"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Johannes Geis"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5079027"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_10005"}

{:event/type "corner"
:event/elapsed 65
:event/subtype "cross_left"
:event/player1 "Miiko Albornoz"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_5079035"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_10005"}

{:event/type "shoton"
:event/elapsed 66
:event/subtype "blocked_shot"
:event/player1 "Leon Goretzka"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5079040"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_10005"}

{:event/type "shoton"
:event/elapsed 67
:event/subtype "blocked_shot"
:event/player1 "Salif Sane"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_5079042"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_10005"}

{:event/type "corner"
:event/elapsed 67
:event/subtype "cross_right"
:event/player1 "Leon Andreasen"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_5079046"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Allan Saint-Maximin"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_5079049"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_10005"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Leon Goretzka"
:event/subtype "trip"
:event/player1 "Oliver Sorg"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5079054"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_10005"}

{:event/type "shoton"
:event/elapsed 69
:event/subtype "blocked_shot"
:event/player1 "Johannes Geis"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_5079059"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Klaas Jan Huntelaar"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5079069"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_10005"}

{:event/type "corner"
:event/elapsed 72
:event/subtype "cross_left"
:event/player1 "Dennis Aogo"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5079077"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_10005"}

{:event/type "shoton"
:event/elapsed 72
:event/subtype "header"
:event/player1 "Joel Matip"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5079079"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Kenan Karaman"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_5079082"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Max Meyer"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5079087"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_10005"}

{:event/type "goal"
:event/elapsed 73
:event/subtype "shot"
:event/player1 "Klaas Jan Huntelaar"
:event/sortorder 2
:event/team "home"
:event/id "event_5079090"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_10005"}

{:event/type "foulcommit"
:event/elapsed 74
:event/player2 "Salif Sane"
:event/subtype "trip"
:event/player1 "Klaas Jan Huntelaar"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5079097"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Dennis Aogo"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5079099"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_10005"}

{:event/type "shoton"
:event/elapsed 75
:event/subtype "shot"
:event/player1 "Max Meyer"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_5079101"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_10005"}

{:event/type "shotoff"
:event/elapsed 77
:event/subtype "shot"
:event/player1 "Eric Maxim Choupo-Moting"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5079117"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Oliver Sorg"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5079133"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_10005"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Christian Schulz"
:event/subtype "trip"
:event/player1 "Pierre-Emil Hoejbjerg"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5079155"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_10005"}

{:event/type "shotoff"
:event/elapsed 81
:event/subtype "post"
:event/player1 "Kenan Karaman"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5079138"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Edgar Prib"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5079139"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_10005"}

{:event/type "goal"
:event/elapsed 81
:event/player2 "Edgar Prib"
:event/subtype "shot"
:event/player1 "Allan Saint-Maximin"
:event/sortorder 3
:event/team "away"
:event/id "event_5079144"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Leroy Sane"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5079147"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_10005"}

{:event/type "goal"
:event/elapsed 82
:event/subtype "header"
:event/player1 "Franco Di Santo"
:event/sortorder 2
:event/team "home"
:event/id "event_5079149"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_10005"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Christian Schulz"
:event/subtype "pushing"
:event/player1 "Leroy Sane"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5079156"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Salif Sane"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5079160"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_10005"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Franco Di Santo"
:event/subtype "pushing"
:event/player1 "Christian Schulz"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5079162"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Johannes Geis"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5079163"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_10005"}

{:event/type "shotoff"
:event/elapsed 85
:event/subtype "shot"
:event/player1 "Leon Goretzka"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5079166"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Franco Di Santo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5079176"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Pierre-Emil Hoejbjerg"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_5079182"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_10005"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Sascha Riether"
:event/subtype "trip"
:event/player1 "Miiko Albornoz"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5079200"
:event/minute 91
:event/match_id "match_10005"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Charlison Benschop"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_5079203"
:event/minute 92
:event/match_id "match_10005"}

{:event/type "corner"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross_right"
:event/player1 "Edgar Prib"
:event/sortorder 5
:event/team "away"
:event/event_type "corner"
:event/id "event_5079204"
:event/minute 93
:event/match_id "match_10005"}


]

