
;;# data
[
{:match/id "match_10516"
:match/league "Italy Serie A"
:match/hometeam "Siena"
:match/awayteam "Chievo Verona"
:match/score "0:2"
:match/hometeam_goals "0"
:match/awayteam_goals "2"}

{:event/type "goal"
:event/elapsed 22
:event/player1 "Sergio Pellissier"
:event/sortorder 0
:event/team "away"
:event/id "event_650143"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_10516"}

{:event/type "card"
:event/elapsed 39
:event/card_type "y"
:event/player1 "Paul Constantin Codrea"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_650282"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_10516"}

{:event/type "card"
:event/elapsed 45
:event/card_type "y"
:event/player1 "Luca Rigoni"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_650493"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_10516"}

{:event/type "goal"
:event/elapsed 48
:event/player1 "Sergio Pellissier"
:event/sortorder 0
:event/team "away"
:event/id "event_650463"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_10516"}

{:event/type "card"
:event/elapsed 84
:event/card_type "y"
:event/player1 "Nicola Amoruso"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_650962"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_10516"}


]

