
;;# data
[
{:match/id "match_2123"
:match/league "England Premier League"
:match/hometeam "Tottenham Hotspur"
:match/awayteam "Stoke City"
:match/score "0:1"
:match/hometeam_goals "0"
:match/awayteam_goals "1"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/sortorder 2
:event/team "away"
:event/event_type "throwin"
:event/id "event_809627"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_2123"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_809633"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_2123"}

{:event/type "shoton"
:event/elapsed 3
:event/subtype "blocked_shot"
:event/player1 "Matthew Etherington"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_809637"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_2123"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Matthew Etherington"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_809656"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_2123"}

{:event/type "corner"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Matthew Etherington"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_809656"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_2123"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Aaron Lennon"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_809680"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_2123"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Benoit Assou-Ekotto"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_809716"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_2123"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Aaron Lennon"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_809728"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_2123"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Niko Kranjcar"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_809732"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_2123"}

{:event/type "corner"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Niko Kranjcar"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_809732"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_2123"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Niko Kranjcar"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_809736"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_2123"}

{:event/type "shoton"
:event/elapsed 12
:event/subtype "header"
:event/player1 "Peter Crouch"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_809737"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_2123"}

{:event/type "corner"
:event/elapsed 12
:event/subtype "short"
:event/player1 "Niko Kranjcar"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_809739"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_2123"}

{:event/type "shotoff"
:event/elapsed 12
:event/subtype "distance"
:event/player1 "Wilson Palacios"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_809744"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_2123"}

{:event/type "shotoff"
:event/elapsed 13
:event/subtype "distance"
:event/player1 "Tom Huddlestone"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_809756"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_2123"}

{:event/type "shoton"
:event/elapsed 17
:event/subtype "distance"
:event/player1 "Niko Kranjcar"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_809793"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_2123"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player1 "James Beattie"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_809820"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_2123"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/sortorder 1
:event/team "away"
:event/event_type "throwin"
:event/id "event_809830"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_2123"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_809856"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_2123"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Tom Huddlestone"
:event/player1 "Salif Diao"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_809863"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_2123"}

{:event/type "shoton"
:event/elapsed 24
:event/subtype "distance"
:event/player1 "Aaron Lennon"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_809879"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_2123"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Niko Kranjcar"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_809880"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_2123"}

{:event/type "corner"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Niko Kranjcar"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_809880"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_2123"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Niko Kranjcar"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_809886"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_2123"}

{:event/type "shotoff"
:event/elapsed 25
:event/subtype "shot"
:event/player1 "Sebastien Bassong"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_809894"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_2123"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Dean Whitehead"
:event/player1 "Wilson Palacios"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_809902"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_2123"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Peter Crouch"
:event/player1 "Abdoulaye Faye"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_809921"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_2123"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Aaron Lennon"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_809927"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_2123"}

{:event/type "shoton"
:event/elapsed 27
:event/subtype "header"
:event/player1 "Peter Crouch"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_809929"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_2123"}

{:event/type "shotoff"
:event/elapsed 28
:event/subtype "post"
:event/player1 "Niko Kranjcar"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_809944"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_2123"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Ricardo Fuller"
:event/player1 "Michael Dawson"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_809950"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2123"}

{:event/type "shotoff"
:event/elapsed 29
:event/subtype "distance"
:event/player1 "Salif Diao"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_809957"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2123"}

{:event/type "card"
:event/elapsed 29
:event/card_type "y"
:event/subtype "verbal_abuse"
:event/player1 "Ricardo Fuller"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_809958"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2123"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_810016"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_2123"}

{:event/type "shotoff"
:event/elapsed 35
:event/subtype "shot"
:event/player1 "Ricardo Fuller"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_810020"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_2123"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "James Beattie"
:event/player1 "Vedran Corluka"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_810042"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_2123"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Niko Kranjcar"
:event/player1 "Dean Whitehead"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_810056"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_2123"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_810089"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_2123"}

{:event/type "shoton"
:event/elapsed 41
:event/subtype "blocked_shot"
:event/player1 "Ricardo Fuller"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_810091"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_2123"}

{:event/type "foulcommit"
:event/elapsed 46
:event/player2 "Aaron Lennon"
:event/player1 "Salif Diao"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_810286"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_2123"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 45
:event/player1 "Peter Crouch"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_810190"
:event/minute 47
:event/match_id "match_2123"}

{:event/type "shoton"
:event/elapsed 47
:event/subtype "direct_freekick"
:event/player1 "Niko Kranjcar"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_810294"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_2123"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Aaron Lennon"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_810201"
:event/minute 48
:event/match_id "match_2123"}

{:event/type "foulcommit"
:event/elapsed_plus 4
:event/elapsed 45
:event/player1 "Peter Crouch"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_810208"
:event/minute 49
:event/match_id "match_2123"}

{:event/type "shoton"
:event/elapsed 49
:event/subtype "shot"
:event/player1 "Robbie Keane"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_810314"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_2123"}

{:event/type "shotoff"
:event/elapsed 49
:event/subtype "shot"
:event/player1 "Benoit Assou-Ekotto"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_810318"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_2123"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Peter Crouch"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_810327"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_2123"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player1 "Benoit Assou-Ekotto"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_810336"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_2123"}

{:event/type "shotoff"
:event/elapsed 51
:event/subtype "distance"
:event/player1 "Salif Diao"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_810345"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_2123"}

{:event/type "shotoff"
:event/elapsed 55
:event/subtype "distance"
:event/player1 "Tom Huddlestone"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_810396"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_2123"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Matthew Etherington"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_810404"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_2123"}

{:event/type "shotoff"
:event/elapsed 55
:event/subtype "header"
:event/player1 "James Beattie"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_810406"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_2123"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/sortorder 1
:event/team "away"
:event/event_type "throwin"
:event/id "event_810414"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_2123"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Robbie Keane"
:event/player1 "Ryan Shawcross"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_810423"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_2123"}

{:event/type "foulcommit"
:event/elapsed 58
:event/subtype "hands"
:event/player1 "Dean Whitehead"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_810437"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_2123"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Aaron Lennon"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_810450"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_2123"}

{:event/type "shoton"
:event/elapsed 60
:event/subtype "blocked_shot"
:event/player1 "Tom Huddlestone"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_810495"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_2123"}

{:event/type "corner"
:event/elapsed 61
:event/subtype "short"
:event/player1 "Tom Huddlestone"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_810483"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_2123"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Aaron Lennon"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_810486"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_2123"}

{:event/type "shoton"
:event/elapsed 62
:event/subtype "header"
:event/player1 "Peter Crouch"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_810487"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_2123"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player1 "Ricardo Fuller"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_810491"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_2123"}

{:event/type "shotoff"
:event/elapsed 63
:event/subtype "distance"
:event/player1 "Dean Whitehead"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_810509"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_2123"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player1 "Peter Crouch"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_810531"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_2123"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Peter Crouch"
:event/player1 "Ryan Shawcross"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_810556"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_2123"}

{:event/type "shotoff"
:event/elapsed 67
:event/subtype "distance"
:event/player1 "Roman Pavlyuchenko"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_810566"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_2123"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player1 "James Beattie"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_810582"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_2123"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player1 "Sebastien Bassong"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_810594"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_2123"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Jermaine Jenas"
:event/player1 "Andy Wilkinson"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_810615"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_2123"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Aaron Lennon"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_810634"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_2123"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Jermaine Jenas"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_810654"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_2123"}

{:event/type "corner"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Jermaine Jenas"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_810654"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_2123"}

{:event/type "foulcommit"
:event/elapsed 74
:event/player2 "Dean Whitehead"
:event/player1 "Wilson Palacios"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_810665"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_2123"}

{:event/type "shoton"
:event/elapsed 74
:event/subtype "blocked_shot"
:event/player1 "Tuncay Sanli"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_810667"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_2123"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Roman Pavlyuchenko"
:event/subtype "pushing"
:event/player1 "Ryan Shawcross"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_810672"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_2123"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Glenn Whelan"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_810679"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_2123"}

{:event/type "shoton"
:event/elapsed 76
:event/subtype "distance"
:event/player1 "Roman Pavlyuchenko"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_810686"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_2123"}

{:event/type "foulcommit"
:event/elapsed 76
:event/player2 "Aaron Lennon"
:event/subtype "serious_foul"
:event/player1 "Glenn Whelan"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_810694"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_2123"}

{:event/type "card"
:event/elapsed 76
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Glenn Whelan"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_810702"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_2123"}

{:event/type "shotoff"
:event/elapsed 80
:event/subtype "shot"
:event/player1 "Tuncay Sanli"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_810726"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_2123"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Roman Pavlyuchenko"
:event/player1 "Salif Diao"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_810739"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_2123"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Jermaine Jenas"
:event/subtype "serious_foul"
:event/player1 "Salif Diao"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_810760"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_2123"}

{:event/type "card"
:event/elapsed 82
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Salif Diao"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_810764"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_2123"}

{:event/type "shotoff"
:event/elapsed 83
:event/subtype "direct_freekick"
:event/player1 "Jermaine Jenas"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_810776"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_2123"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Michael Dawson"
:event/player1 "Ricardo Fuller"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_810780"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_2123"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Jermaine Jenas"
:event/player1 "Dean Whitehead"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_810783"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_2123"}

{:event/type "goal"
:event/elapsed 86
:event/player2 "Ricardo Fuller"
:event/subtype "shot"
:event/player1 "Glenn Whelan"
:event/sortorder 1
:event/team "away"
:event/id "event_810801"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_2123"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Peter Crouch"
:event/player1 "Ryan Shawcross"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_810843"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_2123"}

{:event/type "shoton"
:event/elapsed 90
:event/subtype "blocked_shot"
:event/player1 "Jermaine Jenas"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_810845"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_2123"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Niko Kranjcar"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_810856"
:event/minute 91
:event/match_id "match_2123"}

{:event/type "corner"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Niko Kranjcar"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_810856"
:event/minute 91
:event/match_id "match_2123"}

{:event/type "shotoff"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Peter Crouch"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_810861"
:event/minute 92
:event/match_id "match_2123"}

{:event/type "cross"
:event/elapsed_plus 6
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Jermaine Jenas"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_810880"
:event/minute 96
:event/match_id "match_2123"}

{:event/type "corner"
:event/elapsed_plus 6
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Jermaine Jenas"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_810880"
:event/minute 96
:event/match_id "match_2123"}


]

