
;;# data
[
{:match/id "match_2886"
:match/league "England Premier League"
:match/hometeam "Tottenham Hotspur"
:match/awayteam "Queens Park Rangers"
:match/score "3:1"
:match/hometeam_goals "3"
:match/awayteam_goals "1"}

{:event/type "foulcommit"
:event/elapsed 1
:event/player2 "Gareth Bale"
:event/player1 "Luke Young"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1747323"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_2886"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Rafael van der Vaart"
:event/player1 "Alejandro Faurlin"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1747330"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_2886"}

{:event/type "shoton"
:event/elapsed 3
:event/subtype "big chance shot"
:event/player1 "Rafael van der Vaart"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1747332"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Rafael van der Vaart"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1747334"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_2886"}

{:event/type "corner"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Rafael van der Vaart"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1747334"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Rafael van der Vaart"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_1747338"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_2886"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Aaron Lennon"
:event/player1 "Joey Barton"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1747342"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_2886"}

{:event/type "shotoff"
:event/elapsed 4
:event/subtype "direct_freekick"
:event/player1 "Benoit Assou-Ekotto"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1747345"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_2886"}

{:event/type "foulcommit"
:event/elapsed 6
:event/player2 "Luka Modric"
:event/player1 "Heidar Helguson"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1747355"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_2886"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Benoit Assou-Ekotto"
:event/player1 "Joey Barton"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1747393"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_2886"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Gareth Bale"
:event/player1 "Luke Young"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1747394"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_2886"}

{:event/type "shotoff"
:event/elapsed 13
:event/subtype "header"
:event/player1 "Emmanuel Adebayor"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1747399"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Adel Taarabt"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1747409"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Adel Taarabt"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1747412"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Gareth Bale"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1747418"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_2886"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Adel Taarabt"
:event/player1 "Luka Modric"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1747419"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_2886"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Joey Barton"
:event/player1 "Benoit Assou-Ekotto"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1747439"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_2886"}

{:event/type "shotoff"
:event/elapsed 20
:event/subtype "volley"
:event/player1 "Heidar Helguson"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1747461"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_2886"}

{:event/type "goal"
:event/elapsed 20
:event/player2 "Aaron Lennon"
:event/subtype "shot"
:event/player1 "Gareth Bale"
:event/sortorder 3
:event/team "home"
:event/id "event_1747463"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_2886"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Armand Traore"
:event/player1 "Aaron Lennon"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1747467"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_2886"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Adel Taarabt"
:event/subtype "pushing"
:event/player1 "Rafael van der Vaart"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1747471"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Gareth Bale"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1747485"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_2886"}

{:event/type "shoton"
:event/elapsed 24
:event/subtype "distance"
:event/player1 "Rafael van der Vaart"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1747487"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Emmanuel Adebayor"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1747525"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_2886"}

{:event/type "shotoff"
:event/elapsed 28
:event/subtype "big chance volley"
:event/player1 "Gareth Bale"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1747528"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_2886"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Alejandro Faurlin"
:event/subtype "pushing"
:event/player1 "Rafael van der Vaart"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1747532"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Gareth Bale"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1747535"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_2886"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Luka Modric"
:event/player1 "Shaun Derry"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1747541"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Benoit Assou-Ekotto"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1747564"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_2886"}

{:event/type "shotoff"
:event/elapsed 33
:event/subtype "deflected"
:event/player1 "Ledley King"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1747570"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_2886"}

{:event/type "goal"
:event/elapsed 33
:event/player2 "Ledley King"
:event/subtype "shot"
:event/player1 "Rafael van der Vaart"
:event/sortorder 2
:event/team "home"
:event/id "event_1747571"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_2886"}

{:event/type "shotoff"
:event/elapsed 34
:event/subtype "bad shot"
:event/player1 "Joey Barton"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1747580"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Gareth Bale"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1747587"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Armand Traore"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1747593"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Rafael van der Vaart"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1747602"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Rafael van der Vaart"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1747607"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_2886"}

{:event/type "corner"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Rafael van der Vaart"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1747607"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_2886"}

{:event/type "shotoff"
:event/elapsed 37
:event/subtype "volley"
:event/player1 "Luka Modric"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1747609"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_2886"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Heidar Helguson"
:event/player1 "Kyle Walker"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1747621"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Benoit Assou-Ekotto"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1747642"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_2886"}

{:event/type "shotoff"
:event/elapsed 40
:event/subtype "shot"
:event/player1 "Luka Modric"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1747643"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Adel Taarabt"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1747648"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_2886"}

{:event/type "corner"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Adel Taarabt"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1747648"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_2886"}

{:event/type "shotoff"
:event/elapsed 41
:event/subtype "shot"
:event/player1 "Emmanuel Adebayor"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1747653"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_2886"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Armand Traore"
:event/player1 "Rafael van der Vaart"
:event/sortorder 5
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1747677"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_2886"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Aaron Lennon"
:event/player1 "Armand Traore"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1747685"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_2886"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Luka Modric"
:event/player1 "Joey Barton"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1747806"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_2886"}

{:event/type "shoton"
:event/elapsed 50
:event/subtype "big chance shot"
:event/player1 "Rafael van der Vaart"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_1747818"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Gareth Bale"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1747822"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_2886"}

{:event/type "shoton"
:event/elapsed 51
:event/subtype "header"
:event/player1 "Emmanuel Adebayor"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1747824"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_2886"}

{:event/type "shotoff"
:event/elapsed 52
:event/subtype "bad shot"
:event/player1 "Jay Bothroyd"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1747834"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Joey Barton"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1747846"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Joey Barton"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1747854"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_2886"}

{:event/type "corner"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Joey Barton"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1747854"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Shaun Wright-Phillips"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1747857"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Alejandro Faurlin"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_1747859"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_2886"}

{:event/type "shoton"
:event/elapsed 55
:event/subtype "blocked_shot"
:event/player1 "Emmanuel Adebayor"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1747865"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Rafael van der Vaart"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1747868"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_2886"}

{:event/type "corner"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Rafael van der Vaart"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1747868"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_2886"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Jamie Mackie"
:event/player1 "Benoit Assou-Ekotto"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1747874"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_2886"}

{:event/type "shotoff"
:event/elapsed 56
:event/subtype "deflected"
:event/player1 "Heidar Helguson"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1747885"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Joey Barton"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1747888"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_2886"}

{:event/type "corner"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Joey Barton"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1747888"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_2886"}

{:event/type "shoton"
:event/elapsed 57
:event/subtype "blocked_shot"
:event/player1 "Shaun Wright-Phillips"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1747891"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Joey Barton"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1747892"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_2886"}

{:event/type "corner"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Joey Barton"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1747892"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_2886"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Shaun Wright-Phillips"
:event/subtype "advantage"
:event/player1 "Emmanuel Adebayor"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1747899"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_2886"}

{:event/type "shoton"
:event/elapsed 58
:event/subtype "blocked_shot"
:event/player1 "Shaun Wright-Phillips"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1747903"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_2886"}

{:event/type "foulcommit"
:event/elapsed 59
:event/player2 "Scott Parker"
:event/subtype "dangerous_play"
:event/player1 "Jay Bothroyd"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1747912"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Gareth Bale"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1747917"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_2886"}

{:event/type "shoton"
:event/elapsed 59
:event/subtype "blocked_shot"
:event/player1 "Rafael van der Vaart"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1747918"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_2886"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player2 "Armand Traore"
:event/subtype "pushing"
:event/player1 "Kyle Walker"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1747921"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_2886"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player2 "Scott Parker"
:event/subtype "pushing"
:event/player1 "Jamie Mackie"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1747924"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_2886"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Luke Young"
:event/subtype "advantage"
:event/player1 "Scott Parker"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1747934"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_2886"}

{:event/type "shotoff"
:event/elapsed 62
:event/subtype "deflected"
:event/player1 "Alejandro Faurlin"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1747936"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Joey Barton"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1747937"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_2886"}

{:event/type "corner"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Joey Barton"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1747937"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_2886"}

{:event/type "goal"
:event/elapsed 62
:event/player2 "Heidar Helguson"
:event/subtype "header"
:event/player1 "Jay Bothroyd"
:event/sortorder 3
:event/team "away"
:event/id "event_1747940"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_2886"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Gareth Bale"
:event/player1 "Luke Young"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1747945"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_2886"}

{:event/type "shoton"
:event/elapsed 64
:event/subtype "direct_freekick"
:event/player1 "Rafael van der Vaart"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1747953"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_2886"}

{:event/type "shoton"
:event/elapsed 64
:event/subtype "big chance shot"
:event/player1 "Gareth Bale"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1747957"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_2886"}

{:event/type "shoton"
:event/elapsed 65
:event/subtype "distance"
:event/player1 "Alejandro Faurlin"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1747962"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Luke Young"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1747966"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Joey Barton"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1747972"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_2886"}

{:event/type "corner"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Joey Barton"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1747972"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_2886"}

{:event/type "corner"
:event/elapsed 68
:event/subtype "short"
:event/player1 "Rafael van der Vaart"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1747983"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_2886"}

{:event/type "shoton"
:event/elapsed 68
:event/subtype "distance"
:event/player1 "Benoit Assou-Ekotto"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1747984"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_2886"}

{:event/type "shotoff"
:event/elapsed 68
:event/subtype "header"
:event/player1 "Ledley King"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1747987"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_2886"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Heidar Helguson"
:event/player1 "Kyle Walker"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1748004"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_2886"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Younes Kaboul"
:event/subtype "pushing"
:event/player1 "Jay Bothroyd"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1748014"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_2886"}

{:event/type "goal"
:event/elapsed 72
:event/player2 "Aaron Lennon"
:event/subtype "shot"
:event/player1 "Gareth Bale"
:event/sortorder 1
:event/team "home"
:event/id "event_1748021"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Gareth Bale"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1748032"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_2886"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Joey Barton"
:event/player1 "Scott Parker"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1748044"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_2886"}

{:event/type "shotoff"
:event/elapsed 76
:event/subtype "big chance shot"
:event/player1 "Emmanuel Adebayor"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1748048"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_2886"}

{:event/type "foulcommit"
:event/elapsed 79
:event/player2 "Heidar Helguson"
:event/player1 "Luka Modric"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1748073"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_2886"}

{:event/type "shotoff"
:event/elapsed 80
:event/subtype "direct_freekick"
:event/player1 "Alejandro Faurlin"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1748083"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_2886"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Rafael van der Vaart"
:event/subtype "advantage"
:event/player1 "Jamie Mackie"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1748092"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_2886"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Emmanuel Adebayor"
:event/player1 "Anton Ferdinand"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1748122"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_2886"}

{:event/type "shotoff"
:event/elapsed 86
:event/subtype "shot"
:event/player1 "Shaun Wright-Phillips"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1748137"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Joey Barton"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1748177"
:event/minute 91
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Shaun Wright-Phillips"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1748197"
:event/minute 93
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Joey Barton"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1748199"
:event/minute 93
:event/match_id "match_2886"}

{:event/type "corner"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Joey Barton"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1748199"
:event/minute 93
:event/match_id "match_2886"}

{:event/type "shoton"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "blocked_shot"
:event/player1 "Luke Young"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1748200"
:event/minute 93
:event/match_id "match_2886"}

{:event/type "shoton"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Luke Young"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1748202"
:event/minute 94
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Joey Barton"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1748204"
:event/minute 94
:event/match_id "match_2886"}

{:event/type "corner"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Joey Barton"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1748204"
:event/minute 94
:event/match_id "match_2886"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Alejandro Faurlin"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_1748207"
:event/minute 94
:event/match_id "match_2886"}


]

