
;;# data
[
{:match/id "match_8478"
:match/league "Germany 1. Bundesliga"
:match/hometeam "VfL Wolfsburg"
:match/awayteam "SV Werder Bremen"
:match/score "1:1"
:match/hometeam_goals "0"
:match/awayteam_goals "0"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Mario Mandzukic"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1310945"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_8478"}

{:event/type "shotoff"
:event/elapsed 1
:event/player1 "Marcel Schaefer"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1310947"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 6
:event/player2 "Sascha Riether"
:event/subtype "from_behind"
:event/player1 "Marko Marin"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1310971"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 8
:event/player2 "Diego"
:event/subtype "pushing"
:event/player1 "Sebastian Proedl"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1310984"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_8478"}

{:event/type "shoton"
:event/elapsed 9
:event/subtype "direct_freekick"
:event/player1 "Diego"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1310986"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_8478"}

{:event/type "shotoff"
:event/elapsed 10
:event/subtype "shot"
:event/player1 "Philipp Bargfrede"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1310994"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_8478"}

{:event/type "shotoff"
:event/elapsed 11
:event/subtype "shot"
:event/player1 "Tolga Cigerci"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1310998"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player1 "Edin Dzeko"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1311007"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Marko Marin"
:event/player1 "Peter Pekarik"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1311009"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Marko Marin"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1311013"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_8478"}

{:event/type "corner"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Marko Marin"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1311013"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Sascha Riether"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1311016"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_8478"}

{:event/type "shoton"
:event/elapsed 15
:event/subtype "shot"
:event/player1 "Diego"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1311018"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_8478"}

{:event/type "corner"
:event/elapsed 15
:event/subtype "short"
:event/player1 "Diego"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1311019"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Philipp Bargfrede"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1311042"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Marko Marin"
:event/sortorder 5
:event/team "away"
:event/event_type "corner"
:event/id "event_1311044"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_8478"}

{:event/type "corner"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Marko Marin"
:event/sortorder 5
:event/team "away"
:event/event_type "corner"
:event/id "event_1311044"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Peter Pekarik"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1311049"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Petri Pasanen"
:event/subtype "from_behind"
:event/player1 "Mario Mandzukic"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1311051"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Petri Pasanen"
:event/player1 "Diego"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1311059"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Diego"
:event/subtype "pushing"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1311062"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Sascha Riether"
:event/player1 "Sebastian Proedl"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1311074"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Marko Arnautovic"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1311078"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player1 "Torsten Frings"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1311080"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Aaron Hunt"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1311104"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_8478"}

{:event/type "shoton"
:event/elapsed 29
:event/subtype "shot"
:event/player1 "Marko Arnautovic"
:event/sortorder 5
:event/team "away"
:event/event_type "shoton"
:event/id "event_1311106"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Aaron Hunt"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1311110"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_8478"}

{:event/type "corner"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Aaron Hunt"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1311110"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Torsten Frings"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1311113"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_8478"}

{:event/type "shoton"
:event/elapsed 31
:event/subtype "shot"
:event/player1 "Marko Marin"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1311131"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Marko Marin"
:event/player1 "Josue"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1311138"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_8478"}

{:event/type "shotoff"
:event/elapsed 32
:event/subtype "header"
:event/player1 "Per Mertesacker"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1311142"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Edin Dzeko"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1311148"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_8478"}

{:event/type "shoton"
:event/elapsed 33
:event/subtype "shot"
:event/player1 "Josue"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1311150"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Marcel Schaefer"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1311162"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Peter Pekarik"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1311164"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Peter Pekarik"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_1311167"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Diego"
:event/subtype "pushing"
:event/player1 "Clemens Fritz"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1311188"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Sascha Riether"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1311190"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_8478"}

{:event/type "card"
:event/elapsed 36
:event/card_type "y"
:event/subtype "verbal_abuse"
:event/player1 "Diego"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1311208"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 36
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1311218"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Peter Pekarik"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1311253"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Peter Pekarik"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1311263"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Josue"
:event/player1 "Dominik Schmidt"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1311338"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Simon Kjaer"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1311366"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Mario Mandzukic"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1311651"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Marko Arnautovic"
:event/subtype "obstruction"
:event/player1 "Josue"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1311687"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_8478"}

{:event/type "shoton"
:event/elapsed 49
:event/subtype "blocked_shot"
:event/player1 "Marko Arnautovic"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1311694"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 49
:event/subtype "hands"
:event/player1 "Tolga Cigerci"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1311695"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_8478"}

{:event/type "shoton"
:event/elapsed 50
:event/subtype "blocked_shot"
:event/player1 "Marko Arnautovic"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1311707"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Clemens Fritz"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1311711"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/sortorder 5
:event/team "away"
:event/event_type "cross"
:event/id "event_1311724"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Marcel Schaefer"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1311742"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player1 "Marcel Schaefer"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1311777"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_8478"}

{:event/type "shotoff"
:event/elapsed 54
:event/subtype "shot"
:event/player1 "Aaron Hunt"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1311796"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_8478"}

{:event/type "shoton"
:event/elapsed 55
:event/subtype "shot"
:event/player1 "Mario Mandzukic"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1311807"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Tolga Cigerci"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_1311825"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player1 "Mario Mandzukic"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1311830"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Clemens Fritz"
:event/subtype "obstruction"
:event/player1 "Josue"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1311861"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player2 "Torsten Frings"
:event/subtype "obstruction"
:event/player1 "Josue"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1311886"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player2 "Simon Kjaer"
:event/subtype "pushing"
:event/player1 "Marko Arnautovic"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1311890"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Marcel Schaefer"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1311896"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Diego"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1311899"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_8478"}

{:event/type "corner"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Diego"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1311899"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Marcel Schaefer"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1311904"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Torsten Frings"
:event/subtype "pushing"
:event/player1 "Diego"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1311906"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Sascha Riether"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1311909"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_8478"}

{:event/type "shotoff"
:event/elapsed 62
:event/subtype "shot"
:event/player1 "Mario Mandzukic"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1311910"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Peter Pekarik"
:event/subtype "obstruction"
:event/player1 "Petri Pasanen"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1311916"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Peter Pekarik"
:event/subtype "pushing"
:event/player1 "Marko Marin"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1311922"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Philipp Bargfrede"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1311928"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player1 "Peter Pekarik"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1311929"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Clemens Fritz"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1311933"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Edin Dzeko"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_1311936"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player1 "Marcel Schaefer"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1311946"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_8478"}

{:event/type "shoton"
:event/elapsed 68
:event/subtype "header"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1311949"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_8478"}

{:event/type "shoton"
:event/elapsed 68
:event/subtype "shot"
:event/player1 "Clemens Fritz"
:event/sortorder 4
:event/team "away"
:event/event_type "shoton"
:event/id "event_1311952"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Sebastian Proedl"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1311953"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Aaron Hunt"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1311955"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Marko Marin"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1311958"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_8478"}

{:event/type "corner"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Marko Marin"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1311958"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Marko Marin"
:event/subtype "obstruction"
:event/player1 "Andrea Barzagli"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1311961"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_8478"}

{:event/type "card"
:event/elapsed 71
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Andrea Barzagli"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_1311962"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_8478"}

{:event/type "shotoff"
:event/elapsed 72
:event/subtype "direct_freekick"
:event/player1 "Marko Arnautovic"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1311963"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Marcel Schaefer"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1311966"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Aaron Hunt"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1311973"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_8478"}

{:event/type "shoton"
:event/elapsed 73
:event/subtype "blocked_shot"
:event/player1 "Philipp Bargfrede"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1311974"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 74
:event/player2 "Philipp Bargfrede"
:event/subtype "penalty"
:event/player1 "Marcel Schaefer"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1311975"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_8478"}

{:event/type "goal"
:event/elapsed 75
:event/subtype "saved_back_into_play"
:event/player1 "Torsten Frings"
:event/sortorder 0
:event/team "away"
:event/id "event_1311979"
:event/event_type "goal"
:event/goal_type "npm"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Marko Marin"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1311984"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_8478"}

{:event/type "corner"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Marko Marin"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1311984"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Diego Benaglio"
:event/subtype "pushing"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1311988"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Marcel Schaefer"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1312003"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 76
:event/player2 "Mario Mandzukic"
:event/subtype "penalty"
:event/player1 "Sebastian Proedl"
:event/sortorder 6
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1312010"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_8478"}

{:event/type "card"
:event/elapsed 76
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Sebastian Proedl"
:event/sortorder 9
:event/team "away"
:event/event_type "card"
:event/id "event_1312013"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_8478"}

{:event/type "goal"
:event/elapsed 77
:event/subtype "missed"
:event/player1 "Edin Dzeko"
:event/sortorder 0
:event/team "home"
:event/id "event_1312019"
:event/event_type "goal"
:event/goal_type "npm"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 79
:event/player2 "Marcel Schaefer"
:event/subtype "shirt_pull"
:event/player1 "Philipp Bargfrede"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1312052"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 79
:event/player2 "Tim Wiese"
:event/subtype "serious_foul"
:event/player1 "Simon Kjaer"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1312059"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_8478"}

{:event/type "card"
:event/elapsed 79
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Simon Kjaer"
:event/sortorder 3
:event/team "home"
:event/event_type "card"
:event/id "event_1312060"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Marko Arnautovic"
:event/subtype "from_behind"
:event/player1 "Andrea Barzagli"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1312089"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Sascha Riether"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1312097"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Daniel Jensen"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_1312104"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Marcel Schaefer"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1312111"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_8478"}

{:event/type "shoton"
:event/elapsed 84
:event/subtype "shot"
:event/player1 "Marko Arnautovic"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1312138"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Aaron Hunt"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1312144"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_8478"}

{:event/type "corner"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Aaron Hunt"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1312144"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_8478"}

{:event/type "shoton"
:event/elapsed 84
:event/subtype "header"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_1312148"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Diego"
:event/subtype "pushing"
:event/player1 "Torsten Frings"
:event/sortorder 5
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1312156"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1312166"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_8478"}

{:event/type "shoton"
:event/elapsed 85
:event/subtype "shot"
:event/player1 "Marko Marin"
:event/sortorder 4
:event/team "away"
:event/event_type "shoton"
:event/id "event_1312173"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 86
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1312179"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Aaron Hunt"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1312196"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Marko Marin"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1312207"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_8478"}

{:event/type "corner"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Marko Marin"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1312207"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_8478"}

{:event/type "shotoff"
:event/elapsed 87
:event/subtype "header"
:event/player1 "Clemens Fritz"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1312209"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Diego"
:event/subtype "from_behind"
:event/player1 "Clemens Fritz"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1312249"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_8478"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Clemens Fritz"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1312257"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_8478"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Marko Arnautovic"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1312261"
:event/minute 91
:event/match_id "match_8478"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "big chance blocked"
:event/player1 "Aaron Hunt"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1312262"
:event/minute 91
:event/match_id "match_8478"}


]

