
;;# data
[
{:match/id "match_6838"
:match/league "France Ligue 1"
:match/hometeam "AC Ajaccio"
:match/awayteam "Stade Rennais FC"
:match/score "3:1"
:match/hometeam_goals "3"
:match/awayteam_goals "1"}

{:event/type "card"
:event/elapsed 7
:event/card_type "y"
:event/player1 "Abdoulaye Doucoure"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3252219"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_6838"}

{:event/type "goal"
:event/elapsed 18
:event/player2 "Johan Cavalli"
:event/player1 "Ricardo Faty"
:event/sortorder 0
:event/team "home"
:event/id "event_3252252"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_6838"}

{:event/type "goal"
:event/elapsed 33
:event/player1 "Abdoulaye Doucoure"
:event/sortorder 0
:event/team "away"
:event/id "event_3252272"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_6838"}

{:event/type "goal"
:event/elapsed 37
:event/player2 "Mehdi Mostefa"
:event/player1 "Benjamin Andre"
:event/sortorder 0
:event/team "home"
:event/id "event_3252279"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_6838"}

{:event/type "card"
:event/elapsed 51
:event/card_type "y"
:event/player1 "Sigamary Diarra"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3252335"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_6838"}

{:event/type "goal"
:event/elapsed 77
:event/player1 "Johan Cavalli"
:event/sortorder 0
:event/team "home"
:event/id "event_3252385"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_6838"}


]

