
;;# data
[
{:match/id "match_22375"
:match/league "Spain LIGA BBVA"
:match/hometeam "Málaga CF"
:match/awayteam "Athletic Club de Bilbao"
:match/score "1:1"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "foulcommit"
:event/elapsed 1
:event/player2 "Antonio Apono"
:event/player1 "Iker Muniain"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1356343"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Pablo Orbaiz"
:event/subtype "pushing"
:event/player1 "Ignacio Camacho"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1356341"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_22375"}

{:event/type "shoton"
:event/elapsed 3
:event/subtype "direct_freekick"
:event/player1 "David Lopez"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1356342"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Duda"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1356344"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_22375"}

{:event/type "corner"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Duda"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1356344"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Duda"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1356346"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_22375"}

{:event/type "corner"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Duda"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1356346"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_22375"}

{:event/type "shotoff"
:event/elapsed 7
:event/subtype "bad shot"
:event/player1 "Jose Salomon Rondon"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1356348"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Andoni Iraola"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1356353"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_22375"}

{:event/type "shoton"
:event/elapsed 12
:event/subtype "distance"
:event/player1 "Ander Iturraspe"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1356355"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1356356"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_22375"}

{:event/type "corner"
:event/elapsed 12
:event/subtype "cross"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1356356"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 13
:event/subtype "cross"
:event/player1 "David Lopez"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1356359"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_22375"}

{:event/type "shotoff"
:event/elapsed 13
:event/subtype "header"
:event/player1 "Fernando Llorente"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1356360"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Ignacio Camacho"
:event/player1 "Javier Martinez"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1356363"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 15
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1356367"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_22375"}

{:event/type "shotoff"
:event/elapsed 16
:event/subtype "header"
:event/player1 "Antonio Apono"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1356369"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Mikel San Jose"
:event/player1 "Quincy Owusu-Abeyie"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1356372"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Quincy Owusu-Abeyie"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1356373"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_22375"}

{:event/type "shoton"
:event/elapsed 18
:event/subtype "blocked_shot"
:event/player1 "Antonio Apono"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1356374"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Antonio Apono"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1356375"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 20
:event/subtype "hands"
:event/player1 "Quincy Owusu-Abeyie"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1356382"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Antonio Apono"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1356385"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Quincy Owusu-Abeyie"
:event/player1 "Javier Martinez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1356387"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Duda"
:event/subtype "pushing"
:event/player1 "Iker Muniain"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1356388"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Duda"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1356390"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_22375"}

{:event/type "shotoff"
:event/elapsed 25
:event/subtype "distance"
:event/player1 "Antonio Apono"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1356393"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_22375"}

{:event/type "shoton"
:event/elapsed 26
:event/subtype "shot"
:event/player1 "Javier Martinez"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1356396"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Duda"
:event/player1 "Pablo Orbaiz"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1356397"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Duda"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1356398"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "David Lopez"
:event/subtype "shirt_pull"
:event/player1 "Jesus Gamez"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1356402"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Koikili Campo"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1356409"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_22375"}

{:event/type "shoton"
:event/elapsed 31
:event/subtype "shot"
:event/player1 "Duda"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1356412"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Duda"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1356413"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_22375"}

{:event/type "corner"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Duda"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1356413"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Javier Martinez"
:event/player1 "Ignacio Camacho"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1356417"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_22375"}

{:event/type "card"
:event/elapsed 32
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Ignacio Camacho"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_1356418"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_22375"}

{:event/type "shotoff"
:event/elapsed 33
:event/subtype "distance"
:event/player1 "Javier Martinez"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1356419"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Javier Martinez"
:event/player1 "Jose Salomon Rondon"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1356421"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 34
:event/player2 "Quincy Owusu-Abeyie"
:event/player1 "Koikili Campo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1356424"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Mikel San Jose"
:event/player1 "Ignacio Camacho"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1356426"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Enzo Maresca"
:event/player1 "David Lopez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1356428"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Duda"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1356430"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_22375"}

{:event/type "corner"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Duda"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1356430"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Gorka Iraizoz Moreno"
:event/subtype "pushing"
:event/player1 "Weligton"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1356433"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Antonio Apono"
:event/player1 "Ander Iturraspe"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1356436"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_22375"}

{:event/type "card"
:event/elapsed 38
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Ander Iturraspe"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1356437"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Quincy Owusu-Abeyie"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1356443"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Duda"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1356445"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_22375"}

{:event/type "corner"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Duda"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1356445"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Jesus Gamez"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1356450"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_22375"}

{:event/type "shoton"
:event/elapsed 41
:event/subtype "volley"
:event/player1 "Antonio Apono"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_1356453"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1356454"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_22375"}

{:event/type "corner"
:event/elapsed 42
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1356454"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Patrick Mtiliga"
:event/player1 "Fernando Llorente"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1356462"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player1 "Fernando Llorente"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1356464"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "Weligton"
:event/player1 "Fernando Llorente"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1356471"
:event/minute 46
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Jesus Gamez"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1356494"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_22375"}

{:event/type "corner"
:event/elapsed 46
:event/subtype "short"
:event/player1 "Duda"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1356496"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Enzo Maresca"
:event/player1 "Javier Martinez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1356500"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Andoni Iraola"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1356506"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/sortorder 2
:event/team "away"
:event/event_type "throwin"
:event/id "event_1356508"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Andoni Iraola"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_1356510"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Andoni Iraola"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1356513"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_1356516"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "David Lopez"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1356517"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_22375"}

{:event/type "shoton"
:event/elapsed 52
:event/subtype "shot"
:event/player1 "Iker Muniain"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1356523"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "David Lopez"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1356524"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_22375"}

{:event/type "corner"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "David Lopez"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1356524"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_22375"}

{:event/type "shotoff"
:event/elapsed 52
:event/subtype "header"
:event/player1 "Fernando Llorente"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1356525"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1356527"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Koikili Campo"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1356532"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Jesus Gamez"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1356539"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Javier Martinez"
:event/player1 "Martin Demichelis"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1356541"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_22375"}

{:event/type "card"
:event/elapsed 56
:event/card_type "y"
:event/player1 "Martin Demichelis"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_1356542"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 57
:event/subtype "hands"
:event/player1 "Mikel San Jose"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1356544"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_22375"}

{:event/type "card"
:event/elapsed 57
:event/card_type "y"
:event/subtype "hands"
:event/player1 "Mikel San Jose"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1356546"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Duda"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1356548"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 59
:event/player1 "David Lopez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1356550"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Fernando Llorente"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1356553"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Duda"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_1356559"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "David Lopez"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1356564"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_22375"}

{:event/type "corner"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "David Lopez"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1356564"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Fernando Llorente"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1356565"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Ignacio Camacho"
:event/player1 "Oscar de Marcos"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1356568"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "David Lopez"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1356570"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_22375"}

{:event/type "corner"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "David Lopez"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1356570"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Quincy Owusu-Abeyie"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1356572"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Antonio Apono"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_1356574"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Mikel San Jose"
:event/player1 "Jose Salomon Rondon"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1356576"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 66
:event/subtype "hands"
:event/player1 "Fernando Llorente"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1356579"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 66
:event/player1 "Jesus Gamez"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1356583"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_22375"}

{:event/type "shoton"
:event/elapsed 67
:event/subtype "blocked_shot"
:event/player1 "Fernando Llorente"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1356585"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Iker Muniain"
:event/player1 "Jesus Gamez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1356589"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Jesus Gamez"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1356594"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Jesus Gamez"
:event/subtype "shirt_pull"
:event/player1 "Iker Muniain"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1356596"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_22375"}

{:event/type "card"
:event/elapsed 70
:event/card_type "y"
:event/subtype "shirt_pull"
:event/player1 "Iker Muniain"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1356597"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Jesus Gamez"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1356602"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_22375"}

{:event/type "shotoff"
:event/elapsed 72
:event/subtype "big chance header"
:event/player1 "Jose Salomon Rondon"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1356603"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_22375"}

{:event/type "card"
:event/elapsed 72
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Jose Recio"
:event/sortorder 4
:event/team "home"
:event/event_type "card"
:event/id "event_1356608"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "David Lopez"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1356605"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_22375"}

{:event/type "shotoff"
:event/elapsed 73
:event/subtype "volley"
:event/player1 "Javier Martinez"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1356606"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_22375"}

{:event/type "shotoff"
:event/elapsed 74
:event/subtype "deflected"
:event/player1 "Oscar de Marcos"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1356610"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1356612"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_22375"}

{:event/type "corner"
:event/elapsed 74
:event/subtype "cross"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1356612"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_22375"}

{:event/type "shoton"
:event/elapsed 75
:event/subtype "blocked_shot"
:event/player1 "Sebastian Fernandez"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1356614"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Duda"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1356615"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 76
:event/player2 "Fernando Llorente"
:event/player1 "Martin Demichelis"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1356617"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Sergio Asenjo"
:event/subtype "pushing"
:event/player1 "Fernando Llorente"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1356619"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_22375"}

{:event/type "shotoff"
:event/elapsed 77
:event/subtype "shot"
:event/player1 "Sebastian Fernandez"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1356621"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_22375"}

{:event/type "card"
:event/elapsed 77
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Antonio Apono"
:event/sortorder 5
:event/team "home"
:event/event_type "card"
:event/id "event_1356623"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Oscar de Marcos"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1356624"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_22375"}

{:event/type "shotoff"
:event/elapsed 78
:event/subtype "header"
:event/player1 "Fernando Llorente"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1356625"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Duda"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1356629"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_22375"}

{:event/type "corner"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Duda"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1356629"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_22375"}

{:event/type "goal"
:event/elapsed 81
:event/player2 "Duda"
:event/subtype "header"
:event/player1 "Martin Demichelis"
:event/sortorder 1
:event/team "home"
:event/id "event_1356630"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 83
:event/player2 "Duda"
:event/player1 "Koikili Campo"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1356632"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_22375"}

{:event/type "shotoff"
:event/elapsed 84
:event/subtype "direct_freekick"
:event/player1 "Duda"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1356636"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 85
:event/subtype "hands"
:event/player1 "Sebastian Fernandez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1356639"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Sebastian Fernandez"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1356643"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Igor Gabilondo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1356648"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_22375"}

{:event/type "shotoff"
:event/elapsed 88
:event/subtype "volley"
:event/player1 "Sebastian Fernandez"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1356653"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player1 "Martin Demichelis"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1356656"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Oscar de Marcos"
:event/player1 "Ignacio Camacho"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1356661"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Oscar de Marcos"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1356665"
:event/minute 91
:event/match_id "match_22375"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "header"
:event/player1 "Fernando Llorente"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1356666"
:event/minute 91
:event/match_id "match_22375"}

{:event/type "card"
:event/elapsed_plus 1
:event/elapsed 90
:event/card_type "y"
:event/subtype "stall_time"
:event/player1 "Sergio Asenjo"
:event/sortorder 6
:event/team "home"
:event/event_type "card"
:event/id "event_1356670"
:event/minute 91
:event/match_id "match_22375"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Igor Martinez"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1356673"
:event/minute 92
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Weligton"
:event/subtype "shirt_pull"
:event/player1 "Igor Martinez"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1356675"
:event/minute 92
:event/match_id "match_22375"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Fernando Llorente"
:event/player1 "Martin Demichelis"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1356677"
:event/minute 93
:event/match_id "match_22375"}

{:event/type "goal"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Igor Gabilondo"
:event/subtype "header"
:event/player1 "Javier Martinez"
:event/sortorder 2
:event/team "away"
:event/id "event_1356679"
:event/event_type "goal"
:event/goal_type "n"
:event/minute 93
:event/match_id "match_22375"}


]

