
;;# data
[
{:match/id "match_15520"
:match/league "Netherlands Eredivisie"
:match/hometeam "PSV"
:match/awayteam "FC Groningen"
:match/score "2:0"
:match/hometeam_goals "2"
:match/awayteam_goals "0"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Lorenzo Burnet"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4680170"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Bryan Linssen"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4680173"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Tom Hiariej"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4680175"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_15520"}

{:event/type "corner"
:event/elapsed 4
:event/subtype "cross_right"
:event/player1 "Albert Rusnak"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4680176"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_15520"}

{:event/type "shoton"
:event/elapsed 4
:event/subtype "header"
:event/player1 "Hans Hateboer"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_4680177"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_15520"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Jeffrey Bruma"
:event/subtype "trip"
:event/player1 "Michael de Leeuw"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4680179"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Davy Proepper"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4680180"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Adam Maher"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4680184"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_15520"}

{:event/type "goal"
:event/elapsed 7
:event/player2 "Maxime Lestienne"
:event/subtype "shot"
:event/player1 "Luciano Narsingh"
:event/sortorder 5
:event/team "home"
:event/id "event_4680186"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_15520"}

{:event/type "foulcommit"
:event/elapsed 8
:event/player2 "Hans Hateboer"
:event/subtype "trip"
:event/player1 "Maxime Lestienne"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4680191"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_15520"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Santiago Arias"
:event/subtype "pushing"
:event/player1 "Lorenzo Burnet"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4680192"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Andres Guardado"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4680194"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_15520"}

{:event/type "shoton"
:event/elapsed 11
:event/subtype "blocked_shot"
:event/player1 "Luuk de Jong"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4680198"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_15520"}

{:event/type "shotoff"
:event/elapsed 15
:event/subtype "shot"
:event/player1 "Adam Maher"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4680209"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_15520"}

{:event/type "shoton"
:event/elapsed 17
:event/subtype "blocked_shot"
:event/player1 "Lorenzo Burnet"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4680214"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_15520"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Andres Guardado"
:event/subtype "trip"
:event/player1 "Albert Rusnak"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4680228"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_15520"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Santiago Arias"
:event/subtype "from_behind"
:event/player1 "Bryan Linssen"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4680221"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_15520"}

{:event/type "card"
:event/elapsed 20
:event/card_type "y"
:event/player1 "Bryan Linssen"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4680222"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Adam Maher"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4680224"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Adam Maher"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4680226"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_15520"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Adam Maher"
:event/subtype "pushing"
:event/player1 "Simon Tibbling"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4680232"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_15520"}

{:event/type "shoton"
:event/elapsed 24
:event/subtype "blocked_shot"
:event/player1 "Adam Maher"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4680234"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Maxime Lestienne"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4680235"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Maxime Lestienne"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4680237"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_15520"}

{:event/type "corner"
:event/elapsed 27
:event/subtype "cross_right"
:event/player1 "Maxime Lestienne"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4680245"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_15520"}

{:event/type "foulcommit"
:event/elapsed 30
:event/player2 "Andres Guardado"
:event/subtype "trip"
:event/player1 "Albert Rusnak"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4680250"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Adam Maher"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4680252"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_15520"}

{:event/type "corner"
:event/elapsed 31
:event/subtype "cross_right"
:event/player1 "Maxime Lestienne"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4680259"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_15520"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Andres Guardado"
:event/subtype "trip"
:event/player1 "Bryan Linssen"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4680261"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Maxime Lestienne"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4680262"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_15520"}

{:event/type "foulcommit"
:event/elapsed 34
:event/player2 "Luciano Narsingh"
:event/subtype "trip"
:event/player1 "Hans Hateboer"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4680265"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_15520"}

{:event/type "shotoff"
:event/elapsed 35
:event/subtype "shot"
:event/player1 "Albert Rusnak"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4680266"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Maxime Lestienne"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4680273"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_15520"}

{:event/type "shoton"
:event/elapsed 37
:event/subtype "blocked_shot"
:event/player1 "Michael de Leeuw"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4680276"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_15520"}

{:event/type "shoton"
:event/elapsed 37
:event/subtype "blocked_shot"
:event/player1 "Lorenzo Burnet"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_4680277"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Hans Hateboer"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4680279"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Albert Rusnak"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4680281"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Andres Guardado"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4680286"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_15520"}

{:event/type "shotoff"
:event/elapsed 40
:event/subtype "shot"
:event/player1 "Davy Proepper"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4680289"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_15520"}

{:event/type "shoton"
:event/elapsed 42
:event/subtype "blocked_shot"
:event/player1 "Lorenzo Burnet"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4680294"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_15520"}

{:event/type "corner"
:event/elapsed 42
:event/subtype "cross_left"
:event/player1 "Albert Rusnak"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4680295"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Lorenzo Burnet"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4680297"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_15520"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Andres Guardado"
:event/subtype "trip"
:event/player1 "Johan Kappelhof"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4680301"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_15520"}

{:event/type "card"
:event/elapsed 43
:event/card_type "y"
:event/player1 "Johan Kappelhof"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4680303"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Andres Guardado"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4680305"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_15520"}

{:event/type "shoton"
:event/elapsed 44
:event/subtype "header"
:event/player1 "Luuk de Jong"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4680306"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_15520"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Michael de Leeuw"
:event/subtype "trip"
:event/player1 "Joshua Brenet"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4680312"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_15520"}

{:event/type "card"
:event/elapsed 45
:event/card_type "y"
:event/subtype "violence"
:event/player1 "Albert Rusnak"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4680308"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_15520"}

{:event/type "card"
:event/elapsed 45
:event/card_type "y"
:event/subtype "violence"
:event/player1 "Andres Guardado"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4680309"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Albert Rusnak"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4680314"
:event/minute 46
:event/match_id "match_15520"}

{:event/type "shoton"
:event/elapsed 47
:event/subtype "blocked_shot"
:event/player1 "Luuk de Jong"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4680363"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_15520"}

{:event/type "corner"
:event/elapsed 48
:event/subtype "cross_right"
:event/player1 "Adam Maher"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4680366"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_15520"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Jeffrey Bruma"
:event/subtype "pushing"
:event/player1 "Michael de Leeuw"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4680381"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_15520"}

{:event/type "shotoff"
:event/elapsed 51
:event/subtype "distance"
:event/player1 "Andres Guardado"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4680390"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_15520"}

{:event/type "shoton"
:event/elapsed 52
:event/subtype "blocked_shot"
:event/player1 "Bryan Linssen"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4680394"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Albert Rusnak"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4680395"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_15520"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Santiago Arias"
:event/subtype "trip"
:event/player1 "Lorenzo Burnet"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4680401"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_15520"}

{:event/type "card"
:event/elapsed 53
:event/card_type "y"
:event/player1 "Lorenzo Burnet"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_4680404"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Luciano Narsingh"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4680408"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_15520"}

{:event/type "shoton"
:event/elapsed 54
:event/subtype "shot"
:event/player1 "Davy Proepper"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4680413"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_15520"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Luciano Narsingh"
:event/subtype "trip"
:event/player1 "Lorenzo Burnet"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4680417"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Andres Guardado"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4680435"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_15520"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Davy Proepper"
:event/subtype "trip"
:event/player1 "Tom Hiariej"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4680459"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_15520"}

{:event/type "shoton"
:event/elapsed 57
:event/subtype "big chance shot"
:event/player1 "Luciano Narsingh"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4680436"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_15520"}

{:event/type "shotoff"
:event/elapsed 59
:event/subtype "shot"
:event/player1 "Luciano Narsingh"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4680444"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Hans Hateboer"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4680448"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_15520"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Joshua Brenet"
:event/subtype "trip"
:event/player1 "Tom Hiariej"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4680453"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Maxime Lestienne"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4680462"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_15520"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Davy Proepper"
:event/subtype "trip"
:event/player1 "Simon Tibbling"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4680468"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_15520"}

{:event/type "card"
:event/elapsed 62
:event/card_type "y"
:event/player1 "Simon Tibbling"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_4680469"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Maxime Lestienne"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4680473"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_15520"}

{:event/type "shoton"
:event/elapsed 63
:event/subtype "volley"
:event/player1 "Adam Maher"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4680476"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Maxime Lestienne"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4680499"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Hans Hateboer"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4680505"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_15520"}

{:event/type "corner"
:event/elapsed 68
:event/subtype "cross_left"
:event/player1 "Albert Rusnak"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4680509"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Maxime Lestienne"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4680528"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_15520"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Johan Kappelhof"
:event/subtype "pushing"
:event/player1 "Luuk de Jong"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4680537"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Hans Hateboer"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4680543"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_15520"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Adam Maher"
:event/subtype "trip"
:event/player1 "Etienne Reijnen"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4680555"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_15520"}

{:event/type "goal"
:event/elapsed 76
:event/subtype "shot"
:event/player1 "Luciano Narsingh"
:event/sortorder 1
:event/team "home"
:event/id "event_4680567"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Mimoun Mahi"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4680578"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Mimoun Mahi"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4680598"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_15520"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Lorenzo Burnet"
:event/subtype "trip"
:event/player1 "Luciano Narsingh"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4680603"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_15520"}

{:event/type "shoton"
:event/elapsed 82
:event/subtype "shot"
:event/player1 "Maxime Lestienne"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4680615"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_15520"}

{:event/type "corner"
:event/elapsed 82
:event/subtype "cross_left"
:event/player1 "Maxime Lestienne"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4680616"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Lorenzo Burnet"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4680638"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_15520"}

{:event/type "shoton"
:event/elapsed 84
:event/subtype "header"
:event/player1 "Michael de Leeuw"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4680639"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Jesper Drost"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4680665"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Hans Hateboer"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4680672"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Jesper Drost"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4680675"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_15520"}

{:event/type "shotoff"
:event/elapsed 89
:event/subtype "shot"
:event/player1 "Luuk de Jong"
:event/sortorder 5
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4680683"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Bryan Linssen"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4680689"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_15520"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/sortorder 2
:event/team "away"
:event/event_type "throwin"
:event/id "event_4680695"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_15520"}

{:event/type "shotoff"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Jesper Drost"
:event/sortorder 8
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4680712"
:event/minute 92
:event/match_id "match_15520"}


]

