
;;# data
[
{:match/id "match_5600"
:match/league "France Ligue 1"
:match/hometeam "RC Lens"
:match/awayteam "AJ Auxerre"
:match/score "1:1"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "card"
:event/elapsed 20
:event/card_type "y"
:event/player1 "Eric Chelle"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1313502"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_5600"}

{:event/type "goal"
:event/elapsed 30
:event/player1 "Alaeddine Yahia"
:event/sortorder 0
:event/team "home"
:event/id "event_1313534"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_5600"}

{:event/type "card"
:event/elapsed 60
:event/card_type "y"
:event/player1 "Alain Traore"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1313845"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_5600"}

{:event/type "goal"
:event/elapsed 87
:event/player1 "Jean-Pascal Mignot"
:event/sortorder 0
:event/team "away"
:event/id "event_1313872"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_5600"}


]

