
;;# data
[
{:match/id "match_12996"
:match/league "Italy Serie A"
:match/hometeam "Carpi"
:match/awayteam "Udinese"
:match/score "2:1"
:match/hometeam_goals "2"
:match/awayteam_goals "1"}

{:event/type "foulcommit"
:event/elapsed 1
:event/subtype "hands"
:event/player1 "Ali Adnan"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5162516"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Cyril Thereau"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5162526"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Lorenzo Lollo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5162528"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_12996"}

{:event/type "corner"
:event/elapsed 5
:event/subtype "cross_right"
:event/player1 "Lorenzo Pasciuti"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_5162530"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_12996"}

{:event/type "shoton"
:event/elapsed 5
:event/subtype "deflected"
:event/player1 "Raffaele Bianco"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_5162532"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Ali Adnan"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5162535"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_12996"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Antonio Di Gaudio"
:event/player1 "Silvan Widmer"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5162539"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_12996"}

{:event/type "corner"
:event/elapsed 9
:event/subtype "cross_left"
:event/player1 "Lorenzo Pasciuti"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5162542"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Lorenzo Pasciuti"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5162546"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_12996"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Ali Adnan"
:event/subtype "pushing"
:event/player1 "Jerry Uche Mbakogu"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5162549"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Ali Adnan"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5162551"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Silvan Widmer"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5162560"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Lorenzo Pasciuti"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5162566"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_12996"}

{:event/type "shoton"
:event/elapsed 17
:event/subtype "deflected"
:event/player1 "Cyril Thereau"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_5162570"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_12996"}

{:event/type "corner"
:event/elapsed 17
:event/subtype "cross_right"
:event/player1 "Francesco Lodi"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_5162571"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Cristian Zaccardo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5162577"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Isaac Cofie"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5162579"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_12996"}

{:event/type "shoton"
:event/elapsed 19
:event/subtype "big chance shot"
:event/player1 "Cristian Zaccardo"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_5162581"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Silvan Widmer"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5162583"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_12996"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Ali Adnan"
:event/subtype "trip"
:event/player1 "Riccardo Gagliolo"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5162586"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Ivan Piris"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5162589"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Cristian Zaccardo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5162596"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_12996"}

{:event/type "shoton"
:event/elapsed 24
:event/subtype "header"
:event/player1 "Lorenzo Lollo"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5162597"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Raffaele Bianco"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5162600"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_12996"}

{:event/type "goal"
:event/elapsed 26
:event/player2 "Raffaele Bianco"
:event/subtype "header"
:event/player1 "Lorenzo Pasciuti"
:event/sortorder 1
:event/team "home"
:event/id "event_5162601"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_12996"}

{:event/type "shotoff"
:event/elapsed 27
:event/subtype "bad shot"
:event/player1 "Antonio Di Gaudio"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5162605"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_12996"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Stipe Perica"
:event/player1 "Isaac Cofie"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5162609"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Francesco Lodi"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5162613"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_12996"}

{:event/type "shotoff"
:event/elapsed 29
:event/subtype "header"
:event/player1 "Cyril Thereau"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5162614"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Felipe"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5162620"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_12996"}

{:event/type "corner"
:event/elapsed 31
:event/subtype "cross_right"
:event/player1 "Lorenzo Pasciuti"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_5162624"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_12996"}

{:event/type "shotoff"
:event/elapsed 33
:event/subtype "distance"
:event/player1 "Gaetano Letizia"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5162630"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_12996"}

{:event/type "foulcommit"
:event/elapsed 34
:event/player2 "Raffaele Bianco"
:event/player1 "Ivan Piris"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5162635"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_12996"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Silvan Widmer"
:event/player1 "Gaetano Letizia"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5162640"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_12996"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Silvan Widmer"
:event/player1 "Antonio Di Gaudio"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5162646"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_12996"}

{:event/type "shotoff"
:event/elapsed 39
:event/subtype "deflected"
:event/player1 "Lorenzo Lollo"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5162649"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_12996"}

{:event/type "corner"
:event/elapsed 39
:event/subtype "cross_left"
:event/player1 "Lorenzo Pasciuti"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_5162650"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_12996"}

{:event/type "shoton"
:event/elapsed 40
:event/subtype "blocked_header"
:event/player1 "Jerry Uche Mbakogu"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_5162651"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_12996"}

{:event/type "shoton"
:event/elapsed 40
:event/subtype "blocked_shot"
:event/player1 "Gaetano Letizia"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_5162653"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_12996"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Ali Adnan"
:event/subtype "advantage"
:event/player1 "Lorenzo Pasciuti"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5162657"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Ali Adnan"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5162661"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_12996"}

{:event/type "shotoff"
:event/elapsed 43
:event/subtype "header"
:event/player1 "Emmanuel Agyemang-Badu"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5162662"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_12996"}

{:event/type "shoton"
:event/elapsed 47
:event/subtype "shot"
:event/player1 "Cyril Thereau"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_5162718"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Ali Adnan"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5162738"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_12996"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Stipe Perica"
:event/player1 "Riccardo Gagliolo"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5162744"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_12996"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Bruno Fernandes"
:event/player1 "Cristian Zaccardo"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5162756"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_12996"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Kevin Lasagna"
:event/subtype "pushing"
:event/player1 "Felipe"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5162766"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_12996"}

{:event/type "shoton"
:event/elapsed 60
:event/subtype "volley"
:event/player1 "Kevin Lasagna"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_5162780"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_12996"}

{:event/type "corner"
:event/elapsed 60
:event/subtype "cross_left"
:event/player1 "Lorenzo Pasciuti"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_5162784"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_12996"}

{:event/type "corner"
:event/elapsed 61
:event/subtype "cross_right"
:event/player1 "Bruno Fernandes"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_5162789"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Bruno Fernandes"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5162791"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Lorenzo Pasciuti"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5162800"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Ali Adnan"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5162807"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_12996"}

{:event/type "corner"
:event/elapsed 64
:event/subtype "cross_left"
:event/player1 "Francesco Lodi"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_5162811"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Ivan Piris"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5162827"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_12996"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Marco Crimi"
:event/player1 "Ali Adnan"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5162837"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Marco Crimi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5162840"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Marco Crimi"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5162843"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_12996"}

{:event/type "goal"
:event/elapsed 70
:event/player2 "Kevin Lasagna"
:event/subtype "shot"
:event/player1 "Lorenzo Lollo"
:event/sortorder 4
:event/team "home"
:event/id "event_5162846"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_12996"}

{:event/type "foulcommit"
:event/elapsed 72
:event/player2 "Ali Adnan"
:event/player1 "Marco Crimi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5162856"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Francesco Lodi"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5162857"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_12996"}

{:event/type "shoton"
:event/elapsed 72
:event/subtype "blocked_shot"
:event/player1 "Bruno Fernandes"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_5162859"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_12996"}

{:event/type "goal"
:event/elapsed 72
:event/subtype "shot"
:event/player1 "Duvan Zapata"
:event/sortorder 4
:event/team "away"
:event/id "event_5162860"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Ali Adnan"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5162870"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_12996"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Gaetano Letizia"
:event/player1 "Duvan Zapata"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5162877"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Ivan Piris"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5162879"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_12996"}

{:event/type "foulcommit"
:event/elapsed 78
:event/player2 "Duvan Zapata"
:event/subtype "trip"
:event/player1 "Isaac Cofie"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5162888"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_12996"}

{:event/type "foulcommit"
:event/elapsed 78
:event/player2 "Marco Crimi"
:event/subtype "trip"
:event/player1 "Ivan Piris"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5162891"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_12996"}

{:event/type "card"
:event/elapsed 78
:event/card_type "y"
:event/player1 "Ivan Piris"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_5162892"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_12996"}

{:event/type "shoton"
:event/elapsed 79
:event/subtype "blocked_shot"
:event/player1 "Cristian Zaccardo"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_5162899"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_12996"}

{:event/type "corner"
:event/elapsed 80
:event/subtype "cross_left"
:event/player1 "Lorenzo Pasciuti"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5162903"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Ivan Piris"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5162911"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_12996"}

{:event/type "corner"
:event/elapsed 81
:event/subtype "cross_right"
:event/player1 "Bruno Fernandes"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_5162913"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_12996"}

{:event/type "shotoff"
:event/elapsed 81
:event/subtype "header"
:event/player1 "Duvan Zapata"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5162914"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Bruno Fernandes"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5162917"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_12996"}

{:event/type "corner"
:event/elapsed 82
:event/subtype "cross_right"
:event/player1 "Francesco Lodi"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_5162923"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_12996"}

{:event/type "shotoff"
:event/elapsed 82
:event/subtype "big chance post"
:event/player1 "Emmanuel Agyemang-Badu"
:event/sortorder 6
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5162928"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Ali Adnan"
:event/sortorder 7
:event/team "away"
:event/event_type "cross"
:event/id "event_5162926"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_12996"}

{:event/type "shotoff"
:event/elapsed 82
:event/subtype "header"
:event/player1 "Emmanuel Agyemang-Badu"
:event/sortorder 7
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5162927"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_12996"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Ivan Piris"
:event/player1 "Isaac Cofie"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5162936"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_12996"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Emmanuel Agyemang-Badu"
:event/player1 "Gaetano Letizia"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5162941"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Francesco Lodi"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5162942"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_12996"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Felipe"
:event/player1 "Lorenzo Lollo"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5162944"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_12996"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Kevin Lasagna"
:event/subtype "pushing"
:event/player1 "Emmanuel Agyemang-Badu"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5162949"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_12996"}

{:event/type "foulcommit"
:event/elapsed 87
:event/player2 "Jerry Uche Mbakogu"
:event/player1 "Felipe"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5162953"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_12996"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Emmanuel Agyemang-Badu"
:event/subtype "trip"
:event/player1 "Lorenzo Lollo"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5162960"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Francesco Lodi"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5162961"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_12996"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Emmanuel Agyemang-Badu"
:event/player1 "Lorenzo Pasciuti"
:event/sortorder 5
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5162967"
:event/minute 91
:event/match_id "match_12996"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Francesco Lodi"
:event/player1 "Isaac Cofie"
:event/sortorder 10
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5162972"
:event/minute 92
:event/match_id "match_12996"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Francesco Lodi"
:event/sortorder 11
:event/team "away"
:event/event_type "cross"
:event/id "event_5162973"
:event/minute 93
:event/match_id "match_12996"}

{:event/type "shoton"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "header"
:event/player1 "Emmanuel Agyemang-Badu"
:event/sortorder 12
:event/team "away"
:event/event_type "shoton"
:event/id "event_5162974"
:event/minute 93
:event/match_id "match_12996"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Felipe"
:event/player1 "Emanuele Suagher"
:event/sortorder 13
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5162976"
:event/minute 93
:event/match_id "match_12996"}

{:event/type "card"
:event/elapsed_plus 3
:event/elapsed 90
:event/card_type "y"
:event/subtype "kicked_ball_away"
:event/player1 "Emanuele Suagher"
:event/sortorder 14
:event/team "home"
:event/event_type "card"
:event/id "event_5162977"
:event/minute 93
:event/match_id "match_12996"}

{:event/type "foulcommit"
:event/elapsed_plus 4
:event/elapsed 90
:event/player2 "Felipe"
:event/player1 "Lorenzo Lollo"
:event/sortorder 15
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5162979"
:event/minute 94
:event/match_id "match_12996"}


]

