
;;# data
[
{:match/id "match_11148"
:match/league "Italy Serie A"
:match/hometeam "Udinese"
:match/awayteam "Inter"
:match/score "3:1"
:match/hometeam_goals "3"
:match/awayteam_goals "1"}

{:event/type "shoton"
:event/elapsed 4
:event/subtype "shot"
:event/player1 "Esteban Cambiasso"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1376183"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_11148"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Alexis Sanchez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1376184"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_11148"}

{:event/type "shoton"
:event/elapsed 5
:event/subtype "blocked_shot"
:event/player1 "Alexis Sanchez"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1376185"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Pablo Armero"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1376186"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Mauricio Isla"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1376189"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_11148"}

{:event/type "corner"
:event/elapsed 6
:event/subtype "short"
:event/player1 "Antonio Di Natale"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1376191"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Giampiero Pinzi"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1376192"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_11148"}

{:event/type "shotoff"
:event/elapsed 7
:event/subtype "header"
:event/player1 "Alexis Sanchez"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1376193"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_11148"}

{:event/type "foulcommit"
:event/elapsed 8
:event/player2 "Goran Pandev"
:event/player1 "Maurizio Domizzi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1376196"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Giampiero Pinzi"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_1376200"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Antonio Di Natale"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1376204"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_11148"}

{:event/type "corner"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Antonio Di Natale"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1376204"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_11148"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Thiago Motta"
:event/player1 "Cristian Zapata"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1376205"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_11148"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Kwadwo Asamoah"
:event/player1 "Lucio"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1376211"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_11148"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Alexis Sanchez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1376213"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Cristian Chivu"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1376215"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_11148"}

{:event/type "goal"
:event/elapsed 16
:event/player2 "Thiago Motta"
:event/subtype "shot"
:event/player1 "Dejan Stankovic"
:event/sortorder 1
:event/team "away"
:event/id "event_1376217"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Giampiero Pinzi"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1376219"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Maicon"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1376223"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_11148"}

{:event/type "corner"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Maicon"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1376223"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_11148"}

{:event/type "shoton"
:event/elapsed 19
:event/subtype "volley"
:event/player1 "Dejan Stankovic"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1376225"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Maicon"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1376226"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_11148"}

{:event/type "corner"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Maicon"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1376226"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_11148"}

{:event/type "shoton"
:event/elapsed 20
:event/subtype "volley"
:event/player1 "Lucio"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1376227"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Mauricio Isla"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1376229"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Antonio Di Natale"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_1376231"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_11148"}

{:event/type "corner"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Antonio Di Natale"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_1376231"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_11148"}

{:event/type "goal"
:event/elapsed 21
:event/player2 "Giampiero Pinzi"
:event/subtype "shot"
:event/player1 "Cristian Zapata"
:event/sortorder 1
:event/team "home"
:event/id "event_1376233"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_11148"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Alexis Sanchez"
:event/player1 "Esteban Cambiasso"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1376235"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Alexis Sanchez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1376237"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_11148"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Gokhan Inler"
:event/player1 "Dejan Stankovic"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1376239"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_11148"}

{:event/type "goal"
:event/elapsed 25
:event/subtype "direct_freekick"
:event/player1 "Antonio Di Natale"
:event/sortorder 0
:event/team "home"
:event/id "event_1376240"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_11148"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Samuel Eto'o"
:event/player1 "Giampiero Pinzi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1376241"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Cristian Chivu"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1376242"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_11148"}

{:event/type "shotoff"
:event/elapsed 28
:event/subtype "header"
:event/player1 "Esteban Cambiasso"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1376243"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_11148"}

{:event/type "shoton"
:event/elapsed 30
:event/subtype "distance"
:event/player1 "Samuel Eto'o"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1376245"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Mauricio Isla"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1376247"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_11148"}

{:event/type "shotoff"
:event/elapsed 31
:event/subtype "bad shot"
:event/player1 "Mauricio Isla"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1376250"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_11148"}

{:event/type "shotoff"
:event/elapsed 32
:event/subtype "distance"
:event/player1 "Dejan Stankovic"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1376252"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Kwadwo Asamoah"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1376254"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Giampiero Pinzi"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1376255"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_11148"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Kwadwo Asamoah"
:event/player1 "Javier Zanetti"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1376258"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_11148"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Dejan Stankovic"
:event/player1 "Gokhan Inler"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1376262"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_11148"}

{:event/type "shoton"
:event/elapsed 37
:event/subtype "direct_freekick"
:event/player1 "Dejan Stankovic"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1376263"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Samuel Eto'o"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1376264"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_11148"}

{:event/type "corner"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Samuel Eto'o"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1376264"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_11148"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Alexis Sanchez"
:event/player1 "Ivan Cordoba"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1376266"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_11148"}

{:event/type "shotoff"
:event/elapsed 38
:event/subtype "indirect freekick"
:event/player1 "Antonio Di Natale"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1376267"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_11148"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Samuel Eto'o"
:event/player1 "Mehdi Benatia"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1376269"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Maicon"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1376272"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Pablo Armero"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1376275"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Maicon"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1376278"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_11148"}

{:event/type "shotoff"
:event/elapsed 41
:event/subtype "deflected"
:event/player1 "Samuel Eto'o"
:event/sortorder 5
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1376280"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_11148"}

{:event/type "corner"
:event/elapsed 41
:event/subtype "short"
:event/player1 "Samuel Eto'o"
:event/sortorder 6
:event/team "away"
:event/event_type "corner"
:event/id "event_1376281"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Mauricio Isla"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1376294"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_11148"}

{:event/type "shotoff"
:event/elapsed 48
:event/subtype "shot"
:event/player1 "Antonio Di Natale"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1376296"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_11148"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Giampiero Pinzi"
:event/player1 "Dejan Stankovic"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1376298"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_11148"}

{:event/type "shoton"
:event/elapsed 50
:event/subtype "shot"
:event/player1 "Giampiero Pinzi"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1376301"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_11148"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Alexis Sanchez"
:event/player1 "Dejan Stankovic"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1376302"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_11148"}

{:event/type "shoton"
:event/elapsed 51
:event/subtype "direct_freekick"
:event/player1 "Maurizio Domizzi"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1376303"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_11148"}

{:event/type "corner"
:event/elapsed 51
:event/subtype "short"
:event/player1 "Antonio Di Natale"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1376304"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Antonio Di Natale"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1376305"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Maurizio Domizzi"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1376307"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Dejan Stankovic"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1376309"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Maicon"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1376313"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_11148"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Thiago Motta"
:event/subtype "obstruction"
:event/player1 "Gokhan Inler"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1376314"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Goran Pandev"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1376317"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_11148"}

{:event/type "corner"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Goran Pandev"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1376317"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_11148"}

{:event/type "shoton"
:event/elapsed 55
:event/subtype "blocked_shot"
:event/player1 "Lucio"
:event/sortorder 4
:event/team "away"
:event/event_type "shoton"
:event/id "event_1376319"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Antonio Di Natale"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1376320"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_11148"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Alexis Sanchez"
:event/player1 "Thiago Motta"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1376322"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_11148"}

{:event/type "card"
:event/elapsed 57
:event/card_type "y"
:event/player1 "Thiago Motta"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1376323"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Pablo Armero"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1376324"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Antonio Di Natale"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1376326"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_11148"}

{:event/type "corner"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Antonio Di Natale"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1376326"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Pablo Armero"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1376328"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_11148"}

{:event/type "shotoff"
:event/elapsed 60
:event/subtype "big chance volley"
:event/player1 "Antonio Di Natale"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1376329"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Antonio Di Natale"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1376334"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Antonio Di Natale"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1376336"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_11148"}

{:event/type "corner"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Antonio Di Natale"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1376336"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_11148"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Alexis Sanchez"
:event/player1 "Cristian Chivu"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1376339"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Pablo Armero"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1376340"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_11148"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Kwadwo Asamoah"
:event/subtype "obstruction"
:event/player1 "Ivan Cordoba"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1376343"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_11148"}

{:event/type "card"
:event/elapsed 64
:event/card_type "y"
:event/subtype "emergency_brake"
:event/player1 "Ivan Cordoba"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1376344"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Mauricio Isla"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1376346"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_11148"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Dejan Stankovic"
:event/subtype "pushing"
:event/player1 "Mehdi Benatia"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1376348"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Esteban Cambiasso"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_1376352"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Pablo Armero"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1376355"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_11148"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Gokhan Inler"
:event/player1 "Dejan Stankovic"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1376357"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_11148"}

{:event/type "goal"
:event/elapsed 69
:event/player2 "Kwadwo Asamoah"
:event/subtype "volley"
:event/player1 "Maurizio Domizzi"
:event/sortorder 3
:event/team "home"
:event/id "event_1376361"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Goran Pandev"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1376362"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Samuel Eto'o"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1376365"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_11148"}

{:event/type "corner"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Samuel Eto'o"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1376365"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_11148"}

{:event/type "foulcommit"
:event/elapsed 72
:event/player2 "Alexis Sanchez"
:event/subtype "obstruction"
:event/player1 "Cristian Chivu"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1376368"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_11148"}

{:event/type "card"
:event/elapsed 72
:event/card_type "y"
:event/subtype "emergency_brake"
:event/player1 "Cristian Chivu"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1376369"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Mauricio Isla"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1376370"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_11148"}

{:event/type "shotoff"
:event/elapsed 74
:event/subtype "volley"
:event/player1 "Antonio Di Natale"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1376371"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_11148"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Kwadwo Asamoah"
:event/player1 "Jonathan Biabiany"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1376373"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Giampiero Pinzi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1376376"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_11148"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Goran Pandev"
:event/player1 "Giampiero Pinzi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1376384"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_11148"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Pablo Armero"
:event/player1 "Lucio"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1376385"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_11148"}

{:event/type "shoton"
:event/elapsed 82
:event/subtype "shot"
:event/player1 "Alexis Sanchez"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1376387"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_11148"}

{:event/type "shotoff"
:event/elapsed 82
:event/subtype "shot"
:event/player1 "Antonio Di Natale"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1376388"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_11148"}

{:event/type "shoton"
:event/elapsed 82
:event/subtype "distance"
:event/player1 "Pablo Armero"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_1376390"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_11148"}

{:event/type "foulcommit"
:event/elapsed 83
:event/player2 "Maicon"
:event/subtype "pushing"
:event/player1 "Pablo Armero"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1376394"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_11148"}

{:event/type "shotoff"
:event/elapsed 84
:event/subtype "shot"
:event/player1 "Jonathan Biabiany"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1376396"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Kwadwo Asamoah"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1376399"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_11148"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Alexis Sanchez"
:event/player1 "Lucio"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1376405"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_11148"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Cristian Chivu"
:event/player1 "Mauricio Isla"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1376408"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Alexis Sanchez"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1376414"
:event/minute 93
:event/match_id "match_11148"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Pablo Armero"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1376416"
:event/minute 93
:event/match_id "match_11148"}

{:event/type "foulcommit"
:event/elapsed_plus 4
:event/elapsed 90
:event/player2 "German Denis"
:event/player1 "Dejan Stankovic"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1376418"
:event/minute 94
:event/match_id "match_11148"}

{:event/type "card"
:event/elapsed_plus 4
:event/elapsed 90
:event/card_type "y"
:event/player1 "Dejan Stankovic"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1376419"
:event/minute 94
:event/match_id "match_11148"}


]

