
;;# data
[
{:match/id "match_21815"
:match/league "Spain LIGA BBVA"
:match/hometeam "RC Deportivo de La Coruña"
:match/awayteam "Getafe CF"
:match/score "1:1"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "card"
:event/elapsed 36
:event/card_type "y"
:event/player1 "Cata Diaz"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_684258"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_21815"}

{:event/type "goal"
:event/elapsed 46
:event/player1 "Roberto Soldado"
:event/sortorder 0
:event/team "away"
:event/id "event_684396"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_21815"}

{:event/type "card"
:event/elapsed 56
:event/card_type "y"
:event/player1 "Juan Rodriguez"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_684492"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_21815"}

{:event/type "card"
:event/elapsed 62
:event/card_type "y"
:event/player1 "Fabio Celestini"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_684493"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_21815"}

{:event/type "card"
:event/elapsed 79
:event/card_type "y"
:event/player1 "Alberto Lopo"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_684628"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_21815"}

{:event/type "goal"
:event/elapsed 85
:event/player1 "Ivan Sanchez Riki"
:event/sortorder 0
:event/team "home"
:event/id "event_684583"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_21815"}

{:event/type "card"
:event/elapsed 85
:event/card_type "y"
:event/player1 "Manu del Moral"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_684631"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_21815"}


]

