
;;# data
[
{:match/id "match_11357"
:match/league "Italy Serie A"
:match/hometeam "Lecce"
:match/awayteam "Catania"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "shotoff"
:event/elapsed 1
:event/subtype "shot"
:event/player1 "Maxi Lopez"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1203766"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Alessandro Potenza"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1203769"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Giovanni Marchese"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1203773"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Giuseppe Mascara"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1203778"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_11357"}

{:event/type "shoton"
:event/elapsed 6
:event/subtype "shot"
:event/player1 "Maxi Lopez"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1203780"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1203781"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 8
:event/player2 "Matias Silvestre"
:event/subtype "pushing"
:event/player1 "Ruben Olivera"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1203784"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Giuseppe Mascara"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1203785"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Ciro Capuano"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1203786"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Alessandro Potenza"
:event/subtype "shirt_pull"
:event/player1 "Daniele Corvia"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1203790"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Andrea Rispoli"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1203791"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_11357"}

{:event/type "shoton"
:event/elapsed 12
:event/subtype "shot"
:event/player1 "Ruben Olivera"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1203793"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Mariano Julio Izco"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1203794"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Ciro Capuano"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1203795"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 13
:event/subtype "cross"
:event/player1 "Giuseppe Mascara"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1203797"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_11357"}

{:event/type "corner"
:event/elapsed 13
:event/subtype "cross"
:event/player1 "Giuseppe Mascara"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1203797"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 13
:event/subtype "cross"
:event/player1 "Giuseppe Mascara"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1203799"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_11357"}

{:event/type "corner"
:event/elapsed 13
:event/subtype "cross"
:event/player1 "Giuseppe Mascara"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1203799"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_11357"}

{:event/type "shotoff"
:event/elapsed 14
:event/subtype "shot"
:event/player1 "Maxi Lopez"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1203800"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Carlos Javier Grossmuller"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1203802"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Ruben Olivera"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1203804"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Nicolas Federico Spolli"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1203806"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Ciro Capuano"
:event/subtype "pushing"
:event/player1 "Jedaias Capucho Neves"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1203808"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Stefano Ferrario"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1203810"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Carlos Javier Grossmuller"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1203814"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Giuseppe Mascara"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1203823"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Alessandro Potenza"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1203826"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_11357"}

{:event/type "shotoff"
:event/elapsed 22
:event/subtype "shot"
:event/player1 "Maxi Lopez"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1203827"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_11357"}

{:event/type "shoton"
:event/elapsed 22
:event/subtype "shot"
:event/player1 "Djamel Mesbah"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1203829"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Ruben Olivera"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1203831"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Djamel Mesbah"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1203833"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Giuseppe Mascara"
:event/subtype "shirt_pull"
:event/player1 "Daniele Corvia"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1203835"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Ruben Olivera"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1203836"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Maxi Lopez"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1203839"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Alessandro Potenza"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1203841"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Ruben Olivera"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1203843"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_11357"}

{:event/type "shotoff"
:event/elapsed 27
:event/subtype "shot"
:event/player1 "Daniele Corvia"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1203844"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Alessandro Potenza"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1203846"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 28
:event/subtype "hands"
:event/player1 "Adrian Ricchiuti"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1203847"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Mariano Julio Izco"
:event/subtype "shirt_pull"
:event/player1 "Ignacio Piatti"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1203848"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Andrea Rispoli"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1203849"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Alessandro Potenza"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1203850"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_11357"}

{:event/type "shoton"
:event/elapsed 30
:event/subtype "blocked_shot"
:event/player1 "Giuseppe Mascara"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1203851"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_11357"}

{:event/type "corner"
:event/elapsed 31
:event/subtype "short"
:event/player1 "Giuseppe Mascara"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1203856"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Giuseppe Mascara"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1203857"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Stefano Ferrario"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1203859"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Djamel Mesbah"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1203861"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Giuseppe Mascara"
:event/subtype "shirt_pull"
:event/player1 "Andrea Rispoli"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1203863"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Mariano Julio Izco"
:event/sortorder 5
:event/team "away"
:event/event_type "cross"
:event/id "event_1203864"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_11357"}

{:event/type "shoton"
:event/elapsed 34
:event/subtype "shot"
:event/player1 "Maxi Lopez"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1203865"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Giuseppe Mascara"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1203867"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_11357"}

{:event/type "corner"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Giuseppe Mascara"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1203867"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Djamel Mesbah"
:event/subtype "pushing"
:event/player1 "Adrian Ricchiuti"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1203869"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Ignacio Piatti"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1203870"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Daniele Corvia"
:event/subtype "from_behind"
:event/player1 "Ezequiel Alejo Carboni"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1203872"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Ruben Olivera"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1203873"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_11357"}

{:event/type "shoton"
:event/elapsed 37
:event/subtype "shot"
:event/player1 "Daniele Corvia"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1203874"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_11357"}

{:event/type "goal"
:event/elapsed 37
:event/player2 "Ruben Olivera"
:event/subtype "shot"
:event/player1 "Daniele Corvia"
:event/sortorder 1
:event/team "home"
:event/id "event_1203875"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Marco Biagianti"
:event/subtype "shirt_pull"
:event/player1 "Andrea Rispoli"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1203876"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Giuseppe Mascara"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1203877"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Marco Biagianti"
:event/subtype "shirt_pull"
:event/player1 "Andrea Rispoli"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1203879"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Maxi Lopez"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1203881"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Alessandro Potenza"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1203884"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Djamel Mesbah"
:event/subtype "pushing"
:event/player1 "Adrian Ricchiuti"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1203885"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Giuseppe Vives"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1203886"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Ezequiel Alejo Carboni"
:event/subtype "from_behind"
:event/player1 "Jedaias Capucho Neves"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1203888"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Alessandro Potenza"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1203890"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Adrian Ricchiuti"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1203892"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_11357"}

{:event/type "corner"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Adrian Ricchiuti"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1203892"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Ciro Capuano"
:event/subtype "serious_foul"
:event/player1 "Ruben Olivera"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1203894"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_11357"}

{:event/type "card"
:event/elapsed 44
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Ruben Olivera"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_1203895"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Ciro Capuano"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_1203904"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Maxi Lopez"
:event/sortorder 5
:event/team "away"
:event/event_type "cross"
:event/id "event_1203905"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "Djamel Mesbah"
:event/subtype "pushing"
:event/player1 "Mariano Julio Izco"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1203906"
:event/minute 46
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Adrian Ricchiuti"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1203913"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Stefano Ferrario"
:event/subtype "shirt_pull"
:event/player1 "Maxi Lopez"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1203917"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Jedaias Capucho Neves"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1203918"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/sortorder 1
:event/team "home"
:event/event_type "throwin"
:event/id "event_1203920"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Stefano Ferrario"
:event/subtype "pushing"
:event/player1 "Maxi Lopez"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1203922"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Stefano Ferrario"
:event/subtype "pushing"
:event/player1 "Maxi Lopez"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1203924"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Medina Fabiano"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1203925"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Ciro Capuano"
:event/subtype "pushing"
:event/player1 "Jedaias Capucho Neves"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1203928"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Giuseppe Vives"
:event/subtype "pushing"
:event/player1 "Marco Biagianti"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1203929"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Giuseppe Vives"
:event/subtype "shirt_pull"
:event/player1 "Adrian Ricchiuti"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1203930"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Pablo Martin Ledesma"
:event/subtype "pushing"
:event/player1 "Ruben Olivera"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1203931"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Giuseppe Vives"
:event/subtype "pushing"
:event/player1 "Marco Biagianti"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1203932"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Djamel Mesbah"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1203933"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Maxi Lopez"
:event/subtype "from_behind"
:event/player1 "Stefano Ferrario"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1203936"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Daniele Corvia"
:event/subtype "from_behind"
:event/player1 "Pablo Martin Ledesma"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1203940"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Marco Biagianti"
:event/subtype "pushing"
:event/player1 "Carlos Javier Grossmuller"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1203941"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Mariano Julio Izco"
:event/subtype "pushing"
:event/player1 "Djamel Mesbah"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1203942"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Adrian Ricchiuti"
:event/subtype "pushing"
:event/player1 "Djamel Mesbah"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1203943"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Pablo Martin Ledesma"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1203944"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Ciro Capuano"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_1203948"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Giuseppe Vives"
:event/subtype "shirt_pull"
:event/player1 "Maxi Lopez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1203954"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Pablo Martin Ledesma"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1203957"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Medina Fabiano"
:event/subtype "pushing"
:event/player1 "Maxi Lopez"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1203958"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Andrea Rispoli"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1203959"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Carlos Javier Grossmuller"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1203961"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_11357"}

{:event/type "corner"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Carlos Javier Grossmuller"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1203961"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Alessandro Potenza"
:event/subtype "shirt_pull"
:event/player1 "Ruben Olivera"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1203964"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Nicolas Federico Spolli"
:event/subtype "shirt_pull"
:event/player1 "Jedaias Capucho Neves"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1203965"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1203968"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Giuseppe Mascara"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1203970"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_11357"}

{:event/type "shotoff"
:event/elapsed 66
:event/subtype "post"
:event/player1 "Mariano Julio Izco"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1203971"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Pablo Martin Ledesma"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1203977"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Ignacio Piatti"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1203979"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/sortorder 2
:event/team "home"
:event/event_type "throwin"
:event/id "event_1203981"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Ignacio Piatti"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1203982"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_11357"}

{:event/type "shotoff"
:event/elapsed 70
:event/subtype "shot"
:event/player1 "Daniele Corvia"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1203986"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Giuseppe Mascara"
:event/subtype "shirt_pull"
:event/player1 "Giuseppe Vives"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1203989"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_11357"}

{:event/type "shotoff"
:event/elapsed 71
:event/subtype "shot"
:event/player1 "Mirko Antenucci"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1203990"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Alejandro Daro Gomez"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1203993"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_11357"}

{:event/type "corner"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Alejandro Daro Gomez"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1203993"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Alejandro Daro Gomez"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1203997"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Alessandro Potenza"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1203999"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Ciro Capuano"
:event/sortorder 6
:event/team "away"
:event/event_type "cross"
:event/id "event_1204002"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Alejandro Daro Gomez"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1204004"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_11357"}

{:event/type "corner"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Alejandro Daro Gomez"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1204004"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_11357"}

{:event/type "shotoff"
:event/elapsed 73
:event/subtype "shot"
:event/player1 "Alessandro Potenza"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1204010"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_11357"}

{:event/type "shoton"
:event/elapsed 75
:event/subtype "blocked_shot"
:event/player1 "Alejandro Daro Gomez"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_1204018"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Giuseppe Mascara"
:event/sortorder 5
:event/team "away"
:event/event_type "cross"
:event/id "event_1204020"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Giuseppe Mascara"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1204036"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Pablo Martin Ledesma"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1204037"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Alejandro Daro Gomez"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1204040"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 79
:event/player2 "Alejandro Daro Gomez"
:event/subtype "pushing"
:event/player1 "Djamel Mesbah"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1204046"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Nicolas Federico Spolli"
:event/sortorder 5
:event/team "away"
:event/event_type "cross"
:event/id "event_1204048"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Matias Silvestre"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1204051"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_11357"}

{:event/type "shotoff"
:event/elapsed 81
:event/subtype "shot"
:event/player1 "Alejandro Daro Gomez"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1204057"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Alejandro Daro Gomez"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1204060"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 83
:event/player2 "Pablo Martin Ledesma"
:event/subtype "pushing"
:event/player1 "Giuseppe Vives"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1204064"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Ciro Capuano"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1204065"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Maxi Lopez"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1204082"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Alejandro Daro Gomez"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1204087"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Marco Biagianti"
:event/subtype "pushing"
:event/player1 "Giuseppe Vives"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1204093"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Gianni Munari"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1204101"
:event/minute 91
:event/match_id "match_11357"}

{:event/type "corner"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "short"
:event/player1 "Ignacio Piatti"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1204104"
:event/minute 91
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Djamel Mesbah"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1204107"
:event/minute 92
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Ignacio Piatti"
:event/subtype "pushing"
:event/player1 "Pablo Martin Ledesma"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1204109"
:event/minute 92
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Ciro Capuano"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1204117"
:event/minute 93
:event/match_id "match_11357"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Alessandro Potenza"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1204119"
:event/minute 94
:event/match_id "match_11357"}

{:event/type "foulcommit"
:event/elapsed_plus 4
:event/elapsed 90
:event/player2 "Matias Silvestre"
:event/subtype "pushing"
:event/player1 "Daniele Corvia"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1204121"
:event/minute 94
:event/match_id "match_11357"}


]

