
;;# data
[
{:match/id "match_22302"
:match/league "Spain LIGA BBVA"
:match/hometeam "Real Sporting de Gijón"
:match/awayteam "Real Madrid CF"
:match/score "0:1"
:match/hometeam_goals "0"
:match/awayteam_goals "1"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Cristiano Ronaldo"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1280105"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_22302"}

{:event/type "shotoff"
:event/elapsed 6
:event/subtype "direct_freekick"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1280121"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_22302"}

{:event/type "foulcommit"
:event/elapsed 6
:event/player2 "Cristiano Ronaldo"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1280123"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_22302"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Cristiano Ronaldo"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1280128"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_22302"}

{:event/type "foulcommit"
:event/elapsed 8
:event/player2 "Pepe"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1280137"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_22302"}

{:event/type "shotoff"
:event/elapsed 10
:event/subtype "post"
:event/player1 "Gonzalo Higuain"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1280150"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_22302"}

{:event/type "foulcommit"
:event/elapsed 11
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1280156"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_22302"}

{:event/type "card"
:event/elapsed 11
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Diego Castro"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_1280158"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_22302"}

{:event/type "shoton"
:event/elapsed 14
:event/subtype "deflected"
:event/player1 "Angel Di Maria"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1280174"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_22302"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1280177"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_22302"}

{:event/type "corner"
:event/elapsed 14
:event/subtype "cross"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1280177"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_22302"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Mesut Oezil"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1280197"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_22302"}

{:event/type "foulcommit"
:event/elapsed 17
:event/subtype "hands"
:event/player1 "Carmelo Gonzalez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1280203"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_22302"}

{:event/type "shotoff"
:event/elapsed 22
:event/subtype "shot"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1280246"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_22302"}

{:event/type "shotoff"
:event/elapsed 22
:event/subtype "bad shot"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1280249"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_22302"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Xabi Alonso"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1280262"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_22302"}

{:event/type "corner"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Xabi Alonso"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1280262"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_22302"}

{:event/type "shotoff"
:event/elapsed 24
:event/subtype "deflected"
:event/player1 "Sami Khedira"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1280264"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_22302"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1280273"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_22302"}

{:event/type "corner"
:event/elapsed 25
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1280273"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_22302"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Cristiano Ronaldo"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1280278"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_22302"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1280282"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_22302"}

{:event/type "shoton"
:event/elapsed 28
:event/subtype "shot"
:event/player1 "Diego Castro"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1280293"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_22302"}

{:event/type "foulcommit"
:event/elapsed 30
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1280303"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_22302"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1280334"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_22302"}

{:event/type "corner"
:event/elapsed 35
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1280334"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_22302"}

{:event/type "card"
:event/elapsed 35
:event/card_type "y"
:event/player1 "Gonzalo Higuain"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1280341"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_22302"}

{:event/type "foulcommit"
:event/elapsed 40
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1280365"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_22302"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Diego Castro"
:event/player1 "Sergio Ramos"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1280384"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_22302"}

{:event/type "card"
:event/elapsed_plus 1
:event/elapsed 45
:event/card_type "y"
:event/player1 "Carmelo Gonzalez"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1280407"
:event/minute 46
:event/match_id "match_22302"}

{:event/type "card"
:event/elapsed_plus 1
:event/elapsed 45
:event/card_type "y"
:event/player1 "Sami Khedira"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1280408"
:event/minute 46
:event/match_id "match_22302"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Angel Di Maria"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1280481"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_22302"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 45
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1280418"
:event/minute 47
:event/match_id "match_22302"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 45
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1280420"
:event/minute 47
:event/match_id "match_22302"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Xabi Alonso"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1280483"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_22302"}

{:event/type "corner"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Xabi Alonso"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1280483"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_22302"}

{:event/type "shotoff"
:event/elapsed 47
:event/subtype "bad shot"
:event/player1 "Angel Di Maria"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1280484"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_22302"}

{:event/type "foulcommit"
:event/elapsed 49
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1280486"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_22302"}

{:event/type "shoton"
:event/elapsed 50
:event/subtype "shot"
:event/player1 "Angel Di Maria"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1280487"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_22302"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1280489"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_22302"}

{:event/type "corner"
:event/elapsed 51
:event/subtype "cross"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1280489"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_22302"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Angel Di Maria"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_1280490"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_22302"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Carmelo Gonzalez"
:event/player1 "Pepe"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1280491"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_22302"}

{:event/type "shotoff"
:event/elapsed 53
:event/subtype "direct_freekick"
:event/player1 "Gaston Sangoy"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1280492"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_22302"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Gaston Sangoy"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1280493"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_22302"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Angel Di Maria"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1280498"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_22302"}

{:event/type "foulcommit"
:event/elapsed 55
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1280501"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_22302"}

{:event/type "shotoff"
:event/elapsed 56
:event/subtype "shot"
:event/player1 "Gaston Sangoy"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1280502"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_22302"}

{:event/type "shotoff"
:event/elapsed 57
:event/subtype "deflected"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1280503"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_22302"}

{:event/type "foulcommit"
:event/elapsed 59
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1280506"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_22302"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Sergio Ramos"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1280510"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_22302"}

{:event/type "shotoff"
:event/elapsed 62
:event/subtype "shot"
:event/player1 "Xabi Alonso"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1280511"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_22302"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player1 "Sergio Ramos"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1280513"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_22302"}

{:event/type "foulcommit"
:event/elapsed 66
:event/subtype "hands"
:event/player1 "Karim Benzema"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1280521"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_22302"}

{:event/type "foulcommit"
:event/elapsed 68
:event/subtype "pushing"
:event/player1 "Sergio Ramos"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1280522"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_22302"}

{:event/type "shoton"
:event/elapsed 68
:event/subtype "shot"
:event/player1 "Gonzalo Higuain"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1280523"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_22302"}

{:event/type "corner"
:event/elapsed 69
:event/subtype "short"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1280525"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_22302"}

{:event/type "shotoff"
:event/elapsed 69
:event/subtype "big chance shot"
:event/player1 "Gaston Sangoy"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1280527"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_22302"}

{:event/type "foulcommit"
:event/elapsed 72
:event/player1 "Sebastian Eguren"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1280532"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_22302"}

{:event/type "card"
:event/elapsed 72
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Sebastian Eguren"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_1280533"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_22302"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Marcelo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1280536"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_22302"}

{:event/type "shoton"
:event/elapsed 76
:event/subtype "shot"
:event/player1 "Karim Benzema"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1280542"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_22302"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1280543"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_22302"}

{:event/type "corner"
:event/elapsed 76
:event/subtype "cross"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1280543"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_22302"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1280545"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_22302"}

{:event/type "corner"
:event/elapsed 77
:event/subtype "short"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1280547"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_22302"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Sergio Ramos"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_1280548"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_22302"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Juan Pablo"
:event/player1 "Sami Khedira"
:event/sortorder 5
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1280549"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_22302"}

{:event/type "shotoff"
:event/elapsed 79
:event/subtype "big chance shot"
:event/player1 "Marcelo"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1280552"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_22302"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1280554"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_22302"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Miguel Angel de las Cuevas"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1280556"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_22302"}

{:event/type "corner"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Miguel Angel de las Cuevas"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1280556"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_22302"}

{:event/type "foulcommit"
:event/elapsed 80
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1280557"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_22302"}

{:event/type "card"
:event/elapsed 82
:event/card_type "y"
:event/player1 "Lora"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1280600"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_22302"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Sergio Ramos"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1280561"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_22302"}

{:event/type "goal"
:event/elapsed 82
:event/subtype "shot"
:event/player1 "Gonzalo Higuain"
:event/sortorder 2
:event/team "away"
:event/id "event_1280562"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_22302"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1280563"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_22302"}

{:event/type "shoton"
:event/elapsed 84
:event/subtype "header"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1280564"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_22302"}

{:event/type "foulcommit"
:event/elapsed 88
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1280572"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_22302"}

{:event/type "card"
:event/elapsed 88
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Miguel Angel de las Cuevas"
:event/sortorder 4
:event/team "home"
:event/event_type "card"
:event/id "event_1280573"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_22302"}

{:event/type "card"
:event/elapsed 89
:event/card_type "y"
:event/player1 "Luis Moran"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_1283592"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_22302"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1280580"
:event/minute 91
:event/match_id "match_22302"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_1280589"
:event/minute 92
:event/match_id "match_22302"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Cristiano Ronaldo"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1280590"
:event/minute 92
:event/match_id "match_22302"}

{:event/type "foulcommit"
:event/elapsed_plus 4
:event/elapsed 90
:event/player2 "Cristiano Ronaldo"
:event/player1 "Alberto Botia"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1280593"
:event/minute 94
:event/match_id "match_22302"}

{:event/type "card"
:event/elapsed_plus 4
:event/elapsed 90
:event/card_type "r"
:event/subtype "serious_fouls"
:event/player1 "Alberto Botia"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_1280594"
:event/minute 94
:event/match_id "match_22302"}


]

