
;;# data
[
{:match/id "match_24133"
:match/league "Spain LIGA BBVA"
:match/hometeam "Real Madrid CF"
:match/awayteam "Elche CF"
:match/score "5:1"
:match/hometeam_goals "5"
:match/awayteam_goals "1"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Ferran Corominas"
:event/subtype "pull"
:event/player1 "Daniel Carvajal"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3764361"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_24133"}

{:event/type "card"
:event/elapsed 4
:event/card_type "y"
:event/player1 "Daniel Carvajal"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_3764364"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_24133"}

{:event/type "shoton"
:event/elapsed 5
:event/subtype "direct_freekick"
:event/player1 "Edu Albacar"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3764383"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_24133"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Marcelo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3764391"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_24133"}

{:event/type "corner"
:event/elapsed 6
:event/subtype "cross_left"
:event/player1 "Toni Kroos"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3764395"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_24133"}

{:event/type "foulcommit"
:event/elapsed 6
:event/player2 "Garry Mendes Rodrigues"
:event/subtype "pushing"
:event/player1 "Asier Illarramendi"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3764400"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_24133"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "James Rodriguez"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3764418"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_24133"}

{:event/type "foulcommit"
:event/elapsed 8
:event/player2 "Victor Romero Rodriguez"
:event/subtype "trip"
:event/player1 "Isco"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3764424"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_24133"}

{:event/type "foulcommit"
:event/elapsed 8
:event/player2 "Sergio Pelegrin"
:event/subtype "trip"
:event/player1 "James Rodriguez"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3764432"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_24133"}

{:event/type "shotoff"
:event/elapsed 9
:event/subtype "distance"
:event/player1 "Toni Kroos"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3764446"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_24133"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Isco"
:event/subtype "trip"
:event/player1 "Pedro Mosquera"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3764456"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_24133"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Asier Illarramendi"
:event/subtype "pushing"
:event/player1 "Jonathas"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3764475"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_24133"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Isco"
:event/subtype "trip"
:event/player1 "Domingo Cisma"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3764479"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_24133"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "James Rodriguez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3764484"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_24133"}

{:event/type "shotoff"
:event/elapsed 12
:event/subtype "header"
:event/player1 "Raphael Varane"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3764488"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_24133"}

{:event/type "corner"
:event/elapsed 14
:event/subtype "cross_left"
:event/player1 "Edu Albacar"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_3764519"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_24133"}

{:event/type "shoton"
:event/elapsed 14
:event/subtype "blocked_shot"
:event/player1 "Adrian Gonzalez"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_3764525"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_24133"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Pedro Mosquera"
:event/subtype "penalty"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3764531"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_24133"}

{:event/type "goal"
:event/elapsed 15
:event/player1 "Edu Albacar"
:event/sortorder 0
:event/team "away"
:event/id "event_3764541"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_24133"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Garry Mendes Rodrigues"
:event/subtype "trip"
:event/player1 "Marcelo"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3764561"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_24133"}

{:event/type "card"
:event/elapsed 17
:event/card_type "y"
:event/player1 "Marcelo"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_3764563"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_24133"}

{:event/type "shotoff"
:event/elapsed 18
:event/subtype "direct_freekick"
:event/player1 "Edu Albacar"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3764578"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_24133"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "James Rodriguez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3764606"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_24133"}

{:event/type "goal"
:event/elapsed 20
:event/player2 "James Rodriguez"
:event/subtype "header"
:event/player1 "Gareth Bale"
:event/sortorder 1
:event/team "home"
:event/id "event_3764607"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_24133"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Daniel Carvajal"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3764626"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_24133"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Marcelo"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3764635"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_24133"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Isco"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3764646"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_24133"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Sergio Ramos"
:event/subtype "obstruction"
:event/player1 "Garry Mendes Rodrigues"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3764655"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_24133"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "David Lomban"
:event/subtype "pushing"
:event/player1 "Marcelo"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3764671"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_24133"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Marcelo"
:event/subtype "penalty"
:event/player1 "Garry Mendes Rodrigues"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3764705"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_24133"}

{:event/type "goal"
:event/elapsed 28
:event/player1 "Cristiano Ronaldo"
:event/sortorder 0
:event/team "home"
:event/id "event_3764713"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_24133"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Edu Albacar"
:event/subtype "trip"
:event/player1 "James Rodriguez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3764728"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_24133"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Raphael Varane"
:event/subtype "pushing"
:event/player1 "Jonathas"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3764736"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_24133"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3764747"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_24133"}

{:event/type "corner"
:event/elapsed 30
:event/subtype "short_left"
:event/player1 "Toni Kroos"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3764750"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_24133"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Isco"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3764751"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_24133"}

{:event/type "corner"
:event/elapsed 30
:event/subtype "cross_left"
:event/player1 "Toni Kroos"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_3764752"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_24133"}

{:event/type "foulcommit"
:event/elapsed 30
:event/player2 "Edu Albacar"
:event/subtype "pushing"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3764756"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_24133"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Asier Illarramendi"
:event/subtype "trip"
:event/player1 "Garry Mendes Rodrigues"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3764764"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_24133"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Marcelo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3764773"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_24133"}

{:event/type "goal"
:event/elapsed 32
:event/player2 "Marcelo"
:event/subtype "header"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 1
:event/team "home"
:event/id "event_3764775"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_24133"}

{:event/type "shotoff"
:event/elapsed 35
:event/subtype "distance"
:event/player1 "James Rodriguez"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3764814"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_24133"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Isco"
:event/subtype "trip"
:event/player1 "Victor Romero Rodriguez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3764828"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_24133"}

{:event/type "shoton"
:event/elapsed 37
:event/subtype "direct_freekick"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3764837"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_24133"}

{:event/type "shoton"
:event/elapsed 38
:event/subtype "blocked_shot"
:event/player1 "Isco"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_3764854"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_24133"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_3764855"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_24133"}

{:event/type "shoton"
:event/elapsed 38
:event/subtype "big chance shot"
:event/player1 "Toni Kroos"
:event/sortorder 6
:event/team "home"
:event/event_type "shoton"
:event/id "event_3764857"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_24133"}

{:event/type "shoton"
:event/elapsed 39
:event/subtype "distance"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3764881"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_24133"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Edu Albacar"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3764920"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_24133"}

{:event/type "corner"
:event/elapsed 44
:event/subtype "cross_right"
:event/player1 "James Rodriguez"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3764943"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_24133"}

{:event/type "shoton"
:event/elapsed 44
:event/subtype "big chance header"
:event/player1 "Sergio Ramos"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_3764947"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_24133"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Asier Illarramendi"
:event/subtype "trip"
:event/player1 "Victor Romero Rodriguez"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3764954"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_24133"}

{:event/type "corner"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross_left"
:event/player1 "Toni Kroos"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_3764992"
:event/minute 46
:event/match_id "match_24133"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "Toni Kroos"
:event/subtype "pushing"
:event/player1 "Garry Mendes Rodrigues"
:event/sortorder 6
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3764999"
:event/minute 46
:event/match_id "match_24133"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Marcelo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3765111"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_24133"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Daniel Carvajal"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3765121"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_24133"}

{:event/type "shotoff"
:event/elapsed 48
:event/subtype "header"
:event/player1 "Gareth Bale"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3765122"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_24133"}

{:event/type "shotoff"
:event/elapsed 50
:event/subtype "deflected"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3765164"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_24133"}

{:event/type "corner"
:event/elapsed 50
:event/subtype "cross_left"
:event/player1 "James Rodriguez"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_3765165"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_24133"}

{:event/type "corner"
:event/elapsed 51
:event/subtype "cross_left"
:event/player1 "James Rodriguez"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3765172"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_24133"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Sergio Ramos"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3765179"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_24133"}

{:event/type "shotoff"
:event/elapsed 51
:event/subtype "big chance shot"
:event/player1 "Ferran Corominas"
:event/sortorder 5
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3765190"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_24133"}

{:event/type "shotoff"
:event/elapsed 52
:event/subtype "big chance shot"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3765200"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_24133"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Asier Illarramendi"
:event/subtype "trip"
:event/player1 "Garry Mendes Rodrigues"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3765205"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_24133"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Garry Mendes Rodrigues"
:event/subtype "trip"
:event/player1 "Daniel Carvajal"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3765224"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_24133"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Edu Albacar"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3765227"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_24133"}

{:event/type "shotoff"
:event/elapsed 56
:event/subtype "distance"
:event/player1 "Pedro Mosquera"
:event/sortorder 5
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3765272"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_24133"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Victor Romero Rodriguez"
:event/subtype "trip"
:event/player1 "Sergio Ramos"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3765298"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_24133"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Edu Albacar"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3765299"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_24133"}

{:event/type "shotoff"
:event/elapsed 58
:event/subtype "miss_kick"
:event/player1 "Victor Romero Rodriguez"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3765305"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_24133"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Cristiano Ronaldo"
:event/subtype "trip"
:event/player1 "Edu Albacar"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3765322"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_24133"}

{:event/type "card"
:event/elapsed 58
:event/card_type "y"
:event/player1 "Edu Albacar"
:event/sortorder 4
:event/team "away"
:event/event_type "card"
:event/id "event_3765326"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_24133"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "James Rodriguez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3765340"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_24133"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Faycal Fajr"
:event/subtype "trip"
:event/player1 "Daniel Carvajal"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3765376"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_24133"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Victor Romero Rodriguez"
:event/subtype "pull"
:event/player1 "Asier Illarramendi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3765390"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_24133"}

{:event/type "shoton"
:event/elapsed 62
:event/subtype "blocked_shot"
:event/player1 "Edu Albacar"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3765400"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_24133"}

{:event/type "corner"
:event/elapsed 63
:event/subtype "cross_left"
:event/player1 "Faycal Fajr"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3765404"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_24133"}

{:event/type "shoton"
:event/elapsed 63
:event/subtype "header"
:event/player1 "David Lomban"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3765408"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_24133"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Isco"
:event/subtype "obstruction"
:event/player1 "Domingo Cisma"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3765446"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_24133"}

{:event/type "shoton"
:event/elapsed 66
:event/subtype "big chance shot"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3765476"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_24133"}

{:event/type "corner"
:event/elapsed 66
:event/subtype "cross_left"
:event/player1 "Toni Kroos"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3765481"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_24133"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Marcelo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3765532"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_24133"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Isco"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3765580"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_24133"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "James Rodriguez"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3765586"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_24133"}

{:event/type "shotoff"
:event/elapsed 74
:event/subtype "distance"
:event/player1 "Jonathas"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3765619"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_24133"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Isco"
:event/subtype "trip"
:event/player1 "Garry Mendes Rodrigues"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3765671"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_24133"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Gareth Bale"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3765706"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_24133"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Cristiano Ronaldo"
:event/subtype "penalty"
:event/player1 "Mario Pasalic"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3765718"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_24133"}

{:event/type "goal"
:event/elapsed 80
:event/player1 "Cristiano Ronaldo"
:event/sortorder 2
:event/team "home"
:event/id "event_3765724"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_24133"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Alvaro Arbeloa"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3765758"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_24133"}

{:event/type "shotoff"
:event/elapsed 84
:event/subtype "crossbar"
:event/player1 "Toni Kroos"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3765762"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_24133"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Pedro Mosquera"
:event/subtype "pushing"
:event/player1 "Raphael Varane"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3765784"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_24133"}

{:event/type "shotoff"
:event/elapsed 86
:event/subtype "bad shot"
:event/player1 "Javier Hernandez"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3765789"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_24133"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Marcelo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3765799"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_24133"}

{:event/type "foulcommit"
:event/elapsed 87
:event/player2 "Jonathas"
:event/subtype "pull"
:event/player1 "Nacho Fernandez"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3765806"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_24133"}

{:event/type "shoton"
:event/elapsed 87
:event/subtype "blocked_shot"
:event/player1 "Gareth Bale"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_3765814"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_24133"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Marcelo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3765817"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_24133"}

{:event/type "shoton"
:event/elapsed 88
:event/subtype "big chance header"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3765820"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_24133"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Faycal Fajr"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3765822"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_24133"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "distance"
:event/player1 "Pedro Mosquera"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3765886"
:event/minute 91
:event/match_id "match_24133"}

{:event/type "goal"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Gareth Bale"
:event/subtype "shot"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 6
:event/team "home"
:event/id "event_3765894"
:event/event_type "goal"
:event/goal_type "n"
:event/minute 92
:event/match_id "match_24133"}


]

