
;;# data
[
{:match/id "match_5613"
:match/league "France Ligue 1"
:match/hometeam "SM Caen"
:match/awayteam "OGC Nice"
:match/score "0:0"
:match/hometeam_goals "0"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 38
:event/card_type "y"
:event/player1 "Gregory Paisley"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1326081"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_5613"}

{:event/type "card"
:event/elapsed 40
:event/card_type "y"
:event/player1 "Abdou Traore"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1326082"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_5613"}

{:event/type "card"
:event/elapsed 41
:event/card_type "y"
:event/player1 "Romain Hamouma"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1326219"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_5613"}

{:event/type "card"
:event/elapsed 73
:event/card_type "y"
:event/player1 "Damien Marcq"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1326461"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_5613"}

{:event/type "card"
:event/elapsed 89
:event/card_type "y"
:event/player1 "Kafoumba Coulibaly"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1326524"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_5613"}


]

