
;;# data
[
{:match/id "match_23705"
:match/league "Spain LIGA BBVA"
:match/hometeam "RCD Espanyol"
:match/awayteam "UD Almería"
:match/score "1:2"
:match/hometeam_goals "1"
:match/awayteam_goals "2"}

{:event/type "card"
:event/elapsed 16
:event/card_type "y"
:event/player1 "Victor Alvarez"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3425352"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_23705"}

{:event/type "card"
:event/elapsed 29
:event/card_type "y"
:event/player1 "Cristian Stuani"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3425397"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_23705"}

{:event/type "card"
:event/elapsed 34
:event/card_type "y"
:event/player1 "Sebastian Dubarbier"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3425415"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_23705"}

{:event/type "goal"
:event/elapsed 42
:event/player2 "Sergio Garcia"
:event/player1 "Cristian Stuani"
:event/sortorder 0
:event/team "home"
:event/id "event_3425447"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_23705"}

{:event/type "card"
:event/elapsed 48
:event/card_type "y"
:event/player1 "Cristian Stuani"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3425548"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_23705"}

{:event/type "card"
:event/elapsed 52
:event/card_type "y"
:event/player1 "Corona"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3425570"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_23705"}

{:event/type "goal"
:event/elapsed 69
:event/player2 "Corona"
:event/player1 "Francisco Velez"
:event/sortorder 0
:event/team "away"
:event/id "event_3425661"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_23705"}

{:event/type "card"
:event/elapsed 71
:event/card_type "y"
:event/player1 "Victor Sanchez Mata"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3425671"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_23705"}

{:event/type "goal"
:event/elapsed 72
:event/player1 "Suso"
:event/sortorder 2
:event/team "away"
:event/id "event_3425679"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_23705"}

{:event/type "card"
:event/elapsed 80
:event/card_type "y"
:event/player1 "Sergio Garcia"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3425712"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_23705"}

{:event/type "card"
:event/elapsed 87
:event/card_type "y"
:event/player1 "Angel Trujillo"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3425753"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_23705"}

{:event/type "card"
:event/elapsed 89
:event/card_type "r"
:event/player1 "David Lopez"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3425777"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_23705"}

{:event/type "card"
:event/elapsed 89
:event/card_type "y"
:event/player1 "Hector Moreno"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_3426273"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_23705"}


]

