
;;# data
[
{:match/id "match_23699"
:match/league "Spain LIGA BBVA"
:match/hometeam "Elche CF"
:match/awayteam "Levante UD"
:match/score "1:1"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "card"
:event/elapsed 17
:event/card_type "y"
:event/player1 "Pedro Lopez"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3418591"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_23699"}

{:event/type "card"
:event/elapsed 53
:event/card_type "y"
:event/player1 "Keylor Navas"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3418645"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_23699"}

{:event/type "goal"
:event/elapsed 63
:event/player2 "Garry Mendes Rodrigues"
:event/player1 "Richmond Boakye"
:event/sortorder 0
:event/team "home"
:event/id "event_3418661"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_23699"}

{:event/type "card"
:event/elapsed 65
:event/card_type "y"
:event/player1 "Carles Gil"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3418668"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_23699"}

{:event/type "card"
:event/elapsed 69
:event/card_type "y"
:event/player1 "Simao"
:event/sortorder 4
:event/team "away"
:event/event_type "card"
:event/id "event_3418675"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_23699"}

{:event/type "card"
:event/elapsed 70
:event/card_type "y"
:event/player1 "Domingo Cisma"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3418677"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_23699"}

{:event/type "goal"
:event/elapsed 74
:event/player1 "Angel Rodriguez"
:event/sortorder 0
:event/team "away"
:event/id "event_3418682"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_23699"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Pape Kouli Diop"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3418698"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_23699"}


]

