
;;# data
[
{:match/id "match_24544"
:match/league "Spain LIGA BBVA"
:match/hometeam "Valencia CF"
:match/awayteam "Málaga CF"
:match/score "3:2"
:match/hometeam_goals "3"
:match/awayteam_goals "0"}

{:event/type "foulcommit"
:event/elapsed 1
:event/player2 "Duda"
:event/subtype "trip"
:event/player1 "Joao Cancelo"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4915836"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "Ricardo Horta"
:event/subtype "trip"
:event/player1 "Javi Fuego"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4915854"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Duda"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4915868"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Daniel Parejo"
:event/subtype "trip"
:event/player1 "Ignacio Camacho"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4915892"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_24544"}

{:event/type "corner"
:event/elapsed 6
:event/subtype "cross_right"
:event/player1 "Duda"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4915912"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Duda"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4915963"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Pablo Piatti"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4915977"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_24544"}

{:event/type "corner"
:event/elapsed 11
:event/subtype "cross_left"
:event/player1 "Pablo Piatti"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4915985"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Jose Gaya"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4915993"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Joao Cancelo"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_4915999"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Joao Cancelo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4916008"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_24544"}

{:event/type "corner"
:event/elapsed 12
:event/subtype "cross_right"
:event/player1 "Pablo Piatti"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4916012"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Miguel Torres"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4916037"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Ricardo Horta"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4916065"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_24544"}

{:event/type "shoton"
:event/elapsed 15
:event/subtype "header"
:event/player1 "Charles"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4916066"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Miguel Torres"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4916070"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "Andre Gomes"
:event/subtype "trip"
:event/player1 "Ignacio Camacho"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4916076"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Joao Cancelo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4916101"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Andre Gomes"
:event/subtype "trip"
:event/player1 "Ignacio Camacho"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4916520"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Santi Mina"
:event/subtype "trip"
:event/player1 "Pablo Fornals"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4916186"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Santi Mina"
:event/subtype "trip"
:event/player1 "Miguel Torres"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4916113"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Pablo Piatti"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4916129"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_24544"}

{:event/type "goal"
:event/elapsed 19
:event/player1 "Charles"
:event/sortorder 1
:event/team "away"
:event/id "event_4916136"
:event/event_type "goal"
:event/goal_type "o"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Duda"
:event/subtype "trip"
:event/player1 "Joao Cancelo"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4916153"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Duda"
:event/subtype "trip"
:event/player1 "Andre Gomes"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4916525"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 21
:event/subtype "hands"
:event/player1 "Santi Mina"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4916143"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Duda"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4916154"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_24544"}

{:event/type "corner"
:event/elapsed 21
:event/subtype "cross_left"
:event/player1 "Pablo Piatti"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4916159"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Andre Gomes"
:event/subtype "trip"
:event/player1 "Marcos Angeleri"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4916191"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_24544"}

{:event/type "card"
:event/elapsed 23
:event/card_type "y"
:event/player1 "Marcos Angeleri"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4916192"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Pablo Piatti"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4916200"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Javi Fuego"
:event/subtype "trip"
:event/player1 "Ricardo Horta"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4916236"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_24544"}

{:event/type "corner"
:event/elapsed 28
:event/subtype "cross_right"
:event/player1 "Duda"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4916260"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_24544"}

{:event/type "corner"
:event/elapsed 33
:event/subtype "cross_left"
:event/player1 "Pablo Piatti"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4916329"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_24544"}

{:event/type "goal"
:event/elapsed 33
:event/subtype "volley"
:event/player1 "Andre Gomes"
:event/sortorder 3
:event/team "home"
:event/id "event_4916337"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Daniel Parejo"
:event/subtype "trip"
:event/player1 "Duda"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4916373"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Jose Gaya"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4916378"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Duda"
:event/subtype "trip"
:event/player1 "Pablo Piatti"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4916400"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 38
:event/subtype "penalty"
:event/player1 "Aderlan Santos"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4916414"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_24544"}

{:event/type "goal"
:event/elapsed 39
:event/subtype "saved_back_into_play"
:event/player1 "Duda"
:event/sortorder 0
:event/team "away"
:event/id "event_4916423"
:event/event_type "goal"
:event/goal_type "npm"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_24544"}

{:event/type "corner"
:event/elapsed 39
:event/subtype "cross_left"
:event/player1 "Duda"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4916430"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_24544"}

{:event/type "shotoff"
:event/elapsed 40
:event/subtype "header"
:event/player1 "Ignacio Camacho"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4916432"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Joao Cancelo"
:event/subtype "trip"
:event/player1 "Charles"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4916444"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Pablo Piatti"
:event/subtype "trip"
:event/player1 "Duda"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4916448"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Santi Mina"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4916457"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Jose Gaya"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4916477"
:event/minute 46
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Jose Gaya"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4916551"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_24544"}

{:event/type "corner"
:event/elapsed 47
:event/subtype "short_left"
:event/player1 "Pablo Piatti"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4916554"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Jose Gaya"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4916555"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_24544"}

{:event/type "corner"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross_left"
:event/player1 "Pablo Piatti"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_4916480"
:event/minute 47
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Duda"
:event/subtype "trip"
:event/player1 "Javi Fuego"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4916557"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Duda"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4916558"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_24544"}

{:event/type "shoton"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "shot"
:event/player1 "Juan Carlos"
:event/sortorder 10
:event/team "away"
:event/event_type "shoton"
:event/id "event_4916493"
:event/minute 48
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Juan Carlos"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4916561"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Daniel Parejo"
:event/subtype "trip"
:event/player1 "Duda"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4916575"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Roberto Rosales"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4916589"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_24544"}

{:event/type "shotoff"
:event/elapsed 54
:event/subtype "volley"
:event/player1 "Pablo Fornals"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4916593"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Duda"
:event/subtype "trip"
:event/player1 "Jose Gaya"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4916600"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Duda"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4916603"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Joao Cancelo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4916608"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Duda"
:event/subtype "trip"
:event/player1 "Jose Gaya"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4916612"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Duda"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4916615"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Jose Gaya"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4916620"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_24544"}

{:event/type "shotoff"
:event/elapsed 59
:event/subtype "big chance shot"
:event/player1 "Francisco Alcacer"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4916623"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 59
:event/player2 "Daniel Parejo"
:event/subtype "trip"
:event/player1 "Duje Cop"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4916626"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Duje Cop"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4916632"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player2 "Pablo Piatti"
:event/subtype "dangerous_play"
:event/player1 "Roberto Rosales"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4916633"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_24544"}

{:event/type "card"
:event/elapsed 60
:event/card_type "y"
:event/player1 "Roberto Rosales"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_4916634"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Duda"
:event/subtype "trip"
:event/player1 "Javi Fuego"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4916641"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_24544"}

{:event/type "card"
:event/elapsed 62
:event/card_type "y"
:event/player1 "Javi Fuego"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4916642"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Duda"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4916648"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Aderlan Santos"
:event/subtype "pushing"
:event/player1 "Raul Albentosa"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4916649"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Jose Gaya"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4916651"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Duda"
:event/subtype "pull"
:event/player1 "Santi Mina"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4916653"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_24544"}

{:event/type "card"
:event/elapsed 64
:event/card_type "y"
:event/player1 "Santi Mina"
:event/sortorder 3
:event/team "home"
:event/event_type "card"
:event/id "event_4916654"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_24544"}

{:event/type "shotoff"
:event/elapsed 66
:event/subtype "big chance shot"
:event/player1 "Duje Cop"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4916665"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Roberto Rosales"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4916674"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_24544"}

{:event/type "shoton"
:event/elapsed 70
:event/subtype "blocked_shot"
:event/player1 "Santi Mina"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4916686"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_24544"}

{:event/type "shoton"
:event/elapsed 70
:event/subtype "volley"
:event/player1 "Daniel Parejo"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4916688"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_24544"}

{:event/type "shotoff"
:event/elapsed 70
:event/subtype "shot"
:event/player1 "Zakaria Bakkali"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4916690"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Adnane Tighadouini"
:event/subtype "trip"
:event/player1 "Joao Cancelo"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4916691"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Pablo Fornals"
:event/subtype "dangerous_play"
:event/player1 "Santi Mina"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4916692"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Duda"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4916694"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_24544"}

{:event/type "shoton"
:event/elapsed 72
:event/subtype "blocked_shot"
:event/player1 "Raul Albentosa"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4916697"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_24544"}

{:event/type "corner"
:event/elapsed 72
:event/subtype "cross_right"
:event/player1 "Adnane Tighadouini"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_4916699"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Adnane Tighadouini"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4916701"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Jaume"
:event/subtype "pushing"
:event/player1 "Weligton"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4916704"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Sofiane Feghouli"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4916714"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_24544"}

{:event/type "goal"
:event/elapsed 75
:event/subtype "shot"
:event/player1 "Francisco Alcacer"
:event/sortorder 1
:event/team "home"
:event/id "event_4916716"
:event/event_type "goal"
:event/goal_type "dg"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 76
:event/player2 "Roberto Rosales"
:event/subtype "trip"
:event/player1 "Jose Gaya"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4916728"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 78
:event/player2 "Miguel Torres"
:event/subtype "trip"
:event/player1 "Joao Cancelo"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4916737"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Duje Cop"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4916743"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_24544"}

{:event/type "corner"
:event/elapsed 79
:event/subtype "cross_right"
:event/player1 "Duda"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4916745"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_24544"}

{:event/type "shotoff"
:event/elapsed 79
:event/subtype "shot"
:event/player1 "Pablo Fornals"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4916747"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Duda"
:event/subtype "trip"
:event/player1 "Andre Gomes"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4916755"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Adnane Tighadouini"
:event/subtype "trip"
:event/player1 "Joao Cancelo"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4916760"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Duda"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4916765"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Weligton"
:event/subtype "trip"
:event/player1 "Sofiane Feghouli"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4916770"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Duda"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4916774"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_24544"}

{:event/type "shoton"
:event/elapsed 83
:event/subtype "header"
:event/player1 "Raul Albentosa"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4916776"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Francisco Alcacer"
:event/subtype "trip"
:event/player1 "Ignacio Camacho"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4916781"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_24544"}

{:event/type "corner"
:event/elapsed 85
:event/subtype "cross_left"
:event/player1 "Adnane Tighadouini"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4916792"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Aderlan Santos"
:event/subtype "pushing"
:event/player1 "Raul Albentosa"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4916795"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Ignacio Camacho"
:event/subtype "trip"
:event/player1 "Daniel Parejo"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4916801"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_24544"}

{:event/type "card"
:event/elapsed 86
:event/card_type "y"
:event/player1 "Daniel Parejo"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_4916802"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Duda"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4916803"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Danilo"
:event/subtype "penalty"
:event/player1 "Raul Albentosa"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4916814"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_24544"}

{:event/type "card"
:event/elapsed 88
:event/card_type "y"
:event/player1 "Raul Albentosa"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4916820"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_24544"}

{:event/type "goal"
:event/elapsed 89
:event/player1 "Daniel Parejo"
:event/sortorder 0
:event/team "home"
:event/id "event_4916818"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Joao Cancelo"
:event/subtype "trip"
:event/player1 "Duje Cop"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4916822"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_24544"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Javi Fuego"
:event/subtype "trip"
:event/player1 "Miguel Torres"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4916824"
:event/minute 91
:event/match_id "match_24544"}

{:event/type "corner"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross_left"
:event/player1 "Duda"
:event/sortorder 5
:event/team "away"
:event/event_type "corner"
:event/id "event_4916830"
:event/minute 92
:event/match_id "match_24544"}

{:event/type "shoton"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "blocked_shot"
:event/player1 "Pablo Fornals"
:event/sortorder 7
:event/team "away"
:event/event_type "shoton"
:event/id "event_4916832"
:event/minute 92
:event/match_id "match_24544"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Roberto Rosales"
:event/sortorder 9
:event/team "away"
:event/event_type "cross"
:event/id "event_4916837"
:event/minute 92
:event/match_id "match_24544"}

{:event/type "corner"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross_right"
:event/player1 "Adnane Tighadouini"
:event/sortorder 11
:event/team "away"
:event/event_type "corner"
:event/id "event_4916841"
:event/minute 92
:event/match_id "match_24544"}

{:event/type "shotoff"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "header"
:event/player1 "Weligton"
:event/sortorder 12
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4916842"
:event/minute 93
:event/match_id "match_24544"}


]

