
;;# data
[
{:match/id "match_24555"
:match/league "Spain LIGA BBVA"
:match/hometeam "Athletic Club de Bilbao"
:match/awayteam "Real Sporting de Gijón"
:match/score "4:0"
:match/hometeam_goals "3"
:match/awayteam_goals "0"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Jony"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4959747"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_24555"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Alen Halilovic"
:event/subtype "trip"
:event/player1 "Markel Susaeta"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4959840"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_24555"}

{:event/type "shoton"
:event/elapsed 11
:event/subtype "blocked_shot"
:event/player1 "Alen Halilovic"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4959817"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Inaki Williams"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4959823"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_24555"}

{:event/type "corner"
:event/elapsed 13
:event/subtype "cross_right"
:event/player1 "Benat Etxebarria"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4959831"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_24555"}

{:event/type "shotoff"
:event/elapsed 13
:event/subtype "distance"
:event/player1 "Mikel San Jose"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4959837"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_24555"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Raul Garcia"
:event/subtype "from_behind"
:event/player1 "Alen Halilovic"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4959844"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_24555"}

{:event/type "card"
:event/elapsed 14
:event/card_type "y"
:event/player1 "Alen Halilovic"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4959846"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Markel Susaeta"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4959855"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_24555"}

{:event/type "shotoff"
:event/elapsed 16
:event/subtype "distance"
:event/player1 "Alen Halilovic"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4959869"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Jony"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4959881"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_24555"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Aymeric Laporte"
:event/subtype "pushing"
:event/player1 "Guerrero"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4959883"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Inaki Williams"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4959892"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Oscar de Marcos"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4959896"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_24555"}

{:event/type "shotoff"
:event/elapsed 19
:event/subtype "header"
:event/player1 "Aritz Aduriz"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4959900"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_24555"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Mikel San Jose"
:event/subtype "trip"
:event/player1 "Omar Mascarell"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4959904"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_24555"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Aymeric Laporte"
:event/subtype "trip"
:event/player1 "Guerrero"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4959911"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_24555"}

{:event/type "corner"
:event/elapsed 23
:event/subtype "short_right"
:event/player1 "Benat Etxebarria"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4959920"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Inaki Williams"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4959922"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_24555"}

{:event/type "card"
:event/elapsed 23
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Omar Mascarell"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_4959923"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_24555"}

{:event/type "corner"
:event/elapsed 24
:event/subtype "cross_right"
:event/player1 "Benat Etxebarria"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4959924"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Aymeric Laporte"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4959927"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_24555"}

{:event/type "corner"
:event/elapsed 24
:event/subtype "cross_right"
:event/player1 "Benat Etxebarria"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_4959930"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_24555"}

{:event/type "shotoff"
:event/elapsed 24
:event/subtype "header"
:event/player1 "Xabier Etxeita"
:event/sortorder 5
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4959932"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_24555"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Markel Susaeta"
:event/subtype "obstruction"
:event/player1 "Luis Hernandez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4959938"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Benat Etxebarria"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4959940"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_4959944"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_24555"}

{:event/type "shotoff"
:event/elapsed 28
:event/subtype "bad shot"
:event/player1 "Alen Halilovic"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4959946"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_24555"}

{:event/type "goal"
:event/elapsed 29
:event/player2 "Inaki Williams"
:event/subtype "tap_in"
:event/player1 "Markel Susaeta"
:event/sortorder 3
:event/team "home"
:event/id "event_4959954"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Raul Garcia"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4959957"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Sergio Alvarez"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4959961"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_24555"}

{:event/type "foulcommit"
:event/elapsed 33
:event/subtype "hands"
:event/player1 "Aritz Aduriz"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4959963"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Isma Lopez"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4959965"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Lora"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4959968"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_24555"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Benat Etxebarria"
:event/subtype "trip"
:event/player1 "Sergio Alvarez"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4959971"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Mikel Balenziaga"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4959972"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_24555"}

{:event/type "shoton"
:event/elapsed 38
:event/subtype "big chance header"
:event/player1 "Raul Garcia"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4959974"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_24555"}

{:event/type "corner"
:event/elapsed 38
:event/subtype "cross_right"
:event/player1 "Benat Etxebarria"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4959976"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Oscar de Marcos"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4959980"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_24555"}

{:event/type "shotoff"
:event/elapsed 40
:event/subtype "header"
:event/player1 "Aritz Aduriz"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4959981"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_24555"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Inaki Williams"
:event/subtype "penalty"
:event/player1 "Omar Mascarell"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4959983"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_24555"}

{:event/type "goal"
:event/elapsed 42
:event/subtype "saved_back_into_play"
:event/player1 "Aritz Aduriz"
:event/sortorder 0
:event/team "home"
:event/id "event_4959984"
:event/event_type "goal"
:event/goal_type "npm"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_24555"}

{:event/type "goal"
:event/elapsed 42
:event/subtype "volley"
:event/player1 "Aritz Aduriz"
:event/sortorder 1
:event/team "home"
:event/id "event_4959985"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Markel Susaeta"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4959987"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Nacho Cases"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4959991"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_24555"}

{:event/type "shotoff"
:event/elapsed 47
:event/subtype "big chance post"
:event/player1 "Aritz Aduriz"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4960006"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_24555"}

{:event/type "shoton"
:event/elapsed 47
:event/subtype "big chance shot"
:event/player1 "Benat Etxebarria"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4960007"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_24555"}

{:event/type "corner"
:event/elapsed 47
:event/subtype "cross_left"
:event/player1 "Benat Etxebarria"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_4960009"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_24555"}

{:event/type "corner"
:event/elapsed 47
:event/subtype "cross_left"
:event/player1 "Benat Etxebarria"
:event/sortorder 6
:event/team "home"
:event/event_type "corner"
:event/id "event_4960011"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_24555"}

{:event/type "shotoff"
:event/elapsed 47
:event/subtype "header"
:event/player1 "Xabier Etxeita"
:event/sortorder 7
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4960012"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Oscar de Marcos"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4960016"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_24555"}

{:event/type "corner"
:event/elapsed 50
:event/subtype "cross_right"
:event/player1 "Benat Etxebarria"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4960018"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_24555"}

{:event/type "shotoff"
:event/elapsed 50
:event/subtype "big chance header"
:event/player1 "Raul Garcia"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4960019"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_24555"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Mikel Balenziaga"
:event/player1 "Carlos Carmona"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4960021"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_24555"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Benat Etxebarria"
:event/subtype "trip"
:event/player1 "Jony"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4960022"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Inaki Williams"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4960023"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_24555"}

{:event/type "corner"
:event/elapsed 52
:event/subtype "cross_right"
:event/player1 "Benat Etxebarria"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4960024"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_24555"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Carlos Carmona"
:event/subtype "trip"
:event/player1 "Mikel San Jose"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4960028"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Isma Lopez"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4960031"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_24555"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Inaki Williams"
:event/subtype "trip"
:event/player1 "Isma Lopez"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4960033"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/sortorder 3
:event/team "away"
:event/event_type "throwin"
:event/id "event_4960035"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_24555"}

{:event/type "shotoff"
:event/elapsed 55
:event/subtype "bad shot"
:event/player1 "Alen Halilovic"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4960037"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Jony"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4960039"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_4960042"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Lora"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4960044"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_24555"}

{:event/type "corner"
:event/elapsed 57
:event/subtype "cross_left"
:event/player1 "Carlos Carmona"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_4960046"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_24555"}

{:event/type "foulcommit"
:event/elapsed 59
:event/subtype "hands"
:event/player1 "Carlos Carmona"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4960051"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Aritz Aduriz"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4960054"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_24555"}

{:event/type "shotoff"
:event/elapsed 60
:event/subtype "bad shot"
:event/player1 "Inaki Williams"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4960059"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_24555"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Raul Garcia"
:event/subtype "from_behind"
:event/player1 "Nacho Cases"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4960062"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_24555"}

{:event/type "card"
:event/elapsed 62
:event/card_type "y"
:event/player1 "Nacho Cases"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4960063"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Markel Susaeta"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4960064"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_24555"}

{:event/type "shotoff"
:event/elapsed 62
:event/subtype "bad shot"
:event/player1 "Mikel Balenziaga"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4960066"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_24555"}

{:event/type "shotoff"
:event/elapsed 63
:event/subtype "bad shot"
:event/player1 "Inaki Williams"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4960070"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_24555"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Jony"
:event/subtype "dangerous_play"
:event/player1 "Oscar de Marcos"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4960072"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_4960075"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_24555"}

{:event/type "goal"
:event/elapsed 67
:event/player2 "Benat Etxebarria"
:event/subtype "shot"
:event/player1 "Aritz Aduriz"
:event/sortorder 1
:event/team "home"
:event/id "event_4960080"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_4960084"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Lora"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4960085"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_4960090"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_24555"}

{:event/type "corner"
:event/elapsed 71
:event/subtype "cross_left"
:event/player1 "Pablo Perez"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4960092"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Inaki Williams"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4960094"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Raul Garcia"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4960096"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4960099"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Mikel Balenziaga"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4960104"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_24555"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Luis Hernandez"
:event/subtype "pull"
:event/player1 "Aritz Aduriz"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4960105"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_24555"}

{:event/type "shotoff"
:event/elapsed 76
:event/subtype "shot"
:event/player1 "unknown"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4960109"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_24555"}

{:event/type "card"
:event/elapsed 76
:event/card_type "y"
:event/subtype "verbal_abuse"
:event/player1 "Aritz Aduriz"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_4960111"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_24555"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "unknown"
:event/subtype "trip"
:event/player1 "Benat Etxebarria"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4960117"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Isma Lopez"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4960121"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_24555"}

{:event/type "corner"
:event/elapsed 83
:event/subtype "short_left"
:event/player1 "Pablo Perez"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4960122"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Isma Lopez"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4960123"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_24555"}

{:event/type "foulcommit"
:event/elapsed 83
:event/player2 "Aymeric Laporte"
:event/subtype "pushing"
:event/player1 "Pablo Perez"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4960126"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_24555"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Oscar de Marcos"
:event/subtype "pull"
:event/player1 "Isma Lopez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4960129"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Ibai Gomez"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4960130"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_24555"}

{:event/type "shotoff"
:event/elapsed 87
:event/subtype "distance"
:event/player1 "Ibai Gomez"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4960135"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_24555"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Mikel San Jose"
:event/player1 "unknown"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4960138"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Oscar de Marcos"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4960139"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_24555"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player2 "Sergio Alvarez"
:event/subtype "trip"
:event/player1 "Raul Garcia"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4960143"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_24555"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Lora"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4960144"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_24555"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "blocked_shot"
:event/player1 "Pablo Perez"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4960147"
:event/minute 91
:event/match_id "match_24555"}

{:event/type "shotoff"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "lob"
:event/player1 "Raul Garcia"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4960150"
:event/minute 92
:event/match_id "match_24555"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Lora"
:event/subtype "pull"
:event/player1 "Ibai Gomez"
:event/sortorder 6
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4960152"
:event/minute 92
:event/match_id "match_24555"}

{:event/type "shoton"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "big chance shot"
:event/player1 "Aritz Aduriz"
:event/sortorder 8
:event/team "home"
:event/event_type "shoton"
:event/id "event_4960154"
:event/minute 93
:event/match_id "match_24555"}


]

