
;;# data
[
{:match/id "match_12797"
:match/league "Italy Serie A"
:match/hometeam "Empoli"
:match/awayteam "Fiorentina"
:match/score "2:3"
:match/hometeam_goals "2"
:match/awayteam_goals "3"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Milan Badelj"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4464038"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_12797"}

{:event/type "corner"
:event/elapsed 4
:event/subtype "short_right"
:event/player1 "Josip Ilicic"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4464066"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_12797"}

{:event/type "goal"
:event/elapsed 4
:event/player2 "Milan Badelj"
:event/subtype "shot"
:event/player1 "Josip Ilicic"
:event/sortorder 3
:event/team "away"
:event/id "event_4464075"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_12797"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Elseid Hysaj"
:event/subtype "pushing"
:event/player1 "Juan Vargas"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4464148"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_12797"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "David Pizarro"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4464188"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_12797"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Milan Badelj"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4464223"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_12797"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Massimo Maccarone"
:event/player1 "Jose Maria Basanta"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4464229"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_12797"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Josip Ilicic"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4464281"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_12797"}

{:event/type "corner"
:event/elapsed 14
:event/subtype "cross_right"
:event/player1 "Josip Ilicic"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4464295"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_12797"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Mirko Valdifiori"
:event/subtype "dangerous_play"
:event/player1 "David Pizarro"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4464375"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_12797"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Vincent Laurini"
:event/player1 "Federico Bernardeschi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4464447"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_12797"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Daniele Croce"
:event/player1 "Milan Badelj"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4464485"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_12797"}

{:event/type "card"
:event/elapsed 23
:event/card_type "y"
:event/player1 "Milan Badelj"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_4464488"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_12797"}

{:event/type "shotoff"
:event/elapsed 25
:event/subtype "shot"
:event/player1 "Riccardo Saponara"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4464507"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_12797"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Massimo Maccarone"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4464527"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_12797"}

{:event/type "shotoff"
:event/elapsed 27
:event/subtype "bad shot"
:event/player1 "Alberto Aquilani"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4464547"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_12797"}

{:event/type "goal"
:event/elapsed 28
:event/subtype "shot"
:event/player1 "Riccardo Saponara"
:event/sortorder 2
:event/team "home"
:event/id "event_4464572"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_12797"}

{:event/type "shotoff"
:event/elapsed 30
:event/subtype "deflected"
:event/player1 "Federico Bernardeschi"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4464624"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_12797"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Lorenzo Tonelli"
:event/player1 "Alberto Aquilani"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4464646"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_12797"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Vincent Laurini"
:event/subtype "dangerous_play"
:event/player1 "Juan Vargas"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4464669"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_12797"}

{:event/type "card"
:event/elapsed 33
:event/card_type "y"
:event/player1 "Juan Vargas"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4464670"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_12797"}

{:event/type "foulcommit"
:event/elapsed 34
:event/player2 "Alberto Aquilani"
:event/player1 "Vincent Laurini"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4464685"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_12797"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Vincent Laurini"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4464755"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_12797"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Riccardo Saponara"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4464757"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_12797"}

{:event/type "corner"
:event/elapsed 38
:event/subtype "cross_left"
:event/player1 "Mirko Valdifiori"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4464768"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_12797"}

{:event/type "shotoff"
:event/elapsed 38
:event/subtype "header"
:event/player1 "Massimo Maccarone"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4464775"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_12797"}

{:event/type "corner"
:event/elapsed 41
:event/subtype "short_right"
:event/player1 "Josip Ilicic"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4464836"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_12797"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "David Pizarro"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4464838"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_12797"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Alberto Aquilani"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4464866"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_12797"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "David Pizarro"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4464904"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_12797"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Federico Bernardeschi"
:event/subtype "pushing"
:event/player1 "Vincent Laurini"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4464924"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_12797"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "indirect freekick"
:event/player1 "Juan Vargas"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4464952"
:event/minute 46
:event/match_id "match_12797"}

{:event/type "foulcommit"
:event/elapsed 46
:event/player2 "Lorenzo Tonelli"
:event/player1 "Josip Ilicic"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4465138"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_12797"}

{:event/type "corner"
:event/elapsed 47
:event/subtype "cross_left"
:event/player1 "Mirko Valdifiori"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_4465163"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_12797"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Elseid Hysaj"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4465194"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_12797"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Matias Vecino"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4465200"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_12797"}

{:event/type "shotoff"
:event/elapsed 50
:event/subtype "volley"
:event/player1 "Massimo Maccarone"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4465225"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_12797"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Gonzalo Rodriguez"
:event/subtype "pushing"
:event/player1 "Riccardo Saponara"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4465256"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_12797"}

{:event/type "shoton"
:event/elapsed 52
:event/subtype "blocked_shot"
:event/player1 "Massimo Maccarone"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4465264"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_12797"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Daniele Croce"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4465316"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_12797"}

{:event/type "corner"
:event/elapsed 55
:event/subtype "cross_left"
:event/player1 "Mirko Valdifiori"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4465333"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_12797"}

{:event/type "shotoff"
:event/elapsed 56
:event/subtype "shot"
:event/player1 "Riccardo Saponara"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4465344"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_12797"}

{:event/type "shotoff"
:event/elapsed 57
:event/subtype "shot"
:event/player1 "Massimo Maccarone"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4465354"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_12797"}

{:event/type "goal"
:event/elapsed 57
:event/player2 "Josip Ilicic"
:event/subtype "shot"
:event/player1 "Mohamed Salah"
:event/sortorder 5
:event/team "away"
:event/id "event_4465373"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_12797"}

{:event/type "foulcommit"
:event/elapsed 59
:event/player2 "Mirko Valdifiori"
:event/player1 "Alberto Gilardino"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4465394"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_12797"}

{:event/type "corner"
:event/elapsed 60
:event/subtype "cross_right"
:event/player1 "Josip Ilicic"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4465413"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_12797"}

{:event/type "shoton"
:event/elapsed 63
:event/subtype "shot"
:event/player1 "Mohamed Salah"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4465466"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_12797"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Jose Maria Basanta"
:event/player1 "Manuel Pucciarelli"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4465475"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_12797"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Piotr Zielinski"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4465497"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_12797"}

{:event/type "corner"
:event/elapsed 66
:event/subtype "cross_left"
:event/player1 "Mirko Valdifiori"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4465503"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_12797"}

{:event/type "shoton"
:event/elapsed 68
:event/subtype "blocked_shot"
:event/player1 "Mohamed Salah"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4465538"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_12797"}

{:event/type "goal"
:event/elapsed 68
:event/subtype "shot"
:event/player1 "Josip Ilicic"
:event/sortorder 3
:event/team "away"
:event/id "event_4465541"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_12797"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Matias Vecino"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4465580"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_12797"}

{:event/type "shotoff"
:event/elapsed 73
:event/subtype "shot"
:event/player1 "Piotr Zielinski"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4465627"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_12797"}

{:event/type "foulcommit"
:event/elapsed 74
:event/player2 "Matias Fernandez"
:event/player1 "Massimo Maccarone"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4465645"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_12797"}

{:event/type "shotoff"
:event/elapsed 75
:event/subtype "shot"
:event/player1 "Alberto Aquilani"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4465656"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_12797"}

{:event/type "goal"
:event/elapsed 77
:event/player2 "Riccardo Saponara"
:event/subtype "shot"
:event/player1 "Levan Mchedlidze"
:event/sortorder 5
:event/team "home"
:event/id "event_4465689"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_12797"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Matias Vecino"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4465705"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_12797"}

{:event/type "foulcommit"
:event/elapsed 79
:event/player2 "Piotr Zielinski"
:event/player1 "Milan Badelj"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4465716"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_12797"}

{:event/type "shoton"
:event/elapsed 80
:event/subtype "blocked_shot"
:event/player1 "Mirko Valdifiori"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4465730"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_12797"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Josip Ilicic"
:event/subtype "dangerous_play"
:event/player1 "Lorenzo Tonelli"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4465747"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_12797"}

{:event/type "foulcommit"
:event/elapsed 83
:event/player2 "Gonzalo Rodriguez"
:event/player1 "Levan Mchedlidze"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4465781"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_12797"}

{:event/type "card"
:event/elapsed 83
:event/card_type "y"
:event/player1 "Levan Mchedlidze"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4465784"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_12797"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Elseid Hysaj"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4465806"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_12797"}

{:event/type "shotoff"
:event/elapsed 85
:event/subtype "shot"
:event/player1 "Matias Fernandez"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4465819"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_12797"}

{:event/type "shoton"
:event/elapsed 85
:event/subtype "shot"
:event/player1 "Francesco Tavano"
:event/sortorder 6
:event/team "home"
:event/event_type "shoton"
:event/id "event_4465826"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_12797"}

{:event/type "corner"
:event/elapsed 86
:event/subtype "cross_left"
:event/player1 "Mirko Valdifiori"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4465834"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_12797"}

{:event/type "corner"
:event/elapsed 86
:event/subtype "cross_left"
:event/player1 "Mirko Valdifiori"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4465842"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_12797"}

{:event/type "foulcommit"
:event/elapsed 87
:event/player2 "Josip Ilicic"
:event/player1 "Elseid Hysaj"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4465845"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_12797"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player2 "Riccardo Saponara"
:event/subtype "pushing"
:event/player1 "Matias Fernandez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4465875"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_12797"}

{:event/type "shoton"
:event/elapsed 90
:event/subtype "direct_freekick"
:event/player1 "Mirko Valdifiori"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4465895"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_12797"}

{:event/type "corner"
:event/elapsed 90
:event/subtype "cross_right"
:event/player1 "Mirko Valdifiori"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4465903"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_12797"}

{:event/type "shotoff"
:event/elapsed 90
:event/subtype "deflected"
:event/player1 "Elseid Hysaj"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4465906"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_12797"}

{:event/type "corner"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross_right"
:event/player1 "Mirko Valdifiori"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_4465909"
:event/minute 91
:event/match_id "match_12797"}

{:event/type "shoton"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "blocked_shot"
:event/player1 "Mohamed Salah"
:event/sortorder 10
:event/team "away"
:event/event_type "shoton"
:event/id "event_4465935"
:event/minute 92
:event/match_id "match_12797"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Alberto Aquilani"
:event/player1 "Riccardo Saponara"
:event/sortorder 14
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4465944"
:event/minute 93
:event/match_id "match_12797"}


]

