
;;# data
[
{:match/id "match_9641"
:match/league "Germany 1. Bundesliga"
:match/hometeam "Hamburger SV"
:match/awayteam "VfB Stuttgart"
:match/score "4:2"
:match/hometeam_goals "3"
:match/awayteam_goals "3"}

{:event/type "goal"
:event/elapsed 3
:event/player1 "Alexandru Maxim"
:event/sortorder 0
:event/team "away"
:event/id "event_3075382"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_9641"}

{:event/type "goal"
:event/elapsed 22
:event/player1 "Pierre-Michel Lasogga"
:event/sortorder 0
:event/team "home"
:event/id "event_3075536"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_9641"}

{:event/type "goal"
:event/elapsed 37
:event/player1 "Christian Gentner"
:event/sortorder 0
:event/team "away"
:event/id "event_3075581"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_9641"}

{:event/type "goal"
:event/elapsed 55
:event/player1 "Maximillian Beister"
:event/sortorder 0
:event/team "home"
:event/id "event_3075727"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_9641"}

{:event/type "goal"
:event/elapsed 64
:event/player1 "Johan Djourou"
:event/sortorder 0
:event/team "home"
:event/id "event_3075757"
:event/event_type "goal"
:event/goal_type "o"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_9641"}

{:event/type "goal"
:event/elapsed 67
:event/player1 "Rafael van der Vaart"
:event/sortorder 0
:event/team "home"
:event/id "event_3075771"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_9641"}

{:event/type "card"
:event/elapsed 71
:event/card_type "y"
:event/player1 "William Kvist"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3075785"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_9641"}

{:event/type "card"
:event/elapsed 81
:event/card_type "y"
:event/player1 "Milan Badelj"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3075872"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_9641"}

{:event/type "card"
:event/elapsed 84
:event/card_type "r"
:event/player1 "Antonio Ruediger"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3075887"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_9641"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Vedad Ibisevic"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3075926"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_9641"}


]

