
;;# data
[
{:match/id "match_9662"
:match/league "Germany 1. Bundesliga"
:match/hometeam "SC Paderborn 07"
:match/awayteam "Hertha BSC Berlin"
:match/score "3:1"
:match/hometeam_goals "3"
:match/awayteam_goals "1"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Jens Wemmer"
:event/player1 "Valentin Stocker"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3904317"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Moritz Stoppelkamp"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3904331"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_9662"}

{:event/type "shoton"
:event/elapsed 3
:event/subtype "distance"
:event/player1 "Moritz Stoppelkamp"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3904342"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_9662"}

{:event/type "corner"
:event/elapsed 3
:event/subtype "cross_left"
:event/player1 "Alban Meha"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3904349"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Mario Vrancic"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3904352"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_9662"}

{:event/type "shotoff"
:event/elapsed 4
:event/subtype "big chance header"
:event/player1 "Elias Kachunga"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3904358"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 6
:event/player2 "Jens Wemmer"
:event/player1 "Valentin Stocker"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3904392"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_9662"}

{:event/type "shotoff"
:event/elapsed 9
:event/subtype "distance"
:event/player1 "Marvin Bakalorz"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3904440"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_9662"}

{:event/type "shotoff"
:event/elapsed 10
:event/subtype "distance"
:event/player1 "Marcel Ndjeng"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3904454"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Alban Meha"
:event/player1 "Valentin Stocker"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3904508"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_9662"}

{:event/type "shotoff"
:event/elapsed 14
:event/subtype "distance"
:event/player1 "Alban Meha"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3904513"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Elias Kachunga"
:event/player1 "Marcel Ndjeng"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3904523"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_9662"}

{:event/type "shotoff"
:event/elapsed 15
:event/subtype "direct_freekick"
:event/player1 "Alban Meha"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3904538"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "Hajime Hosogai"
:event/player1 "Moritz Stoppelkamp"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3904554"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Johnny Heitinga"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3904565"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_9662"}

{:event/type "shotoff"
:event/elapsed 17
:event/subtype "volley"
:event/player1 "Valentin Stocker"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3904574"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Valentin Stocker"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3904579"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_9662"}

{:event/type "shotoff"
:event/elapsed 18
:event/subtype "shot"
:event/player1 "Salomon Kalou"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3904581"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_9662"}

{:event/type "shotoff"
:event/elapsed 21
:event/subtype "volley"
:event/player1 "Alban Meha"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3904595"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Moritz Stoppelkamp"
:event/player1 "Salomon Kalou"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3904605"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Per Ciljan Skjelbred"
:event/player1 "Jens Wemmer"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3904608"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Marcel Ndjeng"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3904609"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_9662"}

{:event/type "shoton"
:event/elapsed 24
:event/subtype "header"
:event/player1 "Peter Niemeyer"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_3904610"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_9662"}

{:event/type "corner"
:event/elapsed 26
:event/subtype "cross_left"
:event/player1 "Roy Beerens"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3904619"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Roy Beerens"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_3904622"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_9662"}

{:event/type "shotoff"
:event/elapsed 27
:event/subtype "distance"
:event/player1 "Roy Beerens"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3904623"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Jens Wemmer"
:event/player1 "Valentin Stocker"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3904628"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Jens Wemmer"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3904635"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_9662"}

{:event/type "goal"
:event/elapsed 28
:event/subtype "shot"
:event/player1 "Marvin Bakalorz"
:event/sortorder 3
:event/team "home"
:event/id "event_3904630"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Roy Beerens"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3904643"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Valentin Stocker"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3904645"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Peter Pekarik"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_3904647"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Moritz Stoppelkamp"
:event/player1 "Peter Pekarik"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3904652"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_9662"}

{:event/type "card"
:event/elapsed 31
:event/card_type "y"
:event/player1 "Peter Pekarik"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_3904653"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Patrick Ziegler"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3904658"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Roy Beerens"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3904676"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Alban Meha"
:event/player1 "Per Ciljan Skjelbred"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3904709"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Moritz Stoppelkamp"
:event/player1 "Valentin Stocker"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3904731"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Per Ciljan Skjelbred"
:event/player1 "Alban Meha"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3904761"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Marcel Ndjeng"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3904766"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Valentin Stocker"
:event/player1 "Mario Vrancic"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3904776"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Marcel Ndjeng"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3904784"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Patrick Ziegler"
:event/player1 "Peter Niemeyer"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3904789"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Marcel Ndjeng"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3904808"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_9662"}

{:event/type "goal"
:event/elapsed 41
:event/player2 "Marcel Ndjeng"
:event/subtype "header"
:event/player1 "Salomon Kalou"
:event/sortorder 1
:event/team "away"
:event/id "event_3904810"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Marvin Bakalorz"
:event/player1 "Peter Niemeyer"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3904820"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_9662"}

{:event/type "card"
:event/elapsed 42
:event/card_type "y"
:event/player1 "Peter Niemeyer"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_3904822"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Mario Vrancic"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3904827"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_9662"}

{:event/type "shoton"
:event/elapsed 43
:event/subtype "distance"
:event/player1 "Roy Beerens"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3904845"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Daniel Brueckner"
:event/player1 "Valentin Stocker"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3904855"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Elias Kachunga"
:event/subtype "serious_foul"
:event/player1 "Fabian Lustenberger"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3904863"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_9662"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "blocked_shot"
:event/player1 "Alban Meha"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3904890"
:event/minute 46
:event/match_id "match_9662"}

{:event/type "corner"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross_right"
:event/player1 "Moritz Stoppelkamp"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3904892"
:event/minute 46
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 46
:event/player2 "Marvin Bakalorz"
:event/player1 "Fabian Lustenberger"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3905178"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_9662"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "header"
:event/player1 "Uwe Huenemeier"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_3904895"
:event/minute 46
:event/match_id "match_9662"}

{:event/type "corner"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross_right"
:event/player1 "Moritz Stoppelkamp"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_3904897"
:event/minute 46
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Alban Meha"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3905183"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_9662"}

{:event/type "shotoff"
:event/elapsed 47
:event/subtype "distance"
:event/player1 "Daniel Brueckner"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3905195"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 45
:event/player2 "Fabian Lustenberger"
:event/player1 "Uwe Huenemeier"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3904902"
:event/minute 47
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Moritz Stoppelkamp"
:event/player1 "Peter Pekarik"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3905965"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Jens Wemmer"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3905221"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_9662"}

{:event/type "shotoff"
:event/elapsed 49
:event/subtype "bad shot"
:event/player1 "Marvin Ducksch"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3905224"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Jens Wemmer"
:event/subtype "serious_foul"
:event/player1 "Roy Beerens"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3905231"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_9662"}

{:event/type "corner"
:event/elapsed 50
:event/subtype "cross_right"
:event/player1 "Moritz Stoppelkamp"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3905254"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_3905263"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Jens Wemmer"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3905270"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Jens Wemmer"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3905321"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_9662"}

{:event/type "goal"
:event/elapsed 53
:event/player2 "Jens Wemmer"
:event/subtype "header"
:event/player1 "Elias Kachunga"
:event/sortorder 1
:event/team "home"
:event/id "event_3905304"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Moritz Stoppelkamp"
:event/player1 "Peter Pekarik"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3905350"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Peter Niemeyer"
:event/player1 "Mario Vrancic"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3905400"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player2 "Fabian Lustenberger"
:event/player1 "Marvin Ducksch"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3905493"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Alban Meha"
:event/player1 "Marcel Ndjeng"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3905562"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Roy Beerens"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3905584"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 66
:event/player2 "Mario Vrancic"
:event/player1 "Peter Niemeyer"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3905600"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_9662"}

{:event/type "shoton"
:event/elapsed 67
:event/subtype "blocked_shot"
:event/player1 "Alban Meha"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_3905611"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Marvin Ducksch"
:event/player1 "Johnny Heitinga"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3905630"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Marvin Bakalorz"
:event/player1 "Per Ciljan Skjelbred"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3905956"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Mario Vrancic"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3905636"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_9662"}

{:event/type "corner"
:event/elapsed 70
:event/subtype "cross_right"
:event/player1 "Moritz Stoppelkamp"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3905647"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Moritz Stoppelkamp"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_3905652"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/sortorder 6
:event/team "home"
:event/event_type "throwin"
:event/id "event_3905650"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 71
:event/subtype "hands"
:event/player1 "Mario Vrancic"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3905655"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_9662"}

{:event/type "shotoff"
:event/elapsed 72
:event/subtype "distance"
:event/player1 "Valentin Stocker"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3905665"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Marcel Ndjeng"
:event/player1 "Daniel Brueckner"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3905678"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Ronny"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3905680"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Elias Kachunga"
:event/player1 "Peter Niemeyer"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3905688"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Christian Strohdiek"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3905694"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_9662"}

{:event/type "goal"
:event/elapsed 76
:event/player2 "Elias Kachunga"
:event/subtype "distance"
:event/player1 "Alban Meha"
:event/sortorder 0
:event/team "home"
:event/id "event_3905698"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Peter Niemeyer"
:event/player1 "Patrick Ziegler"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3905949"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Elias Kachunga"
:event/player1 "Fabian Lustenberger"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3905706"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Marvin Bakalorz"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3905725"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 79
:event/player2 "Daniel Brueckner"
:event/player1 "Valentin Stocker"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3905737"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_9662"}

{:event/type "corner"
:event/elapsed 82
:event/subtype "cross_right"
:event/player1 "Moritz Stoppelkamp"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3905756"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Ronny"
:event/player1 "Mario Vrancic"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3905763"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Marvin Bakalorz"
:event/player1 "Per Ciljan Skjelbred"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3905771"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_9662"}

{:event/type "shotoff"
:event/elapsed 84
:event/subtype "distance"
:event/player1 "Moritz Stoppelkamp"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3905785"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Jens Wemmer"
:event/player1 "Genki Haraguchi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3905792"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Salomon Kalou"
:event/player1 "Jens Wemmer"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3905817"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Ronny"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3905824"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_9662"}

{:event/type "shotoff"
:event/elapsed 88
:event/subtype "distance"
:event/player1 "Ronny"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3905832"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player2 "Marcel Ndjeng"
:event/player1 "Moritz Stoppelkamp"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3905844"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Mario Vrancic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3905862"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Genki Haraguchi"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3905870"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Salomon Kalou"
:event/player1 "Mario Vrancic"
:event/sortorder 5
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3905875"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Ronny"
:event/sortorder 6
:event/team "away"
:event/event_type "cross"
:event/id "event_3905885"
:event/minute 91
:event/match_id "match_9662"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "header"
:event/player1 "Fabian Lustenberger"
:event/sortorder 7
:event/team "away"
:event/event_type "shoton"
:event/id "event_3905889"
:event/minute 91
:event/match_id "match_9662"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Moritz Stoppelkamp"
:event/sortorder 8
:event/team "home"
:event/event_type "cross"
:event/id "event_3905893"
:event/minute 91
:event/match_id "match_9662"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "big chance shot"
:event/player1 "Mahir Saglik"
:event/sortorder 9
:event/team "home"
:event/event_type "shoton"
:event/id "event_3905895"
:event/minute 91
:event/match_id "match_9662"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Daniel Brueckner"
:event/player1 "Per Ciljan Skjelbred"
:event/sortorder 11
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3905903"
:event/minute 92
:event/match_id "match_9662"}


]

