
;;# data
[
{:match/id "match_9316"
:match/league "Germany 1. Bundesliga"
:match/hometeam "Hannover 96"
:match/awayteam "Borussia Dortmund"
:match/score "1:1"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "card"
:event/elapsed 9
:event/card_type "y"
:event/player1 "Artur Sobiech"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2404331"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_9316"}

{:event/type "goal"
:event/elapsed 26
:event/player1 "Robert Lewandowski"
:event/sortorder 0
:event/team "away"
:event/id "event_2404417"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_9316"}

{:event/type "card"
:event/elapsed 54
:event/card_type "y"
:event/player1 "Steven Cherundolo"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2404758"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_9316"}

{:event/type "card"
:event/elapsed 79
:event/card_type "y"
:event/player1 "Jan Schlaudraff"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2404860"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_9316"}

{:event/type "card"
:event/elapsed 81
:event/card_type "y"
:event/player1 "Lars Stindl"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2404861"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_9316"}

{:event/type "goal"
:event/elapsed 86
:event/player1 "Mame Biram Diouf"
:event/sortorder 0
:event/team "home"
:event/id "event_2404879"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_9316"}


]

