
;;# data
[
{:match/id "match_7920"
:match/league "Germany 1. Bundesliga"
:match/hometeam "Hertha BSC Berlin"
:match/awayteam "FC Bayern Munich"
:match/score "2:1"
:match/hometeam_goals "2"
:match/awayteam_goals "1"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Rodnei"
:event/player1 "Lucio"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_579125"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_7920"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Miroslav Klose"
:event/player1 "Pal Dardai"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_579127"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_7920"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Rodnei"
:event/player1 "Christian Lell"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_579130"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_7920"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Bastian Schweinsteiger"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_579132"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_7920"}

{:event/type "shotoff"
:event/elapsed 7
:event/subtype "distance"
:event/player1 "Mark van Bommel"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_579133"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_7920"}

{:event/type "shotoff"
:event/elapsed 8
:event/subtype "deflected"
:event/player1 "Philipp Lahm"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_579136"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_7920"}

{:event/type "corner"
:event/elapsed 8
:event/subtype "short"
:event/player1 "Franck Ribery"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_579137"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_7920"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Andrey Voronin"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_579142"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_7920"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Mark van Bommel"
:event/subtype "pushing"
:event/player1 "Andrey Voronin"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_579145"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_7920"}

{:event/type "foulcommit"
:event/elapsed 13
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_579147"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_7920"}

{:event/type "foulcommit"
:event/elapsed 15
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_579151"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_7920"}

{:event/type "foulcommit"
:event/elapsed 15
:event/subtype "pushing"
:event/player1 "Luca Toni"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_579153"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_7920"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Christian Lell"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_579159"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_7920"}

{:event/type "shotoff"
:event/elapsed 20
:event/subtype "distance"
:event/player1 "Patrick Ebert"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_579163"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_7920"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Rodnei"
:event/player1 "Mark van Bommel"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_579169"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_7920"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Ze Roberto"
:event/subtype "from_behind"
:event/player1 "Patrick Ebert"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_579172"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_7920"}

{:event/type "shotoff"
:event/elapsed 27
:event/subtype "direct_freekick"
:event/player1 "Franck Ribery"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_579176"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_7920"}

{:event/type "shoton"
:event/elapsed 27
:event/subtype "blocked_shot"
:event/player1 "Martin Demichelis"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_579177"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_7920"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Franck Ribery"
:event/player1 "Patrick Ebert"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_579181"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_7920"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_579191"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_7920"}

{:event/type "corner"
:event/elapsed 30
:event/subtype "cross"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_579191"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_7920"}

{:event/type "shoton"
:event/elapsed 31
:event/subtype "volley"
:event/player1 "Pal Dardai"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_579192"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_7920"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Franck Ribery"
:event/player1 "Pal Dardai"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_579198"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_7920"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Bastian Schweinsteiger"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_579217"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_7920"}

{:event/type "shotoff"
:event/elapsed 35
:event/subtype "header"
:event/player1 "Luca Toni"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_579218"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_7920"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Landon Donovan"
:event/player1 "Pal Dardai"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_579237"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_7920"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Patrick Ebert"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_579240"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_7920"}

{:event/type "goal"
:event/elapsed 38
:event/player2 "Patrick Ebert"
:event/subtype "header"
:event/player1 "Andrey Voronin"
:event/sortorder 2
:event/team "home"
:event/id "event_579242"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_7920"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Marko Babic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_579249"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_7920"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Philipp Lahm"
:event/player1 "Patrick Ebert"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_579254"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_7920"}

{:event/type "foulcommit"
:event/elapsed 43
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_579262"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_7920"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Bastian Schweinsteiger"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_579264"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_7920"}

{:event/type "foulcommit"
:event/elapsed 44
:event/subtype "pushing"
:event/player1 "Andrey Voronin"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_579273"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_7920"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Ze Roberto"
:event/player1 "Pal Dardai"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_579384"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_7920"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Andrey Voronin"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_579386"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_7920"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Bastian Schweinsteiger"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_579391"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_7920"}

{:event/type "corner"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Bastian Schweinsteiger"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_579391"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_7920"}

{:event/type "foulcommit"
:event/elapsed 51
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_579400"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_7920"}

{:event/type "shotoff"
:event/elapsed 53
:event/subtype "distance"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_579415"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_7920"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Ze Roberto"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_579430"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_7920"}

{:event/type "shoton"
:event/elapsed 54
:event/subtype "header"
:event/player1 "Landon Donovan"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_579431"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_7920"}

{:event/type "shotoff"
:event/elapsed 54
:event/subtype "shot"
:event/player1 "Miroslav Klose"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_579434"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_7920"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Patrick Ebert"
:event/subtype "pushing"
:event/player1 "Martin Demichelis"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_579441"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_7920"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Christian Lell"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_579449"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_7920"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Patrick Ebert"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_579454"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_7920"}

{:event/type "corner"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Patrick Ebert"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_579454"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_7920"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Franck Ribery"
:event/player1 "Patrick Ebert"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_579455"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_7920"}

{:event/type "foulcommit"
:event/elapsed 60
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_579464"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_7920"}

{:event/type "shotoff"
:event/elapsed 60
:event/subtype "shot"
:event/player1 "Raffael"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_579467"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_7920"}

{:event/type "shoton"
:event/elapsed 61
:event/subtype "shot"
:event/player1 "Lucio"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_579469"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_7920"}

{:event/type "shoton"
:event/elapsed 62
:event/subtype "volley"
:event/player1 "Bastian Schweinsteiger"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_579470"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_7920"}

{:event/type "goal"
:event/elapsed 62
:event/subtype "header"
:event/player1 "Miroslav Klose"
:event/sortorder 1
:event/team "away"
:event/id "event_579471"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_7920"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Martin Demichelis"
:event/subtype "pushing"
:event/player1 "Andrey Voronin"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_579474"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_7920"}

{:event/type "shotoff"
:event/elapsed 65
:event/subtype "shot"
:event/player1 "Raffael"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_579478"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_7920"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Franck Ribery"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_579488"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_7920"}

{:event/type "shoton"
:event/elapsed 69
:event/subtype "shot"
:event/player1 "Bastian Schweinsteiger"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_579489"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_7920"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Patrick Ebert"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_579490"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_7920"}

{:event/type "shoton"
:event/elapsed 71
:event/subtype "shot"
:event/player1 "Landon Donovan"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_579494"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_7920"}

{:event/type "corner"
:event/elapsed 71
:event/subtype "short"
:event/player1 "Franck Ribery"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_579495"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_7920"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Mark van Bommel"
:event/player1 "Andrey Voronin"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_579503"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_7920"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Marko Babic"
:event/player1 "Bastian Schweinsteiger"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_579507"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_7920"}

{:event/type "shotoff"
:event/elapsed 76
:event/subtype "volley"
:event/player1 "Maximilian Nicu"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_579518"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_7920"}

{:event/type "goal"
:event/elapsed 77
:event/player2 "Raffael"
:event/subtype "shot"
:event/player1 "Andrey Voronin"
:event/sortorder 2
:event/team "home"
:event/id "event_579527"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_7920"}

{:event/type "foulcommit"
:event/elapsed 80
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_579537"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_7920"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_579538"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_7920"}

{:event/type "shoton"
:event/elapsed 80
:event/subtype "header"
:event/player1 "Lucio"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_579539"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_7920"}

{:event/type "shotoff"
:event/elapsed 81
:event/subtype "shot"
:event/player1 "Franck Ribery"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_579544"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_7920"}

{:event/type "foulcommit"
:event/elapsed 83
:event/player2 "Maximilian Nicu"
:event/player1 "Tim Borowski"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_579555"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_7920"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Landon Donovan"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_579564"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_7920"}

{:event/type "corner"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Landon Donovan"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_579564"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_7920"}

{:event/type "shotoff"
:event/elapsed 85
:event/subtype "deflected"
:event/player1 "Lucio"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_579566"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_7920"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Landon Donovan"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_579567"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_7920"}

{:event/type "corner"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Landon Donovan"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_579567"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_7920"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Franck Ribery"
:event/player1 "Raffael"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_579571"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_7920"}

{:event/type "card"
:event/elapsed 85
:event/card_type "y"
:event/player1 "Raffael"
:event/sortorder 4
:event/team "home"
:event/event_type "card"
:event/id "event_579572"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_7920"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Bastian Schweinsteiger"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_579579"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_7920"}

{:event/type "corner"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Bastian Schweinsteiger"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_579579"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_7920"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Franck Ribery"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_579595"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_7920"}

{:event/type "corner"
:event/elapsed 89
:event/subtype "short"
:event/player1 "Franck Ribery"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_579596"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_7920"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Franck Ribery"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_579599"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_7920"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Miroslav Klose"
:event/player1 "Pal Dardai"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_579609"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_7920"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/subtype "shirt_pull"
:event/player1 "Pal Dardai"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_579610"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_7920"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Ze Roberto"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_579632"
:event/minute 93
:event/match_id "match_7920"}


]

