
;;# data
[
{:match/id "match_11976"
:match/league "Italy Serie A"
:match/hometeam "Fiorentina"
:match/awayteam "Catania"
:match/score "2:0"
:match/hometeam_goals "2"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 19
:event/card_type "y"
:event/player1 "Adem Ljajic"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2352172"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_11976"}

{:event/type "card"
:event/elapsed 39
:event/card_type "y"
:event/player1 "David Pizarro"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2352228"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_11976"}

{:event/type "card"
:event/elapsed 39
:event/card_type "y"
:event/player1 "Alejandro Daro Gomez"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2352229"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_11976"}

{:event/type "goal"
:event/elapsed 43
:event/player1 "Stevan Jovetic"
:event/sortorder 0
:event/team "home"
:event/id "event_2352235"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_11976"}

{:event/type "goal"
:event/elapsed 65
:event/player1 "Luca Toni"
:event/sortorder 0
:event/team "home"
:event/id "event_2352418"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_11976"}

{:event/type "card"
:event/elapsed 68
:event/card_type "y"
:event/player1 "Stevan Jovetic"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2352423"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_11976"}

{:event/type "card"
:event/elapsed 85
:event/card_type "y"
:event/player1 "Nicolas Federico Spolli"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2352513"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_11976"}


]

