
;;# data
[
{:match/id "match_15686"
:match/league "Netherlands Eredivisie"
:match/hometeam "N.E.C."
:match/awayteam "SC Heerenveen"
:match/score "2:0"
:match/hometeam_goals "2"
:match/awayteam_goals "0"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Pele van Anholt"
:event/subtype "trip"
:event/player1 "Marcel Ritzmaier"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4786855"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_15686"}

{:event/type "shoton"
:event/elapsed 4
:event/subtype "distance"
:event/player1 "Caner Cavlan"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4786857"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_15686"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Simon Thern"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4786864"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_15686"}

{:event/type "corner"
:event/elapsed 7
:event/subtype "short_left"
:event/player1 "Branco van den Boomen"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4786866"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_15686"}

{:event/type "corner"
:event/elapsed 7
:event/subtype "short_left"
:event/player1 "Branco van den Boomen"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_4786871"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_15686"}

{:event/type "shoton"
:event/elapsed 7
:event/subtype "blocked_shot"
:event/player1 "Branco van den Boomen"
:event/sortorder 5
:event/team "away"
:event/event_type "shoton"
:event/id "event_4786872"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_15686"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Todd Kane"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4786876"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_15686"}

{:event/type "shotoff"
:event/elapsed 9
:event/subtype "distance"
:event/player1 "Sam Larsson"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4786879"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_15686"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Lucas Woudenberg"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4786892"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_15686"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Luciano Slagveer"
:event/subtype "obstruction"
:event/player1 "Lucas Woudenberg"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4786899"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_15686"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Caner Cavlan"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4786902"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_15686"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Todd Kane"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4786908"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_15686"}

{:event/type "shotoff"
:event/elapsed 16
:event/subtype "big chance header"
:event/player1 "Navarone Foor"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4786909"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_15686"}

{:event/type "shoton"
:event/elapsed 16
:event/subtype "distance"
:event/player1 "Marcel Ritzmaier"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4786912"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_15686"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Todd Kane"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4786914"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_15686"}

{:event/type "corner"
:event/elapsed 17
:event/subtype "cross_left"
:event/player1 "Anthony Limbombe"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4786919"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_15686"}

{:event/type "shotoff"
:event/elapsed 18
:event/subtype "miss_kick"
:event/player1 "Navarone Foor"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4786939"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_15686"}

{:event/type "goal"
:event/elapsed 18
:event/player2 "Lucas Woudenberg"
:event/subtype "shot"
:event/player1 "Christian Santos"
:event/sortorder 2
:event/team "home"
:event/id "event_4786923"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_15686"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Luciano Slagveer"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4786929"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_15686"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Caner Cavlan"
:event/subtype "serious_foul"
:event/player1 "Todd Kane"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4786934"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_15686"}

{:event/type "shoton"
:event/elapsed 21
:event/subtype "direct_freekick"
:event/player1 "Branco van den Boomen"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4786936"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_15686"}

{:event/type "shoton"
:event/elapsed 22
:event/subtype "shot"
:event/player1 "Sam Larsson"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4786946"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_15686"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Janio Bikel"
:event/subtype "trip"
:event/player1 "Joey van den Berg"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4786943"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_15686"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Sam Larsson"
:event/subtype "trip"
:event/player1 "Christian Santos"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4786948"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_15686"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Navarone Foor"
:event/subtype "trip"
:event/player1 "Lucas Bijker"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4786958"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_15686"}

{:event/type "shoton"
:event/elapsed 27
:event/subtype "blocked_shot"
:event/player1 "Anthony Limbombe"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4786962"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_15686"}

{:event/type "shoton"
:event/elapsed 28
:event/subtype "shot"
:event/player1 "Marcel Ritzmaier"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4786967"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_15686"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Janio Bikel"
:event/subtype "pull"
:event/player1 "Simon Thern"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4786970"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_15686"}

{:event/type "foulcommit"
:event/elapsed 30
:event/player2 "Lucas Woudenberg"
:event/subtype "pull"
:event/player1 "Luciano Slagveer"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4786973"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_15686"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Anthony Limbombe"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4786983"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_15686"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Gregor Breinburg"
:event/subtype "trip"
:event/player1 "Luciano Slagveer"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4786986"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_15686"}

{:event/type "shoton"
:event/elapsed 32
:event/subtype "direct_freekick"
:event/player1 "Marcel Ritzmaier"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4786992"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_15686"}

{:event/type "corner"
:event/elapsed 32
:event/subtype "short_left"
:event/player1 "Anthony Limbombe"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4786996"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_15686"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Marcel Ritzmaier"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4786998"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_15686"}

{:event/type "corner"
:event/elapsed 33
:event/subtype "cross_left"
:event/player1 "Marcel Ritzmaier"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4787018"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_15686"}

{:event/type "shoton"
:event/elapsed 34
:event/subtype "blocked_shot"
:event/player1 "Rens van Eijden"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4787022"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_15686"}

{:event/type "shotoff"
:event/elapsed 35
:event/subtype "distance"
:event/player1 "Anthony Limbombe"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4787047"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_15686"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Sam Larsson"
:event/subtype "trip"
:event/player1 "Todd Kane"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4787064"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_15686"}

{:event/type "shoton"
:event/elapsed 37
:event/subtype "direct_freekick"
:event/player1 "unknown"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4787074"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_15686"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Janio Bikel"
:event/subtype "trip"
:event/player1 "Joey van den Berg"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4787097"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_15686"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Lucas Woudenberg"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4787099"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_15686"}

{:event/type "corner"
:event/elapsed 40
:event/subtype "cross_left"
:event/player1 "Anthony Limbombe"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_4787102"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_15686"}

{:event/type "shoton"
:event/elapsed 40
:event/subtype "header"
:event/player1 "Christian Santos"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_4787103"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_15686"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Janio Bikel"
:event/subtype "trip"
:event/player1 "Sam Larsson"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4787124"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_15686"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Anthony Limbombe"
:event/subtype "pull"
:event/player1 "Tarik Kada"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4787150"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_15686"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Kenny Otigba"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4787162"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_15686"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "Christian Santos"
:event/subtype "trip"
:event/player1 "Luciano Slagveer"
:event/sortorder 5
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4787175"
:event/minute 46
:event/match_id "match_15686"}

{:event/type "corner"
:event/elapsed 47
:event/subtype "cross_right"
:event/player1 "Branco van den Boomen"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4787320"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_15686"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Luciano Slagveer"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4787322"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_15686"}

{:event/type "corner"
:event/elapsed 48
:event/subtype "cross_left"
:event/player1 "Branco van den Boomen"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4787324"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_15686"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Tarik Kada"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4787331"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_15686"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Marcel Ritzmaier"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4787366"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_15686"}

{:event/type "shotoff"
:event/elapsed 52
:event/subtype "volley"
:event/player1 "Navarone Foor"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4787370"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_15686"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Tarik Kada"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4787373"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_15686"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Marcel Ritzmaier"
:event/subtype "trip"
:event/player1 "Joey van den Berg"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4787387"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_15686"}

{:event/type "shotoff"
:event/elapsed 57
:event/subtype "shot"
:event/player1 "Luciano Slagveer"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4787416"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_15686"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Anthony Limbombe"
:event/subtype "serious_foul"
:event/player1 "Pele van Anholt"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4787422"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_15686"}

{:event/type "card"
:event/elapsed 57
:event/card_type "y"
:event/player1 "Pele van Anholt"
:event/sortorder 4
:event/team "away"
:event/event_type "card"
:event/id "event_4787424"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_15686"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Pele van Anholt"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4787456"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_15686"}

{:event/type "shoton"
:event/elapsed 60
:event/subtype "shot"
:event/player1 "Sam Larsson"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4787457"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_15686"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Luciano Slagveer"
:event/subtype "trip"
:event/player1 "Wojciech Golla"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4787468"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_15686"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Sam Larsson"
:event/subtype "trip"
:event/player1 "Todd Kane"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4787479"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_15686"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Navarone Foor"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4787480"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_15686"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Gregor Breinburg"
:event/subtype "pushing"
:event/player1 "Simon Thern"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4787482"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_15686"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Marcel Ritzmaier"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4787485"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_15686"}

{:event/type "corner"
:event/elapsed 66
:event/subtype "cross_left"
:event/player1 "Marcel Ritzmaier"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4787487"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_15686"}

{:event/type "shoton"
:event/elapsed 66
:event/subtype "header"
:event/player1 "Janio Bikel"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4787489"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_15686"}

{:event/type "shotoff"
:event/elapsed 66
:event/subtype "post"
:event/player1 "Christian Santos"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4787490"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_15686"}

{:event/type "foulcommit"
:event/elapsed 66
:event/player2 "Sam Larsson"
:event/subtype "trip"
:event/player1 "Todd Kane"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4787491"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_15686"}

{:event/type "card"
:event/elapsed 66
:event/card_type "y"
:event/player1 "Todd Kane"
:event/sortorder 4
:event/team "home"
:event/event_type "card"
:event/id "event_4787492"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_15686"}

{:event/type "shoton"
:event/elapsed 68
:event/subtype "blocked_shot"
:event/player1 "Simon Thern"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_4787499"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_15686"}

{:event/type "shotoff"
:event/elapsed 68
:event/subtype "miss_kick"
:event/player1 "Anthony Limbombe"
:event/sortorder 6
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4787502"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_15686"}

{:event/type "shoton"
:event/elapsed 69
:event/subtype "shot"
:event/player1 "Branco van den Boomen"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4787504"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_15686"}

{:event/type "card"
:event/elapsed 70
:event/card_type "y"
:event/subtype "diving"
:event/player1 "Luciano Slagveer"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_4787507"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_15686"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Gregor Breinburg"
:event/subtype "obstruction"
:event/player1 "Tarik Kada"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4787510"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_15686"}

{:event/type "corner"
:event/elapsed 72
:event/subtype "cross_left"
:event/player1 "Mihai Alexandru Roman"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_4787516"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_15686"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Mohamed Rayhi"
:event/subtype "pushing"
:event/player1 "Luciano Slagveer"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4787518"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_15686"}

{:event/type "corner"
:event/elapsed 74
:event/subtype "cross_left"
:event/player1 "Mohamed Rayhi"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4787522"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_15686"}

{:event/type "shotoff"
:event/elapsed 74
:event/subtype "post"
:event/player1 "Navarone Foor"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4787525"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_15686"}

{:event/type "goal"
:event/elapsed 74
:event/subtype "tap_in"
:event/player1 "Christian Santos"
:event/sortorder 5
:event/team "home"
:event/id "event_4787523"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_15686"}

{:event/type "shoton"
:event/elapsed 77
:event/subtype "shot"
:event/player1 "Tarik Kada"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4787535"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_15686"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Lucas Bijker"
:event/subtype "pushing"
:event/player1 "Navarone Foor"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4787561"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_15686"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Sam Larsson"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4787564"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_15686"}

{:event/type "corner"
:event/elapsed 80
:event/subtype "cross_left"
:event/player1 "Sam Larsson"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_4787569"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_15686"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Tarik Kada"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4787572"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_15686"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Luciano Slagveer"
:event/subtype "trip"
:event/player1 "Lucas Woudenberg"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4787577"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_15686"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Joey van den Berg"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4787580"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_15686"}

{:event/type "shoton"
:event/elapsed 82
:event/subtype "shot"
:event/player1 "Stefano Marzo"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4787591"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_15686"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Mohamed Rayhi"
:event/subtype "pull"
:event/player1 "Stefano Marzo"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4787594"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_15686"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Simon Thern"
:event/subtype "trip"
:event/player1 "Navarone Foor"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4787616"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_15686"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Lucas Bijker"
:event/subtype "trip"
:event/player1 "Christian Santos"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4787622"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_15686"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Kenny Otigba"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4787630"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_15686"}

{:event/type "shoton"
:event/elapsed 89
:event/subtype "blocked_shot"
:event/player1 "Mihai Alexandru Roman"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_4787666"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_15686"}

{:event/type "corner"
:event/elapsed 90
:event/subtype "cross_left"
:event/player1 "Mohamed Rayhi"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4787670"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_15686"}

{:event/type "shotoff"
:event/elapsed 90
:event/subtype "header"
:event/player1 "Christian Santos"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4787673"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_15686"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Lucas Bijker"
:event/subtype "pull"
:event/player1 "unknown"
:event/sortorder 7
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4787694"
:event/minute 92
:event/match_id "match_15686"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Sam Larsson"
:event/sortorder 8
:event/team "away"
:event/event_type "cross"
:event/id "event_4787697"
:event/minute 92
:event/match_id "match_15686"}

{:event/type "corner"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross_right"
:event/player1 "Stefano Marzo"
:event/sortorder 12
:event/team "away"
:event/event_type "corner"
:event/id "event_4787706"
:event/minute 93
:event/match_id "match_15686"}


]

