
;;# data
[
{:match/id "match_2323"
:match/league "England Premier League"
:match/hometeam "Everton"
:match/awayteam "Hull City"
:match/score "5:2"
:match/hometeam_goals "5"
:match/awayteam_goals "1"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_984225"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_2323"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Richard Garcia"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_984244"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_2323"}

{:event/type "shoton"
:event/elapsed 6
:event/subtype "shot"
:event/player1 "Richard Garcia"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_984255"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_2323"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_984289"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_2323"}

{:event/type "shotoff"
:event/elapsed 11
:event/subtype "distance"
:event/player1 "Mikel Arteta"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_984322"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_2323"}

{:event/type "shotoff"
:event/elapsed 13
:event/subtype "big chance post"
:event/player1 "Leon Osman"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_984342"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_2323"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Aiyegbeni Yakubu"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_984394"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_2323"}

{:event/type "goal"
:event/elapsed 17
:event/player2 "Aiyegbeni Yakubu"
:event/subtype "shot"
:event/player1 "Mikel Arteta"
:event/sortorder 1
:event/team "home"
:event/id "event_984396"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_2323"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player1 "Richard Garcia"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_984429"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_2323"}

{:event/type "shoton"
:event/elapsed 21
:event/subtype "blocked_shot"
:event/player1 "Steven Pienaar"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_984439"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_2323"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Philip Neville"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_984443"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_2323"}

{:event/type "foulcommit"
:event/elapsed 22
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_984465"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_2323"}

{:event/type "foulcommit"
:event/elapsed 26
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_984497"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_2323"}

{:event/type "foulcommit"
:event/elapsed 26
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_984506"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_2323"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Paul McShane"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_984512"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_2323"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_984524"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_2323"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Aiyegbeni Yakubu"
:event/subtype "penalty"
:event/player1 "Kamil Zayatte"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_984526"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_2323"}

{:event/type "goal"
:event/elapsed 29
:event/subtype "saved_back_into_play"
:event/player1 "Aiyegbeni Yakubu"
:event/sortorder 0
:event/team "home"
:event/id "event_984536"
:event/event_type "goal"
:event/goal_type "npm"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2323"}

{:event/type "shotoff"
:event/elapsed 30
:event/subtype "distance"
:event/player1 "Leon Osman"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_984541"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_2323"}

{:event/type "foulcommit"
:event/elapsed 31
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_984549"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_2323"}

{:event/type "goal"
:event/elapsed 32
:event/subtype "distance"
:event/player1 "Tom Cairney"
:event/sortorder 2
:event/team "away"
:event/id "event_984565"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_2323"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player1 "Jimmy Bullard"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_984609"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_2323"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Sylvain Distin"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_984636"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_2323"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Steven Pienaar"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_984650"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_2323"}

{:event/type "goal"
:event/elapsed 39
:event/player2 "Steven Pienaar"
:event/subtype "shot"
:event/player1 "Mikel Arteta"
:event/sortorder 2
:event/team "home"
:event/id "event_984647"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_2323"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_984670"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_2323"}

{:event/type "shotoff"
:event/elapsed 43
:event/subtype "distance"
:event/player1 "Richard Garcia"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_984695"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_2323"}

{:event/type "foulcommit"
:event/elapsed 43
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_984704"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_2323"}

{:event/type "foulcommit"
:event/elapsed 47
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_984868"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_2323"}

{:event/type "shoton"
:event/elapsed 47
:event/subtype "blocked_shot"
:event/player1 "Mikel Arteta"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_984872"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_2323"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Mikel Arteta"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_984875"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_2323"}

{:event/type "corner"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Mikel Arteta"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_984875"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_2323"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 45
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_984766"
:event/minute 48
:event/match_id "match_2323"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Jack Rodwell"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_984879"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_2323"}

{:event/type "foulcommit"
:event/elapsed 49
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_984894"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_2323"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Victor Anichebe"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_984907"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_2323"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_984908"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_2323"}

{:event/type "shoton"
:event/elapsed 51
:event/subtype "deflected"
:event/player1 "Jack Rodwell"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_984917"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_2323"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_984920"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_2323"}

{:event/type "goal"
:event/elapsed 51
:event/player1 "Richard Garcia"
:event/sortorder 2
:event/team "away"
:event/id "event_984922"
:event/event_type "goal"
:event/goal_type "o"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_2323"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Jack Rodwell"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_984931"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_2323"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_984944"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_2323"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Jimmy Bullard"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_984982"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_2323"}

{:event/type "corner"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Jimmy Bullard"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_984982"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_2323"}

{:event/type "shotoff"
:event/elapsed 57
:event/subtype "deflected"
:event/player1 "Jack Rodwell"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_984991"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_2323"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Steven Pienaar"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_984998"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_2323"}

{:event/type "corner"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Steven Pienaar"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_984998"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_2323"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_985012"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_2323"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_985018"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_2323"}

{:event/type "shoton"
:event/elapsed 59
:event/subtype "blocked_shot"
:event/player1 "Victor Anichebe"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_985022"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_2323"}

{:event/type "foulcommit"
:event/elapsed 63
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_985060"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_2323"}

{:event/type "shoton"
:event/elapsed 63
:event/subtype "shot"
:event/player1 "Aiyegbeni Yakubu"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_985068"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_2323"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Victor Anichebe"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_985069"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_2323"}

{:event/type "shoton"
:event/elapsed 63
:event/subtype "blocked_shot"
:event/player1 "Mikel Arteta"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_985071"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_2323"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player1 "Steven Pienaar"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_985093"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_2323"}

{:event/type "shotoff"
:event/elapsed 66
:event/subtype "header"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_985101"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_2323"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Steven Pienaar"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_985112"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_2323"}

{:event/type "foulcommit"
:event/elapsed 68
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_985124"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_2323"}

{:event/type "shotoff"
:event/elapsed 74
:event/subtype "shot"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_985187"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_2323"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_985208"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_2323"}

{:event/type "shoton"
:event/elapsed 76
:event/subtype "header"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_985209"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_2323"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_985237"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_2323"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_985280"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_2323"}

{:event/type "goal"
:event/elapsed 82
:event/player2 "Leighton Baines"
:event/subtype "shot"
:event/player1 "Landon Donovan"
:event/sortorder 1
:event/team "home"
:event/id "event_985281"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_2323"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Kevin Kilbane"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_985313"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_2323"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Geovanni"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_985318"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_2323"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Landon Donovan"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_985336"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_2323"}

{:event/type "goal"
:event/elapsed 86
:event/player2 "Landon Donovan"
:event/subtype "shot"
:event/player1 "Jack Rodwell"
:event/sortorder 3
:event/team "home"
:event/id "event_985338"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_2323"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player1 "Paul McShane"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_985367"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_2323"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_985376"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_2323"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Dan Gosling"
:event/subtype "serious_foul"
:event/player1 "Richard Garcia"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_985390"
:event/minute 92
:event/match_id "match_2323"}

{:event/type "card"
:event/elapsed_plus 2
:event/elapsed 90
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Richard Garcia"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_985391"
:event/minute 92
:event/match_id "match_2323"}


]

