
;;# data
[
{:match/id "match_6493"
:match/league "France Ligue 1"
:match/hometeam "Olympique Lyonnais"
:match/awayteam "Olympique de Marseille"
:match/score "0:0"
:match/hometeam_goals "0"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 59
:event/card_type "y"
:event/player1 "Pape Modou Sougou"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2645272"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_6493"}

{:event/type "card"
:event/elapsed 78
:event/card_type "y"
:event/player1 "Mathieu Valbuena"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2645310"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_6493"}


]

