
;;# data
[
{:match/id "match_4169"
:match/league "England Premier League"
:match/hometeam "Aston Villa"
:match/awayteam "Chelsea"
:match/score "1:2"
:match/hometeam_goals "1"
:match/awayteam_goals "2"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Oscar"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4132886"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_4169"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "Willian"
:event/subtype "pushing"
:event/player1 "Aly Cissokho"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4132910"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_4169"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Fabian Delph"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4132928"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_4169"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Cesar Azpilicueta"
:event/subtype "advantage"
:event/player1 "Tom Cleverley"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4132962"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_4169"}

{:event/type "card"
:event/elapsed 5
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Tom Cleverley"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_4132954"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_4169"}

{:event/type "goal"
:event/elapsed 8
:event/player2 "Willian"
:event/subtype "shot"
:event/player1 "Eden Hazard"
:event/sortorder 3
:event/team "away"
:event/id "event_4133048"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_4169"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Aly Cissokho"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4133106"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_4169"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Eden Hazard"
:event/subtype "trip"
:event/player1 "Ashley R. Westwood"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4133123"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_4169"}

{:event/type "shotoff"
:event/elapsed 12
:event/subtype "shot"
:event/player1 "Oscar"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4133146"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_4169"}

{:event/type "corner"
:event/elapsed 13
:event/subtype "cross_left"
:event/player1 "Ashley R. Westwood"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4133180"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_4169"}

{:event/type "foulcommit"
:event/elapsed 14
:event/subtype "hands"
:event/player1 "Gabriel Agbonlahor"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4133187"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_4169"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Ashley R. Westwood"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4133245"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_4169"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Gabriel Agbonlahor"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4133249"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_4169"}

{:event/type "corner"
:event/elapsed 16
:event/subtype "cross_right"
:event/player1 "Ashley R. Westwood"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_4133268"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_4169"}

{:event/type "corner"
:event/elapsed 17
:event/subtype "cross_left"
:event/player1 "Ashley R. Westwood"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4133280"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_4169"}

{:event/type "shotoff"
:event/elapsed 17
:event/subtype "header"
:event/player1 "Andreas Weimann"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4133285"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_4169"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Fabian Delph"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4133334"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_4169"}

{:event/type "shotoff"
:event/elapsed 19
:event/subtype "header"
:event/player1 "Gabriel Agbonlahor"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4133338"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_4169"}

{:event/type "corner"
:event/elapsed 22
:event/subtype "cross_right"
:event/player1 "Willian"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4133390"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_4169"}

{:event/type "shoton"
:event/elapsed 22
:event/subtype "shot"
:event/player1 "Oscar"
:event/sortorder 5
:event/team "away"
:event/event_type "shoton"
:event/id "event_4133405"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_4169"}

{:event/type "corner"
:event/elapsed 23
:event/subtype "short_right"
:event/player1 "Willian"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4133411"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_4169"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Eden Hazard"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4133433"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_4169"}

{:event/type "shoton"
:event/elapsed 23
:event/subtype "header"
:event/player1 "Gary Cahill"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4133413"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_4169"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Willian"
:event/subtype "trip"
:event/player1 "Aly Cissokho"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4133423"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_4169"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Gabriel Agbonlahor"
:event/subtype "trip"
:event/player1 "John Terry"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4133447"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_4169"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Carles Gil"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4133453"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_4169"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Alan Hutton"
:event/subtype "trip"
:event/player1 "Oscar"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4133496"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_4169"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Alan Hutton"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4133533"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_4169"}

{:event/type "corner"
:event/elapsed 31
:event/subtype "cross_left"
:event/player1 "Oscar"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4133571"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_4169"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Tom Cleverley"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4133589"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_4169"}

{:event/type "card"
:event/elapsed 35
:event/card_type "y"
:event/subtype "verbal_abuse"
:event/player1 "Ramires"
:event/sortorder 4
:event/team "away"
:event/event_type "card"
:event/id "event_4133685"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_4169"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Gabriel Agbonlahor"
:event/subtype "trip"
:event/player1 "Branislav Ivanovic"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4133722"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_4169"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Carles Gil"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4133735"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_4169"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Ashley R. Westwood"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_4133744"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_4169"}

{:event/type "corner"
:event/elapsed 39
:event/subtype "cross_right"
:event/player1 "Willian"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4133793"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_4169"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Oscar"
:event/subtype "trip"
:event/player1 "Ashley R. Westwood"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4133822"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_4169"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Carles Gil"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4133947"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_4169"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Alan Hutton"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4133975"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_4169"}

{:event/type "card"
:event/elapsed 44
:event/card_type "y"
:event/player1 "Ashley R. Westwood"
:event/sortorder 6
:event/team "home"
:event/event_type "card"
:event/id "event_4133985"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_4169"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Eden Hazard"
:event/subtype "trip"
:event/player1 "Ashley R. Westwood"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4133991"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_4169"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Aly Cissokho"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4134379"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_4169"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Alan Hutton"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_4134391"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_4169"}

{:event/type "shotoff"
:event/elapsed 47
:event/subtype "volley"
:event/player1 "Andreas Weimann"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4134398"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_4169"}

{:event/type "shoton"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "blocked_shot"
:event/player1 "Eden Hazard"
:event/sortorder 8
:event/team "away"
:event/event_type "shoton"
:event/id "event_4134056"
:event/minute 47
:event/match_id "match_4169"}

{:event/type "shotoff"
:event/elapsed 48
:event/subtype "deflected"
:event/player1 "Tom Cleverley"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4134447"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_4169"}

{:event/type "corner"
:event/elapsed 48
:event/subtype "cross_right"
:event/player1 "Carles Gil"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_4134450"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_4169"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Carles Gil"
:event/sortorder 6
:event/team "home"
:event/event_type "cross"
:event/id "event_4134501"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_4169"}

{:event/type "goal"
:event/elapsed 48
:event/player2 "Carles Gil"
:event/subtype "header"
:event/player1 "Jores Okore"
:event/sortorder 7
:event/team "home"
:event/id "event_4134455"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_4169"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Aly Cissokho"
:event/sortorder 9
:event/team "home"
:event/event_type "cross"
:event/id "event_4134076"
:event/minute 48
:event/match_id "match_4169"}

{:event/type "card"
:event/elapsed 48
:event/card_type "y"
:event/subtype "Removing Shirt"
:event/player1 "Jores Okore"
:event/sortorder 9
:event/team "home"
:event/event_type "card"
:event/id "event_4134592"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_4169"}

{:event/type "corner"
:event/elapsed_plus 3
:event/elapsed 45
:event/subtype "cross_left"
:event/player1 "Ashley R. Westwood"
:event/sortorder 11
:event/team "home"
:event/event_type "corner"
:event/id "event_4134085"
:event/minute 48
:event/match_id "match_4169"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Ashley R. Westwood"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4134514"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_4169"}

{:event/type "shotoff"
:event/elapsed 50
:event/subtype "header"
:event/player1 "Gabriel Agbonlahor"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4134509"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_4169"}

{:event/type "shoton"
:event/elapsed 52
:event/subtype "blocked_shot"
:event/player1 "Ramires"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4134559"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_4169"}

{:event/type "shoton"
:event/elapsed 52
:event/subtype "distance"
:event/player1 "Nemanja Matic"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4134567"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_4169"}

{:event/type "shotoff"
:event/elapsed 55
:event/subtype "shot"
:event/player1 "Willian"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4134658"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_4169"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Andreas Weimann"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4134685"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_4169"}

{:event/type "shotoff"
:event/elapsed 56
:event/subtype "distance"
:event/player1 "Willian"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4134702"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_4169"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Cesar Azpilicueta"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4134724"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_4169"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Fabian Delph"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4134752"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_4169"}

{:event/type "corner"
:event/elapsed 60
:event/subtype "cross_right"
:event/player1 "Willian"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_4134819"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_4169"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Alan Hutton"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4134839"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_4169"}

{:event/type "corner"
:event/elapsed 61
:event/subtype "cross_right"
:event/player1 "Carles Gil"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4134848"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_4169"}

{:event/type "shoton"
:event/elapsed 62
:event/subtype "blocked_shot"
:event/player1 "Ashley R. Westwood"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4134866"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_4169"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Fabian Delph"
:event/subtype "trip"
:event/player1 "Eden Hazard"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4134870"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_4169"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Carles Gil"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4134899"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_4169"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Oscar"
:event/subtype "trip"
:event/player1 "Fabian Delph"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4134910"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_4169"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Cesar Azpilicueta"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4134984"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_4169"}

{:event/type "goal"
:event/elapsed 66
:event/player2 "Cesar Azpilicueta"
:event/subtype "volley"
:event/player1 "Branislav Ivanovic"
:event/sortorder 4
:event/team "away"
:event/id "event_4134970"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_4169"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Fabian Delph"
:event/subtype "trip"
:event/player1 "Oscar"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4135061"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_4169"}

{:event/type "shotoff"
:event/elapsed 72
:event/subtype "deflected"
:event/player1 "Loic Remy"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4135103"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_4169"}

{:event/type "corner"
:event/elapsed 73
:event/subtype "cross_right"
:event/player1 "Willian"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4135120"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_4169"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Fabian Delph"
:event/subtype "obstruction"
:event/player1 "Eden Hazard"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4135148"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_4169"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Aly Cissokho"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4135151"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_4169"}

{:event/type "corner"
:event/elapsed 75
:event/subtype "cross_left"
:event/player1 "Carles Gil"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_4135157"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_4169"}

{:event/type "shotoff"
:event/elapsed 75
:event/subtype "bad shot"
:event/player1 "Ciaran Clark"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4135160"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_4169"}

{:event/type "foulcommit"
:event/elapsed 76
:event/subtype "trip"
:event/player1 "Ciaran Clark"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4135173"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_4169"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Alan Hutton"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4135210"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_4169"}

{:event/type "corner"
:event/elapsed 81
:event/subtype "cross_right"
:event/player1 "Juan Cuadrado"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4135272"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_4169"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Scott Sinclair"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4135354"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_4169"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Scott Sinclair"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4135396"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_4169"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Jores Okore"
:event/subtype "pull"
:event/player1 "Juan Cuadrado"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4135440"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_4169"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Alan Hutton"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_4135463"
:event/minute 92
:event/match_id "match_4169"}

{:event/type "shotoff"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "header"
:event/player1 "Christian Benteke"
:event/sortorder 5
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4135467"
:event/minute 92
:event/match_id "match_4169"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Ashley R. Westwood"
:event/sortorder 7
:event/team "home"
:event/event_type "cross"
:event/id "event_4135478"
:event/minute 93
:event/match_id "match_4169"}

{:event/type "card"
:event/elapsed_plus 4
:event/elapsed 90
:event/card_type "y"
:event/subtype "stall_time"
:event/player1 "Branislav Ivanovic"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_4135542"
:event/minute 94
:event/match_id "match_4169"}


]

