
;;# data
[
{:match/id "match_11335"
:match/league "Italy Serie A"
:match/hometeam "Brescia"
:match/awayteam "Fiorentina"
:match/score "2:2"
:match/hometeam_goals "2"
:match/awayteam_goals "2"}

{:event/type "goal"
:event/elapsed 2
:event/player1 "Juan Vargas"
:event/sortorder 0
:event/team "away"
:event/id "event_1565332"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_11335"}

{:event/type "goal"
:event/elapsed 19
:event/player1 "unknown"
:event/sortorder 0
:event/team "home"
:event/id "event_1565779"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_11335"}

{:event/type "card"
:event/elapsed 51
:event/card_type "y"
:event/player1 "Jonathan Zebina"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1566633"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_11335"}

{:event/type "goal"
:event/elapsed 75
:event/player1 "Alessio Cerci"
:event/sortorder 0
:event/team "away"
:event/id "event_1566802"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_11335"}

{:event/type "goal"
:event/elapsed 88
:event/player1 "Pietro Accardi"
:event/sortorder 0
:event/team "home"
:event/id "event_1566833"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_11335"}

{:event/type "card"
:event/elapsed 89
:event/card_type "y"
:event/player1 "Davide Zoboli"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1566855"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_11335"}


]

