
;;# data
[
{:match/id "match_8200"
:match/league "Germany 1. Bundesliga"
:match/hometeam "FC Schalke 04"
:match/awayteam "1. FC Nürnberg"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Angelos Charisteas"
:event/subtype "pushing"
:event/player1 "Heiko Westermann"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_913748"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 5
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_913791"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_8200"}

{:event/type "shoton"
:event/elapsed 7
:event/subtype "shot"
:event/player1 "Albert Bunjaku"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_913829"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_8200"}

{:event/type "shotoff"
:event/elapsed 9
:event/subtype "distance"
:event/player1 "Ivan Rakitic"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_913845"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Daniel Gygax"
:event/player1 "Jefferson Farfan"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_913858"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Angelos Charisteas"
:event/subtype "from_behind"
:event/player1 "Marcelo Jose Bordon"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_913888"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_8200"}

{:event/type "cross"
:event/elapsed 13
:event/subtype "cross"
:event/player1 "Daniel Gygax"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_913898"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_8200"}

{:event/type "shotoff"
:event/elapsed 13
:event/subtype "shot"
:event/player1 "Ilkay Guendogan"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_913901"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_8200"}

{:event/type "shotoff"
:event/elapsed 15
:event/subtype "shot"
:event/player1 "Albert Bunjaku"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_913943"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "Jefferson Farfan"
:event/subtype "pushing"
:event/player1 "Dennis Diekmeier"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_913949"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player1 "Jefferson Farfan"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_913962"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_8200"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Edu"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_913966"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_8200"}

{:event/type "shotoff"
:event/elapsed 18
:event/subtype "header"
:event/player1 "Kevin Kuranyi"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_913967"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Marcelo Jose Bordon"
:event/player1 "Albert Bunjaku"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_913987"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Rafinha"
:event/subtype "pushing"
:event/player1 "Javier Pinola"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_913993"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Ilkay Guendogan"
:event/player1 "Rafinha"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_914001"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Daniel Gygax"
:event/player1 "Lukas Schmitz"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_914008"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_8200"}

{:event/type "shotoff"
:event/elapsed 26
:event/subtype "big chance post"
:event/player1 "Angelos Charisteas"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_914023"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player1 "Albert Bunjaku"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_914026"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player1 "Haavard Nordtveit"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_914029"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_8200"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Rafinha"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_914034"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_8200"}

{:event/type "corner"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Rafinha"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_914034"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_8200"}

{:event/type "shoton"
:event/elapsed 28
:event/subtype "big chance blocked"
:event/player1 "Albert Bunjaku"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_914038"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_8200"}

{:event/type "shoton"
:event/elapsed 28
:event/subtype "blocked_shot"
:event/player1 "Jefferson Farfan"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_914041"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_8200"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Rafinha"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_914046"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_8200"}

{:event/type "corner"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Rafinha"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_914046"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_8200"}

{:event/type "shotoff"
:event/elapsed 30
:event/subtype "distance"
:event/player1 "Ivan Rakitic"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_914054"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_8200"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_914062"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_8200"}

{:event/type "corner"
:event/elapsed 31
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_914062"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 34
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_914082"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 34
:event/player2 "Rafinha"
:event/subtype "serious_foul"
:event/player1 "Ilkay Guendogan"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_914089"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_8200"}

{:event/type "card"
:event/elapsed 34
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Ilkay Guendogan"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_914090"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Jefferson Farfan"
:event/subtype "from_behind"
:event/player1 "Albert Bunjaku"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_914117"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Lukas Schmitz"
:event/subtype "pushing"
:event/player1 "Albert Bunjaku"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_914155"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_8200"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Jefferson Farfan"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_914172"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 41
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_914185"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_8200"}

{:event/type "shotoff"
:event/elapsed 42
:event/subtype "shot"
:event/player1 "Andreas Ottl"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_914199"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 44
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_914232"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_8200"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Ivan Rakitic"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_914250"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_8200"}

{:event/type "corner"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Ivan Rakitic"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_914250"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_8200"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Ivan Rakitic"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_914256"
:event/minute 46
:event/match_id "match_8200"}

{:event/type "corner"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Ivan Rakitic"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_914256"
:event/minute 46
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "Raphael Schaefer"
:event/subtype "pushing"
:event/player1 "Heiko Westermann"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_914257"
:event/minute 46
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 46
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_914439"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 47
:event/player1 "Albert Bunjaku"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_914449"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_8200"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Jefferson Farfan"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_914469"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_8200"}

{:event/type "goal"
:event/elapsed 48
:event/player2 "Jefferson Farfan"
:event/subtype "shot"
:event/player1 "Kevin Kuranyi"
:event/sortorder 5
:event/team "home"
:event/id "event_914464"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Jefferson Farfan"
:event/player1 "Javier Pinola"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_914479"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_8200"}

{:event/type "card"
:event/elapsed 49
:event/card_type "y"
:event/player1 "Javier Pinola"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_914481"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_8200"}

{:event/type "shotoff"
:event/elapsed 50
:event/subtype "distance"
:event/player1 "Daniel Gygax"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_914495"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Benedikt Hoewedes"
:event/subtype "pushing"
:event/player1 "Angelos Charisteas"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_914520"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Albert Bunjaku"
:event/player1 "Marcelo Jose Bordon"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_914523"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 53
:event/subtype "hands"
:event/player1 "Edu"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_914533"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Breno"
:event/player1 "Kevin Kuranyi"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_914549"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_8200"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Christoph Moritz"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_914565"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_8200"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Jefferson Farfan"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_914576"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_8200"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Ivan Rakitic"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_914579"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_8200"}

{:event/type "corner"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Ivan Rakitic"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_914579"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 59
:event/player2 "Dennis Diekmeier"
:event/subtype "serious_foul"
:event/player1 "Heiko Westermann"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_914594"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 61
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_914611"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Haavard Nordtveit"
:event/subtype "from_behind"
:event/player1 "Kevin Kuranyi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_914620"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_8200"}

{:event/type "shotoff"
:event/elapsed 63
:event/subtype "distance"
:event/player1 "Ilkay Guendogan"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_914622"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_8200"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Ivan Rakitic"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_914634"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_8200"}

{:event/type "corner"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Ivan Rakitic"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_914634"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_8200"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Edu"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_914636"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_8200"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/sortorder 4
:event/team "home"
:event/event_type "throwin"
:event/id "event_914639"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_8200"}

{:event/type "shotoff"
:event/elapsed 69
:event/subtype "big chance post"
:event/player1 "Christian Eigler"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_914661"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_8200"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Daniel Gygax"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_914662"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_8200"}

{:event/type "corner"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Daniel Gygax"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_914662"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 72
:event/player2 "Manuel Neuer"
:event/player1 "Angelos Charisteas"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_914669"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 74
:event/player2 "Jefferson Farfan"
:event/player1 "Christian Eigler"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_914685"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_8200"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_914704"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_8200"}

{:event/type "corner"
:event/elapsed 76
:event/subtype "cross"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_914704"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_8200"}

{:event/type "shotoff"
:event/elapsed 76
:event/subtype "volley"
:event/player1 "Albert Bunjaku"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_914705"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_8200"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Christian Eigler"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_914714"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 78
:event/player2 "Javier Pinola"
:event/subtype "pushing"
:event/player1 "Edu"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_914723"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player1 "Kevin Kuranyi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_914751"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Javier Pinola"
:event/player1 "Christoph Moritz"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_914785"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player1 "Edu"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_914792"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_8200"}

{:event/type "card"
:event/elapsed 85
:event/card_type "y"
:event/player1 "Edu"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_914795"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Edu"
:event/player1 "Andreas Ottl"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_914819"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_8200"}

{:event/type "card"
:event/elapsed 88
:event/card_type "y"
:event/subtype "verbal_abuse"
:event/player1 "Andreas Ottl"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_914820"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_8200"}

{:event/type "shoton"
:event/elapsed 89
:event/subtype "blocked_shot"
:event/player1 "Heiko Westermann"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_914824"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_8200"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Ivan Rakitic"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_914828"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_8200"}

{:event/type "corner"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Ivan Rakitic"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_914828"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Raphael Schaefer"
:event/subtype "pushing"
:event/player1 "Kevin Kuranyi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_914832"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_8200"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Vicente Sanchez"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_914848"
:event/minute 91
:event/match_id "match_8200"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_914864"
:event/minute 92
:event/match_id "match_8200"}


]

