
;;# data
[
{:match/id "match_1828"
:match/league "England Premier League"
:match/hometeam "Hull City"
:match/awayteam "Sunderland"
:match/score "3:3"
:match/hometeam_goals "1"
:match/awayteam_goals "4"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Phil Bardsley"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_533634"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Richard Garcia"
:event/player1 "Danny Collins"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_533640"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "Steed Malbranque"
:event/player1 "Samuel Ricketts"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_533648"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed 5
:event/subtype "hands"
:event/player1 "Djibril Cisse"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_533657"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_1828"}

{:event/type "shotoff"
:event/elapsed 6
:event/subtype "distance"
:event/player1 "Nick Barmby"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_533666"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed 8
:event/player2 "Andrew Reid"
:event/subtype "pushing"
:event/player1 "Bernard Mendy"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_533675"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_1828"}

{:event/type "goal"
:event/elapsed 10
:event/player2 "Danny Collins"
:event/subtype "distance"
:event/player1 "Steed Malbranque"
:event/sortorder 1
:event/team "away"
:event/id "event_533696"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Djibril Cisse"
:event/player1 "Samuel Ricketts"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_533703"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "George Boateng"
:event/player1 "Kieran Richardson"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_533726"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "Kenwyne Jones"
:event/subtype "shirt_pull"
:event/player1 "George Boateng"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_533737"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_1828"}

{:event/type "card"
:event/elapsed 16
:event/card_type "y"
:event/subtype "shirt_pull"
:event/player1 "George Boateng"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_533739"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_1828"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Djibril Cisse"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_533741"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Kieran Richardson"
:event/player1 "Geovanni"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_533746"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_1828"}

{:event/type "shoton"
:event/elapsed 19
:event/subtype "shot"
:event/player1 "Michael Turner"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_533755"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_1828"}

{:event/type "goal"
:event/elapsed 19
:event/subtype "shot"
:event/player1 "Nick Barmby"
:event/sortorder 1
:event/team "home"
:event/id "event_533761"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_1828"}

{:event/type "shoton"
:event/elapsed 22
:event/subtype "blocked_shot"
:event/player1 "Nick Barmby"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_533788"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_1828"}

{:event/type "corner"
:event/elapsed 24
:event/subtype "short"
:event/player1 "Richard Garcia"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_533794"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_1828"}

{:event/type "shoton"
:event/elapsed 24
:event/subtype "shot"
:event/player1 "Geovanni"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_533795"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_1828"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Marlon King"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_533803"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_1828"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Geovanni"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_533810"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_1828"}

{:event/type "corner"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Geovanni"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_533810"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_1828"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Marlon King"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_533812"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_1828"}

{:event/type "shotoff"
:event/elapsed 25
:event/subtype "header"
:event/player1 "Michael Turner"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_533815"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_1828"}

{:event/type "shotoff"
:event/elapsed 27
:event/subtype "distance"
:event/player1 "Marlon King"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_533832"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Steed Malbranque"
:event/player1 "George Boateng"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_533842"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_1828"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Phil Bardsley"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_533848"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_1828"}

{:event/type "shotoff"
:event/elapsed 29
:event/subtype "header"
:event/player1 "Kenwyne Jones"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_533852"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_1828"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Marlon King"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_533867"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_1828"}

{:event/type "shoton"
:event/elapsed 30
:event/subtype "header"
:event/player1 "Geovanni"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_533868"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_1828"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Geovanni"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_533869"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_1828"}

{:event/type "corner"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Geovanni"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_533869"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Marlon King"
:event/player1 "Anton Ferdinand"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_533871"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_1828"}

{:event/type "shoton"
:event/elapsed 32
:event/subtype "direct_freekick"
:event/player1 "Geovanni"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_533875"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_1828"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Geovanni"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_533878"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_1828"}

{:event/type "corner"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Geovanni"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_533878"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Marton Fulop"
:event/player1 "Marlon King"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_533880"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_1828"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Andrew Reid"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_533897"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_1828"}

{:event/type "corner"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Andrew Reid"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_533897"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_1828"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Andrew Reid"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_533904"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_1828"}

{:event/type "corner"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Andrew Reid"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_533904"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_1828"}

{:event/type "shotoff"
:event/elapsed 37
:event/subtype "header"
:event/player1 "Kenwyne Jones"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_533909"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Ian Ashbee"
:event/player1 "Kieran Richardson"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_533914"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_1828"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Steed Malbranque"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_533922"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_1828"}

{:event/type "corner"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Steed Malbranque"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_533922"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_1828"}

{:event/type "shotoff"
:event/elapsed 39
:event/subtype "shot"
:event/player1 "Steed Malbranque"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_533933"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_1828"}

{:event/type "shoton"
:event/elapsed 41
:event/subtype "distance"
:event/player1 "Geovanni"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_533951"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Anton Ferdinand"
:event/player1 "Marlon King"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_533974"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_1828"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Andrew Reid"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_533985"
:event/minute 46
:event/match_id "match_1828"}

{:event/type "corner"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Andrew Reid"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_533985"
:event/minute 46
:event/match_id "match_1828"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "header"
:event/player1 "Kenwyne Jones"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_533988"
:event/minute 46
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed 46
:event/player2 "Andrew Reid"
:event/player1 "Ian Ashbee"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_534021"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Danny Collins"
:event/player1 "George Boateng"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_534048"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_1828"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Andrew Reid"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_534069"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_1828"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Phil Bardsley"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_534076"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_1828"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Andrew Reid"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_534082"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_1828"}

{:event/type "corner"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Andrew Reid"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_534082"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_1828"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Andrew Reid"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_534089"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Kenwyne Jones"
:event/player1 "Kamil Zayatte"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_534098"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_1828"}

{:event/type "shoton"
:event/elapsed 55
:event/subtype "blocked_shot"
:event/player1 "Kieran Richardson"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_534109"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_1828"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Marlon King"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_534112"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Steed Malbranque"
:event/player1 "Samuel Ricketts"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_534120"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_1828"}

{:event/type "shoton"
:event/elapsed 57
:event/subtype "distance"
:event/player1 "Kieran Richardson"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_534123"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_1828"}

{:event/type "shotoff"
:event/elapsed 57
:event/subtype "shot"
:event/player1 "Djibril Cisse"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_534127"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Nick Barmby"
:event/player1 "Anton Ferdinand"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_534130"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Marton Fulop"
:event/player1 "Marlon King"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_534136"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_1828"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Marlon King"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_534140"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_1828"}

{:event/type "shotoff"
:event/elapsed 59
:event/subtype "header"
:event/player1 "Nick Barmby"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_534141"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_1828"}

{:event/type "shoton"
:event/elapsed 61
:event/subtype "blocked_shot"
:event/player1 "Ian Ashbee"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_534154"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_1828"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Marlon King"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_534156"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_1828"}

{:event/type "corner"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Marlon King"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_534156"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_1828"}

{:event/type "shotoff"
:event/elapsed 62
:event/subtype "distance"
:event/player1 "Phil Bardsley"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_534164"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_1828"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Kieran Richardson"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_534190"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_1828"}

{:event/type "corner"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Kieran Richardson"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_534190"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player1 "Danny Collins"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_534191"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Danny Collins"
:event/player1 "Marlon King"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_534194"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Anton Ferdinand"
:event/player1 "Marlon King"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_534212"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Andrew Reid"
:event/player1 "George Boateng"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_534231"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Bernard Mendy"
:event/subtype "serious_foul"
:event/player1 "Kieran Richardson"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_534232"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_1828"}

{:event/type "card"
:event/elapsed 71
:event/card_type "y"
:event/player1 "Kieran Richardson"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_534235"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_1828"}

{:event/type "goal"
:event/elapsed 73
:event/subtype "shot"
:event/player1 "Daniel Cousin,20"
:event/sortorder 1
:event/team "home"
:event/id "event_534247"
:event/event_type "goal"
:event/goal_type "dg"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed 76
:event/player2 "Steed Malbranque"
:event/subtype "serious_foul"
:event/player1 "Samuel Ricketts"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_534270"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_1828"}

{:event/type "card"
:event/elapsed 76
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Samuel Ricketts"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_534274"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_1828"}

{:event/type "shoton"
:event/elapsed 77
:event/subtype "distance"
:event/player1 "Djibril Cisse"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_534285"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_1828"}

{:event/type "shoton"
:event/elapsed 77
:event/subtype "distance"
:event/player1 "Kieran Richardson"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_534318"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_1828"}

{:event/type "goal"
:event/elapsed 78
:event/player1 "Kamil Zayatte"
:event/sortorder 0
:event/team "home"
:event/id "event_534294"
:event/event_type "goal"
:event/goal_type "o"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Phil Bardsley"
:event/subtype "serious_foul"
:event/player1 "Samuel Ricketts"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_534320"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_1828"}

{:event/type "card"
:event/elapsed 81
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Samuel Ricketts"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_534448"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed 83
:event/player2 "Kieran Richardson"
:event/player1 "Geovanni"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_534334"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_1828"}

{:event/type "shoton"
:event/elapsed 83
:event/subtype "distance"
:event/player1 "Djibril Cisse"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_534340"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_1828"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Steed Malbranque"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_534345"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_1828"}

{:event/type "goal"
:event/elapsed 84
:event/player2 "Steed Malbranque"
:event/subtype "header"
:event/player1 "Kenwyne Jones"
:event/sortorder 1
:event/team "away"
:event/id "event_534347"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Nyron Nosworthy"
:event/player1 "Marlon King"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_534395"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_1828"}

{:event/type "card"
:event/elapsed 86
:event/card_type "y"
:event/player1 "Marlon King"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_534356"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_1828"}

{:event/type "shoton"
:event/elapsed 86
:event/subtype "distance"
:event/player1 "Marlon King"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_534362"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed 87
:event/player2 "Kieran Richardson"
:event/subtype "from_behind"
:event/player1 "Bernard Mendy"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_534366"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_1828"}

{:event/type "shotoff"
:event/elapsed 87
:event/subtype "direct_freekick"
:event/player1 "unknown"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_534369"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_1828"}

{:event/type "shotoff"
:event/elapsed 89
:event/subtype "distance"
:event/player1 "unknown"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_534378"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_1828"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Geovanni"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_534398"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_1828"}

{:event/type "corner"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Geovanni"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_534398"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_1828"}

{:event/type "goal"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Carlos Edwards"
:event/subtype "shot"
:event/player1 "Djibril Cisse"
:event/sortorder 2
:event/team "away"
:event/id "event_534406"
:event/event_type "goal"
:event/goal_type "n"
:event/minute 91
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Daniel Cousin,20"
:event/player1 "Nyron Nosworthy"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_534416"
:event/minute 92
:event/match_id "match_1828"}

{:event/type "shotoff"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "direct_freekick"
:event/player1 "Geovanni"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_534422"
:event/minute 93
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed_plus 5
:event/elapsed 90
:event/player2 "Daniel Cousin,20"
:event/player1 "Danny Collins"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_534438"
:event/minute 95
:event/match_id "match_1828"}

{:event/type "foulcommit"
:event/elapsed_plus 5
:event/elapsed 90
:event/player2 "Marlon King"
:event/subtype "shirt_pull"
:event/player1 "Nyron Nosworthy"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_534439"
:event/minute 95
:event/match_id "match_1828"}

{:event/type "shotoff"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "direct_freekick"
:event/player1 "Marlon King"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_534440"
:event/minute 95
:event/match_id "match_1828"}


]

