
;;# data
[
{:match/id "match_15665"
:match/league "Netherlands Eredivisie"
:match/hometeam "FC Groningen"
:match/awayteam "Heracles Almelo"
:match/score "2:1"
:match/hometeam_goals "2"
:match/awayteam_goals "1"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Robin Gosens"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5584798"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_15665"}

{:event/type "shotoff"
:event/elapsed 2
:event/subtype "miss_kick"
:event/player1 "Thomas Bruns"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5584808"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_15665"}

{:event/type "foulcommit"
:event/elapsed 2
:event/subtype "hands"
:event/player1 "Thomas Bruns"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5584812"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Oussama Idrissi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5584908"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_15665"}

{:event/type "shotoff"
:event/elapsed 6
:event/subtype "shot"
:event/player1 "Michael de Leeuw"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5584912"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Juninho Bacuna"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5584933"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_15665"}

{:event/type "foulcommit"
:event/elapsed 8
:event/player2 "Thomas Bruns"
:event/subtype "trip"
:event/player1 "Oussama Idrissi"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5584974"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_15665"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Jesper Drost"
:event/subtype "trip"
:event/player1 "Joey Pelupessy"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5585030"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Albert Rusnak"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5585042"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Jesper Drost"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5585066"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Oussama Idrissi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5585107"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_15665"}

{:event/type "foulcommit"
:event/elapsed 13
:event/subtype "hands"
:event/player1 "Hans Hateboer"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5585418"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Lorenzo Burnet"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5585286"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Oussama Idrissi"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5585297"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_15665"}

{:event/type "shotoff"
:event/elapsed 19
:event/subtype "deflected"
:event/player1 "Lorenzo Burnet"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5585311"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_15665"}

{:event/type "corner"
:event/elapsed 19
:event/subtype "cross_left"
:event/player1 "Albert Rusnak"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_5585321"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_15665"}

{:event/type "corner"
:event/elapsed 20
:event/subtype "cross_left"
:event/player1 "Albert Rusnak"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5585345"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_15665"}

{:event/type "shotoff"
:event/elapsed 20
:event/subtype "header"
:event/player1 "Hedwiges Maduro"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5585358"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_15665"}

{:event/type "corner"
:event/elapsed 21
:event/subtype "cross_right"
:event/player1 "Albert Rusnak"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_5585398"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_15665"}

{:event/type "shotoff"
:event/elapsed 22
:event/subtype "bad shot"
:event/player1 "Oussama Idrissi"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5585410"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_15665"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Paul Gladon"
:event/subtype "obstruction"
:event/player1 "Hedwiges Maduro"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5585588"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Iiass Bel Hassani"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5585622"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Hans Hateboer"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_5585645"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_15665"}

{:event/type "foulcommit"
:event/elapsed 30
:event/player2 "Justin Hoogma"
:event/subtype "pushing"
:event/player1 "Jesper Drost"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5585649"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_15665"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Iiass Bel Hassani"
:event/subtype "pushing"
:event/player1 "Oussama Idrissi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5585697"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_15665"}

{:event/type "shoton"
:event/elapsed 32
:event/subtype "blocked_shot"
:event/player1 "Lorenzo Burnet"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5585710"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Oussama Idrissi"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5585727"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_15665"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Thomas Bruns"
:event/subtype "pushing"
:event/player1 "Juninho Bacuna"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5585734"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_15665"}

{:event/type "shotoff"
:event/elapsed 34
:event/subtype "distance"
:event/player1 "Thomas Bruns"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5585770"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_15665"}

{:event/type "shoton"
:event/elapsed 35
:event/subtype "blocked_shot"
:event/player1 "Lorenzo Burnet"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5585798"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Lorenzo Burnet"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5585801"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Oussama Idrissi"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_5585816"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_15665"}

{:event/type "corner"
:event/elapsed 36
:event/subtype "cross_right"
:event/player1 "Albert Rusnak"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5585832"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_15665"}

{:event/type "shotoff"
:event/elapsed 36
:event/subtype "miss_kick"
:event/player1 "Oussama Idrissi"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5585842"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Robin Gosens"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5585881"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Iiass Bel Hassani"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5585923"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_15665"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Juninho Bacuna"
:event/subtype "from_behind"
:event/player1 "Peter van Ooijen"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5585940"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_15665"}

{:event/type "shotoff"
:event/elapsed 41
:event/subtype "miss_kick"
:event/player1 "Michael de Leeuw"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5586042"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Justin Hoogma"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5586072"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Iiass Bel Hassani"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5586094"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Oussama Idrissi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5586133"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Jesper Drost"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5586569"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Oussama Idrissi"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_5586270"
:event/minute 47
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Hans Hateboer"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5586635"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_15665"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Michael de Leeuw"
:event/subtype "from_behind"
:event/player1 "Justin Hoogma"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5586658"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_15665"}

{:event/type "shoton"
:event/elapsed 49
:event/subtype "blocked_shot"
:event/player1 "Jesper Drost"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5586687"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_15665"}

{:event/type "shotoff"
:event/elapsed 50
:event/subtype "deflected"
:event/player1 "Jesper Drost"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5586695"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_15665"}

{:event/type "corner"
:event/elapsed 50
:event/subtype "cross_left"
:event/player1 "Albert Rusnak"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_5586702"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Lorenzo Burnet"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_5586720"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_15665"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Juninho Bacuna"
:event/subtype "from_behind"
:event/player1 "Thomas Bruns"
:event/sortorder 5
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5586737"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_15665"}

{:event/type "shoton"
:event/elapsed 52
:event/subtype "distance"
:event/player1 "Jesper Drost"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_5586783"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Oussama Idrissi"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5586791"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Hans Hateboer"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5586797"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_15665"}

{:event/type "corner"
:event/elapsed 53
:event/subtype "short_left"
:event/player1 "Albert Rusnak"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_5586830"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_15665"}

{:event/type "goal"
:event/elapsed 53
:event/player2 "Lorenzo Burnet"
:event/subtype "shot"
:event/player1 "Rasmus Lindgren"
:event/sortorder 5
:event/team "home"
:event/id "event_5586836"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_15665"}

{:event/type "shoton"
:event/elapsed 55
:event/subtype "distance"
:event/player1 "Peter van Ooijen"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_5586906"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_15665"}

{:event/type "shotoff"
:event/elapsed 56
:event/subtype "distance"
:event/player1 "Jesper Drost"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5586948"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_15665"}

{:event/type "foulcommit"
:event/elapsed 59
:event/player2 "Joey Pelupessy"
:event/subtype "trip"
:event/player1 "Jesper Drost"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5587074"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Robin Gosens"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5587084"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_15665"}

{:event/type "shoton"
:event/elapsed 59
:event/subtype "header"
:event/player1 "Paul Gladon"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_5587088"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_15665"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player2 "Robin Gosens"
:event/subtype "pushing"
:event/player1 "Oussama Idrissi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5587122"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Oussama Idrissi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5587180"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_15665"}

{:event/type "shotoff"
:event/elapsed 62
:event/subtype "shot"
:event/player1 "Hedwiges Maduro"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5587187"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_15665"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Justin Hoogma"
:event/player1 "Michael de Leeuw"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5587228"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_15665"}

{:event/type "shoton"
:event/elapsed 64
:event/subtype "shot"
:event/player1 "Oussama Idrissi"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5587255"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_15665"}

{:event/type "corner"
:event/elapsed 64
:event/subtype "short_right"
:event/player1 "Albert Rusnak"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_5587261"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Oussama Idrissi"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5587289"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_15665"}

{:event/type "goal"
:event/elapsed 64
:event/player2 "Oussama Idrissi"
:event/subtype "shot"
:event/player1 "Rasmus Lindgren"
:event/sortorder 3
:event/team "home"
:event/id "event_5587268"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Iiass Bel Hassani"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5587320"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_15665"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Thomas Bruns"
:event/subtype "from_behind"
:event/player1 "Michael de Leeuw"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5587337"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_15665"}

{:event/type "shotoff"
:event/elapsed 67
:event/subtype "direct_freekick"
:event/player1 "Iiass Bel Hassani"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5587352"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Thomas Bruns"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5587373"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Oussama Idrissi"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5587395"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_15665"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Joey Pelupessy"
:event/subtype "trip"
:event/player1 "Oussama Idrissi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5587401"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_15665"}

{:event/type "goal"
:event/elapsed 70
:event/player2 "Thomas Bruns"
:event/subtype "shot"
:event/player1 "Iiass Bel Hassani"
:event/sortorder 1
:event/team "away"
:event/id "event_5587435"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_15665"}

{:event/type "shoton"
:event/elapsed 71
:event/subtype "shot"
:event/player1 "Jesper Drost"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_5587478"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_15665"}

{:event/type "corner"
:event/elapsed 72
:event/subtype "cross_left"
:event/player1 "Albert Rusnak"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5587485"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Hans Hateboer"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5587499"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_15665"}

{:event/type "shotoff"
:event/elapsed 74
:event/subtype "distance"
:event/player1 "Albert Rusnak"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5587566"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Iiass Bel Hassani"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5587581"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_15665"}

{:event/type "corner"
:event/elapsed 75
:event/subtype "cross_right"
:event/player1 "Iiass Bel Hassani"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_5587586"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Robin Gosens"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_5587605"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Robin Gosens"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5587693"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_15665"}

{:event/type "corner"
:event/elapsed 80
:event/subtype "short_right"
:event/player1 "Peter van Ooijen"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_5587776"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Iiass Bel Hassani"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_5587778"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_15665"}

{:event/type "shotoff"
:event/elapsed 84
:event/subtype "shot"
:event/player1 "Jesper Drost"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5587892"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Tarik Kada"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5587934"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_15665"}

{:event/type "shoton"
:event/elapsed 85
:event/subtype "blocked_shot"
:event/player1 "Iiass Bel Hassani"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_5587944"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_15665"}

{:event/type "corner"
:event/elapsed 85
:event/subtype "cross_left"
:event/player1 "Brahim Darri"
:event/sortorder 5
:event/team "away"
:event/event_type "corner"
:event/id "event_5587976"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_15665"}

{:event/type "shotoff"
:event/elapsed 86
:event/subtype "bicycle_kick"
:event/player1 "Tarik Kada"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5587987"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Wout Droste"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5588067"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Brahim Darri"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5588087"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Tarik Kada"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5588162"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_15665"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Wout Droste"
:event/player1 "Alexander Soerloth"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5588176"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Wouter Weghorst"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_5588187"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Tarik Kada"
:event/sortorder 7
:event/team "away"
:event/event_type "cross"
:event/id "event_5588225"
:event/minute 91
:event/match_id "match_15665"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Wouter Weghorst"
:event/sortorder 8
:event/team "away"
:event/event_type "shoton"
:event/id "event_5588229"
:event/minute 91
:event/match_id "match_15665"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Juninho Bacuna"
:event/sortorder 10
:event/team "home"
:event/event_type "cross"
:event/id "event_5588290"
:event/minute 92
:event/match_id "match_15665"}

{:event/type "corner"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "short_left"
:event/player1 "Jesper Drost"
:event/sortorder 12
:event/team "home"
:event/event_type "corner"
:event/id "event_5588313"
:event/minute 93
:event/match_id "match_15665"}


]

