
;;# data
[
{:match/id "match_6808"
:match/league "France Ligue 1"
:match/hometeam "SC Bastia"
:match/awayteam "Girondins de Bordeaux"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 28
:event/card_type "y"
:event/player1 "Drissa Diakite"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3220195"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_6808"}

{:event/type "goal"
:event/elapsed 42
:event/player1 "Adama Ba"
:event/sortorder 0
:event/team "home"
:event/id "event_3220208"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_6808"}

{:event/type "card"
:event/elapsed 79
:event/card_type "y"
:event/player1 "Yannick Cahuzac"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3220295"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_6808"}

{:event/type "card"
:event/elapsed 79
:event/card_type "y"
:event/player1 "Julien Faubert"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_3220296"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_6808"}


]

