
;;# data
[
{:match/id "match_3353"
:match/league "England Premier League"
:match/hometeam "Manchester United"
:match/awayteam "Newcastle United"
:match/score "5:2"
:match/hometeam_goals "4"
:match/awayteam_goals "3"}

{:event/type "foulcommit"
:event/elapsed 1
:event/player2 "James Perch"
:event/player1 "Robin van Persie"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2525273"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Vurnon Anita"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_2525280"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_3353"}

{:event/type "shoton"
:event/elapsed 4
:event/subtype "distance"
:event/player1 "Demba Ba"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_2525311"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_3353"}

{:event/type "goal"
:event/elapsed 4
:event/subtype "loose_ball"
:event/player1 "James Perch"
:event/sortorder 2
:event/team "away"
:event/id "event_2525312"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_3353"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Jonny Evans"
:event/player1 "Demba Ba"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2525338"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Javier Hernandez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2525362"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Chris Smalling"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2525375"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Danny Simpson"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2525432"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_3353"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Davide Santon"
:event/player1 "Antonio Valencia"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2525440"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_3353"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Demba Ba"
:event/player1 "Paul Scholes"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2525468"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_3353"}

{:event/type "shoton"
:event/elapsed 17
:event/subtype "blocked_shot"
:event/player1 "Demba Ba"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_2525477"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Gael Bigirimana"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_2525478"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_3353"}

{:event/type "shoton"
:event/elapsed 18
:event/subtype "header"
:event/player1 "Fabricio Coloccini"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_2525480"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3353"}

{:event/type "shoton"
:event/elapsed 18
:event/subtype "blocked_shot"
:event/player1 "Demba Ba"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_2525485"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3353"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Javier Hernandez"
:event/player1 "Mike Williamson"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2525499"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2525525"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_2525531"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Chris Smalling"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2525558"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_3353"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Antonio Valencia"
:event/player1 "Davide Santon"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2525575"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Robin van Persie"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2525581"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3353"}

{:event/type "shoton"
:event/elapsed 25
:event/subtype "blocked_shot"
:event/player1 "Javier Hernandez"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_2525583"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3353"}

{:event/type "goal"
:event/elapsed 25
:event/subtype "tap_in"
:event/player1 "Jonny Evans"
:event/sortorder 3
:event/team "home"
:event/id "event_2525586"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3353"}

{:event/type "shotoff"
:event/elapsed 26
:event/subtype "shot"
:event/player1 "Demba Ba"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2525597"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_3353"}

{:event/type "shoton"
:event/elapsed 28
:event/subtype "deflected"
:event/player1 "Danny Simpson"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_2525625"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_3353"}

{:event/type "goal"
:event/elapsed 29
:event/player1 "Jonny Evans"
:event/sortorder 0
:event/team "home"
:event/id "event_2525629"
:event/event_type "goal"
:event/goal_type "o"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_3353"}

{:event/type "shotoff"
:event/elapsed 32
:event/subtype "shot"
:event/player1 "Danny Simpson"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2525674"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_3353"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player1 "Mike Williamson"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2525684"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Robin van Persie"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2525687"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3353"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Mike Williamson"
:event/player1 "Ryan Giggs"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2525695"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Antonio Valencia"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2525697"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_3353"}

{:event/type "shoton"
:event/elapsed 34
:event/subtype "distance"
:event/player1 "Davide Santon"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_2525710"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_3353"}

{:event/type "foulcommit"
:event/elapsed 36
:event/subtype "hands"
:event/player1 "Jonny Evans"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2525725"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_3353"}

{:event/type "card"
:event/elapsed 36
:event/card_type "y"
:event/subtype "emergency_brake"
:event/player1 "Jonny Evans"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_2525728"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Sylvain Marveaux"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2525733"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Davide Santon"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_2525737"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_3353"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Sylvain Marveaux"
:event/player1 "Javier Hernandez"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2525760"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_3353"}

{:event/type "card"
:event/elapsed 38
:event/card_type "y"
:event/player1 "Javier Hernandez"
:event/sortorder 3
:event/team "home"
:event/event_type "card"
:event/id "event_2525763"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_3353"}

{:event/type "shotoff"
:event/elapsed 39
:event/subtype "crossbar"
:event/player1 "Sylvain Marveaux"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2525777"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "James Perch"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2525782"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Sylvain Marveaux"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2525786"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_3353"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Paul Scholes"
:event/player1 "Fabricio Coloccini"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2525790"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Antonio Valencia"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2525805"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3353"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Ryan Giggs"
:event/player1 "Mike Williamson"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2525831"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_3353"}

{:event/type "card"
:event/elapsed 43
:event/card_type "y"
:event/player1 "Mike Williamson"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_2525833"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_3353"}

{:event/type "shotoff"
:event/elapsed 44
:event/subtype "direct_freekick"
:event/player1 "Robin van Persie"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2525841"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_3353"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "Jonny Evans"
:event/player1 "Demba Ba"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2525869"
:event/minute 46
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Danny Simpson"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2525951"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_3353"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 45
:event/player2 "Rio Ferdinand"
:event/player1 "Demba Ba"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2525885"
:event/minute 47
:event/match_id "match_3353"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Chris Smalling"
:event/player1 "Demba Ba"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2525968"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2525981"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_3353"}

{:event/type "shotoff"
:event/elapsed 49
:event/subtype "volley"
:event/player1 "Robin van Persie"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2525982"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Davide Santon"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2526006"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Papiss Cisse"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_2526029"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_3353"}

{:event/type "shotoff"
:event/elapsed 52
:event/subtype "header"
:event/player1 "Demba Ba"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2526032"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Sylvain Marveaux"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2526036"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_3353"}

{:event/type "corner"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Sylvain Marveaux"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2526036"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Sylvain Marveaux"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_2526038"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_3353"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Danny Simpson"
:event/player1 "Antonio Valencia"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2526043"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_3353"}

{:event/type "card"
:event/elapsed 53
:event/card_type "y"
:event/player1 "Antonio Valencia"
:event/sortorder 5
:event/team "home"
:event/event_type "card"
:event/id "event_2526046"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "James Perch"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2526074"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Robin van Persie"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2526091"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3353"}

{:event/type "corner"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Robin van Persie"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2526091"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Robin van Persie"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_2526094"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3353"}

{:event/type "goal"
:event/elapsed 58
:event/subtype "distance"
:event/player1 "Patrice Evra"
:event/sortorder 4
:event/team "home"
:event/id "event_2526097"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3353"}

{:event/type "foulcommit"
:event/elapsed 59
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2526117"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Antonio Valencia"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2526118"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_3353"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player2 "Jonny Evans"
:event/subtype "dangerous_play"
:event/player1 "Danny Simpson"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2526133"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_3353"}

{:event/type "card"
:event/elapsed 61
:event/card_type "y"
:event/player1 "Danny Simpson"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2526138"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_3353"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Demba Ba"
:event/player1 "Ryan Giggs"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2526150"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Sylvain Marveaux"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2526157"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_3353"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Vurnon Anita"
:event/player1 "Robin van Persie"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2526166"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Vurnon Anita"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2526174"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Mike Williamson"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_2526178"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_2526183"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_3353"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Patrice Evra"
:event/player1 "Papiss Cisse"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2526189"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_3353"}

{:event/type "card"
:event/elapsed 64
:event/card_type "y"
:event/player1 "Papiss Cisse"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_2526191"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_3353"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Robin van Persie"
:event/player1 "Fabricio Coloccini"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2526195"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_2526207"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_3353"}

{:event/type "shotoff"
:event/elapsed 65
:event/subtype "deflected"
:event/player1 "Chris Smalling"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2526209"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Robin van Persie"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2526213"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_3353"}

{:event/type "corner"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Robin van Persie"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2526213"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_2526240"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Gabriel Obertan"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_2526256"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_3353"}

{:event/type "goal"
:event/elapsed 68
:event/player2 "Gabriel Obertan"
:event/subtype "volley"
:event/player1 "Papiss Cisse"
:event/sortorder 4
:event/team "away"
:event/id "event_2526257"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Antonio Valencia"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2526307"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3353"}

{:event/type "shoton"
:event/elapsed 71
:event/subtype "shot"
:event/player1 "Robin van Persie"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_2526309"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3353"}

{:event/type "goal"
:event/elapsed 71
:event/player2 "Michael Carrick"
:event/subtype "shot"
:event/player1 "Robin van Persie"
:event/sortorder 2
:event/team "home"
:event/id "event_2526310"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Danny Simpson"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2526329"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Vurnon Anita"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2526338"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3353"}

{:event/type "corner"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Vurnon Anita"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2526338"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2526356"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_3353"}

{:event/type "shotoff"
:event/elapsed 74
:event/subtype "miss_kick"
:event/player1 "Antonio Valencia"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2526359"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_3353"}

{:event/type "foulcommit"
:event/elapsed 74
:event/player2 "Davide Santon"
:event/player1 "Michael Carrick"
:event/sortorder 5
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2526363"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_3353"}

{:event/type "shoton"
:event/elapsed 75
:event/subtype "distance"
:event/player1 "Sylvain Marveaux"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_2526375"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Patrice Evra"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2526399"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_3353"}

{:event/type "shoton"
:event/elapsed 78
:event/subtype "blocked_shot"
:event/player1 "Javier Hernandez"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_2526423"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_3353"}

{:event/type "shotoff"
:event/elapsed 79
:event/subtype "big chance shot"
:event/player1 "Robin van Persie"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2526444"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Antonio Valencia"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_2526457"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_3353"}

{:event/type "shotoff"
:event/elapsed 80
:event/subtype "big chance header"
:event/player1 "Javier Hernandez"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2526458"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_3353"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Vurnon Anita"
:event/player1 "Robin van Persie"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2526469"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_3353"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Davide Santon"
:event/player1 "Antonio Valencia"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2526479"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_3353"}

{:event/type "shoton"
:event/elapsed 83
:event/subtype "shot"
:event/player1 "Gabriel Obertan"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_2526491"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_3353"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Patrice Evra"
:event/player1 "Mike Williamson"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2526500"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_2526504"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Tom Cleverley"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_2526507"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_3353"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Javier Hernandez"
:event/subtype "trip"
:event/player1 "Sammy Ameobi"
:event/sortorder 6
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2526510"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Robin van Persie"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2526512"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_3353"}

{:event/type "shotoff"
:event/elapsed 85
:event/subtype "big chance post"
:event/player1 "Sammy Ameobi"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2526519"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Antonio Valencia"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_2526531"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Michael Carrick"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_2526537"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3353"}

{:event/type "shoton"
:event/elapsed 87
:event/subtype "big chance header"
:event/player1 "Javier Hernandez"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_2526553"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_3353"}

{:event/type "shoton"
:event/elapsed 88
:event/subtype "header"
:event/player1 "Shola Ameobi"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_2526576"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Tom Cleverley"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2526582"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_3353"}

{:event/type "shotoff"
:event/elapsed 89
:event/subtype "big chance header"
:event/player1 "Robin van Persie"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2526590"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Patrice Evra"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2526624"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3353"}

{:event/type "goal"
:event/elapsed 90
:event/player2 "Michael Carrick"
:event/subtype "tap_in"
:event/player1 "Javier Hernandez"
:event/sortorder 4
:event/team "home"
:event/id "event_2526630"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Fabricio Coloccini"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2526668"
:event/minute 93
:event/match_id "match_3353"}

{:event/type "foulcommit"
:event/elapsed_plus 4
:event/elapsed 90
:event/player1 "Shola Ameobi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2526677"
:event/minute 94
:event/match_id "match_3353"}

{:event/type "foulcommit"
:event/elapsed_plus 5
:event/elapsed 90
:event/player2 "Vurnon Anita"
:event/player1 "Antonio Valencia"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2526690"
:event/minute 95
:event/match_id "match_3353"}

{:event/type "cross"
:event/elapsed_plus 8
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Davide Santon"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_2526704"
:event/minute 98
:event/match_id "match_3353"}

{:event/type "shotoff"
:event/elapsed_plus 8
:event/elapsed 90
:event/subtype "bad shot"
:event/player1 "Danny Simpson"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2526705"
:event/minute 98
:event/match_id "match_3353"}

{:event/type "foulcommit"
:event/elapsed_plus 9
:event/elapsed 90
:event/player2 "Robin van Persie"
:event/player1 "Fabricio Coloccini"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2526708"
:event/minute 99
:event/match_id "match_3353"}


]

