
;;# data
[
{:match/id "match_11323"
:match/league "Italy Serie A"
:match/hometeam "Cesena"
:match/awayteam "Brescia"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 6
:event/card_type "y"
:event/player1 "Felipe"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1554683"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_11323"}

{:event/type "card"
:event/elapsed 16
:event/card_type "y"
:event/player1 "Perparim Hetemaj"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1554851"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_11323"}

{:event/type "card"
:event/elapsed 19
:event/card_type "y"
:event/player1 "Fabio Caserta"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1554852"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_11323"}

{:event/type "card"
:event/elapsed 25
:event/card_type "y"
:event/player1 "Davide Zoboli"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1554929"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_11323"}

{:event/type "goal"
:event/elapsed 60
:event/player1 "Emanuele Giaccherini"
:event/sortorder 0
:event/team "home"
:event/id "event_1555486"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_11323"}

{:event/type "card"
:event/elapsed 74
:event/card_type "y"
:event/player1 "Panagiotis Kone"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1555705"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_11323"}


]

