
;;# data
[
{:match/id "match_3521"
:match/league "England Premier League"
:match/hometeam "Manchester United"
:match/awayteam "Aston Villa"
:match/score "3:0"
:match/hometeam_goals "3"
:match/awayteam_goals "0"}

{:event/type "foulcommit"
:event/elapsed 1
:event/player2 "Ashley R. Westwood"
:event/player1 "Wayne Rooney"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2719437"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_3521"}

{:event/type "foulcommit"
:event/elapsed 1
:event/player2 "Rafael"
:event/player1 "Gabriel Agbonlahor"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2719438"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Rafael"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2719439"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_3521"}

{:event/type "goal"
:event/elapsed 2
:event/player2 "Ryan Giggs"
:event/subtype "tap_in"
:event/player1 "Robin van Persie"
:event/sortorder 2
:event/team "home"
:event/id "event_2719441"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Antonio Valencia"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2719442"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_3521"}

{:event/type "shotoff"
:event/elapsed 3
:event/subtype "big chance volley"
:event/player1 "Robin van Persie"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2719443"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Matthew Lowton"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2719446"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_3521"}

{:event/type "shoton"
:event/elapsed 4
:event/subtype "blocked_shot"
:event/player1 "Andreas Weimann"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_2719447"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Rafael"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2719450"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_3521"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Rafael"
:event/player1 "Fabian Delph"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2719454"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_2719455"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Andreas Weimann"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2719458"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2719462"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Wayne Rooney"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_2719468"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_3521"}

{:event/type "shotoff"
:event/elapsed 10
:event/subtype "post"
:event/player1 "Rafael"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2719470"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Antonio Valencia"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_2719471"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Patrice Evra"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2719474"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_3521"}

{:event/type "shotoff"
:event/elapsed 12
:event/subtype "shot"
:event/player1 "Christian Benteke"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2719479"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_3521"}

{:event/type "goal"
:event/elapsed 13
:event/player2 "Wayne Rooney"
:event/subtype "volley"
:event/player1 "Robin van Persie"
:event/sortorder 1
:event/team "home"
:event/id "event_2719482"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_3521"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Gabriel Agbonlahor"
:event/player1 "Rafael"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2719486"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Joseph Bennett"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2719487"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_3521"}

{:event/type "shoton"
:event/elapsed 15
:event/subtype "distance"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_2719488"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Patrice Evra"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2719489"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_3521"}

{:event/type "shotoff"
:event/elapsed 16
:event/subtype "distance"
:event/player1 "Michael Carrick"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2719493"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_3521"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Rafael"
:event/player1 "Gabriel Agbonlahor"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2719498"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3521"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Gabriel Agbonlahor"
:event/subtype "from_behind"
:event/player1 "Ryan Giggs"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2719499"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Joseph Bennett"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2719509"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Antonio Valencia"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_2719513"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Joseph Bennett"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2719520"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_3521"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Charles N'Zogbia"
:event/subtype "trip"
:event/player1 "Patrice Evra"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2719523"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_3521"}

{:event/type "card"
:event/elapsed 28
:event/card_type "y"
:event/subtype "emergency_brake"
:event/player1 "Patrice Evra"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2719524"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Ashley R. Westwood"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2719527"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_3521"}

{:event/type "foulcommit"
:event/elapsed 30
:event/player2 "Antonio Valencia"
:event/player1 "Joseph Bennett"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2719530"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Charles N'Zogbia"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_2719535"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_3521"}

{:event/type "corner"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Charles N'Zogbia"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_2719535"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_3521"}

{:event/type "shoton"
:event/elapsed 31
:event/subtype "blocked_shot"
:event/player1 "Fabian Delph"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_2719536"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Ashley R. Westwood"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_2719537"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Charles N'Zogbia"
:event/sortorder 5
:event/team "away"
:event/event_type "cross"
:event/id "event_2719538"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_3521"}

{:event/type "shotoff"
:event/elapsed 32
:event/subtype "miss_kick"
:event/player1 "Andreas Weimann"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2719539"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_3521"}

{:event/type "goal"
:event/elapsed 33
:event/player2 "Ryan Giggs"
:event/subtype "shot"
:event/player1 "Robin van Persie"
:event/sortorder 3
:event/team "home"
:event/id "event_2719543"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3521"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Charles N'Zogbia"
:event/player1 "Patrice Evra"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2719552"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Ashley R. Westwood"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2719553"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Patrice Evra"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2719556"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2719558"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3521"}

{:event/type "shotoff"
:event/elapsed 42
:event/subtype "shot"
:event/player1 "Gabriel Agbonlahor"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2719561"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Matthew Lowton"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2719563"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_3521"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Gabriel Agbonlahor"
:event/player1 "Antonio Valencia"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2719566"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_3521"}

{:event/type "shotoff"
:event/elapsed 45
:event/subtype "bad shot"
:event/player1 "Ron Vlaar"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2719570"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_3521"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "Joseph Bennett"
:event/player1 "Antonio Valencia"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2719574"
:event/minute 46
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2719592"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_3521"}

{:event/type "corner"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2719592"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_2719594"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2719596"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_3521"}

{:event/type "corner"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2719596"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_3521"}

{:event/type "shotoff"
:event/elapsed 48
:event/subtype "shot"
:event/player1 "Wayne Rooney"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2719597"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Andreas Weimann"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2719599"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Ashley R. Westwood"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2719602"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_3521"}

{:event/type "corner"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Ashley R. Westwood"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_2719602"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_3521"}

{:event/type "shoton"
:event/elapsed 50
:event/subtype "big chance header"
:event/player1 "Andreas Weimann"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_2719604"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Fabian Delph"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_2719605"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Andreas Weimann"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_2719609"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_3521"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Matthew Lowton"
:event/player1 "Patrice Evra"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2719611"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_3521"}

{:event/type "shoton"
:event/elapsed 53
:event/subtype "shot"
:event/player1 "Christian Benteke"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_2719614"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Karim El Ahmadi"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2719618"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Karim El Ahmadi"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2719621"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Matthew Lowton"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_2719623"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_3521"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Jonny Evans"
:event/player1 "Gabriel Agbonlahor"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2719626"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3521"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Robin van Persie"
:event/subtype "pushing"
:event/player1 "Nathan Baker"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2719629"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Antonio Valencia"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_2719632"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Antonio Valencia"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_2719636"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3521"}

{:event/type "shoton"
:event/elapsed 63
:event/subtype "blocked_shot"
:event/player1 "Wayne Rooney"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_2719638"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3521"}

{:event/type "shotoff"
:event/elapsed 64
:event/subtype "shot"
:event/player1 "Wayne Rooney"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2719641"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_3521"}

{:event/type "shotoff"
:event/elapsed 67
:event/subtype "shot"
:event/player1 "Andreas Weimann"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2719646"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3521"}

{:event/type "shoton"
:event/elapsed 70
:event/subtype "blocked_shot"
:event/player1 "Shinji Kagawa"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_2719652"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2719653"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Wayne Rooney"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2719654"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3521"}

{:event/type "corner"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Wayne Rooney"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2719654"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3521"}

{:event/type "shoton"
:event/elapsed 71
:event/subtype "shot"
:event/player1 "Jonny Evans"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_2719655"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3521"}

{:event/type "foulcommit"
:event/elapsed 72
:event/player2 "Gabriel Agbonlahor"
:event/player1 "Rafael"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2719656"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Robin van Persie"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2719661"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3521"}

{:event/type "shoton"
:event/elapsed 75
:event/subtype "volley"
:event/player1 "Karim El Ahmadi"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_2719663"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Ashley R. Westwood"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_2719665"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3521"}

{:event/type "corner"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Ashley R. Westwood"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_2719665"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Fabian Delph"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2719666"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Matthew Lowton"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_2719668"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3521"}

{:event/type "shotoff"
:event/elapsed 77
:event/subtype "big chance shot"
:event/player1 "Shinji Kagawa"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2719672"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Antonio Valencia"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2719683"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_3521"}

{:event/type "foulcommit"
:event/elapsed 87
:event/player2 "Fabian Delph"
:event/player1 "Phil Jones"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2719687"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_3521"}

{:event/type "shoton"
:event/elapsed 88
:event/subtype "direct_freekick"
:event/player1 "Karim El Ahmadi"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_2719688"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Rafael"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2719689"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_3521"}

{:event/type "corner"
:event/elapsed 89
:event/subtype "short"
:event/player1 "Ryan Giggs"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2719691"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Rafael"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2719692"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2719694"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_3521"}

{:event/type "corner"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2719694"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Michael Carrick"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_2719695"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Antonio Valencia"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2719698"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3521"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Rafael"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2719703"
:event/minute 92
:event/match_id "match_3521"}


]

