
;;# data
[
{:match/id "match_11683"
:match/league "Italy Serie A"
:match/hometeam "Bologna"
:match/awayteam "Napoli"
:match/score "2:0"
:match/hometeam_goals "2"
:match/awayteam_goals "0"}

{:event/type "goal"
:event/elapsed 17
:event/player1 "Alessandro Diamanti"
:event/sortorder 0
:event/team "home"
:event/id "event_2121410"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_11683"}

{:event/type "card"
:event/elapsed 42
:event/card_type "y"
:event/player1 "Simone Loria"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2121818"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_11683"}

{:event/type "card"
:event/elapsed 44
:event/card_type "y"
:event/player1 "Walter Gargano"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2121843"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_11683"}

{:event/type "card"
:event/elapsed 58
:event/card_type "y"
:event/player1 "Nicolo Cherubin"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2122472"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_11683"}

{:event/type "card"
:event/elapsed 61
:event/card_type "y"
:event/player1 "Miguel Britos"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2122474"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_11683"}

{:event/type "goal"
:event/elapsed 64
:event/player1 "Matteo Rubin"
:event/sortorder 0
:event/team "home"
:event/id "event_2122471"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_11683"}

{:event/type "card"
:event/elapsed 66
:event/card_type "y"
:event/player1 "Matteo Rubin"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2122473"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_11683"}

{:event/type "card"
:event/elapsed 74
:event/card_type "y"
:event/player1 "Paolo Cannavaro"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2122758"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_11683"}

{:event/type "card"
:event/elapsed 83
:event/card_type "y"
:event/player1 "Edinson Cavani"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2122768"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_11683"}

{:event/type "card"
:event/elapsed 84
:event/card_type "y"
:event/player1 "Blerim Dzemaili"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2122771"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_11683"}

{:event/type "card"
:event/elapsed 86
:event/card_type "y"
:event/player1 "Salvatore Aronica"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2122961"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_11683"}

{:event/type "card"
:event/elapsed 90
:event/card_type "r"
:event/player1 "Blerim Dzemaili"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2122892"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_11683"}

{:event/type "card"
:event/elapsed 90
:event/card_type "r"
:event/player1 "Archimede Morleo"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2122960"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_11683"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Juan Camilo Zuniga"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2122962"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_11683"}


]

