
;;# data
[
{:match/id "match_2685"
:match/league "England Premier League"
:match/hometeam "Birmingham City"
:match/awayteam "Stoke City"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Danny Pugh"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1404215"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Sebastian Larsson"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1404228"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_2685"}

{:event/type "shotoff"
:event/elapsed 4
:event/subtype "header"
:event/player1 "Nikola Zigic"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1404229"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Rory Delap"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1404261"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "David Bentley"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1404277"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Sebastian Larsson"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_1404279"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Sebastian Larsson"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1404289"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_2685"}

{:event/type "corner"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Sebastian Larsson"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1404289"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "David Bentley"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1404315"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Jonathan Walters"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1404341"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/sortorder 2
:event/team "away"
:event/event_type "throwin"
:event/id "event_1404348"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_2685"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Jermaine Pennant"
:event/player1 "David Bentley"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1404363"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_2685"}

{:event/type "shoton"
:event/elapsed 12
:event/subtype "direct_freekick"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1404372"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_2685"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Danny Pugh"
:event/player1 "Nikola Zigic"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1404386"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_2685"}

{:event/type "shotoff"
:event/elapsed 13
:event/subtype "header"
:event/player1 "John Carew"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1404398"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_2685"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Dean Whitehead"
:event/subtype "pushing"
:event/player1 "Craig Gardner"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1404416"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_2685"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "Sebastian Larsson"
:event/subtype "from_behind"
:event/player1 "Danny Pugh"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1404455"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_2685"}

{:event/type "shoton"
:event/elapsed 17
:event/subtype "header"
:event/player1 "Liam Ridgewell"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1404476"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Kenwyne Jones"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1404509"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Stephen Carr"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1404533"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_2685"}

{:event/type "foulcommit"
:event/elapsed 21
:event/subtype "hands"
:event/player1 "Nikola Zigic"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1404554"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_2685"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Nikola Zigic"
:event/subtype "pushing"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1404634"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_2685"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Robert Huth"
:event/player1 "Craig Gardner"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1404653"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_2685"}

{:event/type "shoton"
:event/elapsed 28
:event/subtype "big chance blocked"
:event/player1 "Kenwyne Jones"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_1404657"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_2685"}

{:event/type "shotoff"
:event/elapsed 28
:event/subtype "deflected"
:event/player1 "Kenwyne Jones"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1404662"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_2685"}

{:event/type "corner"
:event/elapsed 29
:event/subtype "short"
:event/player1 "Jermaine Pennant"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1404671"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2685"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Jermaine Pennant"
:event/subtype "serious_foul"
:event/player1 "Sebastian Larsson"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1404674"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2685"}

{:event/type "shotoff"
:event/elapsed 30
:event/subtype "direct_freekick"
:event/player1 "Jermaine Pennant"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1404692"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_2685"}

{:event/type "foulcommit"
:event/elapsed 31
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1404717"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_2685"}

{:event/type "shoton"
:event/elapsed 32
:event/subtype "distance"
:event/player1 "Craig Gardner"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1404733"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_2685"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Nikola Zigic"
:event/subtype "pushing"
:event/player1 "Robert Huth"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1404745"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_2685"}

{:event/type "shotoff"
:event/elapsed 34
:event/subtype "distance"
:event/player1 "Rory Delap"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1404768"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_2685"}

{:event/type "shoton"
:event/elapsed 37
:event/subtype "shot"
:event/player1 "Kenwyne Jones"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1404824"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Liam Ridgewell"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1404857"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "David Bentley"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1404858"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_2685"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Obafemi Martins"
:event/player1 "Rory Delap"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1404873"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_2685"}

{:event/type "shotoff"
:event/elapsed 41
:event/subtype "distance"
:event/player1 "David Bentley"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1404902"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_2685"}

{:event/type "foulcommit"
:event/elapsed 42
:event/subtype "pushing"
:event/player1 "Ryan Shawcross"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1404918"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_2685"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Obafemi Martins"
:event/subtype "pushing"
:event/player1 "Robert Huth"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1404942"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "David Bentley"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1404951"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_2685"}

{:event/type "foulcommit"
:event/elapsed 44
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1404955"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_2685"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Martin Jiranek"
:event/subtype "pushing"
:event/player1 "Kenwyne Jones"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1404972"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Jonathan Walters"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1404981"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1404998"
:event/minute 46
:event/match_id "match_2685"}

{:event/type "corner"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1404998"
:event/minute 46
:event/match_id "match_2685"}

{:event/type "foulcommit"
:event/elapsed 46
:event/subtype "pushing"
:event/player1 "Craig Gardner"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1405125"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_2685"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "volley"
:event/player1 "John Carew"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_1405011"
:event/minute 46
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1405139"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_2685"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Barry Ferguson"
:event/player1 "Kenwyne Jones"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1405156"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Craig Gardner"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1405158"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Sebastian Larsson"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1405163"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_2685"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Roger Johnson"
:event/player1 "John Carew"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1405171"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Sebastian Larsson"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1405198"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_2685"}

{:event/type "shotoff"
:event/elapsed 55
:event/subtype "big chance shot"
:event/player1 "Sebastian Larsson"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1405271"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1405301"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1405309"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_2685"}

{:event/type "corner"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1405309"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "John Carew"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1405325"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_2685"}

{:event/type "shotoff"
:event/elapsed 59
:event/subtype "shot"
:event/player1 "John Carew"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1405350"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_2685"}

{:event/type "corner"
:event/elapsed 61
:event/subtype "short"
:event/player1 "Sebastian Larsson"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1405383"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Sebastian Larsson"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1405387"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_2685"}

{:event/type "shoton"
:event/elapsed 63
:event/subtype "blocked_shot"
:event/player1 "Kenwyne Jones"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1405420"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_2685"}

{:event/type "shotoff"
:event/elapsed 63
:event/subtype "volley"
:event/player1 "Kenwyne Jones"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1405423"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_1405445"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_2685"}

{:event/type "shotoff"
:event/elapsed 65
:event/subtype "big chance volley"
:event/player1 "Robert Huth"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1405454"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1405488"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_2685"}

{:event/type "shoton"
:event/elapsed 67
:event/subtype "big chance blocked"
:event/player1 "David Bentley"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1405491"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_2685"}

{:event/type "corner"
:event/elapsed 67
:event/subtype "short"
:event/player1 "Jermaine Pennant"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1405496"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_2685"}

{:event/type "shotoff"
:event/elapsed 68
:event/subtype "bad shot"
:event/player1 "Marc Wilson"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1405500"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_2685"}

{:event/type "foulcommit"
:event/elapsed 70
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1405529"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_2685"}

{:event/type "shotoff"
:event/elapsed 70
:event/subtype "direct_freekick"
:event/player1 "Jermaine Pennant"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1405533"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_2685"}

{:event/type "foulcommit"
:event/elapsed 72
:event/player2 "Barry Ferguson"
:event/subtype "pushing"
:event/player1 "John Carew"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1405548"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_2685"}

{:event/type "shoton"
:event/elapsed 72
:event/subtype "shot"
:event/player1 "John Carew"
:event/sortorder 4
:event/team "away"
:event/event_type "shoton"
:event/id "event_1405553"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_2685"}

{:event/type "foulcommit"
:event/elapsed 74
:event/subtype "serious_foul"
:event/player1 "Martin Jiranek"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1405570"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_2685"}

{:event/type "card"
:event/elapsed 74
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Martin Jiranek"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_1405571"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1405588"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_2685"}

{:event/type "corner"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Jermaine Pennant"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1405588"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_2685"}

{:event/type "foulcommit"
:event/elapsed 75
:event/subtype "pushing"
:event/player1 "Robert Huth"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1405593"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_2685"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Danny Pugh"
:event/player1 "Stephen Carr"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1405613"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_2685"}

{:event/type "shotoff"
:event/elapsed 78
:event/subtype "distance"
:event/player1 "Cameron Jerome"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1405630"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Cameron Jerome"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1405665"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_2685"}

{:event/type "shotoff"
:event/elapsed 81
:event/subtype "distance"
:event/player1 "Roger Johnson"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1405667"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Stephen Carr"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1405711"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_1405728"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_1405733"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_2685"}

{:event/type "foulcommit"
:event/elapsed 88
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1405772"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_1405805"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Glenn Whelan"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1405818"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_2685"}

{:event/type "corner"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Glenn Whelan"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_1405818"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Glenn Whelan"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_1405820"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_2685"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Nikola Zigic"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1405827"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Cameron Jerome"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1405830"
:event/minute 91
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Sebastian Larsson"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1405831"
:event/minute 91
:event/match_id "match_2685"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1405856"
:event/minute 93
:event/match_id "match_2685"}

{:event/type "shoton"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "shot"
:event/player1 "David Bentley"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_1405865"
:event/minute 93
:event/match_id "match_2685"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Cameron Jerome"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_1405866"
:event/minute 93
:event/match_id "match_2685"}

{:event/type "goal"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Cameron Jerome"
:event/subtype "header"
:event/player1 "Nikola Zigic"
:event/sortorder 6
:event/team "home"
:event/id "event_1405863"
:event/event_type "goal"
:event/goal_type "n"
:event/minute 93
:event/match_id "match_2685"}


]

