
;;# data
[
{:match/id "match_3979"
:match/league "England Premier League"
:match/hometeam "Cardiff City"
:match/awayteam "Newcastle United"
:match/score "1:2"
:match/hometeam_goals "1"
:match/awayteam_goals "2"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Davide Santon"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3043735"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_3979"}

{:event/type "shoton"
:event/elapsed 5
:event/subtype "blocked_shot"
:event/player1 "Papiss Cisse"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_3043736"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_3979"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Peter Odemwingie"
:event/player1 "Davide Santon"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3043769"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_3979"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Peter Odemwingie"
:event/player1 "Moussa Sissoko"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3043784"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3979"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Mathieu Debuchy"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3043792"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_3979"}

{:event/type "shotoff"
:event/elapsed 11
:event/subtype "distance"
:event/player1 "Papiss Cisse"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3043801"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_3979"}

{:event/type "shotoff"
:event/elapsed 12
:event/subtype "bad shot"
:event/player1 "Yoan Gouffran"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3043811"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_3979"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Kevin Theophile-Catherine"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3043828"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_3979"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Bo-Kyung Kim"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3043829"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_3979"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Loic Remy"
:event/player1 "Aron Gunnarsson"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3043865"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_3979"}

{:event/type "shoton"
:event/elapsed 18
:event/subtype "big chance shot"
:event/player1 "Loic Remy"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3043876"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3979"}

{:event/type "shoton"
:event/elapsed 18
:event/subtype "big chance blocked"
:event/player1 "Papiss Cisse"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_3043878"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3979"}

{:event/type "shoton"
:event/elapsed 18
:event/subtype "distance"
:event/player1 "Moussa Sissoko"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_3043890"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3979"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3043881"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_3979"}

{:event/type "corner"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3043881"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_3979"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Cheik Tiote"
:event/player1 "Peter Odemwingie"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3043884"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_3979"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3043894"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_3979"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Aron Gunnarsson"
:event/player1 "Cheik Tiote"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3043983"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_3979"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Peter Whittingham"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3044024"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3979"}

{:event/type "corner"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Peter Whittingham"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3044024"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3979"}

{:event/type "shoton"
:event/elapsed 27
:event/subtype "blocked_shot"
:event/player1 "Yoan Gouffran"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3044039"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_3979"}

{:event/type "shotoff"
:event/elapsed 28
:event/subtype "distance"
:event/player1 "Gary Medel"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3044042"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_3979"}

{:event/type "shoton"
:event/elapsed 28
:event/subtype "blocked_shot"
:event/player1 "Papiss Cisse"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_3044054"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_3979"}

{:event/type "shotoff"
:event/elapsed 30
:event/subtype "shot"
:event/player1 "Bo-Kyung Kim"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3043979"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_3979"}

{:event/type "goal"
:event/elapsed 30
:event/player2 "Moussa Sissoko"
:event/subtype "shot"
:event/player1 "Loic Remy"
:event/sortorder 2
:event/team "away"
:event/id "event_3044001"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_3979"}

{:event/type "shoton"
:event/elapsed 33
:event/subtype "distance"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3044026"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3979"}

{:event/type "shoton"
:event/elapsed 36
:event/subtype "blocked_shot"
:event/player1 "Fraizer Campbell"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3044070"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_3979"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Yohan Cabaye"
:event/player1 "Gary Medel"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3044075"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_3979"}

{:event/type "shoton"
:event/elapsed 37
:event/subtype "shot"
:event/player1 "Papiss Cisse"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_3044088"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_3979"}

{:event/type "goal"
:event/elapsed 38
:event/subtype "shot"
:event/player1 "Loic Remy"
:event/sortorder 4
:event/team "away"
:event/id "event_3044089"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_3979"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Gary Medel"
:event/player1 "Papiss Cisse"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3044100"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_3979"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Peter Whittingham"
:event/player1 "Yoan Gouffran"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3044108"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3979"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Peter Whittingham"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3044114"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3979"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Mathieu Debuchy"
:event/player1 "Peter Whittingham"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3044120"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_3979"}

{:event/type "shotoff"
:event/elapsed 43
:event/subtype "post"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3044127"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_3979"}

{:event/type "shotoff"
:event/elapsed 43
:event/subtype "bad shot"
:event/player1 "Cheik Tiote"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3044129"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_3979"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Yohan Cabaye"
:event/player1 "Gary Medel"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3044153"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_3979"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3044355"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_3979"}

{:event/type "corner"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3044355"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_3979"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Peter Whittingham"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3044166"
:event/minute 47
:event/match_id "match_3979"}

{:event/type "shoton"
:event/elapsed 47
:event/subtype "distance"
:event/player1 "Yohan Cabaye"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_3044271"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_3979"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Yohan Cabaye"
:event/subtype "dangerous_play"
:event/player1 "Gary Medel"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3044279"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_3979"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Peter Whittingham"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3044329"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3979"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Peter Whittingham"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3044334"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3979"}

{:event/type "corner"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Peter Whittingham"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3044334"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3979"}

{:event/type "shotoff"
:event/elapsed 51
:event/subtype "header"
:event/player1 "Jordon Mutch"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3044339"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3979"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Jordon Mutch"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3044390"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3979"}

{:event/type "shotoff"
:event/elapsed 55
:event/subtype "volley"
:event/player1 "Peter Whittingham"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3044392"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3979"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Yoan Gouffran"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3044426"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_3979"}

{:event/type "goal"
:event/elapsed 58
:event/player2 "Jordon Mutch"
:event/subtype "shot"
:event/player1 "Peter Odemwingie"
:event/sortorder 3
:event/team "home"
:event/id "event_3044460"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3979"}

{:event/type "shotoff"
:event/elapsed 60
:event/subtype "shot"
:event/player1 "Fraizer Campbell"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3044486"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_3979"}

{:event/type "foulcommit"
:event/elapsed 62
:event/subtype "hands"
:event/player1 "Kevin Theophile-Catherine"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3044506"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_3979"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Aron Gunnarsson"
:event/player1 "Yohan Cabaye"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3044518"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_3979"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Peter Whittingham"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3044532"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3979"}

{:event/type "corner"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Peter Whittingham"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3044532"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3979"}

{:event/type "shoton"
:event/elapsed 64
:event/subtype "big chance shot"
:event/player1 "Moussa Sissoko"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_3044544"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_3979"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Peter Whittingham"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3044566"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_3979"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Mathieu Debuchy"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3044607"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3979"}

{:event/type "shoton"
:event/elapsed 67
:event/subtype "blocked_shot"
:event/player1 "Yohan Cabaye"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_3044612"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3979"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Davide Santon"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_3044615"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3979"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Aron Gunnarsson"
:event/player1 "Cheik Tiote"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3044667"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_3979"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3044714"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3979"}

{:event/type "corner"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3044714"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3979"}

{:event/type "shotoff"
:event/elapsed 73
:event/subtype "header"
:event/player1 "Jonas Gutierrez"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3044719"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3979"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Mathieu Debuchy"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3044732"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_3979"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Kevin Theophile-Catherine"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3044751"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3979"}

{:event/type "shoton"
:event/elapsed 76
:event/subtype "shot"
:event/player1 "Craig Bellamy"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3044769"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3979"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Kevin Theophile-Catherine"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3044799"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_3979"}

{:event/type "foulcommit"
:event/elapsed 79
:event/player2 "Cheik Tiote"
:event/player1 "Gary Medel"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3044812"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_3979"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Kevin Theophile-Catherine"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3044828"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_3979"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Davide Santon"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3044840"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_3979"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Peter Whittingham"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3044862"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_3979"}

{:event/type "shoton"
:event/elapsed 84
:event/subtype "lob"
:event/player1 "Jordon Mutch"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3044888"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_3979"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Yohan Cabaye"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3044896"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_3979"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Davide Santon"
:event/player1 "unknown"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3044911"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3979"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Craig Bellamy"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3044949"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_3979"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Craig Bellamy"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3044973"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3979"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Hatem Ben Arfa"
:event/player1 "Aron Gunnarsson"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3044977"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3979"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Aron Gunnarsson"
:event/sortorder 3
:event/team "home"
:event/event_type "card"
:event/id "event_3044981"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3979"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Cheik Tiote"
:event/player1 "Aron Gunnarsson"
:event/sortorder 8
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3045003"
:event/minute 91
:event/match_id "match_3979"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Kevin Theophile-Catherine"
:event/subtype "pushing"
:event/player1 "Hatem Ben Arfa"
:event/sortorder 9
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3045009"
:event/minute 92
:event/match_id "match_3979"}

{:event/type "shotoff"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Kevin Theophile-Catherine"
:event/sortorder 12
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3045037"
:event/minute 95
:event/match_id "match_3979"}


]

