
;;# data
[
{:match/id "match_10758"
:match/league "Italy Serie A"
:match/hometeam "Sampdoria"
:match/awayteam "Catania"
:match/score "1:1"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "goal"
:event/elapsed 14
:event/player1 "Cristian Llama"
:event/sortorder 0
:event/team "away"
:event/id "event_913585"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_10758"}

{:event/type "goal"
:event/elapsed 45
:event/player1 "Giampaolo Pazzini"
:event/sortorder 0
:event/team "home"
:event/id "event_913933"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_10758"}

{:event/type "card"
:event/elapsed 45
:event/card_type "y"
:event/player1 "Matias Silvestre"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_914121"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_10758"}

{:event/type "card"
:event/elapsed 50
:event/card_type "y"
:event/player1 "Marco Rossi"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_914119"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_10758"}

{:event/type "card"
:event/elapsed 60
:event/card_type "y"
:event/player1 "Marco Padalino"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_914283"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_10758"}

{:event/type "card"
:event/elapsed 67
:event/card_type "y"
:event/player1 "Adrian Ricchiuti"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_914386"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_10758"}

{:event/type "card"
:event/elapsed 73
:event/card_type "y"
:event/player1 "Pablo Martin Ledesma"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_914413"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_10758"}

{:event/type "card"
:event/elapsed 86
:event/card_type "y"
:event/player1 "Andrea Poli"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_914569"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_10758"}


]

