
;;# data
[
{:match/id "match_6507"
:match/league "France Ligue 1"
:match/hometeam "FC Sochaux-Montbéliard"
:match/awayteam "Valenciennes FC"
:match/score "1:1"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "goal"
:event/elapsed 8
:event/player1 "Ryad Boudebouz"
:event/sortorder 0
:event/team "home"
:event/id "event_2652866"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_6507"}

{:event/type "card"
:event/elapsed 56
:event/card_type "y"
:event/player1 "Nicolas Issimat Mirin"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2652977"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_6507"}

{:event/type "card"
:event/elapsed 66
:event/card_type "y"
:event/player1 "Lindsay Rose"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2653008"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_6507"}

{:event/type "card"
:event/elapsed 72
:event/card_type "y"
:event/player1 "Cedric Kante"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2653007"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_6507"}

{:event/type "goal"
:event/elapsed 82
:event/player1 "Opa Nguette"
:event/sortorder 0
:event/team "away"
:event/id "event_2653006"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_6507"}


]

