
;;# data
[
{:match/id "match_6514"
:match/league "France Ligue 1"
:match/hometeam "Stade de Reims"
:match/awayteam "FC Sochaux-Montbéliard"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 23
:event/card_type "y"
:event/player1 "Ishmael Yartey"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2305362"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_6514"}

{:event/type "card"
:event/elapsed 30
:event/card_type "y"
:event/player1 "Sebastien Corchia"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2305371"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_6514"}

{:event/type "card"
:event/elapsed 37
:event/card_type "y"
:event/player1 "Sebastien Corchia"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2305372"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_6514"}

{:event/type "goal"
:event/elapsed 90
:event/player1 "Grzegorz Krychowiak"
:event/sortorder 0
:event/team "home"
:event/id "event_2305566"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_6514"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Carlao"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2305573"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_6514"}


]

