
;;# data
[
{:match/id "match_22350"
:match/league "Spain LIGA BBVA"
:match/hometeam "Real Madrid CF"
:match/awayteam "Sevilla FC"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "foulcommit"
:event/elapsed 1
:event/player2 "Sergio Ramos"
:event/subtype "pushing"
:event/player1 "Romaric"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1339388"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_22350"}

{:event/type "shoton"
:event/elapsed 2
:event/subtype "shot"
:event/player1 "Abdoulay Konko"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_1339391"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_22350"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Diego Capel"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1339392"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_22350"}

{:event/type "corner"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Diego Capel"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1339392"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Karim Benzema"
:event/subtype "pushing"
:event/player1 "Fernando Navarro"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1339394"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_22350"}

{:event/type "shoton"
:event/elapsed 6
:event/subtype "direct_freekick"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1339395"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 6
:event/player2 "Andres Palop"
:event/subtype "pushing"
:event/player1 "Karim Benzema"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1339396"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_22350"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Angel Di Maria"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1339399"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Angel Di Maria"
:event/subtype "serious_foul"
:event/player1 "Abdoulay Konko"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1339403"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_22350"}

{:event/type "shoton"
:event/elapsed 10
:event/subtype "blocked_shot"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1339405"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_22350"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Angel Di Maria"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_1339406"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_22350"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Mesut Oezil"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1339408"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_22350"}

{:event/type "corner"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Mesut Oezil"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1339408"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_22350"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Sergio Ramos"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1339410"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_22350"}

{:event/type "corner"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Sergio Ramos"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1339410"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Didier Zokora"
:event/subtype "pushing"
:event/player1 "Lassana Diarra"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1339412"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_22350"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Mesut Oezil"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1339422"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_22350"}

{:event/type "corner"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Mesut Oezil"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1339422"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "Luis Fabiano"
:event/subtype "pushing"
:event/player1 "Sami Khedira"
:event/sortorder 5
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1339427"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_22350"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Diego Capel"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1339428"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_22350"}

{:event/type "shotoff"
:event/elapsed 17
:event/subtype "shot"
:event/player1 "Abdoulay Konko"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1339430"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Diego Capel"
:event/subtype "pushing"
:event/player1 "Angel Di Maria"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1339434"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Sami Khedira"
:event/subtype "pushing"
:event/player1 "Didier Zokora"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1339435"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Sami Khedira"
:event/subtype "from_behind"
:event/player1 "Didier Zokora"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1339440"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_22350"}

{:event/type "shoton"
:event/elapsed 22
:event/subtype "direct_freekick"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1339441"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Alvaro Negredo"
:event/subtype "pushing"
:event/player1 "Ricardo Carvalho"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1339443"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_22350"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Diego Capel"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1339447"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_22350"}

{:event/type "corner"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Diego Capel"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1339447"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_22350"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Diego Capel"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1339453"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_22350"}

{:event/type "corner"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Diego Capel"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_1339453"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_22350"}

{:event/type "shotoff"
:event/elapsed 25
:event/subtype "header"
:event/player1 "Julien Escude"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1339454"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_22350"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Mesut Oezil"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1339462"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_22350"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Mesut Oezil"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1339464"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_22350"}

{:event/type "corner"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Mesut Oezil"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1339464"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_22350"}

{:event/type "shoton"
:event/elapsed 29
:event/subtype "distance"
:event/player1 "Angel Di Maria"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1339470"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_22350"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Angel Di Maria"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1339471"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_22350"}

{:event/type "corner"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Angel Di Maria"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_1339471"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_22350"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Sami Khedira"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1339477"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_22350"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Mesut Oezil"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1339479"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_22350"}

{:event/type "corner"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Mesut Oezil"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1339479"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Julien Escude"
:event/subtype "pushing"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1339480"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Romaric"
:event/subtype "pushing"
:event/player1 "Karim Benzema"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1339481"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_22350"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Angel Di Maria"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1339483"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_22350"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Diego Capel"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1339486"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Diego Capel"
:event/subtype "pushing"
:event/player1 "Lassana Diarra"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1339490"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Didier Zokora"
:event/subtype "pushing"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1339496"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Diego Capel"
:event/subtype "pushing"
:event/player1 "Sergio Ramos"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1339497"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Alvaro Arbeloa"
:event/subtype "pushing"
:event/player1 "Abdoulay Konko"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1339508"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_22350"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Mesut Oezil"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1339512"
:event/minute 46
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 45
:event/player2 "Alvaro Negredo"
:event/subtype "shirt_pull"
:event/player1 "Ricardo Carvalho"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1339516"
:event/minute 47
:event/match_id "match_22350"}

{:event/type "card"
:event/elapsed_plus 2
:event/elapsed 45
:event/card_type "y"
:event/subtype "shirt_pull"
:event/player1 "Ricardo Carvalho"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_1339517"
:event/minute 47
:event/match_id "match_22350"}

{:event/type "shoton"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "direct_freekick"
:event/player1 "Romaric"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_1339519"
:event/minute 47
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Alvaro Arbeloa"
:event/subtype "serious_foul"
:event/player1 "Alvaro Negredo"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1339529"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_22350"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Angel Di Maria"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1339530"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Cristiano Ronaldo"
:event/subtype "pushing"
:event/player1 "Luis Fabiano"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1339539"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_22350"}

{:event/type "shoton"
:event/elapsed 51
:event/subtype "direct_freekick"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1339540"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Andres Palop"
:event/subtype "pushing"
:event/player1 "Angel Di Maria"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1339541"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Alvaro Negredo"
:event/subtype "from_behind"
:event/player1 "Ricardo Carvalho"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1339544"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Pepe"
:event/subtype "pushing"
:event/player1 "Alvaro Negredo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1339545"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Luis Fabiano"
:event/subtype "pushing"
:event/player1 "Ricardo Carvalho"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1339546"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_22350"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1339548"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_22350"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Romaric"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1339553"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_22350"}

{:event/type "shotoff"
:event/elapsed 58
:event/subtype "big chance shot"
:event/player1 "Alvaro Negredo"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1339558"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_22350"}

{:event/type "card"
:event/elapsed 60
:event/card_type "y"
:event/subtype "diving"
:event/player1 "Angel Di Maria"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_1339564"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Diego Capel"
:event/subtype "pushing"
:event/player1 "Alvaro Arbeloa"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1339567"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_22350"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Mesut Oezil"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1339576"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_22350"}

{:event/type "corner"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Mesut Oezil"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1339576"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_22350"}

{:event/type "shotoff"
:event/elapsed 63
:event/subtype "shot"
:event/player1 "Angel Di Maria"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1339577"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Alvaro Negredo"
:event/subtype "serious_foul"
:event/player1 "Ricardo Carvalho"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1339579"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_22350"}

{:event/type "card"
:event/elapsed 64
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Ricardo Carvalho"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1339580"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_22350"}

{:event/type "card"
:event/elapsed 65
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Iker Casillas"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1339581"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_22350"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Angel Di Maria"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1339582"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_22350"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Angel Di Maria"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1339584"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_22350"}

{:event/type "corner"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Angel Di Maria"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1339584"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Angel Di Maria"
:event/subtype "obstruction"
:event/player1 "Abdoulay Konko"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1339587"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_22350"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Angel Di Maria"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1339591"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Luis Fabiano"
:event/subtype "serious_foul"
:event/player1 "Lassana Diarra"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1339593"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_22350"}

{:event/type "card"
:event/elapsed 71
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Lassana Diarra"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_1339594"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_22350"}

{:event/type "card"
:event/elapsed 71
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Pepe"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_1339596"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_22350"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Angel Di Maria"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1339600"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_22350"}

{:event/type "corner"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Angel Di Maria"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1339600"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 74
:event/player2 "Fernando Navarro"
:event/subtype "from_behind"
:event/player1 "Pedro Leon"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1339605"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_22350"}

{:event/type "shoton"
:event/elapsed 76
:event/subtype "blocked_shot"
:event/player1 "Pedro Leon"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_1339620"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_22350"}

{:event/type "goal"
:event/elapsed 77
:event/subtype "shot"
:event/player1 "Angel Di Maria"
:event/sortorder 0
:event/team "home"
:event/id "event_1339614"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_22350"}

{:event/type "card"
:event/elapsed 78
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Mesut Oezil"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1339618"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Esteban Granero"
:event/subtype "serious_foul"
:event/player1 "Didier Zokora"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1339623"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_22350"}

{:event/type "card"
:event/elapsed 80
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Didier Zokora"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1339624"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_22350"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Diego Capel"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1339627"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 83
:event/player2 "Didier Zokora"
:event/subtype "pushing"
:event/player1 "Alvaro Arbeloa"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1339629"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Cristiano Ronaldo"
:event/subtype "from_behind"
:event/player1 "Martin Caceres"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1339634"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_22350"}

{:event/type "card"
:event/elapsed 86
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Martin Caceres"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1339635"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 88
:event/subtype "hands"
:event/player1 "Pedro Leon"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1339639"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_22350"}

{:event/type "card"
:event/elapsed 88
:event/card_type "y"
:event/subtype "hands"
:event/player1 "Pedro Leon"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_1339640"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Angel Di Maria"
:event/subtype "pushing"
:event/player1 "Lautaro Acosta"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1339645"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_22350"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Lautaro Acosta"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1339646"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_22350"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Sergio Ramos"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_1339647"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Angel Di Maria"
:event/subtype "serious_foul"
:event/player1 "Mouhamadou Dabo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1339648"
:event/minute 91
:event/match_id "match_22350"}

{:event/type "card"
:event/elapsed_plus 1
:event/elapsed 90
:event/card_type "r"
:event/subtype "serious_fouls"
:event/player1 "Mouhamadou Dabo"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1339649"
:event/minute 91
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Julien Escude"
:event/subtype "pushing"
:event/player1 "Pedro Leon"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1339651"
:event/minute 92
:event/match_id "match_22350"}

{:event/type "shotoff"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "distance"
:event/player1 "Pedro Leon"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1339657"
:event/minute 94
:event/match_id "match_22350"}

{:event/type "foulcommit"
:event/elapsed_plus 4
:event/elapsed 90
:event/player2 "Martin Caceres"
:event/subtype "pushing"
:event/player1 "Cristiano Ronaldo"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1339659"
:event/minute 94
:event/match_id "match_22350"}

{:event/type "cross"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Fernando Navarro"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_1339662"
:event/minute 95
:event/match_id "match_22350"}


]

