
;;# data
[
{:match/id "match_7177"
:match/league "France Ligue 1"
:match/hometeam "OGC Nice"
:match/awayteam "FC Lorient"
:match/score "3:1"
:match/hometeam_goals "3"
:match/awayteam_goals "1"}

{:event/type "foulcommit"
:event/elapsed 1
:event/player2 "Maxime Barthelme"
:event/subtype "trip"
:event/player1 "Jordan Amavi"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4064603"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_7177"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Walid Mesloub"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4064621"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_7177"}

{:event/type "shoton"
:event/elapsed 1
:event/subtype "header"
:event/player1 "unknown"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_4064625"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_7177"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Maxime Barthelme"
:event/subtype "pushing"
:event/player1 "Jordan Amavi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4064641"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_7177"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Benjamin Jeannot"
:event/subtype "serious_foul"
:event/player1 "Mathieu Bodmer"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4064654"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_7177"}

{:event/type "card"
:event/elapsed 6
:event/card_type "y"
:event/player1 "Mathieu Bodmer"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_4064658"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_7177"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Walid Mesloub"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4064805"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_7177"}

{:event/type "goal"
:event/elapsed 6
:event/player2 "Mehdi Mostefa"
:event/subtype "volley"
:event/player1 "Benjamin Jeannot"
:event/sortorder 3
:event/team "away"
:event/id "event_4064670"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_7177"}

{:event/type "shoton"
:event/elapsed 8
:event/subtype "blocked_shot"
:event/player1 "Valentin Eysseric"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4064690"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_7177"}

{:event/type "corner"
:event/elapsed 8
:event/subtype "cross_right"
:event/player1 "Eric Bautheac"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4064701"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_7177"}

{:event/type "corner"
:event/elapsed 9
:event/subtype "cross_right"
:event/player1 "Eric Bautheac"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4064709"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_7177"}

{:event/type "corner"
:event/elapsed 9
:event/subtype "cross_left"
:event/player1 "Eric Bautheac"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4064713"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_7177"}

{:event/type "shoton"
:event/elapsed 9
:event/subtype "shot"
:event/player1 "Carlos Eduardo"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_4064719"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_7177"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Valentin Eysseric"
:event/subtype "trip"
:event/player1 "Pedrinho"
:event/sortorder 5
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4064963"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_7177"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Valentin Eysseric"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4064740"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_7177"}

{:event/type "corner"
:event/elapsed 11
:event/subtype "cross_left"
:event/player1 "Eric Bautheac"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4064750"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_7177"}

{:event/type "shotoff"
:event/elapsed 12
:event/subtype "distance"
:event/player1 "Alassane Plea"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4064775"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_7177"}

{:event/type "shoton"
:event/elapsed 14
:event/subtype "deflected"
:event/player1 "Eric Bautheac"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4064794"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_7177"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Valentin Eysseric"
:event/subtype "trip"
:event/player1 "Mehdi Mostefa"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4064813"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_7177"}

{:event/type "shotoff"
:event/elapsed 17
:event/subtype "distance"
:event/player1 "Niklas Hult"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4064843"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_7177"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Valentin Eysseric"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4064851"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_7177"}

{:event/type "corner"
:event/elapsed 18
:event/subtype "cross_left"
:event/player1 "Gregoire Puel"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4064864"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_7177"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Nampalys Mendy"
:event/subtype "trip"
:event/player1 "Walid Mesloub"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4064899"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_7177"}

{:event/type "corner"
:event/elapsed 22
:event/subtype "cross_right"
:event/player1 "Eric Bautheac"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4064930"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_7177"}

{:event/type "corner"
:event/elapsed 22
:event/subtype "cross_left"
:event/player1 "Valentin Eysseric"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_4064934"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_7177"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Maxime Barthelme"
:event/subtype "pushing"
:event/player1 "Eric Bautheac"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4064942"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_7177"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Abdoulaye Diallo Sadio,22"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4064976"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_7177"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Eric Bautheac"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4064999"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_7177"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Carlos Eduardo"
:event/subtype "penalty"
:event/player1 "Maxime Barthelme"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4065007"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_7177"}

{:event/type "goal"
:event/elapsed 29
:event/player1 "Eric Bautheac"
:event/sortorder 1
:event/team "home"
:event/id "event_4065014"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_7177"}

{:event/type "foulcommit"
:event/elapsed 30
:event/subtype "hands"
:event/player1 "Vincent Le Goff"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4065029"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_7177"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Eric Bautheac"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4065034"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_7177"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Benjamin Jeannot"
:event/subtype "trip"
:event/player1 "Niklas Hult"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4065039"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_7177"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Maxime Barthelme"
:event/subtype "pull"
:event/player1 "Niklas Hult"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4065047"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_7177"}

{:event/type "foulcommit"
:event/elapsed 34
:event/subtype "hands"
:event/player1 "Mehdi Mostefa"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4065073"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_7177"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Jordan Amavi"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4065086"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_7177"}

{:event/type "shoton"
:event/elapsed 36
:event/subtype "blocked_shot"
:event/player1 "Alexy Bosetti"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4065091"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_7177"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Walid Mesloub"
:event/subtype "obstruction"
:event/player1 "Mathieu Bodmer"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4065108"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_7177"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Walid Mesloub"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4065112"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_7177"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Walid Mesloub"
:event/subtype "pushing"
:event/player1 "Eric Bautheac"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4065133"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_7177"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Vincent Le Goff"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4065139"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_7177"}

{:event/type "foulcommit"
:event/elapsed 40
:event/subtype "hands"
:event/player1 "Carlos Eduardo"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4065150"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_7177"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Walid Mesloub"
:event/subtype "trip"
:event/player1 "Gregoire Puel"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4065174"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_7177"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Pedrinho"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4065177"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_7177"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Pedrinho"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4065179"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_7177"}

{:event/type "shoton"
:event/elapsed 45
:event/subtype "big chance shot"
:event/player1 "Alassane Plea"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4065208"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_7177"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Carlos Eduardo"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4065278"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_7177"}

{:event/type "shotoff"
:event/elapsed 47
:event/subtype "shot"
:event/player1 "Benjamin Jeannot"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4065291"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_7177"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Jordan Amavi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4065300"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_7177"}

{:event/type "shoton"
:event/elapsed 48
:event/subtype "blocked_shot"
:event/player1 "Carlos Eduardo"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_4065311"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_7177"}

{:event/type "shoton"
:event/elapsed 49
:event/subtype "distance"
:event/player1 "Alexy Bosetti"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4065351"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_7177"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Alexy Bosetti"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4065327"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_7177"}

{:event/type "shotoff"
:event/elapsed 50
:event/subtype "header"
:event/player1 "Carlos Eduardo"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4065329"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_7177"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Eric Bautheac"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4065370"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_7177"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Romain Genevois"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4065433"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_7177"}

{:event/type "corner"
:event/elapsed 58
:event/subtype "cross_left"
:event/player1 "Eric Bautheac"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_4065470"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_7177"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Abdoulaye Diallo Sadio,22"
:event/subtype "trip"
:event/player1 "Romain Genevois"
:event/sortorder 5
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4065538"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_7177"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player2 "Mathieu Bodmer"
:event/subtype "obstruction"
:event/player1 "Benjamin Jeannot"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4065489"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_7177"}

{:event/type "goal"
:event/elapsed 60
:event/player2 "Carlos Eduardo"
:event/subtype "header"
:event/player1 "Alexy Bosetti"
:event/sortorder 2
:event/team "home"
:event/id "event_4065502"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_7177"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Carlos Eduardo"
:event/subtype "trip"
:event/player1 "Walid Mesloub"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4065530"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_7177"}

{:event/type "card"
:event/elapsed 62
:event/card_type "y"
:event/player1 "Walid Mesloub"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4066379"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_7177"}

{:event/type "shoton"
:event/elapsed 64
:event/subtype "blocked_shot"
:event/player1 "Carlos Eduardo"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4065559"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_7177"}

{:event/type "foulcommit"
:event/elapsed 66
:event/player2 "Carlos Eduardo"
:event/subtype "pushing"
:event/player1 "unknown"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4065595"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_7177"}

{:event/type "goal"
:event/elapsed 67
:event/player2 "Alassane Plea"
:event/subtype "volley"
:event/player1 "Carlos Eduardo"
:event/sortorder 3
:event/team "home"
:event/id "event_4065605"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_7177"}

{:event/type "foulcommit"
:event/elapsed 73
:event/subtype "hands"
:event/player1 "Benjamin Jeannot"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4065758"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_7177"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Niklas Hult"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4065740"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_7177"}

{:event/type "shoton"
:event/elapsed 75
:event/subtype "shot"
:event/player1 "Nampalys Mendy"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4065746"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_7177"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Pedrinho"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4065754"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_7177"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Mattias Autret"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4065779"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_7177"}

{:event/type "shoton"
:event/elapsed 78
:event/subtype "deflected"
:event/player1 "Mattias Autret"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4065784"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_7177"}

{:event/type "corner"
:event/elapsed 78
:event/subtype "cross_left"
:event/player1 "Mattias Autret"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_4065786"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_7177"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Vincent Le Goff"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4065804"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_7177"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Gregoire Puel"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4065815"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_7177"}

{:event/type "shoton"
:event/elapsed 82
:event/subtype "shot"
:event/player1 "Jordan Amavi"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4065852"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_7177"}

{:event/type "foulcommit"
:event/elapsed 83
:event/player2 "Mehdi Mostefa"
:event/subtype "trip"
:event/player1 "Alassane Plea"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4065863"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_7177"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Pedrinho"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4065868"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_7177"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Mattias Autret"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4065885"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_7177"}

{:event/type "shotoff"
:event/elapsed 85
:event/subtype "shot"
:event/player1 "Gilles Sunu"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4065890"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_7177"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Pedrinho"
:event/subtype "trip"
:event/player1 "Niklas Hult"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4065924"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_7177"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Jordan Amavi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4065931"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_7177"}

{:event/type "shoton"
:event/elapsed 89
:event/subtype "blocked_shot"
:event/player1 "Julien Vercauteren"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4065936"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_7177"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Eric Bautheac"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_4065971"
:event/minute 92
:event/match_id "match_7177"}

{:event/type "shoton"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "deflected"
:event/player1 "Alassane Plea"
:event/sortorder 6
:event/team "home"
:event/event_type "shoton"
:event/id "event_4065983"
:event/minute 92
:event/match_id "match_7177"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Pedrinho"
:event/sortorder 8
:event/team "away"
:event/event_type "cross"
:event/id "event_4065998"
:event/minute 94
:event/match_id "match_7177"}


]

