
;;# data
[
{:match/id "match_9223"
:match/league "Germany 1. Bundesliga"
:match/hometeam "VfB Stuttgart"
:match/awayteam "Borussia Mönchengladbach"
:match/score "1:1"
:match/hometeam_goals "2"
:match/awayteam_goals "0"}

{:event/type "goal"
:event/elapsed 28
:event/player1 "Alvaro Dominguez"
:event/sortorder 0
:event/team "away"
:event/id "event_2699716"
:event/event_type "goal"
:event/goal_type "o"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_9223"}

{:event/type "goal"
:event/elapsed 34
:event/player1 "Christian Gentner"
:event/sortorder 0
:event/team "home"
:event/id "event_2699717"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_9223"}


]

