
;;# data
[
{:match/id "match_12547"
:match/league "Italy Serie A"
:match/hometeam "Genoa"
:match/awayteam "Palermo"
:match/score "2:1"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Facundo Sebastian Roncaglia"
:event/subtype "pushing"
:event/player1 "Paulo Dybala"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3962204"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Diego Perotti"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3962212"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Michel Morganella"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3962219"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Edgar Barreto"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3962222"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Ivailo Chochev"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3962228"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_12547"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Franco Vazquez"
:event/subtype "trip"
:event/player1 "Leandro Greco"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3962240"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_12547"}

{:event/type "goal"
:event/elapsed 7
:event/player2 "Franco Vazquez"
:event/subtype "shot"
:event/player1 "Paulo Dybala"
:event/sortorder 1
:event/team "away"
:event/id "event_3962243"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Luca Antonelli"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3962258"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_12547"}

{:event/type "foulcommit"
:event/elapsed 11
:event/subtype "hands"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3962265"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Diego Perotti"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3962269"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_12547"}

{:event/type "foulcommit"
:event/elapsed 12
:event/subtype "hands"
:event/player1 "Enzo Maresca"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3962273"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_12547"}

{:event/type "shoton"
:event/elapsed 13
:event/subtype "distance"
:event/player1 "Diego Perotti"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3962279"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_12547"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Andrea Bertolacci"
:event/subtype "trip"
:event/player1 "Ezequiel Munoz"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3962280"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Edenilson"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3962282"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_12547"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Franco Vazquez"
:event/subtype "trip"
:event/player1 "Giovanni Marchese"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3962288"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Enzo Maresca"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3962290"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Edgar Barreto"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3962302"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Achraf Lazaar"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3962304"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_12547"}

{:event/type "shotoff"
:event/elapsed 18
:event/subtype "distance"
:event/player1 "Giancarlo Gonzalez"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3962307"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Diego Perotti"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_3962310"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Iago Falque"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3962313"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_12547"}

{:event/type "goal"
:event/elapsed 21
:event/subtype "backheel"
:event/player1 "Iago Falque"
:event/sortorder 0
:event/team "home"
:event/id "event_3962324"
:event/event_type "goal"
:event/goal_type "dg"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_12547"}

{:event/type "corner"
:event/elapsed 21
:event/subtype "cross_right"
:event/player1 "Edenilson"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3962327"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_12547"}

{:event/type "foulcommit"
:event/elapsed 22
:event/subtype "pushing"
:event/player1 "Giovanni Marchese"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3962331"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Ivailo Chochev"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3962343"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_12547"}

{:event/type "shotoff"
:event/elapsed 24
:event/subtype "shot"
:event/player1 "Paulo Dybala"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3962345"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Giovanni Marchese"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3962360"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_12547"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Andrea Bertolacci"
:event/subtype "pushing"
:event/player1 "Franco Vazquez"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3962364"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Andrea Bertolacci"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3962368"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_12547"}

{:event/type "shoton"
:event/elapsed 27
:event/subtype "distance"
:event/player1 "Achraf Lazaar"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_3962375"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_12547"}

{:event/type "shoton"
:event/elapsed 28
:event/subtype "blocked_shot"
:event/player1 "Paulo Dybala"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3962379"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_12547"}

{:event/type "corner"
:event/elapsed 28
:event/subtype "cross_right"
:event/player1 "Paulo Dybala"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3962381"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Diego Perotti"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3962388"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_12547"}

{:event/type "shoton"
:event/elapsed 30
:event/subtype "deflected"
:event/player1 "Andrea Bertolacci"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4017518"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_12547"}

{:event/type "goal"
:event/elapsed 30
:event/player2 "Andrea Bertolacci"
:event/subtype "shot"
:event/player1 "Luca Antonelli"
:event/sortorder 1
:event/team "home"
:event/id "event_3962392"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_12547"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Nicolas Burdisso"
:event/subtype "pushing"
:event/player1 "Franco Vazquez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3962405"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_12547"}

{:event/type "shoton"
:event/elapsed 33
:event/subtype "shot"
:event/player1 "Luca Antonelli"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3962409"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_12547"}

{:event/type "corner"
:event/elapsed 33
:event/subtype "cross_left"
:event/player1 "Iago Falque"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3962410"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_12547"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Franco Vazquez"
:event/subtype "trip"
:event/player1 "Facundo Sebastian Roncaglia"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3962415"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_12547"}

{:event/type "card"
:event/elapsed 34
:event/card_type "y"
:event/subtype "emergency_brake"
:event/player1 "Facundo Sebastian Roncaglia"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3962418"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_12547"}

{:event/type "shoton"
:event/elapsed 35
:event/subtype "blocked_shot"
:event/player1 "Iago Falque"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3962430"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_12547"}

{:event/type "shoton"
:event/elapsed 36
:event/subtype "shot"
:event/player1 "Paulo Dybala"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3962432"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_12547"}

{:event/type "corner"
:event/elapsed 36
:event/subtype "cross_left"
:event/player1 "Achraf Lazaar"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3962434"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Diego Perotti"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3962438"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_12547"}

{:event/type "shoton"
:event/elapsed 40
:event/subtype "blocked_shot"
:event/player1 "Alessandro Matri"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3962456"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Giovanni Marchese"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3962459"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Edenilson"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3962470"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Giovanni Marchese"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3962472"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_12547"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Paulo Dybala"
:event/subtype "pushing"
:event/player1 "Nicolas Burdisso"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3962476"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Achraf Lazaar"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3962479"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_12547"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Franco Vazquez"
:event/subtype "trip"
:event/player1 "Andrea Bertolacci"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3962483"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Facundo Sebastian Roncaglia"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3962551"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_12547"}

{:event/type "foulcommit"
:event/elapsed 46
:event/player2 "Mauricio Pinilla"
:event/subtype "trip"
:event/player1 "Ivailo Chochev"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3962554"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Luca Antonelli"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3962559"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_12547"}

{:event/type "corner"
:event/elapsed 50
:event/subtype "cross_left"
:event/player1 "Diego Perotti"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3962561"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Diego Perotti"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3962571"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Luca Antonelli"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3962575"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Luca Antonelli"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3962591"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_12547"}

{:event/type "foulcommit"
:event/elapsed 56
:event/subtype "hands"
:event/player1 "Leandro Greco"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3962593"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_12547"}

{:event/type "card"
:event/elapsed 56
:event/card_type "y"
:event/subtype "hands"
:event/player1 "Leandro Greco"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_3962594"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Edgar Barreto"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3962595"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_12547"}

{:event/type "shotoff"
:event/elapsed 59
:event/subtype "post"
:event/player1 "Paulo Dybala"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3962606"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_12547"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Andrea Bertolacci"
:event/subtype "trip"
:event/player1 "Franco Vazquez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3962614"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Diego Perotti"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3962621"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_12547"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Franco Vazquez"
:event/subtype "trip"
:event/player1 "Andrea Bertolacci"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3962632"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Giovanni Marchese"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3962637"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Michel Morganella"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3962652"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_12547"}

{:event/type "shoton"
:event/elapsed 69
:event/subtype "big chance header"
:event/player1 "Robin Quaison"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3962655"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Paulo Dybala"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3962668"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Edgar Barreto"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3962672"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_12547"}

{:event/type "shotoff"
:event/elapsed 72
:event/subtype "header"
:event/player1 "Franco Vazquez"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3962674"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_12547"}

{:event/type "shoton"
:event/elapsed 73
:event/subtype "blocked_shot"
:event/player1 "Mauricio Pinilla"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3962678"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Giovanni Marchese"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3962696"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_12547"}

{:event/type "shotoff"
:event/elapsed 77
:event/subtype "big chance header"
:event/player1 "Mauricio Pinilla"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3962706"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_12547"}

{:event/type "shotoff"
:event/elapsed 79
:event/subtype "distance"
:event/player1 "Juraj Kucka"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3962718"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Enzo Maresca"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3962731"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_12547"}

{:event/type "corner"
:event/elapsed 82
:event/subtype "short_right"
:event/player1 "Paulo Dybala"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3962736"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_12547"}

{:event/type "shotoff"
:event/elapsed 82
:event/subtype "shot"
:event/player1 "Paulo Dybala"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3962738"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_12547"}

{:event/type "foulcommit"
:event/elapsed 83
:event/player2 "Paulo Dybala"
:event/subtype "trip"
:event/player1 "Juraj Kucka"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3962745"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_12547"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Robin Quaison"
:event/subtype "trip"
:event/player1 "Leandro Greco"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3962762"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Juraj Kucka"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3962773"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Diego Perotti"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_3962795"
:event/minute 91
:event/match_id "match_12547"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "header"
:event/player1 "Mauricio Pinilla"
:event/sortorder 6
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3962797"
:event/minute 91
:event/match_id "match_12547"}

{:event/type "shoton"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "distance"
:event/player1 "Achraf Lazaar"
:event/sortorder 9
:event/team "away"
:event/event_type "shoton"
:event/id "event_3962815"
:event/minute 93
:event/match_id "match_12547"}

{:event/type "shoton"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "blocked_shot"
:event/player1 "Edenilson"
:event/sortorder 10
:event/team "home"
:event/event_type "shoton"
:event/id "event_3962822"
:event/minute 94
:event/match_id "match_12547"}

{:event/type "shoton"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "distance"
:event/player1 "Juraj Kucka"
:event/sortorder 11
:event/team "home"
:event/event_type "shoton"
:event/id "event_3962823"
:event/minute 95
:event/match_id "match_12547"}

{:event/type "foulcommit"
:event/elapsed_plus 5
:event/elapsed 90
:event/player2 "Nicolas Burdisso"
:event/subtype "pushing"
:event/player1 "Paulo Dybala"
:event/sortorder 12
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3962826"
:event/minute 95
:event/match_id "match_12547"}

{:event/type "cross"
:event/elapsed_plus 6
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Facundo Sebastian Roncaglia"
:event/sortorder 13
:event/team "home"
:event/event_type "cross"
:event/id "event_3962827"
:event/minute 96
:event/match_id "match_12547"}


]

