
;;# data
[
{:match/id "match_6392"
:match/league "France Ligue 1"
:match/hometeam "Stade Brestois 29"
:match/awayteam "Paris Saint-Germain"
:match/score "1:2"
:match/hometeam_goals "0"
:match/awayteam_goals "3"}

{:event/type "card"
:event/elapsed 34
:event/card_type "r"
:event/player1 "Abdoulwahid Sissoko"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2522284"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_6392"}

{:event/type "card"
:event/elapsed 39
:event/card_type "y"
:event/player1 "Zlatan Ibrahimovic"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2522288"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_6392"}

{:event/type "goal"
:event/elapsed 55
:event/player1 "Zlatan Ibrahimovic"
:event/sortorder 0
:event/team "away"
:event/id "event_2522304"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_6392"}

{:event/type "card"
:event/elapsed 67
:event/card_type "y"
:event/player1 "Salvatore Sirigu"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2522312"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_6392"}

{:event/type "goal"
:event/elapsed 73
:event/player1 "Kevin Gameiro"
:event/sortorder 0
:event/team "away"
:event/id "event_2522316"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_6392"}

{:event/type "card"
:event/elapsed 84
:event/card_type "y"
:event/player1 "Jonathan Ayite"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2522323"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_6392"}

{:event/type "goal"
:event/elapsed 90
:event/player1 "Bernard Mendy"
:event/sortorder 0
:event/team "home"
:event/id "event_2522327"
:event/event_type "goal"
:event/goal_type "o"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_6392"}


]

