
;;# data
[
{:match/id "match_9599"
:match/league "Germany 1. Bundesliga"
:match/hometeam "Eintracht Frankfurt"
:match/awayteam "Borussia Dortmund"
:match/score "1:2"
:match/hometeam_goals "1"
:match/awayteam_goals "2"}

{:event/type "goal"
:event/elapsed 10
:event/player1 "Henrik Mkhitaryan"
:event/sortorder 0
:event/team "away"
:event/id "event_2957162"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_9599"}

{:event/type "goal"
:event/elapsed 36
:event/player1 "Vaclav Kadlec"
:event/sortorder 0
:event/team "home"
:event/id "event_2957253"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_9599"}

{:event/type "card"
:event/elapsed 45
:event/card_type "y"
:event/player1 "Mats Hummels"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2957340"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_9599"}

{:event/type "goal"
:event/elapsed 56
:event/player1 "Henrik Mkhitaryan"
:event/sortorder 0
:event/team "away"
:event/id "event_2957583"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_9599"}

{:event/type "card"
:event/elapsed 80
:event/card_type "y"
:event/player1 "Marco Reus"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2957709"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_9599"}

{:event/type "card"
:event/elapsed 83
:event/card_type "y"
:event/player1 "Carlos Zambrano"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2957723"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_9599"}


]

