
;;# data
[
{:match/id "match_3496"
:match/league "England Premier League"
:match/hometeam "Swansea City"
:match/awayteam "Tottenham Hotspur"
:match/score "1:2"
:match/hometeam_goals "1"
:match/awayteam_goals "2"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "Emmanuel Adebayor"
:event/subtype "pushing"
:event/player1 "Chico"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2668997"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_3496"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Scott Parker"
:event/subtype "dangerous_play"
:event/player1 "Michu"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2669042"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_3496"}

{:event/type "goal"
:event/elapsed 7
:event/player2 "Gareth Bale"
:event/subtype "shot"
:event/player1 "Jan Vertonghen"
:event/sortorder 5
:event/team "away"
:event/id "event_2669052"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_3496"}

{:event/type "shoton"
:event/elapsed 13
:event/subtype "shot"
:event/player1 "Emmanuel Adebayor"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_2669133"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_3496"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Kyle Walker"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2669191"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_3496"}

{:event/type "shoton"
:event/elapsed 17
:event/subtype "blocked_shot"
:event/player1 "Gareth Bale"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_2669204"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_3496"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Gareth Bale"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2669227"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_3496"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Dwight Tiendalli"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2669242"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_3496"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Jonathan De Guzman"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2669246"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_3496"}

{:event/type "corner"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Jonathan De Guzman"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2669246"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_3496"}

{:event/type "shotoff"
:event/elapsed 21
:event/subtype "header"
:event/player1 "Michu"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2669249"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_3496"}

{:event/type "goal"
:event/elapsed 21
:event/player2 "Jan Vertonghen"
:event/subtype "shot"
:event/player1 "Gareth Bale"
:event/sortorder 3
:event/team "away"
:event/id "event_2669256"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_3496"}

{:event/type "shotoff"
:event/elapsed 23
:event/subtype "volley"
:event/player1 "Nathan Dyer"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2669306"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_3496"}

{:event/type "shoton"
:event/elapsed 25
:event/subtype "distance"
:event/player1 "Dwight Tiendalli"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_2669330"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3496"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Jonathan De Guzman"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2669335"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3496"}

{:event/type "corner"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Jonathan De Guzman"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_2669335"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3496"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Ben Davies"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2669346"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_3496"}

{:event/type "shotoff"
:event/elapsed 28
:event/subtype "shot"
:event/player1 "Ben Davies"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2669372"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_3496"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Ashley Williams"
:event/player1 "Emmanuel Adebayor"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2669383"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_3496"}

{:event/type "shotoff"
:event/elapsed 30
:event/subtype "shot"
:event/player1 "Gareth Bale"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2669410"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_3496"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Wayne Routledge"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2669420"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_3496"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Dwight Tiendalli"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2669434"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_3496"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Leon Britton"
:event/player1 "Gylfi Sigurdsson"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2669463"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3496"}

{:event/type "shoton"
:event/elapsed 34
:event/subtype "blocked_shot"
:event/player1 "Jonathan De Guzman"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_2669472"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_3496"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Jonathan De Guzman"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2669496"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_3496"}

{:event/type "shoton"
:event/elapsed 35
:event/subtype "blocked_shot"
:event/player1 "Pablo Hernandez"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_2669500"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_3496"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Dwight Tiendalli"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_2669503"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_3496"}

{:event/type "shotoff"
:event/elapsed 36
:event/subtype "crossbar"
:event/player1 "Nathan Dyer"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2669506"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_3496"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Dwight Tiendalli"
:event/subtype "dangerous_play"
:event/player1 "Emmanuel Adebayor"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2669576"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_3496"}

{:event/type "card"
:event/elapsed 40
:event/card_type "y"
:event/player1 "Emmanuel Adebayor"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_2669578"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_3496"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Chico"
:event/subtype "pull"
:event/player1 "Scott Parker"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2669606"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_3496"}

{:event/type "shotoff"
:event/elapsed 43
:event/subtype "shot"
:event/player1 "Jonathan De Guzman"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2669612"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_3496"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Dwight Tiendalli"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2669693"
:event/minute 47
:event/match_id "match_3496"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Nathan Dyer"
:event/player1 "Kyle Walker"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2669806"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_3496"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Aaron Lennon"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2669835"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_3496"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Gareth Bale"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_2669841"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_3496"}

{:event/type "corner"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Gareth Bale"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_2669841"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_3496"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Gylfi Sigurdsson"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_2669851"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_3496"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Aaron Lennon"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2670033"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_3496"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Gareth Bale"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_2670063"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_3496"}

{:event/type "corner"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Gareth Bale"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_2670063"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_3496"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Scott Parker"
:event/player1 "Michu"
:event/sortorder 5
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2670081"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_3496"}

{:event/type "card"
:event/elapsed 62
:event/card_type "y"
:event/player1 "Michu"
:event/sortorder 6
:event/team "home"
:event/event_type "card"
:event/id "event_2670085"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_3496"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Pablo Hernandez"
:event/subtype "pushing"
:event/player1 "Kyle Walker"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2670183"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_3496"}

{:event/type "card"
:event/elapsed 68
:event/card_type "y"
:event/player1 "Kyle Walker"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_2670184"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_3496"}

{:event/type "shotoff"
:event/elapsed 69
:event/subtype "shot"
:event/player1 "Nathan Dyer"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2670169"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_3496"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Dwight Tiendalli"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2670219"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3496"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Sung-Yueng Ki"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2670226"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3496"}

{:event/type "corner"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Sung-Yueng Ki"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2670226"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3496"}

{:event/type "goal"
:event/elapsed 71
:event/player2 "Sung-Yueng Ki"
:event/subtype "header"
:event/player1 "Michu"
:event/sortorder 5
:event/team "home"
:event/id "event_2670229"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3496"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Leon Britton"
:event/player1 "Moussa Dembele"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2670242"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3496"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Sung-Yueng Ki"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2670246"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3496"}

{:event/type "shotoff"
:event/elapsed 74
:event/subtype "shot"
:event/player1 "Gareth Bale"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_2670260"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_3496"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Sung-Yueng Ki"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2670305"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3496"}

{:event/type "corner"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Sung-Yueng Ki"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_2670305"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3496"}

{:event/type "foulcommit"
:event/elapsed 79
:event/player2 "Michu"
:event/player1 "Jan Vertonghen"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2670328"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_3496"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Wayne Routledge"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_2670333"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_3496"}

{:event/type "shotoff"
:event/elapsed 79
:event/subtype "volley"
:event/player1 "Michu"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2670334"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_3496"}

{:event/type "shotoff"
:event/elapsed 82
:event/subtype "shot"
:event/player1 "Michu"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_2670393"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_3496"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Dwight Tiendalli"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2670398"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_3496"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Sung-Yueng Ki"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2670402"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_3496"}

{:event/type "corner"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Sung-Yueng Ki"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_2670402"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_3496"}

{:event/type "foulcommit"
:event/elapsed 83
:event/player2 "Aaron Lennon"
:event/subtype "from_behind"
:event/player1 "Ben Davies"
:event/sortorder 8
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_2670415"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_3496"}

{:event/type "card"
:event/elapsed 83
:event/card_type "y"
:event/player1 "Ben Davies"
:event/sortorder 9
:event/team "home"
:event/event_type "card"
:event/id "event_2670416"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_3496"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Moussa Dembele"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_2670425"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_3496"}

{:event/type "shoton"
:event/elapsed 86
:event/subtype "shot"
:event/player1 "Jermain Defoe"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_2670447"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3496"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player2 "Wayne Routledge"
:event/player1 "Lewis Holtby"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2670480"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_3496"}

{:event/type "card"
:event/elapsed 89
:event/card_type "y"
:event/player1 "Lewis Holtby"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_2670483"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_3496"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Nathan Dyer"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2670490"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3496"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Leon Britton"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2670514"
:event/minute 91
:event/match_id "match_3496"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "blocked_shot"
:event/player1 "Nathan Dyer"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_2670517"
:event/minute 91
:event/match_id "match_3496"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Leon Britton"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_2670522"
:event/minute 92
:event/match_id "match_3496"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Gareth Bale"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_2670553"
:event/minute 94
:event/match_id "match_3496"}

{:event/type "foulcommit"
:event/elapsed_plus 6
:event/elapsed 90
:event/player2 "Ben Davies"
:event/player1 "Scott Parker"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_2670561"
:event/minute 96
:event/match_id "match_3496"}

{:event/type "card"
:event/elapsed_plus 6
:event/elapsed 90
:event/card_type "y"
:event/player1 "Scott Parker"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_2670562"
:event/minute 96
:event/match_id "match_3496"}


]

