
;;# data
[
{:match/id "match_5791"
:match/league "France Ligue 1"
:match/hometeam "Olympique de Marseille"
:match/awayteam "AJ Auxerre"
:match/score "1:1"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "card"
:event/elapsed 26
:event/card_type "y"
:event/player1 "Adama Coulibaly"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1534863"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_5791"}

{:event/type "card"
:event/elapsed 51
:event/card_type "y"
:event/player1 "Cedric Hengbart"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1535288"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_5791"}

{:event/type "goal"
:event/elapsed 56
:event/player1 "Mathieu Valbuena"
:event/sortorder 0
:event/team "home"
:event/id "event_1535287"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_5791"}

{:event/type "goal"
:event/elapsed 77
:event/player1 "Jo-Gook Jung"
:event/sortorder 0
:event/team "away"
:event/id "event_1535554"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_5791"}


]

