
;;# data
[
{:match/id "match_7672"
:match/league "France Ligue 1"
:match/hometeam "LOSC Lille"
:match/awayteam "Toulouse FC"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Tongo Hamed Doumbia"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5421518"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_7672"}

{:event/type "corner"
:event/elapsed 2
:event/subtype "cross_right"
:event/player1 "Etienne Didot"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_5421528"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_7672"}

{:event/type "shoton"
:event/elapsed 2
:event/subtype "header"
:event/player1 "Marcel Tisserand"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_5421534"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_7672"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Djibril Sidibe"
:event/subtype "pull"
:event/player1 "Steeve Yago"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5421608"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Somalia"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5421662"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_7672"}

{:event/type "foulcommit"
:event/elapsed 8
:event/player2 "Steeve Yago"
:event/subtype "from_behind"
:event/player1 "Mounir Obbadi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5421681"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_7672"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Marko Basa"
:event/subtype "trip"
:event/player1 "Wissam Ben Yedder"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5421749"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Francois Moubandje"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5421772"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_7672"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Eder"
:event/player1 "Marcel Tisserand"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5421791"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Sofiane Boufal"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5421810"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Steeve Yago"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5421852"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Eder"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5421860"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_7672"}

{:event/type "goal"
:event/elapsed 17
:event/subtype "shot"
:event/player1 "Morgan Amalfitano"
:event/sortorder 1
:event/team "home"
:event/id "event_5421889"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_7672"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Djibril Sidibe"
:event/player1 "Steeve Yago"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5421993"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Sofiane Boufal"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5422001"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Tongo Hamed Doumbia"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5422009"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_7672"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Adama Soumaoro"
:event/player1 "Martin Braithwaite"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5422026"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Mounir Obbadi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5422032"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Florent Balmont"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5422036"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_7672"}

{:event/type "corner"
:event/elapsed 25
:event/subtype "short_right"
:event/player1 "Morgan Amalfitano"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_5422041"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_7672"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Wissam Ben Yedder"
:event/subtype "pushing"
:event/player1 "Florent Balmont"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5422044"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Martin Braithwaite"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5422063"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_7672"}

{:event/type "shotoff"
:event/elapsed 27
:event/subtype "header"
:event/player1 "Wissam Ben Yedder"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5422065"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Djibril Sidibe"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5422081"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_7672"}

{:event/type "shotoff"
:event/elapsed 30
:event/subtype "distance"
:event/player1 "Mounir Obbadi"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5422100"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Etienne Didot"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5422120"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Djibril Sidibe"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5422148"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_7672"}

{:event/type "shotoff"
:event/elapsed 33
:event/subtype "lob"
:event/player1 "Sofiane Boufal"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5422155"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_7672"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Adama Soumaoro"
:event/subtype "trip"
:event/player1 "Tongo Hamed Doumbia"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5422180"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_7672"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Martin Braithwaite"
:event/player1 "Renato Civelli"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5422200"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Etienne Didot"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5422201"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Francois Moubandje"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5422207"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_7672"}

{:event/type "shoton"
:event/elapsed 38
:event/subtype "shot"
:event/player1 "Eder"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_5422226"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Florent Balmont"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5422229"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_7672"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Eder"
:event/subtype "from_behind"
:event/player1 "Marcel Tisserand"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5422239"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Morgan Amalfitano"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5422244"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_7672"}

{:event/type "corner"
:event/elapsed 40
:event/subtype "cross_right"
:event/player1 "Morgan Amalfitano"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_5422251"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_7672"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Steeve Yago"
:event/subtype "dangerous_play"
:event/player1 "Eder"
:event/sortorder 5
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5422258"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_7672"}

{:event/type "card"
:event/elapsed 40
:event/card_type "y"
:event/player1 "Eder"
:event/sortorder 6
:event/team "home"
:event/event_type "card"
:event/id "event_5422261"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_7672"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Etienne Didot"
:event/subtype "dangerous_play"
:event/player1 "Renato Civelli"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5422287"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_7672"}

{:event/type "card"
:event/elapsed 43
:event/card_type "y"
:event/player1 "Renato Civelli"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_5422294"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Marcel Tisserand"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5422304"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Yann Bodiger"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_5422309"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_7672"}

{:event/type "corner"
:event/elapsed 44
:event/subtype "cross_right"
:event/player1 "Etienne Didot"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_5422316"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Etienne Didot"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5422323"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Sofiane Boufal"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5422331"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_7672"}

{:event/type "shotoff"
:event/elapsed 47
:event/subtype "big chance shot"
:event/player1 "Wissam Ben Yedder"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5422584"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_7672"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Yann Bodiger"
:event/subtype "serious_foul"
:event/player1 "Mounir Obbadi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5422656"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_7672"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Eder"
:event/subtype "trip"
:event/player1 "Marcel Tisserand"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5422679"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Morgan Amalfitano"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5422693"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_7672"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Steeve Yago"
:event/subtype "pull"
:event/player1 "Sofiane Boufal"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5422722"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_7672"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Steeve Yago"
:event/player1 "Mounir Obbadi"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5422732"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Francois Moubandje"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5422743"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_7672"}

{:event/type "shoton"
:event/elapsed 54
:event/subtype "header"
:event/player1 "Adrien Regattin"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_5422745"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_7672"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Eder"
:event/subtype "serious_foul"
:event/player1 "Issa Diop"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5422750"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_7672"}

{:event/type "card"
:event/elapsed 54
:event/card_type "y"
:event/player1 "Issa Diop"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_5422754"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Sofiane Boufal"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_5422762"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_7672"}

{:event/type "shotoff"
:event/elapsed 54
:event/subtype "header"
:event/player1 "Renato Civelli"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5422764"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_7672"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Morgan Amalfitano"
:event/player1 "Francois Moubandje"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5422787"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_7672"}

{:event/type "shoton"
:event/elapsed 56
:event/subtype "shot"
:event/player1 "Tongo Hamed Doumbia"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_5422801"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_7672"}

{:event/type "shoton"
:event/elapsed 57
:event/subtype "blocked_shot"
:event/player1 "Florent Balmont"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5422815"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_7672"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Florent Balmont"
:event/subtype "serious_foul"
:event/player1 "Tongo Hamed Doumbia"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5422835"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_7672"}

{:event/type "card"
:event/elapsed 57
:event/card_type "y"
:event/player1 "Tongo Hamed Doumbia"
:event/sortorder 4
:event/team "away"
:event/event_type "card"
:event/id "event_5422840"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Sofiane Boufal"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5422857"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Djibril Sidibe"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5422947"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_7672"}

{:event/type "shotoff"
:event/elapsed 64
:event/subtype "big chance shot"
:event/player1 "Adrien Regattin"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5422968"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Aleksandar Pesic"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5423017"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_7672"}

{:event/type "shoton"
:event/elapsed 67
:event/subtype "blocked_shot"
:event/player1 "Martin Braithwaite"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_5423021"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_7672"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Rio Mavuba"
:event/subtype "serious_foul"
:event/player1 "Steeve Yago"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5423042"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_7672"}

{:event/type "card"
:event/elapsed 68
:event/card_type "y"
:event/player1 "Steeve Yago"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_5423048"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_7672"}

{:event/type "shoton"
:event/elapsed 70
:event/subtype "blocked_shot"
:event/player1 "Aleksandar Pesic"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_5423070"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Adrien Regattin"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5423152"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Wissam Ben Yedder"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5423172"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Eric Bautheac"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5423232"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Steeve Yago"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5423253"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_7672"}

{:event/type "shotoff"
:event/elapsed 78
:event/subtype "shot"
:event/player1 "Martin Braithwaite"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5423254"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Francois Moubandje"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5423294"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_7672"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Marko Basa"
:event/subtype "pushing"
:event/player1 "Tongo Hamed Doumbia"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5423315"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_7672"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Renato Civelli"
:event/player1 "Aleksandar Pesic"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5423341"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Aleksandar Pesic"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5423377"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Tongo Hamed Doumbia"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5423407"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Yassine Benzia"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5423420"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_7672"}

{:event/type "corner"
:event/elapsed 90
:event/subtype "short_left"
:event/player1 "Sofiane Boufal"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_5423434"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Yassine Benzia"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_5423435"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_7672"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "distance"
:event/player1 "Francois Moubandje"
:event/sortorder 6
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5423451"
:event/minute 91
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Steeve Yago"
:event/sortorder 9
:event/team "away"
:event/event_type "cross"
:event/id "event_5423465"
:event/minute 92
:event/match_id "match_7672"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "diving"
:event/player1 "Sofiane Boufal"
:event/sortorder 11
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5423477"
:event/minute 93
:event/match_id "match_7672"}

{:event/type "card"
:event/elapsed_plus 3
:event/elapsed 90
:event/card_type "y"
:event/subtype "diving"
:event/player1 "Sofiane Boufal"
:event/sortorder 12
:event/team "home"
:event/event_type "card"
:event/id "event_5423479"
:event/minute 93
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Adrien Regattin"
:event/sortorder 13
:event/team "away"
:event/event_type "cross"
:event/id "event_5423487"
:event/minute 93
:event/match_id "match_7672"}

{:event/type "corner"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross_right"
:event/player1 "Adrien Regattin"
:event/sortorder 17
:event/team "away"
:event/event_type "corner"
:event/id "event_5423498"
:event/minute 94
:event/match_id "match_7672"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Pantxi Sirieix"
:event/sortorder 19
:event/team "away"
:event/event_type "cross"
:event/id "event_5423501"
:event/minute 94
:event/match_id "match_7672"}


]

