
;;# data
[
{:match/id "match_7306"
:match/league "France Ligue 1"
:match/hometeam "Stade Rennais FC"
:match/awayteam "En Avant de Guingamp"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "foulcommit"
:event/elapsed 1
:event/player2 "Jeremy Pied"
:event/player1 "Paul-Georges Ntep"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4347726"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_7306"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Benjamin Andre"
:event/player1 "Mustapha Diallo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4347737"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_7306"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Lionel Mathis"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4347559"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_7306"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Benjamin Andre"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4347746"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_7306"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Cheikh Mbengue"
:event/player1 "Jeremy Pied"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4347757"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_7306"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Christophe Mandanne"
:event/subtype "pushing"
:event/player1 "Benjamin Andre"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4347657"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_7306"}

{:event/type "shotoff"
:event/elapsed 9
:event/subtype "deflected"
:event/player1 "Christophe Mandanne"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4347792"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_7306"}

{:event/type "corner"
:event/elapsed 10
:event/subtype "cross_right"
:event/player1 "Jeremy Pied"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4347771"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_7306"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Pedro Henrique"
:event/player1 "Thibault Giresse"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4347911"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_7306"}

{:event/type "card"
:event/elapsed 16
:event/card_type "y"
:event/player1 "Thibault Giresse"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_4347921"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_7306"}

{:event/type "shotoff"
:event/elapsed 16
:event/subtype "distance"
:event/player1 "Jeremy Pied"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4347809"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_7306"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Pedro Henrique"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4347832"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_7306"}

{:event/type "corner"
:event/elapsed 18
:event/subtype "cross_right"
:event/player1 "Paul-Georges Ntep"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4347851"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_7306"}

{:event/type "corner"
:event/elapsed 18
:event/subtype "cross_right"
:event/player1 "Paul-Georges Ntep"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_4347855"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_7306"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_4347892"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_7306"}

{:event/type "shotoff"
:event/elapsed 23
:event/subtype "distance"
:event/player1 "Cheikh Mbengue"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4347994"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_7306"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Cheikh Mbengue"
:event/player1 "Christophe Mandanne"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4348069"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_7306"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Jeremy Pied"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4348079"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_7306"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Younousse Sankhare"
:event/player1 "Gelson Fernandes"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4348105"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_7306"}

{:event/type "foulcommit"
:event/elapsed 30
:event/player2 "Sylvain Armand"
:event/player1 "Younousse Sankhare"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4348108"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_7306"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Thibault Giresse"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4348111"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_7306"}

{:event/type "foulcommit"
:event/elapsed 34
:event/player2 "Benjamin Andre"
:event/player1 "Mustapha Diallo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4348157"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_7306"}

{:event/type "shoton"
:event/elapsed 35
:event/subtype "distance"
:event/player1 "Lionel Mathis"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4348183"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_7306"}

{:event/type "corner"
:event/elapsed 35
:event/subtype "cross_left"
:event/player1 "Jeremy Pied"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4348186"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_7306"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Lionel Mathis"
:event/subtype "serious_foul"
:event/player1 "Pedro Henrique"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4348201"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_7306"}

{:event/type "card"
:event/elapsed 36
:event/card_type "y"
:event/player1 "Pedro Henrique"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4348209"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_7306"}

{:event/type "corner"
:event/elapsed 40
:event/subtype "cross_right"
:event/player1 "Pedro Henrique"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4348284"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_7306"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Pedro Henrique"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4348291"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_7306"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Mustapha Diallo"
:event/subtype "pushing"
:event/player1 "Benjamin Andre"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4348324"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_7306"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Cheikh Mbengue"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4348372"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_7306"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Younousse Sankhare"
:event/player1 "Paul-Georges Ntep"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4348765"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_7306"}

{:event/type "shoton"
:event/elapsed 44
:event/subtype "shot"
:event/player1 "Paul-Georges Ntep"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4348376"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_7306"}

{:event/type "foulcommit"
:event/elapsed 46
:event/player2 "Reynald Lemaitre"
:event/player1 "Abdoulaye Doucoure"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4348589"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_7306"}

{:event/type "foulcommit"
:event/elapsed 47
:event/player2 "Benjamin Andre"
:event/player1 "Mustapha Diallo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4348599"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_7306"}

{:event/type "shoton"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "blocked_shot"
:event/player1 "Pedro Henrique"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4348440"
:event/minute 47
:event/match_id "match_7306"}

{:event/type "card"
:event/elapsed 47
:event/card_type "y"
:event/player1 "Mustapha Diallo"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4348604"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_7306"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Younousse Sankhare"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4348636"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_7306"}

{:event/type "shotoff"
:event/elapsed 50
:event/subtype "deflected"
:event/player1 "Lars Jacobsen"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4348642"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_7306"}

{:event/type "corner"
:event/elapsed 50
:event/subtype "cross_right"
:event/player1 "Jeremy Pied"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4348647"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_7306"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Paul-Georges Ntep"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4348665"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_7306"}

{:event/type "shoton"
:event/elapsed 51
:event/subtype "header"
:event/player1 "Pedro Henrique"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4348667"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_7306"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Mustapha Diallo"
:event/player1 "Sylvain Armand"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4348696"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_7306"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Mustapha Diallo"
:event/player1 "Pedro Henrique"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4348717"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_7306"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Jeremy Pied"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4348701"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_7306"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Younousse Sankhare"
:event/player1 "Gelson Fernandes"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4348859"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_7306"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Lionel Mathis"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4348790"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_7306"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Pedro Henrique"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4348874"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_7306"}

{:event/type "shotoff"
:event/elapsed 56
:event/subtype "header"
:event/player1 "Ola Toivonen"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4348882"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_7306"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Paul-Georges Ntep"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4348801"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_7306"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Gelson Fernandes"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4348834"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_7306"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player2 "Mustapha Diallo"
:event/player1 "Cheikh Mbengue"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4348974"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_7306"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Jeremy Sorbon"
:event/player1 "Ola Toivonen"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4348896"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_7306"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Benjamin Andre"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4348913"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_7306"}

{:event/type "corner"
:event/elapsed 62
:event/subtype "cross_right"
:event/player1 "Benjamin Andre"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4348931"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_7306"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Cheikh Mbengue"
:event/subtype "trip"
:event/player1 "Lionel Mathis"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4348954"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_7306"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Cheikh Mbengue"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4349039"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_7306"}

{:event/type "shoton"
:event/elapsed 64
:event/subtype "blocked_header"
:event/player1 "Ola Toivonen"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_4349040"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_7306"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Paul-Georges Ntep"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4348983"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_7306"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Gelson Fernandes"
:event/player1 "Lionel Mathis"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4349061"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_7306"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Gelson Fernandes"
:event/player1 "Mustapha Diallo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4349089"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_7306"}

{:event/type "corner"
:event/elapsed 72
:event/subtype "cross_left"
:event/player1 "Kamil Grosicki"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4349112"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_7306"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Lionel Mathis"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4349139"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_7306"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Cheikh Mbengue"
:event/subtype "serious_foul"
:event/player1 "Sambou Yatabare"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4349189"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_7306"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Kamil Grosicki"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4349148"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_7306"}

{:event/type "card"
:event/elapsed 75
:event/card_type "r"
:event/player1 "Sambou Yatabare"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_4349214"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_7306"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Romain Danze"
:event/subtype "dangerous_play"
:event/player1 "Lionel Mathis"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4349240"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_7306"}

{:event/type "card"
:event/elapsed 77
:event/card_type "y"
:event/player1 "Lionel Mathis"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4349252"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_7306"}

{:event/type "card"
:event/elapsed 77
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Abdoulaye Doucoure"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_4349257"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_7306"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Mexer"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4349263"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_7306"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Paul-Georges Ntep"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4349281"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_7306"}

{:event/type "shoton"
:event/elapsed 79
:event/subtype "header"
:event/player1 "Abdoulaye Doucoure"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4349284"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_7306"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Kamil Grosicki"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4349343"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_7306"}

{:event/type "goal"
:event/elapsed 80
:event/player2 "Kamil Grosicki"
:event/subtype "volley"
:event/player1 "Ola Toivonen"
:event/sortorder 1
:event/team "home"
:event/id "event_4349295"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_7306"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Mustapha Diallo"
:event/player1 "Gelson Fernandes"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4349351"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_7306"}

{:event/type "card"
:event/elapsed 82
:event/card_type "y"
:event/player1 "Gelson Fernandes"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4349353"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_7306"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Claudio Beauvue"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4349376"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_7306"}

{:event/type "shotoff"
:event/elapsed 84
:event/subtype "shot"
:event/player1 "Mahamadou Habib Habibou"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4349391"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_7306"}

{:event/type "shoton"
:event/elapsed 86
:event/subtype "shot"
:event/player1 "Abdoulaye Doucoure"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4349446"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_7306"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Lars Jacobsen"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4349628"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_7306"}

{:event/type "shotoff"
:event/elapsed 87
:event/subtype "header"
:event/player1 "Christophe Mandanne"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4349490"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_7306"}

{:event/type "shoton"
:event/elapsed 90
:event/subtype "big chance shot"
:event/player1 "Mahamadou Habib Habibou"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4349532"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_7306"}

{:event/type "corner"
:event/elapsed 90
:event/subtype "short_left"
:event/player1 "Paul-Georges Ntep"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4349533"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_7306"}

{:event/type "corner"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross_left"
:event/player1 "Kamil Grosicki"
:event/sortorder 5
:event/team "home"
:event/event_type "corner"
:event/id "event_4349666"
:event/minute 91
:event/match_id "match_7306"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Lionel Mathis"
:event/player1 "Benjamin Andre"
:event/sortorder 8
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4349641"
:event/minute 93
:event/match_id "match_7306"}

{:event/type "shotoff"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "direct_freekick"
:event/player1 "Lionel Mathis"
:event/sortorder 9
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4349648"
:event/minute 93
:event/match_id "match_7306"}

{:event/type "corner"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "cross_left"
:event/player1 "Lionel Mathis"
:event/sortorder 11
:event/team "away"
:event/event_type "corner"
:event/id "event_4349662"
:event/minute 95
:event/match_id "match_7306"}


]

