
;;# data
[
{:match/id "match_10718"
:match/league "Italy Serie A"
:match/hometeam "Fiorentina"
:match/awayteam "Milan"
:match/score "1:2"
:match/hometeam_goals "1"
:match/awayteam_goals "2"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Marco Borriello"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_967607"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Ronaldinho"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_967610"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_10718"}

{:event/type "corner"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Ronaldinho"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_967610"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_10718"}

{:event/type "shoton"
:event/elapsed 2
:event/subtype "blocked_shot"
:event/player1 "Andrea Pirlo"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_967612"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Juan Vargas"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_967613"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_967620"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_10718"}

{:event/type "corner"
:event/elapsed 2
:event/subtype "cross"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_967620"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_10718"}

{:event/type "shoton"
:event/elapsed 3
:event/subtype "header"
:event/player1 "Alberto Gilardino"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_967622"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Lorenzo De Silvestri"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_967629"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_10718"}

{:event/type "shoton"
:event/elapsed 5
:event/subtype "blocked_shot"
:event/player1 "Marco Borriello"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_967635"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Ronaldinho"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_967638"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_10718"}

{:event/type "corner"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Ronaldinho"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_967638"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/sortorder 5
:event/team "away"
:event/event_type "cross"
:event/id "event_967641"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Ronaldinho"
:event/sortorder 6
:event/team "away"
:event/event_type "corner"
:event/id "event_967644"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_10718"}

{:event/type "corner"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Ronaldinho"
:event/sortorder 6
:event/team "away"
:event/event_type "corner"
:event/id "event_967644"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_10718"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Thiago Silva"
:event/subtype "pushing"
:event/player1 "Alberto Gilardino"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_967659"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_10718"}

{:event/type "shotoff"
:event/elapsed 11
:event/subtype "volley"
:event/player1 "Stevan Jovetic"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_967685"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_10718"}

{:event/type "foulcommit"
:event/elapsed 12
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_967702"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_10718"}

{:event/type "shotoff"
:event/elapsed 14
:event/subtype "shot"
:event/player1 "Stevan Jovetic"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_967711"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_967712"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_10718"}

{:event/type "goal"
:event/elapsed 14
:event/subtype "shot"
:event/player1 "Alberto Gilardino"
:event/sortorder 3
:event/team "home"
:event/id "event_967708"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Marco Marchionni"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_967717"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_10718"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "Ronaldinho"
:event/player1 "Riccardo Montolivo"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_967731"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_10718"}

{:event/type "foulcommit"
:event/elapsed 17
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_967741"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_10718"}

{:event/type "shoton"
:event/elapsed 19
:event/subtype "blocked_shot"
:event/player1 "Marco Marchionni"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_967756"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_10718"}

{:event/type "shoton"
:event/elapsed 19
:event/subtype "distance"
:event/player1 "Riccardo Montolivo"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_967757"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_10718"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Ronaldinho"
:event/player1 "Marco Marchionni"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_967761"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_10718"}

{:event/type "card"
:event/elapsed 20
:event/card_type "y"
:event/player1 "Marco Marchionni"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_967762"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Juan Vargas"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_967784"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_10718"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Alessandro Nesta"
:event/player1 "Alberto Gilardino"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_967800"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Lorenzo De Silvestri"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_967807"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_10718"}

{:event/type "shoton"
:event/elapsed 27
:event/subtype "blocked_shot"
:event/player1 "Alberto Gilardino"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_967810"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_10718"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Stevan Jovetic"
:event/subtype "pushing"
:event/player1 "Massimo Ambrosini"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_967812"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_967822"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Juan Vargas"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_967832"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_10718"}

{:event/type "corner"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Juan Vargas"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_967832"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_967836"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_10718"}

{:event/type "shotoff"
:event/elapsed 30
:event/subtype "deflected"
:event/player1 "Stevan Jovetic"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_967840"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_967841"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_10718"}

{:event/type "corner"
:event/elapsed 30
:event/subtype "cross"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_967841"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_10718"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Alberto Gilardino"
:event/player1 "Gennaro Gattuso"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_967860"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_10718"}

{:event/type "shotoff"
:event/elapsed 34
:event/subtype "shot"
:event/player1 "Juan Vargas"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_967861"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_10718"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Ignazio Abate"
:event/player1 "Juan Vargas"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_967894"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_967899"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_10718"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player1 "Gennaro Gattuso"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_967904"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_10718"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Alessandro Nesta"
:event/player1 "Alberto Gilardino"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_967910"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Ignazio Abate"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_967916"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Ronaldinho"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_967920"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_10718"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Stevan Jovetic"
:event/subtype "pushing"
:event/player1 "Andrea Pirlo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_967925"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Marco Marchionni"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_967929"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_967931"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Marco Donadel"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_967934"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_10718"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Ronaldinho"
:event/player1 "Riccardo Montolivo"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_967938"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_10718"}

{:event/type "shotoff"
:event/elapsed 44
:event/subtype "shot"
:event/player1 "Mathieu Flamini"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_967942"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_967991"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_10718"}

{:event/type "foulcommit"
:event/elapsed 46
:event/subtype "pushing"
:event/player1 "Alberto Gilardino"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_967992"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_10718"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 45
:event/player1 "Mathieu Flamini"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_967954"
:event/minute 48
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Andrea Pirlo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_968012"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Alexandre Pato"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_968017"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_10718"}

{:event/type "shoton"
:event/elapsed 53
:event/subtype "shot"
:event/player1 "Juan Vargas"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_968033"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_10718"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player1 "Stevan Jovetic"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_968038"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_10718"}

{:event/type "shotoff"
:event/elapsed 54
:event/subtype "shot"
:event/player1 "Marco Marchionni"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_968041"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_10718"}

{:event/type "foulcommit"
:event/elapsed 55
:event/subtype "hands"
:event/player1 "Juan Vargas"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_968046"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Alexandre Pato"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_968048"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Ronaldinho"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_968056"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_10718"}

{:event/type "shotoff"
:event/elapsed 56
:event/subtype "shot"
:event/player1 "Alexandre Pato"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_968058"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Ronaldinho"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_968071"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_10718"}

{:event/type "corner"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Ronaldinho"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_968071"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Ronaldinho"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_968074"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_10718"}

{:event/type "corner"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Ronaldinho"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_968074"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Andrea Pirlo"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_968078"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_968079"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_10718"}

{:event/type "corner"
:event/elapsed 58
:event/subtype "cross"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_968079"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_968082"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_10718"}

{:event/type "corner"
:event/elapsed 58
:event/subtype "cross"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_968082"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_10718"}

{:event/type "foulcommit"
:event/elapsed 60
:event/subtype "pushing"
:event/player1 "Riccardo Montolivo"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_968097"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_10718"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player1 "Marco Borriello"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_968099"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_10718"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Marco Marchionni"
:event/player1 "Gennaro Gattuso"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_968113"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_10718"}

{:event/type "shoton"
:event/elapsed 64
:event/subtype "blocked_shot"
:event/player1 "Riccardo Montolivo"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_968121"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_968125"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_968128"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_10718"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Andrea Pirlo"
:event/player1 "Cristiano Zanetti"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_968134"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Lorenzo De Silvestri"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_968141"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Juan Vargas"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_968150"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_10718"}

{:event/type "foulcommit"
:event/elapsed 70
:event/player2 "Keirrison"
:event/subtype "pushing"
:event/player1 "Alessandro Nesta"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_968154"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Marco Marchionni"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_968157"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_10718"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Andrea Pirlo"
:event/subtype "serious_foul"
:event/player1 "Marco Donadel"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_968163"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_10718"}

{:event/type "foulcommit"
:event/elapsed 72
:event/player2 "Felipe"
:event/player1 "Marco Borriello"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_968172"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_968183"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_10718"}

{:event/type "shoton"
:event/elapsed 75
:event/subtype "shot"
:event/player1 "Riccardo Montolivo"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_968189"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_10718"}

{:event/type "shotoff"
:event/elapsed 78
:event/subtype "shot"
:event/player1 "Alexandre Pato"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_968202"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Ignazio Abate"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_968223"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_10718"}

{:event/type "goal"
:event/elapsed 81
:event/subtype "shot"
:event/player1 "Klaas Jan Huntelaar"
:event/sortorder 2
:event/team "away"
:event/id "event_968226"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Lorenzo De Silvestri"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_968237"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_10718"}

{:event/type "card"
:event/elapsed 83
:event/card_type "y"
:event/player1 "Marek Jankulovski"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_968239"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_968242"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_10718"}

{:event/type "corner"
:event/elapsed 84
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_968242"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Marco Marchionni"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_968244"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_968247"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_10718"}

{:event/type "corner"
:event/elapsed 84
:event/subtype "cross"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_968247"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_968250"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_968262"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_10718"}

{:event/type "shoton"
:event/elapsed 86
:event/subtype "big chance shot"
:event/player1 "Keirrison"
:event/sortorder 7
:event/team "home"
:event/event_type "shoton"
:event/id "event_968273"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Alexandre Pato"
:event/sortorder 8
:event/team "away"
:event/event_type "cross"
:event/id "event_968274"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Ronaldinho"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_968281"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_10718"}

{:event/type "corner"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Ronaldinho"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_968281"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_10718"}

{:event/type "shoton"
:event/elapsed 88
:event/subtype "distance"
:event/player1 "Juan Vargas"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_968290"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_968292"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_10718"}

{:event/type "corner"
:event/elapsed 88
:event/subtype "cross"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_968292"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_968293"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_10718"}

{:event/type "corner"
:event/elapsed 88
:event/subtype "cross"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_968293"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_10718"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player2 "Ronaldinho"
:event/subtype "pushing"
:event/player1 "Lorenzo De Silvestri"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_968302"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_10718"}

{:event/type "corner"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "short"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_968304"
:event/minute 91
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Marco Marchionni"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_968305"
:event/minute 91
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_968309"
:event/minute 91
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Cristiano Zanetti"
:event/sortorder 7
:event/team "home"
:event/event_type "cross"
:event/id "event_968311"
:event/minute 91
:event/match_id "match_10718"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Marco Marchionni"
:event/sortorder 8
:event/team "home"
:event/event_type "shotoff"
:event/id "event_968312"
:event/minute 91
:event/match_id "match_10718"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Ronaldinho"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_968315"
:event/minute 92
:event/match_id "match_10718"}

{:event/type "goal"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Alexandre Pato"
:event/sortorder 2
:event/team "away"
:event/id "event_968314"
:event/event_type "goal"
:event/goal_type "n"
:event/minute 92
:event/match_id "match_10718"}

{:event/type "card"
:event/elapsed_plus 3
:event/elapsed 90
:event/card_type "y"
:event/player1 "Alexandre Pato"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_969052"
:event/minute 93
:event/match_id "match_10718"}


]

