
;;# data
[
{:match/id "match_10494"
:match/league "Italy Serie A"
:match/hometeam "Siena"
:match/awayteam "Lazio"
:match/score "2:0"
:match/hometeam_goals "2"
:match/awayteam_goals "0"}

{:event/type "goal"
:event/elapsed 25
:event/player1 "Emanuele Calaio"
:event/sortorder 0
:event/team "home"
:event/id "event_632305"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_10494"}

{:event/type "card"
:event/elapsed 30
:event/card_type "y"
:event/player1 "Goncalo Brandao"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_632397"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_10494"}

{:event/type "card"
:event/elapsed 54
:event/card_type "y"
:event/player1 "Paul Constantin Codrea"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_632661"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_10494"}

{:event/type "card"
:event/elapsed 74
:event/card_type "y"
:event/player1 "Sebastiano Siviglia"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_632920"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_10494"}

{:event/type "goal"
:event/elapsed 85
:event/player1 "Massimo Maccarone"
:event/sortorder 0
:event/team "home"
:event/id "event_632996"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_10494"}


]

