
;;# data
[
{:match/id "match_6815"
:match/league "France Ligue 1"
:match/hometeam "LOSC Lille"
:match/awayteam "Stade Rennais FC"
:match/score "1:1"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "goal"
:event/elapsed 34
:event/player1 "Salomon Kalou"
:event/sortorder 0
:event/team "home"
:event/id "event_3225624"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_6815"}

{:event/type "goal"
:event/elapsed 41
:event/player1 "Abdoulaye Doucoure"
:event/sortorder 0
:event/team "away"
:event/id "event_3225626"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_6815"}

{:event/type "card"
:event/elapsed 66
:event/card_type "y"
:event/player1 "Djibril Sidibe"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3225639"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_6815"}


]

