
;;# data
[
{:match/id "match_15479"
:match/league "Netherlands Eredivisie"
:match/hometeam "SC Heerenveen"
:match/awayteam "Excelsior"
:match/score "2:1"
:match/hometeam_goals "2"
:match/awayteam_goals "1"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Daryl van Mieghem"
:event/subtype "trip"
:event/player1 "Joost van Aken"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5099099"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_15479"}

{:event/type "card"
:event/elapsed 4
:event/card_type "y"
:event/player1 "Joost van Aken"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_5099100"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_15479"}

{:event/type "shoton"
:event/elapsed 5
:event/subtype "shot"
:event/player1 "Daryl van Mieghem"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_5099101"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_15479"}

{:event/type "shotoff"
:event/elapsed 5
:event/subtype "deflected"
:event/player1 "Adil Auassar"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5099102"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_15479"}

{:event/type "corner"
:event/elapsed 5
:event/subtype "cross_left"
:event/player1 "Jeff Stans"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_5099103"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_15479"}

{:event/type "corner"
:event/elapsed 5
:event/subtype "cross_left"
:event/player1 "Jeff Stans"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_5099105"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_15479"}

{:event/type "shotoff"
:event/elapsed 8
:event/subtype "bad shot"
:event/player1 "Jerry St. Juste"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5099110"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_15479"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Tom van Weert"
:event/subtype "trip"
:event/player1 "Stefano Marzo"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5099113"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_15479"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Khalid Karami"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5099114"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_15479"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Joost van Aken"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5099116"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_15479"}

{:event/type "shoton"
:event/elapsed 10
:event/subtype "big chance shot"
:event/player1 "Stefano Marzo"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_5099118"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_15479"}

{:event/type "shoton"
:event/elapsed 12
:event/subtype "shot"
:event/player1 "unknown"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_5099122"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_15479"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Morten Thorsby"
:event/player1 "Jurgen Mattheij"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5099124"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_15479"}

{:event/type "cross"
:event/elapsed 13
:event/subtype "cross"
:event/player1 "Morten Thorsby"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_5099125"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_15479"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Stefano Marzo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5099127"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_15479"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Morten Thorsby"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5099129"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_15479"}

{:event/type "corner"
:event/elapsed 15
:event/subtype "cross_right"
:event/player1 "Luciano Slagveer"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5099130"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_15479"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Caner Cavlan"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_5099133"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_15479"}

{:event/type "shotoff"
:event/elapsed 15
:event/subtype "miss_kick"
:event/player1 "Luciano Slagveer"
:event/sortorder 5
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5099135"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_15479"}

{:event/type "foulcommit"
:event/elapsed 17
:event/subtype "hands"
:event/player1 "Stefano Marzo"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5099138"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_15479"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Jeff Stans"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5099139"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_15479"}

{:event/type "shoton"
:event/elapsed 17
:event/subtype "blocked_shot"
:event/player1 "Brandley Kuwas"
:event/sortorder 4
:event/team "away"
:event/event_type "shoton"
:event/id "event_5099141"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_15479"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/sortorder 2
:event/team "home"
:event/event_type "throwin"
:event/id "event_5099144"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_15479"}

{:event/type "shotoff"
:event/elapsed 19
:event/subtype "deflected"
:event/player1 "Jerry St. Juste"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5099146"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_15479"}

{:event/type "corner"
:event/elapsed 20
:event/subtype "cross_right"
:event/player1 "Caner Cavlan"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5099147"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_15479"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Morten Thorsby"
:event/subtype "pull"
:event/player1 "Ricky Kruys"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5099150"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_15479"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Caner Cavlan"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5099151"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_15479"}

{:event/type "corner"
:event/elapsed 22
:event/subtype "cross_left"
:event/player1 "Caner Cavlan"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_5099153"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_15479"}

{:event/type "goal"
:event/elapsed 22
:event/player2 "unknown"
:event/subtype "volley"
:event/player1 "Kenny Otigba"
:event/sortorder 4
:event/team "home"
:event/id "event_5099156"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_15479"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Morten Thorsby"
:event/player1 "Ricky Kruys"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5099157"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_15479"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Morten Thorsby"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5099158"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_15479"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Luciano Slagveer"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5099164"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_15479"}

{:event/type "shotoff"
:event/elapsed 25
:event/subtype "header"
:event/player1 "unknown"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5099165"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_15479"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Jeff Stans"
:event/player1 "Caner Cavlan"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5099167"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_15479"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Stefano Marzo"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5099169"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_15479"}

{:event/type "corner"
:event/elapsed 26
:event/subtype "cross_right"
:event/player1 "Caner Cavlan"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_5099170"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_15479"}

{:event/type "shoton"
:event/elapsed 26
:event/subtype "big chance shot"
:event/player1 "Kenny Otigba"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_5099172"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_15479"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_5099174"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_15479"}

{:event/type "shoton"
:event/elapsed 28
:event/subtype "volley"
:event/player1 "Luciano Slagveer"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_5099176"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_15479"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Adil Auassar"
:event/player1 "Morten Thorsby"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5099177"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_15479"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Jeff Stans"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5099178"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_15479"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Erwin Mulder"
:event/subtype "obstruction"
:event/player1 "Jurgen Mattheij"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5099180"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_15479"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Luciano Slagveer"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5099199"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_15479"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Daryl van Mieghem"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5099210"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_15479"}

{:event/type "shoton"
:event/elapsed 34
:event/subtype "blocked_shot"
:event/player1 "Sam Larsson"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5099224"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_15479"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Sam Larsson"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5099227"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_15479"}

{:event/type "shotoff"
:event/elapsed 34
:event/subtype "shot"
:event/player1 "unknown"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5099229"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_15479"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Luciano Slagveer"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5099246"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_15479"}

{:event/type "corner"
:event/elapsed 41
:event/subtype "cross_left"
:event/player1 "Caner Cavlan"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5099287"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_15479"}

{:event/type "shotoff"
:event/elapsed 41
:event/subtype "bicycle_kick"
:event/player1 "Morten Thorsby"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5099290"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_15479"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Daryl van Mieghem"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5099300"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_15479"}

{:event/type "shoton"
:event/elapsed 43
:event/subtype "header"
:event/player1 "Ricky Kruys"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_5099303"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_15479"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Brandley Kuwas"
:event/subtype "serious_foul"
:event/player1 "Luciano Slagveer"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5099308"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_15479"}

{:event/type "shotoff"
:event/elapsed 45
:event/subtype "post"
:event/player1 "Jerry St. Juste"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5099327"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_15479"}

{:event/type "foulcommit"
:event/elapsed 46
:event/player2 "Bas Kuipers"
:event/subtype "pull"
:event/player1 "Stefano Marzo"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5099450"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_15479"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Bas Kuipers"
:event/subtype "trip"
:event/player1 "Luciano Slagveer"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5099456"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_15479"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Stanley Elbers"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5099459"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_15479"}

{:event/type "corner"
:event/elapsed 49
:event/subtype "cross_right"
:event/player1 "Jeff Stans"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_5099466"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_15479"}

{:event/type "shoton"
:event/elapsed 49
:event/subtype "distance"
:event/player1 "Brandley Kuwas"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_5099468"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_15479"}

{:event/type "shoton"
:event/elapsed 51
:event/subtype "big chance shot"
:event/player1 "Luciano Slagveer"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5099481"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_15479"}

{:event/type "shoton"
:event/elapsed 51
:event/subtype "header"
:event/player1 "unknown"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_5099483"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_15479"}

{:event/type "corner"
:event/elapsed 52
:event/subtype "cross_left"
:event/player1 "Adil Auassar"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_5099489"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_15479"}

{:event/type "shotoff"
:event/elapsed 52
:event/subtype "header"
:event/player1 "Stanley Elbers"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5099491"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_15479"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Bas Kuipers"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5099502"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_15479"}

{:event/type "goal"
:event/elapsed 55
:event/player2 "Joost van Aken"
:event/subtype "distance"
:event/player1 "Sam Larsson"
:event/sortorder 2
:event/team "home"
:event/id "event_5099514"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_15479"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Luciano Slagveer"
:event/subtype "trip"
:event/player1 "Bas Kuipers"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5099528"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_15479"}

{:event/type "shotoff"
:event/elapsed 59
:event/subtype "bad shot"
:event/player1 "Jerry St. Juste"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5099549"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_15479"}

{:event/type "shoton"
:event/elapsed 62
:event/subtype "distance"
:event/player1 "Sam Larsson"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_5099557"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_15479"}

{:event/type "shoton"
:event/elapsed 62
:event/subtype "shot"
:event/player1 "Morten Thorsby"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_5099559"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_15479"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Khalid Karami"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_5099561"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_15479"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Stefano Marzo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5099562"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_15479"}

{:event/type "shoton"
:event/elapsed 63
:event/subtype "blocked_shot"
:event/player1 "Sam Larsson"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_5099564"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_15479"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Sander Fischer"
:event/subtype "trip"
:event/player1 "Sam Larsson"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5099565"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_15479"}

{:event/type "shoton"
:event/elapsed 64
:event/subtype "distance"
:event/player1 "Brandley Kuwas"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_5099566"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_15479"}

{:event/type "shoton"
:event/elapsed 66
:event/subtype "shot"
:event/player1 "Adil Auassar"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_5099569"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_15479"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Sander Fischer"
:event/player1 "unknown"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5099575"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_15479"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Tom van Weert"
:event/subtype "from_behind"
:event/player1 "Joey van den Berg"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5099576"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_15479"}

{:event/type "shotoff"
:event/elapsed 70
:event/subtype "big chance shot"
:event/player1 "Luciano Slagveer"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5099578"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_15479"}

{:event/type "shoton"
:event/elapsed 70
:event/subtype "distance"
:event/player1 "Caner Cavlan"
:event/sortorder 5
:event/team "home"
:event/event_type "shoton"
:event/id "event_5099581"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_15479"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Lucas Bijker"
:event/player1 "Stanley Elbers"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5099582"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_15479"}

{:event/type "corner"
:event/elapsed 75
:event/subtype "cross_right"
:event/player1 "Adil Auassar"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_5099589"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_15479"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Adil Auassar"
:event/sortorder 5
:event/team "away"
:event/event_type "cross"
:event/id "event_5099597"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_15479"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Joey van den Berg"
:event/subtype "pull"
:event/player1 "Tom van Weert"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5099618"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_15479"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Kevin Vermeulen"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5099624"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_15479"}

{:event/type "shoton"
:event/elapsed 79
:event/subtype "shot"
:event/player1 "unknown"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5099640"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_15479"}

{:event/type "shotoff"
:event/elapsed 81
:event/subtype "bad shot"
:event/player1 "unknown"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5099658"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_15479"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Luciano Slagveer"
:event/subtype "pull"
:event/player1 "Bas Kuipers"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5099661"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_15479"}

{:event/type "shoton"
:event/elapsed 85
:event/subtype "blocked_shot"
:event/player1 "Luciano Slagveer"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_5099700"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_15479"}

{:event/type "shotoff"
:event/elapsed 86
:event/subtype "distance"
:event/player1 "Branco van den Boomen"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5099706"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_15479"}

{:event/type "foulcommit"
:event/elapsed 87
:event/player2 "Bas Kuipers"
:event/player1 "unknown"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5099722"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_15479"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Stanley Elbers"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5099726"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_15479"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player2 "Bas Kuipers"
:event/subtype "pushing"
:event/player1 "Morten Thorsby"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5099737"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_15479"}

{:event/type "card"
:event/elapsed 89
:event/card_type "y"
:event/subtype "verbal_abuse"
:event/player1 "Morten Thorsby"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_5099739"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_15479"}

{:event/type "corner"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "short_right"
:event/player1 "Adil Auassar"
:event/sortorder 5
:event/team "away"
:event/event_type "corner"
:event/id "event_5099757"
:event/minute 91
:event/match_id "match_15479"}

{:event/type "shoton"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "blocked_shot"
:event/player1 "Kevin Vermeulen"
:event/sortorder 7
:event/team "away"
:event/event_type "shoton"
:event/id "event_5099763"
:event/minute 92
:event/match_id "match_15479"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "penalty"
:event/player1 "Kenny Otigba"
:event/sortorder 8
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5099761"
:event/minute 92
:event/match_id "match_15479"}

{:event/type "goal"
:event/elapsed_plus 2
:event/elapsed 90
:event/player1 "Jeff Stans"
:event/sortorder 8
:event/team "away"
:event/id "event_5099765"
:event/event_type "goal"
:event/goal_type "p"
:event/minute 92
:event/match_id "match_15479"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "unknown"
:event/player1 "Bas Kuipers"
:event/sortorder 9
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5099776"
:event/minute 93
:event/match_id "match_15479"}


]

