
;;# data
[
{:match/id "match_15579"
:match/league "Netherlands Eredivisie"
:match/hometeam "PEC Zwolle"
:match/awayteam "De Graafschap"
:match/score "2:1"
:match/hometeam_goals "2"
:match/awayteam_goals "1"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Wouter Marinus"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5363093"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_15579"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "Bart Schenkeveld"
:event/player1 "Cas Peters"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5363113"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_15579"}

{:event/type "shoton"
:event/elapsed 4
:event/subtype "big chance shot"
:event/player1 "Lars Veldwijk"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_5363121"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Bryan Smeets"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5363131"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_15579"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Stefan Nijland"
:event/player1 "Bryan Smeets"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5363136"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Lars Veldwijk"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5363139"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_15579"}

{:event/type "corner"
:event/elapsed 6
:event/subtype "cross_left"
:event/player1 "Queensy Menig"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_5363149"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Cas Peters"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5363174"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_15579"}

{:event/type "foulcommit"
:event/elapsed 8
:event/player2 "Wout Brama"
:event/player1 "Bryan Smeets"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5363177"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_15579"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Bart van Hintum"
:event/subtype "dangerous_play"
:event/player1 "Youssef El Jebli"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5363230"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_15579"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Kingsley Ehizibue"
:event/player1 "Jeroen Tesselaar"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5363234"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_15579"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Mark Diemers"
:event/player1 "Wout Brama"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5363254"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_15579"}

{:event/type "corner"
:event/elapsed 16
:event/subtype "cross_right"
:event/player1 "Bryan Smeets"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_5363281"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Youssef El Jebli"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5363289"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_15579"}

{:event/type "shotoff"
:event/elapsed 16
:event/subtype "distance"
:event/player1 "Karim Tarfi"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5363293"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_15579"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Mark Diemers"
:event/player1 "Stefan Nijland"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5363301"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_15579"}

{:event/type "foulcommit"
:event/elapsed 17
:event/subtype "hands"
:event/player1 "Ted van de Pavert"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5363306"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Queensy Menig"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5363319"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_15579"}

{:event/type "shoton"
:event/elapsed 20
:event/subtype "blocked_shot"
:event/player1 "Queensy Menig"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5363337"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_15579"}

{:event/type "shotoff"
:event/elapsed 20
:event/subtype "shot"
:event/player1 "Stefan Nijland"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5363339"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_15579"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Mark Diemers"
:event/player1 "Wout Brama"
:event/sortorder 5
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5363345"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_15579"}

{:event/type "goal"
:event/elapsed 23
:event/player2 "Lars Veldwijk"
:event/subtype "shot"
:event/player1 "Stefan Nijland"
:event/sortorder 2
:event/team "home"
:event/id "event_5363361"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Karim Tarfi"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5363370"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_15579"}

{:event/type "shoton"
:event/elapsed 27
:event/subtype "big chance shot"
:event/player1 "Youssef El Jebli"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_5363392"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_15579"}

{:event/type "shoton"
:event/elapsed 27
:event/subtype "distance"
:event/player1 "Stefan Nijland"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_5363397"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_15579"}

{:event/type "corner"
:event/elapsed 28
:event/subtype "cross_left"
:event/player1 "Stefan Nijland"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5363402"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Mark Diemers"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5363422"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Bart Schenkeveld"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5363427"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_15579"}

{:event/type "goal"
:event/elapsed 32
:event/player2 "Lars Veldwijk"
:event/subtype "shot"
:event/player1 "Stefan Nijland"
:event/sortorder 2
:event/team "home"
:event/id "event_5363430"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_15579"}

{:event/type "shotoff"
:event/elapsed 34
:event/subtype "distance"
:event/player1 "Bryan Smeets"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5363449"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_15579"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Wout Brama"
:event/player1 "Karim Tarfi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5363466"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_15579"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Kingsley Ehizibue"
:event/player1 "Karim Tarfi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5363480"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_5363491"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_15579"}

{:event/type "shoton"
:event/elapsed 39
:event/subtype "blocked_shot"
:event/player1 "Queensy Menig"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_5363493"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_15579"}

{:event/type "shotoff"
:event/elapsed 39
:event/subtype "distance"
:event/player1 "Dirk Marcellis"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5363494"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_15579"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Wout Brama"
:event/player1 "Cas Peters"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5363505"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_15579"}

{:event/type "corner"
:event/elapsed 42
:event/subtype "cross_left"
:event/player1 "Stefan Nijland"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5363521"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_15579"}

{:event/type "shotoff"
:event/elapsed 42
:event/subtype "post"
:event/player1 "Thomas Lam"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5363523"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_15579"}

{:event/type "shoton"
:event/elapsed 42
:event/subtype "big chance shot"
:event/player1 "Stefan Nijland"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_5363525"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_15579"}

{:event/type "corner"
:event/elapsed 42
:event/subtype "cross_left"
:event/player1 "Stefan Nijland"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_5363527"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_15579"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Robin Propper"
:event/player1 "Lars Veldwijk"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5363529"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Youssef El Jebli"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5363535"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Jeroen Tesselaar"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5363541"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_15579"}

{:event/type "shotoff"
:event/elapsed 44
:event/subtype "big chance volley"
:event/player1 "Youssef El Jebli"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5363544"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Karim Tarfi"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5363572"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_15579"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "shot"
:event/player1 "Bryan Smeets"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5363574"
:event/minute 46
:event/match_id "match_15579"}

{:event/type "foulcommit"
:event/elapsed 47
:event/player2 "Bart Schenkeveld"
:event/player1 "Cas Peters"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5363691"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_15579"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Bart Schenkeveld"
:event/player1 "Cas Peters"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5363699"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_15579"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Lars Veldwijk"
:event/player1 "Ted van de Pavert"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5363705"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Stefan Nijland"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5363714"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_5363723"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_15579"}

{:event/type "corner"
:event/elapsed 51
:event/subtype "cross_left"
:event/player1 "Stefan Nijland"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_5363732"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_15579"}

{:event/type "corner"
:event/elapsed 53
:event/subtype "cross_right"
:event/player1 "Bryan Smeets"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_5363760"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_15579"}

{:event/type "shotoff"
:event/elapsed 54
:event/subtype "header"
:event/player1 "Vincent Vermeij"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5363764"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Bryan Smeets"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5363775"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Vincent Vermeij"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5363783"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_15579"}

{:event/type "corner"
:event/elapsed 55
:event/subtype "cross_left"
:event/player1 "Youssef El Jebli"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_5363784"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_15579"}

{:event/type "shoton"
:event/elapsed 57
:event/subtype "deflected"
:event/player1 "Bryan Smeets"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_5363801"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Wouter Marinus"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5363928"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_15579"}

{:event/type "goal"
:event/elapsed 67
:event/player2 "Vincent Vermeij"
:event/subtype "shot"
:event/player1 "Nathan Kabasele"
:event/sortorder 1
:event/team "away"
:event/id "event_5363947"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Youssef El Jebli"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5363974"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Nathaniel Will"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_5363985"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/sortorder 4
:event/team "away"
:event/event_type "throwin"
:event/id "event_5363988"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Karim Tarfi"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5363992"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/sortorder 1
:event/team "away"
:event/event_type "throwin"
:event/id "event_5363996"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_15579"}

{:event/type "shotoff"
:event/elapsed 70
:event/subtype "bad shot"
:event/player1 "Nathaniel Will"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5364004"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_15579"}

{:event/type "shoton"
:event/elapsed 71
:event/subtype "big chance shot"
:event/player1 "Lars Veldwijk"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5364012"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_15579"}

{:event/type "shotoff"
:event/elapsed 71
:event/subtype "distance"
:event/player1 "Kingsley Ehizibue"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5364016"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_15579"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Robin Propper"
:event/player1 "Lars Veldwijk"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5364051"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Karim Tarfi"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5364135"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Dean Koolhof"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5364145"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_15579"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Dirk Marcellis"
:event/player1 "Cas Peters"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5364204"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_15579"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Nathaniel Will"
:event/player1 "Kingsley Ehizibue"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5364240"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Vincent Vermeij"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5364251"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_15579"}

{:event/type "shoton"
:event/elapsed 82
:event/subtype "blocked_shot"
:event/player1 "Karim Tarfi"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_5364253"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_15579"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Karim Tarfi"
:event/player1 "Bram van Polen"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5364257"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Karim Tarfi"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5364262"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/sortorder 2
:event/team "away"
:event/event_type "throwin"
:event/id "event_5364268"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/sortorder 2
:event/team "away"
:event/event_type "throwin"
:event/id "event_5364289"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Karim Tarfi"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_5364294"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_15579"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Wout Brama"
:event/subtype "advantage"
:event/player1 "Karim Tarfi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5364348"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Karim Tarfi"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5364359"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/sortorder 2
:event/team "away"
:event/event_type "throwin"
:event/id "event_5364360"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_15579"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player2 "Ted van de Pavert"
:event/player1 "Lars Veldwijk"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5364386"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_15579"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Karim Tarfi"
:event/player1 "Wout Brama"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5364411"
:event/minute 91
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Karim Tarfi"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5364415"
:event/minute 91
:event/match_id "match_15579"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Vincent Vermeij"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5364416"
:event/minute 91
:event/match_id "match_15579"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Wouter Marinus"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_5364436"
:event/minute 92
:event/match_id "match_15579"}

{:event/type "shotoff"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Bart Schenkeveld"
:event/sortorder 9
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5364457"
:event/minute 93
:event/match_id "match_15579"}


]

