
;;# data
[
{:match/id "match_6831"
:match/league "France Ligue 1"
:match/hometeam "FC Nantes"
:match/awayteam "Olympique Lyonnais"
:match/score "1:2"
:match/hometeam_goals "1"
:match/awayteam_goals "2"}

{:event/type "goal"
:event/elapsed 40
:event/player1 "Alexandre Lacazette"
:event/sortorder 0
:event/team "away"
:event/id "event_3253423"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_6831"}

{:event/type "card"
:event/elapsed 67
:event/card_type "y"
:event/player1 "Clement Grenier"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3253747"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_6831"}

{:event/type "card"
:event/elapsed 74
:event/card_type "y"
:event/player1 "Remy Riou"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3253811"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_6831"}

{:event/type "goal"
:event/elapsed 76
:event/player1 "Bafetimbi Gomis"
:event/sortorder 0
:event/team "away"
:event/id "event_3253779"
:event/event_type "goal"
:event/goal_type "p"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_6831"}

{:event/type "goal"
:event/elapsed 84
:event/player1 "Filip Djordjevic"
:event/sortorder 0
:event/team "home"
:event/id "event_3253857"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_6831"}

{:event/type "card"
:event/elapsed 84
:event/card_type "y"
:event/player1 "Filip Djordjevic"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_3253872"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_6831"}

{:event/type "card"
:event/elapsed 86
:event/card_type "y"
:event/player1 "Filip Djordjevic"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3253883"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_6831"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Johan Audel"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3253914"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_6831"}


]

