
;;# data
[
{:match/id "match_3712"
:match/league "England Premier League"
:match/hometeam "Liverpool"
:match/awayteam "Cardiff City"
:match/score "3:1"
:match/hometeam_goals "3"
:match/awayteam_goals "1"}

{:event/type "shoton"
:event/elapsed 2
:event/subtype "shot"
:event/player1 "Joe Allen"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3178741"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_3712"}

{:event/type "shotoff"
:event/elapsed 3
:event/subtype "shot"
:event/player1 "Luis Suarez"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3178742"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Aron Gunnarsson"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3178744"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Jordon Mutch"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3178747"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_3712"}

{:event/type "shoton"
:event/elapsed 6
:event/subtype "blocked_shot"
:event/player1 "Luis Suarez"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_3178752"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_3712"}

{:event/type "shotoff"
:event/elapsed 7
:event/subtype "shot"
:event/player1 "Philippe Coutinho"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3178754"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Jordon Mutch"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_3178758"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Peter Whittingham"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3178759"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_3712"}

{:event/type "corner"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Peter Whittingham"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3178759"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_3712"}

{:event/type "foulcommit"
:event/elapsed 8
:event/player2 "Martin Skrtel"
:event/subtype "pushing"
:event/player1 "Peter Odemwingie"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3178760"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_3712"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Mamadou Sakho"
:event/subtype "pushing"
:event/player1 "Peter Odemwingie"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3178761"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3712"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Peter Whittingham"
:event/subtype "trip"
:event/player1 "Raheem Sterling"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3178762"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Joe Allen"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3178763"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_3712"}

{:event/type "shotoff"
:event/elapsed 11
:event/subtype "miss_kick"
:event/player1 "Raheem Sterling"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3178766"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_3712"}

{:event/type "shotoff"
:event/elapsed 13
:event/subtype "bad shot"
:event/player1 "Jordon Mutch"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3178769"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 13
:event/subtype "cross"
:event/player1 "Kevin Theophile-Catherine"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_3178771"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_3712"}

{:event/type "shoton"
:event/elapsed 14
:event/subtype "blocked_shot"
:event/player1 "Joe Allen"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3178773"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Glen Johnson"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3178775"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_3712"}

{:event/type "shoton"
:event/elapsed 15
:event/subtype "shot"
:event/player1 "Craig Noone"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_3178778"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Peter Whittingham"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_3178779"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_3712"}

{:event/type "corner"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Peter Whittingham"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_3178779"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_3712"}

{:event/type "shotoff"
:event/elapsed 16
:event/subtype "header"
:event/player1 "Jordon Mutch"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3178780"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_3712"}

{:event/type "shotoff"
:event/elapsed 18
:event/subtype "deflected"
:event/player1 "Luis Suarez"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3178781"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Philippe Coutinho"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3178782"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3712"}

{:event/type "corner"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Philippe Coutinho"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3178782"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3712"}

{:event/type "shoton"
:event/elapsed 18
:event/subtype "blocked_shot"
:event/player1 "Raheem Sterling"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_3178784"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3712"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Peter Odemwingie"
:event/subtype "trip"
:event/player1 "Martin Skrtel"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3178785"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Philippe Coutinho"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3178786"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_3712"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Martin Skrtel"
:event/subtype "pushing"
:event/player1 "Peter Odemwingie"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3178790"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_3712"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Philippe Coutinho"
:event/subtype "trip"
:event/player1 "Gary Medel"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3178791"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_3712"}

{:event/type "shoton"
:event/elapsed 25
:event/subtype "blocked_shot"
:event/player1 "Philippe Coutinho"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3178793"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Jordan Henderson"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3178794"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3712"}

{:event/type "goal"
:event/elapsed 25
:event/player2 "Jordan Henderson"
:event/subtype "volley"
:event/player1 "Luis Suarez"
:event/sortorder 2
:event/team "home"
:event/id "event_3178795"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Joe Allen"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3178796"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_3712"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Craig Noone"
:event/subtype "trip"
:event/player1 "Jordan Henderson"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3178798"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_3712"}

{:event/type "shoton"
:event/elapsed 30
:event/subtype "header"
:event/player1 "Steven Caulker"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3178800"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Raheem Sterling"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_3178802"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_3712"}

{:event/type "shotoff"
:event/elapsed 31
:event/subtype "distance"
:event/player1 "Lucas Leiva"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3178804"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_3712"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Jon Flanagan"
:event/subtype "trip"
:event/player1 "Peter Odemwingie"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3178806"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Joe Allen"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3178808"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3712"}

{:event/type "corner"
:event/elapsed 33
:event/subtype "short"
:event/player1 "Luis Suarez"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_3178812"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3712"}

{:event/type "shotoff"
:event/elapsed 33
:event/subtype "post"
:event/player1 "Philippe Coutinho"
:event/sortorder 5
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3178813"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3712"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Jon Flanagan"
:event/subtype "trip"
:event/player1 "Kevin Theophile-Catherine"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3178814"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Jon Flanagan"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3178815"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_3712"}

{:event/type "shotoff"
:event/elapsed 35
:event/subtype "header"
:event/player1 "Martin Skrtel"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3178816"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Raheem Sterling"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3178818"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Glen Johnson"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3178821"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_3712"}

{:event/type "shoton"
:event/elapsed 38
:event/subtype "shot"
:event/player1 "Jon Flanagan"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3178822"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_3712"}

{:event/type "shoton"
:event/elapsed 39
:event/subtype "shot"
:event/player1 "Raheem Sterling"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3178823"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_3712"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Jordon Mutch"
:event/subtype "serious_foul"
:event/player1 "Martin Skrtel"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3178827"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3712"}

{:event/type "card"
:event/elapsed 41
:event/card_type "y"
:event/player1 "Martin Skrtel"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_3178828"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3712"}

{:event/type "goal"
:event/elapsed 42
:event/player2 "Luis Suarez"
:event/subtype "shot"
:event/player1 "Raheem Sterling"
:event/sortorder 4
:event/team "home"
:event/id "event_3178833"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Raheem Sterling"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3178835"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_3712"}

{:event/type "shotoff"
:event/elapsed 44
:event/subtype "volley"
:event/player1 "Luis Suarez"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3178837"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_3712"}

{:event/type "goal"
:event/elapsed 45
:event/player2 "Jordan Henderson"
:event/subtype "shot"
:event/player1 "Luis Suarez"
:event/sortorder 0
:event/team "home"
:event/id "event_3178839"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Philippe Coutinho"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3178847"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_3712"}

{:event/type "corner"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Philippe Coutinho"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3178847"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_3712"}

{:event/type "shotoff"
:event/elapsed 47
:event/subtype "shot"
:event/player1 "Raheem Sterling"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3178848"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Glen Johnson"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_3178842"
:event/minute 47
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Glen Johnson"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3178851"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_3712"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Glen Johnson"
:event/subtype "trip"
:event/player1 "Jordon Mutch"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3178853"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3712"}

{:event/type "shotoff"
:event/elapsed 51
:event/subtype "distance"
:event/player1 "Philippe Coutinho"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3178854"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Philippe Coutinho"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3178856"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_3712"}

{:event/type "shotoff"
:event/elapsed 53
:event/subtype "distance"
:event/player1 "Jordan Henderson"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3178857"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Peter Whittingham"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3178859"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_3712"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Peter Whittingham"
:event/subtype "trip"
:event/player1 "Glen Johnson"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3178861"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_3712"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Glen Johnson"
:event/subtype "trip"
:event/player1 "Peter Whittingham"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3178866"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_3712"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Fraizer Campbell"
:event/subtype "trip"
:event/player1 "Glen Johnson"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3178868"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3712"}

{:event/type "goal"
:event/elapsed 58
:event/player2 "Peter Whittingham"
:event/subtype "header"
:event/player1 "Jordon Mutch"
:event/sortorder 3
:event/team "away"
:event/id "event_3178870"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3712"}

{:event/type "foulcommit"
:event/elapsed 59
:event/player2 "Joe Allen"
:event/subtype "trip"
:event/player1 "Peter Whittingham"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3178871"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Andrew Taylor"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3178874"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Peter Whittingham"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_3178877"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_3712"}

{:event/type "corner"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Peter Whittingham"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_3178877"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_3712"}

{:event/type "shotoff"
:event/elapsed 62
:event/subtype "header"
:event/player1 "Jordon Mutch"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3178878"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_3712"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Fraizer Campbell"
:event/subtype "pushing"
:event/player1 "Joe Allen"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3178882"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_3712"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Kevin Theophile-Catherine"
:event/subtype "trip"
:event/player1 "Luis Suarez"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3178884"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_3712"}

{:event/type "shoton"
:event/elapsed 66
:event/subtype "header"
:event/player1 "Ben Turner"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3178886"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Jordan Henderson"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3178887"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Philippe Coutinho"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3178889"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3712"}

{:event/type "corner"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Philippe Coutinho"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3178889"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Martin Kelly"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_3178891"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3712"}

{:event/type "shoton"
:event/elapsed 68
:event/subtype "blocked_shot"
:event/player1 "Luis Suarez"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3178894"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Philippe Coutinho"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3178895"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_3712"}

{:event/type "corner"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Philippe Coutinho"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3178895"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_3712"}

{:event/type "shoton"
:event/elapsed 71
:event/subtype "blocked_shot"
:event/player1 "Fraizer Campbell"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3178900"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Peter Whittingham"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3178901"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Craig Noone"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3178902"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Peter Whittingham"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_3178903"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3712"}

{:event/type "corner"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Peter Whittingham"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_3178903"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3712"}

{:event/type "shoton"
:event/elapsed 71
:event/subtype "blocked_shot"
:event/player1 "Ben Turner"
:event/sortorder 4
:event/team "away"
:event/event_type "shoton"
:event/id "event_3178904"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3712"}

{:event/type "foulcommit"
:event/elapsed 72
:event/player2 "Peter Whittingham"
:event/subtype "serious_foul"
:event/player1 "Raheem Sterling"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3178905"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_3712"}

{:event/type "card"
:event/elapsed 72
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Raheem Sterling"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_3178906"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Craig Noone"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3178909"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Andrew Taylor"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3178911"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3712"}

{:event/type "shoton"
:event/elapsed 73
:event/subtype "header"
:event/player1 "Steven Caulker"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_3178912"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Luis Suarez"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3178914"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_3712"}

{:event/type "corner"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Luis Suarez"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3178914"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 76
:event/subtype "cross"
:event/player1 "Joe Allen"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3178916"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3712"}

{:event/type "shotoff"
:event/elapsed 76
:event/subtype "post"
:event/player1 "Luis Suarez"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3178918"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_3712"}

{:event/type "foulcommit"
:event/elapsed 78
:event/player2 "Martin Skrtel"
:event/subtype "trip"
:event/player1 "Fraizer Campbell"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3178920"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Philippe Coutinho"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3178922"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_3712"}

{:event/type "corner"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Philippe Coutinho"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3178922"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_3712"}

{:event/type "shotoff"
:event/elapsed 78
:event/subtype "header"
:event/player1 "Joe Allen"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3178923"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_3712"}

{:event/type "shotoff"
:event/elapsed 80
:event/subtype "distance"
:event/player1 "Craig Noone"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3178927"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_3712"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Philippe Coutinho"
:event/subtype "pushing"
:event/player1 "Kevin Theophile-Catherine"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3178929"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_3712"}

{:event/type "shotoff"
:event/elapsed 81
:event/subtype "distance"
:event/player1 "Philippe Coutinho"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3178930"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_3712"}

{:event/type "shotoff"
:event/elapsed 83
:event/subtype "distance"
:event/player1 "Luis Suarez"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3178934"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Peter Whittingham"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3178942"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_3712"}

{:event/type "corner"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Peter Whittingham"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3178942"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Jordon Mutch"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3178944"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3712"}

{:event/type "shotoff"
:event/elapsed 86
:event/subtype "header"
:event/player1 "Steven Caulker"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3178945"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_3712"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Glen Johnson"
:event/subtype "trip"
:event/player1 "Craig Noone"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3178947"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_3712"}

{:event/type "shoton"
:event/elapsed 90
:event/subtype "big chance shot"
:event/player1 "Luis Suarez"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3178954"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3712"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "blocked_shot"
:event/player1 "Raheem Sterling"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_3178955"
:event/minute 91
:event/match_id "match_3712"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Kevin Theophile-Catherine"
:event/subtype "trip"
:event/player1 "Raheem Sterling"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3178956"
:event/minute 91
:event/match_id "match_3712"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Raheem Sterling"
:event/subtype "trip"
:event/player1 "Steven Caulker"
:event/sortorder 5
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3178958"
:event/minute 92
:event/match_id "match_3712"}

{:event/type "corner"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "short"
:event/player1 "Luis Suarez"
:event/sortorder 8
:event/team "home"
:event/event_type "corner"
:event/id "event_3178961"
:event/minute 93
:event/match_id "match_3712"}

{:event/type "shoton"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "blocked_shot"
:event/player1 "Raheem Sterling"
:event/sortorder 9
:event/team "home"
:event/event_type "shoton"
:event/id "event_3178962"
:event/minute 93
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Glen Johnson"
:event/sortorder 10
:event/team "home"
:event/event_type "cross"
:event/id "event_3178963"
:event/minute 93
:event/match_id "match_3712"}

{:event/type "corner"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "short"
:event/player1 "Luis Suarez"
:event/sortorder 14
:event/team "home"
:event/event_type "corner"
:event/id "event_3178967"
:event/minute 94
:event/match_id "match_3712"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Martin Kelly"
:event/sortorder 15
:event/team "home"
:event/event_type "cross"
:event/id "event_3178968"
:event/minute 94
:event/match_id "match_3712"}


]

