
;;# data
[
{:match/id "match_24236"
:match/league "Spain LIGA BBVA"
:match/hometeam "Granada CF"
:match/awayteam "Atlético Madrid"
:match/score "0:2"
:match/hometeam_goals "0"
:match/awayteam_goals "2"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Yannick Ferreira-Carrasco"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5083090"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_24236"}

{:event/type "foulcommit"
:event/elapsed 6
:event/player2 "Jose Gimenez"
:event/player1 "Dimitri Foulquier"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5083104"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_24236"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Yannick Ferreira-Carrasco"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5083109"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_24236"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Ruben Perez"
:event/player1 "Saul Niguez"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5083115"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_24236"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Dimitri Foulquier"
:event/subtype "pushing"
:event/player1 "Saul Niguez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5083135"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_24236"}

{:event/type "shoton"
:event/elapsed 11
:event/subtype "blocked_shot"
:event/player1 "Fernando Torres"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_5083141"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_24236"}

{:event/type "shoton"
:event/elapsed 11
:event/subtype "shot"
:event/player1 "Saul Niguez"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_5083144"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_24236"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Koke"
:event/player1 "Fran Rico"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5083157"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_24236"}

{:event/type "shotoff"
:event/elapsed 14
:event/subtype "header"
:event/player1 "Fernando Torres"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5083164"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_24236"}

{:event/type "card"
:event/elapsed 19
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Dimitri Foulquier"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_5083229"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_24236"}

{:event/type "shoton"
:event/elapsed 20
:event/subtype "blocked_shot"
:event/player1 "Saul Niguez"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_5083246"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_24236"}

{:event/type "corner"
:event/elapsed 20
:event/subtype "cross_right"
:event/player1 "Koke"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_5083249"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_24236"}

{:event/type "goal"
:event/elapsed 20
:event/player2 "Koke"
:event/subtype "header"
:event/player1 "Diego Godin"
:event/sortorder 3
:event/team "away"
:event/id "event_5083253"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_24236"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Juanfran"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5083274"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_24236"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Oliver Torres"
:event/player1 "Ruben Rochina"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5083280"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_24236"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Cristiano Biraghi"
:event/player1 "Gabi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5083297"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_24236"}

{:event/type "corner"
:event/elapsed 25
:event/subtype "short_left"
:event/player1 "Fran Rico"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5083322"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_24236"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Cristiano Biraghi"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5083325"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_24236"}

{:event/type "shotoff"
:event/elapsed 25
:event/subtype "bad shot"
:event/player1 "Ruben Rochina"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5083333"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_24236"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Gabi"
:event/player1 "Youssef El Arabi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5083354"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_24236"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Success Isaac"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5083367"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_24236"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Koke"
:event/subtype "dangerous_play"
:event/player1 "Fran Rico"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5083371"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_24236"}

{:event/type "card"
:event/elapsed 28
:event/card_type "y"
:event/player1 "Fran Rico"
:event/sortorder 3
:event/team "home"
:event/event_type "card"
:event/id "event_5083384"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_24236"}

{:event/type "shoton"
:event/elapsed 33
:event/subtype "blocked_shot"
:event/player1 "Ruben Rochina"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_5083443"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_24236"}

{:event/type "corner"
:event/elapsed 34
:event/subtype "short_left"
:event/player1 "Fran Rico"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5083447"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_24236"}

{:event/type "shotoff"
:event/elapsed 34
:event/subtype "bad shot"
:event/player1 "Ruben Rochina"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5083449"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_24236"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Ruben Perez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5083462"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_24236"}

{:event/type "shotoff"
:event/elapsed 36
:event/subtype "distance"
:event/player1 "Yannick Ferreira-Carrasco"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5083478"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_24236"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Success Isaac"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5083492"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_24236"}

{:event/type "shotoff"
:event/elapsed 38
:event/subtype "shot"
:event/player1 "Jean-Sylvain Babin"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5083496"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_24236"}

{:event/type "corner"
:event/elapsed 40
:event/subtype "cross_right"
:event/player1 "Gabi"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_5083507"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_24236"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Cristiano Biraghi"
:event/subtype "dangerous_play"
:event/player1 "Saul Niguez"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5083520"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_24236"}

{:event/type "card"
:event/elapsed 40
:event/card_type "y"
:event/player1 "Saul Niguez"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_5083521"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_24236"}

{:event/type "foulcommit"
:event/elapsed 41
:event/subtype "hands"
:event/player1 "Gabi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5083527"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_24236"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Fran Rico"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5083531"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_24236"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Koke"
:event/subtype "trip"
:event/player1 "Fran Rico"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5083539"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_24236"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Success Isaac"
:event/player1 "Gabi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5083547"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_24236"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Dimitri Foulquier"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5083554"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_24236"}

{:event/type "shoton"
:event/elapsed 44
:event/subtype "blocked_shot"
:event/player1 "Youssef El Arabi"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5083556"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_24236"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Koke"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5083753"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_24236"}

{:event/type "foulcommit"
:event/elapsed 47
:event/player2 "Fran Rico"
:event/subtype "pushing"
:event/player1 "Gabi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5083756"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_24236"}

{:event/type "shotoff"
:event/elapsed 49
:event/subtype "big chance shot"
:event/player1 "Filipe Luis"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5083764"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_24236"}

{:event/type "corner"
:event/elapsed 50
:event/subtype "cross_left"
:event/player1 "Yannick Ferreira-Carrasco"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_5083770"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_24236"}

{:event/type "shotoff"
:event/elapsed 50
:event/subtype "big chance header"
:event/player1 "Diego Godin"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5083773"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_24236"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Cristiano Biraghi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5083776"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_24236"}

{:event/type "corner"
:event/elapsed 53
:event/subtype "cross_right"
:event/player1 "Ruben Rochina"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5083782"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_24236"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Fran Rico"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5083784"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_24236"}

{:event/type "shotoff"
:event/elapsed 53
:event/subtype "distance"
:event/player1 "Adalberto Penaranda"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5083788"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_24236"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Fernando Torres"
:event/player1 "Ruben Rochina"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5083799"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_24236"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Yannick Ferreira-Carrasco"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5083801"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_24236"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Fran Rico"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5083812"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_24236"}

{:event/type "shoton"
:event/elapsed 62
:event/subtype "shot"
:event/player1 "Success Isaac"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5083822"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_24236"}

{:event/type "corner"
:event/elapsed 62
:event/subtype "cross_left"
:event/player1 "Fran Rico"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_5083828"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_24236"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Filipe Luis"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5083851"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_24236"}

{:event/type "shoton"
:event/elapsed 65
:event/subtype "big chance shot"
:event/player1 "Fernando Torres"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_5083863"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_24236"}

{:event/type "corner"
:event/elapsed 66
:event/subtype "cross_right"
:event/player1 "Koke"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_5083869"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_24236"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Cristiano Biraghi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5083878"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_24236"}

{:event/type "shotoff"
:event/elapsed 67
:event/subtype "header"
:event/player1 "Youssef El Arabi"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5083884"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_24236"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Fran Rico"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_5083901"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_24236"}

{:event/type "shotoff"
:event/elapsed 68
:event/subtype "big chance shot"
:event/player1 "Robert Ibanez"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5083898"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_24236"}

{:event/type "corner"
:event/elapsed 69
:event/subtype "cross_right"
:event/player1 "Yannick Ferreira-Carrasco"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_5083922"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_24236"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Yannick Ferreira-Carrasco"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5083928"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_24236"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Robert Ibanez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5083941"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_24236"}

{:event/type "corner"
:event/elapsed 71
:event/subtype "cross_right"
:event/player1 "Fran Rico"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_5083950"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_24236"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Ruben Rochina"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5083960"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_24236"}

{:event/type "corner"
:event/elapsed 73
:event/subtype "cross_right"
:event/player1 "Koke"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_5083988"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_24236"}

{:event/type "shotoff"
:event/elapsed 74
:event/subtype "distance"
:event/player1 "Youssef El Arabi"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5083996"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_24236"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Juanfran"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5084031"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_24236"}

{:event/type "goal"
:event/elapsed 76
:event/player2 "Oliver Torres"
:event/subtype "shot"
:event/player1 "Antoine Griezmann"
:event/sortorder 1
:event/team "away"
:event/id "event_5084050"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_24236"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Filipe Luis"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5084116"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_24236"}

{:event/type "shotoff"
:event/elapsed 81
:event/subtype "distance"
:event/player1 "Thomas"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5084122"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_24236"}

{:event/type "shotoff"
:event/elapsed 84
:event/subtype "big chance shot"
:event/player1 "Thomas"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5084166"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_24236"}

{:event/type "shotoff"
:event/elapsed 86
:event/subtype "shot"
:event/player1 "Dimitri Foulquier"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5084187"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_24236"}

{:event/type "foulcommit"
:event/elapsed 87
:event/player2 "Fran Rico"
:event/player1 "Fernando Torres"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5084197"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_24236"}

{:event/type "corner"
:event/elapsed 87
:event/subtype "short_right"
:event/player1 "Nicolas Lopez"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_5084204"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_24236"}

{:event/type "shoton"
:event/elapsed 87
:event/subtype "distance"
:event/player1 "Ruben Rochina"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_5084206"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_24236"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Cristiano Biraghi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5084238"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_24236"}

{:event/type "shoton"
:event/elapsed 89
:event/subtype "blocked_shot"
:event/player1 "Piti"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_5084243"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_24236"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Success Isaac"
:event/subtype "dangerous_play"
:event/player1 "Gabi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5084261"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_24236"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Dimitri Foulquier"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5084265"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_24236"}

{:event/type "corner"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "short_left"
:event/player1 "Koke"
:event/sortorder 5
:event/team "away"
:event/event_type "corner"
:event/id "event_5084306"
:event/minute 91
:event/match_id "match_24236"}

{:event/type "corner"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "short_left"
:event/player1 "Koke"
:event/sortorder 6
:event/team "away"
:event/event_type "corner"
:event/id "event_5084315"
:event/minute 92
:event/match_id "match_24236"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Oliver Torres"
:event/sortorder 10
:event/team "away"
:event/event_type "cross"
:event/id "event_5084339"
:event/minute 93
:event/match_id "match_24236"}


]

