
;;# data
[
{:match/id "match_8659"
:match/league "Germany 1. Bundesliga"
:match/hometeam "VfL Wolfsburg"
:match/awayteam "1. FC Kaiserslautern"
:match/score "1:2"
:match/hometeam_goals "1"
:match/awayteam_goals "2"}

{:event/type "goal"
:event/elapsed 6
:event/player1 "Mario Mandzukic"
:event/sortorder 0
:event/team "home"
:event/id "event_1539782"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_8659"}

{:event/type "goal"
:event/elapsed 25
:event/player1 "Srdjan Lakic"
:event/sortorder 0
:event/team "away"
:event/id "event_1539907"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_8659"}

{:event/type "goal"
:event/elapsed 44
:event/player1 "Martin Amedick"
:event/sortorder 0
:event/team "away"
:event/id "event_1540214"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_8659"}

{:event/type "card"
:event/elapsed 81
:event/card_type "y"
:event/player1 "Marcel Schaefer"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1541158"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_8659"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Pierre de Wit"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1541198"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_8659"}


]

