
;;# data
[
{:match/id "match_12918"
:match/league "Italy Serie A"
:match/hometeam "Genoa"
:match/awayteam "Napoli"
:match/score "0:0"
:match/hometeam_goals "0"
:match/awayteam_goals "0"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Jose Maria Callejon"
:event/subtype "trip"
:event/player1 "Cristian Daniel Ansaldi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4980975"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_12918"}

{:event/type "shoton"
:event/elapsed 3
:event/subtype "blocked_shot"
:event/player1 "Gonzalo Higuain"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4980997"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_12918"}

{:event/type "corner"
:event/elapsed 3
:event/subtype "short_right"
:event/player1 "Marek Hamsik"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4981002"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Marek Hamsik"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4981006"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_12918"}

{:event/type "shoton"
:event/elapsed 5
:event/subtype "distance"
:event/player1 "Jose Maria Callejon"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4981047"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_12918"}

{:event/type "corner"
:event/elapsed 6
:event/subtype "cross_left"
:event/player1 "Jorginho"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4981060"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_12918"}

{:event/type "corner"
:event/elapsed 6
:event/subtype "cross_left"
:event/player1 "Jorginho"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4981069"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_12918"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Diego Perotti"
:event/subtype "trip"
:event/player1 "Allan"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4981083"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Diego Laxalt"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4981098"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Dries Mertens"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4981184"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_12918"}

{:event/type "corner"
:event/elapsed 12
:event/subtype "short_left"
:event/player1 "Jorginho"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4981192"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Allan"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4981193"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_12918"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Blerim Dzemaili"
:event/subtype "trip"
:event/player1 "Kalidou Koulibaly"
:event/sortorder 5
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4981203"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_12918"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Elseid Hysaj"
:event/subtype "pull"
:event/player1 "Tomas Rincon"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4981210"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_12918"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Diogo Figueiras"
:event/subtype "pushing"
:event/player1 "Jorginho"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4981240"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_12918"}

{:event/type "shotoff"
:event/elapsed 16
:event/subtype "distance"
:event/player1 "Diego Laxalt"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4981276"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_12918"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Allan"
:event/subtype "trip"
:event/player1 "Blerim Dzemaili"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4981297"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_12918"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Diego Perotti"
:event/subtype "pushing"
:event/player1 "Allan"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4981303"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_12918"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Jose Maria Callejon"
:event/subtype "pushing"
:event/player1 "Ezequiel Munoz"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4981335"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Jorginho"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4981351"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_12918"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Ezequiel Munoz"
:event/subtype "pull"
:event/player1 "Gonzalo Higuain"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4981359"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_12918"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Allan"
:event/subtype "pushing"
:event/player1 "Tomas Rincon"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4981373"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Jose Maria Callejon"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4981419"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Diego Perotti"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4981430"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Diego Laxalt"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4981438"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Faouzi Ghoulam"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4981442"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Faouzi Ghoulam"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4981455"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_12918"}

{:event/type "shotoff"
:event/elapsed 27
:event/subtype "shot"
:event/player1 "Dries Mertens"
:event/sortorder 3
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4981459"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Dries Mertens"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4981492"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Dries Mertens"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4981496"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_12918"}

{:event/type "foulcommit"
:event/elapsed 30
:event/player2 "Cristian Daniel Ansaldi"
:event/subtype "pushing"
:event/player1 "Jorginho"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4981503"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Faouzi Ghoulam"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4981518"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_12918"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Diego Laxalt"
:event/subtype "dangerous_play"
:event/player1 "Kalidou Koulibaly"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4981536"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_12918"}

{:event/type "shoton"
:event/elapsed 33
:event/subtype "shot"
:event/player1 "Dries Mertens"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4981554"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_12918"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Blerim Dzemaili"
:event/subtype "trip"
:event/player1 "Raul Albiol"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4981592"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Diego Perotti"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4981604"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_12918"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Gonzalo Higuain"
:event/subtype "obstruction"
:event/player1 "Armando Izzo"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4981614"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_12918"}

{:event/type "card"
:event/elapsed 37
:event/card_type "y"
:event/player1 "Armando Izzo"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4981617"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Jorginho"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4981632"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_12918"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Dries Mertens"
:event/subtype "trip"
:event/player1 "Tomas Rincon"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4981703"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/sortorder 1
:event/team "away"
:event/event_type "throwin"
:event/id "event_4981709"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_12918"}

{:event/type "shoton"
:event/elapsed 41
:event/subtype "header"
:event/player1 "Gonzalo Higuain"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4981713"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_12918"}

{:event/type "shoton"
:event/elapsed 41
:event/subtype "blocked_shot"
:event/player1 "Diego Laxalt"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_4981729"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_12918"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Diego Laxalt"
:event/subtype "pushing"
:event/player1 "Faouzi Ghoulam"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4981734"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Blerim Dzemaili"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4981747"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_12918"}

{:event/type "shotoff"
:event/elapsed 42
:event/subtype "header"
:event/player1 "Diego Perotti"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4981756"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_12918"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Allan"
:event/subtype "trip"
:event/player1 "Tino Costa"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4981812"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_12918"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "shot"
:event/player1 "Gonzalo Higuain"
:event/sortorder 6
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4981825"
:event/minute 46
:event/match_id "match_12918"}

{:event/type "corner"
:event/elapsed 47
:event/subtype "cross_right"
:event/player1 "Jorginho"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4982126"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_12918"}

{:event/type "shotoff"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "distance"
:event/player1 "Diego Perotti"
:event/sortorder 9
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4981845"
:event/minute 47
:event/match_id "match_12918"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Armando Izzo"
:event/subtype "pushing"
:event/player1 "Dries Mertens"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4982163"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_12918"}

{:event/type "shotoff"
:event/elapsed 49
:event/subtype "distance"
:event/player1 "Gonzalo Higuain"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4982178"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_12918"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Tino Costa"
:event/subtype "trip"
:event/player1 "Jorginho"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4982206"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Diego Perotti"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4982223"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Diego Perotti"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4982233"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_12918"}

{:event/type "shotoff"
:event/elapsed 52
:event/subtype "header"
:event/player1 "Diego Laxalt"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4982237"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_12918"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Raul Albiol"
:event/subtype "pushing"
:event/player1 "Diego Perotti"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4982244"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_12918"}

{:event/type "shotoff"
:event/elapsed 53
:event/subtype "shot"
:event/player1 "Leonardo Pavoletti"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4982260"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_12918"}

{:event/type "shoton"
:event/elapsed 53
:event/subtype "shot"
:event/player1 "Marek Hamsik"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_4982278"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_12918"}

{:event/type "shoton"
:event/elapsed 53
:event/subtype "shot"
:event/player1 "Dries Mertens"
:event/sortorder 4
:event/team "away"
:event/event_type "shoton"
:event/id "event_4982282"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_12918"}

{:event/type "shoton"
:event/elapsed 54
:event/subtype "blocked_shot"
:event/player1 "Gonzalo Higuain"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4982297"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Diego Perotti"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4982337"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_12918"}

{:event/type "corner"
:event/elapsed 56
:event/subtype "short_left"
:event/player1 "Tino Costa"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4982350"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Diego Perotti"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4982353"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_12918"}

{:event/type "shotoff"
:event/elapsed 56
:event/subtype "distance"
:event/player1 "Diogo Figueiras"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4982370"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Jose Maria Callejon"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4982391"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_12918"}

{:event/type "foulcommit"
:event/elapsed 57
:event/subtype "hands"
:event/player1 "Tino Costa"
:event/sortorder 5
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4982402"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_12918"}

{:event/type "shotoff"
:event/elapsed 58
:event/subtype "shot"
:event/player1 "Jose Maria Callejon"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4982418"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Olivier Ntcham"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4982444"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Jose Maria Callejon"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4982458"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Faouzi Ghoulam"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4982465"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Elseid Hysaj"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4982483"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_12918"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Leonardo Pavoletti"
:event/subtype "pushing"
:event/player1 "Jorginho"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4982549"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Olivier Ntcham"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4982553"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_12918"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Allan"
:event/subtype "pull"
:event/player1 "Tino Costa"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4982563"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Diego Perotti"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4982587"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_12918"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Marek Hamsik"
:event/subtype "trip"
:event/player1 "Tomas Rincon"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4982609"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Manolo Gabbiadini"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4982619"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Marek Hamsik"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4982672"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_12918"}

{:event/type "shotoff"
:event/elapsed 71
:event/subtype "miss_kick"
:event/player1 "Manolo Gabbiadini"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4982674"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Diego Perotti"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4982719"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_12918"}

{:event/type "shoton"
:event/elapsed 76
:event/subtype "distance"
:event/player1 "Diogo Figueiras"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4982742"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_12918"}

{:event/type "shoton"
:event/elapsed 77
:event/subtype "shot"
:event/player1 "Marek Hamsik"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4982769"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_12918"}

{:event/type "corner"
:event/elapsed 77
:event/subtype "short_left"
:event/player1 "Marek Hamsik"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4983236"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_12918"}

{:event/type "shoton"
:event/elapsed 79
:event/subtype "blocked_shot"
:event/player1 "Manolo Gabbiadini"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4982820"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_12918"}

{:event/type "shoton"
:event/elapsed 80
:event/subtype "blocked_shot"
:event/player1 "Diego Laxalt"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4982835"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_12918"}

{:event/type "shoton"
:event/elapsed 81
:event/subtype "distance"
:event/player1 "Lorenzo Insigne"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4982868"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_12918"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Diogo Figueiras"
:event/subtype "dangerous_play"
:event/player1 "Kalidou Koulibaly"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4982876"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_12918"}

{:event/type "card"
:event/elapsed 83
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Olivier Ntcham"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_4982901"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Lorenzo Insigne"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4982940"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_12918"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Tino Costa"
:event/subtype "serious_foul"
:event/player1 "Manolo Gabbiadini"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4982952"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_12918"}

{:event/type "card"
:event/elapsed 85
:event/card_type "y"
:event/player1 "Manolo Gabbiadini"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_4982953"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Lorenzo Insigne"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4982958"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "David Lopez"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4982965"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_12918"}

{:event/type "shotoff"
:event/elapsed 86
:event/subtype "shot"
:event/player1 "Lorenzo Insigne"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4982968"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Lorenzo Insigne"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4983070"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_12918"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Jorginho"
:event/subtype "serious_foul"
:event/player1 "Tino Costa"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4983080"
:event/minute 91
:event/match_id "match_12918"}

{:event/type "card"
:event/elapsed_plus 1
:event/elapsed 90
:event/card_type "y"
:event/player1 "Tino Costa"
:event/sortorder 5
:event/team "home"
:event/event_type "card"
:event/id "event_4983083"
:event/minute 91
:event/match_id "match_12918"}

{:event/type "shoton"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "direct_freekick"
:event/player1 "Manolo Gabbiadini"
:event/sortorder 6
:event/team "away"
:event/event_type "shoton"
:event/id "event_4983096"
:event/minute 92
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Faouzi Ghoulam"
:event/sortorder 7
:event/team "away"
:event/event_type "cross"
:event/id "event_4983099"
:event/minute 92
:event/match_id "match_12918"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Cristian Daniel Ansaldi"
:event/subtype "pull"
:event/player1 "David Lopez"
:event/sortorder 10
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4983115"
:event/minute 93
:event/match_id "match_12918"}

{:event/type "card"
:event/elapsed_plus 3
:event/elapsed 90
:event/card_type "y"
:event/player1 "David Lopez"
:event/sortorder 11
:event/team "away"
:event/event_type "card"
:event/id "event_4983116"
:event/minute 93
:event/match_id "match_12918"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Tino Costa"
:event/sortorder 12
:event/team "home"
:event/event_type "cross"
:event/id "event_4983122"
:event/minute 93
:event/match_id "match_12918"}

{:event/type "shoton"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "distance"
:event/player1 "Lorenzo Insigne"
:event/sortorder 14
:event/team "away"
:event/event_type "shoton"
:event/id "event_4983131"
:event/minute 94
:event/match_id "match_12918"}


]

