
;;# data
[
{:match/id "match_12219"
:match/league "Italy Serie A"
:match/hometeam "Inter"
:match/awayteam "Milan"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 26
:event/card_type "y"
:event/player1 "Mattia De Sciglio"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3181920"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_12219"}

{:event/type "card"
:event/elapsed 45
:event/card_type "y"
:event/player1 "Kevin Constant"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3181924"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_12219"}

{:event/type "card"
:event/elapsed 59
:event/card_type "y"
:event/player1 "Fredy Guarin"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3181942"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_12219"}

{:event/type "card"
:event/elapsed 62
:event/card_type "y"
:event/player1 "Nigel de Jong"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3181944"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_12219"}

{:event/type "card"
:event/elapsed 67
:event/card_type "y"
:event/player1 "Juan"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3181950"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_12219"}

{:event/type "card"
:event/elapsed 71
:event/card_type "y"
:event/player1 "Rolando"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3181957"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_12219"}

{:event/type "goal"
:event/elapsed 86
:event/player1 "Rodrigo Palacio"
:event/sortorder 0
:event/team "home"
:event/id "event_3181970"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_12219"}

{:event/type "card"
:event/elapsed 87
:event/card_type "y"
:event/player1 "Mario Balotelli"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3181975"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_12219"}

{:event/type "card"
:event/elapsed 90
:event/card_type "r"
:event/player1 "Sulley Ali Muntari"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3181982"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_12219"}


]

