
;;# data
[
{:match/id "match_6472"
:match/league "France Ligue 1"
:match/hometeam "Olympique Lyonnais"
:match/awayteam "FC Lorient"
:match/score "3:1"
:match/hometeam_goals "3"
:match/awayteam_goals "1"}

{:event/type "goal"
:event/elapsed 11
:event/player1 "Jeremie Aliadiere"
:event/sortorder 0
:event/team "away"
:event/id "event_2618001"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_6472"}

{:event/type "card"
:event/elapsed 18
:event/card_type "y"
:event/player1 "Kevin Monnet-Paquet"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2618004"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_6472"}

{:event/type "goal"
:event/elapsed 24
:event/player1 "Lisandro Lopez"
:event/sortorder 0
:event/team "home"
:event/id "event_2618011"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_6472"}

{:event/type "card"
:event/elapsed 33
:event/card_type "y"
:event/player1 "Steed Malbranque"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2618043"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_6472"}

{:event/type "card"
:event/elapsed 37
:event/card_type "y"
:event/player1 "Dejan Lovren"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2618072"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_6472"}

{:event/type "card"
:event/elapsed 44
:event/card_type "y"
:event/player1 "Benjamin Corgnet"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2618125"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_6472"}

{:event/type "goal"
:event/elapsed 50
:event/player1 "Rachid Ghezzal"
:event/sortorder 0
:event/team "home"
:event/id "event_2618286"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_6472"}

{:event/type "card"
:event/elapsed 87
:event/card_type "y"
:event/player1 "Enzo Reale"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2618435"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_6472"}

{:event/type "card"
:event/elapsed 88
:event/card_type "y"
:event/player1 "Yassine Benzia"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2618497"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_6472"}

{:event/type "goal"
:event/elapsed 90
:event/player1 "Arnold Mvuemba"
:event/sortorder 0
:event/team "home"
:event/id "event_2618496"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_6472"}


]

