
;;# data
[
{:match/id "match_15177"
:match/league "Netherlands Eredivisie"
:match/hometeam "Go Ahead Eagles"
:match/awayteam "SC Cambuur"
:match/score "1:2"
:match/hometeam_goals "1"
:match/awayteam_goals "2"}

{:event/type "goal"
:event/elapsed 28
:event/player1 "Martijn Barto"
:event/sortorder 0
:event/team "away"
:event/id "event_4011270"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_15177"}

{:event/type "card"
:event/elapsed 59
:event/card_type "y"
:event/player1 "Giliano Wijnaldum"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_4011796"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_15177"}

{:event/type "goal"
:event/elapsed 73
:event/player2 "Lucas Bijker"
:event/player1 "Albert Rusnak"
:event/sortorder 0
:event/team "away"
:event/id "event_4011832"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_15177"}

{:event/type "goal"
:event/elapsed 90
:event/player1 "Deniz Tueruec"
:event/sortorder 0
:event/team "home"
:event/id "event_4011920"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_15177"}


]

