
;;# data
[
{:match/id "match_23592"
:match/league "Spain LIGA BBVA"
:match/hometeam "Real Madrid CF"
:match/awayteam "Elche CF"
:match/score "3:0"
:match/hometeam_goals "3"
:match/awayteam_goals "0"}

{:event/type "goal"
:event/elapsed 34
:event/player2 "Pepe"
:event/player1 "Asier Illarramendi"
:event/sortorder 0
:event/team "home"
:event/id "event_3280345"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_23592"}

{:event/type "card"
:event/elapsed 39
:event/card_type "y"
:event/player1 "Alberto Rivera"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3280401"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_23592"}

{:event/type "card"
:event/elapsed 50
:event/card_type "y"
:event/player1 "Pepe"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3280592"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_23592"}

{:event/type "card"
:event/elapsed 62
:event/card_type "y"
:event/player1 "Alberto Botia"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3280819"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_23592"}

{:event/type "card"
:event/elapsed 69
:event/card_type "y"
:event/player1 "Javi Moreno Marquez"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3280952"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_23592"}

{:event/type "goal"
:event/elapsed 72
:event/player2 "Xabi Alonso"
:event/player1 "Gareth Bale"
:event/sortorder 0
:event/team "home"
:event/id "event_3280970"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_23592"}

{:event/type "goal"
:event/elapsed 81
:event/player2 "Karim Benzema"
:event/player1 "Isco"
:event/sortorder 0
:event/team "home"
:event/id "event_3281118"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_23592"}


]

