
;;# data
[
{:match/id "match_10375"
:match/league "Italy Serie A"
:match/hometeam "Inter"
:match/awayteam "Catania"
:match/score "1:2"
:match/hometeam_goals "2"
:match/awayteam_goals "1"}

{:event/type "goal"
:event/elapsed 42
:event/player1 "Gianvito Plasmati"
:event/sortorder 0
:event/team "away"
:event/id "event_402627"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_10375"}

{:event/type "goal"
:event/elapsed 43
:event/player1 "Ricardo Quaresma"
:event/sortorder 0
:event/team "home"
:event/id "event_402628"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_10375"}

{:event/type "card"
:event/elapsed 45
:event/card_type "r"
:event/player1 "Sulley Ali Muntari"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_402524"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_10375"}

{:event/type "card"
:event/elapsed 45
:event/card_type "y"
:event/player1 "Giacomo Tedesco"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_402599"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_10375"}

{:event/type "goal"
:event/elapsed 48
:event/player1 "Christian Terlizzi"
:event/sortorder 0
:event/team "away"
:event/id "event_402629"
:event/event_type "goal"
:event/goal_type "o"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_10375"}

{:event/type "card"
:event/elapsed 59
:event/card_type "y"
:event/player1 "Patrick Vieira"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_402665"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_10375"}

{:event/type "card"
:event/elapsed 62
:event/card_type "y"
:event/player1 "Pablo Martin Ledesma"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_402675"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_10375"}

{:event/type "card"
:event/elapsed 65
:event/card_type "y"
:event/player1 "Marco Biagianti"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_402685"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_10375"}

{:event/type "card"
:event/elapsed 75
:event/card_type "y"
:event/player1 "Nicolae Dica"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_402718"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_10375"}

{:event/type "card"
:event/elapsed 83
:event/card_type "y"
:event/player1 "Maicon"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_402788"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_10375"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Michele Paolucci"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_402810"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_10375"}


]

