
;;# data
[
{:match/id "match_22526"
:match/league "Spain LIGA BBVA"
:match/hometeam "Racing Santander"
:match/awayteam "Levante UD"
:match/score "0:2"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "card"
:event/elapsed 19
:event/card_type "y"
:event/player1 "Henrique"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1498810"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_22526"}

{:event/type "goal"
:event/elapsed 32
:event/player1 "Victoriano Rivas Nano"
:event/sortorder 0
:event/team "away"
:event/id "event_1498944"
:event/event_type "goal"
:event/goal_type "o"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_22526"}

{:event/type "card"
:event/elapsed 61
:event/card_type "y"
:event/player1 "Miguel Pallardo"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1499199"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_22526"}

{:event/type "card"
:event/elapsed 62
:event/card_type "y"
:event/player1 "Ivan Bolado"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1499198"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_22526"}

{:event/type "card"
:event/elapsed 84
:event/card_type "y"
:event/player1 "Gonzalo Colsa"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1499481"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_22526"}

{:event/type "goal"
:event/elapsed 90
:event/player1 "Rafa Jorda"
:event/sortorder 0
:event/team "away"
:event/id "event_1499449"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_22526"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Manolo Reina"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1499482"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_22526"}


]

