
;;# data
[
{:match/id "match_4050"
:match/league "England Premier League"
:match/hometeam "Liverpool"
:match/awayteam "Stoke City"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "Joe Allen"
:event/player1 "Steve Sidwell"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3969227"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_4050"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Marko Arnautovic"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3969255"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_4050"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Jordan Henderson"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3969314"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_4050"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Jonathan Walters"
:event/subtype "pushing"
:event/player1 "Raheem Sterling"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3969376"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_4050"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Marko Arnautovic"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3969406"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_4050"}

{:event/type "shoton"
:event/elapsed 12
:event/subtype "blocked_shot"
:event/player1 "Erik Pieters"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3969478"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_4050"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Erik Pieters"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3969486"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_4050"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Bojan Krkic"
:event/subtype "trip"
:event/player1 "Lucas Leiva"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3969544"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_4050"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_3969599"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_4050"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Steve Sidwell"
:event/subtype "dangerous_play"
:event/player1 "Rickie Lambert"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3969638"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_4050"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Erik Pieters"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3969654"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_4050"}

{:event/type "corner"
:event/elapsed 23
:event/subtype "cross_left"
:event/player1 "Philippe Coutinho"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3969705"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_4050"}

{:event/type "foulcommit"
:event/elapsed 23
:event/player2 "Bojan Krkic"
:event/player1 "Jose Enrique"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3969708"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_4050"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Jordan Henderson"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3969735"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_4050"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Rickie Lambert"
:event/subtype "dangerous_play"
:event/player1 "Glenn Whelan"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3969739"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_4050"}

{:event/type "shotoff"
:event/elapsed 27
:event/subtype "direct_freekick"
:event/player1 "Rickie Lambert"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3969755"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_4050"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Steven Nzonzi"
:event/subtype "pushing"
:event/player1 "Rickie Lambert"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3969826"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_4050"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player2 "Marko Arnautovic"
:event/subtype "trip"
:event/player1 "Jordan Henderson"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3969830"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_4050"}

{:event/type "foulcommit"
:event/elapsed 34
:event/player2 "Joe Allen"
:event/subtype "trip"
:event/player1 "Bojan Krkic"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3969865"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_4050"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Jose Enrique"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3969874"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_4050"}

{:event/type "corner"
:event/elapsed 35
:event/subtype "short_right"
:event/player1 "Joe Allen"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3969894"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_4050"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Joe Allen"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3969896"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_4050"}

{:event/type "shotoff"
:event/elapsed 36
:event/subtype "volley"
:event/player1 "Martin Skrtel"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3969901"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_4050"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Geoff Cameron"
:event/subtype "dangerous_play"
:event/player1 "Raheem Sterling"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3969926"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_4050"}

{:event/type "shotoff"
:event/elapsed 37
:event/subtype "shot"
:event/player1 "Jonathan Walters"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3969937"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_4050"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Rickie Lambert"
:event/subtype "pull"
:event/player1 "Marc Wilson"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3969961"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_4050"}

{:event/type "card"
:event/elapsed 38
:event/card_type "y"
:event/player1 "Marc Wilson"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_3969962"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_4050"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Jordan Henderson"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3969978"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_4050"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Philippe Coutinho"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3969986"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_4050"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Rickie Lambert"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3970014"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_4050"}

{:event/type "foulcommit"
:event/elapsed 41
:event/subtype "hands"
:event/player1 "Glenn Whelan"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3970031"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_4050"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Philippe Coutinho"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3970045"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_4050"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Philippe Coutinho"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_3970054"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_4050"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Geoff Cameron"
:event/subtype "pull"
:event/player1 "Raheem Sterling"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3970078"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_4050"}

{:event/type "corner"
:event/elapsed 44
:event/subtype "cross_right"
:event/player1 "Bojan Krkic"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3970106"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_4050"}

{:event/type "shotoff"
:event/elapsed 44
:event/subtype "header"
:event/player1 "Mame Biram Diouf"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3970119"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_4050"}

{:event/type "shotoff"
:event/elapsed 45
:event/subtype "bad shot"
:event/player1 "Philippe Coutinho"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3970153"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_4050"}

{:event/type "foulcommit"
:event/elapsed 46
:event/player2 "Philippe Coutinho"
:event/player1 "Ryan Shawcross"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3970411"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_4050"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Glen Johnson"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3970418"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_4050"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Jonathan Walters"
:event/sortorder 8
:event/team "away"
:event/event_type "cross"
:event/id "event_3970191"
:event/minute 47
:event/match_id "match_4050"}

{:event/type "shoton"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "blocked_shot"
:event/player1 "Mame Biram Diouf"
:event/sortorder 9
:event/team "away"
:event/event_type "shoton"
:event/id "event_3970202"
:event/minute 47
:event/match_id "match_4050"}

{:event/type "shoton"
:event/elapsed 48
:event/subtype "blocked_shot"
:event/player1 "Joe Allen"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3970451"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_4050"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Raheem Sterling"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3970507"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_4050"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Jordan Henderson"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3970509"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_4050"}

{:event/type "shotoff"
:event/elapsed 52
:event/subtype "volley"
:event/player1 "Jordan Henderson"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3970606"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_4050"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Raheem Sterling"
:event/subtype "trip"
:event/player1 "Geoff Cameron"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3970657"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_4050"}

{:event/type "card"
:event/elapsed 53
:event/card_type "y"
:event/player1 "Geoff Cameron"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_3970659"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_4050"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Philippe Coutinho"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3970685"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_4050"}

{:event/type "shoton"
:event/elapsed 55
:event/subtype "big chance shot"
:event/player1 "Mame Biram Diouf"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3970714"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_4050"}

{:event/type "shoton"
:event/elapsed 56
:event/subtype "deflected"
:event/player1 "Steven Nzonzi"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3970729"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_4050"}

{:event/type "shoton"
:event/elapsed 58
:event/subtype "blocked_shot"
:event/player1 "Steven Nzonzi"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_3970803"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_4050"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Raheem Sterling"
:event/subtype "obstruction"
:event/player1 "Ryan Shawcross"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3970807"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_4050"}

{:event/type "card"
:event/elapsed 58
:event/card_type "y"
:event/player1 "Ryan Shawcross"
:event/sortorder 4
:event/team "away"
:event/event_type "card"
:event/id "event_3970812"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_4050"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Philippe Coutinho"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3970822"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_4050"}

{:event/type "shotoff"
:event/elapsed 60
:event/subtype "post"
:event/player1 "Bojan Krkic"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3970842"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_4050"}

{:event/type "shotoff"
:event/elapsed 60
:event/subtype "volley"
:event/player1 "Bojan Krkic"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3970848"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_4050"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Jose Enrique"
:event/player1 "Mame Biram Diouf"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3970866"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_4050"}

{:event/type "shotoff"
:event/elapsed 61
:event/subtype "big chance shot"
:event/player1 "Raheem Sterling"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3970877"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_4050"}

{:event/type "foulcommit"
:event/elapsed 62
:event/player2 "Ryan Shawcross"
:event/subtype "pushing"
:event/player1 "Rickie Lambert"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3970894"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_4050"}

{:event/type "shoton"
:event/elapsed 65
:event/subtype "big chance shot"
:event/player1 "Lucas Leiva"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3970982"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_4050"}

{:event/type "shoton"
:event/elapsed 68
:event/subtype "big chance shot"
:event/player1 "Rickie Lambert"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3971070"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_4050"}

{:event/type "shotoff"
:event/elapsed 69
:event/subtype "big chance volley"
:event/player1 "Joe Allen"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3971098"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_4050"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Erik Pieters"
:event/subtype "pull"
:event/player1 "Glen Johnson"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3971115"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_4050"}

{:event/type "shoton"
:event/elapsed 75
:event/subtype "shot"
:event/player1 "Charlie Adam"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_3971212"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_4050"}

{:event/type "shoton"
:event/elapsed 80
:event/subtype "blocked_shot"
:event/player1 "Charlie Adam"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3971318"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_4050"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3971328"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_4050"}

{:event/type "shotoff"
:event/elapsed 80
:event/subtype "deflected"
:event/player1 "Joe Allen"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3971332"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_4050"}

{:event/type "corner"
:event/elapsed 81
:event/subtype "cross_right"
:event/player1 "Philippe Coutinho"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3971336"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_4050"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Ryan Shawcross"
:event/subtype "pushing"
:event/player1 "Martin Skrtel"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3971340"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_4050"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Jonathan Walters"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3971351"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_4050"}

{:event/type "corner"
:event/elapsed 82
:event/subtype "cross_left"
:event/player1 "Charlie Adam"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_3971365"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_4050"}

{:event/type "shoton"
:event/elapsed 82
:event/subtype "big chance shot"
:event/player1 "Mame Biram Diouf"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_3971371"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_4050"}

{:event/type "shoton"
:event/elapsed 82
:event/subtype "shot"
:event/player1 "Jonathan Walters"
:event/sortorder 4
:event/team "away"
:event/event_type "shoton"
:event/id "event_3971379"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_4050"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Glen Johnson"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3971388"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_4050"}

{:event/type "shoton"
:event/elapsed 83
:event/subtype "blocked_header"
:event/player1 "Philippe Coutinho"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3971392"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_4050"}

{:event/type "corner"
:event/elapsed 83
:event/subtype "cross_right"
:event/player1 "Steven Gerrard"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_3971394"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_4050"}

{:event/type "shoton"
:event/elapsed 84
:event/subtype "blocked_shot"
:event/player1 "Jose Enrique"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3971402"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_4050"}

{:event/type "corner"
:event/elapsed 84
:event/subtype "cross_left"
:event/player1 "Philippe Coutinho"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3971406"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_4050"}

{:event/type "shoton"
:event/elapsed 84
:event/subtype "blocked_shot"
:event/player1 "Martin Skrtel"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_3971408"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_4050"}

{:event/type "shoton"
:event/elapsed 85
:event/subtype "blocked_shot"
:event/player1 "Jordan Henderson"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3971416"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_4050"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Jordan Henderson"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3971430"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_4050"}

{:event/type "shotoff"
:event/elapsed 85
:event/subtype "big chance crossbar"
:event/player1 "Rickie Lambert"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3971436"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_4050"}

{:event/type "goal"
:event/elapsed 85
:event/subtype "loose_ball"
:event/player1 "Glen Johnson"
:event/sortorder 3
:event/team "home"
:event/id "event_3971440"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_4050"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Jonathan Walters"
:event/subtype "advantage"
:event/player1 "Dejan Lovren"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3971540"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_4050"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Ryan Shawcross"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3971541"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_4050"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "bad shot"
:event/player1 "Bojan Krkic"
:event/sortorder 7
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3971572"
:event/minute 91
:event/match_id "match_4050"}

{:event/type "shoton"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "volley"
:event/player1 "Bojan Krkic"
:event/sortorder 11
:event/team "away"
:event/event_type "shoton"
:event/id "event_3971594"
:event/minute 92
:event/match_id "match_4050"}

{:event/type "corner"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross_right"
:event/player1 "Charlie Adam"
:event/sortorder 12
:event/team "away"
:event/event_type "corner"
:event/id "event_3971596"
:event/minute 92
:event/match_id "match_4050"}

{:event/type "corner"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross_right"
:event/player1 "Charlie Adam"
:event/sortorder 15
:event/team "away"
:event/event_type "corner"
:event/id "event_3971617"
:event/minute 93
:event/match_id "match_4050"}

{:event/type "shotoff"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "big chance header"
:event/player1 "Ryan Shawcross"
:event/sortorder 16
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3971621"
:event/minute 94
:event/match_id "match_4050"}

{:event/type "cross"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Ryan Shawcross"
:event/sortorder 18
:event/team "away"
:event/event_type "cross"
:event/id "event_3971639"
:event/minute 95
:event/match_id "match_4050"}

{:event/type "corner"
:event/elapsed_plus 6
:event/elapsed 90
:event/subtype "cross_right"
:event/player1 "Charlie Adam"
:event/sortorder 19
:event/team "away"
:event/event_type "corner"
:event/id "event_3971641"
:event/minute 96
:event/match_id "match_4050"}


]

