
;;# data
[
{:match/id "match_2183"
:match/league "England Premier League"
:match/hometeam "Liverpool"
:match/awayteam "Arsenal"
:match/score "2:1"
:match/hometeam_goals "1"
:match/awayteam_goals "2"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Theo Walcott"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_880799"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_2183"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Cesc Fabregas"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_880801"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_2183"}

{:event/type "corner"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Cesc Fabregas"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_880801"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_2183"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Lucas Leiva"
:event/player1 "Alex Song"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_880805"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_2183"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Denilson"
:event/player1 "Javier Mascherano"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_880812"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_2183"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Alex Song"
:event/player1 "Glen Johnson"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_880836"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_2183"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Alex Song"
:event/player1 "Fernando Torres"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_880838"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_2183"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Armand Traore"
:event/player1 "Javier Mascherano"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_880845"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_2183"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_880848"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_2183"}

{:event/type "shoton"
:event/elapsed 12
:event/subtype "big chance shot"
:event/player1 "Fernando Torres"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_880849"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_2183"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Bacary Sagna"
:event/player1 "Fabio Aurelio"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_880857"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_2183"}

{:event/type "shotoff"
:event/elapsed 14
:event/subtype "header"
:event/player1 "Thomas Vermaelen"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_880860"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_2183"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Fernando Torres"
:event/player1 "Alex Song"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_880871"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_2183"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Fabio Aurelio"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_880876"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_2183"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Bacary Sagna"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_880882"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_2183"}

{:event/type "corner"
:event/elapsed 19
:event/subtype "short"
:event/player1 "Cesc Fabregas"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_880884"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_2183"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player2 "Denilson"
:event/player1 "Yossi Benayoun"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_880886"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_2183"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Bacary Sagna"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_880887"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_2183"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Javier Mascherano"
:event/player1 "Bacary Sagna"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_880899"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_2183"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_880904"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_2183"}

{:event/type "corner"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_880904"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_2183"}

{:event/type "shoton"
:event/elapsed 24
:event/subtype "blocked_shot"
:event/player1 "Glen Johnson"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_880906"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_2183"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Fabio Aurelio"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_880907"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_2183"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Javier Mascherano"
:event/subtype "serious_foul"
:event/player1 "Denilson"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_880909"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_2183"}

{:event/type "card"
:event/elapsed 24
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Denilson"
:event/sortorder 4
:event/team "away"
:event/event_type "card"
:event/id "event_880910"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_2183"}

{:event/type "shoton"
:event/elapsed 25
:event/subtype "deflected"
:event/player1 "Glen Johnson"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_880915"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_2183"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_880916"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_2183"}

{:event/type "corner"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_880916"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_2183"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Dirk Kuyt"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_880924"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_2183"}

{:event/type "shoton"
:event/elapsed 28
:event/subtype "blocked_shot"
:event/player1 "Steven Gerrard"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_880925"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_2183"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Theo Walcott"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_880926"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2183"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Denilson"
:event/player1 "Fabio Aurelio"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_880932"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2183"}

{:event/type "shoton"
:event/elapsed 35
:event/subtype "distance"
:event/player1 "Denilson"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_880948"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_2183"}

{:event/type "shotoff"
:event/elapsed 35
:event/subtype "distance"
:event/player1 "Samir Nasri"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_880952"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_2183"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Theo Walcott"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_880956"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_2183"}

{:event/type "foulcommit"
:event/elapsed 40
:event/player2 "Steven Gerrard"
:event/player1 "Denilson"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_880968"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_2183"}

{:event/type "goal"
:event/elapsed 41
:event/subtype "loose_ball"
:event/player1 "Dirk Kuyt"
:event/sortorder 2
:event/team "home"
:event/id "event_880971"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_2183"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Javier Mascherano"
:event/player1 "Alex Song"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_880976"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_2183"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_880978"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_2183"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Theo Walcott"
:event/subtype "serious_foul"
:event/player1 "Fabio Aurelio"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_880980"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_2183"}

{:event/type "card"
:event/elapsed 44
:event/card_type "y"
:event/subtype "emergency_brake"
:event/player1 "Fabio Aurelio"
:event/sortorder 3
:event/team "home"
:event/event_type "card"
:event/id "event_880982"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_2183"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "Armand Traore"
:event/player1 "Fernando Torres"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_880993"
:event/minute 46
:event/match_id "match_2183"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Theo Walcott"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_880996"
:event/minute 47
:event/match_id "match_2183"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_881035"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_2183"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Bacary Sagna"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_881038"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_2183"}

{:event/type "corner"
:event/elapsed 48
:event/subtype "short"
:event/player1 "Cesc Fabregas"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_881042"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_2183"}

{:event/type "shoton"
:event/elapsed 48
:event/subtype "shot"
:event/player1 "Cesc Fabregas"
:event/sortorder 5
:event/team "away"
:event/event_type "shoton"
:event/id "event_881043"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_2183"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Samir Nasri"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_881049"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_2183"}

{:event/type "goal"
:event/elapsed 50
:event/player1 "Glen Johnson"
:event/sortorder 1
:event/team "home"
:event/id "event_881050"
:event/event_type "goal"
:event/goal_type "o"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_2183"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Cesc Fabregas"
:event/subtype "serious_foul"
:event/player1 "Javier Mascherano"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_881067"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_2183"}

{:event/type "card"
:event/elapsed 55
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Javier Mascherano"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_881068"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_2183"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Cesc Fabregas"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_881081"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_2183"}

{:event/type "goal"
:event/elapsed 58
:event/player2 "Cesc Fabregas"
:event/subtype "shot"
:event/player1 "Andrey Arshavin"
:event/sortorder 1
:event/team "away"
:event/id "event_881082"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_2183"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player2 "Jamie Carragher"
:event/player1 "Andrey Arshavin"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_881089"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_2183"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Daniel Agger"
:event/player1 "Andrey Arshavin"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_881098"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_2183"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Dirk Kuyt"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_881113"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_2183"}

{:event/type "foulcommit"
:event/elapsed 72
:event/subtype "hands"
:event/player1 "Dirk Kuyt"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_881119"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_2183"}

{:event/type "shoton"
:event/elapsed 72
:event/subtype "distance"
:event/player1 "Andrey Arshavin"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_881122"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_2183"}

{:event/type "foulcommit"
:event/elapsed 74
:event/player2 "Fernando Torres"
:event/player1 "Thomas Vermaelen"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_881127"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_2183"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_881131"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_2183"}

{:event/type "corner"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Steven Gerrard"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_881131"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_2183"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Dirk Kuyt"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_881135"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_2183"}

{:event/type "foulcommit"
:event/elapsed 79
:event/player2 "David Ngog"
:event/player1 "Alex Song"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_881143"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_2183"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Daniel Agger"
:event/subtype "serious_foul"
:event/player1 "Andrey Arshavin"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_881149"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_2183"}

{:event/type "card"
:event/elapsed 81
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Andrey Arshavin"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_881150"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_2183"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Alberto Aquilani"
:event/player1 "Samir Nasri"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_881151"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_2183"}

{:event/type "card"
:event/elapsed 82
:event/card_type "y"
:event/subtype "kicked_ball_away"
:event/player1 "Cesc Fabregas"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_881152"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_2183"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Cesc Fabregas"
:event/subtype "serious_foul"
:event/player1 "Lucas Leiva"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_881159"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_2183"}

{:event/type "card"
:event/elapsed 85
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Lucas Leiva"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_881160"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_2183"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Jamie Carragher"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_881175"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_2183"}

{:event/type "shotoff"
:event/elapsed 90
:event/subtype "header"
:event/player1 "Fernando Torres"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_881176"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_2183"}

{:event/type "shoton"
:event/elapsed 90
:event/subtype "deflected"
:event/player1 "Andrey Arshavin"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_881178"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_2183"}

{:event/type "corner"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "short"
:event/player1 "Cesc Fabregas"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_881182"
:event/minute 91
:event/match_id "match_2183"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Cesc Fabregas"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_881183"
:event/minute 91
:event/match_id "match_2183"}

{:event/type "foulcommit"
:event/elapsed_plus 4
:event/elapsed 90
:event/player2 "Aaron Ramsey"
:event/player1 "Steven Gerrard"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_881196"
:event/minute 94
:event/match_id "match_2183"}


]

