
;;# data
[
{:match/id "match_6489"
:match/league "France Ligue 1"
:match/hometeam "AC Ajaccio"
:match/awayteam "FC Lorient"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 69
:event/card_type "y"
:event/player1 "Bruno Ecuele Manga"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2642347"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_6489"}

{:event/type "goal"
:event/elapsed 75
:event/player1 "Ronald Zubar"
:event/sortorder 0
:event/team "home"
:event/id "event_2642346"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_6489"}

{:event/type "card"
:event/elapsed 77
:event/card_type "y"
:event/player1 "Lamine Gassama"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_2642390"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_6489"}

{:event/type "card"
:event/elapsed 85
:event/card_type "y"
:event/player1 "Anthony Lippini"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_2642391"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_6489"}


]

