
;;# data
[
{:match/id "match_2277"
:match/league "England Premier League"
:match/hometeam "Arsenal"
:match/awayteam "Manchester United"
:match/score "1:3"
:match/hometeam_goals "1"
:match/awayteam_goals "3"}

{:event/type "shotoff"
:event/elapsed 3
:event/subtype "shot"
:event/player1 "Andrey Arshavin"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_935724"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_2277"}

{:event/type "foulcommit"
:event/elapsed 6
:event/player2 "Tomas Rosicky"
:event/player1 "Patrice Evra"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_935735"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Ji-Sung Park"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_935743"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_935750"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_935758"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_2277"}

{:event/type "corner"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_935758"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_935765"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_2277"}

{:event/type "shotoff"
:event/elapsed 13
:event/subtype "shot"
:event/player1 "Andrey Arshavin"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_935792"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_2277"}

{:event/type "shotoff"
:event/elapsed 15
:event/subtype "distance"
:event/player1 "Samir Nasri"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_935802"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_2277"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Michael Carrick"
:event/player1 "Bacary Sagna"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_935807"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_2277"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "Nani"
:event/subtype "serious_foul"
:event/player1 "Alex Song"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_935823"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_2277"}

{:event/type "card"
:event/elapsed 17
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Alex Song"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_935828"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_2277"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Gael Clichy"
:event/player1 "Nani"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_935840"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_2277"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Cesc Fabregas"
:event/player1 "Patrice Evra"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_935859"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_2277"}

{:event/type "shotoff"
:event/elapsed 24
:event/subtype "distance"
:event/player1 "William Gallas"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_935874"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Michael Carrick"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_935887"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_2277"}

{:event/type "shoton"
:event/elapsed 27
:event/subtype "shot"
:event/player1 "Wayne Rooney"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_935888"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Rafael"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_935894"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_2277"}

{:event/type "shotoff"
:event/elapsed 28
:event/subtype "shot"
:event/player1 "Nani"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_935897"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Ji-Sung Park"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_935903"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2277"}

{:event/type "shoton"
:event/elapsed 29
:event/subtype "deflected"
:event/player1 "Nani"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_935907"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Alex Song"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_935917"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_2277"}

{:event/type "foulcommit"
:event/elapsed 30
:event/player2 "Ji-Sung Park"
:event/player1 "Bacary Sagna"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_935922"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Patrice Evra"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_935940"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_2277"}

{:event/type "goal"
:event/elapsed 33
:event/subtype "shot"
:event/player1 "Nani"
:event/sortorder 0
:event/team "away"
:event/id "event_935944"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_2277"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Alex Song"
:event/player1 "Paul Scholes"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_935957"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Denilson"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_935963"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_2277"}

{:event/type "corner"
:event/elapsed 36
:event/subtype "short"
:event/player1 "Cesc Fabregas"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_935967"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Samir Nasri"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_935968"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_935974"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_2277"}

{:event/type "goal"
:event/elapsed 37
:event/player2 "Nani"
:event/subtype "shot"
:event/player1 "Wayne Rooney"
:event/sortorder 2
:event/team "away"
:event/id "event_935975"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_2277"}

{:event/type "shotoff"
:event/elapsed 38
:event/subtype "distance"
:event/player1 "Andrey Arshavin"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_935985"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Wayne Rooney"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_936002"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_2277"}

{:event/type "shotoff"
:event/elapsed 41
:event/subtype "shot"
:event/player1 "Nani"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_936003"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Cesc Fabregas"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_936025"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_2277"}

{:event/type "corner"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Cesc Fabregas"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_936025"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Rafael"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_936038"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Gael Clichy"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_936155"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_2277"}

{:event/type "shotoff"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "shot"
:event/player1 "Alex Song"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_936047"
:event/minute 47
:event/match_id "match_2277"}

{:event/type "corner"
:event/elapsed 49
:event/subtype "short"
:event/player1 "Nani"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_936184"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_2277"}

{:event/type "shoton"
:event/elapsed 50
:event/subtype "distance"
:event/player1 "Wayne Rooney"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_936192"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_2277"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Andrey Arshavin"
:event/player1 "Nani"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_936207"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_2277"}

{:event/type "goal"
:event/elapsed 52
:event/player2 "Michael Carrick"
:event/subtype "shot"
:event/player1 "Ji-Sung Park"
:event/sortorder 1
:event/team "away"
:event/id "event_936215"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_2277"}

{:event/type "shotoff"
:event/elapsed 54
:event/subtype "distance"
:event/player1 "Cesc Fabregas"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_936235"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "William Gallas"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_936258"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_2277"}

{:event/type "shoton"
:event/elapsed 56
:event/subtype "shot"
:event/player1 "Cesc Fabregas"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_936260"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_2277"}

{:event/type "shoton"
:event/elapsed 58
:event/subtype "distance"
:event/player1 "Alex Song"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_936271"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Patrice Evra"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_936279"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_936286"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_2277"}

{:event/type "corner"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_936286"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_2277"}

{:event/type "shotoff"
:event/elapsed 60
:event/subtype "volley"
:event/player1 "Alex Song"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_936296"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_2277"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Alex Song"
:event/player1 "Nani"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_936327"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_2277"}

{:event/type "corner"
:event/elapsed 64
:event/subtype "short"
:event/player1 "Cesc Fabregas"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_936330"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Bacary Sagna"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_936331"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_2277"}

{:event/type "shotoff"
:event/elapsed 64
:event/subtype "distance"
:event/player1 "Cesc Fabregas"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_936337"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_936349"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_2277"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Cesc Fabregas"
:event/player1 "Jonny Evans"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_936363"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_2277"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Andrey Arshavin"
:event/player1 "Paul Scholes"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_936367"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Cesc Fabregas"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_936382"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_2277"}

{:event/type "corner"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Cesc Fabregas"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_936382"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Cesc Fabregas"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_936385"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Wayne Rooney"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_936390"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Cesc Fabregas"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_936429"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_2277"}

{:event/type "corner"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Cesc Fabregas"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_936429"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Samir Nasri"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_936438"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_2277"}

{:event/type "shotoff"
:event/elapsed 75
:event/subtype "shot"
:event/player1 "Wayne Rooney"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_936441"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_2277"}

{:event/type "goal"
:event/elapsed 80
:event/subtype "deflected"
:event/player1 "Thomas Vermaelen"
:event/sortorder 0
:event/team "home"
:event/id "event_936492"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Andrey Arshavin"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_936509"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Cesc Fabregas"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_936512"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_2277"}

{:event/type "corner"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Cesc Fabregas"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_936512"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_2277"}

{:event/type "shotoff"
:event/elapsed 83
:event/subtype "distance"
:event/player1 "Nani"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_936523"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_936548"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_2277"}

{:event/type "corner"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_936548"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Ryan Giggs"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_936554"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Andrey Arshavin"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_936562"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_2277"}

{:event/type "corner"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Andrey Arshavin"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_936562"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Nani"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_936569"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Emmanuel Eboue"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_936586"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_2277"}

{:event/type "corner"
:event/elapsed 88
:event/subtype "short"
:event/player1 "Cesc Fabregas"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_936589"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Emmanuel Eboue"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_936601"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Nicklas Bendtner"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_936606"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_2277"}

{:event/type "shotoff"
:event/elapsed 90
:event/subtype "big chance header"
:event/player1 "William Gallas"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_936607"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_2277"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Antonio Valencia"
:event/player1 "Andrey Arshavin"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_936618"
:event/minute 91
:event/match_id "match_2277"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Rafael"
:event/player1 "Samir Nasri"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_936632"
:event/minute 93
:event/match_id "match_2277"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Dimitar Berbatov"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_936647"
:event/minute 94
:event/match_id "match_2277"}

{:event/type "shotoff"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "post"
:event/player1 "Wayne Rooney"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_936649"
:event/minute 94
:event/match_id "match_2277"}


]

