
;;# data
[
{:match/id "match_3821"
:match/league "England Premier League"
:match/hometeam "Chelsea"
:match/awayteam "Everton"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Eden Hazard"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3279455"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Frank Lampard"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3279457"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_3821"}

{:event/type "corner"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Frank Lampard"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3279457"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Frank Lampard"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_3279459"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_3821"}

{:event/type "corner"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Frank Lampard"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_3279459"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_3821"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Seamus Coleman"
:event/subtype "obstruction"
:event/player1 "Cesar Azpilicueta"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3279462"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_3821"}

{:event/type "shotoff"
:event/elapsed 4
:event/subtype "shot"
:event/player1 "Willian"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3279466"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Nemanja Matic"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3279468"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 6
:event/subtype "cross"
:event/player1 "Cesar Azpilicueta"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3279471"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_3821"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Kevin Mirallas"
:event/subtype "trip"
:event/player1 "Cesar Azpilicueta"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3279475"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3279477"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_3821"}

{:event/type "shoton"
:event/elapsed 8
:event/subtype "deflected"
:event/player1 "Oscar"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_3279479"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Frank Lampard"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3279480"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3821"}

{:event/type "corner"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Frank Lampard"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3279480"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3821"}

{:event/type "shoton"
:event/elapsed 9
:event/subtype "header"
:event/player1 "John Terry"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3279482"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Frank Lampard"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3279483"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3821"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Steven Naismith"
:event/subtype "dangerous_play"
:event/player1 "Oscar"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3279485"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3821"}

{:event/type "card"
:event/elapsed 9
:event/card_type "y"
:event/player1 "Oscar"
:event/sortorder 5
:event/team "home"
:event/event_type "card"
:event/id "event_3279486"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3279489"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_3821"}

{:event/type "shoton"
:event/elapsed 13
:event/subtype "shot"
:event/player1 "Leon Osman"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3279490"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 13
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3279492"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_3821"}

{:event/type "corner"
:event/elapsed 13
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3279492"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_3821"}

{:event/type "shoton"
:event/elapsed 13
:event/subtype "deflected"
:event/player1 "Sylvain Distin"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_3279495"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3279496"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_3821"}

{:event/type "corner"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3279496"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_3821"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "Kevin Mirallas"
:event/subtype "trip"
:event/player1 "Cesar Azpilicueta"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3279502"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_3821"}

{:event/type "shoton"
:event/elapsed 17
:event/subtype "blocked_shot"
:event/player1 "Kevin Mirallas"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_3279505"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_3279507"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_3821"}

{:event/type "corner"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_3279507"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_3821"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "John Terry"
:event/subtype "pushing"
:event/player1 "Leon Osman"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3279509"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_3821"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Steven Pienaar"
:event/subtype "trip"
:event/player1 "Branislav Ivanovic"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3279516"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_3821"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Steven Naismith"
:event/subtype "pull"
:event/player1 "Frank Lampard"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3279523"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Eden Hazard"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3279527"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Branislav Ivanovic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3279536"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_3821"}

{:event/type "shotoff"
:event/elapsed 28
:event/subtype "miss_kick"
:event/player1 "Samuel Eto'o"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3279538"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Eden Hazard"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3279540"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Eden Hazard"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3279542"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_3821"}

{:event/type "shoton"
:event/elapsed 29
:event/subtype "blocked_shot"
:event/player1 "Branislav Ivanovic"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_3279544"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_3821"}

{:event/type "shoton"
:event/elapsed 30
:event/subtype "shot"
:event/player1 "Cesar Azpilicueta"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3279546"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Branislav Ivanovic"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_3279554"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3279558"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3821"}

{:event/type "shotoff"
:event/elapsed 33
:event/subtype "header"
:event/player1 "Frank Lampard"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3279559"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Seamus Coleman"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_3279562"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_3821"}

{:event/type "corner"
:event/elapsed 34
:event/subtype "short"
:event/player1 "Kevin Mirallas"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3279566"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Kevin Mirallas"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_3279567"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_3821"}

{:event/type "shotoff"
:event/elapsed 34
:event/subtype "header"
:event/player1 "Phil Jagielka"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_3279569"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_3821"}

{:event/type "shoton"
:event/elapsed 37
:event/subtype "big chance shot"
:event/player1 "Samuel Eto'o"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3279577"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3279578"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Kevin Mirallas"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3279580"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_3821"}

{:event/type "corner"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Kevin Mirallas"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_3279580"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Kevin Mirallas"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_3279587"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_3821"}

{:event/type "corner"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Kevin Mirallas"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_3279587"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_3821"}

{:event/type "shoton"
:event/elapsed 40
:event/subtype "deflected"
:event/player1 "Willian"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_3279590"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3279592"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3821"}

{:event/type "corner"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_3279592"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3821"}

{:event/type "shotoff"
:event/elapsed 41
:event/subtype "header"
:event/player1 "John Terry"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3279593"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_3821"}

{:event/type "foulcommit"
:event/elapsed 43
:event/player2 "Willian"
:event/subtype "trip"
:event/player1 "Steven Pienaar"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3279596"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Frank Lampard"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3279598"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_3821"}

{:event/type "foulcommit"
:event/elapsed 44
:event/player2 "Seamus Coleman"
:event/subtype "pushing"
:event/player1 "Nemanja Matic"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3279599"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_3821"}

{:event/type "shoton"
:event/elapsed 45
:event/subtype "blocked_shot"
:event/player1 "James McCarthy"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3279603"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_3279606"
:event/minute 46
:event/match_id "match_3821"}

{:event/type "foulcommit"
:event/elapsed 46
:event/player2 "Steven Pienaar"
:event/subtype "trip"
:event/player1 "Branislav Ivanovic"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3279649"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_3821"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "blocked_shot"
:event/player1 "Leon Osman"
:event/sortorder 4
:event/team "away"
:event/event_type "shoton"
:event/id "event_3279608"
:event/minute 46
:event/match_id "match_3821"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "distance"
:event/player1 "Eden Hazard"
:event/sortorder 6
:event/team "home"
:event/event_type "shoton"
:event/id "event_3279611"
:event/minute 46
:event/match_id "match_3821"}

{:event/type "shoton"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "shot"
:event/player1 "Willian"
:event/sortorder 8
:event/team "home"
:event/event_type "shoton"
:event/id "event_3279614"
:event/minute 47
:event/match_id "match_3821"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 45
:event/player2 "Kevin Mirallas"
:event/subtype "trip"
:event/player1 "Oscar"
:event/sortorder 9
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3279616"
:event/minute 47
:event/match_id "match_3821"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Ramires"
:event/subtype "trip"
:event/player1 "Leon Osman"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3279656"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_3821"}

{:event/type "shoton"
:event/elapsed 50
:event/subtype "shot"
:event/player1 "Eden Hazard"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3279659"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_3821"}

{:event/type "shoton"
:event/elapsed 50
:event/subtype "blocked_shot"
:event/player1 "Frank Lampard"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_3279660"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Frank Lampard"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3279662"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3821"}

{:event/type "corner"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Frank Lampard"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3279662"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3821"}

{:event/type "shoton"
:event/elapsed 51
:event/subtype "deflected"
:event/player1 "John Terry"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_3279664"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_3279665"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3821"}

{:event/type "corner"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_3279665"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_3821"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Gary Cahill"
:event/subtype "trip"
:event/player1 "Gareth Barry"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3279668"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_3821"}

{:event/type "shotoff"
:event/elapsed 53
:event/subtype "direct_freekick"
:event/player1 "Willian"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3279670"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_3821"}

{:event/type "shotoff"
:event/elapsed 55
:event/subtype "distance"
:event/player1 "Ramires"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3279678"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_3821"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Nemanja Matic"
:event/subtype "pushing"
:event/player1 "Leon Osman"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3279682"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_3821"}

{:event/type "shoton"
:event/elapsed 58
:event/subtype "shot"
:event/player1 "Leon Osman"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3279686"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3279687"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_3821"}

{:event/type "corner"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Leighton Baines"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_3279687"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Frank Lampard"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3279692"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_3821"}

{:event/type "corner"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Frank Lampard"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_3279692"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_3279696"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_3821"}

{:event/type "corner"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Willian"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_3279696"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_3821"}

{:event/type "shoton"
:event/elapsed 61
:event/subtype "shot"
:event/player1 "Eden Hazard"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3279698"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_3821"}

{:event/type "shoton"
:event/elapsed 61
:event/subtype "big chance blocked"
:event/player1 "Branislav Ivanovic"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_3279700"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 62
:event/subtype "cross"
:event/player1 "Branislav Ivanovic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3279702"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_3821"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Steven Pienaar"
:event/subtype "pushing"
:event/player1 "Samuel Eto'o"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3279705"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_3821"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Nemanja Matic"
:event/subtype "trip"
:event/player1 "Ross Barkley"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3279713"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Steven Pienaar"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_3279715"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_3821"}

{:event/type "shoton"
:event/elapsed 67
:event/subtype "blocked_shot"
:event/player1 "Ross Barkley"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_3279718"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_3821"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Ramires"
:event/subtype "trip"
:event/player1 "James McCarthy"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3279719"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_3821"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Leighton Baines"
:event/subtype "trip"
:event/player1 "Samuel Eto'o"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3279720"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_3821"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Sylvain Distin"
:event/subtype "trip"
:event/player1 "Fernando Torres"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3279724"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_3821"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "James McCarthy"
:event/subtype "dangerous_play"
:event/player1 "Fernando Torres"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3279729"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_3821"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Gary Cahill"
:event/subtype "pushing"
:event/player1 "Kevin Mirallas"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3279735"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_3821"}

{:event/type "foulcommit"
:event/elapsed 75
:event/player2 "Gareth Barry"
:event/subtype "trip"
:event/player1 "Nemanja Matic"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3279741"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_3821"}

{:event/type "shotoff"
:event/elapsed 77
:event/subtype "shot"
:event/player1 "Fernando Torres"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3279745"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_3821"}

{:event/type "foulcommit"
:event/elapsed 78
:event/player2 "Cesar Azpilicueta"
:event/subtype "trip"
:event/player1 "Gerard Deulofeu"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3279748"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_3821"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Branislav Ivanovic"
:event/subtype "trip"
:event/player1 "Ross Barkley"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3279764"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_3821"}

{:event/type "card"
:event/elapsed 82
:event/card_type "y"
:event/player1 "Gareth Barry"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_3279765"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_3821"}

{:event/type "shotoff"
:event/elapsed 83
:event/subtype "distance"
:event/player1 "Fernando Torres"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3279767"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_3821"}

{:event/type "shotoff"
:event/elapsed 84
:event/subtype "distance"
:event/player1 "Andre Schuerrle"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3279770"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Branislav Ivanovic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3279779"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_3821"}

{:event/type "shotoff"
:event/elapsed 85
:event/subtype "volley"
:event/player1 "Andre Schuerrle"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3279780"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_3821"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Fernando Torres"
:event/subtype "trip"
:event/player1 "Leighton Baines"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3279786"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Frank Lampard"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_3279789"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_3821"}

{:event/type "shoton"
:event/elapsed 89
:event/subtype "blocked_shot"
:event/player1 "Eden Hazard"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_3279790"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Ramires"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_3279792"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_3821"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Frank Lampard"
:event/subtype "trip"
:event/player1 "Gareth Barry"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3279793"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3821"}

{:event/type "shotoff"
:event/elapsed 90
:event/subtype "distance"
:event/player1 "Ramires"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_3279794"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Fernando Torres"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_3279799"
:event/minute 91
:event/match_id "match_3821"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 90
:event/player2 "Ramires"
:event/subtype "trip"
:event/player1 "Phil Jagielka"
:event/sortorder 6
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_3279806"
:event/minute 92
:event/match_id "match_3821"}

{:event/type "card"
:event/elapsed_plus 3
:event/elapsed 90
:event/card_type "y"
:event/player1 "Phil Jagielka"
:event/sortorder 7
:event/team "away"
:event/event_type "card"
:event/id "event_3279807"
:event/minute 93
:event/match_id "match_3821"}

{:event/type "goal"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "direct_freekick"
:event/player1 "Frank Lampard"
:event/sortorder 8
:event/team "home"
:event/id "event_3279808"
:event/event_type "goal"
:event/goal_type "n"
:event/minute 93
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Ramires"
:event/sortorder 10
:event/team "home"
:event/event_type "cross"
:event/id "event_3279815"
:event/minute 95
:event/match_id "match_3821"}

{:event/type "foulcommit"
:event/elapsed_plus 5
:event/elapsed 90
:event/player2 "Gerard Deulofeu"
:event/subtype "trip"
:event/player1 "Eden Hazard"
:event/sortorder 11
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_3279818"
:event/minute 95
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed_plus 6
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Aiden McGeady"
:event/sortorder 14
:event/team "away"
:event/event_type "cross"
:event/id "event_3279821"
:event/minute 96
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed_plus 6
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Gerard Deulofeu"
:event/sortorder 16
:event/team "away"
:event/event_type "corner"
:event/id "event_3279823"
:event/minute 96
:event/match_id "match_3821"}

{:event/type "corner"
:event/elapsed_plus 6
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Gerard Deulofeu"
:event/sortorder 16
:event/team "away"
:event/event_type "corner"
:event/id "event_3279823"
:event/minute 96
:event/match_id "match_3821"}

{:event/type "cross"
:event/elapsed_plus 6
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Seamus Coleman"
:event/sortorder 18
:event/team "away"
:event/event_type "cross"
:event/id "event_3279825"
:event/minute 96
:event/match_id "match_3821"}


]

