
;;# data
[
{:match/id "match_8045"
:match/league "Germany 1. Bundesliga"
:match/hometeam "Borussia Dortmund"
:match/awayteam "DSC Arminia Bielefeld"
:match/score "6:0"
:match/hometeam_goals "6"
:match/awayteam_goals "0"}

{:event/type "goal"
:event/elapsed 43
:event/player1 "Sebastian Kehl"
:event/sortorder 0
:event/team "home"
:event/id "event_682118"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_8045"}

{:event/type "goal"
:event/elapsed 53
:event/player1 "Tamas Hajnal"
:event/sortorder 0
:event/team "home"
:event/id "event_682527"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_8045"}

{:event/type "card"
:event/elapsed 60
:event/card_type "y"
:event/player1 "Neven Subotic"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_682631"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_8045"}

{:event/type "goal"
:event/elapsed 69
:event/player1 "Nelson Haedo Valdez"
:event/sortorder 0
:event/team "home"
:event/id "event_682659"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_8045"}

{:event/type "goal"
:event/elapsed 72
:event/player1 "Sebastian Kehl"
:event/sortorder 0
:event/team "home"
:event/id "event_682692"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_8045"}

{:event/type "goal"
:event/elapsed 84
:event/player1 "Tinga"
:event/sortorder 0
:event/team "home"
:event/id "event_682828"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_8045"}

{:event/type "goal"
:event/elapsed 87
:event/player1 "Mohamed Zidan"
:event/sortorder 0
:event/team "home"
:event/id "event_682962"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_8045"}


]

