
;;# data
[
{:match/id "match_1773"
:match/league "England Premier League"
:match/hometeam "Newcastle United"
:match/awayteam "Wigan Athletic"
:match/score "2:2"
:match/hometeam_goals "2"
:match/awayteam_goals "2"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Ryan Taylor"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_486939"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_1773"}

{:event/type "shotoff"
:event/elapsed 1
:event/subtype "crossbar"
:event/player1 "Olivier Kapo"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_486942"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_1773"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Nicky Butt"
:event/player1 "Wilson Palacios"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_486965"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_1773"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Damien Duff"
:event/player1 "Maynor Figueroa"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_486912"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Maynor Figueroa"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_486858"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_1773"}

{:event/type "shotoff"
:event/elapsed 3
:event/subtype "header"
:event/player1 "Olivier Kapo"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_486861"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_1773"}

{:event/type "goal"
:event/elapsed 3
:event/subtype "distance"
:event/player1 "Ryan Taylor"
:event/sortorder 2
:event/team "away"
:event/id "event_486865"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_1773"}

{:event/type "foulcommit"
:event/elapsed 6
:event/subtype "hands"
:event/player1 "Shola Ameobi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_486903"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_1773"}

{:event/type "shoton"
:event/elapsed 8
:event/subtype "distance"
:event/player1 "Ryan Taylor"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_486945"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_1773"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Jonas Gutierrez"
:event/player1 "Ryan Taylor"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_486961"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Habib Beye"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_487033"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_1773"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Jonas Gutierrez"
:event/subtype "serious_foul"
:event/player1 "Emmerson Boyce"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_487075"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_1773"}

{:event/type "card"
:event/elapsed 16
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Emmerson Boyce"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_487078"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_1773"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Nicky Butt"
:event/subtype "serious_foul"
:event/player1 "Lee Cattermole"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_487101"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_1773"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Paul Scharner"
:event/subtype "shirt_pull"
:event/player1 "Damien Duff"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_487120"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Maynor Figueroa"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_487131"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/sortorder 2
:event/team "away"
:event/event_type "throwin"
:event/id "event_487143"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Ryan Taylor"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_487146"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_1773"}

{:event/type "corner"
:event/elapsed 19
:event/subtype "cross"
:event/player1 "Ryan Taylor"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_487146"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Ryan Taylor"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_487150"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_1773"}

{:event/type "corner"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Ryan Taylor"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_487150"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_1773"}

{:event/type "shotoff"
:event/elapsed 20
:event/subtype "distance"
:event/player1 "Wilson Palacios"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_487154"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Ryan Taylor"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_487158"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_1773"}

{:event/type "corner"
:event/elapsed 20
:event/subtype "cross"
:event/player1 "Ryan Taylor"
:event/sortorder 4
:event/team "away"
:event/event_type "corner"
:event/id "event_487158"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Maynor Figueroa"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_487197"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_1773"}

{:event/type "shoton"
:event/elapsed 24
:event/subtype "distance"
:event/player1 "Wilson Palacios"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_487216"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Jose Enrique"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_487217"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_1773"}

{:event/type "shotoff"
:event/elapsed 28
:event/subtype "distance"
:event/player1 "Jonas Gutierrez"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_487291"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Antonio Valencia"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_487367"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Ryan Taylor"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_487371"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_1773"}

{:event/type "corner"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Ryan Taylor"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_487371"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Antonio Valencia"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_487417"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_1773"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Sebastien Bassong"
:event/player1 "Olivier Kapo"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_487419"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Damien Duff"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_487426"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_1773"}

{:event/type "shotoff"
:event/elapsed 36
:event/subtype "header"
:event/player1 "Shola Ameobi"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_487429"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_1773"}

{:event/type "shotoff"
:event/elapsed 37
:event/subtype "distance"
:event/player1 "Antonio Valencia"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_487437"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Jose Enrique"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_487494"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Habib Beye"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_487504"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/player1 "Damien Duff"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_487550"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_1773"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Fabricio Coloccini"
:event/subtype "shirt_pull"
:event/player1 "Olivier Kapo"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_487567"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_1773"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "blocked_shot"
:event/player1 "Obafemi Martins"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_487582"
:event/minute 46
:event/match_id "match_1773"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "distance"
:event/player1 "Nicky Butt"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_487585"
:event/minute 46
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Antonio Valencia"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_487720"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_1773"}

{:event/type "foulcommit"
:event/elapsed_plus 2
:event/elapsed 45
:event/player2 "Maynor Figueroa"
:event/player1 "Damien Duff"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_487600"
:event/minute 47
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Ryan Taylor"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_487728"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_1773"}

{:event/type "corner"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Ryan Taylor"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_487728"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Ryan Taylor"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_487742"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_1773"}

{:event/type "corner"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Ryan Taylor"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_487742"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 48
:event/subtype "cross"
:event/player1 "Ryan Taylor"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_487750"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_1773"}

{:event/type "shoton"
:event/elapsed 48
:event/subtype "distance"
:event/player1 "Henri Camara"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_487757"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_1773"}

{:event/type "shotoff"
:event/elapsed_plus 4
:event/elapsed 45
:event/subtype "distance"
:event/player1 "Olivier Kapo"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_487621"
:event/minute 49
:event/match_id "match_1773"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Olivier Kapo"
:event/subtype "serious_foul"
:event/player1 "Habib Beye"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_487772"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_1773"}

{:event/type "card"
:event/elapsed 50
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Habib Beye"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_487773"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Ryan Taylor"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_487791"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_1773"}

{:event/type "corner"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Ryan Taylor"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_487791"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed_plus 5
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Jonas Gutierrez"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_487628"
:event/minute 50
:event/match_id "match_1773"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Shay Given"
:event/subtype "serious_foul"
:event/player1 "Titus Bramble"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_487800"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_1773"}

{:event/type "card"
:event/elapsed 50
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Titus Bramble"
:event/sortorder 5
:event/team "away"
:event/event_type "card"
:event/id "event_487802"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_1773"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Obafemi Martins"
:event/subtype "serious_foul"
:event/player1 "Titus Bramble"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_487808"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_1773"}

{:event/type "shotoff"
:event/elapsed 52
:event/subtype "header"
:event/player1 "Sebastien Bassong"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_487824"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Ryan Taylor"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_487836"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_1773"}

{:event/type "corner"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Ryan Taylor"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_487836"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_1773"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Shola Ameobi"
:event/subtype "serious_foul"
:event/player1 "Emmerson Boyce"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_487857"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_1773"}

{:event/type "card"
:event/elapsed 54
:event/card_type "y"
:event/player1 "Emmerson Boyce"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_487861"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_1773"}

{:event/type "shoton"
:event/elapsed 55
:event/subtype "header"
:event/player1 "Nicky Butt"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_487885"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Damien Duff"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_487887"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_1773"}

{:event/type "corner"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Damien Duff"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_487887"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_1773"}

{:event/type "shotoff"
:event/elapsed 56
:event/subtype "header"
:event/player1 "Fabricio Coloccini"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_487891"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_1773"}

{:event/type "shoton"
:event/elapsed 57
:event/subtype "distance"
:event/player1 "Antonio Valencia"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_487908"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Ryan Taylor"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_487911"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_1773"}

{:event/type "corner"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Ryan Taylor"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_487911"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_1773"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Obafemi Martins"
:event/subtype "shirt_pull"
:event/player1 "Wilson Palacios"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_487923"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_1773"}

{:event/type "card"
:event/elapsed 57
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Wilson Palacios"
:event/sortorder 4
:event/team "away"
:event/event_type "card"
:event/id "event_487924"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_1773"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Jonas Gutierrez"
:event/player1 "Wilson Palacios"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_487938"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Henri Camara"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_487940"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Jonas Gutierrez"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_487962"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_1773"}

{:event/type "shotoff"
:event/elapsed 60
:event/subtype "shot"
:event/player1 "Obafemi Martins"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_487966"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Shola Ameobi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_487984"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Jonas Gutierrez"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_487991"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_1773"}

{:event/type "corner"
:event/elapsed 61
:event/subtype "short"
:event/player1 "Damien Duff"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_487995"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Danny Guthrie"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_487998"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_1773"}

{:event/type "shotoff"
:event/elapsed 61
:event/subtype "header"
:event/player1 "Obafemi Martins"
:event/sortorder 6
:event/team "home"
:event/event_type "shotoff"
:event/id "event_488002"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Obafemi Martins"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_488073"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_1773"}

{:event/type "shotoff"
:event/elapsed 66
:event/subtype "distance"
:event/player1 "Jose Enrique"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_488077"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_1773"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Maynor Figueroa"
:event/player1 "Jonas Gutierrez"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_488106"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_1773"}

{:event/type "shotoff"
:event/elapsed 68
:event/subtype "header"
:event/player1 "Titus Bramble"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_488116"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Obafemi Martins"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_488154"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_1773"}

{:event/type "shotoff"
:event/elapsed 71
:event/subtype "shot"
:event/player1 "Michael Owen"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_488159"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Obafemi Martins"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_488185"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_1773"}

{:event/type "shotoff"
:event/elapsed 72
:event/subtype "shot"
:event/player1 "Nicky Butt"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_488187"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_1773"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Lee Cattermole"
:event/subtype "from_behind"
:event/player1 "Obafemi Martins"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_488202"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Obafemi Martins"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_488217"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_1773"}

{:event/type "shoton"
:event/elapsed 74
:event/subtype "header"
:event/player1 "Michael Owen"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_488221"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Damien Duff"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_488227"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_1773"}

{:event/type "corner"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Damien Duff"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_488227"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_1773"}

{:event/type "shotoff"
:event/elapsed 76
:event/subtype "post"
:event/player1 "Henri Camara"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_488244"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_1773"}

{:event/type "foulcommit"
:event/elapsed 76
:event/player1 "Sebastien Bassong"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_488248"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_1773"}

{:event/type "shotoff"
:event/elapsed 77
:event/subtype "header"
:event/player1 "Paul Scharner"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_488258"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_1773"}

{:event/type "shotoff"
:event/elapsed 77
:event/subtype "distance"
:event/player1 "Lee Cattermole"
:event/sortorder 4
:event/team "away"
:event/event_type "shotoff"
:event/id "event_488268"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Obafemi Martins"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_488280"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Habib Beye"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_488283"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_1773"}

{:event/type "shoton"
:event/elapsed 78
:event/subtype "header"
:event/player1 "Shola Ameobi"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_488284"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_1773"}

{:event/type "shoton"
:event/elapsed 80
:event/subtype "distance"
:event/player1 "Shola Ameobi"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_488310"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_1773"}

{:event/type "goal"
:event/elapsed 80
:event/subtype "loose_ball"
:event/player1 "Michael Owen"
:event/sortorder 1
:event/team "home"
:event/id "event_488312"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Danny Guthrie"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_488331"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_1773"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Nicky Butt"
:event/player1 "Wilson Palacios"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_488353"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_1773"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "Paul Scharner"
:event/player1 "Michael Owen"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_488372"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_1773"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Olivier Kapo"
:event/player1 "Nicky Butt"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_488404"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_1773"}

{:event/type "goal"
:event/elapsed 87
:event/player2 "Charles N'Zogbia"
:event/subtype "shot"
:event/player1 "Obafemi Martins"
:event/sortorder 1
:event/team "home"
:event/id "event_488436"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_488445"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Maynor Figueroa"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_488452"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Daniel de Ridder"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_488461"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_1773"}

{:event/type "corner"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Daniel de Ridder"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_488461"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_1773"}

{:event/type "goal"
:event/elapsed 89
:event/player2 "Daniel de Ridder"
:event/subtype "header"
:event/player1 "Titus Bramble"
:event/sortorder 3
:event/team "away"
:event/id "event_488465"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Charles N'Zogbia"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_488476"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_1773"}

{:event/type "corner"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Charles N'Zogbia"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_488476"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Danny Guthrie"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_488480"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_1773"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "distance"
:event/player1 "Danny Guthrie"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_488496"
:event/minute 91
:event/match_id "match_1773"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Habib Beye"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_488503"
:event/minute 93
:event/match_id "match_1773"}


]

