
;;# data
[
{:match/id "match_7298"
:match/league "France Ligue 1"
:match/hometeam "OGC Nice"
:match/awayteam "Évian Thonon Gaillard FC"
:match/score "3:2"
:match/hometeam_goals "2"
:match/awayteam_goals "2"}

{:event/type "foulcommit"
:event/elapsed 1
:event/player1 "Nampalys Mendy"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4315069"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Cedric Mongongu"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4315087"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Daniel Wass"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4315100"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_7298"}

{:event/type "corner"
:event/elapsed 3
:event/subtype "cross_right"
:event/player1 "Valentin Eysseric"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4315111"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player1 "Jesper Juelsgaard"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4315123"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 4
:event/player2 "Nampalys Mendy"
:event/subtype "trip"
:event/player1 "Milos Ninkovic"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4315137"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Kevin Gomis"
:event/subtype "pushing"
:event/player1 "Nicki Bille Nielsen"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4315149"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player1 "Adrien Thomasson"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4315788"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 8
:event/subtype "hands"
:event/player1 "Nampalys Mendy"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4315210"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Clarck Nsikulu"
:event/subtype "penalty"
:event/player1 "Simon Pouplin"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4315245"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_7298"}

{:event/type "card"
:event/elapsed 9
:event/card_type "y"
:event/player1 "Simon Pouplin"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4315250"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_7298"}

{:event/type "goal"
:event/elapsed 10
:event/subtype "saved"
:event/player1 "Daniel Wass"
:event/sortorder 1
:event/team "away"
:event/id "event_4315265"
:event/event_type "goal"
:event/goal_type "npm"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Daniel Wass"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4315309"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_7298"}

{:event/type "corner"
:event/elapsed 13
:event/subtype "cross_right"
:event/player1 "Daniel Wass"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4315311"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 13
:event/subtype "hands"
:event/player1 "Milos Ninkovic"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4315315"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Eric Bautheac"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4315334"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 15
:event/player2 "Nampalys Mendy"
:event/subtype "trip"
:event/player1 "Adrien Thomasson"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4315351"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Said Benrahma"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4315367"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "Kassim Abdallah"
:event/subtype "serious_foul"
:event/player1 "Kevin Gomis"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4315376"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_7298"}

{:event/type "card"
:event/elapsed 16
:event/card_type "y"
:event/player1 "Kevin Gomis"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4315382"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 18
:event/subtype "cross"
:event/player1 "Daniel Wass"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4315413"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_7298"}

{:event/type "goal"
:event/elapsed 18
:event/player2 "Daniel Wass"
:event/subtype "header"
:event/player1 "Dany Nounkeu"
:event/sortorder 1
:event/team "away"
:event/id "event_4315419"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 20
:event/player1 "Alexy Bosetti"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4315473"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Clarck Nsikulu"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4315497"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 22
:event/subtype "hands"
:event/player1 "Jordan Amavi"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4315510"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Kassim Abdallah"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4315570"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 28
:event/subtype "cross"
:event/player1 "Nampalys Mendy"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4315607"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_7298"}

{:event/type "shotoff"
:event/elapsed 28
:event/subtype "shot"
:event/player1 "Alexy Bosetti"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4315608"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Yeltsin Tejeda"
:event/subtype "serious_foul"
:event/player1 "Gregoire Puel"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4315621"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 30
:event/player2 "Simon Pouplin"
:event/subtype "pushing"
:event/player1 "Nicki Bille Nielsen"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4315639"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_7298"}

{:event/type "card"
:event/elapsed 30
:event/card_type "y"
:event/player1 "Nicki Bille Nielsen"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_4315649"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player1 "Milos Ninkovic"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4315654"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Clarck Nsikulu"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4315670"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_7298"}

{:event/type "shotoff"
:event/elapsed 32
:event/subtype "distance"
:event/player1 "Daniel Wass"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4315676"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 32
:event/player1 "Daniel Wass"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4315683"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Eric Bautheac"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4315688"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Adrien Thomasson"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4315706"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 34
:event/player1 "Valentin Eysseric"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4315720"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Eric Bautheac"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4315732"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Jordan Amavi"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4315747"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_7298"}

{:event/type "corner"
:event/elapsed 37
:event/subtype "cross_left"
:event/player1 "Eric Bautheac"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4315760"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player1 "Niklas Hult"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4315781"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 40
:event/subtype "from_behind"
:event/player1 "Alexy Bosetti"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4315801"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player1 "Dany Nounkeu"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4315821"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_7298"}

{:event/type "shotoff"
:event/elapsed 42
:event/subtype "shot"
:event/player1 "Said Benrahma"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4315841"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Kassim Abdallah"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4315893"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Daniel Wass"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4316028"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Kassim Abdallah"
:event/sortorder 5
:event/team "away"
:event/event_type "cross"
:event/id "event_4315915"
:event/minute 46
:event/match_id "match_7298"}

{:event/type "goal"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "Said Benrahma"
:event/subtype "shot"
:event/player1 "Alexy Bosetti"
:event/sortorder 9
:event/team "home"
:event/id "event_4315926"
:event/event_type "goal"
:event/goal_type "n"
:event/minute 46
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Niklas Hult"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4316049"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_7298"}

{:event/type "corner"
:event/elapsed 48
:event/subtype "cross_right"
:event/player1 "Eric Bautheac"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4316060"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Benjamin Leroy"
:event/player1 "Kevin Gomis"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4316066"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 49
:event/subtype "pushing"
:event/player1 "Valentin Eysseric"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4316085"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Clarck Nsikulu"
:event/subtype "trip"
:event/player1 "Niklas Hult"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4316091"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 49
:event/subtype "cross"
:event/player1 "Daniel Wass"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4316099"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Nicki Bille Nielsen"
:event/subtype "trip"
:event/player1 "Romain Genevois"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4316118"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Alexy Bosetti"
:event/subtype "trip"
:event/player1 "Daniel Wass"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4316127"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Alexy Bosetti"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4316133"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Eric Bautheac"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4316155"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_7298"}

{:event/type "shotoff"
:event/elapsed 53
:event/subtype "shot"
:event/player1 "Niklas Hult"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4316159"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Nicki Bille Nielsen"
:event/subtype "pull"
:event/player1 "Nampalys Mendy"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4316172"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Jesper Juelsgaard"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4316179"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Adrien Thomasson"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4316192"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_7298"}

{:event/type "shoton"
:event/elapsed 54
:event/subtype "shot"
:event/player1 "Clarck Nsikulu"
:event/sortorder 4
:event/team "away"
:event/event_type "shoton"
:event/id "event_4316193"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_7298"}

{:event/type "corner"
:event/elapsed 55
:event/subtype "cross_right"
:event/player1 "Eric Bautheac"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4316198"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_7298"}

{:event/type "shoton"
:event/elapsed 55
:event/subtype "deflected"
:event/player1 "Niklas Hult"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_4316202"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Niklas Hult"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4316204"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Eric Bautheac"
:event/subtype "serious_foul"
:event/player1 "Yeltsin Tejeda"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4316213"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_7298"}

{:event/type "card"
:event/elapsed 56
:event/card_type "y"
:event/player1 "Yeltsin Tejeda"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_4316214"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Eric Bautheac"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4316224"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_7298"}

{:event/type "corner"
:event/elapsed 57
:event/subtype "cross_left"
:event/player1 "Valentin Eysseric"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4316229"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Alexy Bosetti"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4316253"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_7298"}

{:event/type "shotoff"
:event/elapsed 59
:event/subtype "volley"
:event/player1 "Said Benrahma"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4316257"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player2 "Gregoire Puel"
:event/subtype "trip"
:event/player1 "Nicki Bille Nielsen"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4316290"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Valentin Eysseric"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4316300"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Said Benrahma"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4316337"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Milos Ninkovic"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4316415"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Clarck Nsikulu"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4316433"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_7298"}

{:event/type "corner"
:event/elapsed 67
:event/subtype "cross_left"
:event/player1 "Jesper Juelsgaard"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4316446"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_7298"}

{:event/type "shoton"
:event/elapsed 68
:event/subtype "shot"
:event/player1 "Alexy Bosetti"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4316455"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_7298"}

{:event/type "goal"
:event/elapsed 68
:event/player2 "Alexy Bosetti"
:event/subtype "shot"
:event/player1 "Valentin Eysseric"
:event/sortorder 5
:event/team "home"
:event/id "event_4316459"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Alioun Fall"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4316544"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Valentin Eysseric"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4316553"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Eric Bautheac"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4316558"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 74
:event/player1 "Alexy Bosetti"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4316605"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_7298"}

{:event/type "card"
:event/elapsed 75
:event/card_type "y"
:event/player1 "Alexy Bosetti"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4316570"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 76
:event/subtype "hands"
:event/player1 "Nampalys Mendy"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4316602"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Alioun Fall"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4316622"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_7298"}

{:event/type "shoton"
:event/elapsed 78
:event/subtype "deflected"
:event/player1 "Adrien Thomasson"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4317535"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_7298"}

{:event/type "goal"
:event/elapsed 78
:event/player1 "Kevin Gomis"
:event/sortorder 2
:event/team "home"
:event/id "event_4316625"
:event/event_type "goal"
:event/goal_type "o"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 79
:event/player1 "Milos Ninkovic"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4316652"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player1 "Eric Bautheac"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4316695"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player1 "Kevin Gomis"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4316707"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 82
:event/player2 "Jesper Juelsgaard"
:event/subtype "trip"
:event/player1 "Neal Maupay"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4316717"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_7298"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Clarck Nsikulu"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4316731"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_7298"}

{:event/type "shotoff"
:event/elapsed 83
:event/subtype "header"
:event/player1 "Pape Modou Sougou"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4316738"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_7298"}

{:event/type "shotoff"
:event/elapsed 85
:event/subtype "distance"
:event/player1 "Clarck Nsikulu"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4316773"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Jesper Juelsgaard"
:event/subtype "trip"
:event/player1 "Eric Bautheac"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4316783"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player1 "Kassim Abdallah"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4316796"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_7298"}

{:event/type "card"
:event/elapsed 87
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Kassim Abdallah"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4316816"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_7298"}

{:event/type "card"
:event/elapsed 87
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Jordan Amavi"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_4316818"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Kevin Gomis"
:event/subtype "pull"
:event/player1 "Clarck Nsikulu"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4316828"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player2 "Kevin Gomis"
:event/subtype "pushing"
:event/player1 "Jesper Juelsgaard"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4316839"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_7298"}

{:event/type "shotoff"
:event/elapsed 89
:event/subtype "crossbar"
:event/player1 "Alexy Bosetti"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4316844"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_7298"}

{:event/type "corner"
:event/elapsed 90
:event/subtype "cross_left"
:event/player1 "Valentin Eysseric"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4316861"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Nampalys Mendy"
:event/subtype "trip"
:event/player1 "Cedric Barbosa"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4316865"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_7298"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player1 "Nampalys Mendy"
:event/sortorder 5
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4316877"
:event/minute 91
:event/match_id "match_7298"}

{:event/type "card"
:event/elapsed_plus 4
:event/elapsed 90
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Eric Bautheac"
:event/sortorder 8
:event/team "home"
:event/event_type "card"
:event/id "event_4316906"
:event/minute 94
:event/match_id "match_7298"}

{:event/type "card"
:event/elapsed_plus 4
:event/elapsed 90
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Pape Modou Sougou"
:event/sortorder 9
:event/team "away"
:event/event_type "card"
:event/id "event_4316909"
:event/minute 94
:event/match_id "match_7298"}


]

