
;;# data
[
{:match/id "match_15682"
:match/league "Netherlands Eredivisie"
:match/hometeam "FC Groningen"
:match/awayteam "SC Heerenveen"
:match/score "3:1"
:match/hometeam_goals "3"
:match/awayteam_goals "1"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Hans Hateboer"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4765488"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 1
:event/subtype "cross"
:event/player1 "Bryan Linssen"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4765490"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_15682"}

{:event/type "shoton"
:event/elapsed 1
:event/subtype "shot"
:event/player1 "Bryan Linssen"
:event/sortorder 5
:event/team "home"
:event/event_type "shoton"
:event/id "event_4765492"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_15682"}

{:event/type "shoton"
:event/elapsed 1
:event/subtype "blocked_shot"
:event/player1 "Danny Hoesen"
:event/sortorder 6
:event/team "home"
:event/event_type "shoton"
:event/id "event_4765500"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_15682"}

{:event/type "goal"
:event/elapsed 1
:event/player2 "Michael de Leeuw"
:event/subtype "shot"
:event/player1 "Danny Hoesen"
:event/sortorder 9
:event/team "home"
:event/id "event_4765494"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 4
:event/subtype "cross"
:event/player1 "Simon Tibbling"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4765504"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Joey van den Berg"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4765510"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 7
:event/subtype "cross"
:event/player1 "Abel Tamata"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4765525"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 9
:event/subtype "cross"
:event/player1 "Hans Hateboer"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4765543"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Joey van den Berg"
:event/subtype "trip"
:event/player1 "Bryan Linssen"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4765546"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Caner Cavlan"
:event/player1 "Bryan Linssen"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4765549"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 10
:event/player2 "Simon Thern"
:event/subtype "pushing"
:event/player1 "Michael de Leeuw"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4765553"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Albert Rusnak"
:event/subtype "pushing"
:event/player1 "Branco van den Boomen"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4765558"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Lucas Bijker"
:event/subtype "pull"
:event/player1 "Albert Rusnak"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4765568"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Bryan Linssen"
:event/subtype "pull"
:event/player1 "Lucas Bijker"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4765570"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_15682"}

{:event/type "shoton"
:event/elapsed 14
:event/subtype "blocked_shot"
:event/player1 "Danny Hoesen"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4765576"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_15682"}

{:event/type "corner"
:event/elapsed 14
:event/subtype "short_right"
:event/player1 "Albert Rusnak"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4765577"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 14
:event/subtype "cross"
:event/player1 "Bryan Linssen"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4765578"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 15
:event/subtype "cross"
:event/player1 "Caner Cavlan"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4765585"
:event/elapsed_plus 0
:event/minute 15
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 16
:event/subtype "cross"
:event/player1 "Simon Tibbling"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4765594"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_15682"}

{:event/type "goal"
:event/elapsed 16
:event/player2 "Simon Tibbling"
:event/subtype "shot"
:event/player1 "Bryan Linssen"
:event/sortorder 1
:event/team "home"
:event/id "event_4765595"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_15682"}

{:event/type "corner"
:event/elapsed 18
:event/subtype "cross_left"
:event/player1 "Branco van den Boomen"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4765606"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Bryan Linssen"
:event/player1 "Branco van den Boomen"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4765607"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_15682"}

{:event/type "shoton"
:event/elapsed 19
:event/subtype "blocked_shot"
:event/player1 "Sam Larsson"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4765611"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Albert Rusnak"
:event/subtype "trip"
:event/player1 "Simon Thern"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4765613"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_15682"}

{:event/type "card"
:event/elapsed 19
:event/card_type "y"
:event/player1 "Simon Thern"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_4765614"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_15682"}

{:event/type "shoton"
:event/elapsed 20
:event/subtype "distance"
:event/player1 "Danny Hoesen"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4765621"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Simon Tibbling"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4765623"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Sam Larsson"
:event/player1 "Hans Hateboer"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4765631"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Johan Kappelhof"
:event/subtype "dangerous_play"
:event/player1 "unknown"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4765634"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_15682"}

{:event/type "corner"
:event/elapsed 24
:event/subtype "cross_right"
:event/player1 "Bryan Linssen"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4765637"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_15682"}

{:event/type "corner"
:event/elapsed 24
:event/subtype "cross_right"
:event/player1 "Bryan Linssen"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4765640"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_15682"}

{:event/type "shoton"
:event/elapsed 24
:event/subtype "header"
:event/player1 "Rasmus Lindgren"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_4765641"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Caner Cavlan"
:event/player1 "Michael de Leeuw"
:event/sortorder 4
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4765643"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_15682"}

{:event/type "shotoff"
:event/elapsed 26
:event/subtype "volley"
:event/player1 "Danny Hoesen"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4765648"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Luciano Slagveer"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4765655"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/sortorder 3
:event/team "away"
:event/event_type "throwin"
:event/id "event_4765658"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_15682"}

{:event/type "shoton"
:event/elapsed 27
:event/subtype "blocked_shot"
:event/player1 "Simon Thern"
:event/sortorder 5
:event/team "away"
:event/event_type "shoton"
:event/id "event_4765660"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/sortorder 6
:event/team "away"
:event/event_type "throwin"
:event/id "event_4765661"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Luciano Slagveer"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4765686"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_15682"}

{:event/type "shoton"
:event/elapsed 33
:event/subtype "blocked_shot"
:event/player1 "Bryan Linssen"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4765693"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_4765697"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 34
:event/player2 "Caner Cavlan"
:event/subtype "pushing"
:event/player1 "Simon Tibbling"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4765702"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Jerry St. Juste"
:event/player1 "Danny Hoesen"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4765708"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Joey van den Berg"
:event/subtype "obstruction"
:event/player1 "Michael de Leeuw"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4765716"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Sam Larsson"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4765720"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_15682"}

{:event/type "shoton"
:event/elapsed 35
:event/subtype "shot"
:event/player1 "Luciano Slagveer"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_4765722"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Michael de Leeuw"
:event/subtype "trip"
:event/player1 "Joey van den Berg"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4765730"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Bryan Linssen"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4765742"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Luciano Slagveer"
:event/subtype "trip"
:event/player1 "Simon Tibbling"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4765746"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Luciano Slagveer"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_4765749"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_15682"}

{:event/type "shotoff"
:event/elapsed 39
:event/subtype "deflected"
:event/player1 "unknown"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4765752"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_15682"}

{:event/type "corner"
:event/elapsed 39
:event/subtype "cross_right"
:event/player1 "Simon Thern"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4765754"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Simon Thern"
:event/subtype "pull"
:event/player1 "Michael de Leeuw"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4765786"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 44
:event/subtype "cross"
:event/sortorder 0
:event/team "home"
:event/event_type "throwin"
:event/id "event_4765808"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_15682"}

{:event/type "corner"
:event/elapsed 44
:event/subtype "cross_right"
:event/player1 "Bryan Linssen"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4765814"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_15682"}

{:event/type "shotoff"
:event/elapsed 44
:event/subtype "header"
:event/player1 "Rasmus Lindgren"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4765816"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_15682"}

{:event/type "shoton"
:event/elapsed 47
:event/subtype "distance"
:event/player1 "Danny Hoesen"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4765937"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Bryan Linssen"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4765946"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_15682"}

{:event/type "shoton"
:event/elapsed 47
:event/subtype "blocked_shot"
:event/player1 "Albert Rusnak"
:event/sortorder 4
:event/team "home"
:event/event_type "shoton"
:event/id "event_4765952"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_15682"}

{:event/type "shoton"
:event/elapsed 48
:event/subtype "blocked_shot"
:event/player1 "Simon Tibbling"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4765958"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_15682"}

{:event/type "shoton"
:event/elapsed 48
:event/subtype "shot"
:event/player1 "Albert Rusnak"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4765960"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_15682"}

{:event/type "corner"
:event/elapsed 48
:event/subtype "cross_left"
:event/player1 "Albert Rusnak"
:event/sortorder 6
:event/team "home"
:event/event_type "corner"
:event/id "event_4765972"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 49
:event/player2 "Simon Thern"
:event/subtype "pull"
:event/player1 "Hedwiges Maduro"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4765979"
:event/elapsed_plus 0
:event/minute 49
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Simon Tibbling"
:event/subtype "pushing"
:event/player1 "Joey van den Berg"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4765994"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Lucas Bijker"
:event/player1 "Simon Tibbling"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4766009"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Albert Rusnak"
:event/player1 "Pele van Anholt"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4766018"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Danny Hoesen"
:event/player1 "Jerry St. Juste"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4766033"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Albert Rusnak"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4766042"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Michael de Leeuw"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4766047"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Bryan Linssen"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4766070"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_15682"}

{:event/type "corner"
:event/elapsed 56
:event/subtype "cross_right"
:event/player1 "Bryan Linssen"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4766075"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/sortorder 3
:event/team "home"
:event/event_type "throwin"
:event/id "event_4766082"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 57
:event/player2 "Lucas Bijker"
:event/subtype "trip"
:event/player1 "Bryan Linssen"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4766088"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_15682"}

{:event/type "card"
:event/elapsed 57
:event/card_type "y"
:event/player1 "Bryan Linssen"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4766091"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_15682"}

{:event/type "shotoff"
:event/elapsed 58
:event/subtype "shot"
:event/player1 "Bryan Linssen"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4766100"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 59
:event/player2 "Joey van den Berg"
:event/subtype "trip"
:event/player1 "Simon Tibbling"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4766120"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Lucas Bijker"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4766126"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 60
:event/player2 "Kenny Otigba"
:event/subtype "obstruction"
:event/player1 "Michael de Leeuw"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4766137"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_15682"}

{:event/type "corner"
:event/elapsed 62
:event/subtype "cross_left"
:event/player1 "Simon Thern"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_4766161"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_15682"}

{:event/type "shoton"
:event/elapsed 62
:event/subtype "distance"
:event/player1 "Simon Thern"
:event/sortorder 4
:event/team "away"
:event/event_type "shoton"
:event/id "event_4766168"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Johan Kappelhof"
:event/subtype "obstruction"
:event/player1 "unknown"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4766179"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 64
:event/subtype "cross"
:event/player1 "Joey van den Berg"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4766191"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 65
:event/player2 "Simon Tibbling"
:event/subtype "from_behind"
:event/player1 "Pele van Anholt"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4766200"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_15682"}

{:event/type "card"
:event/elapsed 65
:event/card_type "y"
:event/player1 "Pele van Anholt"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4766202"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_15682"}

{:event/type "shoton"
:event/elapsed 66
:event/subtype "blocked_shot"
:event/player1 "Albert Rusnak"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4766220"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 66
:event/player2 "Simon Tibbling"
:event/subtype "trip"
:event/player1 "Branco van den Boomen"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4766222"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_15682"}

{:event/type "card"
:event/elapsed 66
:event/card_type "y"
:event/player1 "Branco van den Boomen"
:event/sortorder 2
:event/team "away"
:event/event_type "card"
:event/id "event_4766223"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Bryan Linssen"
:event/player1 "Lucas Bijker"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4766239"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Bryan Linssen"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4766247"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 68
:event/subtype "cross"
:event/player1 "Bryan Linssen"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_4766249"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_15682"}

{:event/type "shotoff"
:event/elapsed 68
:event/subtype "volley"
:event/player1 "Danny Hoesen"
:event/sortorder 4
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4766250"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Sam Larsson"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4766266"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_15682"}

{:event/type "goal"
:event/elapsed 69
:event/player2 "Branco van den Boomen"
:event/subtype "volley"
:event/player1 "Simon Thern"
:event/sortorder 4
:event/team "away"
:event/id "event_4766271"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Simon Thern"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4766285"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 72
:event/subtype "hands"
:event/player1 "Luciano Slagveer"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4766300"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Lucas Bijker"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4766307"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Luciano Slagveer"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4766332"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_4766337"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/sortorder 6
:event/team "away"
:event/event_type "throwin"
:event/id "event_4766340"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_15682"}

{:event/type "shotoff"
:event/elapsed 76
:event/subtype "shot"
:event/player1 "Mimoun Mahi"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4766355"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 76
:event/player2 "Hans Hateboer"
:event/subtype "obstruction"
:event/player1 "Tarik Kada"
:event/sortorder 5
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4766365"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 77
:event/player2 "Pele van Anholt"
:event/player1 "Michael de Leeuw"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4766373"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Tarik Kada"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4766394"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Mimoun Mahi"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4766419"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_15682"}

{:event/type "goal"
:event/elapsed 82
:event/subtype "shot"
:event/player1 "Mimoun Mahi"
:event/sortorder 2
:event/team "home"
:event/id "event_4766428"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_15682"}

{:event/type "shotoff"
:event/elapsed 83
:event/subtype "shot"
:event/player1 "Sam Larsson"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4766455"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Tarik Kada"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4766463"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Jarchinio Antonia"
:event/player1 "Simon Thern"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4766475"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Rasmus Lindgren"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4766480"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_15682"}

{:event/type "shoton"
:event/elapsed 87
:event/subtype "shot"
:event/player1 "Hans Hateboer"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4766501"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed 89
:event/player2 "Michael de Leeuw"
:event/player1 "Branco van den Boomen"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4766522"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_15682"}

{:event/type "shoton"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "blocked_shot"
:event/player1 "Pele van Anholt"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4766558"
:event/minute 91
:event/match_id "match_15682"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 90
:event/player2 "Mimoun Mahi"
:event/subtype "from_behind"
:event/player1 "Lucas Bijker"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4766559"
:event/minute 91
:event/match_id "match_15682"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Sam Larsson"
:event/sortorder 7
:event/team "away"
:event/event_type "cross"
:event/id "event_4766571"
:event/minute 92
:event/match_id "match_15682"}

{:event/type "corner"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross_left"
:event/player1 "Sam Larsson"
:event/sortorder 8
:event/team "away"
:event/event_type "corner"
:event/id "event_4766574"
:event/minute 92
:event/match_id "match_15682"}


]

