
;;# data
[
{:match/id "match_2240"
:match/league "England Premier League"
:match/hometeam "West Ham United"
:match/awayteam "Wolverhampton Wanderers"
:match/score "1:3"
:match/hometeam_goals "1"
:match/awayteam_goals "3"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Julien Faubert"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1008998"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_2240"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Matthew Upson"
:event/player1 "Karl Henry"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1009002"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_2240"}

{:event/type "shotoff"
:event/elapsed 8
:event/subtype "crossbar"
:event/player1 "Kevin Foley"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_1009004"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_2240"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Karl Henry"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1009010"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_2240"}

{:event/type "corner"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "Karl Henry"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1009010"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_2240"}

{:event/type "shoton"
:event/elapsed 11
:event/subtype "distance"
:event/player1 "Scott Parker"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1009014"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_2240"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Bennedict McCarthy,27"
:event/player1 "David Jones"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1009018"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_2240"}

{:event/type "shotoff"
:event/elapsed 13
:event/subtype "distance"
:event/player1 "Julien Faubert"
:event/sortorder 2
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1009021"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_2240"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Alessandro Diamanti"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1009024"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_2240"}

{:event/type "corner"
:event/elapsed 17
:event/subtype "short"
:event/player1 "Alessandro Diamanti"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1009026"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_2240"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Ronald Zubar"
:event/player1 "Carlton Cole"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1009029"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_2240"}

{:event/type "shoton"
:event/elapsed 20
:event/subtype "deflected"
:event/player1 "Carlton Cole"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1009030"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_2240"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "George Elokobi"
:event/player1 "Bennedict McCarthy,27"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1009031"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_2240"}

{:event/type "cross"
:event/elapsed 22
:event/subtype "cross"
:event/player1 "Matt Jarvis"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1009032"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_2240"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Julien Faubert"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1009035"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_2240"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Alessandro Diamanti"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1009037"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_2240"}

{:event/type "corner"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Alessandro Diamanti"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_1009037"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_2240"}

{:event/type "cross"
:event/elapsed 24
:event/subtype "cross"
:event/player1 "Fabio Daprela"
:event/sortorder 4
:event/team "home"
:event/event_type "cross"
:event/id "event_1009039"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_2240"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Marcus Hahnemann"
:event/player1 "Bennedict McCarthy,27"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1009045"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_2240"}

{:event/type "goal"
:event/elapsed 28
:event/subtype "shot"
:event/player1 "Kevin Doyle"
:event/sortorder 0
:event/team "away"
:event/id "event_1009047"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_2240"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Alessandro Diamanti"
:event/subtype "serious_foul"
:event/player1 "Michael Mancienne"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1009048"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2240"}

{:event/type "card"
:event/elapsed 29
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Michael Mancienne"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1009049"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_2240"}

{:event/type "foulcommit"
:event/elapsed 30
:event/player2 "Fabio Daprela"
:event/player1 "David Jones"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1009050"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_2240"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Alessandro Diamanti"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1009051"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_2240"}

{:event/type "corner"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Alessandro Diamanti"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1009051"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_2240"}

{:event/type "shoton"
:event/elapsed 31
:event/subtype "header"
:event/player1 "Matthew Upson"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1009052"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_2240"}

{:event/type "shoton"
:event/elapsed 32
:event/subtype "distance"
:event/player1 "Carlton Cole"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1009053"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_2240"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "David Jones"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1009054"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_2240"}

{:event/type "corner"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "David Jones"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1009054"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_2240"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Matt Jarvis"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1009057"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_2240"}

{:event/type "corner"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Matt Jarvis"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_1009057"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_2240"}

{:event/type "shotoff"
:event/elapsed 45
:event/subtype "post"
:event/player1 "Scott Parker"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1009060"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_2240"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Fabio Daprela"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_1009062"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_2240"}

{:event/type "corner"
:event/elapsed 45
:event/subtype "short"
:event/player1 "Alessandro Diamanti"
:event/sortorder 4
:event/team "home"
:event/event_type "corner"
:event/id "event_1009064"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_2240"}

{:event/type "foulcommit"
:event/elapsed 46
:event/player2 "Matt Jarvis"
:event/player1 "Valon Behrami"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1009083"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_2240"}

{:event/type "foulcommit"
:event/elapsed 48
:event/player2 "Valon Behrami"
:event/subtype "serious_foul"
:event/player1 "Ronald Zubar"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1009087"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_2240"}

{:event/type "card"
:event/elapsed 48
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Ronald Zubar"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_1009088"
:event/elapsed_plus 0
:event/minute 48
:event/match_id "match_2240"}

{:event/type "shoton"
:event/elapsed 54
:event/subtype "distance"
:event/player1 "Scott Parker"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_1009105"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_2240"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "David Jones"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_1009114"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_2240"}

{:event/type "goal"
:event/elapsed 58
:event/player2 "David Jones"
:event/subtype "shot"
:event/player1 "Ronald Zubar"
:event/sortorder 1
:event/team "away"
:event/id "event_1009115"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_2240"}

{:event/type "goal"
:event/elapsed 61
:event/player2 "David Jones"
:event/subtype "shot"
:event/player1 "Matt Jarvis"
:event/sortorder 0
:event/team "away"
:event/id "event_1009120"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_2240"}

{:event/type "foulcommit"
:event/elapsed 64
:event/player2 "Kevin Doyle"
:event/player1 "Alessandro Diamanti"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_1009128"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_2240"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Matt Jarvis"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1009137"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_2240"}

{:event/type "corner"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Matt Jarvis"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_1009137"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_2240"}

{:event/type "cross"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Alessandro Diamanti"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1009152"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_2240"}

{:event/type "corner"
:event/elapsed 71
:event/subtype "cross"
:event/player1 "Alessandro Diamanti"
:event/sortorder 3
:event/team "home"
:event/event_type "corner"
:event/id "event_1009152"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_2240"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Alessandro Diamanti"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1009154"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_2240"}

{:event/type "corner"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Alessandro Diamanti"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1009154"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_2240"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Julien Faubert"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1009160"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_2240"}

{:event/type "shotoff"
:event/elapsed 74
:event/subtype "distance"
:event/player1 "Jonathan Spector"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1009162"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_2240"}

{:event/type "shoton"
:event/elapsed 77
:event/subtype "shot"
:event/player1 "Guillermo Franco"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_1009173"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_2240"}

{:event/type "cross"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Carlton Cole"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1009177"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_2240"}

{:event/type "corner"
:event/elapsed 78
:event/subtype "cross"
:event/player1 "Carlton Cole"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_1009177"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_2240"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Guillermo Franco"
:event/player1 "Michael Mancienne"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_1009198"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_2240"}

{:event/type "shoton"
:event/elapsed 86
:event/subtype "distance"
:event/player1 "Alessandro Diamanti"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1009204"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_2240"}

{:event/type "cross"
:event/elapsed 88
:event/subtype "cross"
:event/player1 "Julien Faubert"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1009214"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_2240"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "distance"
:event/player1 "Alessandro Diamanti"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_1009231"
:event/minute 91
:event/match_id "match_2240"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Julien Faubert"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_1009234"
:event/minute 92
:event/match_id "match_2240"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Carlton Cole"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_1009237"
:event/minute 93
:event/match_id "match_2240"}

{:event/type "shoton"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "blocked_shot"
:event/player1 "Valon Behrami"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_1009238"
:event/minute 93
:event/match_id "match_2240"}

{:event/type "goal"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Valon Behrami"
:event/subtype "shot"
:event/player1 "Guillermo Franco"
:event/sortorder 3
:event/team "home"
:event/id "event_1009239"
:event/event_type "goal"
:event/goal_type "n"
:event/minute 93
:event/match_id "match_2240"}


]

