
;;# data
[
{:match/id "match_12255"
:match/league "Italy Serie A"
:match/hometeam "Atalanta"
:match/awayteam "Cagliari"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 22
:event/card_type "y"
:event/player1 "Stefano Lucchini"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3220965"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_12255"}

{:event/type "goal"
:event/elapsed 68
:event/player1 "Giacomo Bonaventura"
:event/sortorder 0
:event/team "home"
:event/id "event_3221151"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_12255"}

{:event/type "card"
:event/elapsed 81
:event/card_type "y"
:event/player1 "Giulio Migliaccio"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_3221173"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_12255"}

{:event/type "card"
:event/elapsed 90
:event/card_type "r"
:event/player1 "Victor Ibarbo"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_3221200"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_12255"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Cristian Raimondi"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_3221201"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_12255"}


]

