
;;# data
[
{:match/id "match_21607"
:match/league "Spain LIGA BBVA"
:match/hometeam "UD Almería"
:match/awayteam "Real Betis Balompié"
:match/score "1:0"
:match/hometeam_goals "1"
:match/awayteam_goals "0"}

{:event/type "card"
:event/elapsed 24
:event/card_type "y"
:event/player1 "Mane"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_544886"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_21607"}

{:event/type "card"
:event/elapsed 32
:event/card_type "y"
:event/player1 "Jesus Capi"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_544910"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_21607"}

{:event/type "goal"
:event/elapsed 35
:event/player1 "Corona"
:event/sortorder 0
:event/team "home"
:event/id "event_544929"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_21607"}

{:event/type "card"
:event/elapsed 42
:event/card_type "y"
:event/player1 "Carlos Garcia"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_544960"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_21607"}

{:event/type "card"
:event/elapsed 87
:event/card_type "r"
:event/player1 "Kalu Uche"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_545439"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_21607"}

{:event/type "card"
:event/elapsed 90
:event/card_type "r"
:event/player1 "Sergio Garcia"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_545446"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_21607"}


]

