
;;# data
[
{:match/id "match_12708"
:match/league "Italy Serie A"
:match/hometeam "Palermo"
:match/awayteam "Juventus"
:match/score "0:1"
:match/hometeam_goals "0"
:match/awayteam_goals "1"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Stephan Lichtsteiner"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4257986"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_12708"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Roberto Vitiello"
:event/subtype "dangerous_play"
:event/player1 "Stefano Sturaro"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4257988"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_12708"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "Andrea Rispoli"
:event/subtype "trip"
:event/player1 "Paolo De Ceglie"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4258012"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_12708"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Franco Vazquez"
:event/subtype "trip"
:event/player1 "Carlos Tevez"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4258034"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_12708"}

{:event/type "foulcommit"
:event/elapsed 5
:event/player2 "Paolo De Ceglie"
:event/player1 "Andrea Rispoli"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4258042"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_12708"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Stefano Sturaro"
:event/subtype "trip"
:event/player1 "Franco Vazquez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4258060"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_12708"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Luca Rigoni"
:event/subtype "pushing"
:event/player1 "Claudio Marchisio"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4258082"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_12708"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Andrea Rispoli"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4258106"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_12708"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Claudio Terzi"
:event/subtype "from_behind"
:event/player1 "Stefano Sturaro"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4258111"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_12708"}

{:event/type "shotoff"
:event/elapsed 13
:event/subtype "shot"
:event/player1 "Stephan Lichtsteiner"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4258137"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_12708"}

{:event/type "foulcommit"
:event/elapsed 14
:event/player2 "Stephan Lichtsteiner"
:event/subtype "dangerous_play"
:event/player1 "Edgar Barreto"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4258156"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_12708"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "Paulo Dybala"
:event/player1 "Stephan Lichtsteiner"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4258184"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_12708"}

{:event/type "shoton"
:event/elapsed 18
:event/subtype "distance"
:event/player1 "Carlos Tevez"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4258204"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_12708"}

{:event/type "foulcommit"
:event/elapsed 18
:event/player2 "Andrea Rispoli"
:event/subtype "pushing"
:event/player1 "Carlos Tevez"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4258213"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_12708"}

{:event/type "foulcommit"
:event/elapsed 19
:event/player2 "Stephan Lichtsteiner"
:event/subtype "pushing"
:event/player1 "Fabio Daprela"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4258223"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_12708"}

{:event/type "corner"
:event/elapsed 20
:event/subtype "cross_right"
:event/player1 "Claudio Marchisio"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4258232"
:event/elapsed_plus 0
:event/minute 20
:event/match_id "match_12708"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Stefano Sturaro"
:event/subtype "trip"
:event/player1 "Andrea Rispoli"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4258302"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_12708"}

{:event/type "shotoff"
:event/elapsed 25
:event/subtype "shot"
:event/player1 "Stefano Sturaro"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4258309"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_12708"}

{:event/type "cross"
:event/elapsed 26
:event/subtype "cross"
:event/player1 "Stephan Lichtsteiner"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4258320"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_12708"}

{:event/type "foulcommit"
:event/elapsed 26
:event/player2 "Fabio Daprela"
:event/subtype "pushing"
:event/player1 "Stephan Lichtsteiner"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4258323"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_12708"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Roberto Pereyra"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4258373"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_12708"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Stephan Lichtsteiner"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4258424"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_12708"}

{:event/type "shotoff"
:event/elapsed 34
:event/subtype "shot"
:event/player1 "Giorgio Chiellini"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4258452"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_12708"}

{:event/type "shoton"
:event/elapsed 35
:event/subtype "big chance shot"
:event/player1 "Andrea Rispoli"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4258478"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_12708"}

{:event/type "cross"
:event/elapsed 36
:event/subtype "cross"
:event/player1 "Andrea Rispoli"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4258483"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_12708"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Claudio Marchisio"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4258512"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_12708"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/sortorder 0
:event/team "away"
:event/event_type "throwin"
:event/id "event_4258520"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_12708"}

{:event/type "foulcommit"
:event/elapsed 38
:event/player2 "Fabio Daprela"
:event/player1 "Stephan Lichtsteiner"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4258549"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_12708"}

{:event/type "card"
:event/elapsed 39
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Franco Vazquez"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4258550"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_12708"}

{:event/type "shoton"
:event/elapsed 40
:event/subtype "blocked_shot"
:event/player1 "Paulo Dybala"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4258562"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_12708"}

{:event/type "cross"
:event/elapsed 40
:event/subtype "cross"
:event/player1 "Stephan Lichtsteiner"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4258569"
:event/elapsed_plus 0
:event/minute 40
:event/match_id "match_12708"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Roberto Pereyra"
:event/subtype "pull"
:event/player1 "Sinisa Andjelkovic"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4258587"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_12708"}

{:event/type "card"
:event/elapsed 41
:event/card_type "y"
:event/player1 "Sinisa Andjelkovic"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4258590"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_12708"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Claudio Marchisio"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4258607"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_12708"}

{:event/type "shotoff"
:event/elapsed 45
:event/subtype "shot"
:event/player1 "Carlos Tevez"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4258654"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_12708"}

{:event/type "foulcommit"
:event/elapsed_plus 1
:event/elapsed 45
:event/player2 "Luca Rigoni"
:event/player1 "Stefano Sturaro"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4258670"
:event/minute 46
:event/match_id "match_12708"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Franco Vazquez"
:event/sortorder 5
:event/team "home"
:event/event_type "cross"
:event/id "event_4258685"
:event/minute 46
:event/match_id "match_12708"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Roberto Pereyra"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4258829"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_12708"}

{:event/type "foulcommit"
:event/elapsed 50
:event/player2 "Roberto Pereyra"
:event/player1 "Luca Rigoni"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4258862"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_12708"}

{:event/type "shoton"
:event/elapsed 52
:event/subtype "direct_freekick"
:event/player1 "Carlos Tevez"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4258874"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_12708"}

{:event/type "cross"
:event/elapsed 52
:event/subtype "cross"
:event/player1 "Roberto Pereyra"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4258875"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_12708"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Paulo Dybala"
:event/subtype "pull"
:event/player1 "Andrea Barzagli"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4258879"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_12708"}

{:event/type "card"
:event/elapsed 52
:event/card_type "y"
:event/player1 "Andrea Barzagli"
:event/sortorder 4
:event/team "away"
:event/event_type "card"
:event/id "event_4258881"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_12708"}

{:event/type "shoton"
:event/elapsed 54
:event/subtype "deflected"
:event/player1 "Franco Vazquez"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_4258898"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_12708"}

{:event/type "corner"
:event/elapsed 54
:event/subtype "cross_left"
:event/player1 "Edgar Barreto"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4258907"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_12708"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "Roberto Vitiello"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4258912"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_12708"}

{:event/type "foulcommit"
:event/elapsed 55
:event/player2 "Paolo De Ceglie"
:event/player1 "Franco Vazquez"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4258914"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_12708"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Stephan Lichtsteiner"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4258926"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_12708"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Luca Rigoni"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4258931"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_12708"}

{:event/type "corner"
:event/elapsed 58
:event/subtype "cross_right"
:event/player1 "Paulo Dybala"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4258934"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_12708"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Giorgio Chiellini"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4258950"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_12708"}

{:event/type "foulcommit"
:event/elapsed 61
:event/player2 "Enzo Maresca"
:event/player1 "Arturo Vidal"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4258961"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_12708"}

{:event/type "cross"
:event/elapsed 63
:event/subtype "cross"
:event/player1 "Fabio Daprela"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4258970"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_12708"}

{:event/type "corner"
:event/elapsed 64
:event/subtype "cross_left"
:event/player1 "Edgar Barreto"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4258978"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_12708"}

{:event/type "cross"
:event/elapsed 65
:event/subtype "cross"
:event/player1 "Fabio Daprela"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4258987"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_12708"}

{:event/type "shoton"
:event/elapsed 65
:event/subtype "blocked_shot"
:event/player1 "Mate Jajalo"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4258989"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_12708"}

{:event/type "shoton"
:event/elapsed 65
:event/subtype "blocked_shot"
:event/player1 "Edgar Barreto"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4258991"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_12708"}

{:event/type "cross"
:event/elapsed 66
:event/subtype "cross"
:event/player1 "Carlos Tevez"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4259001"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_12708"}

{:event/type "corner"
:event/elapsed 66
:event/subtype "cross_left"
:event/player1 "Claudio Marchisio"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4259005"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_12708"}

{:event/type "shoton"
:event/elapsed 66
:event/subtype "header"
:event/player1 "Stephan Lichtsteiner"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_4259007"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_12708"}

{:event/type "corner"
:event/elapsed 66
:event/subtype "cross_right"
:event/player1 "Claudio Marchisio"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_4259008"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_12708"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Leonardo Bonucci"
:event/subtype "pull"
:event/player1 "Franco Vazquez"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4259015"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_12708"}

{:event/type "foulcommit"
:event/elapsed 68
:event/player2 "Fabio Daprela"
:event/subtype "pushing"
:event/player1 "Alvaro Morata"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4259020"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_12708"}

{:event/type "cross"
:event/elapsed 69
:event/subtype "cross"
:event/player1 "Fabio Daprela"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4259026"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_12708"}

{:event/type "shoton"
:event/elapsed 69
:event/subtype "blocked_shot"
:event/player1 "Arturo Vidal"
:event/sortorder 3
:event/team "away"
:event/event_type "shoton"
:event/id "event_4259031"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_12708"}

{:event/type "goal"
:event/elapsed 70
:event/player2 "Claudio Marchisio"
:event/subtype "shot"
:event/player1 "Alvaro Morata"
:event/sortorder 0
:event/team "away"
:event/id "event_4259036"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_12708"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Franco Vazquez"
:event/player1 "Andrea Barzagli"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4259067"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_12708"}

{:event/type "cross"
:event/elapsed 73
:event/subtype "cross"
:event/player1 "Fabio Daprela"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4259070"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_12708"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Paulo Dybala"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4259085"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_12708"}

{:event/type "shoton"
:event/elapsed 75
:event/subtype "deflected"
:event/player1 "Andrea Rispoli"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4259086"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_12708"}

{:event/type "corner"
:event/elapsed 77
:event/subtype "cross_right"
:event/player1 "Mate Jajalo"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4259105"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_12708"}

{:event/type "shoton"
:event/elapsed 77
:event/subtype "deflected"
:event/player1 "Paulo Dybala"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_4259107"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_12708"}

{:event/type "corner"
:event/elapsed 79
:event/subtype "cross_left"
:event/player1 "Claudio Marchisio"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4259138"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_12708"}

{:event/type "cross"
:event/elapsed 79
:event/subtype "cross"
:event/player1 "Andrea Rispoli"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4259147"
:event/elapsed_plus 0
:event/minute 79
:event/match_id "match_12708"}

{:event/type "foulcommit"
:event/elapsed 80
:event/player2 "Paulo Dybala"
:event/subtype "pushing"
:event/player1 "Alvaro Morata"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4259150"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_12708"}

{:event/type "card"
:event/elapsed 80
:event/card_type "y"
:event/player1 "Alvaro Morata"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4259152"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_12708"}

{:event/type "cross"
:event/elapsed 80
:event/subtype "cross"
:event/player1 "Mate Jajalo"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4259156"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_12708"}

{:event/type "shotoff"
:event/elapsed 81
:event/subtype "shot"
:event/player1 "Alvaro Morata"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4259163"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_12708"}

{:event/type "foulcommit"
:event/elapsed 83
:event/player2 "Sinisa Andjelkovic"
:event/player1 "Alvaro Morata"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4259199"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_12708"}

{:event/type "foulcommit"
:event/elapsed 84
:event/player2 "unknown"
:event/subtype "dangerous_play"
:event/player1 "Stephan Lichtsteiner"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4259212"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_12708"}

{:event/type "card"
:event/elapsed 84
:event/card_type "y"
:event/subtype "serious_fouls"
:event/player1 "Stephan Lichtsteiner"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_4259215"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_12708"}

{:event/type "cross"
:event/elapsed 85
:event/subtype "cross"
:event/player1 "Mate Jajalo"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4259221"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_12708"}

{:event/type "cross"
:event/elapsed 86
:event/subtype "cross"
:event/player1 "Andrea Rispoli"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4259241"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_12708"}

{:event/type "corner"
:event/elapsed 86
:event/subtype "cross_right"
:event/player1 "Mate Jajalo"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_4259247"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_12708"}

{:event/type "foulcommit"
:event/elapsed 87
:event/subtype "hands"
:event/player1 "Paulo Dybala"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4259251"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_12708"}

{:event/type "card"
:event/elapsed 87
:event/card_type "y"
:event/subtype "hands"
:event/player1 "Paulo Dybala"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4259253"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_12708"}

{:event/type "cross"
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Alvaro Morata"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4259287"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_12708"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Paulo Dybala"
:event/player1 "Roberto Pereyra"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4259294"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_12708"}

{:event/type "card"
:event/elapsed 90
:event/card_type "y"
:event/player1 "Roberto Pereyra"
:event/sortorder 3
:event/team "away"
:event/event_type "card"
:event/id "event_4259296"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_12708"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "unknown"
:event/sortorder 6
:event/team "home"
:event/event_type "cross"
:event/id "event_4259315"
:event/minute 91
:event/match_id "match_12708"}

{:event/type "shotoff"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Paulo Dybala"
:event/sortorder 8
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4259319"
:event/minute 91
:event/match_id "match_12708"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Franco Vazquez"
:event/sortorder 12
:event/team "home"
:event/event_type "cross"
:event/id "event_4259343"
:event/minute 93
:event/match_id "match_12708"}


]

