
;;# data
[
{:match/id "match_7300"
:match/league "France Ligue 1"
:match/hometeam "SM Caen"
:match/awayteam "AS Monaco"
:match/score "0:3"
:match/hometeam_goals "0"
:match/awayteam_goals "3"}

{:event/type "foulcommit"
:event/elapsed 2
:event/player2 "Aymen Abdennour"
:event/subtype "trip"
:event/player1 "Lenny Nangis"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4336380"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_7300"}

{:event/type "shotoff"
:event/elapsed 3
:event/subtype "deflected"
:event/player1 "Julien Feret"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4336388"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_7300"}

{:event/type "corner"
:event/elapsed 4
:event/subtype "cross_right"
:event/player1 "Julien Feret"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4336390"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_7300"}

{:event/type "shoton"
:event/elapsed 4
:event/subtype "shot"
:event/player1 "Felipe Saad"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4336394"
:event/elapsed_plus 0
:event/minute 4
:event/match_id "match_7300"}

{:event/type "cross"
:event/elapsed 5
:event/subtype "cross"
:event/player1 "Bernardo Silva"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4336397"
:event/elapsed_plus 0
:event/minute 5
:event/match_id "match_7300"}

{:event/type "foulcommit"
:event/elapsed 9
:event/player2 "Ricardo Carvalho"
:event/subtype "pushing"
:event/player1 "Emiliano Sala"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4336413"
:event/elapsed_plus 0
:event/minute 9
:event/match_id "match_7300"}

{:event/type "cross"
:event/elapsed 10
:event/subtype "cross"
:event/player1 "N'Golo Kante"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4336416"
:event/elapsed_plus 0
:event/minute 10
:event/match_id "match_7300"}

{:event/type "foulcommit"
:event/elapsed 12
:event/player2 "Bernardo Silva"
:event/player1 "Emmanuel Imorou"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4336423"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_7300"}

{:event/type "cross"
:event/elapsed 12
:event/subtype "cross"
:event/player1 "Yannick Ferreira-Carrasco"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4336425"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_7300"}

{:event/type "shotoff"
:event/elapsed 12
:event/subtype "header"
:event/player1 "Elderson"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4336427"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_7300"}

{:event/type "foulcommit"
:event/elapsed 13
:event/player2 "Emmanuel Imorou"
:event/player1 "Joao Moutinho"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4336439"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_7300"}

{:event/type "shoton"
:event/elapsed 14
:event/subtype "blocked_shot"
:event/player1 "Anthony Martial"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_4336435"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_7300"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "N'Golo Kante"
:event/player1 "Ricardo Carvalho"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4336441"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_7300"}

{:event/type "shoton"
:event/elapsed 16
:event/subtype "blocked_shot"
:event/player1 "Herve Bazile"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4336445"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_7300"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Yannick Ferreira-Carrasco"
:event/subtype "serious_foul"
:event/player1 "Herve Bazile"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4336447"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_7300"}

{:event/type "card"
:event/elapsed 17
:event/card_type "y"
:event/player1 "Herve Bazile"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_4336449"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_7300"}

{:event/type "cross"
:event/elapsed 17
:event/subtype "cross"
:event/player1 "Yannick Ferreira-Carrasco"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4336452"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_7300"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Yannick Ferreira-Carrasco"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4336465"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_7300"}

{:event/type "shoton"
:event/elapsed 22
:event/subtype "distance"
:event/player1 "Bernardo Silva"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_4336469"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_7300"}

{:event/type "corner"
:event/elapsed 22
:event/subtype "cross_left"
:event/player1 "Joao Moutinho"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4336470"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_7300"}

{:event/type "corner"
:event/elapsed 23
:event/subtype "cross_right"
:event/player1 "Joao Moutinho"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_4336472"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_7300"}

{:event/type "shotoff"
:event/elapsed 23
:event/subtype "header"
:event/player1 "Andrea Raggi"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4336476"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_7300"}

{:event/type "cross"
:event/elapsed 25
:event/subtype "cross"
:event/player1 "Yannick Ferreira-Carrasco"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4336492"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_7300"}

{:event/type "corner"
:event/elapsed 26
:event/subtype "cross_left"
:event/player1 "Julien Feret"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4336497"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_7300"}

{:event/type "shotoff"
:event/elapsed 26
:event/subtype "header"
:event/player1 "Damien Da Silva"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4336498"
:event/elapsed_plus 0
:event/minute 26
:event/match_id "match_7300"}

{:event/type "foulcommit"
:event/elapsed 28
:event/subtype "hands"
:event/player1 "N'Golo Kante"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4336539"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_7300"}

{:event/type "cross"
:event/elapsed 29
:event/subtype "cross"
:event/player1 "Yannick Ferreira-Carrasco"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_4336531"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_7300"}

{:event/type "goal"
:event/elapsed 29
:event/player2 "Yannick Ferreira-Carrasco"
:event/subtype "shot"
:event/player1 "Anthony Martial"
:event/sortorder 3
:event/team "away"
:event/id "event_4336515"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_7300"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Andrea Raggi"
:event/player1 "Emmanuel Imorou"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4336525"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_7300"}

{:event/type "cross"
:event/elapsed 32
:event/subtype "cross"
:event/player1 "Joao Moutinho"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4336528"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_7300"}

{:event/type "shoton"
:event/elapsed 33
:event/subtype "shot"
:event/player1 "Emiliano Sala"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_4336542"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_7300"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Herve Bazile"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4336549"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_7300"}

{:event/type "foulcommit"
:event/elapsed 36
:event/player2 "Aymen Abdennour"
:event/subtype "pushing"
:event/player1 "Emiliano Sala"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4336556"
:event/elapsed_plus 0
:event/minute 36
:event/match_id "match_7300"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Lenny Nangis"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4336563"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_7300"}

{:event/type "cross"
:event/elapsed 39
:event/subtype "cross"
:event/player1 "Dennis Appiah"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4336572"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_7300"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Lenny Nangis"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4336579"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_7300"}

{:event/type "foulcommit"
:event/elapsed 42
:event/player2 "Anthony Martial"
:event/subtype "pull"
:event/player1 "Emmanuel Imorou"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4336588"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_7300"}

{:event/type "card"
:event/elapsed 42
:event/card_type "y"
:event/player1 "Emmanuel Imorou"
:event/sortorder 2
:event/team "home"
:event/event_type "card"
:event/id "event_4336590"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_7300"}

{:event/type "cross"
:event/elapsed 43
:event/subtype "cross"
:event/player1 "Yannick Ferreira-Carrasco"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_4336591"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_7300"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Ricardo Carvalho"
:event/player1 "Emiliano Sala"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4336683"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_7300"}

{:event/type "shotoff"
:event/elapsed 54
:event/subtype "distance"
:event/player1 "Yannick Ferreira-Carrasco"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4336667"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_7300"}

{:event/type "cross"
:event/elapsed 55
:event/subtype "cross"
:event/player1 "N'Golo Kante"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4336674"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_7300"}

{:event/type "corner"
:event/elapsed 55
:event/subtype "cross_left"
:event/player1 "Julien Feret"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4336678"
:event/elapsed_plus 0
:event/minute 55
:event/match_id "match_7300"}

{:event/type "cross"
:event/elapsed 59
:event/subtype "cross"
:event/player1 "Emmanuel Imorou"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4336701"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_7300"}

{:event/type "shotoff"
:event/elapsed 60
:event/subtype "shot"
:event/player1 "Yannick Ferreira-Carrasco"
:event/sortorder 2
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4336707"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_7300"}

{:event/type "shotoff"
:event/elapsed 63
:event/subtype "deflected"
:event/player1 "Bernardo Silva"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4336721"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_7300"}

{:event/type "corner"
:event/elapsed 64
:event/subtype "short_right"
:event/player1 "Bernardo Silva"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_4336729"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_7300"}

{:event/type "goal"
:event/elapsed 64
:event/player2 "Yannick Ferreira-Carrasco"
:event/subtype "shot"
:event/player1 "Bernardo Silva"
:event/sortorder 2
:event/team "away"
:event/id "event_4336722"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_7300"}

{:event/type "foulcommit"
:event/elapsed 66
:event/player2 "Damien Da Silva"
:event/subtype "pushing"
:event/player1 "Anthony Martial"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4336732"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_7300"}

{:event/type "shotoff"
:event/elapsed 68
:event/subtype "distance"
:event/player1 "N'Golo Kante"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4336738"
:event/elapsed_plus 0
:event/minute 68
:event/match_id "match_7300"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Dennis Appiah"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4336743"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_7300"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Herve Bazile"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_4336748"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_7300"}

{:event/type "cross"
:event/elapsed 72
:event/subtype "cross"
:event/player1 "Julien Feret"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4336754"
:event/elapsed_plus 0
:event/minute 72
:event/match_id "match_7300"}

{:event/type "foulcommit"
:event/elapsed 73
:event/player2 "Damien Da Silva"
:event/player1 "Anthony Martial"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_4336851"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_7300"}

{:event/type "cross"
:event/elapsed 74
:event/subtype "cross"
:event/player1 "Emiliano Sala"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4336764"
:event/elapsed_plus 0
:event/minute 74
:event/match_id "match_7300"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Yannick Ferreira-Carrasco"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4336769"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_7300"}

{:event/type "shotoff"
:event/elapsed 80
:event/subtype "big chance shot"
:event/player1 "Anthony Martial"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_4336793"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_7300"}

{:event/type "corner"
:event/elapsed 81
:event/subtype "cross_left"
:event/player1 "Julien Feret"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_4336797"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_7300"}

{:event/type "shoton"
:event/elapsed 81
:event/subtype "blocked_header"
:event/player1 "Thomas Lemar"
:event/sortorder 1
:event/team "home"
:event/event_type "shoton"
:event/id "event_4336799"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_7300"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/sortorder 2
:event/team "home"
:event/event_type "throwin"
:event/id "event_4336800"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_7300"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Julien Feret"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4336808"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_7300"}

{:event/type "corner"
:event/elapsed 82
:event/subtype "cross_left"
:event/player1 "Thomas Lemar"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_4336810"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_7300"}

{:event/type "shotoff"
:event/elapsed 82
:event/subtype "shot"
:event/player1 "Nicolas Seube"
:event/sortorder 3
:event/team "home"
:event/event_type "shotoff"
:event/id "event_4336811"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_7300"}

{:event/type "cross"
:event/elapsed 83
:event/subtype "cross"
:event/player1 "Yannick Ferreira-Carrasco"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_4336814"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_7300"}

{:event/type "goal"
:event/elapsed 84
:event/player2 "Anthony Martial"
:event/subtype "shot"
:event/player1 "Bernardo Silva"
:event/sortorder 1
:event/team "away"
:event/id "event_4336819"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_7300"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Geoffrey Kondogbia"
:event/player1 "N'Golo Kante"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_4336845"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_7300"}

{:event/type "cross"
:event/elapsed 87
:event/subtype "cross"
:event/player1 "Dennis Appiah"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_4336835"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_7300"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Dennis Appiah"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_4336867"
:event/minute 93
:event/match_id "match_7300"}


]

