
;;# data
[
{:match/id "match_22643"
:match/league "Spain LIGA BBVA"
:match/hometeam "UD Almería"
:match/awayteam "Hércules Club de Fútbol"
:match/score "1:1"
:match/hometeam_goals "1"
:match/awayteam_goals "1"}

{:event/type "card"
:event/elapsed 19
:event/card_type "y"
:event/player1 "Paco Pena"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1235757"
:event/elapsed_plus 0
:event/minute 19
:event/match_id "match_22643"}

{:event/type "goal"
:event/elapsed 37
:event/player1 "Nelson Haedo Valdez"
:event/sortorder 0
:event/team "away"
:event/id "event_1235622"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_22643"}

{:event/type "card"
:event/elapsed 43
:event/card_type "y"
:event/player1 "Sergio Rodri"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1235722"
:event/elapsed_plus 0
:event/minute 43
:event/match_id "match_22643"}

{:event/type "card"
:event/elapsed 44
:event/card_type "y"
:event/player1 "Hernan Dario Bernardello"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1235721"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_22643"}

{:event/type "card"
:event/elapsed 62
:event/card_type "y"
:event/player1 "Abel Aguilar"
:event/sortorder 0
:event/team "away"
:event/event_type "card"
:event/id "event_1235957"
:event/elapsed_plus 0
:event/minute 62
:event/match_id "match_22643"}

{:event/type "goal"
:event/elapsed 83
:event/player1 "Jose Leonardo Ulloa"
:event/sortorder 0
:event/team "home"
:event/id "event_1236175"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 83
:event/match_id "match_22643"}

{:event/type "card"
:event/elapsed 87
:event/card_type "y"
:event/player1 "Modeste M'Bami"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_1236237"
:event/elapsed_plus 0
:event/minute 87
:event/match_id "match_22643"}


]

