
;;# data
[
{:match/id "match_4420"
:match/league "England Premier League"
:match/hometeam "Aston Villa"
:match/awayteam "Manchester City"
:match/score "0:0"
:match/hometeam_goals "0"
:match/awayteam_goals "0"}

{:event/type "cross"
:event/elapsed 2
:event/subtype "cross"
:event/player1 "Jordan Amavi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5011591"
:event/elapsed_plus 0
:event/minute 2
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed 3
:event/subtype "cross"
:event/player1 "Alan Hutton"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5011601"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_4420"}

{:event/type "foulcommit"
:event/elapsed 3
:event/player2 "Carles Gil"
:event/subtype "trip"
:event/player1 "Yaya Toure"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5011610"
:event/elapsed_plus 0
:event/minute 3
:event/match_id "match_4420"}

{:event/type "foulcommit"
:event/elapsed 6
:event/player2 "Micah Richards"
:event/subtype "obstruction"
:event/player1 "Aleksandar Kolarov"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5011634"
:event/elapsed_plus 0
:event/minute 6
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed 8
:event/subtype "cross"
:event/player1 "Jordan Amavi"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5011657"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_4420"}

{:event/type "shotoff"
:event/elapsed 14
:event/subtype "distance"
:event/player1 "Idrissa Gana Gueye"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5011727"
:event/elapsed_plus 0
:event/minute 14
:event/match_id "match_4420"}

{:event/type "foulcommit"
:event/elapsed 16
:event/player2 "Vincent Kompany"
:event/subtype "pushing"
:event/player1 "Jordan Ayew"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5011753"
:event/elapsed_plus 0
:event/minute 16
:event/match_id "match_4420"}

{:event/type "shoton"
:event/elapsed 17
:event/subtype "shot"
:event/player1 "Aleksandar Kolarov"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_5011766"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_4420"}

{:event/type "corner"
:event/elapsed 17
:event/subtype "cross_left"
:event/player1 "Aleksandar Kolarov"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_5011776"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_4420"}

{:event/type "shotoff"
:event/elapsed 18
:event/subtype "shot"
:event/player1 "Fernando"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5011780"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_4420"}

{:event/type "corner"
:event/elapsed 21
:event/subtype "cross_right"
:event/player1 "Kevin de Bruyne"
:event/sortorder 7
:event/team "away"
:event/event_type "corner"
:event/id "event_5011814"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_4420"}

{:event/type "shoton"
:event/elapsed 21
:event/subtype "blocked_header"
:event/player1 "Bacary Sagna"
:event/sortorder 8
:event/team "away"
:event/event_type "shoton"
:event/id "event_5011818"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed 21
:event/subtype "cross"
:event/player1 "Raheem Sterling"
:event/sortorder 10
:event/team "away"
:event/event_type "cross"
:event/id "event_5011820"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed 23
:event/subtype "cross"
:event/player1 "Alan Hutton"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5011846"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_4420"}

{:event/type "foulcommit"
:event/elapsed 24
:event/player2 "Nicolas Otamendi"
:event/player1 "Scott Sinclair"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5011967"
:event/elapsed_plus 0
:event/minute 24
:event/match_id "match_4420"}

{:event/type "foulcommit"
:event/elapsed 27
:event/player2 "Kevin de Bruyne"
:event/subtype "from_behind"
:event/player1 "Alan Hutton"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5011896"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed 27
:event/subtype "cross"
:event/player1 "Aleksandar Kolarov"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5011906"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Yaya Toure"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5012017"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Bacary Sagna"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5012041"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_4420"}

{:event/type "corner"
:event/elapsed 35
:event/subtype "cross_right"
:event/player1 "Kevin de Bruyne"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_5012050"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Idrissa Gana Gueye"
:event/sortorder 3
:event/team "home"
:event/event_type "cross"
:event/id "event_5115506"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Jordan Ayew"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5115514"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_4420"}

{:event/type "foulcommit"
:event/elapsed 39
:event/player2 "Carles Gil"
:event/subtype "trip"
:event/player1 "Nicolas Otamendi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5012133"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_4420"}

{:event/type "card"
:event/elapsed 39
:event/card_type "y"
:event/player1 "Nicolas Otamendi"
:event/sortorder 1
:event/team "away"
:event/event_type "card"
:event/id "event_5012140"
:event/elapsed_plus 0
:event/minute 39
:event/match_id "match_4420"}

{:event/type "shotoff"
:event/elapsed 41
:event/subtype "direct_freekick"
:event/player1 "Carles Gil"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5012176"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed 42
:event/subtype "cross"
:event/player1 "Kevin de Bruyne"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5012194"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Nicolas Otamendi"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5115518"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_4420"}

{:event/type "foulcommit"
:event/elapsed 45
:event/player2 "Carles Gil"
:event/subtype "pushing"
:event/player1 "Raheem Sterling"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5012274"
:event/elapsed_plus 0
:event/minute 45
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 45
:event/subtype "cross"
:event/player1 "Jesus Navas"
:event/sortorder 5
:event/team "away"
:event/event_type "cross"
:event/id "event_5012303"
:event/minute 46
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed 47
:event/subtype "cross"
:event/player1 "Jesus Navas"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5012571"
:event/elapsed_plus 0
:event/minute 47
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed 50
:event/subtype "cross"
:event/player1 "Jordan Amavi"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5012636"
:event/elapsed_plus 0
:event/minute 50
:event/match_id "match_4420"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Nicolas Otamendi"
:event/subtype "trip"
:event/player1 "Jordan Ayew"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5012646"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Yaya Toure"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5012655"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_4420"}

{:event/type "foulcommit"
:event/elapsed 52
:event/player2 "Fernandinho"
:event/subtype "trip"
:event/player1 "Idrissa Gana Gueye"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5012666"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_4420"}

{:event/type "shoton"
:event/elapsed 52
:event/subtype "direct_freekick"
:event/player1 "Aleksandar Kolarov"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_5012685"
:event/elapsed_plus 0
:event/minute 52
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Jesus Navas"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5012702"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Aleksandar Kolarov"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5012706"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed 54
:event/subtype "cross"
:event/player1 "Jesus Navas"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5012710"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_4420"}

{:event/type "shoton"
:event/elapsed 54
:event/subtype "big chance header"
:event/player1 "Raheem Sterling"
:event/sortorder 1
:event/team "away"
:event/event_type "shoton"
:event/id "event_5012716"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_4420"}

{:event/type "corner"
:event/elapsed 54
:event/subtype "cross_left"
:event/player1 "Aleksandar Kolarov"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_5012720"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_4420"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Carles Gil"
:event/subtype "trip"
:event/player1 "Kevin de Bruyne"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5012782"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed 58
:event/subtype "cross"
:event/player1 "Aleksandar Kolarov"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5012820"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_4420"}

{:event/type "shoton"
:event/elapsed 60
:event/subtype "blocked_shot"
:event/player1 "Raheem Sterling"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_5012849"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed 60
:event/subtype "cross"
:event/player1 "Bacary Sagna"
:event/sortorder 4
:event/team "away"
:event/event_type "cross"
:event/id "event_5012858"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_4420"}

{:event/type "corner"
:event/elapsed 60
:event/subtype "cross_right"
:event/player1 "Kevin de Bruyne"
:event/sortorder 5
:event/team "away"
:event/event_type "corner"
:event/id "event_5012863"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_4420"}

{:event/type "shotoff"
:event/elapsed 60
:event/subtype "header"
:event/player1 "Yaya Toure"
:event/sortorder 6
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5012866"
:event/elapsed_plus 0
:event/minute 60
:event/match_id "match_4420"}

{:event/type "foulcommit"
:event/elapsed 63
:event/player2 "Idrissa Gana Gueye"
:event/subtype "trip"
:event/player1 "Fernandinho"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5012905"
:event/elapsed_plus 0
:event/minute 63
:event/match_id "match_4420"}

{:event/type "shoton"
:event/elapsed 64
:event/subtype "blocked_shot"
:event/player1 "Raheem Sterling"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_5012924"
:event/elapsed_plus 0
:event/minute 64
:event/match_id "match_4420"}

{:event/type "corner"
:event/elapsed 65
:event/subtype "cross_right"
:event/player1 "Jesus Navas"
:event/sortorder 3
:event/team "away"
:event/event_type "corner"
:event/id "event_5012933"
:event/elapsed_plus 0
:event/minute 65
:event/match_id "match_4420"}

{:event/type "shotoff"
:event/elapsed 66
:event/subtype "bad shot"
:event/player1 "Kevin de Bruyne"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5012943"
:event/elapsed_plus 0
:event/minute 66
:event/match_id "match_4420"}

{:event/type "shotoff"
:event/elapsed 67
:event/subtype "distance"
:event/player1 "Raheem Sterling"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5012954"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_4420"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Micah Richards"
:event/subtype "pushing"
:event/player1 "Raheem Sterling"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5012990"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed 70
:event/subtype "cross"
:event/player1 "Alan Hutton"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5115972"
:event/elapsed_plus 0
:event/minute 70
:event/match_id "match_4420"}

{:event/type "corner"
:event/elapsed 71
:event/subtype "cross_right"
:event/player1 "Charles N'Zogbia"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_5013006"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_4420"}

{:event/type "foulcommit"
:event/elapsed 71
:event/player2 "Joe Hart"
:event/subtype "pushing"
:event/player1 "Micah Richards"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5013007"
:event/elapsed_plus 0
:event/minute 71
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed 75
:event/subtype "cross"
:event/player1 "Charles N'Zogbia"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5013051"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_4420"}

{:event/type "corner"
:event/elapsed 75
:event/subtype "cross_left"
:event/player1 "Jordan Veretout"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_5013063"
:event/elapsed_plus 0
:event/minute 75
:event/match_id "match_4420"}

{:event/type "foulcommit"
:event/elapsed 76
:event/player2 "Aleksandar Kolarov"
:event/subtype "from_behind"
:event/player1 "Idrissa Gana Gueye"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5013080"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Aleksandar Kolarov"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5013087"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed 77
:event/subtype "cross"
:event/player1 "Yaya Toure"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5013094"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_4420"}

{:event/type "shotoff"
:event/elapsed 80
:event/subtype "shot"
:event/player1 "Aleksandar Kolarov"
:event/sortorder 0
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5013168"
:event/elapsed_plus 0
:event/minute 80
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Charles N'Zogbia"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5013223"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Alan Hutton"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5013232"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Jordan Veretout"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5013240"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_4420"}

{:event/type "corner"
:event/elapsed 88
:event/subtype "cross_left"
:event/player1 "Jordan Veretout"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5013469"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_4420"}

{:event/type "shotoff"
:event/elapsed 88
:event/subtype "shot"
:event/player1 "Rudy Gestede"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5013476"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed 89
:event/subtype "cross"
:event/player1 "Kevin de Bruyne"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5013488"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_4420"}

{:event/type "corner"
:event/elapsed 90
:event/subtype "cross_right"
:event/player1 "Jesus Navas"
:event/sortorder 1
:event/team "away"
:event/event_type "corner"
:event/id "event_5013525"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Jesus Navas"
:event/sortorder 5
:event/team "away"
:event/event_type "cross"
:event/id "event_5013540"
:event/minute 91
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Jesus Navas"
:event/sortorder 8
:event/team "away"
:event/event_type "cross"
:event/id "event_5013549"
:event/minute 91
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed_plus 1
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Jesus Navas"
:event/sortorder 12
:event/team "away"
:event/event_type "cross"
:event/id "event_5013573"
:event/minute 91
:event/match_id "match_4420"}

{:event/type "corner"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "short_right"
:event/player1 "Jesus Navas"
:event/sortorder 13
:event/team "away"
:event/event_type "corner"
:event/id "event_5013583"
:event/minute 92
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Kelechi Iheanacho"
:event/sortorder 14
:event/team "away"
:event/event_type "cross"
:event/id "event_5013591"
:event/minute 92
:event/match_id "match_4420"}

{:event/type "shotoff"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "big chance crossbar"
:event/player1 "Fernando"
:event/sortorder 15
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5013595"
:event/minute 92
:event/match_id "match_4420"}

{:event/type "shoton"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "blocked_shot"
:event/player1 "Nicolas Otamendi"
:event/sortorder 16
:event/team "away"
:event/event_type "shoton"
:event/id "event_5013598"
:event/minute 92
:event/match_id "match_4420"}

{:event/type "shotoff"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Fernandinho"
:event/sortorder 17
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5013602"
:event/minute 92
:event/match_id "match_4420"}

{:event/type "card"
:event/elapsed_plus 3
:event/elapsed 90
:event/card_type "y"
:event/subtype "stall_time"
:event/player1 "Brad Guzan"
:event/sortorder 19
:event/team "home"
:event/event_type "card"
:event/id "event_5013620"
:event/minute 93
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed_plus 3
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Bacary Sagna"
:event/sortorder 20
:event/team "away"
:event/event_type "cross"
:event/id "event_5013626"
:event/minute 93
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Kevin de Bruyne"
:event/sortorder 22
:event/team "away"
:event/event_type "cross"
:event/id "event_5013647"
:event/minute 94
:event/match_id "match_4420"}

{:event/type "shoton"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "blocked_shot"
:event/player1 "Aleksandar Kolarov"
:event/sortorder 24
:event/team "away"
:event/event_type "shoton"
:event/id "event_5013652"
:event/minute 94
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Jesus Navas"
:event/sortorder 25
:event/team "away"
:event/event_type "cross"
:event/id "event_5013654"
:event/minute 94
:event/match_id "match_4420"}

{:event/type "cross"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Kevin de Bruyne"
:event/sortorder 27
:event/team "away"
:event/event_type "cross"
:event/id "event_5013664"
:event/minute 94
:event/match_id "match_4420"}


]

