
;;# data
[
{:match/id "match_12938"
:match/league "Italy Serie A"
:match/hometeam "Genoa"
:match/awayteam "Sassuolo"
:match/score "2:1"
:match/hometeam_goals "2"
:match/awayteam_goals "1"}

{:event/type "foulcommit"
:event/elapsed 1
:event/player2 "Francesco Magnanelli"
:event/player1 "Tino Costa"
:event/sortorder 3
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5045166"
:event/elapsed_plus 0
:event/minute 1
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 7
:event/player2 "Leonardo Pavoletti"
:event/subtype "from_behind"
:event/player1 "Francesco Magnanelli"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5045313"
:event/elapsed_plus 0
:event/minute 7
:event/match_id "match_12938"}

{:event/type "corner"
:event/elapsed 8
:event/subtype "cross_right"
:event/player1 "Darko Lazovic"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5045349"
:event/elapsed_plus 0
:event/minute 8
:event/match_id "match_12938"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Nicola Sansone"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5045417"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_12938"}

{:event/type "corner"
:event/elapsed 11
:event/subtype "short_left"
:event/player1 "Simone Missiroli"
:event/sortorder 2
:event/team "away"
:event/event_type "corner"
:event/id "event_5045426"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_12938"}

{:event/type "cross"
:event/elapsed 11
:event/subtype "cross"
:event/player1 "Alfred Duncan"
:event/sortorder 3
:event/team "away"
:event/event_type "cross"
:event/id "event_5045428"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_12938"}

{:event/type "shoton"
:event/elapsed 11
:event/subtype "shot"
:event/player1 "Domenico Berardi"
:event/sortorder 4
:event/team "away"
:event/event_type "shoton"
:event/id "event_5045435"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 11
:event/player2 "Nicola Sansone"
:event/player1 "Armando Izzo"
:event/sortorder 5
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5045444"
:event/elapsed_plus 0
:event/minute 11
:event/match_id "match_12938"}

{:event/type "shoton"
:event/elapsed 12
:event/subtype "direct_freekick"
:event/player1 "Domenico Berardi"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_5045464"
:event/elapsed_plus 0
:event/minute 12
:event/match_id "match_12938"}

{:event/type "shotoff"
:event/elapsed 13
:event/subtype "distance"
:event/player1 "Diego Perotti"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5045496"
:event/elapsed_plus 0
:event/minute 13
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 17
:event/player2 "Diego Perotti"
:event/player1 "Sime Vrsaljko"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5045641"
:event/elapsed_plus 0
:event/minute 17
:event/match_id "match_12938"}

{:event/type "shotoff"
:event/elapsed 18
:event/subtype "distance"
:event/player1 "Diego Laxalt"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5045597"
:event/elapsed_plus 0
:event/minute 18
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Tino Costa"
:event/player1 "Francesco Magnanelli"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5045662"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 21
:event/player2 "Francesco Magnanelli"
:event/subtype "pushing"
:event/player1 "Tomas Rincon"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5045674"
:event/elapsed_plus 0
:event/minute 21
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 22
:event/player2 "Armando Izzo"
:event/subtype "trip"
:event/player1 "Simone Missiroli"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5045687"
:event/elapsed_plus 0
:event/minute 22
:event/match_id "match_12938"}

{:event/type "shotoff"
:event/elapsed 23
:event/subtype "distance"
:event/player1 "Leonardo Pavoletti"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5045698"
:event/elapsed_plus 0
:event/minute 23
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 25
:event/player2 "Gregoire Defrel"
:event/subtype "pushing"
:event/player1 "Tomas Rincon"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5045753"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_12938"}

{:event/type "card"
:event/elapsed 25
:event/card_type "y"
:event/player1 "Tomas Rincon"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_5045756"
:event/elapsed_plus 0
:event/minute 25
:event/match_id "match_12938"}

{:event/type "shotoff"
:event/elapsed 27
:event/subtype "deflected"
:event/player1 "Darko Lazovic"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5045786"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_12938"}

{:event/type "corner"
:event/elapsed 27
:event/subtype "cross_right"
:event/player1 "Diego Perotti"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_5045795"
:event/elapsed_plus 0
:event/minute 27
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 28
:event/player2 "Paolo Cannavaro"
:event/player1 "Leonardo Pavoletti"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5045798"
:event/elapsed_plus 0
:event/minute 28
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Sime Vrsaljko"
:event/player1 "Leonardo Pavoletti"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5045820"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 29
:event/player2 "Gregoire Defrel"
:event/player1 "Diogo Figueiras"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5045823"
:event/elapsed_plus 0
:event/minute 29
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 30
:event/player2 "Cristian Daniel Ansaldi"
:event/subtype "pull"
:event/player1 "Sime Vrsaljko"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5045837"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_12938"}

{:event/type "cross"
:event/elapsed 30
:event/subtype "cross"
:event/player1 "Alfred Duncan"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5045852"
:event/elapsed_plus 0
:event/minute 30
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 31
:event/player2 "Diego Laxalt"
:event/player1 "Federico Peluso"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5045860"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_12938"}

{:event/type "cross"
:event/elapsed 31
:event/subtype "cross"
:event/player1 "Domenico Berardi"
:event/sortorder 2
:event/team "away"
:event/event_type "cross"
:event/id "event_5045874"
:event/elapsed_plus 0
:event/minute 31
:event/match_id "match_12938"}

{:event/type "shoton"
:event/elapsed 32
:event/subtype "shot"
:event/player1 "Domenico Berardi"
:event/sortorder 0
:event/team "away"
:event/event_type "shoton"
:event/id "event_5045889"
:event/elapsed_plus 0
:event/minute 32
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 33
:event/player2 "Diego Perotti"
:event/player1 "Domenico Berardi"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5045916"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_12938"}

{:event/type "cross"
:event/elapsed 33
:event/subtype "cross"
:event/player1 "Tino Costa"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5045928"
:event/elapsed_plus 0
:event/minute 33
:event/match_id "match_12938"}

{:event/type "shotoff"
:event/elapsed 34
:event/subtype "header"
:event/player1 "Leonardo Pavoletti"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5045936"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_12938"}

{:event/type "cross"
:event/elapsed 34
:event/subtype "cross"
:event/player1 "Darko Lazovic"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5045944"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 34
:event/player2 "Leonardo Pavoletti"
:event/player1 "Francesco Magnanelli"
:event/sortorder 4
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5045955"
:event/elapsed_plus 0
:event/minute 34
:event/match_id "match_12938"}

{:event/type "cross"
:event/elapsed 35
:event/subtype "cross"
:event/player1 "Tino Costa"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5045967"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 35
:event/player2 "Paolo Cannavaro"
:event/subtype "pushing"
:event/player1 "Nicolas Burdisso"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5045976"
:event/elapsed_plus 0
:event/minute 35
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Nicolas Burdisso"
:event/subtype "trip"
:event/player1 "Gregoire Defrel"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5046013"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_12938"}

{:event/type "cross"
:event/elapsed 37
:event/subtype "cross"
:event/player1 "Diego Perotti"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5046025"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 37
:event/player2 "Andrea Consigli"
:event/subtype "pushing"
:event/player1 "Leonardo Pavoletti"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5046029"
:event/elapsed_plus 0
:event/minute 37
:event/match_id "match_12938"}

{:event/type "cross"
:event/elapsed 38
:event/subtype "cross"
:event/player1 "Nicola Sansone"
:event/sortorder 0
:event/team "away"
:event/event_type "cross"
:event/id "event_5046049"
:event/elapsed_plus 0
:event/minute 38
:event/match_id "match_12938"}

{:event/type "cross"
:event/elapsed 41
:event/subtype "cross"
:event/player1 "Darko Lazovic"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5046119"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 41
:event/player2 "Domenico Berardi"
:event/subtype "from_behind"
:event/player1 "Cristian Daniel Ansaldi"
:event/sortorder 2
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5046148"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_12938"}

{:event/type "card"
:event/elapsed 41
:event/card_type "r"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Domenico Berardi"
:event/sortorder 5
:event/team "away"
:event/event_type "card"
:event/id "event_5046199"
:event/elapsed_plus 0
:event/minute 41
:event/match_id "match_12938"}

{:event/type "card"
:event/elapsed 42
:event/card_type "r"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Diego Perotti"
:event/sortorder 0
:event/team "home"
:event/event_type "card"
:event/id "event_5046198"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_12938"}

{:event/type "card"
:event/elapsed 42
:event/card_type "y"
:event/subtype "Unsportsmanlike Cond"
:event/player1 "Mattia Perin"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_5046205"
:event/elapsed_plus 0
:event/minute 42
:event/match_id "match_12938"}

{:event/type "corner"
:event/elapsed 44
:event/subtype "cross_right"
:event/player1 "Simone Missiroli"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_5046295"
:event/elapsed_plus 0
:event/minute 44
:event/match_id "match_12938"}

{:event/type "cross"
:event/elapsed 46
:event/subtype "cross"
:event/player1 "Diogo Figueiras"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5046513"
:event/elapsed_plus 0
:event/minute 46
:event/match_id "match_12938"}

{:event/type "corner"
:event/elapsed_plus 2
:event/elapsed 45
:event/subtype "cross_left"
:event/player1 "Darko Lazovic"
:event/sortorder 2
:event/team "home"
:event/event_type "corner"
:event/id "event_5046316"
:event/minute 47
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 51
:event/player2 "Tomas Rincon"
:event/player1 "Francesco Magnanelli"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5046626"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_12938"}

{:event/type "cross"
:event/elapsed 51
:event/subtype "cross"
:event/player1 "Darko Lazovic"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5046631"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_12938"}

{:event/type "goal"
:event/elapsed 51
:event/player2 "Armando Izzo"
:event/subtype "distance"
:event/player1 "Tomas Rincon"
:event/sortorder 5
:event/team "home"
:event/id "event_5046635"
:event/event_type "goal"
:event/goal_type "n"
:event/elapsed_plus 0
:event/minute 51
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 53
:event/player2 "Francesco Magnanelli"
:event/player1 "Tino Costa"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5046680"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_12938"}

{:event/type "cross"
:event/elapsed 53
:event/subtype "cross"
:event/player1 "Simone Missiroli"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5046695"
:event/elapsed_plus 0
:event/minute 53
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 54
:event/player2 "Francesco Acerbi"
:event/player1 "Tino Costa"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5047928"
:event/elapsed_plus 0
:event/minute 54
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 56
:event/player2 "Tino Costa"
:event/player1 "Francesco Magnanelli"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5046788"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_12938"}

{:event/type "cross"
:event/elapsed 56
:event/subtype "cross"
:event/player1 "Tomas Rincon"
:event/sortorder 1
:event/team "home"
:event/event_type "cross"
:event/id "event_5046792"
:event/elapsed_plus 0
:event/minute 56
:event/match_id "match_12938"}

{:event/type "corner"
:event/elapsed 57
:event/subtype "cross_left"
:event/player1 "Leonardo Pavoletti"
:event/sortorder 0
:event/team "home"
:event/event_type "corner"
:event/id "event_5047150"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_12938"}

{:event/type "cross"
:event/elapsed 57
:event/subtype "cross"
:event/player1 "Darko Lazovic"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5046829"
:event/elapsed_plus 0
:event/minute 57
:event/match_id "match_12938"}

{:event/type "shotoff"
:event/elapsed 58
:event/subtype "header"
:event/player1 "Leonardo Pavoletti"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5046835"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 58
:event/player2 "Tino Costa"
:event/player1 "Federico Peluso"
:event/sortorder 2
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5046889"
:event/elapsed_plus 0
:event/minute 58
:event/match_id "match_12938"}

{:event/type "shoton"
:event/elapsed 59
:event/subtype "shot"
:event/player1 "Leonardo Pavoletti"
:event/sortorder 0
:event/team "home"
:event/event_type "shoton"
:event/id "event_5046880"
:event/elapsed_plus 0
:event/minute 59
:event/match_id "match_12938"}

{:event/type "cross"
:event/elapsed 61
:event/subtype "cross"
:event/player1 "Simone Missiroli"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5046947"
:event/elapsed_plus 0
:event/minute 61
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 67
:event/player2 "Gregoire Defrel"
:event/player1 "Cristian Daniel Ansaldi"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5047050"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_12938"}

{:event/type "cross"
:event/elapsed 67
:event/subtype "cross"
:event/player1 "Nicola Sansone"
:event/sortorder 1
:event/team "away"
:event/event_type "cross"
:event/id "event_5047056"
:event/elapsed_plus 0
:event/minute 67
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 69
:event/player2 "Diego Laxalt"
:event/subtype "trip"
:event/player1 "Sime Vrsaljko"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5047101"
:event/elapsed_plus 0
:event/minute 69
:event/match_id "match_12938"}

{:event/type "corner"
:event/elapsed 73
:event/subtype "cross_right"
:event/player1 "Nicolas Burdisso"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_5047179"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_12938"}

{:event/type "shoton"
:event/elapsed 73
:event/subtype "header"
:event/player1 "Leonardo Pavoletti"
:event/sortorder 2
:event/team "home"
:event/event_type "shoton"
:event/id "event_5047185"
:event/elapsed_plus 0
:event/minute 73
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 76
:event/player2 "Matteo Politano"
:event/subtype "trip"
:event/player1 "Nicolas Burdisso"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5047956"
:event/elapsed_plus 0
:event/minute 76
:event/match_id "match_12938"}

{:event/type "corner"
:event/elapsed 77
:event/subtype "cross_left"
:event/player1 "Sergio Floccari"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_5047250"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_12938"}

{:event/type "shotoff"
:event/elapsed 77
:event/subtype "shot"
:event/player1 "Francesco Magnanelli"
:event/sortorder 1
:event/team "away"
:event/event_type "shotoff"
:event/id "event_5047260"
:event/elapsed_plus 0
:event/minute 77
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 78
:event/player2 "Tino Costa"
:event/player1 "Francesco Magnanelli"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5047295"
:event/elapsed_plus 0
:event/minute 78
:event/match_id "match_12938"}

{:event/type "cross"
:event/elapsed 81
:event/subtype "cross"
:event/player1 "Blerim Dzemaili"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5047356"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_12938"}

{:event/type "shotoff"
:event/elapsed 81
:event/subtype "shot"
:event/player1 "Serge Gakpe"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5047359"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 81
:event/player2 "Diego Laxalt"
:event/player1 "Francesco Magnanelli"
:event/sortorder 3
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5047382"
:event/elapsed_plus 0
:event/minute 81
:event/match_id "match_12938"}

{:event/type "cross"
:event/elapsed 82
:event/subtype "cross"
:event/player1 "Issa Cissokho"
:event/sortorder 0
:event/team "home"
:event/event_type "cross"
:event/id "event_5047402"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_12938"}

{:event/type "shotoff"
:event/elapsed 82
:event/subtype "bicycle_kick"
:event/player1 "Diego Laxalt"
:event/sortorder 1
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5047406"
:event/elapsed_plus 0
:event/minute 82
:event/match_id "match_12938"}

{:event/type "shotoff"
:event/elapsed 84
:event/subtype "deflected"
:event/player1 "Tino Costa"
:event/sortorder 0
:event/team "home"
:event/event_type "shotoff"
:event/id "event_5047432"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_12938"}

{:event/type "corner"
:event/elapsed 84
:event/subtype "short_left"
:event/player1 "Diego Laxalt"
:event/sortorder 1
:event/team "home"
:event/event_type "corner"
:event/id "event_5047438"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_12938"}

{:event/type "cross"
:event/elapsed 84
:event/subtype "cross"
:event/player1 "Tino Costa"
:event/sortorder 2
:event/team "home"
:event/event_type "cross"
:event/id "event_5047443"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_12938"}

{:event/type "shoton"
:event/elapsed 84
:event/subtype "header"
:event/player1 "Leonardo Pavoletti"
:event/sortorder 3
:event/team "home"
:event/event_type "shoton"
:event/id "event_5047451"
:event/elapsed_plus 0
:event/minute 84
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Simone Missiroli"
:event/player1 "Tomas Rincon"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5047470"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 85
:event/player2 "Blerim Dzemaili"
:event/player1 "Simone Missiroli"
:event/sortorder 1
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5047481"
:event/elapsed_plus 0
:event/minute 85
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 86
:event/player2 "Sergio Floccari"
:event/player1 "Diego Laxalt"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5047502"
:event/elapsed_plus 0
:event/minute 86
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 88
:event/player2 "Antonio Floro Flores"
:event/subtype "trip"
:event/player1 "Nicolas Burdisso"
:event/sortorder 0
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5047543"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_12938"}

{:event/type "card"
:event/elapsed 88
:event/card_type "y"
:event/player1 "Nicolas Burdisso"
:event/sortorder 1
:event/team "home"
:event/event_type "card"
:event/id "event_5047548"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_12938"}

{:event/type "shoton"
:event/elapsed 88
:event/subtype "blocked_shot"
:event/player1 "Antonio Floro Flores"
:event/sortorder 2
:event/team "away"
:event/event_type "shoton"
:event/id "event_5047559"
:event/elapsed_plus 0
:event/minute 88
:event/match_id "match_12938"}

{:event/type "corner"
:event/elapsed 89
:event/subtype "cross_left"
:event/player1 "Matteo Politano"
:event/sortorder 0
:event/team "away"
:event/event_type "corner"
:event/id "event_5047564"
:event/elapsed_plus 0
:event/minute 89
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Blerim Dzemaili"
:event/player1 "Antonio Floro Flores"
:event/sortorder 0
:event/team "away"
:event/event_type "foulcommit"
:event/id "event_5047588"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed 90
:event/player2 "Francesco Acerbi"
:event/player1 "Leonardo Pavoletti"
:event/sortorder 1
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5047590"
:event/elapsed_plus 0
:event/minute 90
:event/match_id "match_12938"}

{:event/type "corner"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross_right"
:event/player1 "Antonio Floro Flores"
:event/sortorder 8
:event/team "away"
:event/event_type "corner"
:event/id "event_5047639"
:event/minute 92
:event/match_id "match_12938"}

{:event/type "cross"
:event/elapsed_plus 2
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Simone Missiroli"
:event/sortorder 10
:event/team "away"
:event/event_type "cross"
:event/id "event_5047646"
:event/minute 92
:event/match_id "match_12938"}

{:event/type "foulcommit"
:event/elapsed_plus 3
:event/elapsed 90
:event/player2 "Simone Missiroli"
:event/player1 "Tomas Rincon"
:event/sortorder 12
:event/team "home"
:event/event_type "foulcommit"
:event/id "event_5047664"
:event/minute 93
:event/match_id "match_12938"}

{:event/type "corner"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "cross_left"
:event/player1 "Matteo Politano"
:event/sortorder 13
:event/team "away"
:event/event_type "corner"
:event/id "event_5047725"
:event/minute 94
:event/match_id "match_12938"}

{:event/type "shoton"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "header"
:event/player1 "Sime Vrsaljko"
:event/sortorder 14
:event/team "away"
:event/event_type "shoton"
:event/id "event_5047734"
:event/minute 94
:event/match_id "match_12938"}

{:event/type "goal"
:event/elapsed_plus 4
:event/elapsed 90
:event/subtype "shot"
:event/player1 "Francesco Acerbi"
:event/sortorder 15
:event/team "away"
:event/id "event_5047671"
:event/event_type "goal"
:event/goal_type "n"
:event/minute 94
:event/match_id "match_12938"}

{:event/type "cross"
:event/elapsed_plus 5
:event/elapsed 90
:event/subtype "cross"
:event/player1 "Issa Cissokho"
:event/sortorder 16
:event/team "home"
:event/event_type "cross"
:event/id "event_5047713"
:event/minute 95
:event/match_id "match_12938"}

{:event/type "goal"
:event/elapsed_plus 5
:event/elapsed 90
:event/player2 "Issa Cissokho"
:event/subtype "header"
:event/player1 "Leonardo Pavoletti"
:event/sortorder 17
:event/team "home"
:event/id "event_5047698"
:event/event_type "goal"
:event/goal_type "n"
:event/minute 95
:event/match_id "match_12938"}


]

