model_name: "facebook/bart-base"

dataset_name: "ADE"
files_path: "data/ADE/"

learning_rate: 5e-5

train_batch_size: 8
valid_batch_size: 16
tests_batch_size: 16

encode_length: 256
decode_length: 128

dataload_workers: 4

gradient_clip_value: 10
gradient_acc_steps:

max_steps: 1000 
precision: 16
amp_level: 